### PR TITLE
Add the mavlink logging output to the ULog file

### PR DESCRIPTION
**Pull request by bkueng**
Once the new logger becomes the default, we can remove the current mavlink log files msgs_*.txt

Another goal will be to add the PX4_{WARN,ERR} to the ULog file and replace all warnx/errx with PX4_{WARN,ERR}. But this will require some more refactoring.

### CODE REVIEW

**Comment by kd0aij** [comment]
@bkueng What are your plans for selecting which topics are logged? Will that be hardwired or configurable? Also, I'm confused by the Subscription<> class; what determines which topics are specified in uorb/Subscription.cpp (it doesn't appear to be auto-generated) and what is it's overall purpose?

**Comment by bkueng** [comment]
Which topics we will log depends on the hardware capacities (SD bandwith) and our needs. We want a) analyze flight behavior (which means to log the same stuff as with the old logger) and b) replay and simulate the whole system or at least parts of it (eg EKF module). This requires the raw sensor input, or EKF input topics.

It sure would be nice to have a configuration file for logged topics, in addition to a hardcoded default set of topics. If you want to tackle this, you are welcome to do it. For now I'll focus on replay.

Subscription<> is just a C++ convenience wrapper. If you want to use it, it must be defined in Subscription.cpp for your topic. This is because it's a template class. Normally you have everything in the header file, which would make the definition in Subscription.cpp unnecessary. But I guess the purpose of doing it this way is to avoid code duplication. But I agree, the list is not nice.

**Comment by kd0aij** [comment]
@bkueng Thanks for the clarification. I guess we lost the todo list that I was keeping a while back. You're moving so quickly with this, and I'm not really "in the loop", but if you'd like to break out some features for me to implement, I'd be glad to contribute. Of course my main interest is supporting analysis of flight behavior with high-rate logging of a specific (small) set of topics.

**Comment by bkueng** [comment]
Well, I'm working full time on PX4 :) 
I have some tasks that you can take:
- as mentioned, config file for logged topics. I imagined something simple like this:
```
add=<topic_name>,<rate>
remove=<topic_name>      <- disable a builtin topic
```
  From there you can go further to make it even configurable via QGC.
- logrotate: delete old log files if there are too many or the SD card space falls below a limit.
- go over the ULog file format spec, and if you have some improvements, add them now, and then we can keep the format fixed.

Feel free to pick one you like, I won't work on any of these in near future. Then also:
- once I have the next PR ready for ORB queuing, help with testing the effect of different queue sizes (in terms of memory, latency, etc).
- Later on we also want LogMuncher to support ULog. This probably means to write a (fast) python parser for ULog. But I haven't thought about this in depth yet.

Yes some TODO list where people can take/put tasks would be nice to have.

**Comment by kd0aij** [comment]
I looked at the old todo list and I think you covered everything that's still relevant except for pulling the new logger into branch nuttx_next_cmake. 

I'll implement the topic selection file feature next, and I think if we can already handle mission state with the current file format it's in good shape. 

There is one more thing though: my hack to UlogReader.main to generate CSV files for input to Octave (Matlab). I'd appreciate your advice on whether there's a better way to do that, and how it might become an export option in the FlightPlot file menu.

**Comment by davids5** [comment]
@kd0aij 
I need to do a merge of master into nuttx_v3 (soon) - so the logger that should get pulled in.
Please consider  nuttx_next_cmake superseded by nuttx_v3

**Comment by kd0aij** [comment]
@davids5 That's great. Let me know when that's done and I'll check to see if logger performance has improved.

**Comment by bkueng** [comment]
@kd0aij for sdlog we had the script `Tools/sdlog2/sdlog2_dump.py`. Maybe if we'll use a python parser for web plotting, we can easily add a CSV exporter. That would require the least amount of effort I guess. I don't know FlightPlot well enough to say how much effort an export would be or how to do it exactly. But we will need a solution for this, we also have people using Matlab here.

**Comment by kd0aij** [comment]
It wouldn't be hard to use my existing code to implement an export function in FlightPlot. Just have to define it as a proper method, and add it to the File menu, but I'm reluctant to spend effort on such things without approval from the maintainers, since they usually know a better way to do things.
As it is, the "exporter" runs fine from the command line.

**Comment by davids5** [comment]
@kd0aij , @bkueng, @dagar 

I am in the throes of a master merge into nuttx_v3 and running out of code space.

Building using arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 227977]

region `flash' overflowed by 11032 bytes

What can I disable?

**Comment by dagar** [comment]
@davids5 We could probably live without logger in px4fmu-v2_default for now.

**Comment by davids5** [comment]
@dagar FYI: @LorenzMeier 

 It worked locally but died on travis under 4.8,4.

`flash' overflowed by 2972 bytes

Any other components I can leave out?

**Comment by dagar** [comment]
Apologies for taking this PR way off topic.

How about blinkm?
drivers/blinkm

Are all of these range finders actively used?

drivers/srf02
drivers/sf0x
drivers/ll40ls
drivers/trone

 Does anyone actually have an lis3mdl yet?

drivers/lis3mdl

How many pixhawks with an mpu9250 are in the wild?

drivers/mpu9250

**Comment by davids5** [comment]
Gentlemen Likewise my apologies - I foolishly thought I was just going merge master into nuttx_3 for @kd0aij to test the logger. 

@dagar Let's take this over here: https://github.com/PX4/Firmware/pull/4625 .

**Comment by davids5** [comment]
> @davids5 That's great. Let me know when that's done and I'll check to see if logger performance has improved.

@kd0aij - https://github.com/PX4/Firmware/pull/4451 is ready 

Please take note of the disabled components due to overflowing FLASH.

I think you will have to test on V4 Hw or futz with the v2 config to get the logger in.

**Comment by kd0aij** [comment]
Thanks David. I'm doing most of my testing on Pixracers anyway, so flash
space shouldn't be a problem.
I noticed today that v2 doesn't have space for the new logger plus LPE, so
we may have to decrease the log buffer size on v2. Last time I checked it
was 24K.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
