### PR TITLE
WIP:Master Pixracer PX4FMUV4

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier 

It is coming alive. I still have more to do.

Console output
```
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
[i] microSD mounted: /fs/microsd
nshterm [6:70]
param: selected parameter default file /fs/mtd_params
[param] Loaded: /fs/mtd_params
 0:   RC_MAP_THROTTLE: match
 1000.0000000:   RC3_MIN: match
 0:   RC_MAP_ROLL: match
 1000.0000000:   RC1_MIN: match
 0:   RC_MAP_PITCH: match
 1000.0000000:   RC2_MIN: match
 0:   RC_MAP_YAW: match
 1000.0000000:   RC4_MIN: match
rgbled: no RGB led on bus #1
blinkm: I2C init failed
blinkm: init failed
 1:   SYS_USE_IO: match
 0:   SYS_AUTOSTART: match
[i] No autostart
nsh: px4io: command not found
nsh: px4io: command not found
nsh: px4io: command not found
[i] ERROR: PX4IO not found
[i] ERROR: PX4IO not found, disabling output
dataman: Unknown restart, data manager file '/fs/microsd/dataman' size is 101504 bytes
MS5611_SPI on SPI bus 1 at 3 (11000 KHz)
adc init done
nsh: mpu6000: command not found
nsh: l3gd20: command not found
hmc5883: no device on bus 2
HMC5883_SPI on SPI bus 1 at 5 (11000 KHz)
meas_airspeed: no MS4525 airspeed sensor connected
ets_airspeed: no ETS airspeed sensor connected
ets_airspeed: no ETS airspeed sensor connected
sensors: FATAL: no accelerometer found: /dev/accel0
sensors: sensor initialization failed
sensors: start failed
commander: No RGB LED found at /dev/rgbled0
telem> PREFLIGHT FAIL: MAG #0 UNCALIBRATED
telem> PREFLIGHT FAIL: NO ACCEL SENSOR #0
telem> PREFLIGHT FAIL: NO GYRO SENSOR #0
telem> PREFLIGHT FAIL: AIRSPEED SENSOR MISSING
mavlink_if0: mode: 0, data rate: 1200 B/s on /dev/ttyS1 @ 57600B
mavlink_if0: offboard mission init: ERROR
sdlog2: log buffer size: 12288 bytes
[i] No autostart ID found

```

The Navigator is stuck saying 

WARN  timed out
WARN  timed out
WARN  timed out
WARN  timed out
WARN  timed out
WARN  timed out
WARN  timed out
WARN  timed out

Build with:

px4fmu-v3_default

Bootloader is on master here https://github.com/PX4/Bootloader

First commit https://github.com/PX4/Firmware/commit/792c2eafafa4b20762edd8538a68ec969c6ae1fd is a temporary fix for not having a pio - nuttx_next_cmake has the real fix,

The next 3 commits should have been on master and could be cherry picked or we can wait until this is merged.

Last commit is the FMUV3 support changes

David

### CODE REVIEW

**Comment by LorenzMeier** [comment]
A few selected comments: I would prefer to call the board fmu-v4 because we have a fmu-v3 with Pixhawk 2, but its binary compatible with fmu-v2. Sorry about the confusion.

Then for the driver startup, extend this:
https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rc.sensors#L14

Using a new fmu-v4 string added here:
https://github.com/PX4/Firmware/blob/afb68cb0abee4034582f93d7f383c287b9c9a109/src/lib/version/version.h#L53

To conditionalize the shell script. Then start the mpu9250, ms5611 and hmc5883 drivers based on the condition. That should fix the resulting errors.

**Comment by davids5** [comment]
@LorenzMeier 

I solved the pwm issue. It was incomplete #ifdefs  
image


Phillip and I worked on rotations. I am still not sure sure if the hmc5893 is rotated correctly. Can you look at the layout and verify/suggest the -R values for https://github.com/PX4/Firmware/commit/1dea512fa95e87fb984b3f776aa7499f46558a1c

What is left:

- [ ] Safety LED/Switch
- [ ] sBus
- [ ] RssI in
- [ ] driver for epos8266

**Comment by LorenzMeier** [comment]
Will look at the rotation value. The suggested other items make sense.

**Comment by LorenzMeier** [comment]
Please ensure to start the mpu6k driver first, then the 9K

**Comment by LorenzMeier** [comment]
@tumbili My last commit also fixes battery voltage indication.

**Comment by LorenzMeier** [comment]
@tumbili The last commit might explain the gain differences. Please re-test with higher gains.

**Comment by LorenzMeier** [comment]
@tumbili I rebased the branch, so make sure to do this locally:
```bash
git branch -D master_xracer
git fetch origin
git checkout origin/master_xracer -b master_xracer
```

**Comment by LorenzMeier** [comment]
Load / timings of HPWORK from master:
```
Processes: 19 total, 3 running, 16 sleeping
CPU usage: 59.73% tasks, 0.55% sched, 39.72% idle
Uptime: 111.892s total, 47.998s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
   0 Idle Task                   47997 39.716     0/    0   0 (  0)  READY 
   1 hpwork                       2437  2.206   704/ 1592 192 (192)  w:sig 
   2 lpwork                        427  0.315   588/ 1592  50 ( 50)  w:sig 
   3 init                         1609  0.000  1236/ 2496 100 (100)  w:sem 
   6 nshterm                         0  0.000   700/ 1496  70 ( 70)  w:sem 
 111 commander_low_prio             29  0.000   732/ 2592  50 ( 50)  READY 
  83 dataman                        23  0.000   660/ 1192  90 ( 90)  w:sem 
  95 sensors                      3204  2.836  1580/ 1992 250 (250)  w:sem 
 101 gps                           197  0.157   708/ 1192 220 (220)  w:sem 
 104 commander                   19820 17.888  3332/ 3496 215 (215)  w:sig 
 107 px4io                        3879  3.546   924/ 1496 240 (240)  w:sem 
 174 top                           143  2.442  1228/ 1696 100 (100)  RUN   
 113 mavlink_if0                   794  0.551  2076/ 2392 100 (100)  READY 
 114 mavlink_rcv_if0                74  0.000  1024/ 2096 175 (175)  w:sem 
 132 sdlog2                        227  0.157  2068/ 2992  70 ( 70)  w:sig 
 152 ekf_att_pos_estimator       26837 25.847  3556/ 4592 235 (235)  w:sem 
 154 fw_att_control               2592  2.442  1084/ 1296 250 (250)  w:sem 
 156 fw_pos_control_l1             527  0.472   784/ 1296 250 (250)  w:sem 
 167 navigator                     976  0.866   948/ 1496 105 (105)  w:sem
```

Load / timings from this branch after FMU driver rate change:

```
Processes: 19 total, 2 running, 17 sleeping
CPU usage: 59.06% tasks, 0.71% sched, 40.24% idle
Uptime: 18.813s total, 11.891s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
   0 Idle Task                   11891 40.235     0/    0   0 (  0)  READY 
   1 hpwork                        258  2.823   772/ 1592 192 (192)  w:sem 
   2 lpwork                         47  0.313   572/ 1592  50 ( 50)  w:sig 
   3 init                         1501  0.000  1236/ 2496 100 (100)  w:sem 
   6 nshterm                         0  0.000   668/ 1496  70 ( 70)  w:sem 
 120 commander_low_prio             25  0.000   740/ 2872  50 ( 50)  w:sem 
  92 dataman                        23  0.000   652/ 1192  90 ( 90)  w:sem 
 109 sensors                       283  2.901  1644/ 1992 250 (250)  w:sem 
 111 gps                            15  0.156   700/ 1192 220 (220)  w:sem 
 113 commander                    1486 17.882  3284/ 3592 215 (215)  w:sig 
 116 px4io                         301  3.450   964/ 1496 240 (240)  w:sem 
 123 mavlink_if0                    55  0.627  2076/ 2392 100 (100)  w:sig 
 125 mavlink_rcv_if0                 6  0.000  1060/ 2096 175 (175)  w:sem 
 144 sdlog2                         18  0.156  2068/ 2992  70 ( 70)  w:sig 
 167 ekf_att_pos_estimator        1646 24.627  3516/ 4592 235 (235)  w:sem 
 169 fw_att_control                159  2.431   900/ 1296 250 (250)  w:sem 
 171 fw_pos_control_l1              60  0.392   964/ 1296 250 (250)  w:sem 
 178 navigator                      65  0.705   868/ 1496 105 (105)  w:sem 
 185 top                            99  2.588  1204/ 1696 100 (100)  RUN 
```

**Comment by LorenzMeier** [comment]
This is in. Now we just need to validate CAN.

**Pull request merged**
