### PR TITLE
Add support for ModalAI FC1 target

### PR DESCRIPTION
**Pull request by modaltb**
**Describe problem solved by this pull request**
This PR is to add support for the ModalAI Flight Core 1 board.  This has some commonality with the v5x hardware but is a derivative with designs to mate with the VOXL companion computer.  The fmu_v5x board support was used as the starting point.

The bootloader update for this board has a PR here:
   https://github.com/PX4/Bootloader/pull/155

**Describe your solution**
NA

**Describe possible alternatives**
NA

**Test data / coverage**
Flight testing has been ongoing for the last months with positive results.  Please push back and let me know if more is needed! :)

**Additional context**
I can ship hardware to anyone if needed for testing, just let me know!

### CODE REVIEW

**Comment by dagar** [comment]
Can you add the build to Jenkins? https://github.com/PX4/Firmware/blob/cefa7ec5dc55ea03c0518670c3622043a535676c/.ci/Jenkinsfile-compile#L38

**Comment by modaltb** [comment]
Not sure if the Jenkins job picked up the change with the added target, it's not appearing in the "Compile All Boards" step.  I can re-submit a PR if needed to 'flush' the change if that's needed.

**Comment by hamishwillee** [comment]
When you're in production you might want to document the board. Typically that is done in 2 places:
- board docs: https://docs.px4.io/master/en/flight_controller/
- quick start: https://docs.px4.io/master/en/assembly/quick_start_cuav_v5_plus.html

**Comment by modaltb** [comment]
@hamishwillee thanks for the heads up, I created a task on our end to get this in place before production release.

**Pull request merged**
