### PR TITLE
Drivers: Add TeraRanger Evo 600Hz support

### PR DESCRIPTION
**Pull request by msadowski**
Hi!

We are soon launching a new TeraRanger Evo sensor (Evo 600Hz) and we thought it is a good idea to create a new option for SENS_EN_TRANGER that will correctly represent the minimum and maximum distance of this new sensor.

We also renamed the previous option to TREvo60m (previously just Evo).

If there is anything else you wold like us to update please don't hesitate to ask and someone from our team will work on it.

### CODE REVIEW

**Comment by ndepal** [comment]
Nice!

The new Evo has the same I2C address as the existing one, correct? This breaks the auto-detection of which TeraRanger is connected.

We should either remove the auto-detection or document that it will always assume the 60m Evo.

**Comment by msadowski** [comment]
@ndepal that's correct, the addresses and whoami's will be the same for all sensors in Evo family.

How important are the minimum and maximum ranges from the flight control perspective? We were hoping that for users that are likely to test multiple sensors we could leave autodetection that provides minimum and maximum distances across the whole Evo family of sensors (e.g. 0.1-60m).  I'm more than happy to document this functionality if that's something we want.

**Comment by hamishwillee** [comment]
It would be great if we could update the docs: https://docs.px4.io/en/sensor/rangefinders.html#teraranger-one

Also excellent if the driver could get some in-source docs that can are generated [here](https://dev.px4.io/en/middleware/modules_driver.html) - you can see how this is done in the [Module Template](https://github.com/PX4/Firmware/blob/master/src/templates/module/module.cpp) and in the GPS driver here:
https://github.com/PX4/Firmware/blob/03b8cd78b3e32be581f5e9ecf22358da03b3fe91/src/drivers/gps/gps.cpp#L943

**Comment by dagar** [comment]
@msadowski auto-detection sounds interesting. Were you thinking an additional parameter to enable it?

**Comment by dagar** [comment]
Base driver changes look good. We can do another PR to if for module documentation.

**Comment by msadowski** [comment]
@dagar Thanks for the merge! I don't know if understood your comment on auto-detection. What kind of parameter do you have in mind? There is already an Autodetect parameter in SENS_EN_TRANGER.

**Comment by dagar** [comment]
Ah, I didn't see the existing autodetection option.

**Pull request merged**
