### PR TITLE
commander: Improve calibration routines for mag

### PR DESCRIPTION
**Pull request by LorenzMeier**
@DonLakeFlyer This ensures that the user rotates but at the same time applies slightly more comfortable requirements for the orientation detection. So more convenience and more rigor at the same time, yay!

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I've already fixed this in a pull I"m working on which includes a ton of other improvements as well. I'd rather take that full pull when it's ready than this one so it doesn't cause merge conflicts.

**Comment by LorenzMeier** [comment]
I had looked for a WIP but must have missed it, wouldn't have started else, sorry. Makes sense. I still recommend to take this piece (which is essentially standalone) to ensure the user is actually rotating.

We have had users turn the system into the 3 positions like for the accel, which is a degenerate case. Since there was no check the system and QGC accepted it. This check is pretty soft.
https://github.com/PX4/Firmware/blob/magcalfix/src/modules/commander/mag_calibration.cpp#L190-L240

I also found that shortening the detection times makes both mag and accel easier to use. I've added them as parameter and set them to 1.5 s for accel and 1 s for mag.

**Comment by DonLakeFlyer** [comment]
Haven't pushed any WIP yet. Leave this pull here until I finish mine so I can copy some stuff from it.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer What about the rotation check - should we phase that one in now?

**Comment by DonLakeFlyer** [comment]
It's on my todo list.

**Comment by LorenzMeier** [comment]
The rotation detection is now on master in 29eeb72. Tested with QGC master. Closing.

**Pull request closed without merging**
