### PR TITLE
estimataor reset counter: set Flighttask-counter equal reset-counter 

### PR DESCRIPTION
**Pull request by Stifael**
issue #10033

### CODE REVIEW

**Comment by Stifael** [comment]
@dagar, it fails again because of `auav-x21`

**Comment by dagar** [comment]
Looks like a build slave failure, let's try again.

**Comment by LorenzMeier** [comment]
@dpettenuzzo Could you test with that?

**Comment by DanielePettenuzzo** [comment]
@LorenzMeier I will fly it later today.

**Comment by DanielePettenuzzo** [comment]
@Stifael @LorenzMeier  I just did 5 takeoffs of position mode and I never saw the yaw issue. Will upload logs later today.

**Comment by DanielePettenuzzo** [comment]
@Stifael Here are two logs from yesterday's flights
Log 1: https://review.px4.io/plot_app?log=3332870c-1775-469c-b450-2c81ca166467
Log 2: https://review.px4.io/plot_app?log=3e4701ff-a372-4174-9da0-6d325f90db5f

**Pull request merged**
