### PR TITLE
Navigator: Do not update a position setpoint for mission items not en…

### PR DESCRIPTION
**Pull request by LorenzMeier**
…coding positions. Fix for #3581 - or at least a step towards it.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@AndreasAntener @tumbili I think you need to do this or more to fix the zero altitude you got. It should at least point you into the right direction.

**Comment by LorenzMeier** [comment]
@julianoes Please don't comment on commits, but on the diff here. Its non-consumable. This patch set is not complete. Its just a first step.

**Comment by LorenzMeier** [comment]
What I fixed is the lower-level routine not having any boundary checks. The *real* fix is to ensure it never gets called on a non-position setpoint!

**Comment by LorenzMeier** [comment]
@tumbili @AndreasAntener @julianoes The real fix needs to be applied here: Instead of returning a mission item, this routine needs to return the next action and the next 3D position:
https://github.com/PX4/Firmware/blob/6eac78d67529e20c3170092fd271c11c57c70f2f/src/modules/navigator/mission.cpp#L658-L759

Then the action needs to be handled and the next 3D position is fed into the right mission logic. With that change we always have a next 3D position, no changes to the main waypoint code are required and we just need to slightly change the way commands are published.

The two PRs I submitted could potentially be left out as well. Please make sure you understand the implications before you continue on this.

**Comment by AndreasAntener** [comment]
replaced by #3598

**Pull request closed without merging**
