### PR TITLE
update docker containers (NuttX upgrade and ccache everywhere)

### PR DESCRIPTION
**Pull request by dagar**
- enables ccache for raspi, ocpoc, snapdragon
 - update NuttX to GNU Arm Embedded Toolchain: 7-2017-q4-major December 18, 2017

### CODE REVIEW

**Comment by dagar** [comment]
This PR is good to go once we validate the new NuttX compiler version.

**Comment by dagar** [comment]
Split into separate PRs.
https://github.com/PX4/Firmware/pull/8549

**Comment by hamishwillee** [comment]
@dagar I see an awful lot of changes that specify a particular docker version "px4io/px4-dev-base:2017-12-30". Perhaps a stupid question, but should this be passed in somehow so that you don't need to change the value every time there is an update?

**Comment by dagar** [comment]
The duplication should be minimized (functions in Jenkins), but the specific tag in version control is intentional. This way if you jump between master or an older branch both CI and local docker builds (./Tools/docker_run.sh) have the correct dev environment.

**Pull request closed without merging**
