### PR TITLE
Fix vulnerability in pre flight checks and failsafe

### PR DESCRIPTION
**Pull request by priseborough**
The preflight checking of ekf2 health status as currently implemented in the commander has a two main vulnerabilities:

If GPS arming checks had been disabled via the COM_ARM_WO_GPS parameter, then this was also bypassing the ekf2 health checks.
The ekf2Check() function in the commander is only called once per mode change or arming request which means that the status is a snapshot of the EKF output and does not handle transient errors or noise well.
This PR improves the continuous ekf2 pre-arm checks and publishes the result as a boolean on the estimator_status message, which is then checked by the ekf2Check() function in the commander.
It also removes the bypass of ekf2Check()

Preflight checking changes:

- Separate the vertical and horizontal checks for use by local position validity reporting
- Add checking of yaw using a decaying envelope filter to the horizontal checks.
- Publish the check result to estimator_status topic.

Log from testing of preflight checks here: https://logs.px4.io/plot_app?log=1bc435b7-86e3-4c73-82a5-a98c77949a3d. A magnet was used to cause large changes in magnetic yaw and fail preflight checks whilst attempting to arm.

screen shot 2017-11-27 at 1 29 43 pm

If a RW vehicle takeoff off with a large yaw error, the EKF will start to reject the GPS data due to the inconsistency with the  INS solution. This combined with the position controller can cause an uncontrolled high speed flight condition. When this occurs, the EKF reports the navigation output as invalid, however after reset back to GPS, the navigation solution will be reported as valid again for a varying interval. This causes an interaction with the commander failsafe resulting in unpredictable transitions in and out of the failsafe mode. The solution implemented by https://github.com/PX4/Firmware/commit/39134325740a193fd755763e52faffe030073e5f

- Checks for loss of navigation for up to 30 seconds after takeoff or until  a horizontal speed of 5 m/s has been achieved.
- If the vehicle is not landed and the check is active, then the navigation is declared as failed if the velocity innovations fail for a continuous period of 1 second.
- This will cause the local and global position and velocity validity to be latched false to prevent unsafe use of position control modes.
- An emergency message 'CRITICAL NAVIGATION FAILURE - CHECK SENSOR CALIBRATION' is output to console and mavlink if the failsafe is activated.

Test log generated using SITL with  90 degree misaligned compass data here: https://logs.px4.io/plot_app?log=6aa3a650-a65a-499a-a4ed-9ab287e9e764

### CODE REVIEW

**Comment by priseborough** [comment]
I'll squash the ekf2  commits

**Comment by priseborough** [comment]
Added https://github.com/PX4/Firmware/pull/8374/commits/71eaba761a8ff21685bf661bbc7caa703d78b184 to fix https://github.com/PX4/Firmware/issues/8269

**Comment by priseborough** [comment]
Log from test of GPS pre flight checking here: https://logs.px4.io/plot_app?log=c2cbc696-5036-4056-a26f-87a79619df13

**Comment by priseborough** [comment]
The CI SITL hysteresis test is failing. Will investigate.

**Comment by priseborough** [comment]
Here is log from a test of the last patch which strengthens RW vehicle protection against flyaways caused by large yaw errors. https://github.com/PX4/Firmware/pull/8374/commits/39134325740a193fd755763e52faffe030073e5f

The compass data was rotated by 90 deg to start a flyaway. The failsafe was entered on position control mode and the vehicle automatically transitioned into altitude control mode.

https://logs.px4.io/plot_app?log=37cd9843-e483-49b3-a6c4-d15865668452

**Comment by priseborough** [comment]
I've added patch that clears the failed status when the vehicle enters a normal standby state. This makes flight testing the failsafe possible using multiple takeoffs.

**Comment by priseborough** [comment]
This PR addresses critical vulnerability in the failsafe behaviour following a RW takeoff with bad yaw estimate that currently causes an uncontrollable flyaway in position controlled modes.

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by bkueng** [comment]
@priseborough I'm getting sporadic preflight check failures when bench-testing master and trying to arm:
`PREFLIGHT FAIL: EKF INTERNAL CHECKS`
In about 1 out of 10 times it happens without necessarily me moving the vehicle.
Here's a log: https://logs.px4.io/plot_app?log=373eb52c-ec0b-4a87-9b25-809a0dd53c4f

**Comment by priseborough** [comment]
@bkueng In the log you provided, the failure was caused by a large magnetic yaw inconsistency generated by previous movement of the vehicle and possible magnetic anomaly in the indoor environment. The following plot shows the magnetic yaw innovation in radians.

screen shot 2017-12-07 at 9 27 11 am

It is still recovering back to zero and is just above the max allowed value of 0.25 rad when attempting to arm at 155 sec.

The baro is very noisy on this board, but is below the check limits of 3.0m peak and 1.5m filtered.

**Comment by priseborough** [comment]
@bkueng I can make the check more permissive, by relaxing the yaw requirement if is is not using GPS. This will help with indoor testing without GPS.

**Comment by priseborough** [comment]
I've flight tested this on a small 250 quad and also checked the sensitivity using a nearby magnet indoors.

**Comment by bkueng** [comment]
Thank you, I'll take a look.

**Pull request merged**
