### PR TITLE
update ecl geo_lookup usage

### PR DESCRIPTION
**Pull request by dagar**
~~Waiting on https://github.com/PX4/ecl/pull/851.~~

### CODE REVIEW

**Comment by MaEtUgR** [comment]
I rebased on master to get this in since it came up in an estimation discussion.

**Comment by MaEtUgR** [comment]
It doesn't fit v2 by 845 bytes: https://github.com/PX4/Firmware/pull/15207/checks?check_run_id=917970228

**Comment by dagar** [comment]
> I rebased on master to get this in since it came up in an estimation discussion.

Thanks, I was actually neglecting it because it's mixed with a month of ecl/EKF changes, but it's good to know I need to fight for some flash first.

**Comment by priseborough** [comment]
I am currently including this patch when doing ecl dev work. When https://github.com/PX4/ecl/pull/870 is merged it should help with the flash space issue

**Comment by dagar** [comment]
> I am currently including this patch when doing ecl dev work. When [PX4/ecl#870](https://github.com/PX4/ecl/pull/870) is merged it should help with the flash space issue

Thanks Paul. If needed immediately before sympy we'll have just enough flash to squeeze this in shortly. https://github.com/PX4/Firmware/pull/15445

**Comment by MaEtUgR** [comment]
I switched to the latest ecl version with the SymPy covariance https://github.com/PX4/ecl/pull/870 already merged. Let's see if that all fits.

**Comment by dagar** [comment]
Thanks everyone.

**Pull request merged**
