### PR TITLE
Fix navigator poll

### PR DESCRIPTION
**Pull request by julianoes**
We don't need to poll for vehicle commands, we will get them anyway by
doing orb_check. Also, the polling for them wasn't implemented correctly
anyway.

It didn't explode on my bench but let's wait for jenkins to fly this.

Adresses #5146.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Changing this increases the latency for command handling, which means that the navigator will drop commands if they occur in close sequence. I don't think we can remove the poll here.

**Comment by julianoes** [comment]
That means we should add queuing to the vehicle commands.

**Comment by julianoes** [comment]
Rebased on master. @LorenzMeier let's check CI, but I think this can go in because vehicle_commands are now queued, so no need to poll for them.

**Comment by julianoes** [comment]
@LorenzMeier please review and merge.

**Comment by julianoes** [comment]
@bkueng please review and merge.

**Comment by bkueng** [comment]
Will do. Review swap https://github.com/PX4/DriverFramework/pull/156 ?

**Comment by bkueng** [comment]
rebased & applied, assuming we don't get more than 3 commands in 200ms

**Comment by julianoes** [comment]
Cheers!

**Pull request closed without merging**
