### PR TITLE
add a new rotation to lib/conversion

### PR DESCRIPTION
**Pull request by kd0aij**

### CODE REVIEW

**Comment by kd0aij** [comment]
Question: will calibration work correctly in QGC if the board rotation has values 26 or 27?

**Comment by kd0aij** [comment]
Surprise! reversing the elevon PWM channels and using @tumbili 's Caipi_vtol mixer gives me correct elevator deflection, but reversed ailerons.
In his mixer, elevon 1 is aileron+elevator, elevon 2 is aileron-elevator
In my mixer, elevon 1 is -aileron+elevator, elevon 2 is -aileron-elevator
Looks like reversing both channels **and** swapping 1/2 should do the trick, but that results in correct ailerons and reversed elevator. This doesn't make any sense to me; my arithmetic must be wrong.

But in looking at my mixer, I see that I've also reduced the throw of both elevon servos to 85%
It doesn't seem possible to accomplish this with the current reversing parameter (integer only?).

So it looks like I still need all the changes that were in #2238 to get my Caipi flying again. I suppose there's no point in putting my mixer in master, since it can live on the SD card, but I can't see any way around having a different autostart ID, and that would imply there's a default mixer to go with it...

**Comment by tumbili** [comment]
@kd0aij You mean the level calibration?

**Comment by kd0aij** [comment]
@tumbili I meant all senso cals which ask for board rotation; QGC only lists rotations 1-25

**Comment by DonLakeFlyer** [comment]
When new rotations are added to the firmware someone needs to ping me to update QGC. I'll add the missing ones in.

**Comment by kd0aij** [comment]
Thanks Don, hopefully this will be merged soon, and there will be 2 new rotations to add to QGC

**Comment by DonLakeFlyer** [comment]
If this one is going in as well I'll add it now.

**Comment by DonLakeFlyer** [comment]
Pull for QGC is in. If this doesn't end up getting through for some reason let me know since I'll have to remove it.

**Comment by LorenzMeier** [comment]
@kd0aij Sounds like we should set up a voice call to discuss your setup issue. It shouldn't be rocket-science. Here is how you can load a custom mixer from SD:
https://pixhawk.org/dev/system_startup#output_mixers

**Comment by LorenzMeier** [comment]
Note that if you have the two servos swapped you can get one axis right and one wrong. Make sure the two elevon servos are *not* swapped. Also on the reduction of throws: You could do that with linkage levers. So fundamentally I don't think you need a different setup, you just need to get it right.

**Comment by kd0aij** [comment]
@LorenzMeier Thanks, I was looking at the mixer documentation instead of startup. Hadn't found the config.txt file for setting things at the top of rcS. That's all I need for using my custom mixer, but while one might get be able to get by without the ability to set custom endpoints and offsets, it's a shame to obstruct access to them. Also, my Caipi has had 2 extra servos for the canards...

**Comment by kd0aij** [comment]
@tumbili @LorenzMeier BTW, there is no mention in the startup documentation of the connection between mixer filename and MAV_TYPE. This was one cause of problems and lost time with my Caipi setup, since my use of a custom mixer resulted in MAV_TYPE being (silently) set to the wrong value.

**Comment by kd0aij** [comment]
@tumbili @LorenzMeier Looking at my custom Caipi_vtol mixer, I see that the change I made was to flip the sign of the roll input (relative to the default). This is obviously not the same as reversing one or both servos and it explains why the new servo reversing parameters didn't eliminate the need for a custom mixer. Is there some other configuration difference which would explain why my roll axis has sign opposite to yours?

**Comment by LorenzMeier** [comment]
Servo swapping? Linkage on the other side of the wing?

**Comment by kd0aij** [comment]
swapping can't do it. And my servos are installed normally.

**Pull request merged**
