### PR TITLE
ms5611: cope with early Pixracer prototypes

### PR DESCRIPTION
**Pull request by tridge**
ms5611 was on sensors bus in earlier prototypes

### CODE REVIEW

**Comment by kd0aij** [comment]
What's the reason for giving the MS5611 a different device name in this case?

**Comment by LorenzMeier** [comment]
Should we maybe phase these early prototypes out instead? They also have no support for FRAM.

**Comment by pkocmoud** [comment]
There were not many of these in the wild, so let's not confuse people. Please phase them out.

**Comment by LorenzMeier** [comment]
I think that makes more sense, closing.

**Pull request closed without merging**
