### PR TITLE
Fix Ubuntu Script for 20.04

### PR DESCRIPTION
**Pull request by MaEtUgR**
**Describe problem solved by this pull request**
I set up a new Ubuntu 20.04 VM and ran into a bunch of issues. I made some changes to the setup script to avoid all of them.

**Describe your solution**
The commit messages clearly describe the steps.

**Test data / coverage**
I retested the changes after resetting the VM to a snapshot just after installation.

**Additional context**
The additional python package requirement for matplotlib with an exact old version added in https://github.com/PX4/Firmware/pull/15203 was the main reason the script failed on 20.04.

### CODE REVIEW

**Comment by hamishwillee** [comment]
FWIW (since I can't merge) looks good to me.

**Comment by dagar** [comment]
Looks good. I still want to get this into the containers to keep everything synced nicely. https://github.com/PX4/containers/pull/267

**Comment by julianoes** [comment]
This creates a warning for me: `sudo: dmidecode: command not found`

**Comment by MaEtUgR** [comment]
> This creates a warning for me: sudo: dmidecode: command not found

@julianoes In docker? With normal Ubuntu 20.04 desktop it's preinstalled. Maybe I need to add it for minimal/docker cases.

**Comment by MaEtUgR** [comment]
@julianoes I added the package now before I forget: https://github.com/PX4/Firmware/pull/15388

**Pull request merged**
