### PR TITLE
Position hold for offboard mode also

### PR DESCRIPTION
**Pull request by v01d**
As mentioned in #3004

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@AndreasAntener This change could make your flight performance a lot better because velocity commands are obeyed, but you need to test for integration ripples. How soon could you test this?

**Comment by AndreasAntener** [comment]
We're using position control so basically the more concerning change for us already went in (#3004) ;) But as far as I can see the behaviour in position control didn't actually change, just the way we get to the velocity error, correct?
Of course we need to follow up with master integration anyway at some point, I'll see when we can make some time for that. But we'll do position control tests then, I currently don't have a velocity offboard app.

**Comment by AndreasAntener** [comment]
@v01d about the `hold_max_*` parameters: I see the use-case for those in manual. But in offboard it's a machine behind the input and it can probably send a zero velocity setpoint if it really want's to. Am I missing something?

**Comment by v01d** [comment]
I thought the same at first but when using offboard mode I realized it
isn't that simple. If you really want to keep altitude, sending VZ=0 does
not guarantee that and you can get drift. If you want to control the drone
in the XY plane by velocity from code (same as when in manual), you
probably want to know Z is kept constant.
In some offboard codes you might be able to close the position loop for XY
and Z, but in other cases you might just want to act on XY.

In any case, the defaults are for pure velocity control with no hold
(parameters set to zero) to avoid any surprises. You can consider it an
extra feature which comes in handy for some cases.

**Comment by LorenzMeier** [comment]
@v01d You are still locked in your position or velocity train of thought. Try to give up on that. Consider the system being a physical object and you set its acceleration, velocity and position. These three need to be in sync obviously, but they *do* allow you to set a no-drift position and velocity setpoint.

**Comment by LorenzMeier** [comment]
What you need is obviously the time horizon. We might need to add that to the interface.

**Comment by v01d** [comment]
Could you explain more why? I'm not sure I understand the idea about the
time horizon completely.

**Comment by LorenzMeier** [comment]
You can only control the trajectory if you factor in time. Else you have no relationship between velocity and position. You implicitly assume that you let some parts run open-loop, which is wrong if you try to follow a trajectory, which is 4D (position and time).

**Comment by v01d** [comment]
OK, I understand that. The problem I see, IMHO, is that PID control has its
limitations and the position PID is sometimes difficult to get correctly
tuned (maybe it works well on hover, but not smoothly following setpoints,
and viceversa). Furthermore, with the "carrot based" approach, one
difficulty was to tune the velocity PID at the same time the position PID
was working (therefore, velocity setpoint was not fixed).
In your case you would also have several PID controllers running even when
the user wants to control velocity directly?

In this PR, under velocity mode, you are essentially using the position
controller only near hover state. If you have position + velocity +
acceleration simultaneously, would you not require tuning two (or three)
controllers simultaneously to achieve nice control?

Regarding your second comment (trajectory following), I agree with that.
However, IMHO, it would be nice to leave the door open for easier direct
velocity control with no position controller running on the FCU. Maybe some
user wants to try a different position controller on the companion
computer, which sends velocity commands to the FCU.

**Comment by mzahana** [comment]
Hi all,

I am trying to control a quad by using offboard mode and sending only XYZ,yaw setpoints, not velocities/acceleration (assuming the position controller rely on some max vertical/horizontal velocity parameters). I am currently able to test altitude hold and position control modes (relying on mocap data), and now want to move to offboard mode.

So, it seems that you guys have been putting a good amount of effort on this issue, but I am not able to follow up with  all the changes/update. So, my question is: is the current position controller able to handle position setpoints (ignoring velocities/acceleration) being sent in offboard mode?

I mean, can I just use mask bits to send local NED XYZ & yaw only?
Has this scenario been tested already?

Thanks

**Comment by v01d** [comment]
@mzahana we are discussing changes to master branch here. If you use stable, you can try offboard mode is stated in the documentation. Please direct your questions to the mailing list if you have problems with it.

**Comment by mzahana** [comment]
Thanks! Where can I get the stable version that supports mocap and offboard mode?

**Comment by LorenzMeier** [comment]
It doesn't exist. If you want new stuff you need a new version.

**Comment by julianoes** [comment]
What's the state of this PR? Is this still better and needed?

**Comment by LorenzMeier** [comment]
We did this since in a similar fashion.

**Pull request closed without merging**
