### PR TITLE
mavlink: implement MAV_CMD_REQUEST_FLIGHT_INFORMATION

### PR DESCRIPTION
**Pull request by sugnanprabhu**
Adding support for MAV_CMD_REQUEST_FLIGHT_INFORMATION to get flight information.

#7706

### CODE REVIEW

**Comment by TSC21** [comment]
Is this tested?

**Comment by TSC21** [comment]
Also please check style/format so it passes on CI

**Comment by sugnanprabhu** [comment]
@TSC21 
Yes the changes are tested on intel aero, logs for new changes (armed_time_ms) can be found in the following file.
[00000-2017-08-08_00-31-28_actuator_armed_0.csv](https://github.com/PX4/Firmware/files/1265976/00000-2017-08-08_00-31-28_actuator_armed_0.csv.txt)

**Comment by LorenzMeier** [comment]
Thanks!

**Pull request merged**
