### PR TITLE
[WIP] temperature calibration

### PR DESCRIPTION
**Pull request by LorenzMeier**
@dagar I pushed a commit fixing logging here. I can test tomorrow morning.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Note that for valid results you *HAVE TO* recalibrate using this branch! You will not have valid temperature coefficients else.

**Comment by LorenzMeier** [comment]
@dagar Log file comes out ok, but the data doesn't look good yet. The gyro data is pretty wrong (off by a factor of 1 mn and zero most of the time).

**Comment by LorenzMeier** [comment]
@dagar Any motivation / time to look into this over the weekend?

**Comment by dagar** [comment]
Sorry just moved. I'll start working on this next week once things are back to normal.

**Comment by dagar** [comment]
The logging is working now, but the onboard compensated value is busted. I'll compare the current state of this PR to the original PR #1943 to see if something was missed during the rebase.

plot

**Comment by dagar** [comment]
@LorenzMeier I still need to cleanup and think through the desired workflow, but this is now working rebased on master and ready for more testing.

untitled

**Comment by LorenzMeier** [comment]
Fantastic! My main goal would be now to ensure we can merge this with safe defaults.

@priseborough @bugobliterator You will likely be interested as this allows much tighter Kalman variances since a lot of the uncertainty about the offset is gone.

**Comment by dagar** [comment]
This is likely nearly safe to merge, but probably sufficiently awkward to use it will be ignored and then we won't get testing.

Current limitations
-calibration requires matlab and then hard coding coefficients
-only supports accel0 and gyro0 and must be mpu6000
-mag not implemented

For next steps I was thinking about pulling all the offline calibration work into a python script that updates the temp calibration params over mavlink. Thoughts?

**Comment by dagar** [comment]
Putting this on hold for now unless there's more interest. In my personal usage I've found the temperature of my pixhawk stabilizes fairly quickly in an enclosed avionics bay.

**Comment by dagar** [comment]
TODO:
 - [ ] verify accel
 - [ ] add param to use mpu6000 tc values in sensors

**Comment by LorenzMeier** [comment]
@dagar Can you provide an update where this is standing? If needed I can probably assign a person to push this forward.

**Comment by dagar** [comment]
@LorenzMeier the main reason this stalled is my matlab license expired. 

Things outstanding
- accel testing/validation (I was mostly looking at gyro)
- cleanup sensor 0 assumptions
  - there are a few stupid sensor == 0 checks that should be handled more intelligently.
https://github.com/PX4/Firmware/pull/3390/files#diff-cb5386494d2ac00baa53ed805c1b9e9dR1558
- how to handle actually using the corrected values
 - currently it's a param SENS_TEMP_COMP, but later we could do away with the duplication
- test actually using the corrected values in the estimators and decide if we want to keep and log both the original and tc

If you want to get this going again I can resolve the current conflicts and get a good log from -10C to ~50C this weekend. If someone could jump in and review the data and calculated corrections (matlab), I'll try testing actually using the corrected values, perhaps even in flight if it goes well.

Longer term how do you want to handle updating the values that are currently hard coded and inserted during regular calibration?

**Comment by LorenzMeier** [comment]
Jenkins test this please

**Comment by LorenzMeier** [comment]
@dagar Do you see an easy path to replace our Matlab scripts with Octave? (https://www.gnu.org/software/octave/) That should work. Or go straight to Python?

**Comment by dagar** [comment]
Octave doesn't have tdfread. - https://github.com/PX4/Firmware/pull/3390/files#diff-05363778d4ba69c616097164113ff11fR13

**Comment by LorenzMeier** [comment]
@priseborough @bugobliterator This is a good starting point. What we need to do is to refactor it a bit to match this concept:

ideas - 20

The only open question is if we make an `ACCEL_OFFSET`(0,1,2) topic or a `SENSOR_CALIBRATION` topic with everything and an array of sensor ID -> data.

**Comment by LorenzMeier** [comment]
@dagar Making a real push now to implement this. Please let us know if you have bandwidth or at least comments.

**Comment by bkueng** [comment]
@LorenzMeier looks good. I'm just wondering whether applying the offsets directly within sensor hub makes sense. But then any other module using a sensor directly would not have the offsets.

**Comment by LorenzMeier** [comment]
Yep, that was the thinking. It would be good to have a data path that is super low-latency straight from the sensor.

**Comment by priseborough** [comment]
A few design requirements for the sensor hub:

1) Latency sensitive consumers should have the option of taking raw data directly from the sensor and applying the offsets and scale factors using calibration corrections from the sensor hub.
2) Bias estimates published by the sensor hub will be a sum of the  the a-priori temperature dependant calibration data and the EKF bias estimate.
3) Topics containing sensor data should make a clear distinction between whether data is corrected or uncorrected.
4) The EKF can use data that is corrected for temperature effects, but the data it receives must not be corrected dynamically using the EKF bias estimates, other wise we effectively double the Kalman gains for the bias states in addition to the corrections being delayed due to the EKF delayed fusion time horizon.
5) EKF bias estimates may be used to update the calibration tables for the next switch-on.
6) It should to be backwards compatible with the exisiting offset and scale factor parameters and work with the exisiting sensor calibration workflow
7) An on-board calibration mode is preferable to one that requires external tools

I don't have the C++ skills to do the refactoring from scratch , so what is the availability of @bugobliterator and @dagar  to help with that part of the work?

The other aspect is the calibration workflow including logging and any tools required.

**Comment by bugobliterator** [comment]
@priseborough @LorenzMeier I won’t be available from 15th to 25th, other than that I am available to give time to this.

On Fri, 09 Dec 2016 at 6:19 PM Paul Riseborough

<
mailto:Paul Riseborough <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

A few design requirements for the sensor hub:

Latency sensitive consumers should have the option of taking raw data directly from the sensor and applying the offsets and scale factors using calibration corrections from the sensor hub.

Bias estimates published by the sensor hub will be a sum of the the a-priori temperature dependant calibration data and the EKF bias estimate.

Topics containing sensor data should make a clear distinction between whether data is corrected or uncorrected.

The EKF can use data that is corrected for temperature effects, but the data it receives must not be corrected dynamically using the EKF bias estimates, other wise we effectively double the Kalman gains for the bias states in addition to the corrections being delayed due to the EKF delayed fusion time horizon.

EKF bias estimates may be used to update the calibration tables for the next switch-on.

It should to be backwards compatible with the exisiting offset and scale factor parameters and work with the exisiting sensor calibration workflow

An on-board calibration mode is preferable to one that requires external tools

I don't have the C++ skills to do the refactoring from scratch , so what is the availability of
https://github.com/bugobliterator
and
https://github.com/dagar
to help with that part of the work?

The other aspect is the calibration workflow including logging and any tools required.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/PX4/Firmware/pull/3390#issuecomment-266006014
, or

**Comment by priseborough** [comment]
Here is a way that this could be put together faster than a complete re-factor, and something that I would be start now as it doesn't require creating new modules and/or classes. I would however require some help with the data storage and retrieval.

Phase 1 - minimum work required to get it working:

1) Create a uORB topic called sensor_corrections which contains the offsets  to be applied to each sensor
2) Create a uORB topic called estimated_imu_bias for the IMU sensor bias estimates calculated by the nav estimator.
3) Update estimators to publish to estimated_imu_bias.
4) Add the calculation of temperature dependant sensor offsets to sensors.cpp. Assistance with the data storage and retrieval concept is required here.
5) Update sensors.cpp to apply corrections to all data published on the sensors_combined topic. For angular rate and accel data, this will also include corrections calculated using data from estimated_imu_bias. For delta angle and delta velocity data it will NOT use any data from estimated_imu_bias.
5) Update sensors.cpp to publish to sensor_corrections.
7) Update documentation for all uORB topics containing sensor data making it clear what corrections are included and what are not.

Phase 2 - refactoring of controllers to reduce latency (@MaEtUgR for info)

8) Remove angular rates from the control_state topic
9) Update all consumers of control_state angular rates to take the rates from the sensor_gyro topic and correct using data from sensor_corrections if latency critical, or optionally from sensors_combined if not latency critical. 
10) Modify latency critical consumers of gyro rate data mc_att_control and fw_att control, to wake on sensor_gyro and not control_state.

**Comment by priseborough** [comment]
I've started a Google Document here: https://docs.google.com/document/d/1GHzjsPTfSUAxYGPNlXSL7FYkxFcq76jTfsaquc57Rww/edit?usp=sharing

**Comment by LorenzMeier** [comment]
@priseborough Yes, we should indeed do the temp calibration / compensation automatically onboard once we detect the board being stationary and a full ramp (and maybe some command from the GCS, need to see about that).

**Comment by LorenzMeier** [comment]
And I forgot to respond to the phases proposal: I would indeed perform it in two phases.

**Comment by dagar** [comment]
Busy right now, but I can make time for this over Christmas if no one else is available. I definitely don't want this left to bitrot again.

I need to review the design and existing sensor pipeline usage, but one thought for handling it within sensors is to avoid having to add support in every single driver.

**Comment by LorenzMeier** [comment]
I'm closing this since we are working on a new branch based off the results here. Thanks everybody for contributing!

**Comment by jgoppert** [comment]
I through up some example analysis in the google doc for doing it offboard with px4tools in case anyone is interested.

https://plus.google.com/u/0/photos/albums/pjef7ab3qjpbbn8187fdtb5c8dd103fvr?pid=6372183916828934994&oid=102578156468562321452

**Comment by kd0aij** [comment]
@dagar Is tdfread the only Octave-incompatible function in the Matlab scripts? It looks a lot like a function I wrote for my sysid stuff: https://github.com/kd0aij/impulse-response/blob/master/src/imp_resp/loaders/tdfread.m

**Comment by dagar** [comment]
@kd0aij I believe so, but I think we've moved on from needing those scripts.

**Pull request closed without merging**
