### PR TITLE
WIP: valgrind runtime analysis and fixes

### PR DESCRIPTION
**Pull request by jgoppert**
We really should be using posix + valgrind + callgrind more to improve the runtime analysis. It is pretty easy to use.

image

```bash
sudo apt-get install valgrind kcachegrind
make posix_sitl_default gazebo_iris_valgrind
make posix_sitl_default gazebo_iris_callgrind ( recently add this to iekf branch, need to create a patch for this here)
kcachegrind build_px4fmu-v2_default/tmp/*callgrind.out
```

```bash
==22233== Memcheck, a memory error detector
==22233== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==22233== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==22233== Command: /home/jgoppert/git/px4/px4/build_posix_sitl_default/src/firmware/posix/px4 /home/jgoppert/git/px4/px4 /home/jgoppert/git/px4/px4/posix-configs/SITL/init/ekf2/iris
==22233== 
Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Gazebo multi-robot simulator, version 7.0.0
Copyright (C) 2012-2016 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.123.101
[Msg] Publicized address: 192.168.123.101
data path: /home/jgoppert/git/px4/px4
commands file: /home/jgoppert/git/px4/px4/posix-configs/SITL/init/ekf2/iris
creating new parameters file
creating new dataman file
18446744073709551191 WARNING: setRealtimeSched failed (not run as root?)

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

WARN  [param] error importing from 'rootfs/eeprom/parameters'
Command 'param' failed, returned 1
  SYS_AUTOSTART: curr: 0 -> new: 4010
INFO  [dataman] Unkown restart, data manager file 'rootfs/fs/microsd/dataman' size is 47640 bytes
  BAT_N_CELLS: curr: 0 -> new: 3
  CAL_GYRO0_ID: curr: 0 -> new: 2293768
  CAL_ACC0_ID: curr: 0 -> new: 1376264
  CAL_ACC1_ID: curr: 0 -> new: 1310728
  CAL_MAG0_ID: curr: 0 -> new: 196616
  CAL_GYRO0_XOFF: curr: 0.0000 -> new: 0.0100
  CAL_ACC0_XOFF: curr: 0.0000 -> new: 0.0100
  CAL_ACC0_YOFF: curr: 0.0000 -> new: -0.0100
  CAL_ACC0_ZOFF: curr: 0.0000 -> new: 0.0100
  CAL_ACC0_XSCALE: curr: 1.0000 -> new: 1.0100
  CAL_ACC0_YSCALE: curr: 1.0000 -> new: 1.0100
  CAL_ACC0_ZSCALE: curr: 1.0000 -> new: 1.0100
  CAL_ACC1_XOFF: curr: 0.0000 -> new: 0.0100
  CAL_MAG0_XOFF: curr: 0.0000 -> new: 0.0100
  SENS_BOARD_X_OFF: curr: 0.0000 -> new: 0.0000
  COM_RC_IN_MODE: curr: 0 -> new: 1
  NAV_DLL_ACT: curr: 0 -> new: 2
  COM_DISARM_LAND: curr: 0 -> new: 3
  NAV_ACC_RAD: curr: 10.0000 -> new: 2.0000
  COM_OF_LOSS_T: curr: 0.0000 -> new: 5.0000
  COM_OBL_ACT: curr: 0 -> new: 2
  RTL_RETURN_ALT: curr: 60.0000 -> new: 30.0000
  RTL_DESCEND_ALT: curr: 30.0000 -> new: 5.0000
  RTL_LAND_DELAY: curr: -1.0000 -> new: 5.0000
  MC_ROLLRATE_P: curr: 0.1500 -> new: 0.2000
  MC_PITCHRATE_P: curr: 0.1500 -> new: 0.2000
  MC_PITCH_P: curr: 6.5000 -> new: 6.0000
  MC_ROLL_P: curr: 6.5000 -> new: 6.0000
  MPC_HOLD_MAX_Z: curr: 0.6000 -> new: 2.0000
  MPC_Z_VEL_P: curr: 0.2000 -> new: 0.6000
  MPC_Z_VEL_I: curr: 0.0200 -> new: 0.1500
  EKF2_GBIAS_INIT: curr: 0.1000 -> new: 0.0100
  EKF2_ANGERR_INIT: curr: 0.1000 -> new: 0.0100
  EKF2_MAG_TYPE: curr: 0 -> new: 1
INFO  [platforms__posix__drivers__ledsim] LED::init
INFO  [platforms__posix__drivers__ledsim] LED::init
INFO  [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..
[Dbg] [gazebo_mavlink_interface.cpp:141] <joint_name> not found for channel[0] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:141] <joint_name> not found for channel[1] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:141] <joint_name> not found for channel[2] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:141] <joint_name> not found for channel[3] no joint control will be performed for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:130] joint [zephyr_delta_wing::propeller_joint] not found for channel[4] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:130] joint [zephyr_delta_wing::flap_left_joint] not found for channel[5] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:130] joint [zephyr_delta_wing::flap_right_joint] not found for channel[6] no joint control for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:141] <joint_name> not found for channel[7] no joint control will be performed for this channel.
==22233== Thread 8 sim_rcv:
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x505B21: filterCurrent (battery.cpp:128)
==22233==    by 0x505B21: Battery::updateBatteryStatus(unsigned long, float, float, float, bool, battery_status_s*) (battery.cpp:91)
==22233==    by 0x502C00: Simulator::handle_message(__mavlink_message*, bool) (simulator_mavlink.cpp:334)
==22233==    by 0x503AFA: Simulator::pollForMAVLinkMessages(bool, int) (simulator_mavlink.cpp:719)
==22233==    by 0x5013B1: Simulator::start(int, char**) (simulator.cpp:142)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x505B45: filterCurrent (battery.cpp:135)
==22233==    by 0x505B45: Battery::updateBatteryStatus(unsigned long, float, float, float, bool, battery_status_s*) (battery.cpp:91)
==22233==    by 0x502C00: Simulator::handle_message(__mavlink_message*, bool) (simulator_mavlink.cpp:334)
==22233==    by 0x503AFA: Simulator::pollForMAVLinkMessages(bool, int) (simulator_mavlink.cpp:719)
==22233==    by 0x5013B1: Simulator::start(int, char**) (simulator.cpp:142)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
[Wrn] [Event.cc:87] Warning: Deleteing a connection right after creation. Make sure to save the ConnectionPtr from a Connect call
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris/motors, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris/motor_speed/0, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris/motor_speed/1, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris/motor_speed/2, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris/motor_speed/3, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris/imu, deleting message. This warning is printed only once.
INFO  [simulator] Got initial simuation data, running sim..
INFO  [pwm_out_sim] MODE_8PWM
Sleeping for 1 s; (1000000 us).
==22233== Thread 4 hpwork:
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x47FD6A: land_detector::LandDetector::_cycle() (LandDetector.cpp:141)
==22233==    by 0x446788: work_process (work_thread.c:149)
==22233==    by 0x4467F3: work_hpthread (work_thread.c:270)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Thread 9 commander:
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x46988B: ekf2Check (PreflightCheck.cpp:464)
==22233==    by 0x46988B: Commander::preflightCheck(void**, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, unsigned long) (PreflightCheck.cpp:695)
==22233==    by 0x4607BF: commander_thread_main(int, char**) (commander.cpp:1666)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x469E53: ekf2Check (PreflightCheck.cpp:474)
==22233==    by 0x469E53: Commander::preflightCheck(void**, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, unsigned long) (PreflightCheck.cpp:695)
==22233==    by 0x4607BF: commander_thread_main(int, char**) (commander.cpp:1666)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x469F03: ekf2Check (PreflightCheck.cpp:484)
==22233==    by 0x469F03: Commander::preflightCheck(void**, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, unsigned long) (PreflightCheck.cpp:695)
==22233==    by 0x4607BF: commander_thread_main(int, char**) (commander.cpp:1666)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x469F66: ekf2Check (PreflightCheck.cpp:494)
==22233==    by 0x469F66: Commander::preflightCheck(void**, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, unsigned long) (PreflightCheck.cpp:695)
==22233==    by 0x4607BF: commander_thread_main(int, char**) (commander.cpp:1666)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Thread 14 ekf2:
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x46F948: Ekf2::task_main() (ekf2_main.cpp:554)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x51C927: EstimatorInterface::setMagData(unsigned long, float (&) [3]) (estimator_interface.cpp:163)
==22233==    by 0x4717B9: Ekf2::task_main() (ekf2_main.cpp:557)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x51C941: EstimatorInterface::setMagData(unsigned long, float (&) [3]) (estimator_interface.cpp:168)
==22233==    by 0x4717B9: Ekf2::task_main() (ekf2_main.cpp:557)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x51C96D: EstimatorInterface::setMagData(unsigned long, float (&) [3]) (estimator_interface.cpp:168)
==22233==    by 0x4717B9: Ekf2::task_main() (ekf2_main.cpp:557)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x46F9E2: Ekf2::task_main() (ekf2_main.cpp:585)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x51CE40: EstimatorInterface::setBaroData(unsigned long, float) (estimator_interface.cpp:228)
==22233==    by 0x47181E: Ekf2::task_main() (ekf2_main.cpp:587)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x51CE49: EstimatorInterface::setBaroData(unsigned long, float) (estimator_interface.cpp:232)
==22233==    by 0x47181E: Ekf2::task_main() (ekf2_main.cpp:587)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x51CE75: EstimatorInterface::setBaroData(unsigned long, float) (estimator_interface.cpp:232)
==22233==    by 0x47181E: Ekf2::task_main() (ekf2_main.cpp:587)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x520A92: pop_first_older_than (RingBuffer.h:128)
==22233==    by 0x520A92: Ekf::initialiseFilter() (ekf.cpp:257)
==22233==    by 0x523834: Ekf::update() (ekf.cpp:204)
==22233==    by 0x46FA79: Ekf2::task_main() (ekf2_main.cpp:692)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x520AA1: pop_first_older_than (RingBuffer.h:128)
==22233==    by 0x520AA1: Ekf::initialiseFilter() (ekf.cpp:257)
==22233==    by 0x523834: Ekf::update() (ekf.cpp:204)
==22233==    by 0x46FA79: Ekf2::task_main() (ekf2_main.cpp:692)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x5211B0: Ekf::initialiseFilter() (ekf.cpp:258)
==22233==    by 0x523834: Ekf::update() (ekf.cpp:204)
==22233==    by 0x46FA79: Ekf2::task_main() (ekf2_main.cpp:692)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x521271: pop_first_older_than (RingBuffer.h:128)
==22233==    by 0x521271: Ekf::initialiseFilter() (ekf.cpp:325)
==22233==    by 0x523834: Ekf::update() (ekf.cpp:204)
==22233==    by 0x46FA79: Ekf2::task_main() (ekf2_main.cpp:692)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x52127F: pop_first_older_than (RingBuffer.h:128)
==22233==    by 0x52127F: Ekf::initialiseFilter() (ekf.cpp:325)
==22233==    by 0x523834: Ekf::update() (ekf.cpp:204)
==22233==    by 0x46FA79: Ekf2::task_main() (ekf2_main.cpp:692)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x521420: Ekf::initialiseFilter() (ekf.cpp:326)
==22233==    by 0x523834: Ekf::update() (ekf.cpp:204)
==22233==    by 0x46FA79: Ekf2::task_main() (ekf2_main.cpp:692)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
INFO  [tone_alarm] startup
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14556 remote port 14550
==22233== Thread 19 mavlink_if0:
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x4A2674: MavlinkStreamAltitude::send(unsigned long) (mavlink_messages.cpp:3415)
==22233==    by 0x4AD954: MavlinkStream::update(unsigned long) (mavlink_stream.cpp:81)
==22233==    by 0x4895C2: Mavlink::task_main(int, char**) (mavlink_main.cpp:2296)
==22233==    by 0x48C69F: Mavlink::start_helper(int, char**) (mavlink_main.cpp:2438)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14557 remote port 14540
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
pxh> INFO  [logger] logger started (mode=all)
INFO  [logger] log root dir created: rootfs/fs/microsd/log
INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2017-02-05/19_21_32.ulg
==22233== Thread 21 mavlink_if1:
==22233== Conditional jump or move depends on uninitialised value(s)
==22233==    at 0x4A2674: MavlinkStreamAltitude::send(unsigned long) (mavlink_messages.cpp:3415)
==22233==    by 0x4AD923: MavlinkStream::update(unsigned long) (mavlink_stream.cpp:106)
==22233==    by 0x4895C2: Mavlink::task_main(int, char**) (mavlink_main.cpp:2296)
==22233==    by 0x48C69F: Mavlink::start_helper(int, char**) (mavlink_main.cpp:2438)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
==22233==    at 0x4E4AAD3: ??? (syscall-template.S:84)
==22233==    by 0x48660B: Mavlink::send_packet() (mavlink_main.cpp:950)
==22233==    by 0x4A1361: _mav_finalize_message_chan_send (mavlink_helpers.h:346)
==22233==    by 0x4A1767: mavlink_msg_wind_cov_send_struct (mavlink_msg_wind_cov.h:251)
==22233==    by 0x4A1767: MavlinkStreamWind::send(unsigned long) (mavlink_messages.cpp:3535)
==22233==    by 0x4AD923: MavlinkStream::update(unsigned long) (mavlink_stream.cpp:106)
==22233==    by 0x4895C2: Mavlink::task_main(int, char**) (mavlink_main.cpp:2296)
==22233==    by 0x48C69F: Mavlink::start_helper(int, char**) (mavlink_main.cpp:2438)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233==  Address 0x5f1e9ba is 730 bytes inside a block of size 1,240 alloc'd
==22233==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22233==    by 0x48C682: Mavlink::start_helper(int, char**) (mavlink_main.cpp:2426)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
==22233== Thread 20 log_writer_file:
==22233== Syscall param write(buf) points to uninitialised byte(s)
==22233==    at 0x4E4A4BD: ??? (syscall-template.S:84)
==22233==    by 0x48479A: px4::logger::LogWriterFile::run() (log_writer_file.cpp:205)
==22233==    by 0x484931: px4::logger::LogWriterFile::run_helper(void*) (log_writer_file.cpp:151)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233==  Address 0x5f2d593 is 4,787 bytes inside a block of size 12,288 alloc'd
==22233==    at 0x4C2E80F: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22233==    by 0x48447C: px4::logger::LogWriterFile::init() (log_writer_file.cpp:67)
==22233==    by 0x484115: px4::logger::LogWriter::init() (log_writer.cpp:64)
==22233==    by 0x48359C: px4::logger::Logger::run() (logger.cpp:736)
==22233==    by 0x483F65: px4::logger::Logger::run_trampoline(int, char**) (logger.cpp:372)
==22233==    by 0x445736: entry_adapter(void*) (px4_posix_tasks.cpp:105)
==22233==    by 0x4E416B9: start_thread (pthread_create.c:333)
==22233==    by 0x59F082C: clone (clone.S:109)
==22233== 
INFO  [lib__ecl] EKF aligned, (pressure height, IMU buf: 21, OBS buf: 16)

pxh> 
Exiting...
Shutting down
Restoring terminal
==22233== 
==22233== HEAP SUMMARY:
==22233==     in use at exit: 204,043 bytes in 1,366 blocks
==22233==   total heap usage: 2,283 allocs, 917 frees, 327,328 bytes allocated
==22233== 
==22233== LEAK SUMMARY:
==22233==    definitely lost: 0 bytes in 0 blocks
==22233==    indirectly lost: 0 bytes in 0 blocks
==22233==      possibly lost: 10,944 bytes in 38 blocks
==22233==    still reachable: 193,099 bytes in 1,328 blocks
==22233==                       of which reachable via heuristic:
==22233==                         newarray           : 7,040 bytes in 6 blocks
==22233==         suppressed: 0 bytes in 0 blocks
==22233== Rerun with --leak-check=full to see details of leaked memory
==22233== 
==22233== For counts of detected and suppressed errors, rerun with: -v
==22233== Use --track-origins=yes to see where uninitialised values come from
==22233== ERROR SUMMARY: 78 errors from 25 contexts (suppressed: 1 from 1)
/home/jgoppert/git/px4/px4/Tools/sitl_run.sh: line 161: kill: (22231) - No such process
src/firmware/posix/CMakeFiles/gazebo_iris_valgrind.dir/build.make:57: recipe for target 'src/firmware/posix/CMakeFiles/gazebo_iris_valgrind' failed
make[4]: *** [src/firmware/posix/CMakeFiles/gazebo_iris_valgrind] Interrupt
CMakeFiles/Makefile2:11301: recipe for target 'src/firmware/posix/CMakeFiles/gazebo_iris_valgrind.dir/all' failed
make[3]: *** [src/firmware/posix/CMakeFiles/gazebo_iris_valgrind.dir/all] Interrupt
CMakeFiles/Makefile2:11308: recipe for target 'src/firmware/posix/CMakeFiles/gazebo_iris_valgrind.dir/rule' failed
make[2]: *** [src/firmware/posix/CMakeFiles/gazebo_iris_valgrind.dir/rule] Interrupt
Makefile:3783: recipe for target 'gazebo_iris_valgrind' failed
make[1]: *** [gazebo_iris_valgrind] Interrupt
Makefile:139: recipe for target 'posix_sitl_default' failed
make: *** [posix_sitl_default] Interrupt
```

### CODE REVIEW

**Comment by dagar** [comment]
Nice! Adding a mission test that runs under clang address sanitizer has been on my list for a long time. 

This was only startup and shutdown right? Roughly how long does it take to run? Wondering if we could add it to a build somewhere.

**Comment by dagar** [comment]
One more thought, I still find the sitl target naming to be quite confusing. At a minimum can we maintain some basic notes on usage either in the wiki or makefile help?

Any ideas for making sitl run more intuitive? What if `Tools/sitl_run.sh` was a python script and the model, simulator, debugger, etc were args with a --help?

**Comment by jgoppert** [comment]
The clunky part that is hard to remember is the makefile to cmake target naming. Cmake has nice clean variables for everything. We could maybe ditch the makefile baesd build assistant in favor of python at some point, or write a python script that calls the makefile as an temporary step. I also agree that having sitl_run.sh be a bash script is probably not a wise choice, but just fixing that won't fix the makefile target name issue. If make was better about taking args it would be simpler. Another alternative would be something like EST=lpe SIM=gazebo make posix_sitl_default or something.

**Comment by dagar** [comment]
Getting way off topic from your PR. We should probably open an issue or continue the discussion elsewhere.

I think the problem is that the entire thing has become overloaded. CMake is responsible for configuring, building, installing PX4. I'd argue that beyond that even if it's potentially more convenient to work at that level a lot of the scripting doesn't belong.

We have these orthogonal pieces, but we're cramming them all into the same system.

1. Building PX4
    - we actually only need to be building posix_sitl_default right? All the other targets have grown out of the init script structure and for some reason we've tied them together.
    - this might be built with options for debug, coverage, or santizer use

2. Running PX4
    - select init script which specifies vehicle, estimator, etc
    - ideally this would be a single unified init script and we'd select params for the above, but we're not quite there yet
    - 2a) running PX4 under a debugger or tool like valgrind

3. Building the simulator
    - jmavsim or gazebo

4. Starting the simulation
    - specify simulator, model, world

It should be trivial and obvious how to do these things independently, and then we bring the separate pieces together with a top level makefile target or helper script that knows the dependencies.

**Comment by dagar** [comment]
@jgoppert merge these fixes and continue?

**Comment by jgoppert** [comment]
@dagar Sure, will rebase and merge after this passes.

**Comment by dagar** [comment]
Unless you want to keep the individual commits just use the "Squash and merge" button in Github. The development history is still visible here, but master gets a single clean commit with a reference to this PR.

**Comment by jgoppert** [comment]
Yeah, that's fine with me.

**Pull request merged**
