### PR TITLE
Upgrade Eigen to latest

### PR DESCRIPTION
**Pull request by TSC21**
Pushed upstream Eigen lib. Compiled ok.

### CODE REVIEW

**Comment by TSC21** [comment]
OK seems like there's some difficulties with checking the git hash. So I launched https://github.com/PX4/eigen/pull/3 so it can then be sync.

**Comment by TSC21** [comment]
New PR on Eigen lib launched: https://github.com/PX4/eigen/pull/4. This one now has the commit history, as I was able to push the bitbucket repo to my github repo.

**Comment by TSC21** [comment]
@LorenzMeier problem solved! I ask you to please do 2 things, in order to get things sync and right:
1. push `default` branch form my repo (https://github.com/TSC21/Eigen) to `PX4/eigen` `3.2.5` branch.
2. Rename it `3.2.90`, which is the current latest branch.

**Comment by LorenzMeier** [comment]
Awesome, will do!

**Comment by TSC21** [comment]
@LorenzMeier looks like we don't need a workaround, at least for the first problem: https://bitbucket.org/eigen/eigen/commits/4daca6ab6a501d5edd40941935d6fdb7337d03f4?at=default.
Second one, regarding `EIGEN_MAX_STATIC_ALIGN_BYTES 16`, is supposed to be solved with https://bitbucket.org/eigen/eigen/pull-requests/132/. So for this we can keep the fix on `px4_eigen.h`. Let me just confirm that we don't have to use the `#undef`.

**Comment by TSC21** [comment]
OK I confirmed that that commit fixes the problem with `isfinite()`, etc, so I rebased and just applied the inclusion of `EIGEN_MAX_STATIC_ALIGN_BYTES 16` macro. You now just have to push `default` branch from my repo (https://github.com/TSC21/Eigen) to `PX4/eigen` `3.2.5` branch, rename it `3.2.90`, which is the current latest branch and update the git tag so it compiles ok.

**Pull request merged**
