### PR TITLE
Land detection

### PR DESCRIPTION
**Pull request by LorenzMeier**
@MaEtUgR This implements the complete ground-contact detection and setpoint zeroing we discussed.

### CODE REVIEW

**Comment by MaEtUgR** [comment]
In SITL everything worked fine... but I'm sorry to say that in real world it didn't work at all. I wasn't able to land once (note that it was in very windy conditions).

It seemed to me that it detects ground contact but not landing. I assume that as soon as there's ground contact, the controller is turned off and it does not try to further "press" against the ground and just hovers there with one part of the leg barely touching the ground. And eventually it moves again but it never gets to rest.

**Comment by Stifael** [comment]
I just had a look, and it does not seem complete yet. The new state https://github.com/PX4/Firmware/pull/6362/files#diff-921bb7fba625c282568fb2cbfc8dd414R61 gets newer set, and therefore _vehicle_land_detected.ground_contact boolean in mc_pos_control is alway false. let me know if you have to time to work on it, otherwise I will finish what is missing

**Comment by LorenzMeier** [comment]
Yep, please feel free to go ahead and fix that.

**Comment by LorenzMeier** [comment]
@Stifael Can you please make sure to install the pre-commit hook for formatting on your machine? @bkueng Can help you with that.

@MaEtUgR Can you flight-test this fixed-up version this morning?

**Comment by Stifael** [comment]
@Lorenz. Yep, but I think.it would be advisable to put that in the dev guide ad well.and mention why the fix_astyle.sh in Tool cannot be used for that

**Comment by LorenzMeier** [comment]
Please feel free to edit the dev guide. In fact in can be used for that but your version might be mismatching.

**Comment by Stifael** [comment]
Please do not test it yet outside. I was able to reproduce a case where landing is not detected. Working on fixing that

**Comment by LorenzMeier** [comment]
@MaEtUgR Land detection is not working any more in SITL. The log looks like the system is disarming before taking off.

**Comment by MaEtUgR** [comment]
@LorenzMeier Yes, I see, that's why I wanted to take it to CI here.

**Comment by MaEtUgR** [comment]
@LorenzMeier After digging a bit it seems that the test fails independent of my changes.

If I see it right CI fails for all new pull requests with the same message: `'module' object has no attribute 'ulog2csv'`

Does this have something to do with px4tools @jgoppert ?
Something just after https://github.com/PX4/Firmware/blob/8e297022e6e47c1c8e7034d6770733f9a09db7df/integrationtests/python_src/px4_it/mavros/mission_test.py#L369 ?

**Comment by LorenzMeier** [comment]
Can you rebase again and check with Beat? He has written the ulog Python module.

**Comment by bkueng** [comment]
See https://github.com/dronecrew/px4tools/pull/14

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by MaEtUgR** [comment]
rebased on master

**Comment by MaEtUgR** [comment]
@PX4TestFlights Takeoff and landing in all modes has to be tested.
I tried Manual and Position mode, takeoff and RTL in SITL and with one real model.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Pull request merged**
