### PR TITLE
Support of HITL simulation for Intel Aero FC

### PR DESCRIPTION
**Pull request by trgiman**
As discussed with @bkueng please accept following changes to support HITL correct functionality on Intel Aero RTF

### CODE REVIEW

**Comment by dagar** [comment]
I believe the CI failures will be resolved if you rebase on current PX4 master.

**Comment by dagar** [comment]
@PX4BuildBot rebase

**Comment by trgiman** [comment]
@dagar CI failure is gone. But Jenkins is still failing. Any recommendations?

**Comment by dagar** [comment]
Jenkins doesn't update the build status until it starts running. Check back in a few minutes.

**Pull request merged**
