### PR TITLE
Added QAV-R (raceblade) 5".

### PR DESCRIPTION
**Pull request by jgoppert**
I just tuned the gains for the QAV-R, flies well.

image

http://logs.uaventure.com/view/DHwMiu8HtmWzTwuMoXy77a

### CODE REVIEW

**Comment by LorenzMeier** [comment]
You can see that you have offsets between commanded and actual rate during the flight (middle of the log) what acro pilots call "lock in". A more classic racing tuning would really be interesting and make a lot of sense.

**Comment by jgoppert** [comment]
@LorenzMeier not possible to stabilize above 0.1, because very unstable above 0.12 roll/pitch rate p. Tried playing with d gain, no help. I'm seeing pretty good rate tracking performance. This frame is not a 250 frame, it is smaller, so might account for some of the difference.

**Comment by LorenzMeier** [comment]
Unstable in attitude mode or unstable in acro mode?

**Comment by jgoppert** [comment]
First thing I did to tune it was do hops with outer loop off. So just acro, inner loop is stable. Will try some actual acro flight now to check though. It was also fine at roll/pitch p = 5, but I just cranked it up for a snappier response, I can turn it back down if you prefer.

**Comment by LorenzMeier** [comment]
Snappy is fine. I just wanted to make sure that we tune each loop properly and don't compensate a too soft inner loop with a higher outer.

**Comment by jgoppert** [comment]
Not great at acro mode, but here is a plot showing response, I was flipping back to attitude mode whenever I was going to lose it.

image

**Pull request merged**
