### PR TITLE
Poll test

### PR DESCRIPTION
**Pull request by mcharleb**
Unit test for poll

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice, thanks! Did this uncover anything? I'm fighting against some oddness on Mac OS.

**Comment by mcharleb** [comment]
I am building with log timestamps enabled in px4_log.h

I'll let you know what I find.

**Comment by mcharleb** [comment]
I am seeing the 1 sec delay between zero timeout px4_poll calls (except when data was available).

vcdevtest start
pxh> App name: vcdevtest
vcdevtest
INFO  5750621    priv data = 0x7f03e4000900 PASS
INFO  5750656    pub_blocked = 1 PASS
INFO  5750667    pub_blocked = 0 PASS
INFO  5750741    TEST: BLOCKING POLL ---------------
INFO  5750820    Writer: Sleeping for 2 sec
pxh> INFO  7750949    Writer: writing char 'A'
INFO  7751012    Writer: Sleeping for 2 sec
INFO  7751052    Reader: px4_poll returned 1
INFO  7751099    read 0 write 1
INFO  7751113    Reader: px4_poll     returned 1, read 'A' PASS
INFO  9751106    Writer: writing char 'B'
INFO  9751154    Writer: Sleeping for 2 sec
INFO  9751192    Reader: px4_poll returned 1
INFO  9751224    read 1 write 2
INFO  9751238    Reader: px4_poll     returned 1, read 'B' PASS
INFO  11751250   Writer: writing char 'C'
INFO  11751304   Writer: Sleeping for 2 sec
INFO  11751341   Reader: px4_poll returned 1
INFO  11751381   read 2 write 3
INFO  11751395   Reader: px4_poll     returned 1, read 'C' PASS
INFO  11751408   TEST: ZERO TIMEOUT POLL -----------
INFO  12001288   Reader: px4_poll returned 0
INFO  13001365   Reader: px4_poll returned 0
INFO  13751399   Writer: writing char 'D'
INFO  13751444   Writer: Sleeping for 2 sec
INFO  13751482   Reader: px4_poll returned 1
INFO  13751519   read 3 write 4
INFO  13751533   Reader: px4_poll     returned 1, read 'D' PASS
INFO  13751546   TEST: 1 SEC TIMOUT POLL ------------
INFO  14751678   Reader: px4_poll returned 0
INFO  15751546   Writer: writing char 'E'
INFO  15751595   Writer: Sleeping for 2 sec
INFO  15751635   Reader: px4_poll returned 1
INFO  15751673   read 4 write 5
INFO  15751687   Reader: px4_poll     returned 1, read 'E' PASS
INFO  16751821   Reader: px4_poll returned 0
INFO  16751862   TEST: waiting for writer to stop
INFO  17751684   Writer: writing char 'F'
INFO  17751724   Writer: stopped
goodbye

**Comment by mcharleb** [comment]
In src/platforms/posix/work_queue/hrt_queue.c:

px4_task_kill(wqueue->pid, SIGCONT);

is called when new work is queued, but according to the log, the usleep function is not interrupted by the signal.

**Pull request merged**
