### PR TITLE
[WIP] NuttX LLVM libc++

### PR DESCRIPTION
**Pull request by dagar**
This PR adds LLVM's libc++ for NuttX. Currently only added to the px4fmu-v3.

There was some minor NuttX build pain to get it working, but on the PX4 side everything seems to be working normally. Who wants to try something more interesting? Eigen?

@jgoppert @TSC21 @davids5 @pavel-kirienko @acassis

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesome! With a little more work we should be able to switch to a validated LLVM workflow then, which has pretty good ARM support.

**Comment by TSC21** [comment]
@dagar this is awesome! Maybe we could add some unittests? For Eigen for example?

**Comment by davids5** [comment]
@dagar - 

I see wide char support is enabled and that concerns me on embedded platforms without any real reason for it. 
I would like to see the sizes of the new image for comparison to the non llvm libc++ build.
Then understand the cost vs. benefit. 

I do not see the make sizes output in the build.

**Comment by dagar** [comment]
Rebased and changed base to master_new_archs_nuttx_upgrade. We can consider this once master_new_archs_nuttx_upgrade makes it to master.

**Comment by dagar** [comment]
Merge base changed to master.

**Comment by dagar** [comment]
TODO: fix install usage (not compatible with OSX version).

**Comment by dagar** [comment]
No, it's a problem with the libcxx install command. https://github.com/PX4/libcxx/blob/px4-nuttx/install.sh

**Comment by dagar** [comment]
Current issues
 - MacOS install arguments - http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-compile/detail/pr-nuttx-libcxx/3/pipeline/42

image

 - Windows (cygwin) argument issues - https://ci.appveyor.com/project/Dronecode/firmware/builds/20531678
image

**Comment by dagar** [comment]
NuttX libc++ issues to review 
 - https://groups.google.com/forum/#!searchin/nuttx/Merlino%7Csort:date/nuttx/smNltLDE5Go/discussion

**Comment by dagar** [comment]
Revisit after https://github.com/PX4/NuttX/pull/46 and https://github.com/PX4/NuttX-apps/pull/3

**Pull request closed without merging**
