### PR TITLE
[WIP] FlightTaskAutoSmooth

### PR DESCRIPTION
**Pull request by mrivi**
Flight Task to fly auto maneuvers. 
Instead of flying straight line between waypoints as FlightTaskAutoLine does, it generates a straight line between the acceptance radius of two consecutive waypoints and a Bezier curve inside the acceptance radius.

(Needs) Based on  #10006

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Pretty cool!

**Comment by LorenzMeier** [comment]
FYI: Solving flash space in parallel.

**Comment by Stifael** [comment]
@dagar this adds smooth mission for MPC. There are two flighttasks for mission: flighttask that implements legacy mission (following straight lines) and this new flighttask that uses splines around the corners. This new flighttask, however, requires Bezier lib and Straightline, which both consume more flash than it is available on fmu-v2 and omnibus. 
Since only one of this tasks needs to be active/compiled,  I added this new flighttask as default, but replaced it with the legacy flighttask auto for the platforms that are low on flash.

**Comment by Stifael** [comment]
@PX4/testflights can you please test anything mission related? This PR will smooth the trajectory around the corners. 
Also, pleas play around with `NAV_ACC_RAD` which defines the location at which the vehicle starts to smooth the corner. I expect to see the best result if the `NAV_ACC_RAD` is at least equal or larger than `MPC_XY_CRUISE`.

In addition, also change the `MPC_YAW_MODE`. The difference between 0 (=looking at the next waypoint) and 3 (=along trajectory) should be significant around the corners.

**Comment by santiago3dr** [comment]
couple flights on Pixracer (v4)

nav_acc_rad set to 1m; mpc_yaw_mode set to 0; wrong heading (stuck in mode 3); rtl broken, did not engage at end of mission nor manually
https://logs.px4.io/plot_app?log=ee0f946a-2fbf-4ada-8038-de38adb14e00

nav_acc_rad set to 1m; mpc_yaw_mode set to 0; wrong heading (stuck in mode 3); rtl broken, did not engage at end of mission only after switching to manual and manually triggering rtl
https://logs.px4.io/plot_app?log=12192cc9-38e1-475f-a26f-e78f0521e4e8

heading is still broken as per #10176

**Comment by Avysuarez** [comment]
**Couple flights with pixhawk 2.1 (v3) rtl not working, and there is no difference between 1 and 3 in MPC_YAW_MODE**
https://review.px4.io/plot_app?log=597d3d47-5742-4989-b936-d9528edae2a6
https://review.px4.io/plot_app?log=0cf43bcf-5ec8-443f-b84b-9daeef46b730

**Couple flights with pixhawk 4 (v5) rtl not working, and there is no difference between 1 and 3 in MPC_YAW_MODE**
https://review.px4.io/plot_app?log=85b452aa-6c69-494d-8156-c0a05af89811
https://review.px4.io/plot_app?log=3ce57146-293f-4db8-b243-be0a293bdb03.

**Comment by dannyfpv** [comment]
flight on pixhawk 1 v2 
MPC_YAW_MODE set to 0
https://review.px4.io/plot_app?log=2d0e865f-55a7-48db-8803-af59dbe2f4c2
MPC_YAW_MODE set to 3
https://review.px4.io/plot_app?log=5d57dcbe-389f-4a20-a73a-afeb5c5ae730
MPC_YAW_MODE set to 3 and nav_acc_rad set to 5m

flight on pixmini v3
MPC_YAW_MODE set to 0
https://review.px4.io/plot_app?log=96da9d99-0347-4fb3-b177-b3e1e55d1a02
MPC_YAW_MODE set to 3
https://review.px4.io/plot_app?log=876f5af1-f2f4-4559-bc9c-d9f0f463f550
MPC_YAW_MODE set to 3 and nav_acc_rad set to 5m
https://review.px4.io/plot_app?log=4027dbab-3cd2-422a-8c6a-62fb2dad63c9

flight on pixhawk pro v4
MPC_YAW_MODE set to 0
https://review.px4.io/plot_app?log=a4349617-4f9d-4fc9-8b52-e21e8e98014b
MPC_YAW_MODE set to 3
https://review.px4.io/plot_app?log=a4349617-4f9d-4fc9-8b52-e21e8e98014b
MPC_YAW_MODE set to 3 and nav_acc_rad set to 5m
https://review.px4.io/plot_app?log=0332fefb-a16f-4ff9-b626-e8a158346ff4

**Comment by Stifael** [comment]
@PX4/testflights also would be great to test it with a non-default NAV_ACC_RAD that is larger than 5 meters to better see the smoothing around the corners. That said, it should obviously also work with 1m, but the behavior will be entirely different.

**Comment by dannyfpv** [comment]
flight on pixmini v3
MPC_YAW_MODE set to 0
https://review.px4.io/plot_app?log=52dfa707-5a89-46cf-92a2-a4c2dc30b432
MPC_YAW_MODE set to 3
https://review.px4.io/plot_app?log=b9fd00f6-0fcd-45e4-b186-8a95461780e2
MPC_YAW_MODE set to 3 and nav_acc_rad set to 5m
https://review.px4.io/plot_app?log=6911b3ed-5baf-4c28-a833-0b6b7c762b4b

flight on pixhawk pro v4
MPC_YAW_MODE set to 0
https://review.px4.io/plot_app?log=ffeccefc-9f7f-48c4-8d27-59f9612cd75b
MPC_YAW_MODE set to 3
https://review.px4.io/plot_app?log=0ef18de9-63b8-4e85-94cf-39bbdccb4de1
MPC_YAW_MODE set to 3 and nav_acc_rad set to 6m
https://review.px4.io/plot_app?log=f4ab2037-7e3a-4557-a0b5-0ca8518aab6d
MPC_YAW_MODE set to 3 and nav_acc_rad set to 7m
https://review.px4.io/plot_app?log=80d5d2df-e918-462f-a01a-f03b7e5e70ac

**Comment by Avysuarez** [comment]
**Some flights with pixhawk 2.1 (v3).** @Stifael 
https://review.px4.io/plot_app?log=b7ff650e-55db-492f-b596-9b3f728a1c03
some issues on mission, the copter stop in each waypoint and it went back and forth.
https://review.px4.io/plot_app?log=0303bc94-4794-4bed-9ac7-389429bce4cc
some issues on mission, the copter stop in each waypoint and it went back and forth. and gain altitude on the last wp to 120 meters.
https://review.px4.io/plot_app?log=1fd8ff62-7b52-4414-b80c-c51b4d9cd1d6
some issues on mission, the copter stop in each waypoint and it went back and forth.

**Some flights with pixhawk 4 (v5).**
mpc_yaw_mode 1
https://review.px4.io/plot_app?log=a795c7f1-cbb9-4c3e-9b13-0a4f31e6407c
some issues on mission, the copter stop in each waypoint and it went back and forth. mpc_yaw_mode 1 and NAV_ACC_RAD 6
https://review.px4.io/plot_app?log=25ba7c95-aa6e-41d5-9866-f97c7339177c
mpc_yaw_mode 3 and nav_acc_rad 3
https://review.px4.io/plot_app?log=5f7383db-e985-4817-b6d2-b43cf0ebf38f
some issues on mission, the copter stop in each waypoint and it went back and forth. mpc_yaw_dome 3 and nav_acc_rad 6
https://review.px4.io/plot_app?log=44cd63be-bb1d-4638-b3b6-5f9c74979c9d

**Comment by santiago3dr** [comment]
A few flights on a Pixracer (v4)

nav_acc_rad = 2
https://logs.px4.io/plot_app?log=6349d35c-6191-48f8-8b58-5b223ac0df3b
https://logs.px4.io/plot_app?log=f84891e1-f67b-4104-a63f-79c6b8296861

nav_acc_rad = 6
https://logs.px4.io/plot_app?log=329534e1-671e-4cfe-94a3-5842ae600d7a

nav_acc_rad = 10
https://logs.px4.io/plot_app?log=586459d1-c836-413d-86f3-b87916f12506

nav_acc_rad = 14
https://logs.px4.io/plot_app?log=de114203-1708-42af-96be-388f22ac5875

The horizontal tracking seems smoother around corners but I am expiriencing some horizontal jerks during straight path.
Same flight plan but running on master a9d83b7 for comparison:
https://logs.px4.io/plot_app?log=e7879deb-734c-4475-803e-c5a09b2f26a1

Pitch and Roll Angular Rates show the horizontal jerk

also, rtl seems to be working as expected with latest commit

**Pull request closed without merging**
