### PR TITLE
Remove goto statments, cleanup/tidying in tunes.cpp/h files.

### PR DESCRIPTION
**Pull request by mcsauder**
Hi,

This PR removes a constructor overload by adding default values, performs a handful of variable initializations in tunes.h, replaces goto statements with method calls, and does a bit of formatting/housekeeping for readability.

This PR was bench tested on pixracer (fmu-v4) and pixhawk 4 (fmu-v5) hardware.

Let me know if you have any questions on this PR. Thanks!

-Mark

### CODE REVIEW

**Comment by davids5** [comment]
@mcsauder has this been tested on V2?

**Comment by mcsauder** [comment]
@davids5 , yes, bench tested on pixhawk V2, pixracer V4, pixhawk 4 V5.

**Comment by mcsauder** [comment]
Rebased on current master and re-tested on V2, V4, V5.

**Comment by mcsauder** [comment]
Thanks!

**Pull request merged**
