### PR TITLE
[WIP] icm42688p little endian transfers

### PR DESCRIPTION
**Pull request by dagar**
Opening for a quick initial test on the hardware test rack.

@BazookaJoe1900 FYI

### CODE REVIEW

**Comment by dagar** [comment]
Surprisingly little difference.

``` Console
  PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
  147 wq:SPI2                     10432  3.900  1620/ 2332 252 (252)  w:sem  4   <- master
  147 wq:SPI2                      8108  3.896  1680/ 2332 252 (252)  w:sem  4    <- PR

```

**Comment by BazookaJoe1900** [comment]
it is surprisingly little difference...
I made that pr  #15514 to do some double check and keep a compilation flag. same result
`
147 wq:SPI2                     12100  3.896
`
maybe some optimization makes that swap really fast, HW and software optimization always surprise me

**Comment by BazookaJoe1900** [comment]
note that temperature reading is also little endian
https://github.com/PX4/Firmware/blob/0a2bd6feb1dff44ec601cf4cd47fcda632a247a3/src/drivers/imu/invensense/icm42688p/ICM42688P.cpp#L661

combine function can be removed

**Comment by dagar** [comment]
Thanks @BazookaJoe1900.

Looking at this driver again I have a few updates in mind. I'm also looking at using the full 20 bit accel & gyro data if I can get it to fit cleanly in the existing message architecture PX4 side.

**Pull request closed without merging**
