### PR TITLE
Improve landing for special yawmode settings

### PR DESCRIPTION
**Pull request by thomasgubler**
Currently  when landing with `MIS_YAWMODE` > 0 the yaw setpoint of the waypoint (param4) is used. This leads to unexpected yawing shortly before landing which can confuse the user.

With this PR the yaw setpoint is calculated according to the `MIS_YAWMODE` setting during landing as well. However, in contrast to normal waypoints the yaw setpoint is calculated using the last waypoint instead of the current vehicle position to avoid yawing near the ground.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice! What is the testing level of this?

**Comment by thomasgubler** [comment]
@sjwilks the yawmode was introduced by you originally. I guess you are the primary user. Do you have inputs?

**Comment by thomasgubler** [comment]
> Nice! What is the testing level of this?

@LorenzMeier tested in SITL only

**Comment by LorenzMeier** [comment]
I presume this is not fixing this? https://github.com/PX4/Firmware/issues/3394

**Comment by LorenzMeier** [comment]
I just merged the takeoff & land support from Andreas. Please rebase and re-test.

**Comment by thomasgubler** [comment]
rebased, still works in sitl

**Comment by SimonWilks** [comment]
@thomasgubler looks good.

**Comment by LorenzMeier** [comment]
Awesome!

**Pull request merged**
