### PR TITLE
Only optimize for size on NuttX

### PR DESCRIPTION
**Pull request by julianoes**
With this change only builds for NuttX which are very much flash size
constraint are optimized for size. All other builds (e.g. SITL,
Snapdragon, etc.) are left at the default for debugging or -O2 for the
usual use.

This addresses #4759.

### POSIX:

-Os:
`make posix 164.70s user 11.82s system 334% cpu 52.833 total`

-O2:
`make posix 187.23s user 12.61s system 351% cpu 56.923 total`

(default no -O2, not in this PR):
`make posix 115.52s user 11.32s system 337% cpu 37.601 total`

### QURT:

with -Os
`make qurt_eagle_default  257.10s user 6.22s system 208% cpu 2:06.03 total`

-O2
`make qurt_eagle_default  245.09s user 5.87s system 221% cpu 1:53.15 total`

(default no -O2, not in this PR):
`make qurt_eagle_default  98.16s user 5.94s system 341% cpu 30.496 total`

### px4fmu-v2_default

before (-Os):
`1018992 build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx.bin`

after (-Os):
`1018992 build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx.bin`

Unfortunately, the changes here include the latest ecl submodule, so this can't be merged before the rest of ecl has been merged.

### CODE REVIEW

**Comment by catch-twenty-two** [comment]
> before (-Os):
> 1018992 build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx.bin
> 
> after (-Os):
> 1018992 build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx.bin

Just curious, are these supposed to show a difference?

**Comment by dagar** [comment]
This is definitely than specifying optimization level in every module. A step further would probably be utilizing the existing cmake build types.

      CMAKE_CXX_FLAGS
      CMAKE_CXX_FLAGS_DEBUG           -g
      CMAKE_CXX_FLAGS_MINSIZEREL      -Os -DNDEBUG
      CMAKE_CXX_FLAGS_RELEASE         -O3 -DNDEBUG
      CMAKE_CXX_FLAGS_RELWITHDEBINFO  -O2 -g

**Comment by julianoes** [comment]
@catch-twenty-two No, they show that the size has not changed :) However, the size of this PR is currently bigger than master but that's because the ecl submodule is updated.

@dagar there is quite a bit of stuff in cmake about the optimization flags, so I'm not sure how to change it to the cmake flags you mentionened.

**Comment by bkueng** [comment]
rebased & applied

**Comment by julianoes** [comment]
> Unfortunately, the changes here include the latest ecl submodule, so this can't be merged before the rest of ecl has been merged.

Uh oh. Have all the ecl changes gone in?

**Pull request closed without merging**
