### PR TITLE
add bitmask for param metadata

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
screenshot from 2016-07-03 19-46-54

**Comment by dagar** [comment]
QGC side: https://github.com/mavlink/qgroundcontrol/pull/3723

**Comment by dagar** [comment]
EKF2_REQ_HDRIFT and EKF2_REQ_VDRIFT are repeated. Maybe this is a good time to review the metadata?

**Comment by LorenzMeier** [comment]
Nice!

**Comment by dagar** [comment]
@priseborough would you like to do a quick review/update of the EKF2 bitmask param metadata (EKF2_GPS_CHECK/EKF2_DECL_TYPE/EKF2_AID_MASK) before this goes in? We could strip down the lengthy descriptions and make sure each bit is described accurately.

EKF2_GPS_CHECK
https://github.com/dagar/Firmware/blob/param_bitmask/src/modules/ekf2/ekf2_params.c#L123

EKF2_DECL_TYPE
https://github.com/dagar/Firmware/blob/param_bitmask/src/modules/ekf2/ekf2_params.c#L411

EKF2_AID_MASK
https://github.com/dagar/Firmware/blob/param_bitmask/src/modules/ekf2/ekf2_params.c#L491

**Comment by LorenzMeier** [comment]
@priseborough Will merge this once you've reviewed it.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
