### PR TITLE
fix for sf11/c baudrate in Sf0x driver

### PR DESCRIPTION
**Pull request by bozkurthan**
This pull request is created for this issue #11689 .

**Describe problem solved by the proposed pull request**
SF11/C distance sensor comes with 115200 baudrate. Baudrate of SF11/C should be change from 9600 to 115200 in sf0x driver to meet default configuration of this device. Also, the other devices' baudrate will be left at 9600 because there is no information about them.

**Describe your preferred solution**
Quick check for SF11/C model with if/else statement to change baudrate.

**Describe possible alternatives**
Lightware devices' documentation should be update which mentioned here #11689 in the future.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@bkueng Context for change is in https://github.com/PX4/Firmware/issues/11689. This was suggested by @DanielePettenuzzo because 115200 is the factory setting baudrate for SF11/C - without this the user would have to update the sensor firmware.

**Comment by bozkurthan** [comment]
```
diff --git a/src/drivers/distance_sensor/sf0x/sf0x.cpp b/src/drivers/distance_sensor/sf0x/sf0x.cpp.pretty
index 2e75f2f..4d72034 100644
--- a/src/drivers/distance_sensor/sf0x/sf0x.cpp
+++ b/src/drivers/distance_sensor/sf0x/sf0x.cpp.pretty
@@ -592,15 +592,19 @@ SF0X::cycle()
 
 		/* if dis_sensor model is SF11/C, then set baudrate 115200, else 9600*/
 		int hw_model;
+
 		param_get(param_find("SENS_EN_SF0X"), &hw_model);
+
 		unsigned speed;
-		if (hw_model==5) {
+
+		if (hw_model == 5) {
 			speed = B115200;
 		}
 
 		else {
 			speed = B9600;
 		}
+
 		/* set baud rate */
 		if ((termios_state = cfsetispeed(&uart_config, speed)) < 0) {
 			PX4_ERR("CFG: %d ISPD", termios_state);

Formatted  src/drivers/distance_sensor/sf0x/sf0x.cpp
Format checks passed
```


@hamishwillee The user doesn't have to update firmware of sensor. The baudrate of SF11/C can be change by using Lightware terminal software, but the user has to be use third party software without these changes. The user has to update the firmware to use the sensor on I2C driver.

Before merging, it's important the know that these changes make bug on boot when sensor plugged to Telemetry 1 which is mentioned before at #11689 . FYI, @bkueng 
I'm digging into this issue.

**Comment by bozkurthan** [comment]
There is no problem on telemetry 1 anymore. Maybe I changed different files but I couldn't find or remember.
I amend result by adding format. FYI, @bkueng

**Comment by bkueng** [comment]
Thanks @bozkurthan. Rebased, sqashed & merged.

**Pull request closed without merging**
