### PR TITLE
vehicle_global_position remove redundant data

### PR DESCRIPTION
**Pull request by dagar**
Split from https://github.com/PX4/Firmware/pull/8234

### CODE REVIEW

**Comment by dagar** [comment]
Once https://github.com/PX4/Firmware/pull/8234 is in this will be rebased.

Should we also remove...
 - vel_n/vel_e/vel_d
   - most consumers just use this to calculate ground speed, perhaps we should publish that instead
 - yaw
   - duplicate of local position yaw
 - pressure_alt
   - why not use sensor_baro directly?
 - dead_reckoning
   - unused

**Comment by priseborough** [comment]
Sensor baro is a direct measurement at a data rate and latency not suitable for feedback control whereas pressure_alt is an estimated quantity at a higher rate using fusion with inertial data and suitable for use in flight controllers. In aviation it  is normally the height above sea level assuming an ISA atmosphere model with ATC specified sea level pressure (QNH). However is is not useful the moment because:

1) At the moment estimators currently set it to the raw sensor data so it cannot be used for flight control, only monitoring.
2) There is no means of adjusting the assumed sea level pressure, so the altitude reported is not compatible with ATC requirements.

These two issues will eventually need to be addressed for future use in controlled airspace, but at the moment I agree with removing pressure_alt from this topic.

**Comment by dagar** [comment]
Bug for QNH usage - https://github.com/PX4/Firmware/issues/8252

**Comment by acfloria** [comment]
I would keep the the velocities (vel_n/vel_e/vel_d) and not just use the magnitude of the ground speed. In post processing I am actually using these values and you cannot reconstruct them from just the ground speed magnitude.

**Comment by dagar** [comment]
@acfloria The vehicle_global_position velocity is copied from vehicle_local_position velocity vx/vy/vz. They're both filled in the same spot of the EKF, published at the time same, and then both logged.

This case is minor, but I'm trying to get rid of as much unnecessary duplication as possible.

**Comment by dagar** [comment]
Closing as stale. Some of this has already been merged in separate smaller PRs.

**Pull request closed without merging**
