### PR TITLE
Read RSSI from RC input channel

### PR DESCRIPTION
**Pull request by AndreasAntener**
This adds the possibility to specify an RC input channel that contains the RSSI value from the receiver. PWM range can be specified.

It's bench tested and works, a quick review would be appreciated (regarding parameters).

### CODE REVIEW

**Comment by thomasgubler** [comment]
Cool. Can you upload a picture of the setup in the wiki to make it dummy-proof? :)

**Comment by AndreasAntener** [comment]
Sure, will do. I'd even have a video from the bench test, still fiddling with it though..

**Comment by LorenzMeier** [comment]
Cherry-picked to master - I'll keep this open until the wiki docs have been fixed ;-).

**Comment by LorenzMeier** [comment]
Docs? ;-)

**Comment by AndreasAntener** [comment]
https://pixhawk.org/users/rc_rssi

**Comment by AndreasAntener** [comment]
How's it with DSM/St24 and that sort? they give you RSSI automaticallly over their protocol no?

**Comment by AndreasAntener** [comment]
While writing the docs, I figured the min/max parameters should be called _GOOD _BAD. That would make more sense, will probably rename them later.

**Comment by LorenzMeier** [comment]
Thanks. I extended the page a bit and pushed. https://pixhawk.org/users/rc_rssi?&#directly_from_the_receiver

**Pull request closed without merging**
