### PR TITLE
make motors spin in POSCTRL and ATTCTRL when landed and throttle appl…

### PR DESCRIPTION
**Pull request by tumbili**
…ied by user

### CODE REVIEW

**Comment by kd0aij** [comment]
Is this change to enable runway take-offs in "ASSIST" mode?
How is a runway take-off in AUTO mode initiated?
How does one set up for a catapult launch in ASSIST and AUTO modes?

**Comment by kd0aij** [comment]
flashed this branch on my Ninox.
Armed, switched to ALTCTL and raised throttle. Motor did not spin.

**Comment by LorenzMeier** [comment]
Can we have the log? Just to be sure that its not just your throttle scaling.

**Comment by kd0aij** [comment]
the problem was lack of GPS lock. Faking GPS resulted in motor spinning in both ALTCTL and POSCTL.

Is the spinning prop intended as an additional indication of GPS lock?

**Comment by tumbili** [comment]
@kd0aij I guess the modes are somehow rejected then.

**Comment by kd0aij** [comment]
POSCTL was rejected without GPS, but ALTCTL was not, so I assumed the motor should spin when the throttle was raised.

**Comment by tumbili** [comment]
@kd0aij Would make sense because you don't need GPS for ALTCTL but surely you do for POSCTL

**Comment by kd0aij** [comment]
@tumbili So the remaining question is whether the props should spin when armed in ALTCTL without GPS lock, and whether they will start suddenly when GPS is acquired.

**Comment by LorenzMeier** [comment]
Closing in favour of the branch in the upstream repo. @tumbili Please push to the upstream repo if possible, as branches in your fork are non-accessible for other team members.

**Pull request closed without merging**
