### PR TITLE
Camera trigger WIP

### PR DESCRIPTION
**Pull request by mhkabir**
To test :
```
nsh> camera_trigger start
```

### CODE REVIEW

**Comment by Austriker** [comment]
Why do you take in account the transfer time ?

**Comment by mhkabir** [comment]
@Austriker Some machine vision cameras (e.g Pointgrey Firefly in Mode_0 ) cannot start light integration for the next frame till the transfer is complete.
In which case, the trigger pulse is ignored.

**Comment by mhkabir** [comment]
@LorenzMeier Current status is that the triggerring works perfect, but the app causes the FMU to crash. Clearly reproducible by trying to arm and also it happens sometimes at random instants (no particular phase)
Can you please do a review on this so that I can get it cleaned up and also find any issues which I'm not aware of? (e.g yesterday's fd/ioctl issue) 
This is practically the only thing left to get my system flying.

**Comment by nopeppermint** [comment]
It would be nice, If the camera trigger could be tested as well over a channel on the radio (similar to APM Manually trigger: http://copter.ardupilot.com/wiki/common-optional-hardware/common-cameras-and-gimbals/common-camera-shutter-with-servo/)

**Comment by Austriker** [comment]
@nopeppermint the actual problem is that the app crashes when you arm the system. The RC trigger could be the second step. But for now we are stuck.

**Comment by mhkabir** [comment]
Hi,

While convergence would be nice, this system was designed to  trigger
multiple high rate machine vision cameras in sync with the IMU.

So there is a slight misunderstanding here. This won't directly trigger
your digicams, which most of you guys seem to want for your mapping systems.

Feel free to PR against my branch with additional features needed to make
it work for your application. That said, core functionality remains camera
IMU synchronous triggering.

**Comment by Austriker** [comment]
@mhkabir I understood that but for a mapping solution the sync between IMU and camera is ideal if you want mapping precision (and if your stitching algorithm take account of the imu data). 

But I still can't figure out the issue with the app crashing.

**Comment by mhkabir** [comment]
Hugo, can you try getting a JTAG and debugging the issue?

**Comment by mhkabir** [comment]
@LorenzMeier ping

**Comment by mhkabir** [comment]
Mavros pull is here : https://github.com/mavlink/mavros/pull/312/files
Testers welcome. 

I will be updating the wiki soon, with usage instructions and some basics of how the synchronised triggering system works.

**Comment by LorenzMeier** [comment]
@mhkabir Anything in addition, or is this good to go? Do you need any further feedback?

**Comment by LorenzMeier** [comment]
Running Tools/fix_code_style.sh on the camera trigger files would be great, other than that this looks great code-wise!

**Comment by mhkabir** [comment]
@LorenzMeier, two minor things to go :
[] Test command handling works ( see mavros issue )
[] Handle dynamic pin assignment ( need to adapt it to the new direct GPIO control architecture )
There has been over 6 hours of continuous testing of the core trigger functionality :) 

Once the above are done, I'll run codestyle fix and we're good to go. Also, I made small QML widget for QGC (will test later today) to enable or disable the trigger. 

Architecturally, on ROS side, I'm running a custom driver based on libdc1394 which handles the trigger messages from mavros and syncs image frames. The trigger is automatically turned on by the driver (through mavros) when all systems are ready to go.

**Comment by LorenzMeier** [comment]
@mhkabir Where is your current integration / testing standing?

**Pull request merged**
