### PR TITLE
mixer: organize by type

### PR DESCRIPTION
**Pull request by dagar**
This PR puts each type of Mixer into a separate folder and library. MixerGroup is the top level object that a mixer module interacts with to load mixers from a buffer. Other than basic organization this could allow us to more easily create builds with only a subset of Mixer types included.

``` Console

$ tree
.
├── CMakeLists.txt
├── HelicopterMixer
│   ├── CMakeLists.txt
│   ├── HelicopterMixer.cpp
│   └── HelicopterMixer.hpp
├── load_mixer_file.cpp
├── Mixer
│   ├── CMakeLists.txt
│   ├── Mixer.cpp
│   └── Mixer.hpp
├── MixerGroup.cpp
├── MixerGroup.hpp
├── mixer_load.h
├── MultirotorMixer
│   ├── CMakeLists.txt
│   ├── geometries
│   │   ├── dodeca_bottom_cox.toml
│   │   ├── dodeca_top_cox.toml
│   │   ├── hex_cox.toml
│   │   ├── hex_plus.toml
│   │   ├── hex_t.toml
│   │   ├── hex_x.toml
│   │   ├── octa_cox.toml
│   │   ├── octa_cox_wide.toml
│   │   ├── octa_plus.toml
│   │   ├── octa_x.toml
│   │   ├── quad_deadcat.toml
│   │   ├── quad_h.toml
│   │   ├── quad_plus.toml
│   │   ├── quad_s250aq.toml
│   │   ├── quad_vtail.toml
│   │   ├── quad_wide.toml
│   │   ├── quad_x_pusher.toml
│   │   ├── quad_x.toml
│   │   ├── quad_y.toml
│   │   ├── tools
│   │   │   └── px_generate_mixers.py
│   │   ├── tri_y.toml
│   │   └── twin_engine.toml
│   ├── mixer_multirotor.py
│   ├── MultirotorMixer.cpp
│   ├── MultirotorMixer.hpp
│   └── test_mixer_multirotor.cpp
├── NullMixer
│   ├── CMakeLists.txt
│   ├── NullMixer.cpp
│   └── NullMixer.hpp
└── SimpleMixer
    ├── CMakeLists.txt
    ├── SimpleMixer.cpp
    └── SimpleMixer.hpp

7 directories, 44 files

### CODE REVIEW

**Comment by jlecoeur** [comment]
@dagar Out of scope but related: Control allocator will either supersede or overlap with MultirotorMixer. The existing geometry file format will not be sufficient to describe airframes with flaps, tilting rotors, etc. What would you say will be the best approach: (i) move the geometry files higher in the directory tree and use it to generate both MultirotorMixer gains and Control-allocation effectiveness matrices, or (ii) have two sets of geometry files, one for MultirotorMixer and one for control allocation?

**Comment by dagar** [comment]
> @dagar Out of scope but related: Control allocator will either supersede or overlap with MultirotorMixer. The existing geometry file format will not be sufficient to describe airframes with flaps, tilting rotors, etc. What would you say will be the best approach: (i) move the geometry files higher in the directory tree and use it to generate both MultirotorMixer gains and Control-allocation effectiveness matrices, or (ii) have two sets of geometry files, one for MultirotorMixer and one for control allocation?

I was hoping to wrap my head around the current control allocation proposal and PRs shortly, but at the moment my guess is doing it separately will be the only thing that's really viable. With the structure we have now I was even considering disabling HelicopterMixer on the IO.

**Comment by jlecoeur** [comment]
It would actually make sense to disable some mixers on the FMU because there will be flash used up by control allocation for the same purpose. On IO, as long as all mixers fit, why not keep them a bit longer.

**Comment by dagar** [comment]
> It would actually make sense to disable some mixers on the FMU because there will be flash used up by control allocation for the same purpose. On IO, as long as all mixers fit, why not keep them a bit longer.

I agree, but it's only a matter of time until we'll need to. What would really help is if we split the mixer so that loading (text buffer) is processed fmu side and only the serialized data to construct the particular mixer type is sent over. That would eliminate all the generated MultirotorGeometry and likely a portion of the C library (sscanf, etc) px4io side.

**Pull request merged**
