### PR TITLE
Add external vision to EKF2 and EKF2 replay

### PR DESCRIPTION
**Pull request by devbharat**
Added external vision messages to replay logging and play them in ekf2 replay

### CODE REVIEW

**Comment by devbharat** [comment]
Ah! This is failing here because other changes to enable pushing vision position estimate data into ekf2 are not in here. I'll add them.

**Comment by devbharat** [comment]
This PR needs the visionSupport branch from ECL. That is why it fails.

**Comment by tumbili** [comment]
@devbharat Looks good in general! Can you provide us with a log so that we can try the replay and then merge this?

**Comment by devbharat** [comment]
@tumbili I shared logfile with you on Skype last week.

**Comment by LorenzMeier** [comment]
@devbharat Can you do this a little less obscure, e.g. in an email to Paul and Roman and/or a direct link here to Google drive or Dropbox?

**Comment by devbharat** [comment]
Try [this link](https://drive.google.com/folderview?id=0B_2ZW7-Sj-XRdGlpS0hqdDVGbzg&usp=sharing) for the log file with the replay message. The vision messages are logged under RPL5.x RPL5.y RPL5.z RPL5.yaw. I'd say that the logged vision positions are very very close to ground truth and EKF2 should be tuned to agree to them strongly.

**Comment by devbharat** [comment]
I don't know why the sit test is failing. Its not a build error, and is only failed after I updated the branch from master.

**Comment by LorenzMeier** [comment]
Jenkins test this please

**Comment by LorenzMeier** [comment]
@priseborough @tumbili Can you help to get this in?

**Comment by priseborough** [comment]
I can when i have received a replay log to test this on. All i can do at the moment is verify that it hasn't broken the default behaviour.

**Comment by devbharat** [comment]
@Paul I've added a link to the replay log with vision in the message above. It's a public Google drive link.

**Comment by priseborough** [comment]
@devbharat You haven't yet added the code required to set the the external vision system position and yaw angle 1-sigma observation error estimates . The default value of 0.01 does not work.

**Comment by priseborough** [comment]
I have changed the defaults t 0.1 and updated the ecl reference here:

https://github.com/PX4/Firmware/tree/pr-ekf2VisionSupport

**Comment by devbharat** [comment]
I'll eventually add a mavlink message to communicate the covariance matrix next week.

**Comment by priseborough** [comment]
@devbharat Unfortunately due to the merging of of https://github.com/PX4/Firmware/pull/4518 this PR now has a number of conflicts that need to be resolved. Can you please have a look at them. TXS.

**Comment by devbharat** [comment]
Should work now

**Comment by priseborough** [comment]
Flight test results with default parameters (GPS, Baro and Magnetometer fusion) here:

http://logs.uaventure.com/view/wfws8hYiuZJMF8rMxnaCRT

**Comment by priseborough** [comment]
We need to get this PR rebased and merged as it is holding up support for EV fusion tuning

**Comment by priseborough** [comment]
I've pushed a rebase of this to here: https://github.com/priseborough/Firmware/tree/px4_push_ev_Ekf2_replay

Can someone please verify that it can log and replay EV data.

**Comment by devbharat** [comment]
I just tested it. It played the replay file fine. I've not analyzed the replayed file itself.

Both the original replay file and the created "replayed" logfile are available [here](https://drive.google.com/folderview?id=0B_2ZW7-Sj-XRLWxaTjJidmY0X0U&usp=sharing). It's a public link.

**Comment by priseborough** [comment]
@devbharat Was that log recorded using the rebased branch?

**Comment by devbharat** [comment]
It was from 3c968f32a532a1c05eb8343f0f34c0c5fe05e24f

**Comment by priseborough** [comment]
The EKF2 parameters on your board are out of date then.

**Comment by devbharat** [comment]
The replay.px4log file was the same old one. The replay_replayed.px4log is the replayed file using the commit I mentioned above. I do not have the hardware running to really collect a new dataset right now.

**Comment by priseborough** [comment]
When can you have that running? The testing is incomplete until that can be done.

**Comment by priseborough** [comment]
@devbharat Looking at the replay results, the method you have used to only log the yaw data and then convert it back to a quaternion assuming zero roll and pitch inside ekf2_replay_main.cpp is causing problems with gimbal lock and needs to be changed to logging the whole quaternion. The EKF converts the EV quaternion internally to a yaw angle using either a 321 or 312 Euler sequence depending on the orientation of the vehicle, and it is not practical to replicate this functionality inside ekf2_replay_main.cpp. 

I have also spotted a rebase error in sdlog2.c

I will push fixes for these to my branch for you to test when you get your setup working.

**Comment by priseborough** [comment]
@devbharat I have pushed updates for the logging and replay to my branch:

Fixes the rebase error
Logs the quaternions for use in the replay
Logs the error estimates for use in the replay

**Comment by devbharat** [comment]
I'll try to get a handheld dataset tomorrow.

**Comment by priseborough** [comment]
@devbharat Given I am now the person working on this PR, it makes more sense for it to reference the branch where i can update it as required. I will open a new PR referencing a branch in origin and close this one if that's OK with you.

**Comment by devbharat** [comment]
No problem.

**Comment by priseborough** [comment]
@devbharat what was the intended use of the EKF2_MIN_EV parameter?

**Comment by priseborough** [comment]
Closing this and replacing with https://github.com/PX4/Firmware/pull/4647

**Pull request closed without merging**
