### PR TITLE
New pca9685 driver

### PR DESCRIPTION
**Pull request by SalimTerryLi**
**Describe problem solved by this pull request**
New pca9685 driver, replacing old one.
Almost solved all of problems I could find.

**Test data / coverage**
Works fine on a RPi.

### CODE REVIEW

**Comment by dagar** [comment]
Looks good, although I'm wondering if it should be named differently to indicate it's specifically an "output module" and not a general pca9685 driver.

Maybe something like `drivers/pca9685 -> drivers/pca9685_pwm_out`?

Can you also delete all the PCA9685 references in linux_pwm_out? https://github.com/PX4/Firmware/tree/master/src/drivers/linux_pwm_out

**Comment by SalimTerryLi** [comment]
[This one](https://github.com/PX4/Firmware/blob/d6cff809f3ca9535048e3af32ca80ee7aa6537b7/boards/uvify/core/init/rc.board_sensors#L37) is affected. I'm not sure how it can be solved. It seems PCA9685(and other pwm drivers) needs standalone parameters.

**Comment by jinchengde** [comment]
May I ask the PCA9685 could be worked in pixhawk throught IIC?

**Comment by SalimTerryLi** [comment]
> May I ask the PCA9685 could be worked in pixhawk throught IIC?

It should work in principle. I have no hardware to test. Of course there is no optimization for pixhawk by now.

**Comment by jinchengde** [comment]
https://discuss.px4.io/t/vtol-pwm-channels-from-i2c-pca9685/6756/2

someone try to use PCA9685 for VTOL

**Comment by dagar** [comment]
> [This one](https://github.com/PX4/Firmware/blob/d6cff809f3ca9535048e3af32ca80ee7aa6537b7/boards/uvify/core/init/rc.board_sensors#L37) is affected. I'm not sure how it can be solved. It seems PCA9685(and other pwm drivers) needs standalone parameters.

Good catch. If you can rename the new driver to something like `pca9685_pwm_out` and leave the existing `drivers/pca9685` in place I'll reconcile the differences and delete it later.

**Comment by SalimTerryLi** [comment]
@dagar please have a look.

**Comment by SalimTerryLi** [comment]
It is not worth to remove pca9685 from `linux_pwm_out` now. It should be done once all elements in `linux_pwm_out` have a better replacement.

**Comment by dagar** [comment]
Can you skip the `pwm_out_sim` move for now? I think we'll want to create a common folder for all "output" modules, but more broadly than just pwm (dshot, tap_esc, etc).

**Comment by dagar** [comment]
Looks good, thanks @SalimTerryLi.

**Pull request merged**
