### PR TITLE
400Hz main sampling rate

### PR DESCRIPTION
**Pull request by LorenzMeier**
@kd0aij Could you flight-test this one? The CPU load increases just very slightly by 6% and the change nicely shows that we architected the system correctly to scale as it should.

250 Hz:

```
CPU usage: 35.42% tasks, 0.68% sched, 63.90% idle
Uptime: 239.740s total, 162.472s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
   0 Idle Task                  162471 63.903     0/    0   0 (  0)  READY 
   1 hpwork                       9758  4.672   836/ 1592 192 (192)  w:sem 
   2 lpwork                       1305  0.527   572/ 1592  50 ( 50)  w:sig 
   3 init                         1497  0.000  1316/ 2496 100 (100)  w:sem 
 245 top                            57  3.541  1228/ 1696 100 (100)  RUN   
  90 gps                           645  0.226   780/ 1192 220 (220)  w:sem 
  92 dataman                        23  0.000   652/ 1192  90 ( 90)  w:sem 
 116 sensors                      6710  2.788  1828/ 1992 250 (250)  w:sem 
 118 commander                     967  0.376  3132/ 3592 140 (140)  w:sig 
 119 commander_low_prio              8  0.000   620/ 2992  50 ( 50)  w:sem 
 123 px4io                        7231  3.165   964/ 1496 240 (240)  w:sem 
 134 mavlink_if0                  2360  0.979  2332/ 2896 100 (100)  w:sig 
 135 mavlink_rcv_if0               111  0.000  1148/ 2096 175 (175)  w:sem 
 142 mavlink_if1                  1949  0.753  2340/ 2896 100 (100)  w:sig 
 143 mavlink_rcv_if1               116  0.000   936/ 2096 175 (175)  w:sem 
 171 mavlink_if2                 13839  5.727  2340/ 2896 100 (100)  w:sig 
 172 mavlink_rcv_if2                35  0.000  1032/ 2096 175 (175)  w:sem 
 178 sdlog2                       2877  1.281  2156/ 3392 177 (177)  w:sem 
 216 attitude_estimator_q        13397  5.576  2012/ 2496 250 (250)  w:sem 
 221 position_estimator_inav      6474  2.712  4844/ 5296 250 (250)  w:sem 
 229 mc_att_control               5764  2.411  1316/ 1496 250 (250)  w:sem 
 234 mc_pos_control               1618  0.678  1172/ 1896 250 (250)  w:sem 
 241 navigator                      10  0.000   780/ 1496 105 (105)  w:sem 
nsh> 
```

and 400 Hz:

```
Processes: 23 total, 3 running, 20 sleeping
CPU usage: 41.02% tasks, 0.68% sched, 58.30% idle
Uptime: 238.235s total, 146.381s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
   0 Idle Task                  146381 58.302     0/    0   0 (  0)  READY 
   1 hpwork                       9669  4.132   852/ 1592 192 (192)  w:sem 
   2 lpwork                       1314  0.525   572/ 1592  50 ( 50)  w:sig 
   3 init                         1504  0.000  1420/ 2496 100 (100)  w:sem 
 254 top                           199  3.531  1228/ 1696 100 (100)  RUN   
  90 gps                           645  0.225   788/ 1192 220 (220)  w:sem 
  92 dataman                        23  0.000   652/ 1192  90 ( 90)  w:sem 
 116 sensors                      9624  4.057  1748/ 1992 250 (250)  w:sem 
 118 commander                    1087  0.450  3132/ 3592 140 (140)  w:sig 
 119 commander_low_prio              8  0.000   556/ 2992  50 ( 50)  w:sem 
 123 px4io                        9881  4.132   980/ 1496 240 (240)  w:sem 
 134 mavlink_if0                  2430  1.051  2340/ 2896 100 (100)  w:sig 
 135 mavlink_rcv_if0                76  0.000  1116/ 2096 175 (175)  w:sem 
 142 mavlink_if1                  1976  0.751  2596/ 2896 100 (100)  w:sig 
 143 mavlink_rcv_if1               133  0.000   936/ 2096 175 (175)  w:sem 
 171 mavlink_if2                  8365  3.606  2324/ 2896 100 (100)  w:sig 
 172 mavlink_rcv_if2                20  0.000   828/ 2096 175 (175)  w:sem 
 178 sdlog2                       4082  1.728  2140/ 3392 177 (177)  w:sem 
 216 attitude_estimator_q        19902  8.489  2068/ 2496 250 (250)  w:sem 
 221 position_estimator_inav      9450  3.981  4844/ 5296 250 (250)  w:sem 
 229 mc_att_control               8458  3.606  1316/ 1496 250 (250)  w:sem 
 234 mc_pos_control               1741  0.751  1156/ 1896 250 (250)  w:sem 
 241 navigator                      11  0.000   796/ 1496 105 (105)  w:sem 
nsh> 
```

### CODE REVIEW

**Comment by kd0aij** [comment]
Cool. Will see if I can log a few topics at 400Hz and do impulse response analysis.

**Comment by tumbili** [comment]
@LorenzMeier Tested and it seems ok, although I was having some kind of rc problem at the beginning which gave the feeling that there was a huge latency from rc sticks to attitude.

**Comment by kd0aij** [comment]
bench test with new logger: a bit non-uniform, but a lot of 2.5msec intervals:
400hz

will fly it in a little while

**Comment by LorenzMeier** [comment]
If you look at your sampling it actually looks as if the logger dropped samples in most cases where the spacing is not close to uniform. But I'm not ruling out that this will identify things that we might want to improve.

**Comment by kd0aij** [comment]
The new logger didn't hardfault until I tried to fly it. Seems to know whether it's on battery power.
Here's a px4log instead: http://logs.uaventure.com/view/ZNeii56wUS4iK3xKtsHL3D
Can't say it looked or felt any different.

Discovered that a hardfault doesn't stop the PWM outputs with fmu-v4, makes it very difficult to unplug the battery. @pkocmoud A BTS555 power relay would have been nice to have :)

**Comment by LorenzMeier** [comment]
@kd0aij I've rebased this on master - would you be up for another test flight with the new logger and look at performance?

**Comment by kd0aij** [comment]
@LorenzMeier It looks like the new logger is out of sync with FlightPlot at the moment.
More importantly, the experience of a hardfault on fmu-v4, which left motors running at high speed makes me wonder whether it's possible to disable PWM timers in the hardfault handler. Even if it wasn't 100% reliable, it would be better than nothing. Obviously, enabling the safety switch would do no good.

**Comment by LorenzMeier** [comment]
I think the real fix for this will be the NuttX update which stores the hard fault state and reboots.

**Pull request closed without merging**
