### PR TITLE
Streamline python script for temp cal.

### PR DESCRIPTION
**Pull request by jgoppert**
@priseborough This isn't 100% there yet, but wanted to put it up so we can make sure we are on the same page.

### CODE REVIEW

**Comment by priseborough** [comment]
I was unable run this because of the jinja2 dependancy (I am using OSX). We should provide instructions on how to set up the required python modules, or better still include them in the default PX4 toolchain scripts.

**Comment by jgoppert** [comment]
Yeah, I agree. jinja2 was recently added to the core libraries to clean up a lot of our source code and model generation.

Can you give this a shot: http://beyond925.blogspot.com/2015/05/how-to-install-jinja2-on-mac-os-x.html?view=mosaic

**Comment by priseborough** [comment]
That didn't work for me, and I am not familiar with the json file format.

**Comment by jgoppert** [comment]
OK, good to know. I will comment it out for now so you can use it and put something like you used to have.

**Comment by jgoppert** [comment]
@priseborough Let me know how this works for you.

**Comment by priseborough** [comment]
That worked thanks.

**Comment by jgoppert** [comment]
@priseborough Should we merge this in?

**Comment by priseborough** [comment]
Go for it

**Pull request merged**
