### PR TITLE
batt_smbus: calculate current discharged

### PR DESCRIPTION
**Pull request by rmackay9**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
The usleeps() are still a bit weird, but I presume what it does is the equivalent of yield() and that again has to do with the internal architecture of APM where the internal scheduler doesn't fully know about priorities. I wouldn't be surprised if Tridge's latest hack to boost priority for some tasks isn't already resolving this. If not we might want to build the yield() call into the HRT queue itself, rather than into the driver.

Its not something I'm suggesting to do right now though, but rather something that should be on the architectural agenda.

**Comment by AndreasAntener** [comment]
SITL CI: test this please

**Comment by rmackay9** [comment]
Ok, I've tested removing the usleeps and as you suspected it doesn't cause problems.  I've submited a follow up patch above which removes these.
There's another small unrelated change to the driver to restore the I2C address after performing a "search" for smart batteries. This makes sure the driver continues to work after performing the search.

**Comment by rmackay9** [comment]
great, thanks!

**Pull request merged**
