### PR TITLE
Jenkins CI: move SITL tests to Melodic container

### PR DESCRIPTION
**Pull request by TSC21**
I don't know of the specific reason why this wasn't done before, but I do think it makes sense at this point.

### CODE REVIEW

**Comment by TSC21** [comment]
Seems like `pyulog` wasn't being installed on the Melodic container. I am bringing that in https://github.com/PX4/containers/pull/205/commits/8fbe53020c38069abab2f708e5d2c77950f051c9

**Comment by lamping7** [comment]
We might want to note this change with @hamishwillee in the docs and depreciate Ubuntu 16 & ROS Kinetic. Thoughts?

**Comment by hamishwillee** [comment]
> ... depreciate Ubuntu 16 & ROS Kinetic. Thoughts?

From my perspective I first need a confirmation of what "support" means. I assume something like "We regularly test in CI for this OS/ROS platform combination and will fix bugs for that target"

Then info on what  OS/ROS combinations this is true for :-)

**Comment by TSC21** [comment]
All seems good in CI, so I am bringing this in.

**Pull request merged**
