### PR TITLE
Added mpc_alt_mode.

### PR DESCRIPTION
**Pull request by jgoppert**

### CODE REVIEW

**Comment by mhkabir** [comment]
Slight concern here -  Won't there potentially be a jump in altitude when you lose the terrain estimate for example? 
I propose adding a Z setpoint reset when we switchover from terrain to local altitude and vice versa. That should make the transition unnoticeable.

**Comment by ecmnet** [comment]
@jgoppert One question: Is _local_pos.dist_bottom published via MAVLINK? altitude_terrain seems to be NaN in SITL.

**Comment by jgoppert** [comment]
@mhkabir There is no jump as coded in LPE, this has already been flight tested, we should probably put a note that other estimators should not use MPC_ALT_MODE 1 until they have flight tested it.

Here is how I avoid the jump:

dist_bottom = local_z - terrain_alt

dist_bottom is always published if we can estimate z (it does not rely on can_estimate_terrain), it would jump if I stopped publishing it, but because it is computed as the difference between local_z  and terrain_alt, if terrain_alt stops getting updates, the state will remain the same and the transition is smooth.

**Comment by jgoppert** [comment]
@ecmnet alt_terrain is NaN as long as dist_bottom is not valid. This behaviour is the same in flight testing. If alt_terrain is NaN then it will still fly in MPC_ALT_MODE = 0 effectively due to the logic check.

**Comment by jgoppert** [comment]
I added a warning here to make sure people don't try to flip the switch when in EKF2/ INAV. I believe that it would probably work, but do to the way it is currently coded I would expect a discrete jump: https://github.com/PX4/Firmware/commit/0f0f354acdae354f7e66452c5bbadf40a504ca4b

**Comment by ecmnet** [comment]
@jgoppert I noticed that comparing SP.Z and NED.Z published via MAVLink, there is a signifikant bias, although altitude is kept well using MP_ALT_MODE = 1. I think, that is because NED.Z is local altitude from home and SP.Z corresponds to the distance above ground. Maybe it is a good idea to publish SP.Z corrected by current terrain altitude when using MP_ALT_MODE = 1 .

**Pull request merged**
