### PR TITLE
rename nuttx board support packages for consistency

### PR DESCRIPTION
**Pull request by dagar**
This makes it a little easier to directly compare boards (eg what's different between fmu-v4 and v4pro) and works towards defining what's actually required in a board support package.

### CODE REVIEW

**Comment by dagar** [comment]
That's a fair point I didn't think about. I was more interested in understanding what's actually needed per board, minor differences between similar boards, and then concerned with the amount of manually duplicated code.

For example I can now see large portions of these files are nearly identical between boards.
 - the interactive portion of the crashdump handler (a big chunk of a typical stm32_init) is duplicated code
 - stm32_can is identical
 - many of the timer configs are completely identical, some have identical subsets
 - stm32_usb often identical 
 - this gave me some ideas for generalizing spi select based on the board manifest idea

So if this was purely cosmetic/organizational I'd tend to agree, but I actually see this as a step towards generalizing a lot more of the board support so that the portions we actually need to add and maintain per board are kept to a minimum.

**Comment by davids5** [comment]
@dagar I could not agree with you more on the final point. We should propagate the common file to a board / arch {stm32|stm32f7|kinetis} common lib. Some can be removed wholesale I.E. CAN. The SPI and IO init should be using the new mechanism added for v5 across the board (except where the runtime detection of HW requires alternate uses - that will need to be refactored.)

**Comment by davids5** [comment]
@LorenzMeier yep. Hovering over the tabs in eclipse will show the path. Making sweeping changes has high pain points. 21 files named defconfig, is already error prone. The consolidation will reduce that but we can never eliminate it.  The naming came from nuttx and this build is already a departure so @dagar should do what makes the most sense for the project and I will work with whatever we end up with.

**Comment by dagar** [comment]
TODO - rename generically without arch prefix as discussed to aid general refactoring and board organization. Once we push all the common pieces into libraries in the right layer we can name what's left to something board specific if still desired.

The overall idea this is working towards is consolidating every single piece required for a specific board in a single directory, and treating it like the interface that needs to be implemented for every board.

Example
  - fmu-v2
    - default.cmake
    - nuttx_defconfig
    - include
       - board_config.h
    - src
       - init.c
       - etc

I want to remove as many questions and general ambiguity about adding board support as possible. If we make an effort to extract the duplicated code, compress the defconfig, and a few other generated the pieces (board manifest!), there will actually be very little required to add a new board that's similar to an existing one.

**Comment by dagar** [comment]
Architecture prefixes (stm32, kinetic, samv7) dropped.

**Comment by dagar** [comment]
As discussed we'll go with this for now to facilitate project organization and refactoring, then reevaluate once all board dependencies are consolidate.

**Pull request merged**
