### PR TITLE
fix accel calibration

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by tumbili** [comment]
This is not fully correct yet!!!

**Comment by AndreasAntener** [comment]
Bummer, I just tested it and it got me through calib ;)

**Comment by tumbili** [comment]
Yes, but the offsets are wrong :-(

**Comment by tumbili** [comment]
@AndreasAntener Ok, I think I was wrong about the offsets. Can you verify that the values look ok?

**Comment by AndreasAntener** [comment]
```
1	50	CAL_ACC0_ID	1246218	6
1	50	CAL_ACC0_XOFF	-0.0561886	9
1	50	CAL_ACC0_XSCALE	0.993732	9
1	50	CAL_ACC0_YOFF	-0.0170426	9
1	50	CAL_ACC0_YSCALE	0.99162	9
1	50	CAL_ACC0_ZOFF	0.707426	9
1	50	CAL_ACC0_ZSCALE	0.992477	9
1	50	CAL_ACC1_ID	1114634	6
1	50	CAL_ACC1_XOFF	1.28403	9
1	50	CAL_ACC1_XSCALE	0.99073	9
1	50	CAL_ACC1_YOFF	0.952891	9
1	50	CAL_ACC1_YSCALE	1.00956	9
1	50	CAL_ACC1_ZOFF	-1.16469	9
1	50	CAL_ACC1_ZSCALE	1.01265	9
```

How does that look?

**Comment by AndreasAntener** [comment]
screen shot 2015-05-05 at 17 02 36

Seems gravity is a little stronger in our office though ;)

**Comment by AndreasAntener** [comment]
Thanks :) , will have to try tomorrow again.

**Comment by tumbili** [comment]
@AndreasAntener Finally found out the problem. Should be ok now.

**Comment by LorenzMeier** [comment]
Thanks, awesome!

**Comment by AndreasAntener** [comment]
Thanks Roman, works just fine!

**Pull request merged**
