### PR TITLE
Rover

### PR DESCRIPTION
**Pull request by mstuettgen**
my first pull request

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Can you copy the IO mixer and leave the original file in there as well? The test fail which travis found is due to the missing file.

**Comment by mstuettgen** [comment]
I did. Do I have to send a new pull request or will this one be updated?

**Comment by LorenzMeier** [comment]
You can see that the commit did occur here correctly

**Comment by mstuettgen** [comment]
Yeah I see.... sorry have to get used to Github, but its really awesome!! So Travis does autobuild each commit? Is it your own development or does it come with Github?

**Comment by LorenzMeier** [comment]
Merged to master, thanks!

**Pull request closed without merging**
