### PR TITLE
vtol throttle pulsing fix

### PR DESCRIPTION
**Pull request by tumbili**
This could fix the throttle pulsing for vtol which we have seen recently.

### CODE REVIEW

**Comment by tumbili** [comment]
@SimonWilks @AndreasAntener This could fix #2725

**Comment by AndreasAntener** [comment]
Bench test done: http://dash.oznet.ch/view/C8ijqTFvNWwSo4XdnnHL69 (second transition)
Attitude setpoint is stable, not pulsing on out channels

**Comment by SimonWilks** [comment]
Flight tested,  will merge soon.

**Comment by SimonWilks** [comment]
Merged.

**Pull request closed without merging**
