### PR TITLE
testing results and code coverage

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
tests code coverage - https://2578-5298790-gh.circle-artifacts.com/0/home/ubuntu/Firmware/coverage-html/index.html

**Comment by LorenzMeier** [comment]
Nice! Looking forward to see this in action.

**Comment by dagar** [comment]
@LorenzMeier please review, should be mostly harmless. This is a bit of test and CI cleanup to start posting coverage info and tracking test results. Coverage numbers are currently pretty miserable, but should help guide future test development, and will eventually include mission tests.

 - Makefile: added support for easily running builds and tests within docker
     - set env variable PX4_DOCKER=1 to autostart docker and run target within (only px4-dev-nuttx at the moment). Only tested on Ubuntu so far.
 - split posix sitl tests to run individually in ctest. This allows tracking results of tests and easily rerunning them individually (eg ctest -VR mixer). Tools/CTest2JUnit.xsl added to convert ctest xml output to junit
 - move cmake check into cmake (so Makefile can run on a system without full px4 dev environment)
 - repurpose circleci to run tests and upload coverage to coveralls and keep a copy of lcov output on circleci 
 - cdash support (but not currently uploading)
 - Makefile split checks_default into qgc_firmware + checks_alt. Once this is widely available I can split the 25 minute semaphoreci build into 2 threads

**Comment by dagar** [comment]
- closes #6195

**Pull request merged**
