### PR TITLE
process_sensor_caldata.py: regularly weighted over temperature thermal fitting

### PR DESCRIPTION
**Pull request by NicolasM0**
I opened a thread here to discuss about an issue and propose a fix: https://discuss.px4.io/t/issue-with-thermal-calibration-fitting/14582

**Describe problem solved by this pull request**
If the temperature ramp is not constant during heat up, the fitting give more weight to temperature with lower change rate. If heating become very slow (typically at the high temperature), the calculated polynomial can not fit at all where the temperature change rate was high (typically at low temperature)

**Describe your solution**
This commit add a re sample before fitting to have a more regular weight over temperature

### CODE REVIEW

**Comment by dagar** [comment]
For those that didn't click through to discuss initially (like me). 

Screenshot from 2020-04-30 10-40-58

**Comment by bresch** [comment]
I like the idea and we shouldn't drop it. What's blocking this?

**Comment by NicolasM0** [comment]
I began to implement the onboard version but let it paused because I was in a rush on other tasks. I can try to finish it at the end of the month

**Comment by dagar** [comment]
> I began to implement the onboard version but let it paused because I was in a rush on other tasks. I can try to finish it at the end of the month

How about bringing it in with an option to output the parameters based on the resampled data? Then by default it's in sync with the onboard calibration method, but we can still view the impact of resampling, and opt into the change trivially.

**Comment by priseborough** [comment]
We should get this in and handle the online version in a separate PR.

**Comment by dagar** [comment]
@NicolasM0 can you rebase or merge with master to resolve the conflicts?

**Comment by NicolasM0** [comment]
This commit have been rebased but it is still a draft.
Do you want me to clean it (remove previous fitting), add an option for the new fitting or let it as it is ?

**Comment by dagar** [comment]
> This commit have been rebased but it is still a draft.
> Do you want me to clean it (remove previous fitting), add an option for the new fitting or let it as it is ?

If there are no objections and it's documented I'm fine with it.

**Comment by dagar** [comment]
If it's not too much trouble then simply adding an option to skip the resampling might be worthwhile for anyone considering using online calibration in production and wanting to sanity check the results with offline (more than visually).

**Pull request merged**
