### PR TITLE
[DO NOT MERGE] introduce vehicle_thrust_setpoint

### PR DESCRIPTION
**Pull request by dagar**
For discussion only at this point (not complete or tested).

If this is viable we might be able to drop the virtual attitude setpoints entirely. Then we can lean on thrust setpoints for coordination between position controllers. This should also lead to it being possible to drop virtual actuator controls.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice! This is going in the right direction. We might want to do this in stages though (with the original PR going in first, then this on top of it).

**Comment by bresch** [comment]
@dagar We won't be able to drop the virtual attitude setpoints because during the transition of a standard VTOL, since we want pitch and thrust_x from TECS, roll from L1 and thrust_z from the multicopter position controller. Besides that, splitting the thrust setpoints from the attitudes ones is the right way to go :)

**Comment by dagar** [comment]
@bresch yes, we'd still need a mechanism to combine orthogonal thrust setpoints (MPC altitude controller). This is one of the reasons I asked about the control allocation idea.

**Comment by dagar** [comment]
Revisit for v1.10.0

**Pull request closed without merging**
