### PR TITLE
mc pos ctrl (multiplatform): do not publish att sp in offboard && no position/velocity control

### PR DESCRIPTION
**Pull request by thomasgubler**
@AndreasAntener I think this should fix the issue discussed in #1854

This is the same fix for mc_pos_control and mc_pos_control_multiplatform

### CODE REVIEW

**Comment by AndreasAntener** [comment]
Cool. I'll test it and add an IT for attitude control

**Comment by LorenzMeier** [comment]
@AndreasAntener Anything I can do to support the IT works? I lost track of the current thread - are we close to being able to hook in the Github / Travis API?

**Comment by AndreasAntener** [comment]
Yeah we're close. For the Github integration I need an access token from some "bot" user. Will check what's necessary there in a sec

**Comment by AndreasAntener** [comment]
test

**Comment by AndreasAntener** [comment]
@thomasgubler  I gave it a quick test with #1854 but the attitude test fails. I haven't looked into it though. (But the test from #1854 works when I comment out the publishing in pos_control)

**Comment by AndreasAntener** [comment]
@LorenzMeier This isn't working yet and shouldn't have been merged ;), sorry if I haven't been clear enough.

**Comment by AndreasAntener** [comment]
Ok, the logic seems to be correct. Although I was wondering if it couldn't simply be
`if not ( offboard and attitude_endabled )`

But now my attitude setpoints alternate `roll_body`, between 0 and a value. Thrust always has a value.
@thomasgubler  Wasn't that the issue you discussed here: https://github.com/PX4/Firmware/pull/1786#issuecomment-74435575 ?

**Comment by AndreasAntener** [comment]
It seems that the problems I'm having are not related to this change here. I think I have timing issues depending on when offboard setpoints arrive and when I arm. Will make another PR to fix the test.

**Comment by thomasgubler** [comment]
> Ok, the logic seems to be correct. Although I was wondering if it couldn't simply be
if not ( offboard and attitude_endabled )

attitude is also enabled with position control (cascaded control loops)

>But now my attitude setpoints alternate roll_body, between 0 and a value. Thrust always has a value.
@thomasgubler Wasn't that the issue you discussed here: #1786 (comment) ?

I am not sure how you are sending the setpoints. However the current code should be able to handle that pattern.

**Comment by AndreasAntener** [comment]
Thanks, I figured out why it's like this too, it's all a little intransparent..

My timing issue is rather strange, and it's probably not worth looking into it since I believe it's SITL specific. But I'll describe it anyway for your amusement ;) I can reproduce it with your attitude demo (gazebo_ardrone_empty_world_offboard_attitudedemo.launch).

When I arm (manual input) before mavros is ready and your demo is publishing setpoints, nothing happens anymore. This is understandable because in SITL, once we got manual input, we fix vehicle control mode and changes to offboard mode won't be considered anymore. Vehicle control mode is therefore locked in position control.

When I arm sometime after your demo has started publishing setpoints, everything works.

Now the strange case: When I arm just about when your demo node is started, it produces what I described above. One attitude SP with roll_body, one without. But both with thrust.

**Pull request merged**
