### PR TITLE
[WIP] Bebop/RPi Toolchain Update

### PR DESCRIPTION
**Pull request by mhkabir**
Addresses #6515 

New unified toolchain installer script (installs NuttX, Bebop and RPi in one go, unattended. Probably Snapdragon too in the future): https://github.com/PX4/Toolchains

TODO 
1. Script should check for already-present toolchains and upgrade them
3. Update Devguide with instructions on how to use the new one-line script
4. Update CI system

### CODE REVIEW

**Comment by dagar** [comment]
We'll need to update the raspberry pi container to get this in CI - https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_raspi

**Comment by mhkabir** [comment]
@dagar Thanks. Would you mind reviewing the installer script :  https://github.com/PX4/Toolchains/blob/master/install_toolchain.sh

I've made it fairly robust, but a second pair of eyes on it would be nice.

**Comment by dagar** [comment]
The installer script itself seems like a good start. Unless you have significantly more planned for it that justifies an entire repo maybe it could live in Firmware/Tools? I would also convert the documentation and docker images to use this script. Then we'll only need to update a single location when upgrading and the script itself should get plenty of usage/testing.

**Comment by mhkabir** [comment]
I created its own repo because I wanted all the toolchains to stay in one folder locally. The script downloads and installs it into the "Toolchains" repo folder, so it is very clean.

Moving it to Firmware/Tools is also an option. I *could* add a toolchain folder and gitignore everything inside it. Then all the toolchains could live there, but I prefer having them outside the source tree for visibility and also for developers who will experiment with different versions. Also since I plan for Snapdragon and other future boards with complex toolchains to go in there, its probably for the best.

Which one do you think is better?

> I would also convert the documentation and docker images to use this script. Then we'll only need to update a single location when upgrading and the script itself should get plenty of usage/testing.

That was the idea :) Just updating one line will change it across the board, so makes a lot of sense.

**Comment by dagar** [comment]
Ah, I wasn't considering the location of the download. Probably don't want
that in the firmware tree. I typically extract to /opt or something.

Are you aware of the snapdragon container Mark put together?
https://github.com/ATLFlight/containers
It might help with the script.

**Comment by mhkabir** [comment]
> Are you aware of the snapdragon container Mark put together?
https://github.com/ATLFlight/containers
It might help with the script.

Awesome. I'll have a look. Thanks for the pointers, and I'll integrate that. Will try to get this merge-ready by tomorrow.

**Comment by mhkabir** [comment]
Snapdragon is using the same linaro toolchain that I updated the Bebop/Rpi to here, except that its v4.9 (`gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf`). Can we move it to 5.3 @mcharleb?

**Comment by mhkabir** [comment]
@dagar I think the script is good enough to try and integrate with CI now. Would you mind taking a stab at this? I'll push this branch to PX4/toolchain_update instead of my own fork, so that you can push stuff directly.

**Comment by dagar** [comment]
Sorry, I missed your update. We have a bit of a web of dependencies here. Do you want to incorporate this into the PX4 containers for testing? https://github.com/PX4/containers/tree/master/docker/px4-dev

**Comment by mcharleb** [comment]
@mhkabir I had missed your question above. Snapdragon uses some prebuilt libs that are currently being built with gcc/g++ 4.9 and I am not sure if there would be C++ compatibility issues moving to gcc 5.3. I am working on a new platform build using Yocto Morty and gcc 6.2.

**Comment by mhkabir** [comment]
@mcharleb Ah okay, let's keep Snappy as-is for now in that case. 

I will be pushing to get this in next week when I get some free time.

**Comment by dagar** [comment]
@mhkabir we missed this on the dev call. What is there to discuss?
@bkueng FYI

**Comment by nicolaerosia** [comment]
Could you also drop `cmake_force_c_compiler` and `cmake_force_cxx_compiler` from cmake/toolchains/Toolchain-arm-linux-gnueabihf-raspbian.cmake ? You can use `SET(CMAKE_C_COMPILER ${C_COMPILER})` and `SET(CMAKE_CXX_COMPILER ${CXX_COMPILER})` instead

**Comment by nicolaerosia** [comment]
@mhkabir are you continuing this? If no, I would like to pick it up

**Comment by LorenzMeier** [comment]
Please do. @mhkabir Is currently helping a lot getting the current release stable and probably a bit loaded also keeping this up.

**Comment by nicolaerosia** [comment]
Is there a CI that builds for RPI ? If yes, where can I change the build steps?
Changing the meaning of `PX4_TOOLCHAIN_DIR` in Toolchain-arm-linux-gnueabihf-raspbian.cmake and-or renaming `Toolchain-arm-linux-gnueabihf-raspbian.cmake` to `Toolchain-arm-linux-gnueabihf.cmake` will break builds that use them.

**Comment by dagar** [comment]
Hi @nicolaerosia, I don't know much about PX4 on raspbi, but I might be able to help if you have any questions about the build system in general (cmake, docker, CI, etc).

**Comment by nicolaerosia** [comment]
Continued here https://github.com/PX4/Firmware/pull/7248

**Comment by dagar** [comment]
Replaced by https://github.com/PX4/Firmware/pull/7248

**Pull request closed without merging**
