### PR TITLE
mavlink: accept msgs without source initialized for serial

### PR DESCRIPTION
**Pull request by julianoes**
This should fix serial MAVLink communication on FMU5x where both serial and UDP is available. There the serial connection previously did not work because nothing was connected over UDP.

Found by @dinomani.

### CODE REVIEW

**Comment by dagar** [comment]
I think it makes sense to keep, but obviously should only apply to the UDP case. `_mavlink->get_protocol() == Protocol::UDP`

**Comment by julianoes** [comment]
> I think it makes sense to keep, but obviously should only apply to the UDP case. 

@dagar Why? What is it for?

**Comment by bkueng** [comment]
Why don't you change this logic? https://github.com/PX4/Firmware/blob/1d58caecbe02ae233dd2e8414950af48ef62061f/src/modules/mavlink/mavlink_receiver.cpp#L2622

**Comment by julianoes** [comment]
@bkueng I don't understand what you mean. Do you understand why we don't accept messages until the source is initialized?

**Comment by bkueng** [comment]
> Do you understand why we don't accept messages until the source is initialized?

No, but if you were to remove the `hrt_elapsed_time(&stime) > 3_s` check for example, it would immediately set the source address as well.

**Comment by dagar** [comment]
This is a bit convoluted, let's try to track down the original intent.

**Comment by julianoes** [comment]
> This is a bit convoluted, let's try to track down the original intent.

All I can think of is that the original intent was that we can't send a UDP packet using `sendto` if we don't know where to send it to (duh). In that case it is now totally misplaced.

**Comment by julianoes** [comment]
@dinomani can you try with the latest change?

**Comment by julianoes** [comment]
@bkueng @dagar please review again, thanks.

**Comment by hamishwillee** [comment]
From a MAVLink perspective any message that doesn't have its source set is a bug. You might assume you don't need to because there is only one source/recipient on a serial port, but the routing rules assume you'll forward any broadcast messages to other interfaces too.

**Comment by julianoes** [comment]
@hamishwillee ok thanks for the comment. I'll keep it in mind. I believe this bug here is actually about the UDP IP source rather than the MAVLink source.

**Comment by dinomani** [comment]
Ok cool thx Julien
Tested ion fmuv5x. 
Mavlink on UART works again. Fmu is detected and loaded. Mavlink console works from QCG.
Mavlink on UDP still works. 
Nsh on Telnet works aswell.

**Comment by dagar** [comment]
Thanks everyone. This one should probably be cherry-picked for v1.10 as well.

**Comment by dagar** [comment]
Going into v1.10 - #13301

**Pull request merged**
