### PR TITLE
aerofc: Correctly enable UART driver for UART5(Telemetry port)

### PR DESCRIPTION
**Pull request by zehortigoza**
UART4 and UART5 are not USART instances.

### CODE REVIEW

**Comment by davids5** [comment]
Please do not hand edit defconfig. 

Use ```make oldconfig``` and ```make menuconfig``` to change the defconfig.

The procedure is convoluted at best.

```
make aerofc-v1_default
cd build_aerofc-v1/aerofc-v1/Nuttx/nuttx
make oldconfig
cp .config nuttx-configs/aerofc-v1/nsh/defconfig
```

edit and revert the  changes to to Just these 2 sections
```
#
# Board Selection
#
CONFIG_ARCH_BOARD_AEROFC_V1=y
CONFIG_ARCH_BOARD="aerofc-v1"

#
# Custom Board Configuration
#
CONFIG_BOARD_CRASHDUMP=y
CONFIG_BOARD_RESET_ON_CRASH=y
# CONFIG_BOARD_CUSTOM_LEDS is not set
# CONFIG_BOARD_CUSTOM_BUTTONS is not set
CONFIG_BOARD_HAS_PROBES=y
# CONFIG_BOARD_USE_PROBES is not set
```

then repeat the sequence but run menuconfig

```
make aerofc-v1_default
cd build_aerofc-v1/aerofc-v1/Nuttx/nuttx
make menuconfig
cp .config nuttx-configs/aerofc-v1/nsh/defconfig
```

Again edit and revert the changes to to Just the 2 sections above.

**Comment by lucasdemarchi** [comment]
@davids5 thanks for sharing this. I think this should be documented somewhere or we need to improve/fix/automate the reconfigure steps.

Back to the subject of this patch, I think it should be merged as is because doing what you suggested has this same change (together with a bunch of others that need to be reviewed... In another PR)

**Comment by davids5** [comment]
@lucasdemarchi - When I do uptakes from upstream Nuttx - I do this for all the targets.  I grepped the code base and only the aerofc-v1 had this errant define.  

Once you get a clean CI we can merge it.

**Comment by davids5** [comment]
Jenkins Test this please

**Comment by LorenzMeier** [comment]
Circle is flaky - this looks ok.

**Pull request merged**
