### PR TITLE
Upload latest master, beta and stable builds to AWS

### PR DESCRIPTION
**Pull request by dagar**
I removed the other s3 artifacts upload assuming you don't also want to keep every Firmware.zip on s3.

I uploaded some unnecessary files when attempting to use the travis builtin s3 upload. You could probably delete everything in the bucket at this point and travis will repopulate.

### CODE REVIEW

**Comment by dagar** [comment]
Fixed CI-Tools/s3cmd-put so it only uploads if not a pull request.

**Comment by dagar** [comment]
hmm the dynamically generated s3 directory index isn't quite right.
http://px4-travis.s3.amazonaws.com/master/index.html

**Comment by LorenzMeier** [comment]
In fact we do want artifacts for most builds so our testers can download straight from Travis and don't need the tool chain installed.

**Comment by LorenzMeier** [comment]
I think I'm missing partially context here - the overall state / uploaded material looks good (I cleaned up a bit). I presume we can exchange the flow badge here soon too and call the job done?
http://px4-travis.s3.amazonaws.com/index.html

**Comment by dagar** [comment]
Sorry, that was not very clear. I was referring to the existing travis addon called artifacts which was already uploading Firmware.zip. https://github.com/PX4/Firmware/blob/master/.travis.yml#L81-L82

One last change to put things in project folders (so we can add px4flow alongside) and this should be good to go.

**Comment by LorenzMeier** [comment]
Awesome, merging!

**Pull request merged**
