### PR TITLE
[WIP] initial SSD1306 OLED display driver

### PR DESCRIPTION
**Pull request by dagar**
Not functional yet.

https://github.com/PX4/Firmware/issues/6231

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Cool!

**Comment by tubeme** [comment]
Waiting... I prepared 2.4 inch one for tests...

**Comment by dagar** [comment]
Which screen size is everyone interested in? The driver either needs to be geared towards a particular model, or the dimensions need to be parameterized.

**Comment by tubeme** [comment]
The size does not matter in 1306 because all of them are 128x64. Mine just shows bigger letters and graphs then let say 0.96". For me 0.96" is unreadable because since 2 years I wear glasses for reading :) ithout them the 0.96' looks like noise haha.

**Comment by edsellar** [comment]
I have both sizes in front of me and while the 2.4" is definitely bigger, I'm trying to think of where the larger one could be put on my multi or plane without being in the way. Can have almost 2 of the smaller screens. Looking at this to make sure things are kosher preflight etc is likely the intended use and the ~1" screen I can squeeze into a lot of places. I would think more people would want to not take up too much real-estate. Just my 2¢ but in the case that the driver is independent of screen size then that is good, I still think 1" is more "manageable" but I understand the small text concern.

**Comment by tubeme** [comment]
@edsellar  My point was that the size does NOT concern the driver work, because all of these displays are the same resolution 128x64 dots. There are 0.96", 1.3" and 2.4" for now and all of them show exactly the same graphics and text, just with a different physical size. If you put a 2.4" on a larger plane (3+ meters wingspan) there is plenty of space to fit them somewhere. I agree with the small planes and MCs you could use 0.96"

**Comment by edsellar** [comment]
@tubeme that’s great then! If driver work is completely agnostic of true board size due to same resolution then given we aren’t using these for their beauty capabilities, it’s win win. I’m looking forward to it and will def put the smaller in multi and larger anywhere I can fit.

**Comment by ryanjAA** [comment]
Just built and tried. I2c conflict. 0x78 says connected when not. Will need to change solder pad to 7A on physical board or locate conflict and reassess.

**Comment by ryanjAA** [comment]
Changed address to 0x7A on both physical unit and driver and rebuilt. No text/non-operational.

**Comment by ryanjAA** [comment]
Needs added library for pixel to character. Currently init is functional and will drawn line (thanks to @dagar).

**Comment by dagar** [comment]
Rebased on master.

**Comment by mijarck** [comment]
No support for this in visible future?

**Comment by dagar** [comment]
@mijarck the basic driver works for drawing pixels and lines to the screen. It's need a small library for handling characters (fonts, etc).

**Comment by mijarck** [comment]
Ok, good to know. Was just interested to know about the support on PX4 if could get battery and pre-arm state easily visible, but there’s other ways to solve the issue too.

**Comment by ryanjAA** [comment]
I’ve been wanting this for years. I think it’s a great idea to isolate yourself from needing a computer and have more info than the led or red button can provide. 

Sat info 
Armed status errors
Etc would be helpful for people. 

This is the cleanest solution I can see since reliance on a remote control is diminishing greatly.

**Comment by julianoes** [comment]
@dagar you should get your stuff in :smile:

**Comment by bys1123** [comment]
Any new update?

**Comment by Phillweston** [comment]
Any new update?

**Comment by ryanjAA** [comment]
Actually @AlexKlimaj did a driver for it but it needs backend or expansion done if you want it to work similar to how Ardupilot has it subscribing to data.

**Pull request closed without merging**
