### PR TITLE
Safety prearm

### PR DESCRIPTION
**Pull request by LorenzMeier**
@DonLakeFlyer This is for you to test!

@sjwilks @AndreasAntener This PR allows you to unlock the gimbal with the safety switch, while still clamping all outputs which have some throttle in their input to the disarmed value. Works also for fixed wing to operate the control surfaces without having to worry about throttle.

I have intensely bench tested this, so it should be good to go, just looking for user feedback.

### CODE REVIEW

**Comment by AndreasAntener** [comment]
Interesting, what happens if you have a motor connected to the wrong pin? e.g. one with a high PWM_MIN value?

**Comment by LorenzMeier** [comment]
Nothing changes with respect to the overall setup. The difference is just that non-motor outputs become active with the switch. Whatever you're implying is right now already an issue (or is not), and is completely unrelated.

**Comment by AndreasAntener** [comment]
Sure, but at the time when you arm with the RC you're already away from the vehicle and expect the motors to go on. But with this a motor connected to the elevon pin will turn on as soon as I disable safety?

**Comment by LorenzMeier** [comment]
I see what you're referring to. Yes, its a paradigm change for vehicle setup: You have to be ready for a motor to become active once disabling the safety if you plug things into the wrong channel. Since aileron channels default however to 1500, in most cases the ESC should be able to catch this.

**Comment by LorenzMeier** [comment]
I don't think that's an issue though, because our deployed user base is small and on the mailing list, and its the exactly the right time to do this before doing our first release. Other autopilots already do it this way, and so across the user base this is non-surprising for most.

**Comment by AndreasAntener** [comment]
Ok, maybe it's just because I'm used to the current state.

I think it's a convenient feature, we're always unmounting props and disconnecting motors for these kind of bench tests. However, even with this, should I stop doing that? :)

**Comment by severinleuenberger** [comment]
I would appteciate this enhancement very much. Sounds great. With fixed wing i can do  already a servo check and later arm the motor. On APM it is already like this since ever.

**Comment by AndreasAntener** [comment]
BTW, this is me being paranoid, I know as soon as I'm used to it, I won't disconnect the motors anymore and be happy. Maybe still remove the props ;)

**Comment by LorenzMeier** [comment]
As much testing on this on real airframes as possible would be great. Too many great new features are blocked on integration testing 8).

**Comment by DonLakeFlyer** [comment]
> @DonLakeFlyer This is for you to test!

Will do. Won't be able to today. try tomorrow.

**Comment by AndreasAntener** [comment]
Is something necessary to enable it? When I disable safety on my FX61 it doesn't arm the elevon pins, only after arming completely. Not sure where to start looking.

**Comment by DonLakeFlyer** [comment]
Finally had time to try this. When I hit the safety switch my servos max out in one direction forcing the surfaces to deflect fully in one direction. Then when I arm, the surfaces re-center. So not working correctly for me.

**Comment by LorenzMeier** [comment]
Closing and re-opening against beta.

**Pull request closed without merging**
