### PR TITLE
refactor ecl ekf analysis

### PR DESCRIPTION
**Pull request by JohannesBrand**
this pr refactors the ecl ekf analysis to achieve better extendability, maintainability, readability, and robustness. It also enables the analysis of logs with in-between landings (the current version only runs over the first flight phase for logs with in-between landings). 

Unfortunately the[0bfa8b88-93d6-40be-88d9-47c7f28841ee](https://logs.px4.io/plot_app?log=0bfa8b88-93d6-40be-88d9-47c7f28841ee) changes of this pr might be too big to review it on a change basis. I therefore tried to keep the output consistent with the current version to allow a side-by-side comparison of the outputs. The command line scripts can be used in the exact same way as before.

changes:

* run analyses and report generation separately
* split metrics, checks, plotting functions into separate files
* store the check description in a csv file
* add a class for handling in air detection and its edge cases
* set the value of non-executed checks to `nan` instead of `Pass`
* don't create an empty pdf file if the analyses throws an exception

Find a few comparisons here:

| log | description | old analysis output | new analysis output |
|----|----|----|----|
|0bfa8b88-93d6-40be-88d9-47c7f28841ee|random public log, 1 flight phase|mdat.csvpdf|mdat.csvpdf|
|03d2ecd9-9f8d-4a63-8a74-a0f20824db2d| random public log, 1 flight phase |mdat.csvpdf|mdat.csvpdf|
|25c37f03-8611-4026-bb3a-ae908b19fb71| log with multiple flight phases |mdat.csvpdf|mdat.csvpdf|

as wrike bot seems to have problems with links in tables, here are the links in a list:
- [log1](https://logs.px4.io/plot_app?log=0bfa8b88-93d6-40be-88d9-47c7f28841ee): [old.mdat.csv](https://github.com/PX4/Firmware/files/2844370/0bfa8b88-93d6-40be-88d9-47c7f28841ee_master.ulg.mdat.csv.pdf);[ old pdf](https://github.com/PX4/Firmware/files/2844377/0bfa8b88-93d6-40be-88d9-47c7f28841ee_master.ulg.pdf); [new mdat.csv](https://github.com/PX4/Firmware/files/2844383/0bfa8b88-93d6-40be-88d9-47c7f28841ee.ulg.mdat.csv.pdf); [new pdf](https://github.com/PX4/Firmware/files/2844386/0bfa8b88-93d6-40be-88d9-47c7f28841ee.ulg.pdf)
- [log2](https://logs.px4.io/plot_app?log=03d2ecd9-9f8d-4a63-8a74-a0f20824db2d): [old mdat.csv](https://github.com/PX4/Firmware/files/2844410/03d2ecd9-9f8d-4a63-8a74-a0f20824db2d_master.ulg.mdat.csv.pdf); [old pdf](https://github.com/PX4/Firmware/files/2844413/03d2ecd9-9f8d-4a63-8a74-a0f20824db2d_master.ulg.pdf); [new mdat.csv](https://github.com/PX4/Firmware/files/2844415/03d2ecd9-9f8d-4a63-8a74-a0f20824db2d.ulg.mdat.csv.pdf); [new pdf](https://github.com/PX4/Firmware/files/2844417/03d2ecd9-9f8d-4a63-8a74-a0f20824db2d.ulg.pdf)
- [multi-phase log](https://logs.px4.io/plot_app?log=25c37f03-8611-4026-bb3a-ae908b19fb71): [old mdat.csv](https://github.com/PX4/Firmware/files/2844444/25c37f03-8611-4026-bb3a-ae908b19fb71_master.ulg.mdat.pdf); [old pdf](https://github.com/PX4/Firmware/files/2844449/25c37f03-8611-4026-bb3a-ae908b19fb71_master.ulg.pdf); [new mdat.csv](https://github.com/PX4/Firmware/files/2844452/25c37f03-8611-4026-bb3a-ae908b19fb71.ulg.mdat.pdf); [new pdf](https://github.com/PX4/Firmware/files/2844454/25c37f03-8611-4026-bb3a-ae908b19fb71.ulg.pdf)

The results of the log files with only a single flight phase are the same except for some small numerical differences (due to different airtime handling). For the multi-phase flight the old analyses only considers the first phase.

### CODE REVIEW

**Comment by dagar** [comment]
Take a look at the CI failures, they're from running Tools/ecl_ekf/process_logdata_ekf.py.

**Comment by JohannesBrand** [comment]
@dagar do you know which python version runs on the ci-server? 

code coverage complains about the type hints which exist since python 3.5: [https://www.python.org/dev/peps/pep-0484/#id11](https://www.python.org/dev/peps/pep-0484/#id11)

ubuntu 16.04. includes python 2.7 as well as python 3.5 by default.

**Comment by dagar** [comment]
From the CI output we can see they're currently using the container `px4io/px4-dev-ros-kinetic:2018-09-11`.
image

Running it locally.

``` bash
 % docker run -it px4io/px4-dev-ros-kinetic:2018-09-11 /bin/bash
Starting with UID : 9001
user@9de10fff1bad:/$ lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
user@9de10fff1bad:/$ python --version
Python 2.7.12
user@9de10fff1bad:/$ python3 --version
Python 3.5.2

```

Ubuntu : 16.04
python : Python 2.7.12
python3 : Python 3.5.2

Sounds like explicitly calling python3 should be sufficient?

**Comment by dagar** [comment]
You should also add something in the script itself to assert the required python version.

**Comment by dagar** [comment]
@JohannesBrand it looks like we'll need to get the pyulog dependency installed for python3.

**Comment by JohannesBrand** [comment]
> You should also add something in the script itself to assert the required python version.

@dagar thanks, I forgot that. I added a python interpreter line to all the scripts. If `process_logdata_ekf.py` is executed directly it should now choose the correct python interpreter. 

> @JohannesBrand it looks like we'll need to get the pyulog dependency installed for python3.

OK, I think we need to install pip3 using `sudo apt install python3-pip` and call `pip3 install ...` instead of `pip install ...` Alternatively, I can try to convert it to python 2 code. Apparently there is also [static type checking for python 2](https://mypy.readthedocs.io/en/latest/python2.html#type-checking-python-2-code). I would prefer if we can switch to python 3, since all my code is python 3. I guess I cannot just change python 2 to python 3 here: [dockerfile](https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_ros-kinetic), right? Probably it would break other stuff?

**Comment by dagar** [comment]
Yes you can try changing it here. https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_ros-kinetic#L41

What I'm not sure of is if we can get away with mostly python3 or if we need both.

**Comment by JohannesBrand** [comment]
@dagar thank you. I created this pr in containers: [#177](https://github.com/PX4/containers/pull/177)

**Comment by lamping7** [comment]
> What I'm not sure of is if we can get away with mostly python3 or if we need both.

We need both. The ROS side is python 2.7 which is required for the testing we do with rostest.

**Comment by JohannesBrand** [comment]
> > What I'm not sure of is if we can get away with mostly python3 or if we need both.
> 
> We need both. The ROS side is python 2.7 which is required for the testing we do with rostest.

@lamping7 since the official support for python 2.7 will drop by the end of the year: ([pythonclock](https://pythonclock.org/)), would it be possible to get rostest to python 3, as well?

**Comment by lamping7** [comment]
Yeah. I wrote that before I looked real hard. Then commented on your other pr. It would work, just needs played with.

**Comment by dagar** [comment]
Try updating the container tag to 2019-02-13. This likely won't be available on docker hub for at least a few hours. The automated builds there are incredibly slow.

https://cloud.docker.com/u/px4io/repository/docker/px4io/px4-dev-ros-kinetic/tags

**Comment by JohannesBrand** [comment]
@dagar  ok, thanks. I only updated the tags for `px4-dev-ros-kinetic`.

**Comment by JohannesBrand** [comment]
@dagar  I still had to make a small code change since I was using a python 3.6 feature, now I'm still missing `matplotlib` in the container. Unfortunately, I missed this dependency as it was part of `px4-tools`, sorry. I opened a new pr for containers ([#178](https://github.com/PX4/containers/pull/178)) and I tested that this pr now runs in the docker container.

**Comment by dagar** [comment]
No problem, https://github.com/PX4/containers/pull/178 has been merged and I've pushed a new `2019-02-14` tag. https://cloud.docker.com/u/px4io/repository/docker/px4io/px4-dev-ros-kinetic/timeline

We should capture all of these python requirements here 
 - https://github.com/PX4/Firmware/blob/master/Tools/setup/requirements.txt
Eventually I'd like to get the containers and dev guide using that directly.

**Comment by JohannesBrand** [comment]
thanks.

**Comment by JohannesBrand** [comment]
**Summary:**
additionally, to the changes mentioned in the original pull request [description](https://github.com/PX4/Firmware/pull/11412#issue-251403010), this pr migrates the ecl-ekf analysis to python 3 which required updating the `px4-dev-ros-kinetic` container in pull requests [#177](https://github.com/PX4/containers/pull/177) and [#178](https://github.com/PX4/containers/pull/178): 

all changes:
* run analyses and report generation separately
* split metrics, checks, plotting functions into separate files
* store the check description in a csv file
* add a class for handling in air detection and its edge cases
* set the value of non-executed checks to `nan` instead of `Pass`
* don't create an empty pdf file if the analyses throws an exception
* migrate ecl-ekf analysis to python 3: PX4 container pull requests [#177](https://github.com/PX4/containers/pull/177) and [#178](https://github.com/PX4/containers/pull/178)

**Pull request merged**
