### PR TITLE
smbus: updates from Solo development

### PR DESCRIPTION
**Pull request by tridge**
work done by Sid, this is just to upstream it

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This seems to overwrite contributions that have been made in the meantime here by FotoKite - are there any actual improvements here?

**Comment by tridge** [comment]
I will ask Sid to have a look. I haven't worked on this driver myself, I was just upstreaming.
Sorry for not noticing the updates that have already been done, they really are quite obvious now you point it out

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by LorenzMeier** [comment]
Overall the commit proves to just undo the improvements done here, so I manually picked the 5 lines that actually improved things in 034bbdf. Thanks!

**Pull request closed without merging**
