### PR TITLE
Fix for HobbyKing boards.

### LINKED ISSUE #8477: Upgrade Failure v1.7.0 Stable Release
Upgrade failed following procedure for v1.7.0 stable release firmware. The video was made recreating the issue by reverting back  to v1.6.3. I have been able to successfully revert back to v1.6.5 Stable since the video. Video of the failure is below. Timeline description as follows:

0:25 Shows COM Port recognized in Windows 8.1 Pro prior to upgrade
0:46 Firmware version
0:56 Start of upgrade
1:15 Clipped to shorten video right before it says Upgrade Complete
1:34 Device Manager keeps blinking for PX4 FMU COM Port because it just connects then immediately disconnects and just stuck in this loop. The usual tones indicating upgrade is completing doesn't happen.
1:56 Closed QGC and unplugged USB cable to restart it to let it boot completely, per popup message.
1:56 Plugged in USB but COM Port still stuck in loop.
2:28 Zoomed in on Pixhawk to show all the lights blinking. Noting right B/E blinking rapid Red and left constant Red; ACT blinking Blue.

https://youtu.be/3AwHMFB3_TM

### PR DESCRIPTION
**Pull request by dagar**
Users with Hobbyking boards are getting stuck in bootloops when upgrading to v1.7.0.

@jgoppert seems to already have a fix (quickly verified by @nkhoit). Could you explain the issue?

~~Possible fix for https://github.com/PX4/Firmware/issues/8477.~~
Fixes #8477

### CODE REVIEW

**Comment by dagar** [comment]
@rollysing could you please try this binary? http://ci.px4.io:8080/job/Firmware/job/hk_fix/2/artifact/build/px4fmu-v2_default/px4fmu-v2_default.px4

It resolved the bootloop for @nkhoit's Holybro pixhawk.

**Comment by dagar** [comment]
How do we make this safe for regular boards?

**Comment by rollysing** [comment]
Yes, that worked! Thanks.

**Comment by whyscience** [comment]
also refer to https://github.com/PX4/Firmware/issues/7857

**Comment by dagar** [comment]
@whyscience the commit is causing problems on the pixhawk mini, and I'm not sure how to reconcile the differences. Are you available on slack or skype to discuss? I don't have one of the affected Holybro boards to test.

**Comment by whyscience** [comment]
I'm available on slack. I have a Holybro board, I will test it when I'm back home.

**Pull request merged**
