### PR TITLE
MOCAP support on firmware [new PR]

### PR DESCRIPTION
**Pull request by TSC21**
This is a new PR, given I screwed https://github.com/PX4/Firmware/pull/2317. Please, test this one now, as it also doesn't have the problem regarding the `uavcan` submodule version. (sorry for the previous messy stuff)

### CODE REVIEW

**Comment by moskytoo** [comment]
Today I built and uploaded the mocap_support_restruct Firmware. I use Telemetry2 to send att_pos_mocap MavLink messages and USB for connecting it with QGroundControl to check the state of the autopilot.
It somehow receives the mocap messages, but the result doesn't make a lot of sense.
1. I get [inav] MOCAP data valid, 0.5 s later: [inav] MOCAP timeout, 5 s later again MOCAP data valid and so on
I send a new MavLink message every 0.02 - 0.025 s
2. The movement of the autopilot shown in QGroundControl doesn't represent the data I send.

Both could be problems of my code. Tomorrow I need to check the incoming MavLink messages at the Pixhawk, so I can assure that the data I send is correct.

**Comment by LorenzMeier** [comment]
Over which data rate are you sending? I'm just asking because dropouts could also be a result of overloading the communication link (the link, not Pixhawk).

**Comment by moskytoo** [comment]
I would say I send at 40 Hz to 50 Hz.
What data rate would you recommend?

**Comment by TSC21** [comment]
As @LorenzMeier said, dropouts may be the result of the rate mocap messages are being streamed. Sending your messages at 50hz doesn't mean that the data rate of the link is able to send data at maximum rate.

**Comment by TSC21** [comment]
What messages are you streaming/receiving in the serial bus?

**Comment by moskytoo** [comment]
I just send the MavLink mocap data.
Via USB I've connected with QGroundControl to check the status of the autopilot.

**Comment by moskytoo** [comment]
I changed the rate to 10 Hz, the timeouts still happen, although at longer intervalls.
0.5 s between data valid -> timeout
25 s between timeout -> data valid

**Comment by moskytoo** [comment]
Apparently a lot of data is coming throught the serial port (Telem 2), even when I'm not sending any data. Is PX4 sending all this? Could it be that it's blocking the mocap messages?

Sorry for my PX4-illiteracy.

**Comment by LorenzMeier** [comment]
Depending on the serial link, yes. You will need to provide more info on the type of hardware you're using. Also most telemetry links don't really work - here is what we're using at ETH:
https://pixhawk.org/peripherals/radio-modems/start#lairdtech_proprietary

**Comment by moskytoo** [comment]
I just said Telem2 because I'm using the Telem2 connector of the PixHawk, I don't use actual telemetry.

On my companion computer-side I use a basic FTDI-USB converter: http://www.digchip.com/datasheets/5500508-umft234xd-nc-brd-brkout-usb-ft234xd.html

I build the cable like it is explained here: https://pixhawk.org/dev/companion_link#building_the_cable

**Comment by moskytoo** [comment]
Where on the PX4 I can make sure that I have a uni-directional connection?
A uni-directional connection is good for testing, but for future use-cases it probably also should work on a bi-directional connection.

**Comment by LorenzMeier** [comment]
There is no way it will influence a Linux companion system just by sending data. It would only interfere if you send things straight off radio. Your interface issue must be somewhere else. Are you using hardware flow control? If not, adding it might help.

Also make sure to set the baud rate to 921600.

Please also try current master and make sure to rebuild NuttX. We have improved the serial RX recently. So to recap:

- Set the baud rate to 921600 on both ends
- Update from master and run make archives and rebuild the firmware

You will need to do both.

-Lorenz

**Comment by moskytoo** [comment]
Hardware flow control like in using the CTS/RTS connectors? I do that.
I already set the baud rate.
@TSC21: can you merge the new master into your mocap_support_restruct branch? So that I can update and rebuild the firmware on my board?

**Comment by TSC21** [comment]
Done ;) And you're welcome!

**Comment by moskytoo** [comment]
Built and uploaded the new firmware. No success.
I also tried with a second PixHawk (HW-wise), same problem.

**Comment by moskytoo** [comment]
What I'm at: I checked my FTDI connector and some other stuff and I'm pretty sure that the source for the dropout problem is somewhere at the PixHawk.
This afternoon I will have a closer look at the code and hopefully can narrow down the possible source of the problem.

**Comment by TSC21** [comment]
The current mocap implementation is almost the same as the vision support on firmware, unless something escaped from me. As vision is working in most projects out there, supposedly the mocap addiction should also work. More feedback from other users will help disguise if the problem is in the firmware or project-related.

**Comment by moskytoo** [comment]
Somehow my PixHawk only reads my mavlink messages if they have a certain sequence number, it's probably somewhere in my code.

About the Mocap integration: Nuno, like you mentioned, it's mostly code from the vision position estimate. In the vision support the component ID is used to identify the vision sensor (which is probably part of the UAV). In the present mocap implementation it also says: *"Use the component ID to indentify the mocap system"*. To my understanding (I see mocap system as in Vicon) the mocap system isn't a component of the UAV, it's more like the enviroment and in most applications only one mocap system exists. My point is that component ID is perhabs a little bit misleading in this context.
In the end it probably doesn't really matter and after I wrote this down it seems quite unimportant, but I still want to share this thought.

**Comment by TSC21** [comment]
> My point is that component ID is perhabs a little bit misleading in this context.

You are probably right but in this context, it doesn't really matter. Although is not onboard the vehicle, is an estimator sensor after all, so I don't see any relevant problem that this can cause.

> Somehow my PixHawk only reads my mavlink messages if they have a certain sequence number, it's probably somewhere in my code.

Please check. You can also quickly try our implementation on mavros and see if the problem is caused by your code of if it is something firmware related (if you have some time bandwidth off course, since I'm aware you are not supposed to use ROS; this is just to troubleshoot the problem).

**Comment by moskytoo** [comment]
It was my code, I chopped the original mavlink code appart in pieces and wanted to use only "what I really need". Most stupid idea ever and now I implemented the mavlink library properly and in works (with test data).
Next I'll test it in the real Vicon enviroment.

One question: For NED, does it matter that the x-axis (North) is allignent with the real north?
At the moment I just make a coordinate transformation that the z axis is down.

**Comment by TSC21** [comment]
> One question: For NED, does it matter that the x-axis (North) is allignent with the real north?
At the moment I just make a coordinate transformation that the z axis is down.

Please check this transformations: https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/mocap_pose_estimate.cpp#L92-L102

**Comment by moskytoo** [comment]
ok, I did some small tests with an object in the vicon enviroment and the data (x, y, z, vx, vy, vz, yaw) looks good in general. At the moment I only see two problems:
1. When the vicon system sends empty data (PX4 receives a signal, but only (0,0,0) in position and (1,0,0,0) as quaternion, happens for example when the UAV flies in a blind spot of the cameras), there are jumps in the data when vicon sees the object again.
2. When the PX4 receives empty data  for a longer time, it has a big drift in the altitude somehow. (since I started to write this the my PixHawk thinks right now that he is at 50,000 m)

Tomorrow I will make some logs, which I can upload. Do I need to consider something special for these logs?
Keep in mind that I don't have a flying copter yet, but I can upload logs from vicon and from qgroundcontrol, while moving the object around.

**Comment by TSC21** [comment]
Your logs are welcomed @moskytoo! Thanks for the feedback. We will help you debug those. But seems like a normal behavior from the estimator itself.

**Comment by TSC21** [comment]
@moskytoo BTW, what conversions are you using right now? You have coordinates in which convention and how are you treating the conversions to NED?

**Comment by moskytoo** [comment]
I wrote my own application which receives the Vicon Data Stream and sends the Mavlink messages. I'll upload it to a new repo for it tomorrow.

**Comment by moskytoo** [comment]
Here is the piece of software I'm using to send out the att_pos_mocap messages:
https://github.com/moskytoo/vicon2mav_mocap
You'll find my coordinate transformation in *coordinateTrans_ViconToNED* in functions.h

I send the messages via TCP to an instance of ser2net which sends it via Serial to my PixHawk.

I'll add some documentation when I have to do this anyway for my project (~2 month or earlyer).

**Comment by LorenzMeier** [comment]
Is this PR flight-tested?

**Comment by congleetea** [comment]
when I use optitrack, there is a step to set the ground plane. whether the x axis must points to east? or i can determine it based my environment.

**Comment by TSC21** [comment]
@LorenzMeier, as you can read above, it is tested but not in flight.

@moskytoo, thanks for sharing. About your tests:
1. What kind of jumps are you referring to?
2. Try to set baro weight to 0 (https://github.com/PX4/Firmware/blob/master/src/modules/position_estimator_inav/position_estimator_inav_params.c#L53); you can do it by updating the parameter on QGC or using nsh command: param set INAV_W_Z_BARO 0. The estimator will always try to estimate the height based on the last measurements and based on the weight given to each sensor data. So I believe this is a normal behavior.

**Comment by moskytoo** [comment]
@congleetea I've never used optitrack, so I don't know any details. I have an application on an extra PC which receives the data from the motion capture system and sends out the MavLink messages. This application also handles the needed coordinate transformations. If that was your question?

**Comment by moskytoo** [comment]
@TSC21 I had some unforseen obligations today and this weekend I won't be online. I need to postpone the upload of my logs to monday. =/

**Comment by congleetea** [comment]
@TSC21 I checked  https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/mocap_pose_estimate.cpp#L92-L102
it is not right.it is not the ENU TO NED. and the mav fly confusedly.

**Comment by congleetea** [comment]
@moskytoo  if the mav can not receive the vicon data or vision data indoor, the z value of mav indeed has a big drift. I think it will use other sensor like baro. so the change is very big.

**Comment by TSC21** [comment]
@moskytoo no problem. We will be waiting for your logs then.

@congleetea the code you are pointing in as suffered a modification in a last PR so we could test if it could work on both body and world frames. Pointing out that it's not right and saying that it flyed confusedly doesn't help to figure out what as to be changed or what is wrong. So please:
* Explain how is system configured and how's your app->mavros->fcu is being done
* Share you flight logs through log munchen or print screen them in flightplot
* Purpose a modification in the current mocap plugin code based on the current behavior of your vehicle. Keep in mind that the previous code of the plugin was something like this:
```c++
		float q[4];
		q[0] =  pose->pose.orientation.y;	// w
		q[1] =  pose->pose.orientation.x;	// x
		q[2] = -pose->pose.orientation.z;	// y
		q[3] =  pose->pose.orientation.w;	// z
		// Convert to mavlink body frame
		mocap_pose_send(pose->header.stamp.toNSec() / 1000,
				q,
				pose->pose.position.y, // this was changed to pose->pose.position.x
				pose->pose.position.x, // this was changed to -pose->pose.position.y
				-pose->pose.position.z);
```
So maybe your first try can be applying the upward modification (if the problem is not related to something else ofcourse).

Relatively to the Z offset, as I said in a previous comment, try to set baro weight to 0 (https://github.com/PX4/Firmware/blob/master/src/modules/position_estimator_inav/position_estimator_inav_params.c#L53); you can do it by updating the parameter on QGC or using nsh command: `param set INAV_W_Z_BARO 0`. The estimator will always try to estimate the height based on the last measurements and based on the weight given to each sensor data.

**Comment by TSC21** [comment]
@blackcoder your tests and experiences can become handy here too so we can evaluate the present conversions on mavros code. And also to test the data fusion on the firmware, which is the purpose of this PR.

**Comment by TSC21** [comment]
Note: All of you probably are aware of this but you have to send the coordinates in ROS body/world ENU to the plugins so they can convert them to FCU body/world NED.

**Comment by blackcoder** [comment]
@TSC21 I tested your branch. 
I am sending ENU position to mocap (I am calibrating my tracking system so that N is actually the global earth magnetic north).

I am pointing my quad to North, and running mocap/mavros . The result is somehow weird, the output as observed through QGC points to an angle around 150 degrees (between S and E), totally not expected.

Doing the same, but using vision_estimate plugin I observe an orientation pointing to West (CCW +90). 

I tried to remove the transpose from attitude_estimate_ekf as suggested earlier, and the orientation ends up East (CC +90)

I overcome this at the moment by either:
  - Correct the offset and send it to mavros/vision_estimate
  - Modify the attitude_estimate_ekf to only use magnetometer 
```
z_k[6] = raw.magnetometer_ga[0]; 
z_k[7] = raw.magnetometer_ga[1]; 
z_k[8] = raw.magnetometer_ga[2];
```
For reference, this is the mapping/transformation we are using:

lab_mapping

**Comment by TSC21** [comment]
@all please, if you may, share the flight test results using the following guide: https://pixhawk.org/flying/flight_reports.
A video is also welcomed :)

**Comment by TSC21** [comment]
Guys, FYI I updated the log structure in the latest commit. Can be useful if you want to check `inav.log` log file on your sd.

**Comment by moskytoo** [comment]
So I got finally some presentable logs.
Important to note: These are **no** flight logs! The PixHawk lay on my desk and I moved an object around the vicon enviroment manually to get this data. They are also not made according to the standart log procedure, because I couldn't figure out how to start sdlog2 without arming the copter.

**What these logs are:** I logged what the Vicon system sends as position (x,y,z) and attitude (yaw) and compared it to what PX4 thinks where it is. I logged the position data of the PixHawk via QGroundControl.
Because the PixHawk just lay on the desk and "felt" no movement proper flight tests will be necessary to confirm or disprove what I've meassured yet. I will do this sometime next month.

**About the data:**
_22_log1: This shows really good what happens, when Vicon sends no valid data anymore. I don't know whether this behaviour is wanted.
(here the position jumps to some random position, it would be at (0,0,0) now if I run the test again)
_22_log2: Here is the emphasis on the height-data (z). I set the baro weight 0 for all tests ([here](https://github.com/PX4/Firmware/blob/master/src/modules/position_estimator_inav/position_estimator_inav_params.c#L53))
_22_log4: After Vicon doesn't send any valid data anymore the velocity of the PixHawk reaches more than 35 m/s for a moment.
_24_log3: If the Vicon data stays valid, position data of the Vicon system and the PX4 are pretty close together.

The other logs show pretty much the same.
I guess it doesn't make much sense to discuss the yaw data yet, when the PixHawk itself isn't moving while testing.
All tests where done with X aligned to North, apart from _24_log4 and _24_log5: here X was aligned to the Vicon coordinate system.

I do my tests inside with steel tubes in the ground and everything, so I think that the compass doesn't give any valid information. Do I also need to set its weight to 0?

Some last words:
I know this data is not enough as a real test for the source code, but because I haven't seen any other data yet I wanted to upload this.

https://www.dropbox.com/sh/332jnxojyix4rzf/AADFZ6zlfRUrmRHpQakQH3vqa?dl=0

**Comment by TSC21** [comment]
@moskytoo many thanks for your logs. Some comments:
* I'm not able to check that behavior on _22_log1. Are you sure we are talking about the same log?
* about baro and Z data: try to lower it to above 0.05, instead of 0, as it can lead some strange behaviors at 0 when no other positioning is available, as far as I can tell
* if no other valid positioning system is available, is pretty normal that the estimator will try to compute the position and velocity with the data that it has available at the moment, which is the acc/gyro. As we all know, inav can lead to accumulated errors
* you don't have to lower the compass weight cause `attitude_estimator_ekf` uses one yaw data at a time: it uses mocap data if available, if not it uses vision, if not it uses the compass.

So, as far as I can tell, the shown logs are the expected behavior of the system. We still have to check the first behavior you are talking about.

@LorenzMeier do you have some comments on these? Thanks!

**Comment by blackcoder** [comment]
@TSC21  and myself been working on getting to the end of this issue and I think we finally  have a solution. 
using the mocap_support_restruct and modification of the mocap mavros plugin I was able today to perform a position hold. 

The modifications applied to mavros mocap plugin :
```
	    double roll = M_PI, pitch = 0.0 , yaw = 0.0f; 
	    tf::Quaternion qo; 
	    quaternionMsgToTF(pose->pose.orientation,qo); 
	    tf::Quaternion qr = tf::createQuaternionFromRPY(roll, pitch, yaw); 
	    tf::Quaternion qt = qo * qr; 
	    float q[4]; 
	    
	    q[0] = qt.w(); // w 
	    q[1] = qt.x(); // x 
	    q[2] = qt.y(); // y 
	    q[3] = qt.z(); // z 

	    // Convert to mavlink body frame 
	    mocap_pose_send(pose->header.stamp.toNSec() / 1000, 
			    q, 
			    pose->pose.position.x, 
			    -pose->pose.position.y, 
			    -pose->pose.position.z);
```

Log 1 : http://dash.oznet.ch/view/342Azh7An6XNTJyj8AQCXh
Log 2 : http://dash.oznet.ch/view/Qs28d4xmFPddu2CqcgP3Xb

mocap1

**Comment by moskytoo** [comment]
@TSC21 I meant the spikes in the velocity and the leveling off of the position. But I think I found an improvement which should reduce this effect.
To this point Vicon sent a constant stream of Position data, even when the data was not valid. But PX4 could not detect wether the data by Vicon was valid or not, because it still received data. I changed that: My application won't send any data anymore if it's not valid.
I will test it as soon as I have moved all my software from my Laptop to the companion computer.

**Comment by TSC21** [comment]
@blackcoder thanks once again for your feedback ;) I'll be adding the correction to the conversions in all mavros plugins now that we confirmed that this works.

@moskytoo `position_estimator_inav` doesn't have fault detection and doesn't filter the data values it receives, it just tries to correct them, and that's why you see those overshoots. You can always try to add the fault detection on firmware code, which would be a good addiction to all. Or, you can always filter your data before sending it to mavros plugin (not just "not sending it", but apply a LP filter for example, which is somehow what inav does, but then you would have double filtering, which would be much more accurate but you will have a reduction on performance).

@moskytoo if you could please add some more test results (like doing some flightests) and add some plots as @blackcoder did, I think we then can consider this mergeble, considering you get acceptable results as Tarek did.

@congleetea confirming this also works with Optitrack would be a good confirmation of code functionality.

Once again, thank to you all ;)

**Comment by congleetea** [comment]
I test the firmware using optitrack today, I want the mav to stop in point (0.01, -0.02, -0.5 ) in NED frame. the conversion of frame is 
	void mocap_pose_cb(const geometry_msgs::PoseStamped::ConstPtr &pose)
	{
		float q[4];
		q[0] =  pose->pose.orientation.w;	// w
		q[1] =  pose->pose.orientation.x;	// x
		q[2] = -pose->pose.orientation.y;	// y
		q[3] = -pose->pose.orientation.z;	// z
		// Convert to mavlink body frame
		mocap_pose_send(pose->header.stamp.toNSec() / 1000,
				q,
				pose->pose.position.x,
				-pose->pose.position.y,
				-pose->pose.position.z);
	}
however the mav can not fly normally but be horrific to fly at random.


the px4log file in this link https://drive.google.com/file/d/0B6s1E1cM5KYraEpNUXJreXdJZHc/view?usp=sharing

I check the conversion in qgc before flying , it is right.  but I do not know the reason.

**Comment by TSC21** [comment]
@congleetea mavros was yesterday updated with the correct frame conversions in all plugins. Please pull latest master from it and test.

**Comment by congleetea** [comment]
why does the local_position plugin in latest mavros use the attitude of imu ? when the attitude converse to ENU, it should be same with mocap/pose, however in this plugin , the position xyz is same with mocap/pose, but the attitude quaternion is not. is this a error?

**Comment by TSC21** [comment]
@congleetea the used attitude is exactly the same for both. Also, local_position always piblished attitude from IMU so I don't understand your question.

**Comment by congleetea** [comment]
@TSC21 I means that the attitude of mav should be generated from imu and motion capture system, if we just use the attitude generated from imu, i.e the attitude tracked by motion capture system will not work for attitude of local_position/local . however using  this plugin , I find that the attitude published by local_position/local is not same with the attitude published by mocap/pose, and also not same with the display in QGC ATTITUDE.roll ,ATTITUDE.pitch ,ATTITUDE.yaw. however the attitude in mocap/pose is same with the attitude displayed in GQC. so , I think that the attitude in fcu is relative to mocap, but attitude in local_position/local is not relative to mocap.  btw, my x-axis points to NORTH.

**Comment by TSC21** [comment]
@congleetea,
> I means that the attitude of mav should be generated from imu and motion capture system, if we just use the attitude generated from imu, i.e the attitude tracked by motion capture system will not work for attitude of local_position/local,

You are certainly right. That's why mavros has this https://github.com/mavlink/mavros/blob/master/mavros/src/plugins/imu_pub.cpp#L189-L191. I thought you were saying that the attitude was comming from the `imu_plugin`, which is right, but no, orientation doesn't come from raw IMU, or even HighRes IMU, it comes from the Mavlink `ATTITUDE` or `ATTITUDE_QUATERNION` msg handling. So you should expect to receive the fused attitude estimation coming from the FCU on both mavros and QGC.

> however using this plugin , I find that the attitude published by local_position/local is not same with the attitude published by mocap/pose, and also not same with the display in QGC ATTITUDE.roll ,ATTITUDE.pitch ,ATTITUDE.yaw. however the attitude in mocap/pose is same with the attitude displayed in GQC. so , I think that the attitude in fcu is relative to mocap, but attitude in local_position/local is not relative to mocap.

I find myself with difficulties understanding your problem. Firstly, as I said, `local_position/local` gets the attitude from the `ATTITUDE` msg, which is the estimated attitude of the vehicle, a result of the onboard estimators, as `attitude_estimator_ekf` which is what you should be using on firmware, as it is the one that is receiving the mocap estimated yaw orientation and using it as the main source of yaw orientation. `loca_position/local` is a topic that advertises `geometry_msgs::PoseStamped` msgs which I also suppose you are debugging, or are you using the TF in conjunction with RVIZ to debug it. A rosbag is welcomed so to check the "problem", with mocap data and local_position local topics.

> however the attitude in mocap/pose is same with the attitude displayed in GQC

Didn't understand this. What `attitude displayed in GQC` displayed on QGC are you referring too? From `ATTITUDE` or from `ATT_POS_MOCAP` msg?

> I think that the attitude in fcu is relative to mocap, but attitude in local_position/local is not relative to mocap.

They suppose to be same so please send a rosbag or the same already exported to csv, and some images comparing GCS plot showing ATTITUDE.yaw msg vs the data coming from `local_position/local`.

**Comment by TSC21** [comment]
People using ROS should be aware of https://github.com/mavlink/mavros/commit/6628ce554e30049d00e2716a1a3029fbe9b3cf5f#commitcomment-11950271. New patch will come with quick fix ;)

**Comment by blackcoder** [comment]
My tests indicates that the firmware mocap support introduced by @TSC21 works as expected. I was able to fly and position hold. Once the mavros updated fix is released I will have another crack at it in simulation.

**Comment by TSC21** [comment]
Thanks for the feedback @blackcoder ;) if anyone else has feedback on this I appreciate it, so this can be safe to push to master.

**Comment by LorenzMeier** [comment]
Nice!

**Comment by LorenzMeier** [comment]
Kicking the CI systems again.

**Comment by TSC21** [comment]
Seems like we have CI approval :)

**Comment by mzahana** [comment]
Hi all,

I finished setting up my mocap system, Optitrack, and did the frame conversion and now getting NED position and orientation. This is all done in MATLAB. Now I am sending the quaternion and xyz using mocap_att_pos mavlink message, and I'd like to check that Pixhawk, running the latest px4 frimware, is receiving the correct data, and in adequate rate. How is this possible? Is there some logs that I can plot in the analysis tab of Qgroundcontrol?

My second concern, after successfully transmitting the mocap data to pixhawk, how can I use the position control mode to hold the quad in a particular position, what is the procedure?

Thanks

**Pull request merged**
