### PR TITLE
Restructure posix cmake configuration

### PR DESCRIPTION
**Pull request by eyeam3**
This builds on #6043, which unfortunately broke other posix builds. I added another ifelse and check if we build a SITL board. If this is the case, I execute the related cmake configuration with the changes made for the IDE.

I tested the build for Bebop2 and various SITL targets, which seemed to be working. I cannot verify if the IDE setup still works.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@dagar Any idea why status reporting on Semaphore and Circle is so unreliable?

**Comment by dagar** [comment]
No idea, I don't think we've changed anything. In what way is it
unreliable? Getting stuck in "hasn't completed yet", or something else?

Didn't you disable circle?

**Comment by LorenzMeier** [comment]
They are both sometimes obviously never pinging back Github:

screen shot 2016-12-13 at 20 16 39

**Comment by dagar** [comment]
Sorry for the build system nonsense everyone. I think we're good to go now.

**Pull request merged**
