### PR TITLE
Github Actions: Add jobs running in Ubuntu 20.04 Focal

### PR DESCRIPTION
**Pull request by TSC21**
Following the addition of Ubuntu Focal Docker container, it's time to start adding a CI pipeline that may run over it as well.

### CODE REVIEW

**Comment by MaEtUgR** [comment]
I think we could even add it and fix any possible but unlikely breakage along the way 👍

**Comment by TSC21** [comment]
Seems like we have a limitation in the matrix size - Github automatically cancels the rest of the jobs of the matrix. I guess it's reasonable to keep the Nuttx builds only in 18.04 for now, and gradually move some targets to 20.04.

**Comment by MaEtUgR** [comment]
Here are the container changes that go with this pr:
https://github.com/PX4/containers/pull/256
https://github.com/PX4/containers/pull/257
https://github.com/PX4/containers/pull/258
Could you please add them next time for completeness?

**Comment by TSC21** [comment]
> Here are the container changes that go with this pr:
> [PX4/containers#256](https://github.com/PX4/containers/pull/256)
> [PX4/containers#257](https://github.com/PX4/containers/pull/257)
> [PX4/containers#258](https://github.com/PX4/containers/pull/258)
> Could you please add them next time for completeness?

You mean referene them? That's fine.

**Comment by TSC21** [comment]
> Fine with me. But now we don't test 16.04 anymore, right? If so we should remove in the docs that it is supported. Otherwise, we should still keep one test.

Fair enough. I will add it to the SITL tests job matrix in a new PR.

**Comment by mrpollo** [comment]
@jinger26 this is worth sharing, we now support Ubuntu 20.04 (Focal) 🎉

**Comment by hamishwillee** [comment]
FYI, docs updated to reflect this: https://github.com/PX4/Devguide/pull/998

**Comment by TSC21** [comment]
> FYI, docs updated to reflect this: [PX4/Devguide#998](https://github.com/PX4/Devguide/pull/998)

Thank you @hamishwillee!

**Comment by MaEtUgR** [comment]
Just a note here as exciting as this might be Ubuntu 20.04 is not released yet but planned for April 23, 2020 so I'd be more careful with "supporting". We're using the beta/daily to do our testing.

**Comment by TSC21** [comment]
> Just a note here as exciting as this might be Ubuntu 20.04 is not released yet but planned for April 23, 2020 so I'd be more careful with "supporting". We're using the beta/daily to do our testing.

I would say that considering we are safely running in beta, we can say with 99% certainty this will run in the official release.

**Pull request merged**
