### PR TITLE
Clean up of app.h

### PR DESCRIPTION
**Pull request by CarloWood**
app.h, generated from app.h_in, has unnecessary code duplication
and isn't a header file (it defines globals, static functions
and doesn't have a header guard, moreover, it has a 'using namespace
std;'). Because of this, a real headerfile that declares the stuff
defined in apps.h was missing leading to even more code duplication:
scattered forward declarations in .cpp files and an often repeated
type of std::map&lt;std::string, px4_main_t&gt;.

This patch moves cmake/qurt/apps.h_in to src/platforms/apps.cpp.in
(with some changes) and removes cmake/posix/apps.h_in.
Then src/platforms/apps.cpp.in is split into src/platforms/apps.cpp.in
and src/platforms/apps.h.in, splitting declarations from definitions.

A typedef is defined for the map (apps_map_type).

The main difference between cmake/posix/apps.h_in and
cmake/qurt/apps.h_in was that the first defined a global 'apps',
while qurt stores the apps in QShell. I opted to get rid of
the global variable (which are in general evil for various reasons)
and used the API of cmake/qurt/apps.h_in where a provided 'apps'
map is initialized with a call to init_app_map. Thus removing
the existing code duplication.

### CODE REVIEW

**Comment by julianoes** [comment]
Unfortunately, this is going to conflict big time with #5162.

**Comment by CarloWood** [comment]
@julianoes After having looked quickly at #5162, I believe you mean in terms of merge collisions due to proximate changes, not because they overlap technically.

Since my commit is the smallest, it seems most logical if I'd do the merging; and that wouldn't be a problem if we actually USED merging... but since we use git rebase, the only way to do that is when I'd wait until your PR is in master... I'm not sure if I want to wait that long, cause I need some of the changes in here for fix_headers and am stalled again until it is accepted.

Perhaps this is a solution: 1) This pull request is merged into master. 2) I actually *merge* that into your branch and do a pull request for that. 3) you won't do a rebase anymore, but your branch will just be merged this time. Aka, using git as it is supposed to be used :p.

If that is not an acceptable option, then we can do this: 1) again, merge this into master (as I need it quick), 2) I rebase your whole branch on top of this, fixing the collisions... 3) you wait until that is done and then hard reset to the rebased branch that I'll push to my github (I expect to need 1 hour).

Thoughts?

**Comment by julianoes** [comment]
I would say you get this into master, and I understand that you don't want to wait foe my huge branch. I'll then rebase my branch on master again and resolve the stuff. I should get to it over the weekend.

**Comment by CarloWood** [comment]
I wanted to do a rebase myself, to see how hard it would be, but it turns out your pull request hasn't been rebased onto master for a long time; so when I try it I get many conflicts that have nothing to do with my commit :/. Could you first do a rebase onto the current master?

**Comment by CarloWood** [comment]
I just did a rebase to melt the three patches into one and force pushed this branch.

**Comment by julianoes** [comment]
I reviewed this, looks good. Thanks @CarloWood.

**Comment by julianoes** [comment]
@CarloWood I've already rebased #5162, it wasn't too bad :smile:.

**Comment by CarloWood** [comment]
Thanks!!

**Pull request merged**
