### PR TITLE
Onboard thermal calibrator improvements

### PR DESCRIPTION
**Pull request by priseborough**
**Adds the following**

Extend to Baro and Accel sensors.
Add parameter controlled option to start automatically at next boot
Add parameter control of target temperature delta

**TODO**

These are optional but nice to have:

Provide a % status report to the nsh console.
Adjust the rcS file to not start unnecessary programs if calibrating.
Terminate the calibration if the temperature stops rising for a period of TBD seconds.
Allow a falling temperature profile to be used by specifying a negative temperature delta.

**Testing**

It has been tested using the nsh interface as follows:

1) Loaded onto an old model Pixhawk board with all parameters set to default except frame type set to generic quadrotor.
2) Pixhawk placed in a freezer for 15min
3) Removed from freezer and located in a low humidity room temperature environment, FTDI serial cable connected to Serial 4 port, power applied and a nsh terminal connection established
4) Calibration initiated for the gyro 'send_event start_temp_gyro_cal'
5) Calibration initiated for the accel 'send_event start_temp_accel_cal'
6) Calibration initiated for the baro 'send_event start_temp_baro_cal'
7) Waited for all calibrations to complete which  takes approximately 5-10min to achieve the required 24 deg temp rise on all sensors, checked the nsh output. 
screen shot 2017-02-02 at 9 39 32 am
8) Re-powered the boardVerified that the TC_* thermal calibration parameters had been saved for all sensors and that the X0 coefficients for the baro and accel sensors were zero.
9) Performed a commander initiated gyro calibration 'commander calibrate gyro'
10) Performed a commander initiated 6-sided accel calibration 'commander calibrate accel'
11) Re-powered the board and verified that the TC_*_X0_* coefficients for the the accel and gyro had changed and that the TC_A*_SCL_* parameters for the accels had changed, were sensible values and matched the printed output from the accel cal.

The automatic start has also been tested.

### CODE REVIEW

**Comment by bkueng** [comment]
I refactored this to reduce code duplication (will need a second pass), and added progress output.

I haven't completely validated, but a basic test was successful.

@priseborough you added correction normalization at ref temp, but only for accel & baro. Was that deliberate?

**Comment by priseborough** [comment]
@bkueng Yes it was deliberate. When doing a calibration, the truth angular rate (ignoring earth spin) can be assumed to be zero, however the truth acceleration and pressure values are unknown due to uncertainties in IMU sensor alignment and ambient pressure.

A follow up legacy 6DoF accel calibration will still be required to set absolute value for offset and scale factor.

**Comment by priseborough** [comment]
It looks like the refactoring has broken it. 

When I try repeating yesterdays test  with SYS_CAL_GYRO, SYS_CAL_ACCEL and SYS_CAL_BARO all set to 1 on the Pixhawk board it stops increasing at around the same value (80 to 90%) for all sensors which is suspicious. I have repeated the same test on another board with the same result.

**Comment by LorenzMeier** [comment]
@bkueng Can you look into that today?

**Pull request merged**
