### PR TITLE
CI log upload

### PR DESCRIPTION
**Pull request by AndreasAntener**
@LorenzMeier @bkueng spamming Flight Review (new script called by Jenkins)
The links are now just printed in the console log. Could someone look into pushing those as comment on the PR?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@bkueng Can you by default hide the SITL logs (but allow to enable them with a check box or alike?) We probably also don't want to send notification emails for SITL logs.

Thanks! And thanks for building this awesome logger and awesome plotting. This is really very essential for PX4 and its ecosystem and a contribution not to be underestimated.

**Comment by AndreasAntener** [comment]
Jenkins test this please

**Comment by dagar** [comment]
@AndreasAntener there are some path and whitespace issues (spaces in variables) with upload_test_logs.bash on jenkins. For now I updated the execute shell section on jenkins to find all the ulg's and call the script directly. I also added the email address from the commit and basic description.

screenshot from 2016-12-13 00-46-15

Very cool to see output from these tests!

URL: http://logs.px4.io/plot_app?log=12f7e84e-a7a5-4393-a417-cdd1a6fa375e
URL: http://logs.px4.io/plot_app?log=6d0823a3-237b-4365-a89c-aad814dc3590
URL: http://logs.px4.io/plot_app?log=5fa5057a-d18b-4284-a082-8d4c3e71802f
URL: http://logs.px4.io/plot_app?log=6e62521d-20c8-42ec-8153-9ef83b5c7c31
URL: http://logs.px4.io/plot_app?log=11c0dde3-b3a4-4753-b98d-1650eccd40cd
URL: http://logs.px4.io/plot_app?log=9f9edf3a-3f15-4ccd-9684-e95c27647610
URL: http://logs.px4.io/plot_app?log=36f2c67e-af3f-4599-98f5-c36eb2dbd898

I think we should find a way to have the build results page show these links prominently, rather than posting comments to github. That will generate a lot of comments with rebases.

**Comment by AndreasAntener** [comment]
@dagar Nice integration, thanks!
The reason I would like to have the upload it in a script is that everything done in Jenkins is  in-transparent to anyone else. Thoughts? Environment variables are (should) all available for the called scripts as well.

**Comment by AndreasAntener** [comment]
@dagar You suggestion about the links makes sense.

**Comment by dagar** [comment]
Either way works for me, I just wanted to see the output. Good point about transparency.

**Comment by AndreasAntener** [comment]
I just realized that we'll get emails for the uploaded logs, we probably want to prevent this?

**Comment by LorenzMeier** [comment]
Is this already merged? I'm asking since I did start to get logs already.

**Comment by AndreasAntener** [comment]
No, but Daniels script is running on Jenkins directly. Can we disable emails if source == CI?

**Comment by bkueng** [comment]
Just avoid adding `--email <email>` when using the script does that. Or do you mean different email notifications?

**Comment by AndreasAntener** [comment]
ah ;), thanks

**Comment by AndreasAntener** [comment]
Good to go! Thanks @dagar

**Pull request merged**
