### PR TITLE
Updates & Fixes for Nxphlite-v3

### PR DESCRIPTION
**Pull request by davids5**
From: https://github.com/PX4/Firmware/pull/8030

This is a WIP for the NXP flight V3 HW based on the K66. It builds but is incomplete as it is missing key Nuttx support in the Kinetis architecture.

The drivers/kinetis/\* is just stubbed out.  There is SPI, or DMA support

Missing Components
- [x]  FPU support in the OS
- [ ] DMA
- [x] SPI - Completed
- [ ] CAN
- [ ] VBAT - for bootloader app commnincation.
- [x] Timers PIT, LPTM, and FTM, PDB - for pwm, capture, tones, and hrt.
- [x] RESET up_systemreset(void) noreturn_function;
  
  Incomplete Drivers:
- [x] PWM supports only 1 chan per timer.
- [x] USB The K66 has 2 USB USB0 is FS (Nuttx has driver) USB1 is HS (No NuttX driver!) 
- [ ] UART lacking DMA kinetis_serial_dma_poll(void)
- [x] TERMIOS for serial
- [ ] RTC - up_rtc_getdatetime
- [ ] SDHC DMA disabled will not work with it yet

OS/System dependant SW
- [x] Cannot use FPU yet on kinetis
- [x] Termios
- [x] tcgetattr
- [x] tcsetattr
- [x] cfsetspeed

PX4 FMUV2 Modules removed from build due to No External SPI
- [ ] drivers/bma180
- [ ] drivers/bmi160
  
  NOT Portable YET
- [ ] /Firmware/src/modules/systemlib/mcu_version.c
- [ ] drivers/pwm_input
- [ ] drivers/test_ppm
- [ ] systemcmds/hardfault_log - needs bsram
- [ ] modules/uavcan
- [ ] uavcan
- [ ] uavcan_stm32_driver - need Kinetis CAN driver

PX4 Drivers Needing porting
- [ ] drivers/kinetis/*
- [ ] drv_hrt.c 
   - [x] HRT 
   - [x] PPM
- [ ] drv_input_capture.c
- [x] drv_io_timer.c
- [ ] drv_led_pwm.cpp
- [x] drv_pwm_servo.c
- [x] drivers/kinetis/adc
- [x] drivers/kinetis/tone_alarm

### CODE REVIEW

**Comment by bkueng** [comment]
@davids5 I have found & fixed the PPM issue in https://github.com/PX4/Firmware/pull/8410/commits/e2794147882988f6dee8e4fa6637739102355b1e

**Comment by laube** [comment]
@bkueng I can't seem to get this to run.

The first problem is that I have to comment out [platforms/nuttx/NuttX/nuttx/arch/arm/src/kinetis/kinetis_lowputc.c:274](https://github.com/PX4-NuttX/nuttx/blob/b18053574bf41712cef93e31bf178518f451a350/arch/arm/src/kinetis/kinetis_lowputc.c#L274). It would otherwise hang there forever.

Second, I do not get a serial console on either the USB (random data is streaming, probably mavlink?) or the debug UART port (streams some hex stuff `[...]:F2FeF0F:FCF:FCFSFvF1FCF0FvF2FXF0FXF F0FvF0FDF0F:FCFXF2FSFeF0F[....]`).

Then, I though well I don't need `nsh` to see whether the sensor crashes so I start checking with the logic analyzer. The sensor is not started. I can confirm with GDB that the sensor driver is never called.

What do I miss? I don't have an SD card inserted.

**Comment by laube** [comment]
BTW, I build this on ubuntu with the `gcc-arm-none-eabi-5_4-2016q3` compiler

**Comment by laube** [comment]
@bkueng @davids5 

I tested the suggested fix for the fxos8701 sensor. This works even under high stress situations (with GPS on) that caused a lockup within seconds before.

To keep this simple, I have attached the patch here:

```patch
From e746f6b2d19cf8ded312ce618467e13b6964d454 Mon Sep 17 00:00:00 2001
From: Simon Laube <simon@leitwert.ch>
Date: Wed, 3 Jan 2018 12:37:19 +0100
Subject: [PATCH] Fix FXOS8701 driver: Do not change mode on temperature readout.
---
 src/drivers/fxos8701cq/fxos8701cq.cpp | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
 mode change 100644 => 100755 src/drivers/fxos8701cq/fxos8701cq.cpp

diff --git a/src/drivers/fxos8701cq/fxos8701cq.cpp b/src/drivers/fxos8701cq/fxos8701cq.cpp
old mode 100644
new mode 100755
index 5a7cfdb..61db0a4
--- a/src/drivers/fxos8701cq/fxos8701cq.cpp
+++ b/src/drivers/fxos8701cq/fxos8701cq.cpp
@@ -1395,9 +1395,9 @@ FXOS8701CQ::measure()
 	 * one device to the next
 	 */
 
-	write_checked_reg(FXOS8701CQ_M_CTRL_REG1, M_CTRL_REG1_HMS_A | M_CTRL_REG1_OS(7));
+	// write_checked_reg(FXOS8701CQ_M_CTRL_REG1, M_CTRL_REG1_HMS_A | M_CTRL_REG1_OS(7));
 	_last_temperature = (read_reg(FXOS8701CQ_TEMP)) * 0.96f;
-	write_checked_reg(FXOS8701CQ_M_CTRL_REG1, M_CTRL_REG1_HMS_AM | M_CTRL_REG1_OS(7));
+	// write_checked_reg(FXOS8701CQ_M_CTRL_REG1, M_CTRL_REG1_HMS_AM | M_CTRL_REG1_OS(7));
 
 	accel_report.temperature = _last_temperature;
 
-- 
2.9.3

```

**Comment by bkueng** [comment]
Thanks @davids5 & @laube . I tested it as well (using RC via UART that caused the lockup within seconds too) and can confirm it fixes it.

**Comment by bkueng** [comment]
Thanks for your work @janokle.

I rebased and removed the debug stuff. I tested the GPS driver and it now works better, but there are still problems. Sometimes the communication drops (`gps status` shows 0 Hz update rate) and I saw this:
```
[gps] ubx msg 0x0102 invalid len 1536
```
Similar for SBUS: the channels are detected, but I see random jumps.

@janokle do you have time to look into that?

Other than that, this can be merged now.

**Comment by bkueng** [comment]
I reduced the baudrate for the GPS, which helps.

**Comment by bkueng** [comment]
Rebased & dropped the debug commits. I'm merging this as it contains important fixes for NXPhlite, and we can continue with new PR's.

**Pull request merged**
