### PR TITLE
FW navigation in high winds

### PR DESCRIPTION
**Pull request by dagar**
This is a fix for fixed wing flights in high wind. I've tested this in the field in normal conditions, and in HIL with high winds, but so far not in the field with high winds.

### CODE REVIEW

**Comment by AndreasAntener** [comment]
@dagar Haven't looked at the root cause yet but shouldn't we fix L1 instead?

**Comment by dagar** [comment]
That could work if we passed more state to L1. It currently doesn't know anything about airspeed or wind.

**Comment by LorenzMeier** [comment]
Looking good on a first pass.

**Comment by LorenzMeier** [comment]
@dagar What is the test plan for this?

**Comment by dagar** [comment]
I've been flying it for a couple weeks and I've tested it in xplane with a range of winds. Any other ideas? 
Do you think it should be pushed into L1?

**Comment by LorenzMeier** [comment]
I think medium term yes, but we need to keep moving, so I'll merge and open an issue for 1.5.

**Pull request merged**
