### PR TITLE
Mavros test updates

### PR DESCRIPTION
**Pull request by AndreasAntener**
Minor updates
* Uses MAVROS arm command to arm
* Moved SITL MAVROS nodes to root

### CODE REVIEW

**Comment by thomasgubler** [comment]
Does demo_offboard_attitude_setpoints and demo_offboard_position_setpoints still work with this branch? (they publish data to mavros)

**Comment by AndreasAntener** [comment]
of course not ;) they should now.
Position control works for me but not attitude. Should attitude work too by now?

**Comment by thomasgubler** [comment]
yes attitude should work as well. the quad should 'jump' forwards and backwards. (sinus on throttle and pitch or roll)

**Comment by thomasgubler** [comment]
ros_mavlink is now in master. Can you open a new one against master please? Also: can you please tag

**Comment by AndreasAntener** [comment]
sure

**Pull request closed without merging**
