### PR TITLE
Bosch BMI055 cleanup

### PR DESCRIPTION
**Pull request by dagar**
- move to PX4Accelerometer and PX4Gyroscope helpers

### CODE REVIEW

**Comment by dagar** [comment]
Saves ~ 3.5 KB of flash.

image

**Comment by dagar** [comment]
@PX4/testflights can you give this a quick try on a Pixhawk 4 or Pixhawk 4 mini (flight controllers with a Bosch BMI055 IMU). Please enable "Sensor comparison" via the `SDLOG_PROFILE` parameter.

**Comment by dannyfpv** [comment]
Tested on Pixhawk 4 v5
Modes Tested:

Position Mode: no issue
Altitude Mode: no issue
Stabilized Mode: no issue

Procedure:
Arm in position mode, check take off behavior (Vehicle should stay on the ground as long as the throttle stick is at the middle or below, and start to ascend smoothly as long as throttle stick as above the middle.), the land and disarm.
enable "Sensor comparison" via the SDLOG_PROFILE parameter.


Notes:
No issues were noted on position and altitude, but while testing stabilized mode, vehicle started to ascend slowly before reaching middle position, good flight in general.

Logs:

https://review.px4.io/plot_app?log=c25c1c19-ad22-4cbf-9b61-eb5a9ead669f

https://review.px4.io/plot_app?log=dbeaea5f-5938-4515-aa37-c0df6ff1cdf3

https://review.px4.io/plot_app?log=f2bbc861-f20c-48c0-bd79-743ebce74634

https://review.px4.io/plot_app?log=75cfa4d7-514c-41a3-ad8e-e37886aa508a

**Comment by dagar** [comment]
> Notes:
> No issues were noted on position and altitude, but while testing stabilized mode, vehicle started to ascend slowly before reaching middle position, good flight in general.

Can you point to where? Log and roughly when.

**Comment by Junkim3DR** [comment]
### Tested on Pixhawk 4mini v5

**Flight Card 1**

**Modes Tested:**
- Position Mode: Good. 
- Altitude Mode: Good. 
- Stabilized Mode: Good. 

**Procedure:**
Arm in position mode, check take off behavior (Vehicle should stay on the ground as long as the throttle stick is at the middle or below, and start to ascend smoothly as long as throttle stick as above the middle.), the land and disarm.
Same procedure was repeated with Altitude and Stabilized mode.

**Notes:**
No issues were noted, good flight in general.


**Flight Card 2**

**Modes Tested**
- Mission Plan Mode (Automated): Good.
- RTL (Return To Land): Good.

**Procedure**
Arm and Take off in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior. 

**Note:**
No issues were noted, good flight in general.


**Flight Card 3**

**Modes Tested**
- Position Mode: Good.
- Mission Plan Mode (Automated): Good.
- RTL (Return To Land): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior. 

**Note:**
No issues were noted, good flight in general.

**Logs:**
- Flight Card 1: https://review.px4.io/plot_app?log=d1f5e6d5-557c-408f-9d21-d66c88384539
- Flight Card 2: https://review.px4.io/plot_app?log=ba88abed-218f-461c-bda6-eb23b44e7588
- Flight Card 3: https://review.px4.io/plot_app?log=8cabc3f0-428c-4e82-a6f1-0c59c36f3013

**Comment by dannyfpv** [comment]
@Dagar, everything is working as expected.

There was an issue while commenting, comment has been updated.

**Pull request merged**
