### PR TITLE
Backports of upstream NuttX fixes.

### PR DESCRIPTION
**Pull request by davids5**
Backport of upstream NuttX MTD FLASH driver: Flash corruption fix 

  0a85a41 MTD FLASH driver: Clone Sebastien Lorquet's m25px change to at25, is25xp, ramtron, and sst25xx.

  This patch brings stm32_serial equivalent to upstream Nuttx without the IRQ changes.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Generally looks good to me. @PX4TestFlights please test, start with a thorough bench test and watch for any type of communication drops on the telemetry.

**Comment by davids5** [comment]
Ok I am done with this. It is ready for test. There are really no more we **need**. 
We do need to discuss when we should move to upstream nuttx again. F7, has had a lot of work, Kinetis is there and I will put the other new archs on upstream as well.

**Comment by santiago3dr** [comment]
flight with a quad running pixracer (v4)
indoor test:
http://logs.px4.io/plot_app?log=b80b6b11-275b-41b5-b70d-a295500358a5

full flight:
http://logs.px4.io/plot_app?log=7942c379-a438-435c-8570-25768da405f3

**Comment by Avysuarez** [comment]
flight with Pixhawk Pro (V4 PRO), good flight no issues;
http://review.px4.io/plot_app?log=9a8a50af-52da-4e60-bd57-e802417dcae4
flight with Pixhawk mini (V3) good flight no issues;
http://review.px4.io/plot_app?log=aaf82144-1e8a-4a7c-a020-b6456926d94b

**Comment by LorenzMeier** [comment]
@davids5 Could you fix the merge conflict?

**Comment by davids5** [comment]
@LorenzMeier yep - it is rebased and forced push.

**Pull request merged**
