### PR TITLE
Better granularity for flight failsafe modes

### PR DESCRIPTION
**Pull request by LorenzMeier**
@kd0aij Testing this with props off would be great. Main documentation:

```C++
/**
 * Set data link loss failsafe mode
 *
 * The data link loss failsafe will only be entered after a timeout,
 * set by COM_RC_LOSS_T in seconds.
 *
 * @value 0 Disabled
 * @value 1 Loiter
 * @value 2 Return to Land
 * @value 3 Land at current position
 * @value 4 Outback Challenge (OBC) rules
 *
 * @group Mission
 */
PARAM_DEFINE_INT32(NAV_DLL_ACT, 0);

/**
 * Set RC loss failsafe mode
 *
 * The RC loss failsafe will only be entered after a timeout,
 * set by COM_RC_LOSS_T in seconds. If the timeout value is smaller than
 * zero it will never be entered. If RC input checks have been disabled
 * by setting the COM_RC_IN_MODE param it will also not be triggered.
 *
 * @value 0 Disabled
 * @value 1 Loiter
 * @value 2 Return to Land
 * @value 3 Land at current position
 * @value 4 Outback Challenge (OBC) rules
 *
 * @group Mission
 */
PARAM_DEFINE_INT32(NAV_RCL_ACT, 0);
```

@DonLakeFlyer The comments above should also be enough to re-do the safety screen. I've broken the param system with this change, I need to think how we address that.

### CODE REVIEW

**Comment by kd0aij** [comment]
For testing this, can "datalink" be wifi connection to QGC on pixracer?

**Comment by LorenzMeier** [comment]
Yes, that should trigger it.

**Comment by kd0aij** [comment]
first test of RC loss with option 3 gave no feedback on console or QGC and motor speed did not change

also getting this on the console:
```
WARN  Failed to open MAVLink log: /fs/microsd/msgs_2016_04_23_15_53_43.txt@� errno=22
WARN  Failed to open MAVLink log: /fs/microsd/msgs_2016_04_23_15_53_48.txt@� errno=22
WARN  Failed to open MAVLink log: /fs/microsd/msgs_2016_04_23_15_53_48.txt@� errno=22
```

**Comment by LorenzMeier** [comment]
@kd0aij If you get these you need to wipe your SD card. File system fail.

**Comment by LorenzMeier** [comment]
Its possible that the motor speed is not changing if the system believes it already is landed. But I need to check.

**Comment by kd0aij** [comment]
is there a console or mavlink message indicating failsafe is engaged?

**Comment by kd0aij** [comment]
refetched, cleaned and reflashed. RC loss results in QGC "Landing" mode and much later "failsafe mode on". No messages on console. Motors sped up and stayed at that speed for several minutes. What is supposed to happen?

**Comment by LorenzMeier** [comment]
That sounds about right. It would have landed on-spot.

**Comment by kd0aij** [comment]
motors never stop?

**Comment by kd0aij** [comment]
battery voltage reading in QGC is erratic... critical battery warning with FrSky telemetry showing 11.1V

**Comment by kd0aij** [comment]
I have an ACSP5 on this PixRacer

**Comment by kd0aij** [comment]
Why isn't there an RC failsafe option to kill the motors? Is that the OBC mode?

**Comment by kd0aij** [comment]
Killing the wifi link while armed in manual mode didn't appear to do anything, but I guess there's intentionally no feedback on the console?

**Comment by kd0aij** [comment]
@LorenzMeier I see you merged this with open questions from me... Were there other test results which were more definitive? I tried this again today with the copter tied down, but the "land at current position" motor behavior seemed wrong, and it went to high throttle when I turned the TX back on, so I don't trust that option. So as far as I can tell, there's no safe option available to prevent a fly-away on RC loss.

**Comment by LorenzMeier** [comment]
You will need to try this on a tether, rather than tied down. If its close to home it will land straight, if it is not close to home it will RTL.

**Comment by kd0aij** [comment]
is a GPS lock required?

**Comment by kd0aij** [comment]
apparently this needs more testing, but I would need more explanation of expected results to be able to test it safely: https://github.com/PX4/Firmware/issues/4674

**Comment by xn365** [comment]
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/navigator_main.cpp#L344
I think navigator will not working When we don't have gps.
Could AUTOLAND or LANDGPSFA mode run in this case?

**Pull request closed without merging**
