### PR TITLE
UAVCAN performance audit

### PR DESCRIPTION
**Pull request by pavel-kirienko**
I will be logging my efforts to improve the UAVCAN driver, especially in the sense of CPU load, in this pull request. Please do not merge it yet.

Considerable time has been spent on my fruitless attempts to squeeze the driver into the FMUv2 build by switching some optimization flags and removing some not-so-critical components. Unfortunately, during my experiments the system tended to either overflow ROM, fail in a confusing way during boot, or just refuse to perform basic functions such as connecting to QGC. At some point I gave up (with much regret) and replaced FMUv2 with FMUv4.

According to the reports from @LorenzMeier, a system consisting of Zubax GNSS + a Sapog ESC + FMUv1 creates a 12% CPU load in the UAVCAN driver. I am observing a slightly different number of 7.6% with my FMUv4 setup, perhaps the difference can be explained by a higher clock rate of the newer board.

Looking at the CAN bus traffic I noticed that the ESC command messages carry six values, whereas my setup requires only four. It turned out that the default CAN quadrotor mixer is configured to generate 6 outputs rather than 4, the extra 2 serving some obscure purpose I couldn't understand. In order to validate this, I defined a new mixer and made the CAN quadrotor vehicle config refer to it. Expectedly, this change reduced the number of values per command message from 6 to 4, which allowed the UAVCAN stack to send only one frame per message. This change has dropped the CPU usage from **7.6%** to **5.7%**.

@LorenzMeier @AndreasAntener I strongly advice to review your VTOL mixer files and make sure that no unnecessary outputs are being generated, they slow things down.

I also added a check in the UAVCAN ESC output bridge that removes the trailing zero setpoint values from the output. This should help to somewhat improve performance even when buggy mixing is afoot.

My next step is to let the system run for several hours under a sampling profiler in order to find bottlenecks. Has this ever been done before?

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Looking at preliminary profiling results (profiling is still in progress) I noticed that the system performs *a lot* of 64-bit floating point arithmetic computations. I understand that in some cases it is intentional and perfectly valid, since the resolution of 32-bit float is really limited. However, certain cases look like a smoking gun to me. Have a look at this instance:

screenshot_20170316_025130

Observe that a call stack rooted in the class `Vector<float>` (notice that the template is instantiated with the `float` type argument) ends up in the 64-bit square root computation routine. I checked [the source](https://github.com/PX4/Matrix/blob/master/matrix/Vector.hpp#L75) and found this:

```c++
    Type norm() const {
        const Vector &a(*this);
        return Type(sqrt(a.dot(a)));
    }
```

It looks like the author of this code intended to use `std::sqrt()`, since the version from the C++ standard library is overloaded for `float` and `double`, unlike the version available from the C standard library. The alleged mistake caused the compiler to convert float to double, compute square root using emulated FP, and then convert the result back to float. Note that the M4 core has a hardware support for floating point root finding, so the difference in performance could be drastic.

One might argue that if such an error took place, the compiler would trigger the carefully enabled warning `-Wdouble-promotion`. Correct me if I'm wrong, but as I understand the documentation, this flag will only report *implicit promotion* to double, but not *implicit conversion*. The example above features an implicit conversion rather than promotion, so no warning should be expected. Note that `-Wconversion`, were it enabled, probably would not have helped here either, although for different reasons.

There are dozens of similar suspicious instances where 64-bit soft FP routines are invoked (not only sqrt but also add, asin, mul, etc.) from where they probably shouldn't be. Have a look at this preliminary interactive SVG to get an idea: [pmpn-flamegraph.tar.gz](https://github.com/PX4/Firmware/files/846317/pmpn-flamegraph.tar.gz) (tomorrow I will upload a higher resolution file - sampling is still in progress and it is slow).

Paging @davids5.

**Comment by davids5** [comment]
@jgoppert

@pavel-kirienko has done some really good sleuthing here in. Can we look at avoiding the conversions and emulated FP overhead.

**Comment by jgoppert** [comment]
Good stuff. Happy to make changes to matrix. Can you submit a PR if you get it pinned down?

**Comment by AndreasAntener** [comment]
@pavel-kirienko I've changed the startup on our side so the CAN mixer only ever receives the multirotor component. So we should not have any overhead there. I'll check with @eyeam3 how many values the bus transports in our case.

**Comment by eyeam3** [comment]
We have an octocopter setup, so the bus transports eight values.

**Comment by LorenzMeier** [comment]
@pavel-kirienko Could you please fix the routines in matrix and send a PR?

**Comment by pavel-kirienko** [comment]
@LorenzMeier Already doing so.

**Comment by pavel-kirienko** [comment]
Here's the high resolution output: [pmpn-flamegraph.tar.gz](https://github.com/PX4/Firmware/files/847347/pmpn-flamegraph.tar.gz)

Here's some of the most common endpoint functions:

```
 17.6%    os_start
  6.7%    up_idle
  4.0%    spi_readword
  2.3%    memset
  2.2%    __aeabi_dadd
  1.9%    exception_common
  1.9%    __muldf3
  1.8%    <unknown symbol>
  1.6%    __ieee754_sqrtf
  1.6%    __ieee754_sqrt
```

In this list, all routines prefixed with double underscore perform 64-bit floating point arithmetic.

**Comment by LorenzMeier** [comment]
Way too much memset going on there. We might need to revisit our defensive programming strategies.

**Comment by pavel-kirienko** [comment]
Does anybody else find the 4% of `spi_readword` alarming? I checked the sources and found that the driver does a polling wait from an interrupt handler. I also ventured to make sure that the bus is clocked at the proper rate of 11 MHz (yes it is).

Can DMA or at least an IRQ-driven logic be an option?

**Comment by pavel-kirienko** [comment]
A simple test shows that the system, indeed, spends about 5% of its run time doing nothing in the SPI polling loop (notice the duty cycle estimate in the bottom right corner):

ds1z_quickprint2

The high level is held while the SPI driver is waiting for completion of the current transfer.

**Comment by LorenzMeier** [comment]
That's a design decision originally done for a single sensor and lower-rate reads. The reason this is not an immediate concern from a controls perspective is that if you're not running at 100% load there is nothing you can do before that SPI update - you are waiting for a total system state update and unless you have new accel and gyro data there is no actionable information.

No sensor data, no controller output and if there is no controller output to execute on there is nothing high-priority to do. For the same reason UART has RX DMA so that this prioritisation does not lead to communication drops.

However, work is under way to longer-term replace this with SPI DMA. That will allow to run more CPU load on house-keeping tasks, but it will not improve the flight performance on current setups - because the actionable information does not become available before.

Please focus on the CPU load related aspects. These are the ones that delay executing actionable information.

**Comment by pavel-kirienko** [comment]
For the record here, the best performance can be achieved with `-O2`, which is already the default. `-O3` adds about 8K of code and no noticeable performance gain, `-Os` shrinks the code by 2K and adds about 1% of CPU load.

**Comment by pavel-kirienko** [comment]
Fixing the Matrix library brought CPU usage down by 10%.

Before:
```
Processes: 26 total, 4 running, 22 sleeping
CPU usage: 69.66% tasks, 1.96% sched, 28.39% idle
DMA Memory: 5120 total, 1024 used 1536 peak
Uptime: 1115.418s total, 319.128s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE
   0 Idle Task                  319128 28.385   660/  748   0 (  0)  READY
   1 hpwork                      25149  2.244   784/ 1780 192 (192)  w:sig
   2 lpwork                       1067  0.072   644/ 1780  50 ( 50)  w:sig
   3 init                        10962  0.000  2096/ 2484 100 (100)  w:sem
 338 top                         29590  2.679  1264/ 1684 100 (100)  RUN
 100 gps                          3020  0.434   936/ 1372 220 (220)  w:sem
 103 dataman                       139  0.000   720/ 1180  90 ( 90)  w:sem
 142 sensors                     51157  4.561  1344/ 1980 250 (250)  w:sem
 144 commander                   25550  2.244  2832/ 3548 140 (140)  w:sig
 156 mavlink_if0                 93264  8.472  1688/ 2380 100 (100)  w:sig
 157 mavlink_rcv_if0                79  0.000   952/ 2100 175 (175)  w:sem
 166 mavlink_if1                 21091  1.882  1632/ 2420 100 (100)  w:sig
 168 mavlink_rcv_if1                75  0.000   952/ 2100 175 (175)  w:sem
 179 mavlink_if2                 15795  1.375  1632/ 2388 100 (100)  w:sig
 180 mavlink_rcv_if2                75  0.000   952/ 2100 175 (175)  w:sem
 201 uavcan                      92405  8.037  1848/ 2380 240 (240)  w:sem
 203 uavcan fw srv               14724  1.230  3064/ 5996 120 (120)  w:sem
 204 commander_low_prio             39  0.000   664/ 2996  50 ( 50)  w:sem
 216 frsky_telemetry                12  0.000   552/ 1020 200 (200)  w:sem
 237 mavlink_if3                 46224  4.199  1632/ 2388 100 (100)  w:sig
 239 mavlink_rcv_if3              2153  0.000   952/ 2100 175 (175)  w:sem
 247 sdlog2                        697  0.000  1696/ 3316 177 (177)  w:sig
 282 ekf2                       267381 24.185  5072/ 5780 250 (250)  w:sem
 287 mc_att_control              47537  4.272  1280/ 1676 250 (250)  w:sem
 298 mc_pos_control              40143  3.620  1016/ 1876 250 (250)  w:sem
 309 navigator                    2218  0.144  1040/ 1572 105 (105)  w:sem
```
After:
```
Processes: 26 total, 4 running, 22 sleeping
CPU usage: 59.24% tasks, 2.18% sched, 38.57% idle
DMA Memory: 5120 total, 1024 used 1536 peak
Uptime: 21.391s total, 9.537s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE
   0 Idle Task                    9536 38.573   660/  748   0 (  0)  READY
   1 hpwork                        463  2.401   888/ 1780 192 (192)  w:sig
   2 lpwork                         17  0.072   644/ 1780  50 ( 50)  w:sig
   3 init                        14553  0.000  1996/ 2484 100 (100)  w:sem
 100 gps                            57  0.072   936/ 1372 220 (220)  w:sig
 103 dataman                         2  0.000   720/ 1180  90 ( 90)  w:sem
 142 sensors                       900  4.730  1344/ 1980 250 (250)  w:sem
 144 commander                     389  2.256  2840/ 3548 140 (140)  w:sig
 156 mavlink_if0                  1319  8.005  1664/ 2380 100 (100)  w:sig
 157 mavlink_rcv_if0                 1  0.000   952/ 2100 175 (175)  w:sem
 166 mavlink_if1                   334  1.819  1608/ 2420 100 (100)  w:sig
 168 mavlink_rcv_if1                 1  0.000   952/ 2100 175 (175)  w:sem
 179 mavlink_if2                   259  1.382  1608/ 2388 100 (100)  READY
 180 mavlink_rcv_if2                 1  0.000   952/ 2100 175 (175)  w:sem
 201 uavcan                       1327  8.078  1568/ 2380 240 (240)  w:sem
 203 uavcan fw srv                 413  1.382  3040/ 5996 120 (120)  w:sem
 215 frsky_telemetry                 0  0.000   552/ 1020 200 (200)  w:sem
 319 commander_low_prio              0  0.000   728/ 2996  50 ( 50)  w:sem
 234 mavlink_if3                   931  4.439  1600/ 2388 100 (100)  w:sig
 236 mavlink_rcv_if3                 1  0.000   952/ 2100 175 (175)  w:sem
 245 sdlog2                         11  0.000  1696/ 3316 177 (177)  w:sig
 278 ekf2                         2145 14.119  5072/ 5780 250 (250)  w:sem
 281 mc_att_control                594  3.930  1280/ 1676 250 (250)  w:sem
 286 mc_pos_control                359  3.420   712/ 1876 250 (250)  w:sem
 301 navigator                       7  0.000   960/ 1572 105 (105)  w:sem
 325 top                           445  3.129  1240/ 1684 100 (100)  RUN
```

**Comment by pavel-kirienko** [comment]
I am going to profile this again.

**Comment by pavel-kirienko** [comment]
N.B.: This is the second instance when a serious issue was discovered by way of profiling. The first happened 2 years ago, when we removed profiling instrumentation calls that were used for stack checking, which dropped CPU usage down by 40%: https://github.com/PX4/Firmware/pull/1660. I suspect the project could really benefit from adopting the practice of regular profiling.

**Comment by LorenzMeier** [comment]
The conclusion that stack checking was a performance issue is incorrect. We removed an early stage safety net because the system was stable - it was a design intent to trade CPU load for safety. We might very well re-add it on the F7.

In the case of Matrix lib it's a whole different story as it should not have promoted to double.

I agree on the benefit of regular profiling. Could you create a page in the PX4 dev guide for it?

**Comment by pavel-kirienko** [comment]
> The conclusion that stack checking was a performance issue is incorrect.

It was an issue in the sense that the actual performance hit (40%) was way above the expected penalty (20%). Profiling helped to discover that.

> I agree on the benefit of regular profiling. Could you create a page in the PX4 dev guide for it?

Yes, but I will have to push back on it now a bit.

**Comment by pavel-kirienko** [comment]
I will sum up my findings here, apart from what has been already said above.

### Poll is very slow

About half of the run time of the UAVCAN driver is spent in the `poll()` system call. This issue doesn't affect many other modules using poll as hard because they typically run at lower update frequencies. Besides UAVCAN, optimization of the poll function will also improve some other components, especially sensors, attitude control, position control, and all other modules running at high update rates.

The poll system call must be optimized, I will report this as a separate issue.

screenshot_20170317_160104

### Performance counters are slow

Many performance counters in the system do not worth the performance impact they introduce. I removed them from the UAVCAN driver, which lowered the CPU usage by 0.7%. I would advice to either review their implementation, or just remove them from all high frequency modules. My estimate is that this change alone would drop the CPU usage by up to 5%.

### MAVLink

About 1% of the total run time is spent in this check in `MavlinkStream::update(const hrt_abstime)` which is mostly useless:

```c++
	if (dt > (interval - (_mavlink->get_main_loop_delay() / 10) * 4)) {
```

The performance impact can be seen here on the right, it is significant:

screenshot_20170317_172720

I wouldn't venture to fix it myself, so I propose to register this as a separate issue.

### FPU is misbehaving

See the previous post. I propose to move this issue into a separate ticket, too.

### UAVCAN stack

The UAVCAN stack itself does not have any detectable performance issues.

**Comment by pavel-kirienko** [comment]
New report; note that it was collected before perfcounters were removed from the UAVCAN module: [pmpn-flamegraph.tar.gz](https://github.com/PX4/Firmware/files/850828/pmpn-flamegraph.tar.gz)

**Comment by jgoppert** [comment]
Just talked with @davids5 about this, @pavel-kirienko Can you update matrix in this PR so we can check it passes and we can make sure the build size looks good.

**Comment by pavel-kirienko** [comment]
@jgoppert it is already updated here

**Comment by dagar** [comment]
@pavel-kirienko we could look at enabling this clang-tidy check in the builds.
https://clang.llvm.org/extra/clang-tidy/checks/performance-type-promotion-in-math-fn.html

**Comment by pavel-kirienko** [comment]
@dagar That would be useful.

**Comment by jgoppert** [comment]
I don't see a significant change in build size, so will merge the changes to matrix.

build size of master

```
Building sizes
   text	   data	    bss	    dec	    hex	filename
 891596	   5228	  15208	 912032	  deaa0	build_aerofc-v1_default/src/firmware/nuttx/firmware_nuttx
1317136	   5912	  20412	1343460	 147fe4	build_auav-x21_default/src/firmware/nuttx/firmware_nuttx
 787668	   3816	   9116	 800600	  c3758	build_crazyflie_default/src/firmware/nuttx/firmware_nuttx
1216616	   5844	  20636	1243096	 12f7d8	build_mindpx-v2_default/src/firmware/nuttx/firmware_nuttx
 997252	   4952	  10084	1012288	  f7240	build_px4fmu-v1_default/src/firmware/nuttx/firmware_nuttx
 967696	   5884	  18340	 991920	  f22b0	build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx
 907220	   5884	  18340	 931444	  e3674	build_px4fmu-v2_lpe/src/firmware/nuttx/firmware_nuttx
1442236	   6140	  20724	1469100	 166aac	build_px4fmu-v3_default/src/firmware/nuttx/firmware_nuttx
1350776	   5944	  23820	1380540	 1510bc	build_px4fmu-v4_default/src/firmware/nuttx/firmware_nuttx
 774912	   5332	  15568	 795812	  c24a4	build_tap-v1_default/src/firmware/nuttx/firmware_nuttx
```

build size of this branch:

```
Building sizes
   text	   data	    bss	    dec	    hex	filename
 891356	   5228	  15208	 911792	  de9b0	build_aerofc-v1_default/src/firmware/nuttx/firmware_nuttx
1316616	   5912	  20412	1342940	 147ddc	build_auav-x21_default/src/firmware/nuttx/firmware_nuttx
 787316	   3816	   9116	 800248	  c35f8	build_crazyflie_default/src/firmware/nuttx/firmware_nuttx
1216088	   5844	  20636	1242568	 12f5c8	build_mindpx-v2_default/src/firmware/nuttx/firmware_nuttx
 996756	   4952	  10084	1011792	  f7050	build_px4fmu-v1_default/src/firmware/nuttx/firmware_nuttx
 968832	   5884	  18340	 993056	  f2720	build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx
 907276	   5884	  18340	 931500	  e36ac	build_px4fmu-v2_lpe/src/firmware/nuttx/firmware_nuttx
1441580	   6140	  20724	1468444	 16681c	build_px4fmu-v3_default/src/firmware/nuttx/firmware_nuttx
1350128	   5944	  23820	1379892	 150e34	build_px4fmu-v4_default/src/firmware/nuttx/firmware_nuttx
 774896	   5332	  15568	 795796	  c2494	build_tap-v1_default/src/firmware/nuttx/firmware_nuttx
```

**Comment by davids5** [comment]
@jgoppert - Thank you - at least  it went in the right directions.

**Comment by pavel-kirienko** [comment]
This is ready for merge.

**Comment by davids5** [comment]
@pavel-kirienko 

> This is ready for merge.

Apparently not yet.

Please have a log at the submode commit. See Revert "UAVCAN performance audit" #6846

**Comment by jgoppert** [comment]
This probably happened because I merged the PR on matrix and deleted the old branch and he just needs to update the matrix submodule again.

**Comment by pavel-kirienko** [comment]
Yes, it's fixed already.

**Pull request merged**
