### PR TITLE
Check for full microSD card

### PR DESCRIPTION
**Pull request by LorenzMeier**
Continuing #1577 here. This pull request checks if the microSD card is full and takes appropriate action.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@bansiesta Could you please cross-check this still works on a full microSD card? It does seem to behave for me.

**Comment by LorenzMeier** [comment]
@bansiesta I noticed I hadn't implemented the free space check pacing based on the remaining space as I originally proposed, but for the sake of getting something in this weekend rather than in a few weeks, I guess the current throttling is fine. So if you can re-test this and it holds up, we can get it merged.

**Comment by bansiesta** [comment]
I added the check every 20MB in 0265885. I'm testing it right now.

**Comment by bansiesta** [comment]
Tested, works!

**Comment by LorenzMeier** [comment]
Awesome!

**Pull request merged**
