### PR TITLE
aerofc: Reboot board when force bootloader pin is set

### PR DESCRIPTION
**Pull request by zehortigoza**
This can help "unbrick" AeroFC when a bad firmware is loaded
and it keeps rebooting or it spinning in some loop.

No need to request to stay in booloader as it will stay
in bootloader because the pin is set.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Can this be merged right away?

**Comment by zehortigoza** [comment]
> Can this be merged right away?

@lucasdemarchi ?

**Comment by lucasdemarchi** [comment]
@zehortigoza great. Do you have the changes to the FPGA ready?

@LorenzMeier yes, it can be merged.

**Comment by LorenzMeier** [comment]
What happens if I flash this onto an Aero without FPGA change?

**Comment by lucasdemarchi** [comment]
The FPGA firmware that's there right now will always set this pin to 0  (https://github.com/intel-aero/intel-aero-fpga/blob/master/aero_rtf_kit/RTL/top.v#L138).  There's a "recovery FPGA firmware"  that we also ship that set this pin to 1.  However since the check was only the bootloader, besides having to flash a new FPGA firmware (which takes some minutes) the user has to remove power from the board, otherwise we can't get back to bootloader.

This complements what's there. Now the FPGA will be able to switch back and forth this pin, triggering an interrupt on the stm32 side that reboots the board.

This is https://github.com/intel-aero/meta-intel-aero/issues/34 , to be available on the next version.

**Comment by zehortigoza** [comment]
@lucasdemarchi intel-aero/intel-aero-fpga#4

**Pull request merged**
