### PR TITLE
TECS fix height demand change

### LINKED ISSUE #6664: 2 bugs in TECS
in tecs.cpp
1. in line 110, it should be
`temp = rotMat(0, 2) * CONSTANTS_ONE_G + accel_body(0);`
rather than 
`temp = rotMat(2, 0) * CONSTANTS_ONE_G + accel_body(0);`

because the equation should be rotMat * [0;0;G], which means the element in 1st row 3rd column is enrolled. 

2. From line 283 to 285
`_hgt_dem_adj = 0.1f * _hgt_dem + 0.9f * _hgt_dem_adj_last;`
`_hgt_dem_adj_last = _hgt_dem_adj;`
`_hgt_rate_dem = (_hgt_dem_adj - state) * _heightrate_p + _heightrate_ff * (_hgt_dem_adj - _hgt_dem_adj_last) / _DT;`
line 284 and line 285 must be exchanged. Otherwise the heightrate_ff won't have effect. The derivative is always zero.

### PR DESCRIPTION
**Pull request by dagar**
- fixes #6664

Need to do more testing/comparison. TECS might be slightly easier to tune if we expose a few more things over mavlink.

### CODE REVIEW

**Comment by tumbili** [comment]
@dagar Looks good! We are going to test the feed-forward and maybe will come up with better defaults.

**Comment by tumbili** [comment]
@dagar Can you explain the choice of using 0.1 as default for the feed-forward? In theory the parameter could be set to 1 but I think it's more about finding sensible values which give good performance. Have you ever tested this on a real airframe?

**Comment by dagar** [comment]
No, just simulation so far. It's going to be a few days until I go to the field.
It's a safe arbitrary small starting value, given it was previously 0.

**Comment by LorenzMeier** [comment]
Any test data update?

**Comment by LorenzMeier** [comment]
Any update?

**Comment by AndreasAntener** [comment]
We couldn't fly that yet unfortunately.

**Comment by dagar** [comment]
FYI this has been used in other test flights a few times now.

image


Any objection to setting a much higher default?

**Comment by LorenzMeier** [comment]
No objections from me. It looks like it helps keeping the integrators at bay.

**Comment by dagar** [comment]
Any objections to merging?

**Comment by tumbili** [comment]
@dagar Looks good!

**Pull request merged**
