### PR TITLE
[VTOL]Wrong mixer configuration

### PR DESCRIPTION
**Pull request by xdwgood**
The current master branch, the two motors' tailsitter in rotor mode, yaw's control is the opposite direction, this PR solves this mistake.

PR from: Institute of Geography, Chinese Academy of Sciences

I have completed the flight test. :smiley: 

FYI : @dagar

### CODE REVIEW

**Comment by xdwgood** [comment]
By the way, if PX4 has any changes to the tailsitter, we are happy to provide testing and feedback.

**Comment by LorenzMeier** [comment]
Could you share an image of your aircraft setup, in particular the control surfaces? "Wrong" can be a matter of how you've connected the elevon linkage and might be just due to your aircraft being set up mirrored from the original reference vehicle.

**Comment by xdwgood** [comment]
we use v1.8.2...everything is fine.but we try master ，then found this issue.

**Comment by LorenzMeier** [comment]
@RomanBapst Is it possible that the fix for the pitch sign in VTOL wasn't applied to the tail sitter? That would explain this.

**Comment by RomanBapst** [comment]
@xdwgood The changes look ok, looks like this mixer file was either forgotten or it didn't exist at the time when the parameter was added.
However, I noticed that the mixer file you are changing is a duplicate of caipirinha_vtol.main.mix.
I think I'd makes sense to delete caipirinha_vtol.main.mix and instead use vtol_tailsitter_duo.main.mix
Could you please do this change as well?

**Comment by xdwgood** [comment]
@RomanBapst 
done here： https://github.com/PX4/Firmware/pull/13425/commits/686feab65c7adcd22041600431de033900692366    :smiley:

**Comment by RomanBapst** [comment]
@xdwgood I'd say that looks ok now.

**Pull request merged**
