### PR TITLE
System: Set new logger system as the default

### PR DESCRIPTION
**Pull request by LorenzMeier**
This will upgrade systems to the new .ulog format used by http://logs.px4.io and supported by Flight Plot.

Please comment in this PR if you have concerns about the ripples for the community and legacy systems.

### CODE REVIEW

**Comment by dagar** [comment]
posix-configs as well?

**Comment by LorenzMeier** [comment]
Yep, right - those as well.

**Comment by LorenzMeier** [comment]
Will you add a commit or shall I?

**Comment by dagar** [comment]
Done

**Pull request merged**
