### PR TITLE
wip: mc_pos_control: if takeoff setpoint in auto mode, then do not enter ground contact

### PR DESCRIPTION
**Pull request by Stifael**
follows the discussion here:
https://github.com/PX4/Firmware/issues/6914

### CODE REVIEW

**Comment by Stifael** [comment]
@sanderux do you mind to test it since I was not able to reproduce it in sitl.

**Comment by LorenzMeier** [comment]
@sanderux SITL / CI test fails. Can you look into that?

**Comment by sanderux** [comment]
@LorenzMeier this is mavros CI. It seems to only have failed uploading one mission of several.
I see no reason this is related to this PR

```
[ROSTEST]-----------------------------------------------------------------------

[px4.rosunit-mission_test_new_1/test_mission][passed]
[px4.rosunit-mission_test_new_2/test_mission][passed]
[px4.rosunit-mission_test_old_1/test_mission][passed]
[px4.rosunit-mission_test_old_2/test_mission][passed]
[px4.rosunit-mission_test_old_3/test_mission][FAILURE]--------------------------
(vtol_old_3.txt) mission could not be transfered
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/job/catkin/src/px4/integrationtests/python_src/px4_it/mavros/mission_test.py", line 336, in test_mission
    self.assertTrue(res.success, "(%s) mission could not be transfered" % self.mission_name)
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------
```

**Comment by Stifael** [comment]
Whats the status here?

**Comment by sanderux** [comment]
@Stifael as for CI i dont know, could you try to rebase to force a new run?
as for testing we ran in to an other unrelated issue that requires resolving before we can switch branches on our test plane. I will aim for this weekend.

**Comment by sanderux** [comment]
@Stifael can you rebase to re run SITL CI?

**Comment by LorenzMeier** [comment]
I've rebased this. Good to go once it clears CI.

**Pull request merged**
