### PR TITLE
add option for full attitude control and attitude sequencing in ACRO mode

### PR DESCRIPTION
**Pull request by kd0aij**
initial capability working in SITL. Roll and pitch flips are working, and there are no limitations on desired orientation. Currently, rate/duration commands are necessary to specify inverted orientations

**What's going on with code style?** I'm seeing many whitespace changes in commander.cpp, and all I'm doing is "Tools/fix_code_style".

The sequencer executes a series of rate, attitude and delay commands. Rate commands are the same as ACRO mode rate controls, and attitude commands specify a target orientation using Euler angles. All orientations are legal. 

This is a 360 degree roll:
roll_flip

and this is a "2 point" roll, with a pause at inverted:
two_point_roll

### CODE REVIEW

**Comment by dagar** [comment]
@kd0aij there are some modules which are still excluded from code style enforcement because the change would be massive and difficult to merge for other adopters. Commander is one of them.
https://github.com/PX4/Firmware/blob/master/Tools/files_to_check_code_style.sh#L20

Locally if you do `make check_format` it'll match what the builds check.

**Comment by kd0aij** [comment]
@dagar Thanks, I forgot that not everything had been formatted and quit using "check_format". The commit to "fix" commander.cpp whitespace _does_ look pretty nasty.

Have you noticed that the Iris no longer hovers at 50% throttle in jmavsim SITL? After rebasing on master today, it needs 61% to hover when I'm running this branch.

**Comment by dagar** [comment]
The jmavsim submodule was updated about 4 days ago. Here's the diff https://github.com/DrTon/jMAVSim/compare/a5b0f1f0896c9372c62222e88117c6ced2c6282b...PX4:744585dfa14fb0d51fda665fd32cb66a182ef868

**Comment by kd0aij** [comment]
That would do it if the Iris' mass went up 25% 
Not sure if that's the correct way to fix the default thrust level, but that will keep it solidly on the ground at 50% throttle :)

**Comment by mhkabir** [comment]
@kd0aij How can we test the attitude  sequencing? If I get it correctly, it would allow executions of primitives like flips directly using transmitter buttons, right? What mode would the system need to be in?

**Comment by kd0aij** [comment]
@mhkabir Yes, the idea is that a transmitter switch would be assigned to the the new RC_MAP_SEQ_SW channel. The code implements a one-shot behavior so that the sequence is executed once on the rising edge of that channel.
To test in SITL:
Set the new ACRO_ATT parameter to 1, and switch to ACRO mode. This version of the code executes the (compile time selected) sequence "two_point_roll" every 5 seconds after you enter ACRO mode:
https://github.com/kd0aij/Firmware/blob/attSeq_rebased/src/modules/mc_pos_control/mc_sequencer.cpp#L59
That's because I couldn't figure out how to map a joystick button to an RC channel and didn't want to screw around implementing mavlink commands just to test in SITL. The RC trigger channel I implemented should be workable, but it's commented out here:  
https://github.com/kd0aij/Firmware/blob/attSeq_rebased/src/modules/mc_pos_control/mc_sequencer.cpp#L101

You'll also see sequences defined for "tllt_lr" (45 degree left/right roll), "pitch_flip", and "roll_flip". I'm overflowing flash on fmu-v2 right now though, and these sequence def's should probably be read from a file, with only the active one resident in RAM. But on fmu-v4, it's probably better to have a small set in flash for reduced code complexity and less RAM usage. Suggestions on this would be appreciated.

If you set ACRO_ATT to zero (default), you get normal rate-mode behavior, as before.

**Comment by dagar** [comment]
I'm mostly just thinking out loud here, but instead of handling the switch within the controller what about sending a vehicle command within the autopilot to either initiate a sequence or possibly even define a new sequence? https://github.com/PX4/Firmware/blob/master/msg/vehicle_command.msg#L88
Later a new mavlink command could easily be mapped to the vehicle command.

Do you prefer the old style mode selection to the new simple mode selection?

**Comment by kd0aij** [comment]
I'll first have to search through the code to understand what "vehicle commands" are.
I still fly using the "old" style mode selection because that's simpler than changing all of my transmitter's model settings. And how would you use single channel mode selection with a Spektrum DX7? Would you be limited to 3 modes total? Or is the idea that you need a groundstation to change modes, in addition to the RC TX?

**Comment by dagar** [comment]
Don't let me distract you from actually working on this. It's a relatively small architectural change we could make later that provides some flexibility.

Vehicle commands are just orb messages. https://github.com/PX4/Firmware/blob/master/msg/vehicle_command.msg#L88

Commander would handle reading the switch (both new and "old" style) and publish a vehicle command which the position controller would pickup. We could also have mavlink commands for flips, etc that would become vehicle commands internally.

These days for the radio setup I use a 3 position switch for 3 modes and a separate switch for RTL. If I wanted more I'd mix 2 switches together, but I prefer to keep it simple.

**Comment by kd0aij** [comment]
@dagar I forgot that I could mix the two mode channels together in the DX7 also, but I don't see how that's simpler than the "old style". And it's definitely harder to reprogram my DX7 than the Taranis.

I'll leave things such as vehicle_commands for later, since the primary objective of this PR is to test the dynamic accuracy of attitude estimators without a Vicon system; the first "sequence" for that will be a coordinated turn. 

I also need to figure out how to compare jMAVsim's "ground truth" vehicle attitude to the onboard attitude estimate to automate (and quantify) the dynamic errors.

**Comment by kd0aij** [comment]
It looks like I could use the mavlink connection between jmavsim and the autopilot to send vehicle.attitude to the autopilot for logging in a new topic named something like "simulated_attitude" or "groundtruth_attitude". That would make it easy to compare the estimated attitude (vehicle_attitude) with simulated attitude. 

Would this be the best approach? Any advice would be appreciated.

**Comment by dagar** [comment]
That could work, but there's probably more boilerplate involved than it's worth. What about just dumping it to a file and then import everything into matlab or octave?

**Comment by kd0aij** [comment]
I thought about that, but it looks easy to add a HIL_STATE_QUATERNION message to MAVLinkHILSystem.java. That and a new uORB topic on the PX4 side would let me use FlightPlot to do the comparison, without having to mess with Octave.

**Comment by LorenzMeier** [comment]
@kd0aij Adding HIL ground truth to the log makes a lot of sense.

**Comment by kd0aij** [comment]
Publishing simulated attitude to instance 1 of uORB topic vehicle_attitude breaks LPE and QGC's attitude display. LPE is explicitly subscribing to instance 0, so I don't see why it should be affected. 
Will it be necessary to create a separate topic for publishing simulated vehicle_attitude, or am I doing something wrong?

**Comment by bkueng** [comment]
@kd0aij If the simulator is the first one to publish, it will get instance 0. You can create a separate topic eg. by adding a line `# TOPICS vehicle_attitude_groundtruth` to `vehicle_attitude.msg`, and then publish to this. This would also make it easy to distinguish in the log file.
It will need https://github.com/PX4/Firmware/pull/5323 to be merged.

**Comment by kd0aij** [comment]
@bkueng Thanks, that's working much better now

**Comment by kd0aij** [comment]
Seems to be working properly now with simulator "ground truth" logged. EKF2 is showing smaller error accumulation than the Q estimator during banked turns, as expected (y scale is degrees and deg/sec):
banked_circle_ekf2
banked_circle_lpe

**Comment by jgoppert** [comment]
@kd0aij This is great! Going to be awesome to have ground truth.

**Comment by kd0aij** [comment]
@jgoppert see https://github.com/PX4/jMAVSim/pull/33 for the changes to jMAVSim and jMAVlib
I'm not sure why Travis is failing.
I'll pull the Firmware changes for ground truth logging into a separate PR also.

**Comment by kd0aij** [comment]
New PR against latest master with just the jmavsim groundtruth logging (only via the new logger): https://github.com/PX4/Firmware/pull/5492

**Comment by kd0aij** [comment]
replaced by https://github.com/PX4/Firmware/pull/5498

**Pull request closed without merging**
