### PR TITLE
UAVCAN hardpoint control WIP

### PR DESCRIPTION
**Pull request by pavel-kirienko**
We're working with @ctech4285 on controlling [EPM] (www.docs.zubax.com/opengrab_epm_v3) via UAVCAN from APM.

I will comment here once this PR is ready for final review/merge.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
This is ready for review (but not for merge yet). We added a new IOCTL - `UAVCANIOC_HARDPOINT_SET`, which will be used from APM to control the hardpoint.

**Comment by LorenzMeier** [comment]
Let me know once this has left the WIP state.

**Comment by LorenzMeier** [comment]
Still WIP?

**Comment by pavel-kirienko** [comment]
This is ready.

**Comment by pavel-kirienko** [comment]
@LorenzMeier Can we have this merged?

**Comment by pavel-kirienko** [comment]
I'm asking because there's another upcoming contribution that requires IOCTL in the UAVCAN driver, which is first introduced here.

**Comment by pavel-kirienko** [comment]
Can we please merge this.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
