### PR TITLE
Update sitl gazebo to use new flow repo

### PR DESCRIPTION
**Pull request by ChristophTobler**
I also added a config file for ekf2/flow

### CODE REVIEW

**Comment by ChristophTobler** [comment]
The "continuous-integration/sitl/pr" fails because it tries to build a file (feature_tracker_node.cpp) which it should not. It is part of the klt_feature_tracker submodule (Optical flow repo) and the CMakeLists.txt states that it should not be build if it is not catkin:
```
if(CATKIN_BUILD)
    ## Declare a C++ executable
    add_executable(feature_tracker_node
      src/nodes/feature_tracker_node.cpp
    )
```
Therefore it is not a problem on my desktop. I'm not sure how the CI handles that...

I have no idea why "semaphoreci" fails. There isn't even code that astyle could complain about.

@LorenzMeier any ideas?

**Comment by jgoppert** [comment]
@ChristophTobler CI is built using a catkin workspace.

**Comment by jgoppert** [comment]
@ChristophTobler I didn't know we had a new repo for flow. This still simulates using the px4flow code correct?

**Comment by ChristophTobler** [comment]
@jgoppert hm ok. The file it can't find is normally created by catkin in devel/... so it should still work, no?
It is a new repo so we don't duplicate code. Yes it still has the PX4Flow code but also a OpenCV version.

**Comment by jgoppert** [comment]
@ChristophTobler ok, great. The catkin workspace is created normally and is created directly above the firmware folder, you can try it locally using:

```bash
./integrationtests/run_tests.bash
```

Yes, this will create the devel folder etc. so it should work normally and create any files you need, not sure why it isn't.

When you setup the launch file for ekf2 I don't think that ekf2 supports only flow navigation so you may run into problems if you disable gps.

**Comment by ChristophTobler** [comment]
@jgoppert I ran ```./integrationtests/run_tests.bash``` and I didn't get any errors. The file "catkin/devel/include/klt_feature_tracker/TrackFeatures.h" has been built as expected. However I got a warning " [WARNING] klt_feature_tracker is not found in workspace" but this package gets built right after that. Could you maybe try to run the test with this PR on your desktop?

With the parameter EKF2_AID_MASK = 2 the estimator should just use optical flow and no GPS. So I guess it should be possible

**Comment by LorenzMeier** [comment]
So let's see how this performs with the updated submodule.

**Comment by LorenzMeier** [comment]
Compilation fails:

```
/job/catkin/src/mavlink_sitl_gazebo/external/OpticalFlow/external/klt_feature_tracker/src/nodes/feature_tracker_node.cpp:45:47: fatal error: klt_feature_tracker/TrackFeatures.h: No such file or directory
 #include "klt_feature_tracker/TrackFeatures.h"
```

**Comment by ChristophTobler** [comment]
@LorenzMeier I know. The file ```feature_tracker_node.cpp``` does not get built with a normal make because it just gets built using catkin. But even when trying ```./integrationtests/run_tests.bash``` I could not reproduce this locally. The missing file should exist in ```catkin/devel/include/klt_feature_tracker/TrackFeatures.h```

**Comment by LorenzMeier** [comment]
I'm pretty sure your include path search is incorrect. Are you using `#include "header.h"` in a place where you should be using `#include <header.h>`? Or are you not adding the directory to the include path? Or are you adding the directory of the header to the path but you search for it using `dir/header.h` instead of plain `header.h`? That would explain why things go wrong. You might just get lucky on your local directory setup.

**Comment by ChristophTobler** [comment]
It's in a submodule from AIT that I use for the optical flow repo. But I'm on it

**Comment by ChristophTobler** [comment]
@LorenzMeier I cannot reproduce this error on any machine with ```./integrationtests/run_tests.bash``` nor in a normal catkin workspace. Could be that the ROS distro makes the difference, but I don't think so.
```#include "klt_feature_tracker/TrackFeatures.h"``` seems to be correct since this file is created in catkin/devel/include/... and this directory is in the cmake include_directories.

One possibility would be to fork https://github.com/ethz-ait/klt_feature_tracker with PX4, get rid of the catkin stuff that we don't need anyways and include this as a submodule. I'm not a fan of solving the problem this way but It would solve the problem immediately.

**Comment by ChristophTobler** [comment]
@LorenzMeier Fixed the issue in klt_feature_tracker

**Comment by jgoppert** [comment]
From my testing so far this PR degraded optical flow based missions in SITL. From what I see it isn't reporting flow consistently:

I think we need to work towards getting the flow test for the iris running for the CI.

```bash
Number of good matches: 5, desired: 9
WARN  [iekf] flow fault: beta     8.6385
Number of good matches: 8, desired: 15
WARN  [iekf] flow fault: beta     3.0486
Number of good matches: 11, desired: 20
Number of good matches: 6, desired: 19
WARN  [iekf] flow fault: beta     2.2843
Number of good matches: 5, desired: 20
WARN  [iekf] flow fault: beta    15.6648
Number of good matches: 3, desired: 22
Number of good matches: 3, desired: 25
Number of good matches: 5, desired: 25
WARN  [iekf] flow fault: beta     9.5254
Number of good matches: 1, desired: 25
```

**Comment by ChristophTobler** [comment]
@jgoppert 

Sorry it took me so long to respond too, but I was sick the last week...

* We had a discussion on the sign convention and agreed on this: https://github.com/PX4/Firmware/pull/6212. So to be honest I'm not sure what the IEKF is. It is not the ekf2, right? Because we changed the sign convention in inav and lpe to be the same as ekf2 and the default ```SENS_FLOW_ROT``` to be ```6```, so the same setup can be used as before (PX4Flow Y pointing in the heading direction). So maybe this is an estimator that was not considered?

* I defaulted to OpenCV flow because I had the impression that it is more precise. Is there maybe also an issue because of the scaling? Because if I remember correctly, inav and lpe used a scaling factor of 1.3 for flow measurements.

**Comment by ChristophTobler** [comment]
@jgoppert I saw that I did a small error in the px4flow calculation https://github.com/PX4/sitl_gazebo/pull/76. That should improve results. Can you confirm?

**Pull request merged**
