### PR TITLE
[WIP] Added TI ina226 I2C power monitor

### PR DESCRIPTION
**Pull request by davids5**
@dagar - prelim for discussion on how to factor in this part and finally refactor the batery_status system_power. 

There is extra raw values as debug code in the msg for now.

### CODE REVIEW

**Comment by dagar** [comment]
What are the desired use cases?
 - how should a system with both analog power bricks and ina226 power monitors be configured?
 - multiple ina226 power monitors?

**Comment by davids5** [comment]
@dagar Long term analog will go away. This will replace that function. 1 per brick on separate buses.

**Comment by davids5** [comment]
Address changed to 0x41 to match latest HW.  Re based on master

**Comment by bys1123** [comment]
I brought one, glad to test this driver later, my module have a R100(0.1ohm) regsister on it, looks like it's too big for drone, I need to change it. Happy to see there is a shunt parameter for this sensor.

**Comment by bys1123** [comment]
image
R100 is dead.

**Comment by bys1123** [comment]
I used a wrong formula earlier. Right way to calculate the power of this resistor is `P=I²R`

**Comment by davids5** [comment]
@dagar were you going to merge this?

**Comment by bys1123** [comment]
1. Looks like it's not working
image

image
Parameters shows up, but
1. the shunt value can't storage below “0.001”
2. They are not showing in Sensors group.

**Comment by davids5** [comment]
@bys1123 What flight controller and what connector did you plug it into?

**Comment by bys1123** [comment]
@davids5 It's Pixhawk4, on I2C A port.

**Comment by bys1123** [comment]
image
Looks like the default address is 0x40.

**Comment by davids5** [comment]
The board I am testing is at 0x41, we should add a scan and a range.

**Comment by davids5** [comment]
You can change this [line](https://github.com/PX4/Firmware/pull/11755/commits/bb6340d32c21d7ff297402af560ec8357b428a07#diff-4920b5dd81390b42dd6c201706a8120dR71)  for now

**Comment by bys1123** [comment]
OK, no problem. I'm try it later.

**Comment by bys1123** [comment]
Do you think scan this large range would cause other issue? Maybe a parameter for this address is better? Just a suggestion, let's find out.

**Comment by bys1123** [comment]
image
image
It's working (I didn't connect battery now.)

**Pull request merged**
