### PR TITLE
 DeltaTag: enhanced geo-referencing survey images

### PR DESCRIPTION
**Pull request by sanderux**
DeltaTag provides an alternate method to geo-referencing images from survey missions.
It uses the delta in seconds between the images and the delta between the triggers to 
match geo information with pictures, allowing for missing images.

It uses the last image and last trigger event as a calibration point as errors are
more likely to arise in the first images (test triggers, booting cameras, etc)

Note: DeltaTag does not make copies, it writes the Exif information directly to the images

Install: pip install pyulog piexif Pillow numpy
Run: python geotag_images_ulog.py [logfile] [image dir] (optional offset)
eg: python geotag_images_ulog.py mylog.ulg ./images

Parameters
logfile: a ulog formatted logfile containing camera_capture events (survey missions)
image_dir: the directory where the images are located
offset (optional): skip [offset] triggers to reference the last image
                   0 means the last trigger event equals last image (default)
                   1 means the second last trigger event equals last image
                   ...etc

### CODE REVIEW

**Comment by dagar** [comment]
As it's just a script sitting in `Tools/` could we consider giving it an overly descriptive self explanatory name? Something like `geotag_photos_ulg.py` perhaps.

**Comment by sanderux** [comment]
@dagar done

**Comment by Antiheavy** [comment]
Very cool @sanderux. Do you know if anyone plans to implement this in QGC?

**Comment by IeiuniumLux** [comment]
@sanderux, Does the DeltaTag (geotag_images_ulog.py) require that the camera date/time is set to the current local time in UTC?  That way the script can match the log **time_utc**  with the image exif **Date/Time Original** value, is that how it works?

**Comment by sanderux** [comment]
@IeiuniumLux no it assumes the last picture is equal to the last trigger event and uses the time difference (deltas) between the pictures irrespective of the time setting on the camera.

**Comment by kosakwayne** [comment]
@sanderux Is DeltaTag written for Python2? When running in Python 3 I had to make changes to print statements as well as change line 189 to: 
timestamp = time.mktime(datetime.datetime.strptime(timestring.decode("utf-8"), "%Y:%m:%d %H:%M:%S").timetuple())

**Comment by sanderux** [comment]
@kosakwayne Yes indeed i wrote it on Python2.7 bases.
I would very much welcome a PR making it compatible with both 2 & 3

**Pull request merged**
