### PR TITLE
Update LPE SITL init script.

### PR DESCRIPTION
**Pull request by jgoppert**
Some minor changes to the LPE init script to get it working in sim with optical flow again.

### CODE REVIEW

**Comment by TSC21** [comment]
@jgoppert we should also check why we don't get a proper Z estimation when we don't fuse baro. There are a lot of issues of people having that same issue.

**Comment by TSC21** [comment]
Jenkins test this please.

**Comment by TSC21** [comment]
@jgoppert can you check what is happening with `clang` CI?

**Comment by jgoppert** [comment]
@TSC21 where is the clang issue, it looks like passed CI to me.

This is just for SITL and simple fixes so it would work with optical flow SITL for me again. I don't want to hold this up trying to address something else.

**Comment by TSC21** [comment]
> @TSC21 where is the clang issue, it looks like passed CI to me.

After closing and opening again it passed somehow.

> This is just for SITL and simple fixes so it would work with optical flow SITL for me again. I don't want to hold this up trying to address something else.

Yeah I know I just wanted to make reference to it so we can solve it later.

**Pull request merged**
