### PR TITLE
df_bmp280_wrapper: use mBar

### PR DESCRIPTION
**Pull request by ustbguan**

### CODE REVIEW

**Comment by julianoes** [comment]
Hi, thanks for the pull request.

However, I disagree with the change because the `baro_sensor_data` should be in Pascals (Pa) according to https://github.com/PX4/DriverFramework/blob/0b9afafa2e05ae3899c6d38231196ace265003b2/framework/include/BaroSensor.hpp#L50.

Why did you need this change? Where was it wrong?

**Comment by mhkabir** [comment]
@julianoes I suppose it was confusion with this : https://github.com/PX4/Firmware/blob/master/msg/sensor_baro.msg#L1

**Comment by ustbguan** [comment]
Hi julianoes, I found this issue on snapdragon, because pressure will convert to Pascals in sensor module (https://github.com/PX4/Firmware/blob/master/src/modules/sensors/voted_sensors_update.cpp#L785). Otherwise the height of QGC will be very wrong. And bmp280 driver under src folder also does the same (https://github.com/PX4/Firmware/blob/master/src/drivers/bmp280/bmp280.cpp#L546).

**Comment by julianoes** [comment]
@ustbguan Oh yes, you are right. I confused the different baro topics.

`baro_report`is `sensor_baro_s` according to 
https://github.com/PX4/Firmware/blob/4453e4201b7a245cff52beeb38a293161aea4c48/src/drivers/drv_baro.h#L54 which is in millibar, as @mhkabir pointed out in https://github.com/PX4/Firmware/blob/master/msg/sensor_baro.msg#L1.

@ustbguan can you confirm that it is correct with Snapdragon with this change?

**Comment by ustbguan** [comment]
@julianoes Now it's midnight, I'll confirm it again and tell you the result tomorrow.

**Comment by ustbguan** [comment]
@julianoes Before change：


After change:

**Comment by julianoes** [comment]
@ustbguan so -40m is in the correct range?

**Comment by ustbguan** [comment]
@julianoes It is close to pressure_alt of ms5611.

**Comment by julianoes** [comment]
Thank you @ustbguan for following up.

**Pull request merged**
