### PR TITLE
Changes in firmware for lidar and optical flow in sitl_gazebo

### PR DESCRIPTION
**Pull request by ChristophTobler**

### CODE REVIEW

**Comment by ChristophTobler** [comment]
@LorenzMeier Why is it failing in Tools/sitl_gazebo? The commit d93aadd80c4b5dede772dc9df272d2dca239aaab is the one I did in the submodule.

**Comment by andre-nguyen** [comment]
@ChristophTobler That commit only exists in a branch in your own repository. It needs to be merged in to the main repository https://github.com/PX4/sitl_gazebo and the submodule commit hash in the px4/firmware repository has to be updated.

**Comment by andre-nguyen** [comment]
Ah I get it, this https://github.com/PX4/sitl_gazebo/pull/15 needs to be merged in for the build to work.

**Comment by mhkabir** [comment]
@ChristophTobler Looks like you also have the changes from a different PR in here.

I'd suggest you create two different branches, and [cherry-pick](https://git-scm.com/docs/git-cherry-pick) your last commit over to a branch and re-open this PR from that. 

You should make *your* master branch track Firmware master verbatim, and branch off that when required, instead of directly committing to master and opening PRs against that.

**Comment by mhkabir** [comment]
@ChristophTobler Looks like you'll need to update your submodule to point to the new sitl_gazebo HEAD in order for the integration tests to pass.
Thanks!

**Comment by mhkabir** [comment]
I just tried this PR out, after updating the submodule, etc. Bad crash happens here : 
```
gzserver: /usr/include/boost/smart_ptr/shared_ptr.hpp:653: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = gazebo::physics::Joint; typename boost::detail::sp_member_access<T>::type = gazebo::physics::Joint*]: Assertion `px != 0' failed.
```

**Comment by LorenzMeier** [comment]
I just re-tried, same here on Mac OS. @ChristophTobler What is remarkable is that it fails even for the basic Iris model. Can you diff your changes against the last commit without them and work out what change you introduced killed it? In theory the base Iris model (and plugins not concerning the laser) should have a zero diff.

**Comment by ChristophTobler** [comment]
OK. Yes, I'll have a look at it

**Comment by ChristophTobler** [comment]
Closed. changes are in https://github.com/PX4/Firmware/pull/3532

**Pull request closed without merging**
