### PR TITLE
fw att: add param to select yawrate control method

### PR DESCRIPTION
**Pull request by thomasgubler**
@kd0aij @LorenzMeier As discussed in https://github.com/PX4/Firmware/pull/1533

Depends on and includes https://github.com/PX4/Firmware/pull/1564

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I glanced over it and its looking good. I think with some flight testing from @kd0aij and @sjwilks this should go in.

Note that the coordinated turn method selection makes sense, but eventually I'd like to cut down the number of parameters in the system, so we should select and stick to one within the next few weeks. If the parameter space is too complex we will have a very hard time at providing maintained and operational configs, and flight performance will deteriorate.

**Comment by thomasgubler** [comment]
@LorenzMeier: I agree, but if we set a default param value in the code most users won't notice and we don't have to maintain configs. However, those who want to experiment or have their own ideas/preferences can easily switch and extend.

**Comment by thomasgubler** [comment]
@kd0aij I added the method you described in the comments of the other thread here as a starting point

**Comment by kd0aij** [comment]
@thomasgubler Thanks, it's still beyond my skill level with git to merge your changes with my own branch (I tried and screwed it up :8ball: )
Regarding source formatting; indentation seems wrong at e.g. line 172 of ecl_yaw_controller.cpp
I normally use the auto-formatter in the Eclipse CDT editor, but I'm not sure how to apply the "PX4 code style" referenced on this page: https://pixhawk.org/dev/code_style

**Comment by sjwilks** [comment]
I only have flying wings with an autopilot at the moment so I won't be able to test this for now.

**Comment by LorenzMeier** [comment]
@kd0aij Any news on the testing level of this?

**Comment by LorenzMeier** [comment]
@thomasgubler I tried to merge master and get a bunch of merge fails. Looks like auto-formatting gone nuts :(.

**Comment by thomasgubler** [comment]
Not all commits have been cherry-picked to #1663, re-opening

**Comment by thomasgubler** [comment]
@LorenzMeier looking at the merge problem here: git doesn't get that the commits from #1564 are also included here somehow...

**Comment by LorenzMeier** [comment]
I'll leave it to you to resolve this properly then, feel free to close duplicates.

**Comment by thomasgubler** [comment]
@lorenzmeier, rebased on master

**Comment by thomasgubler** [comment]
@kd0aij can you port your changes to here, without the  whitespace/formatting commits please ;-)

**Comment by kd0aij** [comment]
kd0aij/yawratemethods compares correctly with PX4/yawratemethods now, but my Xplane9 simulation is no longer behaving in a sensible manner. Getting continuous messages in the Xplane console:
```src/comm/QGCXPlaneLink.cc556 UDP datagram overflow, allowed to read less bytes than datagram size```
Not sure whether I broke my code doing the port or whether my HILSIM setup is broken, but the closed loop method is not usable at the moment.

**Comment by LorenzMeier** [comment]
Doesn't build in Travis.

**Comment by thomasgubler** [comment]
Tried to rerun travis but I still get:

`The command "eval git clone --depth=500 --branch=yawratemethods2 git://github.com/PX4/Firmware.git PX4/Firmware" failed. Retrying, 2 of 3.`

No idea why travis wants to get yawratemethods2 (does not exist anymore and was not associated with this PR)

I am going to close and re-open the PR to see if it helps.

**Comment by thomasgubler** [comment]
Now travis started running but it downloaded the master branch. Something is terribly broken here...
Actually travis built this branch (passed) already yesterday: https://travis-ci.org/PX4/Firmware/builds/47492041

**Comment by LorenzMeier** [comment]
@kd0aij @thomasgubler What happened to this PR?

**Comment by thomasgubler** [comment]
well the basic method selection should be good to merge, if we don't change the params the behavior should not change

**Comment by LorenzMeier** [comment]
Ok, could you rebase and merge it then? How do we proceed in testing so we end up setting the right default?
@kd0aij If you could do a bit more flight testing we can then set the default accordingly / correctly.

**Comment by thomasgubler** [comment]
@LorenzMeier rebased

We can leave the default at 0 and switch once we have done our development/research. There is no need to hurry ;-)

**Comment by LorenzMeier** [comment]
Merge at will when Dr. Travis and Dr. Hans are ok with it.

**Comment by kd0aij** [comment]
Regarding my status: I ran into problems 22 days ago (see above) with HILSIM when trying to validate my last code changes. I posted some questions regarding QGC and Xplane9 and am waiting for a solution before continuing work on the closed loop method.

**Comment by LorenzMeier** [comment]
Would you mind digging up the link or filing / commenting on an issue? Don is back and might be able to help. @DonLakeFlyer.

**Comment by kd0aij** [comment]
opened QGC issue 1224; @LorenzMeier had you noticed 1180? I had to add a new rotation for my Caipirinha_VTOL and a trial-and-error session picking existing rotations using QGC was quite confusing :)

**Pull request closed without merging**
