### PR TITLE
Fixes shared memory locking bug and 

### PR DESCRIPTION
**Pull request by jywilson**
eliminates the need for an AppsProc driver to reserve a shared memory region.  Submitted on behalf of Weizhang Luo.

### CODE REVIEW

**Comment by julianoes** [comment]
Thanks @jywilson for submitting this!

It looks like you'll need to run some more astyle:
```
Checking formatting with astyle
src/modules/muorb/adsp/px4muorb.cpp bad formatting, please run "./Tools/fix_code_style.sh src/modules/muorb/adsp/px4muorb.cpp"
src/modules/muorb/krait/px4muorb_KraitRpcWrapper.cpp bad formatting, please run "./Tools/fix_code_style.sh src/modules/muorb/krait/px4muorb_KraitRpcWrapper.cpp"
src/platforms/posix/px4_layer/shmem_posix.c bad formatting, please run "./Tools/fix_code_style.sh src/platforms/posix/px4_layer/shmem_posix.c"
src/platforms/qurt/px4_layer/shmem_qurt.c bad formatting, please run "./Tools/fix_code_style.sh src/platforms/qurt/px4_layer/shmem_qurt.c"
```

**Comment by jywilson** [comment]
I will fix the style issues, but it would be easier if the offending output from astyle were included in the build log.

**Comment by julianoes** [comment]
@jywilson but running the script will show you anyway.

**Comment by jywilson** [comment]
@julianoes I agree running the tool will show me the output, but I shouldn't have to run the tool.  Why not just include it in the build output?  Saves me the trouble of installing it on my workstation.

**Comment by julianoes** [comment]
@jywilson Oh, I see your point. If you don't want to go through the trouble I can close this PR and open a new one with a astyle commit on top.

**Comment by jywilson** [comment]
@julianoes Thanks for the offer, but I went ahead and ran the tool on the files indicated.

**Comment by julianoes** [comment]
I just bench tested this again on my Snappy, and it all seemed to work as expected.
I've rebased the commits to master. Thanks @jywilson for making this PR.

**Comment by jywilson** [comment]
Thanks @julianoes for your help with this PR!

**Pull request closed without merging**
