### PR TITLE
Mavros update

### LINKED ISSUE #1979: Test and fix SITL with latest MAVROS
Lots of changes in latest MAVROS, e.g. changed plugin configuration and renamed topics
Need to update launch files and tests.

### PR DESCRIPTION
**Pull request by AndreasAntener**
**WIP**
@thomasgubler : this updates tests and demo nodes for MAVROS 0.11
More fixes are coming (another NS change) as soon as I get 0.11.1 on Ubuntu, will wait for that before merging.
Fixes #1979

### CODE REVIEW

**Comment by AndreasAntener** [comment]
Needs PX4/containers/pull/12

**Comment by AndreasAntener** [comment]
Looks good on my local installation, will merge as soon as the container on Docker hub is built.

**Comment by AndreasAntener** [comment]
SITL CI: test this please

**Comment by thomasgubler** [comment]
Thanks for doing the update :+1:

**Pull request merged**
