### PR TITLE
px_uploader.py: try to follow PEP8

### PR DESCRIPTION
**Pull request by julianoes**
This fixes some non-Pythonic things and unneccessary semicolons.

Still to fix are line-length and multiple spaces before operators.

### CODE REVIEW

**Comment by julianoes** [comment]
Tested on macOS 10.11, works as well.

**Comment by dagar** [comment]
Was this done manually or with a script?

**Comment by julianoes** [comment]
@dagar: manually

**Comment by dagar** [comment]
We could run all of the python scripts through autopep8 or something, but I'd guess the change would be massive.

**Pull request merged**
