### PR TITLE
Removed special scaling for throttle in HIL

### LINKED ISSUE #5787: Throttle scaled differently in SIL and HIL
Throttle is treated like all other outputs when scaled for HIL_ACTUATOR_CONTROLS messages in SIL (see Simulator::pack_actuator_message() in src/modules/simulator/simulator_mavlink.cpp).

Throttle is scaled 0 to 1 instead of -1 to 1 when publishing messages in HIL mode (see MavlinkStreamHILActuatorControls::send() in src/mavlink/mavlink_messages.cpp).

A fix would be to remove the special scaling for throttle when in HIL mode.  Ensuring scaling is -1 to 1 should happen by clamping the output in the mixer.  This ensures flexibility in which output index is the throttle.

### PR DESCRIPTION
**Pull request by evanmw**
Fixes #5787

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Against which HIL interface did you test this?

**Comment by evanmw** [comment]
Actually using Gazebo and piping messages with Mavros, so not one of the supported setups.  I'm not setup to check it with X-Plane; if someone else could that would be great.

**Comment by bartslinger** [comment]
I guess this will break HIL with x-plane. Will try to have a look at this tomorrow.

**Comment by LorenzMeier** [comment]
@bartslinger Could you test?

**Comment by bartslinger** [comment]
I was confused because of https://github.com/PX4/Firmware/issues/5787 and https://github.com/PX4/Firmware/pull/5716

I cannot test at this moment, but by looking at the code I can tell that it will not work correctly. Throttle in X-Plane is scaled 0:1. Actuators in X-Plane are scaled -1:1. It will need a fix here as well: https://github.com/mavlink/qgroundcontrol/blob/master/src/comm/QGCXPlaneLink.cc#L469

**Pull request closed without merging**
