### PR TITLE
Fix mixer test

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! I've applied most of this.

**Comment by dagar** [comment]
@LorenzMeier what about the RC lost and regained messages? https://github.com/PX4/Firmware/pull/4231/commits/9dac994fb1eb7268abd4440a74ce314799c226b6#diff-1d51a813dcb26f46616f71f28aacc70dR2278

**Comment by LorenzMeier** [comment]
Floating point printing is eval and error prone. We're not doing that in safety critical parts.

**Comment by dagar** [comment]
Makes sense. Thanks

**Pull request closed without merging**
