### PR TITLE
Adding vertical (Z) velocity to inav estimator

### PR DESCRIPTION
**Pull request by dyeldandi**
This is needed for high-accuracy GNSS sensors (like Ashtech MB100 we are using). It allows copter to maintain better altitude stability.

Basically copying horizontal code.

Here is the log http://dash.oznet.ch/view/wxpvxAKYstGZjXvkKTSkye

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Could you provide a more detailed analysis / logs if this actually improves flight performance? We would need plots of the GPS velocity and flights with and without. I'm concerned that in noisy GPS reception situations this patch can deteriorate flight performance as GPS altitude is much more affected than position once the signal quality / sky view deteriorates.

**Comment by DrTon** [comment]
By default the weight for Z velocity can be 0. It needed only for RTK receivers, where altitude accuracy is ~10cm, in this case using velocity may be very useful.

**Comment by anatolfilin** [comment]
We've done lots of flying with and without this patch. We tested with regular Ublox and with Ashtech GPS board. We also played with various combinations of INAV_W_Z_GPS_P/INAV_W_Z_GPS_V/INAV_W_Z_GPS_BARO. The majority of tests were performed before merging Anton's L1 into trunk on MPC_TRACK branch. We haven't noticed any deterioration of quality. However there wasn't definite result on improving quality either. We just didn't have enough time before we stopped flying due to winter. I have plenty of log files with this patch showing very good vertical precision, but can't isolate effect of this particular patch vs overall quality of algorithm / hardware.

**Comment by LorenzMeier** [comment]
Ok. Happy to merge with default weight set to zero then.

**Comment by dyeldandi** [comment]
> Ok. Happy to merge with default weight set to zero then.

Default is changed to zero.

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by anatolfilin** [comment]
Thanks a lot!

**Pull request merged**
