### PR TITLE
Merged master_uavcan_modular src/modules/uavcan/

### PR DESCRIPTION
**Pull request by davids5**
This is the beta compatible version  of  [Integration of the multithreaded version of the uavcan module that saves on memory] (https://github.com/PX4/Firmware/pull/2440)

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@pavel-kirienko Can we focus the integration testing on this branch? This would ensure we're able to deploy it in a reasonable time frame. I also merge this branch regularly to master.

**Comment by LorenzMeier** [comment]
@davids5 I lean towards not merging your master PR and merging this to master - do you feel this will work?

**Comment by davids5** [comment]
@LorenzMeier That was my first approach, but master has px4_config etal changes. The deltas from the master PR to this one are minimal. The master PR is superior in that it uses the RingBuffer name space changes and nullptr.

**Comment by LorenzMeier** [comment]
@pavel-kirienko What I need here is a PR based on this which updates uavcan and which is *tested* against the current up-to-date version for the Zubax GPS (including having the bootloader on it!). If any user of UAVCAN upgrades with current beta he should end up with a working and auto-upgrading GPS as a result.

I'm trying to fix the software support for your customers, and so you should really care about making sure it works well and can be upgraded in the future remotely. We can initially redistribute the Firmware for the GPS in the ROMFS (assuming its small) and then switch to the proper distribution mechanism.

Note that I think its more important to validate the Pixhawk ESC v1.6 hardware, so if you have to split time between those things, please focus on the ESC bringup first and I'll hold off with the release for a few days longer.

**Comment by davids5** [comment]
@pavel-kirienko - testing this against master @4238df3e9fe4a01b22d55fb7088319017bdbab8b

Do the log messsage make sense to you?

```
UAVCAN: CanIOManager: Memory blocks per iface: 4097, total: 8192
UAVCAN: GlobalDataTypeRegistry: Frozen; num msgs: 2, num srvs: 4
UAVCAN: GenericSubscriber: Start as service request listener; dtname=uavcan.protocol.GetNodeInfo
UAVCAN: NodeStatusProvider: Status pub period: 1.000000, TX timeout: 0.950000
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
UAVCAN: TransferReceiver: Restart [ni=1, isa=1, tt=1, si=0, ff=1, nwtid=1, nptid=1, tid=0], prio=16 dtid=341 tt=2 snid=122 dnid=0 sot=1 eot=1 togl=0 tid=1 payload=[21 00 00 00 00 00 00] ts_m=4059.888290 ts_utc=1437593666.591990 iface=0
UAVCAN: TransferReceiver: Restart [ni=1, isa=1, tt=1, si=0, ff=1, nwtid=1, nptid=1, tid=0], prio=16 dtid=341 tt=2 snid=1 dnid=0 sot=1 eot=1 togl=0 tid=5 payload=[c5 00 00 00 00 00 00] ts_m=4059.944159 ts_utc=1437593666.647853 iface=0
UAVCAN: NodeStatusProvider: NodeStatus pub skipped - passive mode
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
 1   |[32m OPERATIONAL     [39m|[32m OK       [39m| 197        | 0000  00000000'00000000  0
 122 |[32m OPERATIONAL     [39m|[32m OK       [39m| 33         | 0000  00000000'00000000  0
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
 1   |[32m OPERATIONAL     [39m|[32m OK       [39m| 197        | 0000  00000000'00000000  0
 122 |[32m OPERATIONAL     [39m|[32m OK       [39m| 33         | 0000  00000000'00000000  0
UAVCAN: TransferReceiver: Restart [ni=0, isa=1, tt=1, si=1, ff=1, nwtid=1, nptid=0, tid=2], prio=16 dtid=341 tt=2 snid=122 dnid=0 sot=1 eot=1 togl=0 tid=2 payload=[22 00 00 00 00 00 00] ts_m=4060.888346 ts_utc=1437593667.592061 iface=0
UAVCAN: TransferReceiver: Restart [ni=0, isa=1, tt=1, si=1, ff=1, nwtid=1, nptid=0, tid=6], prio=16 dtid=341 tt=2 snid=1 dnid=0 sot=1 eot=1 togl=0 tid=6 payload=[c6 00 00 00 00 00 00] ts_m=4060.944475 ts_utc=1437593667.648189 iface=0
UAVCAN: NodeStatusProvider: NodeStatus pub skipped - passive mode
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
 1   |[32m OPERATIONAL     [39m|[32m OK       [39m| 198        | 0000  00000000'00000000  0
 122 |[32m OPERATIONAL     [39m|[32m OK       [39m| 34         | 0000  00000000'00000000  0
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
 1   |[32m OPERATIONAL     [39m|[32m OK       [39m| 198        | 0000  00000000'00000000  0
 122 |[32m OPERATIONAL     [39m|[32m OK       [39m| 34         | 0000  00000000'00000000  0
UAVCAN: NodeStatusProvider: NodeStatus pub skipped - passive mode
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
 1   |[32m OPERATIONAL     [39m|[32m OK       [39m| 199        | 0000  00000000'00000000  0
 122 |[32m OPERATIONAL     [39m|[32m OK       [39m| 34         | 0000  00000000'00000000  0
UAVCAN: TransferListener: Timed out receiver: nid=122 tt=2
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
 1   |[32m OPERATIONAL     [39m|[32m OK       [39m| 199        | 0000  00000000'00000000  0
 122 |[32m OPERATIONAL     [39m|[32m OK       [39m| 34         | 0000  00000000'00000000  0
UAVCAN: NodeStatusProvider: NodeStatus pub skipped - passive mode
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
 1   |[32m OPERATIONAL     [39m|[32m OK       [39m| 200        | 0000  00000000'00000000  0
 122 |[31m OFFLINE         [39m|[32m OK       [39m| 34         | 0000  00000000'00000000  0
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
 1   |[32m OPERATIONAL     [39m|[32m OK       [39m| 200        | 0000  00000000'00000000  0
 122 |[31m OFFLINE         [39m|[32m OK       [39m| 34         | 0000  00000000'00000000  0
UAVCAN: TransferReceiver: Restart [ni=0, isa=1, tt=1, si=1, ff=1, nwtid=1, nptid=0, tid=9], prio=16 dtid=341 tt=2 snid=1 dnid=0 sot=1 eot=1 togl=0 tid=9 payload=[c9 00 00 00 00 00 00] ts_m=4063.942380 ts_utc=1437593670.646093 iface=0
UAVCAN: NodeStatusProvider: NodeStatus pub skipped - passive mode
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
 1   |[32m OPERATIONAL     [39m|[32m OK       [39m| 201        | 0000  00000000'00000000  0
 122 |[31m OFFLINE         [39m|[32m OK       [39m| 34         | 0000  00000000'00000000  0
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
 1   |[32m OPERATIONAL     [39m|[32m OK       [39m| 201        | 0000  00000000'00000000  0
 122 |[31m OFFLINE         [39m|[32m OK       [39m| 34         | 0000  00000000'00000000  0
UAVCAN: NodeStatusProvider: NodeStatus pub skipped - passive mode
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
 1   |[32m OPERATIONAL     [39m|[32m OK       [39m| 202        | 0000  00000000'00000000  0
 122 |[31m OFFLINE         [39m|[32m OK       [39m| 34         | 0000  00000000'00000000  0
[1J[H NID | Mode            | Health   | Uptime [s] | Vendor-specific status code
-----+-----------------+----------+------------+-hex---bin----------------dec--
 1   |[32m OPERATIONAL     [39m|[32m OK       [39m| 202        | 0000  00000000'00000000  0
 122 |[31m OFFLINE         [39m|[32m OK       [39m| 34         | 
```

**Comment by pavel-kirienko** [comment]
@davids5 I don't see any issues in this log.

**Comment by pavel-kirienko** [comment]
### CAN timings configuration

@davids5 I could not reproduce the issue of incorrect bit timing configuration. The algorithm produced the BTR value of `0x40005`, which results in SPL value of 85.7%. The value of BTR has been sampled via debugger soon after its assignment [here](https://github.com/UAVCAN/libuavcan/blob/master/libuavcan_drivers/stm32/driver/src/uc_stm32_can.cpp#L511).

```python
>>> def sample_point_from_btr(x):
...     assert 0b0011110010000000111111000000000 & x == 0
...     ts2,ts1,brp = (x>>20)&7, (x>>16)&15, x&511
...     return (1+ts1+1)/float(1+ts1+1+ts2+1)
... 
>>> sample_point_from_btr(0x40005)
0.8571428571428571
```

### CAN TX problem in the bootloader

@davids5 Under uncertain circumstances, the bootloader stucks during transmission here:

```
Thread [1] (Suspended: Signal 'SIGINT' received. Description: Interrupt.)       
        13 can_tx() driver.c:256 0x08000f92     
        12 uavcan_tx() uavcan.c:293 0x08001324  
        11 uavcan_tx_dsdl() uavcan.c:360 0x08001324     
        10 node_status_process() main.c:297 0x0800031a  
        9 sched_process_timer() timer.c:218 0x08000c90  
        8 up_timerisr() stm32_timerisr.c:113 0x08001dae 
        7 irq_dispatch() irq_dispatch.c:103 0x08001ab2  
        6 up_doirq() up_doirq.c:102 0x08001a0c  
        5 exception_common() stm32_vectors.S:349 0x080000ae     
        4 exception_common() stm32_vectors.S:349 0x080000ae     
        3 exception_common() stm32_vectors.S:349 0x080000ae     
        2 exception_common() stm32_vectors.S:349 0x080000ae     
        1 exception_common() stm32_vectors.S:349 0x080000ae     
```

Context:

```c
void can_tx(uint32_t message_id, size_t length, const uint8_t *message,
	    uint8_t mailbox)
{
	uint32_t data[2];

	memcpy(data, message, sizeof(data));

	/*
	 * Just block while waiting for the mailbox.
	 */

	uint32_t mask = CAN_TSR_TME0 << mailbox;

	while (((getreg32(STM32_CAN1_TSR) & mask) == 0));  ///<<< HERE

	/*
	 * To allow detection of completion  - Set the LEC to
	 * 'No error' state off all 1s
	 */

	putreg32(CAN_ESR_LEC_MASK, STM32_CAN1_ESR);

	putreg32(length & CAN_TDTR_DLC_MASK, STM32_CAN1_TDTR(mailbox));
	putreg32(data[0], STM32_CAN1_TDLR(mailbox));
	putreg32(data[1], STM32_CAN1_TDHR(mailbox));
	putreg32((message_id << CAN_TIR_EXID_SHIFT) | CAN_TIR_IDE | CAN_TIR_TXRQ,
		 STM32_CAN1_TIR(mailbox));
}
```

I'm still on analyzing this.

**Comment by pavel-kirienko** [comment]
@davids5 Re the CAN TX problem in the bootloader described above. Steps to reproduce:

1. Using an STM32 in dual CAN bus configuration, connect it to the bus via CAN2, leaving CAN1 unused.
2. The bootloader will not detect any bus activity, since it doesn't use CAN2, and will subsequently boot the application.
3. The application will communicate with the firmware update server using CAN2.
4. The server will issue an update request, prompting the application to save its current bit rate and node ID into the BL/App shared memory, and then restart.
5. The bootloader will pick up the bus parameters from the application and then it will attempt to transmit a NodeStatus message; however, since the bus is not connected, the CAN controller will never release any TX mailbox, causing a deadlock in the interrupt handler as above.

This problem is unlikely to appear in a sealed application, but it must be fixed before release. I'm not ready yet to propose a valid fix, but probably a minor review of the CAN driver would suffice.

**Comment by LorenzMeier** [comment]
I've merged this PR, as the boot loader fix needs to happen in other branches / repos. I'm calling this a release now. Pavel, its up to you to now to provide the BL + application binary for your GPS customers 8).

**Comment by davids5** [comment]
@pavel-kirienko fyi: @LorenzMeier - the bootloader was designed to only boot on CAN1. I had noted the lack of a timeout  here [https://github.com/PX4/Firmware/issues/2596] before I left for vacation. It is fixed here https://github.com/PX4/Firmware/commit/15cf981ae54ce3c8611c33fe8caef38f7ae4f59f

**Pull request merged**
