### PR TITLE
Initial implementation SF10x driver

### PR DESCRIPTION
**Pull request by ecmnet**
This is a basic implementation for the Lightware SF10a laser range finder connected via I2C. Should work with all Sf10x series sensors. The implementation is based on the sonar implementation for SRF02

### CODE REVIEW

**Comment by ecmnet** [comment]
Tested in flight

**Comment by julianoes** [comment]
Thanks for the contribution, looks very clean!

One thing I'm wondering is why the driver runs at 40 Hz when the device seems to support only 32 Hz according to the [datasheet](http://www.lightware.co.za/shop/en/drone-altimeters/33-sf10a.html), or is this wrong?

**Comment by ecmnet** [comment]
You're right, the data sheet specifies a rate of 32 Hz, but at least my two devices run at 40 Hz without any issues.

**Comment by julianoes** [comment]
Hehe overclocking :) Do you mind adding a comment to the define which specifies this rate then?

**Comment by ecmnet** [comment]
I'll do that.

**Comment by ecmnet** [comment]
Additional note: This driver should also work with the Lightware SF11/c which has a wider range (0..120m)..

**Comment by LorenzMeier** [comment]
Nice! Will get this in now.

**Comment by LorenzMeier** [comment]
I cherry-picked these. I reverted to the device default rate. I recommend you change as well, because you might run into corner cases and crash your plane when you try to outsmart the manufacturer on absolute maximum ratings. It usually holds up until it doesn't, and then things go terribly wrong.

**Pull request closed without merging**
