### PR TITLE
[WIP] uORB topics autogeneration

### PR DESCRIPTION
**Pull request by dagar**
@DrTon @againagainst @kd0aij @jgoppert 
continuation of https://github.com/PX4/Firmware/pull/2780

### CODE REVIEW

**Comment by jgoppert** [comment]
@dagar This should do it. Only 2 errors left now:

```bash
Linking CXX executable firmware_nuttx
../../modules/logger/libmodules__logger.a(logger.cpp.obj): In function `px4::logger::Logger::add_all_topics()':
/home/jgoppert/git/Firmware/src/modules/logger/logger.cpp:189: undefined reference to `orb_get_topics()'
/home/jgoppert/git/Firmware/src/modules/logger/logger.cpp:190: undefined reference to `orb_topics_count()'
collect2: error: ld returned 1 exit status
```

Sorry about the git push -f

**Comment by jgoppert** [comment]
@dagar This builds now.

**Comment by jgoppert** [comment]
Looks like it still fails for ros though:

```bash
Firmware/CMakeFiles/attitude_estimator.dir/src/platforms/ros/nodes/attitude_estimator/attitude_estimator.cpp.o
/sitl/catkin_ws/src/Firmware/src/platforms/ros/nodes/attitude_estimator/attitude_estimator.cpp: In member function 'void AttitudeEstimator::ModelStatesCallback(const ModelStatesConstPtr&)':
/sitl/catkin_ws/src/Firmware/src/platforms/ros/nodes/attitude_estimator/attitude_estimator.cpp:98:12: error: 'px4::vehicle_attitude' has no member named 'timestamp'
  msg_v_att.timestamp = px4::get_time_micros();
```

I'll let you guys tackle that.

**Comment by dagar** [comment]
Thanks @jgoppert - I don't think I fully understand how to get cmake to tolerate generate source. Is it the library or just having the output of a custom command as input to something in the same scope?

**Comment by dagar** [comment]
@kd0aij would you like to give this a try now?

I don't know enough about PX4 ROS at the moment to fix the problem, so I'll have to come back to it later.

Another issue is that many of the topics exceed that max size. I'll have to take a closer look to see if it's safe to simply increase.

WARN  skip topic vehicle_attitude, format string is too large: 289 (max is 254)
WARN  skip topic qshell_req, data size is too large: 416 (max is 253)
WARN  skip topic estimator_status, data size is too large: 269 (max is 253)
WARN  skip topic ekf2_replay, format string is too large: 652 (max is 254)
WARN  skip topic vehicle_control_mode, format string is too large: 482 (max is 254)
WARN  skip topic vehicle_attitude_setpoint, format string is too large: 335 (max is 254)
WARN  skip topic optical_flow, format string is too large: 341 (max is 254)
WARN  skip topic mc_virtual_attitude_setpoint, format string is too large: 335 (max is 254)
WARN  skip topic vehicle_local_position, format string is too large: 356 (max is 254)
WARN  skip topic vehicle_status, format string is too large: 2086 (max is 254)
WARN  skip topic position_setpoint, format string is too large: 439 (max is 254)
WARN  skip topic input_rc, format string is too large: 266 (max is 254)
WARN  skip topic manual_control_setpoint, format string is too large: 315 (max is 254)
WARN  skip topic hil_sensor, data size is too large: 458 (max is 253)
WARN  skip topic fence, data size is too large: 268 (max is 253)
WARN  skip topic vehicle_gps_position, format string is too large: 477 (max is 254)
WARN  skip topic fw_virtual_attitude_setpoint, format string is too large: 335 (max is 254)
WARN  skip topic mission_result, format string is too large: 285 (max is 254)
WARN  skip topic control_state, format string is too large: 279 (max is 254)
WARN  skip topic tecs_status, format string is too large: 388 (max is 254)
WARN  skip topic sensor_combined, data size is too large: 738 (max is 253)
WARN  skip topic esc_status, data size is too large: 340 (max is 253)
WARN  skip topic position_setpoint_triplet, data size is too large: 303 (max is 253)

**Comment by dagar** [comment]
continued here: https://github.com/PX4/Firmware/pull/4045

**Comment by jgoppert** [comment]
@dagar I think what you were doing was correct, but trying to pass around a list of source files like that is cmake is challenging due to relative/absolute path issues. I just circumvented all of that by creating the library in the same file as the source files were declared. This made the most sense since we already had a dummy msg_gen target, and making it a library was the easiest path forward.

**Pull request closed without merging**
