### PR TITLE
Group airframes by type

### PR DESCRIPTION
**Pull request by hamishwillee**
This is address #7473

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This doesn't look scalable - should we instead add a type field to the files themselves?

**Comment by hamishwillee** [comment]
Hi @bkueng 
This groups airframes under a heading, as shown.
image
Implementation is a little messy because the code to set the group "type" has to be done in the __init__ -
I store it in the group object so that we can access it for layout (originally was just going to use it for sorting, but then realised a grouping heading works better (hope you agree).

The groups are just sorted alphabetically by "type". It might be better to add a sorting function that orders them as MC, FW, VTOL, ...., Unknown?

This *might* break the priority ordering stuff which you have created but do not use.

**Comment by hamishwillee** [comment]
Up to you and @bkueng - the script is fairly easy to update, but I don't know the cost of going though and adding type information, and getting people to enter it correctly in the first place.

**Comment by LorenzMeier** [comment]
I would prefer the tag. Will send a PR in a sec.

**Comment by LorenzMeier** [comment]
Please base on this - I just did the files and the parsing, the output generation still needs to be changed: https://github.com/PX4/Firmware/pull/7484

**Comment by hamishwillee** [comment]
@bkueng I updated this to:
1. Create a parameter group based on a combined "aircraft name" and "class". For most cases the result is the same group, but for cases like Simulation where there are simulations for each type of vehicle this creates a unique group for each vehicle type.
2. Switched to using class information to generate the headings.

The output menu looks like this. The Simulation is correctly split across 2 vehicle classes
image

Problems (hope you can help)
1. Anchors are based on headings, and here we have two headings in TOC called Simulation. Toc doesn't link to the second simulation topic.
1. The copter simulation section is below:
image
The lack of MAIN etc outputs is OK - there is nothing in source. BUT, why is the image wrong?

**Pull request merged**
