### PR TITLE
Firefly6 reversed elevon travel.

### PR DESCRIPTION
**Pull request by SimonWilks**
On my stock FireFLY6 the elevons are not moving in the right direction. 

This change works for manual inputs in manual mode as well as in ALTCTL for all stick inputs but elevator is still reversed when it tries to stabilise.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
If you recall our previous experience with wings the wrong travel direction can be quite confusing. Could you provide a log for Roman so he can look at the nominal commanded value and the mixer output? If could be anything ranging from swapped servo cables to servo direction to a -1 in the VTOL control code ;-).

**Comment by SimonWilks** [comment]
Yeah, been trying to dig up those old memories ;) I tried the usual things out but I want to go through it a bit more methodically and then I'll share some logs once I'm sure I think I know what I'm doing.

**Comment by SimonWilks** [comment]
@tumbili with the tailsitter code removed (your branch) the mixer in this PR now works. The control surfaces now move in the correct direction in both manual and stabilised modes.

**Comment by tumbili** [comment]
@SimonWilks Puh, glad to hear that. What about the tilting, does it work?

**Comment by SimonWilks** [comment]
@tumbili tilting works fine too.

**Comment by LorenzMeier** [comment]
Can we fix the 3 commits here into one (GIT rebase -I) and / or also get the remaining required changes onto master? Can the changes done by Roman also be done as Firefly param without commenting out code in a clean fashion? It sounds like it's well enough tested to be on master.

**Comment by Austriker** [comment]
@tumbili Creating a VT param like VT_ELEV_IN_MC for deactivating the elevons in mc would do the trick no ?

**Comment by tumbili** [comment]
Yeah, I will try to merge the branch into master in a clean way

**Comment by LorenzMeier** [comment]
@sjwilks @tumbili @Austriker I find the various PRs very confusing - could you please coordinate on them, update with comments their testing state and help getting them into master? Right now its a bit of a mess with way too much WIP and too little process, confusing everybody and slowing down progress.

**Comment by Austriker** [comment]
@LorenzMeier : @tumbili started to regroup every PR about the FireFLY6 here https://github.com/tumbili/Firmware/tree/firefly6_upgrade

**Comment by LorenzMeier** [comment]
So I'm closing this one then.

**Pull request closed without merging**
