### PR TITLE
When switching to land in VTOL, update land target during back trans

### PR DESCRIPTION
**Pull request by sanderux**
Currently, when switching to LAND mode on a vtol, it will perform a back transition and landing simultaneously. This prevents the vehicle trying to navigate back to where the back transition started during landing as it might result in a landing while tilted.

### CODE REVIEW

**Comment by sanderux** [comment]
@PX4TestFlights Due to weather conditions i am unable to test this safely.
Could you test fly on a vtol:
Param NAV_FORCE_VT: enabled (this is default)
Fly in any mode and switch to LAND. It should do a back transition and land at the location it came out of the backtransition. Before this PR it will attempt to navigate back to the place where the LAND command was initiated while descending.

**Comment by dagar** [comment]
We need to be careful here and make sure the throttle and speed is set in the position setpoint.

**Comment by dagar** [comment]
This is also a problem for regular multicopters if you flip into LAND mode with any velocity.

Something like the simple state machine in other nav states like RTL would work well. First come to a full stop (including back transition if a VTOL), then create the land waypoint below.

Similar to https://github.com/PX4/Firmware/pull/8101.

@Stifael FYI

**Comment by Stifael** [comment]
I think it is similar to https://github.com/PX4/Firmware/pull/8057

**Comment by sanderux** [comment]
Should we get this in after testing and work on a better state machine for 1.8?

**Pull request merged**
