### PR TITLE
AutoMapper1/2: set thrust to NAN at idle

### LINKED ISSUE #11197: Multicopter takes off in HOLD on ground
I found a regression while running the Dronecode SDK integration tests. Before arming, the SDK sets PX4 into HOLD mode. That way we make sure that a drone does not shoot up right after being armed but always sits on ground and just spins the motors in idle, so this is a safety precaution.

However, after 5887a2393cefad7268d165e07352384be61e1404 the drone suddenly starts hovering right after arming even though it's in HOLD mode.

The SDK command to test this is:
```
make && build/default/integration_tests/integration_tests_runner --gtest_filter="SitlTest.ActionHoverAsync"
```

FYI: @Stifael 

https://logs.px4.io/plot_app?log=c387cdf8-120a-4aab-90ca-bcfb559a5ea5

### PR DESCRIPTION
**Pull request by julianoes**
I don't understand all the things that you guys are talking about but I would like to have the regression fixed and this change seems to do it.

Fixes #11197.

If we can't fix this quickly, then I'd suggest to revert #11056 for now.

### CODE REVIEW

**Comment by julianoes** [comment]
One catch is that this only works once, and not again after a takeoff and landing.

**Comment by julianoes** [comment]
I think I don't understand what's going on, especially not this:
https://github.com/PX4/Firmware/blob/ef54bff4ed45755b4762ef58db21fa37d612d44e/src/lib/FlightTasks/tasks/AutoMapper/FlightTaskAutoMapper.cpp#L65-L67

**Comment by LorenzMeier** [comment]
@bresch Could you please chime in here? @julianoes Maybe catch up quickly in person..

**Comment by Stifael** [comment]
@julianoes as I explained in https://github.com/PX4/Firmware/issues/11197, the issue only occurs with with [MPC_AUTO_MODE](https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_params.c#L685) is set to jerk-limited. So if you need a quick fix, then we should change the default back to 0 (https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_params.c#L684)

**Comment by Stifael** [comment]
We can have a call, but I feat the entire "hot-fixes" are going the the complete wrong direction and you just add new issues.

**Comment by julianoes** [comment]
> So if you need a quick fix, then we should change the default back to 0.

I don't need a quick fix but I think the fact that controls are running when the drone is supposed to be idling on ground is a potential safety issue and therefore should get resolved as soon as possible.

The regression happened with #11056, so that's why I'm suggesting to just revert that.

**Comment by julianoes** [comment]
This seems not to work properly, so closing.

**Comment by MaEtUgR** [comment]
@julianoes If it's blocking you from work on master just checkout this hotfix https://github.com/PX4/Firmware/pull/11207 but I'd suggest we don't merge it but rather fix the AutoMapper2 to not produce any unexpected setpoints.

**Pull request closed without merging**
