### PR TITLE
Mixer configuration - View, modify mixer parameters then save to a .mix

### PR DESCRIPTION
**Pull request by crashmatt**
FOR REVIEW ONLY - TESTED ON SITL ONLY - FOR TEST ON FMU-V4 PIXRACER
Conditionally does not build for px4io or px4fmu-v2.

These features are not yet compatible with px4io.

Added the following commands to nsh:
`    PX4_INFO("  mixer save <device> <filename>");`

    PX4_INFO("  mixer list <device>");
Indexed list of mixers with human readable name for each one

    PX4_INFO("  mixer params <device> <mixer_index>");
Show parameters for one of the mixers

    PX4_INFO("  mixer set <device> <mixer_index> <param_index> <value>");
Set a parameter

    PX4_INFO("  mixer config <device>"); 
Generate information for a .mix file but show it instead of saving it.

Parameters are in float units.  Mixers and parameters are accessed by index.  The index can be found from "mixer list" and "mixer params"

<device> is /dev/pwm_output0 for SITL. Unknown for fmu-v4.
<filename> for SITL is format rootfs/fs/something.mix

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Can you share the output of an example session? Looks super interesting!

**Comment by crashmatt** [comment]
Here are some example outputs.

pxh> mixer list /dev/pwm_output0
INFO  List of mixers:
Mixer count : 3 
mixer index 0 : MULTI
mixer index 1 : SIMPLE
mixer index 2 : SIMPLE

The mixer names for multi and simple are generic. In future these names can be filled from the mixer definition file.  This will enable easy mixer identification through a gui.

mixer params /dev/pwm_output0 0
mixer:0  param:0 id:ROLL_SCALE value:1.000000
mixer:0  param:1 id:PITCH_SCALE value:1.000000
mixer:0  param:2 id:YAW_SCALE value:1.000000
mixer:0  param:3 id:IDLE_SPEED value:-1.000000

pxh> mixer params /dev/pwm_output0 1
mixer:1  param:0 id:SCALE_NEG value:1.000000
mixer:1  param:1 id:SCALE_POS value:1.000000
mixer:1  param:2 id:OFFSET value:0.000000
mixer:1  param:3 id:OUTPUT_MIN value:-1.000000
mixer:1  param:4 id:OUTPUT_MAX value:1.000000

pxh> mixer set /dev/pwm_output0 1 0 0.9
mixer:1  param:0 id:�@C value:0.900000 set success

Something went wrong with the parameter id output since I last tested it.  The id will not be supported for mixer set.

pxh> mixer config /dev/pwm_output0
R: 4x 10000 10000 10000 -1000
M: 1
O: **9000** 10000 0 -10000 10000
S: 3 5 10000 10000 0 -10000 10000
M: 1
O: 10000 10000 0 -10000 10000
S: 3 6 10000 10000 0 -10000 10000

See the modified value :-)


pxh> mixer save /dev/pwm_output0 rootfs/fs/microsd/mix.mix
INFO  Wrote mixer /dev/pwm_output0 to file rootfs/fs/microsd/mix.mix

reboot and view config.  Result is default as expected

pxh> mixer config /dev/pwm_output0
R: 4x 10000 10000 10000 -1000
M: 1
O: 10000 10000 0 -10000 10000
S: 3 5 10000 10000 0 -10000 10000
M: 1
O: 10000 10000 0 -10000 10000
S: 3 6 10000 10000 0 -10000 10000

pxh> mixer load /dev/pwm_output0 rootfs/fs/microsd/mix.mix
pxh> mixer config /dev/pwm_output0
R: 4x 10000 10000 10000 -1200
M: 1
O: 9000 10000 0 -10000 10000
S: 3 5 10000 10000 0 -10000 10000
M: 1
O: 10000 10000 0 -10000 10000
S: 3 6 10000 10000 0 -10000 10000

**Comment by crashmatt** [comment]
Lorenz,  this build image is 1250 bytes above the flash size for fmu-v2.  It is also of no use for the failsafe io.  What is the best option for compatibility? optional modules? conditional compilation? Something else?

**Comment by LorenzMeier** [comment]
@crashmatt Do you want to set up a call to discuss this further?

**Comment by crashmatt** [comment]
@LorenzMeier A call would be great.
I don't need px4io compatibility for my projects but to gain community support I suspect I need to support it.  A way around the memory limitation would be good.

**Comment by crashmatt** [comment]
I recommend to remove this pull request.  It is not complete since it does not support the majority of hardware.  There is a path to do do this but I have no spare hours to commit to it.

**Comment by LorenzMeier** [comment]
Makes sense - unfortunate though. Please don't delete the branch and come back when you feel its ready.

**Comment by crashmatt** [comment]
I don't have space to setup a computer to do this and am unlikely to have that space for at least 2 years.  For now here are the problems and some solution proposals.

Problems

The mixer (failsafe) has all of the current settings so it is the only entity that can generate the mixer file.  That means that the failsafe has to know everything about generating that file.  This is not an easy thing to do considering the following.

Compound mixers including the not so simple SimpleMixer are difficult to manage.  1:1 input to output is ok.  N:1 is not so simple.  There are already three dimensions to navigate through, mixer group, mixer index and settings index.  Implementing an extra dimension and getting access through NSH is no problem but implementing this through mavlink will be painfull.  At this point usability is getting to be a challenge.  Implementing an editor for any shape of variable sized compound mixer through mavlink is not something I would support.

For an editor to work sucessfully both mixer and setting naming is required.  Instead of "channel_1->servo_5" we need "roll_command->aileron_2". Instead of "setting_1" we need "gain". The majority of transmitter based mixers do this to make it possible to use.  The mixer settings also need naming for the user to know what each setting is

Mainstream community acceptance is required to get long term support in mavlin and on the groundstation side.  System compatibility with ardupilot is necessary to get whole community acceptance. It needs doing right or not at all.


Solutions

A copy of the failsafe mixer settings could be held on the main processor.  Any updates to settings would happen at both the main processor and the failsafe. The main processor can generate the mixer configuration without involving the failsafe.  The failsafe communication requires little modification since it only needs to handle the settings changes and maybe a checkum of settings.

The mixer and settings naming does not need supporting directly by the mixer.  Naming could be contained in JSON/XML files and read through mavlink file access.  Ardupilot users will need to manage and store the naming on the groundstation side.

It should be possible to automatically translate a SimpleMixer into multiple 1:1 mixers with a python script.  Everthing should be compatible with all existing users.


and finally....  if someone can figure out how I can stop the endless nagging brain death that is childcare I might get time to build a nice warm shed to put my computer in. Then I can get right back on to this topic.

**Pull request closed without merging**
