### PR TITLE
Mavlink Geofence

### PR DESCRIPTION
**Pull request by LorenzMeier**
Rebased version of: https://github.com/PX4/Firmware/pull/6888

This implements the new geofence and rally mission protocol (see https://github.com/mavlink/mavlink/pull/683).

### Current state
- protocol extensions fully implemented, storage & retrieval of data to/from dataman
- navigator geofence updated to handle multiple polygons, notification on geofence update

### Implementation details & further steps
- Combination logic of having multiple polygons is as following:
```
The check passes if: (inside(polygon_inclusion_1) || inside(polygon_inclusion_2) || ... ) &&
                      !inside(polygon_exclusion_1) && !inside(polygon_exclusion_2) && ...
```
@DonLakeFlyer I think we should add this to the mavlink spec.
- Only MAV_FRAME_GLOBAL(_INT) is supported
- Only one transmission at a time is possible (no interleaving)
- Handling of rally points is not done yet and needs to be added at the appropritate places.
- MAV_CMD_NAV_FENCE_RETURN_POINT needs to be handled too
- unlike the missions, geofence and rally points do not switch between 2 datasets. If needed this can be added.

### Open Questions
- What is the altitude used for in the polygon vertex? Is it a minimum or a maximum? How should it be interpolated? If we leave this open now, should we set it to NaN for now? Current implementation just ignores it.
- Can polygons be complex (self-intersecting)? The current implementation cannot handle this and I don't think it's needed (a user could just specify multiple polygons to get the same result). If we don't need it, it should be stated in the mavlink spec and the UI must not allow to draw (or upload) such polygons.

Needs a client implementation for testing.
@DonLakeFlyer

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@bkueng Please continue the integration with this QGC WIP state:
https://github.com/mavlink/qgroundcontrol/pull/5147

You will run into transfer errors, but that should all now be solvable.

**Comment by LorenzMeier** [comment]
@bkueng I've added a new command:
```mavlink verbose```

To enable verbose mode on the shell. Please polish as needed (module instructions, potentially `mavlink verbose on` and `mavlink verbose off`).

**Comment by LorenzMeier** [comment]
@bkueng @DonLakeFlyer It looks like we have different specs here: The PX4 implementation uses the type field in the mavlink mission count to differentiate between "mission types" where each is essentially a separate list. By setting the type we can transfer N different lists. And the QGC implementation uses the MAV_FRAME to interleave the different data types into the same list (e.g. MAV_CMD_NAV_FENCE_POLYGON_VERTEX_INCLUSION). We should discuss architecture on a call and come up with a concise spec on http://mavlink.io

**Comment by bkueng** [comment]
@DonLakeFlyer I added support for the circular areas (https://github.com/mavlink/mavlink/pull/726)

**Comment by DonLakeFlyer** [comment]
Yup, I'll add circular fence next.

**Comment by bkueng** [comment]
geofences can now be updated in-flight. The storage is locked during a transaction, and navigator will not check for geofence violations during that time.

**Comment by LorenzMeier** [comment]
This PR will need this extension to be implemented on PX4 and QGC sides to default them both to MAVLink 2: https://github.com/mavlink/mavlink/pull/728

If the handshake establishes that the link doesn't support it, requests for Geofence should be NACK'ed using a clear string error message that the link is the issue.

Up-to-date 3DR Radios should support MAVLink 2, ESP8266 has an issue filed for it: https://github.com/dogmaphobic/mavesp8266/issues/41

**Comment by bkueng** [comment]
> If the handshake establishes that the link doesn't support it, requests for Geofence should be NACK'ed using a clear string error message that the link is the issue.

A geofence request in mavlink 1 will look exactly like a valid mission request on the FW side, because the mission_type is an extended field that is set to 0 for v1.0. A client (in that case QGC) needs to make sure never to send geofence (and rally point) requests when using mavlink 1 on the link ( @DonLakeFlyer ).

**Comment by LorenzMeier** [comment]
We should address the comment from @bkueng in the matching QGC PR for https://github.com/PX4/Firmware/pull/7344 as well and then merge this and iterate on it.

**Comment by DonLakeFlyer** [comment]
> A geofence request in mavlink 1 will look exactly like a valid mission request on the FW side, because the mission_type is an extended field that is set to 0 for v1.0.

Shouldn't the vehicle side send "not supported" if it gets the fence or rally commands on a regular mission protocol session.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer It fails before that. The only way to consistently prevent that is to have the GCS not send them via MAVLink 1, since it knows that this particular extension is only compatible with v2.

This is not the only feature depending on MAVLink 2, so it would be good to build in an automated check that enables or disables a feature based on wether the vehicle supports MAVLink 2. See #7344 for a proper and very robust detection method.

**Comment by DonLakeFlyer** [comment]
> The only way to consistently prevent that is to have the GCS not send them via MAVLink 1, since it knows that this particular extension is only compatible with v2.

Of course, I understand that and will implement correctly on the QGC side. That is not what I'm talking about. What I am saying is that the vehicle should reject fence and rally mission commands  in the command list if MAV_MISSION_TYPE_MISSION is the protocol exchange type. That can happen whether it's mavlink 1 or mavlink 2. QGC should never do that if implemented correctly, but that doesn't mean you don't need to harden against it.

**Comment by bkueng** [comment]
>  What I am saying is that the vehicle should reject fence and rally mission commands in the command list if MAV_MISSION_TYPE_MISSION is the protocol exchange type.

I added a check for that.

**Comment by bkueng** [comment]
This is ready for review and/or merge. We can do safe points in a follow-up.

@DonLakeFlyer  I did not implement `MAV_CMD_NAV_FENCE_RETURN_POINT`, and I think we should remove it as we already have the rally points.

**Comment by DonLakeFlyer** [comment]
> I did not implement MAV_CMD_NAV_FENCE_RETURN_POINT, and I think we should remove it as we already have the rally points.

I think that's ok for now, but I need to figure out how to deal with that in relationship to ArduPilot which supports a fence return point.

**Pull request merged**
