### PR TITLE
Send camera trigger mavlink message in simulation

### LINKED ISSUE #8739: "Camera triggering" in simulation (SIL/HIL) from PX4
**Feature Request**

When doing simulations of surveying missions, triggering cameras in the simulation is required. I would like to implement this feature in `PX4`.

I've already hacked something together by sending the mav link `COMMAND_LONG` and checking it in AirSim. Since I'm not certain that this is the suitable MavLink message, I also created [this issue](https://github.com/mavlink/mavlink/issues/828)

If i understand the PX4 codebase correctly then the "correct" way to implement it is subscribing to the `camera_trigger` orb in [mavlink simulator](https://github.com/PX4/Firmware/blob/6227139df11cc28939c6a1ccafaa69f5bebe811f/src/modules/simulator/simulator_mavlink.cpp) and send the "correct" mavlink message on the HIL interface when this occurs.

I also hope to [add support for this in AirSim](https://github.com/Microsoft/AirSim/issues/734)

### PR DESCRIPTION
**Pull request by kjetilkjeka**
I've implemented camera trigger over simulation mavlink interface. Fixes #8739 

I've tested it in sitl by using `camera_trigger test` from the px4 command line, and used QGC to fly mission (in AirSim) where camera is triggered (AirSim doesn't normally read this message so I've modded it to do this).

I'm ready for review or instructions of further testing.

### CODE REVIEW

**Comment by dagar** [comment]
What's the full setup here? I'm wondering if there's a way we can go through the regular mavlink module instead of reimplementing these things.

**Comment by LorenzMeier** [comment]
Sorry, I only saw this now. Triggering in simulation was already operational. Key config items:

```
param set TRIG_INTERFACE 3
param set TRIG_MODE 4
mavlink start -x -u 14558 -r 4000 -f -m onboard -o 14530
```

We completely missed to document this. @hamishwillee Can we add that to either SITL or camera trigger docs?

The difference is that in this mode the MAVLink app sends out trigger messages to the simulated camera. It also forwards other commands to it and simulates a MAVLink enabled camera.

This PR instead simulates a more hardware-focused interface. We can't merge as-is as the Typhoon would then get 2 trigger commands. There is value in having both approaches implemented, but we would need make sure this one doesn't get started on Typhoon and we test both.

**Comment by kjetilkjeka** [comment]
Thanks for clearing this up @LorenzMeier, if i understand you correctly enabling this in simulation would also require the simulator to have two mavlink connections. One for HIL-states (14540) and one for "general on board stuff" (14530). I guess this makes sense, and it would instead require me to implement this alternative interface in AirSim.

I would recommend to document this in the SITL part, since the "two mavlinks connections to simulator" is possibly relevant for more things than just the camera trigger.

Using this "as is" is totally acceptable for us and i think it's time better spent implementing the required functionality in AirSim than implementing an alternative way to do already implemented functionality that will require more testing and documentation. I suggest that we close this PR and leave this as is.

**Comment by hamishwillee** [comment]
@LorenzMeier 

So I think that we set the mavlink `-f` flag to forward all MAVLink messages received by PX4 to the specified ports. For this to work the simulator then has to be modified to connect to the camera stream and understand the camera messages (responding appropriately according to the  [camera protocol](https://mavlink.io/en/protocol/camera.html))? Is that correct?

I think we only set `TRIG_INTERFACE 3` to  make sure that the [camera trigger driver](https://github.com/PX4/Firmware/blob/master/src/drivers/camera_trigger/camera_trigger.cpp#L778) doesn't actually modify any aux/gpio ports. Is that correct? 

Detail questions:
1. Is the stream you set up "just" for the camera? i.e. will the simulator still need to interact with the simulation API via 14560 (I assume so)?
1. There is a lot of other information in the stream - should the simulator just throw that away, or is it useful?
1. [param set TRIG_MODE 4](https://dev.px4.io/en/advanced/parameter_reference.html#TRIG_MODE) is "distance based triggering, on command". Does this really need to be set/Why does this mode need to be set rather than the other ones?
1. Regarding:
   ```
   mavlink start -x -u 14558 -r 4000 -f -m onboard -o 14530
   ```
   [mavlink](https://dev.px4.io/en/middleware/modules_communication.html#usage) streams all messages in the `onboard` group to the simulator, specifying a listen port of 14558 and a remote port of 14530. One of the messages that is streamed is the CAMERA_TRIGGER mavlink message, which is obtained from the  uORB `camera_trigger` message. 
   - Why have those two ports been chosen here in this example (-u -o). Can any free ports be used? Are these just what you used for Gazebo?
   - Why is `-x` enabled (FTP)?
   - Why is `-m onboard` used rather than `-m camera`

**Comment by hamishwillee** [comment]
@LorenzMeier Further to https://github.com/PX4/Firmware/pull/8775#issuecomment-361476205 

How would an "ordinary" MAVLink camera setup differ from this? Presumably we still want to set `TRIG_INTERFACE 3`. How would we set up PX4 to forward camera messages to point to the real camera?

**Comment by LorenzMeier** [comment]
@hamishwillee Correct, the instances need the -f flag so that GCS commands are forwarded to the camera. This setup will always look this way for a MAVLink-enabled camera. The camera also needs GPS, which is why it will get additional messages.

On trigger mode: That's a good mode to start in.

-x and --onboard - not sure about those. I might have done that to test the rest as well. Let's try with the cleanup you suggested.

**Pull request closed without merging**
