### PR TITLE
Fix acro transition

### PR DESCRIPTION
**Pull request by kd0aij**
bench tests OK on AUAV-X2 **needs flight testing**
the logic for interpreting the acro and rattitude switches seemed confused
also, the new transition switch wasn't monitored

### CODE REVIEW

**Comment by dagar** [comment]
One thing to be aware of here is that the main state is only changed if the switches change. If you want the modes to do the right thing through transitions it needs to be handled in the state machine.

One question to answer first is how we want mode change requests to work if something unavailable is requested. Do you deny the change, or accept it and actually go to a different mode?

**Comment by AndreasAntener** [comment]
This disables stabilized for fixed-wing completely. What are you trying to fix?

**Comment by kd0aij** [comment]
I cleaned up the logic in an attempt to make my intent as clear as possible. I have always considered MC ACRO to be analogous to FW manual, so this change turns on stabilization only if ACRO is off. If no ACRO switch is assigned, the default FW mode is MANUAL (non-stabilized), since otherwise you would be SOL if the autopilot failed.

**Comment by kd0aij** [comment]
@AndreasAntener Hover testing this PR today shows that the PID rate gains are far too low to fly in MC/ACRO mode so I programmed my TX to enable ACRO mode only when the transition switch is in the FW position. This way, I can do my initial forward transition tests in FW manual mode (ACRO switch on) and not worry about the ACRO switch if I have to fall back to MC mode in an emergency.

**Comment by AndreasAntener** [comment]
> I have always considered MC ACRO to be analogous to FW manual, so this change turns on stabilization (angle mode) only if ACRO is off.

Well it's not ;). But I see that you are progressing towards what has been discussed for flight modes changes. I don't think it would be wise to pick something out of the bigger picture now do you?

For reference:
https://github.com/PX4/Firmware/issues/3967
https://docs.google.com/document/d/1pi7YMKu9dhcq6HRAXQ_gMesn2gGrRa7cdNTYLEsNDjE/edit

Your current issue is basically that you are worried you'll end up in ACRO after STAB flight no? I can make a PR with the stop gap measure we use, basically disabling ACRO for VTOL and putting also the multirotor into STAB. That means you can have the ACRO switch on/off and it won't matter for multirotor but fixed-wing is then stabilized or not as if it would be a stabilized switch. How about that? Or did I completely miss your point...

**Comment by kd0aij** [comment]
@AndreasAntener FW manual **is** analogous to MC ACRO because the controls effectively command roll and pitch *rate* rather than angle. The main difference is there's no control loop for FW.

And thanks for the offer of a patch to disable MC ACRO, but there's no need. I'll do my flight testing using this PR, since it works exactly the way I expect things should. Eventually, I'll see if I can make ACRO work properly for VTOLs in MC mode.

**Comment by kd0aij** [comment]
@AndreasAntener Could you explain to me the reasoning which resulted in ACRO meaning stabilized for fixed-wing setups, or am I completely confused? Also, do you agree that deflection of aileron, elevator and rudder surfaces is effectively a rate demand, or is this the source of confusion?

**Comment by dagar** [comment]
I think you're putting too much weight on the old flight mode evaluation. If I'm not mistaken FW stabilize mode came pretty late and that was probably just an okay place to insert it. The FW user isn't even aware that STAB mode is behind the ACRO switch when they configure through QGC. That old mode setup was also way too confusing for many users.

You're not wrong that FW manual is analogous to ACRO, it's just way less intuitive than calling it manual and makes it sound like the autopilot is doing something special.

**Comment by kd0aij** [comment]
@dagar I understand that with the "new" single channel flight mode selection there is no "ACRO" switch, but the fact is that QGC currently describes STABILIZE mode as "angular rates are controlled, but not the attitude". 

Since that is obviously wrong, there is a real problem here, and I think it resulted from equating ACRO with STABILIZED in the multi-channel flight mode selection.

**Comment by dagar** [comment]
Gross. It's here if you want to add a correct description as a quick fix.
https://github.com/mavlink/qgroundcontrol/blob/master/src/AutoPilotPlugins/PX4/PX4AdvancedFlightModes.qml#L63

I vote we actually implement FW acro to end the confusion :wink:. Although then we don't even have a place for FW stab in the in the old flight mode selection. I also think we should drop MC manual.

**Comment by kd0aij** [comment]
Yes, there is no reason to ever be in "manual" (override) mode for multicopters.

**Comment by kd0aij** [comment]
Regarding the current description for FW STABILIZED mode, I think the description here: https://github.com/mavlink/qgroundcontrol/blob/master/src/AutoPilotPlugins/PX4/PX4AdvancedFlightModes.qml#L48 should be displayed instead.

**Pull request closed without merging**
