### PR TITLE
Airframes: add markdown output

### PR DESCRIPTION
**Pull request by bkueng**
This adds markdown output to the airframes script. It looks like this:

dev-guide_airframes

To generate the output, use `./Tools/px_process_airframes.py -a ROMFS/px4fmu_common/init.d --xml`

I used the images from QGC and I plan to add the motor numbers to them as a next step. Eventually we can add generated wiring diagrams...

It should be added to Jenkins the same way as the parameters.
@dagar  @hamishwillee what do you think?

### CODE REVIEW

**Comment by hamishwillee** [comment]
Looks great. Only thing is that I will be moving all the build log files out of the devguide and into the user guide once it is published. So your links will need to change/go to the user guide. This makes sense since wiring/airframes are as much/more a user guide topic as a devguide topic.

**Comment by bkueng** [comment]
> Only thing is that I will be moving all the build log files out of the devguide and into the user guide once it is published. So your links will need to change/go to the user guide. This makes sense since wiring/airframes are as much/more a user guide topic as a devguide topic.

I thought so too. It will be easy to change since both use gitbook for both.

> Also, what are the outputs for the other flying wings. Are they always the same? If so, this information should possibly be separated out next to the wing itself.

They should be the same, but the information is currently stored independently for each airframe id and thus it could be different. This is why I kept it separate for now as well.

**Comment by dagar** [comment]
This is going to be extremely helpful for regular users.

For now do you want to add it to this? https://github.com/PX4/Firmware/pull/6992/files
We could just do a single Makefile target `px4_metadata` that generates both and dumps them into s3 until we figure out the auto gitbook commit.

**Comment by hamishwillee** [comment]
@bkueng 

>> Also, what are the outputs for the other flying wings. Are they always the same? If so, this information should possibly be separated out next to the wing itself.

> They should be the same, but the information is currently stored independently for each airframe id and thus it could be different. This is why I kept it separate for now as well.

For the parameters I wrote a little code that conditionally included the information. So if all the items in a group/table had same information that appeared up the top, otherwise I reproduce in each table. You could do similar, and IMO that makes sense since otherwise arguably you might need a different image for each case.

**Comment by hamishwillee** [comment]
@dagar 

> For now do you want to add it to this? https://github.com/PX4/Firmware/pull/6992/files
> We could just do a single Makefile target px4_metadata that generates both and dumps them into s3 until we figure out the auto gitbook commit.

We definitely want auto done "sooner" rather than later, but I think this should wait until late next week. The reason is that I want to move the whole devguide to a multilinguage version. That will move most docs under /en folder. I'd do that now except that I only just did QGC and I want to make sure that my new redirect plugin works OK for a few days before I make the change. Also I don't want to make a change like that just before going away for a few days.

NOTE: ARE THERE ANY THINGS THAT I NEED TO BE AWARE OF POSSIBLY BREAKING? (e.g. scripts or whatever that assume existing docs structure)

When we do this I'd like it to replace this doc in the devguide: https://dev.px4.io/parameter_reference.html

For the user guide, it will go under this folder: https://hamishwillee.gitbooks.io/px4-user-guide/content/en/advanced_config/ (again, once this is published ... probably the following week)

**Comment by bkueng** [comment]
> NOTE: ARE THERE ANY THINGS THAT I NEED TO BE AWARE OF POSSIBLY BREAKING?

Not that I'm aware of. Except for existing HTML links.

**Comment by bkueng** [comment]
I merged the Outputs where possible, it looks like this:
dev-guide_airframes_new
For some, like Standard Plane, it does not work, as the airframes use inconsistent orderings.

@jgoppert The airframe id 4002 was duplicated, so I moved  4002_qavr5 to 4003_qavr5.

**Comment by hamishwillee** [comment]
Looks pretty good. You could possibly make table 2 column and put the "Specific outputs" under the Maintainer info, if present. That will look better.

**Comment by LorenzMeier** [comment]
@bkueng Awesome! With the feedback from Hamish factored in this should be good to go.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer @dogmaphobic We should plan for the same thing in QGC to simplify setup.

@sirPerna FYI

**Comment by hamishwillee** [comment]
@bkueng 

> For some, like Standard Plane, it does not work, as the airframes use inconsistent orderings.

Then sorry :-( , but probably my suggestion was wrong. It is better to have something that works everywhere in a consistent way than to have inconsistencies that result in different tables/images in different places.

One possibility is to revert to something [like your original post above](https://github.com/PX4/Firmware/pull/7019#issue-220880761) but you'd need to keep the wing image in the table so that you could associated it orderings correctly.

image

Another variant might be:
image

**Comment by bkueng** [comment]
I have it like this now:
dev-guide_airframes_new2
Wherever there are inconsistencies within an airframe type, the Specific Outputs will indicate so.

I added motor numbers and directions as well. @hamishwillee if you're ok with that, we can merge this.

**Comment by hamishwillee** [comment]
> I added motor numbers and directions as well. @hamishwillee if you're ok with that, we can merge this.

Looks great :-) I am interested to see how the standard plane output differs. But if you are sure this "works" for all our cases, then I'm more than happy for you to merge.

**Comment by bkueng** [comment]
PR for the dev-guide is here: https://github.com/PX4/Devguide/pull/119, so you can look at the 'real thing' yourself.

@DonLakeFlyer I took the airframe SVG's from QGC and added motor numberings & directions. Feel free to use them if you want to.

@tubeme fyi

**Pull request merged**
