### PR TITLE
Eagle build cleanup

### PR DESCRIPTION
**Pull request by mhkabir**
While working on the RPi2 port, I found the Snapdragon build system to be quite confusing, so I decided to do some cleanup.

This PR removes the ```Toolchain-arm-linux-gnueabihf.cmake``` from ```cmake/toolchains``` and sets the build system to use it from ```cmake_hexagon``` (https://github.com/ATLFlight/cmake_hexagon/pull/1), as proposed by @mcharleb in https://github.com/PX4/Firmware/issues/4203

While not strictly required, this makes things a lot easier to understand, since "arm-linux-gnueabihf" encompasses *any* ARM build like Odroid / RPi / Eagle.

Another alternative, if you don't want this would be to rename the current one to "Toolchain-arm-linux-gnueabihf-linaro" and add separate ones like "Toolchain-arm-linux-gnueabihf-raspbian".

### CODE REVIEW

**Comment by mhkabir** [comment]
Related work to bring up RPi2 again : https://github.com/mhkabir/Firmware/tree/rpi2_bringup

**Comment by LorenzMeier** [comment]
@mcharleb @jywilson Can you please review?

**Comment by mcharleb** [comment]
@mhkabir I merged your changes to cmake_hexagon, and DriverFramework. This should now pass the CI test. @LorenzMeier how do we kick off the CI test again?

**Comment by mcharleb** [comment]
See #4467

**Pull request closed without merging**
