### PR TITLE
First cut at temperature calibration [WIP]

### PR DESCRIPTION
**Pull request by LorenzMeier**
This branch adds WIP support for temperature calibration. This needs further polishing and an automated calibration routine.

### CODE REVIEW

**Comment by HesselM** [comment]
I have created a new branch [tempcal](https://github.com/delftswa2014/Firmware/tree/tempcal) on our Software Architecture git, which will contain our effort to incorporate this function.

**Comment by LorenzMeier** [comment]
@HesselM Could you send a pull request against this branch? I'd be happy to incorporate it. I will also provide a dataset with all sensor temperature sensors enabled so that you can continue on a more detailed level.

**Comment by HesselM** [comment]
@LorenzMeier sure, but I am still figuring out how to do some proper testing (besides compiling and uploading). I'll try to add an uORB object, so the compensated measurements are also stored to the sdlog and can be processed by e.g. Matlab for comparison.

**Comment by LorenzMeier** [comment]
@HesselM Testing is extremely easy: Just log the data onboard, then graph it with pyMAVLink (or convert to Matlab using mavtomfile.py from pyMAVLink). If the compensation works you should see close to zero offsets.

**Comment by LorenzMeier** [comment]
Also: Connect with QGroundControl, go to the analyze view and watch the live data as the board heats up. My gut feeling is that you need to re-do the coefficients with the in-sensor sensors which are being logged now.

**Comment by LorenzMeier** [comment]
@HesselM I've added a few commits which fix typos on my end. The offsets are applied now, but the testing results are not correct yet - I do still get some relevant offset with a change in temperature. Will work on better logs for you.

**Comment by LorenzMeier** [comment]
@jschall In case you're interested to follow this WIP.

**Comment by HesselM** [comment]
@LorenzMeier thanks for the fixes. You missed a spot (get_param in sensors.cpp) so I fixed that in [this tree](https://github.com/delftswa2014/Firmware/tree/tempcal). 

Using the IMUT-columns in the log the temperature compensated gyro measurements can be compared with respect to the uncompensated measurements. The log2poly matlab script and python log interpreter in [Tools/polytemp(https://github.com/delftswa2014/Firmware/blob/tempcal/Tools/polytemp/log2poly.m) can be used to calculate the polynomial terms. 

Unfortunately it does not work completely yet: while the IMUT values differ from the IMU in the log, the difference is not what would be expected as there is still an offset

**Comment by HesselM** [comment]
Added some additional fixes and got some (proper) results.
The results are from a ~11 minute dataset

First the temperature of the gyroscope:
mpu6000 gyroscope temperature

And the measurements of the gyro plotted against the temperature. The top image shows the 'raw' (that is, filtered results in [grb.{x,y,z}](https://github.com/delftswa2014/Firmware/blob/tempcal/src/drivers/mpu6000/mpu6000.cpp#L1754-1756) ) and the bottom image the temperature compensated. I have placed the PixHawk in different orientations ('normal', front, back, top, 'normal' respectively), as can be seen by the spikes. 
gyro vs temperature

Finally, the results plotted against time. Again, the top is the 'raw' data, the bottom the compensated results. 
gyro vs time

It is not perfect yet, but is shows that the current approach might help in getting better estimates.
Also note that there is not yet a per-boot bias offset. Hence the compensated graphs do not align with 0.

**Comment by LorenzMeier** [comment]
Awesome! Will need to check this against my unit to see how it behaves.

**Comment by LorenzMeier** [comment]
@tridge @priseborough This looks like its good to go for another test - do you want to give the freezer spray a ride?

**Comment by HesselM** [comment]
@LorenzMeier @tridge @priseborough 

Since it might not be clear from the commits, a sort walkthrough of how to test and generate the polynomial terms:
- generate a log with a stationary unit and and rising temperature
- download log and and use the matlab tool [Tools/polytemp/log2poly](https://github.com/PX4/Firmware/tree/tempcal/Tools/polytemp) to generate polynomials
- copy-paste polynomials of gyro into [gyro_calibation.cpp L225-L242] (https://github.com/PX4/Firmware/blob/tempcal/src/modules/commander/gyro_calibration.cpp#L225-242)
- compile/upload/calibrate unit
- run unit. 

The temperature compensated values are only logged in sdlog2 and does not show up in QGroundControl. Log2Poly can be used for plotting the compensation after a run.

**Comment by LorenzMeier** [comment]
@kd0aij Could you lend a hand with validating this one here?

**Comment by LorenzMeier** [comment]
@HesselM How are things looking on your end - were you able to follow up on this further. @priseborough any time on your end to help validating this?

**Comment by LorenzMeier** [comment]
@HesselM I tried to rebase this against master, but I think its close to hopeless. It might be easier to manually bring the final diff over after the merge I did with master just now. The need to do this arises from commits like the ones with Xcode temp files or the commit series which added and topic and then just removed it again. Those commits create a lot of noise in the history and make bisecting / bug hunting virtually impossible later.

**Comment by HesselM** [comment]
@LorenzMeier 
Unfortunately I haven't been able to continue on the temperature correction, but i hope to get to it soon. How should I approach the transfer of the final differences? Create a new branch from master and insert the updates, followed by a new PR?

**Comment by LorenzMeier** [comment]
@laube Could you also have a look at this and we sync during monday? Thanks!

**Comment by LorenzMeier** [comment]
I just retried rebasing, which is hopeless. Anyone interested should copy the few critical bits over manually.

**Comment by LorenzMeier** [comment]
@yyassa @devbharat @boosfelm This will likely help quite a bit with cold environments. Let me know if you take this on.

**Comment by dagar** [comment]
I'd like to help take this to completion.

WIP merge --squash to master in my repo: https://github.com/PX4/Firmware/compare/master...dagar:tempcal_rebase?expand=1

I still need to implement the changes @LorenzMeier mentioned above.

**Comment by LorenzMeier** [comment]
Awesome! I'd be happy to help where I can. In general try to simplify it and remove the additional data and filters as far as possible, e.g. these:
https://github.com/PX4/Firmware/compare/master...dagar:tempcal_rebase?expand=1#diff-afefce4f4a086c7a7d23e52028f9ae1eR306

I would only leave the bare minimum required for testing. We don't want to blow up log rates by a factor of 2 whenever feasible.

**Pull request closed without merging**
