### PR TITLE
added sensitivity params for manual control

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by tumbili** [comment]
@kd0aij I think this is what you desire, right? Would be nice if you could review and eventually test. I'll also give this a try.

**Comment by kd0aij** [comment]
Thanks, this looks like what I was talking about; the ability to specify "low rate" for manual control.
I'll set up my Ninox with lower manual rates for my next flight test.

The root of my perceived problem is that, when I use dual rates at the TX, only the high rate provides full response in auto modes, since those modes assume the TX is on "max rate", but that in an emergency take-over, the pilot must contend with high rates, or else also switch to low rates during the emergency.

These new parameters allow the pilot to apply a lower rate for manual control without the need to flip a switch at the TX when switching to manual in an emergency. The only downside to this is that you have the option to set the manual sensitivity too low to allow recovery from "unusual attitudes", but this should not be a problem if the parameters are used wisely.

For pilots using programmable transmitters, it is probably possible to couple flight mode to control rates to achieve the same (and greater) capability. The question is whether these parameters provide a necessary feature for low-end RC transmitters or for simplifying setup using high-end TXs.

**Comment by LorenzMeier** [comment]
@kd0aij If you test-fly this we can probably get it into the release. This together with expo should make dual rate completely unnecessary.

**Comment by tumbili** [comment]
@kd0aij Any chance of testing this?

**Comment by kd0aij** [comment]
not yet, will flash it on my Ninox for the next opportunity at the field.

**Comment by tumbili** [comment]
@kd0aij Hi Mark, could you ping me if you are almost ready to test this one. There is this PR #2424  which you could test together with this one. My plane is in the garage at the moment (fried 2 engines) so I cannot test myself.

**Comment by kd0aij** [comment]
this parameter has no effect on elevon deflections, but I verified with warnx printout that it is scaling down the values of _actuators.control[0:1]
Even with the sensitivity params set to 0.0, I get full elevon deflections in roll and pitch

Sorry to hear about the fried motors; hot weather?

**Comment by tumbili** [comment]
@kd0aij @LorenzMeier I think it's because of the manual pass-through. This thing fools me for the 4. time now.

**Comment by kd0aij** [comment]
That would be the "failsafe" manual control provided by the IO processor, I guess. Which means the confusing thing is the else block /* manual/direct control */ which does nothing in fw_att_control. If that's right, the block should be replaced by a comment which reminds us that the IO processor handles everything in manual mode.

**Comment by LorenzMeier** [comment]
That's not correct. The IO block is optional in the system architecture, and neither very old nor very new systems have it.

**Comment by kd0aij** [comment]
This brings up a question about the new STABILIZE mode in FW: I have it set up on a separate switch for my Ninox, but does this mean that to recover manual control on an FMU hang that I must flip the ACRO/STABILIZE switch back to MANUAL? That will require a different reflex action than my current one.

**Comment by tumbili** [comment]
@kd0aij Not 100% sure but in case of a fmu hang the IO should notice and go to failsafe.

**Comment by kd0aij** [comment]
I doubt that the IO processor is smart enough to know when the FMU is confused.

**Pull request closed without merging**
