### PR TITLE
AKM mag cleanup (AK09916 + AK8963) including corresponding Invensense IMUs (icm20948 + mpu9250)

### PR DESCRIPTION
**Pull request by dagar**
@mirkix

### CODE REVIEW

**Comment by dagar** [comment]
I don't think the DRDY bit is populating the way we thought in continuous measurement mode.

Screenshot from 2020-06-18 11-30-54

**Comment by mirkix** [comment]
@dagar Tested is PR today without success. 

It seems that the "dataflow stuck" with your PR tested on Cube Yellow and Orange

With Master:
```Work Queue: 7 threads                        RATE        INTERVAL
|__ 1) wq:lp_default   
|   |__ 1) send_event                     30.0 Hz        33332 us (33333 us)
|   \__ 2) load_mon                        1.0 Hz       996903 us (1000000 us)
|__ 2) wq:hp_default   
|   |__ 1) tone_alarm                     10.2 Hz        97814 us
|   |__ 2) rc_update                       0.0 Hz            0 us
|   |__ 3) adc                           100.0 Hz         9999 us (10000 us)
|   \__ 4) battery_status                100.0 Hz         9999 us (10000 us)
|__ 3) wq:SPI1         
|   |__ 1) ms5611                         99.5 Hz        10054 us
|   \__ 2) icm20649                      750.0 Hz         1333 us (1333 us)
|__ 4) wq:SPI4         
|   |__ 1) ms5611                         99.3 Hz        10071 us
|   |__ 2) icm20602                      799.7 Hz         1251 us (1250 us)
|   |__ 3) icm20948                      749.6 Hz         1334 us (1333 us)
|   \__ 4) icm20948_ak09916               49.5 Hz        20215 us (20000 us)
|__ 5) wq:navigation_and_controllers
|   |__ 1) sensors                       187.6 Hz         5332 us
|   |__ 2) vehicle_acceleration          196.5 Hz         5089 us
|   |__ 3) vehicle_air_data               74.5 Hz        13414 us
|   |__ 4) vehicle_imu                   188.4 Hz         5308 us
|   |__ 5) vehicle_imu                   200.8 Hz         4980 us
|   |__ 6) vehicle_imu                   188.3 Hz         5310 us
|   \__ 7) ekf2                          187.6 Hz         5332 us
|__ 6) wq:rate_ctrl    
|   \__ 1) vehicle_angular_velocity      750.2 Hz         1333 us
\__ 7) wq:uavcan       
    |__ 1) uavcan                        407.5 Hz         2454 us (3000 us)
    \__ 2) uavcan-actuators                0.0 Hz            0 us
```

With this PR:
```
Work Queue: 7 threads                        RATE        INTERVAL
|__ 1) wq:lp_default
|   |__ 1) send_event                     30.0 Hz        33331 us (33333 us)
|   \__ 2) load_mon                        1.0 Hz       996911 us (1000000 us)
|__ 2) wq:hp_default
|   |__ 1) tone_alarm                     10.2 Hz        98045 us
|   |__ 2) rc_update                       0.0 Hz            0 us
|   |__ 3) adc                           100.0 Hz        10000 us (10000 us)
|   \__ 4) battery_status                100.0 Hz         9999 us (10000 us)
|__ 3) wq:SPI1
|   |__ 1) ms5611                         99.6 Hz        10037 us
|   \__ 2) icm20649                      102.6 Hz         9746 us
|__ 4) wq:SPI4
|   |__ 1) ms5611                         99.6 Hz        10042 us
|   |__ 2) icm20602                      799.9 Hz         1250 us (1250 us)
|   |__ 3) icm20948                       86.8 Hz        11523 us
|   \__ 4) icm20948_ak09916               13.5 Hz        74118 us
|__ 5) wq:navigation_and_controllers
|   |__ 1) sensors                       199.5 Hz         5013 us
|   |__ 2) vehicle_acceleration          207.3 Hz         4824 us
|   |__ 3) vehicle_air_data               74.7 Hz        13395 us
|   |__ 4) ekf2                          200.0 Hz         5000 us
|   |__ 5) vehicle_imu                   177.4 Hz         5637 us
|   |__ 6) vehicle_imu                   200.8 Hz         4981 us
|   \__ 7) vehicle_imu                   163.3 Hz         6123 us
|__ 6) wq:rate_ctrl
|   \__ 1) vehicle_angular_velocity      796.3 Hz         1256 us
\__ 7) wq:uavcan
    |__ 1) uavcan                        335.3 Hz         2982 us (3000 us)
    \__ 2) uavcan-actuators                0.0 Hz            0 us
```

**Comment by dagar** [comment]
Thanks for the test. It looks like I managed to break the icm20649 as well. 

``` Console
|__ 3) wq:SPI1
|   |__ 1) ms5611                         99.6 Hz        10037 us
|   \__ 2) icm20649                      102.6 Hz         9746 us
```

I need to give this a try on actual hardware today. I was mainly looking at the mpu9250 so far and mirrored the changes (ak8963 -> ak09916).

**Comment by dagar** [comment]
@mirkix can you give this another try?

``` Console
nsh>  work_queue status

Work Queue: 7 threads                        RATE        INTERVAL
|__ 1) wq:lp_default   
|   |__ 1) send_event                     30.0 Hz        33332 us (33333 us)
|   |__ 2) load_mon                        1.0 Hz       999885 us (1000000 us)
|   \__ 3) mc_hover_thrust_estimator       0.0 Hz            0 us
|__ 2) wq:hp_default   
|   |__ 1) tone_alarm                     10.0 Hz        99843 us
|   |__ 2) rc_update                       0.0 Hz            0 us
|   |__ 3) adc                           100.0 Hz        10000 us (10000 us)
|   |__ 4) battery_status                100.0 Hz        10000 us (10000 us)
|   \__ 5) pwm_out                         0.0 Hz    277134688 us
|__ 3) wq:SPI1         
|   |__ 1) ms5611                         99.6 Hz        10043 us
|   \__ 2) icm20649                      750.1 Hz         1333 us (1333 us)
|__ 4) wq:SPI4         
|   |__ 1) ms5611                         99.5 Hz        10046 us
|   |__ 2) icm20602                      800.0 Hz         1250 us (1250 us)
|   |__ 3) icm20948                      750.1 Hz         1333 us (1333 us)
|   \__ 4) icm20948_ak09916               50.0 Hz        20004 us (20000 us)
|__ 5) wq:navigation_and_controllers
|   |__ 1) sensors                       187.5 Hz         5333 us
|   |__ 2) vehicle_acceleration          188.2 Hz         5314 us
|   |__ 3) vehicle_air_data               74.7 Hz        13392 us
|   |__ 4) ekf2                          187.5 Hz         5332 us
|   |__ 5) mc_pos_control                  0.0 Hz            0 us
|   |__ 6) land_detector                  50.0 Hz        20000 us (20000 us)
|   |__ 7) vehicle_imu                   187.6 Hz         5330 us
|   |__ 8) vehicle_imu                   200.1 Hz         4998 us
|   \__ 9) vehicle_imu                   187.6 Hz         5330 us
|__ 6) wq:rate_ctrl    
|   |__ 1) vehicle_angular_velocity      749.9 Hz         1334 us
|   \__ 2) mc_rate_control               750.0 Hz         1333 us
\__ 7) wq:attitude_ctrl
    \__ 1) mc_att_control                  0.0 Hz            0 us
```

``` Console
nsh> icm20948 status
INFO  [SPI_I2C] Running on SPI Bus 4
INFO  [icm20948] FIFO empty interval: 1333 us (750.2 Hz)
icm20948: transfer: 855586 events, 177684040us elapsed, 207.68us avg, min 173us max 299us 11.228us rms
icm20948: bad register: 0 events
icm20948: bad transfer: 0 events
icm20948: FIFO empty: 0 events
icm20948: FIFO overflow: 0 events
icm20948: FIFO reset: 1 events
icm20948_ak09916: transfer: 57010 events, 1463528us elapsed, 25.67us avg, min 22us max 119us 7.183us rms
icm20948_ak09916: bad transfer: 1 events
icm20948_ak09916: magnetic sensor overflow: 0 events
INFO  [drivers_magnetometer] /dev/mag device instance: 0
INFO  [drivers_magnetometer] calibration scale: 1.00000 1.00000 1.00000
INFO  [drivers_magnetometer] calibration offset: 0.00000 0.00000 0.00000
```

``` Console
nsh> sensors status
INFO  [sensors] selected gyro: 2424842 (0)
INFO  [data_validator] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [data_validator] sensor #0, prio: 100, state: OK
INFO  [data_validator]  val:   0.0039, lp:   0.0002 mean dev:  -0.0000 RMS:   0.0026 conf:   1.0000
INFO  [data_validator]  val:  -0.0031, lp:  -0.0006 mean dev:   0.0001 RMS:   0.0026 conf:   1.0000
INFO  [data_validator]  val:   0.0011, lp:  -0.0001 mean dev:  -0.0001 RMS:   0.0025 conf:   1.0000
INFO  [data_validator] sensor #1, prio: 100, state: OK
INFO  [data_validator]  val:   0.0000, lp:   0.0002 mean dev:   0.0000 RMS:   0.0007 conf:   1.0000
INFO  [data_validator]  val:   0.0002, lp:   0.0000 mean dev:  -0.0000 RMS:   0.0008 conf:   1.0000
INFO  [data_validator]  val:  -0.0006, lp:  -0.0001 mean dev:   0.0000 RMS:   0.0007 conf:   1.0000
INFO  [data_validator] sensor #2, prio: 75, state: OK
INFO  [data_validator]  val:   0.0001, lp:  -0.0004 mean dev:   0.0000 RMS:   0.0016 conf:   1.0000
INFO  [data_validator]  val:   0.0000, lp:   0.0001 mean dev:   0.0000 RMS:   0.0016 conf:   1.0000
INFO  [data_validator]  val:  -0.0017, lp:  -0.0001 mean dev:  -0.0000 RMS:   0.0015 conf:   1.0000

INFO  [sensors] selected accel: 2424842 (0)
INFO  [data_validator] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [data_validator] sensor #0, prio: 100, state: OK
INFO  [data_validator]  val:  -0.7533, lp:  -0.7303 mean dev:   0.0004 RMS:   0.0181 conf:   1.0000
INFO  [data_validator]  val:  -0.9892, lp:  -0.9941 mean dev:   0.0001 RMS:   0.0195 conf:   1.0000
INFO  [data_validator]  val:  -9.7754, lp:  -9.7536 mean dev:  -0.0007 RMS:   0.0236 conf:   1.0000
INFO  [data_validator] sensor #1, prio: 100, state: OK
INFO  [data_validator]  val:  -0.7058, lp:  -0.6979 mean dev:  -0.0001 RMS:   0.0093 conf:   1.0000
INFO  [data_validator]  val:  -0.9546, lp:  -0.9518 mean dev:   0.0000 RMS:   0.0093 conf:   1.0000
INFO  [data_validator]  val:  -9.7474, lp:  -9.7511 mean dev:   0.0019 RMS:   0.0095 conf:   1.0000
INFO  [data_validator] sensor #2, prio: 75, state: OK
INFO  [data_validator]  val:  -0.6975, lp:  -0.6969 mean dev:   0.0003 RMS:   0.0163 conf:   1.0000
INFO  [data_validator]  val:  -0.9411, lp:  -0.9413 mean dev:   0.0003 RMS:   0.0172 conf:   1.0000
INFO  [data_validator]  val:  -9.7590, lp:  -9.7339 mean dev:   0.0021 RMS:   0.0166 conf:   1.0000

INFO  [sensors] selected mag: 0 (0)
INFO  [data_validator] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [data_validator] sensor #0, prio: 75, state: OK
INFO  [data_validator]  val:  -0.5400, lp:  -0.5479 mean dev:  -0.0016 RMS:   0.0177 conf:   1.0000
INFO  [data_validator]  val:  -0.1725, lp:  -0.1701 mean dev:  -0.0010 RMS:   0.0157 conf:   1.0000
INFO  [data_validator]  val:   0.4020, lp:   0.5111 mean dev:  -0.0142 RMS:   0.1155 conf:   1.0000

INFO  [vehicle_air_data] selected barometer: 3997706 (0)
INFO  [data_validator] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [data_validator] sensor #0, prio: 75, state: OK
INFO  [data_validator]  val: 101309.0000, lp: 101311.7031 mean dev:  -0.0355 RMS:   2.7434 conf:   1.0000
INFO  [data_validator]  val:  54.4500, lp:  54.4414 mean dev:  -0.0126 RMS:   0.0187 conf:   1.0000
INFO  [data_validator]  val:   0.0000, lp:   0.0000 mean dev:   0.0000 RMS:   0.0000 conf:   1.0000
INFO  [data_validator] sensor #1, prio: 75, state: OK
INFO  [data_validator]  val: 101265.0000, lp: 101265.9375 mean dev:   0.3565 RMS:   4.1705 conf:   1.0000
INFO  [data_validator]  val:  64.7700, lp:  64.7757 mean dev:   0.0077 RMS:   0.0324 conf:   1.0000
INFO  [data_validator]  val:   0.0000, lp:   0.0000 mean dev:   0.0000 RMS:   0.0000 conf:   1.0000

```

**Comment by dagar** [comment]
If anyone is curious (present or future) about the thought behind maintaining separate ak8963/ak09916 drivers both standalone and within the mpu9250/icm20948, it's because I didn't want to sacrifice the performance of any IMU or any other device on the same SPI bus.

It's possible to create a virtual I2C interface that passes through to the Invensense I2C slaves, however those slow I2C reads could block the bus (a workqueue thread per bus) for a relatively long period (relative to high rate IMU). Alternatively it could be run from a separate thread, but then additional synchronization is needed, and there's still the potential to interfere with high rate IMU access, which is arguably the most important part of the system.

**Comment by mirkix** [comment]
@dagar Tested with CubeYellow, still have the jumps in the zmag.
Screenshot from 2020-06-22 07-56-33

**Comment by mirkix** [comment]
@dagar The zmag noise is from the iomcu https://github.com/PX4/Firmware/blob/master/src/modules/px4iofirmware/px4io.c#L469

**Comment by mirkix** [comment]
@dagar The zmag noise for the CubeYellow and CubeOrange is solved by https://github.com/PX4/Firmware/pull/15181

**Pull request merged**
