### PR TITLE
cubeorange and cubeyellow disable serial console by default

### PR DESCRIPTION
**Pull request by dagar**
- the cube orange comes with ADSB connected to what was the serial console
 - add console builds (cubepilot_cubeorange_console) for hardware test rack

### CODE REVIEW

**Comment by dagar** [comment]
Once this is working it should be back ported for v1.11.1. With ADSB connected to the NuttX serial console it's apparently possible to crash nsh (and the board).

**Comment by hamishwillee** [comment]
@dagar So the port labeled "debug" here on cube yellow and orange is actually not a debug port? http://docs.px4.io/master/en/flight_controller/cubepilot_cube_orange.html#debug-ports

**Comment by mirkix** [comment]
@dagar Tested with CubeOrange successful.
`make cubepilot_cubeorange_default` -> nsh console disabled on debug port, nsh console via MAVLink working
`make cubepilot_cubeorange_console` -> nsh console enabled on debug port and nsh console via MAVLink working

**Comment by dagar** [comment]
> @dagar So the port labeled "debug" here on cube yellow and orange is actually not a debug port (console)? http://docs.px4.io/master/en/flight_controller/cubepilot_cube_orange.html#debug-ports
> 
> Note, I assume it is this one that is the console (not "Edison debug") and that the SWD port is inside the case.

@hamishwillee I'm not sure about that USB debug port on the (original?) cube carrier board, but this is/was the serial console (CONS). My understanding is that at least on the Cube Orange ADSB is now standard on the carrier board and connected to this serial port. I'm not sure about the yellow.

Screenshot from 2020-09-21 11-49-29


> @dagar Tested with CubeOrange successful.
> `make cubepilot_cubeorange_default` -> nsh console disabled on debug port, nsh console via MAVLink working
> `make cubepilot_cubeorange_console` -> nsh console enabled on debug port and nsh console via MAVLink working

@mirkix thanks for the test. I'll keep things consistent between the yellow and orange for now.

**Comment by dagar** [comment]
Backport for v1.11.1 https://github.com/PX4/Firmware/pull/15777.

**Pull request merged**
