### PR TITLE
Fix uUORB multi-pub/sub

### LINKED ISSUE #2319: uORB multi pubsub depends on order of subscribing/publishing
Below is what I found, correct me if I'm just wrong :):

Basically, I think, in the current multi pubsub implementation, the publisher needs to be started before the subscriber, otherwise they won't talk to each other.

An example from #2297 would be:

1. Mavlink starts first and wants to subscribe to the distance_sensor topic. It gets the first instance here:
https://github.com/PX4/Firmware/blob/master/src/modules/uORB/uORB.cpp#L144
2. The the ll40ls wants to do a advertise_multi:
https://github.com/PX4/Firmware/blob/master/src/drivers/ll40ls/LidarLitePWM.cpp#L116
https://github.com/PX4/Firmware/blob/master/src/modules/uORB/uORB.cpp#L93
I believe this fails here:
https://github.com/PX4/Firmware/blob/master/src/modules/uORB/uORBManager_nuttx.cpp#L246
And gets +1 here probably:
https://github.com/PX4/Firmware/blob/master/src/modules/uORB/uORBDevices_nuttx.cpp#L471
3. This leads to mavlink subscribing on 0 and the ll40ls publishing on 1.

Instead of the check ...
- Does the node exist already?

It should be something like:
- Does the node exist already and has stuff been published yet?
- Does the node exist already but is it only opened by a subscriber?

### PR DESCRIPTION
**Pull request by bansiesta**
Fixes #2319.
More description in the commit messages.

Tested with the unittest image.
Please cross-test the POSIX version.

I recommend doing the review based on commits, otherwise there is way too much whitespace noise!

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@mcharleb You will want to have a look here, I want to mainline the fix ASAP since it fixes an init race condition.

**Comment by AndreasAntener** [comment]
SITL CI test this please

**Comment by AndreasAntener** [comment]
SITL CI test this please

**Comment by AndreasAntener** [comment]
SITL CI test this please

**Comment by bansiesta** [comment]
@AndreasAntener This one? https://pixhawk.org/dev/ros/sitl_testing

**Comment by AndreasAntener** [comment]
sorry @bansiesta, that wasn't a request for someone to do the test ;) it's a trigger for Jenkins to start the build again

**Comment by mcharleb** [comment]
/home/travis/build/PX4/Firmware/src/modules/mavlink/mavlink_messages.cpp:418:58: error: 'errno' was not declared in this scope

Otherwise the changes look good.

**Comment by bansiesta** [comment]
@mcharleb I didn't change anything in mavlink_messages.cpp?

**Comment by mcharleb** [comment]
@bansiesta mavlink_messages.cpp was the Travis failure. The file in master seems to include errno.h so not sure what is going on.

**Pull request closed without merging**
