### PR TITLE
EKF voting priority

### PR DESCRIPTION
**Pull request by LorenzMeier**
This adds support for sensor priorities to the voter.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@pavel-kirienko This fixes UAVCAN - I will need your *solid* cross testing (testing that without the 8s delay the mag is found each time correctly and testing that if you unplug the bus it fails over to the internal one).

**Comment by mhkabir** [comment]
I will get this up to scratch.

**Comment by pavel-kirienko** [comment]
@LorenzMeier @mhkabir Sorry, on a business trip, will be able to test it in 2 weeks. Kabir, if you could perform at least some initial validation that would be highly appreciated. I'll be available for assistance via Skype or whatever.

**Comment by mhkabir** [comment]
@pavel-kirienko @LorenzMeier 
OK, this works well :
1. Uses the external UAVCAN mag.
2. On unplugging the unit, falls back to internal.
3. Tested without any timing hacks, powered by battery/USB.
4. The calibration issues due to boot timing no longer an issue after removing boot delay.
Also tested by@Aperture-Laboratories.
We just need to vet the rest of the external mag drivers to make sure that they have higher priority than default.

**Comment by LorenzMeier** [comment]
@mhkabir Could you test this on UAVCAN without boot delay? My goal would be to get things wrapped up completely so that we feel confident its all ready to go.

**Comment by mhkabir** [comment]
Yes, tested without boot delay. See point (3) above. ;)

**Comment by LorenzMeier** [comment]
Its great you've tested it - could we get a PR for that? I appreciate the effort you've put into UAVCAN, but I'm never quite sure how we can reproduce the results as patches and documentation are not around. It would be great to have those, so others can benefit (and see and appreciate all the work you're putting into it!).

**Pull request merged**
