### PR TITLE
Update nuttx with hardfault fix for kinetis on i2c reset

### PR DESCRIPTION
**Pull request by davids5**
This brings in the HF on i2c cable removal or i2c reset.

### CODE REVIEW

**Comment by dagar** [comment]
@davids5 is this safe to test fly?

**Comment by davids5** [comment]
@dagar soon....

**Comment by davids5** [comment]
@dagar yes it is safe to fly. The bug is critical and has been bench test by pulling the i2c.

**Comment by dagar** [comment]
@PX4/testflights could you please test this on nxphlite?

**Comment by Avysuarez** [comment]
The fc arming but the motors do not spin.
https://review.px4.io/plot_app?log=92603aab-382c-4b01-bc66-24efe9a1214a

**Comment by davids5** [comment]
@Avysuarez - Just to close the loop.  This was merged to master with the safety switch fixed. Pleas Fly master. @dagar FYI.

**Pull request merged**
