### PR TITLE
fill missing command ack.

### LINKED ISSUE #4804: Not all commands are being replied with a COMMAND_ACK
Not all commands in COMMAND_INT/COMMAND_LONG messages are being replied with a COMMAND_ACK, for example, MAV_CMD_NAV_TAKEOFF, MAV_CMD_NAV_LAND etc.

Indeed from examining commander.cpp, is seems handle_command doesn't execute answer_command in any condition.

Thank you.

### PR DESCRIPTION
**Pull request by iZhangHui**
fix #4804 Not all commands are being replied with a COMMAND_ACK

### CODE REVIEW

**Comment by julianoes** [comment]
This looks correct.

**Comment by MHageH** [comment]
Is MAV_CMD_NAV_GUIDED_ENABLE (offboard control) getting replied with a COMMAND_ACK? I'm testing this right now, seems fine for arming/disarming, but fails for offboard control.

**Comment by iZhangHui** [comment]
Hi @MHageH, would you please give a description how did you test this?
arm/disarm command ack works on the master code. This PR add the command ack for takeoff, land, guided_enable command.

**Comment by MHageH** [comment]
Hi @iZhangHui, In the original [C UART Interface](https://github.com/mavlink/c_uart_interface_example), (the offboard control example for *nix systems) or even the [modified](https://github.com/MHageH/c_uart_interface) one, I added this segment of code to the [autopilot_interface::read_messages()](https://github.com/mavlink/c_uart_interface_example/blob/master/autopilot_interface.cpp#L235) function : 
```
case MAVLINK_MSG_ID_COMMAND_ACK:{
					printf("Command acknowledgement recieved\n");

					mavlink_msg_command_ack_decode(&message, &(current_messages.command_ack));
					current_messages.time_stamps.command_ack = get_time_usec();
					this_timestamps.command_ack = current_messages.time_stamps.command_ack;
					break;
					}
```
As well as modifying the required data structures in [autopilot_interface.h](https://github.com/mavlink/c_uart_interface_example/blob/master/autopilot_interface.h#L134)

Each time I send MAV_CMD_COMPONENT_ARM_DISARM, the autopilot and even SITL responds with a command ack. This isn't the case for MAV_CMD_NAV_GUIDED_ENABLE. 

Altho this was for the stable version, I'm added the [changes](https://github.com/PX4/Firmware/pull/4814/files) made by this PR to commander.cpp on master manually, and it seems to work fine.

Please check if you can add the changes to stable version too, thanks.

**Pull request merged**
