### PR TITLE
Attempt to fix MAVSDK tests CI

### LINKED ISSUE #14835: intermittent SITL test failures
- https://github.com/PX4/Firmware/pull/14834/checks?check_run_id=646212154
 
Screenshot from 2020-05-05 10-00-36

### PR DESCRIPTION
**Pull request by julianoes**
Work in progress to fix #14835

### CODE REVIEW

**Comment by julianoes** [comment]
Good but now Jenkins fails :thinking:.

**Comment by julianoes** [comment]
However, this still fails sometimes locally, here is an example where the estimation is bonkers:
https://logs.px4.io/plot_app?log=af8d98b8-3042-4e1d-bf43-ca97a5cf9bd0

**Comment by kamilritz** [comment]
Cool. Is it really not possible to keep the vision and flow models?

**Comment by julianoes** [comment]
> Cool. Is it really not possible to keep the vision and flow models?

Good point. I'm just now testing with them again locally.

**Comment by julianoes** [comment]
@kamilritz at 20x they certainly fail:

```
[mavsdk_tests] Target position reached
[mavsdk_tests] target_pos.lat: 47.3978
[mavsdk_tests] target_pos.lon: 8.54561
[mavsdk_tests] current.lat: 47.3979
[mavsdk_tests] current.lon: 8.54579
[mavsdk_tests] Distance: 18.6475
[mavsdk_tests] Acceptance radius: 1
```

**Comment by julianoes** [comment]
We might be able to add them at 1x but given they fail at 20x it would hint that timing in general can make it fail, so e.g. if the CI runner's CPU is low.

**Comment by julianoes** [comment]
@dagar ok if we merge this?

**Comment by julianoes** [comment]
Actually as suggested I should try to re-enable flow_mockup.

**Comment by julianoes** [comment]
Alright, more failures, also locally. I'll have to check again.

**Comment by julianoes** [comment]
I'm gonna merge this because it should be a first improvement. After that I can look at the new failures coming in.

**Pull request merged**
