### PR TITLE
Improvements to SITL to make paths more flexible. (#5181)

### PR DESCRIPTION
**Pull request by LorenzMeier**
@jgoppert This is the diff from the improvements re-applied to master. Needs fixing for local use at least on Mac OS and untangling of ROS from Gazebo dependencies.

### CODE REVIEW

**Comment by jgoppert** [comment]
@LorenzMeier any chance to get this in for 1.4 release?

**Comment by LorenzMeier** [comment]
I don't think so for 1.4.1 but could well go in for 1.4.2.

**Comment by jgoppert** [comment]
@LorenzMeier I had another look at the gazebo ros setup script. There is nothing ROS related in it, or the sitl script now, so I just renamed it to setup_gazebo.sh. Do you have any more details of your issues on Mac, is there any chance we can get them resolved today?

**Comment by jgoppert** [comment]
@dagar, @tumbili , @mhkabir , @julianoes, @bkueng  If you guys can test this I think you will like the improvements to SITL as far as organization of data files and binaries for the end user. It is also an improvement for ROS integration as well. You can build it in a catkin workspace and everything "just works". It passes all the CI, but Lorenz found some issues on Mac that CI didn't catch so we need to make sure it works smoothly on all operating systems.

**Comment by bkueng** [comment]
LGTM, but you need to resolve with @julianoes for #5162 
Why is the `src` symlink needed?

**Comment by jgoppert** [comment]
@bkueng Thanks for taking a look. The src dir I thought was referenced in a unit test, but I can't locate it so I'm removing it and will see if CI passes.

**Comment by jgoppert** [comment]
@bkueng The culprit is rc_tests, it embeds its test data in the src directory, so that is the reason for the symlink.

**Comment by jgoppert** [comment]
@LorenzMeier I have minimized the diff here by splitting out the low-impact changes in #5340. Do you have time to check again if you are having issues on mac?

**Comment by jgoppert** [comment]
@tumbili @bkueng @LorenzMeier this is now a tiny diff from master so it should be easier to review

**Comment by julianoes** [comment]
@jgoppert I'd say the changes are ok but I don't have a strong opinion about this.

Since I've pretty much rewritten the POSIX main.cpp in the shell branch, I'm mostly concerned about having to manually copy over your changes in main concerning the symlinking. It'll be some effort but probably doable.

**Comment by jgoppert** [comment]
@julianoes I want to get your PR in too, so I managed to separate everything that wouldn't impact you and get it into master already. I really think the symlink SITL root is a decent approach and allows us to setup a good structure to mimic the real filesystem without having to duplicate resources or move how things are built. I'm open to other approaches, but I just want to make sure everything works well with ROS/catkin. By adding the path argument for the root filesystem to main this allows ROS to hook in easily.

**Comment by jgoppert** [comment]
@julianoes Are you ok with merging this into master first?

**Comment by julianoes** [comment]
@jgoppert I'm just testing this on Max OS 10.11:

```
cd /Users/julianoes/src/Firmware/...anoes/src/Firmware/build_posix_sitl_default
args: /Users/julianoes/src/Firmware/build_posix_sitl_default/src/firmware/posix/px4 posix-configs/SITL/init/lpe none gazebo none /Users/julianoes/src/Firmware /Users/julianoes/src/Firmware/build_posix_sitl_default
SITL ARGS
sitl_bin: /Users/julianoes/src/Firmware/build_posix_sitl_default/src/firmware/posix/px4
label: posix-configs/SITL/init/lpe
debugger: none
program: gazebo
model: none
src_path: /Users/julianoes/src/Firmware
build_path: /Users/julianoes/src/Firmware/build_posix_sitl_default
empty model, setting iris as default
/Users/julianoes/src/Firmware/Tools/sitl_run.sh: line 79: /usr/share/gazebo/setup.sh: No such file or directory
FAILED: src/firmware/posix/CMakeFiles/gazebo 
cd /Users/julianoes/src/Firmware/build_posix_sitl_default/tmp && /Users/julianoes/src/Firmware/Tools/sitl_run.sh /Users/julianoes/src/Firmware/build_posix_sitl_default/src/firmware/posix/px4 posix-configs/SITL/init/lpe none gazebo none /Users/julianoes/src/Firmware /Users/julianoes/src/Firmware/build_posix_sitl_default
ninja: build stopped: subcommand failed.
make: *** [posix_sitl_default] Error 1
```

What am I doing wrong?

**Comment by LorenzMeier** [comment]
James, seems like paths got hardcoded again.

**Comment by jgoppert** [comment]
@julianoes Thanks for finding this. This reverts the gazebo paths to how they were on master, so it should work on mac without issue.

**Comment by julianoes** [comment]
@jgoppert Thanks, it's working now.

**Comment by jgoppert** [comment]
@LorenzMeier can you give this another once over?

**Comment by julianoes** [comment]
@LorenzMeier are you fine to merge this?

**Comment by jgoppert** [comment]
Would be awesome if we could get this merged today.

**Comment by LorenzMeier** [comment]
@jgoppert Yes, you put so much effort into this we can't afford to keep this lingering any second longer. Thanks for testing on Mac @julianoes 8)

**Comment by julianoes** [comment]
No worries, thanks @jgoppert for your many iterations. I'll start rebasing the shell branch.

**Pull request merged**
