### PR TITLE
Add STM32F4 discovery config.

### PR DESCRIPTION
**Pull request by LorenzMeier**
This is thanks to @nopeppermint. Merging if build systems like it.

### CODE REVIEW

**Comment by nopeppermint** [comment]
> Merging if build systems like it.<

It doesn't like it :-1:

**Comment by dagar** [comment]
Hans-ci (runs testing on a pixhawk) just failed to clone. Travis-ci passed.

**Comment by nopeppermint** [comment]
why Hans-ci failed ? and what does this mean?

**Comment by LorenzMeier** [comment]
A network failure. Will need to cache the GIT repo locally.

**Pull request merged**
