### PR TITLE
Master nuttx warnings

### PR DESCRIPTION
**Pull request by davids5**
Use as strict or stricter warnings than NuttX.

### CODE REVIEW

**Comment by dagar** [comment]
This reminds me, we should really think about enabling (or not disabling) Wsign-compare.

**Comment by dagar** [comment]
NuttX build options are repeated.

arm-none-eabi-gcc -c -std=gnu99 -Wall -Wextra -Werror -Wdouble-promotion -Wframe-larger-than=1024 -Wlogical-op -Wpacked -Wpointer-arith -Wshadow -Wno-sign-compare -Wno-unused-parameter -Wno-nonnull-compare -Wno-misleading-indentation -Wall -Wextra -Werror -Wdouble-promotion -Wframe-larger-than=1024 -Wlogical-op -Wpacked -Wpointer-arith -Wshadow -Wno-sign-compare -Wno-unused-parameter -Wno-nonnull-compare -Wno-misleading-indentation -Wbad-function-cast -Wmissing-parameter-type -Wnested-externs -Wstrict-prototypes -Wno-bad-function-cast -Wno-cpp -Wno-implicit-function-declaration -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-nested-externs -Wno-old-style-declaration -Wno-pointer-sign -Wno-type-limits -Wno-unused-but-set-variable -Wno-unused-function -Wno-unused-label -Wno-unused-variable -Os -fno-strict-aliasing -fno-strength-reduce -fomit-frame-pointer -funsafe-math-optimizations -fno-builtin-printf -ffunction-sections -fdata-sections -g -mcpu=cortex-m4 -mthumb -march=armv7e-m -mfpu=fpv4-sp-d16 -mfloat-abi=hard -I. -isystem /home/dagar/git/Firmware/build_px4fmu-v3_default/px4fmu-v3/NuttX/nuttx/include   -D__KERNEL__ -pipe -fno-common  vfs/fs_rmdir.c -o  fs_rmdir.o

**Comment by davids5** [comment]
@dagar 

>This reminds me, we should really think about enabling (or not disabling) Wsign-compare.

What is the history on this?

**Comment by davids5** [comment]
@dagar 
>NuttX build options are repeated. 

Is fixed in 947d7e4

**Pull request merged**
