### PR TITLE
Adds UAVCAN Support for NXPhlite V3

### PR DESCRIPTION
**Pull request by davids5**
**Test data / coverage**
Vetted against px4esc1.6

### CODE REVIEW

**Comment by davids5** [comment]
@dagar commits af59d00..825e6d0 could just go to master. The remainder have to stay on the leitwert-nxphlite-serial-dma until I get all the Nuttx changes upstreamed.

**Comment by davids5** [comment]
@mcsauder - yep - I missed that, thank you!

We are going to have to do a major pass on the tunes.
For instance:The tune control is blocking. Some of the code is calling tone alarm, Some of the sequences do not emit tones. `tune_control play -m MNBG` on my HW (but I need to check V5)

**Comment by dagar** [comment]
> @dagar commits af59d00..825e6d0 could just go to master.

Can you open a separate PR? This one can be rebased later.

**Comment by davids5** [comment]
>>@dagar commits af59d00..825e6d0 could just go to master.

>Can you open a separate PR? This one can be rebased later.

Done! 

@dagar Now that this has passed CI Let's merge this to leitwert-nxphlite-serial-dma to consolidate 

I will fix the TUNE_ERR issue that @mcsauder pointed out there

**Pull request merged**
