### PR TITLE
Jenkins run tests under address sanitizer and fix issues

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
2 failures

1. mag declination (now part of ecl)
image

2. dataman
image

**Comment by dagar** [comment]
TODO - add proper shutdown so that we can run mission tests under asan. Currently it reports everything as a memory leak.

**Comment by dagar** [comment]
ECL geo_mag_lookup change - https://github.com/PX4/ecl/pull/441

**Comment by bkueng** [comment]
Regarding dataman: the only way how there can be an overflow is if `item` is out of bounds when accessing `g_per_item_size` and your change does not really fix that. The fix would be a simple bound check, and find out where the wrong index comes from.

**Comment by dagar** [comment]
@bkueng I was also trying to get rid of the variable sized array on the stack. Bounds check added.

**Pull request merged**
