### PR TITLE
[DO NOT MERGE] IMU clipping testing

### PR DESCRIPTION
**Pull request by dagar**
This is a followup to https://github.com/PX4/Firmware/pull/13103 to explore remedies for severe IMU clipping.

https://github.com/PX4/ecl/pull/663

### CODE REVIEW

**Comment by dagar** [comment]
@PX4/testflights could you give this a quick test on an fmu-v4 (pixracer) or fmu-v4pro (piwhawk 3 pro)? We just need a quick log for further investigation.

**Comment by Junkim3DR** [comment]
### Tested on Pixhawk Pro v4

**Note**
Vehicle did not connect to RC, it would not let the user bind the RC nor calibrate, same issue was noticed on Master but not on Stable firmware.

**Logs**
- PR13837: https://review.px4.io/plot_app?log=51c918b7-763c-41c8-b7c8-4a162be0fd3d
- Master: https://review.px4.io/plot_app?log=e9b18b85-685e-4f30-8931-9bfdafbc159a

**Comment by dagar** [comment]
> ### Tested on Pixhawk Pro v4
> **Note**
> Vehicle did not connect to RC, it would not let the user bind the RC nor calibrate, same issue was noticed on Master but not on Stable firmware.
> 
> **Logs**
> 
> * PR13837: https://review.px4.io/plot_app?log=51c918b7-763c-41c8-b7c8-4a162be0fd3d
> * Master: https://review.px4.io/plot_app?log=e9b18b85-685e-4f30-8931-9bfdafbc159a

When's the last time the pixhawk 3 pro worked on master? Does fmu-v4 (pixracer) work?

**Comment by jorge789** [comment]
### Tested in PixRacer V4:

**Note:** Indoor test flight Modes: StabalizeNotes: Due to the bad weather we not able to do outdoor test flights. We did some indoor test flights, Takeoff in stabilize mode

**Log:**  https://review.px4.io/plot_app?log=24a6d0da-a1b3-4143-b7ce-6359d3647bb4

**Comment by Junkim3DR** [comment]
> When's the last time the pixhawk 3 pro worked on master? Does fmu-v4 (pixracer) work?

This is a new board, we just installed it to this airframe since the previous board had issues with the SD card slot (It did not spring the SD card). 

Previous board was working well, no issues but the SD card slot.

**Comment by Tony3dr** [comment]
> > ### Tested on Pixhawk Pro v4
> > **Note**
> > Vehicle did not connect to RC, it would not let the user bind the RC nor calibrate, same issue was noticed on Master but not on Stable firmware.
> > **Logs**
> > 
> > * PR13837: https://review.px4.io/plot_app?log=51c918b7-763c-41c8-b7c8-4a162be0fd3d
> > * Master: https://review.px4.io/plot_app?log=e9b18b85-685e-4f30-8931-9bfdafbc159a
> 
> When's the last time the pixhawk 3 pro worked on master? Does fmu-v4 (pixracer) work?
@dagar these are the last working logs on Master for the Pixhawk Pro.  The PixRacer seems to be working fine. 
Flight card 1
Log:  https://review.px4.io/plot_app?log=35d59e70-c3f1-4bfc-a76a-ec8de20261c3
  Flight card 2
Log:   https://review.px4.io/plot_app?log=0ebede1a-549f-4638-af23-7dcfe365e371
  Flight card 3 
Log:  https://review.px4.io/plot_app?log=5bbb5e95-acd1-4fd1-a78d-5f2e028d8fb7
Flight card 4
Log:  https://review.px4.io/plot_app?log=81e3f2bd-bcca-4263-9b00-20f9beea0d6a

**Comment by Tony3dr** [comment]
Reference issue [#13892 ](https://github.com/PX4/Firmware/issues/13892)

**Comment by dannyfpv** [comment]
Flight Card 1

Modes Tested:
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.

Procedure:
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode.

Notes:
No issues were noted, good flight in general.

Logs:

https://review.px4.io/plot_app?log=7c72c51d-b7f5-467a-ae68-3fd87d196041

Flight Card 2

Modes Tested
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

Procedure

Armed form QGC.
Took-off on mission plan mode
. Note that commands were sent form QGC (Armed and takeoff)
Once all waypoint completed vehicle switched to RTL and landed as expected.
Good flight in general.
Note:
No issues were noted, good flight in general.

Logs:

https://review.px4.io/plot_app?log=55a98029-1cc1-4662-a539-7cea2a44b211

Flight Card 3
Modes Tested
Position Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

Procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC.
Good flight in general.

Note:
No issues were noted, good flight in general.

Logs:

https://review.px4.io/plot_app?log=4ae09aca-955a-4418-b44f-2c45bef5098f

Flight Card 4
Modes Tested
Fail safe:The radio control turned off and the vehicle returned and landed correctly.
Tested good.

Logs:
https://review.px4.io/plot_app?log=d0cd4486-1c28-4a22-ba34-7ed21b243db3

**Comment by dagar** [comment]
Thanks @dannyfpv. Sorry I should have specified, but this needs to be tested on fmu-v4 (pixracer) or fmu-v4pro (pixhawk 3 pro). A quick outdoor flight with a pixracer and a side-by-side comparison of the same vehicle with current master would be very helpful.

**Comment by Junkim3DR** [comment]
### Testes on Pixhawk 3 v4Pro

**Note**
Vehicle did not connect to RC and made beeping sounds constantly.

**Log**
https://review.px4.io/plot_app?log=c06d7c56-b518-4769-8af4-2b556a9b200a

**Comment by dagar** [comment]
> ### Testes on Pixhawk 3 v4Pro
> **Note**
> Vehicle did not connect to RC and made beeping sounds constantly.
> 
> **Log**
> https://review.px4.io/plot_app?log=c06d7c56-b518-4769-8af4-2b556a9b200a

Same issue as https://github.com/PX4/Firmware/issues/13892 presumably? 

Can you try a pixracer?

**Comment by jorge789** [comment]
### Tested on PixRacer V4 
Indoor test flightModes: Stabalize
**Notes:**
Calibrations were performed and the flight was continued without GPS inside the cage in stabilized mode and everything worked properly.

**Log:**  https://review.px4.io/plot_app?log=3ba5802b-9082-4fcd-ac08-7ed04273013f

**Comment by Tony3dr** [comment]
> > ### Testes on Pixhawk 3 v4Pro
> > **Note**
> > Vehicle did not connect to RC and made beeping sounds constantly.
> > **Log**
> > https://review.px4.io/plot_app?log=c06d7c56-b518-4769-8af4-2b556a9b200a
> 
> Same issue as #13892 presumably?
@dagar, yes same issue

**Comment by dagar** [comment]
> https://review.px4.io/plot_app?log=3ba5802b-9082-4fcd-ac08-7ed04273013f

Thanks @jorge789. Will you be able to fly this one outdoors in a range of modes (stabilized, altitude, position, mission)?

**Comment by Tony3dr** [comment]
> > https://review.px4.io/plot_app?log=3ba5802b-9082-4fcd-ac08-7ed04273013f
> 
> Thanks @jorge789. Will you be able to fly this one outdoors in a range of modes (stabilized, altitude, position, mission)?

@dagar we will get some test done tomorrow, we had rain today.

**Comment by jorge789** [comment]
### Tested on PixRacer V4 

ONLY IN ALTITUDE MODE, vehicle started to increase throttle drastically. This happened right after switching from position to altitude.

**Log:**  https://review.px4.io/plot_app?log=6018b096-e1e0-4a70-a7b8-f596cc5fd5ee

**Comment by dagar** [comment]
@RomanBapst good logs for looking at clipping and the impact on the estimator.

Screenshot from 2020-01-22 18-26-53

Screenshot from 2020-01-22 18-30-04

**Pull request closed without merging**
