### PR TITLE
move geo and geo_lookup to PX4/ecl

### PR DESCRIPTION
**Pull request by dagar**
These are both dependencies of the ECL.

ECL side - https://github.com/PX4/ecl/pull/410

### CODE REVIEW

**Comment by dagar** [comment]
Waiting on https://github.com/PX4/Matrix/pull/61

**Comment by dagar** [comment]
Declination test failure.
image

**Comment by dagar** [comment]
@priseborough could you take a quick pass to give the test some meaningful values?

https://github.com/PX4/Firmware/blob/master/src/systemcmds/tests/test_autodeclination.cpp#L26-L31

**Comment by dagar** [comment]
Declination test updated.

**Comment by priseborough** [comment]
OK, will do so today

**Comment by dagar** [comment]
Updating clang-tidy in tests only to allow the huge function.

**Comment by dagar** [comment]
ECL side merged and submodule updated. Merge as soon as Firmware CI checks out.

**Comment by dagar** [comment]
The ECL update also brings in "EKF: Reduce effect of GPS noise when using other aiding sources" (https://github.com/PX4/ecl/pull/403).

**Pull request merged**
