### PR TITLE
[WIP] fix aero_upload

### PR DESCRIPTION
**Pull request by dagar**
- fixes https://github.com/PX4/Firmware/issues/11074

### CODE REVIEW

**Comment by dagar** [comment]
@xrb936 could you give this a try?

**Comment by xrb936** [comment]
@dagar Still the same error...

**Comment by dagar** [comment]
Can you post the full output? It should be a slightly different error. I'm away from home and unable to test this directly right now. The plan is to have an intel aero on a hardware test rack in the near future.

**Comment by xrb936** [comment]
I copied the py file to the scripts folder, now it can upload to drone successfully. However I have a new error now:

$ make intel_aerofc-v1_default upload
ninja: Entering directory `/cygdrive/c/PX4/home/Firmware/build/intel_aerofc-v1_default'
[3/4] uploading px4
Copying files to Aero board (root@10.88.193.202)...
root@10.88.193.202's password:
intel_aerofc-v1_default.elf                                                           100%   13MB  17.4MB/s   00:00
px_uploader.py                                                                        100%   36KB   2.9MB/s   00:00
root@10.88.193.202's password:
Linux MECLab-AERO 4.4.76-aero-1.2 #1 SMP PREEMPT Thu Dec 21 09:55:38 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


BIOS_VERSION = Aero-01.00.16
OS_VERSION = Ubuntu 16.04.5 LTS"
AIRMAP_VERSION = unknown
FPGA_VERSION = 0xc2
AeroFC firmware version = 1.6.5


/dev/ttyS1:
Updating firmware on AeroFC
Traceback (most recent call last):
  File "/root/px_uploader.py", line 880, in <module>
    main()
  File "/root/px_uploader.py", line 736, in main
    fw = firmware(args.firmware)
  File "/root/px_uploader.py", line 122, in __init__
    self.desc = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
Firmware updated
Restarting router
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Finished.

**Comment by dagar** [comment]
Oh it looks like the wrong file. It should be the .px4 file, not the .elf.

**Comment by xrb936** [comment]
@dagar Thanks. So how can I get the px4 file? I have one in the folder but it is only 800KB.

**Comment by hamishwillee** [comment]
@julianoes FYI only, Intel are no longer supporting aero. We put a note to this effect in master.

**Pull request closed without merging**
