### PR TITLE
LPE Variance Dependent Publication

### LINKED ISSUE #4909: LPE GPS timeout
I had a test flight today with px4 stable branch + LPE estimator.
Several times there were a strange issues when copter in POSCTL mode becomes drift very fast.
I've inspect a logs and found following messages:
```
2016_06_25_10_13_10: [lpe] gps init lat  55.23 lon  37.74 alt 186.3 m
2016_06_25_10_13_10: [lpe] xy resume 
2016_06_25_10_13_10: [lpe] home lat  55.23 lon  37.74 alt 119.2 m
2016_06_25_10_13_11: [blackbox] /fs/microsd/log/2016-06-25
2016_06_25_10_13_11: [blackbox] recording: 13_13_10.px4log
2016_06_25_10_13_12: [lpe] home lat  55.23 lon  37.74 alt 119.2 m
2016_06_25_10_13_14: LANDING DETECTED
2016_06_25_10_13_26: TAKEOFF DETECTED
2016_06_25_10_13_26: [lpe] home lat  55.23 lon  37.74 alt 119.2 m
2016_06_25_10_13_28: LANDING DETECTED
2016_06_25_10_13_28: TAKEOFF DETECTED
2016_06_25_10_13_29: [lpe] home lat  55.23 lon  37.74 alt 119.2 m
2016_06_25_10_13_41: [lpe] GPS timeout 
2016_06_25_10_13_41: [lpe] xy timeout 
2016_06_25_10_13_48: REJECT AUTO RTL
2016_06_25_10_13_54: [lpe] gps init lat  55.23 lon  37.74 alt 195.6 m
2016_06_25_10_13_54: [lpe] xy resume 
2016_06_25_10_15_00: LOW BATTERY, RETURN TO LAND ADVISED
2016_06_25_10_15_03: LANDING DETECTED
2016_06_25_10_15_03: DISARMED by RC
2016_06_25_10_15_04: [blackbox] stopped (3611 drops)
2016_06_25_10_15_06: [lpe] GPS timeout 
2016_06_25_10_15_06: [lpe] xy timeout 
2016_06_25_10_15_38: ARMED by RC
2016_06_25_10_15_39: [blackbox] /fs/microsd/log/2016-06-25
2016_06_25_10_15_39: [blackbox] recording: 13_15_38.px4log
2016_06_25_10_15_41: DISARMED by RC
2016_06_25_10_15_42: [blackbox] stopped (180 drops)
2016_06_25_10_15_45: ARMED by RC
2016_06_25_10_15_46: [blackbox] /fs/microsd/log/2016-06-25
2016_06_25_10_15_46: [blackbox] recording: 13_15_45.px4log
2016_06_25_10_15_52: DISARMED by RC
2016_06_25_10_15_54: [blackbox] stopped (0 drops)
``` 

http://logs.uaventure.com/view/RZYxAMx9kWHBMCVkTc3kB9

After switching estimator to *inav*  gps timeout issue disappears and there were no any drifts.

### PR DESCRIPTION
**Pull request by jgoppert**
LPE was relying on timeout (of last measurement with good stats) to govern when it should publish its estimates of position. However, this didn't work well for temporary errors in sensor stats that are resolved. For instance, #4909.

To handle this. I am making the timeouts be the time since a last valid measurement (not necessarily with good stats, such as EPH). However, the publication is now dependent on the estimator estimate of the state precision using the variance. This I hope will resolve #4909 but I still have to test it.

### CODE REVIEW

**Comment by jgoppert** [comment]
Here is a plot of the related standard deviations that I"m using to determine if data is valid:

image

**Comment by LorenzMeier** [comment]
This! This should fix the last open issue we found with our test flights here.

**Comment by LorenzMeier** [comment]
@jgoppert Any chance of getting a test flight in today? We will be out flying tomorrow. @tumbili FYI

**Comment by LorenzMeier** [comment]
@jgoppert Have you considered adding another hysteresis at 2x the threshold? I think we need that in addition. Once you're in the air you really want to continue GPS control even if the accuracy is bad.

That's how INAV is doing it and what works really reliably in practice. Not using a hysteresis is just really asking for fly-aways.

**Comment by LorenzMeier** [comment]
Note that the hysteresis cannot be replaced with the variance based approach, because the concept behind the hysteresis is to accept a higher noise ratio once airborne, while this PR only handles transients.

The estimator as it stands here would give up position control entirely even if it had reasonably useful GPS measurements.

**Comment by jgoppert** [comment]
Have done a lot of test flights of this, working on tuning process noise. Here is the result from the iris:

**Comment by jgoppert** [comment]
qav-r (baro only): http://logs.uaventure.com/view/RT5WXHEKKaeDWSPddsifLZ
iris: http://logs.uaventure.com/view/xzxfKgZj7Eh3BNScHaCzum

I had to reduce the z axis process noise so that the baro only flight was smooth enough. I also had to increase the xy axis process noise so that the estimate didn't diverge, but it is working for both vehicles now.

**Comment by jgoppert** [comment]
Here are some more flight test results that I just received, note here that the bias estimation blows up, need to investigate further:

F330 LPE:
http://logs.uaventure.com/view/Lb2EyY2yyZNZQxgYb5nkVU

F330 INAV:
http://logs.uaventure.com/view/pWcMPLtZB5v7JPjZKCEHmR

image

**Comment by jgoppert** [comment]
Here is a plot of the bias estimation with a 3dr iris with the same exact firmware, I have no idea how they could be so different @LorenzMeier any ideas?

image

**Comment by jgoppert** [comment]
@LorenzMeier  Added 4th order integration scheme and also lowpass filter on estimator outputs, default cut frequency is 10 hz. Here is a flight log with my iris.

http://logs.uaventure.com/view/ik78ZNXubcwjywHNenkwqQ

**Comment by jgoppert** [comment]
More plots:

image

image

**Comment by jgoppert** [comment]
Here is a plot of the filtering at 10 Hz, it gets even smoother at 5 Hz, but some degraded performance with high speed spinning, bias drifts off.

10 Hz (only cuts out very rapid changes, but little phase lag)

image

5 Hz (too much phase lag, but very smooth)

image

**Comment by LorenzMeier** [comment]
What I dislike about this strategy is that you're now low passing the accel predictions as well, which makes us loose phase margin. Just distributing position updates would delay the corrections, but not the overall estimate and prediction.

So it doesn't sound like this is a good choice on the conceptional level - is there a particular reason you went into this direction rather than smoothing the update step?

**Comment by jgoppert** [comment]
I think you are talking about the velocity publication to attitude_estimator_q, correct? With the low pass cut frequency at 10 hz, I would argue that it is likely more accurate to have the low pass filter on, if you look at what attitude_estimator_q is doing and the plot above:

```c++
_pos_acc = _q.conjugate_inversed((vel - _vel_prev) / vel_dt);
```

For the sudden jumps due to the correction, without a low pass filter, this would cause large acceleration spikes to go to attitude_estimator_q. This really should have a low pass filter on it anyways. When I tested bias wind up by flying full yaw and full forward stick for 10 seconds, it doesn't cause an issue at 10 Hz.
 
Also, when I started to implement the distribution of correction term, I didn't see how it was significantly different from using a low pass filter. If you calculate at t=0 that gps wants to correct 1 m north, then if you distribute that over the next 10 steps (assuming that we are running at 100 hz, that would mean you would get a 10 cm step at each update (but every step that you don't apply the full correction you are introducing lag), that would also influence the velocity through the correction and also through gps velocity update distribution if you went that route. The low pass filter, on the other hand, would approach the 1m correction as an exponential as you see in the plots, but the behavior is still similar to the distributed correction.

Also, this distributed correction approach seemed like a nightmare to implement since I have 4 different position estimate sources and I would have to do this for everything to be consistent.  Implementing the low pass filter was much cleaner and if you look internally the low pass filter doesn't modify the internal estimator states at all, it is just on the output to the rest of the system. Also for each publication I have the option of publishing the raw state or the low pass state, which might be helpful. The raw state and low pass state are both being logged as well since the raw state is sent to the estimator status message.

**Comment by jgoppert** [comment]
@tumbili  @LorenzMeier ekf2 is also low pass filtering if I'm understanding the code correctly: https://github.com/PX4/ecl/blob/master/EKF/ekf.cpp#L780

The gains here are just the low pass filtering constant. It is not applying the full correction, but a correction proportional to the magnitude of the error, so it is a low pass filter unless I'm missing something.

**Comment by jgoppert** [comment]
Within attitude_estimator_q I disabled the gyro bias estimation during high speed turns, this works very well. Here is a video of me trying to wind up the gyro bias, and you can see the position is rock solid after I release the stick.

video:
https://www.youtube.com/watch?v=4HA6X7V2gXs

log:
http://logs.uaventure.com/view/vJhZtKxeQNERoTyKbgZHsX

**Comment by jgoppert** [comment]
From the log you can see that the smoothing is working very well at 5 Hz and that the lag relative to the velocity dynamics is negligible:

image

**Comment by jgoppert** [comment]
Going to fly on qav-r so I get the full range of vehicle natural frequencies and make sure it works.

**Comment by jgoppert** [comment]
QAV-R flies great. @LorenzMeier I can confirm the baro is messed up on v4 boards on master. It worked fine on v2 boards if that helps. I just set baro noise to 300 m and it actually worked with just GPS.

QAV-R position hold without baro:
http://logs.uaventure.com/view/aALFJDMw6r6dEivXc488YQ

Video:
https://www.youtube.com/watch?v=DgPkecUOjFI

image

image

**Comment by kd0aij** [comment]
What does the baro signal look like on fmu-v2? Significantly lower noise?

**Comment by jgoppert** [comment]
@kd0aij 

Iris (v2):
{'SENS_BaroAlt_dt': 0.094999825024302181,
 'SENS_BaroAlt_mean': 131.10308694879203,
 'SENS_BaroAlt_noise_power': 0.14919326482628734,
 'SENS_BaroAlt_stddev': 1.2531792815762062,
 'SENS_BaroAlt_variance': 1.5704583117718562}

image


qavr (v4):

{'SENS_BaroAlt_dt': 0.071060881566904627,
 'SENS_BaroAlt_mean': 179.98287606413857,
 'SENS_BaroAlt_noise_power': 0.10695588502978866,
 'SENS_BaroAlt_stddev': 1.2268375142913472,
 'SENS_BaroAlt_variance': 1.5051302864725717}

image

**Comment by kd0aij** [comment]
@jgoppert So there's actually less noise with pixracer...
I guess my Skype messages got lost, but I've independently verified that turning off acceleration compensation (the way Bill P. does in Matrixpilot; and imitated by Cleanflight) eliminates the errors due to flying coordinated turns. I completely disabled acceleration compensation for my test to show that GPS should also not be necessary.

**Comment by jgoppert** [comment]
The pixracer has more baro noise, but the baro is messed up on master, so not sure what we can tell from that.

If you are suggesting we don't need GPS for alt, that is true. This PR includes a fix for attitude_estimator_q that stops estimating gyro bias during fast turns, this solves a lot of issues with high performance flight.

**Comment by jgoppert** [comment]
@LorenzMeier @tumbili  are we ready to merge this? I'm happy with it.

**Comment by kd0aij** [comment]
I meant that the GPS-based acceleration compensation in attitude_estimator_q is not necessary.
And didn't you show less baro noise power for v4 than v2 in your comment above?

**Comment by jgoppert** [comment]
@kd0aij Ah, ok. That is good to know. It would be interesting to see if the gyro bias fix help you as well.

I kept repasting the analysis, I tried to find a section of stable hover for both, but currently the qavr(with pixracer) has twice the noise as the iris (with pixhawk)

**Comment by LorenzMeier** [comment]
Baro works fine on master for EKF2. Could you be a bit more specific what part of it is messed up? Variance? Update Rate?

**Comment by jgoppert** [comment]
Do you see the 8m spike in the plot above?

**Comment by jgoppert** [comment]
Could have been a bit due to mounting, had foam over baro port bUT not sure it was in place, can try again later.

**Comment by jgoppert** [comment]
Also variance is larger.

**Comment by kd0aij** [comment]
@jgoppert I was just looking at the noise stats; but spikes would be expected if you didn't have a light shield over the baro. I don't remember clearly, but I thought we demonstrated reduced noise compared to v2 after we moved the baro over to the FRAM SPI bus. OTOH, the ALTCTL surges I was seeing during initial testing could have been due to large noise spikes, but I don't recall finding anything wrong with the baro data from those runs.

**Comment by jgoppert** [comment]
I had electrical tape wrapped it around it before and removed it when messing with gps so that might be it.

**Comment by jgoppert** [comment]
Added subscription throttling on all topics, and really saved a lot of cpu. It took me awhile to track that down, but it flies well, going to try to get some flight videos and logs tomorrow.

Here are some flight log comparisons. The main difference in the missions is that I set the max takeoff altitude to 3 for LPE at the end, forgout about that. Hopefully will get some better comparisons tomorrow.

image

Still the logging is dropping out at times, I would like to resolve that.

image

image

image

image

**Comment by LorenzMeier** [comment]
Comparison is awesome already. Looks like we should put in some decent flight testing now.

**Comment by jgoppert** [comment]
@LorenzMeier I think we should go ahead and merge this, so people can test it on master, what do you think?

**Pull request merged**
