### PR TITLE
Fix bug with imu rotation for tyhpoon in sitl gazebo.

### PR DESCRIPTION
**Pull request by jgoppert**

### CODE REVIEW

**Comment by kd0aij** [comment]
how does this affect "imu rotation"?

**Comment by jgoppert** [comment]
@kd0aij The sitl_gazebo mavlink plugin was using the model link as the reference frame, but there was a sub-link for the imu that was rotated 180 degrees. In the submodule, you can see the fix. There is just a minor switch to logging with the new logger on the px4 side which I used to debug it with the new ground truth logging.

https://github.com/PX4/sitl_gazebo/commit/3a4c503728c0f28cc54f69e41b5e3ba25c4b4648

**Comment by kd0aij** [comment]
Thanks, and sorry for being half blind...

**Comment by jgoppert** [comment]
@kd0aij np, yeah hard to see the submodule changes, like how you can expand them in the diff now

**Comment by julianoes** [comment]
@jgoppert awesome, thank you!

**Pull request merged**
