### PR TITLE
mc pos control:

### PR DESCRIPTION
**Pull request by tumbili**
-when switching into vel control mode (xy) choose vel sp such that attitude
setpoint is continuous

### CODE REVIEW

**Comment by tumbili** [comment]
Needs outdoor testing. It should fix the twitching observed when switching into position control.

**Comment by ecmnet** [comment]
Just made a short flight indoors. Worked for me perfectly.

**Comment by tumbili** [comment]
@ecmnet Thanks for testing! Do you feel the difference to before?

**Comment by ecmnet** [comment]
Perhaps you remember that I've had the 'jump' issue when switching to altHold. That's fixed for sure. I didn't look very much at the point where I switched to posHold.

**Comment by tumbili** [comment]
@ecmnet Yes, the jump issue should be fixed for sure. But also this should improve the transition from manual into position control. To test it best you should transition when the quad has a considerable attitude offset from its neutral pose. The attitude  setpoint should now be continuous over the transition.

**Comment by ecmnet** [comment]
I just switched to jgoppert's LPE implementation struggling with it a bit.As soon as I get reasonable results with it, I will keep an eye on this.

**Comment by ecmnet** [comment]
@tumbili Cool. I fixed now my posHold setup. Switching to posHold seems to be very smooth now, not bouncing back, when manually control position.

**Comment by LorenzMeier** [comment]
@AndreasAntener Could you lend a hand with outdoor testing with this? Should also be highly relevant for all the use cases you care about.

**Comment by LorenzMeier** [comment]
I reviewed the changes and they look good and complete.

**Comment by tumbili** [comment]
I'll fix some spelling mistakes and add another comment to make things a bit clearer.

**Comment by LorenzMeier** [comment]
@tumbili Could you do that now so we can wrap this up?

**Comment by tumbili** [comment]
@LorenzMeier Done!

**Comment by LorenzMeier** [comment]
@AndreasAntener Good to test.

**Comment by AndreasAntener** [comment]
Here you go: http://logs.uaventure.com/view/kh5TX2YVcgdrJLbjtWVzNg

It did nice transitions between altitude <> position control, but from manual to posctl the attitude jumps to neutral instantly.

**Comment by tumbili** [comment]
@AndreasAntener Thanks for testing! Yes, I can see in the log that it doesn't do it right yet. I'll track down what it is.

**Comment by tumbili** [comment]
@AndreasAntener Ok, I could finally reproduce in in SITL. The problem only occurs if you have gone into altitude control mode before.

**Comment by tumbili** [comment]
@AndreasAntener This should be fixed now!

**Comment by LorenzMeier** [comment]
@AndreasAntener Could you cross test this again? It would be great to have this in and fixed.

**Comment by LorenzMeier** [comment]
@AndreasAntener Could you test this one this week?

**Comment by AndreasAntener** [comment]
@LorenzMeier tomorrow should work

**Comment by AndreasAntener** [comment]
Transition manual > pos and alt > pos are really smooth now.
http://logs.uaventure.com/view/FiGDKeiZ9zwERumRDRQbVJ

**Comment by tumbili** [comment]
@AndreasAntener Is there something left todo or is this good to go?

**Comment by AndreasAntener** [comment]
You tell me ;) I haven't looked closely what this change affects otherwise. We changed something with this reset logic for VTOL missions I believe. Offboard I don't see affected by it.

**Comment by tumbili** [comment]
@AndreasAntener I was more referring to some undesired behaviour. It should be ok for missions, the reset logic is the same as before. I'll do a final SITL test.

**Comment by ecmnet** [comment]
@tumbili I don't know whether it fits here. But being in posHold and correcting pos with RC is very snappy (current master with your mc_pos_control_main.cpp). If RC is out of a certain deadband, the vehicle jumps to quite a big roll/pitch angle.

**Comment by tumbili** [comment]
@ecmnet You can reduce the horizontal acceleration of the system using this parameter "MPC_ACC_HOR_MAX".

**Comment by ecmnet** [comment]
@tumbili Were the default values changed? I haven't had that issue with former implementations.

**Comment by tumbili** [comment]
@ecmnet Yes, the gains were recently changed, see this https://github.com/PX4/Firmware/commit/7adaccfe671857b7671b401acb220ca2b97d0813

**Comment by ecmnet** [comment]
@tumbili That's it. Thank you.

**Comment by tumbili** [comment]
@LorenzMeier @AndreasAntener Giving this now a final go in mission mode outdoors and then it can go in.

**Comment by tumbili** [comment]
Merged!

**Pull request merged**
