### PR TITLE
EKF2 output predictor update

### PR DESCRIPTION
**Pull request by priseborough**
Required to use https://github.com/PX4/ecl/pull/148

### CODE REVIEW

**Comment by dagar** [comment]
Ignore the semaphoreci check. It's been disabled.

**Comment by priseborough** [comment]
This now references ecl master.

**Comment by priseborough** [comment]
rebased

**Comment by priseborough** [comment]
rebased

**Comment by priseborough** [comment]
@julianoes I can't work out why travis won't run this

**Comment by julianoes** [comment]
I rebased it again, now I expect it to be able to get the DriverFramework commit that it was "unable to fetch".

**Comment by priseborough** [comment]
What else do i need to do to get this in?

**Comment by LorenzMeier** [comment]
Nothing required else, thanks!

**Pull request merged**
