### PR TITLE
Re-enable autostart

### PR DESCRIPTION
**Pull request by jgoppert**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@AndreasAntener We have CMake now mostly under control and Mac OS SITL is almost there. Do you feel like looking into what it would take to fix ROS / Jenkins?

**Comment by LorenzMeier** [comment]
@vooon @devbharat  interested in looking into fixing the multiplatform targets?

@devbharat Since Mac OS SITL is now almost ready I'm naturally interested to look again into the Protobuf interface for Gazebo.

**Comment by LorenzMeier** [comment]
@thomasgubler Same question for you 8)

**Comment by devbharat** [comment]
Certainly. I see the protobuf addition happening in two steps, getting the rotor_simulator models out of the ros build system into a gazebo naively built model, and then adding the protobuf msg interface between the model and px4. 

Another week block course left, then I could give it some dedicated attention. As a side note, gazebo vtol model has improved quite some recently, hands free hover, climb, decent, transitions and cruise. We can probably discuss about releasing it with @boosfelm

**Pull request merged**
