### PR TITLE
ekf2 handle accelerometer clipping

### PR DESCRIPTION
**Pull request by dagar**
- pass accel clip counts through sensors hub to `sensor_combined`
 - copy accel clip count (and total samples) into ecl/EKF IMU buffer
 - ecl/EKF increase delta velocity variance while IMU sample contains any clipping (https://github.com/PX4/ecl/pull/663)
 - tunable via new parameter `EKF2_ACC_CLPFACT`

Requires https://github.com/PX4/ecl/pull/663

Example flight log with clipping. https://github.com/PX4/Firmware/pull/14294#issuecomment-594918621

clipping

TODO:
 - [ ] get representative logs with clipping (test team pixracer and/or pixhawk 3 pro vehicles)
 - [ ] review and tune via ekf2 replay

The goal is make these brief periods of accel clipping survivable, including alerting the operator if necessary rather than getting caught in the death spiral of clipping -> vz jumps -> more throttle -> more clipping, etc.

### CODE REVIEW

**Comment by dagar** [comment]
@PX4/testflights could you please try this pull request on the same pixracer vehicle you tested in https://github.com/PX4/Firmware/pull/14294#issuecomment-594828748? The vehicle where you reported "in altitude mode, the vehicle did not respect the height that continued to increase in pitch forward".

Try to replicate that flight (https://review.px4.io/plot_app?log=6638bb68-ad37-439b-9c96-c350929a3d28) with this PR. Make sure you reset `SDLOG_PROFILE` to default.

**Comment by dagar** [comment]
Rebased on master. We need to get a good log (ekf2 replayable) from fmu-v4 or fmu-v4pro with accel clipping. We could also expand that to include most other boards with https://github.com/PX4/Firmware/pull/14356.

**Comment by dagar** [comment]
For testing on px4_fmu-v5, px4_fmu-v5x, or modalai_fc-v1 I've added a commit (https://github.com/PX4/Firmware/pull/14304/commits/4e25438d3731d845e8cd94b04dc8d0c78d8e7a5a) that enables the new icm20602, icm20689, and SPI DMA.

**Comment by dagar** [comment]
Here's a good test log. https://logs.px4.io/plot_app?log=c795c4d4-c17c-403a-9bb4-0098d14375c9

Screenshot from 2020-03-19 21-33-47

**Comment by dagar** [comment]
Replayed logs.

Original https://logs.px4.io/plot_app?log=c795c4d4-c17c-403a-9bb4-0098d14375c9
clip_0

EKF2_ACC_CLPFACT 5
clip_1_5

EKF2_ACC_CLPFACT 10
clip_1_10

ECL modified to trigger "bad vertical accel" logic during any clipping
clip_1_bad_vert_accel

**Comment by jorge789** [comment]
### Tested on PixRacer V4:
**Modes Tested**
Position Mode: Good.
Altitude Mode: 
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint then swith RTL.

**Notes:**
**Be sure to reset SDLOG_PROFILE to their default values.** 
**In altitude mode, the vehicle did not respect the height that continued to increase in pitch forward**

**Log:** https://review.px4.io/plot_app?log=26cbd971-6214-4dc2-bbf0-fb07f50c06da

**Modes Tested**
Altitude Mode:
**- Procedure**
Arm and Take off in altitude mode, after flying for approximately one minute, switched to RTL..
**- Notes**
**In altitude mode, the vehicle did not respect the height that continued to increase in pitch forward**

**Log:** https://review.px4.io/plot_app?log=7c1f0f91-7a73-4b43-a4a5-eb070c68310c

**Comment by jorge789** [comment]
### Tested on PixRacer V4

**- Modes Tested**
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.
**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint then swith RTL..
**- Notes
In Position and altitude mode, the vehicle did not respect the height that continued to increase in pitch forward**

**Log:**
https://review.px4.io/plot_app?log=93d9a409-cf0d-4f8f-afae-6a2e229639ff

https://review.px4.io/plot_app?log=c5b378f6-a080-4477-b59e-0f9c95d31c9b

**Comment by dagar** [comment]
Thanks @jorge789. It looks like you grabbed the build right before I pushed a bug fix (to get all axis clip counts to the estimator). Could you try this again with the current build (same vehicle) when you get a chance?

The test can be as long or short as you like, just do whatever you can to try and get to that "vehicle did not respect the height" behaviour. The overall goal is to eliminate or minimize that.

**Comment by mrpollo** [comment]
@Tony3dr Can you please fly this PR again with the changes from @dagar ?

**Comment by jorge789** [comment]
### Tested on PixRacer  V4

**- Modes Tested**
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.
**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC,  once completed all waypoint then swith RTL..
**- Notes**
There were no altitude problems

**Log** https://review.px4.io/plot_app?log=d4987f81-c76f-4278-af21-a944824b7c96

**Comment by dagar** [comment]
Thanks @jorge789!

Like the previous flights from that vehicle there's plenty of accelerometer clipping.
Screenshot from 2020-04-06 15-11-27

Unfortunately that log has too many dropouts to replay and compare without the change, but from previous tests of that same vehicle with similar levels of clipping we can see the difference.


For example in https://review.px4.io/plot_app?log=c5b378f6-a080-4477-b59e-0f9c95d31c9b (same vehicle about a week ago without the ecl clipping change). We can see the estimator velocity test ratio (estimator_status.vel_test_ratio) during periods of clipping.

Screenshot from 2020-04-06 15-41-05

Then in today's log https://review.px4.io/plot_app?log=d4987f81-c76f-4278-af21-a944824b7c96 for comparison where the clipping might be even worse.

Screenshot from 2020-04-06 15-41-49

**Comment by dagar** [comment]
https://github.com/PX4/ecl/pull/663 has merged, updating this branch with latest ecl.

**Pull request merged**
