### PR TITLE
rename platforms/ -> os/ (PX4 layers discussion)

### PR DESCRIPTION
**Pull request by dagar**
As part of an ongoing effort to structure this project in well defined layers I'd like to consider renaming the top level `platforms` directory. This came up during the dev call yesterday to remove potential confusion with src/platforms and better establish what these layers are, or at least should be.

Next I'd like to establish `src/platforms` (renamed -> src/platform) as the "PX4 platform" layer.

Highlevel PX4 layers

 - **PX4 Modules** (src/modules)
   - uORB pub/sub and parameters
   - controllers, estimators, state machines, mavlink, etc
 - **PX4 Drivers** (src/drivers)
   - modules that access hardware
   - sensors, outputs, etc
   - platform agnostic drivers
 - **PX4 Libraries** (src/lib)
   - used by modules and drivers
   - have access to uORB, parameters, etc
   - non-px4 libraries also exist that aren't allowed to use anything in the px4 platform (px4_add_library vs add_library)
 - **PX4 platform layer** (src/platform)
   - uORB, parameters, hrt, work queue, task creation, px4 logging
   - defines everything in the PX4 platform layer, and implements all generic code. Depends on a significant amount of OS specific code (does it make sense for that to live under the top level os/)?
 - **PX4 OS support layer** (os/)
   - nuttx, posix (probably linux separately), qurt
   - contains non-px4 drivers
   - should **not** use anything in the PX4 platform layer (parameters, logging, hrt, etc).

The original intention was to relayer everything such that the OS specific layer could be cleanly extracted into a separate repository. An alternative would be merging the OS support layer with the platform layer.

Related
 - https://github.com/PX4/Firmware/issues/7318
 - https://github.com/PX4/Firmware/pull/10316

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I think that makes a lot of sense.

**Comment by hamishwillee** [comment]
Sounds good - so boards still live at even higher level? https://github.com/PX4/Firmware/tree/master/boards

Can/should we document the source code organisation under [concepts](https://dev.px4.io/en/concept/)? Perhaps in a topic "PX4 Source Code Organisation"?

Also re-verify https://dev.px4.io/en/concept/architecture.html as there has been a bit of churn since it was done.

**Comment by dagar** [comment]
> Sounds good - so boards still live at even higher level? https://github.com/PX4/Firmware/tree/master/boards

Yes, `boards/` is a place where you can optionally supply a wide range of board specific pieces at any level of the system. Certain types of boards (eg NuttX) have different required pieces that plug in to the OS level.

> Can/should we document the source code organisation under [concepts](https://dev.px4.io/en/concept/)? Perhaps in a topic "PX4 Source Code Organisation"?

Yes, but let's let it settle a bit and do that corresponding with v1.9.0. There's another change coming shortly.

**Comment by dagar** [comment]
Merge after https://github.com/PX4/Firmware/pull/11013

**Comment by dagar** [comment]
I'll pause on this and propose something larger.

Basically I'd like to establish a more explicit OS abstraction layer (OSAL) for PX4 that includes the various pieces like task management, semaphores, build hooks, etc.

Overall we need to figure out how that interface is defined, implemented, and where those OS pieces should live (headers and each OS). Then separately how to define the "PX4 platform" in a way that isn't mixed with the OS pieces (or does it matter).

To be continued...

**Pull request closed without merging**
