### PR TITLE
Land detector robustness

### PR DESCRIPTION
**Pull request by LorenzMeier**
@sjwilks @AndreasAntener This is my next stab at land detection. I've now made it more forgiving the first second after arming, which I hope will allow it to ride through motor spool up.

I've also added the condition that a fixed wing has to be armed to get airborne in the process.

### CODE REVIEW

**Comment by SimonWilks** [comment]
This looks good. I'll give it a test on the TBS tomorrow.

**Comment by SimonWilks** [comment]
Tested on the TBS arming multiple times. No more short motor bursts after arming.

**Comment by LorenzMeier** [comment]
@SimonWilks do you have the log for that? The reason I ask is that I want to make sure it still detects the takeoff 8)

**Comment by SimonWilks** [comment]
It worked nicely. Here is the log with the dramatic smoky ending (unrelated to this PR of course): http://dash.oznet.ch/view/PBQasoaVbizsSho33KEFtV

**Pull request merged**
