### PR TITLE
Master dataman ram

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier 

This PR added the RAM based storage directly in dataman. 

Ram usage is way too high! 

```
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
nsh: mount: mount failed: No such device
nsh: mkfatfs: mkfatfs failed: No such device
ERROR [mtd] MTD not enabled, skipping.
WARN  [param] selected parameter default file /fs/microsd/params
INFO  [dataman] Unkown restart, data manager RAM size is 103090 bytes
WARN  [ms5611] no device on bus 1
ERROR [ms5611] driver start failed
WARN  [hmc5883] no device on bus 2
WARN  [mpu6000] no device on bus 1
ERROR [sensors] no barometer found on /dev/baro0 (2)
WARN  [sensors] FATAL: no accelerometer found: /dev/accel0 (2)
WARN  [sensors] FATAL: no gyro found: /dev/gyro0 (2)
WARN  [sensors] FATAL: no magnetometer found: /dev/mag0 (2)
WARN  [sensors] FATAL: No barometer found: /dev/baro0 (2)
ERROR [sensors] sensor initialization failed
ERROR [sensors] no barometer found on /dev/baro0 (2)
ERROR [sensors] no barometer found on /dev/baro0 (2)
INFO  [init] Multicopter
nsh: mixer: command not found
ERROR [init] Error loading mixer: /etc/mixers/hexa_x.main.mix
WARN  [ekf2] alloc failed
```
Please have a look at dataman.h  
```
/** The maximum number of instances for each item type */
enum {
	DM_KEY_SAFE_POINTS_MAX = 8,
#ifdef __cplusplus
	DM_KEY_FENCE_POINTS_MAX = fence_s::GEOFENCE_MAX_VERTICES,
#else
	DM_KEY_FENCE_POINTS_MAX = GEOFENCE_MAX_VERTICES,
#endif
	DM_KEY_WAYPOINTS_OFFBOARD_0_MAX = NUM_MISSIONS_SUPPORTED,
	DM_KEY_WAYPOINTS_OFFBOARD_1_MAX = NUM_MISSIONS_SUPPORTED,
	DM_KEY_WAYPOINTS_ONBOARD_MAX = NUM_MISSIONS_SUPPORTED,
	DM_KEY_MISSION_STATE_MAX = 1
}
```
and suggest or commit the values that make sense and I can re-test.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Ok, so here for RAM constrained systems:

GEOFENCE_MAX_VERTICES = 10
DM_KEY_WAYPOINTS_OFFBOARD_0_MAX = 50
DM_KEY_WAYPOINTS_OFFBOARD_1_MAX = 50
DM_KEY_WAYPOINTS_ONBOARD_MAX = 5

**Comment by davids5** [comment]
@LorenzMeier 

Please see if this meets your expectations.

```
INFO  [dataman] Unkown restart, data manager RAM size is 16120 bytes
```

**Comment by LorenzMeier** [comment]
I was expecting more like 3K. In that case we might have to slim the waypoint data structure

**Comment by davids5** [comment]
datman use 130 byte blocks with 4 bytes of header  and 126 of user space -(128 total size would help with 512 sector devices)

sizeof(mission_item_s) is 92 bytes (1700 wasted for 50 way points)
sizeof(mission_s) = 24
sizeof(fence_vertex_s) = 16
So there is a lot of waste there

**Comment by davids5** [comment]
@LorenzMeier 

Using the union we have.
'''
INFO  [dataman] Unkown restart, data manager RAM size is 13000 bytes
'''

I revived the test_dataman.c to test on FMUV2 in both file and ram mode - it passes.

Last commit just delists the test_dataman is it was prior.

**Comment by davids5** [comment]
@LorenzMeier 

Another thought sizeof(union) is 100 bytes and sizeof(mission_item_s) is 92. - if we set packing on the structs the union can be packed and we probably pick up another 8 bytes per.

**Comment by LorenzMeier** [comment]
Makes sense.

**Comment by davids5** [comment]
@LorenzMeier 

Packed
```
INFO  [dataman] Unkown restart, data manager RAM size is 12480 bytes
```

I evaluated the mixed storage size option:

image

As expected the net gain is small 1284. But a easy win would be removing DM_KEY_SAFE_POINTS_MAX that is only used in the test command saving 768.

**Pull request merged**
