### PR TITLE
Update submodule ecl to latest Thu Jan 30 00:38:08 UTC 2020

### PR DESCRIPTION
**Pull request by dagar**
- ecl in PX4/Firmware (049799f9951349c6edb764bb9e8d9a4333f02676): https://github.com/PX4/ecl/commit/a3e1eb9d509d55c2c476ec093cf24d84da9798e5
    - ecl current upstream: https://github.com/PX4/ecl/commit/da752c9e304ab0847b43beb61a8b508c3cabc1a9
    - Changes: https://github.com/PX4/ecl/compare/a3e1eb9d509d55c2c476ec093cf24d84da9798e5...da752c9e304ab0847b43beb61a8b508c3cabc1a9

da752c9 2020-01-28 kamilritz - Hot flow fusion fix
ee859e0 2020-01-28 kritz - Robustify timestamp checks (#729)
f20726d 2020-01-23 kamilritz - Expand auto-format coverage and tiny style changes
fbdd75d 2020-01-27 kritz - Update CONTRIBUTING.md
5d38b73 2020-01-24 kamilritz - Update description of Firmware build tests
e3af91c 2020-01-24 bresch - Ekf: use helper functions to centralize the checks of horizontal aiding (gps, flow, ev_pos, ev_vel)

### CODE REVIEW

**Comment by bresch** [comment]
@PX4/testflights Could you fly that please?

**Comment by Junkim3DR** [comment]
### Tested on NXP FMUK66 v3

**Indoor Flight Test**
**Modes Tested**
Stabilized Mode: Good.

**Procedure**
Arm and Take off in stabilized mode.

**Notes**
No issues noted, good flight in general.

**Logs**
- https://review.px4.io/plot_app?log=d6f5bb27-de84-4fda-9197-eb29ce1f9085
- https://review.px4.io/plot_app?log=57d43363-7c1e-4a7a-9783-440f09cac1d9

**Comment by dannyfpv** [comment]
Tested on pixhawk4 v5 f-450
Indoor Flight Test
Modes Tested
Stabilized Mode: Good.

Procedure
Arm and Take off in stabilized mode.

Notes
No issues noted, good flight in general.

Logs
https://review.px4.io/plot_app?log=f6518dec-0ffa-4063-9765-43a81bfd6a22

**Comment by jorge789** [comment]
### Tested on PixRacer V4
**Indoor Flight Test**
**Modes Tested**
Stabilized Mode: Good.

**Procedure**
Arm and Take off in stabilized mode.

**Notes**
No issues noted, good flight in general.

**Logs**  
https://review.px4.io/plot_app?log=e67d49b8-3070-4186-9000-631c2855ba09

https://review.px4.io/plot_app?log=e1ff8fed-9530-4278-9b7e-93d694af2033

### Tested on CUAV nano V5

**Indoor Flight Test**
**Modes Tested**
Stabilized Mode: Good.

**Procedure**
Arm and Take off in stabilized mode.

**Notes**
No issues noted, good flight in general.

**Logs**   https://review.px4.io/plot_app?log=75821ed2-1456-48ff-b09c-4afc42869088

**Pull request merged**
