### PR TITLE
ecl: Fix CPU load increase

### PR DESCRIPTION
**Pull request by bresch**
Summary:
- reduce CPU load: https://github.com/PX4/ecl/pull/767 (fixes https://github.com/PX4/Firmware/issues/14204)
- fix earth rate gyro compensation
- make test with clang
- use switch statements in controlHeightFusion

Diff:
https://github.com/PX4/ecl/compare/3fa5f501ae7edc4a793f0973e156706afcc8b419..230c865fa9c02b07b0371df050b339bc37ce0c29

### CODE REVIEW

**Comment by bresch** [comment]
@PX4/testflights Could you please test this PR on several vehicles, all modes?

**Comment by dannyfpv** [comment]
pixhawk4 v5 f-450
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL 

**Notes:**
No issues noted, good flight in general.

**Log:**
https://review.px4.io/plot_app?log=dc44a9e3-0fe5-4bcb-817c-0da42d7ab7bb

**Comment by jorge789** [comment]
### Tested on PixRacer V4:

**Modes Tested**
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint then swith RTL.

**Notes:**
In altitude mode, the vehicle did not respect the height that continued to increase in pitch forward

**Log:**  https://review.px4.io/plot_app?log=6638bb68-ad37-439b-9c96-c350929a3d28

**Modes Tested**
Altitude Mode:
**- Procedure**
Arm and Take off in altitude mode, after flying for approximately one minute, switched to RTL..
**- Notes**
In altitude mode, the vehicle did not respect the height that continued to increase in pitch forward
### It is only in PixRacer
**Log:**  https://review.px4.io/plot_app?log=6297502c-fdb3-4714-b589-068e87e822ae

### Tested on CUAV nano V5:
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC,  once completed all waypoint then swith RTL.
**Notes:**
No issues noted, good flight in general.

**Log:**  https://review.px4.io/plot_app?log=10399f8c-0382-41f3-9b61-2b35b65bdf95

**Comment by dannyfpv** [comment]
pixhawk4 mini v5 f-500
Modes Tested

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

- Procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL

Notes:
No issues noted, good flight in general.

Log:
https://review.px4.io/plot_app?log=e4445bf8-ddff-4a74-921d-d0aef2a321cd

**Comment by bresch** [comment]
Thanks @dannyfpv and @jorge789 !

@jorge789 Thanks for reporting the "height increase in pitch forward with the Pixracer". This PR doesn't affect specifically the PixRacer, so I think it if due to the fact that the barometer is more exposed compared to other boards; is this problem new? Nevertheless, I'll have a look to be sure that there is no bug involved.

**Comment by Junkim3DR** [comment]
### Tested on Pixhawk 3 v4Pro

- Modes Tested
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

- Procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint then trigger RTL.

- Notes
No issues noted, good flight in general.

**Log**
https://review.px4.io/plot_app?log=17325048-6704-429a-857c-f304c8b79e2d

**Pull request merged**
