### PR TITLE
reset setpoint to current position

### PR DESCRIPTION
**Pull request by ChristophTobler**
avoid abrupt position changes in manual as the estimated delta can be quite big depending on deadreckoning/imu (see https://github.com/PX4/Firmware/issues/8151).

### CODE REVIEW

**Comment by priseborough** [comment]
How has this been tested? Do you have a log?

**Comment by ChristophTobler** [comment]
Tested in SITL, https://logs.px4.io/plot_app?log=239613c1-6057-42a9-922f-2345dbf09cf6

**Comment by priseborough** [comment]
That log doesn't the horizontal reset.

**Comment by ChristophTobler** [comment]
@priseborough That's correct it's just in the vertical direction. But why should it behave differently?

**Comment by priseborough** [comment]
Code that does the horizontal reset was changed. The changes should still work, but that misses the point of reversion testing.

**Comment by siddyyagno3** [comment]
I will make the changes and build the code finally Do a flight test. Will see if the issue is resolved. Thanks for help.

**Comment by ChristophTobler** [comment]
@dagar is travis currently broken? Can we merge PRs with CI failing?

**Comment by TSC21** [comment]
@ChristophTobler couldn't we find a midterm delta defined as a threshold, instead of just reseting to the current position?

**Comment by ChristophTobler** [comment]
I discussed with @Stifael and @MaEtUgR and we came to the conclusion that in manual mode you never want the drone to move unexpectedly. And with a delta you have that. In addition, if you look at  https://github.com/PX4/Firmware/issues/8151 you can see that the delta can be totally random depending on the IMU/deadreckoning.

**Comment by TSC21** [comment]
So you assume that if the system has a position drift, you won't move at all?

**Comment by dagar** [comment]
Yes travis-ci was broken yesterday (the service, not our usage of it). We can ignore it and merge, but I'd like to get to the point these CI integrations can be trusted.

**Comment by ChristophTobler** [comment]
@TSC21 No. If the estimator resets the position (which is a jump), we want the setpoints to be the same and not some delta. Because a delta between position and setpoint means a sudden acceleration of the vehicle at a point where the user doesn't expect it.

**Comment by TSC21** [comment]
Ok makes sense to me.

**Pull request merged**
