### PR TITLE
adding airframe config for s500

### PR DESCRIPTION
**Pull request by barzanisar**
This file is a work in progress and will be edited later after fine tuning the gains.

### CODE REVIEW

**Comment by dagar** [comment]
Could we keep this completely generic?

Something like "Generic 500mm Quadcopter" instead of "S500".

**Comment by dagar** [comment]
Makes sense if there's going to be more specific parameters.

**Comment by barzanisar** [comment]
@LorenzMeier This hasn't been *fine* tuned yet. After solving its "preflight fail: mag inconsistent" check (I faced on the Flyday) I had switched my priority to crazyflie. 

I will tune, rename and commit the final parameters on Monday.

**Comment by dagar** [comment]
This is safe to merge, renaming or additional tuning can continue off of master.

**Pull request merged**
