### PR TITLE
WIP: replace RC driver from FC_addon with PX4 RC driver for SD flight plat…

### PR DESCRIPTION
**Pull request by wangxdflight**
…form

### CODE REVIEW

**Comment by ChristophTobler** [comment]
@wangxdflight Thanks! But if I turn on the Spektrum RC I still get https://github.com/PX4/Firmware/issues/6887. Are you not having this issue?

**Comment by LorenzMeier** [comment]
@wangxdflight @ChristophTobler Where is this standing?

**Comment by ChristophTobler** [comment]
The original RC issue was fixed somewhere else and I never use legacy. @wangxdflight ?

**Comment by wangxdflight** [comment]
I don't think these are related. BTW, I need to do flight test and then
submit the merge request again.

**Comment by wangxdflight** [comment]
Will submit another one.

**Pull request closed without merging**
