### PR TITLE
Data validation: Initial concept of RMS + timeout based data validators ...

### PR DESCRIPTION
**Pull request by LorenzMeier**
...and validation groups of N sensors.

@DrTon Could you have a look? This still needs work, but I wanted to sketch out what I meant so we can start discussing how it should be done. Feel free to modify or completely change it by pushing more commits to the branch!

### CODE REVIEW

**Comment by crashmatt** [comment]
Does this presume that all sensors have equal accuracy and sample rate?

**Comment by DrTon** [comment]
It's hard to analyze the idea because of a lot of mistakes and errors :) Main idea and structure looks a good for me. But I don't like idea with RMS and mean. Imagine that one gyro is dead and sends crazy big values. This line https://github.com/PX4/Firmware/commit/2314a190a1e18df1836d5b2067eeecfbfbf306a1#diff-35c2bcd608b7dfda79053c602b93b975R152 will show veeery good confidence. If it's mistake, then the same will happen if gyro sends 0. Also dividing by mean is not good, mean will be around zero for most sensors :) IMO it's better to keep things as simple as possible to avoid false triggering. E.g.:
- Timeout
- Repeating values on at least one axis or on all axes (it's what I seen in log with failed MPU6000 - large constant values on gyro, real sensors always have noise)

Also would be good to analyze all known sensor fails. Can you provide some logs?

**Comment by crashmatt** [comment]
If a sensor is stuck should it be the responsibility of the driver to indicate that?  Different sensors get stuck in different ways.  Writing code to catch all possibilities for all sensors might be tough.  This does not remove the need to vote out a bad reading.

Thinking of the case of airspeed sensors. Pitot tube sensors are terrible at low speeds. Mass airflow sensors are great at low speed but bad at high speed.  What if you have both?  How do you merge that data?  If each sensor reading came with an estimated error value then whatever merges the data knows how much to trust the reading.  But that is not keeping it simple.

**Comment by LorenzMeier** [comment]
@crashmatt Building a robust system is all about "define failure". I think you and @DrTon still assume that a failed sensor does exhibit specific behaviour ("tells you it stopped working") once it fails, but for most of the failures we've seen that's not the case.

One of the most common cases is a sudden scale change. So its neither stuck at one magic value nor does it stop updating.

**Comment by LorenzMeier** [comment]
@DrTon Yes, we should run this in a test harness against the logs. I will dig them up and post them here.

**Comment by crashmatt** [comment]
@LorenzMeier, I see you point about that.  I am thinking of a different use case and off topic.

**Pull request closed without merging**
