### PR TITLE
Bugfix/time_sync

### PR DESCRIPTION
**Pull request by devbharat**
'offset_ns' can be negative

### CODE REVIEW

**Comment by mhkabir** [comment]
@devbharat Thanks!

**Comment by mhkabir** [comment]
Would you mind going over the mavros side as well, so we can have the full loop verified.

**Comment by devbharat** [comment]
I did. It appears to be correctly handled in the mavros plugin. I tested it in the loop and with these fixes it had sensible values for both timestamp_boot and timestamp_computer. I'd still prefer someone else test it too, as my setup manages two pixhawks on one companion computer and I've had to make other changes for that.

**Comment by LorenzMeier** [comment]
Reviewed and applied to master, thanks!

**Pull request closed without merging**
