### PR TITLE
Quick test of ekf att pos for indoor

### PR DESCRIPTION
**Pull request by jgoppert**
Don't Pull: This branch is a work in progress to evaluate the ekf 22 state att pos filter for indoor use.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Please be aware that the whole data association step is not implemented yet - the filter can do it, but the functions to feed flow data are never called. The missing bits are the equivalents of these:
https://github.com/priseborough/InertialNav/blob/optflow_merge/code/main_closed_loop_float.cpp#L379-L472

The filter is valided with log data.

**Comment by jgoppert** [comment]
This was just a quick hack and I'm probably missing something, but the altitude estimate looks pretty poor compared to using sonar alone in the flow position estimator example app. The position also isn't updating. This could be due to my hack gps is passing the home as a measurement/ or the optical flow measurement is disabled, but I didn't see anything like that immediately.

EKF Attitude Position Estimator

ekf-att-pos
ekf-att-pos-top

Flow Position Estimator

flow-pos-est

flow_pos_est_alt

**Comment by jgoppert** [comment]
@LorenzMeier OK, thanks, I figured as much.

**Comment by jgoppert** [comment]
@LorenzMeier If you want to try to merge in that flow correction I can flight test it tomorrow.

**Comment by LorenzMeier** [comment]
I can give it a try, but no guarantees - will require a bunch of debugging probably. But it would be awesome to get this going.

**Pull request closed without merging**
