### PR TITLE
Airspeed sensor check relaxation

### PR DESCRIPTION
**Pull request by LorenzMeier**
@tubeme @dagar This relaxes the airspeed checks within reasonable bounds. If anything is failing still now there is a real issue with the sensor setup which needs to be fixed in hardware.

Arming should also now possible without much noise on the sensor.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Binary for manual flashing through QGC: [nuttx-px4fmu-v2-default.px4.zip](https://github.com/PX4/Firmware/files/706326/nuttx-px4fmu-v2-default.px4.zip)

**Comment by tubeme** [comment]
Thanks a lot Lorenz! I will try the binary tomorrow in the workshop.

**Comment by tubeme** [comment]
It calibrates the eagle tree sensor without a problem. More tests to come.

**Comment by tubeme** [comment]
Works for the HK sensor as well.

**Pull request merged**
