### PR TITLE
Fixed 9250 mag readouts. From @Inspirati

### PR DESCRIPTION
**Pull request by LorenzMeier**
@Inspirati These are your fixes cleaned up into a single commit and rebased on master. @kd0aij Please test this.

### CODE REVIEW

**Comment by kd0aij** [comment]
Will test this ASAP

**Comment by LorenzMeier** [comment]
Thanks! Looking forward to the flight logs.

**Comment by LorenzMeier** [comment]
Rebased on master to fix travis failure.

**Comment by LorenzMeier** [comment]
@kd0aij Merged to master. Testing would be great.

**Comment by kd0aij** [comment]
Having trouble reflashing the PixRacer: parameters were apparently trashed in FRAM. Using QGC on desktop to select airframe results in a QGC hang after "Apply and restart". Restarting QGC failed to re-establish connection via USB. Tried QGC/Android via WiFi: Airframe still not configured, after selection and "Apply and restart" QGC says the airframe is still not specified.

**Comment by LorenzMeier** [comment]
Julian also had issues, but a very old Pixracer - do you have a boot log?

**Comment by kd0aij** [comment]
I didn't capture the console messages, and it doesn't look like anything useful went to the SD card. I was getting the "Sensors need inspection" message on the console, but that's not useful.

**Comment by kd0aij** [comment]
(Using a different PixRacer)
Bench test of latest master with 3 magnetometers. I'm sure one of them is in the 9250 :)
http://logs.uaventure.com/view/DxiMAoWQhuVzuamSfw4zXo

I only noticed 1 spike in FlightPlot.

**Comment by kd0aij** [comment]
A short flight test in ACRO mode ended safely, but something went very wrong. Was unable to switch to any other mode after taking off, and the copter refused to disarm via RC after landing. The kill switch did not work either. Unfortunately there was no log file from the flight, although I armed/disarmed twice doing preflight checks and there are logs from both of those sessions. The kill switch was also working during preflight.

**Comment by LorenzMeier** [comment]
R7 Pixracer is not supported any more.

Can you cycle through that again in a safe fashion, connect the console and get us the output of "top"? I didn't merge anything that should upset the overall system that much, but re-checking stack would be good.

**Comment by kd0aij** [comment]
I have a patch for R7 :)

**Comment by kd0aij** [comment]
free and top looked good on the bench preflight. I'll see if changing to acro mode triggers a problem

**Pull request closed without merging**
