### PR TITLE
Jenkins HIL python scripts update to python3

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by TSC21** [comment]
Do we have Python 3 by default on the base containers?

**Comment by TSC21** [comment]
@dagar We don't have Python 3 being installed in both *px4-dev-base-bionic* and *px4-dev-nuttx*. So is this supposed to work as is?

**Comment by dagar** [comment]
This is a completely different container that runs the slaves with hardware attached. It's private because it carries a proprietary binary (jlink).

**Comment by TSC21** [comment]
> This is a completely different container that runs the slaves with hardware attached. It's private because it carries a proprietary binary (jlink).

Got it!

**Comment by TSC21** [comment]
@dagar it should be fine with "our" containers though: https://github.com/PX4/Firmware/pull/13497/commits/f4244845d3394bc26e0af3a76d2423552d3ddbeb

**Pull request closed without merging**
