### PR TITLE
[Breaking Change]fmuk66-v3: Only Support Rev BX11

### PR DESCRIPTION
**Pull request by davids5**
I2C bus chaged I2C0 is external, I2C1 internal
     Added BMM150 on I2C1 @ Addr 0x100
     Added BMP280 on I2C1 @ Addr 0x76

   UART0 (/dev/ttyS1) now used at Telem 2

   Chip select added for W25X40CLUXIG Calibration EE prom
     Driver is not added at this time

Add SW PU on LPUART0_RX - done
Set Rotation on BMM150 - done.
BMM150 - now starting
BMP280 - now starting.
RGBLED - added simultaneous support for new rgbled_ncp5623c, old TCA62724FMG and PWM 
Add RTC to NuttX and Start RTC - Done

To Do and Verify:
Add Cal EE prom Driver 
Add Secure element driver.

### CODE REVIEW

**Comment by davids5** [comment]
@igalloway FYI

**Comment by igalloway** [comment]
Initial quick notes: 
- Bootloader programmed fine
- OLD firmware programmed fine. (breathing RGB LED etc)
?> primary console terminal - output is ok, but not taking input (could it be the blocking diode?)

**Comment by davids5** [comment]
> OLD firmware programmed fine. (breathing RGB LED etc)
> primary console terminal - output is ok, but not taking input (could it be the blocking diode?)

It could be. A installed backward - or the input not pulled up in SW.

**Comment by dk7xe** [comment]
@davids5 @igalloway My tests so far (successful is checked)

- [ ] bootloader programmed via Segger tool.
- [ ] branch master_nuttx_7.28+_k66_bx11 flashed via QGC
- [ ] MavLink Telemetry via TELEM1 115k2 Bd
- [ ] MavLink Telemetry via TELEM2 (companion) 115k2 Bd
- [ ] Sensor calibration
- [ ] RC input (FrSky SBUS)
- [ ]

**Comment by igalloway** [comment]
@dk7xe  - RE telemetry
"Telemetry link is very unstable again and not all parameters can be loaded always (via TELEM2 115k2 Bd)."

 - As we discussed you may have a cable problem?

**Comment by dk7xe** [comment]
Iain, Maybe. I have attached a 433MHz telemetry TRX to TELEM1 @57k6 Bd speed.
That worked so far. Will do further tests later today.

**Comment by dk7xe** [comment]
i have updated the previous post according second test today.

**Comment by dk7xe** [comment]
Loaded new FW today.
Bmm150 did not show up nur seems to be HW related. On replacement board everything was ok. Testflight done indoors successfully.

**Comment by davids5** [comment]
@igalloway @dk7xe update to current Nuttx in PX4 master. I also tested the date and time with the RTC and that is all working now.

**Comment by jarivanewijk** [comment]
Here in Eindhoven we have also been busy with testing RevC. Sadly, due to rain we have not been able to do a test flight yet.

I have a few things I'd like to add:

**TELEM1 & TELEM2**
This is more hardware related, and we already discussed this with Iain, but I thought it would be good to share this again with the others.

We found that the bi-directional levelshifter between the MCU and the TELEM1 connector is corrupting the signal. This is already the case at 57k6 baud (but still workable) and becomes worse at higher baudrates. Beyond 230400 baud we were not able to get a stable connection. We tested this both with the Holybro telemetry radios and with FTDI cables. We also checked the signal with an oscilloscope, which showed a highly distorted signal.

Also, TELEM2 does not have a levelshifter (or resistors). This one works great and we were even able to communicate with a 3M baudrate. The oscilloscope showed an ok signal.

We fixed TELEM1 by removing the levelshifter U50 on the board, and adding the 220 ohm resistors instead. This has worked great, also at 3M baudrate. The waveform shows a significant improvement.

**RGB LED**
The RGB LED on the FMU is working again, but it shows some weird behavior. When it's blue, the RGB LED inside the Pixhawk 4 GPS is also blue. However, when the GPS goes green, the FMU goes red. Also, the GPS LED driver seems to crash after a while, it stops emitting light.

**New sensors**
All seem to work on my board. Drivers are working, sensors are giving output.

**NXP Magneto**
I think the magnetometer in the accelero/magneto package is still disabled. BOARD_HAS_NOISY_FXOS8700_MAG is still set inside board_config.h
I'm wondering if we should re-enable it and evaluate again?

**SDHC settings**
The SDHC settings were changed as a temporary fix/workaround for the EMI issues which affected the GPS connection. I think this is still the case. I'm also wondering if we should reset this to the usual settings and evaluate this again? Especially now that the board design has improved significantly from EMI perspective, I think.

**Comment by davids5** [comment]
@jarivanewijk - thank you for the feedback. 

###  Telem1 & 2
What does the signal look like at 115200?
What is the load on the CPU at 3MB?

### RGB LED
Possible a new part was used or the got changed.  I will push code to swap the R & G

### SDHC 
FCC Testing will be effected - only benefit may be card choices -   I will defer to @igalloway . 

### MAG 
The test is simple: Rebuild without the disable and visualis that data on QGC. - I will defer to @igalloway if he wants to pursue this,

**Comment by jarivanewijk** [comment]
@davids5 We didn't try 115200, but we have a few snapshots of the signal at 921600. The probe is connected just after the connector. We had an FTDI cable connected when we took these snapshots. Note that I did also try different baudrates with the telemetry radios, and with each increase in baudrate the connection would become less stable (in QGC for instance). Also, I would lose more and more bytes when I tried to transmit messages from the system console.

This is the signal at TELEM2 at 921600 baud. Note that TELEM2 does not have the levelshifter, nor does it have resistors.


This is the signal at TELEM1 at 921600 baud. This is with the levelshifter still in place.

The signal oscillates heavily and does not go down to ground (in all pictures the oscilloscope was set to an offset of -1V, I think). We did also check at 57600 baud (no pictures though), and we also saw that the signal does not go down to ground. Some oscillations were already visible at 57600.

This is also TELEM1 at 921600, but now the levelshifter has been removed and 220 ohm resistors have been installed. The oscillations are gone, and the signal goes down to ground again. We are able to get a stable connection.

The bottom part of the image is just a zoomed in part of the signal.

On Wednesday I will be able to check at 115200, if you really want. I can then also check the CPU load at 3M. We probably don't really need to go up to 3M baud, I just tried the highest setting available from QGC.

**Comment by davids5** [comment]
@jarivanewijk 

> ### RGB LED
> Also, the GPS LED driver seems to crash after a while, it stops emitting light.

I left this running on the bench 4+ hrs LEDs still bothe working. Were there any other issues apparent on console when it failed?

**Comment by jarivanewijk** [comment]
> 
> 
> @jarivanewijk
> 
> > ### RGB LED
> > Also, the GPS LED driver seems to crash after a while, it stops emitting light.
> 
> I left this running on the bench 4+ hrs LEDs still both working. Were there any other issues apparent on console when it failed?

Not that I noticed, but I might have missed something. I'll have a more thorough look at this on Wednesday.

**Comment by dk7xe** [comment]
I was able to fly indoors yesterday with 40358b7.
Today with commit 5169af4 i was not able to fly. Got compass inconsistency errors i could not resolve by recalibration.

**Comment by davids5** [comment]
@dk7xe did you reset the airframe and recalibrate with the new firmware? 
@dagar what is the parameter for compass delta?

**Comment by dk7xe** [comment]
> @dk7xe did you reset the airframe and recalibrate with the new firmware?

Hi David, yes did a complete new. unfortunateley it seems that the OLD telemetry caused the interferences. I removed the telemetry radio and was able to fly without any problems.
Telemetry link was done via TELEM2 and our D2X 5,9GHz communication radio btw.
@igalloway definetely we need to replace all the old telemetry radios still being in use!

**Comment by jarivanewijk** [comment]
@davids5 

TELEM1 with the U50 levelshifter still in place, at 115200 baud (with FTDI cable, measured close to FMU):
115200baud-TELEM1-U50
Signal is oscillating. 

TELEM2 without any levelshifter or resistorpack, at 115200 baud (with FTDI cable, measured close to FMU):
115200baud-TELEM2-noresistor
Signal looks OK. Again, this is TELEM2 which does not have the levelshifter/resistorpack.

TELEM1 with U50 removed and 220R resistorpack installed, at 115200 baud (with FTDI cable, measured close to FMU):
115200baud-TELEM1-resistorpack
Signal is OK. Looks similar now to TELEM2. 

TELEM1 with U50 levelshifter STILL IN PLACE(!), at 115200 baud (with telemetry radio, measured close to radio)
115200baud-TELEM1-U50-telemetry
No oscillations when only the telemetry radio is connected. However, signal does not go down to ground (LOW voltage level is higher than it is without levelshifter).


Also did a quick check of the CPU load with 3M baudrate. I had TELEM1 and TELEM2 enabled and a Mavlink instance running on both. This is the CPU load when both were set to 3M:
3Mbaud

And this is the CPU load with both set to 57k6 baud:
57k6baud

**Comment by davids5** [comment]
@jarivanewijk - this is good feedback - Thank you! The results are troubling in that the DC bias seam to change over time as well. What are the part numbers on the U50 levelshifter on your board. Please also check with a DVM the value cintinity of all the pins VDD, GND, and OE and all the lines on the cable from device to device.

**Comment by dk7xe** [comment]
My experience now with the full functional FMU (at previous the bmm150 was not working) is that i get a lot of times "Preflight Fail: Compass sensor inconsistenrt" errors.

**Comment by davids5** [comment]
@dagar is the calibration math causing @dk7xe issue? @dagar do you need log files to analyze it?

**Comment by davids5** [comment]
@dk7xe in the meantime COM_ARM_MAG can be adjusted upward to overcome the non arming.

**Comment by dk7xe** [comment]
> 
> 
> @dk7xe in the meantime COM_ARM_MAG can be adjusted upward to overcome the non arming.

Hi @davids5 the issue occures 100% when i have the drone on the bench but only randomly when i go for flying.

**Comment by davids5** [comment]
@dk7xe ahh what is on the bench that may affect it magnetically?

**Comment by jarivanewijk** [comment]
@davids5 

Last week I checked with another probe, just to be sure. Seems like the probe was the issue of the changing DC bias. See comparison between two probes:


With the other probe we still get oscillations at higher baudrates (similar to the previous figures), but the DC offset is lower and not changing anymore: 


Also, we did testflights with 2 FMUs yesterday. I didn't get the compass error @dk7xe is reporting, as far as I know.

**Comment by davids5** [comment]
@dagar @igalloway - rebased on master. @PX4/testflights Please test on Rev. C HW

**Comment by igalloway** [comment]
**Additional note on RevC production hardware:**
@davids5 you do not have these changes. Noting here just in case.

- U50 removed in exchange for inline series resistor array
- Glue will be applied on the battery for battery backup to avoid vibrations
- Production drone kit will use "better" power input module with slightly higher Vout (Black? XT60 connectors)

**Comment by Junkim3DR** [comment]
**Tested on NXP v3.x**

**Modes Tested** 
_Position Mode:_ Armed and took-off as expected, once in the air the vehicle was oscillating. 

_Mission Plan Mode (Automated):_ Once switched from position to mission vehicle gain altitude but did not start mission then switched back to position but UAV did not respond and crashed. 

_RTL (Return To Land):_ Untested. 

**Notes** 
Vehicle took-off in position mode but was oscillating while in the air. 
Vehicle did not respond to RC commands after switching from mission mode back to position mode.

https://review.px4.io/plot_app?log=d9e76bc4-5c82-42c5-84bf-19c127e78016

**Comment by dagar** [comment]
Thanks for testing. Looks like the merge was a bit premature. Investigating the bad flight in https://github.com/PX4/Firmware/issues/11767.

**Pull request merged**
