### PR TITLE
Bezier Library

### PR DESCRIPTION
**Pull request by mrivi**
This PR adds the bezier library written by @Stifael .

### CODE REVIEW

**Comment by dagar** [comment]
Minor clang-tidy complains.

image

**Comment by Stifael** [comment]
@dagar do you know why `modernize-pass-by-value` error shows up despite having it added to [.clang.tidy](https://github.com/PX4/Firmware/blob/master/.clang-tidy#L62)?

**Comment by dagar** [comment]
@Stifael that's because tests has its own .clang-tidy. https://github.com/PX4/Firmware/blob/master/src/systemcmds/tests/.clang-tidy

**Comment by Stifael** [comment]
eventually this lib will be used for smoother waypoint transition during missions.

**Pull request merged**
