### PR TITLE
Tko altitude fix +  xy control

### PR DESCRIPTION
**Pull request by Stifael**
The smooth altitude takeoff is broken if there is no velocity estimate available. In addition, xy control was turned off during smooth takeoff. Both issues are addressed in this PR. 
Instead of turning of xy control during smooth takeoff, the tilt is limited 

@PX4/testflights can you please test altitude takeoff when no gps is available (indoors) and compare it to current master.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
It overall looks ok, but I wanted to check in if smooth takeoff needs to be a state or is there a simpler way to do this long-term?

**Comment by Avysuarez** [comment]
Test with pixhawk 4 (v5) 
Good flight, but needs more than 80 percent throttle to take off.
https://review.px4.io/plot_app?log=0766bb77-e560-48a8-92fa-3a85a86593de
Master (commit 55b9f76)
https://review.px4.io/plot_app?log=40861e26-75d3-4557-a755-f1603e25e9e3

Test with pixhawk 2.1 (v3) 
Good flight, but needs more than 80 percent throttle to take off.
https://review.px4.io/plot_app?log=22365343-6c56-44d0-8e01-265d15fa49ff
Master (commit 55b9f76)
https://review.px4.io/plot_app?log=518d293b-ebe2-4054-9d50-d77c4803c547

**Comment by Stifael** [comment]
> if smooth takeoff needs to be a state or is there a simpler way to do this long-term?

A state like arm/disarm?

I mean the way it is currently done is not too complicated, but further encapsulation would probably help.
The goal of the smooth-takoff was to have a mode independent takeoff. Smooth takeoff can currently be triggered by:
1. a position setpoint above takeoff position (this happens in Auot or in offboard)
2. a velocity setpoint upwards above a certain threshold (in Altitude or Position)

Once smooth takeoff is triggered, the Flighttask setpoints along the z-axis and yaw gets overwritten.
I principle smooth-takoff is very simple trajectory implementation along the global z-axis that applies to any altitude related mode.

**Comment by dannyfpv** [comment]
flight indoors pixhawk 1 v2 very smooth takeoff is triggered
https://review.px4.io/plot_app?log=f892bb3b-c8f3-4da7-9b7a-4b5b142d5d2b

flight indoors pixhawk pro v4p very  smooth takeoff is triggered
https://review.px4.io/plot_app?log=2c69d993-84a2-4354-a7e1-02f2fb31b6f1

**Comment by Stifael** [comment]
I think so

**Pull request merged**
