### PR TITLE
MC rate ctrl sync

### PR DESCRIPTION
**Pull request by LorenzMeier**
@priseborough I continued your PR here.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
It seems like the runtime issues are due to changes in the sensors app alone. If I revert them things stabilise. So we can dig in there deeper.

**Comment by LorenzMeier** [comment]
@priseborough This runs now for me. Needs to get more testing.

**Comment by LorenzMeier** [comment]
@bkueng Fixed more compile errors. Still need to validate this end-to-end.

**Comment by bkueng** [comment]
I did some refactoring into a class to cleanly separate the API. In addition, `sensor_correction` is now only published if:
- voting index changes
- temperature changes by 1 or more degree (if that's too slow we can adjust that)

Instead of at the rate of the gyro.

Still left todo:
- more testing & validation
- better error handling & reporting
- my changes assume there's a match between driver class id and uorb pub instance, but that's not necessarily the case. I'll need to look into that.

**Comment by LorenzMeier** [comment]
@bkueng I don't see where the mismatch between class ID and uorb pub instance is. The voted ID you are using is the uORB ID already and that's correctly used.

**Comment by bkueng** [comment]
Looking at MPU6000:
The driver class ID comes from https://github.com/PX4/Firmware/blob/master/src/drivers/mpu6000/mpu6000.cpp#L660
And the uorb pub instance is created some lines further down: https://github.com/PX4/Firmware/blob/master/src/drivers/mpu6000/mpu6000.cpp#L669
These should typically match. However:
- there's a race condition between these 2 events.
- also I'm not quite sure what happens on driver restart: are the 2 ID's released and it gets the same one (as it should), or does it get a new ID?

The assumption in my code is here: https://github.com/PX4/Firmware/pull/6363/commits/13347ffa2588f4a926011db93d43d17ce377a96c#diff-a4442851925fd43c16a781c4b830eb87R165

One way would be to ask the driver for its uorb instance via ioctl(), but requires adding it to all drivers.

**Comment by bkueng** [comment]
Updates:
- `sensors status` now prints whether temp compensation is enabled & correctly configured
- added error reporting
- stack size adjustments were necessary
- fixed a bug in mc_att_control
- removed the requirement that the driver class ID matches the uorb instance

**Comment by LorenzMeier** [comment]
I've tested this on FMUv2 and it behaves now. Thanks!

**Comment by priseborough** [comment]
This has been flight tested on a Pixracer flying a 250 size quad. Log here:http://review.px4.io/plot_app?log=8123b7e5-ae28-4b06-bff1-47131df73cd2

**Comment by MaEtUgR** [comment]
I made a really short test with this pr today with unchanged tuning in manual flight mode outside and didn't note any difference in flying.

**Comment by LorenzMeier** [comment]
Do not delete the branch yet.

**Comment by LorenzMeier** [comment]
@bkueng Rebased and merged - please continue.

**Comment by kd0aij** [comment]
Do we have any quantitative measures of latency reduction with this change?

**Comment by kd0aij** [comment]
@priseborough This is my estimate of rate controller latency for your log:
rate_ctl_latency

**Comment by priseborough** [comment]
@kd0aij What does that latency value include? It is much larger than the average frame time of 4msec.

A good test will be how much the P gain can be increased before the rate loop starts to 'ring' before and after the scheduling change.

**Comment by kd0aij** [comment]
@priseborough My estimate of "rate controller latency" is computed by first assuming that the impulse response is a damped sinusoid and solving for the 3 parameters (h(t) = p3 exp(-p1 t) sin(p2 t)) using a least squares technique with the rate control input as stimulus and the rate gyro signal as output. 

I then convolve this impulse response with the control signal to get the roll/pitchModel signal plotted above, and to compute the quality of fit by comparing to the actual roll/pitch gyro signals. 

The "latency" is computed, by again using a least squares technique to find the delay which best matches the control signal to the model (delayedRoll/Pitch in the plot). 

So this latency is a measure of the speed of response of the closed loop system. It does rely on accurate timestamping of the logged data, and I resample the data to a uniform 100Hz rate prior to processing since the logging intervals are not uniform. 

I have recently been working on mods to the firmware to log all MPU6000 gyro/accel sample data at 1KHz to avoid the (apparent) jitter introduced by the current timestamping method and improve the quality of spectral analysis.

**Comment by priseborough** [comment]
The way that a 1 degree change in temperature is being used as a basis for publishing the sensor corrections is not working as intended because each sensor is measuring a different temperature so it is being published all the time. We need to monitor the temperature separately for each sensor instance. I will push a patch to fix this.

**Pull request merged**
