### PR TITLE
NuttX update to 8.2+

### PR DESCRIPTION
**Pull request by dagar**
We're still relatively close to NuttX master. Instead of accumulating patches (https://github.com/PX4/NuttX/pull/73) let's keep moving forward.

 - https://github.com/PX4/NuttX/commit/43a6e43a0f7aae2c8bf7c9a81b80400dcb61f358
 - https://github.com/PX4/NuttX/commit/fe49dcf622bdc8a1dacb45c90b7b02adf4046261

Newer NuttX also has other NET fixes we might as well take. https://groups.google.com/forum/#!topic/nuttx/JRyrsZw3Vj0

### CODE REVIEW

**Comment by davids5** [comment]
@dagar @LorenzMeier - I expect to have F7 serial TX DMA in Monday. Then any changes to correct the RT1062 in by Friday. At that point in time it would make sense to du the uptake and invest in the testing.

**Comment by dagar** [comment]
I'd like to propose at least experimenting with a slightly different approach where we parallelize the effort. By doing smaller incremental general updates the test team can spend more time rather than lumping together large update + new support (eg h7, imxrt, etc). Then when we get to the point where we want to pull in the new feature it won't be blocked waiting on larger exhaustive general testing across all platforms.

**Comment by davids5** [comment]
@dagar - I would agree with you if upstream master was continual stable. It is not - yet. But I expect it will be in the near future.  Having to firefight unrelated nuttx issues during board bring up is not productive.

**Comment by dagar** [comment]
The idea isn't to dump new NuttX into master, but to stay ahead of upcoming problems we can work through together incrementally (eg px4io flash or build system changes) and not be forced to urgently because it's blocking what you actually want (eg H7 support). We should do this specifically to minimize unrelated NuttX issues during a board bringup.

The vast majority of NuttX commits effectively don't impact us at all, but by the time we try to update there's an incomprehensible amount of total change. By consuming it incrementally and with the help of automated tooling (jenkins builds and per component bloaty reports) we can isolate the relevant changes for targeted testing and closer inspection as time allows.

Another example to consider is how we handled the F7 dcache issue. Within about a month of us discovering the potential data corruption issue (~ Feb 2019) there was a fix in NuttX (cache interface unification and fixing writeback). After this the work was done in PX4 to make the dcache controllable with a parameter. It was more than 4 months later that we stumbled across the NuttX fix and finally had a working dcache again. Obviously this exact scenario won't be repeated, but it makes me think we're under-utilizing the wider NuttX community.

**Pull request closed without merging**
