### PR TITLE
Mavlink2 test

### PR DESCRIPTION
**Pull request by jimdsouza**
Built px4fmu-v2_default with generated C headers from mavlink fork [here](https://github.com/jimdsouza/mavlink/tree/mavlink2-wip_test).

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@DonLakeFlyer This should allow you to copy the headers and to test against a SITL running v2.0

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Did you get a chance yet to create a QGC branch to test?

**Comment by DonLakeFlyer** [comment]
Started, but not much progress. Too many other things going on.

**Comment by LorenzMeier** [comment]
I'm closing this and taking a fresh stab at it.

**Pull request closed without merging**
