### PR TITLE
[WIP] commander delete unused and minor cleanup

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This diff might break other PRs - should we coordinate on a commander rewrite? (which is due anyway).

**Comment by dagar** [comment]
Yes! The only question is how we approach it without breaking the world. 
As appealing as a rewrite sounds the current commander isn't beyond saving incrementally. Delete everything broken or no longer relevant, move anything that doesn't belong in commander, then one by one extract and encapsulate the bigger core behaviour (HOME, command handling, etc). Then turn the base commander into a class, move all the static variables in, params to controllib.

As a crude testing method we could replay logs (real and simulated) with something in place to catch differences in messages published by a stable commander.

**Comment by dagar** [comment]
@LorenzMeier thinking through this a bit more, can you describe what you think is and isn't appropriate for the new events module? Should all calibration code live there and drop the low priority commander thread?

**Comment by dagar** [comment]
I'll revisit this when there's no other active development in commander and we're ready to think about a commander rewrite/refactor.

**Pull request closed without merging**
