### PR TITLE
Added attitude_estimator_ekf2.

### PR DESCRIPTION
**Pull request by jgoppert**
Adds a new ekf attitude estimator using alignment and bias as states. This can be flown in SITL with:

```bash
make posix_sitl_ekf2 jmavsim
```

 I have yet to do a real test flight.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Fantastic!

**Comment by jgoppert** [comment]
I think there is an error in the bias estimation, will have to debug a bit.

**Comment by LorenzMeier** [comment]
Keep in mind that unaccounted position time delay can load the offset as well. If you don't match the delta velocities to the reality you load them into the offset.

**Comment by LorenzMeier** [comment]
I'm closing this as it would be rather untested and unmaintained on master.

**Comment by tuofeichen** [comment]
Hey guys, sorry to comment here, 
I'm wondering what 's the difference between ekf2 and default, the parameters.xml in both folders seemed to be exactly the same? 

I think I have the most updated version of Firmware from the master branch. 

Thanks!

**Comment by LorenzMeier** [comment]
Please use the forum or mailing list for questions, not closed pull requests.

**Comment by tuofeichen** [comment]
oops, sorry! Will do!

**Pull request closed without merging**
