### PR TITLE
LSM9DS1 Driver Framework Wrapper

### PR DESCRIPTION
**Pull request by mayanez**
Wrapper for LSM9DS1 driver.
See Issue https://github.com/PX4/DriverFramework/issues/44
Related PR: https://github.com/PX4/DriverFramework/pull/110
Adds Support for Navio2

### CODE REVIEW

**Comment by mayanez** [comment]
I'm still a bit new to how the submodules work, but it seems like the tests are failing because it is not finding the appropriate commit for DriverFramework.

Should I make a new commit with DriverFramework at master?

**Comment by dagar** [comment]
Your changes need to be available in https://github.com/PX4/DriverFramework for the build system to find them, or you could point PX4/Firmware to a personal DriverFramework (also on github) for testing.

**Comment by julianoes** [comment]
@mayanez I'm currently working on this. Will merge probably less than 1h and you can go from there.

**Comment by julianoes** [comment]
@mayanez We don't usually use git merging but just rebase PR branches like this. I did the same in the DriverFramework which is the reason the git hashes are not available anymore.

**Comment by julianoes** [comment]
@mayanez: Your commits are now in #4900, thanks!

**Pull request closed without merging**
