### PR TITLE
WIP try latest px4-dev-ros image

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I looked at this. Pretty absurd failure, didn't hit the 3rd waypoint or so. Need to test this locally.

@dagar It could be CPU related, e.g. the old image putting CPUs in performance mode and this image not or something like that.

**Comment by LorenzMeier** [comment]
@dagar We didn't happen to reduce the number of cores or something in the image, right?

**Comment by dagar** [comment]
I can't imagine. It's just this and the command that runs it is identical - https://github.com/PX4/containers/blob/master/docker/px4-dev/DockerfileRos

**Comment by LorenzMeier** [comment]
@dagar Jenkins runs on Ubuntu 14.04 IIRC - is it possible that the runtime performance of the 16.04 image is worse because it doesn't allow to map the CPU (or GPU) directly? Can we downgrade to 14.04 again?

**Comment by jgoppert** [comment]
It isn't clear to me why the box test case is failing. Is it just not landing or something, or terminating the sim too early. I looked at the failed log and the trajectory looks fine.

```python
df = px4tools.ulog.read_ulog('./21_17_58.ulg').resample_and_concat(0.1)
px4tools.ulog.estimator_analysis(df)

ESTIMATOR ANALYSIS

mean euler error:
	  1.324152	 deg
	 -1.104819	 deg
	 -0.583186	 deg

standard deviation euler error:
	  0.541134	 deg
	  0.218583	 deg
	  4.715894	 deg
```

image

image

image

image

image

**Comment by jgoppert** [comment]
It looks like the failsafe is kicking on for the mission. The flight performance for offboard looks fine.

```bash
[ INFO] [1482787057.610653174, 4.236000000]: VER: 1.1: Board hardwar[31m[ERROR] [1482787067.007410076, 13.624000000]: FCU: failsafe mode on[0m
[31m[ERROR] [1482787067.606927908, 14.222000000]: FCU: failsafe mode off[0m
[31m[ERROR] [1482787072.406443405, 19.018000000]: FCU: failsafe mode on[0m
INFO  [logger] logger started (mode=all)
INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2016-12-26/21_17_35.ulg
INFO  [mavlink] partner IP: 127.0.0.1
WARN  [mavlink] [timesync] Hard setting offset.
INFO  [tone_alarm] startup
INFO  [lib__ecl] EKF using pressure height - commencing alignment
INFO  [lib__ecl] EKF alignment complete
INFO  [lib__ecl] EKF gps is good - setting origin
INFO  [lib__ecl] EKF commencing GPS aiding
INFO  [commander] home: 47.3977420, 8.5455935, 488.09
INFO  [tone_alarm] home_set
INFO  [tone_alarm] positive
INFO  [commander] no RC and no offboard
WARN  [commander] failsafe mode on
INFO  [commander] home: 47.3977420, 8.5455935, 488.03
INFO  [tone_alarm] positive
INFO  [commander] home: 47.3977420, 8.5455935, 488.03
WARN  [commander] failsafe mode off
INFO  [tone_alarm] arming
INFO  [commander] Takeoff detected
INFO  [tone_alarm] neutral
**INFO  [commander] no RC and no offboard**
WARN  [commander] failsafe mode on
```

**Comment by LorenzMeier** [comment]
@jgoppert The trajectory also looked incorrect - it should be a square, not a triangle. The triangle suggests it skips one waypoint.

**Comment by jgoppert** [comment]
Hopefully the commit above that adds sleep before trying to send the mission is what we needed. I ran into this on IEKF. If the estimators initialize before the sim is done loading it will freeze basically and the auto-disarm on land will kick in before it can takeoff.

**Comment by jgoppert** [comment]
@LorenzMeier That was my mistake, I analyzed the local position setpoint instead of the auto-mission. The box mission doesn't ever takeoff.

**Comment by jgoppert** [comment]
That didn't work, trying more sleep time after sending mission.

**Comment by LorenzMeier** [comment]
One Jenkins against a whole dev team. So far Jenkins: 10 - Dev team: 0. Let's see where that takes us!

**Comment by LorenzMeier** [comment]
I think the key lies in the unrecognised command 176: [33m[ WARN] [1482797064.301335772, 13.206000000]: CMD: Unexpected command 176, result 0[0m

**Comment by LorenzMeier** [comment]
Maybe sleep for 15s?

**Comment by dagar** [comment]
px4-dev-ros rebuilt on px4-dev-base (Ubuntu 16.04) - https://github.com/PX4/containers/pull/44

**Pull request closed without merging**
