### PR TITLE
Enabled gps delay compensation for lpe based on x hist.

### PR DESCRIPTION
**Pull request by jgoppert**
Storing  the state covariance matrix was too much memory, but just the state matrix works great. The fault detection was actually saying the GPS was faulting before this patch due to the delay, so it seems fault detection is also working well  now for LPE. I store the state at 20 Hz. This is so that we get enough resolution for the delay of 200 mz (5 Hz).

This has been tested in SITL. Will do a flight test soon.

### CODE REVIEW

**Comment by ecmnet** [comment]
@jgoppert Did a short flight test with your latest changes. There were none GPS faults anymore. Btw. do you know, when home position is set in global position? It was set to 0.0 - 0.0 in my case.

**Comment by jgoppert** [comment]
@ecmnet If there is no gps it initializes the global position to 0 lat, 0 lon.

I'm still ironing out some bugs with this I found from flight testing, so be careful when testing. I'll probably wrap up my fixes soon.

**Comment by ecmnet** [comment]
@jgoppert Maybe my GPS got the fix late.

**Comment by jgoppert** [comment]
@ecmnet Yes, you probably had flow before you had GPS. We would make it require GPS for global position pub, but you could never fly on flow alone that way. We could also do a hook that say if you didn't have GPS and you get it, that you instantly move the home position to what the GPS says.

**Comment by ecmnet** [comment]
@jgoppert I would prefer the latter alternative, although HomePos might be quite false, if the GPS fix is acquired late during flight. But that might be better than a 0.0 - 0.0 position.

**Comment by jgoppert** [comment]
@ecmnet I added the hook now. It will start publishing global position only when it has received good gps signal at least once.

Also, I just finished a flight test, looks good to merge @LorenzMeier:
http://logs.uaventure.com/view/iixxrUoBwRk7EjKdyYFQ4N

**Comment by jgoppert** [comment]
I still occasionally get a GPS alt fault. I know it is related to the baro bringing down the state z covariance down so low and then drifting all over the place in low frequency, but I'm not sure about how best to deal with it.

**Comment by ecmnet** [comment]
@jgoppert Still I am receiving a home position 0.0 - 0.0; even when the GPS fix is available immediately after booting. Any idea? Another point: Leaving the vehicle on ground, I get a continuous stream of lpe messages (e.g. flow fault).

**Comment by jgoppert** [comment]
@ecmnet I've been focused on GPS/baro for now. Today I'll test with lidar/flow and that should smooth out the latest changes for you.

**Comment by jgoppert** [comment]
@ecmnet This was test flown with lidar now. I changed lidar min range to not throw a fault message and just ignore, so a lot less verbose. Here is a log of a the test flight. I had an sf02 hanging off the front of the go pro mount, so the pitch gain was a bit low to correct for the uncentered cg.

http://logs.uaventure.com/view/G8gDtGnEyuFLy2vQq5xpBL

**Comment by ecmnet** [comment]
@jgoppert Was that flight flow or GPS based (or both)?

**Comment by jgoppert** [comment]
Didn't have flow plugged in for this one.

**Comment by ecmnet** [comment]
@jgoppert Some observations: If I disconnect Flow, no global position is published, even with GPS fix. Still home position is not set properly. Reconnecting flow publishes global position again.

**Comment by jgoppert** [comment]
I just did some more testing with lidar + gps. I had to set ATT_BIAS_MAX = 0 to get the attitude estimation to stop screwing up. So just a heads up there. Not sure if it is due to the new delay compensation. I have to check against inav and lpe master.

@ecmnet Will look into that. Once gps is received once I set globalPositionValid = true. And that is the hook on if global position is published.  To get the home position to work try just adding a delay before the flow init at the start, or temporarily you could add a hook that you only initialize flow if gps is initialized. I will try to make a permanent fix soon.

**Comment by jgoppert** [comment]
@LorenzMeier  This is ready to  go and tested. I plan to merge it after successful test of the rebase on master.

**Comment by ecmnet** [comment]
@jgoppert SITL gives me a compilation error, while LPE compiles without any complaints: 

src/systemcmds/topic_listener/topic_listener.cpp:794:39: fatal error: no member named 'gyro_rad_s' in 'filtered_bottom_flow_s'
                                printf("%8.4f ",(double)container.gyro_rad_s[j]);

Any idea? I think I have used the current master.

**Comment by jgoppert** [comment]
I just built posix_sitl_lpe and posix_sitl_default on master and it works for me.

The filtered_bottom_flow_s was deleted, so that looks like an old object file. Try:

```bash
git clean -dxf
make posix_sitl_lpe 
```

**Pull request merged**
