### PR TITLE
Helicopter mixer scale throttle to -1 .. +1

### PR DESCRIPTION
**Pull request by bartslinger**
Not sure why it worked for me without this change. I cannot test it myself. Should fix https://github.com/PX4/Firmware/issues/8013

### CODE REVIEW

**Comment by tubeme** [comment]
@dagar Can you review this change?

**Comment by tubeme** [comment]
The interesting thing about the current implementation is that once the helicopter mixer runs there is no way I could use the throttle mixer in another channel.

For example as a work around I wanted to use another throttle (plain) mixer at ch6.

M: 1
O: 10000 10000 0 -10000 10000
S: 0 3 0 20000 -10000 -10000 10000

and the servo at ch6 did not move, once I had the helicopter mixer running.

**Comment by tubeme** [comment]
Thanks @LorenzMeier We will try it in the coming days.

**Comment by tubeme** [comment]
@bartslinger @LorenzMeier Works perfect! Thanks

**Comment by JL-1994** [comment]
Hi @tubeme, just wondering, was your motor ESC connected to channel 1 or channel 6? I have a problem to make the motor work.

I was trying to separate the collective control with the motor speed. Do you have any idea how can I achieve that? 

Thanks.

**Comment by tubeme** [comment]
Hi @JL-1994 We have no ESC but servo for the throttle. We are setting up IC engine heli.

The throttle is connected to CH1 with the Blade130 mixer we are using.

And the Throttle and Swash Plate can be scaled totally separated. So you could achieve what you need with the just tweaking the mixer.

With the Helicopter mixer there is no way you could use other channel for throttle, like your example at CH6. We tried this workaround first. It did not work.

**Comment by JL-1994** [comment]
Thanks for the info @tubeme. I've still got some question:

1. So the IC engine heli will spin the motor at constant rpm without the control of the PX4?

2. May I know how does the servo for the throttle of your heli works? Spinning the main motor?

3. I've tried connecting the CH1 to an ESC but the motor doesn't spin. Is it a bug or does the channel only will make a throttle servo work, not an ESC? Any advice? @bartslinger

**Comment by tubeme** [comment]
@JL-1994 Here are some answers.

1+2. THe IC engine heli works exactly like the real helicopter. You don't have a constant throttle! You have an IC engine throttle (servo connected to the air intake valve of the IC like in a real car). The IC engines (and the Jet ones in the real helicopter) are with a very slow response so in order to control with precision they introduced the swash plate with which we change the angle of attack of the blade (and roll+pitch movement). Both the throttle and the angle of attack of the blade are in sync, each with a different scaling. You can control this with the blade130 mixer.

The same holds for the electric heli's. The only difference is that you give the PWM commands not to a servo but to an ESC.

3. Check the ESC and motor, is it working? make ESC calibration (outside the pixhawk, classic way) and see if it spins the motor properly outside the Pixhawk setup.

Do you hear the ESC arming once you connect the battery? Or do you hear beeps from the ESC all the time until you arm?

@bartslinger actually wrote this mixer using and electric heli with ESC connected to CH1.

**Comment by JL-1994** [comment]
Thanks for the explanation~ You are right, my ESC wasn't working and I realise I didn't change to the debugged code. Finally it's working now! Thank you so much!

**Pull request merged**
