### PR TITLE
sensors: split out battery_status to new module

### PR DESCRIPTION
**Pull request by dagar**
Quick PR to split out the analog battery handling from the sensors module.

 - [x] add to each board
 - [x] add to rcS
 - [x] remove BOARD_NUMBER_BRICKS ifdefs and skip the module on boards instead
 - [ ] rename analog_battery_status?

### CODE REVIEW

**Comment by dagar** [comment]
This is a simple incremental step to get the battery handling out of sensors pipeline and helps improve modularity as these power setups continue to get more diverse.

This is going to conflict with some of @ItsTimmy's open PRs, but I'll get them rebased.

**Comment by SalimTerryLi** [comment]
Is it necessary to move the whole adc function out of DriverFramework? Currently differential pressure sensor and battery which rely on adc are all based on df.

**Comment by dagar** [comment]
> Is it necessary to move the whole adc function out of DriverFramework? Currently differential pressure sensor and battery which rely on adc are all based on df.

Yes, but that part actually shouldn't be too difficult. Short term the DriverFramework usage can be replaced with CDev (for block device access) and the new PX4 work queue (for period scheduling).

In the ADC case I'd like to consider merging the frontends and only having to provide a few minor calls for ADC access. Then most platforms could share this common ADC frontend. https://github.com/PX4/Firmware/blob/master/src/drivers/adc/adc.cpp

**Comment by dagar** [comment]
@SalimTerryLi just to be clear on my previous comment, it's necessary medium term to get everything moved out of DriverFramework for several other important reasons, but short term it's not necessary for the sake of analog battery and airspeed.

**Comment by SalimTerryLi** [comment]
@dagar Got it. I would like to have a try :)

**Comment by julianoes** [comment]
> This is going to conflict with some of @ItsTimmy's open PRs, but I'll get them rebased. #12673 #12551

@dagar are you still planning on doing that? If so, when? This is a bit unfortunate because @ItsTimmy had his PR ready to be merged a while ago and we were waiting on the release to go out to then merge these things. We should coordinate these things better otherwise it can be frustrating.

**Pull request merged**
