### PR TITLE
Jenkins: allow test to specify docker image with default

### PR DESCRIPTION
**Pull request by lamping7**
This will allow for specialized environments or for testing multiple setup. Use case -- Gazebo 8 for https://github.com/PX4/Firmware/pull/10780

~~Additionally I'll push a DO NOT MERGE commit once we have a Gazebo 8 container built for testing.~~

@TSC21 @mrivi

### CODE REVIEW

**Comment by lamping7** [comment]
Attitude test still failed... needs looked at.

**Comment by lamping7** [comment]
I'm going to keep some notes here in case anything triggers an idea for someone and so I don't forget:

- I grabbed the 2018-09-11 docker image and ran it locally. Inside it, I used `wget` and pulled the package artifact from Jenkins that was produced with 2019-01-25 [here](http://ci.px4.io:8080/job/PX4_misc/job/Firmware-SITL_tests/job/PR-11294/6/artifact/build/px4_sitl_default/px4-px4_sitl_default-v1.9.0-alpha-292-g458139e.tar.bz2)
- I extracted it as Jenkins does, then executed the test, again just as Jenkins does.
- The result was the same as in Jenkins. PX4 seems to get hung up during startup.
- Thinking about permission problems with the links created at startup I re-did all this, but used `docker run -u 0 -it -e LOCAL_USER_ID=0 ...`. After extracting, I `chown`ed the whole dir with 0:0 and tried again.
- Same thing.
- I decided to repeat the test with the same image that created the package, so I pulled the 2019-01-25 image and repeated the first run as before.
- The test ran... **Huh**?

This is kind of important to figure out what is going on. Not only for the use case here, but for future plans of encouraging users to just pull this package and use it (which doesn't appear to work right now).

**Comment by lamping7** [comment]
What makes this issue interesting is that sitl_gazebo is at that commit specified by this version of PX4. They're in sync, built at the same time then packaged up. The only difference is that we're grabbing this package, built in one container and running it in another. I can open a seperate issue for this.

Either way, I've shown that the PR works and let's you specify a different run container for the test. Should I put everything back to 2018-09-11 and we get this in? I'm fine with that, but until we figure out the problem above it is kind of useless.

**Comment by dagar** [comment]
Still needed?

**Pull request closed without merging**
