### PR TITLE
move -fno-math-errno to nuttx only

### PR DESCRIPTION
**Pull request by dagar**
Causes param errors on Snapdragon for some reason.

@rogelion

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@dagar I think we need on HW-CI before we can make more significant architectural changes.

**Comment by dagar** [comment]
@LorenzMeier yes definitely.

**Comment by LorenzMeier** [comment]
Can we please revert the commit? The daily testing uncovered unexpected behavior

**Comment by LorenzMeier** [comment]
I mean disable the option globally. Its not just posix which has issues.

**Comment by dagar** [comment]
Done - https://github.com/PX4/Firmware/pull/7462

**Pull request merged**
