### PR TITLE
Mission reset in loitering

### PR DESCRIPTION
**Pull request by jinchengde**
current reset mission need vehicle land and disarm, and if mission have no land waypoint, the vehicle will keep loiter, this PR will help to reset the mission during loiter, just change the fligt mode to other and change back to "mission", then the mission will reset.

### CODE REVIEW

**Comment by dagar** [comment]
Won't this reset the mission to the beginning if you leave at any point and reenter?

**Comment by dagar** [comment]
Is the main goal to be able to reset the mission after completion while still in the air?

**Comment by jinchengde** [comment]
yes, reset the mission after completion while vehicle still loitering in the air

**Comment by jinchengde** [comment]
only reset the mission when the mission finish , but not leave any point.
If you leave the mission at any point, still resume the mission

**Pull request closed without merging**
