### PR TITLE
Resized px4io v2 stack to have only 28 bytes headroom (was 432)

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier 

Per your request this get back ~400 bytes. Please verify it with a real mixer. I tested with `px4io test` and `pwm test -a -p  1234`

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@AndreasAntener worth validating on hardware. Should fix our mixer space issues for good.

**Comment by AndreasAntener** [comment]
Cherry-picked this into one of my branches but didn't help, AETR mixer still can't load, tested on a Pixhawk 2

**Comment by LorenzMeier** [comment]
You need to try with a branch based off master. I stripped the gimbal bits from the mixer

**Comment by AndreasAntener** [comment]
But isn't the point of this to make the full 8 channels again?

**Comment by LorenzMeier** [comment]
The main point would be to repair the AETR config. I'm pretty sure that space is not the only issue, there might also be something structural to the mixer loading code that I need to fix.

**Comment by AndreasAntener** [comment]
Simon tried a few things there: https://github.com/PX4/Firmware/issues/4038

**Comment by LorenzMeier** [comment]
I was rather looking for an architectural fix, not a squeeze. Tridge found one which is what we will be using instead of this: https://github.com/diydrones/PX4Firmware/commit/f11d76c4b8c6ff201fe2bf1e1dbd730449c24a53

**Comment by LorenzMeier** [comment]
Given this commit from tridge the change here is clearly wrong:
https://github.com/diydrones/PX4Firmware/commit/4e5cccf67a5d25f8bb9ff87103e31ff8c0b1130b

**Pull request closed without merging**
