### PR TITLE
Tecs fix pitch integ

### LINKED ISSUE #2893: [TECS] Pitch down when engaging alt ctrl for first time
During flight test, when altitude position control has been engaged airplane started to pitch down. The pitch integral reached high negative value at that time. We flew with master 3724947 and we used TECS fix https://github.com/PX4/Firmware/pull/2783
pitchdown

Logging: http://logs.uaventure.com/view/Mz4PbA4F32q9ekaH85xudP

### PR DESCRIPTION
**Pull request by LorenzMeier**
This should fix #2893.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@boosfelm @tumbili please review / test.

**Comment by LorenzMeier** [comment]
@dagar This might be relevant for you.

**Comment by boosfelm** [comment]
from a first glance looks reasonable to me, we will test asap.
@mswingtra this is not yet in master, can you make sure we test it when we go flying next time? Thanks

**Comment by LorenzMeier** [comment]
This could be another instance (pre-fix):
http://logs.uaventure.com/view/CRzMpDoUvSshcFPY8wNXUA

**Comment by LorenzMeier** [comment]
@sjwilks @AndreasAntener Could you maybe cross-test this on a Wing-Wing on your next test flight session?

**Comment by SimonWilks** [comment]
@AndreasAntener did we not already test this? Or are we just not seeing it now that we start with a runway takeoff?

**Comment by AndreasAntener** [comment]
No we didn't test this yet. We don't see the effect of it because during runway takeoff TECS is already running, and at the time when it actually switches to TECS for pitch (after takeoff), the integrator has normalized itself. But the spike is there in the beginning. Let's just take that in for the next test.

**Comment by LorenzMeier** [comment]
Rebased on master

**Comment by AndreasAntener** [comment]
I'll give this a go later.

**Comment by LorenzMeier** [comment]
Rebased on master, applied.

**Comment by AndreasAntener** [comment]
Just to clarify: I've flown master with and without this. I wanted to reproduce it first with plain master but the issue did not occur (in 3 flights, also not with our runway takeoff/land branch), so I can only say that this didn't have an adverse effect.

**Comment by boosfelm** [comment]
We tested the patch and it does not happen anymore. Thanks @LorenzMeier

**Pull request closed without merging**
