### PR TITLE
Update submodule ecl to latest Tue Jun 11 12:38:12 UTC 2019

### PR DESCRIPTION
**Pull request by dagar**
- ecl in PX4/Firmware (6f194d44bd3d11baad47ce23d37fa23299fe91d1): https://github.com/PX4/ecl/commit/0f49eb34a08e499a26d749ed981429047f2100ff
    - ecl current upstream: https://github.com/PX4/ecl/commit/cef2ba5ab9fbc3b36c09181f7a9170d8c255fb8b
    - Changes: https://github.com/PX4/ecl/compare/0f49eb34a08e499a26d749ed981429047f2100ff...cef2ba5ab9fbc3b36c09181f7a9170d8c255fb8b

cef2ba5 2019-05-08 Roman - implemented Kahan summation algorithm for adding process noise to delta angle- and delta velocity bias variance

### CODE REVIEW

**Comment by dagar** [comment]
This brings in the Kahan summation change.

**Comment by dannyfpv** [comment]
Tested on Pixhawk4 V5 f450
Modes Tested

Position Mode: no issue
Altitude Mode: no issue
Stabilized Mode: no issue
mission mode: no issue
rtl: no issue

pr log:
https://review.px4.io/plot_app?log=5b4599f3-2ee9-4bf2-aee0-7630b7e82ae3

master log:
https://review.px4.io/plot_app?log=d6b64a97-057e-4064-a185-97de8c0a5852

**Comment by jorge789** [comment]
### Tested on PixRacer V4:

**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:** 
https://review.px4.io/plot_app?log=90564758-6659-42b3-8004-2d8f1eedf0e7

**Log: Comparison to master:**
https://review.px4.io/plot_app?log=39c9e714-0813-4f8b-8e96-908907baa506


### Tested on Pixhawk 2 Cube V3:
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:**
https://review.px4.io/plot_app?log=266d552b-22f0-4f7f-83a1-d89266fe9636

**Logs: Comparison to master**
https://review.px4.io/plot_app?log=c1d7199f-bd87-4af8-b4f0-c2af71fc3636

**Comment by Junkim3DR** [comment]
### Tested on Pixhawk 4mini v5:

**Modes Tested**
- Position Mode: Good.
- Altitude Mode: Good.
- Stabilized Mode: Good.
- Mission Plan Mode (Automated): Good.
- RTL (Automated): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:** 
_PR 12244_
- https://review.px4.io/plot_app?log=ce2c593c-2afb-4800-acbe-02e6621d4d8a

_Master_
- https://review.px4.io/plot_app?log=28780b02-e52f-4be4-a7de-1ebf6b71c8bd




### Tested on NXP vFMUK6_v3:

**Modes Tested**
- Position Mode: Good.
- Altitude Mode: Good.
- Stabilized Mode: Good.
- Mission Plan Mode (Automated): Good.
- RTL (Automated): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:**
https://review.px4.io/plot_app?log=670aaff6-ba17-4047-ae2c-53e26d74bf74

**Pull request merged**
