### PR TITLE
delete unused doxygen config

### PR DESCRIPTION
**Pull request by dagar**
I don't see this doxygen setup being used anywhere, and it would need work to be useful (generated uorb first, etc). Let's get rid of it unless we actually want to do something with it.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@dagar I completely agree with you .... but when I tried to delete this last time @LorenzMeier objected. Up to him to review this and argue the case.

**Comment by dagar** [comment]
Maybe we should take a look at the current state of the output and see if it's salvageable or not.

**Comment by hamishwillee** [comment]
Yes, and if it is, shove it into the docs and CI so that it gets regularly tested and (ideally) forced to improve.

**Comment by LorenzMeier** [comment]
We ran this on a server at ETH. Rather than deleting it I'd like to see it being executed in CI and uploaded to S3.

**Comment by dagar** [comment]
Let's try to save it.

**Pull request closed without merging**
