### PR TITLE
WIP add new config for QAV250 racing quad

### PR DESCRIPTION
**Pull request by kd0aij**
Needs more testing on PWM_MIN and max/min thrust parameters

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Please do not include the Eclipse project in the PR.

**Comment by kd0aij** [comment]
Sorry, I'm not sure how my Eclipse project got into my fork of master. Will have to research how to keep my own version of the Eclipse project without adding it to git.

**Comment by LorenzMeier** [comment]
Are we sure we want the Eclipse project in? It keeps causing issues and developers are advised to use Qt creator: http://dev.px4.io/starting-building.html#compiling-in-a-graphical-ide

**Comment by kd0aij** [comment]
I prefer Eclipse at present. Qt seems deficient at finding symbol definitions, and worse, it's not stable on my desktop machine.

**Comment by dagar** [comment]
At the very least can we keep a basic eclipse .project so that firmware can be cloned within eclipse or imported directly without creating a new dummy project?

**Comment by kd0aij** [comment]
closed in favor of #3135

**Pull request closed without merging**
