### PR TITLE
v5 tx dma telem2 Using [BACKPORT] stm32f7:Add Serial Tx DMA

### PR DESCRIPTION
**Pull request by davids5**
This is for testing the NuttX changes to support Serial TX DMA ~~(px4_firmware_nuttx-8.2+_serial_tx_dma)~~ [BACKPORT] px4_firmware_nuttx-8.2 on  on V5 Telem2 

@dagar - On px4_firmware_nuttx-8.2+ px4io is down on free memory by 32 bytes!
Do we have a bloaty check on it?

### CODE REVIEW

**Comment by davids5** [comment]
Test:
`mavlink start -d /dev/ttyS2 -b 921600 -m config -z`
**MASTER**
```
 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
   0 Idle Task                   43652 35.373   240/  512   0 (  0)  READY  3
   1 hpwork                          0  0.000   344/ 1260 249 (249)  w:sig  3
   2 lpwork                         51  0.000   604/ 1516  50 ( 50)  w:sig  8
   3 init                          931  0.000  2016/ 2604 100 (100)  w:sem  3
   4 wq:manager                      0  0.000   368/ 1252 243 (243)  w:sem  4
 169 wq:att_pos_ctrl              6085  8.214  4768/ 6596 244 (244)  READY  4
  17 dataman                        98  0.083   760/ 1204  90 ( 90)  w:sem  4
  20 wq:lp_default                  59  0.083   812/ 1700 205 (205)  w:sem  4
  22 wq:I2C1                       399  0.586   820/ 1396 246 (246)  READY  4
  27 wq:hp_default                 777  1.005  1076/ 1796 243 (243)  READY  4
 134 wq:SPI1                     17782 23.302  1032/ 1396 253 (253)  w:sem  4
 146 wq:I2C3                       280  0.419   840/ 1396 244 (244)  READY  4
 149 wq:SPI4                       267  0.419   600/ 1396 250 (250)  w:sem  4
 168 sensors                      1978  2.682  1328/ 1964 237 (237)  READY 10
 171 wq:rate_ctrl                 3919  5.364  1004/ 1596 255 (255)  w:sem  4
 436 log_writer_file              2596  2.598   600/ 1164  60 ( 60)  READY  4
 173 commander                     620  0.754  1528/ 3212 140 (140)  READY  6
 174 commander_low_prio              1  0.000   640/ 2996  50 ( 50)  w:sem  6
 179 mavlink_if0                     3  0.083  1248/ 2572 100 (100)  w:sig  3
 225 gps                           145  0.167  1056/ 1540 208 (208)  w:sem  4
 254 mavlink_if0                  1007  1.173  1632/ 2484 100 (100)  w:sig  4
 255 mavlink_rcv_if0               257  0.251  2576/ 3972 175 (175)  w:sem  4
 279 px4io                        2289  3.185   916/ 1484 240 (240)  READY  4
 413 navigator                     136  0.167   936/ 1764 105 (105)  w:sem  5
 432 logger                       1486  2.011  3000/ 3644 233 (233)  w:sem  4
 442 top                           649  2.849  1560/ 2028 248 (248)  RUN    3
 440 mavlink_if1                  1977  6.621  1824/ 2532 140 (100)  w:sig  4
 441 mavlink_rcv_if1               123  0.335  2576/ 3972 175 (175)  w:sem  4

Processes: 28 total, 10 running, 18 sleeping, max FDs: 20
CPU usage: 62.36% tasks, 2.26% sched, 35.37% idle
DMA Memory: 5120 total, 1536 used 1536 peak
Uptime: 90.219s total, 43.652s idle
nsh> mavlink status

instance #0:
        mavlink chan: #0
        type:           GENERIC LINK OR RADIO
        flow control: ON
        rates:
          tx: 0.334 kB/s
          txerr: 0.000 kB/s
          tx rate mult: 0.402
          tx rate max: 1200 B/s
          rx: 0.000 kB/s
        FTP enabled: YES, TX enabled: YES
        mode: Normal
        MAVLink version: 1
        transport protocol: serial (/dev/ttyS1 @57600)

instance #1:
        GCS heartbeat:  774548 us ago
        mavlink chan: #1
        type:           GENERIC LINK OR RADIO
        flow control: ON
        rates:
          tx: 22.532 kB/s
          txerr: 0.000 kB/s
          tx rate mult: 1.000
          tx rate max: 46080 B/s
          rx: 0.046 kB/s
        FTP enabled: NO, TX enabled: YES
        mode: Config
        MAVLink version: 2
        transport protocol: serial (/dev/ttyS2 @921600)
        ping statistics:
          last: 5.96 ms
          mean: 7.08 ms
          max: 153.57 ms
          min: 3.49 ms
          dropped packets: 0
```
**This PR**
```
baseline: No mavlink start -d /dev/ttyS2 -b 921600 -m config -z
 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
   0 Idle Task                    8677 45.189   208/  512   0 (  0)  READY  3
   1 hpwork                          0  0.000   344/ 1260 249 (249)  w:sig  3
   2 lpwork                         10  0.085   604/ 1516  50 ( 50)  w:sig  8
   3 init                          913  0.000  2032/ 2604 100 (100)  w:sem  3
   4 wq:manager                      0  0.000   368/ 1252 243 (243)  w:sem  4
 161 wq:att_pos_ctrl              1010  7.903  4768/ 6596 244 (244)  READY  4
  17 dataman                        62  0.085   760/ 1204  90 ( 90)  w:sem  4
  20 wq:lp_default                  11  0.085   812/ 1700 205 (205)  w:sem  4
  22 wq:I2C1                        79  0.515   820/ 1396 246 (246)  READY  4
  27 wq:hp_default                 143  1.030  1136/ 1796 243 (243)  READY  4
 121 wq:SPI1                      3675 21.907   984/ 1396 253 (253)  w:sem  4
 137 wq:I2C3                        53  0.343   820/ 1396 244 (244)  READY  4
 139 wq:SPI4                        48  0.343   600/ 1396 250 (250)  w:sem  4
 160 sensors                       369  2.491  1300/ 1964 237 (237)  READY 10
 163 wq:rate_ctrl                  714  4.982  1004/ 1596 255 (255)  w:sem  4
 428 log_writer_file               369  3.350   600/ 1164  60 ( 60)  w:sem  4
 165 commander                     166  0.687  1576/ 3212 140 (140)  READY  6
 166 commander_low_prio              0  0.000   544/ 2996  50 ( 50)  w:sem  6
 171 mavlink_if0                     0  0.000  1376/ 2572 100 (100)  w:sig  3
 216 gps                            24  0.171  1088/ 1540 208 (208)  w:sem  4
 246 mavlink_if0                   319  1.202  1616/ 2484 100 (100)  w:sig  4
 247 mavlink_rcv_if0                66  0.257  2576/ 3972 175 (175)  w:sem  4
 268 px4io                         415  2.835   960/ 1484 240 (240)  READY  4
 402 navigator                      18  0.171   944/ 1764 105 (105)  w:sem  5
 424 logger                        263  1.890  3040/ 3644 233 (233)  w:sem  4
 430 top                           243  2.577  1552/ 2028 248 (248)  RUN    3

Processes: 26 total, 9 running, 17 sleeping, max FDs: 20
CPU usage: 52.92% tasks, 1.89% sched, 45.19% idle
DMA Memory: 5120 total, 1536 used 1536 peak
Uptime: 18.110s total, 8.678s idle
INFO  [ecl/EKF] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)

mavlink start -d /dev/ttyS2 -b 921600 -m config -z

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
   0 Idle Task                   41300 38.860   240/  512   0 (  0)  READY  3
   1 hpwork                          0  0.000   344/ 1260 249 (249)  w:sig  3
   2 lpwork                         57  0.000   604/ 1516  50 ( 50)  w:sig  8
   3 init                          930  0.000  2040/ 2604 100 (100)  w:sem  3
   4 wq:manager                      0  0.000   368/ 1252 243 (243)  w:sem  4
 161 wq:att_pos_ctrl              7206  7.788  4768/ 6596 244 (244)  READY  4
  17 dataman                       104  0.083   760/ 1204  90 ( 90)  w:sem  4
  20 wq:lp_default                  67  0.000   812/ 1700 205 (205)  w:sem  4
  22 wq:I2C1                       470  0.502   820/ 1396 246 (246)  READY  4
  27 wq:hp_default                 924  1.005  1136/ 1796 243 (243)  READY  4
 121 wq:SPI1                     21070 22.110   952/ 1396 253 (253)  w:sem  4
 137 wq:I2C3                       329  0.335   820/ 1396 244 (244)  READY  4
 139 wq:SPI4                       317  0.335   600/ 1396 250 (250)  w:sem  4
 160 sensors                      2339  2.512  1300/ 1964 237 (237)  READY 10
 163 wq:rate_ctrl                 4637  5.025  1004/ 1596 255 (255)  w:sem  4
 428 log_writer_file              2870  2.931   600/ 1164  60 ( 60)  w:sem  4
 165 commander                     739  0.753  1568/ 3212 140 (140)  READY  6
 166 commander_low_prio              1  0.000   576/ 2996  50 ( 50)  w:sem  6
 171 mavlink_if0                     3  0.000  1376/ 2572 100 (100)  w:sig  3
 216 gps                           162  0.167  1088/ 1540 208 (208)  w:sem  4
 246 mavlink_if0                  1166  1.005  1632/ 2484 100 (100)  w:sig  4
 247 mavlink_rcv_if0               301  0.251  2576/ 3972 175 (175)  w:sem  4
 268 px4io                        2734  2.931   916/ 1484 240 (240)  READY  4
 402 navigator                     152  0.167   944/ 1764 105 (105)  w:sem  5
 424 logger                       1701  1.842  2928/ 3644 233 (233)  w:sem  4
 442 top                           338  2.847  1552/ 2028 248 (248)  RUN    3
 432 mavlink_if1                  4798  5.946  1824/ 2532 105 (100)  READY  4
 433 mavlink_rcv_if1               271  0.335  2576/ 3972 175 (175)  w:sem  4

Processes: 28 total, 10 running, 18 sleeping, max FDs: 20
CPU usage: 58.88% tasks, 2.26% sched, 38.86% idle
DMA Memory: 5120 total, 1536 used 1536 peak
Uptime: 97.078s total, 41.300s idle

mavlink status

instance #0:
        mavlink chan: #0
        type:           GENERIC LINK OR RADIO
        flow control: ON
        rates:
          tx: 0.521 kB/s
          txerr: 0.000 kB/s
          tx rate mult: 0.402
          tx rate max: 1200 B/s
          rx: 0.000 kB/s
        FTP enabled: YES, TX enabled: YES
        mode: Normal
        MAVLink version: 1
        transport protocol: serial (/dev/ttyS1 @57600)

instance #1:
        GCS heartbeat:  603743 us ago
        mavlink chan: #1
        type:           GENERIC LINK OR RADIO
        flow control: ON
        rates:
          tx: 22.719 kB/s
          txerr: 0.000 kB/s
          tx rate mult: 1.000
          tx rate max: 46080 B/s
          rx: 0.046 kB/s
        FTP enabled: NO, TX enabled: YES
        mode: Config
        MAVLink version: 2
        transport protocol: serial (/dev/ttyS2 @921600)
        ping statistics:
          last: 147.06 ms
          mean: 112.77 ms
          max: 158.28 ms
          min: 9.53 ms
          dropped packets: 0

```
**A better test case 100% TX channel; utilization (no gaps)**
```
mavlink start -m config -b 921600 -d  /dev/ttyS2
sleep 1
mavlink stop-all

dd if=/dev/urandom of=/dev/ttyS2 bs=4096 count=1000 &
```
**_NO TX DMA_**
```
 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
   0 Idle Task                    4659  0.000   256/  512   0 (  0)  READY  3
   1 hpwork                          0  0.000   344/ 1260 249 (249)  w:sig  3
   2 lpwork                          4  0.000   608/ 1516  50 ( 50)  READY  8
   3 init                          845  0.000  1704/ 2604 100 (100)  w:sem  5
   4 wq:manager                      0  0.000   368/ 1252 243 (243)  w:sem  4
  76 wq:att_pos_ctrl              1197  6.060  4768/ 6596 244 (244)  READY  4
  17 dataman                      1760 13.190   760/ 1204  90 ( 90)  READY  4
  20 wq:lp_default                  14  0.089   812/ 1700 205 (205)  READY  4
  28 wq:hp_default                 197  0.891  1080/ 1796 243 (243)  READY  4
  38 wq:SPI1                      4485 21.033  1000/ 1396 253 (253)  w:sem  4
  51 wq:I2C3                        73  0.356   880/ 1396 244 (244)  READY  4
  53 wq:SPI4                        65  0.356   600/ 1396 250 (250)  w:sem  4
  75 sensors                       456  2.228  1440/ 1964 237 (237)  READY  9
  78 wq:rate_ctrl                  396  1.960   892/ 1596 255 (255)  w:sem  4
 201 log_writer_file              1380  3.386   616/ 1164 255 (255)  w:sem  4
  80 commander                     225  0.713  1552/ 3212 140 (140)  READY  6
  82 commander_low_prio              0  0.000   544/ 2996  50 ( 50)  READY  6
  88 mavlink_if0                     1  0.000  1296/ 2572 100 (100)  w:sig  3
 126 gps                            14  0.089  1056/ 1540 208 (208)  w:sem  4
 214 <pthread>                    4834 36.185   512/ 2044 100 (100)  READY  5
 215 top                           198  2.228  1560/ 2028 248 (248)  RUN    3
 177 navigator                       3  0.000   944/ 1764 105 (105)  w:sem  5
 198 logger                        341  1.515  2880/ 3644 255 (255)  w:sem  4

Processes: 23 total, 12 running, 11 sleeping, max FDs: 20
CPU usage: 90.29% tasks, 9.71% sched, 0.00% idle
DMA Memory: 5120 total, 1536 used 1536 peak
Uptime: 23.051s total, 4.660s idle
```
**_TX DMA_**
```

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
   0 Idle Task                   35498 55.882   208/  512   0 (  0)  READY  3
   1 hpwork                          0  0.000   344/ 1260 249 (249)  w:sig  3
   2 lpwork                         38  0.089   604/ 1516  50 ( 50)  w:sig  8
   3 init                          830  0.000  1704/ 2604 100 (100)  w:sem  5
   4 wq:manager                      0  0.000   384/ 1252 243 (243)  w:sem  4
  76 wq:att_pos_ctrl              3574  5.971  4768/ 6596 244 (244)  READY  4
  17 dataman                        85  0.000   760/ 1204  90 ( 90)  w:sem  4
  20 wq:lp_default                  43  0.089   812/ 1700 205 (205)  READY  4
  28 wq:hp_default                 574  0.980  1200/ 1796 243 (243)  READY  4
  38 wq:SPI1                     12933 21.033   936/ 1396 253 (253)  w:sem  4
  51 wq:I2C3                       211  0.356   820/ 1396 244 (244)  READY  4
  53 wq:SPI4                       200  0.356   600/ 1396 250 (250)  w:sem  4
  75 sensors                      1344  2.228  1300/ 1964 237 (237)  READY  9
  78 wq:rate_ctrl                 1166  1.960   892/ 1596 255 (255)  w:sem  4
 201 log_writer_file              2008  2.762   600/ 1164  60 ( 60)  w:sem  4
  80 commander                     488  0.713  1760/ 3212 140 (140)  READY  6
  82 commander_low_prio              1  0.000   640/ 2996  50 ( 50)  w:sem  6
  88 mavlink_if0                     2  0.000  1224/ 2572 100 (100)  w:sig  3
 126 gps                            43  0.000  1144/ 1540 208 (208)  READY  4
 217 <pthread>                     333  1.871   504/ 2044 100 (100)  w:sem  5
 218 top                           301  2.228  1552/ 2028 248 (248)  RUN    3
 177 navigator                     118  0.178   944/ 1764 105 (105)  w:sem  5
 198 logger                        986  1.604  2928/ 3644 233 (233)  w:sem  4

Processes: 23 total, 9 running, 14 sleeping, max FDs: 20
CPU usage: 42.42% tasks, 1.69% sched, 55.88% idle
DMA Memory: 5120 total, 1536 used 1536 peak
Uptime: 62.732s total, 35.499s idle
```

**Comment by davids5** [comment]
@dagar - the reduction in free heap on PX4IO is not from Nuttx. I suspect DSHOT had increased table sizes.

**Comment by mrpollo** [comment]
@PX4/testflights Please coordinate with @davids5

**Comment by davids5** [comment]
@PX4/testflights  this is perfect rainy weather testing - Load V2, V3, V5,  and make sure you can load all the Air frames with out any issues. 
Keep an eye on the PX4IO leds thay should never do police lights 
(BLUE->ORANGE) - (BLUE->ORANGE) - (BLUE->ORANGE)
connect a debu console and check `px4io status` after every reboot from AF load.

**Comment by dannyfpv** [comment]
pixhawk4 v5 f450
airframe: generic hexarotor coaxial geometry issue
Screen Shot 2019-12-05 at 3 14 51 PM
Screen Shot 2019-12-05 at 3 15 13 PM

**Comment by Junkim3DR** [comment]
### Tested on v3 Firmware | No issue

**Airframe - Esky (Big) Lama v4**
152 bytes free, bellow you can see a screenshot of the message, same procedure has been followed for the rest of the airframes.
image

**Non of the rest Airframes have shown issues but the once in the section bellow.**

**Comment by dagar** [comment]
I'm not sure what happened above, but the Coax airframe (15001) appears to be loading for me, and if it wasn't it wouldn't be related to this PR. We need to add testing that routinely checks all these airframes across all boards.

Let's get this in to enable further testing.

**Pull request merged**
