### PR TITLE
Fix the multi- target targets (#5489)

### PR DESCRIPTION
**Pull request by CarloWood**
On second thought, using % just isn't correct. When a make
target looks like:

foo% bar%:
	...

Then that implies that it will build BOTH foo% and bar% whenever
that rule is triggered (by either) for any value of the pattern %.

Clearly that is not what we want / intend.

So, this commit goes back to using config targets without a % in it
by generating a full list of them.

It also turns sitl_deprecation into a Hidden Target.

Finally, now that we have those target lists anyway, I added
a 'help' and 'list_config_targets' targets that print the
available targets.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by LorenzMeier** [comment]
Can you look into the CI fails? Are the unrelated to this PR and rather triggered by the tests that had been missing before?

**Comment by CarloWood** [comment]
Yes, I already have a resolution, but suddenly had to run to an appointment! Only now just got home.

**Comment by CarloWood** [comment]
This is ready to be merged now. Can it be merged please, since it fixes a bug that I introduced it feels uncomfortable while this isn't merged in yet. ;)

**Comment by CarloWood** [comment]
I did a rebase onto the current master and squashed all commits into one.

**Comment by LorenzMeier** [comment]
Will merge as soon as CI passes.

**Comment by LorenzMeier** [comment]
Thanks!

**Pull request merged**
