### PR TITLE
tap_esc: fix output order for quadrotor

### PR DESCRIPTION
**Pull request by lucasdemarchi**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice, LGTM

**Comment by LorenzMeier** [comment]
@lucasdemarchi Code style fail. You also might want to install the pre-commit hook. See the CI output for instructions to fix.

**Comment by lucasdemarchi** [comment]
I actually saw the coding style file and script. Just assumed it was a bad change from astyle since I had never seen such a weird style in any other project.

**Comment by lucasdemarchi** [comment]
@LorenzMeier fixed

**Pull request merged**
