### PR TITLE
create example vehicle type build configs for fmu-v2 and fmu-v5

### PR DESCRIPTION
**Pull request by dagar**
This PR adds vehicle specific builds for px4_fmu-v2 and px4_fmu-v5. These serve as examples for how to easily create specialized builds and ensures we don't introduce dependencies cross module dependencies preventing it.

### CODE REVIEW

**Comment by dagar** [comment]
Revisit after https://github.com/PX4/Firmware/pull/10964

**Comment by LorenzMeier** [comment]
We also need to consolidate startup scripts, which will contribute to the major saving - is this easily feasible? Otherwise, an example of a single product might make sense. What I'm concerned about is to make sure we are showing that we can work with XY amount of flash, where XY is preferably < 500KB for a multicopter.

**Comment by dagar** [comment]
Yes I've been thinking about that as well. I want to get the airframes and mixers sorted into groups and add simple broad dependencies for inclusion. The core RC scripts will be vehicle and board agnostic.

We can also make it easy to have board specific airframes and mixers for things like the crazyflie, aero, bebop, etc. Little things like this will help keep things small and understandable.

**Comment by hamishwillee** [comment]
Sounds cool, but can we make sure we document all this as soon as it goes in???? 

My concern is stuff like https://github.com/PX4/Firmware/pull/10960#issuecomment-443550374 that just magically appears.

**Comment by dagar** [comment]
TODO: MC + UAVCAN

**Comment by dagar** [comment]
Rebased.

**Pull request merged**
