### PR TITLE
EKF2 always publish status message

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@priseborough Good to go?

**Comment by priseborough** [comment]
These changes as such look OK, but I have two comments:

1) @dagar A miscellaneous set of non-functional code improvements were included. In future can you please put these types of changes into a separate commit.

2) There is no test evidence.

**Comment by priseborough** [comment]
@dagar do you have a log from your testing that you can attach a link to?

**Comment by dagar** [comment]
Only SITL testing so far. Might have a real flight with this by the end of the week.
SITL log: https://logs.px4.io/plot_app?log=023121b6-51b0-42ac-9d24-89021913086b

I can move the vehicle_global_position changes to another PR if there's any issue.

**Comment by priseborough** [comment]
I would prefer a separate PR for changing the global position message.

**Comment by dagar** [comment]
> I would prefer a separate PR for changing the global position message.

Done - https://github.com/PX4/Firmware/pull/8251

**Pull request merged**
