### PR TITLE
FrSky telemetry: add single wire mode

### PR DESCRIPTION
**Pull request by bkueng**
S.Port FrSky telemetry is currently working via:
- Pixracer FrSky port
- [Craft and Theory inverter cable](http://www.craftandtheoryllc.com/store/ct-telemetry-cable-for-frsky-radios/)

However it does not work when using uninverted S.Port (see [here](https://oscarliang.com/uninverted-sbus-smart-port-frsky-receivers/)), and probably also with some other external inverter. To fix this, the UART needs to be put into half-duplex mode.
This PR adds another scanning state to automatically detect that. It allows for example to use telemetry on the Omnibus board without additional chips.

I tested the following configurations:
- S.Port via Pixracer FrSky port
- DType via Pixracer FrSky port
- S.Port via Omnibus on UART6 via [uninverted signal](https://oscarliang.com/uninverted-sbus-smart-port-frsky-receivers/) (connecting both RX & TX)
- S.Port via Pixhawk and an inverter cable on Telem2

In addition this does:
- some code cleanup
- add a scanning timeout of 15 seconds. After that the task exits to free up RAM

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@DanielePettenuzzo this could be helpful

**Comment by bys1123** [comment]
Wow, this is a cool feature, but the doc is not updated, right?
https://docs.px4.io/master/en/peripherals/frsky_telemetry.html

**Comment by hamishwillee** [comment]
Doesn't look like it. @bkueng What would we need to say? Want to take first shot at docs update?

**Comment by bkueng** [comment]
As written above, there's auto-detection, so should be plug-n-play.

**Comment by bys1123** [comment]
@bkueng @hamishwillee but the document still say it need a special cable.

**Comment by hamishwillee** [comment]
> but the document still say it need a special cable.

@bkueng Yes. That was my next question. What cable should you use? We've previously said that you may need a uart to s.port adapter (presumably to invert the signal). We've recommended craft and theory cable. 

image

So my understanding is that people can still use that cable if they want.

But presumably the change here is that you can now use a "single wire cable". How does the wiring between a pixhawk 4 and an S.BUS port on a receiver look? Single wire to me (who knows nothing about hardware) would imply you might have a single wire connecting TX on Pixhawk and RX on the receiver SBUS output. But I bet that isn't the case.

**Comment by bys1123** [comment]
@hamishwillee S.Port is an "inverted" "half-duplex" uart signal for telemetry, only telemetry no RC signal. 
Half-duplex means it use single wire for RX and TX.
Inverted means it's not standard uart signal but inverted, high become low, low become high.
Few years ago, no flight controller support this kind of signal. So it need a special cable makes signal inverted again became uninverted and split RX and TX to two wire.

This PR makes uart on FC support half-duplex mode, but still need uninverted S.Port. Because of nuttx do not support inverted signal yet.
But users could hack the FrSky receivers to get uninverted signal:
https://oscarliang.com/uninverted-sbus-smart-port-frsky-receivers/ 
image
After this PR, connect this uninverted s.port to FC directly with one wire, you will get bidirectional frsky telemetry. No special cable needed.

**Comment by bys1123** [comment]
F.Port is using single wire for RC and telemetry, makes wiring more easier, and save one uart port. It still need developers works to support.
https://discuss.px4.io/t/fmuv5-f-port-frsky-supported/6861

**Comment by hamishwillee** [comment]
@bys1123 Thanks. Also @bkueng Still not _certain_ on this. Let's try some scenarios.

Imagine I have your board here  (or more generally any receiver that can dump out uninverted SBUS) and I want to connect it to a pixhawk 4.

   image

1.  I think I connect a wire (just one) between the pin labeled Uninverted SBUS on this AND the [Pixhawk 4](http://www.holybro.com/manual/Pixhawk4-Pinouts.pdf) pin 2 on the SBUS port.
   image
    - Then I don't need to do anything else - there will be telemetry from the vehicle on my handheld controller? Is that all right?
    - Further, if I have an inverter I could pass my inverted signal through the inverter and then connect to pin 2 on the SBUS port. Is that correct?

2. The diagram also has uninverted SmartPort - can I connect that in the same way?

3. Can I more generally connect to the TX on any UART? I.e. below I have a UART with pin 2 = TX. Can I connect that and setup the serial port using `TEL_FRSKY_CONFIG `?
   image

**Comment by bys1123** [comment]
@hamishwillee Thanks for sharing your understanding.
1. Pixhawk have hardware inverter on sbus, so do not need to use uninverted sbus signal. This uninverted signal is for some racing drone controller.
2. 3. You need to connect s.port to a TX to get telemetry. 
The old documented way were using a convertor cable to split inverted s.port to uninverted TX and RX, so you need to wire like this:
s.port@receiver -----  convertor  ====== Tx.Rx@pixhawk
now:
uninverted s.port -------- Tx @ Pixhawk

**Comment by tiralonghipol** [comment]
@bkueng @bys1123 
I think you can help me, related to this: 
I am trying to connect the Asgard AIO https://www.readytoflyquads.com/flip-32-f4-omnibus-aio-f4
To the Frsky R-XSR https://www.frsky-rc.com/product/r-xsr/

I am using the UART6 port:
FC <------> FrSky
gnd ------gnd
5V ------- 5v
rx6 ------- uninverted sbus

Running Px4 10.1 stable and in qgruondcontrol in the Radio tab I get: "Detected 0 radio channels. To operate ..."

What am I doing wrong?

**Pull request merged**
