### PR TITLE
Make LPE sonar reading more robust.

### PR DESCRIPTION
**Pull request by jgoppert**
This makes LPE optical flow flight outdoors/indoors rock solid. I defaulted the T_Z (terrain noise) param to the outdoors noise level as more users are flying it outdoors now with a comment about values for typical indoor/outdoor settings. Will include flight logs and video below.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice!

**Comment by jgoppert** [comment]
Video:
https://www.youtube.com/watch?v=t7s8027uKZ4

Log:
http://logs.uaventure.com/view/beRXQ3uES9ctPkv2H5ymDQ

In the log you can see the param changes to make the mission takeoff at low altitude and go at a slow velocity so that optical flow isn't lost.

**Comment by jgoppert** [comment]
Note in this log I am in MPC_ALT_MODE =1 , so that the terrain alittude is being regulated instead of the local z altitude

**Comment by mhkabir** [comment]
Why that jump when switching to auto?

**Comment by jgoppert** [comment]
## Altitude spike at start of mission

@mhkabir Not sure why the climb happens, I think it is related to the takeoff command, the z setpoint is not showing it, even though the climb does appear in agl, this is in MPC_ALT_MODE = 1 so the controller is tracking AGL.

```python
pl.figure(figsize=(15,5))
(data.EST0_s7 - data.EST0_s2).plot(label='AGL, m')
(-1*data.LPSP_Z).plot()
data.STAT_MainState.plot()
pl.grid()
pl.legend(loc='best')
```

image

## Flow ground truth vs. GPS

The flow looks very accurate. The only issue is a slight offset due to the start point initialization due to manual error on my part on setting the LPE_LAT/ LPE_LON parameters that it uses to initialize the global position when using flow alone.

```python
data = px4tools.project_lat_lon(px4tools.process_data(pandas.read_csv('lpe_sonar.csv')))
data_auto = data[data.STAT_MainState == 3]
pl.figure(figsize=(8, 10))
px4tools.pos_analysis(data_auto);
pl.axis('equal');
```

image

**Comment by jgoppert** [comment]
@LorenzMeier OK with merging?  just LPE changes.

**Comment by LorenzMeier** [comment]
Sure, please go ahead once it passes (but merging on the console, not with a merge commit). What is the testing state now with LPE? Did we resolve everything we found?

**Comment by dagar** [comment]
FYI the newish github squash + merge option in the web interface works quite well when you're happy squashing a pull request into a single commit. There's no merge commit and it puts a nice reference to the PR in the title which is very helpful when browsing history.

**Comment by jgoppert** [comment]
@dagar thanks, works well

**Comment by M9303105** [comment]
Hi jpoppert 
 I download firmware from https://github.com/jgoppert/Firmware.git and compile code then upload to my pixhawk. When I connect pixhawk to QGC, I can't find MPC_ALT_MODE = 1 in the parameter lists. Also, there has nothing in airframe page. Did I do anything wrong? Look forward to your reply. thanks!

**Comment by mhkabir** [comment]
Flash master please @M9303105

**Comment by M9303105** [comment]
mhkabir
   Thanks for your quickly reply.
   I flashed master and connect to QGC again, all of the parameters what I needed are showing up, but the QGC v2.9.7b tell me "The version of GroundControl can only perform vehicle setup on a newer version of firmware. Please perform a Firmware Upgrade if you wish to use Vehicle Setup". Should I downgrade the version of QGC? Thanks!

**Comment by mhkabir** [comment]
Update QGC to the latest daily. That message seems wrong.

**Comment by M9303105** [comment]
Hi mhkabir
  QGC v2.9.7b is the latest version.
  I can't setup vehicle in this version of QGC.

**Comment by M9303105** [comment]
Hi mhkabir

   QGC v2.9.4 can be used. Thanks!!

**Comment by mhkabir** [comment]
I'm pretty sure that you didn't flash PX4/Firmware master, in that case.

**Comment by M9303105** [comment]
Hi mhkabir
     Thanks! 
     My drone flies very well indoor now!

**Pull request merged**
