### PR TITLE
Update default parameters

### LINKED ISSUE #12361: List of default params that need an update
This is to track parameters which have a default that does not work well on practice or leads to inferior performance on pretty much every airframe.

Parameter name | default | suggested
------------------- | --------- | -------------
MPC_Z_VEL_I | 0.02 | 0.1 
MPC_ACC_DOWN_MAX | 10.0 | 3.0
MPC_ACC_UP_MAX | 10.0 | 4.0
SYS_FORCE_F7DC | 0 | 2
MPC_POS_MODE | 1 | 3
MPC_ACC_HOR | 5 | 3
MPC_ACC_HOR_MAX | 10 | 5
FW_RR_I | 0.01 | 0.1
FW_PR_I | 0.01 | 0.1
FW_YR_I | 0.01 | 0.1
MPC_Z_MAN_EXPO | 0 | 0.6
MPC_XY_MAN_EXPO | 0 | 0.6
MPC_YAW_EXPO | 0 | 0.6
MPC_MAN_Y_MAX | 200 | 150

### PR DESCRIPTION
**Pull request by RomanBapst**
See  #12361  for context.

Also see individual commit message for some explanations.

fixes #12361

### CODE REVIEW

**Comment by Stifael** [comment]
Just one comment to think about:
Given the fact that each of the tuning parameters is very specific to the type of vehicle, I was wondering if it would not make more sense to use MPC_POS_MODE=0 as the default where all the higher-level tuning parameters (MPC_ACC_HOR, MPC_ACC_UP_MAX...) have no effect. This way the user will directly experience how well the more important PID tuning parameters are set and will not be misled by the higher-level tuning.

**Comment by bresch** [comment]
@Stifael I agree that in an ideal world this would be correct, but most likely the reaction of the user will be: "Oh, it feels jerky (we here that a lot), the firmware is bad". We want to make sure that the user experience is good the first time. The experienced user knows what to do and the user that has a first good experience might take time to further tune the vehicle.

**Comment by Stifael** [comment]
> @Stifael I agree that in an ideal world this would be correct

But that is exactly my point. I think in an ideal world you can find default parameter that makes sense, but in reality, it is pretty much impossible to find values where the user will have out-of-the-box good experience. How did you guys come up with MPC_ACC_HOR = 3 vs 10? Is there a reference platform that a new user can refer to?

**Comment by bresch** [comment]
@Stifael Those parameters used to design the trajectories are good for a drone up to ~25kg with average thrust/weight ratio (~2:1). It might feel "too smooth" for a small drone, but we rarely heard someone complaining that the drone flies too smoothly. Why manual and auto accelerations of 5 and 3m/s2, simply because this limits the demanded tilt to about 30 and 20 degrees, respectively. 10m/s2 generates a tilt of ~45 degrees and the maximum tilt `MPC_TILTMAX_AIR` is 45 degrees; you don't leave any space for the controller. 
We could have chosen 4, 6 or something else; it's king of arbitrary, but this gives a good feeling with a wide variety of platforms. We tested those values on F450, F550, QAV-250, BabyShark, Tarot 960. Would you prefer an other value?

**Comment by Stifael** [comment]
> Would you prefer an other value?

No, I don't have a strong opinion, Just know that 3 is quite low and that it is not only weight dependent. I personally can't really contribute much here anyway.

**Comment by bresch** [comment]
@PX4/testflights Can you please test those parameters on several vehicles please? (not necessarily different autopilots, just different drones)

**Comment by jorge789** [comment]
### Tested on PixRacer V4:
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
**The vehicle on the flight showed a little slower (smooth)**
No issues noted, good flight in general.

**Logs**

https://review.px4.io/plot_app?log=7c30a7fe-b46c-4e5c-b942-daf341d21799

https://review.px4.io/plot_app?log=5267c015-5f01-4ecc-bcee-d5c0e5e768d9


### Tested on Pixhawk 2 Cube V3:
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
**The vehicle on the flight showed a little slower (smooth)**
No issues noted, good flight in general.

**Logs**
https://review.px4.io/plot_app?log=8e5c002a-d0b7-4e8d-9b49-335f158a1795

https://review.px4.io/plot_app?log=ba59d64e-20cb-4876-b505-0863acdaffb1

**Pull request merged**
