### PR TITLE
Aero: Increase rate through internal link.

### PR DESCRIPTION
**Pull request by LorenzMeier**
@ChristophTobler @lucasdemarchi This needs validation to make sure we're not starting to loose packets like crazy.

### CODE REVIEW

**Comment by ChristophTobler** [comment]
I guess it should be https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rcS#L710 since we use a baudrate of 460800, right?

**Comment by zehortigoza** [comment]
Running it for 30 secconds with datarte of 25000:
master 25000 datarate logs png
```
Endpoint UART [7] {
        Received messages {
                CRC error: 250 2% 64KBytes
                Sequence lost: 4959 51%
                Handled: 4363 447KBytes
                Total: 9572
        }
        Transmitted messages {
                Total: 249 5KBytes
        }
}
```

Same test but with datarate of 5000:
master clean logs
```
Endpoint UART [7] {
        Received messages {
                CRC error: 1 0% 0KBytes
                Sequence lost: 22 1%
                Handled: 1833 191KBytes
                Total: 1856
        }
        Transmitted messages {
                Total: 242 3KBytes
        }
}
```
It improves the frequency of most messages but also lost way more messages.

**Comment by TSC21** [comment]
Doesn't #7885 supersedes this?

**Comment by ChristophTobler** [comment]
@TSC21 It does. Thanks!

**Pull request closed without merging**
