### PR TITLE
Graph-based Return-To-Land

### PR DESCRIPTION
**Pull request by samuelsadok**
The Return-To-Land mode now makes the vehicle return along the previously flown path. This way, crashes due to tall buildings can be avoided. The new RTL is based on a flight path tracker, which records the flight path as a graph.

The implementation was tested in unit tests (on PX4-FMUv4) and SITL, but no flight tests have been made yet. Some test paths in src/modules/navigator/navigator_tests are quite verbose, maybe I should remove them?

Memory and CPU usage depends heavily on the flight pattern. A 2-4kB bound should be sufficient for most cases. During tests, the most critical algorithm blocked the navigator for 300ms. This should not be an issue if the system behaves as designed, but we still may want to run this on a separate low-priority task instead.

The new RTL mode is now called RTLA while the old mode was renamed to RTLB and is used as a fallback for some failure modes. Also, a new RCRecover mode enables the vehicle to just return a few meters to regain a good signal. Someone with more experience with the system could integrate this such that it is invoked when needed. Changes to QGroundControl may be required to understand the new flight modes.

### CODE REVIEW

**Comment by dagar** [comment]
Awesome! I'm looking forward to this. 

For usage and QGC integration I think the question is if we want to make both basic and advanced RTL accessible as separate modes, or select with a param. Does the tracker always run?

I'll do a review and some FW testing this week.

**Comment by dagar** [comment]
@samuelsadok could you take a look at the CI failures? Would you be able to get rid of the merge commits? We generally rebase on master to merge and keep the history linear.

**Comment by samuelsadok** [comment]
@dagar the tracker runs event driven on every local position update in the navigator main loop. A position update is rejected if its close to the last recorded position, hence you could say that it runs every 1-2 meters. Usually, such an update is negligible, but in the worst case, the buffer becomes full and the entire graph is rewritten (such that only the shortest path to home is retained), which can take a few hundred milliseconds on a 2kB buffer. There is currently no parameter to disable the tracker, if that was your question.

IMO it makes sense to still be able to select the basic RTL mode at runtime, for cases where the user thinks that it's safe. The graph based RTL may in some cases make a large detour, which could be bad in a low battery scenario.

However, understanding two different RTL modes is an additional burden for the user, so a parameter and/or some heuristic may be a viable alternative.

I will look at the failures and try to rebase.

**Comment by dagar** [comment]
> A position update is rejected if its close to the last recorded position

What about rejecting if the update is collinear (+/- a few meters) with the previous two? That could vastly simplify most real world fixed wing missions.

If possible I think we should get this merged once we're satisfied it seems to work and definitely doesn't break any existing functionality. Then it could be off by default, but users could start opting in for testing. This would be much better than letting it bitrot for another 4 months.

**Comment by samuelsadok** [comment]
> What about rejecting if the update is collinear (+/- a few meters) with the previous two? That could vastly simplify most real world fixed wing missions.

I'm not convinced that it is actually necessary, given that adding a position is very cheap in the general case. The expensive stuff is only invoked once in a while (thus the unpredictability). For instance, after 64 new positions, a consolidation pass is invoked, which does things like detecting lines and removing redundant positions.

> If possible I think we should get this merged once we're satisfied it seems to work and definitely doesn't break any existing functionality. Then it could be off by default, but users could start opting in for testing. This would be much better than letting it bitrot for another 4 months.

Yes I agree. In that case, we should make sure that the tracker is truly disabled to make sure that the expensive algorithms don't interfere with anything.

Meanwhile I have done a rebase on a new branch. I think I have to open yet another pull request, since rewriting the history of public branches is said to be a bad thing.

**Comment by dagar** [comment]
> Meanwhile I have done a rebase on a new branch. I think I have to open yet another pull request, since rewriting the history of public branches is said to be a bad thing.

For work in progress branches in your own fork feel free to rewrite and force push if you'd like. Rewriting shared branches is usually where it gets painful.

**Comment by samuelsadok** [comment]
I did the rebase locally on a new branch and I didn't manage to replace the branch of this pull request with my rebased branch. So I just opened a new one here: #5745, sorry for the noise.

**Pull request closed without merging**
