### PR TITLE
multi differential pressure sensor publication and logging

### PR DESCRIPTION
**Pull request by dagar**
This enables publication and logging of multiple differential pressure sensors. Only the primary is used for airspeed and calibration, but that will be the next step. For now this is useful for testing.

Partially cherry-picked from https://github.com/PX4/Firmware/pull/7702.

### CODE REVIEW

**Comment by Antiheavy** [comment]
We flew the double pitot-static set-up recently.  2 flights:  one with SP3x as primary, one with ms4525 as primary, data from both sensors logged using this PR.  Logs below:

SP3x as primary, reading incorrect airspeed resulting in flying too fast and degraded control, the dynamic model for this sensor may need tweaking for different pitot-static installations.
https://review.px4.io/plot_app?log=c0ed0754-c063-402e-a0b2-e34b74bb2164

ms4525 as primary, typical flight speeds and controller performance.
https://review.px4.io/plot_app?log=f0bc836e-84a9-4d70-95be-15c5f29c1095
image
image

**Comment by dagar** [comment]
Good to merge?

**Comment by Antiheavy** [comment]
No objections here.

**Comment by LorenzMeier** [comment]
Isn't this conflicting with the original SDP3x PR which also adds device ID?

**Comment by dagar** [comment]
Yes. Most of it will rebase cleanly, but drv_sensor.h was missing the eagle tree sensor.
Or you can merge #7702 first and I'll rebase here.

**Comment by LorenzMeier** [comment]
Thanks!

**Pull request merged**
