### PR TITLE
Rename src/drivers/adc to src/drivers/adc/arch_adc

### PR DESCRIPTION
**Pull request by SalimTerryLi**
**Describe problem solved by this pull request**
Rename src/drivers/adc to src/drivers/adc/arch_adc

#14437

### CODE REVIEW

**Comment by bys1123** [comment]
@davids5 @dagar

**Comment by davids5** [comment]
@SalimTerryLi Where is the name an issue?  Would calling something new offboard_adc solve the same isuue?

**Comment by SalimTerryLi** [comment]
> 
> 
> @SalimTerryLi Where is the name an issue? Would calling something new offboard_adc solve the same isuue?

Ohh... Maybe "on-chip" sounds better...
Currently I'm preparing my new hardware-design and, will resume working on software side in a week...

**Comment by SalimTerryLi** [comment]
@dagar Here

**Comment by dagar** [comment]
Not that I like debating naming, but I don't think `arch_adc` is quite right because it's very specifically not the architecture specific part of the ADC.

How about something like `board_adc`?

**Comment by SalimTerryLi** [comment]
> Not that I like debating naming, but I don't think `arch_adc` is quite right because it's very specifically not the architecture specific part of the ADC.
> 
> How about something like `board_adc`?

Done.

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
Thanks @SalimTerryLi, I appreciate your persistence.

**Pull request merged**
