### PR TITLE
Reactivate OA/SL in CI

### PR DESCRIPTION
**Pull request by mrivi**

### CODE REVIEW

**Comment by TSC21** [comment]
@mrivi https://github.com/mavlink/mavros/blob/master/mavros/launch/px4_config.yaml#L63

**Comment by TSC21** [comment]
In https://github.com/PX4/avoidance/blob/master/avoidance/resource/px4_config.yaml you still have that issue.

**Comment by mrivi** [comment]
yes, I know the pyYaml problem. I did the fix on mavros

**Comment by TSC21** [comment]
> yes, I know the pyYaml problem. I did the fix on mavros

Right :D

**Comment by TSC21** [comment]
@mrivi you need to change the branch to master: http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-13113/5/pipeline/69#step-202-log-4

**Comment by TSC21** [comment]
So, all good with safe landing. Now, just need to check the issue with the lidar model so to fix the avoidance test.

**Comment by mrivi** [comment]
I think the only piece missing is a new avoidance release. We need it because:
- in the Firmware CI we were using the mavros/launch/px4_config.yaml that with the container update and consequent mavros update yields two separate trees
- the px4_config.yaml in avoidance release 0.3.0 is not updated to use directly radians but the tag `!degree` which doesn't load anymore due to the pyYaml update

FYI @jkflying

**Comment by TSC21** [comment]
@mrivi what about cherry-picking the required changes from master to 0.3.0 release for now?

**Comment by mrivi** [comment]
@TSC21 this is good to merge

**Pull request merged**
