### PR TITLE
RM3100 - continued

### PR DESCRIPTION
**Pull request by klopezal**
This is a continuation of #9818 for the RM3100 magnetometer driver. A few items to discuss : 
- as there is no WHO_AM_I register, driver initialization depends on REVID, so far only tested on 1 breakout board
- the RM3100 sensor provides raw magnetic data as signed 24-bit values, those are stored in 32-bit variables and "artificially" converted to int32_t, is there a cleaner way to do that?
- the ORB struct `sensor_mag_s` only stores raw values as 16-bit integers, is it worth enlarging definition to 32 bits?
- `check_calibration()`, `check_offset()` and `check_scale()` functions have been removed as they will be replaced by an ORB-based mechanism (as of #10126)
- the driver has been succesfully tested on SPI (external SPI on Pixhawk 3 Pro), no I2C available on the breakout board

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice!

**Comment by dagar** [comment]
@ryanjAA FYI

**Comment by dagar** [comment]
As long as this fails and exits cleanly when the RM3100 isn't present it should be safe to merge immediately. That would get it into more hands for testing and adding i2c support.

**Comment by ryanjAA** [comment]
@dagar Thanks. @klopezal great work. We have a few here with i2c wired up so I’ll take a look. I’ve been absent/traveling for the past month so hopefully we can get back into this. Have you done any side by side testing yet?

**Comment by ryanjAA** [comment]
I did a prelim pass. Couldn’t get the driver to start on i2c. Doesn’t find it on the bus. Took a look through the changes and you have the i2c address as 07. Changed it to 20 (have a basic driver working and address set at 20 via hardware so that part is correct on the hardware end although is can be anything from 20-23 with some pin wiring). Wondering about RM3100_REVID and why it’s set st 22. That would be the first thing since it’s all probably correct. Just can’t get it to find it on the i2c ext bus.

**Comment by ryanjAA** [comment]
Scratch the REVID - manually read the regid reg via sending 0xB6 and got 22 back so that makes sense. Then the issue is somewhere else lurking.

**Comment by klopezal** [comment]
@ryanjAA I updated the I2C address and changed logic for I2C read operations, do you see any difference?

**Comment by ryanjAA** [comment]
Nope, no dice. I put an i2c sniffer on there while it was going on and when starting the driver (on fmuv3 and v2) I get the following i2c:


[0x40+0xB6+][0x41+0x00-[][0x40+][0x41+0x01+] when issuing start
[0x40+][0x41+0x01+] 		When issuing -X Start

Now hex of 40 is just 8 bit of 20+ 1 more 0 for write and b6 should return x22. so somewhere around here.

Now when i load up the old driver that would initialize and poll some data before dying it would kick out:

0x40+0x0A-0x41+ 

Somewhere in the start/init is my guess as to the issue.

**Comment by ryanjAA** [comment]
I wanted to look at your spi implementation and it wouldn’t work. I then realized there is no inclusion on any board config but fmu_v4 so that made sense why. Added one over to the v2/3 and that got the driver running but still not recognizing data (only spent a few minutes on it and the v2/3 have different spi bus conventions than v4) so understandably it will need a little more work since the defines on the board config will need altered so as to no be double defined and fail the build.  I’m wondering if there is something related on the i2c side although I haven combed through it, i dont however see a reason why the board config would need altering on the i2c side. But, as of know incremental progress.

**Comment by LorenzMeier** [comment]
@klopezal Could you please share a photo and a wire diagram of your test setup that is working for you?

**Comment by ryanjAA** [comment]
@lorenz Depending on @klopezal s setup and which eval board using, the wiring on the board itself is more important than usual since you need to tie the analog and digital sides together (or at least power them for correct voltage sources) as well ensure the chip is held in spi or i2c mode which is done (board dependent) by tieing it to gnd or vcc. Also, since it’s all only 3.3v compliant, unless using a custom pcb, caution is needed on testing the vcc side. So far need to add and get working the spi implmentetion on the board config for fmuv2 and v5 for testing since carrying the v4 implention over isn’t a straight copy given bus numbers etc etc etc. but we have spi and i2c variants of the sensor on hand as stand alone sensors so once past this will get them airborne. Still suspect there is something incorrect on the i2c driver init side though.

**Comment by dagar** [comment]
I went over this again and it looks safe to merge (even with i2c not yet functional). Let's get it in and then look at adding proper i2c support.

Nice work @klopezal!

**Pull request merged**
