### PR TITLE
sitl_gazebo: update submodule

### PR DESCRIPTION
**Pull request by julianoes**
This fixes the build for Gazebo 9, and seems to contain a few other changes.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by TSC21** [comment]
Something's failing on the tests. I see some symbolic links problems. I will take a look what is hapenning later today.

**Comment by dagar** [comment]
Something to do with the PX4/sitl_gazebo packaging?
@lamping7

**Comment by lamping7** [comment]
I'm seeing undefined symbols. Ex:
- _ZN8mav_msgs4msgs10MotorSpeedC1Ev
- _ZN11sensor_msgs4msgs3ImuC1Ev

```
gzserver: symbol lookup error: /tmp/jenkins/workspace/Firmware_update-sitl_gazebo-DPJBPZRY5GGEC4FCTENIA4RQDLFDKBIN2WPQ6JRRKCGM5TORLXQQ/px4-posix_sitl_default-v1.8.0-beta2-52-g8a3e81a/px4/test/../build/posix_sitl_default/build_gazebo/libgazebo_multirotor_base_plugin.so: undefined symbol: _ZN8mav_msgs4msgs10MotorSpeedC1Ev
```

**Comment by TSC21** [comment]
Fix here: https://github.com/PX4/sitl_gazebo/pull/213. Made a mistake with the lib linkage. All working now (tested with `make posix_sitl_default gazebo`). I didn't catch this before because I was testing the Cmake and catkin build system isolated from the PX4 framework. @julianoes @LorenzMeier please take a look and merge so this PR can be updated with the new git tag.

**Comment by LorenzMeier** [comment]
Good to update from current head and then merge. Also brought other PRs

**Comment by TSC21** [comment]
@julianoes can you please update `sitl_gazebo` to the current head on this PR?

**Comment by LorenzMeier** [comment]
Superseded in master.

**Comment by lamping7** [comment]
In my mind this shows the need to decouple the stil_gazebo module from the firmware repo. Clear versioning of sitl_gazebo will allow for definitive support of the external dependencies that have little to do with the firmware.

**Comment by LorenzMeier** [comment]
I don't see how that applies. The interfaces and models in the Gazebo repo are not linked to flight code, but they are closely linked to the API versioning. You can't really mix & match them. So we need versioning and the submodule is a lot more lightweight than starting to version API and models.

**Pull request closed without merging**
