### PR TITLE
drivers/px4io move to uORB::Subscription

### PR DESCRIPTION
**Pull request by dagar**
This should be tested on boards with a px4io (pixhawk, pixhawk 3 pro, pixhawk 4).

### CODE REVIEW

**Comment by Junkim3DR** [comment]
### Tested on Pixhawk 4 mini v5

**Modes Tested**
- Position Mode: Good.
- Altitude Mode: Good.
- Stabilized Mode: Good.
- Mission Plan Mode (Automated): Good.
- RTL: Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Logs:**
_PR 12222_
- https://review.px4.io/plot_app?log=4d1c9f38-60e5-4166-a5c0-f8f1229e9ab8

_Master_
- https://review.px4.io/plot_app?log=b014c23c-c92a-45fd-8bc7-062bac5d909e

**Comment by dannyfpv** [comment]
Tested on Pixhawk 4 V5
Modes Tested

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

- Procedure
Arm and Take off in stabilized mode, position mode, altitude, and mission mode

Notes:
No issues noted, good flight in general.


pr Log:

https://review.px4.io/plot_app?log=23a388a1-6012-4766-9d2c-060e82a3b26d


master log:

https://review.px4.io/plot_app?log=71a5aa74-1e6e-4c9c-ae20-2baff55f3daf

**Comment by dagar** [comment]
> What's the reason that `_t_actuator_controls_0` is not included?

It's the single subscription used for polling.

**Comment by jorge789** [comment]
### Tested on PixRacer V4
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.
**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Logs:**
https://review.px4.io/plot_app?log=ed875697-5ab3-4076-9be3-eed30fd44085

**Log**
https://review.px4.io/plot_app?log=bd3bb4eb-33eb-4d42-a695-c3bb1e3949d9
**Note:**
**Vehicle was unable to get position mode, satellites were not enough. 

Loaded master to see if issue persists but this was not the case, vehicle was ready to fly in position in less than 30 seconds.**

**Pull request merged**
