### PR TITLE
sensors: keep legacy params active (BAT_V_DIV/BAT_A_PER_V) for QGC SITL

### PR DESCRIPTION
**Pull request by dagar**
- fixes https://github.com/PX4/Firmware/issues/15505

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
What are the new parameter names that QGC should be using?

**Comment by dagar** [comment]
> What are the new parameter names that QGC should be using?

@DonLakeFlyer 

Per analog power module
  - BAT**x**_V_DIV
  - BAT**x**_A_PER_V
  - BAT**x**_V_CHANNEL (not really relevant for a board like a pixhawk 4, but there are boards where it's configurable)
  - BAT**x**_I_CHANNEL

For compatibility there's simple migration code in place for syncing with `BAT_V_DIV` and `BAT_A_PER_V`, but it would be great to get rid of them entirely.

Do we need some mechanism for QGC to detect the number of possible power bricks? It's variable per board. I'm also not sure why the indexing here starts at 1 (BAT1, BAT2, etc) rather than 0 like calibration (CAL_ACC0_ID).

Ideally a board that physically doesn't have this type of analog power monitoring wouldn't even have these parameters (and corresponding code), but I know how problematic that has been from the QGC perspective. Let's figure out a proper solution.

**Comment by DonLakeFlyer** [comment]
OK, great thanks. I'll switch over to that if it exists. You'll need to support the old naming until a new stable goes out which is who know when at this point.

> Do we need some mechanism for QGC to detect the number of possible power bricks?

If I can assume the numbering is always consecutive 1, 2, 3 then I can figure that out myself.

**Comment by hamishwillee** [comment]
> If I can assume the numbering is always consecutive 1, 2, 3 then I can figure that out myself.

Right now you can, because PX4 only supports two batteries. The docs assume that pattern. All params listed here: https://docs.px4.io/master/en/advanced_config/parameter_reference.html#battery-calibration

**Pull request merged**
