### PR TITLE
Hex/Proficnc Cube Orange Change console to UART7

### PR DESCRIPTION
**Pull request by mirkix**
Hex/Proficnc Cube Orange Change console to UART7 which is the default console UART

### CODE REVIEW

**Comment by dagar** [comment]
I believe this was done to work around ads-b the the (default?) orange carrier board. 

One idea would be to turn that into a generic serial port (TELEM) in the default build and separately have a console config (that I'd use on the hardware test rack).

**Comment by mirkix** [comment]
@dagar You are right, then we can close the PR.

**Comment by JacobCrabill** [comment]
Just an FYI, the change back to CONS / UART7 was included in one of my PRs recently, since I do all my testing on non-ADSB carrier boards..

**Comment by dakejahl** [comment]
Since it sounds like I'm the only one with the ADSB carrier board let's just leave it and I'll change it locally when I need to

**Comment by dagar** [comment]
> Since it sounds like I'm the only one with the ADSB carrier board let's just leave it and I'll change it locally when I need to

I believe it's default now?

If things are working reasonably well it might be time to split the build and reclaim the port. I'll open a PR.

**Pull request closed without merging**
