### PR TITLE
update sitl_gazebo to used flow with limited ouput rate

### PR DESCRIPTION
**Pull request by ChristophTobler**
@jgoppert @svpcom could you give this a try?

This uses the newer flow version where the output rate is set to 20Hz (can be changed). Hence, it works with the hard coded limits of the ekf2. We will have to find a solution with @priseborough to use a variable and a solution so that it can automatically takeoff in flow setup (currently ```commander takeoff``` does not work).

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@dagar Is coveralls still an issue?

screen shot 2017-01-13 at 13 33 33

**Comment by dagar** [comment]
@LorenzMeier it's the mixer test that's failing intermittently with or without coverage on.
https://github.com/PX4/Firmware/issues/6281

**Comment by jgoppert** [comment]
@ChristophTobler @priseborough This is how LwPE does auto takeoff with flow: https://github.com/PX4/Firmware/blob/master/src/modules/local_position_estimator/sensors/land.cpp It creates a fake landed measurement  
https://github.com/PX4/Firmware/blob/master/src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp#L307

@ChristophTobler It might be nice if flow accumulated in sim at a higher rate than the publishing rate  like the actual px4flow driver does.

**Comment by ChristophTobler** [comment]
@jgoppert it is actually accumulating at a higher rate (100Hz) like the the px4flow driver. Both versions are

**Comment by svpcom** [comment]
@ChristophTobler  I've tested it. It works but before first focus lost. See https://github.com/PX4/Firmware/issues/6282#issuecomment-272521001

**Pull request merged**
