### PR TITLE
Pr bebop thrust

### PR DESCRIPTION
**Pull request by tumbili**
Maps scaled thrust values to desired motor speed values.

### CODE REVIEW

**Comment by tumbili** [comment]
@ChristophTobler If you are testing with the bebop this would be a good idea to test. I already gave this testing on my side and it flew very nice.
Generally it would be cool if you could give the Bebop and outdoor test.
One thing that we should be sure it works is the failsafe after loss of manual control because we don't have RC. If qgroundcontrol crashes during flight the failsafe should work.

**Comment by ChristophTobler** [comment]
@tumbili Ok. I'll give it a try (see if I can borrow someones notebook). With the parameters you've sent me? So I should be able to close QGC during a flight and then it should return?

**Comment by ChristophTobler** [comment]
@tumbili @MaEtUgR and I tested the PR. 
We tried position hold (probable position controller needs tuning): 
http://logs.px4.io/plot_app?log=62f27d45-af03-497d-b67e-1f43c8bc382a
and auto takeoff:
http://logs.px4.io/plot_app?log=6be85769-1261-4f88-aeb5-28763d5464a2
the auto takeoff completely failed and I think it tried to kill us;) It went up a bit (half a meter) and then went to the side really fast.

**Comment by tumbili** [comment]
@ChristophTobler You will have to rebase on master because there was another PR which got merged which proposed better tuning gains. I'll give it a try tomorrow on master as well.

**Comment by LorenzMeier** [comment]
@tumbili Can you rebase and re-test?

**Comment by tumbili** [comment]
@LorenzMeier This is good to go as soon as https://github.com/PX4/DriverFramework/pull/169
gets merged which is also ready to go. Just gave it a quick test.

**Comment by LorenzMeier** [comment]
Can you update the Driverframework submodule? I just applied that change.

**Comment by LorenzMeier** [comment]
Rebased on master.

**Pull request merged**
