### PR TITLE
Update cmake/cmake_hexagon

### PR DESCRIPTION
**Pull request by kartikmohta**
New updates required to use the Hexagon SDK v3.0 from Qualcomm

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by LorenzMeier** [comment]
@julianoes Can you cross test?

**Comment by julianoes** [comment]
I came to the same conclusion: #4732 :smile:

**Comment by julianoes** [comment]
Rebased and applied, thanks.

**Pull request closed without merging**
