### PR TITLE
follow target filter updates

### PR DESCRIPTION
**Pull request by catch-twenty-two**
Testing completed 

This adds configurable offset, side to track from and height to follow at parameters. It also adds dynamic low pass filtering for the gps position being received along with yaw smoothing and more safety and error checking to the module.

### CODE REVIEW

**Comment by tumbili** [comment]
@catch-twenty-two Could you fix travis please?
This is the message:
´´´
../src/modules/navigator/follow_target.cpp:102:80: error: comparison is always false due to limited range of data type
´´´

**Comment by catch-twenty-two** [comment]
> @catch-twenty-two Could you fix travis please?
will do

**Comment by catch-twenty-two** [comment]
Hey @tumbili now it's failing on a mixer unit test:

https://travis-ci.org/PX4/Firmware/jobs/122620030#L2116

Any idea why?

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by catch-twenty-two** [comment]
@LorenzMeier @tumbili This has been tested and is ready to be merged

**Comment by LorenzMeier** [comment]
Thanks, merged!

**Pull request merged**
