### PR TITLE
Standard vtol sitl

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by tumbili** [comment]
Usage:
```
make posix_sitl_default gazebo_standard_vtol
```

**Comment by tumbili** [comment]
vtol_sketch

**Comment by SimonWilks** [comment]
Lri = 220mm
Lrs = 280
Le = 620
Lrd = 620

Bri = 270
Bwi = 350

He = 50
Hrd = 120
Hri = 100

Wing dimensions approx.: 136mm x 23mm
Horizontal stab.: 360mm x 22m
Vertical stab.: 20mm x 18mm

Weight:
Plan: 1.6kg
4s 4500mah LiPo: 400g

**Comment by tumbili** [comment]
@SimonWilks Thanks!

**Comment by LorenzMeier** [comment]
Rebased and applied!

**Pull request closed without merging**
