### PR TITLE
more px4fmu-v1 cleanup

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by Avysuarez** [comment]
flight with pixhawk 1 V2; good flight

https://review.px4.io/plot_app?log=d1d5640c-2cfe-4505-91c3-710f3b85edf8

**Comment by Avysuarez** [comment]
flight with pixhawk pro V4pro; Good flight 
https://review.px4.io/plot_app?log=0f62d022-dd6c-469b-b64b-9addfcdc8dbe

**Comment by santiago3dr** [comment]
flight with pixracer (V4)
https://logs.px4.io/plot_app?log=fd468bff-9f09-4301-805c-88658d6d87f9

good flight; nice tracking; good hold; proper RTL
note there was no I/O problem with master with this board

**Comment by Avysuarez** [comment]
flight with pixhawk mini V3, good flight;
https://review.px4.io/plot_app?log=67a71d0b-6645-44b5-b7d4-79f82c50ebfa

**Pull request merged**
