### PR TITLE
Improve trigger control for survey applications

### PR DESCRIPTION
**Pull request by LorenzMeier**
QGC enables the trigger now on entering and exiting each transect without impacting the flight controller. 

screen shot 2017-08-06 at 14 01 54

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@dagar @Antiheavy FYI

**Comment by LorenzMeier** [comment]
screen shot 2017-08-06 at 18 10 39
screen shot 2017-08-06 at 18 09 35

**Comment by LorenzMeier** [comment]
The triggering now guarantees that there is a shot at the edge of the polygon:

screen shot 2017-08-06 at 18 13 29

**Comment by Antiheavy** [comment]
Cool.  We'd be interested in testing this on fixed wing survey flights.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Any reason to not merge?

**Comment by dogmaphobic** [comment]
> @DonLakeFlyer Any reason to not merge?

You won't get an answer to this for another 3 weeks or so...

**Comment by Antiheavy** [comment]
Trying to force complete photo coverage around the survey perimeter is generally a good thing.  However, I don't think it actually solves the problem of distance based camera triggers starting/stopping too soon based on the L1 controller waypoint criteria.

For example:
image

The SITL example showb earlier in this thread was flown at 273 m which allows the camera trigger distance to be large compared to L1 waypoint criteria distance.  The typical 122 m altitude limit we have here in North America makes this problem much worse (as does narrower field of view cameras).   We will typically see our camera start/stop 3-5 photos too early (both directions so 6-10 photo shift).  We now always use "take pictures in the turnarounds" and trim the extra photos in post processing.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Yeah, it crashed when I tried to use it ages ago: https://github.com/mavlink/qgroundcontrol/pull/5532

**Comment by DonLakeFlyer** [comment]
If you can rebase it I can try it all out again.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer @Antiheavy Any status update here?

**Comment by Antiheavy** [comment]
We stand ready to flight test whenever QGC has support for this.

**Comment by LorenzMeier** [comment]
Rebased and pushed - ready for a bench test.

**Comment by Antiheavy** [comment]
Still VERY interested in this.  Waiting on QGC support I believe?

**Comment by DonLakeFlyer** [comment]
I tested this with a hacked version of QGC which allows you to add the command. I tested using this simple plan file: 
[ConditionGate.plan.txt](https://github.com/PX4/Firmware/files/2780782/ConditionGate.plan.txt)

My assumption is that this works just like a waypoint, but the acceptance radius doesn't come into play and it flies through the waypoint. Once it is passed the waypoint the next mission command will trigger. Is that a correct assumption?

When I flew the plan in SITL I got this (3 is the CONDITION_GATE, 4 is a camera trigger):

screen shot 2019-01-21 at 3 31 58 pm

**Comment by Antiheavy** [comment]
i think this looks correct, although it might make more sense to see it used with a Survey type mission (understand you hacked it in for the test above).  @LorenzMeier would know for sure if it is acting as intended.

**Comment by DonLakeFlyer** [comment]
The camera trigger should have been after the 3 waypoint not the 2 waypoint as far as I understand how this should work.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Please test with a survey - too hard to see.

**Comment by LorenzMeier** [comment]
I have rebased this PR and moved it here: https://github.com/PX4/Firmware/pull/11878 - I'm closing this, but I'm not deleting the branch just yet. @DonLakeFlyer I need a QGC branch that implements this, so that I can close the loop on testing. Feel free to experiment with the rebased branch, but it might not work at all.

**Pull request closed without merging**
