### PR TITLE
VTOL transition switch parameter checking

### PR DESCRIPTION
**Pull request by sanderux**
Transition switch parameter enforcement

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by sfuhrer** [comment]
@sanderux what actually was the reason for enforcing the transition switch? For me it should be optional and not enforced. We currently e.g. have a RC without any switches, and instead trigger the transitions via mavlink commands.

**Comment by sanderux** [comment]
@sfuhrer this stems from the time where QGC did not support VTOL transitions. We decided to enforce it so that people starting with VTOL would understand it was needed to fly vtol.

I agree it now is just annoying and I second removing it from the required params.

**Comment by sfuhrer** [comment]
Thanks for the feedback, I've made a PR: https://github.com/PX4/PX4-Autopilot/pull/18710

**Pull request merged**
