### PR TITLE
DriverFramework: update to latest master

### PR DESCRIPTION
**Pull request by julianoes**
Note that this update will require a git submodule sync inside
src/lib/DriverFramework.

I've quickly (but not extensively) bench tested this on Snappy.

FYI @ChristophTobler.

### CODE REVIEW

**Comment by julianoes** [comment]
@ChristophTobler please cross-test

**Comment by ChristophTobler** [comment]
@julianoes Thanks. Seems to work with the snapdragon. Can you please add https://github.com/PX4/DriverFramework/pull/194 before merging?

**Comment by santiago3dr** [comment]
snapdragon flight

http://logs.uaventure.com/view/t2JZQLVe7U5z8z6Rx4qjAn
held okay in stabilize, changed to altitude mode; held altitude well for a few seconds then descended 
rapidly with throttle still centered

**Comment by LorenzMeier** [comment]
@ChristophTobler @mcharleb  I tried to rebase this / get it in but the current head of DriverFramework points to a non-existent dspal commit.

**Comment by julianoes** [comment]
@LorenzMeier have you tried `git submodule syn` inside DriverFramework?

**Comment by LorenzMeier** [comment]
Stupid of me. I thought it would complain about non-existent remote, but it just complains about non-existent ref (or I was blind).

Thanks!

Replacement PR: https://github.com/PX4/Firmware/pull/7011

**Pull request closed without merging**
