### PR TITLE
rcS: start frsky_telemetry on Pixracer if not enabled already

### PR DESCRIPTION
**Pull request by bkueng**
This got lost in #10337.

### CODE REVIEW

**Comment by dagar** [comment]
Instead of directly starting this on a pixracer why not set the default parameters and let the regular logic handle it?

In this case the user is going to see "Serial Configuration for FrSky Telemetry" set to disabled.

**Comment by bkueng** [comment]
Beause the FrSky port is not configurable as it contains inverter logic and you cannot use it as a 'normal' UART.

**Comment by dagar** [comment]
I'm aware, but I don't see why we can't show it. It gives the user visibility and control instead of a special case we need to document or explain. "It says disabled but it's actually running by default".

**Comment by bkueng** [comment]
Either way is not ideal. If you allow configuration, users try to use it for different purposes and will fail. But if you feel so strong I'll add it.

**Comment by dagar** [comment]
Actually it's for that same group of users that learn the system by poking around and trying settings that I was hoping the "self documenting" setup would help.

I guess there's no mechanism for limiting the serial dev list per module?

**Comment by bkueng** [comment]
Can you check what the ouput of `frsky_telemetry status` on the console is?

**Pull request merged**
