### PR TITLE
[WIP] vscode configuration

### PR DESCRIPTION
**Pull request by dagar**
[Visual Studio Code](https://code.visualstudio.com/) with a few key plugins and a proper in tree configuration (this PR) is a close to perfect cross platform IDE option for PX4 development.

 - perfect cmake integration
    - driven by gui, but in sync with regular command line actions
 - build, debug, test in IDE
 - IDE uses actual build and current configuration to resolve symbols
    - includes generated pieces like uORB messages
 - debugging targets available from gui (defined in .vscode)
 - embedded debugging (jlink, blackmagic, openocd)
    - uses optional SVD file (like MCU Eclipse https://gnu-mcu-eclipse.github.io/ or commercial options)

image

TODO: 
 - get all PX4 config and debug targets working
 - embedded debug helpers (SVD files, jlink integration)
 - simple setup instructions and usage instructions
   - plugins needed and how to get them, how to run with cmake and get proper symbol resolution

### CODE REVIEW

**Comment by TSC21** [comment]
@dagar great stuff!! Would this follow with some documentation to set this?

**Comment by LorenzMeier** [comment]
I've taken multiple stabs at this with different IDE's and this might be finally "the one". How about GDB? Could you take a stab along the lines of this?

http://justinmklam.com/posts/2017/10/vscode-debugger-setup/

**Comment by MaEtUgR** [comment]
Awsome! I had this on my list for some time now. I want to test this configuration also on the Windows toolchain. It will probably require a helper script to run vscode inside the proper toolchain environment like I did it with eclipse before.

**Comment by bys1123** [comment]
@MaEtUgR That will be fantastic!

**Comment by dagar** [comment]
I'm going to merge this to make it easier to experiment with the missing pieces incrementally. It's entirely contained to `.vscode`, so we can drop it later if necessary.

If we can get this working well let's do a big push to fully document it.

**Pull request merged**
