### PR TITLE
CMake Windows Fixes

### PR DESCRIPTION
**Pull request by dagar**
@LorenzMeier @jgoppert There are several problems with cmake on windows. So far I've identified the following, but I don't have proper fixes yet.

 - [x] remove rsync again - delete and copy NuttX each time
 - [x] change cmake generator to `MSYS Makefiles` (I think), We need some way to detect windows for the toplevel makefile. One hacky way is to check for the SystemRoot env variable that should only be present on windows.
 - [x] set PYTHONPATH properly on windows https://github.com/PX4/Firmware/blob/72dfc6b0b6c3a561f5b338677dce112b41bdce83/cmake/common/px4_base.cmake#L333
 - [x] libuavcan problems with windows include paths not being passed properly
 - [x] topic_listener path split
 - [x] romfs bin_to_obj.py

### CODE REVIEW

**Comment by dagar** [comment]
The include path being passed to uavcan is a mix of windows and cygwin paths.

include C;\Users\Daniel\Documents\GitHub\Firmware\src\include\visibility.h -mcpu=cortex-m4 -mthumb -march=armv7e-m -mfpu=fpv4-sp-d16 -mfloat-abi=hard -nodefaultlibs -nostdlib -DUAVCAN_NO_ASSERTIONS -DUAVCAN_STM32_NUM_IFACES=2 -DUAVCAN_USE_EXTERNAL_SNPRINT -DUAVCAN_MEM_POOL_B
LOCK_SIZE=48 -DUAVCAN_MAX_NETWORK_SIZE_HINT=16 -DUAVCAN_STM32_TIMER_NUMBER=5 -DUAVCAN_STM32_NUTTX=1 -DUAVCAN_CPP_VERSION=UAVCAN_CPP03 -IC;C:\px4\toolchain\msys\1.0\Users\Daniel\Doc
uments\GitHub\Firmware\build_px4fmu-v2_default\px4fmu-v2\NuttX\nuttx-export\include -IC;C:\px4\toolchain\msys\1.0\Users\Daniel\Documents\GitHub\Firmware\build_px4fmu-v2_default\px4
fmu-v2\NuttX\nuttx-export\include\cxx -IC;C:\px4\toolchain\msys\1.0\Users\Daniel\Documents\GitHub\Firmware\build_px4fmu-v2_default\px4fmu-v2\NuttX\nuttx-export\arch\chip -IC;C:\px4
\toolchain\msys\1.0\Users\Daniel\Documents\GitHub\Firmware\build_px4fmu-v2_default\px4fmu-v2\NuttX\nuttx-export\arch\common -Wall -Wextra -Wundef -std=c++03 -Wno-variadic-macros -W
no-long-long -O2 -g -DNDEBUG -I/C/Users/Daniel/Documents/GitHub/Firmware/src/lib/uavcan/./libuavcan/include -I/C/Users/Daniel/Documents/GitHub/Firmware/src/lib/uavcan/./libuavcan/include/dsdlc_generated -I/C/Users/Daniel/Documents/GitHub/Firmware/src/lib/uavcan/libuavcan/include/dsdlc_generated -I/C/Users/Daniel/Documents/GitHub/Firmware/src/lib/uavcan/libua
vcan/include    -o CMakeFiles/uavcan.dir/src/driver/uc_can.cpp.obj -c /C/Users/Daniel/Documents/GitHub/Firmware/src/lib/uavcan/libuavcan/src/driver/uc_can.cpp

**Comment by jgoppert** [comment]
@dagar @pavel-kirienko  This is because the include flags are being passed to the cmake external project as compile flags. we need to get the correct path separator in the uavcan flags.

**Comment by jgoppert** [comment]
Originally I was passing them as include directories, which cmake would then handle correctly, but this was causing problems for @pavel-kirienko. I guess we can just do an ugly hack that if win32 string(REPLACE "/" "\" ..)

**Comment by pavel-kirienko** [comment]
@jgoppert I suggested to avoid mirroring build configuration options in CMakeLists.txt, but I don't remember providing any feedback on include paths. What is your preferred solution?

**Comment by jgoppert** [comment]
@pavel-kirienko OK, great, sorry about the confusion. I think we just need to add back the NUTTX_EXPORT_DIR options to the uavcan cmake file then. And then add the required include directories from there.

**Comment by dagar** [comment]
**Generating romfs.o** failure


screenshot 2015-10-12 21 19 28

**Comment by jgoppert** [comment]
@dagar  I used python to code bintoobj.py but it is calling subprocess to invoke the compilers. One of the arguments must not be getting passed properly.

**Comment by dagar** [comment]
Python argparse is turning `c:/Users/Daniel/Documents/GitHub/Firmware/src/include/visibility.h` into `c;C:\px4\toolchain\msys\1.0\Users\Daniel\Documents\GitHub\Firmware\src\include\visibility.h`

Just wondering why it's necessary to have a python script compile this? Is it not possible to have cmake build and link it?

**Comment by jgoppert** [comment]
Pure cmake would be better if you can manage it. It was just becoming too complicated at the time and I opted for python.

**Comment by dagar** [comment]
@jgoppert @LorenzMeier that should be everything other than uavcan needed to build px4fmu-v2_default on windows. Please review.

**Comment by dagar** [comment]
@jgoppert  Just playing around it seems like it would be relatively easy to pull in uavcan with `add_subdirectory()`, which would solve the remaining windows problems. Any particular reason you used `ExternalProject_Add()` instead?

**Comment by pavel-kirienko** [comment]
@jgoppert The problem with `NUTTX_EXPORT_DIR` remains, however. It adds an ad-hoc feature for NuttX. Can't we find a *generic* solution that would work for any platform, keeping libuavcan's build scripts NuttX-agnostic?

**Comment by LorenzMeier** [comment]
@pavel-kirienko Your call - we need something that works. We'll go with whatever you feel is better in terms of architecture but still works. If you can't find an elegant and working solution we'll just maintain this in a UAVCAN fork. I don't want to have UAVCAN continuing to block toolchain improvements for PX4.

@jgoppert @dagar Any stopgap or proper solution that we could adopt to unblock the Windows folks?

**Comment by dagar** [comment]
@LorenzMeier with this branch px4fmu-v2_default will build on windows if you remove uavcan from nuttx_px4fmu-v2_default.cmake

**Comment by pavel-kirienko** [comment]
@jgoppert 

> I think we just need to add back the NUTTX_EXPORT_DIR options to the uavcan cmake file then. And then add the required include directories from there.

This is a project-specific solution that will work only for PX4, there's no reason to add this in libuavcan.

If my understanding is correct, CMake subprojects inherit certain properties from the top-level project; the set of include directories should be among inherited properties too. Therefore, it should be possible to configure the include directories once in the top-level script using `include_directories()`, or even `target_include_directories(libuavcan)`. Will this work?

**Comment by pavel-kirienko** [comment]
@jgoppert Just noticed that libuavcan is added as an external project, not as a CMake sub-directory;  @dagar has mentioned this above already. This would probably prevent you from using the simple solution I described above. Why did you prefer `externalproject_add` over `add_subdirectory`?

**Comment by jgoppert** [comment]
I'm not opposed to add_subdirectory if that is the simplest solution. Typically each project finds its own deps so add project is easier, but maybe not with how the uavcan cmake build is written.

**Comment by pavel-kirienko** [comment]
> not with how the uavcan cmake build is written.

What needs to be fixed?

**Comment by dagar** [comment]
This is now building on windows. I had to move the libuavcan submodule to src/modules/uavcan because cmake doesn't like out of source builds when you use add_subdirectory() and it's not actually a subdirectory.

**Comment by pavel-kirienko** [comment]
Seems OK to me.

**Comment by LorenzMeier** [comment]
Awesome, thanks!

**Pull request merged**
