### PR TITLE
WIP: Param backend replace utarray with HashMap

### PR DESCRIPTION
**Pull request by jgoppert**
Utarray uses the struct memory address as a key in a hashtable. This means we have to pass around the object instances to reference things like params and topics. This switches the backend to HashMap that does string based hashing. It will allow us to directly implement a ROS like api for param management.

I plan to keep everything 100% backwards compatible, but change the param handles to be strings internally and for new code to just uses the strings directly.

@stephanbro FYI

### TODO

* [x] Add HashMap submodule
* [x] Move param.c to param.cpp
* [x] Create HashMap for params
* [ ] Change backend to use HashMap

### CODE REVIEW

**Comment by bkueng** [comment]
Useful to know: gcc does string deduplication (`-fmerge-constants`): https://gcc.gnu.org/onlinedocs/gcc-4.0.3/gcc/Optimize-Options.html, so 100 equal string literals will not use more Flash.
LLVM does that as well.

**Comment by jgoppert** [comment]
@LorenzMeier unclear about your comment here: https://github.com/PX4/Firmware/pull/6283#issuecomment-272396707

Do you think I'm headed in a good direction with this PR?

**Comment by jgoppert** [comment]
I just added jinja template generation for the params here. This is so I can easily swap the template now and generate the HashMap data structure.

**Comment by dagar** [comment]
Oh, I assumed jinja was for sitl_gazebo. Looks like I added it to the wrong image.

**Comment by jgoppert** [comment]
This now has 8 bytes/param storage size. I don't need to store the char * for the name since I'm using the dict. So (4 bytes for  float/int32 storate), 1 byte for type (uint8_t), and then 3 bytes for alignment that we could store something else there if we wanted. The existing param struct has (4 bytes for float/int32 storage), (4 bytes for const char *, and 1 bytes for type, so I think it takes up 12 bytes/param, need to check.

**Comment by jgoppert** [comment]
@dagar did I not reference docker correctly? https://github.com/PX4/Firmware/pull/6305/commits/9644f7bf9606cefde205df7ba46d94d61bde4fa0

I'm still getting issue where jinja2 is not found.

**Comment by davids5** [comment]
> The existing param struct has (4 bytes for float/int32 storage), (4 bytes for const char *, and 1 bytes for type, so I think it takes up 12 bytes/param, need to check.

@jgoppert rebasing on master will pick up @dagar wonderful Makefile changes and we can see how the sizes change.

**Comment by dagar** [comment]
@jgoppert unfortunately some of it still needs to be configured on the semaphore interface. Travis-ci will need jinja installed for mac. They should all be fixed shortly.

**Comment by dagar** [comment]
@jgoppert should be good to go after a rebase.

**Comment by jgoppert** [comment]
@davids5 Is there somewhere I can look in the bulid log to see the size delta or do I just need to upload and check with free. Also currently this has both param systems since I haven't changed the guts of param.cpp to use the new param dictionary and am trying to do this incrementally.

**Comment by davids5** [comment]
@jgoppert Flash can be checked on semaphoreci - in the Build Sizes

make sizes - will also give you flash usage 
For free RAM - you need to load and use free on nsh.

**Comment by jgoppert** [comment]
@dagar Once the docker image is updated on master it will need the px4tools api change for the CI: https://github.com/PX4/Firmware/pull/6305/commits/28d234af3f6c7fa2c9c8062b5fb037fb3d309f8a

**Comment by jgoppert** [comment]
The last bit of this will require some thought. I have everything working but need to decide how to handle the existing API.

**Comment by dagar** [comment]
Closing PR, but keeping the branch.

**Pull request closed without merging**
