### PR TITLE
add settling time on sensor start-up

### PR DESCRIPTION
**Pull request by ASM3**
Add settling time after setting adis16448 registers

### CODE REVIEW

**Comment by dagar** [comment]
Would further delaying the first cycle resolve the problem? https://github.com/ASM3/Firmware/blob/79bdf007741750c8a78b56e8c2a0b571d0b3ecff/src/drivers/imu/adis16448/adis16448.cpp#L1358

**Comment by ASM3** [comment]
Obviously, this is the purpose. We want to prevent the uc to perform any kind of SPI writing cycle during this epoch, what potentially could mess up the adis16448 registers (happened in very rare cases). If this delay during boot-up sequence is so critical for the system another solution can potentially be figured out.

**Comment by ASM3** [comment]
The restore factory calibration functionality is unnecessary on the boot-up sequence and therefore removed

**Comment by philipoe** [comment]
@dagar @LorenzMeier To explain a bit: We noticed that the `_set_factory_default()` functionality/call can in rare cases (ca 5% of all bootups of the ADIS driver + Pixhawk) put the ADIS in a faulty state where it delivers updates too slowly (causing a "GYRO: STALE" warning by PX4). The reason is that the `set_factory_default()` call requires (as per the analog devices datasheet) a certain time period _without any_ communication on the SPI bus, but apparently something within PX4 is writing stuff to the SPI bus (@asm3 measured this using a logic analyzer). The `set_factory_default()` call is however not really necessary and was just added in case a user messes up the ADIS configuration, but we at ASL have actually never needed that call even in 4 years of using ~5 platforms with the ADIS. Therefore, it is now removed, and testing has shown that everything works perfectly now.

**Pull request merged**
