### PR TITLE
DO NOT MERGE: Smoothing path

### PR DESCRIPTION
**Pull request by Stifael**
first tests with smoothing path along the waypoints.
To actually make it work: 
- navigator reach position needs to adjusted
-mapping from way points to bezier points which contain actual information of the states

Questions still unanswered
-How much of the mapping should be done in the controller, how much in the navigator.

### CODE REVIEW

**Comment by Stifael** [comment]
in the mc_pos_control, there is a compute_yaw function which is not needed

**Comment by tumbili** [comment]
@Stifael Two quick comments:
1) I suggest you should use the matrix class to define vectors and matrices. I think matrix should replace the mathlib at some point if I'm not mistaken. And I can tell you how annoying it is when you are using both libs at the same time in the same module (which is already happening now).
2) I think the cross product for vectors is implemented in the libs already.

**Comment by LorenzMeier** [comment]
Please rebase, thanks!

**Comment by LorenzMeier** [comment]
Closing in anticipation of a new PR with the new version.

**Pull request closed without merging**
