### PR TITLE
Sunset px4_fmu-v2_default

### PR DESCRIPTION
**Pull request by julianoes**
Due to a silicon errata on STM32F427VIT6 we can only use 1 MB flash instead of 2 MBs that would be available on the chip.

The target `fmu-v2` was used for Pixhawks with the silicon errata while the target `fmu-v3` can be used for newer Pixhawks without the errata.

For several years we have maintained the `px4_fmu-v2_default` target by optimizing flash space and removing debug helpers as well as drivers for less common peripherals and sensors.

Now that the release v1.10 is forked off, it's sensible to sunset the `px4_fmu-v2_default` target in order to make development easier.

This only removes the `_default` target which contains multicopter, fixedwing, and VTOL modules but keeps the separate `_multirotor`, `_fixedwing`, `_rover` modules.

### CODE REVIEW

**Comment by julianoes** [comment]
Given `_fixedwing` and `_multicopter` are also overflowing flash now, we might think about deprecating all `v2` targets.

**Comment by davids5** [comment]
@julianoes - let's add this to the agenda for the dev call and see if we get consensus on it.  FYI @mrpollo

**Comment by hamishwillee** [comment]
Can you capture the result of the developer call discussion here. It has fairly significant product and documentation implications. 

I'm presuming that we'd mark v1.10 as the last supported version for fmu_v2.

**Comment by julianoes** [comment]
@dagar mentioned in the call a couple of reasons why we can't/shouldn't do this:

- We will hit the flash limit on other platforms anyway, so it's an ongoing problem that we need to tackle.
- Most downloads are fmu-v2_default, so it should probably stay.

**Pull request closed without merging**
