### PR TITLE
restore px4fmu-v2_test

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
The tests are working other than commander_tests which is a hard faulting and mavlink_tests is missing required generated test data (mavlink_ftp_test_data.py). 

I think some of this testing could work in a posix_sitl_test config and run in the regular travis-ci build.

**Comment by dagar** [comment]
@LorenzMeier this is a mixed bag of testing cleanup. I'm going to start running tests on a pixhawk using that USB relay module we talked about last year.


 - restore the px4fmu-v2_test target and get the tests passing
 - add posix_sitl_test (like px4fmu-v2_test)
 - added ability to run posix_sitl_test with gazebo and no gui (use HEADLESS=1). Try `make test_onboard_sitl`.
 - the top level Makefile now handles building gazebo `make gazebo_build`
 - fixed param_test, and added param_shmem_test (currently broken)
 - unit tests (make unittest) use address sanitizer
 - made `make check_format` run in parallel so hopefully more people will bother checking before pushing
 - split out uORB unit tests to reduce the size of px4fmu-v2_default ever so slightly

**Comment by LorenzMeier** [comment]
Looking good, will go in for 1.4.0 when 1.3.0 is out.

**Comment by LorenzMeier** [comment]
Phew, what a diff, awesome! Could you also write initial test docs for http://dev.px4.io. Please also get in touch with @bkueng who is working on testing with me here.

**Pull request closed without merging**
