### PR TITLE
uORB combine VTOL FW and MC virtual topics

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice cleanup!

**Comment by LorenzMeier** [comment]
@dagar Can you please validate in a log that the individual topics show up in the logger and can be plotted?

**Comment by dagar** [comment]
@sanderux you can optionally add them to logger -
 (https://github.com/PX4/Firmware/blob/2a175aa2f90c5cbbcdbb2902e352b634181ea0cf/src/modules/logger/logger.cpp#L560). 
I don't think we should always log them, but it could conceivably be useful to temporarily add during VTOL testing/work.

**Comment by dagar** [comment]
That SITL setup needs some tuning, but attitude and rates are generally tracking before, during, and after transitions.

**Pull request merged**
