### PR TITLE
[WIP] Jenkins: basic support for hardware testing

### PR DESCRIPTION
**Pull request by darioxz**
**Work in Progress!**

This PR offers basic Hardware-In-The-Loop (HIL) support using Jenkins and Docker. 

**Requirements**

1. PX4 Autopilot HW module, e.g. PX4FMU_V4
1. USB Hub with power control, e.g. D-Link-DUB-H7-High-Speed-7-Port or others see on [hub-ctrl.c](https://github.com/codazoda/hub-ctrl.c)
1. Micro-USB cable
1. USB-FTDI cable (and if required, an adapter to plug into your autopilot module)
1. PC with Docker support (configure Docker to use without sudo: `sudo usermod -aG docker $USER`)

**Setup Jenkins Slave Nodes**
Add a new Jenkins node on your Jenkins master:

* `Name`: fill in `HIL_<HW>_<JENKINS_SLAVE_ID>` whereas `<HW>`is the HW architecture, and <JENKINS_SLAVE_ID> is a unique number. e.g. `HIL_PX4FMU_V4_1`, see below
* `# of executors`: fill in `1`
* `Remote root directory`: fill in `/home/hil/`
* `Usage`: select `Only build jobs with label expressions matching this node`
* `Launch method`: select `Launch agent via Java web start`
* `Disable WorkDir`: unchecked
* `Custom WorkDir path`: empty
* `Internal data directory`: fill in `remoting`
* `Fail if workspace is missing`: unchecked
* `Availability`: select `Keep this agent online as much as possible`
* `Environment Variables`: unchecked
* `Tool locations`: unchecked 

**Setup Slaves**

1. Connect the autopilot module using a micro-usb cable AND a ftdi cable to your USB hub. 
1. Create a json file named `device_config.json` in `./Tools/HIL/` with the following content:

```
[
{
"UID": "360023:32365108:36363331",
"HW": "PX4FMU_V4",
"JENKINS_SLAVE_ID": 1,
"JENKINS_SLAVE_SECRET": "981734aaa51dec5902e971c7e9e4202e7dda0870ddfc3b3d8e4cc586855ad0e5",
"JENKINS_MASTER_URL": "172.17.0.1:8888"
}
]
```

whereas

* `UID` is the UID of your autopilot module. (use the command `ver uid` in your mavlink shell, e.g. `./Tools/mavlink_shell.py` to find out the UID)
* `HW` is the hardware architecture of your autopilot module (use `ver hw` in your mavlink shell to find out)
* `JENKINS_SLAVE_ID`, `JENKINS_SLAVE_SECRET` and `JENKINS_MASTER_URL` are the parameters of your Jenkins node.

To add multiple HIL nodes, just add a new entry to the list (don't forget the comma between the entries!), e.g.:

```
[
{
"UID": "360023:32365108:36363331",
"HW": "PX4FMU_V4",
"JENKINS_SLAVE_ID": 1,
"JENKINS_SLAVE_SECRET": "981734aaa51dec5902e971c7e9e4202e7dda0870ddfc3b3d8e4cc586855ad0e5",
"JENKINS_MASTER_URL": "172.17.0.1:8888"
},
{
"UID": "3333333:88888888:23423424",
"HW": "PX4FMU_V4",
"JENKINS_SLAVE_ID": 2,
"JENKINS_SLAVE_SECRET": "981734aaa51dec5902e971c7e9e4202e7dda0870ddfc3b3d8e4cc586855ad0e5",
"JENKINS_MASTER_URL": "172.17.0.1:8888"
},
]
```

1. Build slave docker container:

```
cd ./Tools/HIL
docker build -f Dockerfile_base -t slave_base .
docker build -f Dockerfile -t blueocean_slave .
```

1. Run docker slaves

```
cd ./Tools/HIL
sudo ./setup_slaves.py
```

This tries to find your configured modules connected to the usb hub, runs a docker container **for each**, and tries to register each container as Jenkins slave at your Jenkins master.

### CODE REVIEW

**Comment by darioxz** [comment]
@dagar, fyi. I added a node called `HIL_PX4FMU_V4_0` to the `http://ci.px4.io:8080` Jenkins master.

The whole Docker part should be rewritten, e.g. the original Dockerfile of the base container could be used after some modifications.

**Comment by dagar** [comment]
Great!
We need to reconcile Dockerfiles here and in the container repo (https://github.com/PX4/containers/tree/master/docker/px4-dev). We also shouldn't keep the slave.jar in this repo. I'm thinking about creating Docker hub automated builds that consistent of the PX4 dev environment and the Jenkins pieces (JRE + slave.jar) configured to autoconnect to the master.

**Comment by LorenzMeier** [comment]
@dagar Should we revive the discussion / effort here? I have a NUC here I could set up as slave as well.

**Comment by dagar** [comment]
> @dagar Should we revive the discussion / effort here?

Yes definitely. I see two extremes for build configurations.

1. USB only flash + boot test. Need to power cycle the board to flash, and scripting over mavlink or something local in firmware to verify everything started correctly. This is should be the baseline for all supported boards.

2. Boards with debugger and serial console. This is where we should run most of the actual testing to gather appropriate feedback if things going really wrong (hardfault). Periodic profiling runs (PMP) would also be quite valuable to stay on top of NuttX performance.

We should also have a variety of peripherals (GPS, airspeed, power modules, lidar, etc) attached.

For the NUC you could start by installing stock Ubuntu 16.04 + docker (https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/), then it's trivial to connect it as a generic build slave. We can use labels in Jenkins to track slaves with particular hardware attached.

We should document each physical board setup and I'll duplicate some of it here.

**Comment by darioxz** [comment]
@LorenzMeier I planned to invest 2-3 weeks on this topic starting from the end of next week. 

@dagar Since jMAVSim now supports mavlink2 with https://github.com/PX4/jMAVSim/pull/65 (Thanks @julianoes!) and I already managed to use it inside a docker container, I would like to use it in combination with DroneCore to enable integration tests. 

The next steps would be:
- Cleanup the Jenkins environment and make it compatible with the existing `Jenkinsfile`. 
- Add the jMAVSim + DroneCore part to Jenkins, add some integration tests

If I understood you correctly, you would prefer to add the debugger support first. If so, then I would skip the integration tests part and do that instead.

**Comment by LorenzMeier** [comment]
@darioxz First priority is to flash the board and run a basic test on it (just launching a test app via NSH). When we have that deployed and documented we can continue.

The biggest reliability issue with hardware is not actually the flight control code, but the variance between boards. We need to get that under control first.

**Comment by darioxz** [comment]
@LorenzMeier Ok thanks. 

At the moment `tests perf` gets executed using the shell (https://github.com/PX4/Firmware/pull/8321/files#diff-7f02c4a960b698866a028a5c81f31be7R25) after the flashing procedure. I'll have a talk with @bkueng and @dagar to find a more appropriate test to perform.

**Comment by julianoes** [comment]
:sob:

**Pull request closed without merging**
