### PR TITLE
SITL fixes

### PR DESCRIPTION
**Pull request by LorenzMeier**
@mcharleb This works around the broken orb_limit calls and makes the HRT 0 interval warnings go away except for on init and on buzzer calls, which both make sense. I have a bad memory access still happening, but its likely unrelated. Currently chasing that one with all of Vagrant's might.

### CODE REVIEW

**Comment by mcharleb** [comment]
@LorenzMeier Will it run it you use AddressSanitizer?

**Comment by LorenzMeier** [comment]
@mcharleb Seeing this:

```
INFO  GYROSIM::measure 8528743
INFO  GYROSIM::measure 8628783
INFO  GYROSIM::measure 8728754
INFO  GYROSIM::measure 8828771
INFO  GYROSIM::measure 8928750
INFO  GYROSIM::measure 9028766
INFO  GYROSIM::measure 9128744
INFO  GYROSIM::measure 9228767
INFO  GYROSIM::measure 9328767
INFO  GYROSIM::measure 9428810
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  GPS timeout
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
WARN  WARNING: degenerate accel / mag!
```

**Comment by LorenzMeier** [comment]
It looks like the HRT is stopping to schedule calls.

**Comment by mcharleb** [comment]
GYROSIM::measure is being called 100 times every 100ms, so every 1ms and
then stops I presume? Sounds like the work queue is locked up. Deadlock?
You might see it a lock is being held.

We should make a PX4 monitor thread that makes sure it gets updates from
all the expected polling at the expected rate and can dump the
work-queue(s) if an event is late.

**Comment by mcharleb** [comment]
@LorenzMeier When you get to the state above to can attach to the running process or generate a core file and look at it with GDB. See which threads are waiting on a lock or have a lock.

kill -SIGQUIT process_id

**Comment by LorenzMeier** [comment]
Getting closer:

```
pxh> INFO  GYROSIM::_set_sample_rate 1000003 Hz
INFO  GYROSIM: Changed sample rate to 1000 Hz
INFO  GYROSIM: Interval 1000
```
but then the timings look like this:
```
INFO  GYROSIM::measure 8850292
INFO  GYROSIM::measure 8950393
INFO  GYROSIM::measure 9050387
INFO  GYROSIM::measure 9150289
INFO  GYROSIM::measure 9250288
INFO  GYROSIM::measure 9350391
```

I just pushed the commit with the instrumentation. Could you try this on your end and see if you get something faster than 10 Hz?

**Comment by mcharleb** [comment]
I'm out for the rest of the day but I can try it tomorrow.

**Comment by LorenzMeier** [comment]
Vagrant has the same basic issue. So something not quite right with HRT.

```
INFO  GYROSIM::measure 13959664
INFO  GYROSIM::measure 14059712
INFO  GYROSIM::measure 14159644
WARN  navigator timed out
INFO  GYROSIM::measure 14259669
INFO  GYROSIM::measure 14359801
INFO  GYROSIM::measure 14459717
INFO  GYROSIM::measure 14559663
INFO  GYROSIM::measure 14660543
INFO  GYROSIM::measure 14759726
```

**Comment by LorenzMeier** [comment]
Rebased on master and force-pushed. New command to run stuff:
```
make posix_sitl_default jmavsim
```

**Comment by LorenzMeier** [comment]
Getting more:

```
make posix_sitl_default jmavsim
```

with this diff:
```diff
diff --git a/cmake/common/px4_base.cmake b/cmake/common/px4_base.cmake
index 26598fe..4c9177d 100644
--- a/cmake/common/px4_base.cmake
+++ b/cmake/common/px4_base.cmake
@@ -530,14 +530,14 @@ function(px4_add_common_flags)
                )
        endif()
 
-       set(max_optimization -Os)
+       set(max_optimization -O1)
 
        set(optimization_flags
                -fno-strict-aliasing
-               -fomit-frame-pointer
                -funsafe-math-optimizations
                -ffunction-sections
                -fdata-sections
+               -g -fsanitize=address -fno-omit-frame-pointer
                )
 
        if (NOT ${CMAKE_C_COMPILER_ID} MATCHES ".*Clang.*")
```

this result:

```
ASAN:SIGSEGV
=================================================================
==95857==ERROR: AddressSanitizer: SEGV on unknown address 0x7fff9a5169ea (pc 0x00010aa4d84f bp 0x00010e209e70 sp 0x00010e209e70 T3)
pxh> pxh>     #0 0x10aa4d84e in dq_rem dq_rem.c:68
    #1 0x10aa4c89e in work_hrtthread hrt_thread.c:146
    #2 0x10aa4ae0c in entry_adapter(void*) px4_posix_tasks.cpp:87
    #3 0x7fff9a519059 in _pthread_body (/usr/lib/system/libsystem_pthread.dylib+0x4059)
    #4 0x7fff9a518fd6 in _pthread_start (/usr/lib/system/libsystem_pthread.dylib+0x3fd6)
    #5 0x7fff9a5163ec in thread_start (/usr/lib/system/libsystem_pthread.dylib+0x13ec)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV dq_rem.c:68 dq_rem
Thread T3 created by T0 here:
    #0 0x10ae2e8d9 in wrap_pthread_create (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x388d9)
    #1 0x10aa4aabf in px4_task_spawn_cmd px4_posix_tasks.cpp:182
    #2 0x10aa4c782 in hrt_work_queue_init hrt_thread.c:270
    #3 0x10aa4a439 in px4::init_once() px4_posix_impl.cpp:71
    #4 0x10aa30070 in main main.cpp:186
    #5 0x7fff8ff965c8 in start (/usr/lib/system/libdyld.dylib+0x35c8)
    #6 0x1  (<unknown module>)

==95857==ABORTING
Tools/sitl_run.sh: line 77: 95857 Abort trap: 6           ./mainapp ../../../../$rc_script
```

**Comment by LorenzMeier** [comment]
Another run with the same setup provided this, which looks like HRT internal stack smashing.

```
INFO  TONE_SET_ALARM 15
INFO  ToneAlarm::start_tune
ASAN:SIGSEGV
INFO  TONE_SET_ALARM 0
=================================================================
==96763==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010f0530eb bp 0x00011280ad80 sp 0x00011280ad50 T3)
INFO  TONE_SET_ALARM 9
INFO  ToneAlarm::start_tune
    #0 0x10f0530ea in ToneAlarm::next_char() tone_alarm.cpp:608
    #1 0x10f052738 in ToneAlarm::next_note() tone_alarm.cpp:418
    #2 0x10f04d3d7 in hrt_tim_isr drv_hrt.c:467
    #3 0x10f04d906 in work_hrtthread hrt_thread.c:171
    #4 0x10f04be1c in entry_adapter(void*) px4_posix_tasks.cpp:87
    #5 0x7fff9a519059 in _pthread_body (/usr/lib/system/libsystem_pthread.dylib+0x4059)
    #6 0x7fff9a518fd6 in _pthread_start (/usr/lib/system/libsystem_pthread.dylib+0x3fd6)
    #7 0x7fff9a5163ec in thread_start (/usr/lib/system/libsystem_pthread.dylib+0x13ec)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV tone_alarm.cpp:608 ToneAlarm::next_char()
Thread T3 created by T0 here:
    #0 0x10f4348d9 in wrap_pthread_create (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x388d9)
    #1 0x10f04bacf in px4_task_spawn_cmd px4_posix_tasks.cpp:182
    #2 0x10f04d792 in hrt_work_queue_init hrt_thread.c:270
    #3 0x10f04b449 in px4::init_once() px4_posix_impl.cpp:71
    #4 0x10f031080 in main main.cpp:186
    #5 0x7fff8ff965c8 in start (/usr/lib/system/libdyld.dylib+0x35c8)
    #6 0x1  (<unknown module>)

==96763==ABORTING
Tools/sitl_run.sh: line 77: 96763 Abort trap: 6           ./mainapp ../../../../$rc_script
```

**Comment by LorenzMeier** [comment]
And another run with similar outcome. First the sensor data goes bad, then it eventually crashes. Looks like the first log is the closest.

```
ASAN:SIGSEGV
=================================================================
==97285==ERROR: AddressSanitizer: SEGV on unknown address 0x7fff9a5169ea (pc 0x000101a6b85f bp 0x000105227e70 sp 0x000105227e70 T3)
INFO  TONE_SET_ALARM 9
INFO  ToneAlarm::start_tune
    #0 0x101a6b85e in dq_rem dq_rem.c:68
    #1 0x101a6a8ae in work_hrtthread hrt_thread.c:146
    #2 0x101a68e1c in entry_adapter(void*) px4_posix_tasks.cpp:87
    #3 0x7fff9a519059 in _pthread_body (/usr/lib/system/libsystem_pthread.dylib+0x4059)
    #4 0x7fff9a518fd6 in _pthread_start (/usr/lib/system/libsystem_pthread.dylib+0x3fd6)
    #5 0x7fff9a5163ec in thread_start (/usr/lib/system/libsystem_pthread.dylib+0x13ec)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV dq_rem.c:68 dq_rem
Thread T3 created by T0 here:
    #0 0x101e4a8d9 in wrap_pthread_create (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x388d9)
    #1 0x101a68acf in px4_task_spawn_cmd px4_posix_tasks.cpp:182
    #2 0x101a6a792 in hrt_work_queue_init hrt_thread.c:270
    #3 0x101a68449 in px4::init_once() px4_posix_impl.cpp:71
    #4 0x101a4e080 in main main.cpp:186
    #5 0x7fff8ff965c8 in start (/usr/lib/system/libdyld.dylib+0x35c8)
    #6 0x1  (<unknown module>)

==97285==ABORTING
Tools/sitl_run.sh: line 77: 97285 Abort trap: 6           ./mainapp ../../../../$rc_script
```

**Comment by LorenzMeier** [comment]
More fun:

```
pxh> pxh> pxh> pxh> pxh> ASAN:SIGSEGV
=================================================================
==99430==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010414364a bp 0x00010845c2d0 sp 0x00010845c140 T13)
WARN  navigator timed out
    #0 0x104143649 in px4_open vdev_posix.cpp:121
    #1 0x10418d3d7 in uORB::Manager::node_open(uORB::Flavor, orb_metadata const*, void const*, bool, int*, int) uORBManager_posix.cpp:267
    #2 0x10418cfd1 in uORB::Manager::orb_advertise_multi(orb_metadata const*, void const*, int*, int) uORBManager_posix.cpp:99
    #3 0x10420406f in AttitudeEstimatorQ::task_main() attitude_estimator_q_main.cpp:459
    #4 0x10414de1c in entry_adapter(void*) px4_posix_tasks.cpp:87
    #5 0x7fff9a519059 in _pthread_body (/usr/lib/system/libsystem_pthread.dylib+0x4059)
    #6 0x7fff9a518fd6 in _pthread_start (/usr/lib/system/libsystem_pthread.dylib+0x3fd6)
    #7 0x7fff9a5163ec in thread_start (/usr/lib/system/libsystem_pthread.dylib+0x13ec)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV vdev_posix.cpp:121 px4_open
Thread T13 created by T0 here:
    #0 0x1045308d9 in wrap_pthread_create (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x388d9)
    #1 0x10414dacf in px4_task_spawn_cmd px4_posix_tasks.cpp:182
    #2 0x1042025da in AttitudeEstimatorQ::start() attitude_estimator_q_main.cpp:239
    #3 0x1042060ec in attitude_estimator_q_main attitude_estimator_q_main.cpp:619
    #4 0x1041347b2 in run_cmd(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool) main.cpp:102
    #5 0x104134305 in process_line(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool) main.cpp:139
    #6 0x10413333e in main main.cpp:196
    #7 0x7fff8ff965c8 in start (/usr/lib/system/libdyld.dylib+0x35c8)
    #8 0x1  (<unknown module>)

pxh> ==99430==ABORTING
Tools/sitl_run.sh: line 77: 99430 Abort trap: 6           ./mainapp ../../../../$rc_script
```

**Comment by LorenzMeier** [comment]
After staring at this a while I think the issue is that the code running off the HRT callbacks assumed interrupt context, which means that it expects its the sole thing running in the system. I'm not sure the semaphore is the right locking mechanism, a simple mutex and the right locking hierarchy might be better in replicating that interrupt style execution.

**Comment by mcharleb** [comment]
I'll have a look. Thanks.

**Comment by LorenzMeier** [comment]
Note the #3113 PR.

**Comment by LorenzMeier** [comment]
I've updated this with all known fixes.

**Comment by LorenzMeier** [comment]
We're still left with these issues:
```
ASAN:SIGSEGV
=================================================================
==5708==ERROR: AddressSanitizer: SEGV on unknown address 0x7fff95d5ec70 (pc 0x0001041d53ef bp 0x00010798de70 sp 0x00010798de70 T3)
    #0 0x1041d53ee in dq_rem dq_rem.c:68
    #1 0x1041d443e in work_hrtthread hrt_thread.c:146
    #2 0x1041d29ac in entry_adapter(void*) px4_posix_tasks.cpp:87
    #3 0x7fff95d61059 in _pthread_body (/usr/lib/system/libsystem_pthread.dylib+0x4059)
    #4 0x7fff95d60fd6 in _pthread_start (/usr/lib/system/libsystem_pthread.dylib+0x3fd6)
    #5 0x7fff95d5e3ec in thread_start (/usr/lib/system/libsystem_pthread.dylib+0x13ec)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV dq_rem.c:68 dq_rem
Thread T3 created by T0 here:
    #0 0x1045b18d9 in wrap_pthread_create (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x388d9)
    #1 0x1041d265f in px4_task_spawn_cmd px4_posix_tasks.cpp:182
    #2 0x1041d4322 in hrt_work_queue_init hrt_thread.c:270
    #3 0x1041d1fd9 in px4::init_once() px4_posix_impl.cpp:71
    #4 0x1041b79b0 in main main.cpp:186
    #5 0x7fff8c9405c8 in start (/usr/lib/system/libdyld.dylib+0x35c8)
    #6 0x1  (<unknown module>)

==5708==ABORTING
Tools/sitl_run.sh: line 88:  5708 Abort trap: 6           ./mainapp ../../../../${rc_script}_${program}
```

**Comment by LorenzMeier** [comment]
Ok, I think I just fixed that. I just keep finding real corner cases in the system. One down!

**Comment by LorenzMeier** [comment]
Tumbili you might want to check if this works better with VTOL.

**Pull request closed without merging**
