### PR TITLE
FW delete unused yaw coordination parameters

### PR DESCRIPTION
**Pull request by dagar**
The ecl side methods can be deleted once this is out of the way.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Not sure yet we want this change or rather enable the coordination?

**Comment by dagar** [comment]
These have been non-functional since the coordinated turn logic changed about a year ago.

https://github.com/PX4/ecl/blob/master/attitude_fw/ecl_yaw_controller.cpp#L171

If someone wants to add support back on the ecl side I'll happily resurrect this. Until then I think non-functional parameters are a bad experience.

**Comment by LorenzMeier** [comment]
Fair!

**Comment by paan2097** [comment]
@dagar @LorenzMeier Hi is the open loop or closed loop coordination used permanently?

**Pull request merged**
