### PR TITLE
px4_fmu-v4pro Fix PX4IO firmware upgrade

### PR DESCRIPTION
**Pull request by davids5**
The PX4IO was responding but the RX DMA stay borke

This fixes USART6 RX DMA Assignment

### CODE REVIEW

**Comment by dagar** [comment]
Thanks David. I'd like to take this as an opportunity to get the test rack into a state where it can actually catch trivial things like this. All boards on the test rack routinely get stuck in a state where the px4io is unrecoverable.

**Comment by dagar** [comment]
Still failing here. http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-hardware/detail/master_px4pro_px4io_fix/1/pipeline/498

Screenshot from 2020-01-30 16-03-25

**Comment by dagar** [comment]
I'm also still trying to figure out why the redefinition wasn't a compile time warning.

**Comment by davids5** [comment]
@dagar 

Would you please send me the image from 0 to 0xffff as a bin file extracted from the PX4IO on the V4PRO of the test rack?

**Pull request merged**
