### PR TITLE
commander: write timestamp of commander_state topic on init and state change

### PR DESCRIPTION
**Pull request by bkueng**
needed for the new logger

@julianoes

### CODE REVIEW

**Comment by julianoes** [comment]
Ok makes sense. Is the timestamp not updated automatically on `orb_publish`?

**Comment by bkueng** [comment]
no the publisher is always responsible for that, because the publisher knows best what the right timestamp is.

**Comment by julianoes** [comment]
Ok, merged.

**Comment by bkueng** [comment]
thanks!

**Pull request merged**
