### PR TITLE
add USART6 to discovery board

### PR DESCRIPTION
**Pull request by nopeppermint**
I am trying to add support for one more serial on my stm32f4discovery board.
I have no build errors, it's booting, I can connect over usart2 and I get the nsh prompt.
With "ls /dev" I get:
>/dev:
>console
>null
>ram0
>ttyACM0
>ttyS0

USART6 is located on PC6 (TX) and PC7 (RX).
Does someone could give me a hint, where I could find my new configured USART6?
@davids5 Are there additional steps with nuttx required to add this serial?
@betterbar do you like to retest this?

Additionally I added some more led configs.

### CODE REVIEW

**Comment by davids5** [comment]
With 2 UARTS UART2 would be /dev/console and ttyS0  and UART6 would be /dev/ttyS1 

So something looks wrong.

If you can set a break point on uart_register in serial.c and see what is it called with, and how many times. Is should be called from stm32_serial.c in up_serialinit.

**Comment by davids5** [comment]
@nopeppermint Did you run make oldconfig on the configuration?

**Comment by nopeppermint** [comment]
I will try do debug this later.
@davids5 where should I run "make oldconfig"
my compile steps were:
git clone https://github.com/nopeppermint/Firmware.git
cd Firmware
git submodule init
git submodule update
make distclean
make archives
make
make px4-stm32f4discovery_default upload

**Comment by davids5** [comment]
PX4 uses Nuttx as an exported build, but one can copy the nuttx-configs/px4-stm32f4discovery into the Nuttx/nuttx/configs directory and build (not link) the board using the standard nuttx build sequence. When doing this one issue is that the NuttX/nuttx/configs/Kconfig will not contain your HW config, This is easy to fix -  Below is a diff to add the PX4 FMU V2 modded for the discovery, (I would not expect it to just apply) but apply the same sort of changes for the px4-stm32f4discovery in NuttX/nuttx/configs/Kconfig.  Just post the diff you end up with back here and keep a copy of it out of the tree. Do not submit it to upstream Nuttx, Greg does not carry the PX4 configs in the his repo any longer.

```
diff --git a/nuttx/configs/Kconfig b/nuttx/configs/Kconfig
index fab0113..9ed10c7 100644
--- a/nuttx/configs/Kconfig
+++ b/nuttx/configs/Kconfig
@@ -606,6 +606,16 @@ config ARCH_BOARD_PIRELLI_DPL10
                This directory contains the board support for Pirelli dpl10 phones.  The
                additions were made by Craig Comstock (with help form Alan Carvalho de Assis).
 
+config ARCH_BOARD_PX4STM32F4DISCOVERY
+       bool "PX4 stm32f4discovery"
+       depends on ARCH_CHIP_STM32F427V <<--- Check this
+       ---help---
+               This is a minimal configuration that supports low-level test of the
+               PX4FMU v2 in the NuttX source tree.  If you are using PX4, you
+               probably don't want this configuration.  You probably want the
+               latest supported configuration available from the PX4 GIT
+               repositories.
+
 config ARCH_BOARD_NUCLEO_F401RE
        bool "STM32F401 Nucleo F401RE"
        depends on ARCH_CHIP_STM32F401RE
@@ -1179,6 +1189,7 @@ config ARCH_BOARD
        default "pic32mz-starterkit"       if ARCH_BOARD_PIC32MZ_STARTERKIT
        default "pirelli_dpl10"            if ARCH_BOARD_PIRELLI_DPL10
        default "nucleo-f4x1re"            if ARCH_BOARD_NUCLEO_F401RE || ARCH_BOARD_NUCLEO_F411RE
+  default "px4-stm32f4discovery"                if ARCH_BOARD_PX4STM32F4DISCOVERY
        default "qemu-i486"                if ARCH_BOARD_QEMU_I486
        default "rgmp"                     if ARCH_BOARD_RGMP
        default "sama5d3x-ek"              if ARCH_BOARD_SAMA5D3X_EK
@@ -1458,6 +1469,9 @@ endif
 if ARCH_BOARD_NUCLEO_F401RE || ARCH_BOARD_NUCLEO_F411RE
 source "configs/nucleo-f4x1re/Kconfig"
 endif
+if ARCH_BOARD_PX4STM32F4DISCOVERY
+source "configs/px4-stm32f4discover/Kconfig"
+endif
 if ARCH_BOARD_QEMU_I486
 source "configs/qemu-i486/Kconfig"
 endif
```

I have looked at the nuttx-configs/px4-stm32f4discovery/nsh/defconfig in your repo. The Board Selection does not set CONFIG_ARCH_BOARD and CONFIG_ARCH_BOARD_xxxxx=y
For this to work you will need CONFIG_ARCH_BOARD_PX4STM32F4DISCOVER to match that of above:
```
#
# Board Selection
#
CONFIG_ARCH_BOARD_PX4STM32F4DISCOVER=y
# CONFIG_ARCH_BOARD_CUSTOM is not set
CONFIG_ARCH_BOARD="px4-stm32f4discovery"
```

Now to the task at hand:

make oldconfig will bring the .config in the root of NuttX/nuttx in alignment with the current Kconfig settings from Nuttx. It is done when Nuttx is upgraded. It may be needed in your case for a new config file copied from some possible stale version of of a PX4 build against an old nuttx. 

The closer the defconfig is to the version of nuttx the less changes you will have to make.

To get a better defconfig, you may want to first compare the px4fmu-v2 defconfig and the discovery's defconfig and maybe just replace nuttx-configs/px4-stm32f4discovery/nsh/defconfig the with nuttx-configs/px4fmu-v2/nsh/defconfig and make only the needed changed to support the discovery's to that file.

There is a comparison tool NuttX/nuttx/tools/  cmpconfig  (run make in that folder to build it)

To run make oldconfig
```
cd NuttX/nuttx
cp -r ../../nuttx-configs/px4-stm32f4discovery/ configs/
make distclean; cd tools;./configure.sh px4-stm32f4discovery/nsh; cd ..
make oldconfig (Answer a lot of question, use ? and take defaults if unsure)
make menuconfig
```
Check all the settings and Save the config.

Once this is done the .config needs to replace the ../../nuttx-configs/px4-stm32f4discovery/nsh/defconfig 

Diff the nuttx-configs/px4-stm32f4discovery/nsh/defconfig and the NuttX/nuttx/.config 
remove any CONFIG_DEBUG=Y and CONFIG_APPS_DIR by prepending # and not set to the end

**Comment by nopeppermint** [comment]
I modified the Kconfig file (only ARCH_CHIP changed compared to yours)
```
---------------------------- nuttx/configs/Kconfig ----------------------------
index b5b03b8..8f7fbfb 100644
@@ -575,16 +575,26 @@ config ARCH_BOARD_STM32F4_DISCOVERY
 	bool "STMicro STM32F4-Discovery board"
 	depends on ARCH_CHIP_STM32F407VG
 	select ARCH_HAVE_LEDS
 	select ARCH_HAVE_BUTTONS
 	select ARCH_HAVE_IRQBUTTONS
 	---help---
 		STMicro STM32F4-Discovery board based on the STMicro STM32F407VGT6 MCU.
 
+config ARCH_BOARD_PX4STM32F4DISCOVERY
+    bool "PX4 stm32f4discovery"
+    depends on ARCH_CHIP_STM32F407VG
+    ---help---
+    This is a minimal configuration that supports low-level test of the
+    PX4STM32F4DISCOVERY in the NuttX source tree.  If you are using PX4, you
+    probably don't want this configuration.  You probably want the
+    latest supported configuration available from the PX4 GIT
+    repositories.
+
 config ARCH_BOARD_STM32L_DISCOVERY
 	bool "STMicro STM32L-Discovery board"
 	depends on ARCH_CHIP_STM32L152RB
 	select ARCH_HAVE_LEDS
 	select ARCH_HAVE_BUTTONS
 	select ARCH_HAVE_IRQBUTTONS
 	---help---
 		STMicro STM32L-Discovery board based on the STMicro STM32L152RB MCU.
@@ -796,16 +806,17 @@ config ARCH_BOARD
 	default "stm32f4discovery"    if ARCH_BOARD_STM32F4_DISCOVERY
+    default "px4-stm32f4discovery"if ARCH_BOARD_PX4STM32F4DISCOVERY
 	default "stm32ldiscovery"     if ARCH_BOARD_STM32L_DISCOVERY
@@ -1040,16 +1051,19 @@  if ARCH_BOARD_STM32F4_DISCOVERY
 source "configs/stm32f4discovery/Kconfig"
 endif
 if ARCH_BOARD_STM32L_DISCOVERY
 source "configs/stm32ldiscovery/Kconfig"
 endif
+if ARCH_BOARD_PX4STM32F4DISCOVERY
+source "configs/px4-stm32f4discovery/Kconfig"
+endif
```

**Comment by davids5** [comment]
I am sorry I may have misled you. If the HW you are working with is a vanilla stm32 discovery board, Then assuming Nuttx supports the board already. KConfig would not need to be changed.

Just the defconfig would use that board.

run make oldconfig against what you have now.
make menuconfig
Select that board.

Save and follow the above https://github.com/PX4/Firmware/pull/2059#issuecomment-94799104

**Comment by nopeppermint** [comment]
I am using the STM32F4DiscoveryBoard with STM32F407VG MCU
http://www.st.com/web/catalog/tools/FM116/SC959/SS1532/PF252419

**Comment by davids5** [comment]
Please run make menuconfig or grep the Kconfig files and see if in the version of NuttX (tied to the Firmware by submodule) you are using has both the Proc STM32F407VG the board  STM32F4DiscoveryBoard  listed.

**Comment by nopeppermint** [comment]
In the Kconfig I get by:
>git clone https://github.com/nopeppermint/Firmware.git
>git submodule init
>git submodule update
>cd NuttX/nuttx/configs
>grep -Hrn 'STM32F4' Kconfig 

```
Kconfig:542:		STMicro STM3220G-EVAL development board based on the STMicro STM32F407IG
Kconfig:547:	depends on ARCH_CHIP_STM32F407IG
Kconfig:574:config ARCH_BOARD_STM32F4_DISCOVERY
Kconfig:575:	bool "STMicro STM32F4-Discovery board"
Kconfig:576:	depends on ARCH_CHIP_STM32F407VG
Kconfig:581:		STMicro STM32F4-Discovery board based on the STMicro STM32F407VGT6 MCU.
Kconfig:592:config ARCH_BOARD_MIKROE_STM32F4
Kconfig:593:	bool "MikroElektronika Mikromedia for STM32F4 board"
Kconfig:594:	depends on ARCH_CHIP_STM32F407VG
Kconfig:596:		This is the port NuttX to the Mikroelektronika Mikromedia for STM32F4 Multimedia Board
Kconfig:803:	default "stm32f4discovery"    if ARCH_BOARD_STM32F4_DISCOVERY
Kconfig:805:	default "mikroe-stm32f4"      if ARCH_BOARD_MIKROE_STM32F4
Kconfig:955:if ARCH_BOARD_MIKROE_STM32F4
Kconfig:1042:if ARCH_BOARD_STM32F4_DISCOVERY
```
Line 574-576 is the correct board and line 803 also.

**Comment by davids5** [comment]
Yes so use these in your defconfig

#
# Board Selection
#
CONFIG_ARCH_BOARD_STM32F4_DISCOVERY=y
# CONFIG_ARCH_BOARD_CUSTOM is not set
CONFIG_ARCH_BOARD="stm32f4discovery"

**Comment by nopeppermint** [comment]
and should be able to build with:
>make distclean
>make archives
>make
>make px4-stm32f4discovery_default upload

right?

**Comment by davids5** [comment]
Still run the make oldconfig and make menuconfig once as described above.  #2059 (comment) 
then when you run make from the Firmware folder use V=1 and ensure the Firmware build is passing the right value in CONFIG_ARCH_BOARD

**Comment by nopeppermint** [comment]
ok, will try

**Comment by nopeppermint** [comment]
I got one error:
```
chip/stm32_serial.c:141:8: error: #error "USART6 DMA channel not defined (DMAMAP_USART6_RX)"
chip/stm32_serial.c:879:20: error: 'DMAMAP_USART6_RX' undeclared here (not in a function)
chip/stm32_serial.c: In function 'up_dma_receive':
chip/stm32_serial.c:2053:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
chip/stm32_serial.c: In function 'up_dma_rxavailable':
chip/stm32_serial.c:2110:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```

**Comment by davids5** [comment]
Find the origin of DMAMAP_USART6_RX. It stems from a CONFIG_xxxxx

Then run make menuconfig in the Firmware directory (see below first)

Then while in the menuconfig type /xxxx where the xxxx is the xxxx part of CONFIG_xxxxx you found above. This will tell you the "path" through the menu to set that setting.

Once done, re run 
make distclean;
BOARDS="px4-stm32f4discovery" make  archivel make px4-stm32f4discovery


DO THIS FIRST and commit your work!:
Did you copy back the .config to the defconfig after the make oldconfig and make menuconfig run from Firmware/Nuttx/nuttx? 

```
cd NuttX/nuttx
cp -r ../../nuttx-configs/px4-stm32f4discovery/ configs/
make distclean; cd tools;./configure.sh px4-stm32f4discovery/nsh; cd ..
make oldconfig (Answer a lot of question, use ? and take defaults if unsure)
make menuconfig
Check all the settings and Save the config.
```
**Once this is done the .config needs to replace the ../../nuttx-configs/px4-stm32f4discovery/nsh/defconfig**

If so you can now run make menuconfig from /Firmware and change the setting.

**Comment by nopeppermint** [comment]
rebase

**Comment by nopeppermint** [comment]
usart6_as_ttys1_on_stm32f4discovery
Got USART6 as ttyS1 working ;-)

**Comment by LorenzMeier** [comment]
Let me know once your changes are complete. This branch still has commits in from master, so I don't think the rebase worked out completely. I'm happy to fix that for you though.

**Comment by nopeppermint** [comment]
I'm not sure how I can access the leds in src/drivers/boards/px4-stm32f4discovery/px4discovery_led.c
to test if they work?

Apart from the leds there are only three files changed:
nuttx-configs/px4-stm32f4discovery/include/board.h (added usart6)
nuttx-configs/px4-stm32f4discovery/nsh/defconfig  (added usart6)
src/drivers/boards/px4-stm32f4discovery/board_config.h  (comments corrected)

**Comment by nopeppermint** [comment]
stm32f4_discovery

new picture for the wiki

**Comment by LorenzMeier** [comment]
Could you just add it to the wiki? You can directly edit it. Thanks!

**Comment by LorenzMeier** [comment]
if you start the commander app it should blink the leds.

**Comment by nopeppermint** [comment]
yes I will add It to the wiki, ones this is in master.

the commander app is not yet in the makefiles/config_px4-stm32f4discovery_default.mk makefile, so I can not use it.

Please merge the following file to master:
nuttx-configs/px4-stm32f4discovery/include/board.h (added usart6)
nuttx-configs/px4-stm32f4discovery/nsh/defconfig (added usart6)
src/drivers/boards/px4-stm32f4discovery/board_config.h (comments corrected)
src/drivers/boards/px4-stm32f4discovery/px4discovery_led.c (leds added)

I will then start again from master to get the LEDs and the commander working.
ok?

**Comment by nopeppermint** [comment]
wiki is updated

**Comment by nopeppermint** [comment]
replaced by #2174

**Pull request closed without merging**
