### PR TITLE
Solve the problem When lost rc signal, it will rtl repeated.

### PR DESCRIPTION
**Pull request by ender-chen**
I think there is something wrong in lost signal condition "!landed". Because in RTL. When touched the land It is still uncompleted. But it will change to other navigator_mode. So I suggest Delete that condition.

### CODE REVIEW

**Comment by dagar** [comment]
Ignore the semaphoreci check. It's been disabled.

**Comment by LorenzMeier** [comment]
Is this based on some flight testing or do you think its wrong?

**Comment by julianoes** [comment]
It's based on this #4607 but I think this change would make it worse because now it would go into RTL even if it has already landed.

**Comment by julianoes** [comment]
Thanks you @ender-chen. I've cherry-picked your commit in #4559.

**Pull request closed without merging**
