### PR TITLE
mavlink_log_info: also print PX4_INFO

### PR DESCRIPTION
**Pull request by dagar**
- any information sent to the ground should also be available for log review

This might be too much information at first, but it's better than being kept in the dark with what a user would have experienced. This came up when debugging https://github.com/PX4/Firmware/pull/14825.

### CODE REVIEW

**Comment by dagar** [comment]
Alternatively we could have logger explicitly grab these.

**Comment by dagar** [comment]
Here we go again.

Screenshot from 2020-05-06 14-51-49

**Comment by bkueng** [comment]
There's already mavlink_and_console_log_info

**Comment by dagar** [comment]
> There's already mavlink_and_console_log_info

Right, I forgot about that one. Do you see distinct use cases that should be preserved (mavlink info with no PX4_INFO)?

There actually aren't that many `mavlink_log_info()` calls.

Screenshot from 2020-05-07 09-06-12

Does anyone see a reason we shouldn't merge `mavlink_log_info` + `mavlink_and_console_log_info()`?

**Comment by bkueng** [comment]
> Does anyone see a reason we shouldn't merge mavlink_log_info + mavlink_and_console_log_info()?

Merging is fine with me.

**Comment by dagar** [comment]
> > Does anyone see a reason we shouldn't merge mavlink_log_info + mavlink_and_console_log_info()?
> 
> Merging is fine with me.

Done.

**Pull request merged**
