### PR TITLE
MC att control demand: Require a higher minimum throttle

### PR DESCRIPTION
**Pull request by LorenzMeier**
@kd0aij @tumbili This is what we discussed.

### CODE REVIEW

**Comment by SimonWilks** [comment]
@LorenzMeier could you explain briefly what this addresses? The branch name (multicopter_fall_fix) sounds like it might be addressing issues we've been facing.

**Comment by tumbili** [comment]
@SimonWilks This should prevent the multicopter from tumbling in manual mode when throttle is set to zero. If you require a min value for thrust then the mixer will always be able to create some roll/pitch authority.

**Comment by tumbili** [comment]
@SimonWilks Sounds like you've been having multicopters "falling" out of the sky? :-)

**Comment by SimonWilks** [comment]
@tumbili I see. Not sure if this is the same. I've been trying to collect plots of failures and comparing the same motion in manual. What happens in my case is I have the throttle at 50% (ALTCTL) and POSCTL active, fly forwards as fast as allowed by the max XY velocity (10m/s) then release. The multirotor then tumbles as it oscillates radically in pitch. It does act like it's underpowered. Very stable in manual mode no matter how violently I throw it around.

**Comment by tumbili** [comment]
@SimonWilks Do you have logs?

**Comment by SimonWilks** [comment]
@tumbili  I do, just wanted to do one more round of tuning on yaw first to make sure it's not a tuning issue...but the rain...grrr. Shall I followup in gitter or mailing list?

**Comment by tumbili** [comment]
@SimonWilks I prefer gitter but it's not a must.

**Comment by kd0aij** [comment]
cherry-picked into release_v1.0.0
no instability at zero throttle in manual mode, nice smooth descent

**Comment by LorenzMeier** [comment]
@SimonWilks This block here might interact with attitude control on large demands. Is your issue reproducible in HIL?
https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L1204-L1212

**Comment by kd0aij** [comment]
also flown on QAV250; good stable descents at zero throttle
Log: https://copy.com/lCXXEJJGLK4knegq

**Comment by kd0aij** [comment]
min throttle test: Local Z estimate too heavily filtered to observe altitude variations, but Z accelerometer correlates well to throttle. Traces are offset to put 1G at zero.
minthrottletest

**Comment by kd0aij** [comment]
I think that the default minimum of 0.18 for MPC_THR_MIN is a bit too high. My QAV250 does stable descents with a value of 0.1, but wants to lift off at 0.18

**Comment by tumbili** [comment]
@kd0aij @LorenzMeier I can see how that works with a 450 today.

**Pull request merged**
