### PR TITLE
IO RSSI handling: Fix RSSI for all protocols.

### PR DESCRIPTION
**Pull request by LorenzMeier**
@AndreasAntener @dogmaphobic @NosDE This is a general RSSI logic cleanup, plus the addition of low-pass filtering the ADC signal.

@tumbili Could you please connect RSSI of your D4R-II and cross-check what you get in QGC?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@dogmaphobic This should get all outputs into the right ranges for you.

**Comment by dogmaphobic** [comment]
> This should get all outputs into the right ranges for you.

This is for RC only, correct? I've already adjusted QGC to handle RC RSSI values using a range of 0-100. I also made the assumption that values over 100 means there is no RSSI and I don't show the indicator at all in those cases.

Telemetry RSSI however, still relies on the 0.5dB per unit giving a range of 0 to 127dB. Will that change?

**Comment by LorenzMeier** [comment]
No, telemetry stays the same.

**Comment by dogmaphobic** [comment]
For what it's worth, I'm getting a steady **0** for RC RSSI. I'm using an FrSky R8X, which outputs a PWM signal out of its RSSI port. Am I right in assuming that the RSSI input on the PX4 is just an ADC and wouldn't know what to make out of the PWM signal coming in there? If that's the case, I would have to find a way to convert the PWM into a 0-3.3v, right?

**Comment by AndreasAntener** [comment]
Usually you'd need an RC circuit: https://www.youtube.com/watch?feature=player_detailpage&v=oU-WQVaHm4g#t=116
(although there the output might be from 0 to 5 but you can try different value components)

But, Lorenz added a low-pass in the code. Although when I look at the code now there might be a problem..

**Pull request merged**
