### PR TITLE
STM32F7 disable d-cache see 1259864 Data corruption in a sequence of …

### PR DESCRIPTION
**Pull request by davids5**
…Write-Through stores and loads
For AB testing with master to determine the effects of disabling the d-cache

image

### CODE REVIEW

**Comment by Tony3dr** [comment]
@LorenzMeier @dagar The Test Flight Team is out in the field and will be testing this PR today.

**Comment by davids5** [comment]
Unaffected IP from ARM:

Arm®  Cortex® -M7 Processor  Revision *r1p2*

Technical Reference Manual

From https://static.docs.arm.com/ddi0489/f/DDI0489F_cortex_m7_trm.pdf

5 November 2018 F Non-Confidential First release for r1p2

So we should assume all IC's in the wild have the bug if the CPUID reset value is not 0x411FC272.

**Comment by dannyfpv** [comment]
tested on pixhawk4 v5 pull.
https://review.px4.io/plot_app?log=7f7dbd2c-749e-4ff9-8881-4918f6d5a499
master
https://review.px4.io/plot_app?log=25512724-aa42-421e-a5cb-269304b2c71b

**Comment by dagar** [comment]
To be paranoid let's merge this now, and revisit enabling the data cache again later as needed.

Very roughly this increases cpu usage by about 10% on fmu-v5, which we can easily afford right now.

**Pull request merged**
