### PR TITLE
Tools: update sitl_gazebo

### PR DESCRIPTION
**Pull request by TSC21**
This brings the new delay and noise models.

### CODE REVIEW

**Comment by ndepal** [comment]
Is the SDF parameter to enable/disable GPS noise documented anywhere?

**Comment by TSC21** [comment]
It's not but is as simples as going to the sdf file and set it or unset it.

**Comment by ndepal** [comment]
It's more about knowing that this is an option. How does somebody who is interested in having simulated GPS noise find out that this is a supported feature and can simply be enabled in the SDF?

**Comment by TSC21** [comment]
By default the noise is enabled. We just added the option to disable it. SITL and Gazebo itself still lack some docs in terms of its internals and features, but the idea is to change that soon.

**Comment by hamishwillee** [comment]
I think we should document (or minimally create issues) for things like this as soon as we find them. I'm suspicious of documentation that is planned for the future :-). Issue created here: https://github.com/PX4/Devguide/issues/415

@ndepal @TSC21 Would you be happy to create a PR? Suggestions on where this might best live is in the issue above.

**Pull request merged**
