### PR TITLE
Prop idling in ALTCTL and POSCTL

### PR DESCRIPTION
**Pull request by LorenzMeier**
@kd0aij This is good for testing. Hopefully the prop now idles without GPS lock and althold works without GPS as well.

### CODE REVIEW

**Comment by tumbili** [comment]
@LorenzMeier I assume this needs testing after your changes?

**Comment by LorenzMeier** [comment]
Yes, and I'm not 100% finished yet. We do not cover the case of no GPS -> GPS yet, and it could induce an uncommitted altitude change (from the perspective of the user).

**Comment by LorenzMeier** [comment]
@tumbili This is now good to go. It should cover all corner cases, idle props correctly and not do stupid stuff when it moves from no GPS -> GPS. If not, the diff your guide is, Luke.

**Comment by tumbili** [comment]
@LorenzMeier This is bench tested, and everything works as expected. I increased the idle to 0.2, think that should be ok. I can flight test this in the afternoon.

**Comment by LorenzMeier** [comment]
cool. Make sure to fly an ALTCTL mission with initially no GPS (if possible) and then GPS lock mid-air. I want to be sure it does the right thing and resets the altitude set point.

**Comment by tumbili** [comment]
@LorenzMeier This works like a charm. But I wasn't able to the gps from getting a fix right away. Is there a way how the put a delay?

**Comment by tumbili** [comment]
http://dash.oznet.ch/view/NXLhWbxtas5ndE2m6z7RYk

**Comment by tumbili** [comment]
@LorenzMeier I'm wondering if we should do a deadzone for the pitch stick in altctl. Often when I fly turns I apply some pitch and the plane looses altitude. I thought it was the controller but the logs showed what actually happened.

**Comment by LorenzMeier** [comment]
Go for it. Makes a lot of sense.

**Comment by kd0aij** [comment]
@tumbili Is that last log from your Ninox?

**Comment by tumbili** [comment]
@kd0aij It's the plane of Lorenz, also one from Bormate but not sure how it's called. It's even small than the Ninox. BTW, I didn't tune one parameter :-D

**Comment by kd0aij** [comment]
probably the "Q" then.

**Comment by tumbili** [comment]
@kd0aij I just see that the roll setpoint is always zero in ALTCTL

**Comment by kd0aij** [comment]
My Ninox seemed to add power and dive when I switched to ALTCTL. Do you think that means trim airspeed is too high?
I guess rollSP isn't published in ALTCTL?

**Comment by tumbili** [comment]
@kd0aij At what value do you have the trim airspeed. Could well be that it tries to pick up speed.

**Comment by kd0aij** [comment]
This is strange. Airspeed min/trim/max params are 10/15/20.
I enter ALTCTL at about 18m/sec then thrust jumps from 50 to 70% and the plane climbs 25m as airspeed drops all the way to 5m/sec. It then takes 17 more seconds to reach trim airspeed and starting altitude; about 25 seconds of confusion before it gets back right. Horrible tuning?
I haven't changed anything but L1 period since the POSCTL/heading lock test which behaved correctly.

**Comment by kd0aij** [comment]
@LorenzMeier @tumbili Is there a better way than looking at vehicle_status.h to figure out what the values of main_state mean? QGC reports friendly values like "ALTCTL", but the logs just show integer values.

**Comment by tumbili** [comment]
@kd0aij Sometimes if I'm nor sure I have a look at the rc values and together with the RC_MAP params you can figure it out. Can you post the log here?

**Comment by kd0aij** [comment]
https://copy.com/XzrHSOwbrChsjdDK

**Comment by LorenzMeier** [comment]
Did you set the trim throttle to 70? If it's too high then the integrator needs to settle first. You need to get throttle trim and airspeed trim to match.

**Comment by kd0aij** [comment]
Ah, I didn't know about that one: FW_THR_CRUISE defaulted to 0.7. Looking at the plot, I guess it should be 0.25

**Comment by kd0aij** [comment]
I bench tested this today (OK with GPS lock), but wasn't able to get the Ninox in the air. Overheated ESC, I think.

**Pull request merged**
