### PR TITLE
Fix romfs pruner

### PR DESCRIPTION
**Pull request by julianoes**
Ignore hidden files starting with .

Can I find agreement to have Python scripts with 4 space indent and limited to 80 chars linelength?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Travis still doesn't seem to like it.

**Comment by julianoes** [comment]
I'm not so sure why this fails:

```
changes detected, packing new archive
.
.
.
.
.
.
.
.
.
.
.
uploading archive
Done. Your build exited with 1.
```

**Comment by julianoes** [comment]
Now ```git submodule update``` fails...

**Comment by LorenzMeier** [comment]
Applied to master, thanks!

**Pull request closed without merging**
