### PR TITLE
Velocity control

### PR DESCRIPTION
**Pull request by tumbili**
Replaces #2930

### CODE REVIEW

**Comment by tumbili** [comment]
@v01d I just did one more change which was to always reset position setpoint when in velocity control mode. Makes it much easier to see what's going on in the logs.
Have you already tested offboard control with this?

**Comment by v01d** [comment]
@tumbili @lorenz
Your changes sound OK to me.

I tested in offboard mode and works as expected. Actually I'm using this:
https://github.com/v01d/Firmware/commit/4c4336e91b451d49a9de9c28265d9e1155825bea
Which extends pos hold top offboard mode.
Could I make a pull request for this too? I find it really helpful and has worked quite well so far.
I can make the change you made here also.

**Comment by LorenzMeier** [comment]
@v01d Your change there holds the position if no off board command is set, correct?

**Comment by v01d** [comment]
No, if no setpoint is sent offboard would time out. The change there is to
switch into pos. hold/ alt. hold when XY/Z velocities setpoint are small
enough, similar to when on manual input.

**Comment by LorenzMeier** [comment]
No I see what you're doing. I'm ok with this change, but I think it needs proper resolution medium term so we can expose this explicitly.

**Comment by v01d** [comment]
Ok, I will make a PR for this commit also.

What do you think would be the proper resolution?

**Comment by LorenzMeier** [comment]
To feed the position and velocity in together, following a strict physical model. E.g. pos sp = time_horizon * velocity, velocity sp = speed in m/s. The controller should then track the velocity as provided and only bound impossible inputs (in other words, it would enforce a minimum speed to reach the position setpoint  and a maximum acceleration).

**Comment by v01d** [comment]
Here's the PR: #3007 
I've added @tumbili modification

**Comment by AndreasAntener** [comment]
I believe this fixed the following issue as well: https://github.com/PX4/Firmware/issues/2810

**Comment by AndreasAntener** [comment]
@v01d Also, this is no probably incorrect now: https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L2764
Adding `!offboard_control_mode.ignore_velocity` was a half-way measure to get velocity control running again. Now the reset logic is different and it seems to have no effect now. But anyway it's probably wrong. How do you see that?

**Comment by v01d** [comment]
I haven't actually tested *position*/*altitude* setpoints for either axis.
I only tested velocity/climb rate setpoints and it works as expected. So,
the problem you point is in this case right?

**Comment by LorenzMeier** [comment]
The problem I see is that we have a switching controller. The switching should not be hardcoded, rather, you should use the flags in the MAVLink topic to disable / re-enable the position controller as needed.

There are two completely different use cases: One is to switch the internal controllers on and off, the other use case is to *command* position and velocity, but the command is open loop and not a controller. We need to support both and support them correctly.

I suggest for your use case you use the bitfields in the position target message and make sure that the system obeys them correctly. You can then do this in your own ROS application based on the remaining velocity.

**Comment by v01d** [comment]
Ok, maybe then it is best to write another plugin in mavros which exposes
the controller switches, which would allow to, e.g. fix altitude when I
want it to or go back to sending climb rates. I briefly thought about this,
but I was unsure how to nicely deal with this on ROS (i.e. most algorithms
either send a Twist or a Pose, not a combination of both). If the decision
is not no merge my last PR I could go about this way.

So, just to know about the intended roadmap for this:
1. the current offboard code (with no holds) will remain for now
2. the switches in commander.cpp may need modifications (to be tested once
I write this new mavros plugin)
3. eventually offboard control will expect a trajectory or at least a
position,velocity,time tuple directly

Is that more or less the idea?

If so, when doing (3), will it be possible to directly control velocity for
example? (i.e. a plugin on mavros expecting a simple Twist message) I
imagine if the position control bit is disabled, it should be possible.
Also, are you thinking of PIDs for this or some other control such as MPC?

**Comment by AndreasAntener** [comment]
@LorenzMeier @v01d there is an implementation pending on the MAVROS side where I also suggested to expose the very same bitfield: https://github.com/mavlink/mavros/pull/393#issuecomment-148925351
Although it concerns another matter, it would be good to sync the efforts, instead of @v01d also writing a new plugin :)

**Comment by v01d** [comment]
I don't understand how is that code (local takeoff) related to this. Also,
what is the setpoint_plugin you mention? I see one plugin per setpoint
type. If we were to expose the bits in MAVROS I understand you would be
thinking of an universal message containing
position+velocity(+acceleration?) all together in the message, with also a
bitfield indicating which values to ignore. Right?

**Comment by AndreasAntener** [comment]
@v01d 
> I only tested velocity/climb rate setpoints and it works as expected. So, the problem you point is in this case right?

Yes, if it would cause trouble you'd have noticed it in your tests. So it seems to do no harm. It should still be fixed I think. When I do some velocity test I'll see if I can remove it.

**Comment by v01d** [comment]
PS: can we split relevant discussions into corresponding issues? It is
getting quite confusing. Maybe it is best to:

* Create new issue on MAVROS: "expose LOCAL_POSITION_NED to mavros directly"
* This PR here: do further testing as you suggested and maybe report back
any problems (although, I would open a new issue in that case since this is
merged already).
* Offboard pos. hold: lets continue dicussion about it in the corresponding
PR (#3007).

Also #2823 and #1810 could probably closed, I think.

**Comment by AndreasAntener** [comment]
> I don't understand how is that code (local takeoff) related to this. Also,
what is the setpoint_plugin you mention? I see one plugin per setpoint
type. If we were to expose the bits in MAVROS I understand you would be
thinking of an universal message containing
position+velocity(+acceleration?) all together in the message, with also a
bitfield indicating which values to ignore. Right?

Sorry for the confusion, of course I mean to extend all the existing setpoint plugins eventually, but maybe start with the ones you use first. The reason I linked the other PR is that he's trying to expose new options in the bitfield for the `setpoint_position` plugin. And one option to do that would be to completely expose the bitfield. So that would be one step, the same can then be done for velocity and acceleration plugin.

So the new messages would contain their ROS type as it is now plus the bitfield.

**Comment by AndreasAntener** [comment]
> PS: can we split relevant discussions into corresponding issues? It is getting quite confusing. Maybe it is best to: 

Agreed

**Comment by v01d** [comment]
@AndreasAntener I've opened https://github.com/mavlink/mavros/issues/402 where we can discuss this further.

**Comment by v01d** [comment]
@AndreasAntener I understand you would be testing this (changes introduced in this PR) under position setpoints and so on? Maybe you can also test the following since I'm hitting a problem which I don't understand why could happen: first time I boot the autopilot and companion computer I attempt to make a swtich to offboard in flight, where computer is sending zero-velocity setpoint. At this point it does not appear that the quad is responding. I then land, make the three-pos switch go into posctl instead offboard and fly. This time, it responds correctly. I go back with the switch mapping and repeat first test, this time it responds.

I suspect there's some state variable not being set properly in control_offboard, but I'm not sure which one could be. Maybe the lines in commander.cpp play a role, I don't know.

Note that I'm flying my modified stable fork, which includes this PR and also #3007 

So if you could test this I could see if the problem lies in the code in this PR or not and maybe we can find a corner case.

**Comment by AndreasAntener** [comment]
Could you upload a log to http://logs.uaventure.com/ for this flight? What do you mean with it doesn't respond when you send a 0 velocity setpoint? Does it not switch into offboard?

**Comment by v01d** [comment]
No, it does, but I did not feel any response.

I'm sharing three logs: offboard where it didn't seem to respond. Then when
I tried with POSCTL. And then again in offboard, this time getting response.

http://logs.uaventure.com/view/9ArtCsmy7Vs4hAjV8VTLN
http://logs.uaventure.com/view/B85WmH3NSd9WWbASoKiqJh
http://logs.uaventure.com/view/rUbsPy2Bq3HpytvZigxwpW

In any case, don't worry too much about my experience. I mainly wanted to
suggest a particular test to do as well if you were already going to test
the new code under different conditions.

**Comment by v01d** [comment]
No, it does, but I did not feel any response. 

I'm sharing three logs: offboard where it didn't seem to respond. Then when I tried with POSCTL. And then again in offboard, this time getting response.

http://logs.uaventure.com/view/9ArtCsmy7Vs4hAjV8VTLN
http://logs.uaventure.com/view/B85WmH3NSd9WWbASoKiqJh
http://logs.uaventure.com/view/rUbsPy2Bq3HpytvZigxwpW

In any case, don't worry too much about my experience. I mainly wanted to suggest a particular test to do as well if you were already going to test the new code under different conditions.

**Comment by v01d** [comment]
@AndreasAntener while looking at the aforementioned issue, I revisited commander.cpp and mavlink_receiver.cpp.

I agree that on commander.cpp there is an issue. Altitude and climb-rate are coupled to position and velocity. In my opinion, this is a problem of not having an equivalent decoupling between XY and Z in the offboard_control_mode struct: there is only velocity and position, not vel/pos (for XY) and climb-rate and altitude (for Z). Right now it is assumed XYZ are controlled together or not at all.
This still works in mc_pos_control since the position_valid/velocity_valid flag of the setpoint tripled is checked as well.

Is it conceivable to change this topic? The set_position_target_local_ned mavlink message already supports individual masking in every axis. 

A second related aspect is that for manual mode, altitude_enabled and position_enabled are true, when now it would be more correct to set them to false since we're actually controlling velocity directly.

**Pull request merged**
