### PR TITLE
Pr update matrix

### PR DESCRIPTION
**Pull request by kamilritz**
Updates to newest master of matrix.
Adds SparseVector class.
Replaces deprecated matrix functions inside Firmware.

### CODE REVIEW

**Comment by dagar** [comment]
Looks like it needs to be synced with the ECL update.

**Comment by jkflying** [comment]
We're getting segfaults on the Plane missions:
https://github.com/PX4/Firmware/pull/15520/checks?check_run_id=966677266

**Comment by kamilritz** [comment]
@jkflying any ideas what could cause this?

**Comment by jkflying** [comment]
I guess some code path in ECL which is only exercised in these tests. @dagar the core dump inspection isn't working, did you ever have that working for the MAVROS tests before?

**Comment by priseborough** [comment]
@kamilritz Can you tell us the story behind https://github.com/PX4/Firmware/pull/15520/commits/9f81ef4a9ab1cc841aa618ba80d914e27f11cd55 ??

**Comment by kamilritz** [comment]
> @kamilritz Can you tell us the story behind [9f81ef4](https://github.com/PX4/Firmware/commit/9f81ef4a9ab1cc841aa618ba80d914e27f11cd55) ??

@priseborough I am not completely sure if this is right. @jkflying was removing the fabsf(dist) inside `waypoint_from_heading_and_distance()`. As @dagar pointed out, the loiter_radius can be positive or  negative, depending on the positive or negative curvature. Since we previously took the absolute value inside the function, I thought I should add it back here, to be safe.

**Pull request merged**
