### PR TITLE
eclipse project file updates

### PR DESCRIPTION
**Pull request by dagar**
- properly index ECL and generated uORB

### CODE REVIEW

**Comment by xuqintao** [comment]
@dagar  Can we open and compile project files by Eclipse in Linux? i can not do that ,and i want to make sure it .

**Comment by kd0aij** [comment]
The eclipse.project and eclipse.cproject files work fine for me in Ubuntu
15.10

**Comment by dagar** [comment]
@xuqintao Can you share an error message or screenshot?

You don't open them directly, you copy eclipse.cproject -> .cproject and eclipse.project -> .project and then import the project. To compile eclipse just calls out to make px4fmu-v2_default, etc.

**Comment by xuqintao** [comment]
@dagar  i just want compile project without makefiles ,because  it takes a lot of times to compile it every   time. Do you compile it by makefiles ?

**Comment by xuqintao** [comment]
@kd0aij  Do you compile it by makefiles?

**Comment by dagar** [comment]
Compiling with makefiles or through eclipse is the same. If you're using Ubuntu or OSX try installing ninja-build. It automatically scales to the number of cores your machine has.

**Comment by xuqintao** [comment]
@dagar could i set a breakpoint when i compiling?

**Comment by dagar** [comment]
Through eclipse you can debug posix_sitl, or a pixhawk with a black magic probe. Eclipse debugging is just a GDB gui.

**Pull request merged**
