### PR TITLE
OSD link support

### PR DESCRIPTION
**Pull request by LorenzMeier**
This addition makes it easier to configure the TELEM2 port for on screen displays.

### CODE REVIEW

**Comment by AndreasAntener** [comment]
@LorenzMeier Cool :) I quickly checked the arducamOSD code, the following MAVLink messages it's listening to (not all common, I think some are Ardupilot specific):
MAVLINK_MSG_ID_HEARTBEAT
MAVLINK_MSG_ID_SYS_STATUS
MAVLINK_MSG_ID_GPS_RAW_INT
MAVLINK_MSG_ID_VFR_HUD
MAVLINK_MSG_ID_ATTITUDE
MAVLINK_MSG_ID_NAV_CONTROLLER_OUTPUT
MAVLINK_MSG_ID_MISSION_CURRENT
MAVLINK_MSG_ID_RC_CHANNELS_RAW
MAVLINK_MSG_ID_WIND
MAVLINK_MSG_ID_RADIO_STATUS

Although the *WIND* message is commented out. I'm not even sure if this exists?

So I suggest to include the additional streams: *VFR_HUD* and *RC_CHANNELS_RAW*

**Comment by LorenzMeier** [comment]
I assume you have the OSD? Could you add ```configure_stream("VFR_HUD", 25.0f);``` and ```configure_stream("RC_CHANNELS_RAW", 5.0f);``` , drop the rate of attitude to 25 and see if things work as they should?

**Comment by AndreasAntener** [comment]
This works:
```
	case MAVLINK_MODE_OSD:
		configure_stream("SYS_STATUS", 5.0f);
		configure_stream("ATTITUDE", 25.0f);
		configure_stream("GPS_RAW_INT", 1.0f);
		configure_stream("GLOBAL_POSITION_INT", 10.0f);
		configure_stream("ATTITUDE_TARGET", 10.0f);
		configure_stream("BATTERY_STATUS", 1.0f);
		configure_stream("SYSTEM_TIME", 1.0f);
		configure_stream("VFR_HUD", 25.0f);
		configure_stream("RC_CHANNELS_RAW", 5.0f);
		break;
```

But if you think it's on the limit, I think 15Hz for attitude and vfr_hud would be enough too

**Comment by LorenzMeier** [comment]
Rebased and applied to master, thanks!

**Pull request closed without merging**
