### PR TITLE
TECS front transition and weathervane

### PR DESCRIPTION
**Pull request by RomanBapst**
This is just a reference for two other pull requests which are combined here.
@PX4/testflights I updated this since you flew last time, could you test again please?

### CODE REVIEW

**Comment by dannyfpv** [comment]
today tested delta v2
https://review.px4.io/plot_app?log=fdac1297-494d-4c16-a3c7-ba12f562b99f

**Comment by RomanBapst** [comment]
@dannyfpv Thanks for testing! I'll come back with some feedback and some changes.
@dagar I think I cannot push to ecl and therefore my TECS change on the ecl side cannot be checkout out. How do you usually handle this?

**Comment by RomanBapst** [comment]
image

**Comment by RomanBapst** [comment]
image

**Comment by hamishwillee** [comment]
@RomanBapst Really stale?

**Comment by RomanBapst** [comment]
Weathervane is done and front transitions don't rely on TECS.
Maybe this will be revisited if there are stronger requirement regarding controller altitude during front transition. But in that case a dedicated controller for the transition would probably make more sense.

**Pull request closed without merging**
