### PR TITLE
mc pos controller:

### PR DESCRIPTION
**Pull request by tumbili**
- zero attitude setpoint struct in between the loops

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Is this tested?

**Comment by tumbili** [comment]
@LorenzMeier No, we wanted to reproduce the error yesterday but we didn't get consistent results. I'll give it a go in SITL now. But I think it's generally a good idea for all modules, right?

**Comment by LorenzMeier** [comment]
Only if you are sure that you're setting all states again in that struct. Some modules just update the fields that need updating, and resetting would have terrible consequences. So you should not assume its generally a good pattern.

**Comment by AndreasAntener** [comment]
Wrong fix, need to take another look

**Comment by AndreasAntener** [comment]
Was a first attempt at #3795

**Pull request closed without merging**
