### PR TITLE
Pr airspeed fusion

### PR DESCRIPTION
**Pull request by tumbili**
@CarlOlsson @priseborough This takes the airspeed logic fusion out of the ecl library.
This needs testing, especially using the replay for a VTOL.
Also we still need to think about how we want to set the airspeed fusion status flag in the filter.
We could have a method that just sets the flag if the conditions for fusing airspeed are not valid.
Carl will do the same approach for side slip fusion. We will have a parameter which determines if fusion should happen or not.

### CODE REVIEW

**Comment by CarlOlsson** [comment]
Awesome! Will test it on the wingwing today

**Comment by tumbili** [comment]
Jenkins test this please!

**Comment by tumbili** [comment]
@CarlOlsson Any update on this one?

**Comment by CarlOlsson** [comment]
Flashed this to a Pixracer, if I boot up **without** sd card (and RPL active) and write top in NSH everything is ok. If I do the same but **with** an SD card I only get "nsh: top: command not found"

**Comment by tumbili** [comment]
@CarlOlsson Damn, seems like we ran out of ram

**Comment by CarlOlsson** [comment]
yep, works if I decrease the sdlog buffer size to 7

**Comment by CarlOlsson** [comment]
[log](http://logs.uaventure.com/view/CeybVAcdd8gz8ksdZjGUa3) from testflight of this pr. Everything was fine, except the memory issues.

**Comment by CarlOlsson** [comment]
@tumbili do you need something more here to merge?

**Comment by priseborough** [comment]
Have we verified both logging and replay?

**Comment by tumbili** [comment]
Replaced by #4755

**Pull request closed without merging**
