### PR TITLE
Anti windup and logging of rate integrators

### PR DESCRIPTION
**Pull request by tumbili**
If the mixer reports that any motor command has saturated the integrals of the rate controller will not be updated.
Log the rate integrator dynamics for better post-flight analysis.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I agree that we should be logging integrals, but I'm not sure we should be putting those into the attitude control topics. Those are the input to the mixer, and the integral states are unrelated. It almost sounds like we need a completely separate controller status topic which logs the contributions of the inner and outer loops and also the integrals. That would also allow to throttle the publication / logging of the topic to a fraction (e.g. just 20 or 50 Hz).

**Comment by tumbili** [comment]
I actually introduced such a status topic but then I decided to put it into ATTC. If you prefer that I will change it again. I didn't really find any good arguments against it but the mixer is a good point.

**Comment by LorenzMeier** [comment]
Its about system architecture. Unrelated parts of the system should not become linked, because else it deteriorates into what people call spaghetti code eventually.

**Comment by tumbili** [comment]
I get the point :-)

**Comment by LorenzMeier** [comment]
Did you analyze a log already with this? Just to be sure it works.

**Comment by tumbili** [comment]
@LorenzMeier No, not yet. I can do it tomorrow morning.

**Comment by tumbili** [comment]
This is flight tested, everything seems to be ok.
Log: http://dash.oznet.ch/view/XZV9RRQkHPG4JSSJs4MpjW

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
