### PR TITLE
NuttX upgrade cmake wrapper 

### PR DESCRIPTION
**Pull request by dagar**
Continuation of https://github.com/PX4/Firmware/pull/7397, but for updated NuttX.

This is an experiment for wrapping the NuttX build differently, overall making it much faster and allowing better integration with PX4.

 - wraps NuttX per library allowing parallel and incremental builds and tighter integration
 - uses NuttX's mechanism for generating builtins which means we don't need sercon/serdis boilerplate in every single config
 - moves patches into git commits
 - NuttX copy per PX4 build can be done with hard links (where supported) which improves in place editing and debugging
 - treats the px4io as a dedicated build, then imports the binary (significantly cleaner and allows us to start using standard cmake for setting compiler flags)
 - imports NuttX CONFIG flags into PX4 cmake to better handle multiple architectures
 - binaries now placed at top level build dir named ${BUILD}.elf
 - all builds moved to a build/ subdirectory
 - significant cleanup of the build system for PX4 UAVCAN bootloaders
 - split px4fmu-v2 and px4fmu-v3 only handling versioning in v3

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Pretty awesome!

**Comment by davids5** [comment]
@dagar - I still have more testing to do.

**Comment by davids5** [comment]
@dagar - 

Bootloader are working (the ones that will build and fit in flash) - Fantastic job! 
FMUv5 - AOK
NXPHlite-V3 - AOK

So once the CI is happy let's merge it!

**Comment by bkueng** [comment]
@dagar can you please go through the dev-guide and apply the necessary changes?
Build directory `build_xy` vs `build/xy`...

**Comment by dagar** [comment]
Sure, I didn't realize that was even mentioned.

**Pull request merged**
