### PR TITLE
SITL path cleanup

### PR DESCRIPTION
**Pull request by jgoppert**
@LorenzMeier @bkueng @julianoes 

This PR has evolved and is now just SITL cleanup to make  the PX4 cmake files more ROS-user friendly.

## Features 
- auto creation of parameters/ eeprom files  required for SITL
- pass path to data directory to SITL (src directory for devel, /usr/share for install)
- given a working directory, construct the root filesystem with sym-links
- standardize integration tests to use a catkin workspace instead of setting ROS_PACKAGE
- add option to build firmware as a catkin package
- build sitl_gazebo using cmake ExternalProject instead of depending on make
- add hook at beginning of cmake to call check submodules, allows clean cmake build without needing to initialize submodules first

## Progress

- [X] Install to devel directory layout for catkin
- [X] Fix posix tests
- [X] Handle install dependency for testing
- [x] Decide how best to deal with paths (environment variables or args to sitl program)
- [x] Fix ros integration tests

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Can you elaborate what the value add of this PR is over the status quo? What is the use case here?

**Comment by jgoppert** [comment]
@LorenzMeier 

Instead of burying all of the important files and executables for sitl in the build directory, this installs them to a local directory so that the sitl commands require less path manipulations. It also allows closer testing to a system install for end-users.

### For developers:

```bash
make posix_sitl_default gazebo_iris
```

This makes sitl_gazebo and builds posix sitl and installs all files to /devel/bin /devel/share (etc.) then launches gazebo like we are currently doing. The developer can make changes without having to install to the system.

### For end-users:

```bash
make posix_sitl_default package
```

Creates a zip or deb for end-users to install to their system. The make file intelligently switches the CMAKE_INSTALL_PREFIX so that the package is created properly.

**Comment by jgoppert** [comment]
Here is the layout:

```bash
~/git/Firmware$ ls build_posix_sitl_default/devel/*
build_posix_sitl_default/devel/bin:
px4

build_posix_sitl_default/devel/lib:
libgazebo_lidar_plugin.so
libgazebo_opticalFlow_plugin.so
libmav_msgs.so
librotors_gazebo_controller_interface.so
librotors_gazebo_imu_plugin.so
librotors_gazebo_mavlink_interface.so
librotors_gazebo_motor_model.so
librotors_gazebo_multirotor_base_plugin.so

build_posix_sitl_default/devel/share:
gazebo-7  px4
```

**Comment by julianoes** [comment]
@jgoppert thanks for write up.

One thing I don't like is the `devel` directory? Is that needed and is that common practice? Or could you just drop it? Everything would still be in `bin` or `share`, right?

**Comment by jgoppert** [comment]
Yes, devel directory could be dropped. I added it to be similar to catkin approach and clearly separate install files from build files.

**Comment by jgoppert** [comment]
@julianoes, how should I handle the data path, do you think an extra arg to sitl main is a good idea?

**Comment by jgoppert** [comment]
@julianoes I moved devel dir above build dir, so this removes another directory layer and makes it clearer what is going on:

```bash
~/git/Firmware$ ls *sitl*
build_posix_sitl_default:
...
devel_posix_sitl_default:
bin  devel  lib  share  tmp
```

**Comment by jgoppert** [comment]
@julianoes @mcharleb @bkueng @LorenzMeier 

This is close to done. The last part I need to fix is to figure out how to handle the paths for SITL. Currently the mixer program loads the path specified is the rcS file. For instance:

```bash
mixer load /dev/pwm_output0 ../share/px4/ROMFS/px4fmu_common/mixers/quad_w.main.mix
```

This means that the currently working directory for SITL always has to have the same relative path relative to the mixer file.

This isn't very flexible however because I would like the user to be able to specify the directory for the ROMFS and the posix-condfigs. For roslaunch I want to be able to specify the args, something like this:

    <node name="sitl" pkg="px4" type="px4" output="screen" args="$(find px4)/posix-configs/SITL/init/rcS_gazebo_iris" $(find px4)/ROMFS>
    </node>

Note the second argument here: $(find px4)/ROMFS sets the files for the mixer path, but for the mixer load to work I would have to cd to the px4 project directory and then just set all of the relative paths to ROMFS instead of  ../share/px4.

The last part is the rootfs directory that holds the params etc. I am thinking that this should just be created in whatever working directory is called, but if I'm going to be cd'ing to the px4 source dir to have a known path to the mixers for loading, this is going to be problematic, beause my tmp files will be created in the source directory.

**Comment by bkueng** [comment]
I don't see the advantage in a separate devel_ dir either. It makes things less clear and I have enough build_* dirs already. We can simply merge them to be build_$(config)/{bin,lib,share, ...}.

You use `tmp` as CWD for the px4 app. The name could be better, and taking into account #4842, we could name it according to the frame/model being simulated. This way, parameters are automatically separated per model. Then `px4` can take care on startup to create the necessary dir structure in the rootfs (rootfs/fs/microsd, touch parameters, ...)
This makes it also possible to start eg. an installed `px4` from a users home directory.

For the mixer paths: #5162 enables to use shell variables in our scripts, so we should also make use of this. For example on script startup we can do:
```
base_dir="$(dirname "$0")"
```
This way we know where the rcS main file is and can load the mixer files relative to that:
```
mixer load /dev/pwm_output0 $base_dir/../mixers/quad_w.main.mix
```

This works from build_ & with an installed px4, eg like this:
```
px4 /usr/share/px4/posix-configs/SITL/init/rcS_gazebo_iris
```
- creates the rootfs in CWD
- finds & uses the mixer files in /usr/share/....
- clear separation between install & develop dirs
- no need for chroot or changing directories within `px4` app

what do you think?

**Comment by jgoppert** [comment]
@bkueng I am using /tmp now for the current working directory, or ~/.ros if using catkin and I'm sym-linking it all in and creating and missing files on the fly (parameters etc.). I just have a few more bugs to fix before it is all working. I moved away from the devel directory and am tying everything in to work with/without install and also as a legitimate catkin package.

**Comment by bkueng** [comment]
Good to know. Of course my solution is only a suggestion. But I think it would be good to first discuss pros & cons for different solutions. It would spare you some effort.

With `/tmp` you don't mean in rootfs/ but really `/tmp`? This is not good because parameters and log files don't survive a reboot.

**Comment by jgoppert** [comment]
@bkueng If we want to add the variables to the script we can do that, but the symlink approach seems to be working pretty well. As far at the working directory, it is easily changeable if you think it should be somewhere else, maybe ~/.px4? We could also put it is the build directory.

**Comment by bkueng** [comment]
If they don't make things much more complex, and don't need to be at a fixed path, symlinks are fine.
Yes, as mentioned (-> #4842), CWD should be in the build directory, and preferably different per model.
This way everything is at one place, which facilitates a clean rebuild.

**Comment by jgoppert** [comment]
@bkueng I agree, makes sense, I will move them into the build dir. I've had to get very deep into the cmake guts of catkin and they use symlinks everywhere, so I don't think it will be very hard to maintain.

**Comment by dirk-thomas** [comment]
I am not sure if supporting the devel space of catkin is really necessary. If you make the package of build type `cmake` and just follow normal CMake guidelines (e.g. having install rules) you can build the package with `catkin_make_isolated` or `catkin build` (not with `catkin_make` though) which I think would be sufficient.

But if you want to support the devel space of catkin you still need to make sure that a real install of the package works well too. The devel space is only a shortcut for local development.

**Comment by jgoppert** [comment]
@dirk-thomas Thanks for taking a look at this.

* I am working on getting the install working as well so I can distribute deb files to some of my end-users for use with ROS.

* I think the catkin devel workspace would be a benefit because many of the px4 developers prefer to be able to execute tests etc. without install.

* Currently the cmake files do install all necessary targets/resources and you can create a debian with cpack.

* When the sitl program starts, it takes the path to the data directory and then creates symlinks in the local workspace to simulate the on-board file system. It also generates new empty files if necessary for parameters etc.

Let me know if you think I can do anything in a more straightforward way from your perspective.

**Comment by dirk-thomas** [comment]
> I think the catkin devel workspace would be a benefit because many of the px4 developers prefer to be able to execute tests etc. without install.

A package can still run tests before installation even without supporting the devel space. Any plain CMake package runs its tests via CTest without the installation step.

**Comment by jgoppert** [comment]
@dirk-thomas Good point, would be pretty easy now that I've set it up to take the data path as an arg.

What I want to do is drop PX4/Firmware in a catkin workspace with a lot of my other packages for offboard control/ computer vision/ gazebo and just have it work out of the box after sourcing ./devel/setup.bash. So that is my motivation. And I think I already have that 95% working.

One confusing part for me is whether or not I could include catkin_package() if catkin is found on the system? What does including catkin_package() do for me? It seems to change all of my cmake install paths and create the symlinks necessary for the devel workspace correct?

**Comment by jgoppert** [comment]
Answering my own question below:

catkin_package.cmake

```cmake
# It installs the package.xml file, and it generates code for
# ``find_package`` and ``pkg-config`` so that other packages can get
# information about this package.  For this purpose the information
# about include directories, libraries, further dependencies and
# CMake variables are used.
```

So the paths shouldn't change and I should be good with or without catkin_package?

**Comment by dirk-thomas** [comment]
`catkin_package()` internally calls `catkin_package_xml()` which calls `catkin_destinations()`. This function changes the location where executables and libraries are being dropped (https://github.com/ros/catkin/blob/d0c4ecb3bac9b38a0883253e1e350d3fb72c4a6f/cmake/catkin_destinations.cmake#L54-L57), This avoids requiring to copy / move the artifacts to the devel space after they have been built.

**Comment by jgoppert** [comment]
All the tests pass but it says results are outdated.  Can anyone take a look at my run_tests.sh and see what I messed up?

**Comment by jgoppert** [comment]
@LorenzMeier @bkueng @julianoes  This is ready to merge, please review.

**Comment by LorenzMeier** [comment]
@bkueng Can you take another pass? I'm available to discuss it in about two hours.

**Comment by bkueng** [comment]
@LorenzMeier I was already on it.
@jgoppert Looks much better already! Some initial remarks:
- jmavsim fails (` line 74: cd: Tools/jMAVSim: No such file or directory`)
- help output for px4 app is incomplete (both data-dir & startup config are non-optional)
- please use proper log levels: `Creating symlink...` is a debug output and `Error opening commands file` is an error not a warning.
- I'd use a buffer size of 256 for cwd, 100 might be too short.

**Comment by jgoppert** [comment]
@bkueng Let me know if I caught everything.

**Comment by LorenzMeier** [comment]
Can you rebase on master instead of merging?

**Comment by jgoppert** [comment]
@LorenzMeier sure, just rebased on master. Will squash and merge if tests pass and everyone is happy with it.

**Comment by LorenzMeier** [comment]
Well I don't think we actually concluded this is through final review - it would be good if we could have a final sign-off before we merge such a massive change.

**Pull request merged**
