### PR TITLE
Posix shell updates

### PR DESCRIPTION
**Pull request by bkueng**
@julianoes

### CODE REVIEW

**Comment by bkueng** [comment]
SITL shell now looks like this:
screenshot_colored_output

**Comment by LorenzMeier** [comment]
Nice!

**Comment by julianoes** [comment]
Why did you add a silently_fail option? Shouldn't we get informed in that case?

**Comment by bkueng** [comment]
This is only set for the built-in call `muorb stop`, which is not available on SITL. If you currently do Ctrl-C in SITL you always see

**Comment by julianoes** [comment]
@bkueng: Ok, makes sense.

**Comment by bkueng** [comment]
rebased & applied

**Pull request closed without merging**
