### PR TITLE
Fixlogname

### PR DESCRIPTION
**Pull request by kd0aij**
for some reason, log_file_path was missing the null terminator
This change tests OK for me and adds timestamps to each log entry

### CODE REVIEW

**Comment by kd0aij** [comment]
```
nsh> cat /fs/microsd/msgs_2016_04_25_16_28_42.txt
2016_04_25_16_28_42: [inav] GPS signal found
2016_04_25_16_28_43: [inav] init ref: 39.7502784, -105.0980037, 1712.5
2016_04_25_16_31_23: [cmd] ARMED by command line
2016_04_25_16_31_23: [blackbox] /fs/microsd/log/2016-04-25
2016_04_25_16_31_23: [blackbox] recording: 16_31_23.px4log
2016_04_25_16_31_43: TAKEOFF DETECTED
2016_04_25_16_31_47: LANDING DETECTED
```

**Comment by LorenzMeier** [comment]
With travis fixed looking good.

**Comment by LorenzMeier** [comment]
@kd0aij What I meant to say: You need to fix the build 8). But otherwise looking good.

**Comment by kd0aij** [comment]
trying to find the posix definition of FILE

**Comment by LorenzMeier** [comment]
```
#include <stdio.h>
```

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
