### PR TITLE
Reset _transfer_in_progress if mavlink transfer times out.

### PR DESCRIPTION
**Pull request by lovettchris**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looking good!

**Comment by lovettchris** [comment]
That was quick!  15 minute pull request turnaround time :-)

**Comment by LorenzMeier** [comment]
Thanks for providing. Was an obvious fix. I usually look at PRs in close to real time, but almost always it requires longer time to properly review.

**Comment by lovettchris** [comment]
Hey I'd love to get your feedback on this issue too:
https://github.com/PX4/jMAVSim/issues/29

**Pull request merged**
