### PR TITLE
Increase rolling average on filtered current

### PR DESCRIPTION
**Pull request by sanderux**
Current is still somewhat erratic with some current sensors, this will improve a/v calibration

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@sanderux How about the plot?

**Comment by sanderux** [comment]
Havent gotten round to it

**Comment by sanderux** [comment]
image

**Comment by sanderux** [comment]
@jgoppert ping

**Comment by sanderux** [comment]
@jgoppert any thoughts?

**Comment by LorenzMeier** [comment]
I'm sorry but I have to reject this. On a recent system analysis I saw that our filtering is already hiding real system issues, so increasing it is not the right approach.

If you are trying to even out battery estimation then you should filter the charge level more.

**Comment by LorenzMeier** [comment]
I'm not deleting the branch in case you want to continue it and move the filtering to a different location.

**Comment by sanderux** [comment]
@LorenzMeier Is there another way to solve the calibration issue?

**Comment by LorenzMeier** [comment]
Let's discuss on the dev call tomorrow. I don't think this is the right solution for a calibration issue, but I'm sure you are facing a real issue and we can find the proper fix.

**Comment by sanderux** [comment]
Add rolling average to QGC

**Pull request closed without merging**
