### PR TITLE
Implemented SK450 DeadCat frame support

### PR DESCRIPTION
**Pull request by anton-matosov**
Implemented SK450 DeadCat frame support
Implemented the way to specify motor output scale which is required for SK450 DeadCat as it has asymetrical arms (front arms are longer than back ones)

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looks good to me.

**Comment by LorenzMeier** [comment]
You will want to rebase this onto master like this:

```
git fetch upstream
git rebase upstream/master --interactive
```
https://help.github.com/articles/about-git-rebase/

I expect one conflicting line, but since you did both changes, that should be trivial. I assume this is flight tested? If / once it is, I'm happy to merge it.

Thanks!

**Comment by anton-matosov** [comment]
Rebased and flight tested. Works fine

**Comment by LorenzMeier** [comment]
What is the difference between the 'w' / wide mixer and the dc mixer?

**Comment by anton-matosov** [comment]
They have different angles (5 deg difference for front rotors, 6 deg back). In addition DC's one has extra correction for the arms length (back arms are 96% of the front)

**Comment by LorenzMeier** [comment]
Ok, got it!

**Pull request merged**
