### PR TITLE
Add optical flow integration test.

### PR DESCRIPTION
**Pull request by jgoppert**
This adds integration testing for optical flow with lpe and fixes a few bugs found via the testing.

### CODE REVIEW

**Comment by jgoppert** [comment]
It doesn't appear the ci server can render the images for the optical flow ci test?

```bash
gzserver: /usr/include/boost/smart_ptr/shared_ptr.hpp:653: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = gazebo::rendering::Camera; typename boost::detail::sp_member_access<T>::type = gazebo::rendering::Camera*]: Assertion `px != 0' failed.
Aborted (core dumped)
```

I'll comment the flow ci test out and merge this if it passes then because there are some critical fixes for lpe + flow in this patch.

**Comment by dagar** [comment]
Does the environment source the gazebo setup.bash?

**Comment by jgoppert** [comment]
@dagar it doesn't source setup_gazebo.bash, it uses the catkin workspace that I create in integrationstests/run_tests.bash, the paths are set using gazebo_ros. The px4 ros package exports the  paths. This all works locally on my machine and for the other integration tests, so I think it is something specific to the camera rendering.

**Comment by dagar** [comment]
It's using this docker image (https://hub.docker.com/r/px4io/px4-dev-ros/) if you'd like to reproduce it locally and figure out what's missing.

    docker pull px4io/px4-dev-ros

Then add the missing packages/setup here - https://github.com/PX4/containers/blob/master/docker/px4-dev/DockerfileRos

**Pull request closed without merging**
