### PR TITLE
trying to enable vmount on px4fmu-v2

### LINKED ISSUE #7085: px4fmu_V2 upgrade issue: nsh: vmount: command not found
When I upgrade the firmware on my Pixhawk v2 to the latest bits (sync'd today), clean clone, & build of master branch, make px4fmu-v2_default, I get the following boot error:
```
ERROR [param] Parameter MNT_MODE_IN not found
nsh: vmount: command not found
```
This happens on multiple pixhawks.  If I go back to latest stable build using QGroundControl then it boots fine.

Curiously if I add the drivers/vmount driver in the cmake/configs/nuttx_px4fmu-v2_default.cmake, then it boots fine.  So what do I need to do to make it boot without this driver since it is supposed to be commented out now... ?

### PR DESCRIPTION
**Pull request by bkueng**
and make sure that boot is not aborted if `vmount start` fails.

`make sizes` before:
```
977344    6452   18676 1002472   f4be8 build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx
```
`make sizes` after:
```
983516    6452   18676 1008644   f6404 build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx
```

Fixes #7085

### CODE REVIEW

**Comment by ndepal** [comment]
Can you explain to me why boot is aborted if a module start fails? I've run into this several times and it ends up costing me quite some debugging time because the device then no longer connects to QGC. Is this a desirable behavior?

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rcS#L3

If a module failed silently and bootup "succeeded" would it ultimately be more annoying to debug?

Maybe we need something verifying that the required modules are running and responding.

**Comment by ndepal** [comment]
Not sure if that would be better. Ideally the user would be notified about all failed starts.

In the case of vmount, the parameter which decides whether it should be started is only defined if vmount is compiled in. If it's not in the firmware, the parameter does not exist and that `if` statement in rcS is still entered, causing an incomplete boot. That seems to invite problems down the road if/when vmount is removed from a build due to flash constraints.

So do I understand correctly that, without `set +e`, a failed module start causes the pixhawk to be unresponsive because `mavlink boot_complete` is never reached?

**Comment by mhkabir** [comment]
> So do I understand correctly that, without set +e, a failed module start causes the pixhawk to be unresponsive because mavlink boot_complete is never reached?

Yes.

**Comment by mhkabir** [comment]
> That seems to invite problems down the road if/when vmount is removed from a build due to flash constraints.

This construct avoids that (by consuming the return value from the start command) : 
```
if vmount start
then
fi
```

**Comment by ndepal** [comment]
Thanks for the clarifications, @mhkabir @dagar !

**Pull request merged**
