### PR TITLE
HoTT Telemetry Update

### PR DESCRIPTION
**Pull request by ChukRhodes**
Still a work in progress... this adds a couple more "sensor" types, and
more info and options are available from command line. A MZ-24 shows all
available sensors as active. This still needs uorb messages to show
"live" data.

Builds under PX4F and APM with adding/enabling only :
drivers/hott/hott_telemetry

Tested only under APM.

dsc01673
dsc01674

### CODE REVIEW

**Comment by ChukRhodes** [comment]
BTW, the most reliable connection seems to be start the Pixhawk/Receiver (power on), start hott_telemetry, then power on receiver.  Other combinations seem to cause some syncing issues. Eventually, a receiver not getting sensor responses gives up, but still sends data on the port - a power cycle seems to be the only fix (aside from an unknown response it may be expecting).

**Comment by LorenzMeier** [comment]
@SimonWilks @AndreasAntener Could you please help out with review / testing / integration, assuming that you guys are still using Graupner?

**Comment by sjwilks** [comment]
@ChukRhodes sorry for the delay on reviewing this. I have my HoTT setup working again so I can help.

When do you plan to use and transmit real data rather than hardcoded values? In some places where real data is already used you replaced it with hardcoded values as well so for that part it's a step backwards.

How about setting defaults (hardcoded) for what's not yet available and reactivating what is? Then we can get this in and complete the rest later.

**Comment by julianoes** [comment]
What's the state here? Should this still go in? Has it been tested?

**Comment by LorenzMeier** [comment]
@sjwilks @SimonWilks Where is this standing from your side?

**Comment by SimonWilks** [comment]
We can close this. I'll pull more in from this via new PR's.

**Pull request closed without merging**
