### PR TITLE
WIP: Vtol TECS fix

### PR DESCRIPTION
**Pull request by AndreasAntener**
@tumbili new tecs fix branch off master

### CODE REVIEW

**Comment by AndreasAntener** [comment]
With this branch, the desired airspeed is nicely ramped up after the transition. I did 2 flights in altitude control (which is btw awesome to fly the standard VTOL in):

tecs init flight 1
http://logs.uaventure.com/view/ArZvMEN93W9uMHHU4igTed

tecs init flight 2
http://logs.uaventure.com/view/zrRkhmi35oGRRZiq9fTcPm

In flight 1 you still see that TECS has a huge pitch integrator to start with. There must be something wrong there when TECS starts. In the following transitions and in flight 2 you never see any integrator when it starts, so I'm assuming it's correctly reset.

**Comment by AndreasAntener** [comment]
Another log from yesterday afternoon where the init was ok: http://logs.uaventure.com/view/Gi8kX8ho4oaye8gcjjS5sd

**Comment by LorenzMeier** [comment]
Are you saying we should merge?

**Comment by AndreasAntener** [comment]
No :) This should be flight tested a bit more, also I need to fix AUX logging so I see FW thrust during the transition which is also one of the reasons for this fix.

**Comment by LorenzMeier** [comment]
Aux logging is fixed on master (as far as implemented).

**Comment by AndreasAntener** [comment]
Two more flights:
mission http://logs.uaventure.com/view/gVUinykcLifN6tCpvTTrW6
altctl http://logs.uaventure.com/view/943VqsD7bbhZq5hX9vzCUf
not analyzed yet

**Comment by AndreasAntener** [comment]
Looked good in both flights:
screen shot 2016-02-12 at 18 04 01

VTOL att contorller is holding thrust until tecs/fw pos is publishing, TECS is reinitialized and airspeed setpoint ramps up. The only thing I don't like now is the thrust dip after the transition, could also still be smoothed out.

@tumbili I implemented the thrust holding for standard vtol, how does it look tailsitter and tiltrotor?

**Comment by AndreasAntener** [comment]
TODOs
- implement wait_on_fw for tailsitter and tiltrotor
- copy MC state until finished waiting so the attitude setpoint doesn't jump to an undefined value

Flight test
- try setting a higher transition speed, e.g. min speed + 1

**Comment by AndreasAntener** [comment]
@tumbili I made the FW position controller aware of when TECS is running and using a 0 pitch and thrust setpoint if not. The irregularity we had before was due to stale TECS data published before it started to run (and reset) again.

**Comment by tumbili** [comment]
@AndreasAntener I had a look and it looks good to me. Looking forward to some flight results.
Especially, for the planes of Marco and Sanders I hope to see some difference. They were always diving quite a bit.

**Comment by sanderux** [comment]
I think i can fly this tomorrow

**Comment by sanderux** [comment]
2 logs of successful missions and one with induced rc loss failsafe RTL;
RTL mission 1: http://logs.uaventure.com/view/3msrKYiSjKrDvKKckveA4e
Full mission 2: http://logs.uaventure.com/view/7y4hdAoz4Bsog8K24qE67c
Full mission 3: http://logs.uaventure.com/view/x7RvfZX3MVfCrnVgocbUoG

For reference here a manual hover log with one yaw turn:
http://logs.uaventure.com/view/YXLzTNbzjasnmqnaQfjMBY

**Comment by sanderux** [comment]
Wobbly back transition, see missions 2 and 3. and video at 4:27
The wobble wasnt there in the transition that happened when switching to manual mode in mission 1

**Comment by AndreasAntener** [comment]
Mission flight on master (without this branch): http://logs.uaventure.com/view/57bJPThtDayp6ZXCQ2guTQ
mission: http://logs.uaventure.com/view/GanJap84VKsX4scBe7Zk5C
altctl: http://logs.uaventure.com/view/vY8d5Hdufkwip8gCobdqEL
abort after transition because it got blown away by wind: http://logs.uaventure.com/view/zQ5WKTyQcqPMJdhLHBD6Zg

**Comment by sanderux** [comment]
After changing some parameters MUCH better performance:
new mission 1: http://logs.uaventure.com/view/zCiXVJtTPNoPNZ7e2cn4h
new mission 2: http://logs.uaventure.com/view/SGutTXNPo92waZE5UBkGSK

**Comment by sanderux** [comment]
There 2 missions with new params were identical.
I do see strange altitude behavior when comparing both:

Mission 1:
alt 1

Mission 2:
alt 2

**Comment by AndreasAntener** [comment]
New test flights, in 0 wind, higher transition speed, and 0 speed weight:
http://logs.uaventure.com/view/2AZKfJ5DHxbAmbbmsg4dr8
http://logs.uaventure.com/view/qjFVbGSC4ACEzeCN3UcMRB
very nice

**Comment by tumbili** [comment]
@AndreasAntener This is tested with tailsitter in SITL.

**Comment by LorenzMeier** [comment]
@AndreasAntener Can we merge this?

**Comment by LorenzMeier** [comment]
Awesome work! Rebased and applied (and I checked that I had Roman's rebased branch and the diff is clean).

**Pull request closed without merging**
