### PR TITLE
Fix Hardware-in-the-loop (HITL)

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by TSC21** [comment]
@argowaner FYI

**Comment by TSC21** [comment]
@LorenzMeier me and @arwagoner were actually facing some weird issues with HITL while adding support for it on Gazebo. @arwagoner will soon add a PR for `sitl_gazebo` with the support for HITL, including a serial interface and a proxy to QGC. The thing to notice is that it works good with 1.6.5. Let's hope this actually fixes for master.

**Comment by TSC21** [comment]
Jenkins test this please.

**Comment by LorenzMeier** [comment]
@arwagoner Any news?

**Comment by arwagoner** [comment]
@LorenzMeier, I just tested these changes. They did fix the problems I was seeing with HIL in Gazebo. I am no longer getting any of the sensor errors. Thanks! 
gazebo_hitl

**Comment by TSC21** [comment]
Jenkins test this please.

**Comment by arwagoner** [comment]
@LorenzMeier I was able to use an unsupported airframe (standard vtol) in HIL mode without seeing this error. https://github.com/PX4/Firmware/pull/8532/files#diff-20f2c9d76df9330422532b87ab964f86R526

Why are the airframes limited for HITL?

**Comment by LorenzMeier** [comment]
They are limited because our HITL tools are limited and knowing that our users don't read documentation that's safer than having them fiddling with it for hours.

**Comment by hamishwillee** [comment]
> They are limited because our HITL tools are limited and knowing that our users don't read documentation that's safer than having them fiddling with it for hours.

The fact that you can't just select whatever airframe you like is also confusing. I'm also not sure that we've properly got those limitations documented so that people could read them (if they wanted).

So while it is certainly good to expose only what we know works, can we:
- Get a list of those limitations (so we can better understand what can/cannot be fixed)
- Work towards opening more airframes up for use?

**Pull request merged**
