### PR TITLE
CI: Update container tags

### PR DESCRIPTION
**Pull request by TSC21**
This brings https://github.com/PX4/containers/pull/133 in.

### CODE REVIEW

**Comment by TSC21** [comment]
We still need AppVeyor to bring the changes in PX4/containers#133. @MaEtUgR

**Comment by TSC21** [comment]
Any ideas about why is this happening: http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-compile/detail/PR-10428/4/pipeline/#step-916-log-15 ?

**Comment by dagar** [comment]
We'll need to do another pass in https://github.com/PX4/containers to force the base to the ubuntu1604 version.

**Comment by TSC21** [comment]
Ok so can you provide a roadmap so I can start doing that? This is just to avoid having CI blocking the development based on dependencies.

**Comment by TSC21** [comment]
@dagar any idea of what is causing this http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-compile/detail/PR-10428/4/pipeline/#step-916-log-15?

**Comment by dagar** [comment]
Continued in https://github.com/PX4/Firmware/pull/10463

**Pull request closed without merging**
