### PR TITLE
ros workspace setup scripts: use master branch

### PR DESCRIPTION
**Pull request by thomasgubler**
@AndreasAntener

### CODE REVIEW

**Comment by AndreasAntener** [comment]
:+1: I added a "px4io" organization on Docker Hub, it will then build the image from px4/Firmware/master. Could you add the Docker Service in the Firmware repository settings? (so Docker gets notified on pushes)

**Comment by LorenzMeier** [comment]
I have created the link to Docker Hub in Github - did it trigger from the master push a few minutes ago? Have a link to the docker org?

**Comment by AndreasAntener** [comment]
Yes, seems to work :)
https://registry.hub.docker.com/u/px4io/px4-ros-full/builds_history/136254/

**Comment by LorenzMeier** [comment]
Cool - should we update the wiki instructions to have people pull this docker image?

**Comment by AndreasAntener** [comment]
Sorry for the late replay, yes, I updated the wiki right after the first build finished :)
Maybe we should pull the Docker stuff out of the Firmware repository, apparently the Hub builds the image on every push..

**Pull request merged**
