### PR TITLE
improve mavros SITL tests

### PR DESCRIPTION
**Pull request by lamping7**
PR created to have Jenkins test this to see if it helps https://github.com/PX4/Firmware/issues/8556.

- created a test base class to centralize redundant methods among the different tests
- added mission waypoint list topic listener (this also helps make sure the simulation is ready)
- check number of mission waypoints in FCU against mission
- increase time for mavros topics to be ready from 30 to 60 seconds
- reduced loop rates for position checks

EDIT: See commit message for additions/fixes that were "riders" with this PR. yapf with default settings is used to format .py files.

### CODE REVIEW

**Comment by mrpollo** [comment]
thanks for the cleanup @lamping7 👍

**Comment by dagar** [comment]
Looks good to me. Let me know if you'd like to merge, or continue testing.

**Comment by lamping7** [comment]
I had the CI run this a bunch of times. Unfortunately, Jenkins dropped the build history, so I can't see what happened with them all.

I caught one failure before it was dropped. It was a VTOL mission and the vehicle never took off. See https://logs.px4.io/plot_app?log=8d3e2c55-d688-40bb-89b7-6ec8a9fee524

I'd like to re-run this more after Jenkins is fixed up to not drop the results.

**Comment by LorenzMeier** [comment]
Cool, getting there!

**Comment by lamping7** [comment]
@dagar Good to go. Build will fail due to Jenkinsfile.

**Comment by dagar** [comment]
Great work!

**Pull request merged**
