### PR TITLE
Mem cleanup

### PR DESCRIPTION
**Pull request by LorenzMeier**
@julianoes Could you please test this by re-flashing Snapdragon AND the Pixfalcon connected to it?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@bkueng Please review.

**Comment by LorenzMeier** [comment]
We're now here.

@davids5 Things that I would like to understand if they are needed:

  * channel_stats
  * The size of g_dma_heap (can we add the usage to our top command?)

```
536899476 00000064 b io_timer_channel_stats
536887317 00000064 b log_dir
536885184 00000064 B sp_man
536898432 00000064 b stm32_exti_callbacks
536875956 00000068 B _ZN12PX4IO_serial11_dma_bufferE
536884976 00000080 B _ZN17snapdragon_rc_pwm3_rcE
536870972 00000080 D _ZN6ms561111bus_optionsE
536892913 00000128 b g_usart1rxbuffer
536873414 00000129 d g_bootcodeblob
536885948 00000168 B streams_list
536871724 00000184 D g_sdiodev
536872104 00000196 d g_uart4priv
536873084 00000196 d g_uart7priv
536871908 00000196 d g_uart8priv
536872496 00000196 d g_usart1priv
536872300 00000196 d g_usart2priv
536872888 00000196 d g_usart3priv
536872692 00000196 d g_usart6priv
536899152 00000256 b channel_stats
536889788 00000256 B g_pidhash
536892357 00000256 b g_uart4rxfifo
536894441 00000256 b g_uart7rxfifo
536892101 00000256 b g_uart8rxfifo
536896497 00000256 b g_usart1rxfifo
536890957 00000256 b g_usart2rxfifo
536891845 00000256 b g_usart3rxfifo
536897053 00000256 b g_usart6rxfifo
536884694 00000272 b _ZZ26mavlink_get_channel_bufferE16m_mavlink_buffer
536892613 00000300 b g_uart4rxbuffer
536895297 00000300 b g_uart4txbuffer
536894141 00000300 b g_uart7rxbuffer
536896197 00000300 b g_uart7txbuffer
536896753 00000300 b g_uart8rxbuffer
536897309 00000300 b g_uart8txbuffer
536894697 00000300 b g_usart3rxbuffer
536891545 00000300 b g_usart3txbuffer
536894997 00000300 b g_usart6rxbuffer
536891213 00000300 b g_usart6txbuffer
536898496 00000320 b g_otgfsdev
536873700 00000340 D _uorb_topics_list
536890604 00000348 B g_mmheap
536890072 00000408 b g_idletcb
536889332 00000416 B g_irqvector
536871276 00000448 d g_dma
536888797 00000512 b g_iobuffer
536895597 00000600 b g_usart2rxbuffer
536897616 00000748 b up_interruptstack
536887528 00000792 B system_load
536893041 00001100 b g_usart2txbuffer
536876096 00008192 b g_dma_heap
```

Here is the complete command for reference:

```
make px4fmu-v2_default && arm-none-eabi-nm --size-sort --print-size --radix=dec build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx | grep " [bBdD] 
```

**Comment by LorenzMeier** [comment]
@julianoes I need to pull this in as its killing us on VTOL.

**Comment by LorenzMeier** [comment]
rebased and applied.

**Comment by davids5** [comment]
@LorenzMeier 

> @davids5 Things that I would like to understand if they are needed:
>
>channel_stats
> The size of g_dma_heap (can we add the usage to our top command?)
>536899152 00000256 b channel_stats

channel_stats 256B is from the timer capture code - it is 8 bytes * MAX_TIMER_IO_CHANNELS
We have several option. 
1. Make it a dynamic allocation 
2. Remove it -This is available via an IOCTL - we could ask the "timer capture" user base if there using the info at runtime. 
3. ifdef it for debug only

io_timer_channel_stats 64B is from the io_timer code - it is 8 bytes * MAX_TIMER_IO_CHANNELS
1. Remove it - not exported
2. ifdef it for debug only


General observation is:
MAX_TIMER_IO_CHANNELS is pushed up to 8 because of the areocore and pio config. 
MAX_IO_TIMERS is 4 and could be 2 for FMUVx 
It could be 6 for FMUVx and we if we drive the size from the board_config file we can save both FLASH and SRAM (small amounts)

**Comment by davids5** [comment]
@LorenzMeier 

> @davids5 Things that I would like to understand if they are needed:
>
>channel_stats
> The size of g_dma_heap (can we add the usage to our top command?)
>536871276 00000448 d g_dma
> 536876096 00008192 b g_dma_heap

g_dma 28 bytes * the 2 STM32 DMA * streams per DMA - it has state for DMA

Options:
1) Review all the DMA and stream assignments used in PX4 and possible drop us doen to 1 DMA,
sizeof(g_dma) \= 2 (this may be limiting or not - review would tell us)

2)- 8 bytes could be moved to const - So it is somework but doable.

g_dma_heap - is in support of the FAT fs dma on the SD card. It should be 512 per open and 512 per mount. I will move the allocator to the common code base and expose an api for top. Then we can adjust it as need be.

**Comment by davids5** [comment]
@LorenzMeier 

DMA Memory: 8192 total, 1024 used 1536 peek

This was with a cat of /fs/microsd/fault_2000_01_01_07_14_49.log

What would be the best stress test?

**Comment by davids5** [comment]
@LorenzMeier 

See https://github.com/PX4/Firmware/pull/4707 adds the usage to our top command

**Pull request closed without merging**
