### PR TITLE
Auto - Update velocity setpoint generator to avoid overshoot at high cruise speed

### PR DESCRIPTION
**Pull request by bresch**
The problem with the current velocity setpoint generator in auto mode is that it assumes a linearly increasing breaking distance. This approximation is good at 5m/s but gets rapidly wrong when the cruise speed in increased. This leads to large overshoots at waypoints and also depends on the maximum acceleration parameter.
To solve this issue, a better approximation is made by assuming square acceleration profile with a scaling to handle the imperfection of this formula. This gives a much better approximation and enables higher cruise speeds without having to adapt the trajectory gain.

Before this PR, with a desired cruise speed of 20m/s:
https://logs.px4.io/plot_app?log=5bb6edfb-4f75-4ca9-8ff1-e42d10ada588
bokeh_plot(18)

With this PR:
https://logs.px4.io/plot_app?log=eba40d2b-ef50-46da-bb0f-c0e512eb16f2
bokeh_plot(19)

replaces #11841

### CODE REVIEW

**Comment by bresch** [comment]
@PX4/testflights Can you thy this PR with different cruise speeds please?
`MPC_CRUISE_SPEED` = 5, 8, 10

**Comment by dannyfpv** [comment]
Tested on Pixhawk4 mini v5
Modes Tested: 

Position Mode: no issue 
mission mode : no issues
Vehicle type: Quadrotor
Airframe: DJI Flame Wheel F450, Quadrotor x
Hardware: PX4_FMU_V5 

log MPC_XY_CRUISE = 5 m/s
https://review.px4.io/plot_app?log=f560ffd1-c49d-40f9-b6f1-bd1a534a8674

log MPC_XY_CRUISE = 8 m/s
https://review.px4.io/plot_app?log=cc101b3b-2ca6-407c-b52e-886aa9c00f3b

log MPC_XY_CRUISE = 10 m/s
https://review.px4.io/plot_app?log=3d55cf6d-ea17-4713-aa8d-e69dfc4cf3d5

**Comment by bresch** [comment]
Perfect, thanks a lot @dannyfpv  !

**Comment by jkflying** [comment]
I did something similar here to make sure we don't exceed safe velocities in the avoidance given our sensor range: https://github.com/PX4/avoidance/blob/b31d149a7433a261f6365c32bb02f12fd1727330/local_planner/src/nodes/local_planner.cpp#L288
It also conservatively takes into account the acceleration ramp-up time based on the jerk limit, by assuming no velocity change happens until acceleration is saturated.

**Comment by bresch** [comment]
@jkflying Thanks for the review. I decided to use your approach but I doubled the acceleration rise time to take in account the case where the current acceleration is opposite. I'll fly it again today

**Comment by bresch** [comment]
@PX4/testflights can you try that PR again please?
You can even go to higher speeds (I went up to 20m/s this afternoon). 
Don't forget to increase the maximum speed `MPC_XY_VEL_MAX` to ~22m/s if you want to set the cruise speed at 20m/s.

**Comment by bresch** [comment]
Flight at 20m/s with the new logic : https://logs.px4.io/plot_app?log=9ae356b7-8d8f-448b-9751-c7e57f69cd2b

**Comment by dannyfpv** [comment]
Tested on Pixhawk4 v5
Modes Tested:

Position Mode: no issue
mission mode : no issues
Vehicle type: Quadrotor
Airframe: DJI Flame Wheel F450, Quadrotor x
Hardware: PX4_FMU_V5

logs MPC_XY_CRUISE = 20 m/s
MPC_XY_VEL_MAX to ~22m/s
https://review.px4.io/plot_app?log=a336879d-cf80-468e-9d7f-0f67281aa7e8
https://review.px4.io/plot_app?log=2f146332-3709-40d3-9cb2-ac011f96a7a9

**Comment by jorge789** [comment]
### Tested on PixRacer V4:

Note:The parameter MPC_XY_VEL_MAX was changed to 22m / s and MPC_XY_CRUISE to 20m / s.

Flight Card 3

**Modes Tested**
Position Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
Vehicle was constantly oscillating during the flight; this could be seen in position, mission and RTL mode.
Loaded master to see if the issue persisted but it was not the case, vehicle flew as expected without oscillations.

**Logs:**
https://review.px4.io/plot_app?log=042d0074-6c9d-4af7-a4c5-4e77bc202963

https://review.px4.io/plot_app?log=ca72ff65-b0a0-47b9-a578-428db63deb3a

**Logs: Comparison to master**
https://review.px4.io/plot_app?log=2655c0a7-dee4-45fc-ae4a-7757831200ed

**Tested on Pixhawk 2 Cube V3:**

Note:The parameter MPC_XY_VEL_MAX was changed to 22m / s and MPC_XY_CRUISE to 20m / s.

Flight Card 3

**Modes Tested**
Position Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
Vehicle was constantly oscillating during the flight; this could be seen in position, mission and RTL mode.
Loaded master to see if the issue persisted but it was not the case, vehicle flew as expected without oscillations.

**Logs:**
https://review.px4.io/plot_app?log=cea0e989-0474-4e84-8b87-b546d32528e1

https://review.px4.io/plot_app?log=b373a2d3-b068-422d-92f7-569fe45cd995

**Logs: Comparison to master**
https://review.px4.io/plot_app?log=6e5db31a-f67a-410f-8252-2e54622c5468

**Comment by Junkim3DR** [comment]
### Tested on Pixhawk Pro v4:
_Note: Parameters MPC_XY_VEL_MAX was changed to 22m/s and MPC_XY_CRUISE to 20m/s._

**Modes Tested**
Position Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
No issues noted, good flight in general.

**Logs:**
- https://review.px4.io/plot_app?log=59f11fa4-2a44-4229-83a1-2dfb91183d2d

- https://review.px4.io/plot_app?log=9190caf4-ba08-456a-8b0e-b6c4fb0bd995






**Tested on NXP FMUK66 v3:**
_Note: Parameters MPC_XY_VEL_MAX was changed to 22m/s and MPC_XY_CRUISE to 20m/s._

**Modes Tested**
Position Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
No issues noted, good flight in general.

**Logs:**
- https://review.px4.io/plot_app?log=aedfced7-926b-456e-8ea5-7ae5ce06bf5a

- https://review.px4.io/plot_app?log=eea3fbd4-26f5-44ac-b0ee-8520c8ae9812

**Comment by bresch** [comment]
Thank you @dannyfpv @jorge789 @Junkim3DR !

@jkflying Can you review and approve again so we can merge this please?

**Comment by bresch** [comment]
Offboard footage: https://youtu.be/OZzi8cmUZ74
Onboard footage: https://youtu.be/cDZWgacUZZc

**Pull request merged**
