### PR TITLE
navigator: mission check refactor

### PR DESCRIPTION
**Pull request by LorenzMeier**
WARNING: This PR leads to a constant mission check and is not ready to go in

The mission feasability checker was called with the same arguments
twice which made it hard to understand when a mission is marked valid.

The mission check should run in these two cases:
- When initializing (if home comes up) if there is already a mission saved.
- When the mission gets updated.

### CODE REVIEW

**Comment by sanderux** [comment]
I'll fix this. it's an important fix

**Comment by sanderux** [comment]
@LorenzMeier should be good now
significant change here: https://github.com/PX4/Firmware/pull/5257/commits/d3049def34be48ec0fc3c3f4737860be1f6ee6d8#diff-9b5a77642a641b107c8f8a966de34acdR1174

**Comment by LorenzMeier** [comment]
Your commit reverts Julian's commit. Is this intentional? I've already reverted that on master.

**Comment by sanderux** [comment]
I forgot to split the commits, will do that in the new pr's

**Comment by sanderux** [comment]
Jenkins test this please

**Comment by dagar** [comment]
@LorenzMeier see https://github.com/PX4/Firmware/pull/5262 for formatting
You can remove the outstanding modules one by one and run `make format` to see the damage.

**Comment by LorenzMeier** [comment]
@dagar Awesome, thanks!

@sanderux Did you end up splitting?

**Comment by sanderux** [comment]
No, do you want me to re-apply or not apply code formatting?

**Comment by LorenzMeier** [comment]
Essentially I have no idea what you changed and I'd like to understand the change. Any means of doing that will do.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by sanderux** [comment]
I re-enabled _home_inited and added a bool to the check_mission function called "force"
the line that will show what i did is this one: https://github.com/PX4/Firmware/pull/5257/commits/d3049def34be48ec0fc3c3f4737860be1f6ee6d8#diff-9b5a77642a641b107c8f8a966de34acdR1174

check mission will only run when:
- home_inited is false and home_position became valid 
home_inited will then be set to true
https://github.com/PX4/Firmware/blob/d3049def34be48ec0fc3c3f4737860be1f6ee6d8/src/modules/navigator/mission.cpp#L1194

- force == true
this is only called with true when check_mission was called from update_offboard_mission 
https://github.com/PX4/Firmware/blob/d3049def34be48ec0fc3c3f4737860be1f6ee6d8/src/modules/navigator/mission.cpp#L297

That's all i changed

**Comment by sanderux** [comment]
ps: i did also change the call from on_inactive to only run the check after being inited

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by LorenzMeier** [comment]
This will go in now but it was too much risk for 1.4.1. We're better off releasing 1.4.2 in 1-2 weeks when we're confident the changes are good now.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Comment by sanderux** [comment]
Thnx, i'll test fly

**Pull request closed without merging**
