### PR TITLE
Multiplatform 1741 and 1801

### PR DESCRIPTION
**Pull request by thomasgubler**
* port of https://github.com/PX4/Firmware/pull/1741 and https://github.com/PX4/Firmware/pull/1801 to multiplatform
  * Tested in SITL: manual control works except for yaw.
  * includes https://github.com/PX4/Firmware/pull/1821
  * includes https://github.com/PX4/Firmware/pull/1822
  * fixes https://github.com/PX4/Firmware/issues/1809
  * fixes https://github.com/PX4/Firmware/issues/1811

### CODE REVIEW

**Comment by thomasgubler** [comment]
Regarding the yaw issue: I verified that the setpoint rotation matrix is updated by the pos controller (checked with rostopic echo `rostopic echo /px4_multicopter/vehicle_attitude_setpoint`) and received by the attitude controller (checked with addtional PX_WARN and rqt).

It seems to be a more general issue however or setup related as atm yaw does not work for me on master neither.

@AndreasAntener can you yaw with the current master and the ardrone?

**Comment by AndreasAntener** [comment]
@thomasgubler I'm on #1793 and yawing works in offboard by setting PoseStamped.pose.orientation

**Comment by thomasgubler** [comment]
I mean yawing in manual with the joystick :)

**Comment by thomasgubler** [comment]
@AndreasAntener any feedack about normal joystick use? Unfortunately I can not test with another setup atm because my docker installation has some X11 issues. ( I will contact you about that ;-)  )

**Comment by AndreasAntener** [comment]
I can yaw on master with the ardrone. (But I had to fake joystick input because I don't have one ;) . Faked by publishing to */joy topics)

**Comment by thomasgubler** [comment]
Ok once you confirm that yaw works also on this branch I will merge this, #1821 and #1822

**Comment by AndreasAntener** [comment]
Tested this merged with master, yaw still works for me.

**Comment by thomasgubler** [comment]
Thanks!I checked the motor velocity topics on my setup and they change when I move the yaw stick! So I guess the problem is gazebo (5?) related. I will open an issue and come back to this after the merge from upstream.

**Comment by thomasgubler** [comment]
travis shows this as fail because I rebased, merged and then deleted the branch. Travis was to slow to checkout the branch before it was deleted. Master builds fine https://travis-ci.org/PX4/Firmware/builds/52031811

**Comment by thomasgubler** [comment]
For reference the yaw issue is here: https://github.com/PX4/euroc_simulator/issues/12

**Pull request merged**
