### PR TITLE
[WIP]: px4_fmu-v5, px4_fmu-v5x, modalai_fv-v1 switch to new InvenSense IMU drivers (icm20602 & icm20689)

### PR DESCRIPTION
**Pull request by dagar**
Requires https://github.com/PX4/Firmware/pull/14207.

@PX4/testflights could you try this on all px4_fmu-v5 (pixhawk 4, 4 mini, CUAV v5+, CUAV Nano) vehicles?

### CODE REVIEW

**Comment by dagar** [comment]
@modaltb FYI

**Comment by modaltb** [comment]
Rad, I can test this out for sure.  Thanks for the heads up.

**Comment by jorge789** [comment]
### Tested on CUAV nano V5

**Indoor Flight Test**
Modes Tested
Stabilized Mode: Good.

**Procedure**
Arm and Take off in stabilized mode.

**Notes**
No issues noted, good flight in general.

**Log**  https://review.px4.io/plot_app?log=6a74189a-82d2-4241-91ac-03a5b0dc2ca8

**Comment by dannyfpv** [comment]
Tested on Pixhawk4 v5 f-450
Indoor Flight Test
Modes Tested
Stabilized Mode: Good.

Procedure
Arm and Take off in stabilized mode.

Notes
No issues noted, good flight in general.

Log 
https://review.px4.io/plot_app?log=f3f445fb-bbf4-433e-bf44-2c5314dce720

Tested on pixhawkmini v5 f-450
Indoor Flight Test
Modes Tested
Stabilized Mode: Good.

Procedure
Arm and Take off in stabilized mode.

Notes
No issues noted, good flight in general.

Log
https://review.px4.io/plot_app?log=39718629-fc97-4b0b-a62b-707e0a8dc0df

**Comment by dagar** [comment]
Continued in https://github.com/PX4/Firmware/pull/14473.

**Pull request closed without merging**
