### PR TITLE
Pr trans switch

### PR DESCRIPTION
**Pull request by tumbili**
This introduces a transition switch for VTOL.

### CODE REVIEW

**Comment by tumbili** [comment]
@DonLakeFlyer Could you look at the QGC side of things?

**Comment by sanderux** [comment]
@tumbili perhaps it would be an idea to publish a warning when it hasn't been assigned. i think this will confuse people currently flying vtol when they upgrade.

**Comment by julianoes** [comment]
The changes look good to me.

**Comment by LorenzMeier** [comment]
Rebased and applied. The warning will be added here: https://github.com/mavlink/qgroundcontrol/issues/3884

**Comment by tubeme** [comment]
So how do I program the transition switch? There is no RC_MAP_TRANS_SW in the QGC and parameters. Probably with a script i should assign RC_MAP_TRANS_SW = 1 in the bootload?

Writing in relation to #5314

**Comment by kd0aij** [comment]
It's probably in the "default group" in QGC

**Comment by tubeme** [comment]
It is indeed. Thanks. No habit of going to "default group"

**Comment by LorenzMeier** [comment]
Fixed in QGC soon: https://github.com/mavlink/qgroundcontrol/pull/3942

**Pull request closed without merging**
