### PR TITLE
Fix sensors startup on pixhawk boards.

### PR DESCRIPTION
**Pull request by svpcom**
Commit 75b93b0728d57c642641c354dc99390a6ac43ee8 (Fix for HobbyKing boards) was not properly reverted

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This will make other boards fail, so we can't merge this. We need to get a bank of boards up and see if we can find a tradeoff between the different manufacturers. Just flicking back and forth between one set not working and one set working is not the solution.

**Comment by LorenzMeier** [comment]
@dagar Do you have all the HW at hand now?

**Comment by dagar** [comment]
I don't believe I have one of the questionable holybro boards, but I have a range of others I can check.

**Comment by LorenzMeier** [comment]
@dagar Do you have time now to look into the boot up?

**Comment by dagar** [comment]
Yes, I'll be back to normal tomorrow and can do a pass over a representative range of FMUv2s.

I still think I'm missing a fundamental understanding of why we needed to do this in the first place. I'll try and piece it together once and for all.

**Comment by dagar** [comment]
Sorry for taking so long here. This is a bit of a mixed bag and I still don't see a good solution. Here are my notes from testing your branch.

 - 3dr pixhawk - fixed sensor startup on reboot command 
 - pixhawk 2 cube - good
 - pixhawk 2.1 cube - no lsm303d 
 - holybro pixhawk - bootloop. With current master it works, although there's no lsm303, l3gd0 after reboot command (fine after power cycle)
 - pixhack v3 - no mag (using an internal ist8310?)
 - mRo pixhawk - master no mag on reboot command
 - older hobbyking pixhawk - bootloop (ms5607 baro working incorrectly!)
 - 3dr pixhawk mini - only 1 IMU

**Comment by svpcom** [comment]
@dagar @LorenzMeier So now we have only a half of supported hardware works on either cases? Maybe we need to add some additional board id to bootloader? Lets it will be an optional field (if HW vendors don't want to cooperate) that customer can fill to ensure proper operation after board reboot.

**Comment by dagar** [comment]
There are other issues mixed in. The overall summary as it relates to this PR, is that it's an improvement for most boards, except holybro/hobbyking, which now get stuck in bootloops.

**Comment by dagar** [comment]
@svpcom still no perfect solution, but trying a slightly different approach here. https://github.com/PX4/Firmware/pull/8871

**Comment by svpcom** [comment]
I've found a simple solution: The problem is that invalid hw_version doesn't match to HW_VER_FMUV2 in drivers/boards/px4fmu-v2/px4fmu_spi.c:93 and SPI bus is not initializing

**Comment by svpcom** [comment]
It seem than jenkins is broken:
```
[Firmware_PR-8703-Y5SSOVHEUV34LU6EPOJYJ4IKWHPUHJW54BI7COB3L3UJXSB3OEMA] Running shell script

Error response from daemon: Container 8482aa411ebe132e1dbc8425e8e1652a468c43071e86f88201d9a70182c7b5db is not running
```

**Comment by dagar** [comment]
Looks good across all the boards I have. It's the same core idea, but I went with something slightly different in https://github.com/PX4/Firmware/pull/9074 so that the default fallback is always the historical px4fmu-v2 behaviour.

**Comment by dagar** [comment]
Should be fixed by https://github.com/PX4/Firmware/pull/9074

**Pull request closed without merging**
