### PR TITLE
jMAVSim: try new libs with newer Java versions

### PR DESCRIPTION
**Pull request by julianoes**
This is an attempt to get jMAVSim to run with Java9+.

### CODE REVIEW

**Comment by julianoes** [comment]
I suggest that we check CI and then merge this because it seem to fix issues on macOS.

@unipheas is blocked by this.

**Comment by unipheas** [comment]
> I suggest that we check CI and then merge this because it seem to fix issues on macOS.
> 
> @unipheas is blocked by this.

Yep, just tested yesterday and had issues with current master, this fixed it.
On latest macOS

**Comment by julianoes** [comment]
@MaEtUgR would you mind testing this on Windows?

**Comment by bresch** [comment]
Works for me on Arch

**Comment by unipheas** [comment]
Seems everything has passed, can we merge now?

**Pull request merged**
