### PR TITLE
PX4Flow : rotate gyro readings

### LINKED ISSUE #3940: SENS_FLOW_ROT parameter does not work
The SENS_FLOW_ROT parameter used to allow for different installation angles for the PX4Flow sensor does not correct the published values.

### PR DESCRIPTION
**Pull request by mhkabir**
This fixes #3940.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! At the same time this shows that we need to do better on the development process, since a driver fix from October last year probably should have gone in much sooner.

Its critical we break things down into smaller pieces, rather than trying to "finish" things (like LPE) and not merge all the adjacent fixes to the main codebase. A diff of the LPE WIP branch should only show diffs in the estimator.

**Comment by mhkabir** [comment]
@LorenzMeier Sorry about that. LPE-improvements branch will be clean now. Only estimator diff.

**Comment by LorenzMeier** [comment]
Appreciated and thanks for helping out here - that shows that other parts of the dev process work really well, since you picked this up yourself, so thanks for being so active and vigilant, this is fantastic!

**Comment by mhkabir** [comment]
Looks like this broke master Travis ugh.

**Pull request closed without merging**
