### PR TITLE
lib: name folders consistently

### PR DESCRIPTION
**Pull request by dagar**
I suspect some people are going to find this a bit obnoxious, but I'd like to address the naming inconsistencies before they get any worse. I could live with either upper camel case or snake case, but please let's not do both.

Git followed the rename, so rebases for any open conflicting work should be relatively painless.

image

### CODE REVIEW

**Comment by MaEtUgR** [comment]
Good point to address. I contributed/initiated quite a part of upper camel case naming. My goal is to follow this naming scheme for new or refactored libraries which are pure C++ class implementations to have the folder named exactly after the main class's name. I consider this good practice and think it really helps to navigate the code. In that scheme the cmake library target follows the same naming convention and the class filenames as well e.g. see https://github.com/PX4/Firmware/tree/master/src/modules/mc_att_control, https://github.com/PX4/Firmware/tree/master/src/modules/mc_pos_control. As a result I would suggest/vote to use upper camel case. I think it's the goal to use C++ classes for future/existing refactored libraries and I would distinguish between implementations that still is C style. Of course we could already switch the naming if desired or I could do prs to adapt the existing ones. Up to discussion, I'm interested to hear your opinion.

**Comment by mcsauder** [comment]
Agreed.  And while on the subject, I care a lot less about the specifics of the convention than I do that there is a convention: https://github.com/PX4/Firmware/issues/9931

**Comment by mcsauder** [comment]
(Compliments mostly of Jacob Oursland for one of his best contributions to laying the groundwork of one of the first projects we ever collaborated on almost 2 decades ago.)

**Comment by dagar** [comment]
@MaEtUgR I think that could make sense, but I'd like to do more complete/opinionated passes for the sake of consistency once there's some agreement. I'm also very much in favor of naming the headers to match the single contained class.

At some point we should put together a simple style guide with a bit more enforcement of naming rules from clang-tidy.

**Comment by MaEtUgR** [comment]
ok, works for me then. Definitely better consistent than discussing indefinitely 😉

**Pull request merged**
