### PR TITLE
Alt hold performance

### PR DESCRIPTION
**Pull request by LorenzMeier**
@julianoes This is an attempt to fix the alt hold performance on your racer.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
https://github.com/PX4/Firmware/commit/c835fb36a6ae5ef6c4941231582612f819fefe86 should fix this.

**Comment by julianoes** [comment]
Not sure if we want to mess with this, at least not without testing.

**Comment by LorenzMeier** [comment]
Yep, I'm also not sure about INAV changes. I'm pretty confident about the baro rate change though, since its essentially a partial revert.

**Comment by LorenzMeier** [comment]
@tumbili @AndreasAntener It would be great if you could assist with your own test flying here as well.

**Comment by LorenzMeier** [comment]
Seems ok with LPE.

**Pull request closed without merging**
