### PR TITLE
Make FTP more robust

### PR DESCRIPTION
**Pull request by bkueng**
Make FTP robust against any kind of packet drops. On the vehicle side, this mostly means to keep a copy of the last sent response, most of the logic is in a QGC PR.

### CODE REVIEW

**Comment by dagar** [comment]
Is the mavlink_ftp_test working now?

**Comment by bkueng** [comment]
It should. At least CI failed because of that, and when I ran the tests locally, the last commit fixed it.

**Comment by dagar** [comment]
I was thinking of this - https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_tests/mavlink_ftp_test.cpp#L936

I could restore the test data generation pretty quickly, but I'm not sure about the others.

**Comment by bkueng** [comment]
Ah I did not see these. If it's not too much effort, it's worth enabling them.

**Comment by bkueng** [comment]
Merging, since the QGC PR got merged.

**Pull request merged**
