### PR TITLE
Safety prearm

### PR DESCRIPTION
**Pull request by LorenzMeier**
@DonLakeFlyer @AndreasAntener This is the new PR, WIP.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Same problem as before. It pegs the servos to full deflections when I press the safety switch.

**Comment by LorenzMeier** [comment]
All fixed now. Was a stupid one-line issue.

**Comment by LorenzMeier** [comment]
Disarmed:
screen shot 2015-07-07 at 09 48 36

**Comment by LorenzMeier** [comment]
Armed, throttle locked:
screen shot 2015-07-07 at 09 48 56

**Comment by LorenzMeier** [comment]
Full armed:
screen shot 2015-07-07 at 09 49 22

**Comment by DonLakeFlyer** [comment]
Working now. Throttle correctly not active. Press safety again and servos go dead. So everything working as far as I can tell.

**Comment by LorenzMeier** [comment]
Awesome. I also checked this on multicopters, so merging.

**Pull request merged**
