### PR TITLE
mpu9250: limit mag updates to 100 Hz

### PR DESCRIPTION
**Pull request by dagar**
This can save a little bit of cpu time, especially on fmu-v3 with 2 x mpu9250s.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Any reason to not bring this in?

**Comment by dagar** [comment]
> Any reason to not bring this in?

I'll test it.

**Comment by CarlOlsson** [comment]
Why was this closed?

**Comment by dagar** [comment]
> Why was this closed?

I'm taking another pass at it where the mpu9250 will provide something like a virtual I2C interface that a more or less regular standalone AK8963 will access (or optionally not started at all).

@CarlOlsson Are you interested in the possible (minor) transfer time savings or using the mpu9250 without mag entirely?

**Comment by CarlOlsson** [comment]
Okey thanks (Y) We got 4 mags running so I was thinking about reducing the update rate to save some CPU. Since you closed it I was just wondering if you had any issues downstream (like ekf etc)

**Pull request closed without merging**
