### PR TITLE
FW waypoint loiter to alt

### LINKED ISSUE #5061: FW navigation loiter to reach waypoint altitude
Currently keeps passing through center, turning around, coming back.

### PR DESCRIPTION
**Pull request by dagar**
- fixes #5061

### CODE REVIEW

**Comment by julianoes** [comment]
I would prefer NAV params to be used in the navigator only and try to keep some separation between modules.

What about catching the case in the navigator and setting a loiter setpoint for the fixedwing controller?

**Comment by dagar** [comment]
I think that works as a special case for waypoint acceptance that temporarily changes the published position setpoint type. Thanks for the feedback.

**Comment by dagar** [comment]
Another thing I'll need to take a closer at is the transition between waypoint and loiter setpoint. I did a real flight with this last week and had some nasty roll setpoint jumps from near 0 -> max and back. I think it's mostly from navigator FOH ramping up altitude which can be avoided if this is done in navigator.

**Comment by LorenzMeier** [comment]
@dagar I guess that means you will keep working on this one?

**Comment by dagar** [comment]
Seems to work well enough from navigator, other than then awkward turn initially entering the loiter (https://github.com/PX4/ecl/issues/185).

I'm debating switching back to regular waypoint acceptance after climbing in the loiter. I guess we need to do it to respect the mission acceptance radius.

screenshot from 2016-08-12 16-01-38

**Comment by dagar** [comment]
TODO: Rebase and test again

**Comment by dagar** [comment]
Rebased and tested again. Can I get a review? In particular the criteria for switching between position and loiter setpoints.

**Pull request merged**
