### PR TITLE
ekf2: remove unused function

### PR DESCRIPTION
**Pull request by CarlOlsson**

### CODE REVIEW

**Comment by dagar** [comment]
Interesting, making this change allowed clang to find private fields that are unused.
https://travis-ci.org/PX4/Firmware/jobs/250265912#L676

**Comment by LorenzMeier** [comment]
@CarlOlsson Can you remove this?

```
src/modules/ekf2/CMakeFiles/modules__ekf2.dir/ekf2_main.cpp.o.d -o src/modules/ekf2/CMakeFiles/modules__ekf2.dir/ekf2_main.cpp.o -c ../src/modules/ekf2/ekf2_main.cpp
../src/modules/ekf2/ekf2_main.cpp:163:7: fatal error: private field '_mag_decl_saved' is not used [-Wunused-private-field]
        bool _mag_decl_saved = false;   // true when the declination for the current position has been saved
             ^
1 error generated.
```

**Comment by CarlOlsson** [comment]
@priseborough please review

**Comment by priseborough** [comment]
When this has been merged, I will re-introduce the logic that saves the declination used by the EKF when the vehicle disarms if bit position 1 in EKF2_DECL_TYPE is set to true.

**Pull request merged**
