### PR TITLE
[FlightTasks] Added class enum for FlightTasks errors

### PR DESCRIPTION
**Pull request by roangel**

### CODE REVIEW

**Comment by roangel** [comment]
Commit history is messed up. Is it github? Do I have to do something?

**Comment by julianoes** [comment]
This looks like a nice improvement, thanks. @Stifael or @MaEtUgR please review.

**Comment by Stifael** [comment]
Yep looks good!

**Comment by julianoes** [comment]
@roangel could you fix the conflicts please?

**Comment by roangel** [comment]
I can't see any conflicts, you mean the git history?

**Comment by julianoes** [comment]
GitHub here complains about: `This branch cannot be rebased due to conflicts`.

**Comment by julianoes** [comment]
Oh, I guess we can squash it.

**Pull request merged**
