### PR TITLE
PX4 flow: add documentation

### PR DESCRIPTION
**Pull request by bkueng**
Originates from https://github.com/PX4/px4_user_guide/pull/286.

@hamishwillee fyi

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @bkueng - really nice job.

**Comment by trgiman** [comment]
Hi @hamishwillee very helpful. Recently I needed to fine tune parameters of PX4flow firmware. But documentation is gone. It was originally at https://pixhawk.org/dev/px4flow#parameters is there any alternative? Thanks.

**Comment by hamishwillee** [comment]
@trgiman Re
"Recently I needed to fine tune parameters of PX4flow firmware. But documentation is gone. It was originally at https://pixhawk.org/dev/px4flow#parameters is there any alternative? Thanks."

Yes, everything in that link went in as part of: https://github.com/PX4/px4_user_guide/pull/286

I still have access to that site. I'm moving the stuff that isn't anywhere else. If you need something desperately, send me an email to prioritise.

**Comment by trgiman** [comment]
Hi @hamishwillee . Thanks, actually I am using link below as you suggested. It includes all param settings, that I was looking for.

 https://github.com/PX4/px4_user_guide/blob/master/en/sensor/px4flow.md

**Pull request merged**
