### PR TITLE
Jenkins px4fmu-v2 hardware test

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
Still a little rough, but it's working.

**Comment by dagar** [comment]
The entire thing needs to be generalized.
 - configuration of available hardware
 - particular debugger and ftdi attached

**Comment by LorenzMeier** [comment]
Awesome!

**Comment by dagar** [comment]
@darioxz this isn't as nice as your PR, but I'd like to get something simple going so we can iterate. So far I've taken a couple of your scripts from https://github.com/PX4/Firmware/pull/8321.

The larger difference is so far I'm using debuggers rather than USB flashing.

**Comment by darioxz** [comment]
@dagar Great! We have a local 24/7 server which we could use to run it. Could you let me know which hardware I exactly need to reproduce your setup? 

- Black Magic Probe (https://www.adafruit.com/product/3839)
- PixHawk 1?

Thanks!

**Comment by dagar** [comment]
This is currently using an original 3DR pixhawk (px4fmu-v2) with jtag added and a black magic probe.

Once we're confident with the basic setup I'm more or less ready to expand it across...
  - pixhawk 2 (3dr and profincnc cube)
  - pixhawk 3
  - pixhawk 4
  - nxphlite
  - mindracer

**Comment by dagar** [comment]
I'll be away for the rest of the week and this hardware testing is dependent on infrastructure currently only in my office. Probably best to leave open until next week.

**Pull request merged**
