### PR TITLE
Aero: update MPC and LND parameters

### PR DESCRIPTION
**Pull request by bkueng**
This updates position controller & landing parameters for the Intel Aero.

@lucasdemarchi

### CODE REVIEW

**Comment by ChristophTobler** [comment]
I'll upload and link a video tonight

**Comment by lucasdemarchi** [comment]
should be aerofc, not aero.

**Comment by ChristophTobler** [comment]
Here's the video https://github.com/PX4/Firmware/pull/6972. Landing now works in position control, as can be seen.

**Comment by zehortigoza** [comment]
Here the link video that everyone can use: https://www.youtube.com/watch?v=5MUXVNllW0k
looks really nice, we will test in here ASAP.

**Comment by bkueng** [comment]
We tested with #6862, locally merged with current master.

**Comment by ChristophTobler** [comment]
@bkueng I have added/changed the parameters from today's test. I guess we can test with barometer "pipe" and lower the `EKF2_BARO_NOISE`

**Comment by lucasdemarchi** [comment]
what do you mean by barometer pipe?

**Comment by ChristophTobler** [comment]
Apparently, Beat has once tried applying a pipe to the barometer so that the opening is where the GPS is. It helped with the ground effect. But that was with the older driver. Maybe the performance will improve

**Comment by lucasdemarchi** [comment]
The default here should be with unmodified vehicle, not the optimal one that requires hw changes. We can give instructions to the users to do hw mods if they want and then instruct them to lower baro noise param.

**Comment by ChristophTobler** [comment]
Yes, this is all for a stock Aero. Still I think we could try lowering the baro noise because it was set to 5m.

**Comment by LorenzMeier** [comment]
@lucasdemarchi If you fly today lowering the baro noise might in fact help quite a bit. Please try with the default for Aero and then reset to the PX4 default. The MS5607 is in general accurate and now that the controller is much better tuned I'd love to see what it does.

**Comment by lucasdemarchi** [comment]
@LorenzMeier according to the datasheet, noise for MS5607 is twice the noise for MS5611. I did a test flight today. With this PR and the other one it's much better than before.

I tried lowering noise and gate (independently) and on Z it became worse... it looks stable for some seconds and then suddenly loses (or gains) ~1m. With the noise and gate parameter there's drift, but altitude doesn't vary so suddenly.

This is on a drone that I know has MS5607... it may be possible that not all of them have that... would be good to know if yours is MS5611 or MS5607.

**Comment by LorenzMeier** [comment]
My baseline is one with a MS5607. It holds altitude better than Aero. I still need to do a better log review though.

**Comment by bkueng** [comment]
Closing, as this got merged in #6972

**Pull request closed without merging**
