### PR TITLE
update sitl_gazebo to include realistic iris drag coeff

### PR DESCRIPTION
**Pull request by baumanta**
update the sitl_gazebo submodule to get more realistic rotor drag for iris: https://github.com/PX4/sitl_gazebo/pull/451

### CODE REVIEW

**Comment by jkflying** [comment]
For some reason the SITL tests are failing. Could this be due to the different vehicle dynamics?

**Comment by TSC21** [comment]
> For some reason the SITL tests are failing. Could this be due to the different vehicle dynamics?

It is possible. The tests that are failing are the offboard attitude control ones.

**Comment by Jaeyoung-Lim** [comment]
I don't see anything wrong when I run SITL locally

**Comment by TSC21** [comment]
> I don't see anything wrong when I run SITL locally

Probably is better that you try the offboard att control test locally and see what's happening.

**Comment by baumanta** [comment]
I ran that test locally on my machine and it seems the drone is crashing. But so far I was not able to figure out why. This is  the flightlog from the test: https://logs.px4.io/plot_app?log=952a2c2d-a64a-41d1-92f8-fae226f4a0ce

**Comment by Jaeyoung-Lim** [comment]
@baumanta Looks like the rate controller is overtuned now: https://logs.px4.io/plot_app?log=952a2c2d-a64a-41d1-92f8-fae226f4a0ce#Nav-Roll-Angular-Rate

**Comment by jkflying** [comment]
Maybe it's flying faster in attitude mode than it was before, so now it flies into terrain?

**Pull request merged**
