### PR TITLE
Add install target to install posix mainapp (renamed to px4) on system

### PR DESCRIPTION
**Pull request by jgoppert**
* Adds install target
* Renames mainapp to px4 in source code and docs.

### CODE REVIEW

**Comment by julianoes** [comment]
> - Renames mainapp to px4 in source code and docs.

:+1: :+1: :+1:

**Comment by jgoppert** [comment]
Let me know if this is OK to merge.

**Comment by julianoes** [comment]
@jgoppert We'll have to update the Devguide before we merge it, and verify that it still runs on Snappy, RPi, etc.

**Comment by jgoppert** [comment]
@julianoes Here are the devguide changes: https://github.com/PX4/Devguide/pull/16

**Comment by julianoes** [comment]
Thanks, I'll verify Snappy in the next days and report back.

**Comment by jgoppert** [comment]
Also added package creation for linux including debs, can invoke with:

```bash
make posix_sitl_default package
```

Creates binary package:
* zip
* deb

```bash
make posix_sitl_default package_source
```

Creates source package:
* zip
* tbz2

**Comment by jgoppert** [comment]
Note, I changed the posix-config path to be an absolute path to the installed directory, so you will need to type make install or install the generated deb package before running sitl.

**Comment by bkueng** [comment]
While I generally like the idea of an install target, I have some concerns about this.

> Note, I changed the posix-config path to be an absolute path to the installed directory, so you will need to type make install or install the generated deb package before running sitl.

- This is now inconsistent with the `sitl_run.sh` script which still uses the files from the src & build dir (source of error and confusion).
- the scripts don't consider the prefix (it's not necessarily `/usr`). So hardcoding this in general is wrong.
- I'd generally like to keep things simple so that I know what config files are actually used, so that I can change the right ones (either only work with the installed files or only with build/src files).
- During development, I don't want the install step in between, so all files need to be taken from the src/build dir. root rights should not be required either.

We plan to let bash interprete our startup scripts, which will allow a more flexible approach. Maybe we should wait until then, at least with the install stuff, the renaming is fine.

**Comment by jgoppert** [comment]
@bkueng My goal is to make it easy for my end-users to run the SITL, and the build process etc. is too much work.

Right now I am distributing the deb files as created above and it is very simple.

I understand the benefit as far as speed of in source development, but we could configure the posix configs to have a path variable to either look  in the source tree or the install path.

**Comment by bkueng** [comment]
I agree with your goals, the question is only how we get there. I think that `install` should not be involved at all during normal development.

We have 2 use cases and we need a solution that works well for both. And I believe we can do that. We already have a solution for devel, now we need one for end-users, that does not mess up the first.

For example, the install script could take care of replacing all relative paths with the absolute install paths, including the prefix (would also take care of the variable prefix). This could work, since the pattern `../../../..` is pretty much unique within these scripts. And once we let bash interpret the scripts, we can switch to a better solution.

**Comment by jgoppert** [comment]
I can use cmake file config to replace the path in posix configs before
sticking it in devel directory or installing.

**Comment by bkueng** [comment]
exactly. but in devel mode we don't need to copy, right?

**Comment by julianoes** [comment]
@jgoppert Could we also move the directories of the executables to e.g. `build_posix_sitl_default/bin` instead of `build_posix_sitl_default/src/firmware/posix/`. It's not really intuitive and it would be nice to have a bin folder with just the exes without cmake artefacts.

**Comment by julianoes** [comment]
> @jgoppert Could we also move the directories of the executables to e.g. build_posix_sitl_default/bin instead of build_posix_sitl_default/src/firmware/posix/. It's not really intuitive and it would be nice to have a bin folder with just the exes without cmake artefacts.

Actually, I found how to change this, so I'm already on it.

**Comment by jgoppert** [comment]
This PR was already largely incorporated except for the rename, so I'm going to close it and delete the old branch. @bkueng I think the bin directory is a good idea.

**Comment by bkueng** [comment]
@jgoppert yes I think so too. We should make sure the directory structure in the build directory is the same as when installed. This way we can use relative paths that work in both cases.

**Pull request closed without merging**
