### PR TITLE
set FW out disarmed values for VTOL configs to 1500

### PR DESCRIPTION
**Pull request by AndreasAntener**
Maybe fix for #3649

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Not setting the disarmed value at all should result in the aux outputs to default to the mixed PWM value for 0, which for a symmetric servo would be 1500.

**Comment by AndreasAntener** [comment]
Interesting: if I don't set the disarmed value, the outputs also don't move anymore after disabling safety before arming.

**Comment by LorenzMeier** [comment]
They should center (if you move them in the de-powered state by hand) do they center or are they not doing anything? If they don't do anything then please file an issue, because David's changes broke it in that case.

**Comment by LorenzMeier** [comment]
Let's merge this as interim fix while I fix up the pre-arm sequence.

**Comment by AndreasAntener** [comment]
Sure

**Comment by davids5** [comment]
@LorenzMeier @AndreasAntener 

Have a look at https://github.com/PX4/Firmware/blob/master/src/drivers/px4fmu/fmu.cpp#L934

What I believe this code does is, if any disarmed non-zero are supplied it will begin using those values when not armed. Until up_pwm_servo_arm(true) is called the IO will remain in input mode.

**Comment by AndreasAntener** [comment]
Follow-up: #3754

**Pull request closed without merging**
