### PR TITLE
update docker containers to 2018-09-11

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
SITL tests still failing.

**Comment by dagar** [comment]
Only the current intermittent VTOL standard failure remains.

image

**Comment by bkueng** [comment]
Cool, thanks!
I guess you know, but OSX and Snapdragon are still missing pyyaml.

**Comment by dagar** [comment]
Snapdragon - https://github.com/PX4/Firmware/pull/10468
OSX we'll have to do manually, although I'm hoping to start using https://github.com/PX4/Firmware/blob/master/Tools/setup/OSX.sh

What about windows?

**Comment by bkueng** [comment]
> What about windows?

@MaEtUgR is on holiday currently.

**Comment by MaEtUgR** [comment]
Something missing for Windows?

**Comment by MaEtUgR** [comment]
I see
https://github.com/PX4/Firmware/pull/10428#issuecomment-419159646
https://github.com/PX4/containers/pull/133#issuecomment-423841909
✔️

**Pull request merged**
