### PR TITLE
Automated updates of the C++ code generated by the multi_tables script, ...

### PR DESCRIPTION
**Pull request by anton-matosov**
...now it is placed into the mixer_multirotor.generated.h file which is generated by makefile

### CODE REVIEW

**Comment by LorenzMeier** [comment]
That's pretty cool! I need to check though about the dependency to tcl for all our platforms (Windows, Linux, Mac OS), so it might take some time to get this in. It would have been easier if its Python, as we fulfill that dependency already. Before requiring it on every build that wasn't a big deal, but now as Makefile dependency it is a concern that needs to be vetted.

**Comment by LorenzMeier** [comment]
That said, a Python version could be merged immediately.

**Comment by anton-matosov** [comment]
Lorenz, please let me know if tcl dependency doesn't work well for all the platforms, and I will rewrite this script with python.

**Comment by LorenzMeier** [comment]
If you don't terribly mind, it would be appreciated yes. Given that TCL and Python are close in their language constructs, I hope its not too much effort.

**Comment by anton-matosov** [comment]
Build failed with really strange error...

$ /usr/bin/mail -s "$SUBJECT ($TRAVIS_COMMIT)" "$PX4_EMAIL" < "$PX4_REPORT"

Cannot parse address `commit 156710e40a9e566834679998fa85f16524b7284d' (while expanding `commit 156710e40a9e566834679998fa85f16524b7284d'): Format of RFC822 object is bad

**Comment by LorenzMeier** [comment]
Let me go and fix Travis, sec.

**Comment by LorenzMeier** [comment]
Ok, if you rebase this onto master the mail related build error should go away.

**Comment by LorenzMeier** [comment]
Would you mind pasting the content of the generated header here? I'd just like to do a paranoid comparison, and then merge.

**Comment by anton-matosov** [comment]
/*
* These file is automatically generated by multi_tables.py - do not edit.
*/

enum MultirotorMixer::Geometry : unsigned int {
	QUAD_X,
	QUAD_PLUS,
	QUAD_V,
	QUAD_WIDE,
	HEX_X,
	HEX_PLUS,
	HEX_COX,
	OCTA_X,
	OCTA_PLUS,
	OCTA_COX,
	TWIN_ENGINE,

	MAX_GEOMETRY
}; // enum MultirotorMixer::Geometry

namespace {
const MultirotorMixer::Rotor _config_quad_x[] = {
	{ -0.707107,  0.707107,  1.000000 },
	{  0.707107, -0.707107,  1.000000 },
	{  0.707107,  0.707107, -1.000000 },
	{ -0.707107, -0.707107, -1.000000 },
};

const MultirotorMixer::Rotor _config_quad_plus[] = {
	{ -1.000000,  0.000000,  1.000000 },
	{  1.000000,  0.000000,  1.000000 },
	{  0.000000,  1.000000, -1.000000 },
	{ -0.000000, -1.000000, -1.000000 },
};

const MultirotorMixer::Rotor _config_quad_v[] = {
	{ -0.322266,  0.946649,  0.424200 },
	{  0.322266,  0.946649,  1.000000 },
	{  0.322266,  0.946649, -0.424200 },
	{ -0.322266,  0.946649, -1.000000 },
};

const MultirotorMixer::Rotor _config_quad_wide[] = {
	{ -0.927184,  0.374607,  1.000000 },
	{  0.777146, -0.629320,  1.000000 },
	{  0.927184,  0.374607, -1.000000 },
	{ -0.777146, -0.629320, -1.000000 },
};

const MultirotorMixer::Rotor _config_hex_x[] = {
	{ -1.000000,  0.000000, -1.000000 },
	{  1.000000,  0.000000,  1.000000 },
	{  0.500000,  0.866025, -1.000000 },
	{ -0.500000, -0.866025,  1.000000 },
	{ -0.500000,  0.866025,  1.000000 },
	{  0.500000, -0.866025, -1.000000 },
};

const MultirotorMixer::Rotor _config_hex_plus[] = {
	{  0.000000,  1.000000, -1.000000 },
	{ -0.000000, -1.000000,  1.000000 },
	{  0.866025, -0.500000, -1.000000 },
	{ -0.866025,  0.500000,  1.000000 },
	{  0.866025,  0.500000,  1.000000 },
	{ -0.866025, -0.500000, -1.000000 },
};

const MultirotorMixer::Rotor _config_hex_cox[] = {
	{ -0.866025,  0.500000, -1.000000 },
	{ -0.866025,  0.500000,  1.000000 },
	{ -0.000000, -1.000000, -1.000000 },
	{ -0.000000, -1.000000,  1.000000 },
	{  0.866025,  0.500000, -1.000000 },
	{  0.866025,  0.500000,  1.000000 },
};

const MultirotorMixer::Rotor _config_octa_x[] = {
	{ -0.382683,  0.923880, -1.000000 },
	{  0.382683, -0.923880, -1.000000 },
	{ -0.923880,  0.382683,  1.000000 },
	{ -0.382683, -0.923880,  1.000000 },
	{  0.382683,  0.923880,  1.000000 },
	{  0.923880, -0.382683,  1.000000 },
	{  0.923880,  0.382683, -1.000000 },
	{ -0.923880, -0.382683, -1.000000 },
};

const MultirotorMixer::Rotor _config_octa_plus[] = {
	{  0.000000,  1.000000, -1.000000 },
	{ -0.000000, -1.000000, -1.000000 },
	{ -0.707107,  0.707107,  1.000000 },
	{ -0.707107, -0.707107,  1.000000 },
	{  0.707107,  0.707107,  1.000000 },
	{  0.707107, -0.707107,  1.000000 },
	{  1.000000,  0.000000, -1.000000 },
	{ -1.000000,  0.000000, -1.000000 },
};

const MultirotorMixer::Rotor _config_octa_cox[] = {
	{ -0.707107,  0.707107,  1.000000 },
	{  0.707107,  0.707107, -1.000000 },
	{  0.707107, -0.707107,  1.000000 },
	{ -0.707107, -0.707107, -1.000000 },
	{  0.707107,  0.707107,  1.000000 },
	{ -0.707107,  0.707107, -1.000000 },
	{ -0.707107, -0.707107,  1.000000 },
	{  0.707107, -0.707107, -1.000000 },
};

const MultirotorMixer::Rotor _config_twin_engine[] = {
	{ -1.000000,  0.000000,  0.000000 },
	{  1.000000,  0.000000,  0.000000 },
};

const MultirotorMixer::Rotor *_config_index[] = {
	&_config_quad_x[0],
	&_config_quad_plus[0],
	&_config_quad_v[0],
	&_config_quad_wide[0],
	&_config_hex_x[0],
	&_config_hex_plus[0],
	&_config_hex_cox[0],
	&_config_octa_x[0],
	&_config_octa_plus[0],
	&_config_octa_cox[0],
	&_config_twin_engine[0],
};

const unsigned _config_rotor_count[] = {
	4, /* quad_x */
	4, /* quad_plus */
	4, /* quad_v */
	4, /* quad_wide */
	6, /* hex_x */
	6, /* hex_plus */
	6, /* hex_cox */
	8, /* octa_x */
	8, /* octa_plus */
	8, /* octa_cox */
	2, /* twin_engine */
};

} // anonymous namespace

**Comment by LorenzMeier** [comment]
If you run ```make tests``` you should be able to reproduce the mixer test fail - maybe a missing header?

**Comment by anton-matosov** [comment]
Header is not missing, it is getting generated without content... However it does work locally for all the targets without any errors.

**Comment by anton-matosov** [comment]
Is build on Trevis single threaded?

**Comment by anton-matosov** [comment]
This error is really strange...
../src/modules/systemlib/mixer/multi_tables> ../src/modules/systemlib/mixer/mixer_multirotor.generated.h
is called only once, as part of the make tests target.
But only the tests target is failing, 'make -j6' passes w/o any errors, meaning that file content is ready and correct at that moment.

**Comment by LorenzMeier** [comment]
The make Tests target compiles on the host. Check out the unittests directory and the Makefile in it. It's not part of the build system building the embedded part of the code.

**Comment by anton-matosov** [comment]
It looks like g++ version installed on Travis build node (4.6.3) doesn't correctly support enum forward declarations.

**Comment by LorenzMeier** [comment]
I tried forcing it to clang and C++11, lets see if that helps any.

**Comment by LorenzMeier** [comment]
Fun. It doesn't support the C++11 option.

**Comment by anton-matosov** [comment]
Strange... which version do you use?
> Clang 3.3 is claimed to be C++11 feature complete.
> Clang's command line is gcc-compatible so you have to enable C++11 support via the followinf command-line switch
-std=c++11

**Comment by LorenzMeier** [comment]
fails: https://github.com/PX4/Firmware/commit/31fb5d4a900272f83e78138f81d07bdc4b1a40a0

**Comment by anton-matosov** [comment]
g++ is hardcoded in the unittests makefile (CC=g++)

From the build log (https://travis-ci.org/PX4/Firmware/builds/45997427):
g++ -o mixer_test ../src/systemcmds/tests/test_mixer.cpp ../src/systemcmds/tests/test_conv.cpp ../src/modules/systemlib/mixer/mixer_simple.cpp ../src/modules/systemlib/mixer/mixer_multirotor.cpp ../src/modules/systemlib/mixer/mixer.cpp ../src/modules/systemlib/mixer/mixer_group.cpp ../src/modules/systemlib/mixer/mixer_load.c ../src/modules/systemlib/pwm_limit/pwm_limit.c hrt.cpp mixer_test.cpp -I. -I../src/modules -I ../src/include -I../src/drivers -I../src -I../src/lib -D__EXPORT="" -Dnullptr="0" -lm -std=c++11 -isystem gtest/include

cc1plus: error: unrecognized command line option ‘-std=c++11’

So you are still using g++, not clang

Another line in the same makefile also has hardcoded compiler:
cd build && CC=gcc cmake .. && $(MAKE) && $(MAKE) test

**Comment by anton-matosov** [comment]
Lorenz, I have found the way to workaround the issue with g++.
Latest build passed the enum issue.

**Comment by dagar** [comment]
I didn't figure out why CC=g++, so forcing CC=gcc for cmake is a temporary workaround.

**Comment by dagar** [comment]
If you still want c++11 you can add this to travis for gcc 4.8

install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -qq g++-4.8 libstdc++-4.8-dev

**Comment by anton-matosov** [comment]
Switching to gcc (clang) and C++11 on the OS X doesn't work well:

gcc -o mixer_test ../src/systemcmds/tests/test_mixer.cpp ../src/systemcmds/tests/test_conv.cpp ../src/modules/systemlib/mixer/mixer_simple.cpp ../src/modules/systemlib/mixer/mixer_multirotor.cpp ../src/modules/systemlib/mixer/mixer.cpp ../src/modules/systemlib/mixer/mixer_group.cpp ../src/modules/systemlib/mixer/mixer_load.c ../src/modules/systemlib/pwm_limit/pwm_limit.c hrt.cpp mixer_test.cpp -I. -I../src/modules -I ../src/include -I../src/drivers -I../src -I../src/lib -D__EXPORT="" -Dnullptr="0" -lm -std=c++11 -isystem gtest/include
error: invalid argument '-std=c++11' not allowed with 'C/ObjC'
error: invalid argument '-std=c++11' not allowed with 'C/ObjC'

So I believe we should postpone it until it is absolutely required and perform testing on all the platforms.

**Comment by LorenzMeier** [comment]
Is your Xcode up to date? Because it compiles for me. But I'll remove it anyway.

**Comment by LorenzMeier** [comment]
@anton-matosov Rebased your work here plus applied gcc 4.8 install fix:
https://github.com/PX4/Firmware/commits/multitables

**Comment by dagar** [comment]
@LorenzMeier hmm that's grabbing g++4.8, and **gcc 4.9**. You might want to add gcc-4.8 to the list of packages to install. 

https://travis-ci.org/PX4/Firmware/builds/46004990

**Comment by anton-matosov** [comment]
I have latest Xcode 6.1.1

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix

**Comment by anton-matosov** [comment]
> @anton-matosov Rebased your work here plus applied gcc 4.8 install fix:
> https://github.com/PX4/Firmware/commits/multitables
Can you please grab the latest changes as well. They include couple fixes for typos, copyrights and makefile improvements, as well as the fix for older version of gcc

**Comment by LorenzMeier** [comment]
If you merge or rebase with my multi tables branch (or cut over the GCC settings) I'd be happy to merge the resulting branch.

**Comment by anton-matosov** [comment]
Merged in the branch.

**Pull request closed without merging**
