### PR TITLE
CMake support from @jgoppert and @mcharleb

### PR DESCRIPTION
**Pull request by LorenzMeier**
This is the new PR after the last web API fail.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@jgoppert @mcharleb Restored pre-fail state. Yes, need to fix power module. @tumbili Could you please verify this tomorrow?

**Comment by jgoppert** [comment]
Sorry for the flurry of commits. Somehow all the way back at 8a0277d654eeed672a79efef78e22cec90a42a01 we lost posix on travis. It took me awhile to get it building again since I couldn't reproduce the error on my linux box.

**Comment by jgoppert** [comment]
@LorenzMeier could you enable protection for this branch to make sure that all commits pass the travis ci? I realize that it is a bit of a headache to create a PR for every commit, but I think it would be better, plus I should have done that anyway to rebase my 10 commits above :-P.

**Comment by LorenzMeier** [comment]
@AndreasAntener Could you have a look at the SITL build breakage?

**Comment by AndreasAntener** [comment]
```
CMake Error at px4ros/Firmware/CMakeLists.txt:143 (include):
  include could not find load file:

    configs/nuttx_px4fmu-v2_default


CMake Error at px4ros/Firmware/CMakeLists.txt:152 (message):
  configs/nuttx_px4fmu-v2_default must implement px4_os_prebuild_targets

```

@jgoppert ?

**Comment by AndreasAntener** [comment]
How does the new cmake build setup relate to the old one which was just for SITL? Do I have to force the right config somehow for the SITL build?

**Comment by LorenzMeier** [comment]
In theory the ROS build should still be operational for ROS-SITL, so I'm not sure what / how it broke. Either the CMake files are interfering now or ROS got accidentally broken during the CMake integration.

**Comment by jgoppert** [comment]
@AndreasAntener , @LorenzMeier I patched ROS sitl support back here: https://github.com/PX4/Firmware/pull/2910  It uses a completely different cmake setup. We could take the time to integrate it with the existing cmake build at some point, but I don't think there is much need. If it sees OS=ROS, it just grabs the description from the other file and builds with that. There are a few build errors that I haven't taken time to fix yet. It just looks like we broke a few includes or something with the other development on cmake-2.

**Comment by LorenzMeier** [comment]
@AndreasAntener Could you have a go? The build fixes should be fairly trivial mostly including headers.

**Comment by LorenzMeier** [comment]
@jgoppert Fails now on Mac OS for the NuttX targets - why is Travis failing to complete the build on these?

```
-- GIT_DESC = "c97a2c4810cbc23bac2013802267feafe549bd5e"
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/src/Firmware/build_px4fmu-v2_default
make -j4 -C /Users/user/src/Firmware/build_px4fmu-v2_default --no-print-directory upload
[  1%] Built target git_genmsg
[  1%] Built target git_gencpp
[  2%] Built target git_uavcan
[  2%] Built target git_mavlink
[  2%] Built target __nuttx_patch_px4fmu-v2
[  2%] Built target git_nuttx
[  2%] Built target mixer_gen
[  2%] Built target __nuttx_patch_px4io-v2
[  2%] Built target __nuttx_copy_px4fmu-v2
[  2%] Built target msg_gen
[  2%] Built target __nuttx_copy_px4io-v2
[  3%] Generating px4fmu-v2.export
Configuring NuttX for px4fmu-v2
[  3%] Generating px4io-v2.export
Configuring NuttX for px4io-v2
make[5]: warning: -jN forced in submake: disabling jobserver mode.
make[5]: warning: -jN forced in submake: disabling jobserver mode.
include/arch/chip already exists but is not a symbolic link
make[5]: *** [clean_context] Error 1
make[5]: *** Waiting for unfinished jobs....
include/arch/chip already exists but is not a symbolic link
make[5]: *** [clean_context] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [src/modules/px4iofirmware/px4io-v2.export] Error 2
make[3]: *** [src/modules/px4iofirmware/CMakeFiles/nuttx_export_px4io-v2.dir/all] Error 2
make[3]: *** Waiting for unfinished jobs....
make[4]: *** [px4fmu-v2.export] Error 2
make[3]: *** [CMakeFiles/nuttx_export_px4fmu-v2.dir/all] Error 2
make[2]: *** [src/firmware/nuttx/CMakeFiles/upload.dir/rule] Error 2
make[1]: *** [upload] Error 2
make: *** [px4fmu-v2_default] Error 2
```

**Comment by jgoppert** [comment]
@LorenzMeier it looks like the build for Mac completed on travis without error. Could you try recloning, or git clean -dxf?

**Comment by LorenzMeier** [comment]
It worked after a git clean - sorry about the false alarm.

**Comment by jgoppert** [comment]
@LorenzMeier, @AndreasAntener 
So this is the current error for ROS sitl:
```bash
[ 89%] Building CXX object CMakeFiles/mc_att_control.dir/src/modules/mc_att_control_multiplatform/mc_att_control_main.cpp.o
/home/jgoppert/git/px4/src/Firmware/src/platforms/ros/nodes/mc_mixer/mc_mixer.cpp:43:40: fatal error: mav_msgs/CommandMotorSpeed.h: No such file or directory
 #include <mav_msgs/CommandMotorSpeed.h>
```

I get the same error when building master myself, so it must be that the jenkins job is including special repos, because ros-indigo-mav_msgs package doesn't install this message description.

Also, the catkin build probably won't build the ros sitl by default, we might need to do something special to detect the catkin build and set the CONFIG=ros_sitl_simple flag.

**Comment by AndreasAntener** [comment]
@jgoppert 
SITL uses an old version of mav_comm: https://github.com/PX4/mav_comm.git . Jenkins uses the repos as specified in the install description for SITL. To update to latest (packaged) versions we need to update and push upstream for rotor_simulator which is kind of pending..

**Comment by AndreasAntener** [comment]
I tried running catkin_make: `catkin_make --cmake-args -DCONFIG=ros_sitl_simple` and get this error now:
```
Scanning dependencies of target px4
[ 79%] Building CXX object px4ros/Firmware/CMakeFiles/px4.dir/src/platforms/ros/px4_ros_impl.cpp.o
/sitl/catkin_ws/src/px4ros/Firmware/src/platforms/ros/px4_ros_impl.cpp:40:17: fatal error: px4.h: No such file or directory
 #include <px4.h>
                 ^
compilation terminated.
```

**Comment by LorenzMeier** [comment]
@AndreasAntener Looks like the include path in CMAKE is missing the folder where the px4.h is contained - could you have a go at that? You just need to make sure all required paths are in here:
https://github.com/PX4/Firmware/blob/cmake-2/cmake/ros-CMakeLists.txt#L129-L139

**Comment by LorenzMeier** [comment]
@jgoppert Could you re-try with this branch now and see if the battery pre-arming still fails? At least the SYS_STATUS MAVLink message has a valid battery voltage now.

**Comment by LorenzMeier** [comment]
I cross checked power and it should be fine. Let me know if you still have issues on your setup.

**Comment by AndreasAntener** [comment]
@LorenzMeier @jgoppert 
I can build it on my ROS installation with cmake directly (with `-DCONFIG=ros_sitl_simple`). Something is fishy when using `catkin_make`, but I don't see through it yet.

**Comment by AndreasAntener** [comment]
@SITL CI: test this please

**Comment by AndreasAntener** [comment]
Need to wait on Docker build, will trigger SITL again later..

**Comment by AndreasAntener** [comment]
@SITL CI: test this please

**Comment by AndreasAntener** [comment]
FYI: it compiled successfully, but I still have an error in the test script. Should be fixed on the next build (1h or so)

**Comment by mcharleb** [comment]
@LorenzMeier Did Eigen get reverted somewhere along the way? I have patches to Eigen master branch that work, but the current commit used on cmake-2 branch uses result_of and provides no way to test if the feature is provided.

**Comment by dagar** [comment]
@mcharleb https://github.com/PX4/Firmware/commits/cmake-2/src/lib/eigen

**Comment by AndreasAntener** [comment]
@SITL CI: test this please

**Comment by AndreasAntener** [comment]
ROS SITL looks good

**Comment by jgoppert** [comment]
What's left to finish on this? Do we need to add a few more board configs and that is it?

**Comment by LorenzMeier** [comment]
@jgoppert @mcharleb Items left to wrap this up:

- Figure out why James had issues with his power module
- More test flights
- Bring in all NuttX board configs

There are other things like fixing Mac OS SITL, but these are non-blocking.

**Comment by LorenzMeier** [comment]
@jgoppert The battery thing is real, as well as the navigator is not loading.

**Comment by LorenzMeier** [comment]
Wohoo! Fixed them and flew this. Looking good!

**Comment by jgoppert** [comment]
Nice!

**Comment by LorenzMeier** [comment]
@jgoppert The last missing bit is now UAVCAN - where is that standing, and how hard would the integration be?

**Comment by jgoppert** [comment]
@LorenzMeier I took a look. The best option would be to add CMake arm build support upstream. Otherwise we would just need to create our own CMakeLists.txt to build it. @pavel-kirienko Do you agree this is the best option/ could you add arm support for cross compiling with arm toolchain files like we have done for the PX4 build?

**Comment by pavel-kirienko** [comment]
@jgoppert What do you want me to add arm support to? I'm kind of out of the context.

**Comment by jgoppert** [comment]
@pavel-kirienko We want to add uavcan support to the px4 cmake build. Currently, the library is being built using make. So I would have to add cmake files to support cross-compiling it with arm, but it makes more sense to me for it to be upstream I think.

**Comment by LorenzMeier** [comment]
@pavel-kirienko You have CMake support here, but not for cross-compiling:
https://github.com/UAVCAN/libuavcan/blob/master/CMakeLists.txt

**Comment by jgoppert** [comment]
@pavel-kirienko  We need to translate https://github.com/PX4/Firmware/blob/cmake-2/src/modules/uavcan/module.mk Into https://github.com/PX4/Firmware/blob/cmake-2/src/modules/uavcan/CMakeLists.txt

**Comment by pavel-kirienko** [comment]
@jgoppert @LorenzMeier OK I see. Any crash course on cross-compilation with CMake? Actually I would be equally happy to just accept a pull request rather than implementing it myself. ;)

**Comment by jgoppert** [comment]
@pavel-kirienko I could help, you can add me on skype: james.goppert  Currently having trouble building on ubuntu: 

```bash
  File "dsdl_compiler/libuavcan_dsdlc", line 59, in <module>
    from libuavcan_dsdl_compiler import run as dsdlc_run
  File "/home/jgoppert/git/libuavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 17, in <module>
    from uavcan import dsdl
ImportError: No module named uavcan
```

**Comment by LorenzMeier** [comment]
@jgoppert Not quite - that builds the PX4 app and integrates the UAVCAN files. We just would need to translate this file: https://github.com/UAVCAN/libuavcan/blob/master/libuavcan/include.mk

I would prefer an incremental approach here and just translate the file in the PX4 repo and include the libuavcan files into the module sources. We are super tight on resources on the UAVCAN dev community and we need to get going for the PX4 community.

We can't afford right now investing any further into architecture, because I really, really need both UAVCAN and CMake to work on master, as I'm running out of time to integrate both.

**Comment by LorenzMeier** [comment]
If you can manage it "properly" within the weekend even better, but we really need this and we need to be careful on what we spend our resources right now.

**Comment by jgoppert** [comment]
@LorenzMeier Understood, I'll try to push support upstream copying what we already have. I think that is the easiest path forward honestly. I don't want to rewrite his whole cmake build for it to get thrown away. If it takes longer than a few hours, I will abort.

@pavel-kirienko Fogot submodule init.

**Comment by zshn25** [comment]
Please help me.
https://github.com/PX4/Firmware/issues/3099

**Pull request merged**
