### PR TITLE
Logger: dynamic number of subscriptions

### PR DESCRIPTION
**Pull request by bkueng**
Fixes errors like `Too many subscriptions, failed to add: sensor_selection 0`.

See commits for details.
Memory usage is about the same, but depends now on the logging profile configuration.

### CODE REVIEW

**Comment by dagar** [comment]
From http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-compile/detail/PR-13745/1/pipeline:
image

We might as well drop the frame-larger-than warning, I don't think it's ever really helped.

**Comment by dagar** [comment]
The SITL test failures looks real.

**Comment by bkueng** [comment]
> We might as well drop the frame-larger-than warning, I don't think it's ever really helped.

Yeah, especially since it is a false positive.

> The SITL test failures looks real.

Not sure what that was.

I moved the subscriptions into a separate class.

**Comment by dannyfpv** [comment]
tested on pixhawk4 v5 f450
position mode: no issues
mission mode: no issues
altitude mode: no issues
stabilize mode: no issues

log:
https://review.px4.io/plot_app?log=ae40f57a-439c-4cc5-a9be-5eefb9f09629

**Comment by jorge789** [comment]
**Tested on PixRacer V4:**
### Maximum wind 10.2 m/s
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
When the vehicle was landing, it did not descend vertically, drifted away with the wind and landed the vehicle manually

**Log:**  https://review.px4.io/plot_app?log=719ab88b-d993-47c8-a9ca-eaf429d4577e

**Comment by bkueng** [comment]
Thanks for testing.
@dannyfpv any reason why you set `SDLOG_MODE` to `from boot until shutdown` on the Pixhawk 4 v5 f450 vehicle?

**Comment by Tony3dr** [comment]
> Thanks for testing.
> @dannyfpv any reason why you set `SDLOG_MODE` to `from boot until shutdown` on the Pixhawk 4 v5 f450 vehicle?

@bkueng we were doing some bench test prior to the testing the PR. We forgot to disable the parameter.

**Pull request merged**
