### PR TITLE
commander: Fixing HIL operation with failing preflight checks

### PR DESCRIPTION
**Pull request by LorenzMeier**
@sjwilks For you

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@SimonWilks this is not compiling, but you'll get the idea. Not sure I'll get around to fix it tomorrow, just needs a simple compile fix.

**Comment by LorenzMeier** [comment]
Fixed the compile error, good for testing.

**Comment by SimonWilks** [comment]
HIL is working again. Thanks :)

**Comment by LorenzMeier** [comment]
Applied via rebase.

**Pull request closed without merging**
