### PR TITLE
Added support to MPU6000 Driver for MPU6050

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier 

Added support to the MPU6000 for the MPU6050 on I2C.

Tested on FMUV1 and TAP

N.B.

1.  https://github.com/PX4/Firmware/pull/5095 should be merge into this branch or master and this rebased on the updated master.

2. TAP rotations need to be set.

3. On TAP @400kHz - the acquisition time alone is ~583 us, We may need 2 phase or slow the rate to 2MS.

### CODE REVIEW

**Comment by davids5** [comment]
@dagar - I know we discussed this, but for the life of me I can not find the thread....

I need to have targets built that are not going to be deployed (yet) via qgc and for now I do not want them in the package but need them built for verification.

But I am not clear on the semantics of the some of the target list in the make file as they relate  to Travis: is it build only or build and deploy etc.

Would you please add document the specific list in the make file and how they relate to Travis them.
i.e
#qgc_firmware - targets listed here will be ... and deployed

Secondly.
How can we implement super low maintenance way to add targets in a commit that need to be build but do not case merge thrashing?

-include (additional_targets.mk) ?

Thank you!

**Comment by dagar** [comment]
I had to shuffle things around when travis-ci performance became unacceptable. 

If you want your target built and uploaded to s3 (where QGC downloads from) then add it to the `qgc_firmware` target. https://github.com/PX4/Firmware/blob/master/Makefile#L314
That currently runs on travis-ci, but could easily change as these free services continue to disappoint.

Add everything we care about to `check` and I'll keep that building somewhere. Currently semaphore-ci can handle it in a reasonable time, but as it grows it might need to move to actual hardware. @sanderux has made his server available for builds.

To resolve merge issues do you want to turn `check` into a single list with each on a separate line?

**Comment by LorenzMeier** [comment]
Rebased and force-pushed.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
