### PR TITLE
[DO NOT MERGE] uORB Subscription callback testing

### PR DESCRIPTION
**Pull request by dagar**
For testing https://github.com/PX4/Firmware/pull/12207

### CODE REVIEW

**Comment by mcsauder** [comment]
@dagar, I gave it a quick flight test and it was lively! :) https://review.px4.io/plot_app?log=adf7ed32-d3af-4559-bc49-3089d287e9e5

This definitely has an impact on timing, I might need to play with tuning gains.  The big thing that needs digging into was that the motors were occasionally twitching/spinning while landed and disarmed. 

I performed a few more short flights in manual mode only and position mode only with similar results.  Here is a manual flight: https://review.px4.io/plot_app?log=f6f65fd3-3a24-4d58-a5e5-aa05d2061ce9

**Comment by dagar** [comment]
Thanks Mark, do you have a good log from this vehicle close to master?

**Comment by mcsauder** [comment]
Hi @dagar, here is a flight from current master on the same airframe for an a/b comparison,
250 sized quad, Holybro pixhawk4 mini: https://review.px4.io/plot_app?log=01342848-e183-4ab3-ba2f-0c5ed2fca2de

**Comment by jorge789** [comment]
### Tested on Pixhawk 2 Cube V3:

Flight Card 1

Modes Tested:
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.

Procedure:
Arm in position mode, check take off behavior (Vehicle should stay on the ground as long as the throttle stick is at the middle or below, and start to ascend smoothly as long as throttle stick as above the middle.), the land and disarm.
Same procedure was repeated with Altitude and Stabilized mode.

Notes:
No issues were noted, good flight in general.

Flight Card 2

Modes Tested
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

Procedure
Arm and Take off in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

Note:
No issues were noted, good flight in general.

Flight Card 3

Modes Tested
Position Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

Procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

Note:
No issues were noted, good flight in general.

Logs:

Flight card 1:  https://review.px4.io/plot_app?log=889ff9ad-23e9-457a-97f8-aa9ed177e82e

Flight card 2:  https://review.px4.io/plot_app?log=0ac6a07c-9a03-4bad-bb04-7e6dce2ed9e4

Flight card 3 :  https://review.px4.io/plot_app?log=0969d351-92c8-414f-a6f9-2c1638a40360

Flight card 3:  https://review.px4.io/plot_app?log=0919a0f4-f2a1-4209-abdc-5e69fdba276c


### Tested on Pixhawk 2 Cube V3:

Modes Tested

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

- Procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

Notes:
No issues noted, good flight in general.

Logs: Comparison to master
https://review.px4.io/plot_app?log=3fdff52a-a110-4e11-b592-8263b1ffaf00

**Comment by mcsauder** [comment]
Here is an additional flight log on pixhawk 4 mini: https://review.px4.io/plot_app?log=08a780ff-9c15-4064-9bb2-27617521d1f7

**Comment by dannyfpv** [comment]
Tested on Pixhawk4 V5 f450 
Modes Tested 

Position Mode: no issue 
Altitude Mode: no issue 
Stabilized Mode: no issue
mission mode: no issue
rtl: no issue

logs:
fc #1:  https://review.px4.io/plot_app?log=4c8364bc-0bb2-4842-8232-ade808b64542

fc#2: https://review.px4.io/plot_app?log=de67c939-f6c3-4f02-866f-263f85176f7e

fc#3:  https://review.px4.io/plot_app?log=01e7590f-be7b-4db0-a844-262270dbfa80

fc#4:    https://review.px4.io/plot_app?log=45cd2709-cd60-43b1-bf01-c95d96336ee5

master log:

https://review.px4.io/plot_app?log=906cf7b4-0c3e-4abd-bd5f-bb3f110ce53e

**Comment by dagar** [comment]
Thanks everyone!

**Pull request closed without merging**
