### PR TITLE
Pr master fix

### PR DESCRIPTION
**Pull request by tumbili**
Thanks to @bkueng for teaching how to bisect.
@LorenzMeier FYI

### CODE REVIEW

**Comment by julianoes** [comment]
Why did this lead to 50% CPU of sensors? I don't quite understand.

**Comment by bkueng** [comment]
The chain of causality is rather non-obvious indeed:
publishing landing state with high frequency lead to parameter updates in ekf_att_pos_estimator which lead to param updates in sensors app, which caused high cpu by expensive calibration & param update calls.

**Comment by LorenzMeier** [comment]
@bkueng @tumbili Awesome job!

**Comment by julianoes** [comment]
Thanks for the explanation, nice work!

**Pull request merged**
