### PR TITLE
implement Spektrum bind function for Pixracer R14

### PR DESCRIPTION
**Pull request by kd0aij**
tested on R14 with DX7 and DSM2 satellite, no impact observed on R12

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice! Looks like we lost track of the GPIO change between revisions.

**Comment by kd0aij** [comment]
According to this document from Horizon Hobby: https://www.spektrumrc.com/ProdInfo/Files/Remote%20Receiver%20Interfacing%20Rev%20A.pdf
we should **always** issue 9 pulses to initiate a bind operation. This means that we should probably eliminate the other 2 options currently available. I have verified that this works with my vintage DX7 and DSM2 satellite. 

If we think that is a sufficient test, then this PR should also include elimination of values 0 and 1 for RC_DSM_BIND, leaving only the "2" option.

**Comment by LorenzMeier** [comment]
Can you issue a separate PR for that? We need to make sure QGC is in sync if we do that. A good intermediate step would be to ignore the param, then later remove it.

**Comment by kd0aij** [comment]
Will do.

**Pull request merged**
