### PR TITLE
Feature: Retry start px4flow

### PR DESCRIPTION
**Pull request by laube**
Implements retrying the I2C connection to the px4flow sensor. This fixes the problem that the px4flow is not detected during cold boot from battery as detailed in issue #2145.  
For this to work the px4flow driver needs to be launched in the background. Can somebody check that the correct rc file has been changed? It works like this for me.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looking good so far, need so cross-test on my system.

**Comment by LorenzMeier** [comment]
@kd0aij Would you mind giving that a try? Just knowing its running would be already great.

**Comment by kd0aij** [comment]
Looks good:
```
sercon: Successfully registered the CDC/ACM serial driver                                                   
[i] microSD mounted: /fs/microsd                                                                            
nshterm [6:70]                                                                                              
param: selected parameter default file /fs/mtd_params                                                       
[param] Loaded: /fs/mtd_params                                                                              
[rgbled] on I2C bus 2 at 0x55 (bus: 100 KHz, max: 100 KHz)                                                  
 1:   SYS_USE_IO: match                                                                                     
 4010: + SYS_AUTOSTART: match                                                                               
px4io: CRCs match                                                                                           
dataman: Power on restart, data manager file '/fs/microsd/dataman' size is 101504 bytes                     
[MS5611_SPI] on SPI bus 4 at 2 (11000 KHz)                                                                  
ms5611: no device on bus 4                                                                                  
[MS5611_SPI] on SPI bus 1 at 3 (11000 KHz)                                                                  
ms5611: no device on bus 1                                                                                  
ms5611: no device on bus 2                                                                                  
<adc> init done                                                                                             
ver hwcmp match: PX4FMU_V2                                                                                  
[HMC5883_I2C] on I2C bus 1 at 0x1e (bus: 100 KHz, max: 400 KHz)                                             
hmc5883: no device on bus 1                                                                                 
mpu6000: driver start failed                                                                                
[MPU6000] on SPI bus 1 at 4 (1000 KHz)                                                                      
[L3GD20] on SPI bus 1 at 1 (11000 KHz)                                                                      
[LSM303D] on SPI bus 1 at 2 (11000 KHz)                                                                     
meas_airspeed: no MS4525 airspeed sensor connected                                                          
ets_airspeed: no ETS airspeed sensor connected                                                              
ets_airspeed: no ETS airspeed sensor connected                                                              
px4flow [82:100]                                                                                            
sensors_task: mag cal status changed                                                                        
px4flow: PX4FLOW not found on I2C busses. Retrying in 1000 ms. Giving up in 5 retries.                      
[px4io] default PWM output device                                                                           
mavlink_if0: mode: 0, data rate: 5000 B/s on /dev/ttyS1 @ 57600B                                            
ver hwcmp match: PX4FMU_V2                                                                                  
[i] MULTICOPTER                                                                                             
+ MAV_TYPE: unchanged                                                                                       
[px4io] mixer sent                                                                                          
[i] Mixer: /etc/mixers/quad_x.main.mix on /dev/pwm_output0                                                  
 1: + INAV_ENABLED: match                                                                                   
                                                                                                            
NuttShell (NSH)                                                                                             
nsh> navigator: offboard mission updated: dataman_id=1, count=5, current_seq=0                              
sdlog2: log buffer size: 12288 bytes                                                                        
gps: ubx msg 0x0103 len 16 unexpected                                                                       
gps: ubx disabling msg 0x0103                                                                               
gps: ubx msg 0x0601 NAK                                                                                     
gps: not using NAV-PVT                                                                                      
px4flow: PX4FLOW not found on I2C busses. Retrying in 1000 ms. Giving up in 4 retries.                      
gps: VER hash 0xe0cc2322                                                                                    
gps: VER hw  "  00040007"                                                                                   
gps: VER sw  "                  7.03 (45970)"                                                               
gps: VER ext "                   7.03 (45969)"                                                              
gps: module found: UBX                                                                                      
px4flow: PX4FLOW not found on I2C busses. Retrying in 1000 ms. Giving up in 3 retries.                      
[PX4FLOW] on I2C bus 1 at 0x42 (bus: 100 KHz, max: 400 KHz)                                                 
telem> settings autosaved                                                                                   
position_estimator_inav: baro offset: 1631 m                                                                
mavlink_if0: Disabling hardware flow control                                                                
px4flow info                                                                                                
state @ 2000b820                                                                                            
px4flow_read: 91 events, 0 overruns, 246740us elapsed, 2711us avg, min 2657us max 3099us 92.966us rms       
px4flow_comms_errors: 0 events                                                                              
px4flow_buffer_overflows: 89 events                                                                         
poll interval:  100 ticks                                                                                   
report queue    2/112 (1/0 @ 20016120)                                                                      
nsh> ps                                                                                                     
PID   PRI SCHD TYPE   NP STATE    NAME                                                                      
    0   0 FIFO TASK      READY    Idle Task()                                                               
    1 192 FIFO KTHREAD   WAITSIG  hpwork()                                                                  
    2  50 FIFO KTHREAD   WAITSIG  lpwork()                                                                  
    3 100 FIFO TASK      RUNNING  init()                                                                    
   68 100 FIFO TASK      WAITSEM  dataman()                                                                 
  133 250 FIFO TASK      WAITSEM  attitude_estimator_q()                                                    
    6  70 FIFO TASK      WAITSIG  nshterm(10004170)                                                         
  103 100 FIFO TASK      WAITSIG  mavlink_if0(1000fff0, 1000d6d0, 1000af30, 1000a590)                       
  104 175 FIFO PTHREAD   WAITSEM  mavlink_rcv_if0(200123a0)                                                 
  138 250 FIFO TASK      WAITSEM  position_estimator_inav()                                                 
  140 250 FIFO TASK      WAITSEM  mc_att_control()                                                          
  142 250 FIFO TASK      WAITSEM  mc_pos_control()                                                          
  112  70 FIFO TASK      WAITSIG  sdlog2(1000ce90, 1000cea0, 1000ceb0, 1000cec0, 1000ced0, 1000cee0, 1000ce)
  145 100 FIFO TASK      WAITSIG  land_detector()                                                           
  148 250 FIFO TASK      WAITSEM  navigator()                                                               
   85 250 FIFO TASK      WAITSEM  sensors_task()                                                            
   87 220 FIFO TASK      WAITSEM  gps()                                                                     
   89 215 FIFO TASK      WAITSIG  commander()                                                               
   90  50 FIFO PTHREAD   WAITSEM  commander_low_prio(0)                                                     
   92 240 FIFO TASK      WAITSEM  px4io()                                                                   
nsh> 
```

**Comment by LorenzMeier** [comment]
Thanks for testing!

**Comment by yl5006** [comment]
I delay the   8s in the end ofrcS file and it work 
  usleep 8000000
        px4flow start
# End of autostart

**Pull request merged**
