### PR TITLE
Set altitude control flag for velocity control

### LINKED ISSUE #1856: Offboard velocity setpoints broken on master
We have reports that https://github.com/PX4/Firmware/pull/1786 introduced a regression that disables offboard velocity setpoints.

More tests are needed.

### PR DESCRIPTION
**Pull request by AndreasAntener**
@LorenzMeier @thomasgubler The only thing missing for velocity control was the right control flag setting, fixes #1856

Tested in SITL. Can anyone test this on a real one?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! I assume your SITL test was more or less complete?

**Comment by AndreasAntener** [comment]
Offboard yes, manual I haven't tried but I don't see any impact there.

**Comment by LorenzMeier** [comment]
It looks pretty solid and I'm merging it. Its better to have this in SITL-only than not.

**Comment by AndreasAntener** [comment]
Not sure what you mean with SITL-only, just to be sure: my commit changes it for both commanders

**Pull request merged**
