### PR TITLE
WIP: position control belnding during MC to FW transition for standard VTOL

### PR DESCRIPTION
**Pull request by AndreasAntener**
The current state of the transition is that we have a constant attitude setpoint (0 pitch/roll, fixed target heading as yaw) which comes naturally from a non-active MC position controller (disabled during the transition). The symptoms we see are the setpoint is not held properly (error too small) and it drifts off path. There are many ideas around on how this should be solved, so far I missed to provide the code for my own, so here it is ;)

I argue against "trims" on the actuator output level because they are impossible to set right and do not account for the changing dynamics during the transition.

How I would do it:
- [x] Position on horizontal plane: use the FW position controller and start using rudder right from the beginning.
- [ ] Altitude: have a mode in TECS where it is able to output a pitch setpoint with airspeed below the minimum

Notes on the implementation here:
- yaw support in SITL doesn't yet work as it should
- instead of adding yaw separately it should be added through the coordinated turn logic but maybe that is overdoing it
- the use of rudder on the back transition needs to be validated

### CODE REVIEW

**Comment by sanderux** [comment]
I think, no matter what approach we use, we should consider planes that do not have a rudder such as a delta wing. tecs seems to be counterproductive during front transition, if we can bypass this it might help. So which approach do you think we should use?

**Comment by AndreasAntener** [comment]
Sure, this works without rudder.

**Comment by sanderux** [comment]
ok i'll do some testing on your approach too

**Comment by sanderux** [comment]
Perhaps you could actuate flaps/flaperons too? that will be useful to implement in back transition

**Comment by tumbili** [comment]
@AndreasAntener @sanderux Let's have a look at this soon and possibly test this next week.

**Comment by sanderux** [comment]
I have a flight window saturday if there would be time to do something before then.

**Comment by LorenzMeier** [comment]
@tumbili Where is this standing?

**Comment by AndreasAntener** [comment]
closing this, will have a new version

**Pull request closed without merging**
