### PR TITLE
MAVLink app: Enable network and serial on POSIX

### PR DESCRIPTION
**Pull request by LorenzMeier**
This fixes some incorrect limitations that were present on POSIX UARTs.

### CODE REVIEW

**Comment by julianoes** [comment]
Reviewed, looks good to me. I tested POSIX SITL with jMAVSim and QGC which worked. I couldn't test the RC_CHANNELS_OVERRIDE yet.

**Comment by LorenzMeier** [comment]
You get RC input for SITL by attaching a Pixhawk, or by configuring the Taranis as Joystick.

**Comment by julianoes** [comment]
@LorenzMeier Can you give me any pointers how to route the incoming RC_CHANNELS_OVERRIDE into jMAVSim or gazebo?

**Comment by LorenzMeier** [comment]
You need to connect a Pixhawk, then the SITL app will try to open the port and read the MAVLink stream. You do *not* use the RC_OVERRIDE input.

**Comment by julianoes** [comment]
I found the hook for [jMAVSim](https://github.com/PX4/jMAVSim/blob/master/src/me/drton/jmavsim/Simulator.java#L320) but it seems WIP for SITL but I can't find it for gazebo...

**Comment by LorenzMeier** [comment]
https://github.com/PX4/Firmware/blob/master/src/modules/simulator/simulator_mavlink.cpp#L473

**Comment by julianoes** [comment]
@LorenzMeier it seems to me that we actually don't need RC_CHANNELS_OVERRIDE but the simulators already RC_CHANNELS.
RC_CHANNELS_OVERRIDE seems to be just duplicate using up bandwith.

**Pull request merged**
