### PR TITLE
[WIP] FW takeoff further limit roll and end climbout sooner

### PR DESCRIPTION
**Pull request by dagar**
Due to TECS climbout mode full throttle takeoff was overshooting the takeoff waypoint altitude and then diving. It's still not great, but this is an improvement.

### CODE REVIEW

**Comment by dagar** [comment]
@AndreasAntener @LorenzMeier have you had good results with FW landing flare? It has not worked well for me and often increases the descent rate. I've been experimenting with a faster initial descent then letting TECS handle flare with speed weight 2 and min airspeed.

**Comment by dagar** [comment]
I've added an in_takeoff_situation check for regular waypoints. That way you won't be completely screwed if you toss a plane directly into a normal mission without takeoff. It's also good enough for takeoff in HIL/SITL.

**Comment by dagar** [comment]
I'll rebase and test this again after https://github.com/PX4/Firmware/pull/4916 is merged.

**Comment by dagar** [comment]
WIP - needs to be rebased

**Comment by dagar** [comment]
Can I always use _ctrl_state.airspeed or do I need to check for an airspeed sensor?

**Comment by LorenzMeier** [comment]
@dagar The struct also has the bool field ```airspeed_valid``` which you should check.

**Pull request closed without merging**
