### PR TITLE
sdlog2 bugfix of vehicle_status conflicting with commander_state

### PR DESCRIPTION
**Pull request by julianoes**
This fixes a bug where vehicle_system_status and the commander internal
state were conflicting.

~~This will need adaptations in logging tools.
The change for FlightPlot is here: https://github.com/DrTon/FlightPlot/pull/62~~

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I don't see why we need to change the output format - can't you buffer the commander state in a local variable and just write it into the main logging thing? I certainly don't want to break all downstream tools for a trivial workaround.

**Comment by julianoes** [comment]
Right, technically feasible. Two points against it:

- I don't want tools to look at the commander internal state, otherwise commander state machine changes will be hard.
- The tools are sort of outdated in that respect anyway, see:
https://github.com/DrTon/FlightPlot/blob/master/src/me/drton/flightplot/export/PX4TrackReader.java
https://github.com/mavlink/mavlink/blob/master/pymavlink/tools/mavgraph.py#L41

Maybe we should publish to both for some transition time?

**Comment by LorenzMeier** [comment]
Removing it is a no-no. This is what we use to understand in what flight mode the system is, there is nothing "internal" about it. And all the tools rely on it and people have written deployed scripts. The value of the new message is marginal as we will likely move on to the new logger entirely. So I would prefer to just patch it up internally and update the tools so we have local stability. Then do all the cleanup using the new format.

**Comment by julianoes** [comment]
@LorenzMeier ok makes sense. Done and tested on Pixhawk.

**Comment by LorenzMeier** [comment]
Awesome, thanks!

**Pull request merged**
