### PR TITLE
Move variable initializations from MK class constructor to declarations.

### PR DESCRIPTION
**Pull request by mcsauder**
Hi,

This PR moves variable initialization in `mkblctrl.cpp` from a class constructor list to the variable declarations and initializes previously uninitialized variables.  It also standardizes comment formats and organizes/alphabetizes method and variable declarations.

Please let me know if you have questions on this PR.  Thanks!

-Mark

### CODE REVIEW

**Comment by mcsauder** [comment]
@dagar, I have applied uniform initialization to this PR as well.

**Comment by mhkabir** [comment]
I generally think we can safely deprecate this driver. I am not aware of anyone using it.

**Comment by dagar** [comment]
Does anyone have this on hand to test?

**Comment by mcsauder** [comment]
I've sent a correspondence to MikroKopter's customer support to discuss deprecation/continued support for this driver.  I will post updates as I have them.

**Comment by dagar** [comment]
Might as well close this until we decide what to do (deprecate or fully support with testing).

**Pull request closed without merging**
