### PR TITLE
Add workaround for flash data cache corruption on read-while-write

### PR DESCRIPTION
**Pull request by zehortigoza**

### CODE REVIEW

**Comment by zehortigoza** [comment]
@lucasdemarchi

**Comment by davids5** [comment]
@zehortigoza 

Do you investigate the cache reset (FLASH_ACR_DCRST) and determine it was not needed?

**Comment by zehortigoza** [comment]
@davids5 It is reseting,  I did not try without reset but I can give I try if you think that it don't need...
```
  /* reset data cache */
  value |= FLASH_ACR_DCRST;
  putreg32(value, STM32_FLASH_A
```

**Comment by davids5** [comment]
@zehortigoza - sorry I missed it.  Thank you!

**Pull request merged**
