### PR TITLE
ecl: Update ekf2 to version that addresses known vulnerabilities

### PR DESCRIPTION
**Pull request by priseborough**
Addresses  loss of height accuracy during sustained yaw spinning and vulnerability to transient sensor errors after in-flight yaw alignment. See:

https://github.com/PX4/ecl/pull/350
https://github.com/PX4/ecl/pull/354

Note the amount of stack allocation has had to be increased to accomodate the potential for larger data buffers created by PR350

One hardware test using a pixracer board https://logs.px4.io/plot_app?log=f3f3826d-f8a7-4fac-91ed-f57c4a2945c1

### CODE REVIEW

**Comment by priseborough** [comment]
@PX4TestFlights

**Comment by santiago3dr** [comment]
full flight with quad running pixracer (v4)
https://logs.px4.io/plot_app?log=80dbdaf2-204b-4427-a34c-58c8c1131390

manual take-off; several full yaws in all modes; stopped and re-engaged auto a few times without issues; solid flight performance

**Comment by Avysuarez** [comment]
Flight with pixhawk 1 (V2). Good flight, no issues.
https://review.px4.io/plot_app?log=eb12e598-4d56-4099-9000-38bd28e29499

**Comment by priseborough** [comment]
Logs look OK.

**Pull request merged**
