### PR TITLE
MPU6K 16g range

### PR DESCRIPTION
**Pull request by LorenzMeier**
This lets the MPU6K default to 16g range. This is required because the previous 8g range led to clipping on a number of airframes, resulting on non-zero mean access readings during flight (vibration) and consequently attitude offsets.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@kd0aij Could you you a quick quad test flight with this one?

**Comment by LorenzMeier** [comment]
Also need to disable the hardware filters by default probably.

**Comment by LorenzMeier** [comment]
@sjwilks @AndreasAntener @tumbili Another change that I've been holding off but which will hit master soon. This is to avoid aliasing in high-vibration environments.

**Comment by kd0aij** [comment]
Is there any downside to reducing accelerometer sensitivity?

**Comment by LorenzMeier** [comment]
Since we do it for zero-mean offset estimation of the gyros - not for attitude. For linear acceleration it might have effects, but the gains of not aliasing should outweigh those.

What I can report is that flight performance goes up with this change, as Paul has validated that extensively.

**Pull request closed without merging**
