### PR TITLE
LPE minor improvement

### PR DESCRIPTION
**Pull request by stmoon**
I found some sensors don't have a selection chance for sensor fusion in LPE.

I added options for that sensors (MOCAP, LIDAR, and SONAR).

### CODE REVIEW

**Comment by stmoon** [comment]
Hi, 

Could you please check it @jgoppert  and @TSC21 ?

I want to go to next step.

**Comment by TSC21** [comment]
@LorenzMeier these changes actually are not right for different reasons. I was out travelling this week and I didn't get a chance to review them. Do I apply a correction to reverse them?

**Comment by LorenzMeier** [comment]
Yes please - could you do that quickly?

**Comment by TSC21** [comment]
Will do it this noon.

**Pull request merged**
