### PR TITLE
update NuttX to 7.29

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
This gives a rough idea of where things changed.

``` Console
dagar@dagar-desktop:~/git/Firmware$ make px4_fmu-v4_default bloaty_compare_master
[1/1] cd /home/dagar/git/Firmware/build/px4_fmu-v4_default && wget --no-verbose https://s3.amazonaws.com/px4-travis/Firmware/master/px4_...-d symbols -n 50 -C full -s vm /home/dagar/git/Firmware/build/px4_fmu-v4_default/px4_fmu-v4_default.elf -- master_px4_fmu-v4_default.elf
2019-06-26 22:50:09 URL:https://s3.amazonaws.com/px4-travis/Firmware/master/px4_fmu-v4_default.elf [24121936/24121936] -> "master_px4_fmu-v4_default.elf" [1]
     VM SIZE                               FILE SIZE
 --------------                         --------------
  [NEW] +1.87Ki lib_vscanf              +1.87Ki  [NEW]
  +127% +1.10Ki lib_vsprintf            +1.10Ki  +127%
  [NEW]    +456 __dtoa_engine              +456  [NEW]
  [NEW]    +436 nx_start                   +436  [NEW]
  [NEW]    +208 nxtask_argsetup            +208  [NEW]
  [NEW]    +160 nxthread_create            +160  [NEW]
  [NEW]    +156 strtoll                    +156  [NEW]
  [NEW]    +134 nxtask_exithook            +134  [NEW]
  [NEW]    +128 g_dtoa_round               +128  [NEW]
  [NEW]    +108 nxtask_schedsetup          +108  [NEW]
  [NEW]     +96 nxtask_spawn_exec           +96  [NEW]
  [NEW]     +96 nxtask_terminate            +96  [NEW]
  [NEW]     +96 page_sizes.7227             +96  [NEW]
  [NEW]     +88 nxtask_assignpid            +88  [NEW]
  [NEW]     +80 nxtask_exit                 +80  [NEW]
   +78%     +76 romfs_hwconfigure           +76   +78%
  [NEW]     +74 pthread_mutex_timedlock     +74  [NEW]
  [NEW]     +72 g_dtoa_scale_down           +72  [NEW]
  [NEW]     +72 g_dtoa_scale_up             +72  [NEW]
  [NEW]     +66 __ultoa_invert              +66  [NEW]
   +41%     +62 strtoull                    +62   +41%
   +53%     +56 strtoul                     +56   +53%
  [DEL]     -62 hi0bits                     -62  [DEL]
  -0.0%     -64 [91 Others]              +196Ki  +0.9%
  [DEL]     -64 freelist                      0  [ = ]
 -91.4%     -64 pthread_mutex_lock          -64 -91.4%
  [DEL]     -74 utohex                      -74  [DEL]
  [DEL]     -80 task_exit                   -80  [DEL]
  [DEL]     -88 multadd.constprop.0         -88  [DEL]
  [DEL]     -88 task_assignpid              -88  [DEL]
  [DEL]     -94 lo0bits                     -94  [DEL]
  [DEL]     -96 page_sizes.7095             -96  [DEL]
  [DEL]     -96 task_spawn_exec             -96  [DEL]
  [DEL]     -96 task_terminate              -96  [DEL]
  [DEL]    -104 llutohex                   -104  [DEL]
  [DEL]    -108 task_schedsetup            -108  [DEL]
  [DEL]    -124 pow5mult                   -124  [DEL]
  [DEL]    -134 task_exithook              -134  [DEL]
  [DEL]    -160 thread_create              -160  [DEL]
  [DEL]    -166 lshift                     -166  [DEL]
  [DEL]    -174 mult                       -174  [DEL]
  [DEL]    -184 tens                       -184  [DEL]
  [DEL]    -208 task_argsetup              -208  [DEL]
  [DEL]    -212 utoascii                   -212  [DEL]
  [DEL]    -224 quorem                     -224  [DEL]
  [DEL]    -274 llutoascii                 -274  [DEL]
  [DEL]    -360 prejustify                 -360  [DEL]
  [DEL]    -404 lib_dtoa.isra.1            -404  [DEL]
  [DEL]    -436 os_start                   -436  [DEL]
 -96.5%    -988 vsscanf                    -988 -96.5%
  [DEL] -3.35Ki __dtoa                  -3.35Ki  [DEL]
  -0.2% -2.82Ki TOTAL                    +194Ki  +0.8%
```

**Comment by dagar** [comment]
px4io-v2_default build failure

This gives a rough idea of where things changed.

``` Console

[196/200] Generating nuttx/libs/libc/libc.a
FAILED: cd /home/dagar/git/Firmware/build/px4_io-v2_default/NuttX/nuttx && find libs/libc -type f -name *.o -delete && make -C libs/libc --quiet --no-print-directory all TOPDIR=/home/dagar/git/Firmware/build/px4_io-v2_default/NuttX/nuttx KERNEL=n EXTRADEFINES= >nuttx_build.log
In file included from signal/sig_psignal.c:42:0:
signal/sig_psignal.c: In function 'psignal':
signal/sig_psignal.c:82:21: error: invalid type argument of '->' (have 'int')
       (void)fprintf(stderr, "%s: %s\n", message, strsignal(signum));
                     ^
signal/sig_psignal.c:86:21: error: invalid type argument of '->' (have 'int')
       (void)fprintf(stderr, "%s\n", strsignal(signum));
                     ^
make[1]: *** [bin/sig_psignal.o] Error 1


```

**Comment by dagar** [comment]
We're getting low on flash in px4_fmu-v2 again.

**Comment by thomasgubler** [comment]
@MikeGoesDrones will assist in getting flight hours on this one before the merge

**Comment by davids5** [comment]
@PX4/testflights , @MikeGoesDrones Please test on V5:Pro,Mini, V4:Mro,NXP, V3:Mro HW

**Comment by dagar** [comment]
Rebased on master and NuttX 7.29+ submodule updated with @bkueng's UART ioctl changes. https://github.com/PX4/NuttX/pull/54

**Comment by jorge789** [comment]
### Tested on PixRacer V4:
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:**
https://review.px4.io/plot_app?log=422782a3-8c40-4d07-89d4-6c0f4f9690cc

https://review.px4.io/plot_app?log=f6131e92-5859-4844-8fc8-ab6a94999574

**Comparison to master:**
https://review.px4.io/plot_app?log=b115a115-c0d9-418c-bdf9-9990201f4089


### Tested on Pixhawk 2 Cube V3:
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:**
https://review.px4.io/plot_app?log=6fbe2b9d-70b2-4030-b414-edf4c58c9247

**Comparison to master:**
https://review.px4.io/plot_app?log=6a5c3cca-8a5b-4beb-bb06-4b2df598869f

**Comment by dagar** [comment]
Any news @MikeGoesDrones (good or bad)?

**Comment by dannyfpv** [comment]
Tested on Pixhawk4 v5 f-450
Modes Tested: 

Position Mode: no issue 
Altitude Mode: no issue 
Stabilized Mode: no issue 
mission mode : no issues
pr log:
https://review.px4.io/plot_app?log=eeb8091a-f69e-4898-b618-3b7aa701d4c6

master log:
https://review.px4.io/plot_app?log=875cb2b2-79d5-4953-b13b-69fe9dba9c9e

**Comment by Junkim3DR** [comment]
### Tested on Pixhawk 4mini v5:

**Modes Tested:**
- Position Mode: Good.
- Altitude Mode: Good.
- Stabilized Mode: Good.
- Mission Plan Mode (Automated): Good.
- RTL: Good.

**Procedure:**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Logs:**

- PR12344: https://review.px4.io/plot_app?log=21355022-ce22-4822-a3be-edf957f1f875

- Master: https://review.px4.io/plot_app?log=20ddbd80-9dc5-4702-9ef2-6ac583c01450



### Tested on Pixhawk Pro v4:

**Modes Tested:**
- Position Mode: Good.
- Altitude Mode: Good.
- Stabilized Mode: Good.
- Mission Plan Mode (Automated): Good.
- RTL: Good.

**Procedure:**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Logs:**
- PR12344: https://review.px4.io/plot_app?log=1638740e-fc12-496a-bbd3-4be30a2f13e3

- Master: https://review.px4.io/plot_app?log=e67424c5-e435-49f1-9b82-c298f5e643d9

### Tested on NXP FMUK66 v3:

**Modes Tested:**
- Position Mode: Good.
- Altitude Mode: Good.
- Stabilized Mode: Good.
- Mission Plan Mode (Automated): Good.
- RTL: Good.

**Procedure:**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Logs:**
- PR12344: https://review.px4.io/plot_app?log=05b18234-c80e-4dbf-8464-6f7f74de4082

- Master: https://review.px4.io/plot_app?log=ab3333a4-175f-40f8-87d3-6dc6b927d0eb

**Pull request merged**
