### PR TITLE
Mavlink fixes & perf improvement

### PR DESCRIPTION
**Pull request by bkueng**
- add optional `disable_sharing` flag to `add_orb_subscription`.
  It is a more generic solution for 532a97041, and also enables it for vehicle_command_ack's.
- `MavlinkOrbSubscription::update`:
    - reorders operations, such that the most expensive one (orb_copy) is done only when really needed.
    - fix corner case: when the topic was not advertised yet, orb_stat() would fail and then update() was called, which succeeds for the first advertisement.
      In that case the timestamp was incorrectly set to 0 and true was returned. The next call would again return true, because the timestamp was updated, but the topic data was still the same.
    
Reduces CPU load by ~2% on a Pixracer.

### CODE REVIEW

**Comment by jdzerve** [comment]
This should be revisited.
The behavior has changed but description has not. Strictly speaking description was incorrect before this commit, too.
We are talking about MavlinkOrbSubscription::update(uint64_t *time, void *data)
In particular:
1) Description "If no data available data buffer will be filled with zeros." is/was not true.
https://github.com/PX4/Firmware/blob/75f1ad36d1210560f00da8f4fa3bddbb3da9da16/src/modules/mavlink/mavlink_orb_subscription.h#L62

2) Description part "will still copy the data" is not true any more.
The problem is that there is a code in MavlinkStreamSysStatus::send which actually relies on the documented behavior (copy even if not updated):
https://github.com/PX4/Firmware/blob/75f1ad36d1210560f00da8f4fa3bddbb3da9da16/src/modules/mavlink/mavlink_messages.cpp#L571

The result is that sometimes SYS_STATUS message goes out with zeroes in onboard_control_sensors_* fields.

I could provide PR because for this particular case but cannot do 100% fix as I'm not that familiar with code to know where else this behavior is relied upon.

**Comment by LorenzMeier** [comment]
Thanks for raising this!

**Comment by bkueng** [comment]
@jdzerve yes, please send a PR to update the comments and fix SYS_STATUS, thanks!
@eyeam3 are you aware of more places?

**Comment by dagar** [comment]
I also stumbled across this when updating the uORB subscription wrappers in mavlink for https://github.com/PX4/Firmware/pull/11176. In that PR I restored the before as described in the comments (zeroing if no data, copy even if not updated) as a precaution, and because it was cheaper with the new interface. 

That PR is going to take time to settle after v1.9.0 is released. I would suggest a quick fix for `SYS_STATUS` right now.

**Comment by jdzerve** [comment]
This is my fix:
https://github.com/jdzerve/Firmware/commit/4f59cf29029f87f02790c9ffee35b4ee70dc84bc
@dagar: Yours is little more involved, so I guess it's more appropriate.

**Pull request merged**
