### PR TITLE
mc_pos_control: do not do tilt compensation when hor velocity is cont…

### PR DESCRIPTION
**Pull request by tumbili**
…rolled

- fixed a bug where tilt compensation was done also when the horizontal
velocity was controlled. This is not needed because in this case
the controller outputs a 3D thrust vector.

Signed-off-by: Roman <bapstroman@gmail.com>

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@MaEtUgR Can you please include this patch in your Intel Aero test flights today?

**Comment by Stifael** [comment]
Initially the that part in the code was for thrust compensation if only in altitude mode. However, @tumbili is correct that this compensation even occurs in position control mode.

**Comment by Stifael** [comment]
The part of the code was intended to be used in altitude control. However, the if statement is also entered in position control mode and therefore @tumbili's change will fix that issue.

**Comment by devbharat** [comment]
@tumbili why wouldn't we want to not limit tilt angles position is controlled? For example, say inner loop pitch tracking is only guaranteed until 60 degrees, you'd never want to have the velocity loop set an angle setpoint beyond that angle.

**Comment by devbharat** [comment]
I think the real problem in this piece of tilt angle limiting code is the `saturation_z` flag. As soon as the tilt setpoint goes beyond the set max parameter, the  `saturation_z` flag is set true. This stops the altitude integral from incrementing/decrementing and leads to poor climbrate control until titl angle setpoint is brought back within bounds. This isn't optimal when you are falling down as the integral would not only stop the 'falling down' but reduce the tilt angle doing it! It's required only when you are climbing up and integral_z is trying to reduce thrust_sp(2) which would increase the tilt angle.

For example, consider moving forward by pitching down in position control(or altitude control) and losing altitude, if your pitch setpoint for the desired velocity is greater than PITCH_MAX, you'd freeze the altitude integral and continue to lose altitude until you center the stick can bring pitch setpoint back within bounds. This is not optimal because had the integral_z not been frozen by  `saturation_z` flag, it'd have increased thrust_sp(2) and actually helped bringing pitch_sp back within bounds!

Thus, you should be freezing the integral_z here only if the _vel(2) error is positive (aircraft is climbing more than required). Hope I was clear.

**Comment by tumbili** [comment]
@devbharat Referring to your first comment: I don't see the relation between what you said and the content of this PR. All I did was to disable altitude thrust compensation for modes which control the 3D thrust vector.

I'm also not very sure about your second comment. The piece of code for which this PR is (attitude compensation) is only for altitude controlled modes so there is no position control involved in this as you mentioned above. There is also no "bringing pitch_sp back within bounds" in altitude control mode because the user directly commands the pitch setpoint, the controller just does the thrust.

However, the problem of freezing the integrator when the actual tilt is larger than the max allowed tilt (which might well be due to poor attitude control) sounds interesting.

**Comment by devbharat** [comment]
> @devbharat Referring to your first comment: I don't see the relation between what you said and the content of this PR. All I did was to disable altitude thrust compensation for modes which control the 3D thrust vector.

You are right, I was talking about the block of code right above it, the one that limits max tilt. My bad.

For the comment on saturation flag, that still stands though. I'll make a PR for that and refer here.

**Comment by tumbili** [comment]
@devbharat That sounds good.

**Pull request merged**
