### PR TITLE
WIP: Add msg parser using regex/ generate listener with jinja

### PR DESCRIPTION
**Pull request by jgoppert**
This improves the msg parser and so we  can scan topics etc easier.

Closes #https://github.com/PX4/Firmware/issues/6607

### Tasks
- [x] Add parser
- [ ] Add jinja2 template for listener.

### CODE REVIEW

**Comment by dagar** [comment]
What about combining this with the existing scripting that already parses the msg files? It seems like the listener code could be generated during the same stage, but placed in a separate module for optional compilation.

**Comment by LorenzMeier** [comment]
Nice! What is the status of the jinja2 template for the listener (open TODO in your list)?

**Comment by jgoppert** [comment]
@LorenzMeier The listener is about half way done. I set this up because @mhkabir needed it and I was hoping he would have time to finish it so he could learn the jinja syntax. @mhkabir let me know if you don't have time and I will finish it. Most of the hard part is done, just needs polishing and to do a diff on the output to make sure it matches the old generation.

**Comment by mhkabir** [comment]
@jgoppert I don't have the bandwidth to do this right now. Not for 2-3 weeks atleast. Would be great if you could pick it up.

**Comment by dagar** [comment]
@jgoppert what do you think about generating the listener stubs as part of the existing msg generation? Then it'll line up with the virtual topics. Only the listener module will build the stubs.

**Comment by dagar** [comment]
Closing as stale. This should be combined with the core message generation.

**Pull request closed without merging**
