### PR TITLE
navio_adc: add driver for Navio2 ADC - 

### PR DESCRIPTION
**Pull request by nicolaerosia**
Hello,

This is my first attempt to make a Navio2 ADC driver for #7211 . Documentation is available [here](https://docs.emlid.com/navio2/dev/adc/) for Navio2.

Currently I'm having troubles getting sensors to see the adc driver:
```
[user@mhome px4]$ ./src/firmware/posix/px4 .
commands file: .
18446744073709551267 WARNING: setRealtimeSched failed (not run as root?)

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

pxh> uorb start
pxh> navio_adc start
INFO  [navio_adc] NavioADC::ctor
INFO  [navio_adc] init done
pxh> sensors start
ERROR [sensors] no ADC found: /dev/adc0 (9)
ERROR [sensors] no barometer found on /dev/baro0 (9)
pxh> list_devices
INFO  [drivers__device] PX4 Devices:
INFO  [drivers__device]    /dev/adc0
INFO  [drivers__device] DF Devices:
pxh> list_files
INFO  [drivers__device] Files:
pxh> 
```

I see sensors use DevMgr to get a handle DevHandle. Have I inherited the wrong class (VDev) ?
Any pointers are appreciated, ping @bkueng

This is WIP, I added the driver to SITL only for dry-testing.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Yes - the POSIX drivers should (counter-intuitively) base off https://github.com/PX4/Firmware/tree/master/src/platforms/posix/drivers and be implemented in DriverFramework: https://github.com/PX4/DriverFramework

We will consolidate that with the NuttX drivers, but that hasn't happened yet.

**Comment by nicolaerosia** [comment]
Thank you, @LorenzMeier .
Should I target DriverFramework instead? That would require creating a wrapper for ... nothing.
I have successfully tested this driver with a 3DR power module (sold by Emlid):

```
param set BAT_CNT_V_VOLT 0.001
#param set BAT_V_DIV 10.9176300578
param set BAT_V_DIV 10.8645533141
param set BAT_N_CELLS 4
param set BAT_CAPACITY 6200

param set BAT_CNT_V_CURR 0.001
param set BAT_A_PER_V 15.391030303

# no load
pxh> listener battery_status

TOPIC: battery_status #1
timestamp: 21757481
voltage_v:  15.1318
voltage_filtered_v:  15.1386
current_a:   0.0000
current_filtered_a:   0.0000
discharged_mah:   0.0006
remaining:   0.5129
scale:   1.0965
cell_count: 4
connected: True
warning: 0

pxh> navio_adc test
INFO  [navio_adc] chan: 0; value: 5222
INFO  [navio_adc] chan: 1; value: 36
INFO  [navio_adc] chan: 10; value: 1384
INFO  [navio_adc] chan: 255; value: 0
INFO  [navio_adc] chan: 4; value: 20
INFO  [navio_adc] chan: 5; value: 32

# load
pxh> commander arm
pxh> listener battery_status

TOPIC: battery_status #1
timestamp: 207425495
voltage_v:  14.8916
voltage_filtered_v:  14.9058
current_a:   0.1231
current_filtered_a:   0.1813
discharged_mah:   0.5273
remaining:   0.6545
scale:   1.0666
cell_count: 4
connected: True
warning: 0
```

Ready for review from my POV.

**Comment by LorenzMeier** [comment]
This looks good. Could you also add the required startup script adjustments so that it all works for a standard setup out of the box?

**Comment by nicolaerosia** [comment]
@LorenzMeier thank you, I've amended the commit & force pushed.

**Comment by LorenzMeier** [comment]
What about battery voltage params? They are not in the startup script, are they?

**Comment by nicolaerosia** [comment]
You are right, I added them now.

**Comment by mhkabir** [comment]
CI is failing on formatting. Please run `make format`.

**Comment by nicolaerosia** [comment]
Fixing now

**Comment by nicolaerosia** [comment]
@mhkabir done

**Pull request merged**
