### PR TITLE
Added landed agl correction for lpe.

### LINKED ISSUE #5658: LPE (AGL as Z): Massive althold 'jump'.
@jgoppert Using LPE_PUB_AGL_Z enabled, I had a serious altitude jump indoors:

local_z

In this case LPOS.Z had been about 3.5m at arming - I assume, this came from baro. In some cases LPOS.Z with LPE_PUB_AGL_Z is set to ground distance when LIDAR initializes soon after takeoff. Here, this was not the case (due to the baro based LPOS.Z?). In the messages i noticed 

2000_01_01_05_51_05: [lpe] lidar fault,  beta  9.21
2000_01_01_05_51_06: [lpe] lidar fault,  beta 31.74

Any position estimation (GPS,Flow,Vision) was disabled. LIDAR seems working fine all the time. I also noticed, that in the beginning Althold was not working very well.

My assumption is, that with AGL_Z enabled, LPOS.Z was set to ground distance at that point in time. This let the position controller assume that the vehicle was far to low.

The log: http://logs.uaventure.com/view/iNiUzgu5dZpiBQNGc5fyVd

Please note also: To achieve precise Althold, I've set LPE_BAR_Z to 20.

### PR DESCRIPTION
**Pull request by jgoppert**
This simulates a lidar when you are landed, or disarmed and not in freefall and you don't have a sonar/ mocap/ vision/ or lidar measurement initialized. This should prevent agl drift from baro while on ground. I've tried it in simulation, but need to test in real life. @ecmnet Hopefully this fixes #5658 for you.

### CODE REVIEW

**Comment by jgoppert** [comment]
@LorenzMeier is this what you had in mind?

**Comment by LorenzMeier** [comment]
Nice, yes, much better! This also will prevent that people using the AGL estimate are confused as to why its drifting on the ground.

**Comment by ecmnet** [comment]
@jgoppert After first tests, it works fine on my device. It considers the landed state as a valid input for Z-position estimation. One additional question: I have maintained LPE_LDR_OFF_Z to adjust the mounting offset of the lidar. When lidar initializes the first time, this offset is taken into account like this:

chart

To avoid that, the landing state could publish some kind of offset as well. Correct?

**Comment by ecmnet** [comment]
@jgoppert Another small issue could be that AGL is not published in all cases. Terrain and ASL are set to the same value, while AGL stays 0 even when LPOS.Z shows the altitude above ground with LPE_AGL_Z enabled.

**Comment by ecmnet** [comment]
After some more tests and flights, I have no baro drift issue anymore. Switching to AltHold is now stable and reliable.

**Comment by jgoppert** [comment]
@ecmnet I think the landing offset should always be zero, since you want agl to be zero when landed. Maybe your lidar offset could be adjusted for agl zero when landed?

**Comment by jgoppert** [comment]
@ecmnet on agl publication,  it should publish when terrain estimate is valid (low covariance) pub agl z still needs to publish something even when you don't have a terrain estimate.  So that all makes sense, but not sure what to change, or if we should. I think publishing agl indicates that we know the ground is beneath us, which with just gps and baro we don't actually know.

**Pull request merged**
