### PR TITLE
default to INAV/Q estimator on FMUv1

### PR DESCRIPTION
**Pull request by kd0aij**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Did you test this? From code review I wasn't entirely sure.

**Comment by kd0aij** [comment]
these changes were flight tested on a branch off master; getting ready to flight test this version now

**Comment by LorenzMeier** [comment]
It looks from your flight tests like this could use more testing before merging?

**Comment by kd0aij** [comment]
The INAV/Q config looks OK in terms of memory usage:
```
nsh> ps
PID   PRI SCHD TYPE   NP STATE    NAME
    0   0 FIFO TASK      READY    Idle Task()
    1 240 FIFO KTHREAD   WAITSEM  hpwork()
    2  50 FIFO KTHREAD   WAITSIG  lpwork()
    3 100 FIFO TASK      RUNNING  init()
    6  70 FIFO TASK      WAITSEM  nshterm(10004140)
  135 250 FIFO TASK      WAITSEM  mc_pos_control()
  137 100 FIFO TASK      WAITSIG  land_detector()
  106  70 FIFO TASK      WAITSIG  sdlog2(10004130, 10004d70, 10006860, 10006870)
  140 120 FIFO TASK      WAITSEM  navigator()
  143 100 FIFO TASK      WAITSIG  mavlink_if0(2000bd80, 2000ba40, 2000d8a0, 100)
  144 175 FIFO PTHREAD   WAITSEM  mavlink_rcv_if0(20009510)
   82 250 FIFO TASK      WAITSEM  sensors_task()
   84 220 FIFO TASK      WAITSEM  gps()
   86 215 FIFO TASK      WAITSIG  commander()
   87  50 FIFO PTHREAD   WAITSEM  commander_low_prio(0)
  120 250 FIFO TASK      WAITSEM  attitude_estimator_q()
   89 240 FIFO TASK      WAITSEM  px4io()
  123 250 FIFO TASK      WAITSEM  position_estimator_inav()
  125 250 FIFO TASK      WAITSEM  mc_att_control()
   63 100 FIFO TASK      WAITSEM  dataman()

nsh> free
             total       used       free    largest
Mem:        183568     149376      34192      30416

Processes: 21 total, 3 running, 18 sleeping
CPU usage: 18.08% tasks, 0.70% sched, 81.22% idle
Uptime: 172.393s total, 143.018s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
   0 Idle Task                  143018 81.221     0/    0   0 (  0)  READY 
   1 hpwork                       4080  2.395   708/ 1792 240 (192)  w:sig 
   2 lpwork                        501  0.231   364/ 1792  50 ( 50)  w:sig 
   3 init                          226  0.000  1428/ 2992 100 (100)  w:sem 
   6 nshterm                         0  0.000   644/ 1496  70 ( 70)  w:sem 
 147 top                           174  2.472  1164/ 1696 100 (100)  RUN   
  63 dataman                       307  0.000   612/ 1792 100 (100)  w:sem 
  82 sensors_task                 4114  2.395  1220/ 1992 250 (250)  w:sem 
  84 gps                           785  0.000   708/ 1496 220 (220)  w:sem 
  86 commander                     761  0.386  2748/ 3392 215 (215)  w:sig 
  87 commander_low_prio             69  0.000   884/ 2592  50 ( 50)  w:sem 
  89 px4io                        3551  2.086   908/ 1792 240 (240)  w:sem 
 143 mavlink_if0                  2467  1.391  1828/ 2392 100 (100)  w:sig 
 144 mavlink_rcv_if0                11  0.000   788/ 2096 175 (175)  w:sem 
 106 sdlog2                        270  0.077  1844/ 2992  70 ( 70)  w:sig 
 120 attitude_estimator_q         3177  1.854  1444/ 2496 250 (250)  w:sem 
 123 position_estimator_inav      2801  1.545  4052/ 4992 250 (250)  w:sem 
 125 mc_att_control               3684  2.086   996/ 1496 250 (250)  w:sem 
 135 mc_pos_control                873  0.463  1044/ 1496 250 (250)  w:sem 
 137 land_detector                 282  0.154   524/  992 100 (100)  w:sig 
 140 navigator                    1024  0.540   900/ 1696 120 (120)  w:sem 
```

**Comment by kd0aij** [comment]
also OK running ekf_att_pos_estimator (INAV_ENABLED=0):
```
nsh> ps
PID   PRI SCHD TYPE   NP STATE    NAME
    0   0 FIFO TASK      READY    Idle Task()
    1 240 FIFO KTHREAD   WAITSIG  hpwork()
    2  50 FIFO KTHREAD   WAITSIG  lpwork()
    3 100 FIFO TASK      RUNNING  init()
  133 100 FIFO TASK      WAITSIG  land_detector()
    6  70 FIFO TASK      WAITSEM  nshterm(10004140)
  136 120 FIFO TASK      WAITSEM  navigator()
  106  70 FIFO TASK      WAITSIG  sdlog2(10004d70, 20008690, 200086a0, 200086b0)
  140 100 FIFO TASK      READY    mavlink_if0(2000ba40, 1000eeb0, 2000c030, 100)
  141 175 FIFO PTHREAD   WAITSEM  mavlink_rcv_if0(20009500)
   82 250 FIFO TASK      WAITSEM  sensors_task()
   84 220 FIFO TASK      WAITSEM  gps()
  117 215 FIFO TASK      WAITSEM  ekf_att_pos_estimator()
   86 215 FIFO TASK      WAITSIG  commander()
   87  50 FIFO PTHREAD   WAITSEM  commander_low_prio(0)
   89 240 FIFO TASK      WAITSEM  px4io()
  122 250 FIFO TASK      WAITSEM  mc_att_control()
  124 250 FIFO TASK      WAITSEM  mc_pos_control()
   63 100 FIFO TASK      WAITSEM  dataman()

nsh> free
             total       used       free    largest
Mem:        183568     162496      21072      18624

Processes: 20 total, 2 running, 18 sleeping
CPU usage: 31.66% tasks, 0.70% sched, 67.65% idle
Uptime: 116.350s total, 80.366s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
   0 Idle Task                   80366 67.647     0/    0   0 (  0)  READY 
   1 hpwork                       2624  2.244   844/ 1792 240 (192)  w:sem 
   2 lpwork                        326  0.232   364/ 1792  50 ( 50)  w:sig 
   3 init                          208  0.000  1404/ 2992 100 (100)  w:sem 
   6 nshterm                         0  0.000   660/ 1496  70 ( 70)  w:sem 
 143 top                            36  2.167  1164/ 1696 100 (100)  RUN   
  63 dataman                       312  0.000   612/ 1792 100 (100)  w:sem 
  82 sensors_task                 2629  2.321  1220/ 1992 250 (250)  w:sem 
  84 gps                           540  0.000   708/ 1496 220 (220)  w:sem 
  86 commander                     539  0.386  2748/ 3392 215 (215)  w:sig 
  87 commander_low_prio             61  0.000   884/ 2592  50 ( 50)  w:sem 
  89 px4io                        1907  1.625   796/ 1792 240 (240)  w:sem 
 140 mavlink_if0                  1604  1.315  1836/ 2392 100 (100)  w:sig 
 141 mavlink_rcv_if0                 8  0.000   788/ 2096 175 (175)  w:sem 
 106 sdlog2                        203  0.077  1844/ 2992  70 ( 70)  w:sig 
 117 ekf_att_pos_estimator       22055 19.117  3700/ 7496 215 (215)  w:sem 
 122 mc_att_control               1112  0.928   996/ 1496 250 (250)  w:sem 
 124 mc_pos_control                753  0.619  1060/ 1496 250 (250)  w:sem 
 133 land_detector                 188  0.077   524/  992 100 (100)  w:sig 
 136 navigator                     692  0.541   796/ 1696 120 (120)  w:sem 
```

**Comment by LorenzMeier** [comment]
Do you have a recent flight log with the Q estimator?

**Comment by kd0aij** [comment]
That would be the first flight report I generated yesterday. Is there any means for me to see what reports I've submitted and to get links to them?
I could use some help interpreting the log; although I thought altitude control was poor, the log doesn't seem to agree with me:
posctl

**Comment by kd0aij** [comment]
Q estimator rate tracking: (excessive overshoot in pitch was since remedied by increasing D gain)
ratetracking

**Comment by kd0aij** [comment]
The CG of the QAV250 is significantly behind the frame center, so pitch control is a bit sloppy, but this isn't a problem in normal operation.
after increasing pitchRate D gain:
pitchtracking

**Comment by kd0aij** [comment]
Log muncher links in case the flight reports got lost:
http://dash.oznet.ch/view/25v8xbwFRyyDZzL9pyTZkL
http://dash.oznet.ch/view/zEBQREqVSF6UwcbPyDSNJS

**Comment by kd0aij** [comment]
last 10 minutes of gyro signals and Q estimator RPY values after several hours on the bench:
qestimator

**Comment by LorenzMeier** [comment]
So you feel this is good to go, correct?

**Comment by kd0aij** [comment]
INAV and Q estimator are running on FMUv1 with about 34K of RAM free, but ALTCTL performance is poor. POSCTL looks good though, and I don't think we can blame the poor altctl performance on lack of RAM. Attitude control looks fine also.

I have some unanswered questions above, but they're not specific to this PR.

**Comment by sjwilks** [comment]
@Andreas during our tuning tests or your flights afterwards with your
250/FMUv1 did you notice ALTCTL issues?

I'd like to get out and fly again and will fly this combo on the F330 on
Monday hopefully either before or after it gets merged.

**Comment by kd0aij** [comment]
today's weather :(
aamwebcam

**Comment by AndreasAntener** [comment]
Last week I tried ALTCTL but only quickly. It worked, I'm not sure what @kd0aij is referring to with "poor performance".

@LorenzMeier all flights I sent you the logs from in the "param save flip issue" were done with the Q estimator.

**Comment by kd0aij** [comment]
@AndreasAntener could you send me a link to one of your logs with good altctl? I'd like to compare my parameter values to yours.

**Comment by AndreasAntener** [comment]
http://dash.oznet.ch/view/jHgqeWCN3VbcDXSjjjjLk5
This is the only ALTCTL test I did so far, it was hovering nicely in calm conditions.

**Comment by kd0aij** [comment]
@AndreasAntener Thanks, my parameters were mostly the same as yours... But I found INAV_ENABLE=0 when I thought it was 1. Not sure if I'm just stupid, or whether there's some kind of bug that causes parameters to change unexpectedly.
Anyway, ALTCTL with my FMUv1/QAV250 is behaving as before now with INAV; around +/-3m when flying around slowly.

I'd say this is ready to merge.

**Comment by AndreasAntener** [comment]
Another flight form today:
http://dash.oznet.ch/view/eahY7CayVDJFpyUoQMZRhC

@kd0aij I flashed release_v1.0.0 brnach today after the flight above, but I'm missing the logfile of it. Do you have any issues with logs now on FMUv1? (I also flashed a Pixhawk with the release branch and have logs..)

**Comment by kd0aij** [comment]
I got a log from my last flight (no GPS) on FMUv1 using this branch: https://github.com/kd0aij/Firmware/tree/fmuv1_inav_q_v100
which is v1.0.0 plus the INAV/Q estimator default config. Haven't noticed any missing logs so far.

**Comment by LorenzMeier** [comment]
@AndreasAntener Could you fly the release_v1.0.0 branch again and share a log? I still don't know why you have this param save issue.

**Comment by AndreasAntener** [comment]
@LorenzMeier Yep, me neither ;) and the fact that I couldn't reproduce it on the bench so far doesn't help.. Simon and I have flown v1.0.0 (with Q estimator) on Sunday on my qav250 and his f330 without in-air tuning and without issues. More flights are coming up this week, will try in-air tuning again then and post a log.

**Comment by AndreasAntener** [comment]
@LorenzMeier 
Flight from yesterday: http://dash.oznet.ch/view/9HdnsX8Q8nM5UNvmwUhxJZ
But with the code from Sunday (https://github.com/PX4/Firmware/commits/073f10fe4f119c115a503d62a596f0f89183ce8b), can't compile release_v1.0.0 ATM

I tried parameter tuning via RC knob, but I'm not sure if it worked in-air (it's working while not armed on the bench). I mapped yawrate_p and changed the value from 0.25 to 0.35 but didn't notice a difference in flight. Will do another test.

**Comment by AndreasAntener** [comment]
Logs with release_v1.0.0 from today, tuning pitchrate_p with knob:
http://dash.oznet.ch/view/8EyK5F82RydL6KQzKuWuQL

Knob-tuning worked, could switch from sloppy to overreacting pitch control :+1:

**Comment by AndreasAntener** [comment]
If it's of interest, I also tried the knobs with pitch/roll FF:
http://dash.oznet.ch/view/JY6v3oUHZADpxgiNdtAB4W

The knob scale was a little high, it oscillated as soon as I touched it ;)

**Comment by kd0aij** [comment]
you really maxed out the motor signals with that FF induced oscillation.
Was it still stable?

**Comment by AndreasAntener** [comment]
yeah.. well it stayed in the air and gave me the one second I needed to turn the knob back

**Comment by AndreasAntener** [comment]
https://www.youtube.com/watch?v=8v-lobkcSjM
Yaw went out of control too during pitch oscillations.

**Comment by kd0aij** [comment]
saw that; assume the mixer is prioritizing roll/pitch

**Comment by kd0aij** [comment]
do you find the RC parameter setup to be a bit more complicated than necessary?
Why are there 4 or 5 degrees of freedom to be assigned for a knob?
I've been working on a change to use only the min/max settings; seems less error prone and safer.

**Comment by AndreasAntener** [comment]
> saw that; assume the mixer is prioritizing roll/pitch

We're actually suspecting this too to happen when you just go full throttle now.. Our F330 that never had any throttle - mag coupling suddenly starts to yaw now on full throttle.

>  I've been working on a change to use only the min/max settings; seems less error prone and safer.

Awesome! I'm thinking exactly the same. Max/min should be the only thing necessary for this.

**Comment by kd0aij** [comment]
now all I have to do is remember what branch that was :(

**Comment by LorenzMeier** [comment]
The throttle behavior is actually correct. But we need to change the mapping of things.

**Comment by kd0aij** [comment]
@AndreasAntener branch https://github.com/kd0aij/Firmware/tree/rcParams
has the change to use only min/max. Next thing we need is QGC widgets for typical use cases, such as MC roll/pitchrate P and D. Since the Taranis has 4 pots...

**Comment by AndreasAntener** [comment]
cool, I can give that a try next week if you want

**Comment by kd0aij** [comment]
It's a minimal change just to make it easier to use in QGC till I get a chance to try out custom qml widgets.

**Pull request merged**
