### PR TITLE
WIP: fix sign of roll in Caipiroshka VTOL elevons mixer

### PR DESCRIPTION
**Pull request by kd0aij**
@tumbili This fixes the elevon deflections for my Caipiroshka-like tailsitter.
@pkocmoud This will probably solve your problem with incorrect yaw response.

An identical custom mixer file on SDcard in /etc/mixers is loaded without errors on boot, but channel 6 never outputs a PWM signal in that case. If anyone can reproduce that behavior, I'll file an issue on it.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@kd0aij Why are you not just inverting the PWM channels for both of your servos?

**Comment by kd0aij** [comment]
because it doesn't fix the problem with the mixer

**Comment by LorenzMeier** [comment]
It still seems to be the incorrect fix. If the servos are connected correctly the only variable for a valid setup would be inverting the direction of the outputs.

**Comment by kd0aij** [comment]
Why do you say it's preferable to change two servo reversing parameters in addition to modifying the mixer, when the mixer must be modified anyway to change scales and offsets?

**Comment by kd0aij** [comment]
I also wonder why @pkocmoud was unable to get his airframe set up properly. Perhaps he didn't try the servo reversing parameters?

**Comment by kd0aij** [comment]
Discovered that changing the output limits on channel 6 is what breaks the mixer. Strange that it doesn't also break channel 5.

**Comment by LorenzMeier** [comment]
@kd0aij This will break existing setups with the Caipi as described on the build log on our website - I still don't understand why we would need the changes here for the default setup.

I understand you want different scalings (I'd suggest to use the servo horns for simplicity). I also understand @pkocmoud had issues, but it sounds like these would be solved by PWM reverse.

I have the gut feeling that switching the servo outputs (5 and 6 with left and right) with PWM reverse is what you might be needing.

**Comment by kd0aij** [comment]
the main reason for the PR is so that Phil can try the mixer mod that is known to work (and to investigate the breakage of my configuration). I'm pretty sure he's been unsuccessful so far with PWM reversing and cable swapping. But swapping the servo outputs would mean at least that the comments in the mixer file are misleading.
If fixing the throws mechanically was practical, I would have done that. And that wouldn't fix the mixer bug anyway.

**Comment by tumbili** [comment]
@kd0aij @LorenzMeier Let me try this PR on my caipi in the lab. If you are not able to get the correct behaviour even when reversing the pwm outputs then something must be wrong. I'm pretty sure I had master on my caipi but I'm going to re-check and merge this if it works.

**Comment by kd0aij** [comment]
@tumbili My Stryker VTOL is hovering again (after stripping 2 sets of servo gears) with the mixer as modified in the above commit. I have not tried swapping the elevon servo cables because it requires too much disassembly of the aircraft.

Unfortunately, at a flying weight of 615g (optimal for the Stryker airframe) there is nowhere near enough pitch authority to reliably maintain hover in MC mode. I expect that if I add enough weight to compensate for that, it will not fly efficiently in FW mode. Perhaps there is some other way to compensate; the "tailsitter recovery" mechanism would not be practical for vertical takeoff and landing.

**Comment by tumbili** [comment]
@kd0aij I tried to hover outdoors with the caipi using the standard elevons. It started well but it lost pitch authority after a small wind gust came. I will now try the recovery mode on the Caipi. Until now I have only tried it on a bigger airframe (1.3 - 1.5 kg). Probably I will also need bigger elevons.

**Comment by LorenzMeier** [comment]
@kd0aij @tumbili Please conclude testing so we can close this. We have testers lined up that we want to support.

**Comment by kd0aij** [comment]
@tumbili My VTOL config flies with the change I proposed in commit 3bf0b0a, but since I need a custom mixer, the version in master won't matter to me for another year or so :)
The apparent bug here: https://github.com/PX4/Firmware/issues/3886 is of more concern to me.

**Pull request closed without merging**
