### PR TITLE
[WIP]: per sensor instance user configurable priority (replaces uORB priority)

### LINKED ISSUE #14948: per sensor configurable priority
- add configurable priority per sensor instance
 - auto set priorities based on startup ordering + potential preferences (external mags, etc)
 - considering dropping entire ORB priority mechanism

### PR DESCRIPTION
**Pull request by dagar**
This pull request introduces a configurable priority parameter per sensor instance. It replaces both the existing `CAL_{ACC,GYRO,MAG}x_EN` parameters and the uORB priority mechanism. 

 - new priority parameters `CAL_ACCx_PRIO`, `CAL_GYROx_PRIO`, `CAL_MAGx_PRIO`
``` C
 * @value 0   Disabled
 * @value 1   Min
 * @value 25  Very Low
 * @value 50  Low
 * @value 75  Default
 * @value 100 High
 * @value 125 Very High
 * @value 255 Max
```
 - CAL_ACC_PRIME, CAL_GYRO_PRIME, CAL_MAG_PRIME deleted (these have occasionally caused confusion)
  - TODO: special cases like external mags can be set to a higher priority by default, otherwise initial sensor priority is startup order
  - TODO: add baro cal for priority configuration
  - TODO: migrate CAL_ACCx_EN/CAL_GYROx_EN/CAL_MAGx_EN
  - closes #14948

I'll come back to this post v1.11 release.

### CODE REVIEW

**Comment by dagar** [comment]
@julianoes, @bkueng, @RomanBapst - No rush, but I'd like to get your feedback on this idea before I go further.

**Comment by dagar** [comment]
We could also consider configuring the order more explicitly rather than a somewhat vague priority.

**Comment by RomanBapst** [comment]
@dagar Thanks for the quick follow up. This is exactly what I imagined. Let's continue after the release then.

**Comment by dagar** [comment]
> We could also consider configuring the order more explicitly rather than a somewhat vague priority.

This might be more awkward dealing with conflicts or gaps. I'll stick with the priority levels.

**Comment by dagar** [comment]
This has been rolled into https://github.com/PX4/Firmware/pull/15235 because it was already addressing some of the missing pieces.

**Pull request closed without merging**
