### PR TITLE
Jenkins add tailsitter CI mission

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
It was stuck in transition. https://logs.px4.io/plot_app?log=1ebebb00-aeae-4522-8af8-09d6f5822a59

**Comment by lamping7** [comment]
@RomanBapst Can you look at the log posted above?

Same mission w/ standard_vtol -- https://logs.px4.io/plot_app?log=7ec07d8d-b1e8-4c77-9c5b-ef660c94d6bf
mission file -- https://github.com/PX4/Firmware/blob/master/integrationtests/python_src/px4_it/mavros/missions/vtol_new_1.plan

**Comment by RomanBapst** [comment]
@lamping7 Should be fixed in my latest PR https://github.com/PX4/Firmware/pull/9330

**Comment by RomanBapst** [comment]
Closing in favor of #9307

**Pull request closed without merging**
