### PR TITLE
New params for QuadRanger

### PR DESCRIPTION
**Pull request by sanderux**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looking good! You should generally assign such a PR to someone to merge, e.g. Ada or me.

**Comment by LorenzMeier** [comment]
Applied to master.

**Comment by sanderux** [comment]
Didnt want to bother you guys with such a small change

**Comment by LorenzMeier** [comment]
What bothers me is having lots of PRs open, and small ones like this one are fast and fun!

**Pull request closed without merging**
