### PR TITLE
uORB pub/sub graph

### LINKED ISSUE #6189: Crawl PX4 codebase and generate pub/sub graph
@CarloWood Would you be interested in helping us out with a Python script (there are a few like the px_generate_params.py and px_generate_airframes.py) that:

  - Parses the complete src directory
  - Identifies modules by their CMakeLists.txt file (see px_generate_params.py for an example)
  - Looks for calls to `orb_advertise()`, `orb_advertise_multi()`, `orb_publish_auto()` and the topic names
  - Looks for calls to `orb_subscribe()`, `orb_subscribe_multi()`
  - Draws a graph that links publishers and subscribers
  - Bonus: Checks a specific config. We can start with SITL configs where all apps that are started are in one file

This would be extremely helpful as it would show developers how the system relates. Eventually I'd like to grow this into a website that links to Doxygen for each module.

### PR DESCRIPTION
**Pull request by bkueng**
This adds a python script to extract uORB pub/sub information from the source tree and create 2 possible graph outputs: JSON for D3.js or Graphviz.

See it in action: https://logs.px4.io/plot_app/static/graphs_selectable/index.html

Fixes #6189 (See also https://github.com/PX4/Firmware/issues/6189#issuecomment-347507465)

I added the D3.js html file, but it does not need to live in this repo. To test it, create the graph with:
```
./Tools/uorb_graph/create.py -e src/examples -f Tools/uorb_graph/graph_full
```
Then open the html file and select the full graph.

TODO:
- generate from a cmake config target: required is only the list of modules. @dagar any good idea, so that we don't do that on every (local) build?
- handle Subscription & Publication classes (I planned to refactor those first, so this can wait)
- integration into the dev-guide. @hamishwillee I could need your help with that. It's 2 static files: a html and one or more JSON files with the graph (due to same-origin policy, the JSON file needs to come from the same server).
- CI and automatic updates based on master

### CODE REVIEW

**Comment by jlecoeur** [comment]
This is super cool!

I have a few cosmetic comments:
- can you prevent items from overlapping?
- can you add a legend ? I did not realize immediately that there were modules in grey and topics in color, and subscribe/publish in dashed/solid lines
- possibly make topics look different from module. For example modules get slightly taller square boxes while topics get thin boxes with rounded corners
- add tiny arrows from publisher to subscriber for extra clarity

**Comment by dagar** [comment]
> @dagar any good idea, so that we don't do that on every (local) build?

Not immediately, but we could consider unifying the per module metadata culling. Identifying all the params, publications, subscriptions used per module would really help identify the cruft.

**Comment by hamishwillee** [comment]
If hover over something it shows me the network for that module. BUT if I filter on logger (say) and then hover over it I don't get the network. Would be good if we could make the filtered items reappear (just) when hovering.

**Comment by bkueng** [comment]
Thanks for your feedback.

> can you prevent items from overlapping?

I already tried different things, and so far this is the best that I got. It uses anti-collision forces to avoid overlapping, but in areas with many nodes it's still possible that they overlap. I planned to take another look at it when integrating to the dev-guide (since other things might change as well, such as the plot size). Meanwhile feel free to play around with it - the force parameters can be adjusted in https://github.com/PX4/Firmware/pull/8393/files#diff-317a01bc575611cdfa242b1536ac3dbaR85 (and the following lines) and https://github.com/PX4/Firmware/pull/8393/files#diff-317a01bc575611cdfa242b1536ac3dbaR262

>  can you add a legend ?

Definitely. The graph needs some explanations, I also planned to do that when adding to the dev-guide.

>  possibly make topics look different from module. For example modules  get slightly taller square boxes while topics get thin boxes with  rounded corners

Yep I'll look into that.

> add tiny arrows from publisher to subscriber for extra clarity

Would be nice, but this one is going to be difficult, because the lines end at the center of the box.

> If hover over something it shows me the network for that module. BUT if I filter on logger (say) and then hover over it I don't get the network. Would be good if we could make the filtered items reappear (just) when hovering.

Do you mean showing the network when hovering, but only when hovering over a search result match? Or do you mean showing just a single node or the network when hovering and in filter mode independent whether the node under the mouse matches? The current behavior is such that you can search and scroll the graph, and only see on the results without distraction. Clicking anywhere on the graph will give you back the full graph.

**Comment by hamishwillee** [comment]
>> can you add a legend ?

>Definitely. The graph needs some explanations, I also planned to do that when adding to the dev-guide.

Adding to the devguide may require some thought because available space is constrained. We should try this.

>> If hover over something it shows me the network for that module. BUT if I filter on logger (say) and then hover over it I don't get the network. Would be good if we could make the filtered items reappear (just) when hovering.

> Do you mean showing the network when hovering, but only when hovering over a search result match? 

I mean that when I hover over something in an unfiltered view I see it's connections and everything else is hidden. I'd like to see that same view (when hovering) when I hover over an item in a filtered view. i.e. including the things that were filtered out. 

Basically I filter to be able to find a module, but I still then want to see its connections, whether or not they would be filtered out. Does that make sense?

**Comment by bkueng** [comment]
> Basically I filter to be able to find a module, but I still then want to see its connections, whether or not they would be filtered out. Does that make sense?

Yes, and I updated accordingly.

I tested adding it to the dev-guide and it somewhat works: https://bkueng.gitbooks.io/px4-devguide/content/en/middleware/uorb_graph.html (however I need to reload the page twice before the graph is visible. I think it's because the `<script>` tag for d3 should be in the `<head>`, not in the `<body>`). Also the size is a bit of a hack: I made it wider than the usual site content is.

I also updated the forces, so that there are less overlapping nodes, and the modules have now rounded corners.

@dagar I added a cmake target, so all the graph files can be created with:
```
./Tools/uorb_graph/create_from_startupscript.sh
./Tools/uorb_graph/create.py --src-path src --exclude-path src/examples --file Tools/uorb_graph/graph_full
make px4fmu-v2_default uorb_graph
make px4fmu-v4_default uorb_graph
make posix_sitl_default uorb_graph
```

**Comment by dagar** [comment]
Should we get this automatically running and posting to the gitbook?

**Comment by hamishwillee** [comment]
Still lots of fun. One issue is that if you hover over something and the connections are offscreen, there is no way to navigate to them and find out what they are.
Not sure how you would fix that - maybe some sort of "latch", or have items reposition closer if you hover for a little while.

How did you hack the page width? Globally or for the page? I might consider not doing this - instead add a note telling them to collapse the left sidebar.

**Comment by bkueng** [comment]
> Should we get this automatically running and posting to the gitbook?

Yes once we have a working solution.

> How did you hack the page width? Globally or for the page? I might consider not doing this - instead add a note telling them to collapse the left sidebar.

Here's the diff: https://github.com/bkueng/Devguide/commit/d95d46cd60bf9579ef317f5aacc1e0af0b2f1a53. I did not change the page width, I just let the image overflow and center it. I'd like to keep it fixed size with an aspect ratio of 1. Everything else will make things much more complicated.
I did not know that you can collapse the sidebar. Can we do that programmatically per page?
Dragging the whole graph should also be possible.

**Comment by hamishwillee** [comment]
Thanks. I doubt page collapsing can be done programmatically - or rather not without writing a plugin. What you've done looks good. 

> Dragging the whole graph should also be possible.

Yes. The problem is that once you move mouse to drag your page, you're no longer hovering over your object of interest.

**Comment by bkueng** [comment]
I fixed the graph loading and added some description: https://bkueng.gitbooks.io/px4-devguide/content/en/middleware/uorb_graph.html

I was also thinking of adding a checkbox to hide the two most heavy modules, which are mavlink and commander. Thoughts?

**Comment by dagar** [comment]
> I was also thinking of adding a checkbox to hide the two most heavy modules, which are mavlink and commander. Thoughts?

Yes that sounds good, although I was actually hoping for checkboxes for all modules. That wait I could isolate a certain subset for any explanatory (or exploratory) purpose.

**Comment by hamishwillee** [comment]
Nice. Thanks for making the hover over a filtered topic show all the connections :-)

Just a thought - it might be good to push most of the description to the bottom of the page - as people will only read it once. So something like 
```
This page provides a uORB publication/subscription graph that shows the communication between modules. It is based on information that is extracted directly from the source code. Usage instructions are provided below [LINKED].
## Module Graph
<MODULE IMAGE>
## Graph Properties
The graph has the following properties:
* Each topic has its own color 
...
```

---
Here is some slightly modified text you may wish to use for the descriptions ...

* Modules are displayed as gray boxes with rounded corners while topics are displayed as coloured rectangular boxes.
* Associated modules are topics are connected by lines.  Dashed lines indicate that the module subscribes to the topic, while solid lines indicate that the module publishes the topic.
* Some modules and topics are excluded:
  * Topics that are subscribed/published by many modules: `parameter_update`, `mavlink_log` and `log_message`. 
  * The set of logged topics, and topics that have no subscriber or no publisher.
  * Modules in **src/examples**.
* Hovering over a module/topic highlights all its connections.
* Double-clicking on a topic opens its message definition.
* Make sure your browser window is wide enough to display the full graph (the sidebar menu can be hidden with the icon in the top-left corner). You can also zoom the image.
* The *Preset* selection list allows you to refine the list of modules that are shown.
* The *Search* box can be used to find particular modules/topics (topics that are not selected by the search are greyed-out).

----
I can explain the above if needed.

**Comment by bkueng** [comment]
Thanks @hamishwillee. I was counting on you to come up with some better text :)
https://bkueng.gitbooks.io/px4-devguide/content/en/middleware/uorb_graph.html

> although I was actually hoping for checkboxes for all modules. That wait I could isolate a certain subset for any explanatory (or exploratory) purpose.

That's almost a bit too much I think. And then you would also need to have perma-links, right?

**Comment by hamishwillee** [comment]
Very nice. Even though there may be other things people want, I vote we push this live and iterate on the released version.

**Comment by dagar** [comment]
Yes, currently we generate metadata in every build (https://github.com/PX4/Firmware/blob/master/Jenkinsfile#L291), but then have a separate job (http://ci.px4.io:8080/job/PX4/job/Devguide/) that runs nightly to update the Devguide with the latest.

Eventually this will probably all migrate to the pipeline we get a handle on the new system.

For uorb_graphs should we only bother running it in master?

**Comment by bkueng** [comment]
Ok, I'm merging this. @dagar can you add the necessary CI things? It would be good to run at least something like `./Tools/uorb_graph/create.py --src-path src` on a PR, as it has some checks. For example if a new special case needs to be added, it will output:
```
Traceback (most recent call last):
  File "./Tools/uorb_graph/create.py", line 616, in <module>
    graph.build(args.src_path, args.exclude_path, use_topic_pubsub_union=args.use_topic_union)
  File "./Tools/uorb_graph/create.py", line 285, in build
    self._build_recursive(path)
  File "./Tools/uorb_graph/create.py", line 338, in _build_recursive
    self._build_recursive(file_name)
  File "./Tools/uorb_graph/create.py", line 338, in _build_recursive
    self._build_recursive(file_name)
  File "./Tools/uorb_graph/create.py", line 350, in _build_recursive
    self._process_source_file(file_name)
  File "./Tools/uorb_graph/create.py", line 415, in _process_source_file
    self._orb_id_vehicle_attitude_controls_topic)
  File "./Tools/uorb_graph/create.py", line 130, in extract
    +file_name+' ('+module+'). You need to add another special case.')
Exception: Subscription w/o ORB_ID(): _controls_topics[i] in src/drivers/snapdragon_pwm_out/snapdragon_pwm_out.cpp (snapdragon_pwm_out). You need to add another special case.
```

**Pull request merged**
