### PR TITLE
px4airframes split mixed windows path with os.path.split

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
fixes #2997

**Comment by dagar** [comment]
Sigh, there are still more path problems.

**Comment by dagar** [comment]
Alright I think it's working now (QGroundControl will connect), but given the number of problems I think we should thoroughly test the firmware binary built on windows.

**Comment by LorenzMeier** [comment]
Awesome, thanks!

**Pull request merged**
