### PR TITLE
AeroFC: Add support to microSD card and CAN

### PR DESCRIPTION
**Pull request by zehortigoza**
Users of Intel Aero RTF can build custom boards exporting some pins that is not exported in Aero RTF.
So this PR enables SD card and CAN support to those users.
This changes depends in FPGA changes(https://github.com/intel-aero/intel-aero-fpga/pull/10)

### CODE REVIEW

**Comment by TSC21** [comment]
This is awesome! @zehortigoza do you have any source for those type of board expansions? Or at least how to make those extensions?

**Comment by lucasdemarchi** [comment]
A custom board can be made by looking at the pinout for the 80-pin IO Expansion connector. It is documented here: https://www.intel.com/content/dam/support/us/en/documents/boardsandkits/aero/intel-aero-compute-board-guide.pdf  (section 3.7).

The changes here should be backward compatible and compatible with any board that use that pinout, but there isn't one in the market that I know of.

**Comment by TSC21** [comment]
Thanks for the feedback Lucas

**Comment by LorenzMeier** [comment]
@zehortigoza Is the FPGA image ready to go in - can I merge timing-wise?

**Comment by zehortigoza** [comment]
> @zehortigoza Is the FPGA image ready to go in - can I merge timing-wise?

We can release a new Aero image with the new FPGA firmware when PX4 1.7 was released until then I can push the new FPGA firmware binary to https://github.com/intel-aero/meta-intel-aero repository, that is enough for now?

**Comment by zehortigoza** [comment]
Closing it, I send a new version soon.

**Pull request closed without merging**
