### PR TITLE
VTOL descend as FW to RTL altitude before back transition

### PR DESCRIPTION
**Pull request by sanderux**
ref: https://github.com/PX4/Firmware/issues/8906
image

### CODE REVIEW

**Comment by sanderux** [comment]
... when performing an RTL

Other then that it looks good

**Comment by dagar** [comment]
I'm not sure if I'm following the logic and intent here. Can't we just move RTL_STATE_TRANSITION_TO_MC to after RTL_STATE_DESCEND?

Isn't a back transition at lower altitude potentially unsafe?

**Comment by dagar** [comment]
If anything wouldn't we want the back transition to happen slightly sooner along the return path? The majority of the return happening at the desired altitude, then as late as possible descend to the lower altitude and back transition such that it finishes over home.

**Comment by sanderux** [comment]
The RTL_STATE_DESCEND descends to the loiter altitude which is generally much lower then the RTL altitude. It could be dangerous to descend as FW to that altitude.

Regarding the approach/descend  on the trajectory that would be interesting but it is making several assumptions about the terrain, i think this is the safest way

**Comment by dagar** [comment]
Sorry, that was a bit vague. What I was really trying to get at is not duplicating the DESCEND state if necessary (eg changing only the altitude). 

Looking at this again wouldn't a LOITER_TO_ALT in the RETURN instead of a WAYPOINT accomplish the same thing? 

The other nitpick is calling the state RTL_STATE_DESCEND_FW. The state itself does nothing specific to MC, FW, or VTOL. Naming based on what it actually does makes it easier to follow. It also helps if the states are ordered as used.

CLIMB -> RETURN -> DESCEND_FW (DESCEND_RETURN?) -> TRANSITION_TO_MC -> DESCEND -> LOITER -> LAND -> LANDED

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/issues/10185

**Comment by sanderux** [comment]
closed in favor of #10404

**Pull request closed without merging**
