### PR TITLE
Improve land detector

### PR DESCRIPTION
**Pull request by julianoes**
I had a read through the land detector on the train and made some fixes. The most important one is probably switching to local position from global position in order to support indoor flying.

Tested in SITL multirotor.

@tumbili please review

### CODE REVIEW

**Comment by tumbili** [comment]
@julianoes I just noticed that the landing detector is not working indoors (not this PR).

**Comment by LorenzMeier** [comment]
@julianoes Please fix Travis.

@tumbili Please review and test where possible.

**Comment by tumbili** [comment]
@julianoes @LorenzMeier Giving this a test as well.

**Comment by tumbili** [comment]
@julianoes Tested this outdoors and it worked well. Giving it an indoor test and reviewing the code.

**Comment by julianoes** [comment]
@tumbili thanks!

**Comment by tubeme** [comment]
Is the land detector working in all modes so I could land in all modes?

**Comment by LorenzMeier** [comment]
Its always active.

**Comment by LorenzMeier** [comment]
@tumbili Did you end up testing it indoors?

**Comment by tumbili** [comment]
Tested indoors, log shows that it works fine. Merged.

**Comment by tumbili** [comment]
http://logs.uaventure.com/view/8jvu8dxHmqVXfRqCQDAG9g

**Pull request closed without merging**
