### PR TITLE
implemented new mixer strategy

### PR DESCRIPTION
**Pull request by tumbili**
This is a new mixer strategy which allows thrust increase/decrease if actuators saturate.
Tested outdoors with IRIS but did not get it to saturate yet.
Hand-held test seemed to be good.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@Zefz This is the "proper" fix for preventing the flip you were experiencing. We're changing short-term the throttle setpoint to prevent an impending flip.

**Comment by Zefz** [comment]
Great work! Is this ready for flight testing?

**Comment by tumbili** [comment]
@Zefz Yes it is ready. I already tested this with the IRIS yesterday but I can't get it to saturate for a long time.
If you are interested you could also play around with these factors
https://github.com/PX4/Firmware/blob/mixer_new/src/modules/systemlib/mixer/mixer_multirotor.cpp#L223

**Comment by Zefz** [comment]
Do I run this parallel with the rate limits from #1928? (or will the rate limits prevent this symptom).

**Comment by LorenzMeier** [comment]
@Zefz In parallel. The rate limits will prevent that the rate controller commands excessive rates, this will prevent flips. Although somewhat related, they cover different corner cases (this here prevents a flip at low throttle, the rate limiter prevents flips on badly tuned systems and on systems with high latency for motor spool-up time).

**Comment by Zefz** [comment]
I've flight-tested this today with an Iris, but it did not go very well (powerful oscillations in roll and pitch at full input). I am unsure if it was caused by bad PID tuning, so I will retry again after resetting the configuration to default Iris settings. I can't fly tomorrow, but I will try to look into it the day after tommorow.

http://dash.oznet.ch/view/Pi7TJjnF4jWe7MzmFTA3An

**Comment by Zefz** [comment]
There is also something weird happening in the X Y position of the log i posted. (GPS glitch?)

The copter did definitely not fly into those trees which it indicates :) It should have been near the container to the left the whole time.

**Comment by tumbili** [comment]
@Zefz Here is the log of my flight http://dash.oznet.ch/view/5ZdwQo8YkRZ2b3nnAoUHCC
My tuning is also not perfect, the controller is a bit too aggressive you can see that the rates tend to overshoot. But I think it tracks quite well.

**Comment by Zefz** [comment]
Yes that is very different from mine :) I see your PID tuning is different from mine. I assume you use the default configuration for Iris drones, so I'll try my next flight test with that one as well.

**Comment by Zefz** [comment]
@tumbili Ok. Resetting the PID to Iris defaults worked.

Good news is that the quad does not flip anymore :+1: On the other hand the scaling seems a bit off and the quad often cannot recover (it loses altitude until it hits the ground).

Here is a log that shows the quad failing to recover:
http://dash.oznet.ch/view/JZWomjsPSFs2ELnZdZFX6L

In this log the quad does recover at the first attempt, but at the second attempt it fails:
http://dash.oznet.ch/view/x22hPKqnKnJJa6tpQ5W2gB

Disclaimer: We did a *very* intensive saturation test, but the effect was reproducible. The flight was done with a normal Iris with default PID values.

**Comment by tumbili** [comment]
@Zefz Thanks Johan for testing this! I will look into it today.

**Comment by LorenzMeier** [comment]
@Zefz Did you have the system on a line? I see throttle being 100% for much of the test, it should have gained altitude like crazy. Also the attitude tracking is absolutely horrible.

You have a phase delay of 180 degrees, its not stable in any fashion any more.

@tumbili Are you sure you're flying default Iris gains? Because the performance @Zefz gets when not at 100% throttle is still bad.

**Comment by Zefz** [comment]
@LorenzMeier No, it was not on a line. I agree the attitude tracking is really bad.

Note that the flight test was done in MANUAL mode (not with PosHold or AltHold).

**Comment by tumbili** [comment]
@LorenzMeier Probably I don't fly exactly the standard gains because we introduced the feed-forward. But @Zefz has my log file so he can see my gains.

**Comment by Zefz** [comment]
@tumbili Our PID gains are very similar. Only ```P_RATE_FF```, ```R_RATE_FF```, ```Y_RATE_FF``` were 0.05 instead of 0. I can try again to see if this makes a huge difference, but I doubt it will.

Perhaps the default Iris params need to be updated? (include the new feed-forward values at least)

**Comment by tumbili** [comment]
Just did a test flight with lots of additional weight on the IRIS. Hover thrust is at about 75%.
You notice that the copter looses height during heavy manoeuvres but I did not find it scary or anything. However, rate tracking performance is still amazingly well even if the actuators saturate.
I think I still can  go further up with weight. Unfortunately, two of the motors of my IRIS are subject to heavy vibrations at a certain motor speed :-(
It would also be interesting to test the other case when the vehicle is hovering at low thrust values.
This is even more convenient because gaining altitude is not as bad as loosing.
Log file is here http://dash.oznet.ch/view/nbbKrbWR9pGecMXKPqzggB

**Comment by Zefz** [comment]
@tumbili It is amazing how much better your rate tracking is, even when the motors are saturated.

I'll retry the new mixer using a new Iris+ drone, see if that makes any difference.

**Comment by Zefz** [comment]
Log from Iris+ test flight:
http://dash.oznet.ch/view/dDKdvNF3CqjwWijP2bthjm

Much more stable behaviour than the other Iris drone. Rate tracking seems better.

**Comment by LorenzMeier** [comment]
@Zefz do you have the FF terms enabled now? Your rate tracking is still not really good for all parts of the flight (it's pretty good for some) and you have large angular errors.
I think we're only done with this once we achieve decent tracking throughout the full flight.

**Comment by Zefz** [comment]
Yes I have exactly the same PID gains as @tumbili now (which include FF terms).

**Comment by LorenzMeier** [comment]
@sjwilks @AndreasAntener Could you test this on your endurance system, preferably with as little payload as possible? You will *directly* benefit here, because right now you're susceptible to motor saturation and resulting flips!

**Comment by Zefz** [comment]
After also pulling in the anti integrator windup from  https://github.com/PX4/Firmware/commit/b52d0ed8a245cc25ffdaf3214f9cf793fe2f1ba6 the attitude controller seems very stable with the new mixer. The Iris+ no longer seems to lose attitude control and crash. Great job @tumbili :+1:

**Comment by LorenzMeier** [comment]
The windup code is in master now - could you share the flight log?

**Comment by LorenzMeier** [comment]
@tumbili I failed with a rebase against master of this. Would be great if you could do a rebase monday so we're not drifting off too far.

**Comment by Zefz** [comment]
Seems I am having trouble uploading my logs to log cruncher. Are they too big? (~30 mb)

**Comment by sjwilks** [comment]
30mb isn't a problem. Any error message?

**Comment by Zefz** [comment]
No. It's just saying that it's working on it, but I never receive an e-mail (waited an hour now... 3 attempts)

**Comment by sjwilks** [comment]
OK, looks like the main plotting engine when down as well as the monitor.
Both are back up now and crunching. You should receive Emails soon if not
already.

**Comment by Zefz** [comment]
Yes got the logs now.

Here is a log where the system is working mostly fine, although it did almost flip at the end:
http://dash.oznet.ch/view/BfkVZBTWJkQXJ56JdEEdi7

This one is worse, same system and same test mechanics caused a double flip that barely recovered before hitting the ground!
http://dash.oznet.ch/view/ZwmN9NMeskty2RwZuedpZE

**Comment by Zefz** [comment]
Note: The actuator output from the previous two tests were a bit unbalanced due to an error in arm positions, which resulted in completely wrong propeller geometry.

**Comment by Zefz** [comment]
@LorenzMeier @tumbili  Is this PR a confirmed fix or do we need to do some more testing?

**Comment by LorenzMeier** [comment]
Need a test on a large quad which hovers at 30% throttle.

**Comment by LorenzMeier** [comment]
@SimonWilks @sjwilks @AndreasAntener Any chance to fly this soon on your big quad? We really need a low-throttle test before we can call this done, and you would be most likely subject to pretty bad corner cases if you don't upgrade to this mixer soon.

**Comment by sjwilks** [comment]
We've already been "around" those corner already ;) As soon as the weather
dries up after the weekend we will test it. It's our main dev quad at the
moment and we need to remove and shift gear around to do this, hence the
delay.

**Comment by SimonWilks** [comment]
@LorenzMeier @tumbili @Zefz we just did two flights with a mostly stripped down TBS long range. Flight 1 was manual first with a hover then throwing it around then continuing this in POSCTL with our own reduced settings (XY_VEL_P 0.06).

Flight 2 was then with a default XY_VEL_P of 0.1 which made it considerably more aggressive but it thankfully remained under control. Ignore the glitch in the second flight where it probably switched quickly in and out of RTL, we have a RC link issue.

Flight 1: http://dash.oznet.ch/view/bZeXMgtAgWtELLM2QCXqN9
Flight 2: http://dash.oznet.ch/view/6SGJ3LEHXN24aEZrVSzFkJ

**Comment by LorenzMeier** [comment]
@tumbili Could you please rebase and make sure to keep the mixer limit status register / feedback intact? It looks like this mixer is missing the update and you need manually re-insert / merge your changes there. A git rebase will show you the conflicts.

**Comment by LorenzMeier** [comment]
Please make sure to re-test after the rebase. @sjwilks Did you test this straight off this branch or merged with master?

**Comment by SimonWilks** [comment]
Straight off this branch.

**Comment by tumbili** [comment]
@LorenzMeier Rebased

**Comment by kd0aij** [comment]
flew this branch with 12" props on my 450 quad to run at reduced thrust setting.
Wasn't able to induce any instability with the following gyrations:
newmixer_out0
newmixer_rates

**Comment by kd0aij** [comment]
another test with the F450 and 12" props. Couldn't induce a flip, but lost yaw control at the end of this log after flying a slow circle: 17_10_46.px4log located here: https://copy.com/UaSWWU6I1xprNh4m

There's also something seriously wrong with the Pixhawk internal magnetometer. It's mounted in the same location as the FMUv1/IO was, but it shows strong influence from thrust variations. This might well have been a factor in the loss of yaw control. 

I performed the calibration yesterday using latest QGC and master.

**Comment by Zefz** [comment]
Test:
* Iris+ with Gimbal
* Strong wind
* PosHold with slight forward output

Drone lost attitude control and did not recover, losing altitude (and crashed after falling about 30 meters). Putting the system back into MANUAL mode did *not* help (could still not control the quadcopter).

Log:
http://dash.oznet.ch/view/xXJ9v734nvANsmhmVyrAX4

**Comment by tumbili** [comment]
@Zefz @LorenzMeier Johann, I'm starting to believe you have other issues. I just tried to look at your log with flight analyzer and the data is so sparse you cannot even make rhyme of what the drone does.
I just analysed my log with the IRIS today and everything seems to be very smooth. It would be very interesting to find out what causes this issue for you but with such logs I can't make any statements.

**Comment by Zefz** [comment]
Yes I agree. I have also noticed the sparse datapoints. I do not know what causes this yet.

**Comment by kd0aij** [comment]
Here's a plot with symbols on the data points. Looks like the loss of stability coincides with a long dropout:
crashdropouts

**Comment by tumbili** [comment]
@kd0aij Thanks Mark! This should become a feature of FlightPlot!

**Comment by Zefz** [comment]
Seems there is a full 100ms where no data points are logged?

**Comment by tumbili** [comment]
I don't even want to say that this is the reason why it crashed. But we can not perform any tests with a system that we don't know what it's doing. @LorenzMeier Do you have any suggestions how we can proceed? @Zefz Can you confirm that you are using master an nothing else? Do you have a second hardware to test on?

**Comment by Zefz** [comment]
Yes. I ran master and nothing else. Flashed from QGC using Developer Build (master). I'm trying the same on my second Iris now.

**Comment by Zefz** [comment]
@tumbili My other Iris is logging at correct rate. Trying to exchange SD cards to see if this is just a data output rate issue. But this does indicate that I'm having a hardware problem on my Iris+.

**Comment by Zefz** [comment]
I think the SD card was the culprit. Using the SD card from the Iris in the Iris+ seems to have solved the logging rate issue! (biggest gaps is now about 10 ms)

**Comment by kd0aij** [comment]
hopefully sdlog2 can't stall any flight-critical threads!

**Comment by tumbili** [comment]
@kd0aij I think this was an issue that the swiss fang team had a while ago. The sdlog2 had a too high priority and blocked some critical task when loading waypoints from the sd card. This resulted in a twitch or so of the air plane attitude. I think that since then sdlog2 has the lowest priority.

**Comment by tumbili** [comment]
thrust

**Comment by tumbili** [comment]
@LorenzMeier These are the results for the tests which Simon did which the discovery (rates up to 9 rad/sec)

**Comment by tumbili** [comment]
I could not really see the height or speed being influenced.

**Comment by tumbili** [comment]
screenshot from 2015-05-10 00 11 23

**Comment by tumbili** [comment]
That's what I call good tracking performance, I will put this on the wiki.

**Comment by LorenzMeier** [comment]
This looks all pretty good - time to mainline this and get it developer-level acceptance testing on master.

**Comment by LorenzMeier** [comment]
Applied via rebase, thanks!

**Pull request closed without merging**
