### PR TITLE
Jenkins ROS mission tests run ecl ekf analysis script

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
Weird failures. Possibly doesn't like the way the logs abruptly end?

image

**Comment by dagar** [comment]
@priseborough FYI

**Comment by dagar** [comment]
TODO: increase the size of each test mission.

**Comment by lamping7** [comment]
I just rebased this now that longer missions were made. I'll check back after CI runs it.

**Comment by dagar** [comment]
Nice! Once it's working reliably we should archive the output and later look into using the table results (csv) to possibly fail the CI test.

image

**Pull request merged**
