### PR TITLE
update ecl/EKF and change default integration period 4000 us -> 2500 us

### PR DESCRIPTION
**Pull request by dagar**
For testing PX4/ecl#795

### CODE REVIEW

**Comment by priseborough** [comment]
I will get some flight testing for this tomorrow (Wed) on an F7 board with logging from boot so we will have a replay log for diagnostics.

**Comment by dagar** [comment]
Thanks @priseborough. I've rebased this PR to current master and updated ecl to point to your current `pr-ekfCovarianceFix` branch.

**Comment by dagar** [comment]
> I also noticed that an accel cal was required after flashing this firmware.

I don't suppose you'd be able to find an older log from this same vehicle?

**Comment by priseborough** [comment]
> > I also noticed that an accel cal was required after flashing this firmware.
> 
> I don't suppose you'd be able to find an older log from this same vehicle?

Yes I can get that. Here is a log before https://review.px4.io/plot_app?log=0ad06c78-d768-41eb-b01a-380fae0b4e6c

What happened after the flash was that I had an accel inconsistency error preventing arming. I then performed an accel cal - here is the log taken during that procedure https://review.px4.io/plot_app?log=66daf97a-e6ac-4332-81be-172522bdd586

It shows that the second IMU X accel was inconsistent at the start. 

Screen Shot 2020-04-22 at 12 18 11 pm

After the cal there was a significant height offset caused by a bad Z value for both accelerometers, so the cal was not successful. and I had to repeat it.

**Comment by dagar** [comment]
> Yes I can get that. Here is a log before https://review.px4.io/plot_app?log=0ad06c78-d768-41eb-b01a-380fae0b4e6c

The first accel x axis offset was enormous in your old log. I'll take a quick look tomorrow to see if this can be explained by the change to the new driver.

Old Log
```
CAL_ACC0_ID, 3932170
CAL_ACC0_XOFF, 1.9338665008544922
CAL_ACC0_XSCALE, 0.9271079897880554
CAL_ACC0_YOFF, 0.03339226171374321
CAL_ACC0_YSCALE, 1.0035347938537598
CAL_ACC0_ZOFF, -0.012606620788574219
CAL_ACC0_ZSCALE, 0.974113941192627
```

New Log
```
CAL_ACC0_ID, 3932170
CAL_ACC0_XOFF, -0.08791636675596237
CAL_ACC0_XSCALE, 0.9931976795196533
CAL_ACC0_YOFF, 0.0453348234295845
CAL_ACC0_YSCALE, 1.0062685012817383
CAL_ACC0_ZOFF, -0.0562596321105957
CAL_ACC0_ZSCALE, 0.9857292771339417
```

**Comment by MaEtUgR** [comment]
> There was a change in POSCTRL flight behaviour compared to testing with earlier versions of master with larger pitch transients during accel decel.

What changed is there's acceleration feed-forward from the trajectory generation now applied directly to the vehicle attitude for better velocity tracking in the smoothed flights in which the generator runs and produces acceleration setpoints. I see you were flying the default multicopter configuration which uses bang bang jerk of 8 m/s^3 in manual flight (4 in mission).

> Flyaway recovery test with declination set to -90 deg

There's an unwanted glitch in rate setpoint probably because the attitude resets and the setpoint getting adjusted after the estimate.
image

**Pull request merged**
