### PR TITLE
batt_smbus rework

### PR DESCRIPTION
**Pull request by dakejahl**
Hi guys, another attempt at a face lift for this driver. I'd like to rename this to `bq40z50`, as this is the hardware this driver has been designed to interface with... we can talk about that :wink: My previous PR #10666 sets up the `SMBus` interface that other (future) smart battery drivers can use. I know the`battery_status` message is getting pretty abused, lets talk about what we can trim from it and what we'd like to keep. I'd also like to ask if anyone is using an ASIC other than the BQ40Z50? If so, lets get a driver made for that and try to keep device specific code in device specific files.

**Brief summary of changes:**
1. Remove `CDev`, use `ModuleBase` for structured set-up/tear-down.
2. Individual cell voltage measurements and imbalance detection to trigger emergency warning. 
3. Using `SMBus` interface class.
4.  Additional bus options.
5. Automatic enable/disable of under voltage protection while in flight to maximize pack capacity and avoid pack cutoff events near end up discharge due to voltage dip under high load. (This probably needs to be re-thought)

This is a WIP, so feel free to rip it apart. Thanks!

### CODE REVIEW

**Comment by dagar** [comment]
Check the CI output for minor clang-tidy complaints.

**Comment by dakejahl** [comment]
I know :( I'll sort it out tomorrow

**Comment by dakejahl** [comment]
Okay I am not sure about this next error... could you assist? @dagar

**Comment by dakejahl** [comment]
@bkueng Does this need to be in here? https://github.com/PX4/Firmware/blame/master/Tools/uorb_graph/create.py#L257

I am not using a variable to store the orb_id, rather I am doing this:
`orb_advertise(ORB_ID(battery_status), &new_report);`
Is this acceptable or should I make changes?

**Comment by bkueng** [comment]
@dakejahl you can just remove this line now: https://github.com/PX4/Firmware/blame/master/Tools/uorb_graph/create.py#L257.

**Comment by dakejahl** [comment]
Ready to merge once @AlexKlimaj has tested and verified correct functionality.

**Comment by dakejahl** [comment]
I found a bug... and it led me down the SMBus rabbit hole. Long story short, this will require a little bit more time as I sort out the nuances of the SBS protocol. I may try to add SMBus support to NuttX i2c, as the signaling between i2c and SMBus is different enough to cause errors on the BQ40Z50 side. These error states can be worked around in a hacky way (which I may end up doing for now) or we can fix the root problem (enabling SMBus mode on the STM32). https://github.com/PX4/NuttX/blob/999c4357a220d9ea271475e74abd5d8ba080be27/arch/arm/src/stm32/stm32f40xxx_i2c.c#L59

**Comment by AlexKlimaj** [comment]
@dagar Everything is working, verified, and tested.

**Comment by mhkabir** [comment]
@dagar Can we merge? This looks like a good step forward.

**Comment by dakejahl** [comment]
@dagar boop

**Pull request merged**
