### PR TITLE
Hamilton Quaternion Multiplication Order

### PR DESCRIPTION
**Pull request by MaEtUgR**
After merging https://github.com/PX4/Matrix/pull/34 I went through the entire Frimware source and was surprised to find out that there is **no non-commutative quaternion multiplication of two `matrix::Quaternion`s except for the ecl library**. I hope I'm not missing anything here but it seems to me that the library is mainly user for conversions Dcmf, Eulerf, Quatf. And the only test for this multiplication outside of the matrix library is one a quaternion with itself here: https://github.com/PX4/Firmware/blob/2b714e079b97976da1b6f633699f7b79f1c01389/src/systemcmds/tests/test_matrix.cpp#L216-L220

What I ended up switching are some calls that were simplified in the past but not applied to any instance in the modules.

@dagar Please quickly check the `.copyTo` call.

@priseborough Please add whenever you're finished and ready for testing your pending changes to the ecl from here https://github.com/PX4/ecl/tree/pr-ekfQuatMultOrder to this pr. I'm not sure what happens when you have a different commit checked out in your own matrix submodule than in the submodule I update here.

### CODE REVIEW

**Comment by jgoppert** [comment]
@priseborough Have you been able to test this on ekf2 yet?

**Comment by jgoppert** [comment]
I just updated this to master to do some flight testing with it.

**Comment by priseborough** [comment]
I have flight tested it with https://github.com/PX4/ecl/tree/pr-ekfQuatMultOrder and it works

**Comment by priseborough** [comment]
See https://github.com/PX4/ecl/pull/323

**Comment by MaEtUgR** [comment]
I rebased with successful auto-merge again foremost to run CI again on an up-to-date branch.

**Comment by MaEtUgR** [comment]
Apparently VTOL does a flyaway with these changes as luckily CI succeeds to show. I can reproduce this in SITL. Let me fix that.

**Comment by MaEtUgR** [comment]
I found a clue: When I update the ecl submodule as well like @priseborough wrote in https://github.com/PX4/Firmware/pull/7908#issuecomment-328684091 then everything works again.

I expected the two matrix submodules to be included without overlap such that either the ecl or the Firmware could use a different version of matrix and does not need to be synced at all time.
Then all the following combinations should work:
```
PX4                               ecl                                   MC                VTOL
old matrix                        old ecl/matrix                        works             works
new matrix + no needed changes    old ecl/matrix                        fails             fails
old matrix                        new ecl/matrix + needed ekf changes   fails             fails
new matrix + no needed changes    new ecl/matrix + needed ekf changes   works             works
```

This means as soon as the ecl library is compiled within the PX4 Firmware it doesn't matter anymore what matrix library is checked out in the ecl library itself because for every call to a matrix also in the ecl library the matrix submodule in PX4 Firmware gets used.
@priseborough @LorenzMeier  Is this by design/desired?

Anyways I'll update the submodule in this pr and I would kindly ask @priseborough to merge https://github.com/PX4/ecl/pull/323 soon such that the https://github.com/PX4/ecl/commit/dd5b8525c391bc4e21907f0074754b8f53c7d80a commit is in the ecl/master history.

**Comment by MaEtUgR** [comment]
Thanks @priseborough for promptly merging https://github.com/PX4/ecl/pull/323 such that I could checkout the merge commit https://github.com/PX4/ecl/commit/160e4d69c1bab6daebedbff2de3c4e08c438eefa (current ecl/master) here by interactive rebase.

I did SITL tests with MC and VTOL and now everything should be fine and ready to merge.
Anyone up for a review?

**Pull request merged**
