### PR TITLE
Add Input Capture capabilities to FMU (For Camera time stamping)

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier  and @tridge,

This PR add the (ioctl) hooks and test for Input Capture capabilities to FMU.

The original  pwm_servo driver and a new input_capture driver are layered on top of a new io_timer driver.

The io_timer driver manages the timer's channel resources in a sharing friendly way. It demuxes interrupts and provides layered callbacks.

Currently the fmu diver has been expanded to support the additional modes of:

Mode | Aux | 1 | 2 | 3 | 4 | 5 | 6
------- | ------|---|---|---|---|---|---
mode_pwm2||P|P|G|G|G|G|
mode_pwm3||P|P|P|G|G|G|
mode_pwm2cap2||P|P|C|C|G|G|
mode_pwm3cap1||P|P|P|C|G|G|

The test command will also display input statistics and capture data.

Some limitations:

Since a Capture input channel and a PWM output channel share the same timer time base. The maximum that a capture channel can be blocked by disabled ISR and not overflow is == the 1/ PWM output rate. Since the pwm runs at. 2.5 and 20 Ms. - This should not be a problem.

For this very reason, when using the PWM Input driver AUX 5 and 6 should be used. It will have a maximum capture range of 62.5MS

**NB** the pwm input driver should be started **AFTER** the FMU driver is started in a mode that leaves AUX 5 and 6 as G(pio)

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looking good from my perspective. I need 1-2 more days to complete the review as I'm currently travelling.

**Comment by LorenzMeier** [comment]
@sjwilks Could you verify the PWM input still works for you with a Lidar-Lite on this branch? I don't want to break the setup once this gets merged.

**Comment by SimonWilks** [comment]
Yep. Will be testing this afternoon.

**Comment by SimonWilks** [comment]
@LorenzMeier just bench tested this, looks good:

```
nsh> ll40ls test pwm
ll40ls: single read
ll40ls: measurement: 0.05 m
ll40ls: time:        33853741
ll40ls: periodic read 0
ll40ls: valid 1
ll40ls: measurement: 0.045 m
ll40ls: time:        33904102
ll40ls: periodic read 1
ll40ls: valid 1
ll40ls: measurement: 0.042 m
ll40ls: time:        33954423
ll40ls: periodic read 2
ll40ls: valid 1
ll40ls: measurement: 0.047 m
ll40ls: time:        34458837
ll40ls: periodic read 3
ll40ls: valid 1
ll40ls: measurement: 0.047 m
ll40ls: time:        34962031
ll40ls: periodic read 4
ll40ls: valid 1
ll40ls: measurement: 0.050 m
ll40ls: time:        35465730
ll40ls: PASS
```

**Comment by LorenzMeier** [comment]
Rebased and applied after further validation and cross-testing here.

**Pull request closed without merging**
