### PR TITLE
WIP: Standard vtol altitude controlled front transition

### PR DESCRIPTION
**Pull request by sanderux**
Using vertical velocity to control pitch angle during quadplane vtol transition.

- [x] Flight test
- [ ] Second flight test
- [ ] Parameterize
- [ ] Increment over delta time
- [ ] use correct delta time instead of fixed value
- [ ] how do we tell TECS to start at the integrated pitch value?

### CODE REVIEW

**Comment by sanderux** [comment]
@tumbili I created a PR to discuss
i added new gains that seem to work in both sitl and deltaquad, these were test flown and seem to work well.

**Comment by tumbili** [comment]
@sanderux Could you provide a log of the flight test you are going to do today?

**Comment by sanderux** [comment]
Tested, works.
selection_019


http://logs.uaventure.com/view/5MFXSfPmYwrUFxuCDnQj7T

**Comment by tumbili** [comment]
This is included in a PR coming soon, currently being tested

**Pull request closed without merging**
