### PR TITLE
Attitude filter for multirotors: Let users choose between filters, default to old one

### PR DESCRIPTION
**Pull request by AndreasAntener**
@LorenzMeier I didn't want to hijack your branch #2135, so here's a new one (also **untested**) with the default changed and the param docs updated.

When I read #2013 it sounds like there are still issues to be taken care of?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
The open issues had been addressed based on a comment from Anton. But I'm ok with defaulting to the old one - however, the performance of the new estimator is likely significantly better, due to the offset estimation, so we should try to test and move to it as fast as possible.

**Comment by LorenzMeier** [comment]
Let us know when you've tested the change.

**Comment by AndreasAntener** [comment]
Change is tested and working.

We just felt that with these kind of drastic changes it's probably good to give it a few more tests. Underlying is much broader discussion though about "stable" which is a topic we need to address very soon..

**Comment by LorenzMeier** [comment]
I'm not sure we need much discussion about stable, rather, a better process. I think the objectives about the stable branch are pretty clear, however, there are a series of testing / review fails in the last days I'm unhappy about, too. I've already taken measures at ETH to improve the situation, however, we probably need additional help, e.g. from you guys. Mostly in being very quick and consistent about regular testing, and some of it is pretty hard at ETH.

**Comment by AndreasAntener** [comment]
I agree, I also meant the process.

**Pull request merged**
