### PR TITLE
fixed error: reset yaw setpoint for acro mode

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by thomasgubler** [comment]
Can you explain how this affects acro? I see that you replace altitude by attitude. From my understanding that part of the if statement checks if we are in position control mode. (position control with the remote control). So after your change this check will not trigger anymore in pos control mode?

**Comment by tumbili** [comment]
I basically just tried to put the logic which was in the mc_att_controller before into one statement.
Before yaw_sp was reset when
1) system was not armed
2) system was is non-manual control mode
3) system is in acro mode which means attitude is not controlled (just rates) and system is in manual mode

Did I miss anything?

**Comment by tumbili** [comment]
But still I think there is something missing. Before the attitude controller was publishing the yaw setpoint which was used again by the position controller. Now the position controller does not get a yaw setpoint I think. So the yaw setpoint should also be generated for position control mode, isn't it?

**Comment by tumbili** [comment]
The PR for the offboard control was closed but I think it had a good point. I've seen that the mavlink receiver is also publishing attitude setpoint and the mc_pos_controller  handles offboard control somehow. So mc_pos_controller should not publish when in offboard control mode?

**Comment by thomasgubler** [comment]
> So mc_pos_controller should not publish when in offboard control mode?

No it should not

**Comment by tumbili** [comment]
So what excatly does it do when in offboard mode? What is this for then 
void
MulticopterPositionControl::control_offboard(float dt) ?

**Comment by thomasgubler** [comment]
ah it depends on the type of incoming message type of course.

What I meant: it should not publish attitude setpoints when someone is sending set attitude target mavlink messages. I guess this should happen automatically because in this case setpoint triple is not updated.

See also #1786

**Comment by tumbili** [comment]
Ok, that's correct. So I will have to fix the attitude setpoint publishing at the end of the main task of mc_pos_controller because now it will always publish.

**Comment by LorenzMeier** [comment]
@Zefz do you have / need this one as well?

**Comment by Zefz** [comment]
Yes this causes issues in other modes than acro

**Comment by tumbili** [comment]
Would be great if you could give some feedback on this. I know that it shouldn't publish attitude setpoint when in offboard mode. I tested MAN, ATTCTL and POSCTL but none of the rest.

**Comment by Zefz** [comment]
@tumbili Take a look at #1801 which resolves some issues in flying autonomous flight mode (including emergency fail-safe landing). You also mixed ```control_altitude_enabled``` with ```control_climb_rate_enabled``` (the former determines absolute altitude setpoints while the latter determines Z velocity)

**Comment by tumbili** [comment]
Could you say what exactly has failed before? Auto mode uses the same controller so if POSHOLD works then auto should also work?

**Comment by tumbili** [comment]
Ok, one thing I see is that the attitude setpoint was created manually for all modes which did not use velocity control. This means that some auto modes were affected.

**Comment by LorenzMeier** [comment]
Closing and choosing @Zefz solution.

**Pull request closed without merging**
