### PR TITLE
FrSky telemetry daemon supporting D16 or SmartPort on FMUv4

### PR DESCRIPTION
**Pull request by kd0aij**
tested with OpenTX 2.1 and FrSky X4R-SB and D4R-II receivers on PixRacer R12
5 virtual smartport sensor IDs currently implemented:
* VFAS reports vehicle_status.battery_voltage
* Current sensor reports vehicle_status.battery_current
* ALT reports raw.baro_alt_meter
* GSPD reports magnitude of global_pos.vel_n,e,d
* FUEL reports vehicle_status.battery_remaining

### CODE REVIEW

**Comment by kd0aij** [comment]
I don't understand why Travis is failing.

**Comment by dagar** [comment]
It failed here running cmake for px4fmu-v4
https://travis-ci.org/PX4/Firmware/jobs/104315343#L1604

    CMake Error at CMakeLists.txt:332 (add_subdirectory):
     add_subdirectory given source "src/drivers/sPort_telemetry" which is not an
     existing directory.

**Comment by kd0aij** [comment]
@dagar Thanks, I had forgotten to push my last commit.

**Comment by LorenzMeier** [comment]
Awesome!

**Comment by LorenzMeier** [comment]
Applied to master, thanks!

**Pull request closed without merging**
