### PR TITLE
Switch fixed wing to EKF2

### PR DESCRIPTION
**Pull request by LorenzMeier**
@dagar We have a couple dozen flights with EKF2 now in this state and think its good to go for fixed wing. I just need to squeeze it in here and need to look at existing code.

### CODE REVIEW

**Comment by dagar** [comment]
Has most of the work been confined within the ECL submodule or does it happen on both sides? I'm wondering if I could just switch the ECL submodule in stable for testing.

**Comment by LorenzMeier** [comment]
It happens on both sides, so you can't just switch the submodule. We're moving too fast in general for this approach to be really workable. Maybe once this is all in and stabilised.

**Comment by LorenzMeier** [comment]
I found a few blunders in the ROMFS (e.g. we were bundling a README file there). That should bring back 10-15K flash. Much more to win, we have 230K strings in there.

**Comment by LorenzMeier** [comment]
@dagar Now this builds. @CarlOlsson @tumbili Would be good if you join us with test flying it.

**Comment by jcooper21** [comment]
I flight tested EKF 2 yesterday and it seemed to work good on the current beta.

**Pull request merged**
