### PR TITLE
CI: update container tags to '2019-01-01'

### PR DESCRIPTION
**Pull request by TSC21**

### CODE REVIEW

**Comment by TSC21** [comment]
@dagar the raspi container failed to build (https://hub.docker.com/r/px4io/px4-dev-raspi/builds) but I am not able to check the reason (the previous docker hub web interface allowed it, but now I cannot check the log). Are you able to check it on your end?

**Comment by lamping7** [comment]
@TSC21 It seems the dev-base container wan't built yet, causing the failure. Try pushing the tag again.

>Building in Docker Cloud's infrastructure...
Cloning into '.'...
Note: checking out '01cbc1f6120678694f13ae9dc397271f0d84cbec'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
git checkout -b <new-branch-name>
KernelVersion: 4.4.0-1060-aws
Components: [{u'Version': u'18.03.1-ee-3', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.4.0-1060-aws', u'Os': u'linux', u'BuildTime': u'2018-08-30T18:42:30.000000000+00:00', u'ApiVersion': u'1.37', u'MinAPIVersion': u'1.12', u'GitCommit': u'b9a5c95', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.10.2'}}]
Arch: amd64
BuildTime: 2018-08-30T18:42:30.000000000+00:00
ApiVersion: 1.37
Platform: {u'Name': u''}
Version: 18.03.1-ee-3
MinAPIVersion: 1.12
GitCommit: b9a5c95
Os: linux
GoVersion: go1.10.2
Starting build of index.docker.io/px4io/px4-dev-raspi:2019-01-01...
Step 1/6 : FROM px4io/px4-dev-base:2019-01-01
manifest for px4io/px4-dev-base:2019-01-01 not found

**Comment by TSC21** [comment]
@lamping7 thanks! How did you check it btw?

Pushed again: https://hub.docker.com/r/px4io/px4-dev-base/builds

**Comment by lamping7** [comment]
You need to be added to px4io repo in docker hub -- @dagar

**Comment by TSC21** [comment]
The fmu-v2 board seems to be down.

**Pull request merged**
