### PR TITLE
rc.sensors simplify

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Tested on Pixracer and verified that the same sensors come up?

**Comment by LorenzMeier** [comment]
@davids5 PX4 defaults on boot to not exit on error (at the top of rcS). Exiting makes really never any sense.

**Comment by LorenzMeier** [comment]
@dagar Have you tested this on Pixracer?

**Comment by davids5** [comment]
@LorenzMeier - thank you, I did not see it in the diff and did not realize it had been changes since I did the original change set.

**Comment by dagar** [comment]
Yes I tested this on a regular pixracer. Please review, but don't merge yet.
I'm going to double check a couple things on px4fmu-v2/v3 and airspeed start across MC/FW/VTOL.

**Comment by LorenzMeier** [comment]
@dagar Any updates on testing?

**Comment by LorenzMeier** [comment]
Closing as stale, I re-did a lot of the good suggestions from Daniel.

**Pull request closed without merging**
