### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by hsteinhaus**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
That doesn't work. You need to update the UAVCAN submodule at the same time if you do this.

**Comment by hsteinhaus** [comment]
I think there is no need to update libuavcan, because it already has been corrected and BasicFileSever is only a typedef to the correctly spelled version:

https://github.com/UAVCAN/libuavcan/blob/master/libuavcan_drivers/posix/include/uavcan_posix/basic_file_server_backend.hpp#L452-L457

**Comment by hsteinhaus** [comment]
@pavel-kirienko, @LorenzMeier: any alternative ideas how to handle this situation?

APM is refusing to build PX4/Firmware, due to -Werror=deprecated-declarations set by default and libuavcan declaring miss-spelled name "BasicFileSever" as deprecated. My favorite still would be to fix the spelling in src/modules/uavcan .

**Comment by pavel-kirienko** [comment]
@LorenzMeier this fix is correct. Necessary renaming has already been done in libuavcan, and the submodule already points to the correct version: https://github.com/UAVCAN/libuavcan/blob/ed1d71e639543ea5743a839c313c53237ab3a27d/libuavcan_drivers/posix/include/uavcan_posix/basic_file_server_backend.hpp#L452-L457.

**Comment by LorenzMeier** [comment]
Ok, thanks for clarifying that. I'm putting it on master now.

**Comment by LorenzMeier** [comment]
Applied to master.

**Pull request closed without merging**
