### PR TITLE
Limit horizontal velocity during landing

### PR DESCRIPTION
**Pull request by bresch**
Usually, a user doesn't need and want to fly at high speed close to ground. We currently already reduce the vertical speed between `MPC_LAND_ALT{1/2}` so I added the same limitation for the horizontal speed.
This also allows more precise control during landing as the scaling on the sticks is reduced.

Additional changes:
- At the same time I centralized the estimation of `_dist_to_ground` in the base FlightTask such that the ManualPosition, AutoMapper(2) and AutoLine can use the same logic without having to recompute it locally.
- I also re-introduced the velocity ramp between alt1 and alt2 that was not implemented in AutoMapper2.

### CODE REVIEW

**Comment by MaEtUgR** [comment]
I allowed myself to rebase the pr and apply some nit-pick suggestions. What is missing for me is a way to disable the functionality. It works well and the implementation is good but there will for sure be someone who wants the legacy behavior because of a missing distance sensor or special use case.

**Comment by MaEtUgR** [comment]
Added a comment in my additional commit on how to disable.

**Comment by bresch** [comment]
Thanks @MaEtUgR .
@PX4/testflights can you please test this PR and verify that when you are in position control mode, the speed is limited when close to the ground? Thanks

**Comment by dannyfpv** [comment]
tested on pixhawk4 v5 f-450
position mode: no issues

log:  https://review.px4.io/plot_app?log=359b3c8c-ccea-4949-a389-ef3a4065f354

pixhawk racer v4 f-450
position mode: no issues

log:  https://review.px4.io/plot_app?log=4b200565-eb8f-49d5-8f04-b88d46987463

**Comment by Junkim3DR** [comment]
**Tested on NXP FMUK66 v3**

Mode Tested: Position Mode.

Procedure: Flight in Position mode and notice ground velocity change proporcional to the altitude of the vehicle.

Notes: No issue.

**Log:**  https://review.px4.io/plot_app?log=b0be1815-e64c-4a6a-808f-b8adce9486db




**Tested on Pixhawk Pro v4**

Mode Tested: Position Mode.

Procedure: Flight in Position mode and notice ground velocity change proporcional to the altitude of the vehicle.

Notes: No issue.

**Log:**  https://review.px4.io/plot_app?log=adab6003-a537-43c3-9c2e-4b31d6003962

**Comment by MaEtUgR** [comment]
I also did some real-world flight testing and if the altitudes `MPC_LAND_ALT1`, `MPC_LAND_ALT2` are not super close like less than a meter to each other it works super nice. If they are too close the maximum allowed speed changes very quickly but that's a question of configuration. I consider this a good feature since especially with a downward-facing distance sensor manual landing even when coming from flying fast forward gets so easy.

**Comment by MaEtUgR** [comment]
I just confirmed an issue: If you go full stick while flying up the allowed velocity gets faster and faster but you acceleration is much lower than when you start flying on the same altitude even after you are long over `MPC_LAND_ALT1`
slowdown

**Comment by MaEtUgR** [comment]
We found that it's not this pr creating the behavior that is shown above but the problem already existed before and it was only found by thoroughly testing this pr. @bresch will create another pr to get rid of this legacy logic. See https://github.com/PX4/Firmware/blob/a3d30fc970262a589ed2ac94c0c5bf18343162c0/src/lib/flight_tasks/tasks/ManualPosition/FlightTaskManualPosition.cpp#L104-L114

**Pull request merged**
