### PR TITLE
VTOL setpoint and integrator reset

### PR DESCRIPTION
**Pull request by dagar**
RE: https://github.com/PX4/Firmware/issues/6554#issuecomment-280133417

@sanderux do you want to give this a try? I've test flown the fw_att change many times, but the mc_pos change is new and so far only tested in SITL.

### CODE REVIEW

**Comment by sanderux** [comment]
yep, it looks good, i'll give it a test fly

**Comment by dagar** [comment]
Test flight from Sander - http://logs.uaventure.com/view/NbpZb9FxEuH4KriuqoDbTi

**Comment by dagar** [comment]
@AndreasAntener or @tumbili could you review?

**Comment by sanderux** [comment]
I would like to get this in before my next round of testing, can someone please merge this?

**Comment by dagar** [comment]
@Stifael could you review the mc_pos_ctrl changes?

**Pull request merged**
