### PR TITLE
[DNM] Testing CI hardfault on NXP

### PR DESCRIPTION
**Pull request by BazookaJoe1900**
this pr is not for merge and is just for testing hardfault that found on #14031.
the hardfault exist from commit ~0c9161f004531b5c8a342ca2a075fbbfd97823ae but not in ~7d295fd99d274e7d4248241ce99f4b11edfc400b.
Because I don't have the NXP board, I am using the CI to run the tests.

### CODE REVIEW

**Comment by BazookaJoe1900** [comment]
status report, by bisect the commits I found that from commit 156cf16265606b2f7fe75c0e4e0f6c3e4a42b052 there is hardfault.
still looking why

**Comment by BazookaJoe1900** [comment]
@dagar I am abit stack here because I don't have the fmuk66 hardware at all (and not really using it...)
is there someone that does use this board that you can point the hardfault issue to?

I am still working on how to read the hardware test output to identify errors such hardfaults

**Comment by dagar** [comment]
Do you have any additional evidence that points to this hardware or not specifically? 

Have you verified all the stacks have a healthy margin?

**Comment by BazookaJoe1900** [comment]
@dagar I have problem to check the fmuk66, because I don't have this hardware. and basiclly I need to do the test by this hardware check.
I Try on this PR to make the hardware check to fail on hardfault.
If it just stack issue, it will be easy to check and fix. but it might be much more complex

**Comment by BazookaJoe1900** [comment]
closing this PR, its better in this stage to find hardfault is better to do with real HW, and not by CI

**Pull request closed without merging**
