### PR TITLE
Update submodule libuavcan to latest Fri Jun 29 21:33:48 EDT 2018

### PR DESCRIPTION
**Pull request by dagar**
- libuavcan in PX4/Firmware (c2987a9cadb8857cabd33b3e9312c5fc7be04fd6): https://github.com/UAVCAN/libuavcan/commit/dfcdf22eda16ff06847976fd6c7f40671fc92eb5
    - libuavcan current upstream: https://github.com/UAVCAN/libuavcan/commit/c044630390370d800a22e7746cd949ddd3c59bb1
    - Changes: https://github.com/UAVCAN/libuavcan/compare/dfcdf22eda16ff06847976fd6c7f40671fc92eb5...c044630390370d800a22e7746cd949ddd3c59bb1

    c044630 2018-06-27 Pavel Kirienko - Merge pull request #138 from thirtytwobits/feature/issue100
4750a50 2018-06-14 Dixon, Scott - Issue #100 remove auto_ptr and c++03 support.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@dagar Let's wait with this for a review from Daniele - but it might take a couple of days for him to get the time to look into it.

**Comment by dagar** [comment]
Yes I didn't want to just merge this one without real testing. Nothing urgent here, but I think it's overall going to be easier to keep up with these incrementally.

**Comment by DanielePettenuzzo** [comment]
I can have a look at it tomorrow.

**Comment by dagar** [comment]
@Tony3dr do you have any UAVCAN devices?
GPS - https://zubax.com/products/gnss_2
ESC - https://zubax.com/products/myxa

**Comment by Tony3dr** [comment]
@dagar no, we do not.

**Comment by mrpollo** [comment]
@dagar @Tony3dr I just reached out to @pavel-kirienko for guidance on hardware for testing, I'll keep you posted.

**Comment by mrpollo** [comment]
@dagar just a heads up the test team is getting UAVCAN hardware and will be ready to test as soon as we receive it and we can assemble a new vehicle, please work with @Tony3dr and @santiago3dr for an ETA on testing for this PR.


Thanks for the hardware Zubax cc @pavel-kirienko 🎉 🚀

**Comment by davids5** [comment]
The Kinetis submodule has been mainlined in uavcan!

**Pull request merged**
