### PR TITLE
Param: Implement RW locking to reduce lock contention

### PR DESCRIPTION
**Pull request by bkueng**
With the introduction of param locking (https://github.com/PX4/Firmware/pull/6597), reading parameters potentially becomes a bottleneck since the whole system wants to read params, and usually at the same time.

This improves that by allowing multiple readers to enter the critical section concurrently. 

However taking a lock is expensive and it can be made more efficient using an [RCU](https://en.wikipedia.org/wiki/Read-copy-update) synchronization scheme. In that case a reader only needs to increase/decrease an atomic counter.

The PR also reduces the size of `param_t` to 16 bits (since we really only need < 1000), freeing up almost 1 KB of RAM (with around 120 changed params).

While updating it, I discovered another concurrency issue (it is a problem we already had). `param_changed_storage` is updated during a param read using non-atomic read-modify-write (https://github.com/PX4/Firmware/compare/param_rw_locking?expand=1#diff-a953b7046039fd7cd55c5860953df79cR721). If 2 (or more) threads try to set a bit at the same time, it can happen that one of updates gets overwritten by the other, thus a param would not be marked as used even though it is.

Tested on SITL & Pixracer.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@julianoes Can you please review ASAP?

**Comment by LorenzMeier** [comment]
@eyeam3 If you have time, can you add a review as well?

**Comment by bkueng** [comment]
Yes, when there are continuously new readers keeping `reader_lock_holders` > 0, a writer waiting for the lock will never make progress.

**Comment by davids5** [comment]
@bkueng
Do you think px4_enter_critical_section and px4_leave_critical_section would be suitable
 for the [bit set]( https://github.com/PX4/Firmware/blob/d55ffc0b46089eba84e3bdaa071ebce293dafba7/src/modules/systemlib/param/param.c#L721) ?

**Comment by davids5** [comment]
@bkueng Any idea what the RCU will costs in terms of RAM?

**Comment by bkueng** [comment]
@davids5 `px4_enter_critical_section` would work on NuttX only. I think using atomic primitives would be best here with minimal overhead (for example a compare-and-swap), which we would need to introduce with RCU anyway. Taking a lock at this place would have a non-negligible negative effect on performance.

With RCU you need a second temporary buffer, the size of `param_values`, so depending on the number of non-default params. However the same is true for the current implementation: we use `realloc` to dynamically resize `param_values`, which usually allocates a new buffer, copies it over and then releases the old one. So my prediction is that it would use roughly the same amount of RAM.

Thanks for the reviews.

**Pull request merged**
