### PR TITLE
Removed CMSIS.

### PR DESCRIPTION
**Pull request by jgoppert**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This looks good - how is the testing? Rebasing on master should fix Travis.

**Comment by jgoppert** [comment]
Has been test flown as part of lpe pr but separating it out into smaller chunks.

**Comment by LorenzMeier** [comment]
Can you quickly rebase? I can pull it in then. Did you compare CPU loads?

**Comment by jgoppert** [comment]
Rebase done. I have not yet done a close comparison of cpu loading. What apps would you like to see? Just LPE, or EKF2 and INAV as well?

**Comment by LorenzMeier** [comment]
mostly LPE and the controllers. EKF2 will not be affected.

**Comment by LorenzMeier** [comment]
https://github.com/PX4/Firmware/pull/4077

**Pull request closed without merging**
