### PR TITLE
Create Vtol solar

### PR DESCRIPTION
**Pull request by hugo25130**
Create a VTOL based on Caipirinha tailsitter, with two more servos.

### CODE REVIEW

**Comment by dagar** [comment]
Hi Hugo,

Doesn't the existing Caipirinha tailsitter already support this?

**Comment by hugo25130** [comment]
Hi,

Not really. My UAV looks like Caipirinha tailsitter, but with a wingspan of 2 m. So I wanted to add two flaps, so my UAV has two elevens and two flaps.
But I don’t really know how can I code this … Do you know or know somebody who can maybe help me ?

Regards

Hugo HONORÉ

De : Daniel Agar [mailto:notifications@github.com]
Envoyé : samedi 15 juillet 2017 16:28
À : PX4/Firmware <Firmware@noreply.github.com>
Cc : Honoré Hugo <hugo.honore@he-arc.ch>; Author <author@noreply.github.com>
Objet : Re: [PX4/Firmware] Create Vtol solar (#7611)


Hi Hugo,

Doesn't the existing already support this?

**Comment by dagar** [comment]
@hugo25130 the missing piece is the mixer. This is the existing mixer. https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/mixers/caipirinha_vtol.main.mix

To add flaps take a look at this standard plane mixer, then add a flaps section to yoru own mixer. https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/mixers/AETRFG.main.mix

	CH5: Flaps mixer
	------------
	Flaps are controlled automatically in position control and auto
	but can also be controlled manually

	M: 1
	O:        5000  10000       0  -10000  10000
	S: 0 4   10000  10000       0  -10000  10000

Mixer documentation here. https://dev.px4.io/en/concept/mixing.html

**Comment by hugo25130** [comment]
I’m not sure if my comprehension is ok : I only have to add a flap section in the caipirinha mixer and the init.d file, build the code in my pixhawk and it’s ok ? Does the pixhawk accept and pilot the 2 servos for flaps ?
De : Daniel Agar [mailto:notifications@github.com]
Envoyé : lundi 17 juillet 2017 15:03
À : PX4/Firmware <Firmware@noreply.github.com>
Cc : Honoré Hugo <hugo.honore@he-arc.ch>; Mention <mention@noreply.github.com>
Objet : Re: [PX4/Firmware] Create Vtol solar (#7611)


@hugo25130<https://github.com/hugo25130> the missing piece is the mixer. This is the existing mixer. https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/mixers/caipirinha_vtol.main.mix

To add flaps take a look at this standard plane mixer, then add a flaps section to yoru own mixer. https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/mixers/AETRFG.main.mix

CH5: Flaps mixer

------------

Flaps are controlled automatically in position control and auto

but can also be controlled manually



M: 1

O:        5000  10000       0  -10000  10000

S: 0 4   10000  10000       0  -10000  10000

Mixer documentation here. https://dev.px4.io/en/concept/mixing.html

**Comment by dagar** [comment]
Yes that will give you flaps in the mixer including the ability to control them with the transmitter, but how do you want to use them? In autonomous mode flaps are deployed for regular fixed wing landing, but otherwise in fully autonomous VTOL they won't be used.

**Comment by hugo25130** [comment]
I don’t really know how I want to use flaps, I will make some tests and I’ll determine after.

I have a question about building code with windows : I cannot find some tutorials or anything, do you know somebody who has already build on windows ?

De : Daniel Agar [mailto:notifications@github.com]
Envoyé : mardi 18 juillet 2017 05:52
À : PX4/Firmware <Firmware@noreply.github.com>
Cc : Honoré Hugo <hugo.honore@he-arc.ch>; Mention <mention@noreply.github.com>
Objet : Re: [PX4/Firmware] Create Vtol solar (#7611)


Yes that will give you flaps in the mixer including the ability to control them with the transmitter, but how do you want to use them? In autonomous mode flaps are deployed for regular fixed wing landing, but otherwise in fully autonomous VTOL they won't be used.

**Comment by dagar** [comment]
A couple developers use Windows, but most use Linux or OSX. Have you tried the documentation here? https://dev.px4.io/en/setup/dev_env_windows.html

**Comment by dagar** [comment]
Closing as stale.

**Pull request closed without merging**
