### PR TITLE
Param index fix

### PR DESCRIPTION
**Pull request by LorenzMeier**
This uses the right function for individual param transfers.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@DonLakeFlyer QGC crashes with this branch, but because it crashes and doesn't report an error its hard to work out what's going wrong. I presume some out-of-order parameter message? Will continue to dig a bit deeper on this one.

```
Process:         qgroundcontrol [66689]
Path:            /Users/USER/*/qgroundcontrol.app/Contents/MacOS/qgroundcontrol
Identifier:      org.qgroundcontrol.qgroundcontrol
Version:         2.0.0 (227)
Code Type:       X86-64 (Native)
Parent Process:  Qt Creator [352]
Responsible:     Qt Creator [352]
User ID:         501

Date/Time:       2015-04-26 14:11:40.256 +0200
OS Version:      Mac OS X 10.9.5 (13F1066)
Report Version:  11
Anonymous UUID:  0BE00B61-2D1F-543C-38F9-2BD7ACFA6ECA

Sleep/Wake UUID: 1DF9F40B-6163-4EA0-AF7B-A7C21F0C1844

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000020

VM Regions Near 0x20:
--> 
    __TEXT                 0000000100000000-0000000100a74000 [ 10.5M] r-x/rwx SM=COW  /Users/USER/*/qgroundcontrol.app/Contents/MacOS/qgroundcontrol

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtCore         	0x000000010181c7b1 QVariant::QVariant(QVariant const&) + 17
1   org.qgroundcontrol.qgroundcontrol	0x0000000100332882 Fact::value() const + 18
2   org.qgroundcontrol.qgroundcontrol	0x000000010030750a AirframeComponent::setupComplete() const + 58
3   org.qgroundcontrol.qgroundcontrol	0x00000001003045ac AutoPilotPlugin::_recalcSetupComplete() + 156
4   org.qgroundcontrol.qgroundcontrol	0x000000010030437d AutoPilotPlugin::_pluginReadyChanged(bool) + 29
5   org.qt-project.QtCore         	0x00000001018115f2 QMetaObject::activate(QObject*, int, int, void**) + 1986
6   org.qgroundcontrol.qgroundcontrol	0x0000000100380e0d AutoPilotPlugin::pluginReadyChanged(bool) + 61
7   org.qgroundcontrol.qgroundcontrol	0x000000010030f757 PX4AutoPilotPlugin::_pluginReadyPreChecks() + 295
8   org.qt-project.QtCore         	0x00000001018115f2 QMetaObject::activate(QObject*, int, int, void**) + 1986
9   org.qgroundcontrol.qgroundcontrol	0x0000000100389ac5 ParameterLoader::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 309
10  org.qt-project.QtCore         	0x00000001018119db QMetaObject::activate(QObject*, int, int, void**) + 2987
11  org.qgroundcontrol.qgroundcontrol	0x0000000100351b36 QGCUASParamManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 1366
12  org.qt-project.QtCore         	0x00000001018119db QMetaObject::activate(QObject*, int, int, void**) + 2987
13  org.qgroundcontrol.qgroundcontrol	0x0000000100178371 UASParameterCommsMgr::updateSilenceTimer() + 1137
14  org.qgroundcontrol.qgroundcontrol	0x00000001001798e1 UASParameterCommsMgr::receivedParameterUpdate(int, int, int, int, QString, QVariant) + 5025
15  org.qgroundcontrol.qgroundcontrol	0x000000010035f1c2 UASParameterCommsMgr::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 2162
16  org.qt-project.QtCore         	0x00000001018119db QMetaObject::activate(QObject*, int, int, void**) + 2987
17  org.qgroundcontrol.qgroundcontrol	0x000000010035b77d UASInterface::parameterChanged(int, int, int, int, QString, QVariant) + 109
18  org.qgroundcontrol.qgroundcontrol	0x000000010016381a UAS::processParamValueMsg(__mavlink_message&, QString const&, __mavlink_param_value_t const&, param_union&) + 1898
19  org.qgroundcontrol.qgroundcontrol	0x00000001001596c1 UAS::receiveMessage(LinkInterface*, __mavlink_message) + 25793
20  org.qgroundcontrol.qgroundcontrol	0x000000010014b13b QtPrivate::QSlotObject<void (UAS::*)(LinkInterface*, __mavlink_message), QtPrivate::List<LinkInterface*, QtPrivate::List<__mavlink_message, void> >, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) + 107
21  org.qt-project.QtCore         	0x00000001018115f2 QMetaObject::activate(QObject*, int, int, void**) + 1986
22  org.qgroundcontrol.qgroundcontrol	0x0000000100349275 MAVLinkProtocol::messageReceived(LinkInterface*, __mavlink_message) + 69
23  org.qgroundcontrol.qgroundcontrol	0x0000000100106a52 MAVLinkProtocol::receiveBytes(LinkInterface*, QByteArray) + 4402
24  org.qgroundcontrol.qgroundcontrol	0x000000010010206a void QtPrivate::FunctionPointer<void (MAVLinkProtocol::*)(LinkInterface*, QByteArray)>::call<QtPrivate::List<LinkInterface*, QtPrivate::List<QByteArray, void> >, void>(void (MAVLinkProtocol::*)(LinkInterface*, QByteArray), MAVLinkProtocol*, void**) + 74
25  org.qt-project.QtCore         	0x000000010180a5c3 QObject::event(QEvent*) + 755
26  org.qt-project.QtWidgets      	0x0000000102bd3dbb QApplicationPrivate::notify_helper(QObject*, QEvent*) + 251
27  org.qt-project.QtWidgets      	0x0000000102bd7110 QApplication::notify(QObject*, QEvent*) + 8192
28  org.qt-project.QtCore         	0x00000001017dfc8b QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 971
29  libqcocoa.dylib               	0x000000010450c1be QCocoaEventDispatcherPrivate::processPostedEvents() + 190
30  libqcocoa.dylib               	0x000000010450ca41 QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 33
31  com.apple.CoreFoundation      	0x00007fff8d7235b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
32  com.apple.CoreFoundation      	0x00007fff8d714c62 __CFRunLoopDoSources0 + 242
33  com.apple.CoreFoundation      	0x00007fff8d7143ef __CFRunLoopRun + 831
34  com.apple.CoreFoundation      	0x00007fff8d713e75 CFRunLoopRunSpecific + 309
35  com.apple.HIToolbox           	0x00007fff96a74a0d RunCurrentEventLoopInMode + 226
36  com.apple.HIToolbox           	0x00007fff96a747b7 ReceiveNextEventCommon + 479
37  com.apple.HIToolbox           	0x00007fff96a745bc _BlockUntilNextEventMatchingListInModeWithFilter + 65
38  com.apple.AppKit              	0x00007fff8ffce24e _DPSNextEvent + 1434
39  com.apple.AppKit              	0x00007fff8ffcd89b -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
40  com.apple.AppKit              	0x00007fff8ffc199c -[NSApplication run] + 553
41  libqcocoa.dylib               	0x000000010450b92d QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2189
42  org.qt-project.QtCore         	0x00000001017dc5ad QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 381
43  org.qt-project.QtCore         	0x00000001017df58a QCoreApplication::exec() + 346
44  org.qgroundcontrol.qgroundcontrol	0x000000010013a3d9 main + 297
45  org.qgroundcontrol.qgroundcontrol	0x000000010000a374 start + 52

Thread 1:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x00007fff97d20662 kevent64 + 10
1   libdispatch.dylib             	0x00007fff91507421 _dispatch_mgr_invoke + 239
2   libdispatch.dylib             	0x00007fff91507136 _dispatch_mgr_thread + 52

Thread 2:: QProcessManager
0   libsystem_kernel.dylib        	0x00007fff97d1f9aa __select + 10
1   org.qt-project.QtCore         	0x000000010177d2af QProcessManager::run() + 143
2   org.qt-project.QtCore         	0x00000001015d5393 QThreadPrivate::start(void*) + 339
3   libsystem_pthread.dylib       	0x00007fff96d52899 _pthread_body + 138
4   libsystem_pthread.dylib       	0x00007fff96d5272a _pthread_start + 137
5   libsystem_pthread.dylib       	0x00007fff96d56fc9 thread_start + 13

Thread 3:: QThread
0   libsystem_kernel.dylib        	0x00007fff97d1fa3a __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff90b9cdc0 nanosleep + 200
2   org.qt-project.QtCore         	0x0000000101688afb qt_nanosleep(timespec) + 43
3   org.qgroundcontrol.qgroundcontrol	0x00000001000f9244 QGCAudioWorker::say(QString, int) + 532
4   org.qgroundcontrol.qgroundcontrol	0x0000000100135e49 void QtPrivate::FunctionPointer<void (QGCAudioWorker::*)(QString, int)>::call<QtPrivate::List<QString, QtPrivate::List<int, void> >, bool>(void (QGCAudioWorker::*)(QString, int), QGCAudioWorker*, void**) + 73
5   org.qt-project.QtCore         	0x000000010180a5c3 QObject::event(QEvent*) + 755
6   org.qt-project.QtWidgets      	0x0000000102bd3dbb QApplicationPrivate::notify_helper(QObject*, QEvent*) + 251
7   org.qt-project.QtWidgets      	0x0000000102bd7110 QApplication::notify(QObject*, QEvent*) + 8192
8   org.qt-project.QtCore         	0x00000001017dfc8b QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 971
9   org.qt-project.QtCore         	0x000000010183201b QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 59
10  org.qt-project.QtCore         	0x00000001017dc5ad QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 381
11  org.qt-project.QtCore         	0x00000001015d1905 QThread::exec() + 117
12  org.qt-project.QtCore         	0x00000001015d5393 QThreadPrivate::start(void*) + 339
13  libsystem_pthread.dylib       	0x00007fff96d52899 _pthread_body + 138
14  libsystem_pthread.dylib       	0x00007fff96d5272a _pthread_start + 137
15  libsystem_pthread.dylib       	0x00007fff96d56fc9 thread_start + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff97d1ba1a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff97d1ad18 mach_msg + 64
2   com.apple.CoreFoundation      	0x00007fff8d714f15 __CFRunLoopServiceMachPort + 181
3   com.apple.CoreFoundation      	0x00007fff8d714539 __CFRunLoopRun + 1161
4   com.apple.CoreFoundation      	0x00007fff8d713e75 CFRunLoopRunSpecific + 309
5   com.apple.AppKit              	0x00007fff9016e05e _NSEventThread + 144
6   libsystem_pthread.dylib       	0x00007fff96d52899 _pthread_body + 138
7   libsystem_pthread.dylib       	0x00007fff96d5272a _pthread_start + 137
8   libsystem_pthread.dylib       	0x00007fff96d56fc9 thread_start + 13

Thread 5:: QQmlThread
0   libsystem_kernel.dylib        	0x00007fff97d1f9aa __select + 10
1   org.qt-project.QtCore         	0x0000000101830134 qt_safe_select(int, fd_set*, fd_set*, fd_set*, timespec const*) + 596
2   org.qt-project.QtCore         	0x0000000101831000 QEventDispatcherUNIXPrivate::doSelect(QFlags<QEventLoop::ProcessEventsFlag>, timespec*) + 672
3   org.qt-project.QtCore         	0x00000001018320ca QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 234
4   org.qt-project.QtCore         	0x00000001017dc5ad QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 381
5   org.qt-project.QtCore         	0x00000001015d1905 QThread::exec() + 117
6   org.qt-project.QtQml          	0x00000001027b4f59 QQmlThreadPrivate::run() + 57
7   org.qt-project.QtCore         	0x00000001015d5393 QThreadPrivate::start(void*) + 339
8   libsystem_pthread.dylib       	0x00007fff96d52899 _pthread_body + 138
9   libsystem_pthread.dylib       	0x00007fff96d5272a _pthread_start + 137
10  libsystem_pthread.dylib       	0x00007fff96d56fc9 thread_start + 13

Thread 6:: MAVLinkDecoder
0   libsystem_kernel.dylib        	0x00007fff97d1f9aa __select + 10
1   org.qt-project.QtCore         	0x0000000101830134 qt_safe_select(int, fd_set*, fd_set*, fd_set*, timespec const*) + 596
2   org.qt-project.QtCore         	0x0000000101831000 QEventDispatcherUNIXPrivate::doSelect(QFlags<QEventLoop::ProcessEventsFlag>, timespec*) + 672
3   org.qt-project.QtCore         	0x00000001018320ca QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 234
4   org.qt-project.QtCore         	0x00000001017dc5ad QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 381
5   org.qt-project.QtCore         	0x00000001015d1905 QThread::exec() + 117
6   org.qt-project.QtCore         	0x00000001015d5393 QThreadPrivate::start(void*) + 339
7   libsystem_pthread.dylib       	0x00007fff96d52899 _pthread_body + 138
8   libsystem_pthread.dylib       	0x00007fff96d5272a _pthread_start + 137
9   libsystem_pthread.dylib       	0x00007fff96d56fc9 thread_start + 13
```

**Comment by vooon** [comment]
It is fix for https://github.com/mavlink/mavros/issues/274 ?

**Comment by LorenzMeier** [comment]
Yes, once this is all functional. I still have some tests to run, its not ready to go yet.

**Comment by vooon** [comment]
Just flashed master. Pixhawk won't start: blinks red, state: uninit. Perhaps i must start HIL (before flash it confugured for HilStar)?
And i still has this strange request-response:
```
[ WARN] [1430054873.245749777]: PR: request param #0 timeout, retries left 0, and 1 params still missing
[DEBUG] [1430054873.245972750]: PR:m: request '', idx 0
[DEBUG] [1430054873.246076244]: serial0: send: Message-Id: 20 [20 bytes] Sys-Id: 1 Comp-Id: 240 Seq: 3
[DEBUG] [1430054873.248388890]: serial0: recv: Message-Id: 22 [25 bytes] Sys-Id: 1 Comp-Id: 50 Seq: 124
[DEBUG] [1430054873.248688902]: PR: Update param MKBLCTRL_TEST (1/368) value: 0 int
```

Indexes starts from 1?

**Comment by LorenzMeier** [comment]
The red light is because you haven't calibrated it. Use QGroundControl and it should become obvious how to fix that. As for the params: I'm looking into it, that looks indeed wrong.

**Comment by vooon** [comment]
Tried to recalibrate: calibrated all but AIRSPEED. Still getting red flashes and the message "sensors not operational".

I found source of mavlink/mavros#269 - inline does something completely wrong.

**Comment by LorenzMeier** [comment]
Do you have it configured as multirotor or as fixed wing?

**Comment by LorenzMeier** [comment]
The SYS_AUTOSTART param would tell you. What is its value?

**Comment by vooon** [comment]
SYS_AUTOSTART=1000

2015-04-26 18:47 GMT+03:00 Lorenz Meier <notifications@github.com>:

**Comment by LorenzMeier** [comment]
Ok, got it. I pushed a potential fix to master. Please re-try.

**Comment by DonLakeFlyer** [comment]
There’s a bug in airframe config which does strange things when SYS_AUTOSTART=0. I believe I already have it fixed in a pull I’m working on now.

**Comment by vooon** [comment]
Just flashed master. Nothing changes. Done calibration again, nothing changes.
Tried to start HIL (with no actual simulator started) -- got fade-in fade-out blue, same as before, but reboot still red.

But now i'm can't debug further, preparing to go to country-house. Will soon open the flight season :)

**Pull request merged**
