### PR TITLE
px4io MIXER_FAIL failure

### PR DESCRIPTION
**Pull request by western-co-at**
After doing several power cycle tests with a PX4 v2 hardware I noticed that my multicopter didn't arm after each 10th to 100th cycle. This is because of a MIXER_FAIL failure in the px4io module:

```nsh>
px4io status
px4io status
WARN  [px4io] loaded
protocol 4 hardware 2 bootloader 3 buffer 64B crc 0x57147223
8 controls 8 actuators 18 R/C inputs 2 analog inputs 0 relays
456 bytes free
status 0x3e4d OUTPUTS_ARMED SAFETY_OFF RC_OK PPM FMU_OK MIXER_FAIL ARM_SYNC INIT_OK FAILSAFE
alarms 0x0000
vservo 1225 mV vservo scale 10000
vrssi 1594
actuators -16666 -16666 -16666 -16666 -16666 -16666 -16666 -16666
servos 900 900 900 900 900 500 900 500
reversed outputs: [________] trims: r:   0.0000 p:   0.0000 y:   0.0000
8 raw R/C inputs 1808 1509 1509 1510 1509 1908 1508 1508
R/C flags: 0x0018 MAPPING_OK
RC data (PPM frame len) 20002 us
mapped R/C inputs 0x000f 0:0 1:0 2:0 3:8772
ADC inputs 507 2016
features 0x0008 RSSI_ADC
arming 0x043b FMU_ARMED IO_ARM_OK FAILSAFE_CUSTOM INAIR_RESTART_OK ALWAYS_PWM_ENABLE OVERRIDE_IMMEDIATE
rates 0x00ff default 50 alt 400 sbus 72
debuglevel 0
controls 0: 5 303 -265 9000 0 0 0 10000
controls 1: 0 0 0 0 0 0 0 0
controls 2: 0 0 0 0 0 0 0 0
controls 3: 0 0 0 8771 0 0 0 0
input 0 min 1105 center 1105 max 1905 deadzone 10 assigned 3 options 0x0001 ENABLED
input 1 min 1106 center 1506 max 1906 deadzone 10 assigned 0 options 0x0003 ENABLED REVERSED
input 2 min 1105 center 1504 max 1905 deadzone 10 assigned 1 options 0x0001 ENABLED
input 3 min 1106 center 1502 max 1906 deadzone 10 assigned 2 options 0x0003 ENABLED REVERSED
input 4 min 1105 center 1505 max 1906 deadzone 10 assigned 100 options 0x0001 ENABLED
input 5 min 1105 center 1505 max 1906 deadzone 10 assigned 255 options 0x0000
input 6 min 1105 center 1505 max 1906 deadzone 10 assigned 255 options 0x0000
input 7 min 1105 center 1505 max 1906 deadzone 10 assigned 255 options 0x0000
input 8 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 9 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 10 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 11 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 12 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 13 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 14 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 15 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 16 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 17 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
failsafe 500 500 500 500 500 500 500 500
disarmed values 900 900 900 900 900 900 900 900
```
The reason why this occur is because of a read-modify-write bug in the px4io firmware:
- In the files controls.c, mixer.cpp and safety.c the variable r_status_flags get modified by |= or &= which are not atomic operations.
- parallel to this the fmu can modify this variable via an interrupt routine in the px4io firmware
Thus the new r_status_flags can be back overwritten by the old value.

To solve this problem I suggest a macro with the px4_enter_critical_section and px4_leave_critical_section for the |= and &= operations (only for controls.c, mixer.cpp and safety.c).

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@davids5 Please review.

**Comment by LorenzMeier** [comment]
@western-co-at Please run `make format` to clear the CI failure (which is because of non-matching code style).

**Comment by LorenzMeier** [comment]
@western-co-at The way you implemented locking here disables interrupts, which is probably not sustainable at this wide usage. The easiest way to improve this would be to only lock if the value needs to be modified (essentially test for `val | mod` == `val`. That would remove a ton of locking already.

On a quick pass it also looks like the remaining locations do in fact require locking and make sense. They are executed during configuration of the system and not during runtime, so the overhead is less of a concern there.

**Comment by LorenzMeier** [comment]
I've started to tinker on a lazy atomic implementation.

**Comment by western-co-at** [comment]
@LorenzMeier You are right. This are many interrupt disables. But does this have an influence reading the ppm input or pwm output or cause any other problems? 
Would the bit-banding of the ARM processor be a solution? With this it would be possible to set and clear bits in an atomic way.
If you have another implementation I can do power cycle tests on that.

**Comment by LorenzMeier** [comment]
Could you review and test this version? https://github.com/PX4/Firmware/pull/7181

I have not really solved the atomic operation bit, but rather solved this very specific issue for modifying flags efficiently.

**Comment by western-co-at** [comment]
@LorenzMeier I will test your solution and grep for the MIXER_FAIL failure. 
Could you have a look to the bit banding: [http://www.micromouseonline.com/2010/07/14/bit-banding-in-the-stm32/](url) I think this may be a better solution.

**Comment by LorenzMeier** [comment]
@western-co-at If you would be willing to implement the bit-banding access I'd be happy to merge that instead of my approach.

**Comment by LorenzMeier** [comment]
Or rather, let me close this PR, merge the other PR and we can replace the backend implementation with bit-banding instead of what I did. The macros required are the same, just their content is changing.

**Pull request closed without merging**
