### PR TITLE
Bringup m3

### PR DESCRIPTION
**Pull request by mcharleb**
This is the fix for POSIX to support px4_getpid() in both px4_task and pthread context.

### CODE REVIEW

**Comment by mcharleb** [comment]
I think this should be good to go.

**Comment by LorenzMeier** [comment]
@mcharleb The diff looks good but the history does contain the history of what you did, not the history of concepts - the difference being that our normal procedure would be to fixup a few of those commits into a single commit. Can you and your team rebase, or do we have to leave these untouched?

**Comment by mcharleb** [comment]
I will rebase on a new branch

**Comment by tumbili** [comment]
@mcharleb It seems like the mavlink app cannot be called in the startup script. If I call it I always get tonns of messages "WARN  node_open as advertiser failed. (file /home/roman/Firmware/src/modules/uORB/uORBManager_posix.cpp line 96)"
If I call it manually from the terminal (mavlink start -u 14556) everything works

**Comment by mcharleb** [comment]
I added support for a sleep command so you should be able to add something like:

sleep 1

before you start mavlink. You could see if that helps. Are you starting things in a different order if you do it from the command line?

**Comment by tumbili** [comment]
Let me just try the sleep. I tried launching it at the very end but didn't help.

**Comment by LorenzMeier** [comment]
We need this one in ASAP:
https://github.com/PX4/Firmware/pull/2371

**Pull request closed without merging**
