### PR TITLE
mc_pos_control: uorb home_postition subscription

### PR DESCRIPTION
**Pull request by Stifael**

### CODE REVIEW

**Comment by Stifael** [comment]
tested outside

**Comment by Stifael** [comment]
Strange that the style fix caused build problems for submodules...?

**Comment by dagar** [comment]
@Stifael can you elaborate? I don't see a failure.

**Comment by Stifael** [comment]
Does not ci fail? It has a red cross and looking at the console output it says that it had a build error with submodule

**Comment by dagar** [comment]
http://sitl01.dronetest.io is only ROS based mission tests. It looks like jenkins failed to clone jmavsim. I'll force it to try again.

**Pull request merged**
