### PR TITLE
Driver NVS receiver

### PR DESCRIPTION
**Pull request by sousapedro596**
@LorenzMeier 
This are the changes that we normally do to the stable branch of Firmware when we want to use the NVS receiver.

This changes implement support for NVS GNSS receiver using BINR protocol ( http://www.nvs-gnss.com/support/documentation/item/download/39.html)

This commit adds two new files:

- this is where we configure and read specific messages from the receiver

**/src/drivers/gps/nvs.cpp**
**/src/drivers/gps/nvs.h**

and changes:

- simple changes to make gps module trying connect to the new NVS receiver
**/src/drivers/gps/gps.cpp**

- added the GPS_DRIVER_MODE_NVS to **enum**
**/src/drivers/drv_gps.h**

- Added the file nvs.cpp to makefile
**/src/drivers/gps/module.mk**

When we have some free time we will try to do some flying tests and add a checksum function.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I'd be happy to merge it once you have validated in flight. The general shape is looking good.

**Comment by vooon** [comment]
A bit off-topic: @sousapedro596 you know any good inexpensive module (antenna+rx) with that NVS receivers? I seen fly away in GCS about 1.5 km, while plane actually lying on the ground (Ublox M8-based module BN-880).
I hope that navis better integrate position data from glonass and gps.

About code: why don't use `M_PI`? Also data accessor functions (I2, R4, R8) may be better make inlined (`static inline`).
Also not sure about PX4 conventions, but spaces instead of tabs are shine in [git diff](https://github.com/PX4/Firmware/pull/2613/files).

**Comment by LorenzMeier** [comment]
@sousapedro596 Where is your testing standing?

**Comment by LorenzMeier** [comment]
@sousapedro596 Please rebase on master and test with your receiver. I'm going to close this in two weeks if there is no solid testing feedback.

**Comment by sousapedro596** [comment]
@LorenzMeier  This driver was previously used in a boat (gnss was not that critical), in test flights we saw some inconsistencies (maybe runtime problems between what px4 expect and what the receiver provided...) and after awhile we stopped to use it for flying. Now we are not using it. Anyway I think this is the last  [log](http://logs.uaventure.com/view/Qdwc3k2pa3hXYY7CxuRkpk).
I am not working with this anymore, but if someone is interested I can try to help finding the problem.

@vooon I think that we contacted NVS through the email on the site and bought the receiver directly, but I think they are also available from farnell. About the code, completely agree.

**Comment by LorenzMeier** [comment]
Closing as inactive. Please re-open if more testing is available. We're adding u-Blox RTK support right now.

**Pull request closed without merging**
