### PR TITLE
Ground firmware

### PR DESCRIPTION
**Pull request by anbriel**
Firmware dedicated for Ground robot using MD25 motor driver, and fuzzy logic for the position control

### CODE REVIEW

**Comment by julianoes** [comment]
Thanks @anbriel for making this PR. Can you rebase on current master and resolve the conflicts?

**Comment by dagar** [comment]
@anbriel could you make this mergeable with master so that builds will run? You could squash it and rebase or git merge --squash on a fresh master based branch.

**Comment by dagar** [comment]
@anbriel it looks like you've overwritten the mavlink submodule with actual file changes. Could you take a look and try to limit the massive diff here?

**Comment by dagar** [comment]
@anbriel I've rebased your work on current PX4 master, but things were quite out of date.
Could you look at the updated branch and make sure everything still works? It would be great to have better rover support in PX4.
https://github.com/PX4/Firmware/compare/anbriel-GroundFirmware?expand=1

**Comment by dagar** [comment]
@anbriel please create a new pull request on top of PX4 master if you're still interested in this.

**Pull request closed without merging**
