### PR TITLE
Drivers switch most DEVICE_DEBUG -> PX4_DEBUG

### PR DESCRIPTION
**Pull request by dagar**
DEVICE_DEBUG is a macro in the Device base class that prints error messages when the _debug_enabled flag is set.

PX4_DEBUG is a debug message that prints if the `DEBUG_BUILD` define is set, otherwise it's omitted from the build entirely.

This PR switches the majority of DEVICE_DEBUG usage to PX4_DEBUG. I've only kept DEVICE_DEBUG in the I2C and SPI classes to help with debugging issues with new drivers.

This saves 3.8 kB of flash on px4fmu-v2 and 4.6 kB on px4fmu-v4.

### CODE REVIEW

**Comment by dagar** [comment]
It still is per device/driver/module. You set `-DDEBUG_BUILD` in the COMPILE_FLAGS for the module you're currently working on. If you need to see I2C/SPI debug messages then also set `_debug_enabled = true`.

Example: mpu6000
https://github.com/PX4/Firmware/blob/master/src/drivers/imu/mpu6000/CMakeLists.txt#L37

**Comment by davids5** [comment]
I can see that that is true but is it now different? I we do a top level -DDEBUG_BUILD we now effect all drivers (real time). I do not think that is the same granularity.

**Comment by dagar** [comment]
I believe in practice it's close to the same level of granularity. 

Previously you'd set _debug_enabled per CDev to see DEVICE_DEBUG both in the driver itself and I2C or SPI debug messages.

Now you'd set it in the driver compilation (or per compilation unit) and print those same debug messages. If you need the internal I2C or SPI messages then you still set _debug_enabled.

Does that accomplish the same goal or can you think of an example where it's a problem?

**Comment by davids5** [comment]
Having a regular boot with just the one driver is in practice the same.  But I am saying is that the debug output from PX4_DEBUG enabled on the total build* will now include all the drivers. That was per driver before and a good dividing line. 

* Assuming it can be built and fit.

I would rather see PX4_DEBUG be PX4_DRIVER_DEBUG in the drivers and be able to throttle the output with -DPX4_DRIVER_DEBUG in a driver. 

As a side note, one thing to consider is that we can not call printf in an ISR. I would hate to have to debug a problem and spend wasted time on finding some other code using a PX4_DEBUG in an ISR thread that is not the problem in a driver we are trying to debug.

**Comment by dagar** [comment]
I really don't think anyone is using system wide DEBUG_BUILD, but if they were I think printing all debug messages is a feature.

The ISR comment is concerning, we can use this PR as an excuse to review if any of the DEVICE_DEBUG messages were possibly in ISRs.

**Comment by bkueng** [comment]
> I really don't think anyone is using system wide DEBUG_BUILD, but if they were I think printing all debug messages is a feature.

I tried that once but the system becomes totally unusable, even for SITL.

The proposed solution here makes sense, and keeping the ability to selectively enable base-class output per-device is important.
Maybe we can simplify it a bit more for development by adding something like:
```
#ifdef DEBUG_BUILD
_debug_enabled = true;
#endif
```

**Pull request closed without merging**
