### PR TITLE
soft iron magnetometer calibration

### PR DESCRIPTION
**Pull request by FabienGriffon**
Hi, here's my first contribution to the project...

I couldn't find a way to do a soft iron calibration on the magnetometer measurements, so here is one way to do it.
Applying a diagonal matrix is the same as rescaling... I don't know if I should keep the two possibilities or only apply the matrix.

Tested on my PX4... apparently works fine.

### CODE REVIEW

**Comment by FabienGriffon** [comment]
@LorenzMeier I tested it on 2 different PX4 FMU, with no issue until now. My last verifications show that calibration is still good after a few month. Needs further testing by others...

@kdaij I will add a display of the rotation of the axis in the Scipab program...

Raw data is an exampte for the scilab code... I added it for testing, but I can remove it if you don't think it should be here.

And for the recquired procedure for calibration, you need to record magnetometer measurements while you rotate the board, in order to get enough points to map the ellipsoid and take noise into account (250-500 pts ). This could be done using QGC...
Avoid using more than 1000 pts, or the computing time would be too long... especially with not-too-powerful computers.
The record file should contain only magnetometer values, in a text spreadsheet layout, in order to be read by the current program.
Once you have a good set of points, run the scilab program,which will compute the calibration matrix (I will also add a proper display of the values in the Scilab code...)
Finally enter the matrix coefficients manually in the PX4.

**Comment by LorenzMeier** [comment]
@FabienGriffon The functionality is welcome, but it does break our user-calibration. So for this to go into master, we would need to find a way to do it on-device. I appreciate the work, but we try to pull only functionality in mainline that is usable for a majority of our users - which requires a robust calibration routine and docs.

**Comment by FabienGriffon** [comment]
@LorenzMeier I understand you don't want to include scilab code, but I think we should replace simple scaling by the calibration matrix anyway : it would allow advanced users to do a better calibration of their PX4 without changing anything for the others, and it can be easily done... Also it could be used later!

I think it is possible to program the same routine in c++, but I'm not familiar with advanced mathematics libraries, which would allow to fit the Matrix
By the way you say you want to do it on-device, but couldn't it be done using QGC?

**Comment by LorenzMeier** [comment]
Are you solving a linear system similar to this one, or are you doing a more complex fit?
https://github.com/PX4/Firmware/blob/master/src/modules/commander/accelerometer_calibration.cpp#L643-L700

I presume from the SciLab code that its slightly more complex. Do you have any quantitative comparison of the result? Could you please do a wiki page on http://px4.io on how to perform the calibration? I think with that context we could merge this in as a high-end calibration option.

**Comment by FabienGriffon** [comment]
It's definitely a more complex fit... I think it's a recursive fit using more complex methods (maybe gradient descent or similar), but I don't have many informations about it...

 For quantitative comparison, the program computes several variances (without calibration, with Offset, with Scaling, and with Matrix), and the difference in angle between the original and calibrated frame axis.

I'll write a wiki page about calibration... Could you just create the new page or tell me how to do it?

**Pull request closed without merging**
