### PR TITLE
uORB split uORBDevices into uORBDeviceNode and uORBDeviceMaster

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Can you provide additional rationale / context? Looking forward to more cleanup!

**Comment by dagar** [comment]
It's a lot easier to navigate and find things when it's organized with each translation unit containing a single class and naming that corresponds with the contents.

**Comment by LorenzMeier** [comment]
Needs a rebase.

**Comment by dagar** [comment]
Rebased on master.

**Pull request merged**
