### PR TITLE
Standardize filename capitalization and extensions in the commander module

### PR DESCRIPTION
**Pull request by mcsauder**
Hi,

This PR standardizes filename capitalizations and file extensions in the commander module by renaming PreflightCheck.cpp/hpp and Commander.hpp files:
 
`PreflightCheck.cpp -> preflightCheck.cpp`
`PreflightCheck.hpp -> preflightCheck.h`
`Commander.hpp    -> commander.h`

Let me know if you have any questions on this PR or if I have missed the background rationale on why these files deviated from the typical naming convention in this module.

Thanks!

-Mark

### CODE REVIEW

**Comment by dagar** [comment]
This is one of those things where we probably need basic guidelines, otherwise we get bombarded with personal opinions.

Here's mine...
 - .h for C header files
 - .hpp for C++

Beyond that I like to keep the filename the same as the class, but I could go either way if we had consistency across the code base.

**Comment by mcsauder** [comment]
Thanks @dagar, 

Agreed on the opinion sentiment.  I hope not to inject an opinion on this PR, just make these files look like the other files in this module.  If the preference is to leave these files as-is, no problem, just let me know!

Thanks again.

-Mark

**Comment by mcsauder** [comment]
@LorenzMeier,  I apologize for bothering you... What standard would you like to see implemented?

**Comment by mcsauder** [comment]
Hi @LorenzMeier , 

To answer your question, renaming these 3 files makes them match the other 31 files in that directory for naming convention.  Please feel free to decline this PR, I honestly understand that th!ere is no functional impact by this change.

Thanks for your time and consideration!

-Mark

**Comment by mcsauder** [comment]
@dagar , @hamishwillee , and @LorenzMeier , I have changed my opinion and think now that Commander.h, PreflightCheck.cpp, and PreflightCheck.h should be capitalized, based on the detail that they each contain a class of the same name.  None of the other files contain classes, so this convention seems appropriate.  In keeping with @dagar's comment and that new observation, I will close this PR and submit a new PR instead to capitalize commander.cpp to Commander.cpp to reflect the same name/capitalization as the class it contains.

Hopefully this seems reasonable?  Thanks for your feedback!

-Mark

**Pull request closed without merging**
