### PR TITLE
fmuk66-v3:Add Ethernet Support

### PR DESCRIPTION
**Pull request by davids5**
see https://github.com/PX4/NuttX/pull/69
@julianoes , @dagar as discussed on the dev call this can come in after the release.

FYI @mrpollo

### CODE REVIEW

**Comment by davids5** [comment]
@PetervdPerk-NXP I made style changes to the patches you sent and up streamed them here  in thie PR https://bitbucket.org/nuttx/nuttx/pull-requests/1064/nxp-k66-ethernet/diff  I also moved the pin definitions where thy belong in board.h .

Thank you for getting this in! Please test this branch. as it is tied to the back port PX4/NuttX#69

**Comment by PetervdPerk-NXP** [comment]
I've successfully compiled your branch and tested it on my fmuk66.

```
mendel@orange-kid:~$ telnet 10.0.0.2
Trying 10.0.0.2...
Connected to 10.0.0.2.
Escape character is '^]'.

NuttShell (NSH)
nsh> ifconfig
eth0    Link encap:Ethernet HWaddr 00:e0:de:ad:be:ef at UP
        inet addr:10.0.0.2 DRaddr:10.0.0.1 Mask:255.255.255.0

nsh> ping 10.0.0.5
PING 10.0.0.5 56 bytes of data
56 bytes from 10.0.0.5: icmp_seq=0 time=1 ms
56 bytes from 10.0.0.5: icmp_seq=1 time=1 ms
56 bytes from 10.0.0.5: icmp_seq=2 time=1 ms
56 bytes from 10.0.0.5: icmp_seq=3 time=1 ms
```

**Comment by davids5** [comment]
@dagar @julianoes - let's bring it in.

**Comment by mrpollo** [comment]
Great work thanks for supporting the NXP team @davids5

**Comment by mrpollo** [comment]
@PX4/testflights Please help test, a basic set of test cards will be sufficient.

**Comment by jorge789** [comment]
### Tested on NXP_FMUK66_V3:

**Flight Card 1**

**Modes Tested:**
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.

**Procedure:**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode.
**Notes:**
No issues were noted, good flight in general.

**Logs:**  https://review.px4.io/plot_app?log=c208c02b-63a4-4c68-8a65-e66c8ed90db4

**Flight Card 2**

**Modes Tested**
Mission Plan Mode (Automated): Good.
RTL (Return To Land): 

**Procedure**

Armed form QGC.
Took-off on mission plan mode
. Note that commands were sent form QGC (Armed and takeoff)
Once all waypoint completed vehicle switched to RTL and landed as expected.

**Logs:**  https://review.px4.io/plot_app?log=07ea150e-4991-41c2-a20f-c410afcab0e3
**Note:**  **When the vehicle was landing, it did not descend horizontally, it started to get off, but it went with the wind, it hit the ground but it did not want to turn off engines and they kept turning and with the wind the vehicle flip** **wind 7.0m/s**

**Log:**  https://review.px4.io/plot_app?log=08f4b7d1-5aae-42c9-bd93-9400b17c9aff
**Note:**  **When the vehicle was landing, it did not descend horizontally, it started to get off, but it went away with the wind and landed manually in the position but did not disassemble it change to stabilized and disarm** **wind 7.0m/s**

**Comment by mrpollo** [comment]
@davids5 please rebase and merge

**Comment by davids5** [comment]
@mrpollo rebased @dagar - if CI is happy please merge

**Comment by dk7xe** [comment]
@LorenzMeier thanx for merging.

**Pull request merged**
