### PR TITLE
Add camera models for VTOL models for sitl

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Describe problem solved by this pull request**
This is a follow up of https://github.com/PX4/sitl_gazebo/pull/360 which adds a sitl models for VTOLS that have camera attached in order to simulate survey missions.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Some developers will not have the CPU performance to run this - have we tested the impact?

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier I didn't add the camera to the existing vtol models, but created additional models for that reason.

I will do a quick test on how much CPU load is required, but on my laptop it wasn't so bad.

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim HOw are these used? Specifically, I assume these allow you to stream video and take images from gazebo. 

Looking at existing docs - what of the following is true?: http://dev.px4.io/master/en/simulation/gazebo.html#video-streaming

**Comment by LorenzMeier** [comment]
I don't see an update of the SITL submodule - how did the new models come in?

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier There was a discussion in https://github.com/PX4/sitl_gazebo/pull/360 where the models were redundent and a test regarding surveying would makes sense to get the models in

**Comment by hamishwillee** [comment]
Hi @Jaeyoung-Lim

I assume you'll answer this before you merge:  https://github.com/PX4/Firmware/pull/13214#issuecomment-543360516

IMO a feature that people can't easily discover use might as well not exist.

**Comment by TSC21** [comment]
> Hi @Jaeyoung-Lim
> 
> I assume you'll answer this before you merge: [#13214 (comment)](https://github.com/PX4/Firmware/pull/13214#issuecomment-543360516)
> 
> IMO a feature that people can't easily discover use might as well not exist.

@hamishwillee, @Jaeyoung-Lim and I already decided in an approach to have usage to the models being added: survey mission testing in CI. More to come next.

**Comment by Jaeyoung-Lim** [comment]
Closing as stale

**Pull request closed without merging**
