### PR TITLE
Add MAVSDK tests

### PR DESCRIPTION
**Pull request by LorenzMeier**
Work in progress to add integration tests using MAVSDK.

FYI @Stifael, @dagar  

Currently needs MAVSDK installed system-wide (e.g. `/usr/local/`).

Todo: 
- [x] Integrate into PX4 build
- [x] Add overall timeout checks.
- [x] Add scripting around a test matrix, PX4 build and shutdown
- [x] Add to CI
- [ ] Make sure tests can run in CI, local, as well as in the real world.

Dependencies:

psutil:

```
sudo -H pip3 install psutil
```

Install MAVSDK:
https://github.com/mavlink/MAVSDK

```
git submodule update
mkdir -p build/default        
cd build/default
cmake ../..
make -j4
make install
```

To build:
```
DONT_RUN=1 make px4_sitl gazebo mavsdk_tests
```

To run:
```
test/mavsdk_tests/mavsdk_test_runner.py --speed-factor 20 --iterations 5 --fail-early
```

I'm not done yet with this convenience target - it builds, but it is missing the iris model file generation step.
```
make tests_integration
```

Closes https://github.com/mavlink/MAVSDK/issues/885.

### CODE REVIEW

**Comment by dagar** [comment]
Lockstep simulation depending on `ekf2_timestamps` isn't ideal, but understandable.

**Comment by LorenzMeier** [comment]
Test failure:

https://github.com/PX4/Firmware/commit/c3e4781dd385377a5d546fb8f121799461a347e0/checks?check_suite_id=372803159#step:7:397

```
[10:52:36|Debug] MAVLink: critical: Data link lost (system_impl.cpp:308)
378
[10:52:36|Debug] MAVLink: info: Data link regained (system_impl.cpp:308)
379
[10:52:39|Debug] MAVLink: info: Landing detected (system_impl.cpp:308)
380
[10:52:39|Debug] MAVLink: info: DISARMED by Auto disarm initiated (system_impl.cpp:308)
381
[10:52:39|Debug] MAVLink: critical: Data link lost (system_impl.cpp:308)
382
[10:52:39|Debug] MAVLink: info: Data link regained (system_impl.cpp:308)
383
[10:52:41|Debug] MAVLink: critical: Data link lost (system_impl.cpp:308)
384
[10:52:41|Debug] MAVLink: info: Data link regained (system_impl.cpp:308)
385
[10:52:44|Debug] MAVLink: critical: Data link lost (system_impl.cpp:308)
386
[10:52:44|Debug] MAVLink: info: Data link regained (system_impl.cpp:308)
387
[10:52:52|Debug] MAVLink: critical: Data link lost (system_impl.cpp:308)
388
[10:52:52|Debug] MAVLink: info: Data link regained (system_impl.cpp:308)
389
[10:53:06|Debug] MAVLink: critical: Data link lost (system_impl.cpp:308)
390
[10:53:06|Debug] MAVLink: info: Data link regained (system_impl.cpp:308)
391
[10:53:15|Debug] MAVLink: critical: Data link lost (system_impl.cpp:308)
392
[10:53:15|Debug] MAVLink: info: Data link regained (system_impl.cpp:308)
393
[10:53:19|Debug] MAVLink: critical: Data link lost (system_impl.cpp:308)
394
[10:53:19|Debug] MAVLink: info: Data link regained (system_impl.cpp:308)
395
[10:53:24|Debug] MAVLink: critical: Data link lost (system_impl.cpp:308)
396
[10:53:24|Debug] MAVLink: info: Data link regained (system_impl.cpp:308)
397
Catch will terminate because it needed to throw an exception.
```

**Comment by julianoes** [comment]
@LorenzMeier:
```
etc/init.d-posix/rcS: 194: etc/init.d-posix/rcS: bc: not found
```

That's why there are the timeouts. It's because the timeout params are not adjusted to lockstep.

**Comment by LorenzMeier** [comment]
Thanks! I missed that and I've fixed that here: https://github.com/PX4/Firmware/pull/13772/commits/1f5df3575afa82cd0a3cf0b35036660539fef46e

Let's see what a grind run with 100 iterations does now.

**Comment by LorenzMeier** [comment]
@dagar This is good to go now if it passes.

**Pull request merged**
