### PR TITLE
Mpc pos control manual mapping

### PR DESCRIPTION
**Pull request by Stifael**
This pull request follows the discussion from issue #5815.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Is this flight tested?

**Comment by tumbili** [comment]
@Stifael Sorry for taking so long, quite busy testing at the moment. I'll look at this very soon!

**Comment by tumbili** [comment]
@Stifael This looks good, I think it's ok if we assume that the manual attitude setpoint angles will be constrained to a reasonable range. We will do some flight testing.

**Comment by tumbili** [comment]
@Stifael I'm also going to provide a fix for the "pusher for pitch" code for the standard vtol which suffers the same problem.

**Comment by LorenzMeier** [comment]
@tumbili Any updates on the fix?

**Comment by tumbili** [comment]
@Stifael @LorenzMeier Ah yes, we did flight test this with good results. If you wait until today in the evening I'll also push the vtol pusher assist code change which needs the same fix. This is also tested.

**Comment by LorenzMeier** [comment]
Yes please.

**Pull request merged**
