### PR TITLE
Start frsky_telemetry for PX4FMU_V4PRO

### PR DESCRIPTION
**Pull request by Haukanes**
This starts Frsky telemetry for Pixhawk 3 Pro on TELEM4.

### CODE REVIEW

**Comment by bkueng** [comment]
Is setting `SYS_COMPANION=10` and using TELEM2 not an option for you? I'm fine either way, but existing users using SYS_COMPANION will have to change.

**Comment by Haukanes** [comment]
frsky_telemetry is constantly "scanning" when using TELEM2 on my Pixhawk 3 pro. I have only had success using "frsky_telemetry start -d /dev/ttyS6".

**Comment by bkueng** [comment]
Strange, I think I have a setup with Pixhawk 3 Pro and FrSky telemetry, but I'd have to double-check, if I use TELEM2.
Do you have D-Type or S-Port?

**Comment by Haukanes** [comment]
I'm using S-Port (X8R). I thought it was strange too.

**Comment by bkueng** [comment]
I checked, and I have the same setup as you (Pixhawk Pro with S-Port) on TELEM2, which works fine.
I'm ok with running it on TELEM4 alternatively, but can you change it to this:
```
if param compare SYS_COMPANION 10
then
       # frsky_telemetry is selected to start on the companion UART
else
 	if ver hwcmp PX4FMU_V4 PX4FMU_V4PRO MINDPX_V2
 	then
 		# on Pixhawk 3 Pro, it's the TELEM4 port
 		frsky_telemetry start -d /dev/ttyS6
 	fi
fi
```

**Comment by Haukanes** [comment]
I agree on the added logic. Do you know why frsky_telemetry is started by default on PX4FMU_V4 and MINDPX_V2, as it is now?

**Comment by bkueng** [comment]
PX4FMU_V4 (aka Pixracer) has a separate FrSky port, specifically for that purpose. I believe it's the same for mindpx.

**Comment by bkueng** [comment]
Thanks, I cherry-picked this on master.

**Pull request closed without merging**
