### PR TITLE
Improve preflight check reporting

### LINKED ISSUE #4695: master: uninformative error message "Not ready to fly: Sensors not set up correctly"
QGC shows all sensors "green". There is no hint as to the cause of the problem.

### PR DESCRIPTION
**Pull request by julianoes**
This should enhance the reporting for preflight check failures and resolve #4695. 

Bench tested on Pixhawk.

### CODE REVIEW

**Comment by bkueng** [comment]
Nice work, looks good

**Comment by kd0aij** [comment]
was it the missing arg to preflightCheck() that prevented reporting errors?

**Comment by mhkabir** [comment]
@Aperture-Laboratories Can you quickly check if this gives better insight on the CAN compass issue?

**Comment by julianoes** [comment]
> was it the missing arg to preflightCheck() that prevented reporting errors?

Presumably, but that alone wasn't enough because consecutive `mavlink_log()` got swallowed as well. This is now fixed as the orb queue is used.

**Comment by LorenzMeier** [comment]
Nice! Have you compared free RAM (```free```) before and after?

**Comment by Aperture-Laboratories** [comment]
@mhkabir Didn't see any issue with calibration on the GNSSv2 with this fix in today's master

**Comment by julianoes** [comment]
@LorenzMeier:

master:
```
             total       used       free    largest
Mem:        236096     196128      39968      34176
```

fix_preflight_verbose:
```
             total       used       free    largest
Mem:        236096     196336      39760      33408
```

**Comment by LorenzMeier** [comment]
Ok, that's what I expected. Please feel free to go ahead and merge.

**Comment by julianoes** [comment]
Rebased and applied.

**Comment by Pedro-Roque** [comment]
@LorenzMeier @julianoes , so the problem is solved on latest release to Master? What was the source of the problem?

**Comment by julianoes** [comment]
@Pedro-Roque: we're tracking your issue in #4695.

**Pull request closed without merging**
