### PR TITLE
EKF2: Improvements to use of non-GPS aiding sources

### PR DESCRIPTION
**Pull request by priseborough**
Requires https://github.com/PX4/ecl/pull/339 to be merged first.

Adds the following capabilities:

1) When navigation is totally reliant on optical flow data, vehicle ground speed is limited in position control modes to respect flow sensor limits.

2) When navigation is totally reliant on optical flow data and the vehicle is in a manual height control mode, the vertical position and velocity set-point is biased if the vehicle is below the flow sensor minimum focal distance to discourage continuous operation below the sensors minimum effective height.

3) Allows for simultaneous use of  intermittent GPS and optical flow provided one or both are working at the same time.

4) Loss of GPS logic in the EKF has been improved so that provided both sideslip and airspeed fusion are active, the EKF can continue to navigate after total loss of GPS. The navigator failsafe logic prevents FW auto modes taking advantage of this, but an operator can now select altitude mode following total GPS loss and fly back to the recovery area using the GCS map and AHRS displays if required.

### CODE REVIEW

**Comment by priseborough** [comment]
replaced by https://github.com/PX4/Firmware/pull/8223

**Comment by ChristophTobler** [comment]
@priseborough Any reason this has been closed? Or is it just because nothing happened?

**Comment by priseborough** [comment]
It was closed by mistake. I will rebase and retest today.

**Comment by priseborough** [comment]
Correction - it was replaced by https://github.com/PX4/Firmware/pull/8223

**Pull request closed without merging**
