### PR TITLE
Generic helicopter mixer

### PR DESCRIPTION
**Pull request by bartslinger**
I finally found some time to continue with my helicopter project. This is the first step, a generic helicopter mixer. This was necessary in order to program throttle- and pitch-curves. I also added an easy interface for swash plate mixing. By providing the angle and arm-length of the swash plate servo's, the mixer automatically calculates the required deflections. I tested this on a Blade 130x helicopter.

Usage:
```
H: <swash plate servo count>
T: <0> <2500> <5000> <7500> <10000>
P: <-10000> <-5000> <0> <5000> <10000>
```
T is the throttle curve. P is the pitch curve.
The definition continues with <swash plate servo count> entries describing
the position of the servo, in the following form:
`  S: <angle (deg)> <normalized arm length> <scale> <offset> <lower limit> <upper limit>`

[demo video](http://www.youtube.com/watch?v=6mi31_99Irs "Video Title")

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice! Most likely need a code style run.

**Comment by kd0aij** [comment]
@bartslinger Thanks, looks like this is 99% of what I'll need for my variable pitch quad. I wasn't sure whether I could use negative thrust in the quad mixer, or would need a new mixer allowing for negative pitch. Are you doing any inverted flight yet?

**Comment by LorenzMeier** [comment]
@bartslinger Flash overflow, which means you added just enough to fill the micro controller. I need to check what we can do about that.

**Comment by kd0aij** [comment]
:) guess that means the answer to my question is no

**Comment by bartslinger** [comment]
@kd0aij I don't think this is suitable for quads. Why can't you use the simple mixer for that?

@LorenzMeier Had to happen sooner or later, but unfortunate timing for me :-p

**Comment by kd0aij** [comment]
@bartslinger The quad mixer doesn't know about collective pitch

**Comment by LorenzMeier** [comment]
I've rebased and continued this here: https://github.com/PX4/Firmware/pull/5617

**Pull request closed without merging**
