### PR TITLE
MPU9250 add support for internal AK8963 magnetometer

### PR DESCRIPTION
**Pull request by Inspirati**
re-submitting PR after fixing up formatting & whitespace with AStyle

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice, thanks!

**Comment by LorenzMeier** [comment]
Thanks, rebased! I reviewed the changes, one thing that I fixed is that your editor does mode changes from 644 to 755. It would be great if you could teach it to not mess up the permissions.

**Comment by Inspirati** [comment]
ah yes, I noticed the permissions changing problem as I was preparing my PR, and fixed up the one instance which I saw. I've just tested pico & pluma, and presume it's definitely not Qt-Creator doing it, otherwise all files would have been affected. I was using ExamDiff-Pro under Wine during my earlier work, but have since adopted Meld, so if it was the culprit, the problem will have gone away. Are there any other well known mechanisms for this happening without my realising it?

**Comment by Inspirati** [comment]
It could also be a poorly configured Samba service, since I occasionally may have edited a few files via my Windows box - I occasionally have a rather weird workflow..

**Comment by LorenzMeier** [comment]
Samba sounds like the most likely culprit.

**Pull request closed without merging**
