### PR TITLE
add Safety switch handling to fmuv4

### PR DESCRIPTION
**Pull request by kd0aij**
this uses logic on the fmu thread instead of scheduling hrt_timer events

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Should we add something to the 250 config to disable the safety?

**Comment by kd0aij** [comment]
Forgot that... I'll add a check for the circuit breaker.

**Comment by kd0aij** [comment]
I think the safety circuit breaker should default to off, just to be on the safe side.

**Comment by LorenzMeier** [comment]
We need to carefully phase this in. Since it will "break" existing setups. Should have set the circuit breaker in the 250 config *facepalm*.

**Comment by kd0aij** [comment]
True, I didn't even have the safety switch installed on my S250. But the alarm tone would have been a strong clue to what was wrong, even without a GCS.
I can't think of any good way to avoid breaking existing configs without adding yet another parameter.

**Comment by LorenzMeier** [comment]
Superseded by https://github.com/PX4/Firmware/pull/3827

**Pull request closed without merging**
