### PR TITLE
Refactor ulanding driver to utilize ScheduledWorkQueue class inheritance

### PR DESCRIPTION
**Pull request by mcsauder**
**Describe problem solved by the proposed pull request**
This PR refactors the ulanding driver to inherit from the ScheduleWorkQueue class and simplify the collect() method logic to mirror logic in the cm8jl65 driver and the example code provided by Aerotenna (uLanding manufacturer).

**Describe your preferred solution**
Standardizing all of the distance sensor driver variable initialization, method ordering and general style will allow for future inheritance structure work to be performed on the distance sensor driver classes, see  #11977.

**Describe possible alternatives**
The driver could be left as-is, it is functional in PX4:master.

**Additional context**
See #9279, #11853, #11857, #1858, #11859, #11891, #11892, #11893,  #11977

Please let me know if you have any questions on this PR. Thanks!

-Mark

### CODE REVIEW

**Comment by mcsauder** [comment]
@RomanBapst , would you be willing to review this PR for me?  I'm trying to align the distance sensor drivers (slowly) so than an inheritance hierarchy can be created and code duplication reduced.  Thank you in advance!

**Comment by mcsauder** [comment]
Thanks @RomanBapst for looking this over.  I'll ask during the dev call this week to see if I can find anyone with hardware that can test it.  I appreciate your time looking it over, thanks again!

**Comment by bys1123** [comment]
I'll tell ulanding them about this change, see if they have time test on is.

**Comment by mcsauder** [comment]
I finished a larger refactoring of this driver to utilize the ScheduledWorkQueue and have added that commit to this PR.

Here is a screen shot of bench testing with QGC Analyze with PX4:master:
image

Here is a screen shot of this PR:
image

**Pull request merged**
