### PR TITLE
Tecs logging

### PR DESCRIPTION
**Pull request by tumbili**
Cleaned up logging of tecs state.

### CODE REVIEW

**Comment by tumbili** [comment]
@LorenzMeier Can you have a look at the quantities which are logged for tecs now?
Since we are limited in the log size I have logged the energy error quantities instead of the setpoint and the actual value.

**Comment by tumbili** [comment]
Flight tested, log:
 http://dash.oznet.ch/view/4ChvyQdeEWpBwaHErYNEni

**Comment by LorenzMeier** [comment]
Could you provide a list of quantities you want to plot in the new Log muncher log? @SimonWilks Would be great to revamp it once its in.

**Comment by SimonWilks** [comment]
@LorenzMeier sounds good. @tumbili when you are ready we can add some new charts together and we can take the opportunity to cleanup some of the ones already in there.

**Comment by tumbili** [comment]
@SimonWilks Let's discuss this today.

**Comment by LorenzMeier** [comment]
@tumbili @SimonWilks Any chance you could make the changes on log muncher quickly today so we get this over with?

**Comment by LorenzMeier** [comment]
Applied to beta and beta_merge4 (which is going into master), closing. Still needs the log muncher update.

**Pull request closed without merging**
