### PR TITLE
added airspeed to ekf2 replay

### PR DESCRIPTION
**Pull request by CarlOlsson**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@CarlOlsson Is this complete and good to go? Can you attach plots of the replay?

**Comment by CarlOlsson** [comment]
Yes it should work. Will update with plots in a sec

**Comment by CarlOlsson** [comment]
Airspeed innovation

[The log file](http://logs.uaventure.com/view/hbXUjHrcGHQm9Dpuxxcv5d)

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by tumbili** [comment]
Jenkins test this please.

**Comment by CarlOlsson** [comment]
Jenkins test this please.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
