### PR TITLE
Mavlink set last sent timestamp to space out initial publication

### PR DESCRIPTION
**Pull request by dagar**
- remove QURT defines no longer required

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@dagar I wouldn't be so sure yet - this should only be merged after careful testing by @DanielePettenuzzo and @RomanBapst. Sometimes QuRT exposes APIs that are present but not fully functional.

**Comment by dagar** [comment]
These minor mavlink changes save 1.3 kB of flash on fmu-v2.

image

Dropping the QuRT defines was done because my understanding of the platform is that mavlink was running on the linux side. Is this incorrect?

**Comment by LorenzMeier** [comment]
Depends on config. Please don’t drop the define.

**Comment by dagar** [comment]
Does running mavlink without writing anything serve a purpose, or is this a precaution for anyone that might try to run it on qurt?

**Comment by LorenzMeier** [comment]
I just had a pass and looked at it in more detail and I agree that it doesn't quite make sense. @RomanBapst Could you please test this PR on Snapdragon?

**Comment by LorenzMeier** [comment]
@RomanBapst Could you please test on Snapdragon?

**Comment by LorenzMeier** [comment]
@RomanBapst I'm merging this now. Please validate master on the 8074.

**Pull request merged**
