### PR TITLE
mc_att_control conversion to control lib

### PR DESCRIPTION
**Pull request by jgoppert**
This is a simple, concise replacement for mc_att_control, tested in sitl full auto as well as manual flight so far. It uses controllib and matrix and accomplishes the same task in 1/3 of the code. The math model behind it is also more standard and easy to write down. Whatever was going on with the quaternion error formulation and mixing between two different rotation mechanisms seemed like it was overthinking it to me. This just uses euler angles and flies better in my opinion.

### CODE REVIEW

**Comment by jgoppert** [comment]
So the goal here was no functional changes. I think I still have to address the tail sitter logic and a few more vehicle specific items, but in general it is working.

**Comment by jgoppert** [comment]
Log of very aggressive flying with iris to show that this is robust:

http://logs.uaventure.com/view/z9r5SRcjkvJEdZdXc9QSaJ

as_pitch

**Comment by jgoppert** [comment]
I've now copied all the logic for vtol in, so hopefully it will be ready for a test flight.

**Comment by jgoppert** [comment]
So after all of the edge case handling, the code size is about 2/3 of the original, so still a big improvement, and I think it is more readable. In addition the euler angle math is more straight forward.

**Comment by jgoppert** [comment]
The cost of the new code is 3% cpu and 1k memory. I think the increased cpu load is due to the added  low pass filters  and bounds checking on integrators etc. The increased memory may be due to the extra parameters for the derivative low pass filtering.

## New

```bash
Processes: 19 total, 2 running, 17 sleeping
CPU usage: 31.95% tasks, 0.85% sched, 67.20% idle
Uptime: 20.644s total, 13.110s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
   0 Idle Task                   13109 67.199     0/    0   0 (  0)  READY 
   1 hpwork                        676  3.853   916/ 1592 192 (192)  w:sig 
   2 lpwork                         94  0.469   572/ 1592  50 ( 50)  READY 
   3 init                         1321  0.000  1420/ 2496 100 (100)  w:sem 
  87 gps                            34  0.093   740/ 1192 220 (220)  w:sem 
 114 sensors                       541  2.631  1772/ 1992 250 (250)  w:sem 
 116 commander                     128  0.469  3148/ 3592 140 (140)  w:sig 
 117 commander_low_prio              0  0.000   532/ 2992  50 ( 50)  w:sem 
 121 px4io                         627  3.289   956/ 1496 240 (240)  w:sem 
 127 mavlink_if0                   168  0.845  2420/ 2696 100 (100)  READY 
 132 mavlink_rcv_if0                 5  0.000  1140/ 2096 175 (175)  w:sem 
 138 mavlink_if1                   140  0.751  2436/ 2696 100 (100)  READY 
 174 attitude_estimator_q          990  5.639  2196/ 2496 250 (250)  w:sem 
 176 position_estimator_inav       547  3.665  4844/ 5296 250 (250)  w:sem 
 179 mc_att_control                946  5.639  4108/ 4496 250 (250)  w:sem 
 184 mc_pos_control                120  0.751  1124/ 1896 250 (250)  w:sem 
 188 navigator                      98  0.657   836/ 1496 105 (105)  w:sem 
 203 nshterm                         1  0.000   780/ 1496  70 ( 70)  w:sem 
 204 top                           417  3.195  1212/ 1696 100 (100)  RUN   
nsh> free
             total       used       free    largest
Mem:        230880     161872      69008      65488
```

## Old

```bash
Processes: 19 total, 2 running, 17 sleeping
CPU usage: 28.49% tasks, 0.66% sched, 70.85% idle
Uptime: 20.676s total, 13.680s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
   0 Idle Task                   13679 70.849     0/    0   0 (  0)  READY 
   1 hpwork                        658  3.584   956/ 1592 192 (192)  w:sig 
   2 lpwork                         90  0.471   572/ 1592  50 ( 50)  READY 
   3 init                         1324  0.000  1420/ 2496 100 (100)  w:sem 
  87 gps                            35  0.094   732/ 1192 220 (220)  w:sig 
 114 sensors                       547  2.641  1668/ 1992 250 (250)  w:sem 
 116 commander                     127  0.377  3180/ 3592 140 (140)  w:sig 
 117 commander_low_prio              0  0.000   532/ 2992  50 ( 50)  w:sem 
 121 px4io                         642  3.396   964/ 1496 240 (240)  w:sem 
 127 mavlink_if0                   168  0.849  2420/ 2696 100 (100)  READY 
 132 mavlink_rcv_if0                 6  0.000  1048/ 2096 175 (175)  w:sem 
 138 mavlink_if1                   138  0.660  2452/ 2696 100 (100)  READY 
 174 attitude_estimator_q          983  5.660  2172/ 2496 250 (250)  w:sem 
 176 position_estimator_inav       552  3.679  4844/ 5296 250 (250)  w:sem 
 179 mc_att_control                395  2.264  1308/ 1496 250 (250)  w:sem 
 184 mc_pos_control                115  0.754  1236/ 1896 250 (250)  w:sem 
 188 navigator                     112  0.754   780/ 1496 105 (105)  w:sem 
 203 nshterm                         1  0.000   812/ 1496  70 ( 70)  w:sem 
 204 top                           417  3.301  1212/ 1696 100 (100)  RUN   
nsh> free
             total       used       free    largest
Mem:        230880     160640      70240      66816
```

**Comment by tumbili** [comment]
@jgoppert Is this globally stable?

**Comment by tumbili** [comment]
@jgoppert I was also wondering about the current mixing of yaw strategies in the controller and what the benefit of that is.
I would prefer something like this http://e-collection.library.ethz.ch/eserv/eth:7387/eth-7387-01.pdf
This is proven to be globally stable and it comes with test results. Also it incorporates intelligent yaw control, in the sense that it will rotate into the direction which will reduce the yaw error faster (if the vehicle has a hight yaw rate).

**Comment by kd0aij** [comment]
@tumbili Thanks for the link to that paper. It looks like a very good
reference, and should extend to variable pitch quads capable of negative
acceleration.

**Comment by jgoppert** [comment]
@tumbili True, near 90 deg pitch it will have issues. It should be pretty easy to swap out different algorithms and compare in sitl.

**Comment by dagar** [comment]
If you're going to bother bulk renaming params what do you think about making the naming consistent with FW?

**Comment by jgoppert** [comment]
The naming of the sub blocks is automatic using the controllib. We only get to choose the name for the root block.

**Comment by LorenzMeier** [comment]
The param renames will break all setups - could you revert the renaming? Its virtually impossible to phase this in like this for us. It also would probably need to be rebased on master, which will be edgy because we fixed a couple of things in the controller.

When you embark on major architectural work like this it would be beneficial to first sync on the timeline and make sure people are available, because spontaneous rewrites like now are easily subject to bit-rot and hard to get in and frustrating to the proposer.

**Comment by LorenzMeier** [comment]
The conversion makes sense, but the param churn is horrible (it will de-tune all systems of all users). Can we re-do this without changing param names?

**Comment by jgoppert** [comment]
Not worth pursuing at this time. Too much change in param names and math.

**Pull request closed without merging**
