### PR TITLE
Work in Progress Nxphlite-v1

### PR DESCRIPTION
**Pull request by davids5**
This is a WIP for the NXP flight V1 HW based on the K64. It builds but it very memory constrained and incomplete as it is missing key Nuttx support in the Kinetis architecture.

The drivers/kinetis/\* is just stubbed out. There is no HRT or SPI.

Missing Components
- [x]  FPU support in the OS
- [ ] DMA
- [ ] SPI - stubbed kinetis_spibus_initialize(int bus);
- [ ] CAN
- [ ] VBAT - for bootloader app commnincation.
- [ ] Timers PIT, LPTM, and FTM, PDB - for pwm, capture, tones, and hrt.
- [ ] RESET up_systemreset(void) noreturn_function;
  
  Incomplete Drivers:
- [ ] PWM supports only 1 chan per timer.
- [ ] USB
- [ ] UART lacking DMA kinetis_serial_dma_poll(void)
- [ ] TERMIOS for serial
- [ ] RTC - up_rtc_getdatetime

OS/System dependant SW
- [x] Cannot use FPU yet on kinetis
- [ ] Termios
- [ ] tcgetattr
- [ ] tcsetattr
- [ ] cfsetspeed

PX4 FMUV2 Modules removed from build due to No External SPI
- [ ] drivers/bma180
- [ ] drivers/bmi160
  
  NOT Portable YET
- [ ] /Firmware/src/modules/systemlib/mcu_version.c
- [ ] drivers/pwm_input
- [ ] drivers/test_ppm
- [ ] systemcmds/hardfault_log - needs bsram
- [ ] modules/uavcan
- [ ] uavcan
- [ ] uavcan_stm32_driver - need Kinetis CAN driver

PX4 Drivers Needing porting
- [ ] drivers/kinetis/*
- [ ] drv_hrt.c
- [ ] drv_input_capture.c
- [ ] drv_io_timer.c
- [ ] drv_led_pwm.cpp
- [ ] drv_pwm_servo.c
- [ ] drivers/kinetis/adc
- [ ] drivers/kinetis/tone_alarm

### CODE REVIEW

**Comment by LorenzMeier** [comment]
add to whitelist

**Comment by LorenzMeier** [comment]
Jenkins add to whitelist

**Comment by pavel-kirienko** [comment]
> uavcan_stm32_driver - need Kinetis CAN driver

May I ask if you're planning to make it standalone? Might you be interested in inclusion of such driver into the libuavcan upstream? In that case I could probably assist with its design (not with coding though).

**Comment by davids5** [comment]
Hi @pavel-kirienko 

Yes. Yes. I would assume the design is the same as the STM32 - No? I have to allocate resources to get all the work done. If you have BW to add it to UAVCAN - I can test it - when it is ready.

**Comment by pavel-kirienko** [comment]
The design depends on the Kinetis's CAN hardware. I will have a look at the documentation.

**Comment by davids5** [comment]
Thank you!

 

K64 and K66 if it is different.

**Comment by davids5** [comment]
Superceeded by https://github.com/PX4/Firmware/pull/6438

**Pull request closed without merging**
