### PR TITLE
Iris mixer

### PR DESCRIPTION
**Pull request by LorenzMeier**
We never really used the Iris so far and our test vehicles clearly showed that the geometry had not been adjusted for it. This fixes this.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
[nuttx-px4fmu-v3-default.px4.zip](https://github.com/PX4/Firmware/files/659183/nuttx-px4fmu-v3-default.px4.zip)

@PX4TestFlights Please test this binary in manual flight and mission. It should perform a lot better in general.

**Comment by PX4TestFlights** [comment]
I try this out tomorrow, expect logs by 1 pm our time

**Comment by santiago3dr** [comment]
jumps in altitude in altitude mode when throttle is at or close to 50%

log:
http://logs.px4.io/plot_app?log=cd6eb700-7f33-4d0b-8abf-086850a95fe0

video:
https://youtu.be/XVI5F3l3pbw

**Comment by santiago3dr** [comment]
http://logs.px4.io/plot_app?log=b8c848e0-fc75-49fb-8b1e-87bfa25168b5

flight not very stable in altitude and position

**Comment by LorenzMeier** [comment]
Test flight issues were due to bad GPS.

**Pull request merged**
