### PR TITLE
INAV based optical flow integration

### PR DESCRIPTION
**Pull request by LorenzMeier**
@ChristophTobler I've rebased your branch against master and added a proper sim target. You can now launch the sim with:

```
make posix gazebo_iris_opt_flow
```
However, I get this output:
```
WARN  LIDAR timeout
WARN  LIDAR timeout
WARN  LIDAR timeout
WARN  LIDAR timeout
WARN  LIDAR timeout
WARN  LIDAR timeout
WARN  LIDAR timeout
WARN  LIDAR timeout
WARN  LIDAR timeout
```

There is also the open question about the estimator oscillation you had in one of your flights.

- [ ] Work out what the root cause of the estimator oscillation was and/or do some intense testing
- [ ] Work out why SITL prints lidar timeout - maybe my machine is just too slow?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
See my comment above.

**Comment by LorenzMeier** [comment]
@bugobliterator This is the state you will want to work off. The Gazebo sim setup is ready to go.

**Comment by LorenzMeier** [comment]
Flight performance is awesome:

Outdoor:
https://youtu.be/4MEEeTQiWrQ

Indoor:
https://www.youtube.com/watch?v=MtmWYCEEmS8

**Comment by bugobliterator** [comment]
@LorenzMeier I have been using the gazebo sim for opflow, but I see a lot of variation in the image update(300ms-80ms) and it has been making ekf go unstable.

**Comment by LorenzMeier** [comment]
The speed is a bit slow, however, the varying processing time would be typical also on real hardware - this is the price that comes with using Linux. This is something you need to be robust against. You can only get equidistant timing with a sensor like PX4FLOW with a dedicated control loop.

**Comment by ChristophTobler** [comment]
closed in favour of https://github.com/PX4/Firmware/pull/3701

**Pull request closed without merging**
