### PR TITLE
RPi2 bringup

### PR DESCRIPTION
**Pull request by mhkabir**
WIP - Do not merge

This PR adds : 
* Fixes build (https://github.com/PX4/Firmware/issues/4203)
* SCP uploader (use ```make posix_rpi2_default upload```, assuming RPI2 is at ```pi@px4autopilot```)
* DriverFramework now builds (https://github.com/PX4/Firmware/issues/4383)
* Sensor drivers work (MPU9250)
* Build all modules

Still TODO :
- [ ] Add working Navio/ErleBrain config
- [ ] Make hostname/username configurable if required (currently hardcoded to ```pi@px4autopilot```)
- [ ] DriverFramework update RPi2 toolchain and general cleanup
- [ ] Rename compile targets to "cross" and "native"
- [ ] Add more drivers to DF
- [ ] Navio2 drivers
- [ ] ...

### CODE REVIEW

**Comment by mhkabir** [comment]
Anyone trying out this branch -
Please make sure toolchain is installed from https://github.com/pixhawk/rpi_toolchain
And your ```.bashrc``` exports ```RPI_TOOLCHAIN_DIR```. The toolchain installer script (as of today) automatically does it : 

```
export RPI_TOOLCHAIN_DIR=/opt/rpi_toolchain
```

```

**Comment by mhkabir** [comment]
@bo-rc Would you be able to work on the Navio2 drivers now? I've got this side almost setup and ready to go. We still need the core drivers like baro and mag in DriverFramework.

I'm currently working on it, but you would probably be able to do it faster.

**Comment by bo-rc** [comment]
yes sure! My Navio2 is here. I just defended my PHD. I have been busy with
my defense recently but since it is done i will have time for development
now.

Best.
Bo

**Comment by nacho-carnicero** [comment]
Thanks @mhkabir for the fix, I have tried out on a RPi3/Navio2 configuration, it compiles and executes but I get errors when deploying the drivers. I guess it is due to the fact that Navio2 is still not supported. I'd be glad to help in making it work in Navio2, so let me know if I can do something (I'm not a code master, but I'm willing to give my best and I own the hardware so I can try fixes).

Also, this is a more generic question, but what is the benefit of adding the `-Werror` flag for the compiler? I was not able to compile the firmware without disabling it, I guess it is not important, but I want to be sure I'm not harming the behavior of the firmware by doing that.

**Comment by mhkabir** [comment]
It doesn't work yet, since something changed in the Emlid image and that breaks our SPI driver. 

-Werror should prevent it from building if there are any warnings, which usually point out bad code. 

This branch should have all the warning stuff fixed up (if you're running the proper DriverFramework version).  What errors do you get?

**Comment by nacho-carnicero** [comment]
Ok, that was it, I was just using an outdated version of DriverFramework, sorry for that.

As far as the DriverFramework is concerned I am able to run the Imu Test application and get data by removing from the code the following in framework/src/SPIDevObj.cpp:
```
	if (transfer_bytes > 21) {
		DF_LOG_ERR("ERROR: SPI transfer bytes request over limit");
		return -1;
	}
```
I get the data but the test is not passed, since I get more read_counts than read_attempts (maybe a problem of synchronization?). Anyway I get this:
imu_test

I don't know if doing this makes sense, but the values don't seem that bad (except for the temperature).

**Comment by julianoes** [comment]
@nacho-carnicero: I have done changes to the IMU driver and not run the unit test since. Let me look at it.
And the temperature seems reasoable, meaning I have seen values around 40-45 degrees before. I'll verify that the calculation is done correctly though.

**Comment by LorenzMeier** [comment]
@julianoes Do you have an opportunity to re-check this?

**Comment by LorenzMeier** [comment]
Rebased and applied. We will move on with this meanwhile on the Parrot Bebop 2.

**Pull request closed without merging**
