### PR TITLE
modules: dataman: Add a ram_flash backend & Use it in AeroFC

### PR DESCRIPTION
**Pull request by zehortigoza**
This first 2 commits here was sent in a previous PR https://github.com/PX4/Firmware/pull/6720

### CODE REVIEW

**Comment by zehortigoza** [comment]
@lucasdemarchi

**Comment by davids5** [comment]
@zehortigoza - have you timed the erase/writes with a scope? I ask because the CPU is held out of flash (stalls) for the duration of the erase/writes in single bank mode. This was ok for parameter writes as they are done while not in flight.

**Comment by zehortigoza** [comment]
@davids5 I did not notice any CPU held probably because I'm using the second bank and STM32 can read from one bank while erasing or writing from another bank.

Here the erase and write(7860 bytes) times:

* Using a 16KB sector from first bank
  * erase took 22585 usec
  * write took 78585 usec

* Using a 16KB sector from second bank
  * erase took 267382 usec
  * write took 78653 usec

* Using a 128KB sector from second bank

  * erase took 2048991 usec
  * write took 92384 usec

I don't have any 128KB sector from the first bank available to test.

So the operations over the second bank are slower because it can swap to another tasks. Also as the Nuttx is writing half-words at each time it will only have a long block when erasing.

But anyway I think is better add some comment in this backend telling about the CPU held if used on the same bank where instructions is read.

**Comment by davids5** [comment]
@zehortigoza Good - I was thinking this was on a F405 and a not F427.

**Comment by LorenzMeier** [comment]
Great, thanks!

**Comment by davids5** [comment]
@zehortigoza 

Is there a need for a linker file change to exclude the the last sector and also a silicon version check for the FLASH bug?

**Comment by zehortigoza** [comment]
@davids5 On AeroFC we did not added the second memory bank to the linker descriptor file. What Flash bug?

**Comment by davids5** [comment]
Oh I see:

```
* The STM32F405RG has 1024Kb of FLASH beginning at address 0x0800:0000 and
 * 192Kb of SRAM. SRAM is split up into three blocks:
 *
 * 1) 112Kb of SRAM beginning at address 0x2000:0000
 * 2)  16Kb of SRAM beginning at address 0x2001:c000
 * 3)  64Kb of CCM SRAM beginning at address 0x1000:0000
 *
 * When booting from FLASH, FLASH memory is aliased to address 0x0000:0000
 * where the code expects to begin execution by jumping to the entry point in
 * the 0x0800:0000 address range.
 *
 * The first 16 KiB of flash is reserved for the bootloader.
 * Paramater storage will use the next 2 16KiB Sectors.
 */

MEMORY
{
    flash (rx)   : ORIGIN = 0x0800C000, LENGTH = 976K
    sram (rwx)   : ORIGIN = 0x20000000, LENGTH = 128K
    ccsram (rwx) : ORIGIN = 0x10000000, LENGTH = 64K
}
```
Now I know why I thought it was a F405 :) 

You may want to replace it with nuttx-configs/px4fmu-v2/scripts/ld.script with the proper augmentation. 

The Silicon  Errata is documented [here](https://pixhawk.org/help/errata)

If you are not subject to it, you can then have more space but will need to locate the FLASH writer appropriately

**Comment by zehortigoza** [comment]
@davids5 Big thank you, AeroFC is not affect by 'PA12 GPIO limitations' but it is by 'Data cache might be corrupted during Flash read-while-write operation'. I will write a patch for Nuttx with the workarround and only enable it if a macro is defined.

**Comment by zehortigoza** [comment]
@davids5 https://github.com/PX4/Firmware/pull/6747

**Pull request merged**
