### PR TITLE
sdlog2: Log actuator output group 1 as well

### PR DESCRIPTION
**Pull request by LorenzMeier**
@tumbili @julianoes this is so we can log the AUX outputs as well.

### CODE REVIEW

**Comment by julianoes** [comment]
Reviewed, looks correct.

**Comment by LorenzMeier** [comment]
Applied to amster.

**Comment by tubeme** [comment]
Master I suppose...

**Comment by tubeme** [comment]
The Masted did not make the transition on the bench test. Did not woke up the servos nor it did start the FW motor on the VTOL. Despite that I had data in the LOG file catching my movements of the Roll/Pitch stick. I attach an image:
aux logging v1
After this I flashed the 1.1.0 stable, everithing was OK on the bench test with the transition.

**Pull request closed without merging**
