### PR TITLE
Make VTOL weathervane when navigating to vtol_land as MC

### PR DESCRIPTION
**Pull request by sanderux**
vtol_land has the following sequence:
1 navigate to WP as FW
2 transition to MC
3 navigate to WP as MC
4 land

Often when reaching sequence 3 it still has too much velocity, attempting to yaw saturates the actuators. Using weathervane will likely be smoother.

### CODE REVIEW

**Comment by sanderux** [comment]
@AndreasAntener mavros sitl fails on this:
```
(vtol_new_1.txt) took too long to get to position lat: 47.397732, lon: 8.543269, alt: 500.185000, xy off: 5.000000, z off: 5.000000, timeout: 600, index: 0, pos_d: 61.378938, alt_d: 0.002000
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/job/catkin/src/px4/integrationtests/python_src/px4_it/mavros/mission_test.py", line 275, in test_mission
    self.reach_position(waypoint.x_lat, waypoint.y_long, alt, 600, index)
  File "/job/catkin/src/px4/integrationtests/python_src/px4_it/mavros/mission_test.py", line 174, in reach_position
    (self.mission_name, lat, lon, alt, xy_radius, z_radius, timeout, index, self.last_pos_d, self.last_alt_d)))
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
```

Do you know why? seems fine in my sim

**Comment by sanderux** [comment]
@LorenzMeier any chance you could add the label testflights_vtol ?

**Comment by LorenzMeier** [comment]
Jenkins add to whitelist

**Comment by sanderux** [comment]
Confirmed, massive improvement; http://logs.uaventure.com/view/QDSHGWMB9RAm3QiCvsrJ3Z#Actuators_PLOT

@LorenzMeier please merge

**Comment by AndreasAntener** [comment]
@sanderux You might need to rebase since the mission item struct changed considerably :(

**Comment by sanderux** [comment]
@andreasantener i rebased, can you review and merge?

**Comment by AndreasAntener** [comment]
Yup

**Comment by AndreasAntener** [comment]
Merged to master

**Pull request closed without merging**
