### PR TITLE
DO NOT MERGE WIP - fmuv5 px4io

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier - here are the #fidefed stubs. The F7 USART needs to be split out (I a think proper class is needed fir F4, F7) #ifdefs will work short term (read hack)

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@laube Could you have a look at this and see how much effort it would be to complete the port of that driver?

**Comment by laube** [comment]
What I am seeing here is the interface over serial to the PX4 IO which is an external microcontroller.

It exposes a register based interface which can be accessed over a file-like interface.

The code here directly accesses the DMA and STM32F4 serial peripherals without using one of the serial drivers from [NuttX core](https://github.com/PX4-NuttX/nuttx/blob/e89edd67848c4939021286ed2bd1fc5adb6cbc39/arch/arm/src/stm32f7/stm32_serial.c).

Is there a reason why this is done like this?

Could it be changed (mainly the `_wait_complete()` function) to use the serial driver from NuttX?

If not, I can spend some more time looking at any upgrade from F4 to F7 documents and see what needs to change. (Or make a diff of the NuttX serial drivers)

**Comment by LorenzMeier** [comment]
We need a quick solution. If using the NuttX driver layer is the right solution for that then that's an option, but my preference would be to port the F4 driver to the F7 as that's a much more self-contained change.

**Comment by LorenzMeier** [comment]
@davids5 @laube Could you schedule a bilateral call early this week and agree on a strategy how the three of us can get this finished the fastest possible? Now that the NXPHite had its first flight and this is still unresolved its becoming the first priority.

**Comment by laube** [comment]
@LorenzMeier Since I do not have hardware to test this, I will go through the code and make it ready without it. In the mean time, where can I pick up a board?

@davids5 Let's setup a call asap, I am available during business hours (Central European Time) this week.

**Comment by davids5** [comment]
@laube my skype name is david_s5.

**Comment by dagar** [comment]
@laube I might have some suggestions for how to structure this in PX4 NuttX. We need to break things down by platform and architecture. Feel free to ping me on slack (@dagar) or skype (dagar86) if you'd like to discuss.

**Comment by laube** [comment]
@dagar @davids5 @LorenzMeier 

I made it work on this pull-request:

https://github.com/PX4/Firmware/pull/8629

- Tests on the other 3 boards have not been done yet:
  - [ ] auav-x21
  - [ ] px4fmu-v2
  - [ ] px4fmu-v4pro
- There were some cache coherency issues that I needed to address. Thats what the arch_flush_dcache and arch_invalidate_dcache calls are for.

**Comment by davids5** [comment]
Since we're in right through mode the problem is simpler. Alignment on a 32 x boundaries is essential though

On January 8, 2018 8:23:29 AM HST, Simon Laube <notifications@github.com> wrote:
>@dagar @davids5 @LorenzMeier 
>
>I made it work on this pull-request:
>
>https://github.com/PX4/Firmware/pull/8629
>
>- Tests on the other 3 boards have not been done yet:
>  - [ ] auav-x21
>  - [ ] px4fmu-v2
>  - [ ] px4fmu-v4pro
>- There were some cache coherency issues that I needed to address.
>Thats what the arch_flush_dcache and arch_invalidate_dcache calls are
>for.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/PX4/Firmware/pull/8490#issuecomment-356050522

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by laube** [comment]
Ok, the alignment issue is not addressed with the current _io_buffer variable setup. I will change the code like this:
- Move the _io_buffer variable into the arch dependent module so we can deal with the details
- Change it for the F7 code to be carved out of a buffer that is <cache-line-size>(32) bytes larger than sizeof(IOPacket) and align it.
- Check that it is safe to call the arch_flush_dcache functions without aligning the end to cache lines.

In addition, care must be taken that the invalidate cache function cannot invalidate memory of other adjacent variables. Maybe the static buffer needs to be increased even further to ensure this.

**Comment by LorenzMeier** [comment]
Awesome! Cross-testing the PR just now.

**Comment by LorenzMeier** [comment]
Closing as duplicate.

**Pull request closed without merging**
