### PR TITLE
Update submodule ecl to latest Wed Oct 17 13:54:47 UTC 2018

### PR DESCRIPTION
**Pull request by dagar**
- ecl in PX4/Firmware (771d451d353ba53b7750bd7ae7a88cb249d0be2d): https://github.com/PX4/ecl/commit/f240eaa5b089c50b957a3ab61aeb722ea57dccd9
    - ecl current upstream: https://github.com/PX4/ecl/commit/e6cd6eff87de5822abb02cb750a62f30815bdec7
    - Changes: https://github.com/PX4/ecl/compare/f240eaa5b089c50b957a3ab61aeb722ea57dccd9...e6cd6eff87de5822abb02cb750a62f30815bdec7

e6cd6ef 2018-09-03 Paul Riseborough - EKF: Fix bug preventing  use of flow sensors without gyros
2c3a064 2018-09-18 Daniel Agar - README.md update Jenkins build status icon and url

### CODE REVIEW

**Comment by dagar** [comment]
@priseborough does the EKF fix (bug preventing use of flow sensors without gyros) need additional testing firmware side?

**Comment by Tony3dr** [comment]
@dagar we don't have any optical flow hardware.

**Comment by Avysuarez** [comment]
@dagar I have one of px4flow

**Comment by priseborough** [comment]
We do need regular testing using crazyflie and PX4Flow hardware. At the moment I am relying on users reporting problems, but in many cases they have bad hardware setups, so testing using a reference hardware setup would be useful.

**Comment by mrpollo** [comment]
@dagar looks like we need a new vehicle, can you please work with @Tony3dr on requirements? do we need a new flight card?

Thanks for the note @priseborough.

**Pull request merged**
