### PR TITLE
Use ecl library version with recent bug fixes and enhancements.

### PR DESCRIPTION
**Pull request by priseborough**
Bug Fixes:

https://github.com/PX4/ecl/pull/586 - EKF: fix covariance and output filter buffer initialization
https://github.com/PX4/ecl/pull/590 - EKF: Fix innovation in fuseDeclination()

Enhancements:

https://github.com/PX4/ecl/pull/543 - ekf_helper: add more useful methods to interface with the covariances
https://github.com/PX4/ecl/pull/588 - Add unit tests for DataValidator

### CODE REVIEW

**Comment by dagar** [comment]
Additional testing required?

**Comment by priseborough** [comment]
Reversion testing with FW and MC platforms is recommended. Individual bugfix changes have been tested, but not flown as a complete package.

**Comment by priseborough** [comment]
Build is failing - will investigate and fix.

**Comment by TSC21** [comment]
@priseborough we seem to have some trouble regarding https://github.com/PX4/Firmware/pull/11092 - which brings usage to PX4/ecl#543.

**Comment by priseborough** [comment]
@TSC21 I will add the minimum changes to ekf2_main to handle the revised access to the state variances.

**Comment by priseborough** [comment]
@dagar and @tstellanova, https://github.com/PX4/ecl/pull/588 appears to be causing the CI SITL ecl data validation tests to fail.

**Comment by priseborough** [comment]
Short flight on a multi-rotor (pixhawk cube) showed no issues with estimator performance or CPU load:

CPU Load:
Screen Shot 2019-03-13 at 10 35 22 am

Estimator time slip:
Screen Shot 2019-03-13 at 10 24 31 am


Magnetomer:
Screen Shot 2019-03-13 at 10 24 31 am

GPs velocity:
Screen Shot 2019-03-13 at 10 25 04 am

GPS Position:
Screen Shot 2019-03-13 at 10 25 52 am

Baro:
Screen Shot 2019-03-13 at 10 26 32 am

Quaternion variances:
Screen Shot 2019-03-13 at 10 28 01 am

Quaternion Reset Count:
Screen Shot 2019-03-13 at 10 29 02 am

**Comment by dagar** [comment]
Should be fixed now.

**Comment by jorge789** [comment]
Tested on Pixracer v4;
Armed, tested in position, then changed to Altitude and a few seconds made a fliped and collapsed.

https://review.px4.io/plot_app?log=2ff0d9b0-58c5-4e2d-9993-2883e2d1fe7f

**Comment by Junkim3DR** [comment]
Tested on Pixhawk 4 v5; no issues were noted, good flight in general.
https://review.px4.io/plot_app?log=e0b0dbb2-c743-445e-a1fc-e17bc89c3d42
Master was tested as well; no noticeable differences.
https://review.px4.io/plot_app?log=c3e08940-4078-466e-aff1-853e28aad108

Tested on Pixhawk 4mini v5; no issues were noted, good flight in general.
https://review.px4.io/plot_app?log=dc3b8978-3879-4e5c-9f76-f059558fa7e7
Master was tested as well; no noticeable differences.
https://review.px4.io/plot_app?log=a6268987-ab5c-4d87-8bbf-e503b30964f1

**Comment by jorge789** [comment]
Tested on Pixhawk cube v2;
It was tested in all modes Position, Altitude, Stabilized, Mission and RTL and it works very well in all modes.

https://review.px4.io/plot_app?log=27081981-026b-4c64-804a-cbad637f821e

**Comment by LorenzMeier** [comment]
@priseborough Sound like issues persist here.

**Comment by priseborough** [comment]
@jorge789 Your crash had nothing to do with the estimator. Innovations were within limits throughout.

**Comment by dagar** [comment]
> Tested on Pixracer v4;
> 
> * Armed.
> * Takeoff on position mode and flew as expected.
> * Switched to altitude mode, a few seconds later vehicle made flipped and collapsed.
> 
> https://review.px4.io/plot_app?log=2ff0d9b0-58c5-4e2d-9993-2883e2d1fe7f

I'm not seeing an obvious issue in this log. Did your battery die? Is your power module (current/voltage sensor) calibrated? https://docs.px4.io/en/config/battery.html

https://review.px4.io/plot_app?log=2ff0d9b0-58c5-4e2d-9993-2883e2d1fe7f#Nav-Power

image

**Pull request merged**
