### PR TITLE
deprecate gumstix aerocore - no longer supported by mfg

### PR DESCRIPTION
**Pull request by davids5**

### CODE REVIEW

**Comment by davids5** [comment]
@hamishwillee - FYI

**Comment by hamishwillee** [comment]
@davids5 Thanks. Can you also remove this out of the [README](https://github.com/PX4/Firmware/blob/master/README.md) - this is the only place I know that it is mentioned.

**Comment by davids5** [comment]
@hamishwillee was there somthing more than https://github.com/PX4/Firmware/pull/11446/files#diff-04c6e90faac2675aa89e2176d2eec7d8 you wanted doen?

**Comment by hamishwillee** [comment]
@davids5 No - sorry, missed that fix. It is all done. Thanks

**Pull request merged**
