### PR TITLE
Auto logic refactor

### PR DESCRIPTION
**Pull request by Stifael**
* removes scaling 
* removes slewrate for auto
* fixes overshoots in xy and z
* moves z foh to mc_pos_control

This auto logic is just temporary and will be moved to flight-task as a first step. 
As a second step an auto logic is added to flight-task which uses splines to generate smooth trajectories.

### CODE REVIEW

**Comment by Stifael** [comment]
I tested mission with speed of 10m/s with different altitudes, surveys, reposition and altitude changes. In all scenarios, the overshoot is gone.

**Comment by TSC21** [comment]
@Stifael this seems to add a substantial change to the controllers. Are you able to give us an overview of the performance before vs after this PR with some flight logs?

> This auto logic is just temporary and will be moved to flight-task as a first step.
As a second step an auto logic is added to flight-task which uses splines to generate smooth trajectories.

Can you explain how you plan to structure this features in terms of navigator logic and controller modifications? Are those changes supposed to supersede this PR? If yes, why not structure a PR or two with the logic already implemented?

**Comment by Stifael** [comment]
1. 
I will collect some logs. It basically fixes everything related to slewrate and makes transition between waypoints less wobbly, more predictable.

2.
This PR is a replacement for the current logic, not an addition. The splined version will be an addition. 
The goal structure is given here:
https://github.com/PX4/Firmware/issues/7318

**Comment by LorenzMeier** [comment]
@PX4TestFlights Please give this some solid, intense testing.

**Comment by LorenzMeier** [comment]
@Stifael I've rebased this on master.

**Comment by Avysuarez** [comment]
flight with pixhawk 1 V2, good flight no issues;
https://review.px4.io/plot_app?log=9936d87a-f88c-4bc3-af2c-c89209ecb1d5

flight with pixhawk mini V3, good flight no issues;
https://review.px4.io/plot_app?log=e352f0e9-b8ad-437c-8415-b71db8bcbea4

**Comment by santiago3dr** [comment]
few flights with pixracer (v4)
speed set to default of 5 m/s:
https://logs.px4.io/plot_app?log=6ca62f9f-04ab-4333-83d3-1944282eac5c

speed set to 7 m/s:
https://logs.px4.io/plot_app?log=6454c3c8-4b42-4e42-bed3-807922d77c29

speed set to 9 m/s:
https://logs.px4.io/plot_app?log=c43a297d-3a30-4297-af03-5c715eda432d

compared to current master with cruise set to default 5 m/s:
https://logs.px4.io/plot_app?log=dfdc9f01-c674-4874-988f-e2b5d612e598

good flight until setting cruise speed to 9 m/s; 60 turns too aggressive and canceled mission from heavy instability at a corner

**Comment by Stifael** [comment]
@santiago3dr can you repeat the test with 9m/s, but set NAV_ACC_RAD to 1 (that should also be the default for mc, but not sure If I can change it since it is also used by fixedwing). In addition, you can also decrease MPC_CRUISE_90 to 2 (this controls how fast it should pass waypoint corners at 90 degrees and as result of that also effects speed at other angles. But more important is that NAv_ACC_RAD is at 1.

**Comment by santiago3dr** [comment]
another couple flights with pixraer (V4)
set NAV_ACC_RAD to 1 and MPC_CRUISE_90 to 2

setting mpc_xy_cruise to 6 m/s:
https://logs.px4.io/plot_app?log=9b13ccce-d70e-4d80-b401-c8ef8be3f0ed

setting mpc_xy_cruise to 10 m/s:
https://logs.px4.io/plot_app?log=a77a5a84-b81f-4712-b5b5-f519ffd16826

**Pull request merged**
