### PR TITLE
Mag cal robustness

### PR DESCRIPTION
**Pull request by LorenzMeier**
@DonLakeFlyer The image below shows the output from the user-interaction during the calibration. The distribution across the sphere is not optimal, and we might need to revise our approach. The "back-side" of the sphere has no points, only the front side which is displayed. You can make out the three circles resulting from the three rotations.

screen shot 2015-06-24 at 12 23 05

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@tumbili The robustness part has to go into the release. I'm currently also chasing a scaling error still which is not present for the internal mag, but is noticeable on the GPS mag.

**Comment by DonLakeFlyer** [comment]
Maybe change from capturing three circles to capturing six points on the sphere. Or in other words move through all 6 orientations like accel cal, hold and capture a few points in each orientation. Detect that you have point in the right place before moving to the next orientation. This is kind of how APM stack does it.

**Comment by DonLakeFlyer** [comment]
Or: Does cal need to rotate through 6 orientations in order to fill the other side of the sphere?

**Comment by DonLakeFlyer** [comment]
Switching to a 6 orientation style cal would also fix the timeout problem since it would wait until you move to the next pose.

**Comment by LorenzMeier** [comment]
What you want is random traces across th sphere, the six orientations are neither optimal nor very convenient.

Any other good ideas how to get enough data with minimum constraints on the user?

**Comment by LorenzMeier** [comment]
Things are looking much better now with a proper random calibration run and some fixes. Now trying the six-axis approach and how dumb a user can be before it deteriorates.

screen shot 2015-06-25 at 10 48 37

**Comment by LorenzMeier** [comment]
Closing this in favour of the new mag_cal_6 branch / PR.

**Pull request closed without merging**
