### PR TITLE
Hex/Proficnc CubeYellow/CubeOrange: fix default config for IMU heating

### PR DESCRIPTION
**Pull request by mirkix**
This PR solves the issue with ICM20948 zmag noise for the Hex CubeYellow and CubeOrange
Screenshot from 2020-06-22 07-56-33

### CODE REVIEW

**Comment by dagar** [comment]
Actually I think it needs to be turned off ` SENS_EN_THERMAL 0` instead. The PX4 heater control only interacts with heating elements FMU side.

If you're interested it just needs a little bit of plumbing to hook up `drivers/heater` with `drivers/px4io`.

**Comment by dagar** [comment]
I disabled it for now. Let me know if you'd like to discuss px4io heater control.

**Comment by mhkabir** [comment]
Out of curiosity, why does this affect the Z mag?

**Comment by dagar** [comment]
> Out of curiosity, why does this affect the Z mag?

The cube put the heater where the px4io blue LED is/was. If it's not set properly then the heater is pulsing like the light at a few Hz.

**Pull request merged**
