### PR TITLE
FW landing check if prev valid before using

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by ryanjAA** [comment]
Flew this in SITL  - flew fine. Would be better to add a lidar to gazebo plane to test more thoroughly -  will try and get this PR on something in the air when weather permits.

**Comment by dagar** [comment]
If you post the sitl log to logs.px4.io it should be enough to see if it's
working as intended (depending on how the mission was laid out).

**Comment by ryanjAA** [comment]
https://review.px4.io/plot_app?log=5be4054e-95bd-4be3-8eeb-fef7d1f23038
https://review.px4.io/plot_app?log=5ffe3ab7-aabb-4996-94cd-478f96931232

Two different types of landing scenarios. With landing pattern the manual landing (had to add the last waypoint in.

Thing to consider and this is likely QGC not PX4 is how slope is displayed when using landing pattern, not displayed on the top of screen or on the altitude graph on the left. Only on the right hand side where the pattern landing settings are.


screen shot 2018-04-13 at 12 50 30 pm

**Comment by Antiheavy** [comment]
I fly a lot of fixed wing landing patterns.  Can you explain what issue is this fixing?  just curious.  thanks.

**Comment by dagar** [comment]
You could think of this as general fixed wing position controller hardening. This is an edge case you can't normally get into if you plan your landing with the QGC pattern or with certain feasibility checks.

The landing slope logic uses the previous waypoint altitude, but wasn't checking if the previous waypoint was actually a valid position waypoint.

**Pull request merged**
