### PR TITLE
WIP: LPE/lidar/flow with LidarLiteV1 PWM glitch removal

### PR DESCRIPTION
**Pull request by kd0aij**
Lidar-based ALTCTL flight testing of baro sensor with static port
This is a fork of mhkabir:lpe_flow (#3209 ) with additions to support AUAV-X2 
Also see #3239

### CODE REVIEW

**Comment by kd0aij** [comment]
version 0674b3a
lidar_baro

**Comment by mhkabir** [comment]
@kd0aij I made load of changes locally (on lpe_flow) relating to terrain estimation, which separates the ranger measurement as a terrain(surface) distance estimate, and diferentially corrects the global altitude estimate with it. So we can very nicely handle changes surfaces (e.g flying over a table won't cause a sudden jump in altitude now)
I need a day or two to finish it up with SITL testing and stuff.
I also cleaned up your final lidar driver changes, squashed it, and will push to lpe_flow soon. I think then we can return to using my lpe_flow fork verbatim as a testing baseline.

**Comment by kd0aij** [comment]
This is a logic analyzer trace showing "glitches" in the LidarLiteV1 PWM output stream.

llv1_glitches

**Comment by mhkabir** [comment]
@kd0aij @scott-eddy Remember Scott's glitches? Looks like I can reproduce them as well now, even with our fix :P The spikes are much smaller than what it used to be without the glitch protection, but it's still does happen.

**Comment by mhkabir** [comment]
Closing this in favour of #3209

**Pull request closed without merging**
