### PR TITLE
uORB: update msgs fields from camelCase to snake_case

### PR DESCRIPTION
**Pull request by TSC21**
**Describe problem solved by the proposed pull request**
In the process of developing a ROS2 package that will be interfacing PX4 with ROS2 through fast-RTPS, I found out that while trying to building the package with the respective ROS msg generation, `rosidl_generate_interfaces()` does not process msg fields which have uppercase letters.

**Describe your preferred solution**
This is an harmless PR which changes some message fields that have uppercase letters (or present a camelCase naming convention) so `rosidl_generate_interfaces()` is able to generate code for ROS IDL files. It basically replaces the uppercase with lowercase, and where required, change the naming convention to snake_case.

**Describe possible alternatives**
Not really much more we can do about it, unless one changes the copied file online during the build process, which is not really efficient.

### CODE REVIEW

**Comment by TSC21** [comment]
Also, after this gets merged, I think it will make sense to actually have something like a schema validator for uORB msgs, so that we can make sure every new fields that is added follows the same convention (does make much sense to have fields following different naming conventions). This validator would run on CI as a new job, parallel to the style check job for example.
@dagar any thoughts?

**Comment by dagar** [comment]
Anything from the ROS world that already solves this problem?

**Comment by TSC21** [comment]
> Anything from the ROS world that already solves this problem?

No. This is actually a requirement for the message generation through ROS IDL generator python scripts.

**Comment by TSC21** [comment]
Will be issuing a PR against Flight Review so to address these changes as well.

**Comment by TSC21** [comment]
Changes on Flight Review addressed in https://github.com/PX4/flight_review/pull/123.

**Comment by LorenzMeier** [comment]
@TSC21 Can you add a change that breaks the build if someone re-introduces this? Like a check in the Python generator for PX4 uORB messages?

**Comment by TSC21** [comment]
>@TSC21 Can you add a change that breaks the build if someone re-introduces this? Like a check in the Python generator for PX4 uORB messages?

@LorenzMeier that's what I actually was referencing here https://github.com/PX4/Firmware/pull/10077#issuecomment-408704710. @dagar believes that clang-tidy could possibly handle this if we actually generate the headers and then do the check against those. Would that be a better option to a check in the Python generator?

**Comment by TSC21** [comment]
@LorenzMeier done

**Comment by TSC21** [comment]
@LorenzMeier thanks for merging. This does unblock the package development.

**Pull request merged**
