### PR TITLE
vscode updates

### PR DESCRIPTION
**Pull request by dagar**
* working debugging (one click build and debug)
    * SITL jmavsim
    * SITL gazebo 
    * jlink px4_fmu-v{2-5}
 * better syntax highlighting
    * GNU linker files
    * ROS message files msg/*.msg
    * jinja2 template files
 * better intellisense support

Screenshot from 2019-03-21 23-12-41

@hamishwillee this still needs some work, but it's probably good enough to start documenting and bringing in more users.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@dagar I know nothing about vscode, so if you want this documented you're going to have to answer a few questions:
1. Why vscode vs eclipse etc? Sounds like Visual Studio IDE - is this something different?
2. How does the integration with PX4 work? ie how do I load, build, debug PX4?
3. Can I integrate with things like GDB?

Basically bullet point what you want here to the point where I can try this without spending ages hacking and I can take it from there.

**Comment by dagar** [comment]
@hamishwillee I didn't mean to imply it's on you to document. I was under the impression you were interested in this, although I might be misremembering. 

Overall the reason vscode is compelling is that with a handful of plugins and a relatively simple (in tree) configuration we can offer a fully integrated development experience. Starting from a Linux machine with the current PX4 development environment installed all I need to do is install vscode. I open the PX4 Firmware folder and it prompts me to install the (PX4) recommended plugins. From there just about everything a developer needs to do is available through the gui. Click to select the configuration, run SITL, flash and debug a board, etc. With a little effort this can work on MacOS and Windows as well.

1. Visual Studio Code (vscode) is a separate project from Visual Studio, but carries over some well known features like Intellisense. Technically Eclipse can already do most of the things I mentioned above, it's just a pain to get working with most of the configuration unable to live in the repository, which means manual configuration and poor distribution. It's also just worse to use (too complicated), and still not as tightly integrated with the underlying cmake build.
2. Click to select the config, click to build, click debug, etc. Perhaps I could give you a walkthrough. 
3. Yes, and that already works out of the box.

**Comment by hamishwillee** [comment]
@dagar Thanks for clarification and info. Yes, I am interested and yes I do want to help. I'll try to try this out in the coming week because it is pretty cool.

FYI, you did correctly diagnose my "oh shit" reaction. Back from a weekend away to a truly stunning pile of emails.

**Comment by bys1123** [comment]
Vscode is a upgraded version Sublime Text for me. XD

**Pull request merged**
