### PR TITLE
Follow me

### PR DESCRIPTION
**Pull request by LorenzMeier**
@catch-twenty-two Replacing your PR with this rebased and formatted version.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@catch-twenty-two What is the current state of this right now? Do you have an updated video?

**Comment by LorenzMeier** [comment]
Matching QGC PR, not merged yet and with CI errors: https://github.com/mavlink/qgroundcontrol/pull/2817

**Comment by catch-twenty-two** [comment]
@LorenzMeier Great thanks for doing that, No updated video yet. I did go out with friend to test it on a bicycle so I could see how well it tracked a fast moving object and all went well.  I'll do one more test tomorrow with all the updated changes and then call it good.  I'll also I'll see if I can get some more video if possible.

**Comment by liang-tang** [comment]
@catch-twenty-two Is there a bug?
```javascript
void FollowTarget::update_position_sp(bool use_velocity, bool use_position)
{
    // convert mission item to current setpoint

    struct position_setpoint_triplet_s *pos_sp_triplet = _navigator->get_position_setpoint_triplet();

    // activate line following in pos control if position is valid

    pos_sp_triplet->previous.valid = use_position;
    pos_sp_triplet->previous = pos_sp_triplet->current;
    mission_item_to_position_setpoint(&_mission_item, &pos_sp_triplet->current);
    pos_sp_triplet->current.type = position_setpoint_s::SETPOINT_TYPE_FOLLOW_TARGET;
    pos_sp_triplet->current.position_valid = use_position;
    pos_sp_triplet->current.velocity_valid = use_velocity;
    pos_sp_triplet->current.vx = _current_vel(0);
    pos_sp_triplet->current.vy = _current_vel(1);
    pos_sp_triplet->next.valid = false;
    _navigator->set_position_setpoint_triplet_updated();
}
```
   pos_sp_triplet->current.valid is miss? control_auto couldn't work well if we missed it..

**Comment by catch-twenty-two** [comment]
@LorenzMeier Happy to report I went out today and everything worked great.  I have some video but my mom took it so I'll have to see if it's worth posting.

**Comment by catch-twenty-two** [comment]
> pos_sp_triplet->current.valid is miss? control_auto couldn't work well if we missed it. when i switch to follow target mode, the vehicle isn't moving at all.

Hmmm...you are right.  I'm actually surprised my tests went okay today odd.... Good catch.  I'll have to fix it and retest tomorrow.

**Comment by LorenzMeier** [comment]
I always love videos, so I hope it turns out well!

**Comment by DonLakeFlyer** [comment]
My suggestion for basic follow me support would be to maintain the current height of the Vehicle. Also mantain the current distance/positioning from the target calculated from the first follow me message.

**Comment by catch-twenty-two** [comment]
I'm no filmmaker... which is very apparent from this video, it contains:
 
1) Me walking with follow me mode activated.
2) My mother who I recruited to help me, walking with follow me mode activated (all the rest of my friends are at work on weekday mornings, imagine that! :) )
3) Me riding my Xooter Scooter that I used to get around San Francisco, with follow me activated.

There was a slight wind blowing probably around 7-10 mph the frame type is a DJI style 330. 

> I always love videos, so I hope it turns out well!

@LorenzMeier Did it turn out well?  No. But hopefully your love of videos makes up for that. lol

https://youtu.be/RxDL4CtkzAQ

**Comment by LorenzMeier** [comment]
Awesome, merged! Now on to the QGC merge, @DonLakeFlyer!

**Pull request closed without merging**
