### PR TITLE
Add missing stm32f4discovery make targets

### PR DESCRIPTION
**Pull request by lchish**
Fixes issue  #3026

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Could you add the make target to .travis.yml? It would be good if its auto-build. See the 'make px4fmu-v2_default' target which is already in there.

**Comment by lchish** [comment]
The CI build is failing on osx due to a server error:
```
curl: (22) The requested URL returned error: 500 Internal Server Error

Error: Failed to download resource "genromfs"

Download failed: http://downloads.sourceforge.net/#!/project/romfs/genromfs/0.5.2/genromfs-0.5.2.tar.gz

```

**Comment by LorenzMeier** [comment]
ok, lets kick it again then.

**Comment by LorenzMeier** [comment]
Sorry for the noise - just trying to get it past hans-ci.

**Comment by LorenzMeier** [comment]
Thanks, applied to master!

**Pull request closed without merging**
