### PR TITLE
FMU driver: Show up as secondary interface to allow mixer loads.

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by anton-matosov** [comment]
Am I right that this change allows to use both FMU and IO pwm outputs?

**Comment by LorenzMeier** [comment]
Yes. You need to load a mixer, but then it should work out of the box.

**Comment by anton-matosov** [comment]
Do you plan to update rc.init script to enable px4fmu (pwm_output1)?
Or it should be done in the config.txt?

**Comment by LorenzMeier** [comment]
Closing in favour of the firefly branch.

**Pull request closed without merging**
