### PR TITLE
add configuration for Caipi vtol with reversed elevon servos

### PR DESCRIPTION
**Pull request by kd0aij**
adds a new mixer for reversed elevon servos, a new rotation in lib/conversion
and sets MAV_TYPE in the init script to avoid the hidden dependency in rcS

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I hate to do this: there is a new PWM_REV param set (look in the default or PWM out group) to reverse individual outputs. That should make special configs unnecessary.

**Comment by kd0aij** [comment]
I can't do without the new rotation value though, and I've burned 3 days trying unsuccessfully to merge this with the pwm_invert branch. You did notice that I tested that branch on a quad? 
Unless I can get a working config under master for my Caipi VTOL, I'm not likely to make any further progress with it. Advice would be appreciated.

**Comment by DonLakeFlyer** [comment]
> there is a new PWM_REV param set (look in the default or PWM out group) to reverse individual outputs.

QGC really needs a way to set all this up (or test it) for fixed wing. I'm just converting a fixed wing from ardupilot board to pixhawk and the fact that I can reverse output in my radio, reverse the rc channel with respect to the RC#_REV parameter and also reverse essentially the mixer output (right?) with these new PWM_REV params really makes you head spin!

**Comment by LorenzMeier** [comment]
Then just copy the small rotation changes over to an up to date release_v1.0.0 branch, which has all that already. Sorry to hear about the pain. I can merge your rotation changes pretty quickly if they are in a single PR.

**Comment by LorenzMeier** [comment]
Yes Don - it's not hard to do. Each step can be verified separately and QGC can set all the params for you. It's only confusing if you only look at inputs and outputs.

**Pull request closed without merging**
