### PR TITLE
RTPS compile error  because of FASTRTPSGEN_DIR

### PR DESCRIPTION
**Pull request by stmoon**
I found compile error happens when there is no "FASTRTPSGEN_DIR" environment variable for RTPS.
Especially, the environment variable is not set, if the fastrtpsgen is installed by binary files.

To solve this problem, I check and insert the fastrtpsgen path automatically in python code.

### CODE REVIEW

**Comment by stmoon** [comment]
I found it is related to #13756

**Comment by stmoon** [comment]
Is there any problem? Could you please check it... @TSC21

**Comment by TSC21** [comment]
> Is there any problem? Could you please check it... @TSC21

All good! Thanks for the fix!

**Comment by TSC21** [comment]
Thanks @stmoon!

**Pull request merged**
