### PR TITLE
Integration of the multithreaded version of the uavcan module that saves on memory

### PR DESCRIPTION
**Pull request by davids5**
UDATED: Ready to merge

@LorenzMeier Hold off on this until @pavel-kirienko and I work out any remaining issues. - DONE

This commit saves on memory by the virtue of changes in uavcan lib and by adding a separate object that runs in a lower priority thread which runs the functions that support bootloading with Dynamic Node ID allocation and FW file serving.

The separate thread is part of the uavcan task and started with a subsequent  ```uavcan start fw```  command. The separate thread is independently stopped with  ```uavcan stop fw```  Or it stops with the main uavcan task  ```uavcan stop``` (if it is already started)

### CODE REVIEW

**Comment by davids5** [comment]
@LorenzMeier FYI @pavel-kirienko 

This is ready

**Comment by davids5** [comment]
Final Memory used

```
nsh> free
             total       used       free    largest
Mem:        222160     130384      91776      89888
nsh> uavcan start
[ snip ]
nsh> free
             total       used       free    largest
Mem:        222160     144512      77648      72784
nsh> uavcan start fw
nsh> free
             total       used       free    largest
Mem:        222160     166272      55888      48768
nsh> uavcan stop fw
nsh> free
             total       used       free    largest
Mem:        222160     145024      77136      72784

```

**Comment by LorenzMeier** [comment]
@davids5 @pavel-kirienko What is the state of this and the relation to the current memory issues on beta and master? Is this already contained in the PRs that I already merged?

**Comment by pavel-kirienko** [comment]
@LorenzMeier This PR implements two-process UAVCAN driver, and yes, it has been merged a while ago. It is currently in beta. Also, beta uses the latest version of libuavcan, that incorporates all known memory optimizations to date.

**Pull request closed without merging**
