### PR TITLE
Autopilot capabilities

### PR DESCRIPTION
**Pull request by tumbili**
Send this message on startup and on request. Corresponding issue is #1861

### CODE REVIEW

**Comment by tumbili** [comment]
@LorenzMeier Comments?

**Comment by LorenzMeier** [comment]
Looks good so far, now we just need to populate the bitmask correctly.

**Comment by LorenzMeier** [comment]
Do you have a WIP branch which fills the static part of the bit mask already?

**Comment by LorenzMeier** [comment]
@tumbili do you have a branch / commits implementing the rest of it somewhere? If not no worries and I'll finish this up tonight so we can close this as well.

**Comment by TSC21** [comment]
mavros is waiting for this message support also: https://github.com/mavlink/mavros/issues/246

**Comment by LorenzMeier** [comment]
@tumbili @kd0aij @mcharleb Implemented git version now as file as suggested. Please test.

**Comment by LorenzMeier** [comment]
@TSC21 Its in master and the release branches now.

**Comment by TSC21** [comment]
@LorenzMeier thank you for the feedback. I already tested it on mavros side and I got this:
```bash
[ INFO] [1432376904.331698271]: VER: Capabilities 0x00000000000004eb
[ INFO] [1432376904.331779081]: VER: Flight software:     00000000 (j?#Q6I`j?#Q6I`)
[ INFO] [1432376904.331814379]: VER: Middleware software: 00000000 (j?#Q6I`)
[ INFO] [1432376904.331850687]: VER: OS software:         00000000 (        )
[ INFO] [1432376904.331881663]: VER: Board hardware:      00000000
[ INFO] [1432376904.331912500]: VER: VID/PID: 26ac:0011
[ INFO] [1432376904.331939803]: VER: UID: 3432470a31323533
```
I can't really tell if this is a problem on mavros side or in the firmware side, or if this values represent a problem at all.

**Pull request merged**
