### PR TITLE
Critical: Fixes Snapdragon Flight parameter synchronization problem

### PR DESCRIPTION
**Pull request by jywilson**
The Snapdragon Flight configs will now cause all modules to be scanned for parameters in both Posix (ARM) and DSP (qurt) builds.

### CODE REVIEW

**Comment by jywilson** [comment]
@bkueng @LorenzMeier @ChristophTobler 

This PR contains the changes requested by @bkueng in the other PR containing the same fix:  The other PR (now closed due to a rebase error on my part) for reference is:

https://github.com/PX4/Firmware/pull/6883

**Comment by bkueng** [comment]
Thanks @jywilson, this is good now, but you accidentally removed `src/platforms/px4_getopt.h`, which causes CI to fail.

**Comment by LorenzMeier** [comment]
@bkueng Can you fix quickly?

**Comment by jywilson** [comment]
@bkeung Very strange.  I am not sure how this happened, and it builds fine for me.  I will replace this file.  Thanks.

**Comment by ChristophTobler** [comment]
@jywilson This has already been fixed and merged https://github.com/PX4/Firmware/pull/6910

**Comment by jywilson** [comment]
Thanks @ChristophTobler. @bkueng just noticed that you applied the change. Thanks.

**Pull request closed without merging**
