### PR TITLE
implemented mission switch

### PR DESCRIPTION
**Pull request by friekopter**
This functionality allows to store 4 missions on the sdcard. Simply pushing roll in standby mode changes between stored missions.
In order to make data migration more stable a version number is added to the dataman file. For now migration between two versions means deleting all data and setting up a new database.
As a consequence all stored data by dataman is deleted by running this feature for the first time.

### CODE REVIEW

**Comment by friekopter** [comment]
Anything I can help to get that merged? Maybe adding a parameter that allows to configure the number of missions with default 1, so that nobody gets confused?

**Comment by LorenzMeier** [comment]
@friekopter Sorry for missing to answer you! Please rebase on master and add the parameter, yes. We will also add a MAVLink command later, once the GCS integration has caught up with this.

**Comment by friekopter** [comment]
I have now added a parameter that allow to configure the number of missions. Default is 1. So for the user there are no changes from prior version. 
@LorenzMeier Will you now be able to merge that?

**Comment by friekopter** [comment]
@LorenzMeier Sorry for asking again, but I would like to know if you still plan to merge that in. I would be happy if you would do that soon because its always some effort for me to resolve conflicts etc. 
I think this functionality has some benefit for the community.

**Comment by friekopter** [comment]
@thomasgubler @AndreasAntener @LorenzMeier 
Any answer? 
You did breaking changes in this area recently and it is a lot of effort for me to merge that in. 
So it would be nice to let me know if it makes sense to do the work.

**Comment by LorenzMeier** [comment]
I'm closing this for now. We currently think its adding more complexity than necessary and we don't have the bandwidth to integrate it properly. We would need GCS support for this, so without further coordination in the community I don't think it makes sense to merge, sorry for initially misguiding you!

**Pull request closed without merging**
