### PR TITLE
WIP: att_estimator_q improvements

### PR DESCRIPTION
**Pull request by kd0aij**
Incorporate some of Bill Premerlani's improvements from MatrixPilot:
(see http://diydrones.com/forum/topics/centrifugal-compensation-with-only-gyros-and-accelerometers?xg_source=activity and http://diydrones.com/profiles/blogs/sustained-rotations-pushing)

- fast rotations: reduce gyro bias estimation error and improve attitude estimation accuracy
- compensate for centripetal acceleration assuming coordinated turns (without GPS velocity)

for testing purposes:

- Add "centripetal" uORB topic
- Implement "dual" estimation and logging of original and "improved" vehicle_attitude estimates for quantitative comparison of results

### CODE REVIEW

**Comment by mhkabir** [comment]
@jgoppert I think you had some improvements to the bias estimation in the LPE PR as well? You might be interested in this one.

**Comment by kd0aij** [comment]
The inertial estimate of velocity is cleaner and more accurate than GPS. The correct value should be 0.59 m/sec:

gps_inertial_speed

**Comment by jgoppert** [comment]
@kd0aij On master I added a check that disables gyro bias estimation if the length of the gyro vector is greater than 1 rad/s. This seemed to work well for me. It looks like you are doing something similar here?

Also, it looks like you are calculating the specific acceleration (by subtracting local gravity), and then using this for correcting the rotation. One thought is that this is also occurring  in the position estimator. So in the old code where they simple take the derivative of the velocity signal that I publish, it should contain this information, but this is not ideal. I think it would be best if the position estimators were responsible for publishing an acceleration estimate, since they have the most data to do so accurately.

**Comment by kd0aij** [comment]
I'm interested in eliminating reliance on GPS for attitude estimation. Does LPE offer any advantages if it has no input other than inertial sensors?

**Comment by jgoppert** [comment]
@kd0aij In the derivation, assuming that \vect{omega_e} = omega_e * \vect{e_z} seems like a big assumption. What about when the vehicle is pitching and rolling instead of yawing?

**Comment by jgoppert** [comment]
Without GPS LPE will do something very similar to this, calculate the specific acceleration etc. Maybe if LPE published the centripetal acceleration topic it would work well for you? We could just move your code there?

**Comment by jgoppert** [comment]
Also assuming \vect{V} = V \vec{b_x} is also a big assumption for quads.

**Comment by jgoppert** [comment]
Here is a log of me stress testing the gyro bias estimation with the code that disabled the estimation when the angular speed is > 1 rad/s: http://logs.uaventure.com/view/vJhZtKxeQNERoTyKbgZHsX

**Comment by kd0aij** [comment]
I only added the "centripetal" message to aid in debugging my vector math. Unlike Bill Premerlani, I always get it wrong the first dozen or so times :). 

Testing shows that the centripetal accel and tangential velocity estimates are of course only accurate when there is no slip. Rotating the Pixracer 90 degrees about the body z axis (so that the motion is all "slip"), results in a velocity estimate of only 0.13 m/sec and approximately 4 degrees of error in estimated roll angle. (roll is then zero and pitch is -45)

But an FPV pilot will probably be minimizing slip/skid so that he's looking in the direction of travel even when flying a multirotor...

sideways

**Comment by kd0aij** [comment]
Actual flight test shows good agreement of tangential speed with gps speed when trying to fly coordinated turns via LOS. The new attitude estimate differs by 1 degree in roll and 4 degrees in pitch, and estimated speed is about 2 m/sec.

aquaquad_flight_test

**Pull request closed without merging**
