### PR TITLE
Extend frsky smartport telemetry with apm compatible flightmode (TEMP…

### PR DESCRIPTION
**Pull request by Stevie69**
…1) and gps satcount/fixstate (TEMP2)

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice! Is this for a particular OpenTX version?

**Comment by Stevie69** [comment]
It should work with all OpenTX versions that support smartport (X-Receicer) telemetry. The generated data (TEMP1 and TEMP2) is compatible to APM version >= 3.2.1 (guessed, cant remember exactly) and is handled best with a telemetry script. See http://fpv-treff.de/viewtopic.php?f=66&t=7717 (german)

**Comment by kd0aij** [comment]
That's a great idea. Now we just need a Taranis script for PX4 modes. QGC has some real competition here :)

**Comment by Stevie69** [comment]
My approach is to map the PX4 flightmodes to APM flightmodes as good as possible, so only one script is necessary and needs to be maintained.

**Comment by Stevie69** [comment]
Clicked the wrong button. Sorry.

**Comment by LorenzMeier** [comment]
Hey Stevie - the idea is great, but I'm concerned that PX4 users are confused by the indication of the display. Let me try to work with the APM community and the user in that thread to see if we can extend it to be more general.

**Comment by LorenzMeier** [comment]
I've filed an issue with the LUA script to see if we can get full support in.

**Comment by ilihack** [comment]
What you wahnt to integrate in the lua Script? I made an Advanced fork of Jace25 Script ,,Lua 
Pilot" on githube  mabye i can help to

**Comment by LorenzMeier** [comment]
@ilihack Essentially a way so the LUA script supports PX4 and APM flight modes (both at the same time) and uses for each flight stack the exact appropriate mode description / text label. This will provide a much better user experience, because our users will be very confused by the APM terms.

**Comment by ilihack** [comment]
okay maybe you have allrady what you whant? i use all Pixhawk flightmodes and include support for Temp1 and Temp2 in my script...

**Comment by LorenzMeier** [comment]
@ilihack We need these flight modes in addition to the APM flight modes:

MANUAL
ACRO
STABILIZED
RATTITUDE
POS CONTROL (short: POSCTRL, long: POSITION CONTROL)
ALT CONTROL (short: ALTCTRL, long: ALTITUDE CONTROL)
OFFB CONTROL (short: OFFBCTRL, long: OFFBOARD CONTROL)
AUTO TAKEOFF
AUTO PAUSE
AUTO MISSION
AUTO RTL
AUTO LANDING

**Comment by LorenzMeier** [comment]
@ilihack Let us know when you have a script for us to test with.

**Comment by ilihack** [comment]
Hey @LorenzMeier, Sory for the late Answer i was not able check all my Emails early,

Okay no Problem i can try to modify my script, what we exatcly need? the Arducopters Flightmodes go from 0 to 17 and send with the Temp Variable...

    FlightModeName[0]="Stabilize"
    FlightModeName[1]="Acro Mode"
    FlightModeName[2]="Alt Hold"
    FlightModeName[3]="Auto Mode"
    FlightModeName[4]="Guided Mode"
    FlightModeName[5]="Loiter Mode"
    FlightModeName[6]="RTL Mode"
    FlightModeName[7]="Circle Mode"
    FlightModeName[8]="Invalid Mode"
    FlightModeName[9]="Landing Mode"
    FlightModeName[10]="Optic Loiter"
    FlightModeName[11]="Drift Mode"
    FlightModeName[12]="Invalid Mode"
    FlightModeName[13]="Sport Mode"
    FlightModeName[14]="Flip Mode"
    FlightModeName[15]="Auto Tune"
    FlightModeName[16]="Pos Hold"
    FlightModeName[17]="Brake Mode"

And we need for the user not Fly with the Pixhawk flight stack:
0 Stabilize  
1 Acro Mode
2 ALT CONTROL (short: ALTCTRL, long: ALTITUDE CONTROL)
3 AUTO MISSION
6 AUTO RTL
9 AUTO LANDING


and this new Flightmodes: ???
18 MANUAL
19 RATTITUDE
20 POS CONTROL (short: POSCTRL, long: POSITION CONTROL)
21 OFFB CONTROL (short: OFFBCTRL, long: OFFBOARD CONTROL)
22 AUTO TAKEOFF
23 AUTO PAUSE

This is easy and not a Problem if i Unterstand you correct ;)

**Comment by BjoernKellermann** [comment]
Hi,
why not providing the Lua script with one model specific configuration option?
Flightstack = PX4 | APM
Than, the script can behave accordingly.

Maybe the LUA script can be changed into direction of the script created by "Craft & Theory" which looks really nice...
http://www.craftandtheoryllc.com/frsky-telemetry-cable-and-user-interface-for-pixhawk/

BR from Hamburg

**Comment by LorenzMeier** [comment]
@BjoernKellermann Its even simpler than that - the LUA script could just be extended with the PX4 flight modes on different indices (above the APM flight modes), then no setup would be required. Anyone here willing to look into that?

**Comment by thedevleon** [comment]
Very interested in making this work as well. 
I think a good solution would be to leave the APM specific flightmodes to 1-17, and then map the PX4 ones from 18-29. 
I have modified the script accordingly (https://github.com/ilihack/LuaPilot_Taranis_Telemetry/pull/2), still need to make the according voice files. 
I have changed the frsky_telemetry driver as well: https://github.com/Stevie69/Firmware/pull/1

**Comment by thedevleon** [comment]
As suggested by @LorenzMeier, I have created a new PR to reflect my changes. See https://github.com/PX4/Firmware/pull/4345. I guess this should be closed then?

**Comment by LorenzMeier** [comment]
We will go for the cross-flight-stack LUA script.

**Pull request closed without merging**
