### PR TITLE
SmartPort telemetry

### PR DESCRIPTION
**Pull request by kd0aij**
rebased on master 
battery voltage reported correctly to Taranis X9D running OpenTX 2.1.7
still have to start daemon sPort_telemetry manually

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesome! Can we still get an image of the cable in here?

**Comment by kd0aij** [comment]
Connect the JST labeled "FRs" on the PixRacer to the S.PORT connector of an FrSky X-series receiver like this (the S.PORT pins should be labeled -, + and s.port on the receiver):

image

**Comment by kd0aij** [comment]
top output at priority 200:
```
 173 sPort_telemetry             13172  2.635  1276/ 1992 200 (200)  w:sem 
 173 sPort_telemetry             14714  3.187  1276/ 1992 200 (200)  w:sem 
``` 
min, mean, max response latency(seconds):  1.549e-03,  2.719e-03,  3.410e-03
latency median: 2.742e-03
latency std. dev.: 3.218e-04
```
run frequency is 83Hz average
```
min, mean, max frame interval (seconds):  1.182e-02,  1.200e-02,  1.217e-02
interval std. dev.: 5.893e-05
```

**Comment by kd0aij** [comment]
pixracer now sends D type telemetry on smartport if an X type receiver is not detected

**Comment by kd0aij** [comment]
With the integration of D type telemetry into sPort_telemetry.c it should be renamed to frsky_telemetry.c and all FrSky telemetry code should be in drivers/frsky_telemetry, eliminating the drivers/sPort_telemetry directory. But this would need to be coordinated with current users of the original frsky_telemetry daemon to avoid breaking their configurations.

**Comment by LorenzMeier** [comment]
There are virtually none, so its better to do a clean cut to avoid technological debt. If you just move things to drivers/frsky_telemetry and use the same start command you will not break anything.

**Comment by kd0aij** [comment]
replaced by #3573

**Pull request closed without merging**
