### PR TITLE
MAVLink app: Send newest param hash for every param change to notify …

### PR DESCRIPTION
**Pull request by LorenzMeier**
…GCS about change

This should help keeping the GCS up to date about asynchronous changes on the autopilot.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
This is going to break QGC. It only expects a hash param in response to the initial param_request_list. Also still not sure how this is supposed to fix the problem?

**Comment by DonLakeFlyer** [comment]
Actually need to look at the QGC code a little more. I think it will end up doing nothing since the hashes won't match (I'm assuming volatile parameter updates are not send to QGC). Otherwise it will kick off a spurious reload from the hash on the QGC side.

**Comment by DonLakeFlyer** [comment]
The protocol is supposed to be:
* QGC sends PARAM_REQUEST_LIST
* Vehicle send _HASH_CHECK first with it's hash
* Vehicle starts streaming parameters
* If QGC and Vehicle hash match
    * QGC sends vehicle write to _HASH_CHECK which is signal to stop streaming parameters
    * QGC loads params from cache
* Otherwise QGC just gets the params from the streamed list

Not sure how QGC is supposed to respond to a one-off _HASH_CHECK parameter update from the vehicle.

**Comment by dagar** [comment]
Somewhat of a side note, but HASH_CHECK isn't that's useful in practice anymore due to the system automatically saving things as parameters like flight time, UUID, EKF learned biases.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer QGC is supposed to reload the param set whenever it finds the hash to mismatch. You cannot assume that the GCS "owns" the parameters during things like calibration, so we need a new and additional interface to tell the GCS that the set changed.

We also need to get to a general paradigm of QGC holding an avatar of the vehicle, not being part of it. There will be things like cloud services in the future that manipulate the vehicle and QGC needs to be able to deal with non-conflicting use cases.

@dagar The easy way to solve that is to mark them as volatile and to exclude them from the hash. That would completely solve it. I need to think more wether that breaks some of the assumptions of the param system but likely it won't.

**Comment by DonLakeFlyer** [comment]
> QGC is supposed to reload the param set whenever it finds the hash to mismatch.

That's news to me!

> You cannot assume that the GCS "owns" the parameters during things like calibration, so we need a new and additional interface to tell the GCS that the set changed.

Which it doesn't. After things like calibration it refreshes specific sets of parameters which are the ones it cares about.

Refreshing **all** parameters every time the hash changes sounds like a really bad idea. That is a lot of wasted bandwidth and time for one parameter possibly changing. For example a Level Horizon cal which tweaks three params I think will then cause hundred+ params to come across the link. Why doesn't the firmware send updates only to the ones that have changed incrementally if they change not in reponse to the ground station changing them?

**Comment by DonLakeFlyer** [comment]
So to summarize. Think this would be better:
* Allow marking or volatile params which do not take part in hash or async update
* When a param which is not marked volatile changes on the vehicle side (not caused by groundstation write) the vehicle sends the update for that param to ground station.

**Comment by LorenzMeier** [comment]
> Why doesn't the firmware send updates only to the ones that have changed incrementally if they change not in reponse to the ground station changing them?

Because its an embedded system, so storing that additional bit does come at a cost. I will check though if we might have free bits that could be reused to store that per param.

**Comment by LorenzMeier** [comment]
Obsoleted by https://github.com/PX4/Firmware/pull/8617#issuecomment-355845057

**Pull request closed without merging**
