### PR TITLE
[WIP] cmake fixes and cleanup

### PR DESCRIPTION
**Pull request by dagar**
- nuttx cmake improved dependencies (https://github.com/PX4/Firmware/issues/7999)
 - improve compiler flag handling (simpler modern cmake rather than error prone string passing)
 - raise cmake requirement to 3.2
 - better cmake git submodule dependencies
 - default -Wdouble-promotion enabled (need to fix or ignore per module)

### CODE REVIEW

**Comment by dagar** [comment]
This fixes the build upload and some dependencies that should get into 1.7.

**Comment by davids5** [comment]
@dagar needs rebase

**Comment by dagar** [comment]
This may force me to finally upgrade/fix the old px4-dev-ros running tests on jenkins.
It's stuck on an old version of cmake.

**Comment by davids5** [comment]
> nuttx cmake improved dependencies (#7999) - you got it! excpet that is what run 2X 

```

**Comment by davids5** [comment]
@dagar -  posted the edit, on the first `make`, load FW, and `free`, it is wrong, On the second `make` and load it is fixed. I can live with that for a bit

**Comment by dagar** [comment]
The larger cmake cleanup will have to wait until I can upgrade what's on jenkins. I'll still look at improving the nuttx dependencies separately.

RTPS portion split out here. https://github.com/PX4/Firmware/pull/8084

**Comment by LorenzMeier** [comment]
Rebase or close as stale?

**Comment by dagar** [comment]
Closing as stale, but gradually pulling ideas from this PR into new work.

**Pull request closed without merging**
