### PR TITLE
Master save mem wd

### PR DESCRIPTION
**Pull request by davids5**
@bkueng has found us more free memory!

I retested and we needed to have the interrupt reserve 4+1 to not allocate more at runtime.

@PX4TestFlights - please bench test first for safety!

### CODE REVIEW

**Comment by NaterGator** [comment]
@davids5 if we're looking for free memory / flash it would be a good time to update matrix to at least https://github.com/PX4/Matrix/commit/66e1b406b8a68422135c365d42b987a64c9ddf8d

**Comment by LorenzMeier** [comment]
We've been bitten by this before. We had to pre-allocate more than we ever use at runtime. Are we confident that issue in NuttX has been resolved?

**Comment by francisco3dr** [comment]
Tested with QAV250:

http://review.px4.io/plot_app?log=b596230d-dff7-485e-b004-6aed49e9456a
http://review.px4.io/plot_app?log=e7879c45-d2e3-455d-a7c1-741c40727976
http://review.px4.io/plot_app?log=f45e2925-cd0d-4573-800a-daef6c40492d

**Comment by santiago3dr** [comment]
couple successful flights on this PR
indoor:
http://logs.px4.io/plot_app?log=e043187d-7145-4b66-a62b-b2248ce2c5a2
https://youtu.be/Xj9bDuYKQ60

field:
http://logs.px4.io/plot_app?log=7f46e55d-9e38-4ff7-9034-0010c0f9e4e3
https://youtu.be/sfRLM5WfceU

**Comment by davids5** [comment]
@LorenzMeier 

By bitten are you referring [to](https://github.com/PX4-NuttX/nuttx/blob/8b81cf5c7ece0c228eaaea3e9d8e667fc4d21a06/sched/wdog/wd_create.c#L117) 
another example of a silent resource failure? 

There are several of this type of silent resource fail. Upstream assumes less of a dynamic runtime environment and that the DEBUGASSERT are adequate and has rejected any more debug instrumentations. 

We can add a set of patches to keep track of the min free resources and display them in top.

We can also look at the soak test setup again and run a patch to change selective DEBUGASSERT to ASSERT on that test build.

In the case of this set of this settings. The code has 2 configuration parameters. One represents the total fixed allocation and the other the number of those allocations reserved for calls off of ISR.  

If on an interrupt handler thread OR if the number of pre-allocated  timer structures exceeds the reserve, then take the the next timer from the head of the free list. If the above is false the an allocation will occur in the non ISR case.

So if allocation = total used + total reserved for IRQ + 1 we should never allocate any timers off the heap.

We maxed out at peek of 18-20 used, we have 4 reserved for ISR  so I set the value at 25.

**Comment by LorenzMeier** [comment]
Too high risk for v1.6

**Comment by davids5** [comment]
As discussed we need the HW soak testing and test build to validate. I will coordinate with @darioxz

**Comment by TSC21** [comment]
@davids5 what's the test status on this PR?

**Comment by davids5** [comment]
@darioxz - How is the HW testing coming?  Per our discussion we still need a way to detect resource exhaustion under flight conditions. Thinks like [here](https://github.com/PX4-NuttX/nuttx/blob/8b81cf5c7ece0c228eaaea3e9d8e667fc4d21a06/sched/wdog/wd_create.c#L117) 
need to be testable. There are a lot of these type conditions in the priority inversion code as well.

**Comment by LorenzMeier** [comment]
Closing - its great but with unknown risk.

**Pull request closed without merging**
