### PR TITLE
Mmc

### PR DESCRIPTION
**Pull request by RizHuang**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
What is the intent with this PR?

**Comment by LorenzMeier** [comment]
Please re-submit in multiple PRs for individual subsystems and changes. Your PR is changing default system behaviour and cannot be merged this way.

**Comment by RizHuang** [comment]
Sorry . I just learning about development  base on PIX4 Flight Stack . Hope someday I can distribute to it and development with you . I need more time to learn about Git .

**Comment by LorenzMeier** [comment]
No worries, please keep the pull requests coming! I saw that you did a new driver - do you maybe want to send only the driver as a pull request?

**Pull request closed without merging**
