### PR TITLE
RC multi input fix

### PR DESCRIPTION
**Pull request by LorenzMeier**
@bkueng Please review. This should help with situations where you have the joystick connected.

### CODE REVIEW

**Comment by dagar** [comment]
I tried this with a friend a few weeks ago and it wasn't working quite how we expected/wanted.

Just to sanity check, if two sources are simultaneously publishing the same topic at different priorities what does a regular subscriber see? Is the subscriber responsible for choosing the highest priority instance?

What about the RC generation case (COM_RC_IN_MODE=2) and RC_CHANNELS_OVERRIDE that publish ORB_ID(input_rc)?

**Comment by LorenzMeier** [comment]
RC generation case is not really supported as its a developer thing. With this change you won't see alternating inputs - you get either, depending on what is on first. Still not optimal, but should be robust. Please re-test.

**Comment by LorenzMeier** [comment]
@PX4TestFlights Can you test if you still get valid inputs?

**Comment by dagar** [comment]
Ah, I see.
Didn't realize RC generation case was considered a developer thing. We could remove the param metadata and make give the other options more appropriate naming. 

If we wanted to switch back and forth based on priority where do you think that should happen? Could we extend uorb to automatically handle it or have an intermediary?

**Comment by bkueng** [comment]
@dagar the subscriber needs to handle priorities. In that case there are many, so an intermediary would make sense. Or let mavlink publish to a different topic name, and let sensors subscribe & handle it.

**Pull request merged**
