### PR TITLE
Revert "Fix for HobbyKing boards."

### PR DESCRIPTION
**Pull request by dagar**
This commit fixed certain px4fmu-v2 boards with the problem described in https://github.com/PX4/Firmware/issues/7857, but causes problems for the pixhawk mini. Opening this PR to discuss possible solutions.

https://github.com/PX4/Firmware/issues/7857
https://github.com/PX4/Firmware/pull/8478

One option (certainly not ideal) is to revert this commit in master for the regular px4fmu-v2, but offer a different binary with this change.

@whyscience

### CODE REVIEW

**Comment by jlecoeur** [comment]
For the record, the commit you revert was already a revert of this commit https://github.com/PX4/Firmware/commit/553c64925292d0fc99b46d9514eb6646472033e7

**Comment by dagar** [comment]
Thanks Julien. The history here was a bit more complicated than I initially realized.

**Comment by Avysuarez** [comment]
flight with pixhawk mini (v3)  good flight no issues
https://review.px4.io/plot_app?log=47e2d7d9-1eb3-43ec-8455-b3d105a74136

flight with pixhawk 1 (v2) good flight, no issues
https://review.px4.io/plot_app?log=c64535e1-1c28-443e-a346-f8c3a9879ec8

**Comment by LorenzMeier** [comment]
@dagar Sound like we should be using this version here.

**Comment by dagar** [comment]
Yes I think so. We can quickly go over it on the dev call.

**Comment by korigod** [comment]
#8478 causes faults of L3GD20 and LSM303D on Radiolink Pixhawk and several similar noname Chinese boards I've tested as well, not only Pixhawk Mini.

**Comment by dagar** [comment]
Sounds like this is the way to go. Unless anyone has another idea I'm going to merge this PR and leave the original commit available on another branch we can refer refer affected users to.

**Pull request merged**
