### PR TITLE
uORB topics autogeneration

### PR DESCRIPTION
**Pull request by againagainst**
issue https://github.com/PX4/Firmware/issues/2486

### CODE REVIEW

**Comment by DrTon** [comment]
New logger works now! File extension changed to .ULG ("micro LoG" / "Uav LoG" / "Universal LoG").

TODO

- Topics list (default + user overridable), now hardcoded topics for accel/gyro/mag
- Arguments parsing: buffer size, default rate etc.
- Files naming using GPS date and time
- Console converter tool
- FlightPlot already supports new format, will be released soon

**Comment by vooon** [comment]
Extending genmsg is a bad think - this was broke ros-sitl build. Alternatively you may add second file with this metadata (example - nanopb uses `*.option` file to specify maximum length + other non-standard options).

**Comment by LorenzMeier** [comment]
I hadn't thought of the .option approach. @againagainst that sounds like a good way to de-conflict things.

**Comment by againagainst** [comment]
:relieved:

**Comment by pavel-kirienko** [comment]
I hereby invoke @LorenzMeier and @DrTon to appreciate this PR, and maybe even merge it.

**Comment by againagainst** [comment]
Generation into the Build directory will require declaration by absolute path for generated cpps in the uORB/module.mk, like this:
```SRCS	+= $(wildcard $(BUILD_DIR)topics_temporary/*.cpp)```
The problem is that in this case *.o files are also compiled by absolute path, into the same directory: 
https://github.com/PX4/Firmware/blob/master/makefiles/module.mk#L195
This makes impossible compilation for several platforms.

I may correct the module.mk rules. Does it make sense, if you (as I understood) are going to use CMake anyway?

**Comment by mcharleb** [comment]
The problem has been when you do a make clean, these things don't get cleaned and can cause problems when you switch between git branches and try to rebuild. If I have to test one target that uses these and then a cmake target that doesn't, it can break the build because its finding the old generated headers.

**Comment by LorenzMeier** [comment]
@againagainst Could you please start looking at the CI output? You fixed the compilation in 96806b7 just to break it again in 102b4f8. You can click on the symbol to get the CI status and the console output.

**Comment by LorenzMeier** [comment]
@DrTon Nice! What from your original todo list is left now? Did @againagainst provide the automated topic list yet?

**Comment by DrTon** [comment]
Some TODO's still left:

- Firmware version logging (very easy)
- Topics list (not implemented yet, but maybe we can simply use topic files?)
- Files naming using GPS time (would be good to fix RTC problems first)
- Precise timestamps (requires timestamps in uORB)
- Multi topics logging

BTW parameters now logged with type, so it's possible to restore parameters list from log as txt to open in qgc.

**Comment by againagainst** [comment]
Automated topic list is implemented. Generation of multiline topics is done for all platforms, but ROS-SITL. 
The px_generate_uorb_topic_headers.py and px_generate_uorb_topic_sources.py scripts are used for generation, they use genmsg as msg parser, and perform generation by empy. 
In ROS-SITL, topics are generated by genmsg through CMake bindings. Since we decided to avoid extending genmsg, the only solution I see is to replace the bindings with a CMake function which calls python scripts for the ROS too. By the way, we already have such CMake function in master, so it's possible to use it inside the ROS's Cmake procedures. @LorenzMeier Please, share you opinion on this solution.

**Comment by LorenzMeier** [comment]
@againagainst Extending CMake sounds fine. Do you need additional hints there? I will review your complete work once all CI systems pass.

**Comment by againagainst** [comment]
I'm experiencing problem with building the ROS-SITL even on master. However, it used to be compilable before merging with cmake build system's branch.
I use the `setup-workspace.bash` script from https://pixhawk.org/dev/ros/sitl in a clean directory, but it fails with the following error:
```
CMake Error at Firmware/CMakeLists.txt:156 (include):
  include could not find load file:

    configs/nuttx_px4fmu-v2_default


CMake Error at Firmware/CMakeLists.txt:168 (message):
  configs/nuttx_px4fmu-v2_default must implement px4_os_prebuild_targets
```
The problem actually caused here: https://github.com/PX4/Firmware/blob/master/CMakeLists.txt#L150 the ${OS} given by catkin's CMake is `nuttx`
@LorenzMeier, @jgoppert any ideas how to fix it? May be I should update the environment somehow?

This problem blocks me with extending CMake for ROS-SITL (obviously).

**Comment by dagar** [comment]
@DrTon @againagainst @kd0aij do you want to try and finish this? I squashed everything together into a single commit off of current master and pushed it to uORB_autogeneration_rebase.
https://github.com/PX4/Firmware/compare/uORB_autogeneration_rebase?expand=1

One piece that may need to be rethought is EKF2_REC_RPL. https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rc.logging#L15

**Comment by dagar** [comment]
The current problem is getting cmake to pickup the generated cpp files in the uORB module.

msg_source_files_out https://github.com/PX4/Firmware/blob/uORB_autogeneration_rebase/cmake/common/px4_base.cmake#L369 needs to be available to https://github.com/PX4/Firmware/blob/uORB_autogeneration_rebase/src/modules/uORB/CMakeLists.txt#L40 at cmake configure time.

**Comment by jgoppert** [comment]
@dagar 
https://github.com/PX4/Firmware/blob/uORB_autogeneration_rebase/cmake/common/px4_base.cmake#L369 needs to be available to
```cmake
add_custom_target(${TARGET}
		DEPENDS ${msg_source_files_out} ${msg_multi_files_out} ${msg_files_out})
set_target_proprties(${TARGET}  msg_files ${msg_files})
```

https://github.com/PX4/Firmware/blob/uORB_autogeneration_rebase/src/modules/uORB/CMakeLists.txt#L40 at cmake configure time.

```cmake
get_target_property(MSG_FILES msg_gen msg_files)
```

This works because CMake is scoped, and msg_gen is defined in the root CMakeLists.txt file as a custom target.

**Comment by dagar** [comment]
Thanks @jgoppert 
That's closer, but cmake is still unhappy because the file doesn't exist at configure time.

    CMake Error at cmake/common/px4_base.cmake:269 (add_library):
      Cannot find source file:

    /home/dagar/git/Firmware/build_posix_sitl_default/topics_sources/vehicle_attitude.cpp

     Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp .hxx .in .txx
    Call Stack (most recent call first):
    src/modules/uORB/CMakeLists.txt:75 (px4_add_module)

    CMake Error: CMake can not determine linker language for target: modules__uORB

I've opened a new pull request https://github.com/PX4/Firmware/pull/4041
Please push changes if you have any ideas.

**Comment by LorenzMeier** [comment]
Included in logger branch, closing, thanks!

**Pull request closed without merging**
