### PR TITLE
delete VT_FW_PITCH_TRIM parameter

### PR DESCRIPTION
**Pull request by dagar**
We don't need this in addition to regular TRIM.

### CODE REVIEW

**Comment by dagar** [comment]
It's only being added to the actuator_control coming from the FW controller. In master - https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/tailsitter.cpp#L403-L404

**Comment by jingego** [comment]
I'm wondering so the RC Trims will not work in MC mode? It looks like regular TRIM_PITCH parameter is related to the RC Trims.

**Comment by jux2** [comment]
I've been using this parameter for a tiltwing that hovers at different angle to forward flight (like @bresch  said). What's alternative to set FW pitch angle different to MC? Cheers

**Comment by dagar** [comment]
@jux2 if you're talking about the FW frame vs MC (not specifically the actuator trim) then take a look at the fixedwing pitch setpoint offset (FW_PSP_OFF).

**Pull request merged**
