### PR TITLE
Vtol work

### PR DESCRIPTION
**Pull request by tumbili**
This branch is rebased on master and contains:

* transition strategy for tailsitters from @davidvor & @yairabr
* fw & mc virtual attitude setpoints in order to clearly distinguish between those setpoints
* quaternion based attitude control for fixed wings in order to use the same coordinate frame for multicopters and fixed wings

### CODE REVIEW

**Comment by tumbili** [comment]
@davidvor This is the branch containing all the work you need for a bench test. It would be nice if we could clean up your commit history a bit. Let's make a skype call so that I can show you how that works. We have vtol simulation running on SITL so I can give this a test tomorrow before you start bench testing it.

**Comment by tumbili** [comment]
Reminder for myself: Don't use euler angles to construct attitude quaternion in fw_att_controller!

**Comment by LorenzMeier** [comment]
You will need to bring in your VTOL POSIX port branch in here. You might need to first apply the formatting in case the first try to rebase or merge fails. In general formatting should be either done as the first step of rework or the last, and not in two branches changing the same file.

**Comment by davidvor** [comment]
i have bench tested it today, it should work in the air,
in the QGC there is still a hump in the pitch set-point, in thFW mode it is around zero while should be around -pi/2
pitch set point new 3 11

**Comment by tumbili** [comment]
@davidvor You have to take out this piece of code here
https://www.kickstarter.com/projects/137596013/x-plusone-your-ultimate-hover-speed-aerial-camera/comments
Since we are using the same reference frame now we don't have to rotate the attitude anymore.

**Comment by LorenzMeier** [comment]
@tumbili Would be good to merge this soon so we avoid merge conflict drama with this one.

**Comment by LorenzMeier** [comment]
@tumbili Please don't let this one dangle any further. If there are particular items that need to be resolved identify them clearly. We need to be much more diligent about preventing dangling PRs whenever we can.

**Comment by tumbili** [comment]
@davidvor I finished vtol tailsitter simulation today and I was able to test this in SITL. I found a small problem with attitude control which I'm going to fix it tomorrow. As soon as I pushed the fix I will let you know. One last bench outdoor test would be great before we can merge this.

**Comment by tumbili** [comment]
@LorenzMeier This is bench tested on my tailsitter. I will ask Marco to give it one final test on his standard airfame and then we should be good to go.

**Comment by tumbili** [comment]
This was flight tested on a tailsitter on 24.11.15. Multicopter operation and transitioning was fine but fw operation was not possible due to an airspeed bug fixed in #3267

**Comment by LorenzMeier** [comment]
Lets get it in and fix up if needed on master

**Pull request merged**
