### PR TITLE
Fix 'stale mag' on POSIX

### PR DESCRIPTION
**Pull request by bkueng**
- fix 'stale mag' error messages on RPi (& POSIX) (commit fb1d479bbe60e2b2c1573e8e5a54762b7fdb43)
- get the 'is external' information via uORB topic instead of ioctl, which does not work reliably on POSIX

Please see the individual commit messages.

Fixes https://github.com/PX4/Firmware/issues/7395

Tested on Pixracer & Pixhawk Pro (with external sensor) & RPi.
@mhkabir

### CODE REVIEW

**Comment by mhkabir** [comment]
Looks good.

@tstellanova Please test this with GNSS v2 + Pixhawk 2, thanks!

**Comment by mhkabir** [comment]
@bkueng Can you rebase my commits (https://github.com/PX4/Firmware/pull/7403/files) into this branch too?

**Comment by nicolaerosia** [comment]
Offtopic: why do we care if an magnetometer is internal or external? Seems a bit too much to carry an extra byte which never changes, in every mag report.

**Comment by mhkabir** [comment]
To handle rotations.

**Comment by bkueng** [comment]
> @bkueng Can you rebase my commits (https://github.com/PX4/Firmware/pull/7403/files) into this branch too?

done!

**Comment by nicolaerosia** [comment]
Works on RPI:
```
INFO  [sensors] gyro status:
INFO  [lib__ecl] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [lib__ecl] sensor #0, prio: 75, state: OK
INFO  [lib__ecl] 	val:   0.0010, lp:   0.0009 mean dev:  -0.0001 RMS:   0.0006 conf:   1.0000
INFO  [lib__ecl] 	val:   0.0154, lp:   0.0149 mean dev:   0.0009 RMS:   0.0017 conf:   1.0000
INFO  [lib__ecl] 	val:   0.0016, lp:   0.0003 mean dev:  -0.0001 RMS:   0.0009 conf:   1.0000
INFO  [sensors] accel status:
INFO  [lib__ecl] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [lib__ecl] sensor #0, prio: 75, state: OK
INFO  [lib__ecl] 	val:  -0.1543, lp:  -0.1545 mean dev:  -0.0080 RMS:   0.0158 conf:   1.0000
INFO  [lib__ecl] 	val:  -0.1337, lp:  -0.1315 mean dev:  -0.0063 RMS:   0.0129 conf:   1.0000
INFO  [lib__ecl] 	val: -10.3677, lp: -10.3721 mean dev:  -0.6319 RMS:   1.0102 conf:   1.0000
INFO  [sensors] mag status:
INFO  [lib__ecl] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [lib__ecl] sensor #0, prio: 50, state: OK
INFO  [lib__ecl] 	val:  -0.1725, lp:  -0.1771 mean dev:   0.0011 RMS:   0.0075 conf:   1.0000
INFO  [lib__ecl] 	val:  -0.0754, lp:  -0.0755 mean dev:  -0.0016 RMS:   0.0083 conf:   1.0000
INFO  [lib__ecl] 	val:   0.2667, lp:   0.2649 mean dev:  -0.0017 RMS:   0.0084 conf:   1.0000
INFO  [sensors] baro status:
INFO  [lib__ecl] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [lib__ecl] sensor #0, prio: 75, state: OK
INFO  [lib__ecl] 	val: -17.2998, lp: -14.8504 mean dev:  -1.7365 RMS:   0.5714 conf:   1.0000
INFO  [lib__ecl] 	val:   0.0000, lp:   0.0000 mean dev:   0.0000 RMS:   0.0000 conf:   1.0000
INFO  [lib__ecl] 	val:   0.0000, lp:   0.0000 mean dev:   0.0000 RMS:   0.0000 conf:   1.0000
```

**Comment by tstellanova** [comment]
Tested on Pixhawk 2.1 with Zubax GNSS2.0.

- UAVCAN mag no longer reports stale
- validator still reports failsafe YES, for what it's worth:

```
INFO  [sensors] mag status:
INFO  [lib__ecl] validator: best: 3, prev best: 0, failsafe: YES (2 events)
INFO  [lib__ecl] sensor #0, prio: 50, state: OK
INFO  [lib__ecl] 	val:   0.1540, lp:   0.1510 mean dev:  -0.0001 RMS:   0.0078 conf:   1.0000
INFO  [lib__ecl] 	val:   0.0852, lp:   0.0868 mean dev:   0.0002 RMS:   0.0082 conf:   1.0000
INFO  [lib__ecl] 	val:   0.4442, lp:   0.4513 mean dev:   0.0004 RMS:   0.0078 conf:   1.0000
INFO  [lib__ecl] sensor #1, prio: 50, state: OK
INFO  [lib__ecl] 	val:   0.1491, lp:   0.1495 mean dev:  -0.0002 RMS:   0.0377 conf:   1.0000
INFO  [lib__ecl] 	val:   0.1091, lp:   0.1101 mean dev:   0.0011 RMS:   0.0094 conf:   1.0000
INFO  [lib__ecl] 	val:   0.4245, lp:   0.4254 mean dev:  -0.0003 RMS:   0.0085 conf:   1.0000
INFO  [lib__ecl] sensor #2, prio: 50, state: OK
INFO  [lib__ecl] 	val:   0.1729, lp:   0.1732 mean dev:   0.0017 RMS:   0.0218 conf:   1.0000
INFO  [lib__ecl] 	val:   0.1042, lp:   0.1062 mean dev:   0.0008 RMS:   0.0066 conf:   1.0000
INFO  [lib__ecl] 	val:   0.4432, lp:   0.4436 mean dev:   0.0001 RMS:   0.0054 conf:   1.0000
INFO  [lib__ecl] sensor #3, prio: 125, state: OK
INFO  [lib__ecl] 	val:   0.1741, lp:   0.1718 mean dev:  -0.0001 RMS:   0.0026 conf:   1.0000
INFO  [lib__ecl] 	val:   0.1323, lp:   0.1315 mean dev:   0.0022 RMS:   0.0065 conf:   1.0000
INFO  [lib__ecl] 	val:   0.4588, lp:   0.4578 mean dev:   0.0021 RMS:   0.0036 conf:   1.0000
```

**Comment by LorenzMeier** [comment]
Filed an issue for it: https://github.com/PX4/Firmware/issues/7423

**Pull request merged**
