### PR TITLE
Commander: Disarm after 5 seconds on the ground.

### PR DESCRIPTION
**Pull request by LorenzMeier**
This needs proper testing, but will make tablet flying more fun!

### CODE REVIEW

**Comment by tumbili** [comment]
@LorenzMeier This looks good, I will give it a first test in simulation.

**Comment by AndreasAntener** [comment]
Cool, could we maybe add a param to turn it on/off?

**Comment by tumbili** [comment]
@LorenzMeier Works like a charm in SITL gazebo. Probably should wait for a real outdoor test.

**Comment by tumbili** [comment]
@AndreasAntener Yes, I can do that.

**Comment by tumbili** [comment]
@AndreasAntener Done. The default value is to disarm when landed. So you'd have to set the parameter COM_DISARM_LAND to 0. Tested in SITL.

**Comment by tumbili** [comment]
@SimonWilks  suggested an even better idea to use the parameter as time-out value.

**Comment by AndreasAntener** [comment]
Sounds good :)

**Comment by tumbili** [comment]
Actually the code had a bug before. The landing detector only update if the status has changed. So if the vehicle was in the air the timestamp was never updated. Thus, the time-out was given by the delay of the landing detector and not the actual time-out. Fixed it and tested in SITL, with values 0, 5 and 10.

**Comment by tumbili** [comment]
@AndreasAntener @SimonWilks So we set the default time-out to zero, so nothing should have changed for you guys.

**Comment by tumbili** [comment]
@LorenzMeier @SimonWilks @AndreasAntener Works as expected even on the PH V2! :-)
Merging.

**Comment by LorenzMeier** [comment]
I presume you'll rebase and then merge?

**Comment by tumbili** [comment]
@LorenzMeier Yes, there was a conflict.

**Comment by LorenzMeier** [comment]
Now building fails 8). Try building px4fmu-v2_default locally.

**Comment by tumbili** [comment]
Retested, works fine, merging.

**Pull request merged**
