### PR TITLE
Tailsitter recovery

### PR DESCRIPTION
**Pull request by tumbili**
This is the tailsitter recovery strategy integrated into the attitude controller.
Replaces #3244

### CODE REVIEW

**Comment by tumbili** [comment]
@kd0aij This is the PR for the optimal recovery. If you hold the vehicle upright you should see normal attitude control in all three axes. If you start tilting the airframe you should see an increasing amount of roll actuation (differential elevons) and if the motors should start pushing the vehicle upright.

**Comment by LorenzMeier** [comment]
@tumbili This doesn't work for @kd0aij. Could you fit in a bench test and fix it up?

**Comment by kd0aij** [comment]
elevons and motors active during bench test now. Don't see much diff elevon though. Maybe my yawrate P gain is too low? Should be able to do a test hover after sunup and before snow :)

**Comment by tumbili** [comment]
@LorenzMeier This is failing because of overflowed flash for px4fmu-v4. I thought the Pixracer hardware had more flash space than the Pixhawk?

**Comment by LorenzMeier** [comment]
Rebased, which will fix it.

**Comment by LorenzMeier** [comment]
Now that this passes, can we merge this? Is this test-flown and good to go?

**Comment by LorenzMeier** [comment]
@kd0aij Can you give this a go?

**Comment by LorenzMeier** [comment]
Applied via cherry-pick.

**Pull request closed without merging**
