### PR TITLE
Update submodule sitl_gazebo to latest Sun Aug 18 08:38:19 EDT 2019

### PR DESCRIPTION
**Pull request by dagar**
- sitl_gazebo in PX4/Firmware (f3aba02654a40759c6c032f53f19ea64298fc56e): https://github.com/PX4/sitl_gazebo/commit/22df9475ca0d157e2db066a20f64c35906bf7f25
    - sitl_gazebo current upstream: https://github.com/PX4/sitl_gazebo/commit/ebe1e07f3377a7f9370c049ad73ab7812c71dfa0
    - Changes: https://github.com/PX4/sitl_gazebo/compare/22df9475ca0d157e2db066a20f64c35906bf7f25...ebe1e07f3377a7f9370c049ad73ab7812c71dfa0

ebe1e07 2019-01-31 Tully Foote - Add gstreamer plugin to the fpv camera
157c52d 2019-02-04 Tully Foote - enable gst stream from geotagged_camera
d75b7cd 2019-01-25 Tully Foote - turn on video streaming by default
cc8d125 2019-08-17 TSC21 - make it compilable in Gazebo version < 9
dae0fde 2019-08-17 TSC21 - add support for both sonar and lidar rotation determination by transform checks
9915be5 2019-08-15 TSC21 - gazebo_mavlink_interface: rename setSensorOrientation to setMavlinkSensorOrientation
99eb6ee 2019-08-15 TSC21 - move the sensor orientation computation to common.h
fd7b3b1 2019-08-15 TSC21 - gazebo_mavlink_interface: setSensorOrientation: fix args
943ae18 2019-08-13 TSC21 - lidar: adjust sensor orientation computation pipeline
06eb458 2019-04-02 Elia Tarasov - add calculation of distance sensor direction
b45a202 2019-03-28 Elia Tarasov - rename parameter from facing to rotation
4c38627 2019-03-26 Elia Tarasov - add facing parameter to lidar and sonar plugins

### CODE REVIEW

**Comment by TSC21** [comment]
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-12735/1/pipeline seems to be pointing to the same issue as we find in Travis: https://travis-ci.org/PX4/sitl_gazebo/jobs/573420039.
I rebased https://github.com/PX4/sitl_gazebo/pull/341 so to check if it fixes the issue, but it seems that it bumps into a similar problem: https://travis-ci.org/PX4/sitl_gazebo/jobs/573417134.
So my question is: do we have `gstreamer` up to date (or even installed) on our containers? Or is this a pkg find problem?

**Comment by TSC21** [comment]
OK I think I know the problem: we do install `gstreamer` in https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_simulation. But that's an 18.04 based container. On our ROS SITL tests, we are using https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_ros-kinetic, which bases from the xenial base container, which doesn't install gstreamer.
So my suggestion is to install gstreamer on the base Xenial and Bionic containers.

@dagar what do you think?

**Comment by dagar** [comment]
What's the plan here?

**Comment by TSC21** [comment]
> What's the plan here?

Containers need to be updated. But we need to change the way they reference each other. We need gstreamer in both Xenial and Bionic.

**Comment by TSC21** [comment]
Changes on the containers side done: https://github.com/PX4/containers/pull/202. Now we just need to wait for them to build on Docker Hub.

**Comment by TSC21** [comment]
Closed in favour of https://github.com/PX4/Firmware/pull/13099.

**Pull request closed without merging**
