### PR TITLE
bmi160 move to PX4Accelerometer and PX4Gyroscope and cleanup

### PR DESCRIPTION
**Pull request by dagar**
@davids5 do you have a pixracer with a bmi160?

This change shouldn't actually be that risky, the changes are nearly the same as the other drivers.

### CODE REVIEW

**Comment by davids5** [comment]
@dagar - yes I do but the build failed.

**Comment by dagar** [comment]
Fixed.

**Comment by davids5** [comment]
@dagar - bench test results in no Sensors Barro  
```
nsh> [boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
HW arch: PX4_FMU_V4
FW git-hash: 5708eeb9d283dc3775ba3c583a6fa31d2ed508ae
FW version: 1.9.0 0 (17367040)
FW git-branch: dagar-pr-bmi160_cleanup
OS: NuttX
OS version: Release 7.28.0 (119275775)
OS git-hash: 423371c7d4012e725ac4ca51323a18df64e581b3
Build datetime: Jun  4 2019 11:49:16
Build uri: localhost
Toolchain: GNU GCC, 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
PX4GUID: 0001000000003938363433365112003e0025
MCU: STM32F42x, rev. 3
[hardfault_log] Fault Log is Armed
INFO  [tune_control] Publishing standard tune 1
ERROR [mtd] failed to initialize mtd driver
INFO  [param] selected parameter default file /fs/microsd/params
Board defaults: /etc/init.d/rc.board_defaults
INFO  [dataman] Unknown restart, data manager file '/fs/microsd/dataman' size is 362560 bytes
INFO  [px4_work_queue] creating: wq:lp_default, priority: 205, stack: 1200 bytes
INFO  [px4_work_queue] creating:WARN  [rgbled] no RGB led on bus wq:I2C1, priority: 248, stack:  #1
1200 bytes
WARN  [rgbled_ncp5623c] no RGB led on bus #1
nsh: rgbled_pwm: command not found
WARN  [blinkm] I2C init failed
WARN  [blinkm] init failed
INFO  [px4_work_queue] creating: wq:hp_default, priority: 244, stack: 1200 bytes
ERROR [param] Parameter SYS_USE_IO not found
Board sensors: /etc/init.d/rc.board_sensors
reset done, 50 ms
WARN  [hmc5883] no device on bus 1 (type: 2)
WARN  [lis3mdl] no device on bus 2
INFO  [ist8310] no device on bus 1
WARN  [bmp280] bus option number is 1
ERROR [bmp280] driver start failed
WARN  [qmc5883] no device on bus 1 (type: 2)
BMM150 on I2C bus 1 at 0x10 (bus: 100 KHz, max: 100 KHz)
HMC5883_SPI on SPI bus 1 at 5 (11000 KHz)
WARN  [hmc5883] no device on bus 1 (type: 3)
WARN  [lis3mdl] no device on bus 2
LIS3MDL_SPI on SPI bus 1 at 7 (11000 KHz)
WARN  [lis3mdl] no device on bus 3
INFO  [px4_work_queue] creating: wq:SPI1, priority: 254, stack: 1200 bytes
BMI055_GYRO on SPI bus 1 at 13 (10000 KHz)
WARN  [mpu6000] no device on bus #3 (SPI1)
WARN  [mpu6000] no device on bus #3 (SPI1)
BMI055_ACCEL on SPI bus 1 at 12 (10000 KHz)
INFO  [mpu9250] Bus probed: 3
WARN  [mpu9250] probe failed! 163
WARN  [mpu9250] no device on bus 3
INFO  [mpu9250] Bus probed: 4
WARN  [mpu9250] probe failed! 255
WARN  [mpu9250] no device on bus 4
BMI160 on SPI bus 1 at 8 (10000 KHz)
INFO  [px4_work_queue] creating: wq:SPI4, priority: 251, stack: 1200 bytes
ERROR [pmw3901] driver start failed
MS5611_SPI on SPI bus 2 at 3 (20000 KHz)
WARN  [ms5611] no device on bus 3
WARN  [bst] no devices found
ERROR [adc] sample timeout
INFO  [mavlink] mode: Config, data rate: 800000 B/s on /dev/ttyACM0 @ 57600B
Starting Main GPS on /dev/ttyS3
Starting MAVLink on /dev/ttyS1
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS1 @ 57600B
INFO  [init] Mixer: /etc/mixers/quad_+.main.mix on /dev/pwm_output0
px4flow [432:100]
Board extras: /etc/init.d/rc.board_extras
INFO  [px4flow] scanning I2C buses for device..
INFO  [mavlink] mode: Normal, data rate: 20000 B/s on /dev/ttyS0 @ 921600B
WARN  [mavlink] hardware flow control not supported
INFO  [logger] logger started (mode=all)

NuttShell (NSH)
nsh> INFO  [ekf2] Mag sensor ID changed to 4395017
INFO  [frsky_telemetry] Scanning timeout: exiting
sensors status
INFO  [sensors] gyro status:
INFO  [ecl/validation] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [ecl/validation] sensor #0, prio: 99, state: OK
INFO  [ecl/validation]  val:  -0.0013, lp:   0.0013 mean dev:   0.0000 RMS:   0.0036 conf:   1.0000
INFO  [ecl/validation]  val:  -0.0357, lp:  -0.0014 mean dev:  -0.0000 RMS:   0.0068 conf:   1.0000
INFO  [ecl/validation]  val:  -0.0020, lp:  -0.0033 mean dev:  -0.0000 RMS:   0.0030 conf:   1.0000
INFO  [ecl/validation] sensor #1, prio: 99, state: OK
INFO  [ecl/validation]  val:   0.0036, lp:   0.0037 mean dev:  -0.0000 RMS:   0.0028 conf:   1.0000
INFO  [ecl/validation]  val:   0.0130, lp:   0.0114 mean dev:   0.0000 RMS:   0.0059 conf:   1.0000
INFO  [ecl/validation]  val:  -0.0019, lp:  -0.0005 mean dev:   0.0000 RMS:   0.0016 conf:   1.0000
INFO  [sensors] accel status:
INFO  [ecl/validation] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [ecl/validation] sensor #0, prio: 99, state: OK
INFO  [ecl/validation]  val:   0.8658, lp:   0.9024 mean dev:  -0.0001 RMS:   0.0258 conf:   1.0000
INFO  [ecl/validation]  val:   1.8004, lp:   1.8140 mean dev:   0.0000 RMS:   0.0214 conf:   1.0000
INFO  [ecl/validation]  val:   9.8190, lp:   9.7706 mean dev:  -0.0001 RMS:   0.0430 conf:   1.0000
INFO  [ecl/validation] sensor #1, prio: 99, state: OK
INFO  [ecl/validation]  val:   0.4750, lp:   0.4561 mean dev:   0.0001 RMS:   0.0230 conf:   1.0000
INFO  [ecl/validation]  val:   1.1768, lp:   1.1800 mean dev:   0.0000 RMS:   0.0217 conf:   1.0000
INFO  [ecl/validation]  val:  10.3383, lp:  10.2785 mean dev:  -0.0003 RMS:   0.0479 conf:   1.0000
INFO  [sensors] mag status:
INFO  [ecl/validation] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [ecl/validation] sensor #0, prio: 100, state: OK
INFO  [ecl/validation]  val:   0.1401, lp:   0.1456 mean dev:   0.0001 RMS:   0.0060 conf:   1.0000
INFO  [ecl/validation]  val:   0.2691, lp:   0.2557 mean dev:  -0.0000 RMS:   0.0091 conf:   1.0000
INFO  [ecl/validation]  val:   0.2855, lp:   0.2813 mean dev:  -0.0001 RMS:   0.0065 conf:   1.0000
INFO  [sensors] baro status:
INFO  [ecl/validation] validator: best: -1, prev best: -1, failsafe: NO (0 events)
INFO  [sensors] Temperature Compensation:
INFO  [sensors]  gyro: enabled: 0
INFO  [sensors]  accel: enabled: 0
INFO  [sensors]  baro: enabled: 0
INFO  [sensors] Airspeed status:
INFO  [ecl/validation]  no data
```

Previous FW:
```
WARN  [platforms__common] Reboot NOW.
[boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
HW arch: PX4FMU_V4
FW git-hash: 7ea0fe7c78e2174fcc6e73323253e2d26045596d
FW version: 1.7.4 0 (17236992)
OS: NuttX
OS version: Release 7.22.0 (118882559)
OS git-hash: 61ccccce09be76a90c2574acea549a8c94596959
Build datetime: May 28 2018 12:31:13
Build uri: BUILD_URI
Toolchain: GNU GCC, 5.4.1 20160609 (release) [ARM/embedded-5-branch revision 237715]
MFGUID: 3938363433365112003e0025
MCU: STM32F42x, rev. 3
UID: 3E0025:33365112:39383634
[hardfault_log] Fault Log is Armed
INFO  [tune_control] Publishing standard tune 1
ERROR [mtd] failed to initialize mtd driver
INFO  [param] selected parameter default file /fs/microsd/params
WARN  [rgbled] no RGB led on bus #1
WARN  [blinkm] I2C init failed
WARN  [blinkm] init failed
nsh: rgbled_pwm: command not found
  BAT_N_CELLS: curr: 0 -> new: 3
ERROR [param] Parameter SYS_USE_IO not found
INFO  [dataman] Unknown restart, data manager file '/fs/microsd/dataman' size is 350216 bytes
WARN  [drivers_board] reset done, 50 ms
MS5611_SPI on SPI bus 2 at 3 (20000 KHz)
WARN  [ms5611] no device on bus 3
WARN  [bst] no devices found
WARN  [hmc5883] no device on bus 1 (type: 2)
WARN  [lis3mdl] no device on bus 2
BMP280_I2C on I2C bus 1 at 0x76 (bus: 100 KHz, max: 100 KHz)
ERROR [bmm150] Internal I2C not available
HMC5883_SPI on SPI bus 1 at 5 (11000 KHz)
WARN  [hmc5883] no device on bus 1 (type: 3)
WARN  [lis3mdl] no device on bus 2
LIS3MDL_SPI on SPI bus 1 at 7 (11000 KHz)
WARN  [lis3mdl] no device on bus 3
BMI055_GYRO on SPI bus 1 at 13 (10000 KHz)
WARN  [mpu6000] no device on bus #3 (SPI1)
WARN  [mpu6000] no device on bus #3 (SPI1)
BMI055_ACCEL on SPI bus 1 at 12 (10000 KHz)
WARN  [mpu9250] probe failed! 163
WARN  [mpu9250] no device on bus 3
WARN  [mpu9250] probe failed! 163
WARN  [mpu9250] no device on bus 4
BMI160 on SPI bus 1 at 8 (10000 KHz)
INFO  [load_mon] stack check enabled
INFO  [mavlink] mode: Normal, data rate: 20000 B/s on /dev/ttyS0 @ 921600B
WARN  [mavlink] hardware flow control not supported
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS1 @ 57600B
INFO  [mavlink] mode: OSD, data rate: 1000 B/s on /dev/ttyS2 @ 57600B
px4flow [232:100]
WARN  [px4flow] scanning I2C buses for device..
INFO  [mavlink] mode: Config, data rate: 800000 B/s on /dev/ttyACM0 @ 57600B
INFO  [init] Mixer: /etc/mixers/quad_+.main.mix on /dev/pwm_output0
INFO  [logger] logger started (mode=all)

NuttShell (NSH)
nsh> sensors status
INFO  [sensors] gyro status:
INFO  [ecl] validator: best: 0, prev best: 1, failsafe: YES (2 events)
INFO  [ecl] sensor #0, prio: 254, state: OK
INFO  [ecl]     val:   0.0064, lp:   0.0014 mean dev:   0.0000 RMS:   0.0041 conf:   1.0000
INFO  [ecl]     val:   0.0074, lp:   0.0007 mean dev:  -0.0000 RMS:   0.0101 conf:   1.0000
INFO  [ecl]     val:  -0.0078, lp:  -0.0034 mean dev:  -0.0000 RMS:   0.0032 conf:   1.0000
INFO  [ecl] sensor #1, prio: 254, state: OK
INFO  [ecl]     val:   0.0578, lp:   0.0045 mean dev:   0.0000 RMS:   0.0036 conf:   1.0000
INFO  [ecl]     val:   0.0064, lp:   0.0092 mean dev:  -0.0001 RMS:   0.0103 conf:   1.0000
INFO  [ecl]     val:  -0.0009, lp:  -0.0018 mean dev:  -0.0000 RMS:   0.0023 conf:   1.0000
INFO  [sensors] accel status:
INFO  [ecl] validator: best: 0, prev best: 1, failsafe: YES (1 events)
INFO  [ecl] sensor #0, prio: 254, state: OK
INFO  [ecl]     val:   0.9650, lp:   0.8647 mean dev:   0.0001 RMS:   0.0300 conf:   1.0000
INFO  [ecl]     val:   1.7540, lp:   1.7704 mean dev:   0.0000 RMS:   0.0241 conf:   1.0000
INFO  [ecl]     val:   9.5691, lp:   9.7514 mean dev:  -0.0000 RMS:   0.0809 conf:   1.0000
INFO  [ecl] sensor #1, prio: 254, state: OK
INFO  [ecl]     val:   0.2472, lp:   0.4230 mean dev:   0.0005 RMS:   0.0282 conf:   1.0000
INFO  [ecl]     val:   1.1354, lp:   1.1930 mean dev:  -0.0005 RMS:   0.0270 conf:   1.0000
INFO  [ecl]     val:  10.4453, lp:  10.3385 mean dev:  -0.0002 RMS:   0.0936 conf:   1.0000
INFO  [sensors] mag status:
INFO  [ecl] validator: best: -1, prev best: -1, failsafe: NO (0 events)
INFO  [sensors] baro status:
INFO  [ecl] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [ecl] sensor #0, prio: 75, state: OK
INFO  [ecl]     val: 994.9175, lp: 994.9290 mean dev:   0.0017 RMS:   0.0131 conf:   1.0000
INFO  [ecl]     val:   0.0000, lp:   0.0000 mean dev:   0.0000 RMS:   0.0000 conf:   1.0000
INFO  [ecl]     val:   0.0000, lp:   0.0000 mean dev:   0.0000 RMS:   0.0000 conf:   1.0000
INFO  [sensors] Temperature Compensation:
INFO  [sensors]  gyro: enabled: 0
INFO  [sensors]  accel: enabled: 0
INFO  [sensors]  baro: enabled: 0
INFO  [sensors] Airspeed status:
INFO  [ecl]     no data
```

**Comment by davids5** [comment]
@dagar it is not this PR that dropped the barro.

master:
```
NuttShell (NSH)
nsh> [boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
HW arch: PX4_FMU_V4
FW git-hash: 232008854154758ab168602af7e8e18a4c92bbbf
FW version: 1.9.0 0 (17367040)
FW git-branch: master
OS: NuttX
OS version: Release 7.28.0 (119275775)
OS git-hash: 423371c7d4012e725ac4ca51323a18df64e581b3
Build datetime: Jun  4 2019 12:05:59
Build uri: localhost
Toolchain: GNU GCC, 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
PX4GUID: 0001000000003938363433365112003e0025
MCU: STM32F42x, rev. 3
[hardfault_log] Fault Log is Armed
INFO  [tune_control] Publishing standard tune 1
ERROR [mtd] failed to initialize mtd driver
INFO  [param] selected parameter default file /fs/microsd/params
Board defaults: /etc/init.d/rc.board_defaults
INFO  [dataman] Unknown restart, data manager file '/fs/microsd/dataman' size is 362560 bytes
INFO  [px4_work_queue] creating: wq:lp_default, priority: 205, stack: 1200 bytes
INFO  [px4_work_queue] creating:WARN  [rgbled] no RGB led on bus wq:I2C1, priority: 248, stack:  #1
1200 bytes
WARN  [rgbled_ncp5623c] no RGB led on bus #1
nsh: rgbled_pwm: command not found
WARN  [blinkm] I2C init failed
WARN  [blinkm] init failed
INFO  [px4_work_queue] creating: wq:hp_default, priority: 244, stack: 1200 bytes
ERROR [param] Parameter SYS_USE_IO not found
Board sensors: /etc/init.d/rc.board_sensors
reset done, 50 ms
WARN  [hmc5883] no device on bus 1 (type: 2)
WARN  [lis3mdl] no device on bus 2
INFO  [ist8310] no device on bus 1
WARN  [bmp280] bus option number is 1
ERROR [bmp280] driver start failed
WARN  [qmc5883] no device on bus 1 (type: 2)
BMM150 on I2C bus 1 at 0x10 (bus: 100 KHz, max: 100 KHz)
HMC5883_SPI on SPI bus 1 at 5 (11000 KHz)
WARN  [hmc5883] no device on bus 1 (type: 3)
WARN  [lis3mdl] no device on bus 2
LIS3MDL_SPI on SPI bus 1 at 7 (11000 KHz)
WARN  [lis3mdl] no device on bus 3
INFO  [px4_work_queue] creating: wq:SPI1, priority: 254, stack: 1200 bytes
BMI055_GYRO on SPI bus 1 at 13 (10000 KHz)
WARN  [mpu6000] no device on bus #3 (SPI1)
WARN  [mpu6000] no device on bus #3 (SPI1)
BMI055_ACCEL on SPI bus 1 at 12 (10000 KHz)
INFO  [mpu9250] Bus probed: 3
WARN  [mpu9250] probe failed! 163
WARN  [mpu9250] no device on bus 3
INFO  [mpu9250] Bus probed: 4
WARN  [mpu9250] probe failed! 255
WARN  [mpu9250] no device on bus 4
BMI160 on SPI bus 1 at 8 (10000 KHz)
INFO  [px4_work_queue] creating: wq:SPI4, priority: 251, stack: 1200 bytes
ERROR [pmw3901] driver start failed
MS5611_SPI on SPI bus 2 at 3 (20000 KHz)
WARN  [ms5611] no device on bus 3
WARN  [bst] no devices found
INFO  [mavlink] mode: Config, data rate: 800000 B/s on /dev/ttyACM0 @ 57600B
Starting Main GPS on /dev/ttyS3
Starting MAVLink on /dev/ttyS1
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS1 @ 57600B
INFO  [init] Mixer: /etc/mixers/quad_+.main.mix on /dev/pwm_output0
px4flow [432:100]
Board extras: /etc/init.d/rc.board_extras
INFO  [px4flow] scanning I2C buses for device..
INFO  [mavlink] mode: Normal, data rate: 20000 B/s on /dev/ttyS0 @ 921600B
WARN  [mavlink] hardware flow control not supported
INFO  [logger] logger started (mode=all)

NuttShell (NSH)
nsh> sensors status
INFO  [sensors] gyro status:
INFO  [ecl/validation] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [ecl/validation] sensor #0, prio: 99, state: OK
INFO  [ecl/validation]  val:  -0.0355, lp:   0.0008 mean dev:   0.0002 RMS:   0.0073 conf:   1.0000
INFO  [ecl/validation]  val:  -0.0822, lp:  -0.0004 mean dev:   0.0002 RMS:   0.0150 conf:   1.0000
INFO  [ecl/validation]  val:  -0.0101, lp:  -0.0029 mean dev:  -0.0001 RMS:   0.0035 conf:   1.0000
INFO  [ecl/validation] sensor #1, prio: 99, state: OK
INFO  [ecl/validation]  val:   0.0232, lp:   0.0043 mean dev:  -0.0000 RMS:   0.0073 conf:   1.0000
INFO  [ecl/validation]  val:   0.0173, lp:   0.0114 mean dev:  -0.0000 RMS:   0.0150 conf:   1.0000
INFO  [ecl/validation]  val:   0.0012, lp:  -0.0015 mean dev:  -0.0001 RMS:   0.0027 conf:   1.0000
INFO  [sensors] accel status:
INFO  [ecl/validation] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [ecl/validation] sensor #0, prio: 99, state: OK
INFO  [ecl/validation]  val:   0.7342, lp:   0.7119 mean dev:   0.0016 RMS:   0.0425 conf:   1.0000
INFO  [ecl/validation]  val:   1.9078, lp:   1.8873 mean dev:   0.0007 RMS:   0.0335 conf:   1.0000
INFO  [ecl/validation]  val:   9.7363, lp:   9.7717 mean dev:  -0.0014 RMS:   0.0956 conf:   1.0000
INFO  [ecl/validation] sensor #1, prio: 99, state: OK
INFO  [ecl/validation]  val:   0.2555, lp:   0.2413 mean dev:   0.0000 RMS:   0.0438 conf:   1.0000
INFO  [ecl/validation]  val:   1.3389, lp:   1.2899 mean dev:  -0.0001 RMS:   0.0365 conf:   1.0000
INFO  [ecl/validation]  val:  10.0707, lp:  10.2898 mean dev:  -0.0009 RMS:   0.1092 conf:   1.0000
INFO  [sensors] mag status:
INFO  [ecl/validation] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [ecl/validation] sensor #0, prio: 100, state: OK
INFO  [ecl/validation]  val:   0.1287, lp:   0.1320 mean dev:   0.0014 RMS:   0.0067 conf:   1.0000
INFO  [ecl/validation]  val:   0.2500, lp:   0.2583 mean dev:  -0.0020 RMS:   0.0088 conf:   1.0000
INFO  [ecl/validation]  val:   0.2804, lp:   0.2795 mean dev:  -0.0022 RMS:   0.0067 conf:   1.0000
INFO  [sensors] baro status:
INFO  [ecl/validation] validator: best: -1, prev best: -1, failsafe: NO (0 events)
INFO  [sensors] Temperature Compensation:
INFO  [sensors]  gyro: enabled: 0
INFO  [sensors]  accel: enabled: 0
INFO  [sensors]  baro: enabled: 0
INFO  [sensors] Airspeed status:
INFO  [ecl/validation]  no data
```

**Comment by davids5** [comment]
@dagar - baro was unrelated issues. Good to Go

**Pull request merged**
