### PR TITLE
WIP: navigator FW takeoff acceptance only require altitude

### LINKED ISSUE #5848: FW takeoff acceptance criteria
I've seen a few different people make this same mistake independently. Plan a full mission with takeoff, waypoints, land. Takeoff manually for some reason and then switch to mission in air and not understand why it's diving to hit the takeoff waypoint. 

@AndreasAntener @LorenzMeier any objection to modifying FW takeoff to accept any altitude > setpoint + acceptance alt? That should allow a regular planned takeoff to still respect the waypoint.

### PR DESCRIPTION
**Pull request by dagar**
As discussed in #5848 accept takeoff waypoints once altitude is achieved for FW. 

I've seen multiple different users confused by this. Sometimes hand launching then switching to mission mode and surprised when the plane dives for the takeoff waypoint. Or tweaking the existing mission while flying, sync causes the mission index to reset to 0 (takeoff), again vehicle dives to takeoff altitude. QGC defaults to creating a takeoff first. I think not having FOH to the takeoff makes it more jarring.

 - closes #5848

### CODE REVIEW

**Comment by AndreasAntener** [comment]
Looks good to me, except this only fixes acceptance of the WP but it would still try to follow the altitude setpoint. Or is this intentional?

**Comment by dagar** [comment]
I'm not sure I follow what you're saying. 
Should it be current acceptant OR alt > alt_sp rather than only altitude acceptance? Now that I think of it that's more in line with what I originally said, although I don't think the difference personally matters to me.

**Comment by AndreasAntener** [comment]
ok, you got me there too. I think your original suggestion makes sense, it should respect the waypoint location on the horizontal plane. IMHO the condition should be `xy reached && alt > alt_sp`

So the way I see it now you would need to change the takeoff handling in the mission logic instead to change the waypoint to be on the current altitude when already above it. That would take care of the dive and still respect the location. No change to the waypoint acceptance logic is needed in that case.

**Comment by LorenzMeier** [comment]
I also think it should respect the waypoint location on the plane. If users want to switch into mission and start with the first regular waypoint we should create a takeoff marker waypoint. That would then allow to differentiate between takeoff sequence, flight sequence and land sequence.

**Comment by dagar** [comment]
Based on the acceptance logic I thought MC was ignoring the waypoint lat/lon once it has sufficient altitude, but I guess that doesn't actually happen due to the mission work item handling?

With that in mind maybe we should instead do more to have and use FOH at all times in mission and make sure the FW takeoff waypoint altitude is reasonable. This is a bit of an architecture question for the line between navigator and the position controller. It's minor, but right now a takeoff position setpoint falls back to acting like a regular position setpoint after gaining altitude. If we get the architecture correct we can avoid repeating ourselves.

I still think most users would want to skip over the takeoff waypoint if they're already in air flying with sufficient airspeed and altitude, but if we can prevent the jarring transition and stupidity (like setting takeoff alt very low) the current behaviour should be fine.

**Comment by LorenzMeier** [comment]
@AndreasAntener Good to go?

**Comment by AndreasAntener** [comment]
No I don't think we should merge this as it would ignore the waypoint position for FW.

> I still think most users would want to skip over the takeoff waypoint if they're already in air flying with sufficient airspeed and altitude, but if we can prevent the jarring transition and stupidity (like setting takeoff alt very low) the current behaviour should be fine.

I disagree. As I said on an other issue I can't find now (...) this entirely depends on the user interface. As long as we plot the takeoff waypoint as a waypoint with a location that the user specifies it indicates that you should fly through it. Counter example is APM: they have the takeoff waypoint always at home, it moves with the vehicle, so it has a different intention.

And IMHO it is anyway wrong to start the mission at waypoint 0 again when the user changes and re-uploads it.

@dagar as for fixing #5848: keeping the altitude if it's above takeoff should happen in the mission logic. It is also architecturally in the right place there because this IS the mission logic. If we want to make the mission logic simplistic again (yes I agree it's now complicated code and error prone on changes), we need the interface to handle all those cases accordingly. For example along those lines: if the user specifies a takeoff somewhere in the field, the GCS would actually send two waypoints: 1) a takeoff above home or completely without location, 2) a regular waypoint where the first point actually is.

**Comment by LorenzMeier** [comment]
I do agree with Andrea's interpretation of the takeoff waypoint and will close this accordingly.

**Pull request closed without merging**
