### PR TITLE
Bug fix: Incorrect APBs used in HRT driver and tone alarm driver.

### PR DESCRIPTION
**Pull request by ksschwabe**
I picked up that some of the HRT timer defines and some of the Tone Alarm driver timer defines were referencing the wrong APB. I think they should all be correct now. This doesn't affect the standard Px4FMU or Pixhawk or Px4IO, since they are using timers that were using the correct APBs. This is just an improvement, if one wants to use another timer for the HRT or Tone Alarm, e.g. porting your own board.

@LorenzMeier: I don't know whether the HRT_TIMER_VECTOR for HRT_TIMER == 9 is correct. It is using STM32_IRQ_TIM1BRK. Shouldn't it be using STM32_IRQ_TIM9? The same question applies for Timers 8, 10 and 11. They are using a variation on the STM32_IRQ_TIM1. I have not changed them since I don't know enough about the timers and the IRQs and don't know what the consequences of that might be.

### CODE REVIEW

**Comment by davids5** [comment]
@ksschwabe , FYI: @LorenzMeier 

This is still not correct.

Timer 1,8-11 are in RCC_APB2
Timer  2-7,12-14 are on RCC_APB1

image

For IRQ steering, this is the breakdown 


STM32_IRQ_TIM1BRK     ------TIM1 Break interrupt/**TIM9** global interrupt
STM32_IRQ_TIM1UP       -------TIM1 Update interrupt/**TIM10** global interrupt
STM32_IRQ_TIM1TRGCOM ---TIM1 Trigger and Commutation interrupts/TIM11 global interrupt
STM32_IRQ_TIM1CC ------------TIM1 Capture Compare interrupt
STM32_IRQ_TIM2 ----------------TIM2 global interrupt
STM32_IRQ_TIM3 ----------------TIM3 global interrupt
STM32_IRQ_TIM4 ----------------TIM4 global interrupt
STM32_IRQ_TIM8BRK ----------TIM8 Break interrupt/TIM12 global interrupt
STM32_IRQ_TIM8UP ------------TIM8 Update interrupt/TIM13 global interrupt
STM32_IRQ_TIM8TRGCOM ---TIM8 Trigger and Commutation interrupts/TIM14 global interrupt
STM32_IRQ_TIM8CC ------------TIM8 Capture Compare interrupt
STM32_IRQ_TIM5 -----------------TIM5 global interrupt
STM32_IRQ_TIM6 -----------------TIM6 global interrupt/DAC1 and DAC2 underrun error interrupts
STM32_IRQ_TIM7 -----------------TIM7 global inte

**Comment by davids5** [comment]
It is probably worth grepping the complete code base for RCC_APB2ENR_TIMxEN  where x is 2-7,12-14 etc

**Comment by ksschwabe** [comment]
@davids5 : Thanks. Well picked up. I have pushed the fix.

When I grepped the repo for other other RCC_APBxENR_TIMyEN patterns I found similar errors in pwm_input.cpp. I have corrected those APBs and pused the changes as well.

Also, thanks for the info regarding the IRQs.

**Comment by davids5** [comment]
@ksschwabe 

Thank you!

**Pull request merged**
