### PR TITLE
Throttle display zero in flight

### PR DESCRIPTION
**Pull request by moreba1**
there is a issue that throttle displaying 0 in qgroundcontrol oscillating during flight  .

### CODE REVIEW

**Comment by dagar** [comment]
> there is a issue that throttle displaying 0 in qgroundcontrol oscillating during flight .

Could you explain how this addresses the problem?

**Comment by moreba1** [comment]
> Could you explain how this addresses the problem? There's also a compile failure.

msg.throttle = 0.0f

this line makes that zero throttle send by mavlink .

**Comment by moreba1** [comment]
image

**Comment by LorenzMeier** [comment]
PX4 master works as expected on a plane:
Screen Shot 2020-03-08 at 14 09 27

On a vtol:
Screen Shot 2020-03-08 at 14 10 56

On a multicopter:
Screen Shot 2020-03-08 at 14 12 30

**Comment by LorenzMeier** [comment]
And this is disarmed -> armed -> takeoff -> transition:
Screen Shot 2020-03-08 at 14 14 26

And back transition:
Screen Shot 2020-03-08 at 14 14 56

**Comment by moreba1** [comment]
so detecting arm state dont work properly for me

**Pull request closed without merging**
