### PR TITLE
MC pos control: Enforce minimum throttle in manual attitude control m…

### PR DESCRIPTION
**Pull request by LorenzMeier**
…ode only if not landed, else default to idle throttle.

@sjwilks This is not the fix to your problem, but it should help generally with the convenience of manual attitude control flights as the idle throttle is now less high, but can still be set for in-flight to a level where the stabilisation is safe. False detections are unlikely in a steep descend situation, so the only potential issue is to have too high idle on the ground, which will be fine once you have resolved the spin-up issue.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@sjwilks I've flight tested this - the ESCs indeed don't spin up all at once on the isolated ones from DJI, but that's because this value here needs adjustment:
https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/4010_dji_f330#L26

**Comment by LorenzMeier** [comment]
@sjwilks The problem might be the arming ramp. With throttle set to zero all motors are clamped to the ramp. With non-zero throttle there is some variance possible. This hand-held tilted arming sequence shows this nicely:

http://dash.oznet.ch/view/86FAuPvscBWNGYj48fsCiT#Actuators_PLOT

So we need to fix the ramp, nothing else.

**Comment by SimonWilks** [comment]
@LorenzMeier thanks. In what way did you adjust the PWM MIN value? We'll be flight testing again this Tuesday if that helps test further (ie: ramp changes).

**Comment by LorenzMeier** [comment]
@sjwilks I'll push a couple of commits, what they change is:

  * They scale the control inputs over the full ramp [with x^3](http://www.wolframalpha.com/input/?i=plot+x*x*x+between+0+and+1+and+plot+x*x+between+0+and+1), which means that the controls will only become effective towards the end of the ramp, when the motors have already spun up.
  * I'm improving the in-air detection, which should lead to lower-speed idling when no GPS lock is present.

  *

**Comment by LorenzMeier** [comment]
@sjwilks This is good to go now. You should see very low throttle when arming with GPS, slightly higher throttle when arming without and you should see all four motors spin up at the same time in any case. Logs appreciated.

**Comment by LorenzMeier** [comment]
@AndreasAntener In case you get a chance to fly this in a lunch break with your little quad..

**Comment by AndreasAntener** [comment]
I'll give it a try shortly. On the second last commit you actually mean *slow* descents right?

**Comment by AndreasAntener** [comment]
How is PWM_MIN and MPC_THR_MIN related? Is THR_MIN added on top of PWM_MIN (looks like it from the second log)? I see there are new PWM_* parameters in addition to the config value. Which one has priority?

All the props spin up at the same time now, but way to high (double PWM_MIN, it flipped when I didn't hold it down):
http://dash.oznet.ch/view/R8N3MkSm89y5AZSbP44vK4
screen shot 2015-06-29 at 15 09 24

Here's a nice log showing the ramp plus reacting to GPS right after:
http://dash.oznet.ch/view/Wv8juxCQXz24CjXEXtUQuB
screen shot 2015-06-29 at 15 19 28

**Comment by AndreasAntener** [comment]
Are the PWM_* parameters even used? I only see that they are being read so they appear in QGC but they don't have the values set in my startup config.

**Comment by AndreasAntener** [comment]
In case this helps, arming with lower PWM_MIN (1100) results in the same ramp:
screen shot 2015-06-29 at 15 59 45

**Comment by LorenzMeier** [comment]
You're confusing environment variables with parameters used within the process. If you use ```set PWM_MIN p:PWM_MIN``` you can tell the PWM output driver to use the system parameter instead of the environment variable.

The transfer function must be wrong regarding the offset, but the scaling of the motor spread seems to work nicely.

The math for the absolute PWM value is simple: PWM_MIN + (PWM_MAX - PWM_MIN) * (max(MPC_THR_MIN, current_throttle))

**Comment by LorenzMeier** [comment]
The response to GPS looks good, once we fixed the ramp shape and absolute PWM values. Thanks for the test!

**Comment by AndreasAntener** [comment]
I'm perfectly aware of the difference between them ;), but I found no usage of the parameters. Now I see, so for future configs or config changes it would make sense to use `set PWM_MIN p:PWM_MIN` and set the actual values in the parameters?

**Comment by AndreasAntener** [comment]
Thanks for clarifying the absolute PWM, all makes sense now.

**Comment by LorenzMeier** [comment]
@AndreasAntener I worked out what I did wrong and re-created the branch with a different approach. Please delete the previous state, checkout fresh and try. It should behave now.

**Comment by AndreasAntener** [comment]
I'll test this again as soon as I can, together with another release test I guess

**Comment by LorenzMeier** [comment]
Any chance for lunch testing today? Its upsetting users and I'm drowning in all the other stuff already 8).

**Comment by AndreasAntener** [comment]
Didn't arm anymore, will check after lunch

**Comment by AndreasAntener** [comment]
Not arming was my fault, but I still got the same behaviour as before

**Comment by LorenzMeier** [comment]
Would you mind sharing the log? Note the MAVLink FTP implementation which makes transfer of short logs a breeze. Since I changed so much it can't be the same as before, unless you're referring to "the same as in stable / master".

**Comment by AndreasAntener** [comment]
No, I'm referring to same behaviour as I stated last time

**Comment by AndreasAntener** [comment]
Wait, let me check it really pulled the new state, might not be my day today...

**Comment by AndreasAntener** [comment]
Cool, it's working, nice ramp ;)

without GPS:
screen shot 2015-07-01 at 16 04 07

getting GPS:
screen shot 2015-07-01 at 16 04 19

with GPS:
screen shot 2015-07-01 at 16 04 32

**Comment by AndreasAntener** [comment]
One ofthose: http://dash.oznet.ch/view/STvBhEFswEUxwK9pPqHRDX

**Comment by LorenzMeier** [comment]
Thanks for the testing!

**Pull request merged**
