### PR TITLE
Update to current ecl library

### PR DESCRIPTION
**Pull request by priseborough**
Includes the following functional fixes and updates:

1.  Efficiency improvements to sensor data buffering that reduce memory and number of data copy operations.
https://github.com/PX4/ecl/pull/358
https://github.com/PX4/ecl/pull/359

2. Adds control interface and internal functions fora Baro ground effect disturbance compensation model that can be activated externally.
https://github.com/PX4/ecl/pull/351

3. Adds an interface and internal functionality for fusion of  landing target velocity observations.
https://github.com/PX4/ecl/pull/362

4. Provides external accessor for FW attitude control integrator state
https://github.com/PX4/ecl/pull/366

5. Adds missing initialisation of ekf class variables.
https://github.com/PX4/ecl/pull/364

6. Fixes https://github.com/PX4/Firmware/issues/8401 loss of navigation message being printed on startup.
https://github.com/PX4/ecl/pull/367

### CODE REVIEW

**Comment by priseborough** [comment]
Requires flight test on RW and FW.

**Comment by priseborough** [comment]
@LorenzMeier Out of all the ecl changes pulled in by this PR, only the fix for https://github.com/PX4/Firmware/issues/8401 is a bug fix. If you want bug fixes for Release 1.7, but not the added features, I can create a branch of ecl for the 1.7 release that only adds https://github.com/PX4/ecl/pull/364 and https://github.com/PX4/ecl/pull/367

**Comment by LorenzMeier** [comment]
I guess a separate branch makes sense. Please keep this PR open as we want to focus on v1.8 on master here soon.

**Comment by priseborough** [comment]
Here's the update for the v1.7.0 release https://github.com/PX4/Firmware/pull/8406

**Comment by dagar** [comment]
Rebased and ready for flight testing. @santiago3dr @r0gelion

**Comment by dagar** [comment]
image

**Comment by priseborough** [comment]
This is no longer required because https://github.com/PX4/Firmware/pull/8489 has been merged.

**Pull request closed without merging**
