### PR TITLE
Update submodule ecl to latest Sun Oct 13 08:37:25 EDT 2019

### PR DESCRIPTION
**Pull request by dagar**
- ecl in PX4/Firmware (a1b8ce29f32c6430e8be21a6475f93055ab0a938): https://github.com/PX4/ecl/commit/f005e0ea8f33d10dd014a0700e712426540bb58a
    - ecl current upstream: https://github.com/PX4/ecl/commit/eae6e8f19c0a587e54beea1bb461c8bb9aae4ccf
    - Changes: https://github.com/PX4/ecl/compare/f005e0ea8f33d10dd014a0700e712426540bb58a...eae6e8f19c0a587e54beea1bb461c8bb9aae4ccf

    eae6e8f 2019-08-06 Paul Riseborough - EKF: Fix on ground yaw drift when using EKF2_MAG_TYPE = 4
    4e946d5 2019-09-04 RomanBapst - implemented synthesized magnetometer Z measurement - calculate a theoretical value based on the knowledge of the direction and strength of the magnetic field vector and X/Y sensor measurements - needs knowledge about location on earth to work

### CODE REVIEW

**Comment by dagar** [comment]
Updated again by PX4Buildbot.

image

**Comment by nkadioglu** [comment]
`Created by TestQuality - Linked to TestQuality.com requirement R3. Do not remove or edit.` [R3](https://3dr.testquality.com/project/6731/testcase/176086/requirement/8304)

**Comment by Tony3dr** [comment]
> rangefinder and an optical flow sensor.
@bresch, unfortunately, we don't have vehicles with rangefinder or optical flow sensor.

**Comment by dagar** [comment]
It's riskier to let all of these unrelated ecl changes pile up and come in at once. I've checked all the ECL PRs accounted for here and they've all been tested individually to some extent. Merging.

 - https://github.com/PX4/ecl/pull/638
 - https://github.com/PX4/ecl/pull/628
 - https://github.com/PX4/ecl/pull/656
 - https://github.com/PX4/ecl/pull/650
 - https://github.com/PX4/ecl/pull/658
 - https://github.com/PX4/ecl/pull/635
 - https://github.com/PX4/ecl/pull/655

**Pull request merged**
