### PR TITLE
[DO NOT MERGE] Add several non-function ECL changes

### PR DESCRIPTION
**Pull request by kamilritz**
This PR brings several non-functional ECL changes to Firmware. Some of them already went into ECL master:
https://github.com/PX4/ecl/pull/674
https://github.com/PX4/ecl/pull/676
https://github.com/PX4/ecl/pull/678
https://github.com/PX4/ecl/pull/681
https://github.com/PX4/ecl/pull/684
https://github.com/PX4/ecl/pull/686
https://github.com/PX4/ecl/pull/687
https://github.com/PX4/ecl/pull/690

Some of them are still pending as PR:
https://github.com/PX4/ecl/pull/688
https://github.com/PX4/ecl/pull/694
https://github.com/PX4/ecl/pull/696

We collected these in general non-functional changes to extensively flight test them together.
@PX4/testflights Can you flight test this extensively? Thank you very much!

Please do not merge this PR.

### CODE REVIEW

**Comment by kamilritz** [comment]
@dagar This will not fit on the holybro durandal.

**Comment by dagar** [comment]
> @dagar This will not fit on the holybro durandal.

It's the stackcheck build. https://nuttx.org/doku.php?id=wiki:howtos:run-time-stack-checking

You can comment it out in the builds for now and I'll re-evaluate later to see if there's still value.

 - https://github.com/PX4/Firmware/blob/031680a5206e45c520cff975c549ebddebaf8cdc/.ci/Jenkinsfile-compile#L40
 - https://github.com/PX4/Firmware/blob/031680a5206e45c520cff975c549ebddebaf8cdc/.ci/Jenkinsfile-hardware#L507-L589

My guess is that the matrix::SquareMatrix operations in ecl/EKF are no longer being inlined with every single call being instrumented.

**Comment by kamilritz** [comment]
@Tony3dr do you have an estimate on when you can test this?

**Comment by Tony3dr** [comment]
> @Tony3dr do you have an estimate on when you can test this?

@kamilritz this will be tested today, the Team is out in the field now.

**Comment by Junkim3DR** [comment]
### Tested on NXP FMUK66 v3

**Flight Card 1**

- Modes Tested
 - Position Mode: Good.
 - Altitude Mode: Good.
 - Stabilized Mode: Good.

- Procedure: Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode.

- Notes: No issues noted, good flight in general.

**Logs**
https://review.px4.io/plot_app?log=b3a00234-ebd9-4f9c-b660-a11785e8e938






**Flight Card 2**

- Modes Tested
 - Mission Plan Mode (Automated): Good.
 - RTL (Return To Land): Good.

- Procedure: Arm and Take off in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

- Notes: No issues noted, good flight in general.

**Logs**
https://review.px4.io/plot_app?log=7f8f012a-e649-452a-9b6f-9d32ac2d8a38












**Flight Card31**

- Modes Tested
 - Position Mode: Good.
 - Mission Plan Mode (Automated): Good.
 - RTL (Return To Land): Good.

- Procedure: Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

- Notes: No issues noted, good flight in general.

**Logs**
https://review.px4.io/plot_app?log=3f58536c-5c41-4308-b6b4-7e0ce8bde629









**Flight Card 4**

- Modes Tested
 - Position Mode: Good.
 - Mission Plan Mode (Automated): Good.
 - RTL (Return To Land): Good. 

- Procedure: Arm and Take off in position mode, after flying for approximately one minute, turned RC off in order to activate failsafe RTL, wait for vehicle to return and land as expected.

- Notes: No issues noted, good flight in general.

**Logs**
https://review.px4.io/plot_app?log=9702e9c9-f72f-4005-87fe-28e38e5c7217

**Comment by dannyfpv** [comment]
Tested on pixhawk4 v5 f-450
Flight Card 1

Modes Tested

Position Mode: Good.

Altitude Mode: Good.

Stabilized Mode: Good.

Procedure: Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode.

Notes: No issues noted, good flight in general.

Logs

https://review.px4.io/plot_app?log=a215c05c-3a98-4dfd-9623-cba6110ca888

Flight Card 2

Modes Tested

Mission Plan Mode (Automated): Good.

RTL (Return To Land): Good.

Procedure: Arm and Take off in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

Notes: No issues noted, good flight in general.

Logs

https://review.px4.io/plot_app?log=2a1710e5-eab8-4da2-84a5-1f1bd633d713


Flight Card 3

Modes Tested

Position Mode: Good.

Mission Plan Mode (Automated): Good.

RTL (Return To Land): Good.

Procedure: Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

Notes: No issues noted, good flight in general.

Logs

https://review.px4.io/plot_app?log=8390f051-461b-48cb-97cf-6ebeb1f129e7

Flight Card 4

Modes Tested

Position Mode: Good.

Mission Plan Mode (Automated): Good.

RTL (Return To Land): Good.

Procedure: Arm and Take off in position mode, after flying for approximately one minute, turned RC off in order to activate failsafe RTL, wait for vehicle to return and land as expected.

Notes: No issues noted, good flight in general.

Logs

https://review.px4.io/plot_app?log=3fd9d652-2401-4449-99ac-2c20f902f6ea

**Comment by kamilritz** [comment]
@PX4/testflights Thank you very much!

**Pull request closed without merging**
