### PR TITLE
reduce ALTCTL Z deadband from 40% to 5%

### PR DESCRIPTION
**Pull request by kd0aij**
I like this a lot better for LOS ALTCTL with the QAV250. Will try FPV goggles tomorrow.

### CODE REVIEW

**Comment by dagar** [comment]
What do you think about making this a param instead?

**Comment by kd0aij** [comment]
That makes sense if there's a good reason to provide such a large deadband. But the only thing deadband does is throw away control precision and make the controls feel sloppy. Expo is the typical means of reducing control sensitivity near center stick without introducing "play". 

But perhaps I'm just unaware of the use case (or controller type) that drives the requirement for a large deadband. In that case maybe the deadband should be mode (or controller) dependent.

**Comment by LorenzMeier** [comment]
@kd0aij You're assuming a spring loaded throttle. Without that 5% will never work for the user. How about trying 10% and seeing if that works? I'm trying to avoid building a system where you need to configure 100 parameters before it works well for you.

**Comment by kd0aij** [comment]
@LorenzMeier :( When I tested this PR at 5% in LOS flight, I was using a Taranis X9D (mode 2) with no spring or ratchet on the throttle stick. What I like about zero deadband is that it gives me better control of vertical speed. Controlling a mult-rotor's vertical speed should be much easier in ALTCTL than in manual mode.

I'm trying to avoid making assumptions, and that's the reason I asked above whether there's a use case (unknown to me) which drives the requirement for a large deadband. My apologies if this issue reflects plain ignorance or a lack of research on my part.

I _assume_ that some pilots would prefer a spring-loaded throttle for multi-rotors, but I consider that a safety hazard for pilots who fly multiple aircraft types.

@tumbili I'd appreciate your opinion on the utility of deadband with the current (much improved) ALTCTL functionality.

**Comment by kd0aij** [comment]
@LorenzMeier Forgot to mention that I agree with you on keeping the number of parameters to a minimum. That's why I started this discussion on requirements.

**Comment by kd0aij** [comment]
Just tested FPV flight. I found ALTCTL to be much easier than manual mode in tight areas requiring precise altitude changes while maneuvering. Is anyone else out there who can try this with a multirotor?

**Comment by LorenzMeier** [comment]
Hey Mark - if you don't user a spring loaded throttle you've already made the point that the deadband is too large right now and it works with 5%. That fundamentally changes my assessment.

**Comment by LorenzMeier** [comment]
I've applied it to master, thanks!

I very much appreciate your constant push for usability. I know its painstaking to find and address and motivating change with other developers can be painstaking as well.

Rock on!

**Comment by kd0aij** [comment]
Thanks, Lorenz. I hope other pilots agree with me.

Here's a plot from my first FPV flight in ALTCTL mode with the small deadband. This portion of the flight was from 1.5 to 3.5m AGL navigating under trees at very low groundspeeds and throttle stick position ranges about +/-25% with very little time spent in the deadband. I'm a bit surprised at how much the vertical speed varies, but the actual altitude plot looks pretty smooth, as was my perception of altitude in the goggles.
Maybe, with some practice, the vertical speeds will smooth out too. I also need to try a course where I can fly faster with less risk of collisions. 

fpv_throttle_alt
http://logs.uaventure.com/view/qrwNZBuwppfheHP4gZBYF4

**Pull request closed without merging**
