### PR TITLE
NXP i.MXRT port of PX4 FMUv5

### PR DESCRIPTION
**Pull request by davids5**
Continuation of https://github.com/PX4/Firmware/pull/11351 rebased-ed on master and reorganized with drivers moved to platforms

This is the initial Work In Progress of a PX4 FMUv5 port to the NXP iMXRT 1062 SoC. 

Current Code bringup is being done on the [MIMXRT1060-EVK: i.MX RT1060 Evaluation Kit](https://www.nxp.com/support/developer-resources/run-time-software/i.mx-developer-resources/mimxrt1060-evk-i.mx-rt1060-evaluation-kit:MIMXRT1060-EVK)

Since the EVK hardware is application specific, full integration testing is not possible untile the real HW is ready.

Therefor there are some #ifdefs that ensure we do not create a contention on pins other then on J22 - J25. 

This branch is subject to change via forced pushed!

Status:
- [x] PLL and Clock Tree 576Mhz
- [x] hrt - tested 
  - [x] PPM 
- [x] Tone alarm
- [x] PWM 
  - [x] PWM Source 16Mhz input clock derivation via TMR3:0 and XBAR - tested
  - [x] PWM  Output
- [x]  Status LEDs
- [x] ADC
  - [x] HW rev/ver
- [x] SPI (Functional performance is not tuned yet)
- [x] I2C
- [x] SDIO 
- [x] GPIO/XBAR/DAISY - tested
- [ ] USB
     - [X] USB VBUS detection
- [x]  UARTS
- [ ]  DMA
- [ ] Bootloader
- [x] UUID and CPU info

### CODE REVIEW

**Comment by davids5** [comment]
@PX4/testflights Please fly this on V5, V4, V2

**Comment by dannyfpv** [comment]
Tested on pixhawk4 v5 f-450
Flight Card 1

Modes Tested

Position Mode: Good.

Altitude Mode: Good.

Stabilized Mode: Good.

Procedure: Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode.

Notes: No issues noted, good flight in general.

Logs

https://review.px4.io/plot_app?log=79aefba3-1bf4-46ed-a109-7f3e6d8dc940
Flight Card 2

Modes Tested

Mission Plan Mode (Automated): Good.

RTL (Return To Land): Good.

Procedure: Arm and Take off in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

Notes: No issues noted, good flight in general.

Logs

https://review.px4.io/plot_app?log=ee4f5c58-58c8-4eae-89a4-cee5b9b338ad

Flight Card 3

Modes Tested

Position Mode: Good.

Mission Plan Mode (Automated): Good.

RTL (Return To Land): Good.

Procedure: Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

Notes: No issues noted, good flight in general.

Logs

https://review.px4.io/plot_app?log=a8f1fd41-c614-46ac-b4e2-4be0b65b2dd6

Flight Card 4

Modes Tested

Position Mode: Good.

Mission Plan Mode (Automated): Good.

RTL (Return To Land): Good.

Procedure: Arm and Take off in position mode, after flying for approximately one minute, turned RC off in order to activate failsafe RTL, wait for vehicle to return and land as expected.

Notes: No issues noted, good flight in general.

Logs

https://review.px4.io/plot_app?log=936b8f0b-e2e9-41b7-90b9-97e6b6d08999

**Comment by jorge789** [comment]
### Tested on PixRacer V4:                             
                                                                
**Flight Card 1**

**Modes Tested:**
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.

**Procedure:**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode.

**Notes:**
No issues were noted, good flight in general.

**Logs:**  https://review.px4.io/plot_app?log=27e13846-692c-4b64-872e-2139316e7b07

**Flight Card 2**

**Modes Tested**
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**

Armed form QGC.
Took-off on mission plan mode
. Note that commands were sent form QGC (Armed and takeoff)
Once all waypoint completed vehicle switched to RTL and landed as expected.
Good flight in general.
**Note:**
No issues were noted, good flight in general.

**Logs:**  https://review.px4.io/plot_app?log=2d760f29-a076-4a88-a6f1-f8508de59b7c

 Flight Card 3

**Modes Tested**
Position Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.
Good flight in general.

**Note:**
No issues were noted, good flight in general.

**Logs:**  https://review.px4.io/plot_app?log=e22c7098-df03-4359-9a5e-37b199291da4

**Flight Card 4**

**Modes Tested**
Fail safe:The radio control turned off and the vehicle returned and landed correctly.
Tested good.

Logs:  https://review.px4.io/plot_app?log=7c795685-670e-4e13-ae89-a7e92876ee60





### Issue Note

**Issue Description**
Issue persists, vehicle keeps showing an incorrect altitude reading with a discrepancy of 5 to 10 meters.

**Problem Caused by the Issue**
Since the vehicle reads the altitude incorrectly, it lands with force and bounces off the ground.

**Comment by jorge789** [comment]
### Tested on PixRacer V4:                       

**Flight Card 1**

**Modes Tested:**
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.

**Procedure:**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode.

**Notes:**
No issues were noted, good flight in general.

**Logs:**  https://review.px4.io/plot_app?log=94f53b16-d13d-4fab-b4c5-679bf6117ac9

**Flight Card 2**

Modes Tested
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**

Armed form QGC.
Took-off on mission plan mode
. Note that commands were sent form QGC (Armed and takeoff)
Once all waypoint completed vehicle switched to RTL and landed as expected.
Good flight in general.
**Note:**
When the vehicle was landing, it did not descend vertically, drifted away with the wind and landed the vehicle manually

**Logs:**  https://review.px4.io/plot_app?log=67a2120c-a473-43a3-a556-6a542f62f7b1

**Comment by davids5** [comment]
@dagar waiting on nuttx to merge my pending commits.  But this is go to go once I back port them.

**Comment by davids5** [comment]
@dagar https://github.com/PX4/NuttX/pull/81 now has the backports. Once this passes CI it should come in. 

There is still some work to be done, and it will be done on a new branch. 

FYI: @bkueng This should come in today.

**Pull request merged**
