### PR TITLE
Quaternion logging

### PR DESCRIPTION
**Pull request by tumbili**
Removed secondary attitude and logged quaternion.

### CODE REVIEW

**Comment by tumbili** [comment]
Waiting for @LorenzMeier to come up with the transformation quaternion

**Comment by LorenzMeier** [comment]
@tumbili I believe you can represent your transformations like this:
```
R_out = R_transform * R_diag
```
With:
```
R_transform =

     0     0     1
     0     1     0
    -1     0     0


R_diag =

     1     0     0
     0     1     0
     0     0     1


R_out =

     0     0     1
     0     1     0
    -1     0     0
```

**Comment by LorenzMeier** [comment]
Given that the flight code does not depend on this and merging it will clean up logging, I'm merging now.

**Comment by LorenzMeier** [comment]
Applied via rebase.

**Comment by tumbili** [comment]
The problem is that your example just works if the plane does not roll/yaw. This is because the pitch axis is the same for fw and mc. But as soon as you have yaw/roll values your rotation matrix will not be correct anymore.
Example: Imagine the plane (treating it as a multicopter) is yawing 0.5 rad and pitching forward -pi/2. If you now treat the plane as a fw you realize that this is equivalent to only yawing 0.5 rad.
Now let us look at the rotation matrices:
The original mc rot matrix looks somehow like this:
R_mc =
    0.0000   -0.7071   -0.7071
    0.0000    0.7071   -0.7071
    1.0000         0        0.0000

now R_transform * R_mc = 
    1.0000         0    0.0000
    0.0000    0.7071   -0.7071
   -0.0000    0.7071    0.7071

but it should be
    0.7071   -0.7071    0.0000
    0.7071    0.7071    0.0000
   -0.0000         0       1.0000

You can see that it is wrong already due to the fact that
the first column is unaltered which would mean that the plane is rolling but it is actually yawing.

**Comment by tumbili** [comment]
Bottom line is that you can always do attitude transformations as long as your body axes are consistent meaning the stay the same. The problem is that we are rotating the body frame of the plane from mc to fw and that is why I believe you cannot represent this with a simple rotation.

**Comment by tumbili** [comment]
But I have to give in that your representation of matrices in github looks much better than my copy paste version :-)

**Comment by thomasgubler** [comment]
@tumbili what about post-multiplication: sth. like `R_out = R_mc * R_transform`

**Comment by tumbili** [comment]
@thomasgubler Yes, this will work, and I honestly didn't think of that. I the long term I think we are looking for one reference frame for both mc and fw for VTOL but for now this the cleanest solution.
Thanks!

**Pull request closed without merging**
