### PR TITLE
Yaw mode manual auto

### PR DESCRIPTION
**Pull request by Stifael**
Based on the discussion [here](https://github.com/PX4/Firmware/issues/9114).

What this PR does:
* move logic defined by MIS_YAWMODE to mc_pos_control
* Navigator has higher priority than mc_pos_control to set yaw (only applies to auto) 
  *  Navigator sends yaw if: waypoint contains yaw (!=NAN), ROI is turned on but mount has no yaw control
* MIS_YAWMODE has an affect on manual (pleas give feedback if that makes sense)
   * `0`: yaw is not changed and is equal to the yaw when MIS_YAWMODE switched to 0
   * `1`: yaw is controlled from sticks
   * `2`: heading points towards home if available. otherwise mode `0` applies.
   * `3`: heading points away from home if available. otherwise 1 mode `0` applies.

~~Although MIS_YAWMODE is not used in the navigator anymore, I kept this parameter for legacy reason.~~

@dagar, I was very confused about the `heading_sp_update` method (https://github.com/PX4/Firmware/compare/yaw_mode_manual_auto?expand=1#diff-9b5a77642a641b107c8f8a966de34acdL222), in particular about the different flags. For instance, to me it is not clear why the heading update method gets entered if the vehicle is a vtol...

The biggest advantage of PR is that for MC, the triplets are no longer sent continuously during mission.

### CODE REVIEW

**Comment by dagar** [comment]
I think the MIS_YAWMODE parameter can move to MPC and be renamed appropriately. Generally we want to minimize parameter churn to not break configurations, but in this case the vast majority will be unaffected. We should still make note of the change and call it out in the release notes.

**Comment by Stifael** [comment]
@dagar I replaced it. 
However, I am still wondering if this breaks anything vtol related, mainly because of this check here:
https://github.com/PX4/Firmware/pull/9146/files#diff-9b5a77642a641b107c8f8a966de34acdL222

**Comment by Stifael** [comment]
@RomanBapst do you have any insight about vtol yaw handling in the navigator? In particular, why this [line](https://github.com/PX4/Firmware/pull/9146/files#diff-9b5a77642a641b107c8f8a966de34acdL222) was required?

**Comment by dagar** [comment]
Obviously we need to check every case, but I'm reasonably certain the proper thing to do is not treat VTOL any differently. The vtol "controller" is capable of overriding the attitude setpoint for things like weathervane mode (ie yaw rate crippling).

**Comment by Stifael** [comment]
@dagar, you are saying that [here](https://github.com/PX4/Firmware/pull/9146/files#diff-9b5a77642a641b107c8f8a966de34acdR218) is also should check for VTOL?

**Comment by dagar** [comment]
A single is_rotary_wing check should be sufficient. The is_rotary_wing flag is true when a VTOL is in MC mode.

**Comment by dagar** [comment]
Sorry, we lost track of this PR. Let me know when you're ready to move forward with it.

**Comment by Stifael** [comment]
close this since obsolete

**Pull request closed without merging**
