### PR TITLE
sim drivers rework

### PR DESCRIPTION
**Pull request by nicolaerosia**
This series reworks all sim drivers.

### CODE REVIEW

**Comment by dagar** [comment]
Just curious, what problems were you encountering?

Did we really not have mag at all in those simulations?

**Comment by nicolaerosia** [comment]
none - it was bugging me.
We did - accelsim was both accelerometer and magnetometer, gyrosim was both gyro and accel.

**Comment by nicolaerosia** [comment]
@dagar if you pick this, could you please rebase? I don't have bw for this atm

**Comment by dagar** [comment]
I'm not yet familiar with this code, but I can rebase and test. I'm wondering if this would be a better simulation interface for HIL, but I'll save that for later.

**Comment by nicolaerosia** [comment]
@dagar @LorenzMeier worth noting is that simulator_mavlink can also publish this data:
https://github.com/PX4/Firmware/blob/master/src/modules/simulator/simulator_mavlink.cpp#L994
which defeats the idea of having separate drivers. I would also note they are incomplete in the sense that they don't do any filtering or whatsoever.

Having everything published from a single place (simulator_mavlink) has the advantage of knowing immediately when there is fresh date since that's the place where it is received over MAVLink. The disadvantage would be that the code gets complex if we want to be able to publish the data at a fixed frequency without respect to the actual rate that we're getting the data.

Currently we get sensor data over MAVLink messages at a rate which is controlled by sitl_gazebo:
https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_imu_plugin.cpp#L240
https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_mavlink_interface.cpp#L428
https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_mavlink_interface.cpp#L788
If we publish the data from simulator_mavlink (of course, we can do the filtering, etc there), we will match that.
If we want to keep separate drivers, we can choose whatever frequency, with the comment that if the our publish frequency is higher than the one from sitl_gazebo, we are publishing the same data.

In any case, we should decide and keep only one since it's confusing.

**Comment by dagar** [comment]
I'd like to look at getting this in soon.

**Pull request closed without merging**
