### PR TITLE
[Ekf] controlMagFusion refactor and mag field strength check

### PR DESCRIPTION
**Pull request by bresch**
Ecl update to include https://github.com/PX4/ecl/pull/662

### CODE REVIEW

**Comment by bresch** [comment]
@PX4/testflights can you test that on several vehicles please?

**Comment by dagar** [comment]
To get it building you'll need to rebase or merge newer PX4/ecl after https://github.com/PX4/ecl/pull/665.

**Comment by jorge789** [comment]
### Tested on PixRacer V4:

**Flight Card 1**

Modes Tested:
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.

Procedure:
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode.

Notes:
No issues were noted, good flight in general.

**Logs:**  https://review.px4.io/plot_app?log=64df3ac7-f119-44de-bada-c32240a6836e

**Flight Card 2**

Modes Tested
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure:**
Armed form QGC.
Took-off on mission plan mode
. Note that commands were sent form QGC (Armed and takeoff)
Once all waypoint completed vehicle switched to RTL and landed..

**Note:**
**When the vehicle was landing, and I touched the ground, it began to make small leaps, but did not land completely after a few seconds, it was necessary to land manually.**

**Logs:**  https://review.px4.io/plot_app?log=4052c3e7-2718-4fcf-83e9-4480bdf2da4c

**Flight Card 3**
**Modes Tested**

Position Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
When the vehicle was landing, and I touched the ground, it began to make small leaps, but did not land completely after a few seconds, it was necessary to land manually.

**Logs:**  https://review.px4.io/plot_app?log=b5801c80-c580-4582-ad8c-0d6dbac3aa25

**Comment by dannyfpv** [comment]
Tested on Pixhawk4 v5 f-450
Flight Card 1

Modes Tested:
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.

Procedure:
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode.

Notes:
No issues were noted, good flight in general.

log: 
https://review.px4.io/plot_app?log=9253ad7d-088f-4d19-bc49-d721a3663e6f

Flight Card 2

Modes Tested
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

Procedure:
Armed form QGC.
Took-off on mission plan mode
. Note that commands were sent form QGC (Armed and takeoff)
Once all waypoint completed vehicle switched to RTL and landed..

Note:
When the vehicle was landing, and I touched the ground, it began to make small leaps, but did not land completely after a few seconds, it was necessary to land manually.

Logs: 
https://review.px4.io/plot_app?log=00ce36e8-b95a-4b53-8bbe-28cf371e00c0


Flight Card 3
Modes Tested

Position Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

Procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

Note:
When the vehicle was landing, and I touched the ground, it began to make small leaps, but did not land completely after a few seconds, it was necessary to land manually.

Logs: 
https://review.px4.io/plot_app?log=afdebd06-a22f-4c1f-9519-fea7e7307dd7


Flight Card 3
fail safe test
log:
https://review.px4.io/plot_app?log=3ec413de-9d5d-482d-bf1d-274bfa08a08b

**Comment by bresch** [comment]
@jorge789 @dannyfpv Thanks for the flights guys. The landing issue you noticed will be fixed here: https://github.com/PX4/Firmware/pull/13381

**Comment by bresch** [comment]
@PX4/testflights I made a few modification and would need a second round of tests flights. Could you fly this PR on a few vehicles please?

**Comment by bresch** [comment]
@PX4/testflights Could you do a new series of flight tests with this PR please? Thanks in advance

**Comment by jorge789** [comment]
### Tested on PixRacer V4:
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
**When the vehicle was landing, it did not descend horizontally, began to get off, but went away with the wind and landed manually**

**Log:**   https://review.px4.io/plot_app?log=5596aa22-cb71-44ba-8505-d620fb2feb3b

### Tested on PixRacer V4:
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
**When the vehicle was landing, it did not descend horizontally, began to get off, but went away with the wind and landed manually**

**Log:**  https://review.px4.io/plot_app?log=594e1f56-e249-4771-bf4e-d9fd174b1cc7

**Comment by bresch** [comment]
@jorge789 Thanks for the flights. The issue you reported is real, apparently the position controller stopped working during landing, this is why the drone was drifting with the wind. I'll open an issue.

Regarding this PR, everything seems to work as expected.

**Comment by bresch** [comment]
Merged on ecl, this will come automatically in the next ecl update.

**Comment by bresch** [comment]
Closed in favor of #13433

**Pull request closed without merging**
