### PR TITLE
FMUv2 Hardware identification some mpu9250 fixes, mpu9250 deprecated on PXMini

### PR DESCRIPTION
**Pull request by davids5**
These 2 changes should fix the mpu9250 failing the mag initialization as noted in https://github.com/PX4/Firmware/issues/7327#issuecomment-315404970

   Mpu9250:Allow internal reset to complete, when started from VDD of 0V
   Per the data sheet: Start-up time for register read/write from power-up is
   Typically 11 ms and the Maximum is 100 ms.

   It seems the power up reset is only triggered at VDD < 150 mV. So the
   symptom reported: Failure is only happening after a long power down is
   consistent with VDD not dropping below 150 mV, therefore not generating
   a POR and being ready to be written with out delay.

  This fix adds a delay of 110 ms to ensure the reset has ended with some.
  margin.

   px4fmu-v2:board init restructuring VDD_3V3_SENSORS and PWM
   Insure a 0.0 voltage initial condition on VDD_3V3_SENSORS
   By starting the GPIO_VDD_3V3_SENSORS_EN, low and deferring
   the GPIO init of the slave selects and drdy signals until
   board_app_initialize. We get ~ 180 ms of power off time
   with 0.00 voltage applied to the sensors.

   Add board_on_reset to insure FMU PWM is clamped on reset
   and held off for > 400 ms to delay the 3.1 ms pules that
   is due to the delay from chip reset to setting the GPIO
   pins.

### CODE REVIEW

**Comment by davids5** [comment]
@LorenzMeier this contains HW version . https://github.com/PX4/Firmware/pull/7645 as it was needed to manage the changes herein. 

We had some chip selects that were not participating in sensor reset, and in the case of v3, SPI4 was not included.  On the PixhawkMini,  PC14 is 20608_DRDY for a SPI1 device, but was configured by the code as an output GPIO_EXT_1 on SPI4 bus. The result was that GPIO_EXT_1 did not participate in sensor reset and was back feeding, preventing a clean sensor reset. 

I have tested this on FmuV2 (both v2 and v3 build), PixhawkMini, Fmuv3 Cube V2.0 and 2.1 All  SPI HW initialized. The only deltas were that i added 10 to the PX4_SPIDEV _XXX for the externals, so we can see them on the console.

The rese is just more mpu9250 clean up; @dennisss Please check this on the CF2.

**Comment by davids5** [comment]
Jenkins test this please.

**Comment by davids5** [comment]
@dennisss Thank you! 

Can you put me in touch with someone to get a CF2 from? I only need it for bench testing the new driver framework on the daisy chained I2C HW.

**Comment by davids5** [comment]
@PX4TestFlights 

We want to insure that all the device have started in the pr (sans the mpu9250 on the mini)

Test plan:

HW:
a) FMUv2 - w/silicon errata (px4fmu-v2_default - only)
b) FMUv2 - with OUT silicon errata
c) FMUv2-PixhawkMini (with console mod)
d) FMUv3 (2.1, 20) - if available
e) FMUv4
f) FMUv4Pro


Step 1)
1) Build current master
2) Load  px4fmu-v2_default on a-d)
3) Load  px4fmu-v4_default on e)
4) Load  px4fmu-v4pro_default on f)
5) capture the boot output for each
6) 'ls /dev'
7) for a-d Save results to file named master-bv2-<HW>.txt (where <HW> a,b...d)
8) Load  px4fmu-v3_default on b-d)
9) for a-d Save results to file named master-bv3-<HW>.txt  (where <HW> a,b...d) 
10)  for e Save results to file named master-bv4-e.txt
11)  for f Save results to file named master-bv4pro-f.txt

Step 2)
build px4fmu-v2_default and px4fmu-v3_default px4fmu-v4_default and px4fmu-v4pro_default of this PR.

1) Load  px4fmu-v2_default on a-d)
2) Load  px4fmu-v4_default on e)
3) Load  px4fmu-v4pro_default on f)
4) Run and capture the boot output 
5) 'ls /dev'
6) Save results to file named as above but replace 'master' with `pr` as the prefix 
7)  for e Save results to file named pr-bv4-e.txt
8)  for f Save results to file named pr-bv4pro-f.txt

Pass criteria:
1) compare master-bv2-<HW>.txt  and pr-bv2-<HW>.txt,
    a) Other than NN the `xxxxx on SPI bus 4 at NN (ffffff KHz)`  for all devices should match
    b) the 'ls /dev' should match.
2) compare master-bv4-e.txt  and pr-bv4-e.txt,
    a) Other than NN the `xxxxx on SPI bus 4 at NN (ffffff KHz)`  for all devices should match
    b) the 'ls /dev' should match.
3) compare master-bv4pro-e.txt  and pr-bv4pro-e.txt,
    a) Other than NN the `xxxxx on SPI bus 4 at NN (ffffff KHz)`  for all devices should match
    b) the 'ls /dev' should match.
If there are any discrepancies here files here.

1) Load  px4fmu-v3_default on c-d)
2) Run and capture the boot output 
3) 'ls /dev'
4) Save results to file named pr-v3-<HW>.txt 

Pass criteria:
1) compare each master-bv3<HW>.txt  and pr-bv3-<HW>.txt 
    a) Except for pixhawkmini. other than NN the `xxxxx on SPI bus 4 at NN (ffffff KHz)`  for all devices should match
    b) the 'ls /dev' should match.
    c) Pixhawk Mini should not list the `MPU9250_SPI on SPI bus 4 at NN (ffffff KHz)
    c) Pixhawk Mini should not list 
              mpu9250_accel
              mpu9250_gyro
              mpu9250_mag
If there are any discrepancies here files here.

Step 3)
Fly:
1) b) with v2 build
2) b) with v3 build
3) c) FMUv2-PixhawkMini
4)) FMUv3 (2.1, 20) - if available
5) FMUv4
6) FMUv4Pro

Pass criteria:
Should be as good as current mater.
for PixhawkMini not any deltas.

**Comment by dennisss** [comment]
@davids5 unfortunately, I'm not particularly well connected to get a Crazyflies very easily. I have a few which I purchased directly from Bitcraze (https://www.bitcraze.io/) and am actively using. Some of the ETHz affiliated developers on here would probably be more able to get some for testing purposes as they surely have many lying around.

**Comment by davids5** [comment]
@dennisss - Thank you! I see I can get one on Amazon that can be here fairly quickly. I'm very much interested in refactoring the I2C interface. So I'll need HW to be able to test this thoroughly.

**Comment by LorenzMeier** [comment]
@davids5 Please tag @PX4TestFlights on it as assignee if you want them to test a branch.

**Comment by r0gelion** [comment]
b) FMUv2 - with OUT silicon errata - **Pass**
- Files comparison - **Pass**
-- [master-bv2-b.txt](https://github.com/PX4/Firmware/files/1192275/master-bv2-b.txt)
-- [pr-bv2-b.txt](https://github.com/PX4/Firmware/files/1192276/pr-bv2-b.txt)
-- [master-bv3-b.txt](https://github.com/PX4/Firmware/files/1192282/master-bv3-b.txt)
-- [pr-bv3-b.txt](https://github.com/PX4/Firmware/files/1192283/pr-bv3-b.txt)
- Flight test - **Pass**
-- v2 build [flight log](http://logs.px4.io/plot_app?log=45fa1334-294a-4ca2-812c-433949b05883)
-- v3 build [flight log](http://logs.px4.io/plot_app?log=af054286-19bd-41c8-ab25-fe0220d42cc2) 

**Note:** Work in progress, I will update this comment.

**Comment by davids5** [comment]
@r0gelion 

All of the above noted differences are expected, details follow TLDNR;. 

For the pr-bv3-c, a parameter reset may be needed. Contact me on slack and we can work through any remaining issues.

### Details:
> davids5 Are the differences, missing and additional messages OK?

Yes. This PR makes the V3 build of FW aware of the hardware it is running on 
V2 - NON silicon errata FMUv2
V2M - PixhawkMini
V30 - Cube

The V2 FW build is too space constrained to support this hardware awareness feature. 

**After this PR is merged. A V2 build should not be used on the PixhawkMini.**

> Differences:
-- master-bv3-c:
--- MPU6000 on SPI bus 1 at 2 (1000 KHz)
-- pr-bv3-c:
--- MPU6000 on SPI bus 1 at 6 (1000 KHz)

\<DEVICE\> on SPI bus \<bus\> at \<device id\> (\<freqency> KHz)


This is OK - in this PR the < device id > (PX4_SPIDEV_[eee]_ddd) have been [changed](https://github.com/PX4/Firmware/pull/7618/commits/4af8acfc76ac5630c6b6eeb93c8e001e5007830e#diff-50af260099447227b508aa0de8655ffbL115) to help debug issues. If a < device id > is greater than 10 it is one of the PX4_SPIDEV_EXT_ddd devices, on the external bus. If the value is less than 10 it is one of the PX4_SPIDEV_ddd devices on the internal bus. 




> Missing in pr-bv3-c:
-- WARN [mpu9250] probe failed! 255
-- WARN [mpu9250] no device on bus 4
-- MPU9250 on SPI bus 1 at 4 (1000 KHz)
-- ERROR [mpu9250] AK8963: bad id 0 retries 7
-- ERROR [mpu9250] AK8963: bad id 0 retries 6
-- ERROR [mpu9250] AK8963: bad id 0 retries 5
-- ERROR [mpu9250] AK8963: bad id 0 retries 4
-- ERROR [mpu9250] AK8963: bad id 0 retries 3
-- ERROR [mpu9250] AK8963: bad id 0 retries 2
-- ERROR [mpu9250] AK8963: bad id 0 retries 1
-- ERROR [mpu9250] AK8963: bad id 0 retries 0
-- ERROR [mpu9250] AK8963: failed to initialize, disabled!
-- ERROR [mpu9250] driver start failed

Yes - These error messages are missing from the PR's V3 build on a PixhawkMini (pr-bv3-c) because the PR adds the HW awareness (see next item) to not to use the mpu9250 on the PixhawkMini.  The unreliable mpu9250 is not started on a V3 build.

We can not use the mpu9250 on the PixhawkMini because there is a HW errata on the PixhawkMini that prevents it from being reliable. This is not a problem because the ICM20608 is now supported along with the Mag on the included GPS.

>Additional in pr-bv3-c:
-- INFO [ver] match: V2M

Yes this is the the output of the "HW awareness" check done [here](https://github.com/PX4/Firmware/pull/7618/files#diff-dc146e6fb305825fdba36bf461a3e970R106)

**Comment by r0gelion** [comment]
@davids5 tests passed.

**Comment by davids5** [comment]
@LorenzMeier - This is ready for final review and merge.

**Comment by jkrueger188** [comment]
Apologies for opening this back up after so long. I teach a class at the University of North Dakota for our unmanned aircraft systems degree - students build their own small unmanned aircraft using pixhawk's and px4 software. This semester we have 17 students (14 of which bought "new" pix mini's from getfpv.com)  

8 of the 14 have the mag inconsistent error which has been described in many forums and many cases on github (as I'm now finding out).  We are flashing latest Qgroundcontrol build. Stumbled across this today while searching for a clear and concise fix.

Since the MPU9250 is disabled with this release, the pixhawk then relies on the included external GPS/Mag. That makes sense however, we go through sensor calibration with the external gps attached and it fails the sensor calibration consistently like it ignores that there is an external gps attached. Is there a setting I have to change in software for to use the external GPS?

I thought the pixhawk mini would automatically use the external gps with the MPU9250 disabled and go through calibration without issue but it's not.... What are my options? 

Would my students be better off returning their pixhawk mini's and getting pixhawk 4's (or other new supported model) instead?

Apologies if this is an inappropriate place for this - I'm somewhat of a github newbie.

**Comment by davids5** [comment]
@dagar  Did the onboard mag creep back in? Can you lend a hand to @jkrueger188.

**Pull request merged**
