### PR TITLE
NuttX/nuttx with SDIO fixes

### PR DESCRIPTION
**Pull request by davids5**
This PR addressees hangs when the SD card is removed while writing.

Fixes PX4/Firmware#12071 (comment)
Fixes PX4/Firmware#13087 (comment)

@PX4/testflights - Please test on FMUv4 and FMUv5

### CODE REVIEW

**Comment by julianoes** [comment]
This will also need to be cherry-picked into v1.10.

**Comment by julianoes** [comment]
And thanks @davids5!

**Comment by dagar** [comment]
https://github.com/PX4/NuttX/pull/68 has merged and I've updated this PR to point to the tip of ` px4_firmware_nuttx-7.29+ `.

**Comment by julianoes** [comment]
I tested this branch in HITL and navigator correctly complains "Waypoint could not be read" and RTL is still possible.

I also checked @BazookaJoe1900's `statfs` issue. I could reproduce the issue with master but not with this fix, so that's fixed as well.

**Comment by BazookaJoe1900** [comment]
@davids5 Thanks!
I have tested it too on my costum branch and the fix seems to work well

**Pull request merged**
