### PR TITLE
cmake_hexagon: rpcmem and linking fix

### LINKED ISSUE #5756: Snapdragon: linking fails on QURT
Unfortunately #5715 leads to "linking" errors on the Snapdragon. The linking on Snapdragon doesn't happen until you start the px4 bin and it loads the part running on the DSP. It then resolves all the symbols it needs.

I verified and it definitely does compile `apps.cpp` in and it even passes the `make qurt_travis_default` build test which supposedly should detect linking errors.

@CarloWood any advice or idea how to debug this?

```
    556734: HAP:12350:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    556734: HAP:12350:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
    556753: HAP:12350:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    556753: HAP:12350:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
    556772: HAP:12350:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    556772: HAP:12350:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
    556792: HAP:12350:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    556792: HAP:12350:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
    556811: HAP:12350:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    556811: HAP:12350:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
    556829: HAP:12350:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    556829: HAP:12350:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
    556848: HAP:12350:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    556848: HAP:12350:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
    556868: HAP:12350:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    556868: HAP:12350:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
    556888: HAP:12350:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    556888: HAP:12350:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
    556907: HAP:12350:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    556907: HAP:12350:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
    557353: HAP:12350:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    557353: HAP:12350:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
    557380: HAP:12350:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    557380: HAP:12350:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
    557716: HAP:12349:undefined PLT symbol _Z12init_app_mapRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (1194) /libp (symbol.c:303)
    557716: HAP:12349:undefined PLT symbol _Z13list_builtinsRSt3mapISsPFiiPPcESt4lessISsESaISt4pairIKSsS3_EEE (77) /libpx (symbol.c:303)
```

With `c++filt` this translates to:

```
[08500/03]  22:37.028  HAP:20542:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:37.028  HAP:20542:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
[08500/03]  22:37.052  HAP:20542:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:37.053  HAP:20542:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
[08500/03]  22:37.076  HAP:20542:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:37.076  HAP:20542:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
[08500/03]  22:37.100  HAP:20542:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:37.100  HAP:20542:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
[08500/03]  22:37.125  HAP:20542:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:37.125  HAP:20542:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
[08500/03]  22:37.148  HAP:20542:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:37.148  HAP:20542:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
[08500/03]  22:37.172  HAP:20542:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:37.172  HAP:20542:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
[08500/03]  22:37.196  HAP:20542:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:37.196  HAP:20542:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
[08500/03]  22:37.221  HAP:20542:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:37.221  HAP:20542:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
[08500/03]  22:37.245  HAP:20542:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:37.245  HAP:20542:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
[08500/03]  22:37.795  HAP:20542:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:37.795  HAP:20542:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
[08500/03]  22:37.836  HAP:20542:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:37.836  HAP:20542:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
[08500/03]  22:38.251  HAP:20541:undefined PLT symbol init_app_map(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (1194) /libp  0303  symbol.c
[08500/03]  22:38.251  HAP:20541:undefined PLT symbol list_builtins(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int (*)(int, char**), std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int (*)(int, char**)> > >&) (77) /libpx  0303  symbol.c
```

### PR DESCRIPTION
**Pull request by julianoes**
This updates cmake_hexagon and cmake_hexagon inside DriverFramework
which fixes somethine about rpcmem.a and the double linking issue.

Finally closes #5756.

### CODE REVIEW

**Comment by julianoes** [comment]
Testing on Snapdragon shows that it still crashes.

**Comment by LorenzMeier** [comment]
yuck.

**Comment by julianoes** [comment]
@LorenzMeier, see https://github.com/ATLFlight/cmake_hexagon/pull/15

**Comment by mcharleb** [comment]
Your fix may "work" for px4 but it breaks cmake_hexagon functionality. I'll try to test px4 today on Eagle.

**Comment by CarloWood** [comment]
The actual problem, as Julian and I found on sunday (see ,https://github.com/PX4/Firmware/issues/5756#issuecomment-258689623) is that cmake (re)adds all the static archives when linking the proper (cmake) way with libpx4.so. This exact problem is described here: http://stackoverflow.com/questions/31503597/cmake-link-a-shared-library-to-static-libraries

As I meantioned here,
https://github.com/PX4/Firmware/issues/5756#issuecomment-2587107744
I think I figured out what is the correct way to fix that linking issue.

Looking at https://github.com/ATLFlight/cmake_hexagon/pull/16 I do not see this problem addressed at all; I can't/didn't test it, bit since after this the px4 library is still created by linking with static libraries, the issue that causes @julianoes to crash must still exist imho.

I am convinced that if we do what I proposed in https://github.com/PX4/Firmware/issues/5756#issuecomment-2587107744
then the duplication is gone and the crash too.

Furthermore, I do not understand the remark in https://github.com/ATLFlight/cmake_hexagon/pull/15#pullrequestreview-7455339 where @mcharleb says that Julian's fix would "This seems to completely eliminate the ability to add other library deps via QURT_LIB_LINK_LIBS. ".   I just don't understand this remark, because it seems (I'm being bold here) rather nonsensical. The whole list of modules in QURT_LIB_LINK_LIBS are linked as archives into libpx4.so, that's exactly why we get the duplicates when linking with them again (the archives) when linking with libpx4.so (by using the cmake method).

**Comment by julianoes** [comment]
@CarloWood thanks for explaining this. I completely agree.

**Comment by julianoes** [comment]
@CarloWood I'm not sure how much work and how many changes your suggestion would need. If you want to tackle it, I'm not opposed, but for now I'm fine with just applying the hack because it only affects Snapdragon.

**Comment by mcharleb** [comment]
@CarloWood I see now that Julian's change removed the duplicate use of LINK_LIBS, but my patch also removed the duplicate use of LINK_LIBS. I didn't like the explicit use of the soname vs the cmake lib target name. If that is required because of a PX4 issue of mixing static libs and shared libs then that should be fixed, not hacked around. I can fix the duplicate

**Comment by julianoes** [comment]
@mcharleb: I already sunk several evenings and most of Sunday into this (as @CarloWood as well). I have a fix proposel and I need to leave it at that.

**Comment by mcharleb** [comment]
I added the hack to cmake_hexagon.

https://github.com/ATLFlight/cmake_hexagon/commit/69a7b313eb8963e2b8909dc8e2ce8e98ae4a99e8

**Comment by LorenzMeier** [comment]
Awesome, thanks! @julianoes Any chance of quickly cross-testing?

**Comment by julianoes** [comment]
Thanks @mcharleb for fixing this! I've cross tested it and it's linking and not crashing anymore.

**Comment by julianoes** [comment]
@mcharleb: Could you please fix the error happening on semaphoreci:
https://semaphoreci.com/px4/firmware/branches/update_cmake_hexagon/builds/2

**Comment by julianoes** [comment]
@dagar: I'm confused why semaphoreci fails? Any idea? Can you try resetting caches?

**Comment by dagar** [comment]
Semaphoreci only caches the non snappy docker images (due to size). Did you try building within julianoes/px4-snappy-2016-10-16 locally?

**Comment by mcharleb** [comment]
@julianoes I can have a look at it.

**Comment by mcharleb** [comment]
The problem is that there is nothing in /home/runner/Firmware/build_qurt_eagle_default/external/Install/lib. When I do a make locally, there is nothing in that directory and the link line is vastly different from what is output for semaphore CI.

FAILED: : && /home/docker1000/Qualcomm/HEXAGON_Tools/7.2.12/Tools/bin/hexagon-link  -march=hexagon -mcpu=hexagonv5 -shared -call_shared -G0 /home/docker1000/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic/initS.o -o src/firmware/qurt/libpx4muorb_skel.so -L/home/docker1000/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic -Bsymbolic /home/docker1000/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic/libgcc.a --wrap=malloc --wrap=calloc --wrap=free --wrap=realloc --wrap=memalign --wrap=__stack_chk_fail -lc -soname= --start-group --whole-archive src/firmware/qurt/CMakeFiles/px4muorb_skel.dir/px4muorb_skel.c.o -L/home/runner/Firmware/build_qurt_eagle_default/external/Install/lib -lpx4 --end-group  --start-group -lgcc --end-group /home/docker1000/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic/finiS.o && :
Fatal: cannot recognize namespec -lpx4

**Comment by mcharleb** [comment]
@julianoes I have built using both make and ninja and both succeed. I have no way to access the SemaphoreCI image (I don't have the login and I don't see any scripts in the Firmware repo the define the Semaphore CI docker image). Clearly there is something wrong with the link line that fails. Nothing is installing libpx4.so into  /home/runner/Firmware/build_qurt_eagle_default/external/Install/lib

**Comment by mcharleb** [comment]
@julianoes When I run make VERBOSE=1 (and disable ninja) I see that the first thing that happens when building px4muorb_skel is:

cd /topdir/Firmware/build_qurt_eagle_default/src/firmware/qurt

This contains libpx4.so and the link command is:

**cd /local2/mnt/workspace/dronecode/Firmware/build_qurt_eagle_default/src/firmware/qurt** && /usr/bin/cmake -E cmake_link_script CMakeFiles/px4muorb_skel.dir/link.txt --verbose=1
/home/mcharleb/testme/Qualcomm/HEXAGON_Tools/7.2.12/Tools/bin/hexagon-link  -march=hexagon -mcpu=hexagonv5 -shared -call_shared -G0 /home/mcharleb/testme/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic/initS.o -o libpx4muorb_skel.so -L/home/mcharleb/testme/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic -Bsymbolic /home/mcharleb/testme/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic/libgcc.a --wrap=malloc --wrap=calloc --wrap=free --wrap=realloc --wrap=memalign --wrap=__stack_chk_fail -lc -soname= --start-group --whole-archive CMakeFiles/px4muorb_skel.dir/px4muorb_skel.c.o  **-L/local2/mnt/workspace/dronecode/Firmware/build_qurt_eagle_default/external/Install/lib libpx4.so** ../../drivers/device/libdrivers__device.a ../../modules/sensors/libmodules__sensors.a ../../platforms/posix/drivers/df_mpu9250_wrapper/libplatforms__posix__drivers__df_mpu9250_wrapper.a ../../platforms/posix/drivers/df_bmp280_wrapper/libplatforms__posix__drivers__df_bmp280_wrapper.a ../../platforms/posix/drivers/df_hmc5883_wrapper/libplatforms__posix__drivers__df_hmc5883_wrapper.a ../../platforms/posix/drivers/df_trone_wrapper/libplatforms__posix__drivers__df_trone_wrapper.a ../../platforms/posix/drivers/df_isl29501_wrapper/libplatforms__posix__drivers__df_isl29501_wrapper.a ../../systemcmds/param/libsystemcmds__param.a ../../modules/attitude_estimator_q/libmodules__attitude_estimator_q.a ../../modules/position_estimator_inav/libmodules__position_estimator_inav.a ../../modules/local_position_estimator/libmodules__local_position_estimator.a ../../modules/ekf2/libmodules__ekf2.a ../../modules/mc_att_control/libmodules__mc_att_control.a ../../modules/mc_pos_control/libmodules__mc_pos_control.a ../../modules/param/libmodules__param.a ../../modules/systemlib/libmodules__systemlib.a ../../modules/systemlib/mixer/libmodules__systemlib__mixer.a ../../modules/uORB/libmodules__uORB.a ../../../libmsg_gen.a ../../modules/commander/libmodules__commander.a ../../modules/land_detector/libmodules__land_detector.a ../../drivers/gps/libdrivers__gps.a ../../drivers/pwm_out_rc_in/libdrivers__pwm_out_rc_in.a ../../drivers/qshell/qurt/libdrivers__qshell__qurt.a ../../lib/controllib/liblib__controllib.a ../../lib/mathlib/liblib__mathlib.a ../../lib/mathlib/math/filter/liblib__mathlib__math__filter.a ../../lib/geo/liblib__geo.a ../../lib/ecl/liblib__ecl.a ../../lib/geo_lookup/liblib__geo_lookup.a ../../lib/conversion/liblib__conversion.a ../../lib/terrain_estimation/liblib__terrain_estimation.a ../../lib/runway_takeoff/liblib__runway_takeoff.a ../../lib/tailsitter_recovery/liblib__tailsitter_recovery.a ../../lib/DriverFramework/framework/liblib__DriverFramework__framework.a ../../lib/DriverFramework/framework/src/libdf_driver_framework.a ../../platforms/common/libplatforms__common.a ../../platforms/qurt/px4_layer/libplatforms__qurt__px4_layer.a ../../platforms/posix/work_queue/libplatforms__posix__work_queue.a ../../modules/muorb/adsp/libmodules__muorb__adsp.a ../../lib/DriverFramework/drivers/mpu9250/libdf_mpu9250.a ../../lib/DriverFramework/drivers/bmp280/libdf_bmp280.a ../../lib/DriverFramework/drivers/hmc5883/libdf_hmc5883.a ../../lib/DriverFramework/drivers/trone/libdf_trone.a ../../lib/DriverFramework/drivers/isl29501/libdf_isl29501.a -lm  --no-whole-archive /home/mcharleb/testme/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic/libstdc++.a --end-group  --start-group -lgcc --end-group /home/mcharleb/testme/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic/finiS.o

**Comment by mcharleb** [comment]
@julianoes The above was with the previous version of cmake_hexagon. With the latest version the link line becomes:

 **cd /local2/mnt/workspace/dronecode/Firmware/build_qurt_eagle_default/src/firmware/qurt** && /usr/bin/cmake -E cmake_link_script CMakeFiles/px4muorb_skel.dir/link.txt --verbose=1
/home/mcharleb/testme/Qualcomm/HEXAGON_Tools/7.2.12/Tools/bin/hexagon-link  -march=hexagon -mcpu=hexagonv5 -shared -call_shared -G0 /home/mcharleb/testme/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic/initS.o -o libpx4muorb_skel.so -L/home/mcharleb/testme/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic -Bsymbolic /home/mcharleb/testme/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic/libgcc.a --wrap=malloc --wrap=calloc --wrap=free --wrap=realloc --wrap=memalign --wrap=__stack_chk_fail -lc -soname= --start-group --whole-archive CMakeFiles/px4muorb_skel.dir/px4muorb_skel.c.o  **-L/local2/mnt/workspace/dronecode/Firmware/build_qurt_eagle_default/external/Install/lib -lpx4**  --end-group  --start-group -lgcc --end-group /home/mcharleb/testme/Qualcomm/HEXAGON_Tools/7.2.12/Tools/target/hexagon/lib/v5/G0/pic/finiS.o

The libpx4.so file is in the current build directory: /local2/mnt/workspace/dronecode/Firmware/build_qurt_eagle_default/src/firmware/qurt

I don't know why that isn't the case for the Semaphore CI build.

**Comment by mcharleb** [comment]
There is a difference: My desktop build is using "-o libpx4muorb_skel.so". The Semaphore CI build is linking "-o src/firmware/qurt/libpx4muorb_skel.so" which means that libpx4.so is likely in src/firmware/qurt relative to the current build directory.

**Comment by mcharleb** [comment]
@julianoes It should be fixed by https://github.com/ATLFlight/cmake_hexagon/commit/799d8215a096298f89d9abe77c9f75c9b7cd9a15

**Comment by julianoes** [comment]
@mcharleb awesome, thank you! My local docker build is already happy. I'll pull in the latest in DriverFramework as well and then merge this.

**Pull request merged**
