### PR TITLE
commander: enable partial preflight checks on RPI

### PR DESCRIPTION
**Pull request by nicolaerosia**
See https://github.com/PX4/Firmware/issues/7253

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Can this be done without the usage of a local static variable?

**Comment by nicolaerosia** [comment]
I would rather keep the rate limiting for warning since in one occasion, my console was flooded with this mesage. If you have another suggestion, let me know.

**Comment by mhkabir** [comment]
There is already a framework for reporting these in a rate limited fashion (when a link is first connected) : https://github.com/PX4/Firmware/blob/master/src/modules/commander/PreflightCheck.cpp#L266-L268.

Would make sense if you used that.

**Comment by nicolaerosia** [comment]
thank you, did not know that.

**Comment by mhkabir** [comment]
@nicolaerosia Just gate those warning with `reportFailures` from here : https://github.com/PX4/Firmware/blob/master/src/modules/commander/PreflightCheck.cpp#L555

**Comment by nicolaerosia** [comment]
@mhkabir done, sorry it took forever

**Comment by mhkabir** [comment]
Thanks!

**Pull request merged**
