### PR TITLE
Prevent height set-point variations due to bad GPS

### PR DESCRIPTION
**Pull request by priseborough**
Fixes: https://github.com/PX4/Firmware/issues/6193

**TODO**

Code review
Compatibility testing with LPE

### CODE REVIEW

**Comment by LorenzMeier** [comment]
ECL is in.

**Comment by Stifael** [comment]
I tested it in SITL, and it seems to work, but I cant see the output of the continuous integration right now. 
I also would add the check if the vehicle hasnt armed yet, since the reference altitude is not changing once the vehicle armed (https://github.com/PX4/Firmware/pull/6197/files#diff-fc77c3ef569029d45764664c75d4b0c1R853) && !_control_mode.armed

**Comment by Stifael** [comment]
I  need to test it a bit more, bc I think it could become an issue when flying in manual right after arming, and the switch to mission

**Comment by LorenzMeier** [comment]
@Stifael Can you please drive this one to completion this week?

**Comment by LorenzMeier** [comment]
Continued here: https://github.com/PX4/Firmware/pull/6459

**Pull request closed without merging**
