### PR TITLE
Add SENS_MAG_ID parameter

### PR DESCRIPTION
**Pull request by hauptmech**
Record devid to SENS_MAG_ID during mag calibration
Verify devid matches SENS_MAG_ID during preflight_check

Fixes issue #1583

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesome! Would you terribly mind also doing that for accel and gyro? We do have similar constraints there.

**Comment by LorenzMeier** [comment]
Regarding commits, you might want to consider an interactive rebase:
https://help.github.com/articles/about-git-rebase/

And for a PR, run:
```bash
git fetch upstream
git rebase --interactive upstream/master
```

We're not doing that in master, but before we merge a branch to master there is some opportunity for some cleanup - e.g. here you could fixup the 2nd commit into the first, making the commit log easier to read.

**Comment by hauptmech** [comment]
Yes, I'll rebase as a single commit. I don't have hardware available this coming week but I'll review what needs to be done for accel and gyro. I'll let you know if I can do it.

**Comment by LorenzMeier** [comment]
Merged via rebase. Please base accel / gyro changes off master. Thanks for the contribution!

**Pull request closed without merging**
