### PR TITLE
parameters fix PARAM_DEFAULT_OVERRIDES and merge testing

### PR DESCRIPTION
**Pull request by dagar**
This PR fixes PARAM_DEFAULT_OVERRIDES (broken by https://github.com/PX4/Firmware/commit/db816982cde07a19975b02bd2e7d63242d5d8f04) and simplifies the parameter gen within cmake.

I also merged the last sad unittest/ into the main tests command.

### CODE REVIEW

**Comment by dagar** [comment]
- fixes #7362

**Comment by dagar** [comment]
Thanks for the explanation in https://github.com/PX4/Firmware/issues/7362 and https://github.com/PX4/Firmware/issues/7364 @jywilson. To be paranoid can you verify this branch is now working? Master is currently broken and I don't have a Snapdragon.

I've verified all generated param files are identical.

``` Bash

 % git status
On branch pr-parameters
nothing to commit, working directory clean

 % ./Tools/docker_run.sh 'make eagle_default'    
...
...
...

 % diff ./build_qurt_eagle_default/parameters.xml ./build_posix_eagle_default/parameters.xml                                                            
 % diff ./build_qurt_eagle_default/src/modules/systemlib/param/px4_parameters.c ./build_posix_eagle_default/src/modules/systemlib/param/px4_parameters.c
 % diff ./build_qurt_eagle_default/src/modules/systemlib/param/px4_parameters.h ./build_posix_eagle_default/src/modules/systemlib/param/px4_parameters.h

```

**Comment by d3z0rian** [comment]
I built eagle_legacy_default and got param errors in Today's master and in this branch. The errors are different in each build.

Today's master output:
http://pasted.co/dc60a156

dagar/pr-parameters output:
http://pasted.co/a1a39fb0

**Comment by dagar** [comment]
@d3z0rian is that with both posix_eagle and qurt_eagle built from the exact same version?

**Comment by d3z0rian** [comment]
Commit 343578e fixed the parameters issues but it still returning errors.

px4 output:
px4_output - f0c3ca00

mini-dm output:
http://pasted.co/1ac69b20

**Comment by jywilson** [comment]
@dagar 
I built the code in this branch and the portion of the PX4 code that runs in the aDSP is crashing.
The crash is apparent since the blsp_config.c debug output is present, which only runs at aDSP startup.  

Ultimately, this is what causes the parameter errors to appear in the PX4 console since the aDSP subsystem restarts when the crash occurs.  Essentially the muORB calls made by the AppsProc to synch parameters return an error since the FastRPC to the aDSP cannot be completed.  

Identifying the code in the aDSP that is crashing is difficult.  The minidm output is helpful, but will drop the debug messages that were still in the cache when the aDSP restarts, leaving you with an incomplete list of debug messages.  

From the minidm output that is present it looks like the crash is occurring during the loading of a particular module, but I am not sure which.  I typically try to debug these issues by subtraction, loading modules one-by-one in the px4.config file, until I find one that causes a crash.  Once the suspect module is identified, you can focus on the recent code changes.

I am debugging a different issue at the moment.  Once this other issue is resolved I can help you locate the code generating the exception and the resulting aDSP restart.  

Jim W.

**Comment by dagar** [comment]
Thanks, I don't have this hardware, but I have a pretty good idea what changed in PX4 recently.
As a baseline try this commit from 4 days right before I changed the BlockParams.

https://github.com/PX4/Firmware/commit/0dfd8cd0390f82859bb0ae3952fc172dcec01e6f

One other thing that comes to mind is multiple different optimization flags were being passed to QuRT targets and I updated cmake to only set it once.

**Comment by dagar** [comment]
Qurt was previously passing both `-O0` and `-O2` and based on the manual `-O0` setting in px4_impl_qurt.cmake I assumed that was desired. Due to the ordering of the arguments -O2 was the actual optimization level, which I've now corrected in the last commit.

**Comment by jywilson** [comment]
@dagar: I just tried https://github.com/PX4/Firmware/commit/0dfd8cd0390f82859bb0ae3952fc172dcec01e6f the commit you made reference to above and the aDSP crash is resolved.  I was also able to arm the motors, but I didn't do a flight test.  Nice work!

@mcharleb: Can you look at dagar's comment above regarding optimization flags.  I doubt we intended -O0 since this would disable all optimizations.  Do you know?

@dagar: When you are ready, I can also so a quick sanity check with a basic flight test.   

Jim W.

**Comment by dagar** [comment]
- fixes #7385

**Comment by mcharleb** [comment]
@jywilson I think the -O0 was required for the 6.x Hexagon Tools so that was explicitly set in cmake_hexagon. I haven't tested other optimization levels since updating to the 7.2 Hexagon Tools.

**Comment by dagar** [comment]
I'm not sure how long it's been like this, but the -O2 was taking precedence over the -O0. Looking at it again the -O0 C flag wasn't even being used as the variable is actually added_c_flags (was missing an underscore). CXX flags had -O0 -O2 though.
https://github.com/PX4/Firmware/blob/master/cmake/qurt/px4_impl_qurt.cmake#L184

**Comment by jywilson** [comment]
@dagar @mcharleb 
Okay, so in light of Mark's reply regarding the intention to us -O0, let's stick with Daniel's fix to consistently us -O0.  In the meantime, I can do additional testing to verify that -O2 works correctly with the newer version of the Hexagon tools.  

@mcharleb Do we still support builds using the older 6.x toolchain?  If 7.x tests out okay with  optimization enabled, then can we remove the -O0 reference, assuming that the 6.x toolchain is no longer supported.

**Comment by ChristophTobler** [comment]
@dagar bench tested on a Snapdragon Flight -> the errors have gone

**Comment by dagar** [comment]
@jywilson actually it's now -O2. It wasn't working when forced to -O0, but we don't know why. The overall cmake build now sets CMAKE_BUILD_TYPE and respects the corresponding optimization levels.
https://github.com/PX4/Firmware/blob/master/CMakeLists.txt#L157

**Comment by dagar** [comment]
@jywilson @ChristophTobler given master is currently broken should we get this in and continue the discussion of intended optimization level in another issue?

**Comment by ChristophTobler** [comment]
Sounds reasonable

**Pull request merged**
