### PR TITLE
PX4 on nuttx 7.28+

### PR DESCRIPTION
**Pull request by dagar**
Continuation of https://github.com/PX4/Firmware/pull/11013 now that there's a new NuttX release.

As of writing this the only notable change from the last state of https://github.com/PX4/Firmware/pull/11013 is that we're currently completely in sync with upstream NuttX with no patches!

### Testing Status

- [x] px4_fmu-v2
- [x] px4_fmu-v3
- [x] px4_fmu-v4
- [x] px4_fmu-v4pro (@klopezal - please give this a test.)
- [x] px4_fmu-v5
- [ ] airmind_mindpx-v2 (@rolandash - please give this a test.)
- [ ] auav_x21 (@pkocmoud  - please give this a test.)
- [x] av_x-v1 (@dagar please give this a test.)
- [ ] bitcraze_crazyflie (@DanielePettenuzzo  - please give this a test.)
- [ ] gumstix_aerocore2 
- [ ] intel_aerofc-v1 (@dagar)
- [x] nxp_fmuk66-v3 (@igalloway  - please give this a test.)
- [x] omnibus_f4sd (@bkueng )
- [ ] atmel_same70xplained - deprecated - will be removed after merge
- [ ] stm_nucleo-F767ZI - deprecated - will be removed after merge
- [ ] stm_32f4discovery - deprecated - will be removed after merge

### CODE REVIEW

**Comment by Avysuarez** [comment]
Tested on pixhawk 4 and pixhawk 2.1.
Good flights, no issues.
pixhawk 4
https://review.px4.io/plot_app?log=62fdfc12-ec0b-47e7-a63b-c4336cdd650b
pixhawk 2.1
https://review.px4.io/plot_app?log=7f94c1d5-4319-4915-af74-20756f68a8e1

**Comment by davids5** [comment]
@dagar - hold off merging - I just upstreamed a bug fix in `open` 

This was a fun bug. The console was being closed out from under nsh.

mkfatfs was called with no sd in slot.
image

block_proxy returned ERROR but needed highlighted line to propagate
to caller. 

mkfatfs had FD of 0 and closed it on exit.

**Comment by davids5** [comment]
@dagar - the fix is in upstream and nuttx/apps are updated. Got to go from my perspective.

**Comment by dagar** [comment]
I've updated the default branch to `px4_firmware_nuttx-7.28+` and enabled branch protection on https://github.com/PX4/NuttX and https://github.com/PX4/NuttX-apps.

**Comment by davids5** [comment]
@dagar thank you!

**Comment by spheroidal** [comment]
Hi, I found that PX4 no longer works on crazyflie 2.0 after this merge. I was able to compile and flash the codes, but I was unable to connect to the nsh console using mavlink afterwards.

I connected my ubuntu laptop to the crazyflie via usb and the command I used was ./Tools/mavlink_shell.py /dev/ttyACM0. The connect get stuck forever after displaying "Connecting to MAVLINK..." and no error message was displayed. I verified that crazyflie was indeed connected to /dev/ttyACM0 using command dmesg. In addition, the M1 light on the crazyflie did not blink after I flashed the codes.

Before this merge, the codes work normally. I also tried the latest stable release(v 1.9.2) and the current master, but got the same problem. Does anyone have similar problems or have any idea to fix it? Thanks!

**Pull request merged**
