### PR TITLE
Master micro hal

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier 

This is one step to make merging master to nuttx_v3 cleaner and allows WIP to remove CONFIG_ARCH_BOARD_xxxx

Please review, and merge

### CODE REVIEW

**Comment by davids5** [comment]
@mcharleb, @jgoppert  is CONFIG_ARCH_BOARD_SIM still used? If so were is it set?

**Comment by davids5** [comment]
Jenkins test this please

**Comment by davids5** [comment]
@LorenzMeier  - Ping.  This now passes but need had merge.

**Comment by davids5** [comment]
@LorenzMeier reverted mine and CP yours. Please merge when can.

**Comment by LorenzMeier** [comment]
Will get this done today

**Comment by LorenzMeier** [comment]
@davids5 Something went terribly wrong with your PR here because rebasing this on master completely explodes.

**Comment by LorenzMeier** [comment]
Please try to stick to a clean rebase workflow. Something about your own merging strategy made this explode.

**Comment by LorenzMeier** [comment]
I can't even cherry-pick the first commit here. You must have been using a super old master when you started this. Let's chat on Monday on workflows and how to resolve.

**Comment by LorenzMeier** [comment]
I squashed this and merged it.

**Pull request closed without merging**
