### PR TITLE
add Safety switch handling to fmuv4

### PR DESCRIPTION
**Pull request by LorenzMeier**
@kd0aij This is your rebased branch with transitional handling added so users don't feel the pain.

### CODE REVIEW

**Comment by kd0aij** [comment]
flashing this branch via QGC initially showed an airframe choice of "generic_250"
Selecting that airframe resulted in a garbage value for SYS_AUTOSTART
Confusion ensued, but I think restarting QGC solved the problem because the dropdown menu now shows "Generic 250 Racer"
Choosing that airframe and applying caused default param values to be set.

It looks like the firmware should work properly for users once SYS_AUTOSTART is set properly. I believe the need to restart QGC under certain circumstances is a long-standing issue, but I'll leave it to the QGC devs to determine the existence and extent of the problem.

**Comment by LorenzMeier** [comment]
@kd0aij Could you rebase and test this? Your report above doesn't really give away if this is ready or not?

**Comment by kd0aij** [comment]
I don't think there's anything wrong with this code. But I think someone who understands QGC should test changing airframes, because it always confuses me. I vaguely recall being told that QGC needs to be restarted at some point, but if it prompted to do that, I didn't see it.

**Comment by LorenzMeier** [comment]
I still can't parse your response. Did you confirm during your test that you're not forced to use the safety switch to arm?

**Comment by kd0aij** [comment]
that is correct, as long as the parameters are set correctly. But for me, accomplishing that with QGC was far from painless.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
