### PR TITLE
WIP: FrSky SmartPort telemetry initial testing

### PR DESCRIPTION
**Pull request by kd0aij**
1) use a blocking read to wait for poll frame
2) write/read a single byte to check timing

### CODE REVIEW

**Comment by kd0aij** [comment]
sometimes the response byte is not written promptly?
smartport_test

captured uart data
https://copy.com/04oMj4WmhgRrFjPr

**Comment by kd0aij** [comment]
At a priority of 200, max latency with blocking read allows enough time to transfer >50 bytes 
and sensor responses are only 8 bytes long
Next step is to implement the actual sensor response code.

**Comment by pkocmoud** [comment]
image

Looks good using my Diode crossover cable. The PixRacer signal are the lower voltage level pulses with the logical value of 0x55.

**Comment by kd0aij** [comment]
@pkocmoud commit c92d257 should display A2 = 5.5V with max et to 18.4V on you Taranis TX.
My TX periodically displays higher, incorrect values, but the logic analyzer says I was transmitting the correct data at those times. Can you see if you get the same behavior with your setup?

**Comment by kd0aij** [comment]
Commit 76ec260 should display voltage_v from the battery_status message on A2.

**Comment by LorenzMeier** [comment]
@kd0aij So what you're saying suggests we have a signal integrity issue on the bus?

**Comment by kd0aij** [comment]
more likely to be a timing issue. scope says signal levels are valid and edges are clean. logic analyzer shows no uart framing errors

**Comment by LorenzMeier** [comment]
Can you paste traces of the original and the one Pixracer emits? How high is the active voltage? If it's less than 2.5V some receivers might consider is marginal

**Comment by kd0aij** [comment]
Phil captured this on his Saleae last night. First set of pulses is the RX polling, next is the PixRacer reply
image

**Comment by pkocmoud** [comment]
It should be noted that is with the TX and RX lines connected directly without a diode.

**Comment by kd0aij** [comment]
upgrading the firmware on my Taranis to OpenTX 2.1.7 has completely changed the behavior observed at the TX. More trial and error iterations required.

**Comment by LorenzMeier** [comment]
Signal looks really good. How about making a cable for S.Port like that?

**Comment by LorenzMeier** [comment]
@kd0aij it would be great if you could keep the parsing in separate files in the lib folder like we did for lib/rc. I want to share more code with other projects.

**Comment by pkocmoud** [comment]
We have that cable in the works already.

**Comment by kd0aij** [comment]
Verified stable and correct transmission of A2 voltage using OpenTX 2.1.7. Now trying to get it logged on the TX.

**Comment by LorenzMeier** [comment]
Nice!

**Comment by LorenzMeier** [comment]
@kd0aij I just did some handheld tests on the input sampling:

```
nsh> tests adc
2: 4  3: 6  4: 2982  10: 2318  11: 1842  12: 1458  13: 1136  14: 2  16: 4  
2: 4  3: 4  4: 2964  10: 2305  11: 1793  12: 1367  13: 1118  14: 2  16: 4  
2: 5  3: 4  4: 2986  10: 2322  11: 1827  12: 1434  13: 1094  14: 2  16: 4  
2: 4  3: 4  4: 2984  10: 2319  11: 1847  12: 1491  13: 1200  14: 1  16: 4  
2: 6  3: 4  4: 2955  10: 2299  11: 1923  12: 1482  13: 1180  14: 2  16: 4  
         ADC test successful.
nsh> tests adc
2: 4  3: 4094  4: 2947  10: 2822  11: 2252  12: 1839  13: 1476  14: 6  16: 5  
2: 5  3: 4093  4: 2973  10: 2843  11: 2278  12: 1901  13: 1581  14: 0  16: 4  
2: 4  3: 4094  4: 2973  10: 2844  11: 2281  12: 1883  13: 1539  14: 2  16: 4  
2: 4  3: 4093  4: 2951  10: 2826  11: 2240  12: 1803  13: 1390  14: 2  16: 5  
2: 4  3: 4095  4: 2972  10: 2840  11: 2261  12: 1863  13: 1521  14: 2  16: 4  
         ADC test successful.
```

That was with 0V and 3.3V applied to the current input pin - can you provide the output of your board when flashed with master and with power module connected?

**Comment by kd0aij** [comment]
replaced by https://github.com/PX4/Firmware/pull/3553

**Comment by kd0aij** [comment]
sorry, didn't see your comment till just now. I'm not set up to pull current from the power module yet; what conditions did you want to test with?

**Pull request closed without merging**
