### PR TITLE
Navigator: Fix RTL to return in a straight line

### PR DESCRIPTION
**Pull request by LorenzMeier**
This is untested, but should let the system return in a straight line.

### CODE REVIEW

**Comment by bansiesta** [comment]
Hm, so the aim of this is that the previous position setpoint only gets set once and that should be when we start returning, right?

**Comment by LorenzMeier** [comment]
Yes, exactly. Right now its constantly reset, leading to no cross track / wind correction.

**Comment by bansiesta** [comment]
Ok, seems right to me then.

**Comment by tumbili** [comment]
To be tested in SITL

**Comment by LorenzMeier** [comment]
Tested, applied!

**Pull request closed without merging**
