### PR TITLE
NuttX Upgrade

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier 

Nuttx v3 commits regrouped from https://github.com/PX4/Firmware/tree/nuttx_upgrade

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@davids5 Can you rebase on master to solve the syslink conflict? Should be fairly easy with this change set.

I reviewed that this branch has only a whitespace diff to nuttx_upgrade. One thing I wanted to check on is submodule version checking. I'd like to have this active to default. Did you maybe disable it here by default?

**Comment by LorenzMeier** [comment]
Mem / RAM on master:

```
Processes: 23 total, 3 running, 20 sleeping
CPU usage: 51.70% tasks, 0.44% sched, 47.86% idle
DMA Memory: 5120 total, 1536 used 1536 peak
Uptime: 42.795s total, 22.466s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
   0 Idle Task                   22465 47.855     0/    0   0 (  0)  READY 
   1 hpwork                       1580  4.068   868/ 1592 192 (192)  w:sem 
   2 lpwork                        172  0.369   572/ 1592  50 ( 50)  w:sig 
   3 init                         1650  0.000  1324/ 2496 100 (100)  w:sem 
 151 commander_low_prio              1  0.000   732/ 2992  50 ( 50)  w:sem 
 101 gps                           111  0.221   764/ 1192 220 (220)  w:sem 
 103 dataman                        19  0.000   740/ 1192  90 ( 90)  w:sem 
 139 sensors                      1982  5.029   936/ 1696 250 (250)  w:sem 
 141 commander                    1140  2.662  2828/ 3192 140 (140)  w:sig 
 147 px4io                        1090  3.032  1004/ 1392 240 (240)  w:sem 
 297 top                            63  3.106  1212/ 1696 100 (100)  RUN   
 156 mavlink_if0                   716  1.553  1716/ 2392 100 (100)  w:sig 
 157 mavlink_rcv_if0                12  0.000  1324/ 2096 175 (175)  w:sem 
 172 mavlink_if1                   464  1.183  1740/ 2392 100 (100)  READY 
 174 mavlink_rcv_if1                50  0.073  1248/ 2096 175 (175)  w:sem 
 185 uavcan                        637  1.627  1108/ 2392 240 (240)  w:sem 
 210 mavlink_if2                  1411  3.476  1620/ 2392 100 (100)  READY 
 212 mavlink_rcv_if2                 3  0.000   956/ 2096 175 (175)  w:sem 
 219 sdlog2                         29  0.073  1692/ 3392 177 (177)  w:sig 
 272 ekf2                         6216 17.381  4964/ 5792 250 (250)  w:sem 
 277 mc_att_control               1449  4.659  1268/ 1496 250 (250)  w:sem 
 280 mc_pos_control               1055  3.180  1100/ 1896 250 (250)  w:sem 
 287 navigator                       7  0.000   964/ 1296 105 (105)  w:sem 
nsh> free
             total       used       free    largest
Mem:        236272     197712      38560      33424
nsh> 
```

and this branch:

```
Processes: 23 total, 3 running, 20 sleeping
CPU usage: 52.48% tasks, 2.03% sched, 45.50% idle
DMA Memory: 5120 total, 1536 used 1536 peak
Uptime: 80.570s total, 43.679s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
   0 Idle Task                   43679 45.495   636/  668   0 (  0)  READY 
   1 hpwork                       2734  3.903   880/ 1780 192 (192)  w:sem 
   2 lpwork                         80  0.075   632/ 1780  50 ( 50)  w:sig 
   3 init                        20898  0.000  2116/ 2484 100 (100)  w:sem 
 303 top                            94  3.153  1224/ 1684 100 (100)  RUN   
 110 gps                           306  0.225  1040/ 1172 220 (220)  w:sem 
 112 dataman                        18  0.000   736/ 1180  90 ( 90)  w:sem 
 149 sensors                      3681  5.480  1112/ 1684 250 (250)  w:sem 
 151 commander                    2207  3.003  2832/ 3148 140 (140)  w:sig 
 157 px4io                        2016  3.003   944/ 1380 240 (240)  w:sem 
 169 mavlink_if0                  1256  1.576  1720/ 2332 100 (100)  w:sig 
 170 mavlink_rcv_if0                21  0.000   952/ 2100 175 (175)  w:sem 
 180 mavlink_if1                   879  1.201  1696/ 2284 100 (100)  w:sig 
 182 mavlink_rcv_if1                46  0.000   952/ 2100 175 (175)  w:sem 
 197 uavcan                       1095  1.651  1128/ 2380 240 (240)  w:sem 
 299 commander_low_prio              2  0.000   680/ 2996  50 ( 50)  w:sem 
 218 mavlink_if2                  2615  3.753  1608/ 2284 100 (100)  w:sig 
 219 mavlink_rcv_if2                 5  0.000   944/ 2100 175 (175)  w:sem 
 230 sdlog2                         44  0.000  1704/ 3316 177 (177)  w:sig 
 273 ekf2                        11618 17.792  4968/ 5780 250 (250)  w:sem 
 280 mc_att_control               2873  4.654  1272/ 1476 250 (250)  w:sem 
 284 mc_pos_control               1948  3.003   960/ 1876 250 (250)  w:sem 
 292 navigator                      10  0.000   920/ 1276 105 (105)  w:sem 
nsh> free
             total       used       free    largest
Mem:        237456     196608      40848      36704
nsh> 
```

**Comment by LorenzMeier** [comment]
Variable expansion: The mixer file name doesn't get expanded any more (this is in the rcS script:

```
INFO  [init] Mixer:  
```

complete log makes sense except for that.

```
WARN  [bst] no devices found
INFO  [ver] match: PX4FMU_V2
HMC5883_I2C on I2C bus 1 at 0x1e (bus: 100 KHz, max: 400 KHz)
LIS3MDL bad ID: 3cWARN  [lis3mdl] no device on bus 2
WARN  [hmc5883] no device on bus 1
WARN  [mpu6000] no device on bus 3
WARN  [mpu6000] no device on bus 4
WARN  [mpu6000] no device on bus 4
WARN  [mpu9250] no device on bus 4
MPU6000 on SPI bus 1 at 4 (1000 KHz)
WARN  [mpu6000] no device on bus 4
WARN  [mpu9250] no device on bus 3
WARN  [mpu9250] no device on bus 4
L3GD20 on SPI bus 1 at 1 (11000 KHz)
LSM303D on SPI bus 1 at 2 (11000 KHz)
Airspeed on I2C bus 1 at 0x28 (bus: 100 KHz, max: 100 KHz)
nsh: sf1xx: command not found
WARN  [hmc5883] mag cal status changed 
INFO  [load_mon] stack check enabled: no
INFO  [px4io] default PWM output device
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS1 @ 57600B
INFO  [mavlink] mode: OSD, data rate: 1000 B/s on /dev/ttyS2 @ 57600B
WARN  [uavcan] Node ID 1, bitrate 1000000
WARN  [uavcan] CAN driver init...
WARN  [uavcan] SW version vcs_commit: 0x7fffffff
WARN  [uavcan] sensor bridge 'gnss' init ok
WARN  [uavcan] sensor bridge 'mag' init ok
WARN  [uavcan] sensor bridge 'baro' init ok
INFO  [ver] match: PX4FMU_V2
px4flow [205:100]
WARN  [px4flow] scanning I2C buses for device..
INFO  [mavlink] mode: Config, data rate: 800000 B/s on /dev/ttyACM0 @ 57600B
INFO  [init] Mixer:  
WARN  [fmu] no mixers defined
INFO  [init] Mixer:  
INFO  [lib__ecl] EKF IMU buffer length = 21
INFO  [lib__ecl] EKF observation buffer length = 16

NuttShell (NSH)
nsh> WARN  [mavlink] Disabling hardware flow control
INFO  [lib__ecl] EKF using pressure height - commencing alignment
INFO  [lib__ecl] EKF alignment complete
WARN  [commander] Not ready to fly: Sensors not set up correctly
```

**Comment by LorenzMeier** [comment]
IO status:

```
nsh> px4io status
WARN  [px4io] loaded
protocol 4 hardware 2 bootloader 3 buffer 64B crc 0x49700500
8 controls 8 actuators 18 R/C inputs 2 analog inputs 0 relays
312 bytes free
status 0x2741 OUTPUTS_ARMED SAFETY_SAFE RC_FAIL FMU_OK MIXER_OK ARM_SYNC INIT_OK
alarms 0x0030 FMU_LOST RC_LOST
vservo 41 mV vservo scale 10000
vrssi 1171
actuators -10000 -10000 -10000 -10000 0 0 0 0
servos 900 900 900 900 0 0 0 0
reversed outputs: [________] trims: r:   0.0000 p:   0.0000 y:   0.0000
0 raw R/C inputs
R/C flags: 0x0000
mapped R/C inputs 0x0000
ADC inputs 16 1478
features 0x0008 RSSI_ADC
arming 0x0430 FMU_DISARMED IO_ARM_DENIED INAIR_RESTART_OK ALWAYS_PWM_ENABLE OVERRIDE_IMMEDIATE
rates 0x000f default 50 alt 400 sbus 72
debuglevel 0
controls 0: -157 -144 -3143 0 0 0 0 -10000
controls 1: 0 0 0 0 0 0 0 0
controls 2: 0 0 0 0 0 0 0 0
controls 3: 0 0 0 0 0 0 0 0
input 0 min 1000 center 1500 max 2000 deadzone 10 assigned 255 options 0x0000
input 1 min 1000 center 1500 max 2000 deadzone 10 assigned 255 options 0x0000
input 2 min 1000 center 1500 max 2000 deadzone 10 assigned 255 options 0x0000
input 3 min 1000 center 1500 max 2000 deadzone 10 assigned 255 options 0x0000
input 4 min 1000 center 1500 max 2000 deadzone 10 assigned 255 options 0x0000
input 5 min 1000 center 1500 max 2000 deadzone 10 assigned 255 options 0x0000
input 6 min 1000 center 1500 max 2000 deadzone 10 assigned 255 options 0x0000
input 7 min 1000 center 1500 max 2000 deadzone 10 assigned 255 options 0x0000
input 8 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 9 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 10 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 11 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 12 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 13 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 14 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 15 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 16 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 17 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
failsafe 900 900 900 900 1500 1500 0 0
disarmed values 900 900 900 900 0 0 0 0
```

**Comment by LorenzMeier** [comment]
@davids5 I rebased and force pushed. Fixed a couple of cosmetics along the way.

**Comment by LorenzMeier** [comment]
@davids5 Have you seen the build failure?

```
[202/420] Building C object src/driver...rds__tap-v1.dir/tap_timer_config.c.obj
FAILED: /usr/lib/ccache/arm-none-eabi-gcc  -DBUILD_URI=localhost -DCONFIG_ARCH_BOARD_TAP_V1 -DMEMORY_CONSTRAINED_SYSTEM -DMODULE_NAME=\"drivers__boards__tap-v1\" -D__DF_NUTTX -D__PX4_NUTTX -D__STDC_FORMAT_MACROS -I../src -I. -Isrc -I../src/modules -I../src/include -I../src/lib -I../src/platforms -I../src/drivers/boards/tap-v1 -Isrc/modules/px4_messages -Isrc/modules -I../mavlink/include/mavlink -I../src/lib/DriverFramework/framework/include -I../src/lib/matrix -Itap-v1/NuttX/nuttx/nuttx-export/include -Itap-v1/NuttX/nuttx/nuttx-export/include/cxx -Itap-v1/NuttX/nuttx/nuttx-export/arch/chip -Itap-v1/NuttX/nuttx/nuttx-export/arch/common -Itap-v1/NuttX/nuttx/nuttx-export/arch/armv7-m -Itap-v1/NuttX/apps/include -Iexternal/Install/include -g -std=gnu99 -fno-common -Wall -Werror -Wextra -Wno-sign-compare -Wshadow -Wfloat-equal -Wpointer-arith -Wmissing-declarations -Wno-unused-parameter -Werror=format-security -Werror=array-bounds -Wfatal-errors -Werror=unused-variable -Werror=reorder -Werror=uninitialized -Werror=init-self -Werror=unused-but-set-variable -Wformat=1 -Wdouble-promotion -Werror=double-promotion -Wbad-function-cast -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wold-style-declaration -Wmissing-parameter-type -fvisibility=hidden -include visibility.h -mcpu=cortex-m4 -mthumb -march=armv7e-m -mfpu=fpv4-sp-d16 -mfloat-abi=hard -nodefaultlibs -nostdlib -Os -fno-strict-aliasing -fomit-frame-pointer -funsafe-math-optimizations -ffunction-sections -fdata-sections -fno-strength-reduce -fno-builtin-printf   -Wframe-larger-than=1024 -Os -fno-strict-aliasing -fomit-frame-pointer -funsafe-math-optimizations -ffunction-sections -fdata-sections -fno-strength-reduce -fno-builtin-printf -MMD -MT src/drivers/boards/tap-v1/CMakeFiles/drivers__boards__tap-v1.dir/tap_timer_config.c.obj -MF src/drivers/boards/tap-v1/CMakeFiles/drivers__boards__tap-v1.dir/tap_timer_config.c.obj.d -o src/drivers/boards/tap-v1/CMakeFiles/drivers__boards__tap-v1.dir/tap_timer_config.c.obj   -c ../src/drivers/boards/tap-v1/tap_timer_config.c
../src/drivers/boards/tap-v1/tap_timer_config.c:78:35: error: conflicting types for 'led_pwm_timers'
 __EXPORT const struct io_timers_t led_pwm_timers[1] = {
                                   ^
compilation terminated due to -Wfatal-errors.
```

**Comment by davids5** [comment]
@LorenzMeier Thank you ! I force pushed the missed one. Working on  https://github.com/PX4/Firmware/issues/5710

**Comment by davids5** [comment]
@LorenzMeier

I had a bug in the SPI init and it has been fixed and rebased into the `Adding px4fmu-v5` commit.

The baro is working now.

Commit 805c4c9 has the startup script changes. Unfortunately the MPU6000 driver in ICM-20608 mode (even with a quick hack) will not start the ICM-20602. So we need to add the ICM and BMI drivers before FMUv5 can be flight tested.

On to bootloader...

**Comment by LorenzMeier** [comment]
http://review.px4.io/plot_app?log=d7ccce37-ea47-423e-9375-1f1495a34486

**Comment by santiago3dr** [comment]
Tested this morning; all went well
http://review.px4.io/plot_app?log=d7ccce37-ea47-423e-9375-1f1495a34486

**Comment by davids5** [comment]
@LorenzMeier Bottloader is done https://github.com/PX4/Bootloader/pull/68 and needs edcb0f2bc76ef1686be15e2c408cc06a0dead05b to position the code.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by LorenzMeier** [comment]
Rebased and force-pushed to fix CI.

**Comment by LorenzMeier** [comment]
Ok, so this looks like its good to go. Timeline to get this in is early next week. I want the test flight crew to clock up 50 flights on it first.

**Comment by santiago3dr** [comment]
Three flights from this morning
http://review.px4.io/plot_app?log=d10f4062-e9c1-4800-9f29-f059300921d9
http://review.px4.io/plot_app?log=bcc670a6-a69f-46cd-9584-a1f1a26e57cb
http://review.px4.io/plot_app?log=7dc41b0c-5db1-4b32-957f-090b5f94c74e

few notes...
having trouble maintaining connection to QGC during setup with usb connection
first flight when landing did not detect ground and tried to flip over
very slight movement in roll axis without roll input in second flight
third flight is very stable and landed appropriately but took a few seconds more than expected to disarm

**Comment by davids5** [comment]
@LorenzMeier rebased on master and forced pused

**Comment by santiago3dr** [comment]
a few flights from today

http://review.px4.io/plot_app?log=f31f93a0-457d-4f7e-adfc-121228bc9012
http://review.px4.io/plot_app?log=cc80d38b-0be1-4d0f-bf4d-2c08bc1294e0
http://review.px4.io/plot_app?log=73e523b2-3c4d-43be-9e38-f22f6740533f
http://review.px4.io/plot_app?log=fc450a61-29a5-4dbd-8142-bbedffef577c
http://review.px4.io/plot_app?log=3d3674fe-37e5-48cd-8cdb-a525d674feec

**Comment by LorenzMeier** [comment]
Continued here: https://github.com/PX4/Firmware/pull/6099

**Pull request closed without merging**
