### PR TITLE
Reduce STM32 CAN IRQ overhead with new error handling logic

### PR DESCRIPTION
**Pull request by pavel-kirienko**
This change only updates the libuavcan submodule. Other relevant changes in the submodule that also will be pulled in with this PR (see libuavcan commit log for details):

* Fixed IRQ race condition in CAN controller initialization
* Merge pull request #81 from UAVCAN/stm32_can_error_codes
* Optimized clock instance access

Performance improvement:

### Before

```
Processes: 23 total, 6 running, 17 sleeping
CPU usage: 56.18% tasks, 0.82% sched, 43.00% idle
Uptime: 15.288s total, 5.638s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE
   0 Idle Task                    5637 42.996     0/    0   0 (  0)  READY
 145 uavcan                       1665 12.808  1516/ 1792 240 (240)  w:sem
 150 uavcan fw srv                 270  1.947  3516/ 5992 120 (120)  w:sem
```

### After

```
Processes: 23 total, 3 running, 20 sleeping
CPU usage: 42.21% tasks, 0.60% sched, 57.19% idle
Uptime: 160.452s total, 91.338s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE
   0 Idle Task                   91337 57.185     0/    0   0 (  0)  READY
 145 uavcan                      16809 10.759  1516/ 1792 240 (240)  w:sem
 150 uavcan fw srv                2425  1.429  3516/ 5992 120 (120)  w:sem
```

This is ready for merge.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
@hsteinhaus You may want to pull this into APM as well.

**Comment by LorenzMeier** [comment]
Thanks! Will merge as the CI build passes.

**Comment by LorenzMeier** [comment]
I rebased on master which should fix CI.

**Comment by LorenzMeier** [comment]
Applied to master, thanks!

**Pull request closed without merging**
