### PR TITLE
WIP: Manual attitude setpoint for large heading errors

### LINKED ISSUE #3620: Special handling for manual control inputs for large heading errors
As soon as the heading error becomes large (often the case for VTOL in high winds) the manual roll and pitch controls do not lead to the reaction the user would expect. This is because the roll and pitch sequence comes after the yaw sequence in the euler formulation we are using (we are generating the attitude setpoint quaternion from euler angles).
However, this is tricky for the user and should be fixed.

### LINKED ISSUE #4556: Transform roll/pitch commands with current yaw instead of setpoint
@tumbili @LorenzMeier 
VTOLs really suffer from this currently, would be great if we can get to the bottom of it soon.

For reference, a similar previous attempt: https://github.com/PX4/Firmware/pull/3397

### PR DESCRIPTION
**Pull request by tumbili**
mc pos control: In manual mode calculate attitude setpoint such that it reflects the users intuition of roll and pitch for any given heading error.

TODO:
- [x] extensive testing in SITL
- [x] testing on real multicopter
- [ ] review
- [x] add comments to code

Fixes #4556
Fixes #3620

### CODE REVIEW

**Comment by tumbili** [comment]
A good way to test this:
1) Comment this line https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L1982

2) Assign any value between -pi and pi to _att_sp.yaw_body here https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L1979

3) Disable absolute yaw control by commenting this line https://github.com/PX4/Firmware/blob/master/src/modules/mc_att_control/mc_att_control_main.cpp#L708

By doing the above steps the copter will no longer have absolute yaw control but you can still make it turn in yaw since there is a FF on the rates. In this situation you can produce an arbitrary yaw error and verify that roll and pitch commands match the users intuition.

**Comment by tumbili** [comment]
Log where absolute yaw control was disabled -> arbitrary high yaw error: User was still able to control roll and pitch as he expected:
http://logs.uaventure.com/view/svVXALTKZbkZbCwuyD37v8

Log where absolute yaw control was enabled
http://logs.uaventure.com/view/fBnVjFEUm9BJf6Mmhr9zhX

**Comment by LorenzMeier** [comment]
@tumbili The logic looks right, but I would like to clarify if the only derivation we can choose is through the proposed mix of euler angles, quaternions, trigonometric functions and rotation matrices. It would be good to have a second pass and see if we can't express this more compact using entries of a rotation matrix. I'm concerned that while we fix the common yaw case we might miss extreme angles, in particular for racers.

**Comment by tumbili** [comment]
@LorenzMeier Tested in SITL and the behaviour is exactly the same. Maybe I can try to add even better comments.

**Comment by LorenzMeier** [comment]
Looks good, thanks!

**Comment by LorenzMeier** [comment]
Thanks for the quick fix of this issue, I'm sure a lot of users will really appreciate it. I've back ported this to master.

**Pull request merged**
