### PR TITLE
Multi pub/sub UAVCAN

### PR DESCRIPTION
**Pull request by LorenzMeier**
@pavel-kirienko Could you have a look here? I can't seem to be able to fix the compile errors introduced by the last commit.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
```
CXX:     /Users/user/src/Firmware/src/modules/uavcan/sensors/mag.cpp
/Users/user/src/Firmware/src/modules/uavcan/sensors/mag.cpp: In constructor 'UavcanMagnetometerBridge::UavcanMagnetometerBridge(uavcan::INode&)':
/Users/user/src/Firmware/src/modules/uavcan/sensors/mag.cpp:46:14: error: no matching function for call to 'UavcanCDevSensorBridgeBase::UavcanCDevSensorBridgeBase(const char [11], const char [16], const char [9], const orb_metadata*)'
 _sub_mag(node)
              ^
compilation terminated due to -Wfatal-errors.
```

**Comment by pavel-kirienko** [comment]
@LorenzMeier fixed, but I didn't run it, so I'm not sure if the new publisher handling logic in the UAVCAN sensor base class is implemented correctly.

**Comment by LorenzMeier** [comment]
@hsteinhaus @pavel-kirienko Let me know if you get a chance to cross-test this.

**Comment by LorenzMeier** [comment]
@pavel-kirienko @hsteinhaus Rebased on master including an USB startup fix. It would be awesome if you could give this some quick cross testing, as I'm eager to get this cleanup onto master. The API has tremendously improved with this one.

**Comment by LorenzMeier** [comment]
@jgoppert @sjwilks @bansiesta If you have cycles for code review I would deeply appreciate a few notes. The change is unit-tested and the unit-test is active on the auto-testing system, however, I want to make sure to not have screwed up things. I noticed that we actually carried typos for the 3rd sensor set, and I want to be sure to have things right this time.

With the C++ sub framework of @thomasgubler this patch set will allow to automatically fail over to a different sensor if the first one fails. I will add the multi-sensor calibration capability as time permits. With those changes we'll be completely up-to-date then on the backend side.

**Comment by LorenzMeier** [comment]
Tested against sensor calibration and real sensor values. Looking valid, but if someone could confirm the correct operation of a mag setup on a Pixhawk (internal and external) that would be great.

**Comment by LorenzMeier** [comment]
Closing in favour of #1711.

**Pull request closed without merging**
