### PR TITLE
Cmd forwarding

### PR DESCRIPTION
**Pull request by LorenzMeier**
@AndreasAntener @sanderux This should be enough to forward the transition command and allow to embed it into missions. It also prepares everything for camera triggers. QGC should get support for all this also today.

None of this is tested, so bring up carefully. But it shows at least where to put the plumbing.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@SimonWilks This goes pretty far in enabling what we discussed.

**Comment by LorenzMeier** [comment]
You can use this QGC branch: https://github.com/mavlink/qgroundcontrol/pull/2510

screen shot 2016-01-02 at 21 32 28

**Comment by LorenzMeier** [comment]
This is in QGC master and has made it into the daily build.

**Comment by sanderux** [comment]
PR https://github.com/PX4/Firmware/pull/3426
Untested but a basis to expand on.

I will field test this asap. If succesful i will add some more logic like failsafe.

**Comment by LorenzMeier** [comment]
@sanderux Before re-working the whole mission / transition logic, should we maybe test this and try to get this in? It should enable transitions already.

**Comment by sanderux** [comment]
@LorenzMeier The commands where not picked up by the VTOL controller. The current setup doesn't use the helper classes to perform these tasks in missions. (same with takeoff / land).they are only used for navigation modes.

I have added publishing the command and checking transition completion in the current style for missions. I would be an advocate of rewriting this so that the helper classes are used in missions as well. Currently that would mean changing transition, takeoff and land procedures in the mission_block.

**Comment by AndreasAntener** [comment]
@sanderux With helper classes I assume you are referring to the independent nav state handlers (takeoff.cpp, land.cpp etc). I agree that we should try to reuse the handling code, like mission item creation which I already refactored for takeoff/land and RTL (common code in the super class mission_block.cpp). That should go into the direction you mean right?

But generally these navigation states can be executed standalone and therefore have different entry/exit state handling which we cannot merge. Otherwise we need to think about the general approach there.

**Comment by AndreasAntener** [comment]
I think this can be merged. Just did another test with the rebased version.

**Comment by LorenzMeier** [comment]
Nice!

**Pull request merged**
