### PR TITLE
mpu 9250 fixes

### PR DESCRIPTION
**Pull request by davids5**
This should fix the mag issues on PixhawkMini https://github.com/PX4/Firmware/issues/7327 and the odd Z reading on FMUv4Pro https://github.com/PX4/Firmware/issues/7541

@klopezal, @bresch, @gbrunso @PX4TestFlights - please give this a try. The console output will help debug this, it is still failing.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I found an unit where I get this:

```
nsh> mpu9250 start
MPU9250 on SPI bus 1 at 4 (1000 KHz)
ERROR [mpu9250] AK8963: bad id 0 retries 7
ERROR [mpu9250] AK8963: bad id 0 retries 6
ERROR [mpu9250] AK8963: bad id 0 retries 5
ERROR [mpu9250] AK8963: bad id 0 retries 4
ERROR [mpu9250] AK8963: bad id 0 retries 3
ERROR [mpu9250] AK8963: bad id 0 retries 2
ERROR [mpu9250] AK8963: bad id 0 retries 1
ERROR [mpu9250] AK8963: bad id 0 retries 0
ERROR [mpu9250] AK8963: failed to initialize, disabled!
ERROR [mpu9250] driver start failed
nsh> 
```

**Comment by LorenzMeier** [comment]
Enabling debug brings it back to life. Maybe the delays in the driver were not so wrong after all.

**Comment by davids5** [comment]
I do not think that is it. - the mpu's SPI to IC bridge AKA master has latched and we can not issue the reset.
Does this happen every power cycle?

**Comment by LorenzMeier** [comment]
This fixed it: https://github.com/PX4/Firmware/commit/24ffada340acaf02fa5cc16066866a4ff01df5d4

**Comment by gbrunso** [comment]
I just flashed the latest px4 v3 master and can still replicate issue in #7327.  Unlike before, when the sensors fail to start up, QGC shows the following messages:
```
Warning: Primary compass not found
PREFLIGHT FAIL: NO ACCEL SENSOR 0
Warning: Primary accelerometer not found
PREFLIGHT FAIL: NO GYRO SENSOR 0
Warning: Primary gyro not found
```

**Comment by mhkabir** [comment]
@gbrunso Can you recalibrate?

**Comment by gbrunso** [comment]
@mhkabir recalibrating doesn't seem to fix the problem.

**Pull request merged**
