### PR TITLE
Master expunge ifdef crazyflie

### PR DESCRIPTION
**Pull request by davids5**
@dennisss , FYI @LorenzMeier 

I need to remove all the CONFIG_ARCH_BOARD_xxxx from the code base. We want to have a more component based approach to share code, but not tie it to one board.

@dennisss Would you please review and test this.

### CODE REVIEW

**Comment by davids5** [comment]
Jenkins please test this

**Comment by davids5** [comment]
Jenkins test this please.

**Comment by dennisss** [comment]
Tested and working!

I've also looked into removing the alternative rate. This (https://github.com/dennisss/Firmware/commit/ad12b4c7d7198d4501a867da0e5147b6089b5f32) works per your notes. I haven't seen any artifacts arise for the slight delay in rate setup during startup. I believe that it shouldn't be an issue as the stock firmware switches to lower rates initially for audible sound purposes anyway.

**Comment by davids5** [comment]
@LorenzMeier - 

i am having to do this in pieces.

Please review and merge -

**Pull request merged**
