### PR TITLE
Master pwm glitch fix

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier 

Current Master: with 2e8accc that broke the test command.

From Boot
image

Zooming in we see state changes on the pwm during config
image

This PR: Reverts 2e8accc and moves the IO init out to the point of arming

From Boot:

image

Zooming in we see the pins go low once before the

image

image

first 1 Ms pulse

image

### CODE REVIEW

**Comment by kd0aij** [comment]
Does this work for FMUv4 also?

**Comment by davids5** [comment]
It should it is the same code for the FMU side

**Comment by LorenzMeier** [comment]
On the 2nd lowest plot there is no time scale - I would need to understand the length of the pulse to judge wether its acceptable or not.

**Comment by davids5** [comment]
@LorenzMeier added detail in original post for second from bottom

**Pull request closed without merging**
