### PR TITLE
Update submodule libuavcan to latest Sun Apr  1 17:52:32 UTC 2018

### PR DESCRIPTION
**Pull request by dagar**
- Changes: https://github.com/UAVCAN/libuavcan/compare/e1c9a4f5064a336295125da25c0542a5cd601dd7...master

### CODE REVIEW

**Comment by dagar** [comment]
@pavel-kirienko FYI update to current libuavcan not currently building on PX4/NuttX. I'll look into it later.

**Comment by dagar** [comment]
image

**Comment by pavel-kirienko** [comment]
Okay, this is a NuttX compatibility issue. Who will volunteer to fix it? Can we ask @davids5 for help?

**Comment by dagar** [comment]
> Okay, this is a NuttX compatibility issue. Who will volunteer to fix it? Can we ask @davids5 for help?

@pavel-kirienko could you elaborate on what needs to be fixed? I don't know CAN or UAVCAN internals at the moment, but I wouldn't mind getting up to speed.

**Comment by davids5** [comment]
@dagar It looks like the ISR registration that checked on nuttx to carry the context pointer. @LorenzMeier do you want me to fix this?

**Comment by LorenzMeier** [comment]
@davids5 Please go ahead, yes.

**Comment by davids5** [comment]
@dagar @pavel-kirienko @LorenzMeier Continued here https://github.com/PX4/Firmware/pull/9650

**Pull request closed without merging**
