### PR TITLE
simulator in hardware (rebased)

### PR DESCRIPTION
**Pull request by bkueng**
@romain-chiap I rebased #11400, so we can bring it in.

### CODE REVIEW

**Comment by romain-chiap** [comment]
> @romain-chiap I rebased #11400, so we can bring it in.

Awesome, thanks a lot. Are we still interested in an [integration test](https://dev.px4.io/en/test_and_ci/integration_testing.html)? (i.e. a simulated mission that ensures that the sih is functional).

**Comment by bkueng** [comment]
> Awesome, thanks a lot. Are we still interested in an integration test? (i.e. a simulated mission that ensures that the sih is functional).

Yes, would be cool. But I'm fine with merging this already.

**Comment by romain-chiap** [comment]
> > Awesome, thanks a lot. Are we still interested in an integration test? (i.e. a simulated mission that ensures that the sih is functional).
> 
> Yes, would be cool. But I'm fine with merging this already.

Ok. I'm fine with it too.

For the visualization, I developed a [MAVLink to UDP bridge to be used with FlightGear](https://github.com/romain-chiap/MAVLinkToUDP). @hamishwillee shall I add that to the documentation?

I'm also working on jMAVsim, so far the connection is established but the display is laggy.

**Comment by hamishwillee** [comment]
@romain-chiap Sorry for the delay, I've been on holiday and now working through emails !
I have merged the docs you worked on now, so you can iterate as needed.

> For the visualization, I developed a MAVLink to UDP bridge to be used with FlightGear. 
> @hamishwillee shall I add that to the documentation?

Could you instead use https://github.com/intel/mavlink-router ? As that is the more generally recommended MAVLink routing software?

If so, then I'd certainly outline this as an option and link to the relevant docs on how to setup. 

> I'm also working on jMAVsim, so far the connection is established but the display is laggy.

yes, that will be even better if you can get it working.

**Comment by romain-chiap** [comment]
> I'm also working on jMAVsim, so far the connection is established but the display is laggy.

This is now working properly! I created a [pull request on jMAVSim](https://github.com/PX4/jMAVSim/pull/101)

**Comment by hamishwillee** [comment]
@romain-chiap Very cool. Hope that goes in. At that point, adding docs on how to use the update makes a lot of sense.

**Pull request merged**
