### PR TITLE
[WIP][do not merge] Add OBC datalink failsafe in parallel with GCS datalink failsafe

### PR DESCRIPTION
**Pull request by TSC21**
The purpose of this patch is enable failsafe for datalink with OBC, which will work the same way as the datalink failsafe of a GCS. This will allow, for example, setting missions using the OBC and change for AUTO modes the same way, without relaying on the presence of the heartbeat of the GCS. Having the possibility of listen and control the heartbeat of the OBC is also a feature that makes sense nowdays, as the number systems using an OBC increases, and reliably checking for the link status is a must. This works differently from the offboard failsafes, as we may use the OBC without offboard control.
One of the things that I question is about the check present in https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L1710 - if the OBC is on the vehicle, shouldn't the sysid be equal to the sysid of the vehicle? And if yes, does it make sense to have `msg->sysid != mavlink_system.sysid` when `hb.type == MAV_TYPE_ONBOARD_CONTROLLER`? Also, why does the HEARTBEAT msg stream also contains the HEARTBEATS from the FCU itself? Shouldn't those be broadcast, without loopback? I question why is `msg->sysid != mavlink_system.sysid` even required, if I can make a check for the `MAV_TYPE`.
@LorenzMeier, @DonLakeFlyer, @dagar your feedback on this is welcomed.

### CODE REVIEW

**Comment by dagar** [comment]
The flow is mavlink receives a HEARTBEAT, if it's from a GCS (and different sys id) publish a telemetry_status uORB message that commander checks for the data link loss failsafe.

How about a new bitmask parameter that allows you to configure the MAV_TYPE that mavlink respects HEARTBEATs from?

 - MAV_TYPE_GCS
 - MAV_TYPE_ONBOARD_CONTROLLER

**Comment by TSC21** [comment]
>How about a new bitmask parameter that allows you to configure the MAV_TYPE that mavlink respects HEARTBEATs from?
>
> - MAV_TYPE_GCS
> - MAV_TYPE_ONBOARD_CONTROLLER

Thanks for the feedback @dagar. And how do that bitmask fits here?

**Comment by TSC21** [comment]
Jenkins test this please.

**Comment by dagar** [comment]
The bitmask sets which source of HEARTBEATs we care about for the data link loss failsafe. All the logic after that wouldn't have to change.

**Comment by TSC21** [comment]
What if I care about both and want to verify both datalinks? I added this logic so I am able to monitor both heartbeats.

**Comment by dagar** [comment]
Yes, that's the point. You'd be able to select any combination.

**Comment by TSC21** [comment]
Oh ok. So what you are suggesting is to complement the forward logic and not to replace it, is that right?

**Comment by TSC21** [comment]
Jenkins test this please.

**Comment by TSC21** [comment]
@dagar can you check if the last update follows what you suggested?

**Comment by TSC21** [comment]
@dagar we definitely need to check what is happening with MAVROS tests on CI.

**Comment by dagar** [comment]
I'm trying to remember where we left this. One question was if we actually need separate parameters for every type of data link loss and action or if we simply have a longer parameter that specifies what the data link lost check and actions apply to.

I think it really depends on the use case outside of offboard control.

**Comment by TSC21** [comment]
> I think it really depends on the use case outside of offboard control.

Correct. Have an OBC link doesn't mean we are under offboard. It just means that that link is required for something, like telemetry or even other types of data sharing.

**Comment by dagar** [comment]
Revisiting this idea - https://github.com/PX4/Firmware/pull/10933

**Pull request closed without merging**
