### PR TITLE
commander auto disarm if kill switch engaged for 5 seconds

### LINKED ISSUE #10133: Kill switch and arm/disarm logic
From the discussion that started on the PX4 slack this issue is opened so the discussion on the relation between the kill switch and arm/disarm logic.

As proposed by me and also other users on the slack the kill switch (KS) should also automatically disarm the platform. Right now if the KS is activated, props stop immediatly (good for emergencies) but if the user/dev forgets to disarm before deactivating the KS props immediatly turn on with a high probabiliy of a crash (because the control loop is still on).

**So proposal #1 is when the Killswitch is activated the platform is immediatly and automatically disarmed aswell.**

This would improve security.

Another proposal that was discussed was the possible addition of a arm/disarm switch.

### PR DESCRIPTION
**Pull request by dagar**
- closes #10133

### CODE REVIEW

**Comment by hamishwillee** [comment]
This has a documentation impact:
- Kill switch: https://docs.px4.io/en/config/safety.html#kill_switch - currently says does not disarm

Can you guys either update the docs or send me an explicit reminder when this goes in?

**Comment by LorenzMeier** [comment]
Looking reasonable, but I haven't reviewed the code itself. @bkueng Could you do that please? Thanks!

**Comment by dagar** [comment]
Opened only for discussion with https://github.com/PX4/Firmware/issues/10133, labelling "[DO NOT MERGE]" for now.

**Comment by MaEtUgR** [comment]
I still think this pr is a useful solution to #10133

**Comment by dagar** [comment]
@MaEtUgR I agree.

It didn't rebase cleanly. Can you give this a fresh review?

**Comment by dagar** [comment]
@PX4/testflights could you test the kill switch, auto disarming, and auto disarming from the kill switch on a multicopter? Initially without flying at all, but if those goes smoothly you could verify auto disarm after a flight works properly (respecting the COM_DISARM_LAND parameter value).

**Comment by dannyfpv** [comment]
Pixhawk4 mini was conducted, there were no issues. 

Kill Switch Test
https://review.px4.io/plot_app?log=9d8ffb23-765f-4c5d-b49c-91e6c04c93dc

Auto Disarm 
https://review.px4.io/plot_app?log=31e2b2de-e04e-4242-8853-3c4dd5629f54

**Comment by jorge789** [comment]
Pixhawk v4pro test was conducted, there were no issues.

Kill Switch Test
https://review.px4.io/plot_app?log=9c19eecc-2928-4119-ac7e-96b6664e7d11

Auto Disarm
https://review.px4.io/plot_app?log=c995ae9d-9ae6-4430-a871-ea45e7ed68f0

**Comment by jorge789** [comment]
Pixhawk Racer v4 test was conducted, there were no issues. 

Kill Switch Test
https://review.px4.io/plot_app?log=8b66722d-09eb-4af9-a3fb-6f65840a7559

Auto Disarm 
https://review.px4.io/plot_app?log=e3265df4-7878-4876-aa83-2624f6f880a0

**Comment by MaEtUgR** [comment]
I checked in SITL again disarm on land works fine in long short and disabled configuration.

The exemplary well conducted and labeled outdoor test look good as well. It disarms 5 seconds after killing:
kill-switch-disarm

**Pull request merged**
