### PR TITLE
clarify the codes of LPE

### PR DESCRIPTION
**Pull request by stmoon**
To clarify the name of GPS for LPE, I modified some item name of array.

### CODE REVIEW

**Comment by stmoon** [comment]
Hello  @mhkabir 

Could you tell me why the process has been holding? 
I don't understand the process is stopped at continuous-integration/jenkins/pr-head for a long time.

Thanks in advance

**Comment by mhkabir** [comment]
@dagar Do you know what's going on with Jenkins here? It seems to be stuck, and I can't access the status.

**Comment by mhkabir** [comment]
Jenkins test this please.

**Comment by dagar** [comment]
That's really weird, there was something wrong with the original commit. Jenkins wouldn't take it until I rebased on px4 master and reset the dates.

**Comment by stmoon** [comment]
Hi, @mhkabir  and @jgoppert 

It works again! thanks to @dagar.

Please check it again 

sorry for inconvenience

**Pull request merged**
