### PR TITLE
Pixracer rev 12 support

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by kd0aij** [comment]
code inspection: makes perfect sense now :)
Will test on xr12 shortly

**Comment by kd0aij** [comment]
looks like PX4_SPI_BUS_BARO needs to be defined in all board_config files, not just v2 and v4

**Comment by LorenzMeier** [comment]
How come the build test then passes, even for v1? Its not required.

**Comment by LorenzMeier** [comment]
I will leave this sitting here until RC12 boards are redistributed.

**Comment by kd0aij** [comment]
I guess that means PX4_SPIDEV_BARO is not defined in the other board configs

**Pull request closed without merging**
