### PR TITLE
Improvements to temp calibration script

### PR DESCRIPTION
**Pull request by jgoppert**
@priseborough @bkueng Hope this is a little more helpful.

[7a3f865f-2013-472b-8345-cee7f3ec1e2d_temp_cal.pdf]
(https://github.com/PX4/Firmware/files/736729/7a3f865f-2013-472b-8345-cee7f3ec1e2d_temp_cal.pdf)

@bkueng Finally found the pandas from dict ctor, so this avoids csv conversion. I'll switch to that in px4tools as well.

@priseborough I tried to process what you said, but in case I missed something, I cleaned it up so it is very easy to hack. I added lambda functions to the configs, so you can pass whatever function you want it to use for the offset for each sensor type. Let me know if anything looks wrong and I'll will try to fix it quickly.

```python
    # default for config
    config = {
        'fields': [],
        'units': [],
        'poly_deg': 3,
        'xlabel': 'Temp, deg C',
        'ylabel': '',
        'min': lambda x: x.min(),
        'max': lambda x: x.max(),
        'ref': lambda x: (x.min() + x.max())/2,
        'offset': lambda y: 0,
        'save_plot': True,
        'plot_interval': '5 s',
    }

    pdf = PdfPages(pdf_filename)

    for topic in r.keys():
        for multi_id in r[topic].keys():

            name = '{:s}_{:d}'.format(topic, multi_id)
            print('processing', name)

            if topic == 'sensor_baro':
                config['fields'] = ['altitude']
                config['ylabel'] = 'pressure altitude, m'
                config['offset'] = lambda y: y.median()
            elif topic == 'sensor_gyro':
                config['fields'] = ['x', 'y', 'z']
                config['ylabel'] = 'gyro, rad/s'
            elif topic == 'sensor_accel':
                config['fields'] = ['x', 'y', 'z']
                config['ylabel'] = 'accel, m/s^2'
                config['offset'] = lambda y: y.median()
            else:
                continue
```
I currently just dump in json, I can convert it to the other format if that would be helpful.

```json
{
  "sensor_accel_0": {
    "T_max": 49.761322021484375, 
    "T_min": 17.083843231201172, 
    "T_ref": 33.422582626342773,
    "poly": {
      "x": [
        0.11914293536764142, 
        -0.25798326376446895, 
        0.062178720451732117, 
        0.063227634334971999
      ], 
      "y": [
        0.033010063025516664, 
        -0.086134444348327954, 
        0.023964080141885936, 
        0.02258029015071409
      ], 
      "z": [
        -0.039279647723242161, 
        0.23074154509705264, 
        -0.18153830355532988, 
        -0.032419765056276965
      ]
    }
  }, 
```

### CODE REVIEW

**Comment by priseborough** [comment]
@jgoppert  I understood a bit of what you explained above. I will have a look  at the code, then would appreciate setting up a call so I can get you to explain it via screen share.

**Comment by priseborough** [comment]
I'm unable to run the script now - I get the following error:

Traceback (most recent call last):
  File "process_sensor_caldata.py", line 35, in <module>
    import pandas
ImportError: No module named pandas

**Comment by mhkabir** [comment]
@priseborough You need to install pandas : http://stackoverflow.com/questions/13249135/installing-pandas-on-mac-osx

**Comment by jgoppert** [comment]
@priseborough Let me know what time is good for you. I have a meeting 12-3 pm EST but am free otherwise.

**Comment by priseborough** [comment]
So this isn't installed as part of the PX4 toolchain? I know we want to make this modular, etc, but from my perspective this is becoming harder to maintain with reliance on 'pandas' and 'jsons'

**Comment by jgoppert** [comment]
* Json is part of the python standard library, so no worries there, json is also made for parsing so it is easy to go back and forth between text and in memory
* pandas is used by bokeh -> pyulog, and px4tools (for our CI) so while you can get by without it, it really should be installed up front as part of a developer install script, along with jinja2 and the like

I think all we need to do is update this line in the dev toolchain manual:

https://dev.px4.io/starting-installing-mac.html#homebrew-installation

It should say

```bash
sudo easy_install pip
sudo pip install pyserial empy pandas jinja2
```

**Comment by LorenzMeier** [comment]
I updated the documentation.

**Comment by jgoppert** [comment]
@priseborough I'm available now if you wanted to sync up.

**Comment by priseborough** [comment]
When I try running it on this log file http://logs.px4.io/plot_app?log=7a3f865f-2013-472b-8345-cee7f3ec1e2d  I get the following error:

  File "process_sensor_caldata.py", line 85
    pdf = PdfPages(pdf_filename)
                               ^
IndentationError: unindent does not match any outer indentation level
Pauls-MacBook-Pro:Tools paul$ python process_sensor_caldata.py /Users/paul/Downloads/02_00_03.ulg 
  File "process_sensor_caldata.py", line 85
    pdf = PdfPages(pdf_filename)
                               ^
IndentationError: unindent does not match any outer indentation level

**Comment by jgoppert** [comment]
In that last patch it needs one more space on that line, I will fix.

**Comment by jgoppert** [comment]
:thumbsup:

**Comment by jgoppert** [comment]
@priseborough, is this good to merge now, still want to meet up to cover usage?

**Comment by priseborough** [comment]
@jgoppert  I'm unable to test it on my machine because despite following the install instructions for pandas, I still get the following error:

Traceback (most recent call last):
  File "process_sensor_caldata.py", line 35, in <module>
    import pandas
ImportError: No module named pandas

I would like to go through this with you if possible. My Skype ID is p_riseborough.

**Comment by mhkabir** [comment]
@priseborough I can help with that. I've sent you a request on Skype.
It worked fine for me on a fresh install : 
```
Kabirs-MacBook-Pro:~ Kabir$ sudo pip install pyserial empy pandas jinja2
Collecting pyserial
  Downloading pyserial-3.2.1-py2.py3-none-any.whl (189kB)
    100% |████████████████████████████████| 194kB 209kB/s 
Collecting empy
  Downloading empy-3.3.2.tar.gz (138kB)
    100% |████████████████████████████████| 143kB 270kB/s 
Collecting pandas
  Downloading pandas-0.19.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (11.9MB)
    100% |████████████████████████████████| 11.9MB 48kB/s 
Collecting jinja2
  Downloading Jinja2-2.9.5-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 345kB/s 
Requirement already satisfied: pytz>=2011k in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pandas)
Requirement already satisfied: python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pandas)
Requirement already satisfied: numpy>=1.7.0 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pandas)
Collecting MarkupSafe>=0.23 (from jinja2)
  Downloading MarkupSafe-0.23.tar.gz
Installing collected packages: pyserial, empy, pandas, MarkupSafe, jinja2
  Running setup.py install for empy ... done
  Running setup.py install for MarkupSafe ... done
Successfully installed MarkupSafe-0.23 empy-3.3.2 jinja2-2.9.5 pandas-0.19.2 pyserial-3.2.1

```

**Comment by jgoppert** [comment]
I think he was able to install but got an import error on running the script.  Can you check that? Probably multiple python versions on the system and the wrong one is the first in the path somehow.

**Comment by priseborough** [comment]
Thank you @mhkabir for getting me unstuck with the python version issue.

I have tested the script file and the following issues need to be fixed.

1) The baro fit is to altitude, not pressure in Pa as required.
2) The baro fit is 3rd order, not 5th order as required.
3) The .params file is not in a format that can be loaded via QGC as per the instructions in the header.

**Comment by jgoppert** [comment]
@priseborough I fixed the issues mentioned above. Please have a look.

**Comment by priseborough** [comment]
I get the following result:

processing sensor_baro_0
processing sensor_gyro_0
processing sensor_gyro_1
processing sensor_gyro_2
processing sensor_accel_0
processing sensor_accel_1
processing sensor_accel_2
Traceback (most recent call last):
  File "process_sensor_caldata.py", line 230, in <module>
    temperature_calibration(args.ulog, not args.noplot)
  File "process_sensor_caldata.py", line 181, in temperature_calibration
    data = coeffs[topic][multi_id]
KeyError: 2

**Comment by jgoppert** [comment]
Can you send me a link to this dataset so I can track it down  and fix.

**Comment by priseborough** [comment]
My testing is producing sensible results using this script so I am happy for it to be merged.

**Comment by priseborough** [comment]
Works with my testing.

**Comment by jgoppert** [comment]
@priseborough Do you have a known working param set that I could diff against.

**Comment by priseborough** [comment]
I will send the param file I get for http://logs.px4.io/plot_app?log=7a3f865f-2013-472b-8345-cee7f3ec1e2d

**Comment by dagar** [comment]
@jgoppert any update here?

**Comment by jgoppert** [comment]
I'm not sure this ended up being useful for @priseborough

**Comment by priseborough** [comment]
It doesn't produce the correct parameter values. It needs to produce equivalent values to the script it is replacing which is this one: https://github.com/PX4/Firmware/blob/master/Tools/process_sensor_caldata.py

**Comment by jgoppert** [comment]
@priseborough would you prefer I fix this or just stick with what you have?

**Comment by TSC21** [comment]
@jgoppert should this be fixed to get in?

**Comment by priseborough** [comment]
@jgoppert I'm OK either way but it does need to produce equivalent fit performance and parameter values. It is a low priority task IMO.

**Comment by dagar** [comment]
Closing the PR as stale, but we can keep the branch for a bit.

**Pull request closed without merging**
