### PR TITLE
Update submodule sitl_gazebo to latest Sat Jun 20 00:38:35 UTC 2020

### PR DESCRIPTION
**Pull request by TSC21**
- sitl_gazebo in PX4/Firmware (28a695dce4e8df66a05d37714ff46367fc4b937b): https://github.com/PX4/sitl_gazebo/commit/846190e8a33063a62997f2ad18c9de5c5233d9f9
    - sitl_gazebo current upstream: https://github.com/PX4/sitl_gazebo/commit/0f5e081842b08903f9f752ab199c1d9a31eab145
    - Changes: https://github.com/PX4/sitl_gazebo/compare/846190e8a33063a62997f2ad18c9de5c5233d9f9...0f5e081842b08903f9f752ab199c1d9a31eab145

    0f5e081 2020-06-19 JaeyoungLim - Fix multivehicle regressions for plane and standard_vtol model
    13f62be 2020-06-19 JaeyoungLim - Fix gazebo7 build failure
    e8b8151 2020-06-19 Supakorn Suttiruang - Add pitching moment control via control surfaces (#521)

### CODE REVIEW

**Comment by TSC21** [comment]
Requires https://github.com/PX4/Firmware/pull/15126 so the tailsitter test can pass.

**Comment by TSC21** [comment]
@lum-supakorn the tailsitter test is failing: http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-15150/2/pipeline/57

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Do you think it might be related to https://github.com/PX4/sitl_gazebo/pull/524 ?

**Comment by TSC21** [comment]
superseded

**Comment by lum-supakorn** [comment]
What was the issue?

**Comment by Jaeyoung-Lim** [comment]
@lum-supakorn tailsitter issue is not solved

**Pull request closed without merging**
