### PR TITLE
Fix incorrect rotation of internal magnetometers

### PR DESCRIPTION
**Pull request by priseborough**
Fixes https://github.com/PX4/Firmware/issues/7325

### CODE REVIEW

**Comment by mhkabir** [comment]
This not the correct fix. It breaks my race-condition fix. I will have look soon and properly fix it, now that we know where it goes wrong.

**Comment by LorenzMeier** [comment]
@mhkabir Did you have a chance to look at this yet?

**Comment by mhkabir** [comment]
Yes I did and I know how to fix it, but i won't get a chance to send the correct PR till tomorrow morning.

**Comment by LorenzMeier** [comment]
Can you provide a few pointers? Given the large number of potentially affected users and the already existing v1.6 tag this is super high priority to fix, so I'd like to take a stab at this today. I think I know what to look for, but I don't want to ignore the work you have already done.

**Comment by mhkabir** [comment]
@LorenzMeier @priseborough OK, fixed properly here. Please test since I don't have hardware : https://github.com/PX4/Firmware/pull/7337

**Pull request closed without merging**
