### PR TITLE
Fixed-wing: allow mission takeoff

### PR DESCRIPTION
**Pull request by AndreasAntener**
I forgot about fixed-wing.. `do_need_takeoff` was never true for fixed-wing therefore the takeoff waypoint couldn't have been set. We need a fixed-wing SITL test :) @dagar can you review?

TODO: SITL test

### CODE REVIEW

**Comment by dagar** [comment]
Wouldn't this still be a good thing for FW? Maybe some altitude changes.

Why does do_need_vertical_takeoff() return true if the mission_item is already a NAV_CMD_TAKEOFF?

**Comment by AndreasAntener** [comment]
My main concern right now is that it doesn't work at all ;). However you're right and we also need to check what happens if there is a takeoff waypoint in the middle of a mission. In theory its not so dramatic as the fixed-wing mission code for takeoff only has impact below climbout height and will be treated as a normal waypoint.

**Comment by dagar** [comment]
Fair enough, merge away. I have more questions about this part of the mission code in general, but we can come back to it later.

**Comment by chief51** [comment]
Is there a 1.5.4 release coming out or what's the best way to change my 1.5.2 build on my pixracer?

Ben

**Pull request merged**
