### PR TITLE
Uorb fixes

### PR DESCRIPTION
**Pull request by bkueng**
Some uorb cleanups, extend documentation & a fix for a subtle bug (see commit messages)
@tumbili

### CODE REVIEW

**Comment by kd0aij** [comment]
It looks like you deleted all of the functional descriptions of methods, not just redundant stuff.

**Comment by bkueng** [comment]
what do you mean exactly? For the C-style functions I removed the ones from the source file, in the header I refer to the class members in `uORBManager.hpp` which have exactly the same interface. The description of these is still there.

**Comment by kd0aij** [comment]
Sorry, I failed to notice the @see lines. Looks good to me now.

**Comment by tumbili** [comment]
@bkueng @LorenzMeier Merging this after checks have passed.
Tested on posix and NuttX!

**Pull request closed without merging**
