### PR TITLE
Fix dataman and allow more waypoints

### PR DESCRIPTION
**Pull request by julianoes**
The dataman started overwriting contents after 256 items because the
item index were only uint8_t. This fix allows for more than 256
waypoints.

Since using more than 256 mission items has been tested and fixed, the
limit can now be raised to more than 256 (but smaller than UINT16_MAX).

Since the whole file is allocated in advance on NuttX, the limit there
is (arbitrarily) set to 2000. For POSIX archs such as SITL, we don't
really need to constrain ourselves any longer.

Found together with @bkueng.
You might be interested to review @AndreasAntener, I think, you asked in the past what the state was.

Tested with up to 65000 mission items using SITL and 400 on a Pixracer.

@LorenzMeier am I missing any architecture setup to test?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Seems to be fine.

**Comment by dagar** [comment]
Make test_dataman appropriate for SITL and enable?

**Comment by dagar** [comment]
Added test_dataman, but limited to 50 items so it runs in a reasonable time. Better than nothing.

**Comment by julianoes** [comment]
Awesome, thanks @dagar

**Comment by LorenzMeier** [comment]
@dagar Your clang-tidy checks are biting you:
```
106 warnings generated.
/home/travis/build/PX4/Firmware/src/systemcmds/tests/test_dataman.c:109:10: error: rand() has limited randomness [cert-msc30-c,-warnings-as-errors]
                usleep(rand() & ((64 * 1024) - 1));
                       ^
```

**Comment by dagar** [comment]
Ha, or alerting us to very real security concerns...
Let's ignore that one for now.

**Comment by karimarar** [comment]
Hallo guys,

i have a question : 
how i can change that code.
where can i find it please  because i have 20000 way points and i want to upload to QGSC . thanks for help

**Pull request merged**
