### PR TITLE
added library for tailsitter optimal recovery

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by tumbili** [comment]
Tested on 24.11.2105. Minor fixes to come in. Will be merged together with #3090

**Comment by tumbili** [comment]
I will change this to be a class which will handle tailsitter recovery.

**Comment by LorenzMeier** [comment]
Would be good if this would get into a state where it can be actually test-flown. If you do rework things after the test-flight in the future, please do at least a bench-test with the reworked state. That does consume very little time but ensures that we don't continue to have dangling changes which are not actually ready to be integrated.

**Comment by tumbili** [comment]
Closing in favour of #3352

**Pull request closed without merging**
