### PR TITLE
MAV_CMD_DO_LAND_START

### PR DESCRIPTION
**Pull request by dagar**
MAV_CMD_DO_LAND_START
- both a waypoint and command
- as a waypoint it marks the beginning of a landing sequence, like the approach and land for a plane
- as a command it switches to mission at the MAV_CMD_DO_LAND_START marker (implemented with MAV_CMD_MISSION_START)

Tested in SITL, but could probably use a little more testing.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Can you fix CI?

**Comment by dagar** [comment]
Fixed

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by LorenzMeier** [comment]
ok, so this worked.

**Comment by LorenzMeier** [comment]
Please rebase and flight test. Is there an associated PR for QGC which enables the UI to run this?

**Comment by dagar** [comment]
Inserting MAV_CMD_DO_LAND_START in the mission is already there. 

I haven't decided how to handle sending the command or if it should somehow be combined the landing mode.

One option I considered was updating QGC guided mode land to send MAV_CMD_DO_LAND_START instead of switching to LAND mode. Then onboard switch to mission at MAV_CMD_DO_LAND_START if available, otherwise switch to LAND mode. That could be dangerous though as I doubt the current LAND mode landing is good enough for most FW users. Unless we added a param to block landing mode for FW?

Thoughts?

**Comment by dagar** [comment]
I think I'm going to do mission start a bit differently without having to republish offboard_mission.

**Comment by LorenzMeier** [comment]
So this will change again?

**Comment by dagar** [comment]
Yes, I think so.
What do you think of commander handling VEHICLE_CMD_NAV_WAYPOINT as a switch to auto mission? Just like VEHICLE_CMD_NAV_{TAKEOFF, LAND} request main state change to AUTO_{TAKEOFF, LAND}.

**Comment by LorenzMeier** [comment]
Fine for me. I want to move to an action based architecture where you tell the vehicle what you want and not programmatically take it through steps. That allows for leaner but also more defined interfaces.

**Comment by dagar** [comment]
I'm interested in hearing more about your ideas for action based architecture. I see a lot of complexity developing on the GCS side that I personally think might make more sense in the firmware. 

My goal for these commands is to make them (mostly) atomic. Send a command to do something that requires being in mission (start or land), but only switch if the mission (+ land) is valid. Internally it's broken into multiple commands between navigator and commander.

**Comment by dagar** [comment]
-closes #4017

**Comment by dagar** [comment]
TODO: Rebase and test again

**Comment by dagar** [comment]
TODO: Rebase and test again

**Pull request merged**
