### PR TITLE
add option to select full attitude control in ACRO mode

### PR DESCRIPTION
**Pull request by kd0aij**
new parameter is ACRO_ATT: default 0 is gyro-only rate control
change to 1 for full rate mode attitude control

flight tested on 250 size FPV racer (no flips or inverted flight yet)
flips tested in SITL; okay if MC_ACRO_P/R/Y_MAX rates are achievable by the airframe.

### CODE REVIEW

**Comment by kd0aij** [comment]
- now stable in SITL even if rate demand is greater than vehicle can achieve
- ready for flight testing flips and inverted flight

Question: yaw is currently implemented as rotation about body z axis, but would it be preferable to rotate about the Earth Z axis instead?

**Comment by julianoes** [comment]
@kd0aij I don't understand how the two modes differ. Can you try to explain it again? What problem are you trying to solve?

**Comment by kd0aij** [comment]
@julianoes I would hope the difference is obvious when you look at the new code (and comments) in mc_pos_control. If not, please suggest a way to improve the readability.
To reiterate: this ACRO mode implements control of **attitude**, instead of just gyro rate. That eliminates drift (if the attitude estimator is correct), and highlights shortcomings in the estimator if not.
Regarding "problems" solved, ACRO mode will be a necessity for variable pitch quads capable of sustained inverted flight, and I'd like to see it make full use of all available sensor data.

**Comment by kd0aij** [comment]
What's going on with the Travis failure? The log says all tests passed, and I can't find any error messages in it.

**Comment by julianoes** [comment]
@kd0aij thanks for the explanation. What's the reason to keep the gyro only mode around?

**Comment by kd0aij** [comment]
There's good reason to believe the attitude estimator could get confused in highly dynamic flight (which I have not been able to demonstrate myself; not enough acro skill). In that case one would need to fall back to rate-only control.

Unfortunately, either mocap or a very competent test pilot would be required to recognize dynamic attitude estimation errors. In https://github.com/PX4/Firmware/pull/4989 I did testing on a turntable at 45RPM (replicating Bill Premerlani's experiment) and implemented "dual" attitude estimators to compare results with and without certain compensation. This confirmed that Bill's (MatrixPilot complementary filter) approach to handling fast rotations works well. I was also experimenting with using the magnetometer as an additional reference for vertical as an alternative to GPS velocity info, and that looks promising.

**Comment by julianoes** [comment]
Hm interesting, I have actually seen attitude diverge quite a bit (sometimes around 40 degrees) when doing FPV on my 210 racer presumably due to high vibrations, however, the angular rates would still not diverge (or only very slowly). The position estimate was usually completely garbage with my racers but that's another topic.

**Comment by kd0aij** [comment]
@julianoes How are you observing the attitude estimation error? Do you have an artificial horizon in an OSD?

So far, I've been flight testing both ACRO modes via LOS flight, and comparing the "feel" when flying small (slow) circles trying to maintain a constant bank angle and forward speed. I'm also flying a stock Vortex 250 (Cleanflight) the same way for comparison and they all seem the same to me. I need to find someone who can do 20G pylon turns to properly test this :)

**Comment by kd0aij** [comment]
Oh, I asssumed you were in ACRO mode. And yes, stabilized mode is a good way to check for attitude errors, since center stick won't be level if there's any error. With hard-mounted pixracers on latest master, I'm unable to induce noticeable attitude errors in stabilize mode though.

**Comment by julianoes** [comment]
Ah fair question then. Yes, I haven't got a decent ACRO tuning yet, and I'm also lacking the skills.

**Comment by kd0aij** [comment]
replaced by https://github.com/PX4/Firmware/pull/5498

**Pull request closed without merging**
