### PR TITLE
Handling and logging the RC RSSI value

### PR DESCRIPTION
**Pull request by bartosz-wawrzacz**
See commit messages.

### CODE REVIEW

**Comment by bartosz-wawrzacz** [comment]
Seems that Travis doesn't like my formatting - one added tab in the code. Should I re-open this PR with the fix to have it green?

**Comment by LorenzMeier** [comment]
Just push a commit to your branch.

**Comment by LorenzMeier** [comment]
Thanks! Could you describe the initial symptom? It looks like the math was so wrong that it should have been initially completely off?

**Comment by bartosz-wawrzacz** [comment]
Actually the math stays the same - just instead of doing X / (Y/100) it's (X * 100) / Y. This way you don't lose accuracy when the min and max PWM values are close to each other (as they are ints not floats).

I our case:
_rssi_pwm_min = 900
_rssi_pwm_max = 1050

For the input value of 1050 you would get:
(1050-900) / ((1050-900)/100) = 150 / (150/100) = 150 / 1 = 150 -> gets clamped to 100
And for 1000:
(1000-900) / ((1050-900)/100) = 100 / (150/100) = 100 / 1 = 150 -> also 100

With the fix:
((1050-900) * 100) / (1050-900) = (150 * 100) / 150 = 100
((1000-900) * 100) / (1050-900) = (100 * 100) / 150 = 66

**Pull request merged**
