### PR TITLE
commander: add vehicle-status nav_state change timestamp

### PR DESCRIPTION
**Pull request by dagar**
Possibly helpful for https://github.com/PX4/Firmware/issues/13293.

### CODE REVIEW

**Comment by Stifael** [comment]
that should work.
I will quickly test the two corner cases

**Comment by dagar** [comment]
Added a navigator change to populate the timestamp of the actual position setpoint (within the triplet).

**Comment by Stifael** [comment]
I was only able to test one of the corner cases where the `vehicle_status` is newer than the `triplet`, and that worked. 
I am confident that the second corner case where the `triplet` is outdated works as well. I will come back once I fixed the bug that prevents me from testing it 

I will also open a PR based on this where I pass the timestamp to FlightTasks.

**Comment by dagar** [comment]
Even if we don't ultimately use these timestamps for FlightTasks I think they're still useful. Merging.

**Pull request merged**
