### PR TITLE
Bring SITL back to life

### PR DESCRIPTION
**Pull request by julianoes**
Reverted the evil commit, works again.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I'll try to fix it proper. I have flown dozens of times in jMAVSim without any regression - can you explain the steps to repro?

**Comment by julianoes** [comment]
```
git checkout master
git submodule update
make clean
make posix gazebo
```

Then wait for home, and do `commander takeoff` and it slides along, flips and the estimator goes towards Rapperswil. :smiley:

**Comment by LorenzMeier** [comment]
Can you get me a screenshot of the Accel Z measurements of your fixed state? I'd like to see how they look when its idle on the ground.

**Comment by julianoes** [comment]
terrible_accel
Yer that looks pretty terrible.

**Comment by julianoes** [comment]
That would explain the bad flight performance with lots of slow oscillations in gazebo but that's another issue.

This is a general takeoff issue that affects definitely both jMAVSim and gazebo.

**Comment by LorenzMeier** [comment]
What are the steps with jMAVsim to repro?

**Comment by julianoes** [comment]
Same thing.

```
git checkout master
git submodule update
make clean
make posix gazebo
```

```
commander takeoff
```

**Comment by LorenzMeier** [comment]
Got it. This must actually be much more recent than the commit you bisected. Because I tested that commit that way.

**Comment by julianoes** [comment]
Well I did a bisect and that's what I got.

**Comment by LorenzMeier** [comment]
I was inaccurate. I did fire the takeoff command via QGC, not shell. And it turns out the shell version did not stick to the API. I just fixed that and now things behave.

**Comment by LorenzMeier** [comment]
I also replaced EKF2 with LPE in SITL. You should find your workflow to be back to bearable. Still looking into speeding up boot time.

**Comment by julianoes** [comment]
Aha, nice catch!

Thanks.

**Pull request closed without merging**
