### PR TITLE
Orbit approach with a line trajectory library

### PR DESCRIPTION
**Pull request by MaEtUgR**
**Describe problem solved by the proposed pull request**
As requested by @RomanBapst I'm fixing the initial approach of the vehicle to the circle in orbit mode. This should vastly improve the user experience when using the Orbit mode.

**Test data / coverage**
SITL tested. @RomanBapst please submit your feedback on user experience.

**Describe your preferred solution**
The `StraightLine` library is supposed to implement a motion primitive to move the vehicle from point A to B on a planned trajectory such that this functionality can be reused where such setpoint generation is useful. The initial approach to the orbit circle is a very good example of such a use case and is now the first client code to test the interface of the library.

The `StraightLine` implementation currently does a velocity ramp based on the progress measured in distance between the start and endpoint. It ramps up the velocity for half the way and down the second half. The velocity is then limited to the specified speed e.g. the cruise speed.

**Describe possible alternatives**
The `StraightLine` implementation here is working but not yet optimal. The idea is to have a minimum viable implementation now to set a baseline that can be tested and built on. I would be very interested to bring in @bresch's jerk optimized planning to be reused in this form.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@MaEtUgR When this is done, sounds like we might need some more docs; note that I don't fully understand what the change is. It sounds like the vehicle will follow the same path for orbit as before, but just change the way that it accel/decelerates to start the orbit. 

Docs to consider are http://docs.px4.io/master/en/flight_modes/orbit.html . Depending on how generic this is/what the options are, we might need to create some docs a bit like http://docs.px4.io/master/en/config_mc/mc_slew_rate_type_trajectory.html

**Comment by MaEtUgR** [comment]
I
- rebased on master
- fixed the issues when changing radius during orbiting (thanks for reporting @RomanBapst )
- fixed the yaw feed-forward resulting in a small weir offset during initial approach

@hamishwillee Thanks for chiming in. The orbiting itself stays the same but when commanding a new orbit the vehicle approaches the circle in a more controlled less aggressive way on a straight line before starting to rotate.

**Comment by MaEtUgR** [comment]
We just come from real-world testing with a big vehicle. The approach is now much more agreeable. I don't say it's perfect but it makes a big difference for orbit user experience. Improvements of the `StraightLine` implementation will make it better and the most aggressive behavior is now actually pausing with high velocity. We need a stopping motion primitive to solve that, I'll address it.

**Comment by hamishwillee** [comment]
> The orbiting itself stays the same but when commanding a new orbit the vehicle approaches the circle in a more controlled less aggressive way on a straight line before starting to rotate.

Thanks @MaEtUgR Then IMO no docs are required :-)

**Comment by MaEtUgR** [comment]
@RomanBapst Since this is well tested, clearly much better than before and had no conflicts. I'm merging as soon as CI ran successfully.

**Pull request merged**
