### PR TITLE
Update mavlink trajectory

### PR DESCRIPTION
**Pull request by mrivi**
This PR updates the mavlink `TRAJECTORY` message to be compatible with the recently merged 
https://github.com/mavlink/mavlink/pull/915

This PR needs to be merged together with the update of the mavlink submodule otherwise master doesn't build anymore.

It would be great to also sync with the mavros update. Otherwise the pipeline is broken.

### CODE REVIEW

**Comment by dagar** [comment]
I updated the mavlink submodule. We can merge after CI passes.

**Comment by mrivi** [comment]
@dagar could you please wait for mavros?

**Comment by mhkabir** [comment]
@mrivi Do you have a PR for mavros yet?

**Comment by mrivi** [comment]
I am fixing some things on it

**Comment by dagar** [comment]
Feel free to merge when you're ready.

**Pull request merged**
