### PR TITLE
param subsystem: Only send the instantiated parameters via telemetry

### PR DESCRIPTION
**Pull request by LorenzMeier**
This reduces the number of parameters exposed via Telemetry.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@DrTon I tested this successfully on the bench. It cuts down the number of parameters in the multicopter mode to 278 and the total transmit time via USB to ~1.5 seconds. It should improve on a telemetry link dramatically as well.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer @dogmaphobic You will love this as well. It makes the UI much more responsive.

**Comment by kd0aij** [comment]
:+1:

**Comment by DonLakeFlyer** [comment]
It started getting so long I moved up the parameter download progress bar in QGC to the top of my list!

**Comment by LorenzMeier** [comment]
So the issue is that e.g. the battery params are missing, probably because we are not reading all them.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Could you provide some more details on exactly what this pull does? Does it mean that only parameters which are referenced prior to the first full list request are sent across? Does a parameter being at a default value cause anything to be different?

Thinking about affect on parameter editor as well as FactSystem.

**Comment by dogmaphobic** [comment]
On a minor note, it also affects the current Quick View as it build its list based on received messages.

**Comment by DonLakeFlyer** [comment]
QuickView come from mavlink messages not parameters.

**Comment by dogmaphobic** [comment]
After I wrote that I realized it. You beat me to it... :)

**Comment by LorenzMeier** [comment]
@DonLakeFlyer @dogmaphobic What this patch does is to only transmit parameters which have been selected with param_find(). So in a way it does the same as a compiler when pruning unreachable code. It means that all apps which have not been started are not exporting their parameters.

**Comment by DonLakeFlyer** [comment]
My concern is whether it will kick out a parameter that QGC is referencing. That will cause an assert in QGC. Maybe because it isn't reference at boot time, but only refernced later say when you arm the system.

**Comment by LorenzMeier** [comment]
The whole assert story still only makes partially sense to me. I have merged the patch and it works quite nicely. You can try it by flashing off master.

**Comment by DonLakeFlyer** [comment]
The UI code expects parameters to always be available. If they are not available it's an indicator that something has gone very wrong. Because of this the UI code does not code defensively to the possibility of a parameter being missing. It generally just asserts for that case since it likely indicates a code error. 

There are a few optional parameters like the new ones recently added for calibration. In those few cases the code expects the possibility that these may be missing depending on the firmware version you are running.

**Pull request closed without merging**
