### PR TITLE
Add address sanitizer to SITL pipeline

### PR DESCRIPTION
**Pull request by LukasWoodtli**
- Environment variables for building with asan
- Docker argument for leak sanitizer
- Regex for tests to fail on sanitizer error

Signed-off-by: Lukas Woodtli <woodtli.lukas@gmail.com>

Please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/) to align on pull requests if necessary.

**Test data / coverage**
Logs uploaded to http://logs.px4.io or screenshots.

**Describe problem solved by the proposed pull request**
A clear and concise description of the problem, if any, this feature will solve. E.g. I'm always frustrated when ...

**Describe your preferred solution**
A clear and concise description of what you have implemented.

**Describe possible alternatives**
A clear and concise description of alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots for the feature request here.

### CODE REVIEW

**Comment by TSC21** [comment]
@LukasWoodtli can this be added to `sitl_gazebo` repo Travis CI as well?

**Comment by LukasWoodtli** [comment]
@LorenzMeier I'm glad I could help. Hopefully I’ll be able to contribute more soon!

**Comment by LukasWoodtli** [comment]
@TSC21 I'll add it to sitl_gazebo as soon as I get some time.

**Comment by TSC21** [comment]
@LukasWoodtli awesome! Thanks for contributing!

**Pull request merged**
