### PR TITLE
Attitude loop speed

### PR DESCRIPTION
**Pull request by LorenzMeier**
@AndreasAntener This is still WIP, but ready for initial testing: This change should not change much about the flight behaviour, but make it in general a bit smoother and snappier.

### CODE REVIEW

**Comment by AndreasAntener** [comment]
@LorenzMeier is this regarding my comment about FW stabilized not being so snappy anymore?

**Comment by LorenzMeier** [comment]
No its not. Its just a general improvement we can do.

**Comment by AndreasAntener** [comment]
Ok. I think I can test that on Sunday.
What should I try to look for except the general behaviour? I assume a stabilized and mission flight would be good?

**Comment by LorenzMeier** [comment]
Yes, that would be good. It should work similar or better.

**Comment by LorenzMeier** [comment]
Closing this and re-opening against the release branch.

**Pull request closed without merging**
