### PR TITLE
[WIP] Telemetry status: report type and ID of remote system

### PR DESCRIPTION
**Pull request by jlecoeur**
This PR adds infos about remote MAVLink systems into the topic telemetry_status:
- the remote system type (enum MAV_TYPE). This allows to know if a mavlink instance is connected to a ground control station, needed by #9440 
- the remote system ID and component ID are set from heartbeat messages sent by the remote system, they were previously set from radio status message inserted by the radio module.
- `mavlink status` prints these infos, useful to identify which instance is connected to what

Please review carefully the changes in Commander, I do not want to break the detection of loss of GCS telemetry.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Quick question: If the link is connected to multiple external/remote systems, what happens? Do we maybe need to report 0 then for ALL / broadcast? I want to avoid having the remote ID toggling randomly.

**Comment by jlecoeur** [comment]
Good point. We can detect if the ID changes more than once (ex 0 - > 1 - > 255) and report 0.

**Comment by lamping7** [comment]
This is causing a failsafe activation in CI leading to a mode switch failure. Failsafe repeatedly cycles between enabled and disabled. Unfortunately, I don't have more info than that.

ex:
```
[ INFO] [1526507826.169861039, 28.210000000]: FCU: Failsafe mode disabled
[ INFO] [1526507827.115278143, 29.154000000]: FCU: Failsafe mode enabled
[ INFO] [1526507827.165489924, 29.204000000]: FCU: Failsafe mode disabled
[ INFO] [1526507828.110843369, 30.150000000]: FCU: Failsafe mode enabled
[ INFO] [1526507828.161152307, 30.200000000]: FCU: Failsafe mode disabled
[ INFO] [1526507829.110614177, 31.148000000]: FCU: Failsafe mode enabled
[ INFO] [1526507829.160875006, 31.198000000]: FCU: Failsafe mode disabled
[ INFO] [1526507830.117813725, 32.154000000]: FCU: Failsafe mode enabled
[ INFO] [1526507830.168128978, 32.206000000]: FCU: Failsafe mode disabled

```

**Comment by dagar** [comment]
Revisiting this idea - https://github.com/PX4/Firmware/pull/10933

**Pull request closed without merging**
