### PR TITLE
check vel_setpoint instead of stick input for position lock

### PR DESCRIPTION
**Pull request by baumanta**
When using the collision prevention library the position lock was broken when using the smooth velocity mode. This can be fixed by checking the velocity setpoint (which is modified by the collision prevention) instead of the raw stick input to determine whether the position lock is activated.

### CODE REVIEW

**Comment by bresch** [comment]
@PX4/testflights Could you test this PR, on a multicopter, mainly in position control and altitude modes please?

**Comment by jorge789** [comment]
**Tested on PixRacer V4:**
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:**
https://review.px4.io/plot_app?log=ad7f07b7-e54a-4d32-83ac-88ea178b1499

**Tested on CUAC+ V5:**
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:**
https://review.px4.io/plot_app?log=3f6b8ba7-31b9-4b47-a989-15a2a4e226cc

**Comment by Junkim3DR** [comment]
**Tested on Pixhawk Pro v4:**

**Modes Tested**
- Position Mode: Good.
- Altitude Mode: Good.
- Stabilized Mode: Good.
- Mission Plan Mode (Automated): Good.
- RTL: Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:**
https://review.px4.io/plot_app?log=d7b7af7d-2dea-42c8-acb4-933edcc44e68












**Tested on Pixhawk 4mini v5:**

**Modes Tested**
- Position Mode: Good.
- Altitude Mode: Good.
- Stabilized Mode: Good.
- Mission Plan Mode (Automated): Good.
-RTL: Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:**
https://review.px4.io/plot_app?log=7ed7e325-88ad-4183-880f-deda04048032

**Comment by bresch** [comment]
Thanks @jorge789 and @Junkim3DR !
@baumanta I merged master into the branch and we can merge once CI passes.

**Pull request merged**
