### PR TITLE
Fixes TX DMA on px4_fmu-v5 

### PR DESCRIPTION
**Pull request by davids5**
This fixes https://github.com/PX4/Firmware/issues/14659#issuecomment-617035607

It requires https://github.com/PX4/NuttX/pull/113

### CODE REVIEW

**Comment by dagar** [comment]
Should we fully revert the revert? https://github.com/PX4/Firmware/pull/14771

**Comment by davids5** [comment]
> Should we fully revert the revert? #14771

Yes, but I wanted so cross testing first.

**Comment by dagar** [comment]
Previously on fmu-v5 it was USART3 (TELEM2) where the companion computer is typically connected.

**Comment by dagar** [comment]
I'll also give this a try.

**Comment by davids5** [comment]
@dagar F4 does not have TX DMA

**Comment by dagar** [comment]
> @dagar F4 does not have TX DMA

Ha, I guess it was a good placebo.

**Comment by dagar** [comment]
Bench tested on px4_fmu-v5.

**Pull request merged**
