### PR TITLE
Update mc_pos_control_main.cpp

### PR DESCRIPTION
**Pull request by zerohit**
the z axis is [sin(theta)cos(phi) -sin(phi) cos(theta)cos(phi)]

### CODE REVIEW

**Comment by Stifael** [comment]
I try to walk through this problem:
A rotation matrix can be constructed by the multiplication of several rotation matrices. One possibility is the R_321 matrix, which is constructed by multiplying the Rotational matrix around each coordinate system individually: R_321 = R_zyx = R_z * R_y * R_x = R_yaw * R_pitch * R_roll. Since we are only interested in roll and pitch, we can consider only the R_y and R_x matrix. 
R_tilt = R_y * R_x = [cy, 0, sy,            [1, 0, 0
                                   0,   1, 0 ,       *     0, cx, -sx
                                  -sy, 0, cy ]            0, sx, cx]

= [cy,  sy*sx,  sy*cx
    0,      cx     , -sx
   -sy,  cy*sx,  cy*cx]
= 
[r00,  r01, r02;
 r10, r11, r12;
 r20, r21, r22]

where s = sin; c = cos

- from r12, we have: -sx = -sin(roll) = -sin(r12) => roll = -arcsin(r12)

- from tan(#) = sin(#)/tan(#) we have tan(pitch)=tan(y)=sin(y)/cos(y)=sy/cy = sy*cx/(cy *cx)=r02/r22 =>
 roll = atan2(r02, r22).

Howerver, this is only true if cx = cos(x) = cos(roll) != 0, or roll != +- pi/2. if that is the case, 
then pitch is undefinded:
cy*sx = cos(y)*sin(x) = cos(y) = r21
sy*sx= sin(y)*sin(x) = sin(y) = r01
have two equation and one unknown.

So in our case, I agreed with @zerohit  that pitch is atan2(z_roll_pitch_sp[0], z_roll_pitch_sp2) but only if cos(roll) not equal 0. if that is the case, the roll with then just be -argsin(z_roll_pitch_sp[1]).
This is in fact the opposite of the previous implementation. 

@zerohit : can you pleases eleaborate about the roll?

**Comment by zerohit** [comment]
1. In the present codes, pitch_new = asin(r02), roll_new=-atan(r12,r22), it means R_tilt = R_x * R_y ? However R_sp is computed by R_zyx = R_z * R_y * R_x ?  It's confused.
2. Also in the present codes, if pitch = +-pi/2, then roll is undefined. 
3. According to the present codes, if  rpy sp = [pi/2 -pi/4 0] and yaw_error=0, then the calculated angles will become [pi/2 0 0]. We lose the pitch angle.
4. If roll = +-pi/2, can we set the new pitch angle = _att_sp.pitch_body ?

**Comment by Stifael** [comment]
@zerohit: did you read my comment :) ?
you are right about having pitch = atan2(r02,r22) (if roll not equal pi/2) and roll should be -arcsin(r12). but please can you elaborate what you did with the "if" statement, where you assign the roll according to the sin_pitch

**Comment by tumbili** [comment]
@Stifael @zerohit Thanks for looking at this! 
@zerohit Has correctly stated that the tilted z axis can be expressed in earth fixed frame as
[sin(theta)cos(phi) -sin(phi) cos(theta)cos(phi)]
and captures the desired tilt when looking into the direction of the desired heading.
The calculations look fine to me, I believe the roll is calculated as follows

if sin(pitch) != 0:
divide 2. vector element by 1. vector element which gives
-sin(phi) / (sin(theta) * cos(phi)) = vec(1) / vec(0)

-> tan(phi) = -sin(theta) * vec(1) / vec(0)

this can now be solved for phi by using atan2. This equation does not work if sin(theta) = 0.
For the other case you can do the same thing but use the the 2. and the 3. vector element.
@Stifael Does that make any sense?

**Comment by Stifael** [comment]
Ok, I think we all agree on the following points:
- the previous implementation is not correct.  
- rotational tilt matix follows the definition of R_tilt = Ry * Rx

I have to look into the implementation of what you guys used (not entirely convinced yet). It is important that we keep in mind that when using the equation for tilted z axis, the order of rotation should be preserved. As @zerohit also pointed out, the pitch angle is not defined when roll is +-pi/2. Thereofore, it seems strange to compute the pitch first, and then the roll. That is first opposite of the definition of R_tilt (first roll and the pitch).
It is also worth to mention, that with the current Px4 implementation (at least what I think it is), the vehicle can only reach a tilt less than +-pi/2, and therefore the case of having roll +-pi/2 should not be reached anyway. nonetheless, this case needs to be take care of as well

**Comment by Stifael** [comment]
I will do a new pull request applying the above changes

**Comment by tumbili** [comment]
@Stifael I can help with testing.

**Comment by LorenzMeier** [comment]
@Stifael Can you go in general through the 1.5.1 issue list and make sure you comment on anything that is relevant to your line of work? Thanks!
https://github.com/PX4/Firmware/milestone/20

**Pull request closed without merging**
