### PR TITLE
Tools: update sitl_gazebo

### PR DESCRIPTION
**Pull request by TSC21**
Addresses:
1. SDF validation and integration of it to CI: https://github.com/PX4/sitl_gazebo/pull/156
2. Look for Mavlink headers on the local repos first: https://github.com/PX4/sitl_gazebo/pull/160

### CODE REVIEW

**Comment by TSC21** [comment]
Just to confirm the Mavlink search is working properly:
http://ci.px4.io:8080/blue/organizations/jenkins/Firmware/detail/PR-8597/1/pipeline#step-1002-log-86

**Comment by TSC21** [comment]
Jenkins test this please.

**Comment by TSC21** [comment]
ROS VTOL mission old 3 seems to be failing.

**Comment by TSC21** [comment]
Jenkins test this please.

**Comment by dagar** [comment]
It will likely pass after a restart, but clearly some of these tests still have intermittent failures. Please start opening github issues for test failures like this.

**Pull request merged**
