### PR TITLE
move ekf2 and mc_pos_control to WQ

### PR DESCRIPTION
**Pull request by dagar**
Opening this as an experiment to see if it's worthwhile moving both ekf2 and mc_pos_control to the same WQ. This is potentially worthwhile as it will save quite a lot of stack (6-7 KB), and a little bit of cpu (maybe 2-3% TBD).

### CODE REVIEW

**Comment by dannyfpv** [comment]
tested on pixhawk4 v5 f-450
- Modes Tested
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
- Procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.
- Notes
No issues noted, good flight in general.

Pr log:
https://review.px4.io/plot_app?log=d0dd8ee0-856d-4403-bbb1-5ddc5a5c908c

master  log:
https://review.px4.io/plot_app?log=12ce1554-5313-48fb-be4f-e04a6c49106b





tested on pixracer v4 f-450
- Modes Tested
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
- Procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.
- Notes
No issues noted, good flight in general.

Pr log:
https://review.px4.io/plot_app?log=6e167d47-a556-4ae9-895e-c77aa48a8713

master  log:
https://review.px4.io/plot_app?log=b50324e3-2342-4a2b-98a7-44f2961fb3a0

**Comment by dagar** [comment]
This saves nearly 7K of memory on a pixracer configured as a generic multicopter and from the logs I don't see any other issues.

Let's try again with `mc_pos_control` limited to 50 Hz updates (as it is in master) and compare the cpu usage.

**Comment by dagar** [comment]
Thanks @dannyfpv. Could you repeat that same test again with the current state of the PR? Just the pixracer is fine.

**Comment by dagar** [comment]
Once this is merged it should be safe to lower the CONFIG_MAX_TASKS again.

**Comment by dagar** [comment]
Relative to current master this frees up about 8 KB of ram on px4_fmu-v4 (configured as generic multicopter).

``` Console
nsh> free
             total       used       free    largest
Umem:       230624     181744      48880      46160   <-- master
Umem:       231712     174848      56864      53440   <-- PR
````

**Pull request merged**
