### PR TITLE
Fix mission change speed

### LINKED ISSUE #11764: Mission speed change not working
In recent jMAVSim SITL tests using the [Dronecode SDK](https://github.com/Dronecode/DronecodeSDK/blob/develop/integration_tests/mission_change_speed.cpp) I found that the MAVLink command [MAV_CMD_DO_CHANGE_SPEED](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_CHANGE_SPEED) does not seem to have any effect.

No matter what the speed is set, the vehicle speed is always 5 m/s presumably the cruise velocity.

Firmware version: 0b548fa6849e7a608b4c120fb66a760e51806056

### PR DESCRIPTION
**Pull request by bresch**
fixes #11764 

@julianoes Please check if it fixes the issue.

### CODE REVIEW

**Comment by julianoes** [comment]
Thanks, this doesn't fix it. It does work for speeds set slower than cruise velocity but for speeds faster than cruise we're limited to cruise.

**Comment by bresch** [comment]
@julianoes Hmm, then I don't understand how your fix worked before.

**Comment by bresch** [comment]
@julianoes Should be good now but I'm not sure of the side effects. We need to do a non-regression test before merging that.

**Comment by julianoes** [comment]
Still the same problem. If you want to reproduce the tests, this is the Dronecode SDK command:
```
make && build/default/integration_tests/integration_tests_runner --gtest_filter="SitlTest.MissionChangeSpeed"
```

**Comment by julianoes** [comment]
Replaced by https://github.com/PX4/Firmware/pull/11836.

**Pull request closed without merging**
