### PR TITLE
SDIO Clocks were wrong.

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier 

In working an issue on SDIO I noticed that all the SDIO clock stanza were wrong. This crept in from master before the nuttx upgrade. 

Since CONFIG_SDIO_DMA is true we were configuring the clock at 12 Mhz not 16 Mhz and the initial value was 266 kHz not 400Khz

### CODE REVIEW

**Comment by LorenzMeier** [comment]
What is the testing level of this on different boards? On which one(s) did you test?

**Comment by davids5** [comment]
Only on px4fmu-v2 so far.

**Comment by pkocmoud** [comment]
I can fly with a Pixracer in about 1.5 hours.

**Comment by pkocmoud** [comment]
Flies fine on Pixracer.

http://logs.px4.io/plot_app?log=779e879f-eaf5-4480-ba3d-8141165c0b34

**Comment by LorenzMeier** [comment]
Thanks!

**Pull request merged**
