### PR TITLE
commander cleanup battery failsafe handling

### PR DESCRIPTION
**Pull request by dagar**
Needs careful testing.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by LorenzMeier** [comment]
@PX4/testflights Please test this PR with low batteries and let the system run into the low battery RTL handling.

**Comment by Avysuarez** [comment]
**Flight with pixhawk 4 (V5). Battery fail-safe doesn't work.**
https://review.px4.io/plot_app?log=e727e3fa-eac4-4ca3-888f-5d8f0a271cf9

**Flight with pixhawk 2.1 (V3). Battery fail-safe respond properly, no issues.**
https://review.px4.io/plot_app?log=4acde8b6-6543-4bac-ae0a-9e2c47bf9996

**Comment by dannyfpv** [comment]
test on pixhawk 1 v2. not work the low battery safe (not rtl)
https://review.px4.io/plot_app?log=0dfba974-e0c8-4a08-85ac-4256edff61c5

test on pixhawk mini v3. work properly.
https://review.px4.io/plot_app?log=0ea7ce42-f917-48e7-9ae6-800f57e4aa81

test on pixhawk pro v4. work properly.
https://review.px4.io/plot_app?log=6bdfcc81-d92f-40ee-a643-5a63f7b0d399

**Comment by dagar** [comment]
Thanks, I'll do some bench testing with a pixhawk 4.

**Comment by santiago3dr** [comment]
flight on Pixracer (v4)
battery failsafe does not look to be working
https://logs.px4.io/plot_app?log=90e69131-92e1-426f-9d04-1d16aa7edc77

**Comment by dagar** [comment]
@santiago3dr this is because you have the circuit breaker "power supply check" set.

**Comment by dagar** [comment]
I'll remove the extended system power circuit breaker behaviour so that it's consistent with current master, but we should separately look at your setups where it's been enabled.

**Comment by dagar** [comment]
@santiago3dr could you give this another try?

**Comment by santiago3dr** [comment]
reset power circuit breaker, battery failsafe working now:
https://logs.px4.io/plot_app?log=6de8728f-b371-48fe-ae60-06e4f9c5d5ac
https://logs.px4.io/plot_app?log=1feef14f-cc28-404f-a975-951d62263635

**Comment by dagar** [comment]
Thanks for testing.

**Pull request merged**
