### PR TITLE
Tools/setup.sh only install python3 dependencies

### PR DESCRIPTION
**Pull request by dagar**
Also made a few other improvements to make it easier and safer to repeatedly rerun the script.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@dagar I still haven't tested this in anger. Do you think that we're at the point where these might replace many of the devguide scripts?

**Comment by dagar** [comment]
The CI system uses them for "production builds" and I use them for real on Ubuntu (at least current LTS) and MacOS. I think we'd have to do a quick pass to check for parity. Off the top of my head they're still missing FastRTPS, but I think until there's more traction (or a clean package) that could be a standalone set of instructions (a few lines).

**Comment by hamishwillee** [comment]
>I think until there's more traction (or a clean package) that could be a standalone set of instructions (a few lines).

Does that mean yes or no?  (could be either, but I "think" probably it means that "you can use this now if you don't need FastRTPS, and the process would be easier that what we currently have")

**Comment by dagar** [comment]
It's a yes, but it may not be 100% identical.

**Pull request merged**
