### PR TITLE
VTOL: explicitly start FW & MC controllers in VTOL mode

### PR DESCRIPTION
**Pull request by dagar**
We know at startup when launching the controllers if the system is a VTOL or not. This allows using the newer uORB::Publication API and simplifies a few other minor parts of init.

### CODE REVIEW

**Comment by sfuhrer** [comment]
@dagar This looks good at a first glance. Also SITL testing for standard VTOL looks good. It though seems like master for was broken for tailsitters when you merged it into this PR, it can't climb in FW (tested also master before your commit, c8e59c4, there it's the same). So could you please rebase, then I can give it a more thorough pass (including SITL and real world flying).

**Comment by dagar** [comment]
Thanks for the review @sfuhrer. This needs to be rebased and updated with mc_rate_control as well.

**Comment by dagar** [comment]
Updated to add vtol start to mc_rate_control, rebased on master, and bench tested.

**Comment by dagar** [comment]
> Thanks for updating @dagar . I've looked through it, and also sitl tested on standard VTOL and tailsitter. No issue found. We probably also should get some real world testing Id' say, or what do you think?

Probably doesn't really matter for this PR, but certainly never hurts. I'm also not sure when master was last tested on a real tailsitter.

**Comment by sfuhrer** [comment]
@dagar I had hoped to make a flight with this PR today/this week, but weather didn't permit it. I leave it up to you whether you want to wait till next week, ping the testing team for it or merge it:)
And no clue about tailsitters, haven't flown one since a couple of months. Is it getting tested for 1.10?

**Comment by dagar** [comment]
> And no clue about tailsitters, haven't flown one since a couple of months. Is it getting tested for 1.10?

The test team doesn't have one, so not really out of SITL (which we can't currently put much weight on).  @RomanBapst mentioned tiltrotor transitions in master are rough, so we might need to take a look across the board and do a better job locking it down to prevent regressions.

**Comment by xdwgood** [comment]
@dagar   We have two-motor tailsitter vtol and our team is willing to provide testing (our tailsitter is currently in the manual flight phase)

**Comment by igalloway** [comment]
@dagar FYI - I EXPECT I will test the low cost NXP-FLITETEST VTOL
tailsitter in about two weeks. They're in transit from our development
build and we're tied up with an event next week.
(You can see a glimpse of it here - https://youtu.be/EndVnYr06KA

**Pull request merged**
