### PR TITLE
Tunes library

### PR DESCRIPTION
**Pull request by LorenzMeier**
This is a significant cleanup in terms of how we play tunes.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@PX4/testflights Please flight test and listen to the tunes - there should be no difference.

**Comment by santiago3dr** [comment]
ran flash, fight a couple calibrations, and booting without sd card on pixracer (V4)
https://logs.px4.io/plot_app?log=3b70ab97-d593-4adc-83ef-75df5a6a7228

only difference I could find from master is the startup tones
I have disabled the safety switch so on bootup I normally don't get the startup tone but rather the beep from when you activate the safety switch.
On this PR, with the safety switch disabled, I now get the regular startup tones.

**Comment by Avysuarez** [comment]
flight with pixhawk pro (V4pro) only diference is the tone of startup
https://review.px4.io/plot_app?log=1b10dea3-2009-46f2-a517-ac879cd14ddf

flight with pixhawk 1 (V2) only diference is the tone of startup
https://review.px4.io/plot_app?log=69d87bff-398a-4a56-af95-d973baffdee8

**Comment by r0gelion** [comment]
Is the tune at the startup the expected tune?

**Comment by dagar** [comment]
Overall looks quite good, it's just a lot to go through to verify we haven't lost any functionality.

**Comment by simonegu** [comment]
@r0gelion what is the difference? Is the tune different, or the time in which it is played?

**Comment by santiago3dr** [comment]
quick video to show the tones we expect from master and those of this PR:
https://youtu.be/6_QM0Qf3HP0

**Comment by potaito** [comment]
can you hold off with merging? I might have a few fixes for this branch. Mostly about corner cases.

**Comment by simonegu** [comment]
@santiago3dr thanks a lot for the video. So it seems that the tune sequence gets always played. I personally like that but I leave the decision to @LorenzMeier or @dagar.

**Comment by dagar** [comment]
@potaito what issues?

**Comment by dagar** [comment]
Thanks everyone!

**Comment by potaito** [comment]
@dagar you gave me 5 minutes to reply? 🙃 I'm living on a fork and was not sure what issues are caused by the tunes libraries and what are caused by the (possibly wrong) way I am using it. That's why I was not specific. "Corner cases" I mentioned involve this uninitialized guy for example:
https://github.com/PX4/Firmware/blob/47e5382e7efa68bc3f34fd767a1a76193610112c/src/lib/tunes/tunes.h#L100

**Comment by dagar** [comment]
@potaito I didn't see anything critical and wanted to get this in before it needed yet another rebase (one of the reasons this has dragged on for months). Let's open a new issue or PR to keep working on any issues.

**Pull request merged**
