### PR TITLE
ENV variable cleanup

### PR DESCRIPTION
**Pull request by LorenzMeier**
We kept a lot of unneeded ENV variables around:

```
nsh> free
             total       used       free    largest
Mem:        229952     189680      40272      36720
```

with just better management going to:

```
nsh> free
             total       used       free    largest
Mem:        229952     188368      41584      38128
```

### CODE REVIEW

**Comment by LorenzMeier** [comment]
With the last commit arriving at:

```
nsh> free
             total       used       free    largest
Mem:        229952     188032      41920      38480
```

So ~1.8K just be being smarter about ENV vars.

**Comment by LorenzMeier** [comment]
Now at full 2K freed:
```
nsh> free
             total       used       free    largest
Mem:        229952     187744      42208      38864
```

**Comment by LorenzMeier** [comment]
@bansiesta @thomasgubler Could you review this? It frees 2K RAM (which allows 3 MAVLink links + UAVCAN, which eats 42K alone). But I don't want to accidentally break something.

**Comment by thomasgubler** [comment]
The changes seem sensible overall. I assume you bench-tested this :)

I dislike that $TUNE_ERR was now replaced by a hard-coded value (maintainability).

**Comment by LorenzMeier** [comment]
Replaced this with 0cab404 on master.

**Pull request closed without merging**
