### PR TITLE
ask for climbout mode when doin takeoff help

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by tumbili** [comment]
@LorenzMeier These are the changes I did to the takeoff help. I explicitly ask for climbout and I set the altitude to 50m above ground.

**Comment by tumbili** [comment]
@LorenzMeier The last commit makes sure tecs is not run when on the ground. I can test this tomorrow in the morning if the weather allows. Otherwise the day after will be nice weather for sure.

**Comment by tumbili** [comment]
@LorenzMeier Also do you think I should set the min pitch value to 0 when in climbout mode?

**Comment by LorenzMeier** [comment]
I think so. I don't think it will be needed, but its a good safety.

**Comment by tumbili** [comment]
@LorenzMeier I looks good in HIL now. I limit pitch to 10 degrees in takeoff situations.
Also I limit roll to 15 degrees in takeoff situations for LOITER and POSCTRL.

**Comment by tumbili** [comment]
@LorenzMeier This is tested and @sjwilks will share the logs soon.

**Comment by tumbili** [comment]
@LorenzMeier This is good to go.

**Pull request merged**
