### PR TITLE
3-axis mag calibration

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
@LorenzMeier Could you give this a try and see if you get good calibration values from it. This is a work in progress for the new 3-axis mag calibration routine.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Hoping you can figure it out just from the calibration messages. Just need to test from:
commander calibrate mag
No need for QGC since it just does log based mag cal at this point anyway.

**Comment by LorenzMeier** [comment]
will do!

**Comment by DonLakeFlyer** [comment]
I've tried this on my Iris+ using master with and without these changes to compare cal values. They ended up being +/- .01 away from each other on the X/Y/Z values. So I think that means that it is pretty much generating the same calibration values from just doing 3 axes.

**Comment by LorenzMeier** [comment]
That sounds pretty solid. I have been trapped in various planes for the last day and didn't want to pull out blinking wires from my bag, so I need to test tomorrow :)

**Comment by LorenzMeier** [comment]
I tried it, but I have to admit that I found it relatively confusing how to hold things. Maybe we should schedule a call to discuss the pros and cons and see if we can simplify it?

One of the main sources of confusion is if you have it in one orientation, what is the axis you should be turning around? The one that is pointing up?

**Comment by DonLakeFlyer** [comment]
> One of the main sources of confusion is if you have it in one orientation, what is the axis you should be turning around? The one that is pointing up?

Yes. There needs to be some way to word that. With visuals in QGC this will be much easier. Take the global reference plane of the floor. The rotation axis is straight down through the vehicle looking towards the floor. This straight up/down axis is the same rotation for all orientations.

In reality the axis you rotate around doesn't matter as long as it is the same in global reference plane for all orientations. Each of the 3 orientations forms a set of 2d points on a circle (really 3d with jitter). You then put the 3 circles together and you get a 3d circle to calculate from.

**Comment by DonLakeFlyer** [comment]
Using this video as reference: https://www.youtube.com/watch?v=OxMjTjywbYc&t=111. The first rotation would be the right-side up rotation, the second rotation would be the left side (I think it's left, could be right, but it doesn't really matter) rotation I believe. Then you need to add a third rotation for nose-down and do it the same way.

**Comment by DonLakeFlyer** [comment]
The other issue is that the up/down, front/back orientation names don't really make much sense to me. If I remember correctly back is actually right side up. But I can't change them since QGC is coded to those names. To me these make more sense: right-side up, upside down, nose down, tail down, left/right.

**Comment by DonLakeFlyer** [comment]
Latest update:
- Orientation detection mechanism is now a worker routine which is used by both mag and accel cal. This worker routine will time out if it fails to detect the next orientation after 10 tries. Which will in turn fail the cal.
- Mag cal: Allows you to pick any side as a starting point. When that side is complete, it will also marks the opposite side as complete. This makes it a bit easier to get things done.
- Progress indicators: Better but still not finished.
- Lots of tweaks here and there.

Pull still not ready for true commit, but the functionality should all be there now.

**Comment by DonLakeFlyer** [comment]
Last push is now final bits for testing. If testing is good I'll close this pull and fix up the commits. Also waiting on answer to one last question on whether we can calibrate all mags at one time.

**Comment by DonLakeFlyer** [comment]
I'm going to close this to put through the real pull.

**Pull request closed without merging**
