### PR TITLE
Make PWM_RATE configurable via QGroundControl

### PR DESCRIPTION
**Pull request by anton-matosov**

### CODE REVIEW

**Comment by anton-matosov** [comment]
Can someone take a look at this PR?

**Comment by dagar** [comment]
What about pulling these params into the PWM module as the default value if not set on the command line?

**Comment by anton-matosov** [comment]
I can add this as well. will do in couple of days

**Comment by dagar** [comment]
Just a thought that it seems much cleaner to pull all relevant params into the modules and avoid the sensors param_find hack and init script complexity. For the time being this change looks good me.

**Pull request merged**
