### PR TITLE
fix bug in the logging app:

### PR DESCRIPTION
**Pull request by tumbili**
- either sensor combined or the replay topic where copied into
the union buffer but at times the memory was overwritten by other
topics which updated below
- this change makes sure that the two topics are copied into the union
buffer at the correct location in the code

### CODE REVIEW

**Comment by tumbili** [comment]
@priseborough Could you give this a try with replay? I already tested it in SITL and it works fine. I was able to reproduce the false logging in SITL so I'm confident that it works.

**Comment by tumbili** [comment]
@devbharat Sorry for the delay, I thought I'd find a gap in the afternoon but we busy testing RTK.

**Comment by priseborough** [comment]
It works

**Comment by tumbili** [comment]
Merged!

**Pull request merged**
