### PR TITLE
Firmware is not able to compile due to conflicting optimization flags

### PR DESCRIPTION
**Pull request by akatrevorjay**
**Describe problem solved by the proposed pull request**

Firmware is not able to compile without this change with recent gcc.
The flags are redundant at least with gcc, so I just removed them.
If there's a better way of handling this let me know.

Eg:

```
msg/topics_sources/uORBTopics.cpp:1:0: error: switch -mcpu=cortex-m7 conflicts with -march=armv7e-m switch [-Werror]
 /****************************************************************************

compilation terminated due to -Wfatal-errors.
```

**Describe your preferred solution**

Removed conflicting optimization flags (they're redundant anyway).

**Describe possible alternatives**

alternative 1: ignore the issue
    side effects: project will not be compilable using recent gccs.

alternative 2: silence the warning
    side effects: gross

**Additional context**
Add any other context or screenshots for the feature request here.

### CODE REVIEW

**Comment by dagar** [comment]
@akatrevorjay I believe you only actually need `-march=armv7e-m` and -mcpu could be dropped.

Do you want to give it a try? Make sure the generated binary is identical.

**Comment by dagar** [comment]
Sorry I'm dense and didn't notice this was a PR instead of an issue.

**Comment by dagar** [comment]
I compared the binaries before and after across px4fmu-v2, io-v2, fmu-v5, etc. No change.

**Comment by akatrevorjay** [comment]
Thanks!

**Pull request merged**
