### PR TITLE
mc_pos_control: velocity control with pos. hold

### PR DESCRIPTION
**Pull request by v01d**
This PR is the follow up of @tumbili 's work in #2305 

# Overview

Following original idea, manual control in POSCTL directly commands velocity (sets velocity setpoint). To aid manual control, whenever user centers sticks, XY and/or Z positions are held (position hold to that position is enabled).

# Summary of features

* Original work by @tumbili targeted only modified behavior for manual mode. This PR implements actual velocity setpoints (instead of move rate of position setpoint, as it is now) for offboard mode, when a velocity setpoint is received. Positions setpoints are still handled as before
* Position hold when centering sticks is only an aid during manual control. Velocity setpoints received in offboard mode do not have this behavior. User could mimic this on offboard side by switching to sending position setpoints if desired.
* Four parameters are introduced: the deadzone (in % of stick throw) for XY and Z sticks are considered centered (which is required for pos. hold to enable) and maximum XY and Z velocities that are allowed when switching to pos. hold.
* Deadzones can be set to 0 to completely disable position hold feature (pure velocity commands). Max velocities can also be set to 0 to not require this condition and always activate pos. hold when sticks are centered.
* Separate deadzones for XY and Z allow setting XY_DZ=0 and Z_DZ!=0, thus hold altitude while using velocity control for XY (the reverse might not be that useful).

# Implementation aspects

* @tumbili initial implementation had all code running on main task, dependent on manual mode enabled. I've thus moved most of pos. hold handling to control_manual() function to keep things clean.
* the P controller for position/altitude runs on main_task (as before) by default, but control_* functions can choose to not run it (when it is then assumed that these functions directly set velocity setpoint)
* sp_move_rate variable was removed (actually renamed). The input from sticks is termed "requested velocity setpoint" and is only local to control_manual() function
* in pos hold mode for either XY or Z, the position setpoint is set, and the velicity setpoint is computed (P control) computed. Otherwise, the velocity setpoint is updated from stick inputs.
* Offboard mode was modified to directly set the velocity setpoint instead of playing with the sp_move_rate
* As in #2886 , the handling of velocity setpoint resetting was corrected to only be performed when the corresponding velocity control is disabled. Similarly the resetting of the alt/position setpoints is only performed when the corresponding position/alt control modes are disabled. This allows offboard to work as expected.
* vel_ff is unused at the moment since now I believe there's no place for it. But I may be wrong.

# Possible improvements

1. Initially I wanted to implement (as suggested in a TODO comment) separate X,Y hold. This is non trivial since PID controllers work in NED frame. Thus, even while moving "forward" this translates to both _vel_sp(0) and _vel_sp(1) values, depending on yaw direction. I guess it could be done, by updating the axis to be held based on current yaw, but to me it doesn't warrant such work. If the user is commanding the copter in XY, it is better to let him feel in control of all axis.
2. The current code base would also allow for offboard mode to follow horizontal velocity setpoints while maintaining altitude. To achieve this, in commander.cpp, a simple modification could be done to allow these combinations. I'm interested in this position. Let me know if you are also and I can try it and make a PR.

# Testing status

I've tested this under SITL, both in manual and offboard modes. I have trouble getting good PID values for jmavsim, but the response is as expected. I will port this now to stable on my fork, to be able to use it on my quad. However, testing on master would also be nice if someone wants to do it.

UPDATE: I have ported this to stable branch and tested in manual mode. I have it set to maintain vertical position and follow horizontal velocity. This greatly helps in tuning the vel. PIDs. I will test offboard mode on the real quad soon.

### CODE REVIEW

**Comment by v01d** [comment]
@LorenzMeier would you have some feedback on this?
I'm currently considering also implementing improvement number 2 listed above. I have some ideas on how to achieve it. But I'm not sure to proceed if the approach in this PR sounds reasonable or not.

**Comment by LorenzMeier** [comment]
Odd - I though I had commented on this already.

**Comment by LorenzMeier** [comment]
It looks really good. Its merely about the flight testing, but in general this is going into the right direction.

Did you happen to improve the altitude hold performance already by re-tuning INAV? That is still on our list, along with checking wether we should switch to James Goppert's Kalman filter for local position estimation.

**Comment by v01d** [comment]
Great!

Well, as I mentioned, the manual part I'm already using for several flights
on my real quad, with code ported to stable branch. I would need to also
test offboard mode, which I will do next week. Maybe others can test it off
master under varying conditions.

Regarding INAV, I have modified it to use mostly sonar instead of baro when
in PX4FLOW's sonar range. I removed surface detection since the framework
is not robust enough to distinguish surface changes from sonar errors.
Moreover, sonar now corrects baro offset (instead of the other way around)
for when going above sonar range (or when momentarily loosing sonar for
more than a few seconds).
You can look at the code in my fork, where I made a PR to myself, to review
the code and test it with the help of another user:
https://github.com/v01d/Firmware/pull/2

I have not made a pull request on this since I wasn't sure if this
implementation would go in the intended direction for INAV. Moreover, I got
the idea the new Kalman would supercede it. In any case, I just did this
since I'm in a hurry to have good Z control using sonar, but if the new
Kalman estimator eventually hits stable I would definitely switch to that
since I'm sure it would be considerably more robust.

**Comment by v01d** [comment]
By the way, contrary to my previous statements above, I decided to add something similar to offboard mode. This is really useful to, for example, maintain altitude and only control X,Y velocity. The idea is that two parameters are included, which set a threshold for the received velocity setpoint (in XY and Z). If either velocity is below the threshold, pos. hold is activated. Setting these to zero (the suggested defaults) results in no pos. hold and pure velocity control.

I have this feature on a separate branch. If you like the idea, I can include it in this PR.
You can see the changes (w.r.t. this PR) here: https://github.com/v01d/Firmware/compare/velocity_control...v01d:velocity_control_offboard_hold

**Comment by LorenzMeier** [comment]
@tumbili Could you please review, test in SITL and provide feedback?

**Comment by tumbili** [comment]
@v01d @LorenzMeier I rebased this on master and tested it in SITL. Seems to work as expected.
The only thing I noticed is that the position setpoint only jumps to the new setpoint once the sticks are centered and the velocity has been reduced. Maybe we could always set position setpoint to the actual position during velocity control mode. This would maybe make it more clear in the logs that we are controlling position.

**Comment by LorenzMeier** [comment]
Makes sense - could you apply that change?

**Comment by tumbili** [comment]
Closing in favour of #3004

**Pull request closed without merging**
