### PR TITLE
WIP: Rate mode implemented with full attitude control

### PR DESCRIPTION
**Pull request by kd0aij**
move "acro" mode handling to mc_pos_control to validate attitude estimation and control

must change the computation of attitude setpoint to operate on quaternion or rotation matrix instead of Euler angles
Bench testing indicates that the MC attitude controller responds correctly for all roll/pitch orientation setpoints, but it seems the mixer doesn't work properly for inverted poses.

### CODE REVIEW

**Comment by kd0aij** [comment]
Also flies well in Acro mode with ATT_BIAS_MAX at default value:
http://logs.uaventure.com/view/WjV4mqDRdwwNydtdBXbS75#Filter_Watchdog_PLOT

Would have to modify the flight mode logic to allow rate mode control + ALTCTL

**Comment by kd0aij** [comment]
pitchint_attbias

**Comment by einma1** [comment]
Hello, interesting concept... feeding the attitude controller with integrated stick inputs...
With this there will be no more gyro drift in acro mode.
PIDs for acro and attitude mode could be equal, isn't it?
How is the racing-feeling at the rc-stick compared to gyro-only?

**Comment by kd0aij** [comment]
The stick feel is the same as gyros-only Acro mode. Not messing with the yaw axis yet.

**Comment by jgoppert** [comment]
Do you have a plot of the pitch rate integrator with the old setup. I was expecting to see more discrete jumps at low frequency caused by external corrections, but I don't see that. It looks more like a term proportional to pitch rate, maybe due to inertia or drag.

**Comment by kd0aij** [comment]
No, I can't find a gyros-only log with high I gains and ATT_BIAS_MAX nonzero. And there's essentially no short-term integrator variation with the lower gains.

**Comment by LorenzMeier** [comment]
What is the relationship to #3833?

**Comment by kd0aij** [comment]
This is for multirotors using the standard mixer, #3833 will support 3D capable variable-pitch multis, but will need a new mixer which handles negative thrust properly.

**Comment by LorenzMeier** [comment]
I'm closing this due to the state estimation related issues that result from flying attitude without GPS on a racer.

**Pull request closed without merging**
