### PR TITLE
drivers: I2CSPIDriver add a number of missing addresses

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by SalimTerryLi** [comment]
How about make [constructor](https://github.com/PX4/Firmware/blob/9ae2f0ea969a4808fc5d2e554b812e353e8dde8d/platforms/common/include/px4_platform_common/i2c_spi_buses.h#L233)  request for address as well, instead of an optional parameter?

**Comment by dagar** [comment]
This was just a quick attempt to silence distracting console output before the next release. 

``` Console
[2020-04-16T10:00:16.987Z] ERROR [SPI_I2C] Bug: driver rgbled does not pass the I2C address to I2CSPIDriverBase
[2020-04-16T10:00:16.987Z] rgbled #0 on I2C bus 2 (external)
```

**Comment by bkueng** [comment]
> This was just a quick attempt to silence distracting console output before the next release.

That is indeed wrong then. I was looking at LidarLiteI2C.
Going through them, only blinkm, rgbled_ncp5623c and rgbled need to be fixed.

**Comment by dagar** [comment]
Updated to only blinkm, rgbled_ncp5623c and rgbled.

**Comment by dagar** [comment]
Sweet silence (or at least slightly improved).

Screenshot from 2020-04-17 11-52-24

**Pull request merged**
