### PR TITLE
Jenkins add ShellCheck

### PR DESCRIPTION
**Pull request by dagar**
Waiting on docker hub builds.

### CODE REVIEW

**Comment by dagar** [comment]
Need to either tweak for ShellCheck in Ubuntu 16.04 or update what's in the docker container.

**Comment by bkueng** [comment]
I'd rather use an up-to-date ShellCheck version. Ubuntu packages generally lag too much behind.

**Comment by dagar** [comment]
Trying again with Ubuntu 18.04.

**Comment by dagar** [comment]
@bkueng working now.

**Pull request merged**
