### PR TITLE
Test NuttX upgrade with CI

### PR DESCRIPTION
**Pull request by LorenzMeier**
@davids5 This is now the monster diff. We can check this now out and create separate commits for each sub-aspect.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@dagar I've set the CCACHE off environment variable in Semaphore. Let's see if this does anything.

**Comment by LorenzMeier** [comment]
@dagar Still need to disable CCACHE in Semaphore. I really don't think we want any caching.

**Comment by LorenzMeier** [comment]
@davids5 We will need to re-balance CI runs so that we can finish in under 10 minutes. That should be feasible by more parallel machines.

**Comment by LorenzMeier** [comment]
The last change set deletes each build folder and just retains the .px4 files from it. Will likely need more tuning.

**Comment by LorenzMeier** [comment]
@dagar Pushing more commits to distribute the workloads better would be most appreciated.

**Comment by LorenzMeier** [comment]
@dagar As expected Semaphore is now the slowest.

**Comment by LorenzMeier** [comment]
@dagar An obvious optimisation would be to generate the parameters.xml and airframes.xml only once for all targets.

**Comment by LorenzMeier** [comment]
25 mins and counting.

**Comment by LorenzMeier** [comment]
@davids5 I only silenced spurious error messages. The size output is still there.

@dagar @davids5 I squashed my WIP commits. Now the CI changes are clean and we just need to break down the original diff as needed. I also removed the global switch of CCACHE (relying on the Semaphore-only switch now).

**Comment by dagar** [comment]
Let me see if there's anything we can do right now to improve the build. We're limited in what we can split because the semaphore change would also immediately apply to master/beta/stable.
I'll try generating parameter/airframe only once, but I believe it's only a few seconds per build.

**Comment by davids5** [comment]
@LorenzMeier - Do you see the 'size' it in the output?

**Comment by dagar** [comment]
After the nuttx upgrade which builds do we want to upload to s3?

**Comment by LorenzMeier** [comment]
Master, beta and stable, nothing else.

**Comment by dagar** [comment]
Sorry should have said configs.
https://github.com/PX4/Firmware/blob/nuttx_upgrade/Makefile#L224

    aerofc-v1_default
    auav-x21_default
    crazyflie_default
    esc35-v1_bootloader
    mindpx-v2_default
    posix_sitl_default
    px4-stm32f4discovery_default
    px4cannode-v1_bootloader
    px4cannode-v1_default
    px4esc-v1_bootloader
    px4esc-v1_default
    px4flow-v2_bootloader
    px4fmu-v1_default
    px4fmu-v2_default
    px4fmu-v2_test
    px4fmu-v3_default
    px4fmu-v4_default
    px4fmu-v4_default_and_uavcan
    px4fmu-v4pro_default
    px4fmu-v5_default
    px4nucleoF767ZI-v1_default
    s2740vc-v1_bootloader
    s2740vc-v1_default
    tap-v1_default
    zubaxgnss-v1_bootloader

**Comment by LorenzMeier** [comment]
Everything that is not a boot loader.

**Comment by davids5** [comment]
@dagar 

```
aerofc-v1_default
auav-x21_default
crazyflie_default
mindpx-v2_default
posix_sitl_default
px4-stm32f4discovery_default
px4fmu-v1_default
px4fmu-v2_default
px4fmu-v2_test
px4fmu-v3_default
px4fmu-v4_default_and_uavcan
px4fmu-v4pro_default
px4fmu-v5_default
px4nucleoF767ZI-v1_default
tap-v1_default
```
I think the others are not complete enough or used.

**Comment by dagar** [comment]
At this point I think we're going to need to evenly distribute builds across semaphore, travis, circleci and put using multiple compilers on hold.
Sharing parameters only saves a few seconds per build, airframes even less.

Let's try and group things logically so all the builds that need to be uploaded to s3 run in the same place.

**Pull request closed without merging**
