### PR TITLE
Atl flight excelsior legacy support

### PR DESCRIPTION
**Pull request by LorenzMeier**
@wangxdflight I rebased and continued https://github.com/PX4/Firmware/pull/6326 here.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@wangxdflight @dagar We are failing now here:

```
-- CMAKE_MODULE_PATH: /home/runner/Firmware/cmake
CMake Error at cmake/cmake_hexagon/toolchain/Toolchain-arm-oemllib32-linux-gnueabi.cmake:81 (message):
  could not find arm-oemllib32-linux-gnueabi-gcc compiler
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt:249 (project)


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
```

**Comment by LorenzMeier** [comment]
@ChristophTobler @Stifael Any idea where that toolchain is located? Do you have `arm-oemllib32-linux-gnueabi-gcc` on your system? If yes, we need to update our CI image.

**Comment by LorenzMeier** [comment]
@wangxdflight @mcharleb Let us know if you have any pointers. We need that toolchain to fix CI and I'm hesitant committing a target without full support.

**Comment by dagar** [comment]
I just added excelsior_default. Should I remove it?
It's passing in master.

**Comment by LorenzMeier** [comment]
@dagar Better remove it - its passing on master because its using an older toolchain. Excelsior is a new board for which we do not have hardware yet.

**Comment by dagar** [comment]
Gone, and build restarted.

**Comment by ChristophTobler** [comment]
@LorenzMeier We don't have the ```arm-oemllib32-linux-gnueabi-gcc``` compiler

**Comment by wangxdflight** [comment]
Has the shmem issue been verified as fixed with this change? Thanks.

**Comment by wangxdflight** [comment]
Got it. Glad that it is verified. Thanks.

**Comment by wangxdflight** [comment]
As for the tool-chain, we will try to make use of the existing released tool-chain for excelsior. The work is still going on.

**Pull request merged**
