### PR TITLE
git submodules sanity and minor Makefile cleanup

### PR DESCRIPTION
**Pull request by dagar**
More fun with our favorite subject git submodules. This PR fixes a bunch of little problems I've encountered as I frequently jump between master, stable, and even older. In particular submodules within submodules appearing and disappearing between checkouts is especially fun.

Summary
 - `make submodulesclean`  - the nuclear option for forcing them to reset and cleanup.
 - `make distclean` - restore everything to the state of a fresh clone
 - restored default eclipse project files - it's not clear why these were causing problems. If it's still a problem can you please provide details so I could fix it?
 - run unit tests with `make tests` and ignore generated files
 - moved travis-ci vectorcontrol build commands into `make uavcan_firmware`
 - added `make check` which builds all nuttx configs, runs the tests (which builds posix_sitl_default), and checks formatting. I'd eventually like to turn this into the thing you can run locally to replicate exactly what travis-ci does.
 - added `make package_firmware` to zip all the .px4 binaries into Firmware.zip

### CODE REVIEW

**Comment by dagar** [comment]
Fixed mixer_test and made the output a little easier to see.

**Comment by LorenzMeier** [comment]
It looks except for the Eclipse project files. If we want to upgrade the default template it will create a conflict with the local files that Eclipse users have because they will have local changes.

**Comment by dagar** [comment]
@LorenzMeier - I updated the eclipse project templates to stay as template_ so they won't conflict with local .project and .cproject

**Comment by LorenzMeier** [comment]
Rebased and applied, thanks!

**Pull request closed without merging**
