### PR TITLE
SITL_configs: by default, disable datalink and RC failsafes 

### PR DESCRIPTION
**Pull request by TSC21**
The purpose is to avoid SITL to get into RTL after takeoff and if not using QGC or RC.

### CODE REVIEW

**Comment by dagar** [comment]
I'm wondering if we should leave RC loss on. Then if you're using manual control in a manual mode and lose it you'll get the expected response.

**Comment by dagar** [comment]
Wait, are you talking about TAKEOFF the mode? Did the auto transition to HOLD mode after successful takeoff change this for you?

**Comment by TSC21** [comment]
@dagar this happens when, after taking off (TAKEOFF mode), when getting to the minimum takeoff altitude, instead of changing to HOLD, it changes to RTL because of datalink or RC failsafe. Strange is that it actually lets me takeoff even if the failsafes are on

**Comment by LorenzMeier** [comment]
I don't understand the rationale for the change yet.

**Comment by TSC21** [comment]
The idea is allow me to use SITL without depending on: 1. Having a datalink; 2. Having an RC connection. What I am seeing is that it let's me takeoff (without QGC or RC), but when it gets to the takeoff altitude, it imediatly goes RTL. I don't know if this is actually supposed to happen or if it is some logic gap.

**Comment by TSC21** [comment]
I am just opening this cause before I was actually able to use SITL without having QGC on. I don't know what changed on the logic, but I don't know why I would actually want to have a datalink everytime I pilot my vehicle (RC I understand but without QGC, I don't have a way of plugging RC without QGC or 3rd party as ROS).

**Comment by lamping7** [comment]
@TSC21 asked me to verify the behavior he was seeing on my system. It looks like the automatic transition introduced with https://github.com/PX4/Firmware/pull/8020 is the source of this. The commander_state message isn't being logged, but it can seen that this is what is going on.

Commander's main state changes here after takeoff -- https://github.com/PX4/Firmware/blob/0fd043af017e4e2a01f80d8fe392672f4abe1405/src/modules/commander/commander.cpp#L2890

Which then leads to this --
https://github.com/PX4/Firmware/blob/45fd908784bfc4e0a788c7b5418df8d04a5b5a56/src/modules/commander/state_machine_helper.cpp#L766

Triggering the failsafe.

To reproduce:
* run `make posix_sitl_default gazebo_iris`
* after the simulation is up, issue takeoff in the shell `commander takeoff`

Output:
```
pxh> commander takeoff
pxh> INFO  [tone_alarm] positive
INFO  [tone_alarm] arming
INFO  [commander] Takeoff detected
WARN  [commander_tests] Failsafe enabled: no datalink
INFO  [navigator] RTL: climb to 494 m (5 m above home)
INFO  [navigator] RTL: return at 494 m (5 m above home)
INFO  [navigator] RTL: descend to 494 m (5 m above home)
INFO  [navigator] RTL: loiter 5.0s
WARN  [navigator] RTL: land at home
INFO  [commander] Landing detected
INFO  [tone_alarm] neutral
INFO  [logger] closed logfile, bytes written: 3453061
```

Plot:
takeoff-wo-datalink

**Comment by TSC21** [comment]
@lamping7 thanks for confirming this. I actually think that if we are to apply the failsafe, that should be also on the TAKEOFF mode, so it refuses to takeoff given there is no datalink/RC/other. Given the situation, I think the logic is not correct, and should be consider when trying to change to TAKEOFF mode.
The other thing is: why do we need datalink in LOITER mode? And why would I want this to be set by default for SITL, when I can play with the simulation without a ground station?
@dagar, @LorenzMeier can you please give your opinion on this? Should this be pushed and continue on another issue?

**Comment by bkueng** [comment]
I agree, there are 2 issues here:
- failsafe is only triggered after takeoff is completed and switching to hold.
- I think SITL should be usable without RC or QGC opened. That is helpful for quick testing, and minimizes runtime dependencies.

**Comment by TSC21** [comment]
Anyone wants to propose a better solution for this? Besides, based on what @bkueng said and @lamping7 confirmed, we need to recheck the logic for the failsafe triggering on `LAND` mode also.

**Comment by lamping7** [comment]
I agree with the PR. If the concern is to test failsafes in CI's ROS SITL tests, these params can be set via MAVROS during the setup of the test.

**Comment by TSC21** [comment]
@lamping7 good point. Can you add th respective param set on the scripts?

**Comment by lamping7** [comment]
> Can you add th respective param set on the scripts?
Yeah. That's no problem. I imagine that is something that would get implemented anyway from https://github.com/PX4/Firmware/issues/8619

Changing params is an easy way to simulate failures and check how robust the system is. The only thing I'm not sure of at the moment is when certain modules are responsive to parameter changes (i.e when the FW reads different params -- before arming, during flight, etc.).

**Comment by TSC21** [comment]
@dagar @LorenzMeier @bkueng @lamping7 is there something more to add to this?

**Comment by dagar** [comment]
My preference would be the default simulation mirroring real world setup and usage as closely as possible. 

How are you normally using this? Could you have a particular launch file that disables these parameters at start?

**Comment by TSC21** [comment]
I don't want to depend on lauch files for this. As @bkueng says, you usually want to fast debug stuff using (pure) SITL with Gazebo (no ROS), no QGC either, and the fact that these two failsafes are set by default doesn't allow it. The thing as ai said and confirmed by @lamping7 is that even the failsafe logic for the LAND mode is not right, and the datalink failsafe only triggers when it changes to HOLD.

**Comment by TSC21** [comment]
> . Why are you allowed to arm in the first place without valid RC or datalink if the failsafes are enabled? Why are failsafes ignored during takeoff? Imagine a user accidentally entering a bogus takeoff altitude and then losing the link. These are real things that happen.

Those are all questions I made above and we should probably answer them.

And that mechanism is actually what I am asking about currently. What do you suggest besides using launch files?

**Comment by TSC21** [comment]
For example, how do you currently test things in SITL? With QGC up and virtual joystick activated?

**Comment by dagar** [comment]
> Those are all questions I made above and we should probably answer them.

Good, let's fix them before the workaround though.

> And that mechanism is actually what I am asking about currently. What do you suggest besides using launch files?

Slightly different solutions for different use cases. I was trying to suggest something that covered your primary use case.

> For example, how do you currently test things in SITL? With QGC up and virtual joystick activated?

Sometimes, but not always. It completely depends what you're trying to test. There's not a whole lot you can do without connecting something through (QGC, MAVROS, Dronecore).

**Pull request closed without merging**
