### PR TITLE
Added terrain estimator to INAV

### PR DESCRIPTION
**Pull request by AndreasAntener**
@tumbili @LorenzMeier I added the terrain estimator to INAV. I had to change inav to c++ which was (too) easy. So I would appreciate an experts opinion on that ;)

I just tested it outdoors quickly together with #3234 and it works. But a flight test would be good. I can also make a new PR including #3234 , would be easier to test because it includes the altitude message.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looking good at first glance. Do you have a log file with the terrain estimate you got?

**Comment by AndreasAntener** [comment]
Unfortunately I was running around unarmed.

**Comment by LorenzMeier** [comment]
I think having that would be good, because we're sure that things work like they should.

**Comment by AndreasAntener** [comment]
Here it is: http://logs.uaventure.com/view/aensR2aR8aGAUUskhXFe5W

**Comment by LorenzMeier** [comment]
If you rebase on master Travis should pass.

**Comment by AndreasAntener** [comment]
I rebased, but there still seems to be an error, which could be related to my change:
```
../src/modules/position_estimator_inav/position_estimator_inav_main.cpp: In function ‘int position_estimator_inav_thread_main(int, char**)’:

../src/modules/position_estimator_inav/position_estimator_inav_main.cpp:1051:18: error: ‘isfinite’ was not declared in this scope

    if (isfinite(c)) {

                  ^

compilation terminated due to -Wfatal-errors.

[252/256] Building CXX object src/modu...__commander.dir/gyro_calibration.cpp.o

ninja: build stopped: subcommand failed.

make: *** [posix_sitl_simple] Error 1
```

However if I run `make posix_sitl_simple` locally it fails much earlier:
```
/Users/ada/UAV/src/Firmware_cmake/src/drivers/device/vdev_posix.cpp: In function 'int px4_open(const char*, int, ...)':
/Users/ada/UAV/src/Firmware_cmake/src/drivers/device/vdev_posix.cpp:109:21: error: 'mode_t {aka short unsigned int}' is promoted to 'int' when passed through '...' [-Werror]
    mode = va_arg(p, mode_t);
                     ^
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[3]: *** [src/drivers/device/CMakeFiles/drivers__device.dir/vdev_posix.cpp.o] Error 1
make[2]: *** [src/drivers/device/CMakeFiles/drivers__device.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by AndreasAntener** [comment]
I guess the isfinite call can be replaces by PX4_ISFINITE

**Comment by LorenzMeier** [comment]
Yes, and it has to.

**Comment by AndreasAntener** [comment]
When I'm at it already, any others? warnx?

**Comment by LorenzMeier** [comment]
I would keep changes minimal. Refactoring can be done later. We have optical flow work on this so I don't want to blow up the diff unnecessarily.

**Comment by AndreasAntener** [comment]
Ok, I pushed this, let's see what travis says, I will also make a quick new test.

**Comment by AndreasAntener** [comment]
New log: http://logs.uaventure.com/view/QdYTDAijvVzF3zaoFyVP29 and travis is happy

**Comment by LorenzMeier** [comment]
Nice!

**Pull request merged**
