### PR TITLE
Tko ramp: fix takeoff issue with large tko ramp time

### PR DESCRIPTION
**Pull request by bresch**
fixes https://github.com/PX4/Firmware/issues/15408

Because the velocity starts with a positive value (down) to ramp-up slowly the motors, the position setpoint (integral) was going down into the ground, canceling the input of the velocity controller during the early takeoff phase.
Instead of a smooth ramp, the behavior was a delay followed by a quick takeoff or a land detection.
Setting the current altitude setpoint with the current altitude during this phase avoids the canceling effect and creates a takeoff purely velocity-based.

SITL (jMavSim) results:
`MPC_TKO_RAMP_T = 5s` for both tests.

Before, the trajectory_setpoint.z was going down during the early takeoff phase, delaying the thrust ramp:
Screen Capture_select-area_20200807140839

Now, the thrust ramps properly since the beginning of the velocity ramp:
Screen Capture_select-area_20200807140857

@ThomasRigi Could you please test this?
@julianoes This was also probably a reason why we sometimes had a land detection during takeoff

### CODE REVIEW

**Comment by jkflying** [comment]
Not broken by this PR, but I'd just like to point out we have a big-ish spike in acceleration between the 1.5m/s and 3m/s climb speeds. We should probably lower the limit there in auto mode, since this high acceleration in Z isn't used in any other context I can think of, and Z accelerations can be scary from a prop noise and power consumption perspective.

**Comment by bresch** [comment]
@jkflying Well, it's a ramp, not a spike! :D But we can reduce the default jerk, yes.

**Comment by ThomasRigi** [comment]
Thanks @bresch for fixing the ramp!

I just tested with `HEADLESS=1 make px4_sitl gazebo_standard_vtol` and the ramp works : https://logs.px4.io/plot_app?log=9e20a1fb-ce21-423b-8a82-a8994cb4f130

There are large oscillations, but I don't think your PR is to blame for this. The Z velocity setpoint is good in any case.

Good to go in I'd say. :)

**Comment by bresch** [comment]
Thanks for the test @ThomasRigi . I still need to investigate if the CI SITL failure is real.

**Comment by bresch** [comment]
CI failures were due to older VTOL STIL issues (underpowered); rebasing solved the issue.

**Pull request merged**
