### PR TITLE
Enable GPS flight without magnetometer

### PR DESCRIPTION
**Pull request by kamilritz**
This PR brings interface updates in ECL to the Firmware. 
See ECL PR for more information:
- https://github.com/PX4/ecl/pull/770
- https://github.com/PX4/ecl/pull/755

Complete diff: https://github.com/PX4/ecl/compare/870ec380f13707cde0e6adda5bf52838aa602ebd...2fa43419d2bd7319024682b311f52c78f9a86f52

### CODE REVIEW

**Comment by bresch** [comment]
@PX4/testflights Could you please carefully test this PR please?
First set [EKF2_MAG_TYPE](https://dev.px4.io/master/en/advanced/parameter_reference.html#EKF2_MAG_TYPE) to `none` (0) and reboot.

The vehicle will need some motion to initialize its heading, so it won't be able to switch to position mode on the ground, do the following:
- move the RC switch to position mode (the vehicle will stay in altitude)
- takeoff and move forward
- after a few meters, the vehicle should have identified its heading and switch to position mode automatically (because the switch is set to position)
- Fly around in position mode, try other modes (e.g.: auto/rtl)

Thanks in advance

**Comment by bresch** [comment]
Sorry @kamilritz , I completely hijacked your branch and PR :D

**Comment by kamilritz** [comment]
@bresch no worries. I am completely happy with this as long as ECL development is not blocked for too long.

**Comment by Junkim3DR** [comment]
### Tested on NXP FMUK66 V3

**Modes Tested**
- Position Mode: Good.
- Altitude Mode: Good.
- Stabilized Mode: Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode.

**Notes**
No issues noted, good flight in general.

**Logs**
- https://review.px4.io/plot_app?log=6e5ec7d0-ca21-4095-b608-5cbb66ae5817
- https://review.px4.io/plot_app?log=7ea98cd3-4e45-45ff-a905-62587d6a8319

**Comment by dannyfpv** [comment]
pixhawk4 v5 f-450

Modes Tested

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.

- Procedure
Arm and Take off in stabilized mode, after flying for approximately one minute, switched to position then stabilized mode 

Notes:
No issues noted, good flight in general.

Logs:
https://review.px4.io/plot_app?log=43659326-5a6d-45ca-8dff-f73b1951c31c
https://review.px4.io/plot_app?log=f88356a1-42b2-4d6d-8dad-0bc5749f9103

**Comment by jorge789** [comment]
### Tested on PixRacer V4

**It was flown according to the instructions.**

**Modes Tested**
Altitude mode
Mode Position
Stabilized mode

**EKF2_MAG_TYPE to none (0) and restart.**
**Process**
The vehicle will need some movement to initialize its heading, so you will not be able to switch to ground position mode, do the following:

move RC switch to position mode (vehicle will remain at altitude)
take off and move forward
after a few meters, the vehicle should have identified its course and switched to position mode automatically (because the switch is in position)
Fly around in position, altitude and stabilized mode

**Note:In altitude mode, the vehicle did not respect the height that continued to increase in pitch forward**

**Log:**
https://review.px4.io/plot_app?log=5a2113ed-c073-4c8d-a4b2-ed2d10f5c637

https://review.px4.io/plot_app?log=5109f5a4-e903-4054-ae3f-43eb3dc3a605

**Comment by hamishwillee** [comment]
Is this going into v1.11 ?

**Comment by bresch** [comment]
@hamishwillee Potentially, yes, but there are still some improvements required to be a "supported official mode". I think it could go as a "developer/beta feature"

**Comment by bresch** [comment]
Many thanks @Junkim3DR , @dannyfpv  and @jorge789 for the flight tests, those were really helpful.
In summary, it works, but:
- the auto modes are not available using this in-air yaw alignment because the home position is not set (due to the fact that "Global position" is not valid if the GPS isn't fused and GPS can't be fused without yaw alignement) -> this has to be fixed as we just need to know the lon/lat coordinates to set a home position
- it takes way too long to accept the local position in commander. As seen in the attached graph, the local position is valid already 6s after arming, but Commander only allows to switch into Position mode 72 seconds later! This is most likely due to that probation period (FYI @MaEtUgR ) : https://github.com/PX4/Firmware/blob/1f4b2d1d53c48f8041152dd2c906502062bbad2f/src/modules/commander/Commander.cpp#L3031-L3032
DeepinScreenshot_select-area_20200401111958

@jorge789 The height problems you have in altitude mode are sometimes due to excessive airflow on the baro and sometimes due to accelerometer clipping (FYI @dagar )
Baro:
2020-04-01_11-45-45_01_plot
Accel clipping:
2020-04-01_11-46-32_01_plot

**Comment by bresch** [comment]
Merging not to now block ecl development but there are still some improvement required to make it a complete feature

**Pull request merged**
