### PR TITLE
ekf2: Fix EKF preflight check fail false positives

### PR DESCRIPTION
**Pull request by dagar**
Uses a relaxed yaw innovation check threshold for fixed wing vehicle that can recover from larger yaw errors after takeoff.
Replaces the peak hold with decay filtering applied to the magnetic yaw innovations with a conventional lowpass filter. This prevents mag heading innovation transients caused by preflight handling from failing the check, but catches persistent errors. Sign swapping of innovations due to angle wrapping is not a problem due to the way that innovations are calculated inside the EKF, so a simple LPF sufficient.

### CODE REVIEW

**Comment by dagar** [comment]
@antiheavy

**Comment by Antiheavy** [comment]
@dagar is this PR the same as the test firmware we are flying?  Going to do more flying and ground testing tomorrow.

**Comment by dagar** [comment]
Yes, it's identical.

**Comment by Antiheavy** [comment]
Flight testing has shown a large reduction in EKF “internal errors” during preflight handling. I should have some logs to post tomorrow.

**Comment by Antiheavy** [comment]
@priseborough @dagar 

Here are some flight logs with this PR.  Overall it looks like it has successfully suppressed the false positive EKF internal check warnings during pre-flight handling of our hand launched fixed wing.

This FW flight log used firmware based on 1.8.0 release candidate (a few days before formal 1.8.0 release).  This PR was included in a short list of non-related custom items  Everything was great from the user perspective, but looking at the log there are a lot of airspeed innovations.
https://github.com/PX4/Firmware/pull/9723#issuecomment-399091038

These 3 logs are from a 2nd FW vehicle using firmware based on actual 1.8.0 formal release, plus this PR and a short list of other non-related custom items.
https://review.px4.io/plot_app?log=80301c1d-fac9-4a8a-a5e1-870927233e64
https://review.px4.io/plot_app?log=2c435fd6-96c2-41c7-b942-ed77ddb4942c
https://review.px4.io/plot_app?log=825a56c2-6c43-436b-b560-f365edeac9fa
https://review.px4.io/plot_app?log=2dcb0012-38a1-48cc-b144-bcbd06a310c8

**Pull request merged**
