### PR TITLE
fmu-v5 config split

### PR DESCRIPTION
**Pull request by simonegu**
**Describe problem solved by the proposed pull request**
It is not simple to read through the board_config file. This will separate the gpio configuration according to the fmu-v5 spec https://docs.google.com/spreadsheets/d/1-n0__BYDedQrc_2NHqBenG1DNepAgnHpSGglke-QQwY/edit?usp=sharing

**Describe your preferred solution**
Ported the gpio and bus specific configuration in a separate common file `gpio_config.h` between different revision. `RC00` / `RC01`

**Possible additional improvements**
It would even better if we would get rid of the `RC00` version specific config and the `BOARD_HAS_LTC4417`, thoughts?

**Test**
Bench tested on a fmu-v5

### CODE REVIEW

**Comment by dagar** [comment]
Did `PX4_FMUV5_RC00` ever ship in a product? If not I think we should drop it.

**Comment by dagar** [comment]
Can we review and merge this one first? https://github.com/PX4/Firmware/pull/11370

**Comment by dagar** [comment]
If there's interest in breaking up this file why not do it by function?

adc/power
spi
can
timers

**Comment by simonegu** [comment]
> Can we review and merge this one first? #11370

:+1: 

> If there's interest in breaking up this file why not do it by function?

@dagar I thought about that but since it is really specific to each board I thought that it could become a little cumbersome in the future maintenance if we split in 4 or more files for each board.

**Comment by davids5** [comment]
@simonegu, @dagar here we we should only remove the dead code for PX4_FMUV5_RC00

But leave I would the BOARD_HAS_LTC4417 - or you will have to  document  how to build a non LTC4417 design.

```
//#define PX4_FMUV5_RC00

#define PX4_FMUV5_RC01
#define BOARD_HAS_LTC4417
```

**Pull request closed without merging**
