### PR TITLE
MavlinkReceiver::handle_message_request_data_stream walks into delete…

### PR DESCRIPTION
**Pull request by lovettchris**
MavlinkReceiver::handle_message_request_data_stream walks into deleted memory when you send the "stop" bit on a stream. It also fails to restart the stream because it deletes the stream when you send the stop command.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! Can you run Tools/check_code_style_all.sh and follow the instructions it will provide?

**Comment by LorenzMeier** [comment]
@bkueng Can you review and fix / rebase / push as needed?

**Comment by bkueng** [comment]
Looks basically correct. Please fix the TODO as you suggested, by using the id (since MavlinkStream* already have the `get_id`, we just have to make it static).
Then I think a stream should be stopped independent from the rate (`&& req.req_message_rate != 0`), but that's a problem that already existed.

Something else: the description of the message says it's deprecated (https://pixhawk.ethz.ch/mavlink/#REQUEST_DATA_STREAM), and `MESSAGE_INTERVAL` should be used, but I don't see `MESSAGE_INTERVAL` implemented. @LorenzMeier what's your view on that?

**Comment by LorenzMeier** [comment]
We should implement both and warn about the deprecation of the old message.

**Comment by lovettchris** [comment]
I rebased, but the pullrequest is not picking that up automatically, so I will create another.

**Pull request closed without merging**
