### PR TITLE
fix MISSION_ITEM REACHED message broadcast

### PR DESCRIPTION
**Pull request by lamping7**
See https://github.com/PX4/Firmware/issues/8245

Tested in SITL.

Navigator `mission_result.reached` flag is already cleared once the message is published to px4 mavlink module here:
https://github.com/PX4/Firmware/blob/e9e663432b397e939db0a0e20a7f9fbf242dbf06/src/modules/navigator/navigator_main.cpp#L1133

@dagar @LorenzMeier @julianoes

### CODE REVIEW

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/blob/master/msg/mission_result.msg#L3

Can we drop the bool and use only seq_reached?

**Comment by dagar** [comment]
I don't think the spec actually says it should only be sent once.

I think it should either be repeated at a very low rate only in mission mode and only starting once a waypoint is reached.

OR

Update the mavlink spec so it can be acknowledged.

**Comment by lamping7** [comment]
You can't use seq_reached because it is unsigned and 0 is default value, which is a valid mission seq.

I don't see the point of constantly broadcasting the message because the current mission (with the current seq) is constantly published. For example why have it continuously publish "I reached WP #  1" when we already publish "I'm on WP # 2."

**Comment by dagar** [comment]
Yes I know, but you can change it here. https://github.com/PX4/Firmware/blob/master/msg/mission_result.msg#L3

I know it's kind of stupid to rebroadcast, but isn't the reason obvious? Without acknowledgement or rebroadcasting you can't rely on this message. That might be fine most time from a companion, but think of all the users with flaky serial radio connections. The message becomes useless for a majority of users and ground control stations. Nearly everything else has some level of acknowledgement or is continuously streamed. Let's fix the core problem.

**Comment by lamping7** [comment]
Yup. Ok. I get it (my application involves companion if you couldn't tell). I'll update shortly.

**Comment by dagar** [comment]
Thanks

**Comment by lamping7** [comment]
WIP -- `seq_reached` getting set to 0 somewhere at startup

**Comment by dagar** [comment]
Each NavigatorMode (Mission, etc) implements this interface.
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/navigator_mode.h

You could set it to -1 in on_inactive().

**Comment by lamping7** [comment]
@dagar That should build in CI... I moved the setting to -1 as you suggested (it made more sense where you suggested after running and comparing the values)... I wish I saw your suggestion earlier, but I did explore the code base quite a bit in the process.

Any chance this can get in 1.7.0? Let me know if you have nay other issues. Again, tested in SITL only.

**Comment by lamping7** [comment]
Not sure of the reason of failure `make posix_sitl_default test_results_junit` works fine for me.

**Comment by lamping7** [comment]
For some reason CI is using the unchanged message definition for mission_result, resulting in the generation of a bad mission_result topic listener. Can this be merged or do I have an issue somewhere?

**Comment by LorenzMeier** [comment]
@dagar Is this CCache failing?

**Comment by dagar** [comment]
No, much dumber, jenkins wasn't cleaning up.

Will be fixed shortly.

**Comment by lamping7** [comment]
@dagar Build and tests are good. Can this be merged in?

**Comment by dagar** [comment]
I spent some time testing this in SITL and on the bench and all is good. I reduced the size of a few of the member variables to match actual missions (squashed into your commit).

Thanks!

**Comment by dagar** [comment]
Need to dig into the ROS mission test failure.

**Comment by lamping7** [comment]
@dagar The SITL failure was not caused by this PR. It has been broken for a while.

Looking at Jenkins SITL PR tests [here](http://sitl01.dronetest.io/job/PX4%20Firmware%20POSIX%20SITL%20PRs/) you can see in the build history that this same failure has been going on intermittently with other PRs as far back as I can see (Dec 4th). Also, if you look at build history [here (not PRs)](http://sitl01.dronetest.io/view/Firmware/job/PX4%20Firmware%20POSIX%20SITL/) in Jenkins, the same has been going on since Dec 2. Both of them are showing a 40% success rate over the last 5 builds.

If you look at the [console output](http://sitl01.dronetest.io/view/Firmware/job/PX4%20Firmware%20POSIX%20SITL%20PRs/7749/console) of this PR tests, you'll see that during this test (vtol_new_2) we have:
```
INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2017-12-08/04_57_55.ulg
INFO  [mavlink] partner IP: 127.0.0.1
ERROR [mavlink] [timesync] Hard setting offset.
INFO  [commander] Landing detected
INFO  [lib__ecl] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
INFO  [lib__ecl] EKF GPS checks passed (WGS-84 origin set)
INFO  [commander] home alt: 488.08
INFO  [lib__ecl] EKF commencing GPS fusion
INFO  [commander] home: 47.3977419, 8.5455938, 488.12
INFO  [tone_alarm] home_set
WARN  [navigator] offboard mission updated: dataman_id=1, count=3, current_seq=0
INFO  [tone_alarm] neutral
INFO  [tone_alarm] positive
WARN  [commander_tests] PREFLIGHT FAIL: ACCELS INCONSISTENT - CHECK CAL
INFO  [tone_alarm] negative
WARN  [commander] Arming not possible in this state
INFO  [tone_alarm] negative
ERROR [mavlink] [timesync] Hard setting offset.
```
So, yup, it's going to surely fail if the thing doesn't arm. To see this more easily I threw it up in Flight Review too -- > https://logs.px4.io/plot_app?log=29749896-8761-41d8-80ce-e325a96b6e90

I also pulled up an older build test [here](http://sitl01.dronetest.io/view/Firmware/job/PX4%20Firmware%20POSIX%20SITL/2163/console) that failed to compare with this one. Same failure, but different test (vtol_new_1).
```
INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2017-12-02/11_47_39.ulg
INFO  [mavlink] partner IP: 127.0.0.1
ERROR [mavlink] [timesync] Hard setting offset.
INFO  [commander] Landing detected
INFO  [lib__ecl] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
WARN  [lib__ecl] EKF stopping navigation
INFO  [lib__ecl] EKF GPS checks passed (WGS-84 origin set)
INFO  [lib__ecl] EKF commencing GPS fusion
INFO  [commander] home: 47.3977419, 8.5455937, 488.06
INFO  [tone_alarm] home_set
WARN  [navigator] offboard mission updated: dataman_id=0, count=2, current_seq=0
INFO  [tone_alarm] neutral
INFO  [tone_alarm] positive
WARN  [commander_tests] PREFLIGHT FAIL: ACCELS INCONSISTENT - CHECK CAL
INFO  [tone_alarm] negative
WARN  [commander] Arming not possible in this state
INFO  [tone_alarm] negative
```
log --> https://logs.px4.io/plot_app?log=d6ba8172-41e2-4dcb-a465-bc965de54b84

The cause here is probably invalid data on boot and not enough delay before the tests start. Either an issue with sensors app or maybe just sleep longer in [mission_test.py](https://github.com/PX4/Firmware/blob/master/integrationtests/python_src/px4_it/mavros/mission_test.py#L234). Unless you find something odd in the sensor app, it is my guess that this is probably an issue with the Jenkins test environment (maybe running slow?) due to how intermittent it is.

It can also be seen in the Jenkins build history that this tested good multiple times last night after we finished it up. Anyway, this is a separate issue, and this PR is good. Hopefully this was helpful.

**Pull request merged**
