### PR TITLE
[WIP] Mount and ROI implementation rebased & refactored

### PR DESCRIPTION
**Pull request by bkueng**
Continuation of #4624 

Needs testing on actual HW.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Please rebase on master to fix CI.

**Comment by bkueng** [comment]
This includes the switch to HIL_ACTUATOR_CONTROLS message and thus depends on
https://github.com/PX4/jMAVSim/pull/31 and https://github.com/PX4/sitl_gazebo/pull/38

@hsu you can test gimbal control with this branch and the gazebo PR:
```
commander takeoff
vmount test yaw 30
```
However if you do for example `vmount test yaw 90`, the control becomes unstable. Can you please look into that?

**Comment by LorenzMeier** [comment]
@bkueng In case Jenkins should not be passing please check.

**Comment by LorenzMeier** [comment]
@bkueng Looks like the standard VTOL tests are failing, maybe due to a subtle mapping change.

**Comment by LorenzMeier** [comment]
@bkueng Here is what broke: If you run ```make posix gazebo_standard_vtol``` and then issue ```commander takeoff``` (which will already fail) you also need to be able to successfully run ```commander transition``` (at which point the vehicle should be circling the home position, as visible in QGroundControl). Some of the actuator mappings broke with your changes.

**Comment by LorenzMeier** [comment]
@bkueng This here gets it to take off (in Tools/sitl_gazebo):

```diff
diff --git a/models/standard_vtol/standard_vtol.sdf b/models/standard_vtol/standard_vtol.sdf
index b63cc2b..7d87426 100644
--- a/models/standard_vtol/standard_vtol.sdf
+++ b/models/standard_vtol/standard_vtol.sdf
@@ -854,6 +854,53 @@
       <robotNamespace></robotNamespace>
       <imuSubTopic>/imu</imuSubTopic>
       <motorSpeedCommandPubTopic>/gazebo/command/motor_speed</motorSpeedCommandPubTopic>
+      <control_channels>
+        <channel name="rotor0">
+          <input_index>0</input_index>
+          <input_offset>1</input_offset>
+          <input_scaling>450</input_scaling>
+          <zero_position_disarmed>0</zero_position_disarmed>
+          <zero_position_armed>0</zero_position_armed>
+          <joint_control_type>velocity</joint_control_type>
+          <joint_name>rotor_0_joint</joint_name>
+        </channel>
+        <channel name="rotor1">
+          <input_index>1</input_index>
+          <input_offset>1</input_offset>
+          <input_scaling>450</input_scaling>
+          <zero_position_disarmed>0</zero_position_disarmed>
+          <zero_position_armed>0</zero_position_armed>
+          <joint_control_type>velocity</joint_control_type>
+          <joint_name>rotor_1_joint</joint_name>
+        </channel>
+        <channel name="rotor2">
+          <input_index>2</input_index>
+          <input_offset>1</input_offset>
+          <input_scaling>450</input_scaling>
+          <zero_position_disarmed>0</zero_position_disarmed>
+          <zero_position_armed>0</zero_position_armed>
+          <joint_control_type>velocity</joint_control_type>
+          <joint_name>rotor_2_joint</joint_name>
+        </channel>
+        <channel name="rotor3">
+          <input_index>3</input_index>
+          <input_offset>1</input_offset>
+          <input_scaling>450</input_scaling>
+          <zero_position_disarmed>0</zero_position_disarmed>
+          <zero_position_armed>0</zero_position_armed>
+          <joint_control_type>velocity</joint_control_type>
+          <joint_name>rotor_3_joint</joint_name>
+        </channel>
+        <channel name="rotor4">
+          <input_index>4</input_index>
+          <input_offset>1</input_offset>
+          <input_scaling>900</input_scaling>
+          <zero_position_disarmed>0</zero_position_disarmed>
+          <zero_position_armed>0</zero_position_armed>
+          <joint_control_type>velocity</joint_control_type>
+          <joint_name>rotor_puller_joint</joint_name>
+        </channel>
+      </control_channels>
       <left_elevon_joint>
         left_elevon_joint
       </left_elevon_joint>

```

**Comment by LorenzMeier** [comment]
But it still fails to transition.

**Comment by LorenzMeier** [comment]
Transition works locally now, but apparently not in CI yet.

**Comment by bkueng** [comment]
Narrowed to problem down to changes in motor_model by @hsu. CI succeeds when reverting the motor_model changes, as done in https://github.com/PX4/sitl_gazebo/commit/642aa8535196cbbca42e623321a9444af3031c5e

**Comment by thedevleon** [comment]
Thanks for continuing my work @bkueng! Will be testing it out today :)

**Pull request merged**
