### PR TITLE
cleanups - remove non-used pca8574 and oraled drivers

### PR DESCRIPTION
**Pull request by BazookaJoe1900**
**Describe problem solved by the proposed pull request**
Both led drivers (pca8574 and oraled) are not used, but keep being compiled on many boards.
there is no pca8574 and oraled start on any rcS.
removed as discussed on #12832

**Test data / coverage**
none done by me....

### CODE REVIEW

**Comment by dagar** [comment]
Can you delete the actual driver code?

**Comment by BazookaJoe1900** [comment]
@dagar @LorenzMeier. I can delete it completely, but are you 100% sure that nobody uses it?
users might use it with non-upstream code, or call it by rc.extra, or call by runtime....

**Comment by dagar** [comment]
Yes for the same reasons mentioned in https://github.com/PX4/Firmware/issues/12832.
If there's value in keeping any of these things we can resurrect them with some minimal real testing, but based on the state of this code I don't see any real users. Keeping anything in tree without compiling is even worse.

**Comment by BazookaJoe1900** [comment]
> Yes for the same reasons mentioned in #12832.
> If there's value in keeping any of these things we can resurrect them with some minimal real testing, but based on the state of this code I don't see any real users. Keeping anything in tree without compiling is even worse.

Done

**Comment by BazookaJoe1900** [comment]
refs to #12409

**Pull request merged**
