### PR TITLE
PMW3901: use quality metric

### PR DESCRIPTION
**Pull request by nicovanduijn**
This PR adds support for the quality metric of the flow data of the PMW3901 optical flow sensor.

Previously, the quality field of the `distance_sensor` message was populated in a binary way, either 0 for infinitesimally small motion or 255 in any other case.

image

However, the data inherently computes a flow metric which can be read from register 7. (See [here](https://wiki.bitcraze.io/_media/projects:crazyflie2:expansionboards:pot0189-pmw3901mb-txqt-ds-r1.00-200317_20170331160807_public.pdf))

image

Sadly, I was unable to find any documentation about what the values really mean. But I've done a good amount of testing and must say that it correlates exceptionally well with what I would expect to influence the flow quality:
- It goes very low (<60, with long spans of constant 0) in complete darkness
- It goes very low if there is no texture
- It's around 80-100 in normal office lighting
- It's around 120-150 on a sunny day outside

I'm not familiar with the exact way how this data is fused by EKF2, but I believe that it scales the variance linearly between `EKF2_OF_QMIN`  and 255. Based on my tests I would recommend that parameter to be set to 60.

** Handheld flow-tests **
I started the logger and took my quad for a little walk. Obviously the two "walks" are not very similar. This is just to get an idea of how often EKF2 resets, how much it drifts etc. I can not see a difference in performance between the two, to be honest. But I can't imagine things would be worse
Master: https://review.px4.io/plot_app?log=348f5982-94b0-4d92-8ed7-1f506576eef4
This PR: https://review.px4.io/plot_app?log=baf10d57-5b5d-4de5-b596-c6b9b0d9873e

### CODE REVIEW

**Comment by TSC21** [comment]
@nicovanduijn can you rebase? Thanks

**Comment by nicovanduijn** [comment]
Thanks for merging. In case it still matters, I flight-tested this just a few minutes ago:
https://review.px4.io/plot_app?log=0cb88ee7-59e6-4706-992a-a9cc2e0a51f1

**Comment by TSC21** [comment]
> Thanks for merging. In case it still matters, I flight-tested this just a few minutes ago:
> https://review.px4.io/plot_app?log=0cb88ee7-59e6-4706-992a-a9cc2e0a51f1

Cool. I see you flew with flow only. How was the performance on hover? Also, have you tried this with GPS + Flow fusion?

**Comment by nicovanduijn** [comment]
Yes, I purposely disabled GPS to see the pure flow performance. Performance was really good, actually. Take-off is questionable, until you reach the height where the distance sensor gives good data. I'm looking into that next.
I haven't tried fusing GPS back in, not sure why I would test that. Can't be worse, really

**Comment by TSC21** [comment]
> I haven't tried fusing GPS back in, not sure why I would test that. Can't be worse, really

Main reason is to understand if you lose GPS signal, how would EKF2 will behave with only flow at that stage.

**Comment by nicovanduijn** [comment]
That's a general EKF2 question, which I'm investigating too, to some extent. We have flown into- and out of GPS denied areas. This works okay-ish, but sure needs more testing. One time we've seen it starting to drift, because GPS was there, but inaccurate.

But it's not related to this PR

**Comment by TSC21** [comment]
> But it's not related to this PR

I know. I was more looking for your feedback on the subject. We may sync on Slack. Thanks

**Pull request merged**
