### PR TITLE
posix-configs: set SYS_MC_EST_GROUP

### PR DESCRIPTION
**Pull request by bkueng**
... so that tools like flight_review know which estimator was used.
@jgoppert

### CODE REVIEW

**Comment by jgoppert** [comment]
@bkueng I've got IEKF set as 3, if you don't have that mapping yet does it just default to showing the int?

**Comment by LorenzMeier** [comment]
@bkueng Please include IEKF as 3 in flight review. Thanks!

**Comment by LorenzMeier** [comment]
@bkueng Needs rebase.

**Comment by bkueng** [comment]
Sure I'll add IEKF to flight_review. @jgoppert can you add it to the MC_SYS_EST_GROUP param definition (or is it already?)

Rebased

**Comment by jgoppert** [comment]
I added it on iekf branch, pr isn't merged yet, close to ready.

**Pull request merged**
