### PR TITLE
Refactor sdflight configs

### PR DESCRIPTION
**Pull request by mcharleb**
Signed-off-by: Mark Charlebois <charlebm@gmail.com>

### CODE REVIEW

**Comment by mcharleb** [comment]
Do not merge yet. Needs review.

@jywilson Can you please review?

**Comment by mcharleb** [comment]
These changes depend on https://github.com/PX4/Firmware/pull/6926

**Comment by LorenzMeier** [comment]
@jywilson @mcharleb We have everything else almost done now, so validating and feature-freezing the Qualcomm configs is the last bit missing for v1.6

**Comment by LorenzMeier** [comment]
@jywilson @mcharleb Where is this standing?

**Comment by LorenzMeier** [comment]
@mcharleb @jywilson Can you rebase and update?

**Comment by LorenzMeier** [comment]
@mcharleb @jywilson Can you rebase and update?

**Comment by LorenzMeier** [comment]
Closing as abandoned.

**Pull request closed without merging**
