### PR TITLE
FW don't allow ACRO or RATTITUDE

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by kd0aij** [comment]
Are acro, rattitude and angle distinct modes or are they "submodes" of MANUAL?
The wording here falsely implies that manual mode is stabilized for FW

**Comment by dagar** [comment]
I'm not sure I follow what you're saying. There aren't really submodes, although it doesn't really seem that way when using the current(/old?) nested mode switch configuration.

What are you looking at that falsely implies that manual mode is stabilized for FW? If it's just the state machine then they're only the same in that they both don't require any special flags (valid position, altitude, etc).

**Comment by kd0aij** [comment]
I thought ACRO meant non-stabilized when in fixed-wing mode, so "disallowing" it implied to me that you could no longer turn stabilization off. But this page: http://dev.px4.io/concept-flight-modes.html doesn't mention that there are two different "manual" modes for FW, so I'm definitely confused.

**Comment by dagar** [comment]
I was under the impression ACRO is rate mode, which we don't have in the fixed wing controller. Any mode without the control_attitude_enabled just falls through to manual. Is ACRO mode for FW unstabilized/manual a common interpretation? This actually explains something I heard from a user that I thought was just confused.

I've thought about implementing ACRO and/or RATTITUDE for fixed wing I just haven't gotten around to it. I don't think it would be difficult if anyone is interested.

Another point of confusion I want to get rid of is MANUAL/STABILIZED being the same for MC. Either startup straight into stabilized or take care of it in the state machine. Position control for fixed wing should probably have a better name, but I'll save that thought for another day.

**Comment by kd0aij** [comment]
I recall having stabilized mode in addition to ALTCTL and POSCTL for FW. It just controlled roll/pitch attitude and yaw rate. FW "manual" mode is analogous to MC ACRO mode in that you can do rolls and loops with it, so I used the same TX switch to select MC ACRO and FW non-stabilized modes, as though ACRO/non-stablized are sub-modes of MANUAL for both FW and MC.

**Comment by dagar** [comment]
@kd0aij Looking at the flight mode switch evaluation your current/desired usage shouldn't change.

What I'm trying to prevent with this PR is selecting ACRO/RATTITUDE through QGC (or gamepad) and PX4 entering and reporting ACRO/RATTITUDE, but the FW controller actually behaving like MANUAL.

For RC I much prefer the new simple flight mode selection.

**Comment by kd0aij** [comment]
So "Manual" and "Stabilized" are the two manual modes for FW?

**Comment by dagar** [comment]
Yes, but that concept of manual really only exists in the current/old RC switch logic and that diagram. Why are STABILIZED/ACRO/RATTITUDE manual modes? STABILIZED definitely sounds like an assist mode to me.
It's probably not a good sign if even we're confused by this.

It's funny how mode discussion always seem to blow up - https://github.com/PX4/Firmware/issues/3967

The bottom line is ACRO and RATTITUDE aren't yet implemented for FW, so the transition should be blocked by commander. Agreed?

**Comment by kd0aij** [comment]
I was just confused by the omission of "stabilize" mode from this text (and the code, of course)
https://github.com/PX4/Devguide/pull/165

And I don't get involved in discussions like #3967 unless I feel I'm in a good position to drive changes.

**Comment by dagar** [comment]
I wonder if adding table to the documentation that shows modes mapping to control flags would help?
https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L3301

Manual - nothing
Acro - rates
Stabilized - rates, attitude
Altitude control - rates, attitude, altitude
Position control - rates, attitude, altitude, position
etc

**Comment by kd0aij** [comment]
It would certainly be helpful to a maintenance programmer, as would notes indicating where there is any lack of orthogonality between the flags.

**Comment by dagar** [comment]
It looks like I should actually be checking status.is_rotary_wing which accounts for the vtol mode. Updating PR.

**Comment by kd0aij** [comment]
I think the original concept of MANUAL simply meant that attitude was controlled directly by the pilot. The autopilot did nothing beyond executing the pilot's attitude control commands.
 
And ASSISTED has always meant that the autopilot did something more, like control altitude or position based on stick inputs, or fly fully autonomous. 

The one asymmetry in "MANUAL" is the FW (autopilot bypass) failsafe mode which MC can't provide (since copters aren't inherently stable), but that seems clearly analogous to MC's ACRO mode. So FW has always had two "manual" modes, STABILIZE and ACRO, while MC has 3, now that there's also RATTITUDE. Again the asymmetry only in that FW ACRO mode doesn't need an autopilot to implement rate-based control of a FW craft.

**Comment by tubeme** [comment]
There were a numerous discussions on this issues.

Here is a DOC file that summarizes all the issues related to flight mode names.

Now is the time to set proper names once and for all and get the things in right order.

https://docs.google.com/document/d/1pi7YMKu9dhcq6HRAXQ_gMesn2gGrRa7cdNTYLEsNDjE/edit

If you want to read the discussions I can give you pointers in the git.

**Comment by dagar** [comment]
@LorenzMeier review/merge?

**Comment by LorenzMeier** [comment]
Rebased and applied, thanks!

**Pull request closed without merging**
