### PR TITLE
microRTPS: use packaging.version to compare FastRTPS lib versions

### PR DESCRIPTION
**Pull request by TSC21**
Supersedes and fixes the reported in https://github.com/PX4/Firmware/pull/14393.

@stmoon after some research I found that `packaging.version` is suited to these kind of comparisons, and so there's no need for parsing the major and minor to numerical. I tested this with FastRTPS master built and installed from source, matching the 1.10 version, and this works as it should. Please test on your side and thanks for the contribution!

### CODE REVIEW

**Comment by TSC21** [comment]
We are just missing @MaEtUgR to update the Windows toolchain and this should be good to go.

**Comment by MaEtUgR** [comment]
I'm adding it. I have it working locally and will deploy v0.9 with that added and multiple toolchain components up to date.

**Comment by TSC21** [comment]
> I'm adding it. I have it working locally and will deploy v0.9 with that added and multiple toolchain components up to date.

Awesome! Good news! Thank you!

**Comment by stmoon** [comment]
@TSC21 Yes~~~ It's working!!!.

After merging to master, #14394 will be solved too.

**Comment by MaEtUgR** [comment]
Done, Windows should build fine now. I'll be faster next time since I improved automatic deployment. There's only one manual step remaining that I need to automate.

**Comment by TSC21** [comment]
@MaEtUgR something else seems to be failing...

**Comment by MaEtUgR** [comment]
This seems worse, it looks like cmake problems with NuttX targets 😞

**Comment by TSC21** [comment]
> This seems worse, it looks like cmake problems with NuttX targets

Can we by any chance solve this in another PR?

**Comment by TSC21** [comment]
@hamishwillee this will require an update in the build scripts (ubuntu/arch).

**Comment by hamishwillee** [comment]
@TSC21 Can you make it then - these live in firmware now, so you could do it as part of this pull. 

Also, the docs assume you use a version of scripts in same release tag - would be need to fix up older tree too? e.g. for new release 1.11?

**Comment by TSC21** [comment]
> @TSC21 Can you make it then - these live in firmware now, so you could do it as part of this pull.
> 
> Also, the docs assume you use a version of scripts in same release tag - would be need to fix up older tree too? e.g. for new release 1.11?

This is only applicable to the 1.11.

**Comment by hamishwillee** [comment]
Great. So please do put the needed changes in the build scripts too. Then everything will link up right when the 1.11 branch of docs gets created.

**Comment by MaEtUgR** [comment]
@TSC21 I fixed the Windows toolchain issue with v0.9 and rebuilt the installer. I rebased this pr on master without conflict to retrigger CI. Now it fails on some other containers missing the packaging. Sorry for any delays. That was an uncommon problem, usually it's straight forward and mostly automated to update the toolchain.

**Comment by TSC21** [comment]
> @TSC21 I fixed the Windows toolchain issue with v0.9 and rebuilt the installer. I rebased this pr on master without conflict to retrigger CI. Now it fails on some other containers missing the packaging. Sorry for any delays. That was an uncommon problem, usually it's straight forward and mostly automated to update the toolchain.

Thanks for the help @MaEtUgR!

**Comment by TSC21** [comment]
All checks passed. Merging

**Comment by bys1123** [comment]
image
Intereting, I still get No module named 'packaging' with latest setup script.

**Comment by TSC21** [comment]
> image
> Intereting, I still get No module named 'packaging' with latest setup script.

What script are you using? This I suppose? https://github.com/PX4/Firmware/blob/master/Tools/setup/ubuntu.sh?

**Comment by julianoes** [comment]
@bys1123 `pip3 install --user packaging`.

**Comment by TSC21** [comment]
`packaging` was added here as you can see https://github.com/PX4/Firmware/commit/975227c52ab9424a497a0e7f6c7c07b3c60848fb. Now I don't know if everytime the script is run if it gets the Python requirements. If it doesn't use @julianoes recommendation.

**Comment by bys1123** [comment]
@julianoes I fixed with `sudo pip3 install packaging` yesterday.
but interesting thing is it doesn't work with `packaging` already added in requirements.txt.

**Comment by bys1123** [comment]
Emm, I watched my video recording, maybe caused by I ran ubuntu.sh with sudo?

**Comment by julianoes** [comment]
> maybe caused by I ran ubuntu.sh with sudo?

Yes, don't do that.

What's the output of:
```
which python
which python3
which pip
which pip3
python --version
python3 --version
pip --version
pip3 --version
```

**Comment by bys1123** [comment]
@julianoes I think I found the reason. 1. I ran it with "sudo" 2. I didn't ran it with "bash".

**Comment by bys1123** [comment]
image
@julianoes This also happened in new installed PX4 Cygwin Toolchain.

**Comment by TSC21** [comment]
> image
> @julianoes @MaEtUgR This also happened in new installed PX4 Cygwin Toolchain.

@bys1123 version 0.9 of the toolchain already has `packaging` installed - https://github.com/PX4/windows-toolchain/releases/tag/v0.9.

**Comment by bys1123** [comment]
@TSC21 Thanks again……looks I installed wrong file……I installed old experiment 0.9 version.

**Pull request merged**
