### PR TITLE
This makes QGC connect with crazyflie

### PR DESCRIPTION
**Pull request by barzanisar**
Discussed in https://github.com/PX4/Firmware/issues/8924

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@bueng is the crazyradio UART correctly configured and all input handling (CR, LF) disabled? This change looks like it’s working around that.

**Comment by LorenzMeier** [comment]
Please compare how the UART is configured in the MAVLink app. It needs that.

**Comment by bkueng** [comment]
The change here looks strange to me too. I already gave @barzanisar a commit to test that changes the settings to disable input handling (as `gps` does): https://github.com/bkueng/Firmware/commit/b8ba1b74436f0be29469c1c7c9de0a2b8e6ecaa8. @barzanisar can you try this again instead?

**Comment by barzanisar** [comment]
Ok I tried @bkueng 's changes instead and QGC connects.  So I guess no need to change # CONFIG_DEV_LOWCONSOLE to CONFIG_DEV_LOWCONSOLE=y

**Pull request merged**
