### PR TITLE
Add Safe Landing Planner to CI

### PR DESCRIPTION
**Pull request by mrivi**
- update avoidance ci to release 0.3.0
- add safe landing planner CI

### CODE REVIEW

**Comment by mrivi** [comment]
@dagar we are seeing this issue https://github.com/PX4/Firmware/issues/11662 in the CI with the updated containers.  Downgrading PyYAML from 5.1 to 3.13 could be an option

**Comment by dagar** [comment]
> @dagar we are seeing this issue #11662 in the CI with the updated containers. Downgrading PyYAML from 5.1 to 3.13 could be an option

We can pin it to a known working version.
https://github.com/PX4/Firmware/blob/46662072d162011178655b026dae140d8a5c0836/Tools/setup/requirements.txt#L11

**Comment by mrivi** [comment]
@dagar we would need to downgrade PyYaml on the container side, right?
@TSC21 - What do you think about fixing the issue on the mavros side instead?

**Comment by TSC21** [comment]
> @TSC21 - What do you think about fixing the issue on the mavros side instead?

Related: https://github.com/mavlink/mavros/issues/1210. I guess either way is fine - it's not a matter of a fix since this worked before with pyyaml. So I guess since we are moving the pyyaml version further we can add the workaround on the `px4_config.yaml` for now.

**Comment by mrivi** [comment]
@dagar could we get this in?

**Pull request merged**
