### PR TITLE
Analog Devices ADIS16448 cleanup

### PR DESCRIPTION
**Pull request by dagar**
- move to PX4Accelerometer and PX4Gyroscope helpers

### CODE REVIEW

**Comment by dagar** [comment]
The file `adis16448.cpp` was split into `ADIS16448.cpp` and `ADIS16448.hpp`. As a result that diff looks more substantial than it actually is.

**Comment by LorenzMeier** [comment]
Could you rebase and have you tested this on HW?

**Comment by dagar** [comment]
It's been tested on Linux. Need to get wiring together to make sure it's still fully functional in NuttX.

**Comment by dagar** [comment]
Still working on the bench.

**Pull request merged**
