### PR TITLE
WIP: VTOL_TAKEOFF and VTOL_LAND mission command support

### PR DESCRIPTION
**Pull request by sanderux**
Fixes: https://github.com/PX4/Firmware/issues/3492
Fixes: https://github.com/PX4/Firmware/issues/3414
Support for MAV_CMD_NAV_VTOL_TAKEOFF and MAV_CMD_NAV_VTOL_LAND

todo

- [ ] Rebase and remove weathervane merge (maybe setup new branch)
- [ ] Implement weathervane land for VTOL_LAND
- [ ] Flight test

### CODE REVIEW

**Comment by sanderux** [comment]
@DonLakeFlyer these commands should be supported in QGC
they are in every sense similar to takeoff and land commands

**Comment by sanderux** [comment]
Here's the test mission waypoint file
[vtol takeoff and land.txt](https://github.com/PX4/Firmware/files/120995/vtol.takeoff.and.land.txt)

**Comment by sanderux** [comment]
whoops, merge was not intended

**Comment by AndreasAntener** [comment]
It's probably best to wait with this until the new mission handling is in (it's ready now, just needs a last flight test).

**Comment by LorenzMeier** [comment]
I'm going to reset this branch. @sanderux Please delete this branch locally and re-checkout it.

**Comment by LorenzMeier** [comment]
No, actually not resetting. We'll deal with this later.

**Comment by sanderux** [comment]
Both these items need further testing in actual flight (mostly weathervane) because testing this in SITL is hard.

**Comment by sanderux** [comment]
@AndreasAntener i merged this code in your vtol_mission_fixes tree locally. works (much better).

**Pull request closed without merging**
