### PR TITLE
[makefile]: Changed PWD -> CURDIR. PWD omitted backslashes on the win…

### PR DESCRIPTION
**Pull request by oberion**
…dows machine
Hope this does not mess up with other OS.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Let us know what else is required to fix the Windows build.

**Comment by oberion** [comment]
Thats the only thing necessary to build the default nutty firmware. The changes are only necessary, if the repo folder is not located at a top level directory.

**Comment by oberion** [comment]
Hmm is there a problem with it on mac. thougth yesterday it did pass-

**Comment by LorenzMeier** [comment]
Closing this, @dagar has fixed Windows on master since. Thanks!

**Pull request closed without merging**
