### PR TITLE
Small simulator/lockstep fixes

### PR DESCRIPTION
**Pull request by julianoes**
I've manually applied some of the changes proposed by @lovettchris in #13442 because the patches did not apply cleanly anymore.

This depends on https://github.com/mavlink/mavlink/pull/1311.

### CODE REVIEW

**Comment by dagar** [comment]
Seems fine to me. Do you want to wait for the mavlink side?

If I was going to do anything here I think we should be getting rid of all this code that maps the simulated actuator_outputs PWM values back to normalized.

**Comment by Jaeyoung-Lim** [comment]
I think this has broke some SITL plugins (parachute plugin / catapult plugin) where it was checking the pwn values the vehicles. @TSC21 FYI

**Comment by TSC21** [comment]
Weird. This has been out for some time now. Isn't the catapult plugin a more recent add?

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Not really, the catapult plugin was added 5 months ago!

**Comment by TSC21** [comment]
> @TSC21 Not really, the catapult plugin was added 5 months ago!

Ok I see. So do you have a suggestion or an alternarive approach to these changes to make it work?

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Not yet, I would need to have a closer look. It seems like the actuator control values don't change anymore with disarm / flight termination.

**Pull request merged**
