### PR TITLE
fw_pos_control_l1 add new simple min groundspeed

### LINKED ISSUE #10078: Feature Request: improved minimum ground speed controller for Fixed Wing
For general questions please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/).

Currently the FixedwingPositionControl will increase the airspeed set point to attempt to maintain a minimum ground speed derived from FW_AIRSPD_MIN:  https://github.com/PX4/Firmware/blob/50ae8c9c6f8e5d56e91d43604950ab97333a7e17/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp#L522

This is somewhat arbitrary.  Users and integrators should be able to explicitly set a minimum ground speed as a separate parameter appropriate to their vehicle and use cases.  Being able to explicitly choose a minimum ground speed  will help with optimizing and trading endurance, range, takeoff and landing performance and other factors.

We could either add a new parameter that:
a) sets this explicitly, e.g.  **FW_GNDSPD_MIN** (default 5 m/s ?)
b) scales minimum ground speed to minimum airspeed, e.g. **FW_GNDSPD_MIN_SC** (default 1.0), this may be an approach to not impact current users.

Additionally, we should consider adding a moving average filter to the inputs to this calculation to smooth out wind gusts or other temporary disturbances.

FYI @dagar

### PR DESCRIPTION
**Pull request by dagar**
This introduces a new FW parameter `FW_GND_SPD_MIN` to set the desired minimum groundspeed. This replaces existing logic which projects your current airspeed to the ground and has weird coupling with large pitch changes.

Fixes #10078

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Makes sense

**Comment by dagar** [comment]
We should be able to test this effectively in SITL, although a real flight never hurts.

**Comment by Antiheavy** [comment]
> We should be able to test this effectively in SITL, although a real flight never hurts.

happy to flight test.  might not be until next week based on weather here this week.

**Comment by Antiheavy** [comment]
Flight tested successfully.  We set FW_GND_SPD_MIN very low (1 m/s) and see that the airspeed remains very steady even when flying into a headwind where it would previously have increased airspeed.  We believe this is working correctly.

Flight log:
https://review.px4.io/plot_app?log=7113bba3-2e45-4b01-8d59-a97ea66e93f7

**Comment by Antiheavy** [comment]
Been flying this a lot lately. Works great and improves flight control in windy conditions. Would be nice if it made in into Master IMHO.

**Comment by LorenzMeier** [comment]
Needs a squash and merge.

**Comment by Antiheavy** [comment]
This would be good to get in for v1.10.  Been flying a version of it successfully for a couple months.

**Comment by Antiheavy** [comment]
@dagar I think this is good to go?  we've been flying it a lot lately and it works as intended.

**Comment by LorenzMeier** [comment]
@Antiheavy Could you ping me on any other PRs in similar states that really should go in?

**Pull request merged**
