### PR TITLE
Add offboard velocity control with z-axis position control.

### PR DESCRIPTION
**Pull request by clovett**
The set_position_target_local_ned.type_mask allows for individual bit masks for x,y,z,vx,vy,vz, but px4 only implemented 0x7 for position control OR 0x38 for velocity control.  This change allows you to mix 0x4 for z-axis control with 0x30 for vx,vy control.  The mc_pos_control module will then maintain the specified z-position while honoring the vx,vy velocity control.  This makes it super simple to fly nice curves while not having to worry about implementing a pid-algorithm for managing height.  Besides it is better for mc_pos_control to do that since it has a much tighter loop than an offboard mavlink connection.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Makes a lot of sense overall. Could you please do the suggested changes? @Stifael please review.

**Comment by clovett** [comment]
Stifael, have you had a chance to look at this yet?  I've been testing it successfully for the last week and it seems good to go.

**Comment by mzahana** [comment]
This featuring is interesting. I am wondering if the vx/vy are in local NED frame, or in body fixed frame. Ca it be used such that when I would like to command the vehicle to mode forwared (command +vx), right (command +vy) w.r.t to vehicle-fixed NED frame?

**Comment by Stifael** [comment]
@mzahana: the velocity setpoints are in local frame coordinate system, so you if you work offboard you can just transform the body fixed velocity vectors to the local frame

**Comment by TobiMiller** [comment]
please merge it in master asap :) thx

**Comment by LorenzMeier** [comment]
Replaced by rebased https://github.com/PX4/Firmware/pull/5816

**Comment by LorenzMeier** [comment]
Rebased, squashed and merged.

**Pull request closed without merging**
