### PR TITLE
Thermal control for Pixhawk 2

### PR DESCRIPTION
**Pull request by LorenzMeier**
@dagar This is untested but should give you all the pointers needed to fiddle with thermal control on your Pixhawk 2.1

### CODE REVIEW

**Comment by proficnc** [comment]
Thanks Lorenz!

**Comment by dagar** [comment]
Pretty close :wink: 
I'll let it run for a bit to verify, unless there's an easy way to poke around the io?
Thanks Lorenz

**Comment by dagar** [comment]
I verified this PR works via the blue LED on a pixhawk. On a pixhawk 2.1 the cube still feels warm though.

Temperatures in celsius after 30 minutes on my desk with the IMU heater disabled.
both mpu9250s ~low 60s
both ms5611s ~ mid 40s
l3gd20 41C

@proficnc Does this sound normal with the heater disabled? My office is 24C.

**Comment by LorenzMeier** [comment]
@dagar Sounds normal from my experience.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by proficnc** [comment]
With heater "disabled" you are still running the blue light... to truely
"disable" the heater, you must control the blue light to ensure it is not
turning the heater on.

**Comment by LorenzMeier** [comment]
The blue ring and the blue led are not the same physical pin / output. Are you saying the heater is connected to both?

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by proficnc** [comment]
The heater is connected to the old I/O Blue LED that was on Pixhawk 1

If it is just left as I/O activity, then it will be on a significant amount of time.  

So it is important that the old function is disabled when it is a pixhawk 2.1

**Comment by dagar** [comment]
Interesting, the mpu9250s run much hotter than I expected.
Thanks

**Pull request merged**
