### PR TITLE
fixing sitl bug

### PR DESCRIPTION
**Pull request by iftahnaf**
https://discuss.px4.io/t/how-to-fixed-this-problem-when-run-the-sitl/14995/12

**Describe problem solved by this pull request**
running gazebo in sitl, compilation error - the simulation isn't running.

**Describe your solution**
 in the gazebo_opticalflow_plugin.h I edit the #define HAS_GYRO true to #define HAS_GYRO 1
now it works.

**Describe possible alternatives**
Im not sure if it is the best option, please review.

**Test data / coverage**
now it complies and I can run the sitl.

**Additional context**
thanks for reviewing it.

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@iftahnaf This was already fixed ing https://github.com/PX4/Firmware/pull/14110

**Comment by iftahnaf** [comment]
@Jaeyoung-Lim  Sorry, my mistake.
I'm on Ubuntu 18.04. It worked for me only after changing the HAS_GYRO value.

**Comment by TSC21** [comment]
> @Jaeyoung-Lim Sorry, my mistake.
> I'm on Ubuntu 18.04. It worked for me only after changing the HAS_GYRO value.

This is a problem on the stable release that was fixed already. Details in https://github.com/PX4/sitl_gazebo/pull/408. If you want to use the stable release then you can keep this change locally. Otherwise, this is already fixed in master and you just need to clone the master branch instead of the stable branch.

**Comment by TSC21** [comment]
Also just to clarify that given that the 1.11 release is happening soon, it doesn't make sense at this point to add patches or propagate changes back to 1.10.

**Comment by iftahnaf** [comment]
@TSC21 Ok, Thanks for the help and sorry for your time!

**Pull request closed without merging**
