### PR TITLE
Fix calibration messages in QGC

### LINKED ISSUE #4158: Mag calibration fails over WiFi connection
This is using a PixRacer over WiFi. Important messages which trigger the QGC state machine to move to the next step get lost, which then causes QGC to get confused. The one which I have noticed is the "side done" message, although I'd assume others could get lost as well. For QGC it's important that it receives the start/done/fail and orientation detected/side done messages. If some of these are missed the ui state machine doesn't work. It seems to be caused by progress messages being output at too high a rate. If I comment out the progress updates mag cal will suceed. Leave them it, and I have 100% failure rate.

### PR DESCRIPTION
**Pull request by julianoes**
This should fix #4158.

Only tested on Pixhawk connected over USB. Needs cross-testing on Pixracer over Wifi.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
A number of problems:
- Unsupported command
- High vibration when I'm just moving it around to an orienation
- Missed side done message

screen shot 2016-04-05 at 9 31 09 am

**Comment by DonLakeFlyer** [comment]
Also FYI: I was planning to do a WiFi setup demo on my PixRacer with QGC at the conference on Thursday. So if possible would be great to figure it out. Not the end of the world since I can do USB, but not as nice of a demo.

**Comment by DonLakeFlyer** [comment]
FYI: Just tested PixRacer with WiFi and Stable and that works. So I can use that for my demo.

**Comment by sn0west** [comment]
on the latest master it still dosn't work over wifi.

**Comment by LorenzMeier** [comment]
@sn0west Try master now. Its only now merged to master.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier I tested this by building it myself and it didn't work (as documented above). Is there another pull that was supposed to fix this.

**Comment by LorenzMeier** [comment]
yes, can you re-try current master from *now*?

**Comment by DonLakeFlyer** [comment]
Just flashed master using QGC. Same exact problems as above. Unsupported command then missed messages.

**Comment by julianoes** [comment]
`Unsupported command`? That's confusing, I haven't seen that recently.

**Pull request closed without merging**
