### PR TITLE
update ecl submodule to include range aid fixes/updates

### PR DESCRIPTION
**Pull request by ChristophTobler**
This update includes fixes discussed in https://github.com/PX4/Firmware/pull/6989#issuecomment-310340785
Still need to go out and test (only SITL tested so far).

@ndepal Could you maybe test with your setup once more since it is perfect for corner cases ;)

### CODE REVIEW

**Comment by ndepal** [comment]
Tested this. As far as I can see, it only ever used the ranger, never the main height source GPS.
http://logs.px4.io/plot_app?log=9d42b693-78f5-4dfa-bba0-a1ae3d20eea2

**Comment by ChristophTobler** [comment]
@ndepal Thanks! I'll have a look at it.

**Comment by ChristophTobler** [comment]
@ndepal you are right, it never fused GPS... can you test https://github.com/PX4/ecl/pull/289?

**Comment by ChristophTobler** [comment]
now includes https://github.com/PX4/ecl/pull/289#pullrequestreview-47164255 which has already been tested.
@ndepal Thanks for the testing! Can you also review the PR?

**Comment by ndepal** [comment]
One thing I forgot to mention about the test flight for https://github.com/PX4/ecl/pull/289#pullrequestreview-47164255:

At about 178s I stepped under the quad to cause a range measurement jump. I was hoping for it to reject range and fall back to GPS, thereby keeping its altitude. What I observed was that it climbed significantly, as if it was always using the ranger.

Looking at the log I see that at that time it was actually using GPS (apparently because range measurements were `> 0.7 * max_hagl_for_range_aid`) but as I stepped under the quad it switched to range aid. The switch happens after the HAGL innovations become low again, yet the estimated vehicle height starts dropping while the range measurements are quite stable.
As I step away again, it switches back to GPS as expected but the quad climbs more than 2m as can be seen in the range measurements.

Any ideas why this is happening?

image

**Comment by ChristophTobler** [comment]
Seems to me like it switches to range_aid (because it's below 3.5m) and initializes a range offset because the terrain is delayed. Because of that offset z estimate changes and the quad increases it's altitude. Not yet quite sure why it switches back to GPS so early.

**Comment by ndepal** [comment]
> initializes a range offset because the terrain is delayed
Do you mean that `_hgt_sensor_offset` is computed with the (delayed) terrain estimate? Because that isn't the case as far as I can see. Or am I misunderstanding you?

I think it left range aid mode because of [this line](https://github.com/PX4/ecl/blob/e1274ad28a3f1ad25d56b150ed70bbd66ccecc81/EKF/control.cpp#L884): It switches back when `_hagl_innov = -1.6`, `_hagl_innov_var = 0.073` (approx).

**Comment by ChristophTobler** [comment]
Well, the offset is set here https://github.com/PX4/ecl/blob/master/EKF/control.cpp#L789 and as can be seen in the plot above (distance between range distance and dist_bottom at the switch), there is a wrong offset initialized because the dist_bottom is delayed (normal, because it's a filter). Or what do you think?

>I think it left range aid mode because of this line: It switches back when _hagl_innov = -1.6, _hagl_innov_var = 0.073 (approx).

Yup.

**Comment by ChristophTobler** [comment]
@ndepal FYI: this ecl update is obsolete because of https://github.com/PX4/Firmware/commit/b7a5fd314714580274b5fe3d9b3ba632400abc71. Nevertheless, I think it makes sense if we discuss this issue and hopefully fix it.

**Comment by ndepal** [comment]
>Well, the offset is set here https://github.com/PX4/ecl/blob/master/EKF/control.cpp#L789 and as can be seen in the plot above (distance between range distance and dist_bottom at the switch), there is a wrong offset initialized because the dist_bottom is delayed (normal, because it's a filter).

You're right, my mistake.

Two things:
 1) The range measurements from this sensor (LidarLite v3) are not very noisy. Perhaps the EKF should trust it more, which would reduce the hagl delay.

2) This exact problem is supposed to be prevented by [this line](https://github.com/PX4/ecl/blob/e1274ad28a3f1ad25d56b150ed70bbd66ccecc81/EKF/control.cpp#L884). I don't understand why hagl innovation is so low already at the point of switching to range aid, since the terrain estimate clearly has not yet caught up to the range measurements.

**Comment by ChristophTobler** [comment]
> The range measurements from this sensor (LidarLite v3) are not very noisy. Perhaps the EKF should trust it more, which would reduce the hagl delay.

True.

> This exact problem is supposed to be prevented by this line. I don't understand why hagl innovation is so low already at the point of switching to range aid, since the terrain estimate clearly has not yet caught up to the range measurements.

This 1.0f is rather high, I think. [Here](http://pasted.co/cf379b8f)'s the output of that term (printed above the statement). As you can see it reaches `1.0f` fairly quick and `_terrain_vpos` is still changing `~30cm`. Sometimes even more.
I guess it would make sense to use a hysteresis there as well. Probably around `0.01` if it wasn't using range aid before and `0.1` else. What do you think? With this I can see a better behavior in SITL.

**Comment by ChristophTobler** [comment]
Note: The output is from SITL where I try to reproduce your scenario. Above 5m, then place an object (higher than 1.5m) below the quad. The object's below the quad, once `hagl term` changes (`hagl term = 27.217264`, line 7).

**Comment by ChristophTobler** [comment]
move discussion to https://github.com/PX4/ecl/pull/295

**Comment by ndepal** [comment]
A hysteresis might indeed make sense.
I also think that a hard coded value of `range_aid_innov_gate = 1.0f` might be too high.
How did you come up with 0.1 and 0.01? Could that be a bit too restrictive? Should `range_aid_innov_gate` be a parameter exposed to the user and the hysteresis just uses e.g. `0.1*range_aid_innov_gate`?

**Pull request closed without merging**
