### PR TITLE
WIP: airspeed sanity

### PR DESCRIPTION
**Pull request by sanderux**
Fixes https://github.com/PX4/Firmware/issues/3746
Attempt to failsafe erroneous readings from airspeed sensor

### CODE REVIEW

**Comment by sanderux** [comment]
@AndreasAntener @LorenzMeier still WIP, statics will be params, but is this an approach you both are comfortable with?

**Comment by LorenzMeier** [comment]
What happens in wind here?

**Comment by sanderux** [comment]
It would abort if the wind measured is higher then the transition airspeed. i don't even think it could cope with such a situation. imagine the pitch angle at that moment

**Comment by LorenzMeier** [comment]
@tumbili please review

**Comment by AndreasAntener** [comment]
@sanderux you also had the idea in the beginning to have a minimum transition time. This came up in the airspeed filter discussion again. What about waiting at least until throttle is ramped up (forward transition time)? And no aborting, because it should not be about airspeed failure detection.

**Comment by sanderux** [comment]
minimum transition time would probably work for the transition, but the erroneous airspeed sensor would make autonomous flight unsafe. but that would probably work just as well to avoid the crash i experienced with the malfunctioning airspeed sensor. It does require a good setting for every model though.

**Comment by AndreasAntener** [comment]
We'll have #3863 instead

**Pull request closed without merging**
