### PR TITLE
sensors split rc_update into new standalone module

### PR DESCRIPTION
**Pull request by dagar**
This PR splits the rc update handling (rc_update) out of the sensors module monolith, similar to https://github.com/PX4/Firmware/pull/13073 and https://github.com/PX4/Firmware/pull/12601.

In isolation this change isn't that interesting, although it likely removes a bit of latency in RC updates and has some potential side benefits for truly RC-less systems. The larger goal is to reduce the sensors module complexity and get to the point where it's not a bottleneck for running multiple estimators. By splitting these logical pieces into separate modules they become a bit easier to manage and refactor.

A follow up PR could update this new module to properly use module parameters.

### CODE REVIEW

**Comment by dagar** [comment]
The new module could probably use a better name. Any suggestions?

**Comment by mcsauder** [comment]
> The new module could probably use a better name. Any suggestions?

```
### Description
The rc_update module handles RC channel mapping: read the raw input channels (`input_rc`),
then apply the calibration, map the RC channels to the configured channels & mode switches,
low-pass filter, and then publish as `rc_channels` and `manual_control_setpoint`.
```

Here are a few thoughts to throw at the wall, nothing I am completely in love with either though: RCSignalMapper, RCSignalHandler, RCInputHandler, RCHandler

**Comment by jorge789** [comment]
**Tested on PixRacer V4:**
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:**  https://review.px4.io/plot_app?log=b0dfe561-655a-4c14-8471-8fb52849151c

**Comment by Junkim3DR** [comment]
### Tested on NXP FMUK66 v3

**Modes Tested**
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:**  https://review.px4.io/plot_app?log=ba92644b-8c82-489b-81d9-d70d309d6b79





### Tested on Pixhawk Pro v4

**Modes Tested**
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint activate RTL and see landing behaviour.

**Notes:**
No issues noted, good flight in general.

**Log:**  https://review.px4.io/plot_app?log=d5d2da77-ef1d-41ec-8f70-23ea67cd165d

**Comment by Tony3dr** [comment]
Tested on Pixhawk 4 V5

**Modes Tested**
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**Procedure**
Arm and Takeoff in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint activate RTL vehicle landed smooth and vehicle disarmed.

**Notes:**
No issues noted good flight in general.

**Log:** https://review.px4.io/plot_app?log=4621e90d-6903-46e2-8def-ba8f8d3f06c0&fbclid=IwAR2iF5xcbaaPBK0TnLx42SnC-9EWpwZblnTHSNKJgXm9nf4q36xXL-WsbHI

**Comment by dagar** [comment]
Thanks for the review and testing. This will be easy to rename and refactor as a standalone module.

**Pull request merged**
