### PR TITLE
[DO NOT MERGE] nxphlite-v3:Add HolyBro GPS on I2C 2 using ist8310

### PR DESCRIPTION
**Pull request by davids5**
@igalloway - plase test this with your HW. If it works we will merge it.

### CODE REVIEW

**Comment by Nielesonimusso** [comment]
Tested on hardware revB, ist8310 driver is started correctly

**Comment by davids5** [comment]
@Nielesonimusso - thank you! Were calibrations and rotations correct?

**Comment by Nielesonimusso** [comment]
Haven't payed attention to exact values during tests today, but it was able to calibrate, and at the moments I looked at the heading in QGC it seemed to correspond to the actual heading of the drone. We have performed some position control flights using this driver, which were not a success (main issues are mentioned in the "additional feedback" of the logs, I put a more detailed flight explanation in the ``rddrone_fmuk66`` channel on Slack), but you might be able to see the compass performance from their logs (https://logs.px4.io/plot_app?log=1fc9ab04-ad86-4fe8-941c-d30480fa2a1d and 
https://logs.px4.io/plot_app?log=951f6392-12f2-43f3-941c-649e0f26cf26) 

Between these test runs, we had an issue that at some point the IST8310 did not appear on the I2C bus at all (manually starting the driver indicated that there was no device on the bus), but this was magically solved by a couple of reboots, and I haven't been able to reproduce the error through numerous reboots, either by reset switch, reboot command or battery removal.

**Comment by davids5** [comment]
@dagar - let merge this, if it needs tweaking we can do that later.

**Pull request merged**
