### PR TITLE
Add help to qshell

### PR DESCRIPTION
**Pull request by ericye16**
Fixes issue #5111

### CODE REVIEW

**Comment by julianoes** [comment]
@ericye16: Can you please this on PX4/master and push it again. You'll have to force push using -f to your branch. This will then run the CI checks again. Thanks.

**Comment by ericye16** [comment]
I think you a word ;-P Did you mean rebase? As far as I can tell, this branch is already based on PX4/master...

**Comment by julianoes** [comment]
Ha! Yep rebase :)

**Comment by julianoes** [comment]
Jenkins: test this please

**Comment by ericye16** [comment]
>Fetching upstream changes from https://github.com/PX4/Firmware
>\> git --version # timeout=10
>\> git -c core.askpass=true fetch --tags --progress https://github.com/PX4/Firmware +refs/heads/*:refs/remotes/origin/*
>ERROR: Timeout after 10 minutes
>ERROR: Error cloning remote repo 'origin'
>ERROR: Error cloning remote repo 'origin'

Is the infra down maybe?

**Comment by julianoes** [comment]
Applied via rebase, thanks!

**Pull request closed without merging**
