### PR TITLE
cmake patch depend on previous patch target

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
Weird issue with cmake dependencies to custom command generated files and GNU Make in parallel.

**Comment by davids5** [comment]
@dagar 
some of the <target>_stamps are still in build_ top level directory.
so  ```rm -fr build_px4fmu-v2_default/px4io-v2/NuttX``` does not work. Can this be changed?

**Comment by dagar** [comment]
I think I've got them all now.

**Comment by davids5** [comment]
@dagar - '''rm -fr build_px4fmu-v3_default/px4io-v2/''' works now!

**Pull request merged**
