### PR TITLE
changed mavlink log msgs to guide users how to solve the preflight fail issue

### PR DESCRIPTION
**Pull request by barzanisar**

### CODE REVIEW

**Comment by dagar** [comment]
This is a great idea, but unfortunately exceeds the statustext length.

**Comment by barzanisar** [comment]
Is there a way to break it into two messages? 

Preflight Fail issue is **very very** common and new users like me have no idea what to do in this case. I later found explanation of these checks in (dev guide)[https://dev.px4.io/en/tutorials/pre_flight_checks.html] but this topic is hidden under a completely unrelated section called **Tutorials**. I will discuss with Hamish about it.

**Comment by LorenzMeier** [comment]
Please reword them to fit within 50 characters.

**Comment by hamishwillee** [comment]
> Preflight Fail issue is very very common and new users like me have no idea what to do in this case. I later found explanation of these checks in (dev guide)[https://dev.px4.io/en/tutorials/pre_flight_checks.html] but this topic is hidden under a completely unrelated section called Tutorials. I will discuss with Hamish about it.

Yes, I thought the same thing, which is why I am in the process of moving it into the user guide :-) See https://github.com/PX4/px4_user_guide/pull/210

As an aside, I hope to completely remove that tutorials section in the coming months - everything will be grouped along with relevant related topics. If that is not possible, then they will be "advanced"

**Comment by dagar** [comment]
I agree this is a very common problem and needs a good solution, but I see the use of STATUSTEXT as fundamentally limiting. 

If possible you could try rewording them for now to fit in slightly more information, but I think it's going to be difficult. In some cases you could send more than one line, but QGC critical is only going to show one at a time, and these messages have no guaranteed delivery. There's also absolutely no mechanism for internationalization.

We need to handle more on the ground side either by passing flags rather than text or with something like the event interface (http://discuss.px4.io/t/event-interface/2318). 

On the ground these messages could continue links to the documentation as well as options to go directly to the relevant section (eg sensor calibration).

**Comment by dagar** [comment]
This reminds me of something I discussed with @DonLakeFlyer not too long ago. 
QGC already gives messages prefixed with "PreArm:" special treatment. If we did that here it would provide slightly more space to work with and improve things slightly ground side.

**Comment by TSC21** [comment]
@barzanisar @dagar is this still relevant?

**Pull request closed without merging**
