### PR TITLE
Getting precise landings with a low-range sonar

### PR DESCRIPTION
**Pull request by almaaro**
**Test data / coverage**
In the log below: Terrain altitude offset testing. Green dots for start of the landing, orange for landing abort and blue for landing.

1. The barometer altitude has drifted quite a bit, the home position altitude was -0.5m when taking off (drift created artificially with https://github.com/almaaro/Firmware/tree/qnh-change-mid-flight). The plane has passed the LAND point by over FW_LND_MAX_MV (set to 5 meters) without starting to flare (in this case FW_LND_REQ_TERR was true). Setting terrain altitude offset so that the global position altitude for the landing point on the next attempt will be 0.5 *FW_LND_FLALT below our current altitude (assuming that the flare altitude is set so that the rangefinder would get a reading if we are under 0.5 *FW_LND_FLALT from the ground). What do you think, is this a good setpoint for the next try or should it just be set to our current altitude?
1. Now there is a _land_terrain_alt_offset added to the waypoint altitudes, in this case ~ -1.2m.
1. Second landing attempt, this time we can set the _land_terrain_alt_offset very precisely as we get the terrain altitude valid (but are too high -> the _land_touchdown_point_shift will exceed FW_LND_MAX_MV).
1. _land_terrain_alt_offset is about -4m.
1. Safe landing (the glideslope altitude sp didn't have a drop even with the terrain altitude being a little lower than on the 2. attempt) . FW_LND_FLALT was 1 meter.
rangefinder-bump

**Describe problem solved by the proposed pull request**
It is somewhat unreliable to get **precise** and **smooth landings at the same time** with a low (~1m) range sonar. Taking an Ardupilot-style approach: Preventing steep descends near to the ground and in case of an aborted landing, saving the terrain altitude for another attempt.

**Describe your preferred solution**
**New parameters:**

1. FW_LND_REQ_TERR: If set to true, don't flare before having a valid terrain altitude. Prevents the plane from flaring too high, but can also lead to an unflared landing.
1. FW_LND_MAX_MV: The maximum distance the landing point can be moved further from the original position.
1. FW_LND_MV_ALT: The maximum altitude under which any glideslope position adjustments can take place.
1. FW_LND_GS_TOL: The maximum proportional error relative to the glideslope altitude setpoint. If the glideslope altitude setpoint is under FW_LND_MV_ALT and the vehicle's altitude is higher than (1+FW_LND_GS_TOL) * altitude_setpoint, the landing point will be moved further away to prevent the plane from diving to catch the slope. 

**The ideas**

1. Rangefinder bump handling: What to do when the terrain altitude is higher or lower than we thought. This introduces the concept of **_land_touchdown_point_shift** variable. Basically, tells how much the landing point will be moved further away from the original position. If it is over FW_LND_MAX_MV, the landing will be aborted. Setting FW_LND_MAX_MV to a high value, such as 1000, means that the landing will be practically never aborted.

```
**_land_touchdown_point_shift** is calculated when the terrain altitude becomes valid. Here is an example how it is calculated: We are following the landing slope with no valid terrain altitude, and the global position altitude setpoint for the landing point is 0. The terrain altitude becomes valid and now the new altitude setpoint for the landing point altitude is -2 -> need to descent 2 meters to catch the landing slope that just jumped 2 meters down. Because we don't want to descent 2 meters this close to the ground, we just move the landing point further away so that we are at the correct altitude in the slope again. This only happens if we are too high relative to the landing slope; if we are lower than we should, just climb back to the correct altitude.
```

```
In the picture below: Black is the curve that we should be following. After the terrain altitude becomes valid, our altitude relative to the ground will change. If the old global position altitude setpoint was within green area, do nothing. If it was in the orange area, move the landing slope so that the **global position altitude setpoint** **will not change**.
Flaring can only occur when the relative altitude to the landing altitude setpoint is under FW_LND_FLALT and we are closer than (_flare_length - _land_touchdown_point_shift) to the original landing setpoint. The horizontal limit means that the flaring can not start if the relative altitude setpoint is under the flare altitude after the rangefinder bump, but we are still too far away from the landing point.
For example in the red curve going through point B: It represents the actual altitude from the terrain altitude. Before B, we think that we are actually following the black curve. We even started flaring, because FW_LND_REQ_TERR was set to false. At B, the terrain altitude jumps down, which means that the global position altitude setpoint will jump down just as much. As the new altitude setpoint follows the black burve, our old altitude setpoint was actually in the orange zone. This means that we move the landing point further so that we jump back to the glideslope from flaring without having to dive. The blue line going throuch point A demostrates the same effect.
![rangefinder_bump_limits](https://user-images.githubusercontent.com/5569656/50423769-7c7e9b00-0862-11e9-8d81-257aef2e7a73.jpg)
```

1. Terrain altitude offsetting: After an aborted landing, it would not be very useful if we did the next approach from the same altitude. The difference between the landing point altitude setpoint and the actual terrain altitude will be stored in **_land_terrain_alt_offset** which is added to all upcoming waypoints. 

1. Changes to landingslope library, the biggest change would be to indicate that the landing waypoint has been passed by setting wp_distance to its opposite value in the fw position controller (no need to use the bearings anymore).
1. The flare pitch control will be handled by tecs if the terrain altitude is valid, otherwise by the fw position controller.

**Other considerations**

* Unfortunately I don't have any significant test data to demonstrate the touchdown point displacement. Although, I have done over 20 landings with this setup and never had a crash.
* This is a long and complex pull request, please ask if something is unclear. 
* Landing aborts should probably be disabled under some conditions, such as with low battery emergency landings or some RTLs.

Best regards, 
almaaro

### CODE REVIEW

**Comment by dagar** [comment]
@antiheavy @ryanAA

**Comment by Antiheavy** [comment]
Very interesting!  I think it would be great if we could improve fixed wing landing accuracy.

**Comment by ryanjAA** [comment]
This looks great and will be fun to test for some comparisons. Definitely need to improve and make autoland more robust.

**Comment by TSC21** [comment]
@almaaro this needs to be rebased as well. Thank you!

**Comment by ryanjAA** [comment]
What’s the status of this?

Is there any benefit to utilizing this with a much higher range lidar (50-100m) or can we assume that terrain altitude would simply be valid at the higher altitude and negate all the work this does?

**Comment by dagar** [comment]
Can you re-open this with a fresh pull request? The original repo disappeared ("unknown repository") and it seems to be confusing the CI system.

image

**Comment by ryanjAA** [comment]
@almaaro is this still of interest to get in?

**Comment by almaaro** [comment]
Not really. This project has involved so many features already (including many tecs changes) that I don't think I have the time and motivation to make the changes into separate mergeable branches. Furthermore, I'm not sure if this branch is even up to date.

Nevertheless, my own tests have showed very nice autolands with ~1m winspan planes with only a cheap sonar in use. If anybody else is still interested in fine-tuning the autoland system, I'll be glad to help. 

Finally, since there are very cheap and lightweight lidars on the market, I don't think that sonars are not worth the effort any more.

**Pull request closed without merging**
