### PR TITLE
Fix att_estimator_q slowly reacting to declination change #3270

### PR DESCRIPTION
**Pull request by muharred**
This fixes the slow reaction and stops the estimator from calculating the false gyro bias by applying the declination instantly when the parameter changes or GPS-calculated declination greatly differs.
Screenshot of the same scenario as described in the issue:
yawvsmag

Tested on the table, but similar fix was tested in a different fork in simulator.
I'm not sure if arbitrary chosen "ignorable" change of declination by 0.0001f is any good. Seemed ok in simulator. I've added this to avoid calls to expensive decl_rotation.from_yaw (sin and cos calls) and quaternion multiplication on each GPS declination update.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Cool! We'll cross test this.

**Comment by LorenzMeier** [comment]
@tumbili I need you to test and get this in today. Shortest task first!

**Comment by tumbili** [comment]
@muharred I tested this also and it seems to be ok. Can you fix code style (/Tools/fix_code_style.sh) so the the checks pass?

**Comment by muharred** [comment]
@tumbili Which modules need to be fixed? The script changes some of the mathlib files that I didn't change.

**Comment by tumbili** [comment]
@muharred It's just the attitude estimator q file.

**Comment by tumbili** [comment]
Closed in favour of #3323

**Pull request closed without merging**
