### PR TITLE
sensors remove airspeed negative check

### PR DESCRIPTION
**Pull request by dagar**
- closes https://github.com/PX4/Firmware/issues/9567

Need to verify the FW & VTOL controllers can handle this during ground testing.

### CODE REVIEW

**Comment by Antiheavy** [comment]
Negative airspeed shows through in QGC.  What sort of testing can we do to verify there aren't any negative impacts to the rest of the system?   @dagar @kjkinney

image

**Comment by Antiheavy** [comment]
Pre-flight checks also seem to work when airspeed is a large negative value:
image

**Comment by dagar** [comment]
What about shifting the differential pressure offset enough so arm with a smaller negative airspeed. See anything weird?

I'll review the controllers as well.

**Comment by dagar** [comment]
I added a simple IAS > 0 check to the FW & VTOL controllers.

**Comment by Antiheavy** [comment]
We have about 10 fixed wing flights or so on this PR so far.  no noticeable issues from the user perspective.

**Comment by dagar** [comment]
Thanks for testing.

**Pull request merged**
