### PR TITLE
actuator controls update

### PR DESCRIPTION
**Pull request by dagar**
https://dev.px4.io/en/concept/mixing.html

* remove parachute from end of gimbal mixer
* add failsafe actuator_controls
* add payload actuator_controls X 2

Questions

* how would a user be expected to use DO_SET_SERVO?https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_SERVO
* should we create a subscription helper for the output modules

### CODE REVIEW

**Comment by dagar** [comment]
Likely needs a bit more discussion, but the first goal was getting the parachute out of the gimbal actuator controls.

**Comment by nskjoung** [comment]
@dagar do you have any plan parachute action in fail safe (fixedwing)  in place of actuator_controls_2(7).?
i have experience vmount module working good multicopter airframe, but it was wrong act with vtol airframe.

**Comment by AlexisTM** [comment]
Note that this PR increases the number of actuator controls groups, so we have to add them to the mavlink receiver (to be handled from the offboard mode)

https://github.com/PX4/Firmware/blob/2250946eaaecd61a3a88e802b65537ede540f701/src/modules/mavlink/mavlink_receiver.cpp#L1111-L1164

**Comment by dayjaby** [comment]
Is this still up to date? Can we get this merged?

**Comment by LorenzMeier** [comment]
I'm closing this as stale.

**Pull request closed without merging**
