### PR TITLE
FlightTaskAuto: set reference to 0 if auto is requested but no global…

### PR DESCRIPTION
**Pull request by Stifael**
#issue https://github.com/PX4/Firmware/pull/9895#issuecomment-408144002

@TSC21 
do you mind to test this branch. I tested it in simulation. Takeoff and land should be possible without global position. 

However, I noticed some inconsistency with reference altitude and lat/lon. For that I will open a new issue

### CODE REVIEW

**Comment by TSC21** [comment]
@Stifael let's take as an example of LPE does: https://github.com/PX4/Firmware/blob/master/src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp#L336-L347.
Why not add a couple of parameters to set the reference latitude and longitude system wise so it can be used, not only here, but also on EKF2 (and replace the LPE parameters as well with this)? These parameters could be set on the estimator side immediately on system boot and while we know that we won't be having GPS data being fused on the estimators.

**Comment by dagar** [comment]
> Prefer if we actually just support local frame navigation in missions.

I've looked at doing this in navigator (operating frame agnostic vs exclusively global or local) and it's not actually that difficult, but there's quite a lot of code to work through. If anyone is interested in pursuing it we could get the details organized in an issue and find a way to work towards it incrementally.

**Comment by mhkabir** [comment]
I'd argue that we don't even have to be frame agnostic, just operating navigator in local frame would probably work, and global missions could be projected to local frame.
I'm happy to assist here, as this is tightly coupled with my ongoing work.

**Comment by TSC21** [comment]
@dagar I agree that would be the best approach. But I wonder how much work (and time) will it actually take before we can bring that approach to upstream and unblock other PRs.

**Comment by Stifael** [comment]
This frame discussion was raised already several times in  the past, and there were even attempts made to shift the navigator to local frame entirely. However, as @TSC21 pointed out, the bottleneck are not the ideas, but rather the amount of work and the time required to make that shift. 

@TSC21 did you have time to test this branch?

**Comment by dagar** [comment]
> @dagar I agree that would be the best approach. But I wonder how much work (and time) will it actually take before we can bring that approach to upstream and unblock other PRs.

Probably quite a long time if we never start. :smirk:

**Comment by TSC21** [comment]
> @TSC21 did you have time to test this branch?

Still haven't, sorry. Will do ASAP.

**Comment by TSC21** [comment]
@Stifael can you rebase?

**Comment by Stifael** [comment]
rebased: needs approval again

**Pull request merged**
