### PR TITLE
 Merge FMUv3 into FMUv2

### PR DESCRIPTION
**Pull request by dagar**
This is a fix for the pixhawk mini which needs to use the px4fmu-v2_default binary due to lacking bootloader versioning.

FMUv3 was a superset of FMUv2 that used the full 2MB flash and added runtime version detection to handle various board differences in the pixhawk 2 cube and pixhawk mini. 

This PR combines FMUv3 into FMUv2 with the only difference being the linker script used by FMUv3 and PX4 module list.

### CODE REVIEW

**Comment by dagar** [comment]
I've done some simple bench testing with an original pixhawk (px4fmu-v2) and pixhawk cube 2.1 (px4fmu-v3). The version is correctly detected and all sensors are present with correct external detection.

@PX4TestFlights @LorenzMeier @bkueng could someone thoroughly checkout a pixhawk mini with this branch? Flash px4fmu-v2, reset all params, and recalibrate. From that ulog we can verify everything.

**Comment by r0gelion** [comment]
@dagar 

I'm getting [this error](http://pasted.co/48540b8b) when trying to compile px4fmu-v2

running cmake 3.7.1 in mac os sierra 10.12.6

**Comment by dagar** [comment]
Removed ground vehicle controllers from px4fmu-v2 to make room.

**Comment by santiago3dr** [comment]
pixhawk mini bench test after flash and full reset; all sensor calibrations went through without errors
https://logs.px4.io/plot_app?log=728eb1e2-7e1c-4f2b-9f34-6c97ef2f579e

**Comment by santiago3dr** [comment]
ran full setup on a different pixhawk mini
calibrations:
https://logs.px4.io/plot_app?log=8511764b-6b29-49c0-8b2e-62312963789d
indoor flight test:
https://logs.px4.io/plot_app?log=074589a2-6696-49c8-9287-114ffbced108
full outdoor flight test:
https://logs.px4.io/plot_app?log=ac5c287a-d7d6-46da-8d85-bc7ef268128c

no errors, flew well; all tested modes worked as expected

**Comment by hamishwillee** [comment]
@dagar 

> Removed ground vehicle controllers from px4fmu-v2 to make room.

Saw above in email. Does that mean you can't do rover type vehicle on Pixhawk etc any more? Do we need to communicate somehow to users either how they add them back (ideally) or what FMU versions will work?

**Comment by dagar** [comment]
@hamishwillee good catch, but I backed that out after freeing up some extra space here. https://github.com/PX4/Firmware/pull/8344

**Pull request merged**
