### PR TITLE
WIP: Added circle mode for multicopters

### PR DESCRIPTION
**Pull request by tumbili**
- [x] extract circle radius and center from vehicle command
- [ ] add QGC support
- [ ] testing

### CODE REVIEW

**Comment by tumbili** [comment]
In order to test this just use position control mode. As soon as you switch into it the origin of the circle will be set 3 m in front of the drone (in the direction it is currently facing). If you don't touch the roll/ pitch sticks the drone will just keep position facing the origin of the circle.
Use the roll stick to move along the circle. Use the pitch stick to make the radius of the circle bigger. The minimum radius is set to three meters.
Altitude control is the same as in position control.

**Comment by mhkabir** [comment]
@tumbili I gave this a quick test in Gazebo SITL. (```commander takeoff```, followed by switching to position control). The vehicle starts circling, but also starts descending, and eventually crashes. Couldn't see anything immediately wrong in the diff.

Any ideas?

**Comment by tumbili** [comment]
@mhkabir Hm, are you using a joystick for control? If you do nothing with the sticks it should do nothing. I tested this maybe 20 times. Anyway, I have to integrate it properly, after that you can try again.

**Comment by mhkabir** [comment]
@tumbili I didn't have any controller connected at all.

**Comment by tumbili** [comment]
@mhkabir Ok, I think I know then what happened. The system was using manual control setpoints which were not updated. Probably all the values were zero which would explain that the vehicle dropped down and circled in one direction.

**Comment by mhkabir** [comment]
Yup. That was my conclusion as well. We should protect against this case
though.

**Comment by tumbili** [comment]
@LorenzMeier This now needs a proper interface on the QGC side. I added a vehicle command for position control submode. If the submode is set to CIRCLE then also the circle radius and the coordinates of the center of the circle should be given.

**Comment by tumbili** [comment]
@LorenzMeier This goes together with https://github.com/mavlink/mavlink/pull/574

**Comment by LorenzMeier** [comment]
@tumbili MAVLink update is through. Can you do a rebase? I can then start to look at the QGC side implementation.

**Comment by tumbili** [comment]
@LorenzMeier Done!

**Comment by MHageH** [comment]
@tumbili @LorenzMeier  Can this be implemented in the [C UART interface](https://github.com/mavlink/c_uart_interface_example) ? Since it uses an [older](https://github.com/mavlink/c_library_v1/tree/7d0aa0205ef8bd13bf855b21d3ebe054dc9109ef) version of MAVLink.

**Comment by tumbili** [comment]
Jenkins test this please!

**Comment by tumbili** [comment]
@julianoes @kd0aij If you feel bored some time you could give this a test :-)

**Comment by julianoes** [comment]
Is it supported in QGC? Any instructions how to use it?

**Comment by tumbili** [comment]
@julianoes Yes, the newest QGC should support it. At the moment, it's still very basic such that if you enter orbit mode the vehicle will set the center of the circle some distance in front of it  and keep it's current altitude. You can then use the roll / pitch stick to move along the circle and change the radius of the circle. The vehicle will always try to face the center of the circle. You could give it a try in SITL first.

**Comment by kd0aij** [comment]
@tumbili I should be able to flight test this sometime this week. Sounds very useful for a camera ship.

**Comment by kd0aij** [comment]
@tumbili I get "cmdid 4001 not supported" in latest daily QGC when I try to select orbit mode in SITL

**Comment by dogmaphobic** [comment]
> I get "cmdid 4001 not supported" in latest daily QGC when I try to select orbit mode in SITL

I don't know where that is coming from either but the command was sent through and you should be able to use the sticks to *circle*.

**Comment by kd0aij** [comment]
Works as described in SITL, but I have a few questions before actual flight testing:
1. Is this the first and only "sub-mode" we have?
2. Is there a way to enter "orbit" mode without using a groundstation?
3. How do you terminate orbit mode?

**Comment by dogmaphobic** [comment]
> Works as described in SITL, but I have a few questions before actual flight testing:

This question should be brought to the QGC side as it's all mostly a UI/UX question. I find all the *modes* in QGC utterly confusing and there should be some discussion about how to go about making this simple for users. Right now, what I do is to set the mode to "Position" (or some such) to get out of orbit (pun intended) 8P

**Comment by kd0aij** [comment]
I don't think this is a QGC-only question unless we completely abandon RC control :)
But perhaps this is the first flight mode which is intentionally inaccessible via RC control?

**Comment by kd0aij** [comment]
@tumbili I tried bench testing this on my aeroquad, but the "orbit" option isn't available in QGC till after one uses QGC to command "takeoff" (not sure whether that's intended), And after I do that the response to selecting orbit is "4001 command not supported"
Also, do you have any answers for these questions? https://github.com/PX4/Firmware/pull/4792#issuecomment-235349728

**Comment by kd0aij** [comment]
@tumbili I flew this branch yesterday to see whether POSCTL would be good enough for testing (not sure how to get into orbit mode yet). Too twitchy using INAV, LPE seemed not to work at all, but EKF2 worked very well. ALTCTL seemed good with all 3 estimators.

**Comment by tumbili** [comment]
@kd0aij Thank you for the test flights! I'm not sure why it didn't let you enter orbit mode, seemed to work in SITL. Would be cool to see what's up with the other estimators and why the performance is not good.
At the moment the concept of submodes for POSCTRL is implemented as follows:
1) Per default if you enter into POSCTRL via RC or QGC you are going to get standard position control.
2) You should be able to use QGC to switch between submodes, this is why the mavlink command has both orbit and standard POSCTRL options.
3) At the moment RC only supports activating standard POSCTRL. Additionally, if you entered orbit mode via QGC and after that flick in and out of POSCTRL (via RC or QGC) then you are going to be in standard POSCTRL again.

**Comment by tumbili** [comment]
Rebased on master.

**Comment by kd0aij** [comment]
The log doesn't show any problems with LPE: http://logs.uaventure.com/view/zFyciwJwRmPazfpkDbcYdU
I must have been confused when I thought it wasn't responding properly to stick input.

I'll try again on the bench to get the aeroquad into orbit mode; maybe the error message is wrong?
Does the "takeoff" command switch to ALTCTL? What is the interaction with RC control; is the flight mode set by RC ignored when you send commands via QGC?

**Comment by kd0aij** [comment]
wasn't it once possible to change eph_min and epv_min in commander via parameter?

**Comment by kd0aij** [comment]
even with fake gps, it refuses to enter POSCTL on the bench with EKF2. Only feedback is "posctl rejected" in QGC, none at all on the console.

**Comment by kd0aij** [comment]
fake GPS worked with INAV, but not with LPE either. Problem appears to be that home isn't set with fake GPS and LPE/EKF2 (or else is't set incorrectly and there's no feedback).
I think "verbosity" has been prematurely (and drastically) reduced and that is negatively affecting the efficiency of testing.

I still get the "command rejected" message when I select "orbit" mode from QGC. Is it worth looking at the log to see whether that is a lie?

**Comment by dagar** [comment]
What's the status of this? There was some interest in gitter.

**Comment by dagar** [comment]
@kd0aij would you be interested in picking this up? It likely won't rebase cleanly, but manually copying over the mc_pos_control changes shouldn't be too bad.

**Comment by kd0aij** [comment]
@dagar I'm not inclined to put any more effort into this when my questions go unanswered.

**Comment by kd0aij** [comment]
I'm still curious as to how one is supposed to use modes like this though. Special RC transmitter with QGC and a touchscreen too?

**Comment by dagar** [comment]
Fair enough. If you wanted to pick it up I'll help answering any questions as well as testing and review.
I hate seeing nearly working code wasted. Especially something like this that users regularly ask about.

**Comment by dagar** [comment]
It's a submode of position control. With the code as is you'd need to send a command, which could be an onscreen button in QGC. It wouldn't be hard to also make it accessible from RC switches.

**Comment by tumbili** [comment]
@kd0aij @dagar I think best would be to copy the functionality and put it into latest master. There has been a rewrite of the position controller so I'm not sure how good a rebase will come out. Let me know if you need help or if there's something missing.

**Comment by dagar** [comment]
Continued in #6306, but will likely need to be rebased yet again. Let's keep the original pr-circleMode branch around until circle mode finally makes it in.

**Pull request closed without merging**
