### PR TITLE
Work on px4io firmware building.

### PR DESCRIPTION
**Pull request by jgoppert**
I just renamed the branch on PR #2842 for my own sanity.

I also rebased this on cmake-2 so it is a simple patch.

This is the compile flag diff we need to analyze to fix the linking.

```cmake
--- ms5611_build_cmake  2015-09-12 14:40:34.753689277 -0400
+++ ../Firmware/ms5611_build_orig   2015-09-12 14:40:39.901689126 -0400
@@ -1,48 +1,43 @@
 arm-none-eabi-g++
+   -MD
    -c
    -fno-exceptions
    -fno-rtti
    -std=gnu++0x
    -fno-threadsafe-statics
    -D__CUSTOM_FILE_IO__
    -Os
+   -g3
    -fno-strict-aliasing
    -fno-strength-reduce
    -fomit-frame-pointer
    -funsafe-math-optimizations
    -fno-builtin-printf
    -ffunction-sections
    -fdata-sections
    -mcpu=cortex-m4
    -mthumb
    -march=armv7e-m
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard
    -DCONFIG_ARCH_BOARD_PX4FMU_V2
    -D__PX4_NUTTX
    -DCONFIG_WCHAR_BUILTIN
    -Isrc/
-   -Ibuild_px4fmu-v2_default
-   -Ibuild_px4fmu-v2_default/src
    -Isrc/modules/
    -Isrc/include/
    -Isrc/lib/
    -Isrc/platforms/
+   -IBuild/versioning/
    -Isrc/drivers/boards/px4fmu-v2
-   -Isrc/modules/px4_messages
-   -Imavlink/include/mavlink
    -Isrc/lib/eigen/
    -Inuttx-export/include
    -Inuttx-export/include/cxx
    -Inuttx-export/arch/chip
    -Inuttx-export/arch/common
    -DPX4_MAIN=ms5611_app_main
    -fvisibility=hidden
    -include src/include/visibility.h
-   -nodefaultlibs
-   -nostdlib
    src/drivers/ms5611/ms5611_nuttx.cpp
    -o
    ms5611_nuttx.cpp.o
```

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Could you rebase this one? This would also trigger a new Travis run, which I now have much more confidence in given we have two OS going for us already.

**Comment by jgoppert** [comment]
Ok, just rebased, should be good.

**Comment by davids5** [comment]
@jgoppert: @LorenzMeier asked me to look into the pio build issue. 

I am on Centos 7. 

Is there a list of packages and versions needed and a setup guide for the new build structure?

What branch should I use?

Thank you,

David

**Comment by jgoppert** [comment]
@davids5 

branch: https://github.com/jgoppert/Firmware/blob/cmake-io

Currently cmake 2.8 and cmake 3.2 are being tested using the continuous integration. So you should use one of those if possible, anything > 2.8 should work. Outside of that, the makefile interfaces to cmake so that all of the familiar commands work, such as make px4fmu-v2_default.

To build the io firmware in addition to the regular firmware, you have to uncomment this line:
https://github.com/jgoppert/Firmware/blob/cmake-io/CMakeLists.txt#L281

and type
```bash
 make px4fmu-v2_default
```

The io board is specifically listed in the config file here:
https://github.com/jgoppert/Firmware/blob/cmake-io/cmake/configs/nuttx_px4fmu-v2_default.cmake#L168

**Comment by jgoppert** [comment]
Thanks to @davids5  we have this building now, but we might have found some weak functions that weren't getting called in the original build and it might be an upstream Nuttx bug.

**Comment by jgoppert** [comment]
The io firmware is building, but it isn't being copied to the ROMFS yet to be included in the firmware image. That part should be easy.

**Pull request merged**
