### PR TITLE
auav-x21:Delete PX4_I2C_BUS_ONBOARD

### PR DESCRIPTION
**Pull request by davids5**
Continuation of https://github.com/PX4/Firmware/pull/7487

I removed the onboard definition. @tubeme Please test this.

### CODE REVIEW

**Comment by tubeme** [comment]
@mhkabir @davids5 Sorry for the request, can you make me a binary for testing?

**Comment by davids5** [comment]
[auav-x21_default e8e34004a05c578d10b025d812d9151ffe90b132 ](https://github.com/PX4/Firmware/files/1109120/firmware_nuttx.zip)

**Comment by tubeme** [comment]
Thank you very much @mhkabir @davids5 @LorenzMeier 

RESOLVED :) Everything works perfect. The external mag is now at "No Rotation"(not "Internal Mag"). We were able to change the  CAL_MAG0_ROT to 180 yaw and back to 0 and it was correct. The internal compass is correct as well.

P.S. @davids5 Sorry but just want to understand what happened.

By deleting the 
#define PX4_I2C_BUS_ONBOARD   1
You disabled the I2C2 bus??
If I want to enable both I2C1 and I2C2 buses do I have to change the line to:
#define PX4_I2C_BUS_ONBOARD   2

Is the I2C2 refered as Internal I2C?

Thanks again.

**Comment by mhkabir** [comment]
I don't have the schematics, but from the board config, I see that there is only 1 physical bus on the STM32 which is routed out to the connectors. I2C1 and I2C2 are just the connectors - that is irrelevant here. Some board have different physical buses routed to different I2C connectors, which is why we define `PX4_I2C_BUS_ONBOARD` ,`PX4_I2C_BUS_EXTERNAL`, etc. 

For the X2.1, I think that I2C1 and I2C2 connectors are just bridged. Everything should work on both ports.

**Comment by davids5** [comment]
>For the X2.1, I think that I2C1 and I2C2 connectors are just bridged. Everything should work on both ports.

@mhkabir The short answer is: No they are not. The AUAV 2.1 HW only bring's out 1 i2c port I2C1 - I2C2 is not enabled on the HW config. 

@tubeme - no. 

The AUAV X2.1 not FMUv2 compatible at the HW level. 

FMUv2 HW has 2 i2c buses I2C1  and I2C2 .  One is internal, the other is external.

AUAV X2.1 only has one and it is external.

There reason the V2 FW "Ran" was because the init of I2C2 failed. So you only get one device instance of the MAG. But the mistake I made was to assigning the Internal bus to the External bus.  So the init of was done 2 time on a working bus. (Boy that seems dumb now that I say it out loud)  That gave you 2 instance of the MAG. My Bad! At the time I did not consider un-defining it. Because I thought the build would fail like it does when the external is undefined.  I am sorry for the problem it caused.

**Comment by mhkabir** [comment]
Ah thanks for the clarification. Any specific reason why we don't enable I2C2?

**Pull request merged**
