### PR TITLE
sitl_gazebo: update submodule

### PR DESCRIPTION
**Pull request by julianoes**
This should fix the regression where the mag values were not properly initialized and caused EKF2 to stop in CI.

### CODE REVIEW

**Comment by julianoes** [comment]
CI passed once, force pushing.

**Comment by julianoes** [comment]
CI passed twice, force pushing...

**Comment by julianoes** [comment]
@dagar Fingers crossed, I think this is fixed.

**Comment by dagar** [comment]
Looks good, I'm going to grind the Jenkins build a bit.

**Pull request merged**
