### PR TITLE
ROS launch file cleanup

### PR DESCRIPTION
**Pull request by lamping7**
Most of this was discussed in https://github.com/PX4/Firmware/pull/8817

I picked xmllint as a formatter to make these look uniform (where `$XMLLINT_INDENT="    "`, 4 spaces). I dug through the dev guide and didn't find any references to the launch files I removed. I also grep'ed the Firmware repo directory and didn't see any references there either. Some of this will introduce updates to the dev guide (e.g. the removal of `headless`), which will be made if this looks good.

Some background, copied from the previous discussion:

- https://github.com/PX4/Firmware/blob/master/launch/mavros.launch isn't necessary. The dev guide docs point to the use of mavros's px4.launch. This removes having to maintain this here and simplifies the other launch files (no yaml config arguments -- which are on the mavros side anyway).
- Remove the Gazebo headless argument. It doesn't do anything. See ros-simulation/gazebo_ros_pkgs#491 and https://bitbucket.org/osrf/gazebo_tutorials/pull-requests/379/rename-headless-parameter-to-recording/diff#chg-ros_roslaunch/tutorial.md
- Vehicle and world specific launch files are not necessary. That's what the arguments are for. The others that I'd like to remove are old and depreciated.

### CODE REVIEW

**Comment by lamping7** [comment]
@dagar this tested good in CI covering the changes to the .test files used there, mavros_posix_sitl.launch, and posix_sitl.launch. I tested the multi_uav launch file which covers single_vehicle_spawn as well.

**Comment by dagar** [comment]
Looks good to me, but let's run it by a few people to make sure we don't lose anything worth keeping.

**Comment by dagar** [comment]
@jgoppert @TSC21 @arwagoner @JonasVautherin @AndreasAntener @RomanBapst 

Any objection to this big cleanup of the launch directory? Speak now or forever hold your peace.

**Comment by lamping7** [comment]
Sounds good. After review I'll squash it before merging.

**Comment by lamping7** [comment]
To be clear about possible side effects with these changes -- If users have incorporated posix_sitl.launch or mavros_posix_launch.launch into their launch files previously, they will be met with errors if they're passing the `headless` or `ns` args to it. But as stated above, `headless` has no function (I assume it will eventually be dropped from gazebo_ros), and the `ns` arg in posix_sitl.launch did absolutely nothing (a little misleading), and in mavros_posix_launch.launch it only set a ns for the mavros node. 

He's an example of the error (which should be pretty straightforward for a user to figure out if this effects them):
```
unused args [ns, headless] for include of [/home/tony/px4/Firmware/launch/posix_sitl.launch]
The traceback for the exception was written to the log file
```

**Comment by LorenzMeier** [comment]
@jgoppert @TSC21 @arwagoner @JonasVautherin @AndreasAntener @RomanBapst Could you please review? Thanks!

**Pull request merged**
