### PR TITLE
FW pos control: Perform climbout if user requests more than 85% pitch up

### PR DESCRIPTION
**Pull request by LorenzMeier**
@tumbili Please add this to your test. It might solve the manual flight issues in the climb out modes and also might help a bunch with takeoff already.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Also note this: TECS params are documented here:
http://www.pixhawk.org/firmware/parameters#fixed_wing_tecs

Look for FW_T_SPDWEIGHT and play with it on your next flight to improve the altitude tracking.

**Comment by tumbili** [comment]
@LorenzMeier This is the log http://dash.oznet.ch/view/ghMdD6TXJBA83Hx5TayLrF
I will take some time tomorrow to analyse this through. The climbout option seems to work but we have to talk about the situation when it stalls. There was a lot of wind which allowed me to also test POSCTRL.

**Comment by LorenzMeier** [comment]
TECS does ensure to not stall. Please share logs / plots where you think its stalling.

**Comment by tumbili** [comment]
@LorenzMeier Is the desired airspeed from TECS logged?

**Comment by LorenzMeier** [comment]
AsSP

**Pull request merged**
