### PR TITLE
Camera Trigger fixes

### PR DESCRIPTION
**Pull request by mhkabir**
_This fixes everything_. (see https://github.com/PX4/Firmware/issues/6961)

image

@birchera Please cross-test with Seagull MAP2 and Sony Camera. I will too, once I have the hardware.

### CODE REVIEW

**Comment by mhkabir** [comment]
The last commit also fixes the `pwm info` command, such that it doesn't show output groups which it _does not control._

**Comment by mhkabir** [comment]
@PX4TestFlights We will need a flight test with this branch. Please test with Pixracer, because this makes changes to the way FMU handles actuator outputs. We would need testing to confirm that the first 4 channels work well (so a F450-type platform would be best).

**Comment by mhkabir** [comment]
Current status : Works on all the hardware which I tested. I also added simple PWM mode for things like IR triggers and servo-pushing-shutter-button type triggers.

TODOs : 
1. Figure out why the HRT callback stops firing sometimes. (Also restarts by itself)
2. Clean up power control options, move it into CameraInterface.
3. Simplify on/off and keepalive calls. Way too cruddy and hard to read at the moment.
4. Move `TRIG_PIN` handling into CameraInterface.

**Comment by mhkabir** [comment]
So I finally tracked down why it locks up. Turns out that the HRT engage/disengage callback can fire in between two PWM pulses. You can see it in the logic analyzer traces here : 

Bad (trigger engages and disengages between two pulses): 
image

Good (engage and pulse generation is aligned) : 
image

**Fixes :** 
1. Just increase (and enforce a lower bound) on the activation time (in PWM mode) so that it can't disengage in-between two pulses even in the worst case.
OR
2. Sync the disengage call with an interrupt from the PWM timer so that it doesn't disengage till a new pulse is generated.

**Comment by LorenzMeier** [comment]
Option 1. sounds good. What would the lower bound be?

**Comment by mhkabir** [comment]
20 ms is sufficient to make sure it can't disengage in-between, but turns out that the MAP2 isn't exactly the highest-quality hardware, and it often misses trigger events if they're only 1 pulse long. So it might require some empirical tuning to get a reliable bound. I will test and lock it in tomorrow.

**Comment by LorenzMeier** [comment]
Good to go?

**Comment by mhkabir** [comment]
Yep.

**Pull request merged**
