### PR TITLE
cmake improve submodule handling and nuttx copy

### PR DESCRIPTION
**Pull request by dagar**
Unfortunately because of the way git submodules work I think we'll have to update them every single make. There's no easy way for cmake to detect that a submodule needs to be updated.

### CODE REVIEW

**Comment by dagar** [comment]
Actually, let me try one more thing...

**Comment by dagar** [comment]
Nevermind, running `git submodule summary` and then only updating if there's a change is basically the same as just running git submodule update (without --init or --force).

Please review.

**Comment by LorenzMeier** [comment]
Looking good, should we go ahead and merge?

**Comment by dagar** [comment]
Yes, please merge.
If you come across yet another way submodules are screwing us please let me know.

**Pull request merged**
