### PR TITLE
Add SITL target for simulating catapult / handlaunching fixed wing

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Describe problem solved by this pull request**
This PR implements a SITL target for a `plane_catapult` model which includes a catapult plugin implemented in https://github.com/PX4/sitl_gazebo/pull/393

This simulates fixed wing being launched by a catapult or being hand launched. This is required to test the takeoff mode of the fixed wing, which has been largely untested in simulation until now. 

**Describe your solution**
The plugin ca be launched with the following command
```
make px4_sitl gazebo_plane_catapult
```

**Test data / coverage**
launcher

**Additional context**
This was brought up from a discussion with @dagar  
Might be of interest to @Antiheavy

### CODE REVIEW

**Comment by dagar** [comment]
That was fast! Nice work.

**Comment by mhkabir** [comment]
Will you point the nose along the launch vector?

**Comment by Jaeyoung-Lim** [comment]
@mhkabir I am currently just applying force for a fixed duration. Does this mean that I should constrain the motion while the vehicle is being launched?

My thought process was that hand launching would be a more general case which would include the catapult launch, and constraining the attitude or line of motion wouldn't make much sense.

**Comment by LorenzMeier** [comment]
I think what is here is perfectly fine. If someone wants a simulated catapult they can contribute it - that's the great thing about open source. We shouldn't be in the business of doing the work for people on features - we have our hands full maintaining the core.

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim This is very cool. Can you add a heading and very brief explanation of the option under here: http://dev.px4.io/master/en/simulation/gazebo.html#running-the-simulation ?

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee Sure!

@dagar Can we get this in unless there is anything missing please?

**Pull request merged**
