### PR TITLE
Navigator mission cleanup

### PR DESCRIPTION
**Pull request by dagar**
- remove remaining parameters from MissionBlock
 - merge onboard and offboard missions (these are simply different dataman ids)
 - remove MIS_ONBOARD_EN parameter (this was confusing to users)
 - initialize all navigator states, but skip redundant updateParams()
 - log mission and mission_result (very helpful for debugging)

### CODE REVIEW

**Comment by dagar** [comment]
After this I plan to separate navigator mission from accepting a new mission that isn't feasible.

**Comment by LorenzMeier** [comment]
Good to go for 1.7 or did you intent this for 1.8?

**Comment by dagar** [comment]
It can wait.

**Comment by dagar** [comment]
Continued in https://github.com/PX4/Firmware/pull/8497.

**Pull request closed without merging**
