### PR TITLE
Save more RAM

### PR DESCRIPTION
**Pull request by bkueng**
This frees ~1.1 KB in sensors, for boards with only one sensor per type and frees 2.3KB in EKF2.

Requires https://github.com/PX4/ecl/pull/208

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I merged ECL, can you update?

**Comment by LorenzMeier** [comment]
@bkueng Good to merge?

**Comment by bkueng** [comment]
No, the ecl update contains other changes, with an unresolved issue, see https://github.com/PX4/ecl/issues/211

**Comment by LorenzMeier** [comment]
@bkueng Paul fixed it, now good?

**Comment by bkueng** [comment]
I updated the submodule, so this is good to go now. Thanks @priseborough

**Pull request merged**
