### PR TITLE
Support for HMC5983, which can also be attached via SPI

### PR DESCRIPTION
**Pull request by LorenzMeier**
@tridge FYI - this is the last missing bit for the next-gen sensor suite support.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This is largely untested. Testing welcome.

**Comment by LorenzMeier** [comment]
@sjwilks A quick test with this would be great! Open questions for FMUv3:

  * Ensure that the SPI mag has the same orientation

The internal mag can be tested with:
```
hmc5883 -I test
```

**Comment by sjwilks** [comment]
@LorenzMeier I don't have a functional FMUv3 if that's what you want me to test with.

**Comment by LorenzMeier** [comment]
@sjwilks Actually I fear more having broken existing setups ;-). So if your quad still works / flies I would have actually succeeded.

**Comment by LorenzMeier** [comment]
Merged via rebase to master. Tested fine on internal and external compass. Flight testing of master still appreciated.

**Comment by sjwilks** [comment]
OK, I'll test master on Monday once the weather has improved.

**Comment by sjwilks** [comment]
Just flew latest master on a quad with a V1 board. All good.

**Pull request closed without merging**
