### PR TITLE
Mission feedback

### PR DESCRIPTION
**Pull request by LorenzMeier**
@tumbili This gives you the tunes you were asking for.

### CODE REVIEW

**Comment by tumbili** [comment]
@LorenzMeier This is much better but it would be nice if we could have a warning tone. Currently, the "ok" sound is used for warnings which might make the user think that all is ok.

**Comment by LorenzMeier** [comment]
I guess you were missing this commit in your test?
https://github.com/PX4/Firmware/commit/54503715aefde135d14390a64e53148d31c8d1fd

**Comment by tumbili** [comment]
@LorenzMeier No, I think I had all. But still the warnings are not treated separately I guess.

**Comment by LorenzMeier** [comment]
Lets try today then.

**Comment by LorenzMeier** [comment]
@tumbili Could you quickly cross-test this?

**Pull request merged**
