### PR TITLE
Cosmetic startup fixes

### PR DESCRIPTION
**Pull request by bansiesta**
Some printf cleanup.

### CODE REVIEW

**Comment by mhkabir** [comment]
@bansiesta Gotta love your commit messages ;)

**Comment by TSC21** [comment]
> @bansiesta Gotta love your commit messages ;)

AHAH true :D

**Comment by bansiesta** [comment]
Talking of funny commit messages: http://www.commitlogsfromlastnight.com/

**Comment by LorenzMeier** [comment]
Thanks, that's great! There is nothing worse than unreadable bootlogs.

**Pull request merged**
