### PR TITLE
Fix fmu running as task

### PR DESCRIPTION
**Pull request by bkueng**
There were several problems when the fmu was running as a task, see individual commit messages. 
Note that these issues already existed before the modules base class PR https://github.com/PX4/Firmware/pull/7616.

Bench tested & test flown with a Pixracer.

TODO: I'll add a config param to start the fmu as task.

### CODE REVIEW

**Comment by bkueng** [comment]
I added a param `SYS_FMU_TASK` to run the fmu as a task.

**Comment by dagar** [comment]
Thanks! I had this on my list.
What do you think about either pulling the param into the fmu module, or always starting fmu as a task when an IO isn't present?

Params only used in rcS can be awkward. https://github.com/PX4/Firmware/blob/master/src/modules/sensors/parameters.cpp#L236

**Comment by MaEtUgR** [comment]
Here are logs from the test of this pr with a pixracer 250 and enabled oneshot:
- Acro mode
http://review.px4.io/plot_app?log=9a8ce565-5af4-4c50-8314-82352c4b15d6
- Manual mode (untuned attitude controller)
http://review.px4.io/plot_app?log=c103b9fd-19e4-45f0-a897-30e1b2e3bf31
- Acro and manual (fast flicking attitude)
http://review.px4.io/plot_app?log=ce8ce910-4011-4da2-b8dc-e64e5adccd59

The rate controller can be tuned just a bit further and you can really notice the difference while flying acro. In the logs you can see rate controller is at the limit and attitude controller was not tuned at all.
Most notably I was able to command rate, let go of the stick and it visually stayed in the orientation for quite some time. I was even able to let go of the RC for some seconds in acro.

**Comment by dagar** [comment]
Additionally if it's handled in the FMU module it will only be available in QGC parameters for users that actually have an FMU.

**Comment by bkueng** [comment]
@dagar I generally prefer it that way because it does not create conflicts with CLI params. For boards with an IO, the fmu is used as well for the AUX outputs. I'd like to avoid more complicated logic, but we could default to task for instance on Pixracer.

**Comment by dagar** [comment]
Makes sense, but at that point you don't need the command line options. Not immediately relevant here, but this type of thing has been a problem for all the non nuttx boards. Users see all these params for logger options, pwm configuration, etc but they're ignored unless started by rcS.

**Comment by nkhoit** [comment]
@bkueng looks like this works for me. I can see the fmu task running and I can arm+fly it.
Here's an acro log: http://logs.px4.io/plot_app?log=c686a30f-2a7d-4657-a934-c137a42b4037

**Pull request merged**
