### PR TITLE
NuttX update to current master

### PR DESCRIPTION
**Pull request by dagar**
Opening this PR to consider bumping the NuttX version again.
 - NuttX changes: https://github.com/PX4/NuttX/compare/1f2f6d8cbe7c85f30fd75ec53c20566e91b14f21...0523e8a1d0a973eeaee1a909556b14b9946f5774
 - NuttX Apps changes: https://github.com/PX4/NuttX-apps/compare/7db2a352fb19438bb966e419c61e55092056d385...9fbc93ec9f343d316e4c37edae14ea5e045bb243
 - Update to c11 needed for NuttX:e982488e6cb5001dff41f4289b5da83d7c750f7d
 - print_load_nuttx:Adhere to printf spec
 - no defconfig changes
 - px4_fmu-v2 symbol comparison
``` Console
     VM SIZE                           FILE SIZE
 --------------                     --------------
  [NEW] +1.87Ki lib_vscanf          +1.87Ki  [NEW]
  +125% +1.09Ki lib_vsprintf        +1.09Ki  +125%
  [NEW]    +456 __dtoa_engine          +456  [NEW]
  [NEW]    +436 nx_start               +436  [NEW]
  +0.4%    +425 g_cromfs_image         +425  +0.4%
  [NEW]    +214 strtoull               +214  [NEW]
  [NEW]    +208 nxtask_argsetup        +208  [NEW]
  [NEW]    +160 nxthread_create        +160  [NEW]
  [NEW]    +156 strtoll                +156  [NEW]
  [NEW]    +134 nxtask_exithook        +134  [NEW]
  [NEW]    +128 g_dtoa_round           +128  [NEW]
  [NEW]    +108 nxtask_schedsetup      +108  [NEW]
  [NEW]     +96 nxtask_spawn_exec       +96  [NEW]
  [NEW]     +96 nxtask_terminate        +96  [NEW]
  [NEW]     +96 page_sizes.7174         +96  [NEW]
  [NEW]     +88 nxtask_assignpid        +88  [NEW]
  [NEW]     +80 nxtask_exit             +80  [NEW]
   +78%     +76 romfs_hwconfigure       +76   +78%
  [NEW]     +72 g_dtoa_scale_down       +72  [NEW]
  [NEW]     +72 g_dtoa_scale_up         +72  [NEW]
  [NEW]     +66 __ultoa_invert          +66  [NEW]
   +53%     +56 strtoul                 +56   +53%
  [DEL]     -52 cmp                     -52  [DEL]
  [DEL]     -62 hi0bits                 -62  [DEL]
  [DEL]     -64 freelist                  0  [ = ]
  [DEL]     -74 utohex                  -74  [DEL]
  [DEL]     -80 task_exit               -80  [DEL]
  [DEL]     -88 multadd.constprop.0     -88  [DEL]
  [DEL]     -88 task_assignpid          -88  [DEL]
  [DEL]     -94 lo0bits                 -94  [DEL]
  [DEL]     -96 page_sizes.7095         -96  [DEL]
  [DEL]     -96 task_spawn_exec         -96  [DEL]
  [DEL]     -96 task_terminate          -96  [DEL]
  [DEL]    -104 llutohex               -104  [DEL]
  [DEL]    -108 task_schedsetup        -108  [DEL]
  -0.1%    -123 [72 Others]          +170Ki  +1.5%
  [DEL]    -124 pow5mult               -124  [DEL]
  [DEL]    -134 task_exithook          -134  [DEL]
  [DEL]    -160 thread_create          -160  [DEL]
  [DEL]    -166 lshift                 -166  [DEL]
  [DEL]    -174 mult                   -174  [DEL]
  [DEL]    -184 tens                   -184  [DEL]
  [DEL]    -208 task_argsetup          -208  [DEL]
  [DEL]    -212 utoascii               -212  [DEL]
  [DEL]    -224 quorem                 -224  [DEL]
  [DEL]    -274 llutoascii             -274  [DEL]
  [DEL]    -360 prejustify             -360  [DEL]
  [DEL]    -404 lib_dtoa.isra.1        -404  [DEL]
  [DEL]    -436 os_start               -436  [DEL]
 -96.5%    -988 vsscanf                -988 -96.5%
  [DEL] -3.35Ki __dtoa              -3.35Ki  [DEL]
  -0.2% -2.39Ki TOTAL                +168Ki  +1.3%
```

### CODE REVIEW

**Comment by dagar** [comment]
px4_fmu-v2 changes per NuttX library

### libarch
``` Console
     VM SIZE                         FILE SIZE
 --------------                   --------------
  [NEW]     +96 page_sizes.7174       +96  [NEW]
  [NEW]     +38 go_nx_start           +37  [NEW]
  [NEW]     +16 __FUNCTION__.8763     +16  [NEW]
  [NEW]     +13 __FUNCTION__.7271     +13  [NEW]
  [NEW]     +13 __FUNCTION__.8747     +13  [NEW]
  [NEW]     +13 __FUNCTION__.8773     +13  [NEW]
  [NEW]     +12 __FUNCTION__.8755     +12  [NEW]
  [NEW]     +10 __FUNCTION__.8785     +10  [NEW]
  [NEW]      +1 once.7442               0  [ = ]
  [ = ]       0 [Unmapped]        -1.38Ki  -0.2%
  [DEL]      -1 once.7354               0  [ = ]
  [DEL]     -10 __FUNCTION__.8706     -10  [DEL]
  [DEL]     -12 __FUNCTION__.8676     -12  [DEL]
  [DEL]     -13 __FUNCTION__.7192     -13  [DEL]
  [DEL]     -13 __FUNCTION__.8668     -13  [DEL]
  [DEL]     -13 __FUNCTION__.8694     -13  [DEL]
  [DEL]     -16 __FUNCTION__.8684     -16  [DEL]
  [DEL]     -38 go_os_start           -37  [DEL]
  [DEL]     -96 page_sizes.7095       -96  [DEL]
  [ = ]       0 TOTAL             -1.38Ki  -0.1%
```

### libbinfmt
 - no change

### libconfigs
 - no change

### libdrivers
``` Console
     VM SIZE                     FILE SIZE
 --------------               --------------
  +6.6%     +18 uart_write        +18  +6.6%
   +13%     +16 uart_register     +16   +13%
  [ = ]       0 [Unmapped]    +1.13Ki  +0.2%
  -7.7%     -12 uart_open         -12  -7.7%
 -13.2%     -18 uart_close        -18 -13.3%
  +0.0%      +4 TOTAL         +1.13Ki  +0.2%
```

### libfs
``` Console
     VM SIZE                         FILE SIZE
 --------------                   --------------
   +78%     +76 romfs_hwconfigure     +76   +78%
   +45%     +28 romfs_hwread          +28   +46%
   +17%     +10 romfs_checkmount      +10   +18%
  +6.6%      +8 romfs_bind             +8  +6.6%
  +9.1%      +8 romfs_unbind           +8  +9.2%
  [ = ]       0 [Unmapped]        +4.88Ki  +0.4%
  +0.4%    +130 TOTAL             +5.01Ki  +0.3%
```

### libc
``` Console
     VM SIZE                                 FILE SIZE
 --------------                           --------------
  [NEW] +1.87Ki lib_vscanf                +1.87Ki  [NEW]
  +125% +1.09Ki lib_vsprintf              +1.09Ki  +126%
  [NEW]    +456 __dtoa_engine                +455  [NEW]
  [NEW]    +128 g_dtoa_round                 +128  [NEW]
  [NEW]     +72 g_dtoa_scale_down             +72  [NEW]
  [NEW]     +72 g_dtoa_scale_up               +72  [NEW]
  [NEW]     +68 vfscanf                       +67  [NEW]
  [NEW]     +66 __ultoa_invert                +65  [NEW]
   +41%     +62 strtoull                      +62   +41%
   +53%     +56 strtoul                       +56   +53%
  [NEW]     +52 sethostname                   +51  [NEW]
  [NEW]     +36 gethostname                   +35  [NEW]
  [NEW]     +36 scanf                         +35  [NEW]
  [NEW]     +33 g_hostname                      0  [ = ]
  [NEW]     +32 path.7219                       0  [ = ]
   +32%     +32 uname                         +32   +32%
 +10.0%     +28 getopt                        +28   +10%
  [NEW]     +26 fscanf                        +25  [NEW]
   +16%     +22 strtoll                       +22   +17%
  [NEW]     +20 buffer.7110                     0  [ = ]
   +16%     +16 strtol                        +16   +16%
  [NEW]     +12 symtab_sortbyname             +11  [NEW]
  [NEW]      +8 symtab_comparename             +7  [NEW]
  [NEW]      +4 g_argc                          0  [ = ]
  [NEW]      +4 g_argv                          0  [ = ]
  [ = ]       0 [AR Headers]                 +610  +2.8%
  [ = ]       0 [AR Symbol Table]            +172  +2.9%
  [ = ]       0 [ELF Headers]             +7.49Ki  +2.2%
  [DEL]      -4 p5s                             0  [ = ]
  [DEL]      -4 result.7666                     0  [ = ]
  [DEL]      -4 result_k.7667                   0  [ = ]
  [DEL]      -7 g_nullstring                   -7  [DEL]
  [DEL]      -7 spaces                         -7  [DEL]
  [DEL]     -12 p05.7520                      -12  [DEL]
  [DEL]     -20 buffer.7022                     0  [ = ]
  [DEL]     -22 lib_dtoa_string               -21  [DEL]
  [DEL]     -24 Bfree                         -23  [DEL]
  -0.6%     -26 [Unmapped]                -2.72Ki  -0.2%
  [DEL]     -32 path.7131                       0  [ = ]
  [DEL]     -33 CSWTCH.33                     -33  [DEL]
  [DEL]     -33 CSWTCH.34                     -33  [DEL]
  [DEL]     -40 bigtens                       -40  [DEL]
  [DEL]     -46 postjustify                   -45  [DEL]
  [DEL]     -48 Balloc                        -47  [DEL]
  [DEL]     -50 symtab_findorderedbyvalue     -49  [DEL]
  [DEL]     -52 cmp                           -51  [DEL]
  [DEL]     -62 hi0bits                       -61  [DEL]
  [DEL]     -64 freelist                        0  [ = ]
  [DEL]     -74 utohex                        -73  [DEL]
  [DEL]     -88 multadd.constprop.0           -87  [DEL]
  [DEL]     -94 lo0bits                       -93  [DEL]
  [DEL]    -104 llutohex                     -103  [DEL]
  [DEL]    -124 pow5mult                     -123  [DEL]
  [DEL]    -166 lshift                       -165  [DEL]
  [DEL]    -174 mult                         -173  [DEL]
  [DEL]    -184 tens                         -184  [DEL]
  [DEL]    -212 utoascii                     -211  [DEL]
  [DEL]    -224 quorem                       -223  [DEL]
  [DEL]    -274 llutoascii                   -273  [DEL]
  [DEL]    -360 prejustify                   -359  [DEL]
  [DEL]    -404 lib_dtoa.isra.1              -403  [DEL]
 -96.5%    -988 vsscanf                      -988 -96.6%
  [DEL] -3.35Ki __dtoa                    -3.35Ki  [DEL]
  -8.7% -3.04Ki TOTAL                     +2.56Ki  +0.1%
```

### libxx
 - no change

### libmm
``` Console
     VM SIZE                         FILE SIZE
 --------------                   --------------
   +85%     +94 gran_byte_info        +94   +86%
  [ = ]       0 [AR Symbol Table]     -82 -10.2%
  [ = ]       0 [ELF Headers]         -80  -0.2%
  -2.2%      -1 [Unmapped]        -1.03Ki  -0.5%
  -7.4%      -8 gran_hword_info        -8  -7.5%
  [DEL]     -64 gran_nibble_info      -63  [DEL]
  +0.6%     +21 TOTAL             -1.17Ki  -0.5%
```

### libsched
``` Console
     VM SIZE                          FILE SIZE
 --------------                    --------------
  [NEW]    +436 nx_start              +435  [NEW]
  [NEW]    +208 nxtask_argsetup       +207  [NEW]
  [NEW]    +176 nxtask_vforksetup     +175  [NEW]
  [NEW]    +172 nxtask_vforkstart     +171  [NEW]
  [NEW]    +160 nxthread_create       +159  [NEW]
  [NEW]    +134 nxtask_exithook       +133  [NEW]
  [NEW]    +108 nxtask_schedsetup     +107  [NEW]
  [NEW]     +96 nxtask_spawn_exec      +95  [NEW]
  [NEW]     +96 nxtask_terminate       +95  [NEW]
  [NEW]     +88 nxtask_assignpid       +87  [NEW]
  [NEW]     +80 nxtask_exit            +79  [NEW]
  [NEW]     +52 nxtask_start           +51  [NEW]
  [NEW]     +44 nx_bringup             +43  [NEW]
  [NEW]     +44 nxtask_spawn_proxy     +43  [NEW]
  [NEW]     +40 nxtask_vforkabort      +39  [NEW]
   +19%     +28 nxsig_deliver          +28   +19%
  [NEW]     +24 nxtask_recover         +23  [NEW]
  +1.9%      +4 nxmq_do_send            +4  +1.9%
  +7.1%      +4 timer_timeout           +4  +7.3%
  +0.5%      +2 [Unmapped]         +4.74Ki  +0.2%
  [NEW]      +1 g_nx_initstate           0  [ = ]
  [ = ]       0 [AR Symbol Table]      +20  +0.3%
  [DEL]      -1 g_os_initstate           0  [ = ]
  [DEL]     -24 task_recover           -23  [DEL]
  [DEL]     -40 task_vforkabort        -39  [DEL]
  [DEL]     -44 os_bringup             -43  [DEL]
  [DEL]     -44 task_spawn_proxy       -43  [DEL]
  [DEL]     -52 task_start             -51  [DEL]
  [DEL]     -80 task_exit              -79  [DEL]
  [DEL]     -88 task_assignpid         -87  [DEL]
  [DEL]     -96 task_spawn_exec        -95  [DEL]
  [DEL]     -96 task_terminate         -95  [DEL]
  [DEL]    -108 task_schedsetup       -107  [DEL]
  [DEL]    -134 task_exithook         -133  [DEL]
  [DEL]    -160 thread_create         -159  [DEL]
  [DEL]    -172 task_vforkstart       -171  [DEL]
  [DEL]    -176 task_vforksetup       -175  [DEL]
  [DEL]    -208 task_argsetup         -207  [DEL]
  [DEL]    -436 os_start              -435  [DEL]
  +0.2%     +38 TOTAL              +4.80Ki  +0.2%
```

### libapps
``` Console
     VM SIZE                        FILE SIZE
 --------------                  --------------
  [NEW]     +22 format.7693          +22  [NEW]
  [NEW]      +1 initialized.7526       0  [ = ]
  [ = ]       0 [Unmapped]          +160  +0.0%
  [DEL]      -1 initialized.7438       0  [ = ]
  [DEL]     -22 format.7605          -22  [DEL]
  [ = ]       0 TOTAL               +160  +0.0%
```

**Comment by dagar** [comment]
Looks good on the bench. @davids5 any concerns?

**Comment by davids5** [comment]
I will have a look at it on Monday. I have some things in the RT branch that need to come in as well

On February 24, 2019 2:21:05 PM PST, Daniel Agar <notifications@github.com> wrote:
>Looks good on the bench. @davids5 any concerns?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/PX4/Firmware/pull/11537#issuecomment-466823501

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dannyfpv** [comment]
tested on pixhawk4 v5 good flights pr and master
pr
https://review.px4.io/plot_app?log=91a7b788-ea30-4827-8d38-6207a6bf8454
master
https://review.px4.io/plot_app?log=a582a3a0-b49e-4622-a236-fa9059125bb0

**Comment by jorge789** [comment]
Tested on Pixhawk Pro v4 Pro, no significant differences in behavior between PR and Master, only thing to point out is velocity difference (Master was close to 40% faster than PR).

https://review.px4.io/plot_app?log=15d61ed9-acc6-41e6-9409-3357e62d1792

Same behavior when tested on Pixracer v4, no significant differences between Master and PR but the velocity.

https://review.px4.io/plot_app?log=c090400c-b18c-44f0-8925-5c7db824b8ac

**Comment by dagar** [comment]
Thanks for the testing @dannyfpv and @jorge789. Nothing in this PR explains the velocity difference, so I'll take a look at those logs.

**Pull request closed without merging**
