### PR TITLE
Fix threading problem in mavlink_parameters.cpp

### PR DESCRIPTION
**Pull request by lovettchris**
The mavlink_parameters::handle_message method was trying to send responses back immediately from the mavlink_receiver::receive_thread.  This conflicts with messages already being sent on the main thread, resulting in random CRC failures, and flakey results from PARAM_REQUEST_READ and PARAM_SET.  The following shows a log of the attempts to read a parameter before this fix:

param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
MavLink message 147, seqno 8c has bad CRC 19 received, expecting 1a6d!
Exception: Parameter 'SENS_EN_SF1XX' not found' 
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
MavLink message 30, seqno bb has bad CRC 19 received, expecting a7c5!
MavLink message 21, seqno c5 has bad CRC 15 received, expecting ec5f!
Exception: Parameter 'SENS_EN_SF1XX' not found
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
MavLink message 105, seqno 96 has bad CRC 19 received, expecting 346b!
Exception: Parameter 'SENS_EN_SF1XX' not found
param get SENS_EN_SF1XX
MavLink message 105, seqno 5d has bad CRC 19 received, expecting f1a4!
Exception: Parameter 'SENS_EN_SF1XX' not found
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4

The following shows the result of the fix:

param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param set SENS_EN_SF1XX 12
setting param SENS_EN_SF1XX to new value 12.000000
success
param get SENS_EN_SF1XX
SENS_EN_SF1XX=12
param get SENS_EN_SF1XX
SENS_EN_SF1XX=12
param get SENS_EN_SF1XX
SENS_EN_SF1XX=12
param set SENS_EN_SF1XX 4
setting param SENS_EN_SF1XX to new value 4.000000
success
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice find! The issue with the fix is that it consumes additional RAM and over 3 links on a system quite a bit of it. I would prefer the use of a blocking lock which ensures that the send function is never accessed concurrently. This will slow the param handling thread, but in this case that's fine. @bkueng this might influence more locations like mission transfers and log streaming.

**Comment by lovettchris** [comment]
Yeah, I was worried about the memory usage also.  I did find a mutex in Mavlink::send_bytes, which is called from mavlink_send_uart_bytes, but my debug log above indicates this mutex isn't working... or there is more than one mavlink_channel trying to share the same serial port?

**Comment by bkueng** [comment]
@lovettchris `mavlink_send_uart_bytes` is not necessarily called with a whole mavlink packet. I'm pretty sure the mutex works, but it does not protect full mavlink message.

**Comment by bkueng** [comment]
`MavlinkMissionManager` is affected too, `MavlinkLogHandler` and `MavlinkFTP` look ok.
It would simplify things if `Mavlink::handle_message` was called from the main mavlink thread.

More affected places:
- https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L372 (all calls to `mavlink->send_autopilot_capabilites`)
- https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L1494
- https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L1564
- https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L1612

**Comment by lovettchris** [comment]
Oh, you are right, it is always 3 calls to send a message:
	MAVLINK_START_UART_SEND(chan, MAVLINK_NUM_NON_PAYLOAD_BYTES + (uint16_t)length);
	_mavlink_send_uart(chan, (const char *)buf, MAVLINK_NUM_HEADER_BYTES);
	_mavlink_send_uart(chan, packet, length);
	_mavlink_send_uart(chan, (const char *)ck, 2);
	MAVLINK_END_UART_SEND(chan, MAVLINK_NUM_NON_PAYLOAD_BYTES + (uint16_t)length);

What if we use the MAVLINK_START_UART_SEND and MAVLINK_END_UART_SEND to grab and release the lock ?

**Comment by bkueng** [comment]
> What if we use the MAVLINK_START_UART_SEND and MAVLINK_END_UART_SEND to grab and release the lock ?

Sounds like a simple & clean solution, but it leads to more subtle concurrency issues. `_mav_finalize_message_chan_send` accesses and modifies the status, for example in [0], and also for the signing.
If we moved `MAVLINK_START_UART_SEND` further up, it might work, but it seems fragile.

[0] https://github.com/mavlink/c_library_v2/blob/master/mavlink_helpers.h#L326

**Comment by lovettchris** [comment]
I'm closing this pull request, and submitting another.

**Comment by lovettchris** [comment]
I think the status->current_tx_seq++; line is ok, it should be atomic.  Even if it isn’t, the sequence number will get bumped a few times, but that’s ok, no one checks that number anyway ☺  The important thing is that _mav_finalize_message_chan_s is operating on a local buffer on the stack, uint8_t buf[MAVLINK_NUM_HEADER_BYTES];
so that buffer is safe.

I tested the new fix, it seems to work.

See new pull request: https://github.com/PX4/Firmware/pull/5880

**Pull request closed without merging**
