### PR TITLE
Export symbols init_app_map and list_builtins

### PR DESCRIPTION
**Pull request by CarloWood**
See discussion at https://github.com/PX4/Firmware/issues/5756

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Much appreciated!

**Comment by LorenzMeier** [comment]
@Stifael @julianoes Can you please test this today?

**Comment by julianoes** [comment]
Thanks @CarloWood, I'll test this today.

**Comment by julianoes** [comment]
`init_app_map` and `list_builtins` are fixed but now I get:

```
     30762: HAP:63:undefined PLT symbol _Dtest (1328) /libpx4muorb_skel.so (symbol.c:303)
```

I'll check if this is related to this change.

**Comment by julianoes** [comment]
Strange enough if I cherry-pick this commit right after the initial cleanup commit I get:

```
   1298408: HAP:63:undefined PLT symbol localeconv (278) /libpx4.so (symbol.c:303)
```

**Comment by CarloWood** [comment]
Starting work on this now...

**Comment by CarloWood** [comment]
Hoping for a short cut, I just concentrated on the target qurt_eagle_default again.
The only reference to a symbol with even the string 'localeconv' in it appears in apps.cpp.o.
So, from now on only looking at that object file.

Compilation:

```
sean:/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/src/firmware/qurt>/usr/src/px4/snapdragon/Qualcomm/HEXAGON_Tools/7.2.12/Tools/bin/hexagon-clang++   -DCONFIG_ARCH_BOARD_EAGLE -D__DF_QURT -D__PX4_POSIX -D__PX4_QURT -D__PX4_QURT_EAGLE -D__QAIC_SKEL_EXPORT=__EXPORT -D__STDC_FORMAT_MACROS -Dpx4_EXPORTS -I/usr/src/px4/snapdragon/Qualcomm/Hexagon_SDK/3.0/incs -I/usr/src/px4/snapdragon/Qualcomm/Hexagon_SDK/3.0/incs/stddef -I/usr/src/px4/snapdragon/Qualcomm/Hexagon_SDK/3.0/libs/common/rpcmem/inc -I/usr/src/px4/snapdragon/Qualcomm/Hexagon_SDK/3.0/libs/common/qurt/ADSPv5MP/include -I/usr/src/px4/Firmware/Firmware.git/src -I/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default -I/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/src -I/usr/src/px4/Firmware/Firmware.git/src/modules -I/usr/src/px4/Firmware/Firmware.git/src/include -I/usr/src/px4/Firmware/Firmware.git/src/lib -I/usr/src/px4/Firmware/Firmware.git/src/platforms -I/usr/src/px4/Firmware/Firmware.git/src/drivers/boards/eagle -I/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/src/modules/px4_messages -I/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/src/modules -I/usr/src/px4/Firmware/Firmware.git/mavlink/include/mavlink -I/usr/src/px4/Firmware/Firmware.git/src/lib/DriverFramework/framework/include -I/usr/src/px4/Firmware/Firmware.git/src/lib/matrix -I/usr/src/px4/Firmware/Firmware.git/src/lib/DriverFramework/dspal/include -I/usr/src/px4/Firmware/Firmware.git/src/lib/DriverFramework/dspal/sys -I/usr/src/px4/Firmware/Firmware.git/src/lib/DriverFramework/dspal/sys/sys -I/usr/src/px4/Firmware/Firmware.git/src/lib/DriverFramework/dspal/mpu_spi/inc -I/usr/src/px4/Firmware/Firmware.git/src/lib/DriverFramework/dspal/uart_esc/inc -I/usr/src/px4/Firmware/Firmware.git/src/platforms/qurt/include -I/usr/src/px4/Firmware/Firmware.git/src/platforms/posix/include -I/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/external/Install/include -I/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/src/firmware/qurt -I/usr/src/px4/snapdragon/Qualcomm/Hexagon_SDK/3.0/libs/common/rpcmem -I/usr/src/px4/snapdragon/Qualcomm/Hexagon_SDK/3.0/libs/common/remote/ship/hexagon_Debug  -DCONFIG_WCHAR_BUILTIN -D__CUSTOM_FILE_IO__ -mv5 -G0 -DDSP_TYPE_ADSP -g -fno-exceptions -fno-rtti -std=gnu++0x -fno-threadsafe-statics -DCONFIG_WCHAR_BUILTIN -D__CUSTOM_FILE_IO__ -Wall -Werror -Wextra -Wno-sign-compare -Wshadow -Wfloat-equal -Wpointer-arith -Wmissing-declarations -Wno-unused-parameter -Werror=format-security -Werror=array-bounds -Wfatal-errors -Werror=unused-variable -Werror=reorder -Werror=uninitialized -Werror=init-self -Wno-missing-field-initializers -fvisibility=hidden -include visibility.h -O0 -O2 -fno-strict-aliasing -fomit-frame-pointer -funsafe-math-optimizations -ffunction-sections -fdata-sections -fPIC  -DCONFIG_WCHAR_BUILTIN -D__CUSTOM_FILE_IO__ -mv5 -G0 -DDSP_TYPE_ADSP -DCONFIG_WCHAR_BUILTIN -D__CUSTOM_FILE_IO__ -mv5 -G0 -DDSP_TYPE_ADSP -fPIC   -D __QURT -D _PID_T -D _UID_T -D _TIMER_T -D _HAS_C9X -D restrict=__restrict__ -D noreturn_function= -include visibility.h -D __QURT -D _PID_T -D _UID_T -D _TIMER_T -D _HAS_C9X -D restrict=__restrict__ -D noreturn_function= -o CMakeFiles/px4.dir/__/__/__/apps.cpp.o -c /usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/apps.cpp
```

symbols with the string 'locale' in it:

```
sean:/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/src/firmware/qurt>readelf -s -W CMakeFiles/px4.dir/__/__/__/apps.cpp.o | grep locale
   244: 00000000   184 FUNC    WEAK   HIDDEN   204 _ZNSt5ctypeIcE7_GetcatEPPKNSt6locale5facetEPKS1_
   247: 00000000     4 FUNC    WEAK   HIDDEN   225 _ZNSt6locale5facetD2Ev
   249: 00000000   172 FUNC    WEAK   HIDDEN   134 _ZNSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE7_GetcatEPPKNSt6locale5facetEPKS5_
   254: 00000000   148 FUNC    WEAK   HIDDEN   162 _ZNSt8numpunctIcE7_GetcatEPPKNSt6locale5facetEPKS1_
   288: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZNKSt6locale9_GetfacetEj
   292: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZNSt6locale2id7_Id_cntE
   293: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZNSt6locale5facet9_RegisterEv
   326: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND localeconv
```

It annoys me that locale is used at ALL. It seems something we could do without.
Therefore I'll have to get back to c200ef88edb314b852ec4a5bcfb4042d5dfc6da8
and investigate what exists there...

**Comment by davids5** [comment]
Can you pull in Nuttx's locale stubs?

**Comment by CarloWood** [comment]
Ok, in c200ef8 there is no symbol localeconv anywhere at all. So, a solution would be something where that UND symbol disappears from apps.cpp.o. Furthermore, apps.h is included there in src/platforms/qurt/px4_layer/main.cpp : 

Compilation:

```
sean:/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/src/platforms/qurt/px4_layer>/usr/src/px4/snapdragon/Qualcomm/HEXAGON_Tools/7.2.12/Tools/bin/hexagon-clang++   -DCONFIG_ARCH_BOARD_EAGLE -DMODULE_NAME=\"platforms__qurt__px4_layer\" -D__DF_QURT -D__PX4_POSIX -D__PX4_QURT -D__PX4_QURT_EAGLE -D__QAIC_SKEL_EXPORT=__EXPORT -D__STDC_FORMAT_MACROS -I/usr/src/px4/snapdragon/Qualcomm/Hexagon_SDK/3.0/incs -I/usr/src/px4/snapdragon/Qualcomm/Hexagon_SDK/3.0/incs/stddef -I/usr/src/px4/snapdragon/Qualcomm/Hexagon_SDK/3.0/libs/common/rpcmem/inc -I/usr/src/px4/snapdragon/Qualcomm/Hexagon_SDK/3.0/libs/common/qurt/ADSPv5MP/include -I/usr/src/px4/Firmware/Firmware.git/src -I/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default -I/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/src -I/usr/src/px4/Firmware/Firmware.git/src/modules -I/usr/src/px4/Firmware/Firmware.git/src/include -I/usr/src/px4/Firmware/Firmware.git/src/lib -I/usr/src/px4/Firmware/Firmware.git/src/platforms -I/usr/src/px4/Firmware/Firmware.git/src/drivers/boards/eagle -I/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/src/modules/px4_messages -I/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/src/modules -I/usr/src/px4/Firmware/Firmware.git/mavlink/include/mavlink -I/usr/src/px4/Firmware/Firmware.git/src/lib/DriverFramework/framework/include -I/usr/src/px4/Firmware/Firmware.git/src/lib/matrix -I/usr/src/px4/Firmware/Firmware.git/src/lib/DriverFramework/dspal/include -I/usr/src/px4/Firmware/Firmware.git/src/lib/DriverFramework/dspal/sys -I/usr/src/px4/Firmware/Firmware.git/src/lib/DriverFramework/dspal/sys/sys -I/usr/src/px4/Firmware/Firmware.git/src/lib/DriverFramework/dspal/mpu_spi/inc -I/usr/src/px4/Firmware/Firmware.git/src/lib/DriverFramework/dspal/uart_esc/inc -I/usr/src/px4/Firmware/Firmware.git/src/platforms/qurt/include -I/usr/src/px4/Firmware/Firmware.git/src/platforms/posix/include -I/usr/src/px4/Firmware/Firmware.git/build_qurt_eagle_default/external/Install/include  -g -fno-exceptions -fno-rtti -std=gnu++0x -fno-threadsafe-statics -DCONFIG_WCHAR_BUILTIN -D__CUSTOM_FILE_IO__ -Wall -Werror -Wextra -Wno-sign-compare -Wshadow -Wfloat-equal -Wpointer-arith -Wmissing-declarations -Wno-unused-parameter -Werror=format-security -Werror=array-bounds -Wfatal-errors -Werror=unused-variable -Werror=reorder -Werror=uninitialized -Werror=init-self -Wno-missing-field-initializers -fvisibility=hidden -include visibility.h -O0 -O2 -fno-strict-aliasing -fomit-frame-pointer -funsafe-math-optimizations -ffunction-sections -fdata-sections -fPIC -fPIC   -D __QURT -D _PID_T -D _UID_T -D _TIMER_T -D _HAS_C9X -D restrict=__restrict__ -D noreturn_function= -include visibility.h -O2 -fno-strict-aliasing -fomit-frame-pointer -funsafe-math-optimizations -ffunction-sections -fdata-sections -fPIC -o CMakeFiles/platforms__qurt__px4_layer.dir/main.cpp.o -c /usr/src/px4/Firmware/Firmware.git/src/platforms/qurt/px4_layer/main.cpp
```
symbols with the string 'locale' in it do not exist at all. I like that more ;).
The question is now thus: why is locale suddenly being used?

**Comment by CarloWood** [comment]
davids5: That sounds like what is missing, but I had never heard of Nuttx's locae stubs :p. So, I'm not sure at all HOW to do that.

**Comment by CarloWood** [comment]
I just tried compiling main.cpp with the command line that compiled apps.cpp and still no locale... so it's not something that is passed to the compiler.

**Comment by davids5** [comment]
Look here 

https://bitbucket.org/nuttx/nuttx/src/2fa8b9ba34d73bd0157c1d4f407a060fae796c2b/include/locale.h?at=master&fileviewer=file-view-default

This work to make the the arm tool chain compile.

The latter code is not even linked bit is here:

https://bitbucket.org/nuttx/nuttx/src/2fa8b9ba34d73bd0157c1d4f407a060fae796c2b/libc/locale/?at=master

**Comment by CarloWood** [comment]
Really... I just copied all header files at the top of main.cpp into apps.cpp(.in) and compiled apps.cpp with the same command line as main.cpp is compiled, plus a -I. and a copy of get_commands.h into .
... Still locate symbols in apps.cpp.o.

**Comment by CarloWood** [comment]
Ok, I found the problem... now lemme think of a proper solution...

**Comment by CarloWood** [comment]
So, david was right and linking with Nuttx's locale stubs would be a (the?) proper way to solve the linking issue... but I had to figure out why the old code didn't need those stubs. The answer is actually pretty embarrassing, locale gets dragged in by using std::cout, something I had done without giving it much thought: the posix/apps.h_in used cout, qurt/apps.h_in used printf, .. and I wasn't going to put a printf in a .cpp file haha.

At this point I'm not sure what to do though: adding an empty localeconv would work, but other locale related symbols are being linked and I'm worried about needless larger code because of this? I just have no idea. If it links then that code already exists anyway and you could argue as well that using printf will grow the code.

A "not a regression" solution would be to go back to printf, but that feels ugly to me.
I'll leave this choice to you guys (though I'm willing to write the patch, just let me know).

**Comment by LorenzMeier** [comment]
@CarloWood Embedded RTOS systems (like QuRT) generally implement just enough of the C/C++ standards to run "true low level" code. Often also custom implementations are used (QuRT has its own CLANG version). It can prove costly (in terms of loss of time, loss of drones and even loss of life) to test the boundaries of the C++ support. We don't know how well tested the string stream operators are.

You cannot make the assumption that everything that links is actually well implemented and well tested. I therefore want to go back to printf() and not run any more string stream operation than required. If we did we would need first to write a test suite to test the whole standard, including a valgrind session. We don't have the time for that unfortunately.

Thanks!

**Comment by CarloWood** [comment]
@LorenzMeier Does the software not print to 'cout' at all then, when compiled for QuRT? Because that seems what you imply; that it hasn't been used at all yet, so we don't know anything about the stability.

**Comment by CarloWood** [comment]
Note that the relevant diff from before and what we have now, for QuRT is:

```
-        unsigned long usecs = ( (unsigned long) atol( argv[1] ) ) * 1000 * 1000;
-        PX4_WARN("Sleeping for %s, %ld",argv[1],usecs);
-        usleep( usecs );
+        unsigned long usecs = 1000000UL * atol(argv[1]);
+        printf("Sleeping for %s s; (%ul us).\n", argv[1], usecs);
+        usleep(usecs);
```
I have to say that I didn't understand why that had to be a warning, so I used printf :*).
printf was already used elsewhere in that file, for another command.

While for POSIX the relevant diff is now:
```
+void list_builtins(apps_map_type &apps)
 {
-       cout << "Builtin Commands:" << endl;
-       for (map<string,px4_main_t>::iterator it=apps.begin(); it!=apps.end(); ++it)
-               cout << '\t' << it->first << endl;
+       PX4_INFO("Builtin Commands:\n");
+       for (apps_map_type::iterator it = apps.begin(); it != apps.end(); ++it)
+               PX4_INFO("%s : 0x%x\n", it->first.c_str(), it->second);
 }
```
and
```
+int sleep_main(int argc, char *argv[])
 {
-       if (argc != 2) {
-               cout << "Usage: sleep <seconds>" << endl;
-               return 1;
-       }
-       sleep(atoi(argv[1]));
-       return 0;
+        if (argc != 2) {
+           PX4_WARN( "Usage: sleep <seconds>" );
+           return 1;
+        }
+
+        unsigned long usecs = 1000000UL * atol(argv[1]);
+        printf("Sleeping for %s s; (%ul us).\n", argv[1], usecs);
+        usleep(usecs);
+        return 0;
 }
```

So, on posix we didn't print that we were sleeping at all; but now it does.

Also, sleep(3) conforms to POSIX.1-2001. While usleep was removed from POSIX in 2008 (it was obsoleted in POSIX.1-2001) and people should use nanosleep. I don't think it's a problem however we use usleep on POSIX (aka, linux), until it simply stops compiling.

**Comment by LorenzMeier** [comment]
@CarloWood I would not be conscious about using cout on any of our RTOS builds and yes, I would actively avoid using it. I do expect that its not used intensely and that we turn ourselves into guinea pigs when we do.

I'm speaking of experience - we have suffered through a lot of corner cases on various RTOS systems when using higher-level C++ features.

That does not mean I'm against targeting that medium term - but it would be a shame to gate your good cleanup on a complete cout test suite. Instead I'd like to dodge it for now, get the PX4 internals cleaned up and then consciously attack these standardisation aspects one-by-one with enough time to ring them out.

**Comment by LorenzMeier** [comment]
I'm bringing this in now. If there is any cleanup left we'll handle in a separate PR. Thanks!

**Comment by jywilson** [comment]
@CarloWood @LorenzMeier 
I am late to party here, but I just wanted to say thanks for tracking this down.  I will spread the word around here internally.  I will also see if I can find an official statement of the level of C++ support provided by the Hexagon SDK.  

To Lorenz's point about C++ sometimes causing unexpected issues, we have a known bug related to the initialization of static C++ classes executed on the DSP.  I don't know all the details, but I believe the ctors's of the statically declared classes are not always executed correctly.  

I will try to get more information on this as well.

**Comment by CarloWood** [comment]
@jywilson Not sure what you mean, since this was about a regression that I caused with another commit ;). The least I can do then is to track down and fix the issue. Also, this doesn't seem directly related to Hexagon SDK (although I have a few remarks about that elsewhere; in that it doesn't totally conform to the standard).

As for your second paragraph, static (and global) non-POD classes (aka, classes with a constructor) are evil to begin with; they should be avoid at almost every cost in any project imho. If this project has them then we should think about getting rid of them for the sake of stability anyway.

**Comment by jywilson** [comment]
I agree this was a regression, but I think it would be helpful to know the extent of C++ support in the Hexagon tool chain to avoid future regressions.

**Pull request merged**
