### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by LorenzMeier**
This brings Linux support running as a single app with each node running as a thread. Builds on Linux and NuttX.

@davids5 Could you have a look?

@dagar Any comments?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@mcharleb The CI systems already hint there is some work needed. I also looked at the diff, and I see massive diffs in some places I didn't expect them in - did you run some sort of auto-formatting tool on some files? Tools/fix_code_style.sh maybe? In general we avoid running it unless needed. I think I need to reduce the diff a bit before I can really review this ;-).

**Comment by mcharleb** [comment]
There shouldn't be any formatting differences. What is the best way to
stage this then?

**Comment by mcharleb** [comment]
I replaced isfinite() with PX4_ISFINITE() in a later commit. There are  issues with scope and isfinite depending on which OS you build from.

**Comment by mcharleb** [comment]
In order to build for each OS you have to use:
make PX4_TARGET_OS=<target>
where target is nuttx, or linux

**Comment by LorenzMeier** [comment]
This branch builds for Linux and includes Linux system headers if not building for NuttX. Could we change this so it builds for POSIX and compiles Linux headers conditionally? A lot of our developers run on Mac OS and would want to do SITL there as well (including me).

**Comment by mcharleb** [comment]
Yes, I can make a __PX4_POSIX define and change linux to posix for the PX4_TARGET_OS setting.

**Comment by LorenzMeier** [comment]
@mcharleb Thanks for this massive contribution! We flight tested it today successfully on Pixhawk!

**Comment by LorenzMeier** [comment]
@mcharleb I still need to resolve the CI test failure. @AndreasDanielAntener could you have a look a the SITL CI fail and let me know what failed there?

**Comment by AndreasAntener** [comment]
@LorenzMeier ATM, it cannot compile (http://sitl01.dronetest.io/job/PX4%20Firmware%20SITL%20PRs/577/console):
```
actuator_controls_3.h: unchanged
mc_att_ctrl_status.h: unchanged
vehicle_attitude_setpoint.h: unchanged
[ 47%] Built target multiplatform_message_headers
Scanning dependencies of target px4
[ 47%] Building CXX object Firmware/CMakeFiles/px4.dir/src/platforms/ros/px4_ros_impl.cpp.o
In file included from /sitl/catkin_ws/src/Firmware/src/include/../platforms/px4_nodehandle.h:45:0,
                 from /sitl/catkin_ws/src/Firmware/src/include/px4.h:46,
                 from /sitl/catkin_ws/src/Firmware/src/platforms/ros/px4_ros_impl.cpp:40:
/sitl/catkin_ws/src/Firmware/src/include/../platforms/px4_posix.h:102:2: error: #error "No TARGET OS Provided"
 #error "No TARGET OS Provided"
  ^
make[2]: *** [Firmware/CMakeFiles/px4.dir/src/platforms/ros/px4_ros_impl.cpp.o] Error 1
make[1]: *** [Firmware/CMakeFiles/px4.dir/all] Error 2
make: *** [all] Error 2
Base path: /sitl/catkin_ws
```

**Comment by mcharleb** [comment]
I haven't been testing the ROS builds. I'll do that and fix the errors.

**Comment by mcharleb** [comment]
ROS, POSIX and QuRT all build successfully now

**Comment by LorenzMeier** [comment]
Awesome!

**Comment by LorenzMeier** [comment]
I merged master. If this build goes through I'll go ahead with the master merge.

**Comment by mcharleb** [comment]
I had to fixup one poll to px4_poll after your merge

**Comment by LorenzMeier** [comment]
@mcharleb To prevent this in the future, could you please add a test target here, similar to what's already there?
https://github.com/PX4/Firmware/blob/master/.travis.yml#L64

At least the compilation should be covered. Of course running it would be even better.

How can we resolve the need to create a few magic files in the root directory of the host computer?

**Comment by LorenzMeier** [comment]
@mcharleb Travis didn't like the last merge I did, checking..

**Comment by LorenzMeier** [comment]
Weird - failed again here: Ideas?
```
[ 12%] [32mBuilding CXX object CMakeFiles/mixer_test.dir/mixer_test.cpp.o
[0mIn file included from /home/travis/build/PX4/Firmware/unittests/../src/drivers/drv_mixer.h:56:0,
                 from /home/travis/build/PX4/Firmware/unittests/../src/modules/systemlib/mixer/mixer.h:132,
                 from /home/travis/build/PX4/Firmware/unittests/mixer_test.cpp:1:
/home/travis/build/PX4/Firmware/unittests/../src/platforms/px4_defines.h:87:2: error: #error "No target OS defined"
 #error "No target OS defined"
```

**Comment by mcharleb** [comment]
I just did a successful ROS build so I'm not sure what's going on

**Comment by mcharleb** [comment]
The unit tests work now.

**Comment by LorenzMeier** [comment]
@mcharleb Its failing now here:
```
[0mIn file included from /home/travis/build/PX4/Firmware/unittests/../src/platforms/px4_defines.h:75:0,
                 from /home/travis/build/PX4/Firmware/unittests/../src/platforms/px4_posix.h:42,
                 from /home/travis/build/PX4/Firmware/unittests/../src/drivers/drv_hrt.h:42,
                 from /home/travis/build/PX4/Firmware/unittests/hrt.cpp:3:
/home/travis/build/PX4/Firmware/unittests/../src/platforms/px4_includes.h:113:58: fatal error: platforms/posix/px4_messages/px4_rc_channels.h: No such file or directory
 #include <platforms/posix/px4_messages/px4_rc_channels.h>
```

This is because the unit tests rely on the POSIX headers to be generated. I have now worked around this in the Travis CI config, but we probably need to make the POSIX header generation a dependency of the unit test run.

**Comment by LorenzMeier** [comment]
Ok, this did it - prime time!

**Comment by mcharleb** [comment]
Awesome!! Thanks for your help with the integration.

**Pull request merged**
