### PR TITLE
Create parrot_disco_mod.main.mix

### PR DESCRIPTION
**Pull request by jliphard**
Flight tested with both Pixhawk Mini and Pixracer.

### CODE REVIEW

**Comment by dagar** [comment]
I've been trying to reduce the number of duplicated/identical configurations. If I'm not mistaken this is identical to the Q and X5 mixers. What do you think about calling this "generic wing" or similar and then I could delete the others?

**Comment by jliphard** [comment]
Yes, a very good idea. If people really need to differ from your proposed generic_wing.main.mix, then they can always do that and submit a differing .main.mix.

> On Jul 15, 2017, at 12:11 PM, Daniel Agar <notifications@github.com> wrote:
> 
> I've been trying to reduce the number of duplicated/identical configurations. If I'm not mistaken this is identical to the Q and X5 mixers.
> 
Yes, it’s identical. 
> What do you think about calling this "generic wing" or similar and then I could delete the others.
> 
Sure!

**Comment by dagar** [comment]
I probably went overboard, but in https://github.com/PX4/Firmware/pulls I added a generic wing mixer.

**Comment by jliphard** [comment]
The PR is not longer needed since there is a new generic wing mixer (fw_generic_wing.main.mix)

**Pull request closed without merging**
