### PR TITLE
Clean up vehicle_status message

### PR DESCRIPTION
**Pull request by julianoes**
Do not merge yet, untested, just for review.

This is work in progress trying to clean up the vehicle_status message.
Current changes include:
- Remove circuit breakers from vehicle_status
- Delete mavlink compatible fields which were not in sync anymore.
- Move vtol_vehicle_status enum to vtol_status topic.
- Move battery calculations to the respective drivers (sensors.cpp and px4io.cpp).
- Move battery data to battery_status topic.
- Internalize condition bools into commander and out of vehicle_status.
- Use land_detected message everywhere instead of the landed bool in vehicle_status.

For more detailed explanations, please read through the commit messages.

This PR is now on top of #3857.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Architectural implications / cleanup looks good.

**Comment by julianoes** [comment]
@LorenzMeier Any idea why the mavlink include doesn't work in travis:
https://travis-ci.org/PX4/Firmware/jobs/111996908#L625

If I use the exact same command on my machine, it works.

**Comment by dagar** [comment]
Have you tried `#include <v1.0/common/mavlink.h>`?

**Comment by julianoes** [comment]
@dagar thanks, I'll give it a try.

**Comment by jschall** [comment]
@julianoes looks like there's some ros stuff failing CI tests (src/platforms/ros/nodes/commander/commander.cpp). Looks like it is simple to fix. Should I address problems with it? Can I be made a collaborator here so that I can push to the branch?

@LorenzMeier what is the timeline like for getting this pushed in once it passes CI tests?

@liamstask fyi

**Comment by jschall** [comment]
Which target should I build to reproduce the error? I tried ros_sitl_default but it said that target was deprecated and to use posix_sitl_default (which works)

**Comment by liamstask** [comment]
@LorenzMeier any pointers on debugging the travis failures per @jschall's questions above?

**Comment by dagar** [comment]
@jschall you can open a pull request onto this branch. It looks like you just need to update the ros commander node to use commander_state.

**Comment by jschall** [comment]
There's a new "commander_state" message but no one publishes it as far as I can tell.

**Comment by julianoes** [comment]
@jschall :

> looks like there's some ros stuff failing CI tests (src/platforms/ros/nodes/commander/commander.cpp). Looks like it is simple to fix. Should I address problems with it? Can I be made a collaborator here so that I can push to the branch?

I didn't know about this ROS stuff, let me have a look.

> There's a new "commander_state" message but no one publishes it as far as I can tell.

Oh, good catch. I'll add that.

**Comment by AndreasAntener** [comment]
Jenkins: test this please

**Comment by julianoes** [comment]
I rebased this once again on master. Every time there is some conflicts, so it would be good to flight test this and merge as soon as possible.

@tumbili any chance you could give this a flight test (in the snow :smile:)?

**Comment by AndreasAntener** [comment]
Jenkins: test this please

**Comment by julianoes** [comment]
@LorenzMeier and @liamstask

This would be ready to be merged, I've test flown it today. However, I'd like to hold off the merge until Monday in case it breaks somebody's setup because I'll be offline and not able to resolve conflicts or help debug problems.

**Comment by liamstask** [comment]
sounds good!

**Comment by julianoes** [comment]
Rebased and applied!

**Pull request closed without merging**
