### PR TITLE
Changed sitl targets to be easier to call from  make.

### PR DESCRIPTION
**Pull request by jgoppert**

### CODE REVIEW

**Comment by jgoppert** [comment]
New syntax is:
```bash
make TARGET VEIWER_DEBUGGER
```

examples
```bash
make posix_sitl_default jmavsim
make posix_sitl_default jmavsim_gdb
make posix_sitl_default jmavsim_lldb

make posix_sitl_default gazebo
make posix_sitl_default gazebo_gdb
make posix_sitl_default gazebo_lldb

make posix_sitl_lpe gazebo
make posix_sitl_lpe gazebo_gdb
make posix_sitl_lpe gazebo_lldb

```

**Comment by LorenzMeier** [comment]
Thanks! Applied via rebase.

**Comment by mcharleb** [comment]
@jgoppert I now see this error when running the above

/bin/sh: 1: [: Unix Makefiles: unexpected operator

**Comment by LorenzMeier** [comment]
@mcharleb We'll look into that, meanwhile please continue on sitl_repro or on sitl_bus_fixes. https://github.com/PX4/Firmware/pull/3068

**Comment by dagar** [comment]
@mcharleb You just need to change the "==" to "=" for /bin/sh.

https://github.com/dagar/Firmware/commit/1694230d23ff4b65d22cc83d746dee7a9dfc8d9f

**Comment by LorenzMeier** [comment]
@mcharleb Fix from @dagar applied on master.

**Pull request closed without merging**
