### PR TITLE
Start UAVCAN in the two phases required

### PR DESCRIPTION
**Pull request by LorenzMeier**
@eyeam3 @pavel-kirienko Am I right that this fix is required for UAVCAN?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@pavel-kirienko @davids5 Is the full RAM needed for the UAVCAN app? Can we reduce the stack to 1900 for `uavcan` and 3400 for `uavcan fw srv`

```
 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
 184 uavcan                       4014  3.019  1580/ 2392 240 (240)  w:sem 
 186 uavcan fw srv                1666  1.251  3060/ 5992 140 (120)  w:sem 
```

**Comment by pavel-kirienko** [comment]
This fix would appear to be correct, although I didn't test it. The firmware update logic was implemented mostly by @davids5.

> Is the full RAM needed for the UAVCAN app?

There is no easy way to reduce memory consumption at the moment. If you need the UAVCAN application to free up the memory that it is not actively using at the moment (if there is any), you can invoke `uavcan shrink`; YMMV. More about `shrink` [here](https://github.com/PX4/Firmware/pull/3005).

> Can we reduce the stack to 1900 for `uavcan` and 3400 for `uavcan fw srv`

No.

**Comment by davids5** [comment]
Yes it is 2 operations to be able to  stop the FW server and save RAM.

**Comment by LorenzMeier** [comment]
I think we need an automatic method of shutting down the server on arming then.

**Comment by eyeam3** [comment]
That is done here: https://github.com/PX4/Firmware/blob/master/src/modules/uavcan/uavcan_servers.cpp#L535

There could be a timing issue, if the logger already allocates memory and the server is still active. But I have not fully tested this so far.

**Comment by pavel-kirienko** [comment]
shrink should be invoked too when the update server is shut down, otherwise the UAVCAN app will keep more heap memory than it needs.

**Pull request merged**
