### PR TITLE
Fix mpu9250 driver missing mpu6500 detection issue.

### PR DESCRIPTION
**Pull request by airmind**
**Describe problem solved by this pull request**
Fix new mpu9250 driver missing mpu6500 detection issue. This issue may cause mag calibration fail on any FCUs that use mpu6500 sensor.

**Describe your solution**
Add/recover detection for mpu6500.

**Test data / coverage**
Tested against MindPX/MindRacer/Pixhawk.

### CODE REVIEW

**Comment by dagar** [comment]
Hi @airmind,

We're going through some fairly heavy driver refactoring at the moment (https://github.com/PX4/Firmware/pull/14438, https://github.com/PX4/Firmware/pull/14356, etc). I'll make sure the mindpx is in a good state before we branch master for the next release (hopefully next week).

**Comment by SalimTerryLi** [comment]
Segmentation fault. In the following case:
MPU9250 connected to SPI bus.
AK8963 is accessed by SPI to I2C bridge that 9250 built-in with.

**Comment by airmind** [comment]
@dagar thanks for that. 
Pls let me know if any further actions needed from me.

**Comment by dagar** [comment]
@rolandash there's now a significantly improved dedicated mpu6500 driver. https://github.com/PX4/Firmware/pull/14473

**Comment by rolandash** [comment]
> @rolandash there's now a significantly improved dedicated mpu6500 driver. #14473

Thanks a lot @dagar , this is great. 
Can you also please keep the mpu6000 ? as it also exists in some MindPX revision. I do not want those users got surprised.

**Comment by dagar** [comment]
> > @rolandash there's now a significantly improved dedicated mpu6500 driver. #14473
> 
> Thanks a lot @dagar , this is great.
> Can you also please keep the mpu6000 ? as it also exists in some MindPX revision. I do not want those users got surprised.

I didn't see that in the schematic. Is it an mpu6000 or mpu6500 in the same place (same orientation, chip select, data ready)?

**Comment by rolandash** [comment]
> > > @rolandash there's now a significantly improved dedicated mpu6500 driver. #14473
> > 
> > 
> > Thanks a lot @dagar , this is great.
> > Can you also please keep the mpu6000 ? as it also exists in some MindPX revision. I do not want those users got surprised.
> 
> I didn't see that in the schematic. Is it an mpu6000 or mpu6500 in the same place (same orientation, chip select, data ready)?

Right It is not in schematic. 
6500 is on a isolated IMU module in MIndPX. Since mpu6000 driver was already there, so part of the hardware also used 6000-based module as a drop-in replacement to 6500 isolation IMU module, depends on user's demand. 
It is the same orientation/chip select/data ready. So should be OK that just recover the removed lines.

**Comment by dagar** [comment]
Closing in favor of https://github.com/PX4/Firmware/pull/14473.

@rolandash please be sure to review and test https://github.com/PX4/Firmware/pull/14473 on all variations you'd like supported. Once that's verified I'll make sure it's maintained going forward.

**Comment by rolandash** [comment]
> Closing in favor of #14473.
> 
> @rolandash please be sure to review and test #14473 on all variations you'd like supported. Once that's verified I'll make sure it's maintained going forward.

Looks OK.
Will test it in next few days.

**Comment by rolandash** [comment]
@dagar is Rotation of all motion sensors changed in v1.10 & 1.11? 

lsm303d & lgd20 not working properly now with current rotation param. 
And Sry that I just noticed you changed 6000&6500's rotation, so they seems working fine.

**Comment by dagar** [comment]
> @dagar is Rotation of all motion sensors changed in v1.10 & 1.11?
> 
> lsm303d & lgd20 not working properly now with current rotation param.
> And Sry that I just noticed you changed 6000&6500's rotation, so they seems working fine.

@rolandash the new InvenSense drivers under src/drivers/imu/invensense and enabled in https://github.com/PX4/Firmware/pull/14473 have a new rotation convention. 

We want to return data to the system as +X forward, +Y right, +Z down (right hand).
Screenshot from 2020-03-27 09-24-58

So the convention is now up (face of the sensor) is up (-Z), +X is the same, Y is corrected to maintain the right hand rule (Y => -Y).

It's a bit confusing during the transition, but hopefully will be simpler once I've switched everything over (no change to the lsm303d & lgd20 yet).

**Comment by rolandash** [comment]
thanks for the info @dagar .

lsm303d & lgd20 behaves weird in #14473 , thought it's related to rotation. 
As you mention no changes to them yet, I am not sure what may causing the issue.

Will test more and let you know.

**Comment by dagar** [comment]
Ok, please open a new issue for the lsm303d & l3gd20 and we'll get it resolved before the next release. 

As a start, please verify this. https://github.com/PX4/Firmware/blob/eb1bad018587497928c7d81949397d8e243a8d05/boards/airmind/mindpx-v2/src/spi.cpp#L46-L47

**Comment by rolandash** [comment]
@dagar , there is a mistake in L46,
````
initSPIDevice(DRV_GYR_DEVTYPE_L3GD20, SPI::CS{GPIO::PortB, GPIO::Pin2}, SPI::DRDY{GPIO::PortE, GPIO::Pin14}), 
````

DRDY should be Pin4, not Pin14. Looks like a typo.
However, this is not the reason as DRDY is not used I think, but good to correct it anyway.

I found a more clear statement for lsm303d & l3gd20 issue, after tests on many different combinations of sensors. I will open a new issue soon.

**Comment by dagar** [comment]
> @dagar , there is a mistake in L46,
> 
> ```
> initSPIDevice(DRV_GYR_DEVTYPE_L3GD20, SPI::CS{GPIO::PortB, GPIO::Pin2}, SPI::DRDY{GPIO::PortE, GPIO::Pin14}), 
> ```
> 
> DRDY should be Pin4, not Pin14. Looks like a typo.
> However, this is not the reason as DRDY is not used I think, but good to correct it anyway.
> 

Fixed in https://github.com/PX4/Firmware/pull/14507.

**Pull request closed without merging**
