### PR TITLE
[WIP] Mixer configuration - View, modify mixer parameters then save to a .mix - With px4io and mavlink support

### PR DESCRIPTION
**Pull request by crashmatt**
Rework of previous pull request with additional support for px4io.
https://github.com/PX4/Firmware/pull/4844

**NEW**: [This document describes the system.  It does not describe the px4 implementation:](https://docs.google.com/document/d/1LeQC2qtxqdesNuJ3RAWH_MJ_30xjf-PMN3bd5wtUAUo/edit?usp=sharing)

**NEW:** Modified to access all mixer parameters ie. both input and output mixers for SimpleMixer.
New usage instructions to follow below.
**NEW:** Support through mavlink messages with mavproxy mixer module available here:.
https://github.com/crashmatt/MAVProxy/tree/mixer
**NEW:** Stream all mixer data so a GCS can pick it up.  
**NEW**:  Get mixer connections data so a GCS knows what each mixer is connected to

User instructions in post below.

**BUILD INSTRUCTION:**
Feature included automatically for targets without the 1MB flash limit.
To include in smaller targets define MIXER_TUNING in the board config

**ACTION**: Check that both fmu and io resources are within limits.
  px4io changes are limited to the following changes for mixer config option only:
    5 new 16bit i2c registers and additional case statement for them.
    The set_parameter function and case statement for each mixer type
  
px4io support is done by having a copy of the mixers on the fmu.  The fmu and io changes are kept synchronized.  When a request to generate the mixer file is done, it is done from the fmu copy.

No flight testing is done since I have no time or space for it right now.  SITL will not test this.  HITL might test but this needs review
**ACTION**: Find someone to do testing or get HITL running - Thanks Mark W for first tests

px4io is critically short of memory.  Running the parameters access might push it over the limit.
**ACTION:** Run diagnostics and a suitable soak test for stability

**TODO**
Fix travis errors due to virtual name hiding
Tidy up px4io firmware naming
Limit set parameter changes to appropriate operation mode
Prevent reboot due to mixers not being loaded
Fix hacked mixer save confirmation message
Fix failure to clear local mirror mixers when re-uploading to px4io
Fix mixer naming headers
Fix signed-unsigned mismatch through mavlink for error values (sub count and more?)

**PLANNED:**
- Support on qgc
- Automated test support
- Clean up - not so much left
- Converting XML file to headers

### CODE REVIEW

**Comment by crashmatt** [comment]
px4io is critically short of memory.  Running the parameters access might push it over the limit.
**ACTION:** Run diagnostics and a suitable soak test for stability

**Comment by crashmatt** [comment]
**Typical usage for px4** 
Pre-loaded with aileron-flap-vtail airframe on main and aux mixer.

**Mixer commands**
nsh> mixer
INFO  [mixer] missing command
INFO  [mixer] usage:
INFO  [mixer]   mixer load <device> <filename>
INFO  [mixer]   mixer save <device> <filename>
INFO  [mixer]   mixer list <device>
INFO  [mixer]   mixer params <device> <mixer_index>
INFO  [mixer]   mixer params <device> <mixer_index> <sub_index>
INFO  [mixer]   mixer set <device> <mixer_index> <param_index> <value>
INFO  [mixer]   mixer set <device> <mixer_index> <sub_index> <param_index> <value>
INFO  [mixer]   mixer config <device>

**List of mixers and submixers for main mixer group (px4io)**
nsh> mixer list /dev/pwm_output0
INFO  [mixer] List of mixers:
Mixer count : 8
mixer:0 submixers:2 type:2 id:SIMPLE
mixer:0  submixer:1 type:5 id:SIMPLE_INPUT
mixer:0  submixer:2 type:5 id:SIMPLE_INPUT
mixer:1 submixers:2 type:2 id:SIMPLE
mixer:1  submixer:1 type:5 id:SIMPLE_INPUT
mixer:1  submixer:2 type:5 id:SIMPLE_INPUT
mixer:2 submixers:2 type:2 id:SIMPLE
...etc....

**List of mixers and submixers for aux mixer group (fmu)**
nsh> mixer list /dev/pwm_output1
INFO  [mixer] List of mixers:
Mixer count : 4
mixer:0 submixers:1 type:2 id:SIMPLE
mixer:0  submixer:1 type:5 id:SIMPLE_INPUT
mixer:1 submixers:1 type:2 id:SIMPLE
mixer:1  submixer:1 type:5 id:SIMPLE_INPUT
mixer:2 submixers:1 type:2 id:SIMPLE
mixer:2  submixer:1 type:5 id:SIMPLE_INPUT
mixer:3 submixers:1 type:2 id:SIMPLE
mixer:3  submixer:1 type:5 id:SIMPLE_INPUT

**Parameters for main (px4io), first mixer, output mixer**
nsh> mixer params /dev/pwm_output0 0 0
mixer:0  sub_mix:0 param:0 id:SCALE_NEG value:1.0000
mixer:0  sub_mix:0 param:1 id:SCALE_POS value:1.0000
mixer:0  sub_mix:0 param:2 id:OFFSET value:0.0000
mixer:0  sub_mix:0 param:3 id:OUTPUT_MIN value:-1.0000
mixer:0  sub_mix:0 param:4 id:OUTPUT_MAX value:1.0000

**Parameters for main (px4io), first mixer, first input mixer**
nsh> mixer params /dev/pwm_output0 0 1
mixer:0  sub_mix:1 param:0 id:SCALE_NEG value:1.0000
mixer:0  sub_mix:1 param:1 id:SCALE_POS value:1.0000
mixer:0  sub_mix:1 param:2 id:OFFSET value:0.0000
mixer:0  sub_mix:1 param:3 id:OUTPUT_MIN value:-1.0000
mixer:0  sub_mix:1 param:4 id:OUTPUT_MAX value:1.0000

**Set first parameter on main (px4io), first mixer, first input mixer**
nsh> mixer set /dev/pwm_output0 0 1 0 0.6
mixer:0 sub_mixer:1 param:0 value:0.6000 set success

**Read parameters to verify change**
nsh> mixer params /dev/pwm_output0 0 1
mixer:0  sub_mix:1 param:0 id:SCALE_NEG **value:0.6000**
mixer:0  sub_mix:1 param:1 id:SCALE_POS value:1.0000
etc...

**Show mixer config with changes**
nsh> mixer config /dev/pwm_output0
M: 2
O: 10000 10000 0 -10000 10000
S: 0 0 6000 10000 0 -10000 10000
S: 0 6 10000 10000 0 -10000 10000
M: 2
O: 10000 10000 0 -10000 10000
S: 0 0 10000 10000 0 -10000 10000
S: 0 6 -10000 -10000 0 -10000 10000
... etc...

**Write mixer config to file**
nsh> mixer save /dev/pwm_output0 /fs/microsd/mix.mix
INFO  [mixer] Wrote mixer /dev/pwm_output0 to file /fs/microsd/mix.mix

**Comment by crashmatt** [comment]
**MAVLINK SUPPORT THROUGH PARAMETERS**

The following parameters were added to access the multiple data dimensions of the mixers.
Mavlink access does not give you parameter or mixer naming.  The GCS is expected to handle this.

MIX_GROUP : 0=fmu, 1=px4io
MIX_INDEX : As per NSH commands 
MIX_PARAM_INDEX : As per NSH commands 
MIX_SUB_INDEX : As per NSH commands
MIX_PARAMETER : As per NSH commands

MIX_PARAM_ACTION : 
 * @value -1 Action failed
 * @value 0 No action / Action complete
 * @value 1 Write
 * @value 2 Read
 * @value 3 Read mixer count in a mixer group
 * @value 4 Read mixer or submixer type
 * @value 5 Read submixer count for a mixer in a mixer group
 * @value 100 Store (Future)

MIX_TYPE : As per NSH commands
 * @value 0 None
 * @value 1 Null
 * @value 2 Simple
 * @value 3 Multirotor
 * @value 4 Helicopter
 * @value 5 Simple Input
 * @value 6 Multicopter Rotor

**Comment by LorenzMeier** [comment]
This looks a bit like you need a new MAVLink message to map - what would that need to include to make your use case work?

**Comment by magicrub** [comment]
Hi Matt, would you like me to make an example MAVLink packet for you containing this data?

**Comment by crashmatt** [comment]
A new mavlink message is my preference.  I used parameters since it was easier.
I need some guidance on where to put a new message.  The last time I did this was for matrixpilot and that was a very different animal.

**Comment by crashmatt** [comment]
Oh look, there is the dev guide I had not read.....

**Comment by kd0aij** [comment]
@crashmatt I built and flashed this branch onto an AUAV-X2 (build target px4fmu-v2_default) and this is all I get from "mixer":
```
nsh> mixer
INFO  [mixer] missing command
INFO  [mixer] usage:
INFO  [mixer]   mixer load <device> <filename>
nsh> 
```

**Comment by crashmatt** [comment]
@kd0aij You need to build with target px4fmu-v2_mixer.

**Comment by kd0aij** [comment]
```
nsh> mixer set /dev/pwm_output0 0 1 2 0.2
mixer:0 sub_mixer:1 param:2 value:0.2000 set success
```
changed pwm output period from 1490 to 1590 usec

**Comment by crashmatt** [comment]
@kd0aij  Thanks Mark.  That made my day.

**Comment by kd0aij** [comment]
I guess CI isn't testing the _mixer target. I had to fix a few typos to get this to compile:
https://github.com/kd0aij/Firmware/commit/1401d8d04b3e710f4ef8f277bbc41e3c64c61c89

**Comment by crashmatt** [comment]
Thanks for the test time.  Not sure if I can get from your fix to my repo.

Cl doesn't test this as far as I know. That is something else to learn /
fix.
I thought I had checked this last minute change.  I was bouncing between
the posix_sitl and px4fmu builds so I have missed it.

**Comment by kd0aij** [comment]
I don't know if there's a way for me to generate a PR against your fork, and I expect figuring that out would be much more effort than just typing a few characters :)
The bigger hassle for me is that you're forced to do a full recalibration when you change airframes...

**Comment by crashmatt** [comment]
@LorenzMeier which is the best way to get from mavlink to the mixer driver?  mavlink->ioctl->driver or mavlink->uorb->driver->uorb->mavlink.  Is the non blocking uorb better?
I implemented uorb but ioctl only would limit the complexity and maintenance.

**Comment by LorenzMeier** [comment]
Hi Matt - do you need further support to get this from WIP to final?

**Comment by LorenzMeier** [comment]
@crashmatt We should probably talk about the IOCTL interface. Its deprecated and will eventually get removed because it does not scale well to modern architectures.

**Comment by crashmatt** [comment]
A new PR is opened here:
https://github.com/PX4/Firmware/pull/6960

**Pull request closed without merging**
