### PR TITLE
delete mathlib Vector/Matrix

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
Ran full calibration and compared parameters before and after. No significant differences. Commander didn't require any additional stack either.

**Comment by dagar** [comment]
@PX4/testflights on a couple random boards (fmu-v2, fmu-v4, etc) could you please do some basic bench testing with this branch? Save your parameters from before (master baseline) and after a full calibration on this branch and we'll compare them.

**Comment by santiago3dr** [comment]
Pixracer (V4)
fresh flash with master d40d165
reset all parameters to default and ran full setup
[master.txt](https://github.com/PX4/Firmware/files/1858141/master.txt)

Flashed this PR
reset all parameters to default and ran full setup

Mag calibration just hangs and does not complete; after waiting a few minutes, qgc flagges the fc as disconnected
stuck calibration

These are the parameters with setup until getting stuck at mag calibration
[pr_9181.txt](https://github.com/PX4/Firmware/files/1858143/pr_9181.txt)

**Comment by dagar** [comment]
Definitely need more stack for the mag cal routine.

**Comment by jgoppert** [comment]
I'm looking forward to seeing this merged.

**Comment by dagar** [comment]
We can keep the mat_inverse for now and still get rid of the rest.

**Comment by LorenzMeier** [comment]
@dagar @RomanBapst We need to make sure to bring the Snapdragon fixes onto master and test this rebased onto them.

**Comment by dagar** [comment]
Rebased on master (with snapdragon fixes). Tested snapdragon basic usage and full recalibration of a pixracer.

**Pull request merged**
