### PR TITLE
Logger cmd line

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by tumbili** [comment]
@kd0aij Could you give this a try? You should be able to start and stop the logger from the command line, e.g. 

```
logger start -r 100 -b 20 -e
```

-r log rate in Hz
-b buffer size in kB
-e enable logging on start

**Comment by kd0aij** [comment]
After stopping and restarting the logger, I noticed that there were two log_writer processes, and it seems as though the buffer memory is not freed on stopping:
```
Processes: 26 total, 2 running, 24 sleeping
CPU usage: 46.98% tasks, 0.65% sched, 52.36% idle
Uptime: 203.539s total, 128.137s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
   0 Idle Task                  128136 52.363     0/    0   0 (  0)  READY 
   1 hpwork                       9497  4.654   776/ 1592 192 (192)  w:sig 
   2 lpwork                        792  0.363   356/ 1592  50 ( 50)  w:sig 
   3 init                         1512  0.000  1388/ 2496 100 (100)  w:sem 
 157 log_writer                      0  0.000   340/ 1016  60 ( 60)  w:sem 
  87 gps                            93  0.072   740/ 1192 220 (220)  w:sem 
  89 dataman                         1  0.000   652/ 1192  90 ( 90)  w:sem 
 112 sensors                      5554  2.909  1636/ 1992 250 (250)  w:sem 
 114 commander                     990  0.436  3116/ 3592 140 (140)  w:sig 
 115 commander_low_prio              8  0.000   676/ 2992  50 ( 50)  w:sem 
 123 mavlink_if0                 11308  5.454  2396/ 2696 100 (100)  w:sig 
 124 mavlink_rcv_if0                15  0.000   828/ 2096 175 (175)  w:sem 
 126 mavlink_if1                  2017  0.945  2396/ 2696 100 (100)  w:sig 
 127 mavlink_rcv_if1                14  0.000   828/ 2096 175 (175)  w:sem 
 137 mavlink_if2                  1635  0.727  2396/ 2696 100 (100)  w:sig 
 236 log_writer                    366  0.945   692/ 1016  60 ( 60)  READY 
 235 logger                       3443  8.654  2668/ 3096 250 (250)  w:sig 
 175 attitude_estimator_q        14285  7.054  2148/ 2496 250 (250)  w:sem 
 180 position_estimator_inav      7662  4.000  4796/ 5296 250 (250)  w:sem 
 182 mc_att_control               4634  2.327  1316/ 1496 250 (250)  w:sem 
 196 mc_pos_control               1496  0.799  1212/ 1896 250 (250)  w:sem 
 199 navigator                      10  0.000   780/ 1496 105 (105)  w:sem 
 205 frsky_telemetry                 2  0.000   540/ 1096 200 (200)  w:sem 
 216 mavlink_if3                  7916  3.854  2380/ 2696 100 (100)  w:sig 
 229 mavlink_rcv_if3                17  0.000   828/ 2096 175 (175)  w:sem 
 266 top                           104  3.781  1228/ 1696 100 (100)  RUN   
nsh> commander disarm
nsh> logger: stop log
log_writer: stopped, bytes written: 1127442
```

**Comment by tumbili** [comment]
@kd0aij Yes, I was trying to get rid of that but I haven't found a way yet. I think we need to carefully look how to spawn and stop the logwriter thread.

**Comment by tumbili** [comment]
@LorenzMeier Could you have a look what's up with the overflowed flash region?

**Pull request closed without merging**
