### PR TITLE
Configuration parameter for TeraRanger One

### PR DESCRIPTION
**Pull request by lfrodrigues**
Added configuration parameter for TeraRanger One rangefinder.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! Have you tested this successfully in a full setup?

**Comment by lfrodrigues** [comment]
The driver is working fine in APM but today I realized that we didn't have it in startup scripts / configuration for PX4. 

Honestly I don't know how to enable the parameter. Just having ```trone start``` in rcS works fine so I copied setup from mb12xx as it's equivalent to trone.

**Comment by LorenzMeier** [comment]
Nice, thanks!

**Comment by IeiuniumLux** [comment]
Unless we build the firmware, I guess this will be included in the next 1.4.x release, correct?

**Comment by mzahana** [comment]
I am trying to run the TeraRangerOne with Px4 firmware. I set the corresponding parameter to True on QGC. However, the driver does not start. When I try to start the driver from NSH ```trone start``` it fails.

This is on Pixhawk2.1, latest master at the time of this comment .

What could be the problem?!

**Comment by lfrodrigues** [comment]
@mzahana as the driver in repository is working perfectly I expect to be a problem with your setup or hardware. Please send an email to support@teraranger.com and my colleagues will follow up.

**Comment by abencomo** [comment]
@lfrodrigues the TeraRangerOne still requires the I2C adapter to connect to the Pixhawk, correct?

**Comment by lfrodrigues** [comment]
@abencomo yes it does

**Comment by mzahana** [comment]
So, I am able to use the TeraRanger One wit Pixhawk 1, with stable version 1.5.3.

Does the sensor need to be gimbaled?

**Comment by lfrodrigues** [comment]
Yes you should. 

@mzahana please send your questions to support email as they're not connected to this thread

**Comment by abencomo** [comment]
Does it still need to be gimbaled if you only use it for alt-hold and loiter modes?

**Comment by mhkabir** [comment]
That doesn't seem correct. Gimbaling the sensor will adversely affect the IMU-based tilt-compensation that we apply, which assumes the sensor is rigidly fixed to the bottom of the vehicle.
If you're on default PX4, do not gimbal _any_ rangefinder.

**Comment by mzahana** [comment]
@mhkabir Makes more sense now. Thanks.

**Pull request merged**
