### PR TITLE
Enable I2C2 bus of auav x21

### PR DESCRIPTION
**Pull request by tubeme**
Enable the I2C2 bus of auav x2.1. This change came after a MAG registering 3 times on the I2C bus due to messed initialization script on the x21 board.

We slightly moded the board so we could use the I2C2 bus but now there was no initialization of the bus.

### CODE REVIEW

**Comment by tubeme** [comment]
@davids5 Remember we made this changes when we were fighting the MAG registering on the I2C bus? Can you help me make this work? I want to turn on back the I2C2 bus and use it. I cannot compile so I need binary for this change to see how it goes. I really will appreciate it.

**Comment by dagar** [comment]
@nkhoit can you review this?

**Comment by nkhoit** [comment]
@tubeme How are you connecting to I2C2? It's not broken out to any header. 
I2C2 isn't configured on auav-x21.

**Comment by tubeme** [comment]
@nkhoit we are using a slightly modified board so we made header for the I2C2. It was initialized before #7496. Now it is not.

**Comment by dagar** [comment]
We need to be careful with these defines. There are implications for internal/external buses that go beyond arbitrary naming.

     PX4_I2C_BUS_LED		PX4_I2C_BUS_ONBOARD

Is there any LED on the regular auav/mRo x2.1?

**Comment by tubeme** [comment]
@dagar It is not arbitrary. You can see what are the changes introduced in #7496. I just reverse the changes with a small correction. This correction was one the reasons for not proper initialization of I2C thus registering the external Mag hmc5883 registering as 3 devices.

The problem was rather at a different place.  in the rc.sensors. Also the line 
#define PX4_I2C_BUS_ONBOARD   1 
is wrong in the original auav x21 script prior to #7496 
it should be
#define PX4_I2C_BUS_ONBOARD   2

the same as in FMUv2 driver script.

The FMUv2 and auav are the same in terms of cpu thus with the same IOs.
auav x2.1 has I2C2 bus it is just not connected to the outside world. But we connected a LED module to see the status (the same way it is connected in the original FMUv2). But it does not work now...

**Comment by nkhoit** [comment]
@tubeme Have you tested if this works on your hardware? I ran it on my X2.1 and nothing seemed too wrong. But it's not easy for me to check if I2C2 works.
I'm pretty sure we'll have to configure the port here as well: https://github.com/PX4/Firmware/blob/master/nuttx-configs/auav-x21/nsh/defconfig#L426

**Comment by tubeme** [comment]
@nkhoit That was my point. I have no way to compile the px4. So if you could share the auav x21 binary that you compiled, I will flash it and test it with my hardware? I will appreciate it. Then I will report back here.

**Comment by nkhoit** [comment]
You'll also need to add

~~~
#define GPIO_I2C2_SCL    GPIO_I2C2_SCL_1
#define GPIO_I2C2_SDA    GPIO_I2C2_SDA_1
#define GPIO_I2C2_SCL_GPIO \
  (GPIO_OUTPUT|GPIO_OPENDRAIN|GPIO_SPEED_50MHz|GPIO_OUTPUT_SET|GPIO_PORTB|GPIO_PIN10)
#define GPIO_I2C2_SDA_GPIO \
   (GPIO_OUTPUT|GPIO_OPENDRAIN|GPIO_SPEED_50MHz|GPIO_OUTPUT_SET|GPIO_PORTB|GPIO_PIN11)
~~~
to https://github.com/PX4/Firmware/blob/master/nuttx-configs/auav-x21/include/board.h
as well.

**Comment by nkhoit** [comment]
Here's a binary file you can upload and try. [auav-x21_PR8138.zip](https://github.com/PX4/Firmware/files/1407738/auav-x21_PR8138.zip)

**Comment by tubeme** [comment]
Hey @nkhoit I want to thank you very much! It works perfect, the LEDs are showing the status :). I tried the firmware to un-moded X21 and it does not create a problem if there is no I2C2 connected. I checked carefully to see if there is going to be a problem with the Mag and Airspeed. Everything is perfect. Can this be added to the master? Otherwise we have to create this custom hack every time there is new version.

**Comment by dagar** [comment]
Is this still wanted?

**Comment by tubeme** [comment]
Yes e want this. :)

**Comment by dagar** [comment]
Can you verify this is harmless for a regular mRo X21?
@nkhoit

**Comment by tubeme** [comment]
Hello @nkhoit can you please verify if there is no problem with this i2c2 enabled with regular AUAV X2.1 board.

We test it and there are no problems...

Thanks in advance

**Comment by dagar** [comment]
Is this still needed?

**Comment by tubeme** [comment]
@dagar Yes Daniel if possible?

**Comment by davids5** [comment]
From what I see on the Schematic AUAV_X21_FMU_V2_R01 - 11/10/2017

PB10 is now used as KILL. 
PB11 is a no connect.
image

What will happen for the users with something connected to KILL?

@pkocmoud - is the above the "as shipped" Schematic?

**Comment by pkocmoud** [comment]
@davids5 - That snip is correct for the shipping x2.1

**Comment by pkocmoud** [comment]
@davids5 - It is just a GPIO, the idea was for it to be connected to a power switch to allow the FC to disable the vehicle or deploy a independent recovery device in case of emergency. It did not seem to get much traction.

To the best of my knowledge, nobody has ever used it nor suggested code to enable it.

You can just treat it as an available IO pin.

**Comment by dagar** [comment]
Needs to be rebased.

**Pull request closed without merging**
