### PR TITLE
IO firmware: Output a disarmed pulse on lockdown

### PR DESCRIPTION
**Pull request by LorenzMeier**
@kd0aij This should lock the system down with a disarmed pulse.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@kd0aij could you cross test somehow? Don't want to interrupt your workflow though with the test.

**Comment by kd0aij** [comment]
cherry-picked into master at f10770a 11Feb, kill switch had no effect on v2, works properly on v4

**Comment by LorenzMeier** [comment]
Did your v2 config have a disarmed pulse set? It will not work without.

**Comment by LorenzMeier** [comment]
And we're you using the IO or FMU outputs / main / aux?

**Comment by kd0aij** [comment]
QAV250 config uses quad_x mixer, and 
PWM_DISARMED = 900
PWM_AUX_DISARMED = 1000

**Comment by LorenzMeier** [comment]
Rebased, added test command, force pushed.

**Comment by LorenzMeier** [comment]
Fixed and tested on master.

**Pull request closed without merging**
