### PR TITLE
add boolean parameters to enable/disable each sensor

### PR DESCRIPTION
**Pull request by dagar**
This was merged earlier, but then reverted. Further testing required.

### CODE REVIEW

**Comment by dagar** [comment]
@priseborough the change in this PR was merged a couple weeks ago, but you reverted it and I didn't have time to investigate. What issue did you see?
https://github.com/PX4/Firmware/commit/b3d045d4d0ceda861dc52a8002d754821159cf99

I've resurrected the commit and tried it on a pixracer and in SITL without issue.

**Comment by priseborough** [comment]
I reverted  commit 48b237f5aadeb95febdcc993554bd775c3252fde because on the pixracer board I was using it was causing the EKF to not start. The parameters should be  used to disable, not enable the sensor. That way they will be enabled by default even if the param does not load.

**Comment by dagar** [comment]
I can change the initial value for the temporary to default to 1 (enabled).

Can you try this branch on your pixracer setup?

**Comment by priseborough** [comment]
OK, will do.

**Comment by priseborough** [comment]
This branch works on my setup

**Comment by priseborough** [comment]
Can you initialise the temporary to 1 (enabled). The startup default should be to use sensors.

**Comment by dagar** [comment]
Thanks for testing again. Device enabled initial value changed to 1 (squashed into first commit).

**Comment by dagar** [comment]
I split the param metadata files by index so that it's easy to add more and compare to keep them consistent (they weren't). Later I was thinking of adding something to generate duplicate params like this at build time.

**Comment by dagar** [comment]
This should go into v1.7.0 for users that hit mag inconsistencies.

**Pull request merged**
