### PR TITLE
process_sensor_caldata.py: skip accel or gyro if temperature is NAN

### PR DESCRIPTION
**Pull request by dagar**
FYI @NicolasM0

### CODE REVIEW

**Review by NicolasM0 — APPROVED** [review]

**Comment by NicolasM0** [comment]
If thermal compensation is enabled but a sensor id is not found in TC_* parameters, an error appear: 
` ERROR [temperature_compensation] gyro init: failed to find device ID 4325386 for                          instance 2`

**Comment by dagar** [comment]
> If thermal compensation is enabled but a sensor id is not found in TC_* parameters, an error appear:
> ` ERROR [temperature_compensation] gyro init: failed to find device ID 4325386 for instance 2`

I was considering that to be a feature. Would you like to change it?

**Comment by NicolasM0** [comment]
I was thinking that this file should be changed to add the sensor id in parameters even if temperature is nan and let other TC_* par for this sensor to 0 to avoid this error.

**Comment by dagar** [comment]
> I was thinking that this file should be changed to add the sensor id in parameters even if temperature is nan and let other TC_* par for this sensor to 0 to avoid this error.

That could work, although I have a slight preference for not carrying the dead weight. If anything I was more interested in the case where the sensor is calibrated against a different temperature source (perhaps configurable per instance), however it doesn't seem to matter here.

**Pull request merged**
