### PR TITLE
[WIP] update micro-CDR to latest

### PR DESCRIPTION
**Pull request by dagar**
The micro-cdr api has changed a bit. Not yet functional.

### CODE REVIEW

**Comment by TSC21** [comment]
It seems ti is getting the same problem as I am in my local toolchain: http://ci.px4.io:8080/blue/organizations/jenkins/Firmware/detail/pr-microcdr_update/1/pipeline#step-642-log-59

**Comment by TSC21** [comment]
@dagar were you able to build this locally?

**Comment by dagar** [comment]
No not fully, it still needs a few things updated to the new API in `msg/templates/uorb_microcdr`.

Try it in sitl first (posix_sitl_rtps), it's getting a lot further http://ci.px4.io:8080/blue/organizations/jenkins/Firmware/detail/pr-microcdr_update/1/pipeline/58#step-642-log-59.
Nuttx will be another small toolchain change.

**Comment by TSC21** [comment]
@dagar so you want to take this further or should I step in?

**Comment by dagar** [comment]
Continued in https://github.com/PX4/Firmware/pull/9651

**Pull request closed without merging**
