### PR TITLE
ecl: attitude_fw update

### PR DESCRIPTION
**Pull request by tstastny**
- move angular rate limits to body angular rates
- handle rattitude/acro vs attitude mode rate limits

updates ecl submodule, see PX4/ecl#404.
see also PX4/ecl#402 for details.

(follow-up from #9017)

### CODE REVIEW

**Comment by tstastny** [comment]
@dagar  I initialized the _flag_control_attitude_enabled_last to false, and removed the setters from the param update function. however - i also added the params_updated bool to the reset limits condition, to make sure we catch scenarios where the mode does not change, but perhaps someone sets a new limit with a param update.

let me know if I've missed any other corner cases.

**Comment by dagar** [comment]
Did you update the submodule to point at the new branch in PX4/ecl?

**Comment by tstastny** [comment]
> Did you update the submodule to point at the new branch in PX4/ecl?

I believe so. I checked out PX4/ecl/pr-fw_att_lim_body_rates before amending the commit. The hash matches. I can try again though after rebase, unless you can think of something else I could have possibly done wrong.

**Comment by dagar** [comment]
This looks good. Let's do a bit of testing (SITL is fine) that both exercises the full ecl/attitude_fw controllers and jumps back and forth between acro, rattitude, etc a few times.

**Comment by LorenzMeier** [comment]
@tstastny Could you do the SITL testing and share a log here?

**Comment by tstastny** [comment]
> @tstastny Could you do the SITL testing and share a log here?

on my list for today - will upload this afternoon

**Comment by tstastny** [comment]
See SITL logs with various modes switching back and forth and giving full rates.

https://review.px4.io/plot_app?log=5b1b0e2a-64b2-4220-87f9-fc5fbee91392

Rattitude and Acro modes allow the acro max rates, while Stabilized and Altitude modes allows only the stabilized max rates. A little harder to see the Rattitude threshold effects (I was not so good at flying this blind.. hard to see the plane in Gazebo). But I definitely saw the difference when passing the 80% threshold that was set.

**Comment by dagar** [comment]
Colourful testflight!

image

**Comment by dagar** [comment]
ECL side merged, I'm going to add a commit to this PR that updates ECL, then squash them together on merge.

**Pull request merged**
