### PR TITLE
low pass manual velocity setpoint

### PR DESCRIPTION
**Pull request by tumbili**
Tested in SITL, feels really good. Needs outdoor testing.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Would be awesome if we could rush the testing for that. Its on the super high wanted list.

**Comment by LorenzMeier** [comment]
How complicated would it be to include the acceleration limit for auto-setpoints? It should be something like
```
if ((vel_curr - vel_commanded).length() > accel_max * dt) {
  vel_setpoint = vel_setpoint * ((accel_max * dt) / (vel_curr - vel_commanded).length());
} else {
  vel_setpoint = vel_commanded;
}
```
This should apply to all flight modes. Can you add that before investing the time for the outdoor flight test?

**Comment by tumbili** [comment]
@LorenzMeier I rechecked the code and found the tilt limitation here https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L1357
I think this is indirectly already an acceleration limit. Moreover, it's parameter is more intuitive to set because everybody can imagine tilt and knows what it will mean for the system.

**Comment by LorenzMeier** [comment]
We might want to rename that, because its not actually limiting the angle (which can still go much further) but how strong the acceleration can be, expressed in equivalents of lateral acceleration.

What it does not account for is drag. Which means that if you set this to a narrow limit you're limiting the top speed, even if the system is not making any abrupt velocity changes.

**Comment by LorenzMeier** [comment]
Or in other words: Its not damping change rate, but only absolute angle.

**Comment by tumbili** [comment]
Closing in favour of #3322 The result is not the same but it has a similar effect on the quad.

**Pull request closed without merging**
