### PR TITLE
Cw fix headers

### PR DESCRIPTION
**Pull request by CarloWood**
These are the last commits that I have related to the Tools/fix_headers.sh script, including the script itself.
After merging this, an admin can run the script to see what it does. I wouldn't immediately push the result to master because it's a rather large commit and perhaps we can find a smart(er) way to get it in without giving everyone with branches that changed one of more #include's a headache.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Perfect, looks good.

**Comment by CarloWood** [comment]
Just rebased to current master. No collisions.

**Comment by CarloWood** [comment]
Just rebased again to current master. No collisions.
Now the dust has settled on qurt, can this be merged please?
We can talk about running the script and getting the generated changes in later.

**Comment by CarloWood** [comment]
@LorenzMeier I don't think that circleci failure is my fault?

**Comment by dagar** [comment]
@CarloWood I'm not sure why docker pull failed on circleci, but it's fixed now.

**Comment by CarloWood** [comment]
@dagar Thanks!

**Pull request merged**
