### PR TITLE
durandal-v1:Bootloader

### PR DESCRIPTION
**Pull request by davids5**
Change PID to 0x4b:
     Holybro obtained their own PID and VID but APM did not follow
     the PX4 convention of makeing the board_id (0x8b) match the PID)

   Incorporated the Upstream Bootloader state sequencing checking change.

   Change the usb cout to send all chars in 1 write.

@bkueng   - Please test on your machine. FYI @LorenzMeier

### CODE REVIEW

**Comment by bys1123** [comment]
No offence, but looks like APM is also 0x4b: 
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/hwdef/Durandal/hwdef-bl.dat

**Comment by davids5** [comment]
@bys1123 None taken - just stating the facts that we had to change the PX4 USB configuration to match.

The PID is the the USB Product ID that Holybro registered. 
The BOARD_TYPE aka (board_id) is the PX4 firmware ID. 

PX4 has been making the value the same for a all FMUv5 and up.

**Comment by bys1123** [comment]
Get it, Thanks!

**Comment by bys1123** [comment]
@davids5 Is that some major differents between opencm3 bootloader and nuttx-based bootloader?

**Comment by davids5** [comment]
yes. Why do you ask?

**Comment by bys1123** [comment]
@davids5 Some Chinese companies are starting developments on Durandal, or porting PX4 to other H7 chips to fit their autopilots. So they hope to know what they should take care on nuttx bootloader. Especially some of them is used to opencm3 bootloader, so if there are some quick guide they glad to know it.

**Comment by davids5** [comment]
@bys1123 

There is no STM32H7 support in the opencm3.  So there is no PX4 H7 opencm3 bootloader.

There have been major changes in the bootloader (the repos on Bootloader and the addition of the H7 bootloader located in Firmware) 

Companies should monitor all pull request on the Bootloader and Firmware git Repositories.
To be able to update the files they are installing on products when changes are made.

When updates are made to the bootloader on either the Bootloader or Firmware Repo. Companies should pull and build the latest bootloader - then install them on one or two units and verify that: 
            1) make upload - works
            2) QGC - works
            3) Any other tools they use still work

If Companies run into any problems they should file an Issue in the repo and assign it to me (@davids5).

If all the tests pass then the company should use then new set of files in their production.

**Comment by bys1123** [comment]
Thanks!

**Pull request merged**
