### PR TITLE
WIP: vtol pusher for mc cruise

### PR DESCRIPTION
**Pull request by sanderux**
first attempt at standard vtol using pusher for forward flight in MC mode

### CODE REVIEW

**Comment by sanderux** [comment]
Currently facing SITL issues

**Comment by LorenzMeier** [comment]
I didn't review the patch line by line, but the general architecture is looking great!

**Comment by tumbili** [comment]
@sanderux I fixed this up and tested it in SITL. It works really well. You can also test it in manual mode with a game pad, flies great! I assume the problems you had were related to timing, I don't have any issues so far.

**Comment by LorenzMeier** [comment]
@AndreasAntener @SimonWilks Please add to test flight queue

**Comment by tumbili** [comment]
vtol_pusher

**Comment by sanderux** [comment]
Outside tested, flies fantastic!
Manual flight
Log: http://logs.uaventure.com/view/ZRcMKLShRphYSju4DcC2cN
Video:  https://drive.google.com/file/d/0B27AvDmVit4KOVJtcjMtTk9SdzA/view?usp=sharing

/cc @AndreasAntener @LorenzMeier

**Comment by sanderux** [comment]
And a mission mode, it seemed to overshoot the waypoint a little bit
Log: http://logs.uaventure.com/view/WTgKa7RtKGBEnBwBJXWSR3
Video: https://drive.google.com/file/d/0B27AvDmVit4KQkNHTlhfc002Wms/view?usp=sharing

**Comment by LorenzMeier** [comment]
Nice! I presume we are sure that the back pitch / braking motion is not affected by this patch?

The other question I have is on the control accuracy: do we maybe always need to provide a reasonable amount of forward pitch with the quad motors to ensure attitude authority and only add some additional force with the pusher?

My apologies if that's already done, just from the ground track it looks like the dynamics changed considerably.

**Comment by sanderux** [comment]
The back pitch was all me, it was to see if it would not engage the pusher: http://logs.uaventure.com/view/ZRcMKLShRphYSju4DcC2cN#RC_Raw_PLOT

The setpoint is updated to 5 degrees max (param), so it is indeed adding a little forward pitch while flying with pusher: https://github.com/PX4/Firmware/pull/3848/files#diff-e77eee61c15714b4d081bdf856470e46R292.

From a flight perspective it was perfect in manual flight. 
in mission it felt like it overshot the waypoints a little bit.

**Comment by LorenzMeier** [comment]
What is the transfer function for the pusher? We likely need to reduce its influence quite a bit to match the other axis.

**Comment by sanderux** [comment]
The influence seemed quite low when flying. Maybe we could go even less, tomorrow there will be some wind for me to test in.

**Comment by sanderux** [comment]
A mission on this branch shows a very big overshoot on the back transition.
There was 23kph (6.3m/s) wind, the forward and back transition where done nose in wind.

Log: http://logs.uaventure.com/view/EJHhFbmVrkJ3S9cJuwYdmB
Video: https://drive.google.com/file/d/0B27AvDmVit4KRF9rRGFFVjNaTkE/view

**Comment by sanderux** [comment]
This is a manual flight in high wind conditions. In loiter the pusher was not used:
Log: http://logs.uaventure.com/view/yeabxkikE26QMKyCPxrbGQ
Video: https://drive.google.com/file/d/0B27AvDmVit4KLVVyazdqTWNRZkE/view?usp=sharing

**Comment by tumbili** [comment]
@sanderux I'll look at the logs and see if we can improve something.

**Comment by sanderux** [comment]
This could also be related to my 4 sec back trans. I'll try 3 next time

**Comment by tumbili** [comment]
@sanderux Generally, I don't see how this PR could influence the overshooting of the waypoints. The backtransition is done open loop (position controller not active) and as soon as it kicks in it will try to brake rather than to use the pusher to fly forward. I think we could address the overshooting in a different issue and bring this one in. What do you think? @AndreasAntener

**Comment by AndreasAntener** [comment]
What about the comment from Lorenz?
> What is the transfer function for the pusher? We likely need to reduce its influence quite a bit to match the other axis.

This was also the reason why I asked you if the velocity controller might have difficulties, because it will react differently in one direction compared to the others.

**Comment by tumbili** [comment]
@AndreasAntener It depends on your pusher motor. If it's thrust characteristics are very different to the quad motors then we might need a parameter to scale it down or up.

**Comment by tumbili** [comment]
@AndreasAntener So let me add a parameter which we set to 1 as default. The log files should show if the parameter needs to be adjusted.

**Comment by AndreasAntener** [comment]
@tumbili cool
@sanderux I quickly checked your logs for the overshoot. It still had quite some speed after the 4 sec back transition so it traveled even further. The problem is not the pusher (it's not active during the back transition) but the actually the position controller who doesn't know you were still floating off path after the transition. I have an idea how we can resolve this, hoping to have something soon.

**Comment by sanderux** [comment]
The overshoot is not the back transition (it overshoots there too but that was not what i meant). The overshoot is noticeable when it travels to the final land waypoint. 

What i think is happening is that the efficiency with which the pusher moves the vehicle through the air is much higher so it holds more kinetic energy. I have limited the max horizontal velocity to improve backtrans performance but this seems to cause a little overshoot, that overshoot is bigger with pusher engaged.

**Comment by sanderux** [comment]
I forgot to mention i see this overshoot happening in normal MC navigation too:
have a look here: http://logs.uaventure.com/view/WTgKa7RtKGBEnBwBJXWSR3

There is no transition, only manual flight and massive overshoot

**Comment by tumbili** [comment]
@sanderux @AndreasAntener I added a parameter "VT_FWD_THRUST_SC" to allow scaling of the pusher thrust used to accelerate forward. This is rebased on master.

**Comment by LorenzMeier** [comment]
Nice, sounds like we can move to test flights!

**Comment by AndreasAntener** [comment]
Hey, great stuff, did a manual and a mission flight today:
http://logs.uaventure.com/view/vfaf9nL4JEBc45Rau5UzV7
http://logs.uaventure.com/view/4ECff5bcpDosoX8JzF2TDo

**Comment by LorenzMeier** [comment]
Nice! Good to merge then?

**Comment by AndreasAntener** [comment]
I have one question after looking at my logs: do we have an issue in the attitude controller because it now never actually meets the pitch setpoint?

**Comment by tumbili** [comment]
@AndreasAntener Hehe, I think flight performance is ok because the vehicle should not be pitching forward because we instead are using the pusher to move forward. However, you are right in the sense that we should correct the desired pitch angle in the attitude setpoint topic. I'll do that quickly!

**Comment by tumbili** [comment]
@LorenzMeier @AndreasAntener @sanderux Fixed, can be merge after check pass!

**Comment by AndreasAntener** [comment]
Oh, now that I see your fix I of course I got this wrong. Thanks for the log fix, will prevent further confusion on my side ;)

**Comment by tumbili** [comment]
@sanderux @AndreasAntener @LorenzMeier One more thing. Do you think we should disable this when the throttle scale parameter is set to 0?

**Comment by tumbili** [comment]
I mean do we want to give a user the chance to fly old school?

**Comment by AndreasAntener** [comment]
That reminds me, although it would be very cool to have this enabled by default, there is a problem for VTOLs like ours where we don't have any FW prop clearance on the ground. Depending on the takeoff or landing it could spin it up. ?

**Comment by tumbili** [comment]
@AndreasAntener I should have never said anything :-D

**Comment by AndreasAntener** [comment]
Could you enable it depending on ground offset at boot from a range finder please? ;)

**Comment by sanderux** [comment]
I think the final approach could also be based on baro then the offset is high enough.
even my delta ing is able to hold attitude when not moving. and descend doesnt really take a high toll on the quad drive

**Comment by tumbili** [comment]
Merged!

**Pull request merged**
