### PR TITLE
Add info and usage argument defaults and add doxy documentation in px4_module_params.h and px4_module.h.

### PR DESCRIPTION
**Pull request by mcsauder**
Hi,
This PR adds checks for `info` and `usage` arguments to the ModuleBase class `main()` argument parser, adds doxy documentation in px4_module_params.h and px4_module.h, and orders the argument parsing to be `start`, `status`, then `stop`.

Let me know if you have any questions on this PR!

-Mark

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice, thanks!

**Comment by mcsauder** [comment]
@hamishwillee , I just re-read your above comments, thank you for your thoughtful suggestions.  I agree with everything your wrote.

@roseyangyu , this was a little bit difficult for me as well when I first implemented a ModuleBase inheritance structure.  You will need to ensure that you are correctly inheriting from ModuleBase and declaring and defining the method and virtual method inheritance architecture correctly... Could you perhaps open an issue to continue this discussion or post a link to your code so that we can observe its use in context?

**Comment by roseyangyu** [comment]
My code is same as vmount.cpp. The difference is that gimbal_airwing_thread_main only.

static int gimbal_airwing_thread_main(int argc, char *argv[])
{
    while(!thread_should_exit){
    if(argc > 0){
        if (!strcmp(argv[0],"setangle")){
            const char *axis_name[3] = {"roll","pitch","home"};
            int angle;

            if (argc == 3) {
                bool found_axis = false;

                for (int i = 0 ; i < 3; ++i){
                    if(!strcmp(argv[1],axis_name[i])){
                        long angle_deg = strtol(argv[2],nullptr,0);
                        angle = (int)angle_deg;
                        G.set_angle(i,angle);//angle need
                        found_axis = true;
                    }//roll/pitch
                }//for
                if (!found_axis){
                    usage();
                    PX4_INFO("set failed");
                    return -1;
                }
                return 0;
            }//argc = 3

        }//setangle
        PX4_INFO("Input gimbal_airwing setangle roll/pitch/home angle please");
    }//argc>0
    return -1;
    }

    thread_running = false;
    return 0;
}

**Comment by roseyangyu** [comment]
> My code is same as vmount.cpp. The difference is that gimbal_airwing_thread_main only.
> 
> static int gimbal_airwing_thread_main(int argc, char *argv[])
> {
> while(!thread_should_exit){
> if(argc > 0){
> if (!strcmp(argv[0],"setangle")){
> const char *axis_name[3] = {"roll","pitch","home"};
> int angle;
> 
> ```
>         if (argc == 3) {
>             bool found_axis = false;
> 
>             for (int i = 0 ; i < 3; ++i){
>                 if(!strcmp(argv[1],axis_name[i])){
>                     long angle_deg = strtol(argv[2],nullptr,0);
>                     angle = (int)angle_deg;
>                     G.set_angle(i,angle);//angle need
>                     found_axis = true;
>                 }//roll/pitch
>             }//for
>             if (!found_axis){
>                 usage();
>                 PX4_INFO("set failed");
>                 return -1;
>             }
>             return 0;
>         }//argc = 3
> 
>     }//setangle
>     PX4_INFO("Input gimbal_airwing setangle roll/pitch/home angle please");
> }//argc>0
> return -1;
> }
> 
> thread_running = false;
> return 0;
> ```
> 
> }

when I input gimbal_airwing status and gimbal_airwing stop,nsh is shot down.

**Comment by roseyangyu** [comment]
I have solved.In my code I have a while() fun don't end.Thanks!

**Pull request merged**
