### PR TITLE
add new asymmetric airframe for Spedix S250AQ

### PR DESCRIPTION
**Pull request by kd0aij**
@anton-matosov This new airframe spec also accounts for the fact that the S250AQ front motors are closer to the CG than the rear motors (along the X axis).  I'm not sure this actually makes much difference though, except possibly in the way the mixer logic handles extreme thrust differentials.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@dagar I'm disabling CircleCI since its unreliable.

**Comment by LorenzMeier** [comment]
@kd0aij Because airframe configs go into flash we first need to introduce a way to load new racer configs only in Pixracer, as they will over-commit Pixhawk.

**Comment by kd0aij** [comment]
@LorenzMeier Do you have any data or analysis which shows any disadvantages in using the quad_x mixer for an asymmetric frame?

**Comment by LorenzMeier** [comment]
Yes, you loose roll / pitch tracking on yawing. So it is important.

**Comment by kd0aij** [comment]
Thanks, I haven't seen a problem with my 250s, but they're overpowered compared to "normal" setups.

**Comment by LorenzMeier** [comment]
Please add to any new config and any new mixer for racers:
```
# @board px4fmu-v1 exclude
# @board px4fmu-v2 exclude
```

**Comment by anton-matosov** [comment]
@kd0aij I had all kind of problems with asymmetric frame unless I fixed mixing. But that was on the big and heavy SK450-deadcat frame.

**Comment by kd0aij** [comment]
now dependent on #6111

**Comment by LorenzMeier** [comment]
@kd0aij Can you review and approve the rebased version here? https://github.com/PX4/Firmware/pull/6116

**Pull request closed without merging**
