### PR TITLE
Attitude estimator Q failsafe & vibration level estimation

### PR DESCRIPTION
**Pull request by LorenzMeier**
Done, good to go.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This gets us now a pretty neat output:
```bash
nsh> attitude_estimator_q status
attitude_estimator_q: gyro status:
attitude_estimator_q: validator: best: 0, prev best: 0, failsafe: NO (# 0)
sensor #0:
        mean:  -0.0010 lp:  -0.0010 RMS:   0.0017
        mean:   0.0025 lp:   0.0025 RMS:   0.0011
        mean:  -0.0001 lp:  -0.0001 RMS:   0.0005
sensor #1:
        mean:  -0.0011 lp:  -0.0011 RMS:   0.0030
        mean:  -0.0013 lp:  -0.0012 RMS:   0.0032
        mean:  -0.0014 lp:  -0.0015 RMS:   0.0027
sensor #2:
        no data
attitude_estimator_q: accel status:
attitude_estimator_q: validator: best: 0, prev best: 0, failsafe: NO (# 0)
sensor #0:
        mean:   1.2787 lp:   1.2787 RMS:   0.0184
        mean:   0.2487 lp:   0.2487 RMS:   0.0126
        mean:  -9.6933 lp:  -9.6921 RMS:   0.1135
sensor #1:
        mean:   1.0938 lp:   1.0935 RMS:   0.0309
        mean:   0.2340 lp:   0.2340 RMS:   0.0271
        mean:  -9.6087 lp:  -9.6075 RMS:   0.1172
sensor #2:
        no data
attitude_estimator_q: mag status:
attitude_estimator_q: validator: best: 0, prev best: 0, failsafe: NO (# 0)
sensor #0:
        mean:   0.2869 lp:   0.2869 RMS:   0.0042
        mean:   0.1720 lp:   0.1720 RMS:   0.0027
        mean:   0.4019 lp:   0.4018 RMS:   0.0048
sensor #1:
        mean:   0.1289 lp:   0.1288 RMS:   0.0020
        mean:  -0.3038 lp:  -0.3037 RMS:   0.0037
        mean:   0.5017 lp:   0.5017 RMS:   0.0059
sensor #2:
        no data
```

**Comment by LorenzMeier** [comment]
If I let the MPU6K stop updating things are detected correctly:
```
nsh> mpu6000 stop
nsh> attitude_estimator_q status
attitude_estimator_q: gyro status:
attitude_estimator_q: validator: best: 1, prev best: 0, failsafe: YES (# 1)
sensor #0:
        mean:   0.0000 lp:   0.0000 RMS:   0.0014
        mean:   0.0021 lp:   0.0021 RMS:   0.0010
        mean:  -0.0006 lp:  -0.0006 RMS:   0.0005
sensor #1:
        mean:  -0.0007 lp:  -0.0007 RMS:   0.0029
        mean:  -0.0014 lp:  -0.0014 RMS:   0.0031
        mean:  -0.0007 lp:  -0.0007 RMS:   0.0027
sensor #2:
        no data
attitude_estimator_q: accel status:
attitude_estimator_q: validator: best: 1, prev best: 0, failsafe: YES (# 1)
sensor #0:
        mean:   1.2675 lp:   1.2675 RMS:   0.0127
        mean:   0.2499 lp:   0.2499 RMS:   0.0121
        mean:  -9.7169 lp:  -9.7165 RMS:   0.0575
sensor #1:
        mean:   1.0812 lp:   1.0812 RMS:   0.0284
        mean:   0.2280 lp:   0.2280 RMS:   0.0268
        mean:  -9.6134 lp:  -9.6131 RMS:   0.0658
sensor #2:
        no data
attitude_estimator_q: mag status:
attitude_estimator_q: validator: best: 0, prev best: 0, failsafe: NO (# 0)
sensor #0:
        mean:   0.2872 lp:   0.2871 RMS:   0.0030
        mean:   0.1714 lp:   0.1714 RMS:   0.0021
        mean:   0.4009 lp:   0.4009 RMS:   0.0027
sensor #1:
        mean:   0.1284 lp:   0.1284 RMS:   0.0017
        mean:  -0.3042 lp:  -0.3042 RMS:   0.0021
        mean:   0.5017 lp:   0.5017 RMS:   0.0032
sensor #2:
        no data
```

**Comment by LorenzMeier** [comment]
Triggering an MPU failure leads to the intended failsafe:
```
nsh> telem> SENSOR FAILSAFE! RETURN TO LAND IMMEDIATELY

nsh> attitude_estimator_q status
attitude_estimator_q: gyro status:
attitude_estimator_q: validator: best: 1, prev best: 0, failsafe: YES (# 1)
sensor #0:
        mean:   0.0006 lp:   0.0006 RMS:   0.0864
        mean:   0.0018 lp:   0.0018 RMS:   0.1768
        mean:   0.0000 lp:   0.0000 RMS:   0.0740
sensor #1:
        mean:   0.0015 lp:   0.0015 RMS:   0.0884
        mean:  -0.0033 lp:  -0.0033 RMS:   0.1786
        mean:  -0.0019 lp:  -0.0019 RMS:   0.0730
sensor #2:
        no data
attitude_estimator_q: accel status:
attitude_estimator_q: validator: best: 1, prev best: 0, failsafe: YES (# 1)
sensor #0:
        mean:   0.5106 lp:   0.5107 RMS:   0.2481
        mean: -47.8880 lp: -47.8845 RMS:   0.2852
        mean: -10.1183 lp: -10.1182 RMS:   0.4184
sensor #1:
        mean:   0.1986 lp:   0.1986 RMS:   0.2541
        mean:  -0.5225 lp:  -0.5224 RMS:   0.6017
        mean:  -9.6777 lp:  -9.6776 RMS:   0.4319
sensor #2:
        no data
attitude_estimator_q: mag status:
attitude_estimator_q: validator: best: 0, prev best: 0, failsafe: NO (# 0)
sensor #0:
        mean:   0.1724 lp:   0.1724 RMS:   0.0031
        mean:   0.2828 lp:   0.2828 RMS:   0.0049
        mean:   0.3943 lp:   0.3943 RMS:   0.0024
sensor #1:
        mean:   0.2297 lp:   0.2297 RMS:   0.0050
        mean:  -0.1666 lp:  -0.1666 RMS:   0.0028
        mean:   0.5178 lp:   0.5178 RMS:   0.0027
sensor #2:
        no data
```

**Comment by LorenzMeier** [comment]
@kd0aij @tumbili @sjwilks @AndreasAntener This is good to go for a test flight. I would want to have this in the v1.1 release because we have seen user reports with failed sensors in the past.

**Comment by LorenzMeier** [comment]
I flew this on 4 short but aggressive flights with no obvious issues:
http://dash.oznet.ch/view/E6xC85LzYKrftB2DSQj54j
http://dash.oznet.ch/view/XWnDhWETchtQ8aLa9MnrwK
http://dash.oznet.ch/view/EKFkFKFRH4M2t25hDZ9vAW
http://dash.oznet.ch/view/86FAuPvscBWNGYj48fsCiT#Actuators_PLOT

More testing needed though.

**Comment by LorenzMeier** [comment]
Also need to perform failover to 2nd accel for INAV.

**Comment by LorenzMeier** [comment]
@sjwilks @AndreasAntener @tumbili Same here - this will hit master soon, as it will prevent crashes.

**Comment by mhkabir** [comment]
@LorenzMeier As you said, we need the switcher logic in this PR to obey the priorities of each sensor in ```sensor_combined```. It's the only thing blocking prio-based switching.

**Pull request closed without merging**
