### PR TITLE
Allow GCS to clearly identify a non-calibrated RC control

### PR DESCRIPTION
**Pull request by LorenzMeier**
This should not affect existing users but allow new users to have a better RC calibration experience.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Done. One odd things to note though is that the MIN / MAX detection did in fact work. What screwed things over was that the user had multiple channels mapped to his stick, and that was the root cause and still is broken in QGC.

**Comment by DonLakeFlyer** [comment]
Correct for this case. But prior to this ive run into the min max problem a number of times. I believe taranis defaults to the exact values I was looking for

**Comment by LorenzMeier** [comment]
Ok. Once this PR is in this should be all fixed.

**Comment by LorenzMeier** [comment]
Applied to master, closing.

**Pull request closed without merging**
