### PR TITLE
Tiltrotor update and Convergence config and Mixer parsing fixes

### PR DESCRIPTION
**Pull request by AndreasAntener**
@LorenzMeier Merged the Tiltrotor and mixer updates, including new updates to how the MC controls are faded out in the transition. Tested today and rebased. Flown on the Convergence and on the Firefly6. Will add logs in a sec and merge when tests pass.
Closes #6221 
Closes #6226

### CODE REVIEW

**Comment by AndreasAntener** [comment]
Firefly6: http://logs.uaventure.com/view/Z2TBjp6FHrFvmqy46RorFP
Convergence: http://logs.uaventure.com/view/fjKu6LFMXV4XUHFLcNuGuF

**Comment by AndreasAntener** [comment]
@LorenzMeier the mixer test failed now on CircleCI but nothing changed anymore compared to the original branch which passed. Any insights?

**Comment by dagar** [comment]
The testing did change slightly in that period, with tests now broken up and run individually instead of tests all. Let me see if it's related.

**Comment by AndreasAntener** [comment]
@dagar feel free to push something here in case you spot the issue

**Comment by dagar** [comment]
@AndreasAntener this is working now rebased on master where code coverage has been disabled on circleci for a different reason (hopefully temporarily).

The only difference with code coverage is that everything is build with optimization disabled and the options -fprofile-arcs -ftest-coverage. We'll have to revisit this mixer failure to get code coverage working again, but that doesn't have to happen here. Sorry for the distraction.

**Comment by AndreasAntener** [comment]
@dagar thanks! merged

**Pull request merged**
