### PR TITLE
Add docs for tune_control command

### PR DESCRIPTION
**Pull request by hamishwillee**
Add auto-generate docs for tune_control. This is first part of fixing https://github.com/PX4/Devguide/issues/528

@bkueng Note,
* the docs methods for int param accept a min and max value, but these do not render in the output - so I have put that info in the description.
* It would be quite nice if we could put in a short name for the param (ie now it renders `[-f <val>]` but it would be possibly nicer if `[-f <frequency>]`

More important, to fix https://github.com/PX4/Devguide/issues/528 I should also document the [tune](https://github.com/PX4/Firmware/tree/master/src/lib/tunes) module. I think doing that in the same way makes sense - would you think this would be a [system](http://dev.px4.io/en/middleware/modules_system.html) module?

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @bkueng - all makes sense. I've added the `#include` now. Will need re-approval I think .. or just merge if you think OK. 

Also, as per top post I should also document the tune module. I think doing that in the same way makes sense - would you think this would be a SYSTEM module?

**Comment by bkueng** [comment]
>  Also, as per top post I should also document the tune module. I think doing that in the same way makes sense - would you think this would be a SYSTEM module?

Since it's a library and not a module that you can use via console, I would document it differently. On one hand there is already a class & method documentation (https://github.com/PX4/Firmware/blob/master/src/lib/tunes/tunes.h#L53), which is quite good. On the other hand we can add a separate page on the dev-guide for a high-level documentation (like the tunes format).
What do you think?

**Comment by hamishwillee** [comment]
@bkueng This is failing on 
```
../../src/systemcmds/tune_control/tune_control.cpp:72:42: fatal error: implicit conversion from 'long' to 'int' changes value from 4294967295 to -1 [-Wconstant-conversion]
        PRINT_MODULE_USAGE_PARAM_INT('d', 0, 0, 4294967295, "Duration of the tone (in us)", true);
```
That number (4294967295) is the value of the int32 for max duration, so don't know why the system is choking. That said, shouldn't this value be limited to some more reasonable max than 4294 seconds? Perhaps we should just put in a limit - 20 seconds?

>> Also, as per top post I should also document the tune module. I think doing that in the same way makes sense - would you think this would be a SYSTEM module?

> Since it's a library and not a module that you can use via console, I would document it differently. On one hand there is already a class & method documentation (https://github.com/PX4/Firmware/blob/master/src/lib/tunes/tunes.h#L53), which is quite good. On the other hand we can add a separate page on the dev-guide for a high-level documentation (like the tunes format).
> What do you think?

I was imagining a magic system where we could in theory create a doc for each and every library and executable in-source, if we so wish. My reasoning is that it gives us a way to document things that have a relatively small footprint in docs, and keep them associated with the code for easy update. 
This library being a a prime example - good to have a doc in the devguide for discoverability and to make the information well formatted, but choosing a place in our current structure for it not so easy.

Either way, I think having docs in the devguide makes sense. Would this count as "middleware"? If not, where would you put it?

**Comment by bkueng** [comment]
> That number (4294967295) is the value of the int32 for max duration, so don't know why the system is choking. That said, shouldn't this value be limited to some more reasonable max than 4294 seconds? Perhaps we should just put in a limit - 20 seconds?

The maximum value is 2,147,483,647 because it's a signed integer. You can set it to 60'000'000 (60 seconds).

> I was imagining a magic system where we could in theory create a doc for each and every library and executable in-source, if we so wish.

Isn't that doxygen?

> My reasoning is that it gives us a way to document things that have a relatively small footprint in docs, and keep them associated with the code for easy update.
This library being a a prime example - good to have a doc in the devguide for discoverability and to make the information well formatted, but choosing a place in our current structure for it not so easy.

True, having it in the source tree makes sense and I prefer that as well.
A library is quite a bit different from a module:
- None of the documentation should go into the compiled binary, so it does not need to be a string, but can be a comment.
- The focus should be on the API (plus a high-level overview), since that is what the users (=devels) have to deal with.

Not sure what's best, but doxygen seems appropriate (or something similar).

**Comment by bkueng** [comment]
> Doxgen only has work if it is integrated and used.

True, at the moment it's not integrated.

>  Perhaps for now, could this go in a page in Middleware? - or maybe under Middleware / Libraries / Tunes ?

Yes that makes sense.

**Comment by hamishwillee** [comment]
I believe this has largely been addressed. We don't have doxygen linked, but the information about tunes is well linked from a number of places. 

https://github.com/PX4/px4_user_guide/issues/426 is going to add info about the actual tunes from a user perspective.

**Pull request closed without merging**
