### PR TITLE
RM3100 Mag - WIP

### PR DESCRIPTION
**Pull request by ryanjAA**
RM3100 Mag Driver WIP - Needs data sheet to be gone over and added in
where missing. Builds and gets initial data from sensor. cmake fmuv2 changed only to test functionality on 1mb fmuv2.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Cool, thanks, looking forward to this!

**Comment by ryanjAA** [comment]
@LorenzMeier Thanks - we have it reading data but still lots to do. Could be a great unit though given (apparently) no calibrating needed.

**Comment by astekachev** [comment]
Hi everybody!
Currently, I design an autopilot board with RM3100 via SPI. Maybe someone already has a ready driver for connecting the RM3100 via SPI to STM32F7?
Thanks! Have a nice day, everyone!

**Comment by dagar** [comment]
Continued in https://github.com/PX4/Firmware/pull/10302.

**Pull request closed without merging**
