### PR TITLE
Enable RSSI via RC on all platforms

### PR DESCRIPTION
**Pull request by nanthony21**
Currently the ability to map an RC channel as an indicator of the RSSI is only available on the PX4IO platform. However this functionality is not really hardware dependent so there is no reason why it shouldn't be available on all platforms. This PR moves the relevant code from the PX4IO driver to the `rc_update.cpp` which processes all RC data regardless of platform.

In addition the default, min, and max values for the RC_RSSI_PWM parameters have been changed to match up with the values for other RC PWM parameters.

This PR is linked to issue #8856

### CODE REVIEW

**Comment by hamishwillee** [comment]
Can we please have some docs on mapping channels/RSSI when this is merged?

**Comment by nanthony21** [comment]
It looks like it has a problem with the change to the rtsp messages. Can someone point me in the right direction on this?

**Comment by dagar** [comment]
This doesn't feel quite right, having a duplicate message with nothing other than RSSI computed?

Why not push it into a library and call it from px4io and px4fmu? We already need to do that for RC parsing, mixing, etc.

Builds are failure due to style check and mission test failures will likely be resolved if you rebase on master.

**Comment by nanthony21** [comment]
I agree that having the two nearly identical messages seems clumsy. I guess I was wanting to avoid having the px4io/pxfmu drivers have to deal with it at all since it isn't really a very hardware dependent feature, but that would greatly simplify the uorb message situation. Is there already a library that would be good to add this to?

**Comment by dagar** [comment]
No, but all the output modules have this problem of sharing the same RC configuration parameters, so if we started a new lib it would be a good place to move them all.

**Pull request closed without merging**
