### PR TITLE
navigator and mavlink fix code style

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@julianoes @AndreasAntener Any concerns? I'm happy to put this in.

**Comment by dagar** [comment]
After this it's really just commander and mavlink that matter. Please let me know if we can ever get away with formatting them.

**Comment by LorenzMeier** [comment]
I think we can format the MAVLink app any time now. There is little activity and very little churn to be expected.

**Comment by dagar** [comment]
@AndreasAntener please merge if/when this won't cause any issues for you.

**Pull request merged**
