### PR TITLE
WIP: fix jMAVSim body-fixed XYZ Euler Angles

### PR DESCRIPTION
**Pull request by kd0aij**
This removes the roll/pitch swap and needs an updated jMAVSim submodule: https://github.com/PX4/jMAVSim/pull/36

Will add the submodule update here once that PR is merged

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@kd0aij Waiting on the jMAVSim PR going in.

**Comment by kd0aij** [comment]
waiting on merge of https://github.com/PX4/jMAVSim/pull/37

**Comment by kd0aij** [comment]
I think I got the submodule references correct; I think both jMAVSim and jMAVlib are referencing PX4/xxx/master now.

**Comment by kd0aij** [comment]
@bkueng I could use some advice on what's wrong with the submodule refs. It all looks correct to me.

**Comment by bkueng** [comment]
Submodules look all fine to me too, and a local test checkout works as well. @dagar could it be a CI caching problem? The submodule repo got changed.

**Comment by dagar** [comment]
It looks like it. Let me see what we can do.

**Comment by dagar** [comment]
I'm getting the same thing locally. It's confused with the switch from DrTon/jMAVlib.

**Comment by dagar** [comment]
I wiped the semaphore-ci cache and it builds now, but I think other developers are going to hit this. Let me see what the right answer.

**Comment by dagar** [comment]
@kd0aij Can you rebase on master?

**Comment by kd0aij** [comment]
@dagar Thanks, I had to checkout the submodules again, but that seems to have fixed it.

**Comment by bkueng** [comment]
rebased & applied

**Pull request closed without merging**
