### PR TITLE
Master prefix err, errx, warn and warnx with px4_

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier This is to decouple the err and warn from the OS

### CODE REVIEW

**Comment by bkueng** [comment]
Any reason why you did not switch to PX4_WARN? The current mix of warnx/PX4_WARN is very inconsistent.

**Comment by davids5** [comment]
Yes - only to keep it symmetrical and identifiable as part of this change.

**Comment by davids5** [comment]
@bkueng 
I am not ignoring your input on this - but currently while warn and warnx map to the same macro, I did not want to merge the distinct names (warn and warnx) until later.

@dagar 

Would you please review and merge.

**Comment by LorenzMeier** [comment]
@davids5 I will need to think about the optimal strategy. While your approach is prudent, not going to PX4_WARN() means that we will have a similar monster diff again at some point.

**Comment by julianoes** [comment]
I don't understand this change. I think we should go through each module/driver one by one and replace all `warnx`/`warn` with  `PX4_DEBUG`/`PX4_INFO`/`PX4_WARN`/`PX4_ERR` based on what it actually is.

**Comment by davids5** [comment]
I am Sorry I probably should have listed the rational - name collisions

Upstream nuttx just changed debug.h  to look like [this] (https://bitbucket.org/nuttx/nuttx/src/00a67b5d2bc34d42ce4acd7910477a4f6f4a3435/include/debug.h?at=master&fileviewer=file-view-default)

The discussion of which is [here] (https://groups.yahoo.com/neo/groups/nuttx/conversations/topics/12350;_ylc=X3oDMTM3NGgzZDRtBF9TAzk3MzU5NzE0BGdycElkAzIzMzg5MDcwBGdycHNwSWQDMTcwNTAwNjU1OQRtc2dJZAMxMjM3NARzZWMDZnRyBHNsawN2dHBjBHN0aW1lAzE0NjU5NDI2MjIEdHBjSWQDMTIzNTA-)

So we now have an issue going to nuttx_v3 where the names collide.

I can accept Greg's POV on err() and warn() but the problem goes on to involve info() and now alert()

**Comment by dagar** [comment]
@davids5 is this immediately blocking your nuttx_v3 work or do we have some time? If it's not urgent maybe we could split up the modules between us and incrementally get to the final PX4_INFO/WARN/ERR usage I assume everyone wants.

**Comment by davids5** [comment]
@dagar - It is but upstream has not stopped churning yet - I think we could proceed as is or just wait and see what Greg does with err(), warn and info and skip this completely. 

My thoughts on the PR are:

I think since the massive diff with  px4_warn[x]() -> PX4_WARN() folds warn and warnx into one - it is best done separately.

I also think that PX4_XXXX are logger functions and since px4_err[x] - exits it should be kept as a it is in the PR or changed to PX4_ERR() followed by the exit(n) because a logger with filtering is not process control.

I also think we need to check the use of exit() in err.h and #define px4_task_exit(x) _exit(x) in px4_task.h and make sure we are always using the correct one.

**Comment by julianoes** [comment]
@davids5 Thanks, now I understand.

@dagar: The exit handling is currently here (for NuttX and POSIX): https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/err.h#L78

**Comment by davids5** [comment]
Closing this for now as I have a work arround for being blocked on nuttx_v3

**Pull request closed without merging**
