### PR TITLE
Board config: timer config simplifications

### PR DESCRIPTION
**Pull request by bkueng**
Having done another PX4 board port, the most tedious, error-prone and redundant part I find is the timer configuration. This PR aims at improving that, with generality in mind.

### Summary

A current timer + channel config looks like this:
```
	{
		.base = STM32_TIM1_BASE,
		.clock_register = STM32_RCC_APB2ENR,
		.clock_bit = RCC_APB2ENR_TIM1EN,
		.clock_freq = STM32_APB2_TIM1_CLKIN,
		.first_channel_index = 0,
		.last_channel_index = 3,
		.handler = io_timer_handler0,
		.vectorno =  STM32_IRQ_TIM1CC,
		.dshot = {
			.dma_base = STM32_DMA2_BASE,
			.dmamap = DMAMAP_TIM1_UP,
			.start_ccr_register = TIM_DMABASE_CCR1,
			.channels_number = 4u /* CCR1, CCR2, CCR3 and CCR4 */
		}
	},
```
```
	{
		.gpio_out = GPIO_TIM1_CH4OUT,
		.gpio_in  = GPIO_TIM1_CH4IN,
		.timer_index = 0,
		.timer_channel = 4,
		.ccr_offset = STM32_GTIM_CCR4_OFFSET,
		.masks  = GTIM_SR_CC4IF | GTIM_SR_CC4OF
	},
```
Accompanied with several defines in the header in the form `#define GPIO_TIM12_CH2OUT     /* PH9   T12C2  FMU8 */ GPIO_TIM12_CH2OUT_2`.

The PR reduces all of it to 2 lines, one for the timer definition:
```
initIOTimer(Timer::Timer1, DMA{DMA::Index2, DMA::Stream5, DMA::Channel6}),
```
and one for the channel:
```
initIOTimerChannel(io_timers, {Timer::Timer1, Timer::Channel4}, {GPIO::PortE, GPIO::Pin14}),
```

### Details
- the 1. commit breaks the cyclic dependency between the `io_timers_t` and `timer_io_channels_t` data structures, and removes some fields that are not required or we can easily get at runtime.
- general removal of the use of `GPIO_GPIOx_OUTPUT`, and usage of timer_io_channels instead. The data structure stays otherwise the same, but instead of explicitly setting each field, `constexpr` methods are used for initialization during build time. This allows to specify only the information that is really required (i.e. timer, channel and pin), while ending up with the same binary.
- some architecture-specific mapping code is required to map from the specified configuration (i.e. `Timer::Timer1` to the NuttX defines (the ones that are currently used).
- requires C++14 for the constexpr code ( #13811)

### Benefits
- specify only the details that are required
- while still allowing for full flexibility. The existing method of explicitly initializing everything could still be used. But customizations can also be done much nicer, and more specific, see v4 (pulldown, https://github.com/PX4/Firmware/commit/da38cd0daa64ab73bef6c0047b0e9a2f3359b5dd) or crazyflie (different clock frequency, https://github.com/PX4/Firmware/commit/4d609bd18bf60b79466ef7f62ba151647aa1108a) for example.
- complex compile-time checks are possible, for example ensuring that all channels of a certain timer are grouped together.

### Drawbacks
- even though the method is generic, and could be used for SPI for example, it cannot be used for the NuttX `board.h` config, as it requires C++. Overall I still think it's worth exploring a script-based generator (including for the NuttX defconfig).

### Bugs
While working through this, I found 2 configuration bugs:
- nxp/fmuk66-v3: the 2. timer has 3 channels associated not 2
- crazyflie: TIM2 channels are not all grouped together. The current data structure does not allow for this. This issue is still unresolved and I see several options:
  - use a bitfield instead of `first_channel_index` and `last_channel_index`, or remove the fields altogether. The `io_timer_handler` IRQ handler would become slightly slower.
  - use a custom mixer to account for this (assuming we won't have more boards with that issue)
  - add a board-specific channel reodering

@davids5 @dagar

### CODE REVIEW

**Comment by davids5** [comment]
@bkueng - this looks interesting.  I do not understand how the association of the IP blocks that are need to support a timer are going to be done.  

Like where KINETIS_SIM_SCGC6 is the place that FTM0 on a K66 is enabled by what bit is not the same for an FTM3 etc. 

Where are cascaded clocks handled? (see the IMX rt branch)

ISRs should be short as possible. So not calculating (or shifting) at run time is preferred.  How will that be done?

**Comment by dagar** [comment]
> * crazyflie: TIM2 channels are not all grouped together. The current data structure does not allow for this. This issue is still unresolved and I see several options:
>   
>   * use a bitfield instead of `first_channel_index` and `last_channel_index`, or remove the fields altogether. The `io_timer_handler` IRQ handler would become slightly slower.
>   * use a custom mixer to account for this (assuming we won't have more boards with that issue)
>   * add a board-specific channel reodering
> 

A custom mixer for the crazyflie sounds fine, it's already a weird target. Last I heard it's not even working in master (I don't have one to test).

**Comment by davids5** [comment]
@bkueng - please have a look at the [IMXRT](https://github.com/PX4/Firmware/tree/master_imxrt) and suggest how this can be applied to it.

**Comment by bkueng** [comment]
> A custom mixer for the crazyflie sounds fine, it's already a weird target.

I've done that.

> @bkueng - please have a look at the IMXRT and suggest how this can be applied to it.

@davids5 I have merged the RT branch and done the changes (not quite finished yet) in https://github.com/bkueng/Firmware/commit/d363393dbf638a92ef0da2beafb41da1ae66f1fd and https://github.com/bkueng/Firmware/commit/b5b68263607c88ee37f2e09604e11d626ebc6d73. The main difference is that the IOMUX PAD and GPIO port + pin are independent. The timer setup and config could also be more generalized (also with cascaded clocks if needed), but I did not look into that.
Let me know what you think.

> ISRs should be short as possible. So not calculating (or shifting) at run time is preferred. How will that be done?

All ISR routines are unchanged in terms of runtime.

If everything looks good I'll continue and update all boards.

**Comment by davids5** [comment]
> > A custom mixer for the crazyflie sounds fine, it's already a weird target.
> 
> I've done that.
> 
> > @bkueng - please have a look at the IMXRT and suggest how this can be applied to it.
> 
> @davids5 I have merged the RT branch and done the changes (not quite finished yet) in [bkueng@d363393](https://github.com/bkueng/Firmware/commit/d363393dbf638a92ef0da2beafb41da1ae66f1fd) and [bkueng@b5b6826](https://github.com/bkueng/Firmware/commit/b5b68263607c88ee37f2e09604e11d626ebc6d73). The main difference is that the IOMUX PAD and GPIO port + pin are independent. The timer setup and config could also be more generalized (also with cascaded clocks if needed), but I did not look into that.
> Let me know what you think.
> 
> > ISRs should be short as possible. So not calculating (or shifting) at run time is preferred. How will that be done?
> 
> All ISR routines are unchanged in terms of runtime.
> 
> If everything looks good I'll continue and update all boards.

@bkueng - can we have a review of this on the dev call or some other time this week?

**Comment by bkueng** [comment]
Sure

**Comment by davids5** [comment]
@bkueng - Now that I understand the genius in this I have a great appreciation for the work you have done herein.

As discussed I will rebase and bring the RT in this week, then you can bring this in on top of it.

Thank you!

**Comment by bkueng** [comment]
This is now getting ready, I updated all boards.
Tested so far on Pixracer, both PWM + DShot.

@davids5 once the imxrt is in, I'll rebase once again and update that as well.

@PX4/testflights can you test this on all boards that you have?

**Comment by davids5** [comment]
@bkueng - So that I am clear, moving forward the defconfig will not state what HW Timers are enabled if PX4 is driving them as PWM ?

I am guessing it was inconsistent? 

What about UAVCAN, HRT etc? 

The thing we will need to look out for is a HW timer that has shared usage. Assume A and B a drivers use TIM1.
A & B had the timers enabled in the RCC before either driver runs and the start up ordered or A and B did not matter. Now all drivers need to do the ENR enable AND not use the RST in the rcc on  a shared timer. 

The former MAY manifest it's self as a hardfault (buss fault on not enabled IP block), the more subtle failure will be Wrong (or reset) values in registers. 

We should leverage all the goodness you have added to get a compilation time HW resource usage/contention map.

**Comment by bkueng** [comment]
Yes it was inconsistent, and it was also never clear to me when I ported a board if it was needed/harmful/does not matter.

HRT also has a check (`#  error must not set CONFIG_STM32_TIM1=y and HRT_TIMER=1`), for UAVCAN I don't know.
I agree we should consolidate that further, especially where overlapping use is possible.
From what I saw, we or NuttX does not init any timers by just enabling the NuttX timer config, but I may have overlooked something.

**Comment by davids5** [comment]
@bkueng 

>  not init any timers 

That is true if the driver are not included via defconfig.

RCC is it. An example of the RCC stuff is here. is here. https://github.com/PX4/NuttX/blob/px4_firmware_nuttx-8.2/arch/arm/src/stm32/stm32f40xxx_rcc.c#L332-L386

**Comment by Junkim3DR** [comment]
### Tested on NXP FMUK66 v3

**Modes Tested**
- Position Mode: Good.
- Altitude Mode: Good.
- Stabilized Mode: Good.
- Mission Plan Mode (Automated): Good.
- RTL (Return To Land): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint then trigger RTL.

**Notes**
No issues noted, good flight in general.

**Log**
- https://review.px4.io/plot_app?log=24dab5c2-ee6f-4e5a-aee9-a1436b7deb10

**Comment by dagar** [comment]
The NXP i.MXRT changes (https://github.com/PX4/Firmware/pull/13678) have merged to master.

**Comment by bkueng** [comment]
Updated for imxrt - it is really not SW-developer friendly.
I validated that the generated timer/channel data structure is binary-equivalent to before, so I expect it to work.

**Comment by Tony3dr** [comment]
We are encountering issues with CUAV Nano V5 and Pixhawk 4 V5. The firmware is broken for those vehicles, no connection on the vehicles  doesn't detect the ESC's, see image below:
83400023_780120509164251_4812812692584660992_n

@bkueng

**Comment by jorge789** [comment]
### Tested on PixRacer V4

 Indoor test flight.
Mode tested on Stabilized

 Takeoff and landing on Stabilized

**Log:** https://review.px4.io/plot_app?log=b797910e-f15b-433a-9b52-1167a364d0de

**Comment by bkueng** [comment]
@Tony3dr It was a problem with unused timers leading to `channel_count` set to 0, which led to underflows. It is fixed now.
Can you test again?

**Comment by jorge789** [comment]
### Tested on CUAV nano V5

**- Modes Tested**
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.
**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint then trigger RTL.

**- Notes**
When the vehicle was landing, it did not descend vertically, moved away with the wind and landed 25 meters from the point where it took off 
**Viento** 5.3 m/s

**Log**  https://review.px4.io/plot_app?log=a25476da-58cd-46f0-9f3a-78ac9be2d0a7

**Comment by dannyfpv** [comment]
tested on pixhawk4 v5 f-450

DJI 420 LITE ESC
PWM Input Signal Level | 3.3 / 5 VDC compatible
-- | --
Signal Frequency | 30 to 450 Hz
Battery Requirements | 3 to 4 S LiPo

vehicles doesn't detect the ESC's on this firmware change to master firmware and work correctly

**Comment by bkueng** [comment]
> The vehicle doesn't detect the ESC's on this PR, changed to master firmware and works correctly

I'll look into it. Thanks for testing.

**Comment by bkueng** [comment]
2 of the IO pins were incorrect, which is now fixed. I validated there is PWM on all 8 channels.

@dannyfpv can you test again?

**Comment by dannyfpv** [comment]
tested on pixhawk4 v5 f-450


**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL 
**Notes:**
No issues noted, good flight in general.

**Log:**
https://review.px4.io/plot_app?log=3d9858c1-82c4-41e3-8dc3-f03e28d8e5c2

**Pull request merged**
