### PR TITLE
Takeoff - allow publishing NAN longitude and latitude

### LINKED ISSUE #12919: Issue when getting lon/lat reference in air
**Describe the bug**
With an optical flow sensor, the local position is valid and it is possible to to an automatic takeoff before global position is valid. As soon as the GPS checks pass and the global position is valid, the drone starts to move to in some direction (previous origin?). This is truly commanded and is most likely an issue in `FlightTaskAuto`.

**To Reproduce**
1. Do an auto takeoff with flow only (without ever having global frame initialized)
2. Start GPS in air
3. When the global position gets valid, the drone will start to fly towards some direction

**Expected behavior**
Stay at the same location, shift properly the origin of the local frame and the memorized positions.

**Log Files and Screenshots**
I don't have a log file to share right now, will try to upload one soon.
Below is a screenshot showing 
2019-09-06_17-32-00_01_plot

### PR DESCRIPTION
**Pull request by bresch**
A NAN is interpreted in the FlightTaskAuto as a non-valid global coordinate and sets a local position.
If a zero is sent instead, the global coordinate is recognized as valid and will be executed.
This is a problem when the global position is gained for the first time after takeoff and that a valid global reference did not exist before

fixes #12919 

To reproduce:
- Trigger an automatic takeoff without having a global position valid but optical flow only (`ekf2 stop`, `gps stop`, `ekf2 start`)
- Enable gps in air (`gps start ...`)
- The drone does not fly towards longitude/latitude 0 anymore

### CODE REVIEW

**Comment by bresch** [comment]
@PX4/testflights Could you test that PR please?
What's important here is to test autonomous takeoffs: 
- start mission from ground
- takeoff triggered from ground station.

**Comment by jorge789** [comment]
**Tested on CUAC+ V5:**
**Modes Tested**

Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
- Armed form QGC.
Took-off on mission plan mode
. Note that commands were sent form QGC (Armed and takeoff)
Once all waypoint completed vehicle switched to RTL and landed as expected.
Good flight in general.
**Notes:**
No issues noted, good flight in general.

**Log:**
https://review.px4.io/plot_app?log=de1e7c8b-b555-4706-b168-2d9a6d6bf4db

**Tested on PixRacer V4:**
**Modes Tested**

Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
- Armed form QGC.
Took-off on mission plan mode
. Note that commands were sent form QGC (Armed and takeoff)
Once all waypoint completed vehicle switched to RTL and landed as expected.
Good flight in general.
**Notes:**
No issues noted, good flight in general.

**Log:**
https://review.px4.io/plot_app?log=0228f5f2-5470-4d2f-9a60-cfa1091b1366

**Comment by dannyfpv** [comment]
Tested on pixhawk4 f-450
Modes Tested

Mission Plan Mode (Automated): Good.
RTL: Good.

- Procedure

Armed form QGC.
Took-off on mission plan mode
. Note that commands were sent form QGC (Armed and takeoff)
Once all waypoint completed vehicle switched to RTL and landed as expected.
Good flight in general.
Notes:
No issues noted, good flight in general.
Log:

https://review.px4.io/plot_app?log=0ca6226f-71c0-4774-b79b-00bc7986c79f

**Comment by bresch** [comment]
@jorge789 @dannyfpv Thanks guys, that's all good.

**Pull request merged**
