### PR TITLE
travis-ci add GCC7 SITL build and tests

### LINKED ISSUE #7539: Run CI with gcc 7
Starting from version 7, gcc provides additional warnings, see here for the detail https://gcc.gnu.org/gcc-7/changes.html.
In PX4, these warnings were fixed for posix targets in #7332, and arm targets in #7502. 
The benefits are:
- users of distros with recent versions of gcc and arm-none-eabi-gcc (such as archlinux) can happily compile PX4 using the default compilers
- more warnings means safer code, for instance this bug was difficult to notice but the compiler catched it: https://github.com/PX4/ecl/commit/d0b4f1e225a5252d543cbc419d642277df535ee7. The implicit-fallthrough warning is also nice because it imposes to explicitly document missing breaks in a switch statement.

But the compatibility with gcc 7 needs to be enforced by CI. @dagar proposed to add a docker image
> If someone would like to get a gcc 7 docker image together I'll get it into the build system.
https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_nuttx

However I am not familiar with docker. I just found this Dockerfile that might do the job for posix targets (see https://hub.docker.com/_/gcc/ and https://github.com/docker-library/gcc/blob/3b33871fe9558262cb5ed6253d358f76710e9ccb/7/Dockerfile).
Anybody willing to help is welcome!

### PR DESCRIPTION
**Pull request by dagar**
- closes #7539 

@jlecoeur once this is passing the GCC 7 SITL build is working.

### CODE REVIEW

**Comment by jlecoeur** [comment]
Great!
It seems gcc7 compatibility was broken already, fixed in #7646

**Comment by jlecoeur** [comment]
Ok @dagar , #7646 was merged, so a rebase should fix the CI here.

**Comment by dagar** [comment]
@jlecoeur getting closer. Looks like a tiny difference in a conversion with GCC 7.

**Comment by jlecoeur** [comment]
@dagar I had the same issue with clang 4.0.1 and gcc 7.1.1. With rounding, the conversion does not fail, see https://github.com/dagar/Firmware/pull/2

**Comment by LorenzMeier** [comment]
@dagar Could you rebase? I'd love to get the great work of @jlecoeur in - @jlecoeur keep it coming, your contributions are very, very welcome and appreciated.

**Comment by dagar** [comment]
Rebased and now passing. Thanks!

**Pull request merged**
