### PR TITLE
mavsdk_tests: add iris_dual_gps tests

### PR DESCRIPTION
**Pull request by TSC21**
Let's give this a try again so to avoid it falls by the wayside.

### CODE REVIEW

**Comment by TSC21** [comment]
The tests keep failing intermittently, and not just in this specific model...

**Comment by dagar** [comment]
> The tests keep failing intermittently, and not just in this specific model... Had to rerun the pipeline a couple of times to have them all pass.

What else was failing? At a minimum let's start collecting all details in issues.

**Comment by TSC21** [comment]
> > The tests keep failing intermittently, and not just in this specific model... Had to rerun the pipeline a couple of times to have them all pass.
> 
> What else was failing? At a minimum let's start collecting all details in issues.

Some that I remember was th iris mock opt flow failing on offboard. But was randomly on any of the test coordinates, not a pattern.

**Comment by dagar** [comment]
We shouldn't tolerate intermittent failures that can't be blamed on infrastructure. Unless the failure rate is very low please comment it out and open an issue (or try to fix it immediately).

**Comment by TSC21** [comment]
> We shouldn't tolerate intermittent failures that can't be blamed on infrastructure. Unless the failure rate is very low please comment it out and open an issue (or try to fix it immediately).

I get that but I run these tests at more than 10 times in a row on my local system and neither failed. So or something is not weel configured on the containers or is something else that doesn't seem to be easily reproducible.

**Comment by dagar** [comment]
> > We shouldn't tolerate intermittent failures that can't be blamed on infrastructure. Unless the failure rate is very low please comment it out and open an issue (or try to fix it immediately).
> 
> I get that but I run these tests at more than 10 times in a row on my local system and neither failed. So or something is not weel configured on the containers or is something else that doesn't seem to be easily reproducible.

As projects mature intermittent failures become the norm (especially for anything multi-threaded). Please open issues for failures and don't tolerate these failures.

**Pull request merged**
