### PR TITLE
Commander: fix low battery failsafe behavior and messages

### PR DESCRIPTION
**Pull request by korigod**
If battery failsafe action set to RTL (`COM_LOW_BAT_ACT = 1`), failsafe is triggered only in `BATTERY_WARNING_CRITICAL` state. If battery drops to `EMERGENCY` state missing `CRITICAL`, failsafe will not be activated. While this transition is unlikely, it is still possible and PR fixes this behavior adding check for `critical_battery_voltage_actions_done` in `BATTERY_WARNING_EMERGENCY` state handler so RTL will be triggered there when battery enters `EMERGENCY` state.

PR makes state transition outcomes' checks consistent, replacing
`TRANSITION_CHANGED == main_state_transition(...)` with
`TRANSITION_DENIED != main_state_transition(...)` in `BATTERY_WARNING_EMERGENCY` `if` branch — commit 263b7ea ("commander battery failsafe only error if TRANSITION_DENIED", 2017-10-06) already did this replacement in `BATTERY_WARNING_CRITICAL` branch. Comparison with `TRANSITION_CHANGED` can lead to "LANDING FAILED" message when the vehicle is actually landing.

Battery failsafe messages were fixed for consistency too.

The code was compiled and tested in SITL.

### CODE REVIEW

**Comment by korigod** [comment]
The branch has been rebased on the current master. @dagar, could you review?

**Comment by dagar** [comment]
Sorry, this slipped through.

The issue with RTL: "Return to launch" is that it's possible for it to also initiate landing via mission at DO_LAND_START.

That being said I'm wondering if we can get away with not including the full text. The mode also changes (which will typically be spoken GCS side). The important information to add is the reason (battery low, critical, etc).

**Comment by dagar** [comment]
Larger cleanup of battery failsafe handling with small state machine here. https://github.com/PX4/Firmware/pull/10139

**Comment by dagar** [comment]
I believe the underlying issue has been addressed in master. Please let me know if that's not correct.

**Pull request closed without merging**
