### PR TITLE
Cut down verbosity

### PR DESCRIPTION
**Pull request by julianoes**
This is a try to cut down on verbosity by getting rid of some printfs and removing false positive warnings.

Parts:

- [x]  Snapdragon POSIX
- [x]  Snapdragon QURT
- [x]  POSIX SITL
- [x]  Pixracer/Pixhawk Nuttx

- [x] prepend module name to PX4_DEBUG/INFO/WARN/ERR

### CODE REVIEW

**Comment by bkueng** [comment]
This is great! We really need to make sure people use the proper log levels, not just `warnx` for everything.

Can you also prepend the module name to the PX4_{WARN,ERR..} defines? Then we can deprecate `warnx`.

**Comment by julianoes** [comment]
@bkueng: Yes, I agree we should prepend the module name. I'll check how this can be done.

**Comment by julianoes** [comment]
@bkueng I think it would be easiest to use the `MODULE` name which is set in CMakeLists.txt but I'm not sure how to get to it.

**Comment by bkueng** [comment]
No, actually you can use `getprogname`. If a thread is started with `px4_task_spawn_cmd`, this works, if `pthread_create` is used directly, it does not (which means we should use `px4_task_spawn_cmd` everywhere).
I think the only places where it will not work (or at least you don't get the desired result) is in the callbacks from the DriverFramework, which runs everything on the same thread, and thus all sensors have the same 'module' name.

`getprogname` is already used for this purpose in `warnerr_core`, in `err.c`, under NuttX.
The `MODULE` version would avoid runtime overhead, but has the disadvantage, that it does not work for shared code, e.g. within the orb functions.

**Comment by LorenzMeier** [comment]
@bkueng No, task spawn should only be used if you want to spawn a *task* because pthreads != tasks.

**Comment by bkueng** [comment]
ok, yes, they're not the same conceptually. But then our implementation is wrong on posix: calling `getprogname` from a `pthread_create`d thread gives you "UnknownApp", instead of the task name.

**Comment by julianoes** [comment]
@bkueng Another problem is that for everything that runs in the work queues `getprogname` will just return `hpwork` and `lpwork`.

**Comment by julianoes** [comment]
@LorenzMeier: Any idea how to get to `MODULE` in code? Is there some define?

**Comment by julianoes** [comment]
> @LorenzMeier: Any idea how to get to MODULE in code? Is there some define?

Don't worry, I found a way.

**Comment by julianoes** [comment]
I see that using a define of the module name is not really feasible on Pixhawk because it uses too much flash space.

**Comment by julianoes** [comment]
@bkueng, @LorenzMeier: I added a define for the module name and prepends it to the printf. This is fine for SITL but leads to an increase in flash space, right now about 8000 Bytes.

Any idea what to do? Use `getprogname` instead on STM32 and accept that it will say `Xpwork`?

**Comment by bkueng** [comment]
@julianoes how do you do the printf? `printf(MODULE ARG)` or `printf(MODULE); printf(ARG)` ? In the second case GCC should be able to dedup the strings (`-fmerge-constants`), and then I think it should be considerably less than 8kB.

**Comment by julianoes** [comment]
@bkueng it already gets munched into one big printf:
https://github.com/PX4/Firmware/blob/master/src/platforms/px4_log.h#L151

**Comment by julianoes** [comment]
Ready to flight test and merge.

**Comment by julianoes** [comment]
I've rebased this and fixed the merge conflicts.

It's flown on Snapdragon, SITL and Pixfalcon, good to merge in my opinion.

The size difference for px4fmu-v2_default is as follows:

<table>
    <tr>
        <td>master</td>
        <td>1028808 bytes</td>
    </tr>
    <tr>
        <td>fix_printfs</td>
        <td>1023952 bytes</td>
    </tr>
</table>

**Comment by LorenzMeier** [comment]
Nice!

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
