### PR TITLE
Pr att bias cleanup2

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by priseborough** [comment]
I'll get the changes in that @sanderux  requested for the fixed wing controller.

**Comment by sanderux** [comment]
@priseborough thanks for addressing my comments.
I mentioned inconsistent use of airspeed_mode vs airspeed_disabled and you choose to use airspeed_mode consistently. reading the code perhaps airspeed_disabled would have been clearer, but not a big issue. I'm fine with it either way.

**Comment by priseborough** [comment]
I can change it to be airspeed disabled everywhere assuming that it will always be used as a boolean and we will not be adding other mode selections (eg use none, use estimated, use measured).

**Comment by sanderux** [comment]
considering now it is a boolean and if in the future that changes the code would have to change anyway, i say lets make it airspeed_disabled

**Comment by LorenzMeier** [comment]
@PX4TestFlights Please thoroughly re-test this. Thanks!

**Comment by LorenzMeier** [comment]
On all airframes that is - multicopter, VTOL, fixed wing.

**Comment by mhkabir** [comment]
Rebased.

**Comment by santiago3dr** [comment]
a few flights with pixracer (v4)
https://logs.px4.io/plot_app?log=23e9ccd1-66ae-4225-9fba-a838bc5a0a9b
https://logs.px4.io/plot_app?log=cfb8bd26-aa36-4ad4-bf7e-1838d995bf6f
https://logs.px4.io/plot_app?log=7afbd5d8-92e6-4568-bd69-e5f037f7a37e

very stable; seemingly better tracking; no issues

**Comment by Avysuarez** [comment]
Flight with pixhawk 1(V3); Good flight, no issues
https://logs.px4.io/plot_app?log=70e4aca1-4882-4b38-9250-7480e5b96c53

Flight with pixhawk pro (V4PRO); Good flight, no issues
https://logs.px4.io/plot_app?log=7dc4c2cf-58f7-4e3e-b944-b811abe4f4e8

Flight with pixhawk 1 (V2); Good flight, no issues
https://logs.px4.io/plot_app?log=d89361b0-a187-4f83-a61b-3eba8ff3e25e

**Comment by mhkabir** [comment]
@santiago3dr @Avysuarez Thanks! We still need coverage on VTOL and FW. :)

**Comment by mhkabir** [comment]
Unrelated to the PR, but one of the logs have that annoying transformation bug. Those tracking errors would've constituted a flyaway in reality : 
image

**Comment by dagar** [comment]
> Unrelated to the PR, but one of the logs have that annoying transformation bug. Those tracking errors would've constituted a flyaway in reality :

Any clues for where it's happening? When have you seen this bug?

**Comment by mhkabir** [comment]
@dagar It's filed here : https://github.com/PX4/pyulog/issues/13, but I don't think anyone is closer to finding the core problem.

**Comment by santiago3dr** [comment]
vtol flight:
https://logs.px4.io/plot_app?log=da7635c7-209f-4567-a5d8-efbe06ca3769

compared to master:
https://logs.px4.io/plot_app?log=d71c9cbc-ceef-4c96-a786-dd1f09b34fd9

...and compared to stable:
https://logs.px4.io/plot_app?log=8ab54dbc-4c72-4134-98a8-1b52aae0cf4c



FW flights:
https://logs.px4.io/plot_app?log=d7b17818-2d28-40a4-9829-615a7cc1b09f
https://logs.px4.io/plot_app?log=4a79be68-d2ab-4b5a-a6d7-81607bd8d865

compared to master:
https://logs.px4.io/plot_app?log=04f281af-624d-48d2-b345-29eb792ff665

good flight performance; stable with nice tracking with both platforms

**Comment by mhkabir** [comment]
@santiago3dr Many thanks for the excellent test coverage! 

@LorenzMeier @priseborough @dagar I wil merge this soon after a final review unless any of you have any objections. :)

**Comment by sanderux** [comment]
Your change has some impact on airspeedsensorless vehicles. Do you think i should give it a quick test on the deltaquad?

**Comment by mhkabir** [comment]
@sanderux Yes definitely! Please do test and let us know if airspeed-less operation works as expected.

**Comment by LorenzMeier** [comment]
@sanderux Any chance to get this done today?

**Comment by sanderux** [comment]
Sorry, no luck yet, planning and weather keep interfering. I will try in the next 2 days

**Comment by mhkabir** [comment]
@sanderux Updates? If none, let's get this in anyway.

**Comment by dagar** [comment]
Rebasing

**Comment by r0gelion** [comment]
@dagar does @PX4TestFlights need to re-test?

**Comment by dagar** [comment]
Rebase became difficult and didn't seem worth it. 
Continued here as a squashed commit, https://github.com/PX4/Firmware/pull/7882. 
We can split it into smaller commits if desired.

**Pull request closed without merging**
