### PR TITLE
Added support for ICM20602 and ICM20689

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier 

This has been tested on px4fmu-v5* and regression tested on auav-x21 

@kd0aij would you please please fly this on pixracer as a cross check. 

* At this point I did not look at the register deltas from part to part. I just insured that the drivers would start and find the correct whoami and product id and render some data..

This is still using the original enumeration. I would like to fix that once  nuttx_upgrade_grouped is merged into master

For now the fmu-v5 creates:

```
 mpu6000_accel
 mpu6000_accel1
 mpu6000_gyro
 mpu6000_gyro11
```
Which I think this should be: 

```
 mpu6000_accel0
 mpu6000_accel1
 mpu6000_gyro0
 mpu6000_gyro11
```

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@davids5 We might have to hunt a couple of excessive error / feedback messages to trim this further down. Just 200 bytes missing. Need to also prune the ROMFS.

**Comment by kd0aij** [comment]
Flown by Phil: 
This seems to work just fine on a Pixracer.
http://logs.uaventure.com/view/Ni4TYbC3EjVdwDiZ8jDYKj

**Comment by LorenzMeier** [comment]
This hardfaults on FMUv5

**Comment by LorenzMeier** [comment]
@davids5 Hard fault fixed. Waiting for test results from @sirPerna.

**Comment by LorenzMeier** [comment]
So the driver starts now without hard faulting, but it doesn't successfully initialise both - only the ICM20602.

**Comment by LorenzMeier** [comment]
@davids5 Can you share a boot console log when you did your next iteration? Current issues:

  * USB unstable (Windows says "stopped working")
  * I2C4 not moving at all
  * GPS driver on USART1 not operational (cause unknown)
  * ICM20602 starts, ICM20608 doesn't

Would be good to have a boot log from you to compare to other boards to rule out HW issues.

**Comment by davids5** [comment]
@LorenzMeier 

```
```

**Comment by pkocmoud** [comment]
I would like to urge caution with my test flight results. While I did have several successful flights with this PR, I also had a single instance where my attitude was pitching and rolling at a constant rate after boot up on a Pixracer. A power cycle corrected this but its cause is unknown and I have seen at least 1 other user mention a similar problem.

**Comment by davids5** [comment]
@LorenzMeier 

today's build

```
nsh> ver all
HW arch: PX4FMU_V5
FW git-hash: 3197ccab7b527816134b919f7656896ec1e5f9a0
FW version: v1.5.2-222-g3197cca (1.5.2 0), 17105408
OS version: 7.18 (117508351)
Build datetime: Dec 19 2016 05:29:27
Build uri: localhost
Toolchain: 5.4.1 20160609 (release) [ARM/embedded-5-branch revision 237715]
MCU: STM32F76xxx, rev. A

WARNING   WARNING   WARNING!
Revision A has a silicon errata
This device can only utilize a maximum of 1MB flash safely!
https://pixhawk.org/help/errata

UID: 26003E:33355102:36303934
nsh> reboot
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
[i] microSD mounted: /fs/microsd
[hardfault_log] Fault Log is Armed
WARN  [param] selected parameter default file /fs/mtd_params
INFO  [ver] match: PX4FMU_V5
INFO  [ver] match: PX4FMU_V5
INFO  [dataman] Unkown restart, data manager file '/fs/microsd/dataman' size is 47640 bytes
MS5611_SPI on SPI bus 4 at 64 (20000 KHz)
WARN  [bst] no devices found
INFO  [ver] match: PX4FMU_V5
MPU6000 on SPI bus 1 at 17 (1000 KHz)
MPU6000 on SPI bus 1 at 16 (1000 KHz)
nsh: bmi055: command not found
WARN  [hmc5883] no device on bus 1 (type: 2)
WARN  [hmc5883] no device on bus 2 (type: 2)
WARN  [hmc5883] no device on bus 4 (type: 2)
ERROR [meas_airspeed] no MS4525 airspeed sensor connected
ERROR [ets_airspeed] no ETS airspeed sensor connected
ERROR [ets_airspeed] no ETS airspeed sensor connected
nsh: sf1xx: command not found
WARN  [sensors] FATAL: no magnetometer found: /dev/mag0 (2)
ERROR [sensors] sensor initialization failed
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS1 @ 57600B
INFO  [mavlink] mode: OSD, data rate: 1000 B/s on /dev/ttyS3 @ 57600B
WARN  [mavlink] hardware flow control not supported
INFO  [mavlink] mode: Config, data rate: 800000 B/s on /dev/ttyACM0 @ 57600B
No autostart ID found

NuttShell (NSH)
nsh> ls /dev
/dev:
 accel0
 accel1
 adc0
 baro0
 console
 gyro0
 gyro1
 icm20602_accel
 icm20602_gyro
 icm20689_accel
 icm20689_gyro
 led0
 mmcsd0
 ms5611_spi_int
 mtdblock0
 mtdblock1
 null
 pwm_output0
 px4fmu
 ram0
 rgbled0
 tone_alarm0
 ttyACM0
 ttyS0
 ttyS1
 ttyS2
 ttyS3
 ttyS4
 ttyS5
 ttyS6
````

**Comment by LorenzMeier** [comment]
@davids5 On my unit:

```
MPU6000 on SPI bus 1 at 17 (1000 KHz)
MPU6000 ID 0x02
MPU6000 on SPI bus 1 at 16 (1000 KHz)
MPU6000 unexpected ID 0x03
MPU6000 CDev init failed
```

**Comment by davids5** [comment]
@pkocmoud 

>I would like to urge caution with my test flight results. While I did have several successful flights with this PR, I also had a single instance where my attitude was pitching and rolling at a constant rate after boot up on a Pixracer. A power cycle corrected this but its cause is unknown and I have seen at least 1 other user mention a similar problem.

Thank you for the feedback and caution!

The  px4fmu-v4 vetting would be a Go-No-Go. The change that affected  px4fmu-v4 was my original assumption that the undocumented Product ID value of 0xff for a ICM 20608.  was "Nothing read" value. The code now expects 0xff from the ICM 20608. If that was a bad assumption prior to df33543
 it would have caused a hardfault. After df33543 the ICM 20608 would fail to start the ICM 20608.

**Pull request merged**
