### PR TITLE
EKF: Let the EKF know if the vehicle is operating as a fixed wing type.

### PR DESCRIPTION
**Pull request by priseborough**
Allows fixed wing aircraft to recover from bad compass at launch using https://github.com/PX4/ecl/pull/294.

Will improve reduce incidence of loss of navigation at start of flight such as seen here: http://logs.px4.io/plot_app?log=833a9742-1e37-4741-aaf4-2dbee246246e

### CODE REVIEW

**Comment by priseborough** [comment]
@PX4TestFlights Can you please test this, preferably using an airframe with bad compass calibration and with SDLOG_MODE = 2 so that the log can be used for replay.

**Comment by dagar** [comment]
I'm not sure if this is obvious, but with a VTOL this changes in flight at the end of forward transition and beginning of back transition.

**Comment by priseborough** [comment]
At the moment the normal mag heading alignment which happens at 1.5m will be performed for VTOL types, so they should experience no change in behaviour because the final in-flight alignment flag is already set before transition.

**Comment by sanderux** [comment]
I would note that a VTOL will usually experience a different mag error during MC mode then it will during FW mode as the current draw is very different and flows elsewhere in both modes. Ideally mag would be aligned after transitions

**Comment by priseborough** [comment]
OK, it sounds like a separate PR to add a yaw reset request interface to the ecl/EKF is required that can be triggered when transition is complete.

**Comment by priseborough** [comment]
In the meantime, I will merge this when it has been tested as it is a significant improvement for FW vehicle types and does not affect rotary wing or VTOL.

**Comment by santiago3dr** [comment]
couple flights with the phantom flying wing
http://logs.px4.io/plot_app?log=6d42c96b-cfdc-4485-b49d-5ec0234e93b7
http://logs.px4.io/plot_app?log=041ef121-a1aa-4217-9b92-b5f46347d210

did not run calibrations as per instructed
good flights; no issues

**Comment by priseborough** [comment]
Both those flights  had large magnetometer offset errors and successfully invoked the use of GPS to reset the yaw angle as evidenced by:

1) Rapid rise in velocity innovations at launch

2) Increment in the quaternion reset counter at launch and output of the following Mavlink message
WARNING | [lib__ecl] EKF bad yaw corrected using GPS course

screen shot 2017-07-29 at 7 12 44 am

3) The velocity innovations recover immediately after the reset

4) Large learned X and Z bias values 

screen shot 2017-07-29 at 7 14 15 am

5) Magnetomer innovations are low throughout flight:

screen shot 2017-07-29 at 7 15 16 am

The learned mag bias values should be gradually be saved in the EKF2_MAGBIAS parameters, so I will check that as a separate issue.

**Pull request merged**
