### PR TITLE
airspeed driver: un-advertise differential pressure topic

### PR DESCRIPTION
**Pull request by RomanBapst**
Signed-off-by: Roman <bapstroman@gmail.com>

### CODE REVIEW

**Comment by dagar** [comment]
There's already a NULL pointer check within uORB. https://github.com/PX4/Firmware/blob/master/src/modules/uORB/uORBDevices.cpp#L473

**Comment by RomanBapst** [comment]
@dagar I wanted to avoid people looking at that code and thinking what I'm doing is dangerous.
Looks like there was a 50 50 chance that you would complain because in about half of the cases in PX4 this check is done.

**Comment by dagar** [comment]
It's definitely good practice in general.

**Comment by dagar** [comment]
Once off it doesn't matter, but it's the kind of the thing that starts to add up across an entire codebase. Likewise for checking NULL before calling delete.

**Comment by RomanBapst** [comment]
@dagar Done

**Pull request merged**
