### PR TITLE
Changed get_distance_to_line() to calculate distance to line segment

### PR DESCRIPTION
**Pull request by arbulgazar**
`get_distance_to_arc(..)` could be updated to follow the same logic

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Can you please run Tools/check_code_style.sh?

**Comment by arbulgazar** [comment]
Sure, will do this today.                                                                                                                                                                                                                                                                                                                                        Max ShvetsovFirmware Developer+371 29802988Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Lorenz MeierSent: Thursday, 11 February 2016 12:51To: PX4/FirmwareReply To: PX4/FirmwareCc: Max ShvetsovSubject: Re: [Firmware] Changed get_distance_to_line() to calculate distance to line segment (#3710)Can you please run Tools/check_code_style.sh?

—Reply to this email directly or view it on GitHub.

**Comment by LorenzMeier** [comment]
@arbulgazar This still fails the CI tests.

**Comment by LorenzMeier** [comment]
@arbulgazar Can you share again what exactly this fixes and rebase on master? Otherwise I'm closing this until the end of the year.

**Pull request closed without merging**
