### PR TITLE
Enable ms5611 driver and fix build errors.

### PR DESCRIPTION
**Pull request by SimonWilks**
This fixes:
- what appears to be a path error in the sitl_run script (we need a non sitl script?)
- general compile errors
- converts errx to PX4_WARN
- fixes the find_bus() calls
- enables the MS5611 driver which isn't fully functional yet.

Thanks @tumbili for the help on this.

### CODE REVIEW

**Comment by mhkabir** [comment]
@sjwilks @tumbili Is this tested on your Navio setups? I'm looking to help with this and the other drivers, so let me know.

**Comment by tumbili** [comment]
@mhkabir Hi Kabir, I've been working on this lately, but unfortunately I'm still trying to solve other problems. I've been trying to use "sshfs" to mount the file system of the RPI so that I can develop more conveniently but that has not worked yet for some reason. Also I tried to activate the verbose debugging but I'm also having trouble with this.

**Comment by SimonWilks** [comment]
@mhkabir yes this has been tested on the Navio+ with the RPi 2 using the Emlid RT supplied kernel. I agree with the approach you propose on the abstraction level.

@mcharleb can you have a quick look at this? 

We should probably all sync on next steps via email/chat/skype soon.

**Comment by LorenzMeier** [comment]
I guess there is no harm in merging this - applied to master. Please work off that for the next steps.

**Pull request closed without merging**
