### PR TITLE
prevent use of PX4 param system in ArduPilot

### PR DESCRIPTION
**Pull request by tridge**
This prevents the use of the PX4 parameter system in ArduPilot. ArduPilot now has its own stub functions for the px4 parameter system here:
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_HAL_PX4/px4_param.cpp
this fixes an issue where servos would not operate correctly on helicopters, as the INIT_OK flag was not set by px4io

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I'm happy to fix this, but I don't think we should take the app-build #ifdef style approach as it will badly scale. We will come up with something architected to solve this for good - I'll leave this open in the meantime so we don't forget.

**Comment by tridge** [comment]
I presume you're referring to the module.mk ifeq? There are no #ifdefs in the patches.
The file that the ifeq was added to already has two other ifeq slabs in it. It seemed the logical approach to follow that existing system in the same file.
I could instead define a ardupilot specific module.mk that lives outside the systemlib directory, but that seems like it creates more divergence.
Alternatively we could split systemlib into multiple modules, and ardupilot could not include the param module.
I certainly do not want the px4 param system linked in to ardupilot. I don't want there to be any chance of an alternative parameter system running which could give bad config values.
Can you suggest any other alternatives?

**Comment by LorenzMeier** [comment]
To me the right fix seems to move the param lib functionality into src/lib/param and to just not build it in the APM build. The system lib is anyway too big and this shows we need a higher resolution for component selection.

**Comment by LorenzMeier** [comment]
This here is the right fix. Your first three commits plus this should result in a fix with the same functionality that you were striving for, but without magic ifdefs in the Makefile.
https://github.com/PX4/Firmware/pull/2520

**Comment by LorenzMeier** [comment]
We have the critical fixes here in. In general I'd like to factor out the param system properly, so closing this in the interim.

**Pull request closed without merging**
