### PR TITLE
Update nuttx

### PR DESCRIPTION
**Pull request by janokle**
This fixes a blocking issue of the serial transmission

### CODE REVIEW

**Comment by dagar** [comment]
Circleci astyle versioning error should go away if you rebase this branch on master.

**Comment by dagar** [comment]
@PX4BuildBot rebase

**Comment by LorenzMeier** [comment]
It didn't actually rebase!

**Comment by LorenzMeier** [comment]
@PX4BuildBot Rebase

**Comment by dagar** [comment]
Killed the API limit again. Please rebase manually, the CI system nonsense will be resolved shortly.

**Comment by dagar** [comment]
Circleci is failing due to this (https://github.com/PX4/Firmware/pull/8689), but it's resolved on master.

All the NuttX builds (including nxphilte) are passing.

**Comment by dagar** [comment]
@LorenzMeier oh, I missed that this wasn't merging to master. That's why the rebase didn't work.

**Pull request merged**
