### PR TITLE
WIP: constrain RPY rates to +/- pi/2

### PR DESCRIPTION
**Pull request by kd0aij**

### CODE REVIEW

**Comment by dagar** [comment]
Isn't this already done in ECL based on the params?

https://github.com/PX4/ecl/blob/master/attitude_fw/ecl_roll_controller.cpp#L75

**Comment by kd0aij** [comment]
oops. I didn't look inside that method, because I couldn't find any parameters for setting the max rate.
Talk about implementation hiding :)

**Comment by kd0aij** [comment]
This is very confusing: I found a declaration for _max_rate in src/lib/ecl/ecl_pitch_controller.h (nowhere else). The Eclipse search failed because it isn't even looking at the same sourc files. I guess I'll have to give up on Eclipse now unless I can figure out how the build system works.

But to me it appears that the **_max_rate** stuff is a NOP for roll and yaw.

**Comment by dagar** [comment]
I expect the indexer to occasionally be helpful, but my day to day in eclipse is completely dependant on file search. Select the src tree, ctrl + h, limit filename pattern (*, *.c, *.cc, *.cpp, *.h, *.hpp, *.mix, *.msg, *.py, *.txt, *.xml).

**Comment by kd0aij** [comment]
I get upset when things like "open declaration" and "references" don't work :)
I use the file search a lot, but index searches are obviously much faster and more convenient.

With more grepping and file searching, I found that there *are* parameters for max roll rate, etc.:
e.g. FW_R_RMAX. The names are just very different from say MC_ROLLRATE_MAX.
And the default roll rate is only 70 deg/sec, so this PR should only make the problem worse.

**Comment by dagar** [comment]
Yes param naming consistency would be really nice, but at this point it would be an annoying change for people to consume.

**Comment by kd0aij** [comment]
closing this since rate limiting is already implemented in the ecl library

**Pull request closed without merging**
