### PR TITLE
vscode launch.json add black magic probe debug config

### PR DESCRIPTION
**Pull request by dagar**
Screenshot from 2019-06-14 09-26-32

Somewhat unfortunately the address of the Black Magic probe has to be specified in the config.

https://github.com/PX4/Firmware/blob/0684d66067a55208070975af3d123ded377ee723/.vscode/launch.json#L175

@julianoes

### CODE REVIEW

**Comment by julianoes** [comment]
Nice, I will try that!

**Comment by julianoes** [comment]
Selection_030

@dagar do you know what I'm missing? I have the svd files where they are supposed to be.

**Comment by dagar** [comment]
Can you try it manually with straight GDB first? I had a lot of trouble with the Black Magic Probe with F7 support broken in different releases. That's one of several reasons I switched to JLink. I have one you can take tomorrow.

**Comment by julianoes** [comment]
Manually it works fine.

**Comment by dagar** [comment]
Can you try removing this? https://github.com/PX4/Firmware/blob/master/.vscode/launch.json#L204

**Comment by julianoes** [comment]
Oh this is the problem:
```
"/home/julianoes/src/Firmware/build/px4_sitl_default/bin/px4": not in executable format: File format not recognized
```

**Comment by julianoes** [comment]
I had to chose the correct cmake build and the kit of VSCode needs to be "No active kit".

**Pull request merged**
