### PR TITLE
simplify param scoping (fix out of tree builds) and fix qurt fc_addon linking

### PR DESCRIPTION
**Pull request by dagar**
Possible fix for #8280

@ChristophTobler @santiago3dr could you see if this fixes eagle_legacy_default? I don't have one to test, or FC_ADDON to even build.

### CODE REVIEW

**Comment by r0gelion** [comment]
@dagar 

eagle_legacy_default

No parameter issues, but I got a lot of warnings when running ./px4 mainapp.config the warnings didn't stop so I halted the execution (ctrl + c)

mainapp.log
http://pasted.co/30b6beae

mini-dm
http://pasted.co/d7709ab1

**Comment by r0gelion** [comment]
make distclean solved the issue (I thought I did that, but I didn't)

No param issues.

mainapp.log
http://pasted.co/e4ac79e9

mini-dm
http://pasted.co/0bc17859

make output
http://pasted.co/efd9165c

**Comment by LorenzMeier** [comment]
Did you try to fly?

**Comment by santiago3dr** [comment]
couple indoor flights with a small 200qx quad
https://logs.px4.io/plot_app?log=53f84bb4-2946-4e3a-a1d9-2533b7e89e64
https://logs.px4.io/plot_app?log=1d3603ce-3396-4343-9cc4-7ca882479307

**Comment by dagar** [comment]
These logs have 4 instances of every topic, but in the handful of cases I checked there's only data in the first instance.

image

**Pull request merged**
