### PR TITLE
Bringup m1

### PR DESCRIPTION
**Pull request by mcharleb**
bringup branch rebased on px4:master

Adds SITL test functionality. 

uORB refactoring. Problem with NuttX linking due to use of std::string.

### CODE REVIEW

**Comment by mcharleb** [comment]
The issue with C++ STL and NuttX was resolved and libstdc++ is no longer required for the NuttX build.

**Comment by LorenzMeier** [comment]
@mcharleb Please see the Travis output for build breakage. In particular the ```make tests``` command broke.

**Comment by LorenzMeier** [comment]
@mcharleb Can we replace these calls with something in the local file system, given that the path already changed from what it used to be in NuttX? It would be great to get to a point where we do not require super user rights for SITL soon.
```
sudo mkdir -p /fs/msdcard
sudo chmod 777 /fs/msdcard
```

**Comment by LorenzMeier** [comment]
Also these of course:
```
sudo mkdir -p /eeprom
sudo chmod 777 /eeprom
```

**Comment by LorenzMeier** [comment]
There seems to be an inconsistency between ```/fs/msdcard``` and ```/fs/microsd``` - the latter is what is used in NuttX. Can we settle for ```~/px4/``` for the Linux / POSIX build?

**Comment by LorenzMeier** [comment]
@mcharleb even after creating /fs/microsd I still have issues with the system startup - the navigator prints a file related error I didn't fully understand yet.

**Comment by LorenzMeier** [comment]
@tumbili Would be great if you could cross-test and complete the ```make posixrun``` target so that things are consistently reproducible. We really, really need to get out of the current situation where things are moving so wildly that half the dev team can't even launch a test case at any given point in time.

**Comment by mcharleb** [comment]
I can make the locations settable from start args and create a sane default
under current dir.

**Comment by LorenzMeier** [comment]
That sounds fair to me.

**Comment by mcharleb** [comment]
This finally has a chance of passing all the gtests. Most of the errors that were seen when running the simulator have been cleaned up. Doing make posixrun now runs the tone_alarm (simulator) in rc.S. I also added a builtin sleep function as there were issues with the sensors module starting before the simulated devices had finished initializing.

I have not yet added the changes for the file paths not being at the root of the filesystem for posix builds.

**Pull request merged**
