### PR TITLE
[READY FOR test] Add f7 bl update

### PR DESCRIPTION
**Pull request by davids5**
@DanielePettenuzzo - please test

### CODE REVIEW

**Comment by davids5** [comment]
We need to see if the Nuttx Driver needs the dsb instructions added as in https://github.com/PX4/Bootloader/blob/master/main_f7.c#L570

**Comment by DanielePettenuzzo** [comment]
@davids5 I tried it a couple times with two different bootloader binaries and it seems to work on fmu-v5 (pixhawk 4).

**Comment by davids5** [comment]
@DanielePettenuzzo - Are you comfortable the the level of testing to bring this in?

**Comment by DanielePettenuzzo** [comment]
@davids5 I tried this on 4 new pixhawk 4 and it was always successful

**Comment by dagar** [comment]
Rebase and merge?

**Comment by davids5** [comment]
@dagar rebased on master

**Comment by davids5** [comment]
@dagar I am waiting on some definitive feedback before merging.

**Pull request merged**
