### PR TITLE
implement MAV_CMD_MISSION_START

### PR DESCRIPTION
**Pull request by dagar**
Used to start a mission (at a particular index) and arm in a single command.
Only changes to AUTO_MISSION if the mission is valid, and only arms if the mode change wasn't denied.

### CODE REVIEW

**Comment by dagar** [comment]
The mavlink spec lists a first_item, and last_item. Could we update the wording to make last_item optional?

**Comment by LorenzMeier** [comment]
Looks generally good, but needs testing - @AndreasAntener can you review?

@dagar I think we can make the last item optional if set to 0.

**Comment by dagar** [comment]
Basic testing in SITL to arm and initiate a mission at the first waypoint and arbitrary. Also used during an active mission in place of MISSION_SET_CURRENT which reloads from dataman.

@AndreasAntener what about interrupting a non default work_item_type?

Do we care about onboard missions? I originally had this update the index for either depending on mission type, but I came across some onboard inconsistencies.

**Comment by LorenzMeier** [comment]
Reviewed again, good to go, thanks!

**Pull request merged**
