### PR TITLE
Compile fixes for old/unused targets.

### PR DESCRIPTION
**Pull request by CarloWood**
These are some changes that I needed to compile
most of the unsupported targets.

After this all (make list_config_targets) compile
for me except: posix_eagle_muorb, posix_sdflight_default
and qurt_eagle_legacy_driver_default.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! @bharath374 @mcharleb @jywilson Can you have a look and advise what we do with these?

**Comment by CarloWood** [comment]
If this is the last change, then just cherry-picking cfa0f0 will do ;)

**Comment by LorenzMeier** [comment]
Jenkins add to whitelist

**Comment by LorenzMeier** [comment]
@CarloWood Could you rebase this on master?

**Comment by CarloWood** [comment]
Done :)

**Comment by julianoes** [comment]
@CarloWood thanks for going through this.

Let me try to comment/clarify:

> After this all (make list_config_targets) compile
for me except: posix_eagle_muorb, posix_sdflight_default
and qurt_eagle_legacy_driver_default.

`posix_eagle_muorb`: I don't know what this is for.
`posix_sdflight_default`: This is re-used by `posix_eagle_default` and `posix_excelsior_default`, I assume you realized that? It should not actually be a target by itself.
`qurt_eagle_legacy_driver_default`: This needs an additional folder set in the env variable `FC_ADDON` as described here: https://github.com/ATLFlight/ATLFlightDocs/blob/1c13a6f3474ba3163cb74b715c5dd62ab3ea929b/PX4.md#building-px4-with-the-fc_addon-drivers

**Comment by CarloWood** [comment]
@julianoes Thanks for this info! Unfortunately, I can't "Login to the Intrinsyc support website and download the latest Flight Controller AddOn" because I don't have a serial number... I did get the Flight_3.1.1_qrlSDK.zip directly from someone at Intrinsyc after emailing them, but well... Don't feel like begging for another proprietary file :/. If any of the devs can give it the ADDON to me then please :) 

How about the PR itself? I have to admit that I've been gambling a bit with regard to these fixes, but at least it compiles with this - and it doesn't without. [Note that breakage seems to have come from code duplication, which is Evil(tm); my guess is that at some point an existing file was copied and slightly changed because that was the easiest way to add support for a new target. Then later someone working on target 'X' only updated the file for target X, not knowing about the duplicate Y or afraid to change something that they can't compile/test. But in the mean time the nobody was compiling target Y anymore (apparently, cause it's broken). So, what I did was "sync" whatever wasn't compiling anymore with what seemed to be the most recent update of this (duplicated) code. If I was more knowledgeable about the subject then I might have removed the code duplication completely by putting it in a single file and including that, instead of having copies (like posix_sdflight_default)]

**Comment by julianoes** [comment]
You are correct with your analysis. And it's indeed stupid that you can't get this proprietary file.

I think this PR is worth having, it's for sure not introducing any regressions.

**Comment by LorenzMeier** [comment]
Thanks!

**Pull request merged**
