### PR TITLE
simulator: create standalone battery simulator module

### PR DESCRIPTION
**Pull request by dagar**
As a small step towards unifying SITL and HITL I've broken the battery simulator portion of the simulator module out as a simple standalone module.

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
I actually wanted to make a battery plugin for SITL gazebo, but seems like we are missing a HITL mavlink message for it. Do you think I should add one? or do you have a better idea on how we can make this possible?

**Comment by dagar** [comment]
> @dagar I actually wanted to make a battery plugin for SITL gazebo, but seems like we are missing a HITL mavlink message for it. Do you think I should add one? or do you have a better idea on how we can make this possible?
> 
> Related: #15034

That would be great. You could start with the existing BATTERY_STATUS (https://mavlink.io/en/messages/common.html#BATTERY_STATUS) and from there we can decide if a dedicated simulation battery message is necessary.

**Comment by Jaeyoung-Lim** [comment]
@dagar Okay, so I guess this would mean that the plugin will directly talk to the GCS and not to the firmware

**Comment by dagar** [comment]
> @dagar Okay, so I guess this would mean that the plugin will directly talk to the GCS and not to the firmware

No, I was talking about sitl_gazebo mavlink to the PX4 simulator. Within PX4 it would then effectively be `Mavlink BATTERY_STATUS (simulator)` => `uORB battery_status` => `Mavlink BATTERY_STATUS (mavlink module)` => `GCS`.

**Comment by julianoes** [comment]
So given the discussion should I still review this?

**Comment by Jaeyoung-Lim** [comment]
@julianoes Yes please, my comment is not directly related to this PR

**Pull request merged**
