### PR TITLE
Pr rc filtering

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@MaEtUgR @dagar We should bring this in and then remove it with the stick mapper. We need weeks worth of validation for the massive stick mapper change and we need the filtering earlier. We can't fix this one by rewrite easily.

**Comment by MaEtUgR** [comment]
Not finished yet!

**Comment by LorenzMeier** [comment]
@MaEtUgR This looks good. If its test flown and ready to go it can be applied.

**Comment by MaEtUgR** [comment]
Did a successful flight test yesterday. Further testing?
To enable expo in position control set MPC_XY_MAN_EXPO to for example 0.69.
To change filter settings change RC_FLT_SMP_RATE and RC_FLT_CUTOFF to desired values (Cutoff 5Hz made sense for me).

Something I realized:
Slow velocity setpoints get cut out by the deadzone (MPC_HOLD_XY_DZ) and maximum position hold velocity (MPC_HOLD_MAX_XY). I'll report on this when I find a solution.

**Comment by dagar** [comment]
Any interest in generalizing expo or do you only want it for MC position?

**Comment by MaEtUgR** [comment]
I'm totally interested! Sorry for putting it there directly, it's urgent now. Would on the long term be nice to have a central point for such input tweaks such that they are available with a joystick and every mode but I would still keep the option to configure them differently dependent on the flight mode.

Here is the first simple formula version: https://github.com/PX4/Firmware/blob/71dda2cf4462b2a15a2c8fdfd3934be1bca6bc5a/src/lib/mathlib/math/Expo.hpp
Negative expo and other features can follow in the future.

**Comment by MaEtUgR** [comment]
rebased and did further tests today.
- with RC_FLT_CUTOFF = 5 I found good filtering of osciallations when just letting the spring loaded stick go in manual or position mode.
- with MPC_XY_MAN_EXPO = 0.69, MPC_XY_CRUISE ~ 10 and MPC_HOLD_XY_DZ ~ 0.01 (as small as possible) I found very intuitive control over the vehicle velocity in position mode from very gentle small corrections up to full speed.

**Comment by LorenzMeier** [comment]
Awesome!

**Pull request merged**
