### PR TITLE
Update sitl_gazebo submodule

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Describe problem solved by this pull request**
This updates the sitl_gazebo submodule to the latest

The update includes the folloiwng changes
- Fix for jinja transition and git ignores (https://github.com/PX4/sitl_gazebo/pull/602, https://github.com/PX4/sitl_gazebo/pull/600)
- Cleanup for received_actuator (https://github.com/PX4/sitl_gazebo/pull/597)
- Fix geotagged_images return (https://github.com/PX4/sitl_gazebo/pull/601)
- Move iris to jinja templates (https://github.com/PX4/sitl_gazebo/pull/609)

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
SITL tests hang because the `gazmodelspawn` is unable to handle sdf files with a `-gen` suffix

**Comment by Jaeyoung-Lim** [comment]
@dagar I solved it by spawning the file on path `<model>/*.sdf` instead of copying the sdf files in the build directory. I think copying in will break all the use cases that `sitl_gazebo` are used stand alone (e.g. ROS) 

This seems like a more neat solution since the sdf file should always be in the path of either `<model>/<model>.sdf` or `<model>/<model>-gen.sdf`

**Review by julianoes — APPROVED** [review]
Thank! So all of them are generated now?

**Comment by julianoes** [comment]
> SITL tests hang because the gazmodelspawn is unable to handle sdf files with a -gen suffix

Why would that be?

**Comment by Jaeyoung-Lim** [comment]
> Thank! So all of them are generated now?
@julianoes The ones that are run in the tests, yes

> Why would that be?
When the spawnrunner cannot find the sdf file, it seems to continuously run in a loop without any logs. I will look into this

**Review by jkflying — APPROVED** [review]

**Pull request merged**
