### PR TITLE
log velocity - and acceleration/thrust setpoint

### PR DESCRIPTION
**Pull request by tumbili**
- log velocity setpoint and acceleration/thrust setpoint
- good to see w.t.h. controller is doeing

### CODE REVIEW

**Comment by thomasgubler** [comment]
looks good. This is tested I assume?

**Comment by tumbili** [comment]
No, will test it tomorrow since I want to go outside and verify the position controller. Kinda hard to get gps reception in my flat ;-)

**Comment by thomasgubler** [comment]
https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rcS#L117 or jmavsim if you want to be sure that the logging works while inside :snowflake:

**Comment by tumbili** [comment]
Thanks, should get familiar with this, never used it until now.

**Comment by LorenzMeier** [comment]
Looks good, please rebase on master before testing and let us know when we should merge it.

**Comment by tumbili** [comment]
rebased and flight tested

**Pull request merged**
