### PR TITLE
Beta pio memory

### PR DESCRIPTION
**Pull request by davids5**
This regains a bunch of memory.

First note that make oldconfig has been run and the defconfig has been updated.

The FW is now using the interrupt stack. This allows the reduction for both idle and the main task's stack

CONFIG_ARCH_INTERRUPTSTACK = 500 40 Bytes margin
CONFIG_IDLETHREAD_STACKSIZE= 290 - usage is ~136 bytes with a 154 byte margin
CONFIG_USERMAIN_STACKSIZE=800 with a 268 bytes margin 

# Last build of Beta:
```
 px4io status
px4io: loaded
protocol 4 hardware 2 bootloader 3 buffer 64B crc 0x69b3b47b
8 controls 8 actuators 18 R/C inputs 2 analog inputs 0 relays
376 bytes free
status 0x2741 OUTPUTS_ARMED SAFETY_SAFE RC_FAIL FMU_OK MIXER_OK ARM_SYNC INIT_OK
alarms 0x0030 FMU_LOST RC_LOST
vservo 65 mV vservo scale 10000
```

# This build
```
nsh> px4io status
px4io: loaded
protocol 4 hardware 2 bootloader 3 buffer 64B crc 0xa931098c
8 controls 8 actuators 18 R/C inputs 2 analog inputs 0 relays
1496 bytes free
status 0x2741 OUTPUTS_ARMED SAFETY_SAFE RC_FAIL FMU_OK MIXER_OK ARM_SYNC INIT_OK
alarms 0x0030 FMU_LOST RC_LOST
vservo 62 mV vservo scale 10000
vrssi 863
actuators 0 0 0 0 0 0 0 0
servos 0 0 0 0 0 0 0 0
reversed outputs: [________] trims: r:   0.0000 p:   0.0000 y:   0.0000
0 raw R/C inputs
R/C flags: 0x0000
mapped R/C inputs 0x0000
ADC inputs 27 1768
features 0x0008 RSSI_ADC
arming 0x0030 FMU_DISARMED IO_ARM_DENIED INAIR_RESTART_OK ALWAYS_PWM_ENABLE
rates 0x000f default 50 alt 400
debuglevel 0
controls 0: 498 -691 497 0 0 0 0 0
controls 1: 0 0 0 0 0 0 0 0
controls 2: 0 0 0 0 0 0 0 0
controls 3: 0 0 0 0 0 0 0 0
input 0 min 1000 center 1500 max 2000 deadzone 10 assigned 0 options 0x0001 ENABLED
input 1 min 1000 center 1500 max 2000 deadzone 10 assigned 1 options 0x0001 ENABLED
input 2 min 1000 center 1500 max 2000 deadzone 10 assigned 3 options 0x0001 ENABLED
input 3 min 1000 center 1500 max 2000 deadzone 10 assigned 2 options 0x0001 ENABLED
input 4 min 1000 center 1500 max 2000 deadzone 10 assigned 255 options 0x0000
input 5 min 1000 center 1500 max 2000 deadzone 10 assigned 255 options 0x0000
input 6 min 1000 center 1500 max 2000 deadzone 10 assigned 255 options 0x0000
input 7 min 1000 center 1500 max 2000 deadzone 10 assigned 255 options 0x0000
input 8 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 9 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 10 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 11 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 12 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 13 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 14 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 15 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 16 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
input 17 min 1000 center 1500 max 2000 deadzone 0 assigned 255 options 0x0000
failsafe 0 0 0 0 0 0 0 0
disarmed values 900 900 900 900 0 0 0 0
```

### CODE REVIEW

**Comment by davids5** [comment]
@LorenzMeier 

In debugging this I have seen text_length = 178 Which implies a length of 181 as an input to the routine. That explains why it fails at 180 and the free memory is so much larger. This may be the case with 220 for a size as well. The 36 byte difference (256->220) Still results in a increase of 496 bytes (968 -> 1464)  of free memory

**Comment by LorenzMeier** [comment]
ok. I'll back out that change then.

**Comment by LorenzMeier** [comment]
Force-pushed a version without the buffer change.

**Comment by davids5** [comment]
@LorenzMeier is this good to go?

**Comment by LorenzMeier** [comment]
Needs more in-system testing.

**Comment by LorenzMeier** [comment]
Rebased and applied to master.

**Pull request closed without merging**
