### PR TITLE
FW: simplified flap/flaperon logic and always move them at the same r…

### PR DESCRIPTION
**Pull request by AndreasAntener**
…ate (don't jump)

Outputs checked in SITL

### CODE REVIEW

**Comment by AndreasAntener** [comment]
@dagar something for you to review?

**Comment by dagar** [comment]
Happy to take a look. Do we have working flaps in any SITL or HIL models?

**Comment by dagar** [comment]
Looks good, thanks for getting rid of the statics. I'm not setup to test either flaps or flaperons at the moment. Is there anyone with a working flaps setup that could give this a quick try? @kd0aij?

**Comment by AndreasAntener** [comment]
Thanks, I'm hoping to test that today.

**Comment by AndreasAntener** [comment]
I really like watching flaps go up and down ;) Rebased and applied

**Pull request closed without merging**
