### PR TITLE
update micro-CDR version and msg templates to fit the up to date version

### PR DESCRIPTION
**Pull request by TSC21**
This updates the Micro-CDR submodule to latest `develop` branch of Micro-CDR, with the respective changes on the `micrortps_client` code and templates. Replaces https://github.com/PX4/Firmware/pull/10728.

### CODE REVIEW

**Comment by TSC21** [comment]
Something's wrong on the CI side. There are some "No space left on the device" notices.

**Comment by dagar** [comment]
Tested?

**Comment by TSC21** [comment]
> Tested?

Yes at least the data exchanges points (client and agent) are created and initialised properly. I have not tested the listener to see the data, since it's giving some issues (unrelated with this change).

**Comment by TSC21** [comment]
An example of `micrortps_agent` out (after SIGINT):
```sh
UDP transport: recv port: 2020; send port: 2019; sleep: 1us

Trying to connect...
connected to server!
DebugVect subscriber started
OpticalFlow subscriber started
Airspeed publisher started
SensorBaro publisher started
SensorCombined publisher started
SensorSelection publisher started
^CInterrupt signal (2) received.
Close sender socket
Close receiver socket
Read fail 9

SENT:     0 messages - 0 bytes
RECEIVED: 41877 messages - 2025945 bytes; 1 LOOPS - 120.183 seconds - 16.86KB/s
```

**Pull request merged**
