### PR TITLE
Update sitl_gazebo to latest master

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Describe problem solved by this pull request**
This commit updates the sitl_gazebo submodule to latest master

Relevent changes includes the following
- Remove `-gen.sdf` suffixes for generated sdf files (https://github.com/PX4/sitl_gazebo/pull/621)
- Switch to python3 (https://github.com/PX4/sitl_gazebo/pull/619)
- Fix iris obs avoid sensor location (https://github.com/PX4/sitl_gazebo/pull/618)
- Cleanup unused variables (https://github.com/PX4/sitl_gazebo/pull/616)
- Remove motor model from uuv plugin (https://github.com/PX4/sitl_gazebo/pull/615)
- Typo fixes (https://github.com/PX4/sitl_gazebo/pull/614)

**Test data / coverage**
Tested in SITL / passes SITL CI tests

**Additional context**
- This replaces https://github.com/PX4/Firmware/pull/15854, where it fixes the mavros tests failing

### CODE REVIEW

**Comment by TSC21** [comment]
Tests are failing here

**Comment by dagar** [comment]
For a different reason it seems. https://github.com/PX4/Firmware/pull/15884/checks?check_run_id=1211505914

Screen Shot 2020-10-05 at 8 17 29 PM


Then in https://github.com/PX4/Firmware/pull/15884/checks?check_run_id=1211282294 I see. 
Screen Shot 2020-10-05 at 8 18 13 PM

**Comment by dagar** [comment]
Let's keep picking away at it from this point.

**Review by dagar — APPROVED** [review]

**Comment by Jaeyoung-Lim** [comment]
@dagar Interesting...because none of the model uses sdf 1.7

**Comment by Jaeyoung-Lim** [comment]
@dagar Fixed in https://github.com/PX4/sitl_gazebo/pull/624

**Pull request merged**
