### PR TITLE
commander: always set armed.force_failsafe

### PR DESCRIPTION
**Pull request by julianoes**
@jlecoeur what do you think about this addition?

Note this is against https://github.com/PX4/Firmware/pull/12709.

### CODE REVIEW

**Comment by jlecoeur** [comment]
It is more consistent for sure. Now, I am not sure that this is the best thing to do. 

Termination should be enough on its own, it indicates to the controller that they should stop, see:
https://github.com/PX4/Firmware/blob/5c68880b564d5bc31debc8cb653555f80b919a8d/src/modules/mc_att_control/mc_att_control_main.cpp#L640-L646

https://github.com/PX4/Firmware/blob/5c68880b564d5bc31debc8cb653555f80b919a8d/src/modules/fw_att_control/FixedwingAttitudeControl.cpp#L550-L556 

For example in the FW case, by forcing failsafe values we may prevent parachute deployment.

**Comment by julianoes** [comment]
Interesting, so we have duplicate flags for this. I suppose this needs a more in-depth review/refactor then. Otherwise it might have unforeseen consequences.

**Comment by jlecoeur** [comment]
Yeah :-( 
From what I have just shown, I would even suggest to *remove* the force failsafe when flight termination is ongoing!

**Comment by jlecoeur** [comment]
Also note that these are not duplicate flags. For example in multirotor, the controller sends 0 actuator output, which is neither equal to disarmed value, nor failsafe value.

**Comment by julianoes** [comment]
> For example in the FW case, by forcing failsafe values we may prevent parachute deployment.

That's a big or wrong config then. A parachute should be deployed when failsafe values are set.

> Also note that these are not duplicate flags. For example in multirotor, the controller sends 0 actuator output, 

That also seems wrong.

**Pull request closed without merging**
