### PR TITLE
ekf2: added beta test ratio to estimator_status

### PR DESCRIPTION
**Pull request by CarlOlsson**
Needs changes in ecl: https://github.com/PX4/ecl/pull/371

### CODE REVIEW

**Comment by dagar** [comment]
For the sake of CI and flight testing you could push https://github.com/PX4/ecl/pull/371 to a branch off the main ecl repo and update the commit here. Then once everything is ready we coordinate the ecl merge, then immediately switch to ecl master in Firmware and merge.

**Comment by LorenzMeier** [comment]
@CarlOlsson Could you update?

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by priseborough** [comment]
Rebase when https://github.com/PX4/Firmware/pull/8447 is merged. CI tests should then pass.

**Comment by CarlOlsson** [comment]
Hi, sorry for the late reply, I have been out over Christmas. Do I need to do something here? Looks to me like CI failed due to flash overflow

**Comment by LorenzMeier** [comment]
@CarlOlsson PX4 is not a static thing. If you rebase today you get a completely different result compared to two weeks ago - so please do.

There went well over 150 commits into master since you tried last, so please rebase.

**Comment by dagar** [comment]
@CarlOlsson that CI failure is fixed in https://github.com/PX4/Firmware/pull/8560. Please rebase yet again once it's merged.

**Comment by priseborough** [comment]
When this is merged we can close https://github.com/PX4/Firmware/pull/8405

**Comment by priseborough** [comment]
Be aware that merging this does also includes the following functional fixes and updates for ecl:

Efficiency improvements to sensor data buffering that reduce memory and number of data copy operations.
PX4/ecl#358
PX4/ecl#359

Adds control interface and internal functions fora Baro ground effect disturbance compensation model that can be activated externally.
PX4/ecl#351

Adds an interface and internal functionality for fusion of landing target velocity observations.
PX4/ecl#362

Provides external accessor for FW attitude control integrator state
PX4/ecl#366

Adds missing initialisation of ekf class variables.
PX4/ecl#364

Fixes #8401 loss of navigation message being printed on startup.
PX4/ecl#367

**Pull request merged**
