### PR TITLE
Makefile add doxygen helper

### PR DESCRIPTION
**Pull request by dagar**
Small helper to make it easy to run doxygen.

@mcsauder @hamishwillee 

The current configuration takes quite a long time to generate (many graphs) and the output folder is ~ 1GB. Need to get auto generation and hosting setup. We could probably abuse github pages.

### CODE REVIEW

**Comment by dagar** [comment]
Needs https://github.com/PX4/ecl/pull/488.

**Comment by dagar** [comment]
TODO: Figure out how to use doxygen properly.

 - how do we document per module?
 - how should we tag?

**Comment by dagar** [comment]
https://github.com/PX4/Firmware-Doxygen

**Comment by hamishwillee** [comment]
@dagar 

I am not sure how we document or tag, but when we have this hosted somewhere it can be viewed maybe we can experiment. 

My 2 bits:
- It would be good if we can include existing module documentation inside inside doxygen output. We shouldn't duplicate or waste it.
- I am more concerned about libraries, because we don't document them currently.
- I tend to think that we should build this monolithically (with submodules). Ideally push docs changes to them as needed.

@bkueng - I am sure you have a view? See https://github.com/PX4/Firmware/pull/10090#issuecomment-408870163

**Comment by bkueng** [comment]
Generally I find doxygen valuable for API documentations, so libraries, but also within larger modules. In particular I'd like to see corner cases and error behavior documented more clearly (the rest is often already clear by chosing good class, method & variable names).

Eigen is indeed a very good example, but it's also the only good one using doxygen that I know of.

**Pull request merged**
