### PR TITLE
magnetometer's move to PX4Magnetometer and cleanup

### PR DESCRIPTION
**Pull request by dagar**
I didn't particularly want to do this now as we're closing in on a release, but I found a number of inconsistencies and errors (eg bmm150 completely missing calibration). Many of these drivers are quite similar as they were created by duplicating an existing driver, so this was actually pretty fast and easy to do.

### CODE REVIEW

**Comment by dagar** [comment]
Saves about 2.6 kB of flash on fmu-v2 and > 9 kB on fmu-v4/v5, etc.

**Comment by dagar** [comment]
LIS3MDL temperature looks bogus.

**Comment by dagar** [comment]
Quickly verified hmc5883, ist8310, lsm303d, lis3mdl.

**Comment by dannyfpv** [comment]
pixhawk4 v5 f-450

**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL 

**Notes:**
No issues noted, good flight in general.

**Logs:**
https://review.px4.io/plot_app?log=b6c9e488-ab13-4a01-b09b-54968b6b0062
https://review.px4.io/plot_app?log=f25e9a1c-092f-4211-80e0-af9de92b2fc4

**Comment by Junkim3DR** [comment]
### Tested on NXP FMUK66 V3

**Modes Tested**
- Position Mode: Good.
- Altitude Mode: Good.
- Stabilized Mode: Good.
- Mission Plan Mode (Automated): Good.
- RTL (Return To Land): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint then trigger RTL.


**Notes**
No issues noted, good flight in general.

**Logs**
- https://review.px4.io/plot_app?log=234626e0-8e65-450e-ad2e-b2ab5d93867e
- https://review.px4.io/plot_app?log=c69cd3df-0328-42a1-89ab-189219caa288

**Comment by jorge789** [comment]
### Tested on PixRacer V4

**- Modes Tested**
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.
**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC,  once completed all waypoint then swith RTL..
**- Notes
In altitude mode, the vehicle did not respect the height that continued to increase in pitch forward**

**Log:** 
https://review.px4.io/plot_app?log=e6f911c2-f5a2-48bc-ab05-a2033626add9

https://review.px4.io/plot_app?log=ac5ee748-7309-4945-99b1-f5967b3e853d

**Comment by dannyfpv** [comment]
pixhawk4 mini v5 f-500

Modes Tested

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

- Procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL

Notes:
No issues noted, good flight in general.

Logs:
https://review.px4.io/plot_app?log=f97f9b2d-0d08-4d54-9326-6bdc27fdb10c
https://review.px4.io/plot_app?log=7e10a7d8-5513-4f27-b534-a5d699c378ed

**Pull request merged**
