### PR TITLE
mavlink_log refactor take 2

### PR DESCRIPTION
**Pull request by julianoes**
Since we can't use the ioctl call on Snapdragon, let's move the mavlink_log calls from ioctls to the uORB interface.

This is a second (hopefully threadsafe) refactor and replaces #3984.

@LorenzMeier please review.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looking good on first pass, but we'll need the file-level logging in again since that's a critical part of the user support. It makes all the difference in working out what went wrong for them.

**Comment by julianoes** [comment]
@LorenzMeier file logging is back in and tested in SITL and on NuttX.

One thing to note is that there is no buffering right now and I'm not sure how to resolve it. I guess it will just depend on the priority of the tasks vs. mavlink whether subsequent messages all make it through or not.
The right way would be to support some buffering by the uORB.

**Comment by julianoes** [comment]
@AndreasAntener any chance you could give this a try and check if it breaks stuff for you?

**Comment by LorenzMeier** [comment]
I don't get why you had to disable / change the buffering code. It's essential and we need it.

**Comment by julianoes** [comment]
@LorenzMeier ok sure, I'll have another look.

**Comment by julianoes** [comment]
Closing, superseeded by #4057.

**Pull request closed without merging**
