### PR TITLE
Avionics power only circuit breaker

### PR DESCRIPTION
**Pull request by simonegu**
**Describe problem solved by the proposed pull request**
The `CBRK_SUPPLY_CHK` circuit breaker is used  to disable the preflight checks
https://github.com/PX4/Firmware/blob/103fcc6c0583645e742a1ecac1651554bc73f9c3/src/modules/commander/PreflightCheck.cpp#L706 
https://github.com/PX4/Firmware/blob/103fcc6c0583645e742a1ecac1651554bc73f9c3/src/modules/commander/PreflightCheck.cpp#L936-L940
but also the low battery arming behavior.
https://github.com/PX4/Firmware/blob/103fcc6c0583645e742a1ecac1651554bc73f9c3/src/modules/commander/state_machine_helper.cpp#L909-L929 

**Describe your preferred solution**
The new circuit breaker `CBRK_AVIO_CHK` disables only the avionics checks (5V and 3.3V) without impacting the arming behavior on low battery. This solution does not impact the behavior on the `CBRK_SUPPLY_CHK` circuit breaker.

Maybe we should separate the two functionalities, thoughts?

### CODE REVIEW

**Comment by dagar** [comment]
Additionally, wouldn't it make more sense to make the avionics power checks configurable per board? Isn't that the underlying issue here?

**Comment by dagar** [comment]
Personally I don't even like the circuit breakers in many cases. What about a more explicit list of preflight checks? Likely a big bitmask of options in a single parameter.

Things like low battery can already be covered by the existing battery failsafe parameters.

**Comment by simonegu** [comment]
@dagar make sense. If i understood you correctly, this would then be part of the board configuration or do you think a parameter could be useful?
Do you think we should do it for all the different preflight checks?

**Comment by dagar** [comment]
> @dagar make sense. If i understood you correctly, this would then be part of the board configuration or do you think a parameter could be useful?

Board configuration if possible, or if it's a variant of an existing board we could make the levels configurable via parameter.

> Do you think we should do it for all the different preflight checks?

Yes, I want to collect them all into a bitmask parameter. From there I want to expand the checks and add more granularity. Something like COM_ARM_REQ, that will consume the current arming requirement parameters like COM_ARM_WO_GPS and COM_ARM_MIS_REQ and add all these new pieces.

**Comment by simonegu** [comment]
Ok, let me close this PR then. Will try to squeeze the functionality in next week :smile:

**Pull request closed without merging**
