### PR TITLE
PWM drivers for Lidar Lite

### PR DESCRIPTION
**Pull request by Zefz**
This is the begin of porting the I2C drivers for LidarLite to read using PWM instead. The same module should be able to handle both and the different driver protocol would be instantiated this way:
```
ll40ls start i2c
ll40ls start pwm
```
(and use i2c by default for backwards compatibility if no protocol is specified).

[Here](https://github.com/PulsedLight3D/LIDARLite_Basics/blob/master/Arduino/LIDARLite_PWM_GetDistance_ContinuousRead/LIDARLite_PWM_GetDistance_ContinuousRead.ino) is the LidarLite official PWM code for Arduino.

Note that there is a bug in the PWM firmware of the LidarLite and the software fix is shown [here](https://github.com/PulsedLight3D/LIDAR_Lite_PWM_Fix).

[Here](https://github.com/diydrones/ardupilot/blob/master/libraries/AP_RangeFinder/AP_RangeFinder_PX4_PWM.cpp) is ArduPilot's take on reading PWM rangefinder using PX4.

@LorenzMeier Can you point me in the direction of a [pulseIn](http://arduino.cc/en/Reference/pulseIn) equivalent for PX4?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
The architecture of the drivers looks neat. Here is the PWM input capture you were asking about: https://github.com/PX4/Firmware/tree/master/src/drivers/pwm_input

**Comment by TSC21** [comment]
Looking up for this :D @Zefz if you need any help on coding or just a tester, let me know ;)

**Comment by Zefz** [comment]
Feel free to continue development on this PR. I'm currently trying to see if I really can't get I2C mode working properly.

It seems LidarLite has some I2C issues where it can hang the entire I2C bus for a period of time (which interferes with other components like external magnetometer).

**Comment by TSC21** [comment]
Thanks! From what I can see, that seems to be a LIDAR Lite firmware problem. Unless there some electronic misconception. Mine is from before March (I was one of the 30 early-birds of the project on Dragon Innovation), so I suppose I will suffer from the same problem.
Already tried the Arduino PWM code and seems to be working fine. Didn't tried I2C yet.

**Comment by LorenzMeier** [comment]
@bansiesta ping

**Comment by Zefz** [comment]
@LorenzMeier Note that I have discontinued development on this PR, but I have not removed it in case anyone else was interested in picking up where I left.

**Comment by TSC21** [comment]
@Zefz what is left to be done?

**Comment by TSC21** [comment]
Related to this topic: https://github.com/mavlink/mavros/pull/296. This means that publishing LIDAR Lite data to a `DISTANCE_SENSOR` type uORB topic is a must or desired feature - https://github.com/PX4/Firmware/issues/1986.

**Comment by TSC21** [comment]
https://github.com/PX4/Firmware/pull/2200 is the starting implementation of `DISTANCE_SENSOR` adoption of firmware side. Tips are welcomed @Zefz.

**Comment by bansiesta** [comment]
@LorenzMeier Ping ACK, working on this...

**Comment by TSC21** [comment]
@bansiesta is it possible you could develop this against #2200?

**Comment by bansiesta** [comment]
@TSC21: Ok, I'll try to get PWM up and running first and then look at #2200.

**Comment by TSC21** [comment]
@bansiesta thanks!

**Comment by bansiesta** [comment]
I have combined that with #2196 and it looks promising, I'll commit it all tomorrow.

```
nsh> ll40ls test pwm
ll40ls: single read
ll40ls: measurement: 1.85 m
ll40ls: time:        0
ll40ls: periodic read 0
ll40ls: measurement: 1.837 m
ll40ls: time:        0
ll40ls: periodic read 1
ll40ls: measurement: 1.830 m
ll40ls: time:        0
ll40ls: periodic read 2
ll40ls: measurement: 1.832 m
ll40ls: time:        0
ll40ls: periodic read 3
ll40ls: measurement: 1.818 m
ll40ls: time:        0
ll40ls: periodic read 4
ll40ls: measurement: 1.821 m
ll40ls: time:        0
ll40ls: PASS
```

**Pull request merged**
