### PR TITLE
Sensor cal rework

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
This is a major rework of sensor cal to provide better usability. It requires a companion pull from QGroundControl to make it all work:
- Calibration can now be cancelled
- More lenient rest position detection for mag cal
- Calibration messages are versioned so QGC can stay in sync
- Other things I forgot

This has been before and after tested with QGC/Firmware combination to make sure generated cal values come out the same.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
QGC pull: https://github.com/mavlink/qgroundcontrol/pull/1503

**Comment by DonLakeFlyer** [comment]
@LorenzMeier I have not yet added rotation detection to mag cal. I needed to update the QGC state machine to correctly wait for that and set images correctly. I will do that in a separate pull.

**Comment by LorenzMeier** [comment]
Closing this in favor of rebased PR.

**Comment by LorenzMeier** [comment]
Closing in favor of #2091.

**Pull request closed without merging**
