### PR TITLE
build: avoid wiping an existing PYTHONPATH variable

### PR DESCRIPTION
**Pull request by tridge**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This exact change leads to build errors on Windows (Randy). Please check with him for a patch which works on both platforms you're using ;-).

**Comment by LorenzMeier** [comment]
We still need a way to prevent a backslash-containing Windows python path ENV leaking into the toolchain here, as everything explodes. Maybe using uname to identify the CYGWIN env and ignoring it?

**Comment by tridge** [comment]
ArduPilot is building fine for Randy on Windows with this patch (it is in ArduPilot master). I don't know about the native build on Windows.

**Comment by LorenzMeier** [comment]
Fair enough, applied via cherry-pick!

**Pull request closed without merging**
