### PR TITLE
POSIX: Fixes for HRT implementation of simulated HW clock polling

### PR DESCRIPTION
**Pull request by mcharleb**
There is a race condition for the accel and mag polling rates.
Whichever one gets set first, the other will be uninitialized.
    
Set the mag polling rate to 1ms if uninitilized.

The workqueues measure time in ticks  which is typically 10ms.
Some interrupt events in Nuttx occur at about 1ms so a more
granular workqueue is needed for POSIX.

Added a separate hrt_queue for handling fast periodic events.

### CODE REVIEW

**Comment by tumbili** [comment]
@mcharleb Is this ready for testing?

**Comment by mcharleb** [comment]
This should be OK for testing now.

**Comment by tumbili** [comment]
@mcharleb Thanks!

**Comment by LorenzMeier** [comment]
Code wise the changes look good and valid. No surprise it didn't work well before since we rely on the us-resolution scheduling in a lot of places. Can be merged once testing says its ready.

**Comment by mcharleb** [comment]
I don't see where the failures are?

**Comment by LorenzMeier** [comment]
You need to download the log and search for "Error 1", which will get you straight here:
```
[1m/home/travis/build/PX4/Firmware/src/platforms/posix/drivers/airspeedsim/airspeedsim.cpp:217:16: [0m[0;1;31mfatal error: [0m[1m
      comparison of integers of different signs: 'unsigned long' and 'long'
      [-Wsign-compare][0m
  ...if (ticks < USEC2TICK(_conversion_interval))
[0;1;32m          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m1 error generated.
```

**Pull request closed without merging**
