### PR TITLE
Fix comparison error in RC+GPS triggered FTS failsafe check

### PR DESCRIPTION
**Pull request by NaterGator**
This bug would cause loss of RC + loss of GPS to trigger a FTS when flying in non-manual modes with a good data link but no RC signal

### CODE REVIEW

**Comment by NaterGator** [comment]
@LorenzMeier would you mind taking a quick look at this to verify the expected behavior?

**Comment by LorenzMeier** [comment]
Sorry it took some time. I initially didn't understand it, but yes, it looks like this should go in as-is. I'm not sure if there was a typo or initial testing value which accidentally went in.

Do you guys do a lot of failsafe testing? We have not touched that much lately (its expected to work hence) and I'd be interested in recent test results.

**Comment by NaterGator** [comment]
No problem. I am a bit conservative and wouldn't say "a lot" of failsafe testing, but we have exercised these failsafes and they worked as expected.

**Comment by LorenzMeier** [comment]
I've cherry-picked your commit.

**Pull request closed without merging**
