### PR TITLE
Detect external buses on FMU variants correctly and clean up driver implementation

### PR DESCRIPTION
**Pull request by dagar**
- merge posix and nuttx Device and CDev
 - create px4_i2c_bus_external/px4_spi_bus_external helpers
   - implement special handling for FMUv3 (all i2c external, all spi internal)
 - push per driver external checks into Device class

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@dagar I'm currently testing this.

**Comment by LorenzMeier** [comment]
Compile error:

```
In file included from /Users/distiller/Firmware/src/drivers/device/device.h:37:
/Users/distiller/Firmware/src/drivers/device/CDev.hpp:110:18: fatal error: 
      'device::CDev::read' hides overloaded virtual function
      [-Woverloaded-virtual]
        virtual ssize_t read(file_t *filep, char *buffer, size_t buflen);
                        ^
/Users/distiller/Firmware/src/drivers/device/Device.hpp:96:14: note: hidden
      overloaded virtual function 'device::Device::read' declared here: type
      mismatch at 1st parameter ('unsigned int' vs 'device::file_t *')
        virtual int     read(unsigned address, void *data, unsigned coun...
                        ^
```

**Comment by LorenzMeier** [comment]
@PX4TestFlights @mrpollo Please add this to the test queue.

**Comment by dagar** [comment]
I've verified a few different pixhawk 2.1 configurations with different mags connected to different buses and different board and external mag rotations. Things seem to be correctly marked as external now, but there are still minor issues.

For example the hmc5883 i2c rotation supplied here is not correct. https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rc.sensors#L77

**Comment by dagar** [comment]
Here's a pixhawk 2.1 cube with current master. The pixhawk is rotated roll 180, and there's an hmc5883 mag connected to the GPS 2 port (aka "internal" i2c).

ph2_orig_roll180

**Comment by LorenzMeier** [comment]
Do you feel you can finish rotations and I can focus on just validating them?

**Comment by dagar** [comment]
Yes, and I think we're nearly done, but one question is how to handle the situation where a rotation is supplied on the command line for an external mag. https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rc.sensors#L77

Should the driver ignore that command line for an external or do we work around it in rc.sensors?

**Comment by LorenzMeier** [comment]
Just ignore for an external? I'm also fine with working around it for now.

**Comment by r0gelion** [comment]
@LorenzMeier we don't have a Pixhawk 2.1 to test.

**Comment by dagar** [comment]
@r0gelion testing other FMUv3 variants would help as well.

**Comment by msadowski** [comment]
@dagar I just tested this fix with i2c rangefinder (TeraRanger Evo) on Pixhawk 2.1 and couldn't make it work. Are there any extra steps that have to be performed to make it work?

**Comment by dagar** [comment]
@msadowski can you try the other i2c bus? Please open a new issue if you can't get it working.

**Pull request merged**
