### PR TITLE
[WIP] Mag Validator

### PR DESCRIPTION
**Pull request by stephanbro**
See PX4/ecl#239 and #5843.

Along with the ecl update, this adds a type concept to the data validator to allow for specific error checking based on what the data is coming from. This PR also implements an inclination lookup table which can be used to detect magnetometer errors when comparing against the magnetometer's current inclination ([See this paper](https://github.com/PX4/Firmware/issues/www.mdpi.com/1424-8220/14/11/20008/pdf)).

Things are generally working, but I'm having a bit of issue with the current inclination value looking off when I tilt the UAV. Any insight into what could be the issue would be greatly appreciated.

### CODE REVIEW

**Comment by mhkabir** [comment]
@stephanbro did you ever figure this out?

**Comment by ll-stephan** [comment]
It sounds like this might already be addressed in #5843. I can verify this week, but this can probably be closed.

**Comment by stephanbro** [comment]
It sounds like this might already be addressed in #5843. I can verify this week, but this can probably be closed.

**Comment by dagar** [comment]
[sensors-14-20008.pdf](https://github.com/PX4/Firmware/files/2546172/sensors-14-20008.pdf)

Attaching paper referenced above (link was broken).

**Comment by dagar** [comment]
@priseborough any interest in this?

**Comment by priseborough** [comment]
These checks will fail when taking off from a metal surface or near other another source of mag interference. We already have mag inclination and strength tables and do consistency checking between mags before takeoff. Mag inclination ad field strength is also used internally by the EKF to place limits in mag field learning.

I am interested in this as a general concept, but am concerned about the number of false positives created. We would need a way to interact with the user to help them clear the fault an also change checks criteria when operating in a known indoor environment.

**Comment by dagar** [comment]
Given the state of the PR I think we have no choice but to close as stale. If anyone is interested in picking this up I can help resurrect the pieces quickly.

**Pull request closed without merging**
