### PR TITLE
Commander: prevent the user from arming the system with USB

### PR DESCRIPTION
**Pull request by LorenzMeier**
@tumbili This addresses #3048.

### CODE REVIEW

**Comment by tumbili** [comment]
@LorenzMeier I guess this just needs testing?

**Comment by LorenzMeier** [comment]
Yes, anything without specific comments: Code review + testing.

**Comment by tumbili** [comment]
@LorenzMeier I tested this and it won't let me arm if I have or had the usb cable connected.
However, since I still have the wrong boot loader on the PH V2 I cannot test if I can still arm because I always have to connect usb first :-) I will test it in the lab tomorrow and upload the correct boot loader.

**Comment by tumbili** [comment]
@LorenzMeier Tested, works, merging!

**Pull request merged**
