### PR TITLE
Flight style

### PR DESCRIPTION
**Pull request by LorenzMeier**
This branch is working towards supporting different flight styles from smooth to sport / pro and allowing users to set a range of limit / max params conveniently.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This adresses #2576

**Comment by LorenzMeier** [comment]
@sjwilks @AndreasAntener Would you mind testing this one as well? It differentiates between auto min-throttle and manual min-throttle (so you can still do gravity flips if you want to). I'd love to get this into the current release.

**Comment by SimonWilks** [comment]
Yes, will try to test this too today, tomorrow latest.

**Comment by LorenzMeier** [comment]
Did you happen to test this yet?

**Comment by SimonWilks** [comment]
Ada will test it this afternoon with his 250 setup. Our TBS is still dead.

**Comment by AndreasAntener** [comment]
Wouldn't it make sense to scale the inputs to the range between min/max thrust? You can now remove the deadband for manual Anton mentioned, but you'll loose yaw control again.

**Comment by LorenzMeier** [comment]
Anton wants to loose yaw control as it's more "real". There is fundamentally no way in an under actuated system. You need to fulfill the constraints and for us this means having some minimum and maximum throttle.

**Comment by AndreasAntener** [comment]
I did a quick flight now with manual min/max to 0/1, seems to work. In manual it tumbles down, in altctl it comes down stable. Interestingly it didn't loose yaw on full throttle in manual. Unfortunately I don't have a log to show, I think my sdcard slot on the V1 is pretty dead now.. Might need todo a test on something else.

I still think scaling the input to the actual range would make sense, even with this. The non-FPV racer  doesn't have to "know" we limit throttle, but I'm guessing he expects to see a reaction on the whole range of his stick.

**Comment by LorenzMeier** [comment]
Rebased and applied to beta. I think I now understand what you mean with whole stick range. We can still add that. Do you feel the deadzones are right now very noticeable?

**Comment by AndreasAntener** [comment]
To be honest, no ;)

**Pull request closed without merging**
