### PR TITLE
FMUv5 IO Driver

### PR DESCRIPTION
**Pull request by LorenzMeier**
@laube I've quickly tested it. Output looks good so far (but I see a couple of INF values at the end), but the upgrade fails with a CRC failure. Is there an off-by-one or alignment issue?

### CODE REVIEW

**Comment by laube** [comment]
I think we have to look into the DMA issues as described [here](https://github.com/PX4/Firmware/pull/8490#issuecomment-356089146) to fix INF values.

What are you referring to when you say CRC failure during upgrade? Upgrade of the firmware?

**Comment by LorenzMeier** [comment]
@laube Any update on this?

**Comment by laube** [comment]
Working on it, will give you an update at lunch time.

**Comment by laube** [comment]
The sequence is the following:
- The CRC of the IO firmware does not match (since it was the factory programmed firmware image)
- IO is put into bootloader mode
- Firmware is uploaded
- The bootloader does not exit after the firmware has been uploaded
- It does not work.

But sometimes the update succeeds (I am still investigating why this is) After it succeeds the first time, startup works fine every time. CRC matches every time.

So, what do you think? It might be a bootloader communication problem caused by NuttX serial drivers? 
Or maybe a timing issue since the F7 is a faster processor?

**Comment by laube** [comment]
@LorenzMeier 

This is fixed now. Have a look at my original branch here:
https://github.com/PX4/Firmware/pull/8629

I will now conduct a test on v2 hardware.

**Comment by laube** [comment]
Ok, works on px4fmu-v2 as well. This should be ready to merge when the two commit from `laube:master_fmuv5_px4io` are added.

**Comment by LorenzMeier** [comment]
@dagar is Appveyor supposed to pass? If not, shall we disable?

**Comment by dagar** [comment]
I didn't enable appveyor. @MaEtUgR FYI

**Comment by LorenzMeier** [comment]
Rebased version: https://github.com/PX4/Firmware/pull/8668

**Comment by MaEtUgR** [comment]
@dagar You can get rid of it.
It originated from my first tests to bring up a stable windows build support which I didn't intend to attach to each pr. I even checked a box for only checking tagged commits. But that obviously didn't work. Sorry for any inconvenience.

**Pull request closed without merging**
