### PR TITLE
Tailsitter mixer

### PR DESCRIPTION
**Pull request by tumbili**
@LorenzMeier @kd0aij Flight tested with the Cairpi, works!

### CODE REVIEW

**Comment by tumbili** [comment]
I will push one last commit.

**Comment by tumbili** [comment]
Tested with quad and caipirinha, works as expected!

**Comment by kd0aij** [comment]
@tumbili Thanks for straightening this out. 
But I don't think you need to reduce the output scaling in the default mixer. I only had it in there because it doesn't seem to work with the mixer on SD card.

**Comment by tumbili** [comment]
@kd0aij Thanks, I'll revert that!

**Comment by LorenzMeier** [comment]
I'm not sure if reverting is good. It might make sense to not allow either control channel to saturate the outputs. It could explain why you loose complete authority in some circumstances.

**Pull request merged**
