### PR TITLE
Increase GPS altitude weights for INAV. Needs extensive flight testing

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
With gains:

+    param set INAV_W_Z_BARO     0.25
+    param set INAV_W_Z_GPS_P    1
+    param set INAV_W_Z_GPS_V    1

http://logs.uaventure.com/view/G9fxaDR95WQa4VfphG8axa

**Comment by LorenzMeier** [comment]
With the exact gains from this PR:
http://logs.uaventure.com/view/UWkEeaoReEbEEfXpxiYE8V

**Comment by LorenzMeier** [comment]
And pretty awesome GPS quality:
gps_uncertainty

**Comment by mhkabir** [comment]
@LorenzMeier What GPS system is that?

**Comment by AndreasAntener** [comment]
Great :) Did your reduced settings take the edge off a little? I'll give those a try as well.

@mhkabir I had the same good GPS performance yesterday with the default 3DR GPS

**Comment by kd0aij** [comment]
testing the assertion: "GPS velocity, which tends to be more robust than absolute GPS altitude" for my case near tall trees.
 3DR GPS (Ublox LEA6, 2.5cm ceramic patch antenna) 

derivative of GPS altitude plotted against GPS vertical speed looks like a filtered derivative of altitude:
velcheck1

**Comment by kd0aij** [comment]
Ublox Neo-7M from HobbyKing (with Lidar), absolute error of GPS on the order of 10m:
gpsvelcheck1

**Comment by kd0aij** [comment]
above log showing baro, gps and lidar altitude. Baro variation is within 2m of ground truth (lidar), and GPS altitude precision is not good enough:
barovsgps

**Comment by AndreasAntener** [comment]
@kd0aij could you share those logs? My main question is if the weight "fallback" to baro works for you in that case?

**Comment by kd0aij** [comment]
http://logs.uaventure.com/view/wyyobUZKS8X9ziwiXz7NuT
http://logs.uaventure.com/view/4o8UgHr5VASPL6rTaCiX5P

@AndreasAntener Those are old logs, and the AeroQuad was using the LPE estimator. I was unaware that INAV could "fall back" to baro under some conditions. When was the fallback logic added? 
I can try this PR on the AeroQuad today if the weather holds; would be nice to have the Lidar for ground truth, but don't know if that's possible without changing code.

**Comment by AndreasAntener** [comment]
That would be great, just remember to turn on INAV ;). It should log your lidar anyway and INAV also fills the terrain estimator from Roman which will give you a filtered bottom clearance.

I'm not sure if the fall-back was added later or not. It works like this: The GPS weights we increased in this PR are scaled with EPV. Specifically, if EPV is <=2 it will take the full weights, above 2 it scales them.

**Comment by kd0aij** [comment]
Guess I was too ambitious to hope for Lidar data with this. Seems like disabling LPE and enabling INAV causes the Lidar to be disabled after boot. 
Unfortunately, flashing this branch and/or changing those enables appears to have exposed a bug in parameter handling: I got errors saying sensors weren't calibrated, and after reloading params from a file mag, accel and gyro are failing selftest. Maybe recalibrating will clear that problem, but this is a real PITA.

**Comment by AndreasAntener** [comment]
We fly exclusively with with INAV and lidar.

**Comment by kd0aij** [comment]
Accel calibration failed; no idea what was wrong there, so:
Just enabled INAV in my working branch and changed the 3 gains in this commit: http://logs.uaventure.com/view/aFP87fHJBBRPUBhzDwmm4Z
Altitude control was reasonably well behaved, but not very precise.
inav_altctl

**Comment by AndreasAntener** [comment]
Thanks, looks like your baro does a much better job than your GPS. Maybe we need to reduce the weights a bit still.

**Comment by kd0aij** [comment]
It looks like the drift in baro alt is due to temperature. Here's a plot of compensated baro alt using this formula: SENS.BaroAlt+(27.5-SENS.BaroTemp)/4
compensated_baroalt

**Comment by thomasgubler** [comment]
I flew the iris with these parameters. I did not observe a significant difference from the ground. I verified that INAV was running. Here are some logs without further analysis/comment:

Before (default params): http://logs.uaventure.com/view/zyhvqC7CMD6t43uaYtvTNR
After (params from this PR):http://logs.uaventure.com/view/qjhqKcCdcysHLP6a82ZsGg

**Comment by LorenzMeier** [comment]
Dropping, too risky. Will put this all into EKF2.

**Pull request closed without merging**
