### PR TITLE
QuadChute monitor tecs height rate

### PR DESCRIPTION
**Pull request by sanderux**
Added some more QuadChute logic to cope with vehicles that still perform but don't make their setpoints.

### CODE REVIEW

**Comment by sanderux** [comment]
SITL tested with params that made it perform poorly.
Quadchute only triggered when it reached a point where it could no longer maintain flight.
Previously it would already trigger if it didnt make the setpoint in time

**Comment by LorenzMeier** [comment]
Release critical?

**Comment by sanderux** [comment]
Adaptive quadchute now only functions when the vehicle is ideally tuned (makes tecs climb rate setpoint). Any deviation like a gimbal or payload that offsets this even a little would result eventually in a quadchute event.

Adaptive quadchute is disabled by default. Release critical? i don't know, what do you think?

**Comment by sanderux** [comment]
This change makes so that the vehicle needs to actually be descending at 1m/s+ while 1ms+ ascend was requested.

**Comment by sanderux** [comment]
@LorenzMeier @dagar After giving this some more thought i do think this is critical.
Even well tuned vehicles will not achieve their normal climb rate at higher altitudes. Especially when they are carying a payload. This might cause quadchute to hit at the worst possible time (when the vehicle is very high) and could result in a crash as RTL and LAND as MC might not be possible from that altitude.

**Comment by sanderux** [comment]
@dagar i implemented the hysteresis as discussed. Also added the stall detection although on somewhat hard values. In both cases the situation needs to be combined with a large negative altitude error.

Can you review?

**Comment by sanderux** [comment]
Tested, no regression:
no payload high wind: https://logs.px4.io/plot_app?log=6a1846b3-ba28-4863-96bd-6e910f7c6711
1kg payload high wind: https://logs.px4.io/plot_app?log=3e59096d-c993-40cc-9b06-bebf59559800

**Comment by dagar** [comment]
For the record I'll object one last time about slipping new features into a release that's already behind, but given your thorough testing and the fact that this is disabled by default we can make an exception.

Looking forward let's figure out a better release and QA workflow (GitFlow?). I also want to generalize these types of controller checks and get away from the "vtol attitude controller" peering into nearly every part of the system.

**Pull request merged**
