### PR TITLE
Racing Improvements (2/2): D gain filtering

### PR DESCRIPTION
**Pull request by LorenzMeier**
@MaEtUgR This adds a new filter for D-gain addition. It is *NOT* being used in the controller yet. The theory is that using a better estimate of the derivative we can go for a more aggressive rate controller tuning (PID instead of PI), which allows us to track rates more accurately.

This branch still contains a lot of instrumentation. Some of that would need to be removed before merging.

Thanks @bresch !

### CODE REVIEW

**Comment by MaEtUgR** [comment]
Sounds like a very good plan!!
@bresch I guess that's pretty new  Any tests already? Do you have it in real world use?

**Comment by nkhoit** [comment]
This is an initial flight test with this: http://logs.px4.io/plot_app?log=efe42194-6409-4ebe-91d2-e584340d9f22
Probably need to do some tuning with this in mind though.

**Comment by LorenzMeier** [comment]
Thanks! That log will be useful for plotting. @MaEtUgR Do you feel like enabling it for the D gain?

**Comment by bresch** [comment]
@MaEtUgR Yes, it is quite new but I already flew it several times but for logging only. Just to make sure it doesn't output anything crazy.

**Comment by LorenzMeier** [comment]
@bresch Can you default the controller to using the new filter?

**Comment by bresch** [comment]
@LorenzMeier The rates controller now uses the estimated derivative of the FOAW filters in the D term. The outputs of the filters are logged in mc_att_ctrl_status.

**Comment by bresch** [comment]
@nkhoit Thank you for the test! Could you try again with the latest modification? I don't need a big log, just hovering around with some high and low angular accelerations if possible will be perfect. Then I can tune the differentiator properly for you.

**Comment by nkhoit** [comment]
@bresch So this ended up making my vehicle unstable at first. I could only get it flyable once I zero'd out the rate_d gains.
(rate_d = 0.0007): http://logs.px4.io/plot_app?log=dec95b56-c4ec-4ccb-9b9f-7bda3290ffb6
(rate_d: 0.0007-->0): http://logs.px4.io/plot_app?log=0997c63d-beec-41ae-9ec2-e9a4c41c476f
(rate_p: 0.07-->0.03): http://logs.px4.io/plot_app?log=08a9c371-c845-449e-8326-5863129b7b50

Wasn't too sure how long I should be spending to tune this. So just dumping some logs for now in case there's something interesting that you can see. Because my gains are so different from master, I'm struggling with that more right now, so I can't see any differences yet besides that.

**Comment by bresch** [comment]
@nkhoit Thank you, I'll have a look.

**Comment by bresch** [comment]
@nkhoit I found the issue, the derivative was applied with a positive sign instead of a negative sign => positive feedback => unstable
It's fixed now.

**Comment by nkhoit** [comment]
Just as an initial test, it's stable now with derivative gain.
http://logs.px4.io/plot_app?log=c866c0ff-b907-4cd5-b145-e723c78a3afb

**Comment by bresch** [comment]
@nkhoit Cool, it looks to work properly now. However, since your gyro measurements are pretty clean (nice setup!), the `delta` tuning parameter of the filter can be reduced in order to reduce the delay. I should add a parameter to be able to modify it through QGC.

**Comment by nkhoit** [comment]
I increased my rate_p gains from 0.055~ --> 0.1
This has usually been unstable for me. But I was able to lower the delta parameter to get it stable with the same gains (I'm assuming it's these values here? https://github.com/PX4/Firmware/blob/8760f2fdcae2a0dcee638357c1497fe89563dab8/src/modules/mc_att_control/mc_att_control_main.cpp#L444)
delta = 0.025 --> http://logs.px4.io/plot_app?log=69590f59-a46f-4d92-a4b6-88a4b59549fa
delta = 0.01 --> http://logs.px4.io/plot_app?log=b2013dc6-0bab-42e2-8928-14f8961f0159

So, all I know is this parameter is doing something and I can play around with it.

**Comment by LorenzMeier** [comment]
@bresch I'm not sure what you did, but this branch is completely messed up in terms of commits - it has your commits multiple times in it. Is it possible you merged your feature branch into an already rebased version? I will squash this into a single commit to fix.

**Comment by bkueng** [comment]
Replacement PR: #7698

**Pull request closed without merging**
