### PR TITLE
Flight mode rework

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@AndreasAntener @tumbili I think I nailed the issue now. Please re-test on the bench.

**Comment by tumbili** [comment]
@LorenzMeier Thanks, disabling manual override looks promising! Will test this today.
@AndreasAntener Ada, can you share the link to the fw log we did yesterday?

**Comment by AndreasAntener** [comment]
Here's a flight log from yesterday with the old branch:
http://dash.oznet.ch/view/68G8YHqxb3CmjMZQHLagHK

ALT and POSCTL worked nicely :)

In POSCTL the heading "lags" behind a little. So when you roll back fast (e.g. let the stick go), the heading is not up-to-date yet so it snaps back a few degrees. Maybe a small delay after it has 0 roll before it takes the heading would already be enough to compensate for this. Maybe there's also a better approach.

**Comment by tumbili** [comment]
@AndreasAntener Thanks!

**Comment by sjwilks** [comment]
Note that the log won't display in logmuncher as this code was pulled at
point when there were still bugs in the sdlog formatting. I think
flightplot can survive this though. Master and release are fixed again
though.

**Comment by tumbili** [comment]
@LorenzMeier Will test this when I'm home, don't have anything in the lab at the moment.

**Comment by AndreasAntener** [comment]
Flight tested ;)
http://dash.oznet.ch/view/D4X9K2TvyYaZUksquecF8L

Nice touch with the throttle override in alt/posctl, no cutting fingers on the bench.

Stabilized is working again. Although it seemed not so snappy anymore. Was that just me or did the behaviour there change?

Same issue of course in POSCTL. Had the goggles on, there it is even more noticeable of course. But else, great stuff. I could observe how it rolled in crosswind and corrected (now I need a roll camera compensation for FPV ;)).

**Comment by AndreasAntener** [comment]
(tested before the latest changes from just now. my state was https://github.com/PX4/Firmware/commits/948c29fc8601f98141c67d60f9df052cb1a17fda)

**Comment by tumbili** [comment]
@LorenzMeier Stabilization seems to be working. Night.

**Comment by LorenzMeier** [comment]
@AndreasAntener @sjwilks a quick flight test in POSCTL would be all it takes now 8)

**Comment by AndreasAntener** [comment]
I took the weekend off ;)
I'll surely find some time to test it this week

**Comment by LorenzMeier** [comment]
Re-sending this against the release branch, closing.

**Pull request closed without merging**
