### PR TITLE
Allow parameter culling to be turned off for SnapDragon

### PR DESCRIPTION
**Pull request by davids5**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesome! @julianoes Please review, test and merge.

**Comment by mcharleb** [comment]
All of the *_eagle_* .cmake files will need this change.

**Comment by julianoes** [comment]
@mcharleb: thanks for the note. Done in 0c5c111cdd9b3693fea0272a8507ae7c530a87d7.

**Comment by julianoes** [comment]
Tested that parameters are still sculled on SITL, but that all parameters are available on Snapdragon.

**Comment by julianoes** [comment]
Merged, thanks @davids5 for the fast turnaround.

**Pull request merged**
