### PR TITLE
Mavros test updates

### PR DESCRIPTION
**Pull request by AndreasAntener**
Supersedes #1847, against master

### CODE REVIEW

**Comment by AndreasAntener** [comment]
@thomasgubler regarding attitude control I found out why it doesn't work for me:
mc_post_control overwrites the attitude setpoint at high frequency, the updates from mavlink just fall between them and have therefore no impact.
[Here](https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control_multiplatform/mc_pos_control.cpp#L1019) we publish a setpoint constantly disregarding the control flags. If I comment it out, attitude control works.

**Comment by thomasgubler** [comment]
@AndreasAntener great find. that stems from https://github.com/PX4/Firmware/pull/1823 (or https://github.com/PX4/Firmware/pull/1741 in other words) which I never tested with offboard. We have the same logic error in the normal pos control app on master.

**Comment by AndreasAntener** [comment]
This now contains updated SITL ITs including a new one for offboard attitude, which currently fails as expected.

**Comment by AndreasAntener** [comment]
This could already go in. All SITL tests will go through as soon as #1857 is resolved.

**Pull request merged**
