### PR TITLE
EKF gyro offsetfix

### PR DESCRIPTION
**Pull request by LorenzMeier**
This fixes the use of the IMU delta T for gyro bias compensation and leads to more stable gyro offset results.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@Zefz A code review would be great. The updates were based on code review and bench tests. I now have nice spike-free, zero-mean angular rate readings and a steady horizon in HUD.

**Comment by Zefz** [comment]
Seems good, as long as dtIMUfilt stays non-zero (which it should be, unless something is wrong). We do a lot of divisions by dtIMUfilt.

I'll do a bench test myself on a couple of Pixhawks tomorrow and a quadcopter flight test as well.

**Comment by LorenzMeier** [comment]
It shouldn't become ever zero as dtIMU is guaranteed to be finite, smaller than one and greater than zero.

**Comment by LorenzMeier** [comment]
@Zefz I just reviewed it again. More testing would be extremely welcome, but after my intense bench testing today I feel confident that my changes actually help a bunch. Thanks for fixing up the EKF in the last weeks, you've significantly pushed things!

**Pull request merged**
