### PR TITLE
[WIP-fix to dagar/newLogger2] 

### PR DESCRIPTION
**Pull request by kd0aij**
@dagar timestamp was missing from autogenerated sources

### CODE REVIEW

**Comment by kd0aij** [comment]
I'm getting good logfiles now. Will do some flight testing tomorrow.

**Comment by dagar** [comment]
Ah thanks. I'm still getting occasional hard faults which I can't explain. I take it you aren't? I wonder if it's time for ` -mno-unaligned-access`.

**Comment by kd0aij** [comment]
haven't seen any on the bench, but that doesn't prove anything :( 
If there's a way to get C compilers to generate valid code (with me in the loop), I'm all for it. There's a reason I chose Java for my PhD work...

**Comment by kd0aij** [comment]
BTW, is my fix correct, or was there logic hiding somewhere that I missed?

**Comment by dagar** [comment]
Your changes look good. You can see the output in build_*/topics_sources/vehicle_attitude_setpoint.cpp, etc.

I'm glad there's no noticeable overhead. With the fields sorted it should still mostly be a linear copy.

I'll get everything in https://github.com/PX4/Firmware/pull/4429. Once we're confident the hard faults are gone we can merge into the main repo newLogger2 and concentrate there.

**Pull request closed without merging**
