### PR TITLE
FW landing project virtual waypoint to handle landing overshoot

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
No obvious regressions in a simple landing test. https://github.com/PX4/Firmware/pull/8985
Ideally we need a way to force an overshoot.

**Comment by dagar** [comment]
Here's one where I set the landing angle unrealistically high.

image

**Comment by RomanBapst** [comment]
@dagar Will review this tomorrow morning!

**Comment by RomanBapst** [comment]
@dagar Have you ever thought of splitting this up into several files?

**Comment by dagar** [comment]
Not really, but that might help. I feel like a lot of it could probably be condensed a lot better. For example when handling the manual position mode we could be first generating the setpoint, then going through the exact same control_position code as regular navigation. Likewise for takeoff after altitude/airspeed is achieved and several other cases.

**Pull request merged**
