### PR TITLE
Added CMake based build, added sim target, builds NuttX in parallel

### PR DESCRIPTION
**Pull request by jgoppert**
Test with cmake/build_archives.sh

This builds all archives on my machine in 35 seconds and it works with the existing make build for the rest of the firmware using symbolic links to the Archive directory.

### CODE REVIEW

**Comment by dagar** [comment]
@jgoppert I thought about moving the firmware build to cmake, but it looked like a huge job. Let me know if there's any way I could help. Maybe we could split up the modules.

**Comment by jgoppert** [comment]
@dagar The scariest part for me was NuttX, and now that I have that wrapped up I think we are pretty close.  I also got cmake working on the Flow, so I know that my build flags etc. are working. The last part will be creating an equivalent for all the files in the makefiles directory.  I will try to create one example, and if you could try to think of an easy way to streamline it so we don't have to maintain both a cmake mad make version of all modules lists/ flags etc it would be helpful.

**Comment by jgoppert** [comment]
I also just added git submodule handling. It is intelligent and can download submodules in parallel and then wait before firing off the parallel builds for each board.

**Comment by jgoppert** [comment]
@dagar I completed an example module build. If you want to run with this and see if you can get a full executable linked, it would be helpful.

To make this pull request useful right now, I added a script that builds the NuttX archives as fast as possible without running into threading issues: 
```bash
./cmake/build_archives px4fmu-v2_default     # takes about 10 seconds
./cmake/build_archives            # (will build all libraries) in about  45 seconds
```

**Comment by jgoppert** [comment]
I created some sample config files that live in the cmake directory.

px4fmu-v2_default.cmake: This file is the equivalent of makefiles/px4fmu-v2_default.mk

px4modules.cmake: This file defines how to build every module.

**Comment by jgoppert** [comment]
I added a NuttX sim config now and have a module compiling against the sim version of NuttX built on Linux host. So this is really close to the SITL we had hoped for.

**Comment by jgoppert** [comment]
I rebased this on nuttx-bringup because the NuttX sim works much better in 7.x.

**Comment by LorenzMeier** [comment]
This is really interesting! I just want to be sure that we don't try to start maintaining two build systems in parallel, which won't give a great experience on either one. So I would encourage to start a discussion on build systems on the mailing list. I don't want to merge partial / stale CMake support if its not our new main and only build system, as the consequence last time was that it gave new developers which tried to use it a hard time as it quickly became stale.

**Comment by LorenzMeier** [comment]
@jgoppert This ended up unfortunately in the unmaintained state I was concerned about. Please do not delete this branch, I've kept a reference, but I'm closing the PR as it would need more support in order to be sustainable.

**Pull request closed without merging**
