### PR TITLE
Ekf reinitialization after motion

### PR DESCRIPTION
**Pull request by bresch**
**Describe problem solved by this pull request**
The EKF has been designed to work properly when the operator follows the following steps:
- put the drone at the takeoff location
- plug the battery (-> EKF initializes)
- takeoff

It has been robustified for pre-takeoff repositioning (GPS drift-rate check is suspended during motion) but can diverge if carried over for long time in a changing environment such as GPS quality fluctuations, high vibrations, magnetic field disturbances, high pressure change, etc.

A few of examples are: 
- powering the drone indoor, sometimes getting a GPS lock at some point, then going outside by passing a few metallic doors
- powering the drone in a car or the back of a pickup then transporting it to the takeoff location
- powering the drone indoor and carrying it in a backpack to go to the takeoff location

**Describe your solution**
Monitoring the "at_rest" flag and triggering a state and covariance reset after a few seconds of motion or a full EKF reset after a longer motion.

**Describe possible alternatives**
Increasing the EKF resilience: this is much more complicated and is a long-term improvement

**Test data / coverage**
Bench tests only

Should be merged after: https://github.com/PX4/ecl/pull/664

TODO:
- [ ] check for normalized innovation test ratios before doing a reset as they should be large if a reset is required
- [ ] split linear (vel, pos, acc bias) and rotational (quat, mag bias, gyro bias) resets

### CODE REVIEW

**Comment by kamilritz** [comment]
This is a very nice added functionality which will improve user experience by a huge amount!

Doing the reset after short motion, resets the state & convariances, but triggers no new tilt alignment. Should we not do the tilt alignment in any case. When the terrain slope is different after this short motion we probably converge slower to the right tilt, then doing a new tilt alignment.

I feel that presumably we do not need to differ between long-term and short-term motion. Additionally we could still lower the hysteresis time for motion to 1-2 seconds.

**Comment by dagar** [comment]
Nice one! Next we should use this to reset after sensor calibration.

**Comment by bresch** [comment]
@PX4/testflights Could you please test fly this PR? General testing is fine, nothing specific required. Thanks

**Comment by jorge789** [comment]
**Tested on PixRacer V4:**
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
**When the vehicle was landing, it did not descend horizontally, began to get off, but went away with the wind and landed manually**

**Log:**  https://review.px4.io/plot_app?log=c7f16479-47d1-42be-90e1-bcde2d08c42c

**Tested on Pixhawk 4 V5:**
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

**Notes:**
**When the vehicle was landing, it did not descend horizontally, began to get off, but went away with the wind and landed manually**

**Log:**  https://review.px4.io/plot_app?log=0df23cb0-93c5-4490-b00b-ecc540547f8d

**Comment by bresch** [comment]
fmu_v2 overflow ...

**Comment by bresch** [comment]
Note: after discussion with @kamilritz , it turn out that I forgot to trigger a re-alignment with the mag.
Also, SITL tests fail on this PR because the gyro noise level on gazebo is too high and triggers the motion detection logic of the EKF.
The 3rd plot of the image below shows when the gyro triggers the motion:
file:///home/mathieu/Pictures/2019-11-25_12-45-59_01_plot.png

**Comment by bresch** [comment]
> A full reset of all the states and covariances like this seems unnecessary if innovations test ratios are low. What was the reason for not checking the innovations and only using the movement?

Mainly because the check is then simpler and that I thought that the cost of doing a quick reset was low. I can add an additional check for the innovation test ratios.

> The EKF is in a state of increased sensitivity to GPS glitches and other sensor transients for a few seconds after a reset like this and bias states will take a few seconds to learn, so a suitable delay before a valid output is reported should be applied to prevent immediate takeoff.

I think the innovations should be high enough during that time and the innovations checks should be sufficient to prevent arming.

**Comment by priseborough** [comment]
> I think the innovations should be high enough during that time and the innovations checks should be sufficient to prevent arming.

Not necessarily. If the vehicle is static at the time of reset, innovation test levels will be low immediately after reset. A time delay of a few seconds to allow the variances to stabilise and allwo the effect of a large IMU bias to become observable  is required.

**Comment by bresch** [comment]
More experimentation showed that this method of triggering the EKF reset was sometimes degrading the solution since the EKF was reset when in a perfectly good state. I tried to add an additional check for the innovation pre-flight checks and showed better results.
I'll then rewrite this logic to partially and carefully reset some states triggered by an innovation pre-flight check failing for a long period of time (e.g.: a yaw innovation failure for more than 10s will trigger a reset of the gyro biases and their covariance, and magnetic yaw reset).

**Pull request closed without merging**
