### PR TITLE
navigator_main: reference update for local position

### PR DESCRIPTION
**Pull request by Stifael**
This method is not used anywhere yet. The next step is to free
the position controller from any gloabal computation.

It is a much smaller version of https://github.com/PX4/Firmware/pull/7432.

### CODE REVIEW

**Comment by dagar** [comment]
This looks good. Short term we should probably make sure all these reprojection calls aren't too expensive in the cases where the position setpoint triplet is continuously updating.

**Comment by LorenzMeier** [comment]
We need to review this carefully. The system is built to work with long flight paths right now and moving everything to local would destroy this as the tangent plane runs away from the spherical coordinate frame.

**Comment by Stifael** [comment]
@LorenzMeier there is no difference between this implementation and the legacy one, except that that mapping from global to local happens in the navigator.

**Comment by dagar** [comment]
Why don't we have navigator periodically update the position setpoint triplet (at a very low rate)? Navigator will operate in whichever coordinate system required. Most missions will be global, but local could become possible. At position setpoint triplet update time the transformation to local is performed.

**Comment by Stifael** [comment]
> Why don't we have navigator periodically update the position setpoint triplet (at a very low rate)?

Do you mean to correct for the earth curvature? Sure. 

If I understand it correctly @LorenzMeier refers to the fact that  `line-tracking` in local frame is not as accurate as `line-tracking` in  global-frame where the curvature of the earth is to some extend taken care of (it depends on the projection). I completely agree with this. However, it is important to know that currently for MC the line tracking already happens in local frame anyway and therefore nothing would change with this PR and with any other PR that frees the MC position controller from global frame. 

What would be the benefit of having  MC running in global frame as well?  IMHO that would be a huge downgrade because in contrast to fixedwings, MCs will become more important indoors as well. For MC, mission mode does not have to be only gps dependent, but could very well be supported for local coordinate frame state estimates as well. In addition, there is always the alternative to update the global waypoints more regularly to compensate for the earth curvature (as @dagar suggested?)

**Comment by dagar** [comment]
Perhaps we should take a step back and define the basic requirements. From there we can determine an appropriate strategy.

**Comment by dagar** [comment]
Closing this PR as stale, but I definitely want to prioritize finding a general solution this year.

**Pull request closed without merging**
