### PR TITLE
Update submodule sitl_gazebo to latest Sat Aug 15 00:38:36 UTC 2020

### PR DESCRIPTION
**Pull request by dagar**
- sitl_gazebo in PX4/Firmware (22a7bf6ec72b4ecbde9767924e5c33d025b3ab71): https://github.com/PX4/sitl_gazebo/commit/0da08f0333cd14c08a9545c6ba7ddfc18706398f
    - sitl_gazebo current upstream: https://github.com/PX4/sitl_gazebo/commit/50f0a63541b219d2c31e4506112734050279ad2e
    - Changes: https://github.com/PX4/sitl_gazebo/compare/0da08f0333cd14c08a9545c6ba7ddfc18706398f...50f0a63541b219d2c31e4506112734050279ad2e

    50f0a63 2020-08-08 JaeyoungLim - Separate out HIL mavlink interface

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@dagar Does this mean SITL gazebo is actually broken?

**Comment by dagar** [comment]
> @dagar Does this mean SITL gazebo is actually broken?

Yes, I was assuming (incorrectly?) there was corresponding PX4/Firmware work needed.

**Comment by Jaeyoung-Lim** [comment]
@dagar As far as I am concerned, this is not the case.

Not sure why the SITL tests are failing though

**Comment by dagar** [comment]
Alright, let's take a closer look.

Screenshot from 2020-08-15 15-50-02

Screenshot from 2020-08-15 15-50-16

**Comment by Jaeyoung-Lim** [comment]
@dagar Seems like it is coming from the refactoring I did, I will try to run the tests locally

**Comment by Jaeyoung-Lim** [comment]
Also added a firmware build test in `sitl_gazebo` to prevent this from happening

**Comment by Jaeyoung-Lim** [comment]
Closing since this update is not relevant anymore

**Pull request closed without merging**
