### PR TITLE
Adds Calibration Support for RPi2 and Navio2

### PR DESCRIPTION
**Pull request by mayanez**
Allows for calibration of sensors from GCS.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice. Should go in once it passes.

@julianoes Do you have bandwidth to build a complete setup on a quad?

**Comment by LorenzMeier** [comment]
@julianoes E.g. with this one? https://www.brack.ch/dji-innovations-flame-wheel-255131

**Comment by julianoes** [comment]
> @julianoes E.g. with this one? https://www.brack.ch/dji-innovations-flame-wheel-255131

Wow, you can still buy these?

I still have a bunch of parts, should be able to set one up.

**Comment by julianoes** [comment]
Thanks @mayanez, I'll test this PR in the next days.

**Comment by mayanez** [comment]
Sounds good. We've been testing on our end as well with the F450 frame listed above. Would you mind sharing what flight tests the team typically does so that we can also reproduce them.

**Comment by LorenzMeier** [comment]
Manual hover, then altitude control, then position control with GPS, then an autonomous mission.

Logs preferably uploaded to http://logs.uaventure.com

**Pull request merged**
