### PR TITLE
Ekf2 fuse airspeed

### PR DESCRIPTION
**Pull request by CarlOlsson**
Added function for airspeed fusion into the EKF. Simulated but not flight tested yet.

### CODE REVIEW

**Comment by CarlOlsson** [comment]
Plots from simulation
map
plot1
plot2

**Comment by LorenzMeier** [comment]
@CarlOlsson @tumbili Could you please revive this (rebase on master, since EKF2 has improved quite a bit since). It would be great to get this stable and in.

**Comment by tumbili** [comment]
@CarlOlsson Can you rebase this on master and sync it with the correct ecl version?

**Comment by CarlOlsson** [comment]
Rebased in #4011

**Pull request closed without merging**
