### PR TITLE
UAVCAN diagnostics

### PR DESCRIPTION
**Pull request by pavel-kirienko**
Hey @DonLakeFlyer, 

I attempted to reproduce your issues locally, and failed. I based my attempts with the current master, and found out that everything works as expected. In order to help with the investigation on your end, I added a useful diagnostic that prints the list of all online nodes with the status output (`uavcan status`). It looks like that:

```
Online nodes (Node ID, Health, Mode):
        115 OK         OPERAT    
        116 OK         OPERAT    
        117 OK         OPERAT    
        118 OK         OPERAT  
```

Please merge or cherry-pick this change and show what status output you get.

You can also verify whether your PX4 has access to the configuration parameters via CLI as follows: `uavcan param list 115` (the last number is the node ID, adjust as necessary). You should get back a list of configuration parameters of the specified node:

```
name: esc_index 2
name: cmd_ttl_ms 200
name: cmd_start_dc 0.2500
name: uavcan_node_id 0
name: light_index 0
name: pwm_max_usec 2000
name: pwm_min_usec 1000
(...snip)
```

If the above works for you, then the configuration management module is working well, and the issue should be within the MAVLink part of the system, rather than UAVCAN.

Finally, this is what I get when loading configuration parameters via QGC:

image

Please let me know how else I can assist.

### CODE REVIEW

**Comment by mhkabir** [comment]
@pavel-kirienko What is @DonLakeFlyer running into?

**Comment by pavel-kirienko** [comment]
He can't load any parameters via QGC.

**Comment by mhkabir** [comment]
That can happen if the enumeration is done incorrectly. It works for me ATM.

**Comment by pavel-kirienko** [comment]
ESC enumeration has no relation to anything but motor control. It cannot affect other functions, such as parameter management.

**Comment by mhkabir** [comment]
That may be what is 'supposed' to happen. Try resetting the parameters on the ESCs. Then run `uavcan status` and see the artifacts.

**Comment by pavel-kirienko** [comment]
Ok, I just reset ESC params, re-checked, and found no difference in behavior. As expected.

The MAVLink side is quite wonky though, so it could be that you mistakenly identified random glitches as a result of a difference in configuration.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Pull request merged**
