### PR TITLE
Master param mem usage redux

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier Please Ignore https://github.com/PX4/Firmware/commit/9c6a70d4a75b5909a3f7fede2805bdf4b62d05c2 

Use this instead - NB https://github.com/PX4/Firmware/compare/master_param_mem_usage_redux?expand=1#diff-a953b7046039fd7cd55c5860953df79cL562 - the old code looks very wrong.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I agree that the old code looked wrong, but this one here doesn't work. With SYS_AUTOSTART set to 4011 (after a reboot) this is what I get for the multicopter params. They should *ALL* be marked with a plus as used:

```
nsh> param show MC*
Symbols: x = used, + = saved, * = unsaved
    MC_ACRO_Y_MAX [201,200] : 120.00000
    MC_ACRO_P_MAX [-1,201] : 90.00000
    MC_ACRO_R_MAX [-1,202] : 90.00000
    MC_YAWRATE_MAX [-1,203] : 120.00000
    MC_PITCHRATE_MAX [-1,204] : 360.00000
    MC_ROLLRATE_MAX [-1,205] : 360.00000
    MC_YAW_FF [205,206] : 0.5000
    MC_YAWRATE_FF [208,207] : 0.0000
    MC_YAWRATE_D [-1,208] : 0.0000
  + MC_YAWRATE_I [-1,209] : 0.1000
  + MC_YAWRATE_P [-1,210] : 0.2000
  + MC_YAW_P [-1,211] : 2.8000
    MC_PITCHRATE_FF [209,212] : 0.0000
  + MC_PITCHRATE_D [-1,213] : 0.0030
    MC_PITCHRATE_I [-1,214] : 0.0000
    MC_PITCHRATE_P [-1,215] : 0.1000
  + MC_PITCH_P [214,216] : 7.0000
    MC_ROLLRATE_FF [218,217] : 0.0000
  + MC_ROLLRATE_D [223,218] : 0.0030
    MC_ROLLRATE_I [225,219] : 0.0000
    MC_ROLLRATE_P [-1,220] : 0.1000
  + MC_ROLL_P [-1,221] : 7.0000
```

**Comment by LorenzMeier** [comment]
I stared at this for a while and couldn't find the root cause immediately. I still would love to get this in ASAP to save the memory, but I might need your help in fixing it.

**Comment by davids5** [comment]
@LorenzMeier  - Originally I had just blindly translated the code blindly.  With fresh eye this AM I reviewed and I believe I fixed the issue.

The original code was wrong
```
unsigned bitindex = param_index - (param_index / sizeof(param_changed_storage[0]));
                0     =    N  - ( N / 1)
```

Now it is effectively 
```
     unsigned bitindex  =   param_index % bits_per_allocation_unit;
                      n[0:7]          =            N    mod        8
```
Please test it.

**Comment by LorenzMeier** [comment]
Unfortunately still wrong. Params don't transmit properly from the GCS and I can see that some params which should not be marked as used in fact are marked:

```
nsh> param show RTL*
Symbols: x = used, + = saved, * = unsaved
x   RTL_LAND_DELAY [-1,254] : -1.0000
x + RTL_DESCEND_ALT [564,255] : 10.00000
x + RTL_RETURN_ALT [-1,256] : 30.00000

 527 parameters total, 332 used.
```

The -1 entries should not be there.

Looking at the code of rtl.cpp, all three or none have to be lit:
```C++
	_param_return_alt(this, "RTL_RETURN_ALT", false),
	_param_descend_alt(this, "RTL_DESCEND_ALT", false),
	_param_land_delay(this, "RTL_LAND_DELAY", false)
```

Comparing with master:

```
nsh> param show RTL*
Symbols: x = used, + = saved, * = unsaved
x   RTL_LAND_DELAY [93,254] : -1.0000
x + RTL_DESCEND_ALT [94,255] : 10.00000
x + RTL_RETURN_ALT [95,256] : 30.00000

 527 parameters total, 332 used.
```

**Comment by LorenzMeier** [comment]
Fixed!

```
nsh> param show RTL*
Symbols: x = used, + = saved, * = unsaved
x   RTL_LAND_DELAY [93,254] : -1.0000
x + RTL_DESCEND_ALT [94,255] : 10.00000
x + RTL_RETURN_ALT [95,256] : 30.00000

 527 parameters total, 332 used.
```

**Comment by LorenzMeier** [comment]
Just found another thing to fix - no negative effects, but people with non-default param values might have transmitted a lot more params than necessary, because unused non-default params also got marked as used.

**Comment by LorenzMeier** [comment]
Testing good, code review good, looks like its good to go.

**Pull request merged**
