### PR TITLE
travis-ci use ninja and restore s3 upload

### PR DESCRIPTION
**Pull request by dagar**
Using ninja will allow us to remove the travis output folding which seems to make it difficult for new contributors to find build failures. It might also be slightly faster.

@LorenzMeier I just noticed all the s3 upload stuff is still commented. Would you like it re-enabled?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Yes, S3 re-enabling would be good. I lost track of that, but its clearly important!

**Comment by LorenzMeier** [comment]
@dagar You're missing ```brew install ninja```

**Comment by dagar** [comment]
@LorenzMeier the firmware is now named nuttx-px4fmu-v2-default.px4, but QGroundControl grabs  px4fmu-v2_default.px4. Should we change it here or in QGC as cmake propagates from master -> beta -> stable?

**Comment by LorenzMeier** [comment]
@dagar I would propose to add a manual copy step here. We'll figure it out then.

**Comment by dagar** [comment]
Done

**Comment by LorenzMeier** [comment]
Merging when Travis passed.

**Comment by dagar** [comment]
@LorenzMeier FYI you'll need to change the gtest path in unittests/CMakeLists.txt if you reuse it.
https://github.com/PX4/Firmware/blob/master/unittests/CMakeLists.txt#L40

**Comment by LorenzMeier** [comment]
Thanks! Rebased and applied.

**Pull request closed without merging**
