### PR TITLE
mavlink: use voter to send HIGHRES_IMU

### PR DESCRIPTION
**Pull request by julianoes**
It would be helpful if mavlink sends the sensor values which are
actually getting used in estimation and control.

I used this for the MPU9250 mag testing.

### CODE REVIEW

**Comment by mhkabir** [comment]
@julianoes Can't we just get the best sensor IDs from the voter in the attitude estimator? This approach of multiple voter instances would create 
1. Warning management issues if a sensor failed. 
2. Possible race conditions between attitude estimator and the mavlink voter instances.

**Comment by julianoes** [comment]
@mhkabir I see your point but we need to be able to debug sensor signals in QGC.

**Comment by mhkabir** [comment]
I can implement this differently if you'd like. Would be easy enough to get the data from the attitude estimator into a sensor_status topic, which mavlink can use to populate the stream.

**Comment by julianoes** [comment]
> I can implement this differently if you'd like. Would be easy enough to get the data from the attitude estimator into a sensor_status topic, which mavlink can use to populate the stream.

That's an option. @LorenzMeier thoughts?

**Comment by LorenzMeier** [comment]
I think the status topic makes sense.

**Comment by LorenzMeier** [comment]
Maybe look at how vibration is already reported. Extending that makes a lot of sense.

**Comment by mhkabir** [comment]
@LorenzMeier @julianoes Vibration is reported via the vehicle_attitude topic. Let me move it out of there and create a separate ```inertial_sensor_status ``` topic. Sounds OK?

**Comment by mhkabir** [comment]
OK, I'm almost done with this. Will send PR later.

@LorenzMeier @julianoes While working on this (and also implementing voting support in LPE), I was wondering if it would be worthwhile to move the voting into the sensors app. Instead of publishing data from all the sensors all the time, we can possible move the full voting process into sensor app and have the whole system use the data from the 3 best sensors.
Otherwise, we still end up having to use multiple voter instances for the attitude estimator, position estimator, etc. It also makes failover report handling a nightmare with a lot of boilerplate code.

I'm not sure if there would be any disadvantages to this approach though. Opinions? If there's any other way to clean up the architecture, I'd be happy to take up the same.

**Comment by julianoes** [comment]
@mhkabir I agree that it would make sense to have it in the sensors module in the current setup, however, eventually it should be up to an estimator to decide what sensors to use, how to fail-over, etc. Also the plan is to get rid of sensors at some point because it's actually just copying data.

**Comment by mhkabir** [comment]
@julianoes Could you please review my take on this issue in #4802

**Comment by julianoes** [comment]
I prefer #4802 and will close this.

**Pull request closed without merging**
