### PR TITLE
Commander : Effectively track failure reporting and handle hotplug sensors

### PR DESCRIPTION
**Pull request by mhkabir**
Now commander will report all issues when a new link is connected. So no messages are lost.
:) Also, with my changes, it will now wait in ARMING_STATE_INIT till all primary sensors come online.

This will need some careful review, but I'm confident this works 100% as tested. Please let me know what else is needed.

New output when link first connects (hotplug sensor not up yet though) : 
```
[20:14:12.645 - COMP:1] Info: new data link connected #0
[20:14:12.861 - COMP:1] Critical: warning: primary compass not operational
[20:14:12.964 - COMP:1] Critical: Not ready to fly: Flying with USB connected prohibited
[20:14:13.068 - COMP:1] Critical: Not ready to fly: Sensors need inspection
```

### CODE REVIEW

**Comment by mhkabir** [comment]
Note to self : Figure out a way to flag external/hotplug sensors during calibration, and not play annoying error tune right at boot before it has come up.
Suggestions, Lorenz?

**Comment by LorenzMeier** [comment]
I would propose to not warn for the first two seconds. After that it's unlikely a sensor will still show up without user intervention. So the first two seconds after boot it should just flag the system as by ready, but not warn via MAVLink or buzzer.

**Comment by mhkabir** [comment]
Implemented. Works perfectly. We don't warn the user for upto 4 seconds after booting (this value was the minimum required one, tested with UAVCAN mag)

**Comment by LorenzMeier** [comment]
Awesome work! Just going through it now.

**Comment by mhkabir** [comment]
OK, I just added some user experience tweaks to warn the user later if sensors fail, etc. This *feels* very polished now.

Timeout is set to 5 seconds, which works fine with USB, but on battery, with the faster boot, and UAVCAN sensors ridiculously taking around 8-9 seconds (after commander starts) to come up, the system starts warnings, before the sensors come up.

Now the weird thing is, if I set the timeout to > 5s commander never goes into a proper failure state if nothing is connected. Tracking it down now. If you find anything please let me know.

**Comment by LorenzMeier** [comment]
Hard to tell why it's different on battery without sitting in front of the system. Have you pinged @pavel-kirienko to see why it takes so long to enumerate?

**Comment by mhkabir** [comment]
Ok, so I fixed the remaining small user-experience issues, other than the long enumeration times. The system works exactly as expected now, and warns perfectly in every condition. I check with all sorts of combinations - bad calibrations, mag unplugged, plugged, uavcan enabled/disabled etc. and it works great!

Timeout is set to 8 seconds till Pavel can provide us with faster enumeration times. System won't warn till 8 seconds are over -- but it will still refuse to go to STANDBY silently.

I also added a small differentiation between pre-arm and pre-flight. USB power is only checked if we are doing a pre-arm check, not for pre-flight (as in bench tests or otherwise) This can be expanded later to encompass more system checks.

**Comment by mhkabir** [comment]
@LorenzMeier Could you please give a high-level review of this meanwhile ? Does everything look OK, or does anything need more re-factoring/optimization?

**Comment by LorenzMeier** [comment]
This looks really good. I will cross-test and get this in tomorrow.

**Pull request merged**
