### PR TITLE
Enable Simulation of the Hippocampus (AUV from TUHH)

### PR DESCRIPTION
**Pull request by LorenzMeier**
Adding files which enable a simulation with the autonomous underwater
vehicle (AUV) from the Technical University Hamburg-Harburg

### CODE REVIEW

**Comment by TSC21** [comment]
@LorenzMeier is there a reason the mixer having to be on ` ROMFS/px4fmu_test/mixers/`?

**Comment by TSC21** [comment]
Jenkins test this please.

**Comment by LorenzMeier** [comment]
Yes - everything that goes into common adds to the flash space use on the main MCU

**Comment by TSC21** [comment]
> Yes - everything that goes into common adds to the flash space use on the main MCU

Ok makes sense. There was heavy formatting on the mixer file in order to be accepted by the CI system. Is there a reason for it sometimes not accepting sectioning titles for example?

**Comment by NRottmann** [comment]
Nice, thanks @LorenzMeier . But as @TSC21 mentionend, do you know why I had such trouble to get the mixer accepted by the CI?

**Comment by TSC21** [comment]
@NRottmann can you still please update the Devguide here: https://dev.px4.io/en/simulation/gazebo.html

**Comment by NRottmann** [comment]
@TSC21 Sure, but at the moment I am not at the university. I will do it when I am back. I think this will be around the first of september.

**Comment by TSC21** [comment]
> @TSC21 Sure, but at the moment I am not at the university. I will do it when I am back. I think this will be around the first of september.

That's fine. Thanks!

**Comment by NRottmann** [comment]
@TSC21 Hi, I want to update the Devguide. I've already forked it but I have a few questions:
1.) The simulation of the HippoCampus works right now only with ROS wrappers, so I just would add things here: https://dev.px4.io/en/simulation/ros_interface.html , is this right?
2.) Shall I just add things or can I also rewrite somethings?

**Comment by TSC21** [comment]
> 1.) The simulation of the HippoCampus works right now only with ROS wrappers, so I just would add things here: https://dev.px4.io/en/simulation/ros_interface.html , is this right?

Would be good if you can remove this dependency and have it working with Gazebo only. Something that could run after issuing `make posix_sitl_default gazebo_hippocampus`. If you have any doubts I can help ya on how to do it.

> 2.) Shall I just add things or can I also rewrite somethings?

You can add and rewrite whatever you like as long it is explainable and makes sense.

**Comment by NRottmann** [comment]
@TSC21 Hi, I've seen that you already approved the changes to the sitl_gazebo submodule. A new pull request for the master has been started in order to enable simulation without ROS wrappers (https://github.com/PX4/Firmware/pull/7888).

**Pull request merged**
