### PR TITLE
fix handling of mavlink mode argument

### PR DESCRIPTION
**Pull request by tumbili**
@LorenzMeier This should fix the problem with the low rc channels message rate.

### CODE REVIEW

**Comment by tumbili** [comment]
Tested, works again.

**Comment by tumbili** [comment]
@LorenzMeier Any idea what went wrong? BTW, I also don't understand why the compiler was not complaining about "optarg" not being defined (see commit).

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by LorenzMeier** [comment]
optarg is a global var. The travis run failed because it couldn't download the compiler image. Merging.

**Comment by LorenzMeier** [comment]
Applied to master/beta/stable.

**Pull request merged**
