### PR TITLE
Rename commander.cpp to Commander.cpp and update CMakeLists.txt.

### PR DESCRIPTION
**Pull request by mcsauder**
Hi,

This PR replaces PR #9860 for the rationale discussed in that PR and aims to unify the naming convention between `commander.cpp` and `Commander.hpp`.  This PR reinforces convention within that module such that files containing classes reflect the name (with respective capitalization) of the class contained within that file.

Let me know if you have any questions on this PR.

-Mark

### CODE REVIEW

**Comment by mcsauder** [comment]
@hamishwillee , should I close out this PR?  Thanks for your advice!

-Mark

**Comment by hamishwillee** [comment]
@mcsauder I am OK with this, but my field is docs, not code. @dagar - OK to merge?

**Comment by dagar** [comment]
Conflicts at the moment, but I'm fine with the rename.

**Comment by mcsauder** [comment]
Thanks @dagar , merge conflicts resolved and pushed up!

**Pull request merged**
