### PR TITLE
Minor I2C fixes for fmu-v5

### PR DESCRIPTION
**Pull request by DanielePettenuzzo**
This PR allows px4flow to run also on the PX4_I2C_BUS_EXPANSION2 on fmu-v5.

Moreover it also fixes the i2c bus enumeration in several drivers, so that each external i2c bus has a different number assigned to it. 

Note: currently just the first external bus can be launched with -X. For the other two you need to scan all busses (with no bus selection argument).

### CODE REVIEW

**Comment by bkueng** [comment]
> Moreover it also fixes the i2c bus enumeration in several drivers, so that each external i2c bus has a different number assigned to it.

Was this not intended, so that you can start with `-X` and it will scan all external busses?

**Comment by DanielePettenuzzo** [comment]
@bkueng ok then I will remove these changes and just keep the optical flow one

**Comment by hamishwillee** [comment]
Does this change anything in [setup instructions](https://docs.px4.io/en/sensor/px4flow.html#pixhawk-setup) ?

**Comment by bkueng** [comment]
@DanielePettenuzzo I cherry-picked 0319b85eebbc797c5b47310a99bcf04ae803d8e9.

@hamishwillee 
> Does this change anything in setup instructions ?

No changes needed.

**Pull request closed without merging**
