### PR TITLE
Dll mission fix

### PR DESCRIPTION
**Pull request by sanderux**
When mission is finished with dl lost condition and dl lost failsafe off, RTL should only be activated when in air.

Significant changes in 
https://github.com/PX4/Firmware/commit/2c68e48c0f2d84db2867598d7cff9f59f4ab4743
https://github.com/PX4/Firmware/pull/5230/commits/684f6695eb79adfd2203007ede62e21c8f16c625
rest is code style

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@julianoes Can you review & merge?

**Comment by julianoes** [comment]
@sanderux Sorry can you break that down for me. What was the (wrong) behaviour before and what is the new behaviour?

**Comment by sanderux** [comment]
@julianoes 

The following scenario was attempted:
- No RC RX attached
- Datalink lost failsafe disabled
- RC mode to 'no rc'
- RC failsafe disabled

- Connect GCS through wireless telemetry
- Switch to mission mode
- Arm

Failsafe kicked in while switching to mission mode, this is because of https://github.com/PX4/Firmware/issues/5229

Uppon further investigation of the behavior in the state_helper under the condition of RC_Lost and Datalink lost while both failsafes for that were disabled, i came to the conclusion that the approach was wrong. The idea behind this failsafe is when a mission ends with no active links (RC or DL), even if the DL failsafe was switched off it should RTL. But the way it was implemented was wrong;

it only checked the rc link and the mission_finished condition, it did not check the datalink. So even if that link was active it would still failsafe. 

Additionally (also to bypass the bug above) i added the landed condition to the failsafe, RTL would normally never initiate when landed but it does give errors that should not be there.

**Comment by julianoes** [comment]
Ok, the change looks correct from my understanding.

**Comment by sanderux** [comment]
We might tag along a fix for https://github.com/PX4/Firmware/issues/5229 after some testing tonight

**Comment by sanderux** [comment]
bench tested, works as expected
@julianoes i think this can go in

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
