### PR TITLE
Removed duplicate and fix SRF02 driver

### PR DESCRIPTION
**Pull request by AlexandreBorowczyk**
I've remove the duplicate SRF02 driver and fix the remaining one.
I've also added a parameter to enable the driver at startup.
The driver functionality has been tested with a pixhawk and the SRF08 sensor (same interface as the SRF02).

### CODE REVIEW

**Comment by dagar** [comment]
Looks good. I'm surprised we didn't even have a mechanism to start it. Are there any notable changes to the driver itself?

**Comment by AlexandreBorowczyk** [comment]
Not really, the only thing I had to do to make it work was to update the I2C address range and remove the probe() method as it's call in the I2C init() and will fail if the first address is not the right one.

**Comment by dagar** [comment]
There are a few more differences than I initially saw, but so far it looks fine.

Are you able to actually test this?

**Comment by AlexandreBorowczyk** [comment]
Yes with a px4pilot (HK) and the srf08 sensor which was the same interface that the srf02 but was a light sensor.

**Pull request closed without merging**
