### PR TITLE
Integration of a new geometry (inverted Y)

### PR DESCRIPTION
**Pull request by Tiktiki**
Please review and integrate.
Built using Ninja under Ubuntu.
Uploaded and tested on Pixhawk 2.4.6 with STM rev.3

### CODE REVIEW

**Comment by dagar** [comment]
Looks good. The travis-ci build failed to a small code style issue. https://travis-ci.org/PX4/Firmware/builds/200553493

Is a "3DStuff Trijumper" going to be something I can buy or follow instructions to make? If not maybe a more descriptive generic name would be better so people can figure out what it is?

**Comment by Tiktiki** [comment]
It should be available this summer.
Considering it's a tilt-rotor VTOL with no control surfaces and detacheable wings, it might be a bit hard to scratch-build, but I might release a blog/post on PX4.io to explain the basics.

**Comment by dagar** [comment]
@Tiktiki any news?

**Comment by Tiktiki** [comment]
It's been sitting on a shelf since this winter. Lots of other projects going on at the same time.
Also laws have recently become very obstructive for Canadian drone users, can't test anything "legally" for now.

**Comment by dagar** [comment]
Sorry to hear that, I got around it by moving to Florida.

I'm going to add a tricopter t mixer in another pull request. Let's reopen this to add the rest of the trijumper mixer when there's something to go along with it? Otherwise, it mainly confuses users.

**Pull request closed without merging**
