### PR TITLE
Optionally load mavlink plugin to gazebo models

### PR DESCRIPTION
**Pull request by devbharat**
Added flag to optionally load mavlink plugin to gazebo models (if rotors_simulator is built without mavros for pure ros sitl, the mavlink plugin would not be built, then it shouldn't be added to the gazebo models).

I am adding a corresponding PR in rotor_simulator too.

### CODE REVIEW

**Comment by devbharat** [comment]
I don't know why it shows sitl merge is failing. I can build it just fine on my local machine, and the launch file change shouldn't even effect sitl.

**Comment by LorenzMeier** [comment]
@AndreasAntener Does this need a change in the SITL CI system?

**Comment by AndreasAntener** [comment]
@devbharat Against what version/branch of rotors_simulator do you work?

**Comment by devbharat** [comment]
The master branch on px4/rotor_simulator. 

My build system is a little more complicated now that I installed gazebo and ros separately, with protobufs 3 and what not, so the CMakeList I use to build rotor_simulator is different than the current master on px4/rotor_simulator. But I've filtered out the changes for the PR.

You could checkout the current master in both px4/firmware and px4/rotor_simulator (and mavros if you want to) in a catkin workspace and build it with either

    catkin_make 

or

    catkin_make -DMAVLINK_DIALECT=pixhawk -DMAVLINK_INTERFACE=y

The later assuming you have mavros. It builds fine for me. Then you could then launch either

    roslaunch px4 gazebo_iris_empty_world.launch

or 

    roslaunch px4 gazebo_iris_mavros_posix_sitl.launch

They also work for me (except that I need the protobuf/msgs directory included and linked in my CMakelist.txt but shouldn't be required if you have the default gazebo_ros packages).

Also, it'll be helpful if you could run and tell if you have an error, as I've been running them only on my system. Thanks.

**Comment by AndreasAntener** [comment]
Ah I see. I missed your PR against rotors_simulator. I kicked off the rebuild of the SITL containers, so we should soon have some that have updated MAVROS packages.

**Comment by AndreasAntener** [comment]
Ok, build not really kicked off yet, have to wait until Github troubles disappear :/

**Comment by AndreasAntener** [comment]
@CI test this please

**Comment by AndreasAntener** [comment]
@LorenzMeier @devbharat looks good now. Haven't tried it my self though, but seems to work ok in SITL. Just one note: since this together with rotors_simulator depends on latest MAVROS (0.14, extracted message package), it could still take a few days until the Ubuntu repos have that (the SITL containers are using shadow repos to be up-to-date faster)

**Comment by LorenzMeier** [comment]
@devbharat Is this still relevant?

**Comment by devbharat** [comment]
I realize now that mavros isnt really required for this functionality and I can simply pack the mavlink data to UDP directly. I'll make the changes and update this soon.

**Pull request closed without merging**
