### PR TITLE
Master f7 stackcheck - result update stacks

### PR DESCRIPTION
**Pull request by davids5**
Fixes https://github.com/PX4/Firmware/pull/11554#event-2169097364 with SYS_AUTOSTART=4001

The cause of the stack detection fault is because of the
   level of nesting in the start up script. We need to
   determine the worst case configuration and set the
   bar there.

   This fault occurred some 42 calls deep due to script
   calling script (repeat).

   The HW stack check requires as a margin of 204 bytes. That is
   ISR HW stacking of CPU(8) FPU(18) registers and SW stacking of
   CPU(11) and FPU(16) registers. Total CPU(19) registers is
   68 bytes and the total FPU(34) registers is 136 bytes.  On
   a system with a separate ISR stack This only needs to be 104
   so there is 100 bytes of headroom. But as coded the detection
   will give a false positive detection and fault. This does not
   mean that the stack will be corrupted.

   Adjustments to that stack can have no effect due to rounding.
   A stack size of 2608 and 2616 can yield the exact same size stack.
   So even when the failure is due to a 4 byte overflow, it can take
   greater than a 16 bytes increase to fix it. Because the final
   stack size is calculated with an 8 byte alignment after a 4 byte
   decrease. So 2624 becomes 2620 at runtime and will boot
   with SYS_AUTOSTART=4001.

### CODE REVIEW

**Comment by davids5** [comment]
I am hoping to get this in upstream:
https://bitbucket.org/nuttx/nuttx/pull-requests/834/armv7-m-stackcheck-allow-faulting-stack/diff

image

Subtract R11 from R10 and add 12. Then that number to the failed stack size.

**Comment by davids5** [comment]
@dagar it is in and documented in http://nuttx.org/doku.php?id=wiki:howtos:run-time-stack-checking&#per_function_call

**Comment by davids5** [comment]
@dagar Doe it make sense to take one more drink from upstream on https://github.com/PX4/Firmware/pull/11537 to get the stack info in the up_assert display?

**Comment by dagar** [comment]
> @dagar Doe it make sense to take one more drink from upstream on #11537 to get the stack info in the up_assert display?

Yes I'll update https://github.com/PX4/Firmware/pull/11537 again.

**Pull request merged**
