### PR TITLE
Move hysteresis test to gtest

### PR DESCRIPTION
**Pull request by julianoes**
I did the move of the hysteresis class as I envision it. It's now a self-contained simple class without dependencies or side effects and the unit tests run immediately and won't ever by flaky because of stalled CI hosts.

I agree that we still want to run unit tests like these on real hardware, I'm therefore planning to run the gtest tests on a Pixhawk and if that's impossible we need to find some test framework that makes it possible.

I'm not sure yet if every module should come in this form, so without many dependencies, or if we need higher level tests for some "modules".

### CODE REVIEW

**Comment by julianoes** [comment]
> Playing devils advocate for a minute, don't you think this makes hysteresis slightly easier to misuse?

Yes, I agree, the API is suboptimal.

**Comment by julianoes** [comment]
@dagar an alternative would be to set a fake clock and inject it into the constructor of the `Hysteresis` object, or some global set up of the fake clock.

**Comment by dagar** [comment]
I don't think shifting some of the complexity to the caller in order to enable faster more convenient unit tests is ultimately going to put us in a better place. Maybe this is a trivial example to get hung up on or maybe that makes it easier to discuss.

As much as possible I'd rather we encapsulate these things to make them easy to use, hard to misuse.

What if we did something within the framework of lockstep SITL (fake clock), but drove it internally as fast as possible (without the simulator)?

**Comment by julianoes** [comment]
> What if we did something within the framework of lockstep SITL (fake clock), but drove it internally as fast as possible (without the simulator)?

Yes, I'll think something like that could work. On the other hand many classes - in my opinion - should have less dependencies and side effects, and time is one of those things.

**Comment by MaEtUgR** [comment]
I changed the filename according to my comment and am rebasing on master since I introduced the conflicts.

**Pull request merged**
