### PR TITLE
Fix: ROS install space

### PR DESCRIPTION
**Pull request by TSC21**
**Describe problem solved by the proposed pull request**
Inside a ROS context, there are currently two distinctive ways we can build packages inside a workspace: using `catkin tools` or using `colcon`. While the first one supports a *devel* space, the second one doesn't and installs the project according to the directives on the `CMakeLists.txt` files.

So, while using `catkin tools`, the solution would work as expected, since everything will be set and under a *devel* space, when using an *install* space, things wouldn't work properly, as we are not installing the required files onto the expected directories.

**Describe your preferred solution**
The solution was to get into the posix platform build structure, specifically for the sitl target, and rearrange the install dirs, in a way that they match the expected organisation for a ROS workspace. While this continues to work in a normal raw CMake build, the current install dirs also allow it to work inside a ROS workspace.

**Additional context**
To test it, one can use and install `colcon` on his system (assuming that you have ROS installed already). If you are under a ROS 1 context:
```sh
$ sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
$ sudo apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 421C365BD9FF1F717815A3895523BAEEB01FA116
$ sudo apt update
$ sudo apt install python3-colcon-common-extensions
```

Then, to build PX4 under a ROS1 workspace:
```sh
$ mkdir -p colcon_ws/src
$ cd colcon_ws/src
$ git clone --recursive https://github.com/PX4/Firmware
$ ln -s Firmware/Tools/sitl_gazebo mavlink_sitl_gazebo
$ colcon build --event-handlers console_direct+
```

The above can also be tested using `catkin` by setting an `install` space: `catkin config --install`.

Then, to test if it works, first source your workspace using `source install/local_setup.bash` (or `setup.bash` for the `catkin` case). Then, try running one of the launch files: `roslaunch px4 mavros_posix_sitl.launch`. If all was properly set, the Gazebo simulation with PX4 SITL and MAVROS will launch as they should.

### CODE REVIEW

**Comment by TSC21** [comment]
Just need to fix now the path for `test` on CI and all should be good.

**Comment by TSC21** [comment]
Yep:
```sh

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'

  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

Aborted (core dumped)
```
This is happening on the `rostest`. I have no idea of what's causing this. Locally the test is failing as well, though it doesn't through the above error. Have to dig in.

**Comment by TSC21** [comment]
Here's how a catkin workspace is organized: http://wiki.ros.org/catkin/workspaces.
Colcon will build the package as a standard CMake build, but for usage in ROS1, it totally depends on how you organize the install structure. The problem doesn't occur when you build it using `catkin tools` because it is created a `devel` space. But when building with `colcon`, everything gets installed, so to use it as if it was in a ROS workspace, you need to place the binaries and required tools under the `shared` folder.

**Comment by dagar** [comment]
> @dagar I just explained above how this changes in catkin and colcon.

Yes I know, but what I'm talking about is taking a step back to make sure the basics are in place first so we stop playing issue whack-a-mole. Throwing everything into share like this just isn't right.

**Comment by TSC21** [comment]
I am not sayint that throwing everything into  share is the solution. But something has to go there eventually.

**Comment by TSC21** [comment]
@dagar what do you suggest to be done in order this gets solved? We need to eventually bring something under `share` folder so the installed stuff gets solved and sourced properly in a ROS environment. I am not saying all should go to `share`, but at least the `package.xml`, launch files and the PX4 bin file.

**Comment by TSC21** [comment]
@dagar please let me know how do you want to proceed with this. I am ok on discussing this on a call. Thanks

**Comment by TSC21** [comment]
Still needs discussion.

**Comment by TSC21** [comment]
This needs discussion but let's close it for now. I will get back to it later.

**Pull request closed without merging**
