### PR TITLE
use correct Unix line ending character

### PR DESCRIPTION
**Pull request by tumbili**
@AndreasAntener Can you cherry pick this commit and run the pruner tool on the mixer file?
I couldn't reproduce the problem anymore after this fix.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@tumbili We still might want to merge this one to prevent windows users from falling over.

**Comment by LorenzMeier** [comment]
@tumbili Could you please re-test this so we can merge it?

**Comment by tumbili** [comment]
Tested, merging.

**Comment by LorenzMeier** [comment]
Awesome!

**Pull request merged**
