### PR TITLE
Enable auto disarm by default

### PR DESCRIPTION
**Pull request by MaEtUgR**
**Describe problem solved by the proposed pull request**
Based on defaults used by products at Yuneec and Auterion, feedback from @MikeGoesDrones and discussions with @RomanBapst and @LorenzMeier I think we need to adjust our defaults to the more common use-case of adopters having a good out of the box experience instead of needing to look up how to enable everything that seems intuitive.

**Test data / coverage**
Untested but it's only a parameter change to a configuration that was used a lot before.

### CODE REVIEW

**Comment by dagar** [comment]
I agree with the `COM_DISARM_LAND` change, but not so sure about `COM_RC_OVERRIDE`. It was quite a long time ago, but I recall several developers (not necessarily users) reporting it as unexpected/concerning behavior. A large part of this might be existing expectation though.

**Comment by MaEtUgR** [comment]
> but I recall several developers (not necessarily users) reporting it as unexpected/concerning behavior

@dagar I can't think of one single person that didn't react with oh nice, why do I have to find this parameter first to make it intuitive. That said there might be corner cases for a mapping drone with a pilot that accidentally moves the stick while it's far away. But in that case you still see in telemetry that the mission was interrupted and there is the option to disable it.

**Comment by igalloway** [comment]
This is not the same issue as auto disarm on land, but I am wondering the
reasoning behind it - why does the kill switch not disarm the vehicle after
a short period? Over seen people use the kill switch to turn off the rotors
on landing or panic situation, but since the vehicle remains active, it
poses a high risk to operator or others if the switch gets bumped again.
Disarm on landing will take care of this partially. An optional delay timer
to auto disarm on kill switch would take care of the remaining risk for
rotor craft. I assume you *may want to stay armed for other types of
vehicles?

**Comment by dagar** [comment]
> auto disarm on kill switch

@igalloway this was added for v1.9

**Comment by MaEtUgR** [comment]
> why does the kill switch not disarm the vehicle after
a short period?

it does after 5 seconds since https://github.com/PX4/Firmware/pull/10175 (contained in 1.9)

**Comment by LorenzMeier** [comment]
Let’s get this - we need to drive the UX in PX4 towards what people expect.

**Comment by dagar** [comment]
I'm in favor of the change I'd just like to be sure we understand why it was objectionable in the first place.
`COM_RC_OVERRIDE` was added by @sanderux in https://github.com/PX4/Firmware/pull/7025. Was the concern FW going into position control mode from RTL or something else?

As a side note this is a good example of the how we should try to capture more context in PRs to understand the background motivation.

**Comment by sanderux** [comment]
The concern was that we had clients that were flying missions with an RC that was sending some noise, or they accidentally touched a stick. It then went into POSTCTL without their knowledge and they only barely got it back.

I added this because it needs to be extremely clear in what mode the vehicle is flying, suddenly changing out of auto mission because a stick was touched sees like a very bad idea to me. perhaps on a quadcopter its not so much an issue, but a vtol/fw will just fly away

**Comment by sanderux** [comment]
Perhaps COM_RC_OVERRIDE should only default to 1 on vehicles that hold position in POSCTL

**Comment by LorenzMeier** [comment]
That’s a sensible suggestion.

**Comment by dagar** [comment]
Thanks for the quick response @sanderux. 

How about we limit the override evaluation to rotary wing (including VTOLs in MC mode) and update the param comment?

https://github.com/PX4/Firmware/blob/423219c60ed2a9e4f97484634e2e4f4adc218d5b/src/modules/commander/Commander.cpp#L1825-L1867

**Comment by MaEtUgR** [comment]
Sounds like a good idea to me. I can do that.

**Comment by MaEtUgR** [comment]
Based on the discussion I suggest we separate this pr and only enable auto disarming after land detection by default and I'll create another pr to implement https://github.com/PX4/Firmware/pull/12346#issuecomment-506960499 and link it here.

I rebased on master and took out the RC override changes.

**Comment by Antiheavy** [comment]
Auto-disarm after land detection is problematic for hand launched fixed wing drones.  We are working on a PR in a custom branch that will address this and allow auto-disarm to be enabled by default.  It blocks auto-disarm whenever LaunchDetection is running using a new uORB message that lets the system know when LaunchDetection is running.   FYI @kjkinney

**Comment by MaEtUgR** [comment]
@Antiheavy Thanks for pointing that out. So should I put it to disabled in the fixed-wing defaults in the meantime?

**Comment by MaEtUgR** [comment]
Separate pr for RC override default now here: https://github.com/PX4/Firmware/pull/12495

**Comment by Antiheavy** [comment]
> @Antiheavy Thanks for pointing that out. So should I put it to disabled in the fixed-wing defaults in the meantime?

From a safety standpoint I still think it is a good idea to default the parameter to enabled for all.  Maybe this is a good excuse for us to push the LaunchDetection disarm blocker upstream sooner rather than later.

**Comment by MaEtUgR** [comment]
@Antiheavy Ok, then I leave it like it is. I guess for the hand launch mode case you would want to take a look at the variable `have_taken_off_since_arming` https://github.com/PX4/Firmware/blob/4a02475dd183721701536fbcb4a4229d55911006/src/modules/commander/Commander.cpp#L1632

**Comment by hamishwillee** [comment]
@MaEtUgR @RomanBapst When this goes in can you confirm the actual change -for docs because there is a lot of discussion here.

1. Will [COM_DISARM_LAND](http://docs.px4.io/master/en/advanced_config/parameter_reference.html#COM_DISARM_LAND) enabled by default be applied to all frames or just some?
2. Was the [COM_RC_OVERRIDE =1](http://docs.px4.io/master/en/advanced_config/parameter_reference.html#COM_RC_OVERRIDE) implemented, and if so, for vehicles that hold position in POSCTL? I presume this means MC and VTOL in MC mode?
3. Anything else?

>> auto disarm on kill switch

>this was added for v1.9

@dagar Did this have any configuration? Is this immediate?
- I think we just need to change http://docs.px4.io/master/en/config/safety.html#kill_switch where we say "The vehicle is not disarmed, and the motors will restart if the switch is reverted."

**Comment by MaEtUgR** [comment]
> 1. Will COM_DISARM_LAND enabled by default be applied to all frames or just some?

Yes, I asked again in the dev call yesterday and it seemed appropriate for the user experience on all platforms except for the corner case of the launch mode mentioned by @Antiheavy above. He said he'll take care that it will not disarm during fixed-wing hand launch when the feature is finished.

> 2. Was the COM_RC_OVERRIDE =1 implemented, and if so, for vehicles that hold position in POSCTL? I presume this means MC and VTOL in MC mode?

That moved to https://github.com/PX4/Firmware/pull/12495 and there were some misunderstandings. The result of yesterdays devcall discussion was that this functionality is only useful for multicopter flying.

> I think we just need to change http://docs.px4.io/master/en/config/safety.html#kill_switch where we say "The vehicle is not disarmed, and the motors will restart if the switch is reverted."

Yes, it's not configurable and it's planned to stay like this according to my understanding. I don't see any problem with that except that apparently the docs are off.

**Comment by MaEtUgR** [comment]
@hamishwillee Suggestion for documentation for kill switch https://github.com/PX4/px4_user_guide/pull/528

**Comment by hamishwillee** [comment]
THanks @MaEtUgR - the auto disarm docs for you to review in https://github.com/PX4/px4_user_guide/pull/530
I

**Comment by Antiheavy** [comment]
>  Maybe this is a good excuse for us to push the LaunchDetection disarm blocker upstream sooner rather than later.

FYI https://github.com/PX4/Firmware/pull/12513

**Pull request merged**
