### PR TITLE
disable -fassociative-math (within -funsafe-math-optimizations)

### PR DESCRIPTION
**Pull request by dagar**
* includes ECL #601: Implemented Kahan summation algorithm for adding process noise
* https://github.com/PX4/ecl/pull/601

### CODE REVIEW

**Comment by dagar** [comment]
Overall flash differences from current master on px4_fmu-v5.

image

**Comment by dagar** [comment]
@PX4/testflights could you give this one quick flight on a single platform with a comparison to current master?

**Comment by dagar** [comment]
Questions
1. Does this result in any major performance regressions?
2. Can we convince ourselves that this is the strictly safer thing to do?

**Comment by jkflying** [comment]
Note this also has the Kahan summation, so I expect the flight performance to be a little different, since the bias variance estimates will actually grow now unless there is data fused that reduces them. The CPU load will be particularly interesting to track. Note the places with big code size differences will probably also be the places with big performance differences - mostly stuff with matrix oeprations that can't have common calculations factored out or cancelled now. It depends if it is in a hot loop or not.

There are also some risks, for example the optimization would save us from 0/0 situations since the variables would be cancelled. We'll have to keep an eye out for this.

**Comment by jkflying** [comment]
SITL testing works fine for me, not noticeable changes.

**Comment by LorenzMeier** [comment]
I would merge Kahan summation first, then evaluate the math flags separately.

**Comment by jkflying** [comment]
The issue is that the Kahan summation is optimized out by the math flags, so is 'implicitly disabled' unless we do workarounds in the ECL.

**Comment by LorenzMeier** [comment]
I'm aware, but I would do that locally first.

**Comment by Junkim3DR** [comment]
### Tested on Pixhawk 4mini v5

**Modes Tested** 
- Position Mode: Good. 
- Altitude Mode: Good. 
- Stabilized Mode: Good. 
- Mission Plan Mode (Automated): Good. 
- Failsafe RTL (Return To Land): Not returning after RC shutdown. 

**Procedure** 
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint turn off RC to trigger Failsafe RTL and see landing behavior. 

**Notes** 
No issues noted, good flight in general.

**Logs**
- Master
https://review.px4.io/plot_app?log=9cb9ecae-bdf7-49aa-968e-6c523a153220
- PR 12096
https://review.px4.io/plot_app?log=16427fc8-4db8-4f08-a525-895c51298e3f

**Comment by dagar** [comment]
Unexpectedly the cpu usage actually decreased slightly.


Master - https://review.px4.io/plot_app?log=9cb9ecae-bdf7-49aa-968e-6c523a153220
image


PR 12096 - https://review.px4.io/plot_app?log=16427fc8-4db8-4f08-a525-895c51298e3f
image

**Comment by dannyfpv** [comment]
Tested on Pixhawk 4 v5
Modes Tested

Notes: Acro mode has a stabilization assistance feeling while flying, it does not feel like full acro mode.

Procedure: tested on acro mode only
acro Mode
https://review.px4.io/plot_app?log=5f79e673-f4f3-41e3-a1c1-da3205ca4437

**Comment by dagar** [comment]
@PX4/testflights please exhaustively test this across all vehicles.

**Comment by jorge789** [comment]
### Tested on PixRacer V4:

**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.
**- Notes**
No issues noted, good flight in general.

**Logs**

**- PR 12096** 
https://review.px4.io/plot_app?log=aa1756f3-2994-4adc-bca0-2f0c271

**Log Comparison** to Master:
https://review.px4.io/plot_app?log=1c2fcafa-9b0f-41a2-8435-8c3350c8cfb8

### Tested on PixRacer V4:

Modes Tested:
-Acro mode.

**Procedure:**
Armed and took-off in acro mode, while in the air performed flips and rolls for about a minute, then proceeded to land.

**Notes:** In Acro mode, while flying, it does not feel like full acro mode.
In rotation, the vehicle hesitates when passing through its level upright position in what seems like an attempt to stabilize.
Flying acro with other flight controllers would produce a smooth pass through this position.

**Log:**
https://review.px4.io/plot_app?log=a21269c1-081e-4379-8ce8-00c3841372bc

**Comment by jorge789** [comment]
### Tested on PixRacer V4:
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.
- Notes
No issues noted, good flight in general.

**Logs**

- PR 12096
https://review.px4.io/plot_app?log=aa1756f3-2994-4adc-bca0-2f0c271

Log Comparison to Master:
https://review.px4.io/plot_app?log=1c2fcafa-9b0f-41a2-8435-8c3350c8cfb8

### Tested on PixRacer V4:
Modes Tested:
-Acro mode.

**Procedure:**
Armed and took-off in acro mode, while in the air performed flips and rolls for about a minute, then proceeded to land.

**Notes:** In Acro mode, while flying, it does not feel like full acro mode.
In rotation, the vehicle hesitates when passing through its level upright position in what seems like an attempt to stabilize.
Flying acro with other flight controllers would produce a smooth pass through this position.

**Log:**
https://review.px4.io/plot_app?log=a21269c1-081e-4379-8ce8-00c3841372bc

### Tested on Pixhawk 2 Cube V3:
**Modes Tested**

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL: Good.

**- Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.
**- Notes**
No issues noted, good flight in general.

**Logs**
https://review.px4.io/plot_app?log=c87d3e56-c34a-4562-af1e-3426e5ab4648

Log Comparison to Master:
https://review.px4.io/plot_app?log=29af6d61-61ac-49c6-a71e-df221eef0ac3

### Tested on Pixhawk 2 Cube V3:

**Modes Tested:**
-Acro mode.

**Procedure:**
Armed and took-off in acro mode, while in the air performed flips and rolls for about a minute, then proceeded to land.

**Notes:** In Acro mode, while flying, it does not feel like full acro mode.
In rotation, the vehicle hesitates when passing through its level upright position in what seems like an attempt to stabilize.
Flying acro with other flight controllers would produce a smooth pass through this position.

**Log:**
https://review.px4.io/plot_app?log=18af06e1-a19c-4037-8932-fc77dc4e4330

**Comment by Junkim3DR** [comment]
### Tested on Pixhawk 4 mini v5

**Modes Tested**
- Position Mode: Good. 
- Altitude Mode: Good. 
- Stabilized Mode: Good. 
- Mission Plan Mode (Automated): Good. 
- RTL (Return To Land): Good.
- Acro: Good.

**Procedure** 
- Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint trigger RTL and see landing behavior. 

- For Acro mode: Armed and took-off in acro mode, while in the air performed flips and rolls for about a minute, then proceeded to land.

**Notes** 
- No issues noted, good flight in general.
- For Acro mode: While flying, it does not feel like full acro mode.
In rotation, the vehicle hesitates when passing through its level upright position in what seems like an attempt to stabilize.
Flying acro with other flight controllers would produce a smooth pass through this position.

**Logs**
- Acro
https://review.px4.io/plot_app?log=6fbb0cf5-a8fa-4552-a940-f80b589faaf8


### Tested on Pixhawk Pro v4

**Modes Tested**
- Position Mode: Good. 
- Altitude Mode: Good. 
- Stabilized Mode: Good. 
- Mission Plan Mode (Automated): Good. 
- RTL (Return To Land): Good.
- Acro: Good.

**Procedure** 
- Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint trigger RTL and see landing behavior. 

- For Acro mode: Armed and took-off in acro mode, while in the air performed flips and rolls for about a minute, then proceeded to land.

**Notes** 
- No issues noted, good flight in general.
- For Acro mode: While flying, it does not feel like full acro mode.
In rotation, the vehicle hesitates when passing through its level upright position in what seems like an attempt to stabilize.
Flying acro with other flight controllers would produce a smooth pass through this position.

**Logs**
- PR 12096
https://review.px4.io/plot_app?log=3f2c5b69-d586-47f1-bc53-017384d600e2
- Acro
https://review.px4.io/plot_app?log=6e167ab8-4d2f-4458-8908-872df4bfae43


### Tested on NXP FMUK66 v3

**Modes Tested** 
- Position Mode: Good. 
- Altitude Mode: Good. 
- Stabilized Mode: Good. 
- Mission Plan Mode (Automated): Good. 
- RTL (Return To Land): Good. 

**Procedure** 
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint trigger RTL and see landing behavior. 

**Notes** 
Vehicle felt more responsive, smoother and more stable; good flight in general.

**Logs**
- PR 12096
https://review.px4.io/plot_app?log=c6daf4c7-fd04-47d1-a074-db1f7b9d2d9a

**Comment by dagar** [comment]
This is looking good so far. New plan, I'll update the PR to bring in only the optimization flag changes, which will then put https://github.com/PX4/ecl/pull/601 in a position where they can bring in the change when @priseborough is ready.

**Comment by jorge789** [comment]
### Tested on PixRacer V4:

**Flight Card 1**

**Modes Tested:**
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.

**Procedure:**
Arm in position mode, check take off behavior (Vehicle should stay on the ground as long as the throttle stick is at the middle or below, and start to ascend smoothly as long as throttle stick as above the middle.), the land and disarm.
Same procedure was repeated with Altitude and Stabilized mode.

**Notes:**
No issues were noted, good flight in general.

**Flight Card 2**

**Modes Tested**
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Take off in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
No issues were noted, good flight in general.

**Flight Card 3**

**Modes Tested**
Position Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
No issues were noted, good flight in general.

**Logs:**

Flight card 1:  https://review.px4.io/plot_app?log=63ea5b4e-d8df-49cf-a25b-ad5495395a76

Flight card 2:  https://review.px4.io/plot_app?log=7c6f8293-2489-4784-8823-df034c5d17a2

Flight card 3:  https://review.px4.io/plot_app?log=e195ddd3-b27b-4d66-a010-1759d23809cf

**Comment by Junkim3DR** [comment]
### Tested on Pixhawk Pro v4

**Flight Card 1**

**Modes Tested:**
- Position Mode: Good. 
- Altitude Mode: Good. 
- Stabilized Mode: Good. 

**Procedure:**
Arm in position mode, check take off behavior (Vehicle should stay on the ground as long as the throttle stick is at the middle or below, and start to ascend smoothly as long as throttle stick as above the middle.), the land and disarm.
Same procedure was repeated with Altitude and Stabilized mode.

**Notes:**
No issues were noted, good flight in general.


**Flight Card 2**

**Modes Tested**
- Mission Plan Mode (Automated): Good.
- RTL (Return To Land): Good.

**Procedure**
Arm and Take off in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior. 

**Note:**
No issues were noted, good flight in general.


**Flight Card 3**

**Modes Tested**
- Position Mode: Good.
- Mission Plan Mode (Automated): Good.
- RTL (Return To Land): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior. 

**Note:**
No issues were noted, good flight in general.


**Flight Card 4**

**Modes Tested**
- Position Mode: Good.
- Failsafe RTL (Return To Land): Not returning after RC shutdown. 

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, turned RC off in order to activate failsafe RTL, wait for vehicle to return and land as expected.  

**Note:**
No issues were noted, good flight in general.


**Logs:**
- Flight Card 1: https://review.px4.io/plot_app?log=913c24c2-fcfa-48f6-aeb2-b21f2c159c29
- Flight Card 2: https://review.px4.io/plot_app?log=d50c17e6-4419-4846-a028-dd06a2f064e4
- Flight Card 3: https://review.px4.io/plot_app?log=a312d9d1-ac90-4218-bd21-13b9c46ab6b6
- Flight Card 4: https://review.px4.io/plot_app?log=a3cd52f5-3ee1-4882-9078-6a28b7d46472



### Tested on Pixhawk 4 mini v5

**Flight Card 1**

**Modes Tested:**
- Position Mode: Good. 
- Altitude Mode: Good. 
- Stabilized Mode: Good. 

**Procedure:**
Arm in position mode, check take off behavior (Vehicle should stay on the ground as long as the throttle stick is at the middle or below, and start to ascend smoothly as long as throttle stick as above the middle.), the land and disarm.
Same procedure was repeated with Altitude and Stabilized mode.

**Notes:**
No issues were noted, good flight in general.


**Flight Card 2**

**Modes Tested**
- Mission Plan Mode (Automated): Good.
- RTL (Return To Land): Good.

**Procedure**
Arm and Take off in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior. 

**Note:**
No issues were noted, good flight in general.


**Flight Card 3**

**Modes Tested**
- Position Mode: Good.
- Mission Plan Mode (Automated): Good.
- RTL (Return To Land): Good.

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior. 

**Note:**
No issues were noted, good flight in general.


**Flight Card 4**

**Modes Tested**
- Position Mode: Good.
- Failsafe RTL (Return To Land): Not returning after RC shutdown. 

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, turned RC off in order to activate failsafe RTL, wait for vehicle to return and land as expected.  

**Note:**
No issues were noted, good flight in general.


**Logs:**
- Flight Card 1: https://review.px4.io/plot_app?log=2832fce5-062f-4cf0-b9de-fc22e55f4e95
- Flight Card 2: https://review.px4.io/plot_app?log=22f07599-5e3f-4328-89b2-77801de30399
- Flight Card 3: https://review.px4.io/plot_app?log=def44909-756a-42b3-93ea-7b1cc19648a3
- Flight Card 4: https://review.px4.io/plot_app?log=6fa32b26-6bc8-46c4-9cd2-ca00cb054aa8

**Comment by dannyfpv** [comment]
Tested on Pixhawk 4 mini v5 v-tol convergence

Modes Tested:

Position Mode: perfect
Stabilized Mode: perfect
transition: perfect
log:
https://review.px4.io/plot_app?log=a5c65240-61c9-40dd-872f-96a761cf7cdf

mission mode: perfect
transition: perfect
land: perfect
log:
https://review.px4.io/plot_app?log=22a506bb-1eec-401e-9764-e945440bc36d

**Comment by jkflying** [comment]
@PX4/testflights can you do another acro test with the latest build? The Kahan stuff has been removed, I want to see if that fixes the feeling of stabilization when exactly horizontal in acro. It needs to be compared to master to see if it feels different.

**Comment by dannyfpv** [comment]
Tested on Pixhawk pro:

Modes tested: Acro mode

Notes: In Acro mode, while flying, it does not feel like full acro mode. In rotation, the vehicle hesitates when passing through its level upright position in what seems like an attempt to stabilize. Same behavior as before noted. No improvements noted.
On master and Acro mode is better but still feels like it has assistance.
Flying acro with other flight controllers would produce a smooth pass through this position.

Acro mode test log:
https://review.px4.io/plot_app?log=ba7bce05-4718-4ff8-bec9-8404683d823e
https://review.px4.io/plot_app?log=21ec7361-08e6-4684-8835-b0fbc13bdcbb

Master:
https://review.px4.io/plot_app?log=1fdeec0d-604f-473f-8e63-e40ff6e5d316

Tested on Pixhawk4 mini v5
Modes Tested: Acro mode

Notes: In Acro mode, while flying, it feels much better than before,  but still it does not feel like full acro mode. You can still note slight assistance to attempt to stabilize. It definitely improved, noted lock-in when rotating.
On master, Acro mode is better but you can still note slight assistance.

PR Acro mode test log:
https://review.px4.io/plot_app?log=ce154708-36a4-4917-b5ba-efdcd25b40f2
https://review.px4.io/plot_app?log=daee9d62-2a99-45ea-8421-91a7d706359d

Master test log:
https://review.px4.io/plot_app?log=c11dda1a-4632-4656-be76-7a75a2faf964

**Comment by bkueng** [comment]
> Notes: In Acro mode, while flying, it still does not feel like full acro mode. In rotation, the vehicle hesitates when passing through its level upright position in what seems like an attempt to stabilize. Same behavior as before noted, no improvements noted.

@dannyfpv please enable Airmode and let me know if it still feels off. The rate tracking is also not great on the log I see. Can you tune it? Make sure to increase the I gains.

**Pull request merged**
