### PR TITLE
UAVCAN ESC Config

### PR DESCRIPTION
**Pull request by LorenzMeier**
This is a starting point for ESC configuration. @bendyer this is the PX4 middleware side of things, and the button in QGroundControl will trigger the code here.

@pavel-kirienko I would have loved to test this, but UAVCAN eats up 40-50K+ in RAM once started with the dynamic server, resulting in a total RAM overflow. I'm sorry to put it so boldly, but this is *not* an embedded protocol. We need to do better.

I would recommend to change your workflow and test *every single pull request against UAVCAN* on a Pixhawk. The experience as an adopter is horrible, since the protocol bloat is exploding with every revision. You can't develop an embedded protocol on Linux and its not sufficient to rely on other people to test it for you. If you need hardware I can arrange a batch of 5-10 units to be shipped to you.

Its like I would develop flight code in a Matlab simulation and never test it in HIL or outside. It just doesn't work, and anyone trying to use it in the real application is constantly bitten by the enormous resource use.

UAVCAN uses right now as much RAM as the complete flight control logic + all sensor drivers + MAVLink. And none of that is particularly optimised.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@davids5 FYI - if you have ideas how to get down to 8-20K for the overall UAVCAN stack let us know.

**Comment by pavel-kirienko** [comment]
> I would have loved to test this, but UAVCAN eats up 40-50K+ in RAM once started with the dynamic server, resulting in a total RAM overflow.

Let me know how do you get these results, because I can't confirm this on the latest beta. I tried to set `UAVCAN_ENABLE` to 2 on a system with normally 52528 bytes free, and it boots successfully, leaving 17152 bytes unused, therefore UAVCAN takes 35376 bytes. This number accords with our previous tests at https://github.com/UAVCAN/libuavcan/issues/33#issuecomment-117712026.

At any rate, 40-50K is unrealistic, there could be some other problem involved. I need to know your exact configuration in order to reproduce it locally.

**Comment by LorenzMeier** [comment]
The last commit shaves enough RAM off the default config to allow a successful boot in config mode with one MAVLink instance via USB. On clicking the button here:

screen shot 2015-08-22 at 19 18 01

The output is:
```bash
nsh> <pthread>: received UAVCAN CONFIG command
<pthread>: UAVCAN CONFIG: Actuator assignment requested
```

@bendyer That should be enough for you to continue here. You need to configure as multicopter or plane via QGroundControl and set the UAVCAN_ENABLE param to 2. Note that right now it takes 8 seconds until you can connect via USB. These limitations will be addressed within the next few days. Once we have the CAN RAM consumption a bit more balanced this will be on by default.

**Comment by bendyer** [comment]
I have completed the ESC side of this (estimating motor position and angular velocity while the controller is not running); my intention is to have the Pixhawk monitor ESC status messages during configuration, and as the user rotates each motor in clockwise sequence around the vehicle, the ESC index and rotation direction parameters will be configured based on which ESC(s) are reporting angular velocity above a threshold value.

@pavel-kirienko, this will require standard names for index and rotation direction. Bearing in mind the parameter name length restrictions imposed by MAVLink, I would like to suggest the parameter names be `esc_index` and `motor_dir`. The `esc_index` parameter would take an integer value from 0–19, and the `motor_dir` parameter would take the value `0` or `1`.

After setting the ESC parameters via uavcan.protocol.param.GetSet and saving them to flash via uavcan.protocol.param.ExecuteOpcode, I intend to restart the ESC(s) via uavcan.protocol.RestartNode to ensure the parameter change is applied.

Any objections to the above?

**Comment by pavel-kirienko** [comment]
@bendyer I had a different approach in mind. The one you have proposed is simple and it doesn't seem to require any additional UAVCAN messages (assuming that the angular velocity can be transferred via the `rpm` field of the ESC status message), but it is has three issues:

1. It is not generic enough to be usable with nodes other than ESC. For example, I expect that servo nodes or certain sensor nodes may also require a similar way of automated enumeration, so an ad-hoc solution that works only with ESC may be not the best approach.
2. It requires to configure the RPM threshold on Pixhawk.
3. A major issue: your approach requires a standard parameter name for rotation direction. It is a problem, because other standard parameter names proposed so far by the specification are defined by either data type names or by the names of their fields. **Since we don't have a field for rotation direction, we cannot define a standard parameter name in a coherent manner**.

I'd like to propose a different solution, based on the old approach with [`uavcan.protocol.EnumerationRequest`](https://github.com/UAVCAN/dsdl/blob/ae48bff0b338d5766fc8f462a316fd467855d7ed/uavcan/protocol/301.EnumerationRequest.uavcan) ([it is implemented in the original PX4ESC](https://github.com/PX4/px4esc/blob/master/firmware/src/uavcan_node/uavcan_node.cpp#L203)), which is now deprecated because it can't coexist with our new feature of dynamic node ID allocation.

The approach is based on a new standard message, let's call it `uavcan.protocol.InstanceIdentification`. Whenever a node receives a specific user input (e.g. rotation of a motor, or pressing a button), this message will be published. The master node (Pixhawk in this case) will then pick up the message and use it to assign the instance ID (`esc_index` in this case). This takes care of the first and second problems.

As for the last problem: we don't really need to set the direction of rotation using UAVCAN. The ESC can self-configure its reverse settings. One of the ways to implement this is to make ESC aware of whether it has a valid configuration (e.g. by setting `esc_index` to -1 by default), and if a valid configuration is not found, the ESC will self-configure its reverse settings according to the direction of rotation during enumeration.

This is my proposition.

In the way of arguing with myself, I can propose an alternative solution to the last problem. Say, the message `uavcan.protocol.InstanceIdentification` could contain an array of key/value pairs, where keys would be strings and values would be tagged unions `uavcan.protocol.param.Value`. Whenever a node receives an identification input from the user, it could collect the settings that were conveyed to the node through the user's input, and put them into the key/value array in the identification message. Pixhawk then will receive the exact set of configuration parameters that need to be set if it choses to accept this enumeration. This approach is interesting as it could let the user, for example, configure ESC indices by means of turning the propellers a specified number of times (UX in this particular use case is questionable, consider it an abstract example).

**Comment by bendyer** [comment]
@pavel-kirienko regarding the three issues you raise:

1. I am not convinced that a fully generic solution to this problem is possible as in my view it's an interaction design issue rather than a technical issue. That is to say, I consider it likely that the user-level procedure for configuring ESCs would be so different to the procedure for configuring actuators or indication controllers that the same protocol conventions could not be used for all three cases.
2. I don't think this needs to be configurable: it simply needs to be above the background noise (if any), so for argument's sake we can simply look for an angular velocity (reported rpm) ≥ 1σ for ≥ 1 s.
3. If standard parameter names for common devices are not explicitly defined, I expect ad-hoc standards will emerge based on whatever the manufacturers of popular devices happen to implement. For example, it's likely that if the manufacturer of the first popular ESC decides to use `num_poles` to store the pole count of the motor, other ESC manufacturers will need to follow suit. I think therefore that the choice is mainly whether the parameter name is a formal standard or an ad-hoc standard; my preference would be for a formal standard.

The above being said, I don't mind your suggested approach. I assume that during configuration the controller (Pixhawk) would publish a `uavcan.protocol.InstanceIdentification` message periodically, indicating what parameter it's currently seeking identification for (e.g. `esc_index`, `hardpoint_id`, `light_id`, `actuator_id`, `gimbal_id`), and then any node supporting that parameter would publish a `uavcan.protocol.InstanceIdentification` with the same parameter name when it receives its user input?

**Comment by pavel-kirienko** [comment]
> I am not convinced that a fully generic solution to this problem is possible as in my view it's an interaction design issue rather than a technical issue. That is to say, I consider it likely that the user-level procedure for configuring ESCs would be so different to the procedure for configuring actuators or indication controllers that the same protocol conventions could not be used for all three cases.

Could you point out exact issues with the generic solution I proposed? I'm not saying the generic approach is the only right one, I just can't model a sensible use case where it won't work. Configuration of nodes like ESC, actuators or sensors can be modeled in identical terms: the user initiates a certain enumeration procedure on the master node (Pixhawk), then the user interacts with the enumerable nodes in a certain order, conveying the order to the master node via UAVCAN.

In your non-generic solution, by moving functions pertaining to RPM analysis from ESC to the master node, you're breaking node's encapsulation, demoting the level of abstraction of node's interface from an abstract level (where generic terms like 'user input' can be applied) to a lower level that calls for inferring high-level actions form monitoring node's state variables (the RPM field).

> If standard parameter names for common devices are not explicitly defined, I expect ad-hoc standards will emerge based on whatever the manufacturers of popular devices happen to implement. For example, it's likely that if the manufacturer of the first popular ESC decides to use num_poles to store the pole count of the motor, other ESC manufacturers will need to follow suit.

I don't see much point in explicit specification of everything. Parameters like instance ID, node ID, bit rate, etc, require to be standartized, because they are expected to be involved in machine-to-machine interaction, and a machine can't *reasonably guess* that `esc_index` and `ESC.index` mean the same thing. The user (hazarding a guess here that all users are humans), on the other hand, can infer the meaning of `num_poles`/`motor.pole_count`/etc, therefore there's no immediate need for explicit standardization. That is not to say that I'm promoting incoherence at this level - the idea is that overspecification will inevitably leave a number of use cases unaddressed, harming flexibility/general-purposity of the standard.

**Comment by bendyer** [comment]
> Configuration of nodes like ESC, actuators or sensors can be modeled in identical terms: the user initiates a certain enumeration procedure on the master node (Pixhawk), then the user interacts with the enumerable nodes in a certain order, conveying the order to the master node via UAVCAN.

Many devices will not be able to accept user input, either because there is no button/input on the device, or because the device is mounted in an inaccessible location.

Such devices will need a different approach to enumeration, for instance having the controller assign a unique index to each of them and then interacting with the user via the GCS to refine the assignments.

> In your non-generic solution, by moving functions pertaining to RPM analysis from ESC to the master node, you're breaking node's encapsulation, demoting the level of abstraction of node's interface from an abstract level (where generic terms like 'user input' can be applied) to a lower level that calls for inferring high-level actions form monitoring node's state variables (the RPM field).

Alternatively, by forcing each node to be aware of concepts like "user input" when it doesn't strictly have to be, the proposed `uavcan.protocol.InstanceIdentification` approach violates separation-of-concerns and causes individual nodes to impose their own views on interaction design, taking responsibility for user experience away from the GCS/flight controller.

> The user (hazarding a guess here that all users are humans), on the other hand, can infer the meaning of num_poles/motor.pole_count/etc, therefore there's no immediate need for explicit standardization. That is not to say that I'm promoting incoherence at this level - the idea is that overspecification will inevitably leave a number of use cases unaddressed, harming flexibility/general-purposity of the standard.

In the particular case of `pole_count` or whatever for ESCs, that parameter *must* be configured to get correct rpm values, so it needs to be part of the ESC configuration procedure. In the presence of a standard `pole_count` parameter, this can be as simple as opening a dialog, asking the user to enter the pole count of their motors, and configuring that on all attached ESCs.

In the absence of such a parameter, we'd have to show the user a list of all enumerated parameters for each ESC, ask them to find the parameter(s) that look most like they might configure the pole count, and then apply them individually.

I understand that you don't want to overspecify in order to avoid reducing flexibility, and that's certainly a worthy consideration, but I think in situations where we have parameters which we know ~all devices will need to provide in order to implement the standard, it makes sense to include the names of those parameters as part of the standard.

**Comment by proficnc** [comment]
Please ensure we also allow for hard ID assignment. For RTF craft, the use of ID Pins is the simplest method, as user interaction is not expected in the setup.

**Comment by bendyer** [comment]
My thinking on pre-configured parameters would be that you'd have one pin to configure direction, and 2–3 (or a voltage divider on an ADC line) to configure index. These pins would be read when restoring the flash parameters to defaults, including on first start-up of the device.

That way you'd be able to override the hard configuration if required, for instance when replacing parts.

**Comment by pavel-kirienko** [comment]
> Many devices will not be able to accept user input, either because there is no button/input on the device, or because the device is mounted in an inaccessible location.

I recognize that most nodes will not be able to accept user input, and therefore the enumeration procedure will not be applicable to them. Such nodes are out of the scope of the problem. I expect that there will be other nodes (like already mentioned actuators) that will be able to accept user input via a button, therefore a generic solution should make sense.

> causes individual nodes to impose their own views on interaction design

This is precisely the point.

We seem to hold opposing views on the amount of logic a node like ESC should implement. You're proposing that an ESC should merely publish its status information to the bus, letting the master node interpret it. I'm proposing that an ESC should provide a black-box API, *which implies interpreting user's input*. Consider a large vehicle with 29+" propellers and an appropriately powerful ESC - in a setup like that, spinning the rotors could be inconvenient for the user. If the enumeration logic was implemented according to the black-box approach, the ESC designers could choose to implement the user's input via a button, leaving the difference hidden from the master node.

> In the particular case of pole_count or whatever for ESCs, that parameter must be configured to get correct rpm values

There are two solutions: a direct one - standardize common parameter names (shortcomings were mentioned earlier); and a generic one - design the user interface in such a way so as to allow them to mass-configure arbitrary ESC parameters. The advantage of the latter is that it is not susceptible to imagination failure in standardizing all parameters that a user may want to assign identical values to.

For purposes of example, the user will likely need to configure such parameters as current limits, temperature warning settings, PID controller settings, RPM limits, etc. I am not convinced that enforcing parameter naming guidelines for all of these parameters is a sensible idea; neither do I see why `num_poles` should be excepted.

As for GCS GUI design, there's a number of ways to implement the generic solution in a user-friendly way. For example, a user could be presented with a list of parameters taken from any ESC, where all parameters known to be unrelated (such as `uavcan.node_id`, `uavcan.bit_rate`, etc) are removed. The user then will be instructed to mark the parameters they'd like to be distributed to all ESC, assign their values, and press OK.

P.S. as a side note, it makes sense to let the ESC automatically infer the direction of rotation, as opposed to configuring it via a parameter, because it makes it indifferent to the order in which motor wires are connected.

**Comment by bendyer** [comment]
Both approaches seem pretty straightforward; while I think the one I suggested is a bit simpler overall, I'm happy to implement either.

@pavel-kirienko re: what I asked in my first reply to you:
>  I assume that during configuration the controller (Pixhawk) would publish a `uavcan.protocol.InstanceIdentification` message periodically, indicating what parameter it's currently seeking identification for (e.g. `esc_index`, `hardpoint_id`, `light_id`, `actuator_id`, `gimbal_id`), and then any node supporting that parameter would publish a `uavcan.protocol.InstanceIdentification` with the same parameter name when it receives its user input?

Is that what you had in mind? If not, please could you flesh the idea out so I can get started?

**Comment by pavel-kirienko** [comment]
> Is that what you had in mind?

In general - yes. I haven't bothered yet to actually *sit and think* about implementation details.

Now I'm sitting and thinking.

Enumerable nodes will have to somehow distinguish the messages from *enumerators* (like Pixhawk) and fellow nodes that are being enumerated (I feel urge to coin a term! Can we call them *enumerees* please?). We could add a field indicating whether it's a request or indication; or we could define two messages, like `InstanceIdentificationRequest` and `InstanceIdentificationIndication` (what a name).

There should be an explicit way to stop the process of enumeration. We could add a duration field to the request message; if we did this, the enumerator will be also able to explicitly stop enumeration by broadcasting a request with zero duration.

Or we could resort to services. Say, there could be a service that the enumerator would be polling until enumeration is complete; but considering that it will have to send the parameter name over the bus, such polling will create high traffic, so no. We could use a service to only enable/disable enumeration, and use messages only for indication purposes. This latter idea allows to precisely pick the nodes for enumeration by one (since services are unicast things), instead of blindly enumerating ALL nodes that support given parameter.

Extending the latest, brightest idea, I propose the following definitions:

`uavcan.protocol.enumeration.Enable`:

```
uint16 TIMEOUT_CANCEL   = 0
uint16 TIMEOUT_INFINITE = 65535
uint16 timeout_sec
uint8[<=92] parameter_name
---
uint8 ERROR_OK                  = 0
uint8 ERROR_INVALID_MODE        = 1
uint8 ERROR_NO_SUCH_PARAMETER   = 2
uint8 ERROR_UNKNOWN             = 255
uint8 error
```

`uavcan.protocol.enumeration.Indication`:

```
uint8[<=92] parameter_name
```

Yes I somehow ended up calling it enumeration instad of identification. I'm not sure why, could be because enumeration is a less generic term, more appropriate in this case.

Does it look good? Did I miss anything important? Do we have to reserve some space in the data structures for arguments or something?

**Comment by davids5** [comment]
Whatever we do, it should be very memory conscious!

 

It would be nice if it follows some well known naming, so it is clear what the roles are:

 

Allocator - Allocatee made sense ….

So would it follow that Enumerators  - Enumeratee Would make sense?

 

Enumeration is clearer then InstanceIdentification

 

Here is me just thinking out loud:

 

It would be nice if there was a way to define a type, prompt, regex (index or well know regex with min/max) for validation in a compact way (think bits). Then a host could prompt or forward the request to a UI based host that could prompt the users or fetch the value from a DB. 

 

The idea is that the device knows what it needs and it does not have a lot of code or data need to describe what it needs and the chain of smarter devices can provide it. (Think proxies)…

**Comment by pavel-kirienko** [comment]
> Whatever we do, it should be very memory conscious!

I'm so memory conscious I can barely sleep at night. This proposed solution should not take much memory though.

> So would it follow that Enumerators  - Enumeratee Would make sense?

I liked this naming too, I just wasn't sure if it's OK to abuse English like that. Anyway, let's take it.

> Here is me just thinking out loud:

I'm not sure I follow. Could you provide an example?

**Comment by pavel-kirienko** [comment]
@bendyer Waiting for your confirmation/rejection. Once the idea is finalized, we could go document it in the form of a diagram with @davids5.

**Comment by bendyer** [comment]
@pavel-kirienko: 

> I liked this naming too, I just wasn't sure if it's OK to abuse English like that. Anyway, let's take it.

From what I can see it's a Latin word imported into English via French; everyone who cares about Latin is long dead, and I think you're outside the jurisdiction of the Académie française as well. Just don't try using it in Scrabble.

@davids5:

> It would be nice if there was a way to define a type, prompt, regex (index or well know regex with min/max) for validation in a compact way (think bits). Then a host could prompt or forward the request to a UI based host that could prompt the users or fetch the value from a DB.
> 
> The idea is that the device knows what it needs and it does not have a lot of code or data need to describe what it needs and the chain of smarter devices can provide it. (Think proxies)…

So this would be a way to prompt the user (or some database) to configure mandatory parameters, if they're not currently specified/valid? 

If so, it sounds useful, but initially I'd like to stick to the minimum possible amount of work so we can get these things ready for advanced users ASAP.

@pavel-kirienko:

> @bendyer Waiting for your confirmation/rejection.

Two points:

1. `uavcan.protocol.enumeration.Enable`: I think there should be a specific error for "this device is unable to accept user input"; `ERROR_UNSUPPORTED` or similar would be clear enough. This would be a cue to the user interface to use an alternative approach.
2. `uavcan.protocol.enumeration.Indication`: it feels like it would be nice to include a value associated with the parameter name, so that devices capable of accepting parametric input could report it here. However I have not fully thought that through and do not particularly care whether or not it is present.

Other than that, I'm happy with the proposal.

**Comment by davids5** [comment]
@bendyer 

>So this would be a way to prompt the user (or some database) to configure mandatory parameters, if they're not currently specified/valid?

>If so, it sounds useful, but initially I'd like to stick to the minimum possible amount of work so we can get these things ready for advanced users ASAP.

Yes and agree to defer it. @pavel-kirienko believes the underpinning exist in the dsdsl of parameter definitions to determine min/max for a param worst case there would be an added element.

Also just an fyi - @pavel-kirienko and I discussed the class of a device that does not have persistent storage - he has suggested a FileRead could be used to fulfill the notion of a proxy. - also being deferred.

**Comment by pavel-kirienko** [comment]
@bendyer

`uavcan.protocol.enumeration.Enable`:

```
uint16 TIMEOUT_CANCEL   = 0
uint16 TIMEOUT_INFINITE = 65535
uint16 timeout_sec
uint8[<=92] parameter_name
---
uint8 ERROR_OK                  = 0
uint8 ERROR_INVALID_MODE        = 1
uint8 ERROR_NO_SUCH_PARAMETER   = 2
uint8 ERROR_UNSUPPORTED         = 3
uint8 ERROR_UNKNOWN             = 255
uint8 error
```

`uavcan.protocol.enumeration.Indication`:

```
uavcan.protocol.param.NumericValue value
uint8[<=92] parameter_name
```

Numeric value: http://uavcan.org/Specification/7._List_of_standard_data_types/#numericvalue
ESC will not use this field, keeping it empty.

I'm going to PR this into the DSDL repo.

**Comment by bendyer** [comment]
@pavel-kirienko sounds good.

**Comment by pavel-kirienko** [comment]
All seems fine.

**Pull request closed without merging**
