### PR TITLE
Driver framework memory fixes and verbosity cleanups

### PR DESCRIPTION
**Pull request by LorenzMeier**
@mcharleb @erikd These are memory initialisation fixes which should be harmless but should help in general. Please review carefully. I also removed a bunch of output which was cluttering the shell without adding any information.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I have this state taking off. In case pre-flight checks fail, here is how to override them (debugging a sensor check which seems to only fail on my machine -> memory):
```diff
diff --git a/src/modules/commander/PreflightCheck.cpp b/src/modules/commander/PreflightCheck.cpp
index 3ca741d..f5ac19c 100644
--- a/src/modules/commander/PreflightCheck.cpp
+++ b/src/modules/commander/PreflightCheck.cpp
@@ -532,7 +532,7 @@ bool preflightCheck(int mavlink_fd, bool checkMag, bool checkAcc, bool checkGyro
        }
 
        /* Report status */
-       return !failed;
+       return true;//!failed;
 }
```

**Comment by LorenzMeier** [comment]
To use takeoff, type ```commander takeoff``` after you have seen the home location set message (about 1-2 seconds after boot, last message). It should immediately gain altitude and continue to rise. Will add more fun things later.

**Comment by LorenzMeier** [comment]
This is how it looks here:

```
WARN  init ref: lat=55.7533950, lon=37.6254270, alt=  0.0000
telem> home: 55.7533950, 37.6254270, 0.00
pxh> 
pxh> commander takeoff
WARN  note: not updating home position on commandline arming!
pxh> WARN  navigator: got takeoff coordinates
WARN  taking off!
telem> home: 55.7533950, 37.6254270, -0.00
telem> TAKEOFF DETECTED
telem> home: 55.7533950, 37.6254270, -0.00
```

**Comment by erikd** [comment]
Yep, can confirm that `commander takeoff` worked. Now what? :-) I suppose I need QGroundControl.

**Comment by LorenzMeier** [comment]
@erikd Next step is to validate the same using the Gazebo simulator: ```make posix gazebo```, then again ```commander takeoff```.

http://dev.px4.io/simulation-gazebo.html

**Comment by LorenzMeier** [comment]
Ok, so I got this now kinda stable on Mac Os with this diff. There is some oddness after a while in the attitude control response, but I'm almost certain that's what Roman and Bharat have been seeing on master and its unrelated to Mac Os. Should not be hard to fix for good now.

@mcharleb Can we discuss today how to get from there to a consolidated stable state?

```
diff --git a/src/drivers/device/vdev_posix.cpp b/src/drivers/device/vdev_posix.cpp
index 745a2ac..c6b0c64 100644
--- a/src/drivers/device/vdev_posix.cpp
+++ b/src/drivers/device/vdev_posix.cpp
@@ -56,12 +56,12 @@ pthread_mutex_t filemutex = PTHREAD_MUTEX_INITIALIZER;
 
 extern "C" {
 
-       static void timer_cb(void *data)
-       {
-               px4_sem_t *p_sem = (px4_sem_t *)data;
-               px4_sem_post(p_sem);
-               PX4_DEBUG("timer_handler: Timer expired");
-       }
+       // static void timer_cb(void *data)
+       // {
+       //      px4_sem_t *p_sem = (px4_sem_t *)data;
+       //      px4_sem_post(p_sem);
+       //      PX4_DEBUG("timer_handler: Timer expired");
+       // }
 
 #define PX4_MAX_FD 200
        static device::file_t *filemap[PX4_MAX_FD] = {};
@@ -270,14 +270,15 @@ extern "C" {
                if (ret >= 0) {
                        if (timeout > 0) {
                                // Use a work queue task
-                               work_s _hpwork = {};
+                               work_s _hpwork;
+                               memset(&_hpwork, 0, sizeof(_hpwork));
 
-                               hrt_work_queue(&_hpwork, (worker_t)&timer_cb, (void *)&sem, 1000 * timeout);
+                               //hrt_work_queue(&_hpwork, (worker_t)&timer_cb, (void *)&sem, 1000 * timeout);
                                px4_sem_wait(&sem);
 
                                // Make sure timer thread is killed before sem goes
                                // out of scope
-                               hrt_work_cancel(&_hpwork);
+                               //hrt_work_cancel(&_hpwork);
 
                        } else if (timeout < 0) {
                                px4_sem_wait(&sem);
```

**Comment by mcharleb** [comment]
This change removes the timeout functionality so it will block until the semaphore is posted.

**Comment by LorenzMeier** [comment]
So this is now running without any mac specific hackery by just using timed wait semaphores instead of the HRT for px4_poll(). I have now the same state as on Linux. Still some dynamic symptoms to resolve, but the days of fruitless debugging seem over.

**Comment by mcharleb** [comment]
Excellent!

**Pull request merged**
