### PR TITLE
Adding STM32F7 Support px4nucleoF767ZI-v1 

### PR DESCRIPTION
**Pull request by davids5**
This PR ports PX4 to the STM32F7. Specifically the px4nucleoF767ZI-v1  which is based on the STMicro Nucleo-144 development board family.  

The STMicro Nucleo-144 can be thought in terms of OOD/OOP as a "base class" and the specialization are instanced as the Nucleo-144 variants. 

image

All the boards are identical, differing only in the installed part and some solder blob option.

The NUCLEO-F767ZI hosts a  STM32F767ZIT6 which is a 216MHz Cortex-M7 with 2048Kb Flash memory and 512Kb SRAM.

This is a WIP development platform based on the FMUv5 specification, and since the NUCLEO-F767ZI is not an auto pilot, it is not flyable without adding  a lot of IO devices. (Anyone want to spin a companion board?)

### CODE REVIEW

**Comment by wangxuanjie** [comment]
Hello,david!
I can not find a bootloader for nuttx_v3_px4nucleoF767ZI-v1 firmware , and how to run nuttx_v3_px4nucleoF767ZI-v1 on a nucleo board,thanks

**Comment by davids5** [comment]
With the build in STlink or add JTAG as described in the [manual] (http://www.st.com/content/ccc/resource/technical/document/user_manual/group0/26/49/90/2e/33/0d/4a/da/DM00244518/files/DM00244518.pdf/jcr:content/translations/en.DM00244518.pdf)

Leave the CN4 jumper on.

**Comment by wangxuanjie** [comment]
Reply really fast，david
Yes,I already did that
I type command "st-flash write nuttx-px4nucleoF767ZI-v1-default.px4 0x8000000", everything is ok,but the UART8 does not print any nuttx shell, it seems that the board does not work.
Is there any steps i miss

**Comment by davids5** [comment]
st-flash write nuttx-px4nucleoF767ZI-v1-default.px4 -> st-flash write nuttx-px4nucleoF767ZI-v1-default.bin

**Comment by wangxuanjie** [comment]
Thank you very much david
Do you mean that the nuttx-px4nucleoF767ZI-v1-default.px4 is a hex file?And i have to cover it into a bin file then i can flash it

**Comment by wangxuanjie** [comment]
Thank you david 
It is very kind of you
The problem is sloved

**Comment by yangang123** [comment]
Hlleo every!

  1.  git clone https://github.com/PX4/Firmware.git
  2. cd Firmware
      git submodule update --init --recursive
      cd ..
  3. cd Firmware
      make px4nucleoF767ZI-v1_default
  4. Download the file "./build_px4nucleoF767ZI-v1_default/src/firmware/nuttx/firmware_nuttx.bin" to 
       address 0x8000 0000
 
  Note:  Don't need a bootloader for px4nucleoF767ZI-v1_default firmware 。

**Comment by davids5** [comment]
Just a heads up. Since the HW does not have any FMU peripherals onboard and has a limited pinout.  This platform is depreciated and is for reference only.   While it will build not a features may work.

**Comment by yangang123** [comment]
david： 
    Thank you for your reply.

**Comment by yangang123** [comment]
hi david:
-------------------------------------------------
"FMUv5.x (ARM Cortex M7, future Pixhawk)" 
-------------------------------------------------
 FMUv5 Board When to release?

**Comment by q490116910** [comment]
hi david:

"FMUv5.x (ARM Cortex M7, future Pixhawk)"

FMUv5 Board When to release?



I want to know it also~

**Pull request merged**
