### PR TITLE
WIP: Cessna gazebo

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by tumbili** [comment]
This is currently blocked due to strange imu data from the simulator. The acceleromater data is terribly noisy and jumping all over the place. It leads to bad attitude estimation and thus the plane can't be flown in any non manual modes.

**Comment by mhkabir** [comment]
@tumbili @LorenzMeier 
So I've been doing simulation of some rather *non-standard* vehicles in Gazebo, and integrated it with PX4 SITL, and I can reproduce this bad inertial data too. 

The attitude estimate becomes complete garbage due to the accelerometer going crazy.
screenshot from 2016-01-03 16 18 49

Is there any diagnosed root-cause of this? I had a theory that the IMU is colliding with the model, but that seems to not be the case. 
And an unrelated question, is there any way to get direct attitude ground truth from Gazebo and bypass the attitude estimators ?

**Comment by LorenzMeier** [comment]
Yes it is. Can you file a new issue for ground-truth attitude? I should have added that a long time ago, since its rather simple.

**Comment by mhkabir** [comment]
@LorenzMeier done, #3424

**Comment by LorenzMeier** [comment]
Superseded.

**Pull request closed without merging**
