### PR TITLE
MC pos control refactoring

### PR DESCRIPTION
**Pull request by Stifael**
changed the code such that it uses matrix library instead of mathlib library vectors

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@Stifael @julianoes Needs rebase and CI fixing. @julianoes I think it will be smart to bring in https://github.com/PX4/Firmware/pull/6020 first, then rebase this on top - but I'm open to either order and you might want to try which approach is faster / easier.

**Comment by julianoes** [comment]
#6020 doesn't conflict, does it?

**Comment by LorenzMeier** [comment]
No, it should not conflict. First step here is a rebase and build fix.

**Comment by Stifael** [comment]
I checked if the change to matrix has any effect. so far all I know it the following:
quaternion to DCM has no effect and vice versa
euler to DCM has no effect
In principle they should be the same, but for instance from DCM to euler is differently computed. 

I think the only way to make sure that everything works is by 1.) testing  and 2.) go through the math in the position controller and make sure that all transformation are done correctly. If not, then the math should be changed and not the library

**Comment by LorenzMeier** [comment]
Can you rebase this on master and coordinate with all the other ongoing refactor efforts?

**Comment by dagar** [comment]
If you wanted to save some space.

    using matrix::Vector3f;
    using matrix::Eulerf;
    etc

**Comment by Stifael** [comment]
Since I decided now to.write tests first and then start shrinking and changing the code, I will close this and reopen once it can be ensured through unit tests that nothing breaks

**Comment by dagar** [comment]
Very good idea!

**Pull request closed without merging**
