### PR TITLE
fw att control: cleanup, create base class for ECL

### PR DESCRIPTION
**Pull request by thomasgubler**
Adding a new base class to remove a lot of boilerplate code, no
functionality changes

Tested in HIL. Flighttesting still required.

### CODE REVIEW

**Comment by sjwilks** [comment]
Happy to help flighttest this on a wing next week.

**Comment by LorenzMeier** [comment]
Nice!

**Comment by sjwilks** [comment]
I'll test this on a FW tomorrow afternoon.

**Comment by thomasgubler** [comment]
Tested with @sjwilks , merging

**Comment by thomasgubler** [comment]
merged via cherry-pick

**Pull request closed without merging**
