### PR TITLE
Update submodule ecl to latest

### PR DESCRIPTION
**Pull request by dagar**
Update submodule ecl to latest Thu Jan 31 14:56:03 UTC 2019

    - ecl in PX4/Firmware (2b4fe9a): PX4/ecl@721f5e6
    - ecl current upstream: PX4/ecl@dd58e69
    - Changes: PX4/ecl@721f5e6...dd58e69

	dd58e69 2019-01-30 Paul Riseborough - EKF: Ensure FW yaw alignment method is used on first in-air reset
	3accab1 2019-01-28 Paul Riseborough - EKF: protect declination fusion from badly conditioned earth field estimates
	7bddbd1 2019-01-28 Paul Riseborough - EKF: Update cleaned up autocode fragment with sign error fix and missing LD
	fe378fd 2019-01-22 Paul Riseborough - EKF: Prevent unwanted declination fusion when re-starting 3-axis fusion
	bd1647a 2019-01-22 Paul Riseborough - EKF: Rework use of fuseDeclination()
	d52f536 2019-01-17 Paul Riseborough - EKF: Save mag field covariance data before reset
	82ce7a8 2019-01-17 Paul Riseborough - EKF: Save mag field covariance information on startup
	708c79e 2019-01-17 Paul Riseborough - EKF: Ensure mag field state covariance data is always available for re-use
	8839e4e 2019-01-17 Paul Riseborough - EKF: Don't discard declination certainty information when resuming 3-axis fusion.
	25148e1 2019-01-17 Paul Riseborough - EKF: Prevent rapid changes in declination estimate after a reset
	6e7c119 2019-01-16 CarlOlsson - EKF: limit yaw variance increase to 0.01 rad^2 to prevent a badly conditioned covariance matrix
	0896f7b 2019-01-16 CarlOlsson - EKF: Also fill in lower part of covariance matrix in increaseQuatYawErrVariance()
	4b3140e 2019-01-16 Paul Riseborough - EKF: Fix rebase error
	911d4d8 2019-01-16 Paul Riseborough - EKF: Fix sign error in increaseQuatYawErrVariance function
	a0b9cb0 2018-12-24 Paul Riseborough - EKF: Use consistent method for recording completion of in-flight yaw alignment
	ef5a87c 2018-12-21 Paul Riseborough - EKF: Rework quaternion yaw reset.
	fc2a089 2018-12-21 Paul Riseborough - EKF: Add function to un-correlate quaternion states
	bce1b96 2018-12-21 Paul Riseborough - EKF: Add function enabling yaw variance to be increased
	bf1f3a2 2018-12-21 Paul Riseborough - EKF: Derive equations enabling yaw variance to be increased
	81eabc1 2019-01-29 Daniel Agar - Jenkins update all containers to latest tag 2019-01-28
	a5e6191 2019-01-29 Daniel Agar - EKF add clarity brackets to avoid potential confusion

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@RomanBapst Good to merge?

**Comment by dagar** [comment]
We're accumulating quite a few ECL changes. Have all of these been tested with Firmware independently? 

image

**Comment by priseborough** [comment]
Not all of them have. The majority of untested changes are non-functional. The one remaining that could change behaviour is a one line bug fix  https://github.com/PX4/ecl/pull/549 which was causing the  incorrect  parameter value to be used to set initial yaw uncertainty after a reset.

The collection of these changes is large enough that flight testing is warranted. Because four of the functional changes affect the way that magnetometer data is used to set the yaw angle and/or variances.  I would like to see a test where a multi-rotor takes off adjacent a bar magnet positioned to cause a significant (>45 degree) change in the magnetic yaw so that the in-flight yaw reset functionality is fully exercised.

**Comment by dagar** [comment]
Thanks for the update @priseborough 

@PX4/testflights could you please put this PR through the regular set of MC and FW flight cards? In addition we'll need to do a special test with a multicopter described below.

> I would like to see a test where a multi-rotor takes off adjacent a bar magnet positioned to cause a significant (>45 degree) change in the magnetic yaw so that the in-flight yaw reset functionality is fully exercised.

**Comment by dannyfpv** [comment]
tested on pixhawk v4 pro
mc#1=https://review.px4.io/plot_app?log=caf0ba69-a20e-4fea-a0cf-2b0c58876577
mc#2=https://review.px4.io/plot_app?log=b3d55dec-fea6-47b0-9a70-693ce035031d
mc#3=https://review.px4.io/plot_app?log=b50c34a6-d583-497c-8f81-6f86b96c7dd1

**Comment by dagar** [comment]
@PX4/testflights were you able to try the magnet experiment?

> 
> @PX4/testflights could you please put this PR through the regular set of MC and FW flight cards? In addition we'll need to do a special test with a multicopter described below.
> 
> > I would like to see a test where a multi-rotor takes off adjacent a bar magnet positioned to cause a significant (>45 degree) change in the magnetic yaw so that the in-flight yaw reset functionality is fully exercised.

**Comment by Avysuarez** [comment]
Tested on pixhawk 4 and pixhawk 2.1
Good flights, no issues.
pixhawk 2.1
https://review.px4.io/plot_app?log=d42dec9a-a666-4909-a11c-b682170e4eaf
pixhawk4
https://review.px4.io/plot_app?log=1de24eb2-342b-4b6f-ab66-a357dd119ba2

**Comment by dannyfpv** [comment]
tested on pixhawk v4 pro
https://review.px4.io/plot_app?log=a572f8ca-64ea-409b-aff4-7bc8e1cd6d9d

**Comment by CarlOlsson** [comment]
Just a heads up that this should not be merged until [this](https://github.com/PX4/ecl/issues/554) is fixed in ECL

Here is the earth magnetic field states variances from the pixhawk v4 pro linked above
image

**Comment by dagar** [comment]
Thanks @CarlOlsson

**Comment by dagar** [comment]
Waiting for https://github.com/PX4/ecl/issues/554

**Comment by dagar** [comment]
Updated again to contain https://github.com/PX4/ecl/pull/556
Here are the total changes. https://github.com/PX4/ecl/compare/721f5e61a5965a08a34b2875d2bdc0b5d3b80601...dd58e695494acab73fb6fcec7074291edb5c226b

**Comment by dagar** [comment]
@PX4/testflights could you please test this branch updated PR?

**Comment by dannyfpv** [comment]
Tested on Pixhawk4 v5, good flights, no issues  
https://review.px4.io/plot_app?log=1a4c79f9-3da5-4d51-9123-406a184edb91

**Comment by priseborough** [comment]
Unable to test due to https://github.com/PX4/Firmware/pull/11353 breaking build for px4_fmu targets on Ubuntu 16.04 with toolchain installed using latest scripts.

**Comment by priseborough** [comment]
> Tested on Pixhawk4 v5, good flights, no issues.
> https://review.px4.io/plot_app?log=1a4c79f9-3da5-4d51-9123-406a184edb91
> 
> Pixhawk racer v4 good flights, no issues.
> https://review.px4.io/plot_app?log=73c815ab-0730-4226-8578-8dc732b14548
> 
> Pixhawk mini v5 good flights, no issues.
> https://review.px4.io/plot_app?log=60f07f7e-e47d-4403-b32d-93f6503e71e8
> 
> Pixhawk v4 pro, communication to link sik radio lost = rtl, installed the stable firmware version and the flight was good.
> https://review.px4.io/plot_app?log=338da11e-a233-49ca-8f64-4c7864bccf4d
> image

Data from these flights looks OK.

**Pull request merged**
