### PR TITLE
Bosch sensor driver integration

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Testing status:

  * Tested ok on Pixracer
  * Tested ok on FMUv5 with BMI055
  * Tested ok on Boschracer

**Comment by LorenzMeier** [comment]
@PX4TestFlights Please test on Pixracer.

**Comment by LorenzMeier** [comment]
@dagar @davids5  Interested to review?

**Comment by davids5** [comment]
@LorenzMeier Most all my commnet were incorporated on the initial PR.  I can have a second look in the AM, but do not wait for me if the others bess it first.

**Pull request merged**
