### PR TITLE
Throttle trim

### PR DESCRIPTION
**Pull request by LorenzMeier**
This add support for trimming the throttle value - helpful for gas planes.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Enjoy!

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Do you want to test this?

**Comment by DonLakeFlyer** [comment]
Tried running this branch and TRIM_THROTTLE isn't coming across in the initial parameter set?

**Comment by LorenzMeier** [comment]
Not sure we need this. Will retain the branch but close the PR.

**Pull request closed without merging**
