### PR TITLE
better PWM_MIN defaults for 250 airframes

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by kd0aij** [comment]
@tumbili Did you test this on a Spedix S250?

**Comment by tumbili** [comment]
@kd0aij I did test it on my QAV250. It was unflyable.

**Comment by kd0aij** [comment]
Interesting. Are you using the stock Lumenier ESCs?

**Comment by kd0aij** [comment]
This is confusing, though. I just checked my QAV250 and S250, and both have PWM_MIN=1075, although recent logs for the QAV show a min of 980. Looks like my parameters are changing unexpectedly, but that's not surprising given how frequently I reflash and the prevalence of "automatic" behavior.

**Pull request merged**
