### PR TITLE
Updating simulator to mavlink 2.0

### PR DESCRIPTION
**Pull request by catch-twenty-two**
This pull request cleans up and, updates the simulator to mavlink 2.0.  Disregard the name of the branch.  I was confused about the naming conventions for the mavlink releases.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! Still needs fixes for packet counters. Also SITL CI failed (which is testing the simulator interface).

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by catch-twenty-two** [comment]
I'll have to look into automatic detection of mavlink 1, it looks like the sim ignores the switch when it is talking to a mavlink 1 device on the other side of the connection.

**Comment by catch-twenty-two** [comment]
Fixed!

**Comment by catch-twenty-two** [comment]
Nevermind, I see what you are talking about.  Ill take a look.

**Comment by LorenzMeier** [comment]
Closing for now per our discussion.

**Comment by mhkabir** [comment]
@LorenzMeier What was the conclusion from the discussion? It would be nice to have jMAVSim working with Mavlink 2 in order to properly test the new geotag stuff.

**Pull request closed without merging**
