### PR TITLE
snapdragon disable power module

### PR DESCRIPTION
**Pull request by ChristophTobler**
currently doesn't work on all boards... Until there's a fix, I'll just disable it.

fixes https://github.com/PX4/Firmware/issues/8756

FYI @santiago3dr

### CODE REVIEW

**Comment by ChristophTobler** [comment]
issue to fix it https://github.com/PX4/Firmware/issues/8805

**Comment by dagar** [comment]
Another intermittent ROS mission test failure (with no log). @lamping7 FYI
http://ci.px4.io:8080/blue/organizations/jenkins/Firmware/detail/PR-8804/1/pipeline/

Restarting.

**Comment by dagar** [comment]
Do you need to disable any failsafes or battery reporting?

**Comment by lamping7** [comment]
@dagar Looks like a fluke. From what I can see there was an issue with Gazebo spawning the model. Something caused this:
`terminate called after throwing an instance of 'std::bad_weak_ptr'  what():  bad_weak_ptr`
 -- killing Gazebo. Which caused the model not to spawn, which triggered ROS to shutdown.

**Comment by ChristophTobler** [comment]
@dagar not that I know of. Pre-flight checks were never enabled on the Snapdragon.

**Comment by LorenzMeier** [comment]
Are we spawning the models differently in CI? Reason I ask is that the Tools/run_sitl.sh script has smarts to make sure stuff is launched in order.

**Comment by dagar** [comment]
> Are we spawning the models differently in CI? 

Yes, it's different.

mavros_posix_test_mission.test -> mavros_posix_sitl.launch -> posix_sitl.launch
 - start px4 sitl binary with args
 - start gazebo_ros

https://github.com/PX4/Firmware/blob/master/launch/posix_sitl.launch#L24-L37

**Pull request merged**
