### PR TITLE
Added matrice 100 vehicle.

### PR DESCRIPTION
**Pull request by jgoppert**

### CODE REVIEW

**Comment by jgoppert** [comment]
@dagar @julianoes @LorenzMeier 

Any mac users that can test this? It uses the jinja2 python modules, so I want to make sure you guys have it and it works on your system.

```bash
make posix_sitl_default gazebo_matrice_100
```

**Comment by dagar** [comment]
I barely use my mac, so it should be close to a clean install.

I had to `pip install jinja2 rospkg` to get your branch working.

**Comment by jgoppert** [comment]
@dagar Thanks for testing!

Is everyone ok with those deps, we could just add to the installation instructions. The rospkg dep we could get rid of if we want. It is so that the jinja template for the gazebo model can call rospkg.find_packge() if you want to pull in models from other ros descriptions.

**Comment by LorenzMeier** [comment]
So looking at this what will happen is that anyone having a working setup will have SITL stop working on him, right? What is the value that Jinja is adding? Less boilerplate?

**Comment by jgoppert** [comment]
Yes, jinja reduces boilerplate. It will break sitl for users who don't have those packages, but will give a  python import error that should be fairly straightforward.  Right now all of our sitl gazebo files are copy and paste hacks of the iris from rotors, this isn't maintainable. I assessed options such as erb, xacro, but I found Jinja to be the most powerful and easy to use.

**Comment by LorenzMeier** [comment]
Do we know if one of there generators is already widely used?

**Comment by jgoppert** [comment]
Currently erb is the most widely used in the gazebo_models repo here:
https://bitbucket.org/osrf/gazebo_models

erb doesn't seem to have a good way of creating a macro though, you can see
the equivalent of a macro here:
https://bitbucket.org/osrf/gazebo_models/src/ae948cd0b5518a394ce12825fd36e7560ba56867/submarine_sinking/model.sdf.erb?at=default&fileviewer=file-view-default#model.sdf.erb-57

Xacro is used by some ros packages such as rotors, but doesn't have for
loops.

jinja hasn't been used to generate sdf models before, but is what I used
since it has the most capabilities and has a large user base similar to erb.

Here is a comparison of erb and jinja:
http://vschart.com/compare/jinja/vs/erb-template-system

**Comment by LorenzMeier** [comment]
Jenkins add to whitelist.

**Comment by jgoppert** [comment]
I think this warrants thinking about in the future, as the current gazebo models are a maintenance nightmare, but we need some more input from the community on which template system to use.

**Comment by jgoppert** [comment]
I'll close this for now and leave the branch up.

**Pull request closed without merging**
