### PR TITLE
WIP: S.BUS parsing fix

### PR DESCRIPTION
**Pull request by LorenzMeier**
So far only better reporting. Will get a fixed decoder.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@pkocmoud Please upload your logic traces and reference them here. I will track the progress of that effort here.

**Comment by LorenzMeier** [comment]
More failure: http://logs.uaventure.com/view/AVsebbotTJZdZrHBkyfQDJ#RC_Raw_PLOT

**Comment by mhkabir** [comment]
@kd0aij This looks like your RC glitches.

**Comment by kd0aij** [comment]
yes, Taranis Plus mode D16 and Frsky X6R

**Comment by kd0aij** [comment]
X4RSB sbus logic traces; transmitter on and off
https://copy.com/hziryGRNf0iuUFRt

**Comment by LorenzMeier** [comment]
Thanks Mark!

**Comment by kd0aij** [comment]
new 5 second capture at https://copy.com/V4CuxE6CtQDVlcRX (frsky_sbus_txoff.scana) 
Definitely covers multiple glitches of the QGC Radio Cal display, but no problems apparent using the UART decoder.
@LorenzMeier is the last commit a bugfix? I was running a recent master build for this capture

**Pull request closed without merging**
