### PR TITLE
commander accel calibration: Use pre-rotated topic in board frame

### PR DESCRIPTION
**Pull request by LorenzMeier**
@AndreasAntener This is untested, but should fix your issue. @DonLakeFlyer in case you want to include this in your testing - this now really uses the board rotation param, whereas the individual sensor topics don't.

### CODE REVIEW

**Comment by AndreasAntener** [comment]
@LorenzMeier Thanks! Mag and Gyro looks good. But it looks like the AP crashes on accel calibration now.

**Comment by DonLakeFlyer** [comment]
> But it looks like the AP crashes on accel calibration now.

AP = ?

**Comment by DonLakeFlyer** [comment]
FYI: I'm not quite sure what this pull means with respect to any possible changes needed in QGC?

**Comment by AndreasAntener** [comment]
@DonLakeFlyer with AP I mean autopilot. This doesn't need any changes in QGC (at leas I don't think so). The firmware now simply reports the orientation with regard to the autopilot orientation setting.

So at the moment, mag and gyro calibration work fine, but when I hit accel calib I loose the connection to the autopilot, so I assume it locks-up (tested on a FMUv1)

**Comment by AndreasAntener** [comment]
Also on the v2:
```
telem> [cal] Assertion failed at file:armv7-m/up_hardfault.c line: 184 task: Idle Task
sp:     20008bd0
IRQ stack:
  base: 20008c1c
  size: 000005d8
20008bc0: 080c0fd2 20008bd0 200092cc 0809242f 080c1098 000000b8 0808c25d 00000010
20008be0: 20006958 00000003 00000000 080926b9 080926a5 0809efdf 20008c60 0809bea1
20008c00: 00000010 1000f6a4 1000f530 00000000 00000000 08092629 20008b8c 00000000
sp:     20008b9c
User stack:
  base: 200092cc
  size: 000003e8
R0: 20008c60 0809bea1 00000010 1000f6a4 0809a37d 080a0439 00000011 00000010
R8: 20006958 00000011 0808e387 080c0fed 1000f530 0808e373 00000000 00000000
xPSR: 08092629 BASEPRI: 00000010 CONTROL: 00000000
EXC_RETURN: 20008bc4
```

**Comment by tumbili** [comment]
The calibration routine crashes here https://github.com/PX4/Firmware/blob/cal_orientation_fix/src/modules/commander/calibration_routines.cpp#L461
And this is what the terminal sys:
teAssertion failed at file:armv7-m/up_hardfault.c line: 184 task: Idle Task
sp:     20008bd0
IRQ stack:
  base: 20008c1c
  size: 000005d8
20008bc0: 080c1282 20008bd0 200092cc 080926cf 080c1348 000000b8 0808c4fd 00000010
20008be0: 20006958 00000003 00000000 08092959 08092945 0809e57f 2001ffe0 0809c1a9
20008c00: 000000b0 08000b03 08000b01 08000b01 08000b01 080928c9 2001ff0c 00000000
sp:     2001ffe0
User stack:
  base: 200092cc
  size: 000003e8
R0: 0000002c 2001ff98 20020000 08000abd 08000b03 08000b01 08000b01 08000b01
R8: 08000b01 00000000 00000000 00000000 20004bd0 2001ffe0 00000000 00000000
xPSR: 4000000b BASEPRI: 000000b0 CONTROL: 00000000
EXC_RETURN: fffffff1

**Comment by tumbili** [comment]
I think it's a memory issue. If I run the routine with no code the system does not crash. If I declare a sensor_combined struct inside it without any other code it also crashes.

**Comment by tumbili** [comment]
@AndreasAntener Increased the stack size of the commander low prio thread. Seems to work now.

**Comment by LorenzMeier** [comment]
Applied, thanks!

**Pull request closed without merging**
