### PR TITLE
Improve new logger update rate

### PR DESCRIPTION
**Pull request by bkueng**
As @kd0aij noticed, the new logger dropped every ~4th sample of the sensor_combined, even though the logger update rate was high enough.

I noticed, under NuttX with the default rate of 285Hz, the actual measured rate was only 200Hz while on Linux it was ~280Hz. The reason is that NuttX only uses a usleep() granularity of 1ms, so that the typical sleep time is longer than what we set.

Now the logger waits on a semaphore, which gets activated periodically with a hrt timer. With this the measured rate is exactly the expected one, 285Hz.

Thanks @kd0aij, and @davids5 for the hrt timer tip.

This is a time difference plot of sensor_combined, before:
rate_default_logged_everything_sess014

And after:
rate_default_logged_everything_hrt_timer

Another irregularity is that some samples have a slightly higher time difference (4800 instead of 4000). This does not come from the logger, but somewhere else. Should be analyzed as well.

@julianoes can you test this on Snappy & possibly RPi, before and after? I instrumented with:
```
	int counter = 0;
	hrt_abstime time_start_hz = hrt_absolute_time();
```
before the logger main loop, and inside:
```
		hrt_abstime elapsed_hz = hrt_elapsed_time(&time_start_hz);
		if (elapsed_hz > 1e6) {
			time_start_hz = hrt_absolute_time();
			PX4_WARN("hz=%.3f", (double)counter / (elapsed_hz / 1.e6));
			counter = 0;
		}
		++counter;
```

### CODE REVIEW

**Comment by kd0aij** [comment]
Was this issue ever investigated?
"Another irregularity is that some samples have a slightly higher time difference (4800 instead of 4000). This does not come from the logger, but somewhere else. Should be analyzed as well."

**Comment by bkueng** [comment]
Yes, @julianoes found this: https://github.com/PX4/Firmware/blob/master/src/drivers/mpu9250/mpu9250.cpp#L91, and the driver runs at 1kHz, which explains the 4800.

**Comment by kd0aij** [comment]
thanks, I wouldn't have expected that kind of implementation

**Comment by bkueng** [comment]
Me neither. Feel free to improve it!

**Pull request merged**
