### PR TITLE
Update submodule sitl_gazebo to latest Mon Jun 10 00:39:33 UTC 2019

### PR DESCRIPTION
**Pull request by dagar**
- sitl_gazebo in PX4/Firmware (b0176dc88aecd22363f771bfe62dafa57a6a194a): https://github.com/PX4/sitl_gazebo/commit/a0b0eb8df12b11e8f63d3cc766dee97cefa32ab7
    - sitl_gazebo current upstream: https://github.com/PX4/sitl_gazebo/commit/af00ac4dfc5cfb25140254c5cae2a225944fc1c1
    - Changes: https://github.com/PX4/sitl_gazebo/compare/a0b0eb8df12b11e8f63d3cc766dee97cefa32ab7...af00ac4dfc5cfb25140254c5cae2a225944fc1c1

af00ac4 2019-06-07 Lukas Woodtli - Add support for unit tests on macOS
3a81838 2019-06-04 Lukas Woodtli - Add support to build and run unit tests with catkin
c59d214 2019-05-11 Lukas Woodtli - Add unit tests for gps plugin
860e1ce 2018-09-20 Lukas Woodtli - Add unit tests for gimbal controller plugin

### CODE REVIEW

**Comment by jkflying** [comment]
This PR breaks `make px4_sitl gazebo` for me, with the message
```
CMake Error at CMakeLists.txt:55 (add_subdirectory):
  The source directory

    /home/julian/Firmware/Tools/sitl_gazebo/external/OpticalFlow

  does not contain a CMakeLists.txt file.
```

Which make sense, since the directory is empty :wink:

**Comment by julianoes** [comment]
@jkflying even if you do?
```
git submodule update --init --recursive
```

**Comment by jkflying** [comment]
:man_facepalming: Sorry, missed the `--recursive` somehow

**Comment by dagar** [comment]
You can also try `make submodulesclean` or `make distclean` to get them in order.

**Comment by jkflying** [comment]
That's actually how I got into this, `make distclean` didn't seem the do the `--recursive`, or at least the automatic checkout didn't afterwards when I did a `make px4_sitl gazebo`

**Comment by dagar** [comment]
That deinits the submodules, then when building cmake should reinit only the ones in that particular config. Sounds like we're missing a recursive somewhere.

https://github.com/PX4/Firmware/blob/1ebf5d04d9e1bae142ac3c502e3832e88b793f85/cmake/px4_git.cmake#L77

**Pull request merged**
