### PR TITLE
snapdragon cmake cleanup

### PR DESCRIPTION
**Pull request by dagar**
General build system cleanup for snapdragon that can go in after https://github.com/PX4/Firmware/pull/9467 and https://github.com/PX4/Firmware/pull/9493.

This reduces the numerous snapdragon configs and variants to something a bit more maintainable (20 configs -> 4). It also simplifies the actual px4 binary build, making it consistent with a regular linux build + muorb (less cmake magic).

TODO
 - test
 - do we keep eagle_legacy?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I would keep `qurt_excelsior_default.cmake` as well, as we will push for a major update there shortly.

**Comment by dagar** [comment]
Ok I'll readd it. Anything we keep will have a corresponding build in CI. 

As a side note the binaries built within px4-dev-snapdragon don't seem to work on real hardware. If we can find the problem there Jenkins will be able to start testing real hardware.

**Comment by dagar** [comment]
Rebase and merge after https://github.com/PX4/Firmware/pull/9503

**Comment by dagar** [comment]
I've restored the excelsior target. It's currently identical to eagle, but with a different define.

**Comment by RomanBapst** [comment]
@dagar On excelsior I get a ton of undefined symbols for libpx4muorb_skel.so
I think it's missing, muorb_adsp, uorb, driverframework and the pthread lib.
I'll see if I can fix it.

**Comment by RomanBapst** [comment]
@dagar I was able to resolve the missing symbols and adjusted some other relevant stuff, mostly related to different file path on excelsior.
Will test this tomorrow on eagle and excelsior so that we can bring it in.

**Comment by RomanBapst** [comment]
@dagar I'm struggling with this. I still get tons of undefined symbols on the qurt side.
I think we should avoid such massive changes that mix config cleanup with fundamental build system changes. The qurt build system is already quite a mystery itself.
In case you want to invest some time to fix it, this is the current output:
```
[08500/03]  01:18.683  10a5:undefined PLT  symbol #1188 sem_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.690  10a5:undefined PLT  symbol #866 sem_getvalue in libpx4.so  0354  symbol.c
[08500/03]  01:18.691  10a5:undefined PLT  symbol #1467 pthread_condattr_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.700  10a5:undefined PLT  symbol #119 pthread_cond_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.707  10a5:undefined PLT  symbol #864 pthread_mutexattr_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.780  10a5:undefined PLT  symbol #1385 pthread_mutexattr_settype in libpx4.so  0354  symbol.c
[08500/03]  01:18.780  10a5:undefined PLT  symbol #583 pthread_mutex_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.781  10a5:undefined PLT  symbol #891 pthread_cond_timedwait in libpx4.so  0354  symbol.c
[08500/03]  01:18.781  10a5:undefined PLT  symbol #933 pthread_cond_wait in libpx4.so  0354  symbol.c
[08500/03]  01:18.781  10a5:undefined PLT  symbol #256 pthread_cond_signal in libpx4.so  0354  symbol.c
[08500/03]  01:18.781  10a5:undefined PLT  symbol #1107 clock_gettime in libpx4.so  0354  symbol.c
[08500/03]  01:18.782  10a5:undefined PLT  symbol #171 cfsetspeed in libpx4.so  0354  symbol.c
[08500/03]  01:18.782  10a5:undefined PLT  symbol #227 _FDclass in libpx4.so  0354  symbol.c
[08500/03]  01:18.782  10a5:undefined PLT  symbol #585 pthread_attr_getschedparam in libpx4.so  0354  symbol.c
[08500/03]  01:18.782  10a5:undefined PLT  symbol #847 pthread_attr_getstacksize in libpx4.so  0354  symbol.c
[08500/03]  01:18.783  10a5:undefined PLT  symbol #992 pthread_attr_setschedparam in libpx4.so  0354  symbol.c
[08500/03]  01:18.783  10a5:undefined PLT  symbol #851 pthread_self in libpx4.so  0354  symbol.c
[08500/03]  01:18.783  10a5:undefined PLT  symbol #1221 pthread_exit in libpx4.so  0354  symbol.c
[08500/03]  01:18.783  10a5:undefined PLT  symbol #194 pthread_cancel in libpx4.so  0354  symbol.c
[08500/03]  01:18.783  10a5:undefined PLT  symbol #150 pthread_kill in libpx4.so  0354  symbol.c
[08500/03]  01:18.785  10a5:dlopen failed, libpx4muorb_skel.so  0727  rtld.c
[08500/03]  01:18.785  10a5:undefined PLT  symbol #796 ioctl in libpx4.so  0354  symbol.c
[08500/03]  01:18.785  10a5:undefined PLT  symbol #710 sem_destroy in libpx4.so  0354  symbol.c
[08500/03]  01:18.785  10a5:undefined PLT  symbol #1188 sem_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.785  10a5:undefined PLT  symbol #866 sem_getvalue in libpx4.so  0354  symbol.c
[08500/03]  01:18.785  10a5:undefined PLT  symbol #1467 pthread_condattr_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.785  10a5:undefined PLT  symbol #119 pthread_cond_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.785  10a5:undefined PLT  symbol #864 pthread_mutexattr_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.785  10a5:undefined PLT  symbol #1385 pthread_mutexattr_settype in libpx4.so  0354  symbol.c
[08500/03]  01:18.785  10a5:undefined PLT  symbol #583 pthread_mutex_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.785  10a5:undefined PLT  symbol #891 pthread_cond_timedwait in libpx4.so  0354  symbol.c
[08500/03]  01:18.786  10a5:undefined PLT  symbol #933 pthread_cond_wait in libpx4.so  0354  symbol.c
[08500/03]  01:18.786  10a5:undefined PLT  symbol #256 pthread_cond_signal in libpx4.so  0354  symbol.c
[08500/03]  01:18.786  10a5:undefined PLT  symbol #1107 clock_gettime in libpx4.so  0354  symbol.c
[08500/03]  01:18.786  10a5:undefined PLT  symbol #171 cfsetspeed in libpx4.so  0354  symbol.c
[08500/03]  01:18.786  10a5:undefined PLT  symbol #227 _FDclass in libpx4.so  0354  symbol.c
[08500/03]  01:18.787  10a5:undefined PLT  symbol #585 pthread_attr_getschedparam in libpx4.so  0354  symbol.c
[08500/03]  01:18.787  10a5:undefined PLT  symbol #847 pthread_attr_getstacksize in libpx4.so  0354  symbol.c
[08500/03]  01:18.787  10a5:undefined PLT  symbol #992 pthread_attr_setschedparam in libpx4.so  0354  symbol.c
[08500/03]  01:18.787  10a5:undefined PLT  symbol #851 pthread_self in libpx4.so  0354  symbol.c
[08500/03]  01:18.787  10a5:undefined PLT  symbol #1221 pthread_exit in libpx4.so  0354  symbol.c
[08500/03]  01:18.788  10a5:undefined PLT  symbol #194 pthread_cancel in libpx4.so  0354  symbol.c
[08500/03]  01:18.788  10a5:undefined PLT  symbol #150 pthread_kill in libpx4.so  0354  symbol.c
[08500/03]  01:18.788  10a5:dlopen failed, libpx4muorb_skel.so  0727  rtld.c
[08500/02]  01:18.796  9b:uimg not supported  0527  map_object.c
[08500/02]  01:18.806  109d:uimg not supported  0527  map_object.c
[08500/03]  01:18.875  10a5:undefined PLT  symbol #1114 usleep in libpx4.so  0354  symbol.c
[08500/03]  01:18.875  10a5:undefined PLT  symbol #515 sem_wait in libpx4.so  0354  symbol.c
[08500/03]  01:18.876  10a5:undefined PLT  symbol #896 sem_post in libpx4.so  0354  symbol.c
[08500/03]  01:18.876  10a5:undefined PLT  symbol #317 __hexagon_sqrtf in libpx4.so  0354  symbol.c
[08500/03]  01:18.876  10a5:undefined PLT  symbol #880 pthread_mutex_unlock in libpx4.so  0354  symbol.c
[08500/03]  01:18.876  10a5:undefined PLT  symbol #968 pthread_mutex_lock in libpx4.so  0354  symbol.c
[08500/03]  01:18.877  10a5:undefined PLT  symbol #825 pthread_attr_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.877  10a5:undefined PLT  symbol #1159 pthread_attr_setstacksize in libpx4.so  0354  symbol.c
[08500/03]  01:18.877  10a5:undefined PLT  symbol #630 pthread_create in libpx4.so  0354  symbol.c
[08500/03]  01:18.877  10a5:undefined PLT  symbol #1437 pthread_attr_destroy in libpx4.so  0354  symbol.c
[08500/03]  01:18.877  10a5:undefined PLT  symbol #708 pthread_join in libpx4.so  0354  symbol.c
[08500/03]  01:18.878  10a5:undefined PLT  symbol #1335 tcgetattr in libpx4.so  0354  symbol.c
[08500/03]  01:18.878  10a5:undefined PLT  symbol #879 cfsetispeed in libpx4.so  0354  symbol.c
[08500/03]  01:18.878  10a5:undefined PLT  symbol #1322 cfsetospeed in libpx4.so  0354  symbol.c
[08500/03]  01:18.878  10a5:undefined PLT  symbol #245 tcsetattr in libpx4.so  0354  symbol.c
[08500/03]  01:18.878  10a5:undefined PLT  symbol #813 fsync in libpx4.so  0354  symbol.c
[08500/03]  01:18.880  10a5:undefined PLT  symbol #796 ioctl in libpx4.so  0354  symbol.c
[08500/03]  01:18.880  10a5:undefined PLT  symbol #710 sem_destroy in libpx4.so  0354  symbol.c
[08500/03]  01:18.880  10a5:undefined PLT  symbol #1188 sem_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.880  10a5:undefined PLT  symbol #866 sem_getvalue in libpx4.so  0354  symbol.c
[08500/03]  01:18.880  10a5:undefined PLT  symbol #1467 pthread_condattr_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.880  10a5:undefined PLT  symbol #119 pthread_cond_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.880  10a5:undefined PLT  symbol #864 pthread_mutexattr_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.880  10a5:undefined PLT  symbol #1385 pthread_mutexattr_settype in libpx4.so  0354  symbol.c
[08500/03]  01:18.880  10a5:undefined PLT  symbol #583 pthread_mutex_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.880  10a5:undefined PLT  symbol #891 pthread_cond_timedwait in libpx4.so  0354  symbol.c
[08500/03]  01:18.881  10a5:undefined PLT  symbol #933 pthread_cond_wait in libpx4.so  0354  symbol.c
[08500/03]  01:18.881  10a5:undefined PLT  symbol #256 pthread_cond_signal in libpx4.so  0354  symbol.c
[08500/03]  01:18.881  10a5:undefined PLT  symbol #1107 clock_gettime in libpx4.so  0354  symbol.c
[08500/03]  01:18.881  10a5:undefined PLT  symbol #171 cfsetspeed in libpx4.so  0354  symbol.c
[08500/03]  01:18.881  10a5:undefined PLT  symbol #227 _FDclass in libpx4.so  0354  symbol.c
[08500/03]  01:18.882  10a5:undefined PLT  symbol #585 pthread_attr_getschedparam in libpx4.so  0354  symbol.c
[08500/03]  01:18.882  10a5:undefined PLT  symbol #847 pthread_attr_getstacksize in libpx4.so  0354  symbol.c
[08500/03]  01:18.882  10a5:undefined PLT  symbol #992 pthread_attr_setschedparam in libpx4.so  0354  symbol.c
[08500/03]  01:18.882  10a5:undefined PLT  symbol #851 pthread_self in libpx4.so  0354  symbol.c
[08500/03]  01:18.882  10a5:undefined PLT  symbol #1221 pthread_exit in libpx4.so  0354  symbol.c
[08500/03]  01:18.882  10a5:undefined PLT  symbol #194 pthread_cancel in libpx4.so  0354  symbol.c
[08500/03]  01:18.883  10a5:undefined PLT  symbol #150 pthread_kill in libpx4.so  0354  symbol.c
[08500/03]  01:18.883  10a5:dlopen failed, libpx4muorb_skel.so  0727  rtld.c
[08500/02]  01:18.895  a0:uimg not supported  0527  map_object.c
[08500/02]  01:18.905  209f:uimg not supported  0527  map_object.c
[08500/03]  01:18.982  209d:undefined PLT  symbol #1114 usleep in libpx4.so  0354  symbol.c
[08500/03]  01:18.983  209d:undefined PLT  symbol #515 sem_wait in libpx4.so  0354  symbol.c
[08500/03]  01:18.983  209d:undefined PLT  symbol #896 sem_post in libpx4.so  0354  symbol.c
[08500/03]  01:18.983  209d:undefined PLT  symbol #317 __hexagon_sqrtf in libpx4.so  0354  symbol.c
[08500/03]  01:18.985  209d:undefined PLT  symbol #880 pthread_mutex_unlock in libpx4.so  0354  symbol.c
[08500/03]  01:18.985  209d:undefined PLT  symbol #968 pthread_mutex_lock in libpx4.so  0354  symbol.c
[08500/03]  01:18.985  209d:undefined PLT  symbol #825 pthread_attr_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.985  209d:undefined PLT  symbol #1159 pthread_attr_setstacksize in libpx4.so  0354  symbol.c
[08500/03]  01:18.985  209d:undefined PLT  symbol #630 pthread_create in libpx4.so  0354  symbol.c
[08500/03]  01:18.985  209d:undefined PLT  symbol #1437 pthread_attr_destroy in libpx4.so  0354  symbol.c
[08500/03]  01:18.985  209d:undefined PLT  symbol #708 pthread_join in libpx4.so  0354  symbol.c
[08500/03]  01:18.985  209d:undefined PLT  symbol #1335 tcgetattr in libpx4.so  0354  symbol.c
[08500/03]  01:18.985  209d:undefined PLT  symbol #879 cfsetispeed in libpx4.so  0354  symbol.c
[08500/03]  01:18.986  209d:undefined PLT  symbol #1322 cfsetospeed in libpx4.so  0354  symbol.c
[08500/03]  01:18.986  209d:undefined PLT  symbol #245 tcsetattr in libpx4.so  0354  symbol.c
[08500/03]  01:18.986  209d:undefined PLT  symbol #813 fsync in libpx4.so  0354  symbol.c
[08500/03]  01:18.986  209d:undefined PLT  symbol #796 ioctl in libpx4.so  0354  symbol.c
[08500/03]  01:18.986  209d:undefined PLT  symbol #710 sem_destroy in libpx4.so  0354  symbol.c
[08500/03]  01:18.987  209d:undefined PLT  symbol #1188 sem_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.987  209d:undefined PLT  symbol #866 sem_getvalue in libpx4.so  0354  symbol.c
[08500/03]  01:18.987  209d:undefined PLT  symbol #1467 pthread_condattr_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.987  209d:undefined PLT  symbol #119 pthread_cond_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.987  209d:undefined PLT  symbol #864 pthread_mutexattr_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.988  209d:undefined PLT  symbol #1385 pthread_mutexattr_settype in libpx4.so  0354  symbol.c
[08500/03]  01:18.988  209d:undefined PLT  symbol #583 pthread_mutex_init in libpx4.so  0354  symbol.c
[08500/03]  01:18.988  209d:undefined PLT  symbol #891 pthread_cond_timedwait in libpx4.so  0354  symbol.c
[08500/03]  01:18.988  209d:undefined PLT  symbol #933 pthread_cond_wait in libpx4.so  0354  symbol.c
[08500/03]  01:18.988  209d:undefined PLT  symbol #256 pthread_cond_signal in libpx4.so  0354  symbol.c
[08500/03]  01:18.990  209d:undefined PLT  symbol #1107 clock_gettime in libpx4.so  0354  symbol.c
[08500/03]  01:18.990  209d:undefined PLT  symbol #171 cfsetspeed in libpx4.so  0354  symbol.c
[08500/03]  01:18.990  209d:undefined PLT  symbol #227 _FDclass in libpx4.so  0354  symbol.c
[08500/03]  01:18.990  209d:undefined PLT  symbol #585 pthread_attr_getschedparam in libpx4.so  0354  symbol.c
[08500/03]  01:18.990  209d:undefined PLT  symbol #847 pthread_attr_getstacksize in libpx4.so  0354  symbol.c
[08500/03]  01:18.990  209d:undefined PLT  symbol #992 pthread_attr_setschedparam in libpx4.so  0354  symbol.c
[08500/03]  01:18.990  209d:undefined PLT  symbol #851 pthread_self in libpx4.so  0354  symbol.c
[08500/03]  01:18.990  209d:undefined PLT  symbol #1221 pthread_exit in libpx4.so  0354  symbol.c
[08500/03]  01:18.990  209d:undefined PLT  symbol #194 pthread_cancel in libpx4.so  0354  symbol.c
[08500/03]  01:18.990  209d:undefined PLT  symbol #150 pthread_kill in libpx4.so  0354  symbol.c
[08500/03]  01:18.991  209d:dlopen failed, libpx4muorb_skel.so  0727  rtld.c
[08500/02]  01:18.996  10a1:uimg not supported  0527  map_object.c
[08500/02]  01:19.005  309f:uimg not supported  0527  map_object.c
[08500/03]  01:19.083  209c:undefined PLT  symbol #1114 usleep in libpx4.so  0354  symbol.c
[08500/03]  01:19.083  209c:undefined PLT  symbol #515 sem_wait in libpx4.so  0354  symbol.c
[08500/03]  01:19.083  209c:undefined PLT  symbol #896 sem_post in libpx4.so  0354  symbol.c
[08500/03]  01:19.083  209c:undefined PLT  symbol #317 __hexagon_sqrtf in libpx4.so  0354  symbol.c
[08500/03]  01:19.085  209c:undefined PLT  symbol #880 pthread_mutex_unlock in libpx4.so  0354  symbol.c
[08500/03]  01:19.085  209c:undefined PLT  symbol #968 pthread_mutex_lock in libpx4.so  0354  symbol.c
[08500/03]  01:19.085  209c:undefined PLT  symbol #825 pthread_attr_init in libpx4.so  0354  symbol.c
[08500/03]  01:19.085  209c:undefined PLT  symbol #1159 pthread_attr_setstacksize in libpx4.so  0354  symbol.c
[08500/03]  01:19.085  209c:undefined PLT  symbol #630 pthread_create in libpx4.so  0354  symbol.c
[08500/03]  01:19.085  209c:undefined PLT  symbol #1437 pthread_attr_destroy in libpx4.so  0354  symbol.c
[08500/03]  01:19.085  209c:undefined PLT  symbol #708 pthread_join in libpx4.so  0354  symbol.c
[08500/03]  01:19.085  209c:undefined PLT  symbol #1335 tcgetattr in libpx4.so  0354  symbol.c
[08500/03]  01:19.086  209c:undefined PLT  symbol #879 cfsetispeed in libpx4.so  0354  symbol.c
[08500/03]  01:19.086  209c:undefined PLT  symbol #1322 cfsetospeed in libpx4.so  0354  symbol.c
[08500/03]  01:19.086  209c:undefined PLT  symbol #245 tcsetattr in libpx4.so  0354  symbol.c
[08500/03]  01:19.086  209c:undefined PLT  symbol #813 fsync in libpx4.so  0354  symbol.c
[08500/03]  01:19.086  209c:undefined PLT  symbol #796 ioctl in libpx4.so  0354  symbol.c
[08500/03]  01:19.086  209c:undefined PLT  symbol #710 sem_destroy in libpx4.so  0354  symbol.c
[08500/03]  01:19.087  209c:undefined PLT  symbol #1188 sem_init in libpx4.so  0354  symbol.c
[08500/03]  01:19.087  209c:undefined PLT  symbol #866 sem_getvalue in libpx4.so  0354  symbol.c
[08500/03]  01:19.087  209c:undefined PLT  symbol #1467 pthread_condattr_init in libpx4.so  0354  symbol.c
[08500/03]  01:19.087  209c:undefined PLT  symbol #119 pthread_cond_init in libpx4.so  0354  symbol.c
[08500/03]  01:19.087  209c:undefined PLT  symbol #864 pthread_mutexattr_init in libpx4.so  0354  symbol.c
[08500/03]  01:19.088  209c:undefined PLT  symbol #1385 pthread_mutexattr_settype in libpx4.so  0354  symbol.c
[08500/03]  01:19.088  209c:undefined PLT  symbol #583 pthread_mutex_init in libpx4.so  0354  symbol.c
[08500/03]  01:19.088  209c:undefined PLT  symbol #891 pthread_cond_timedwait in libpx4.so  0354  symbol.c
[08500/03]  01:19.088  209c:undefined PLT  symbol #933 pthread_cond_wait in libpx4.so  0354  symbol.c
[08500/03]  01:19.088  209c:undefined PLT  symbol #256 pthread_cond_signal in libpx4.so  0354  symbol.c
[08500/03]  01:19.090  209c:undefined PLT  symbol #1107 clock_gettime in libpx4.so  0354  symbol.c
[08500/03]  01:19.090  209c:undefined PLT  symbol #171 cfsetspeed in libpx4.so  0354  symbol.c
[08500/03]  01:19.090  209c:undefined PLT  symbol #227 _FDclass in libpx4.so  0354  symbol.c
[08500/03]  01:19.090  209c:undefined PLT  symbol #585 pthread_attr_getschedparam in libpx4.so  0354  symbol.c
[08500/03]  01:19.090  209c:undefined PLT  symbol #847 pthread_attr_getstacksize in libpx4.so  0354  symbol.c
[08500/03]  01:19.090  209c:undefined PLT  symbol #992 pthread_attr_setschedparam in libpx4.so  0354  symbol.c
[08500/03]  01:19.090  209c:undefined PLT  symbol #851 pthread_self in libpx4.so  0354  symbol.c
[08500/03]  01:19.090  209c:undefined PLT  symbol #1221 pthread_exit in libpx4.so  0354  symbol.c
[08500/03]  01:19.090  209c:undefined PLT  symbol #194 pthread_cancel in libpx4.so  0354  symbol.c
[08500/03]  01:19.090  209c:undefined PLT  symbol #150 pthread_kill in libpx4.so  0354  symbol.c
[08500/03]  01:19.091  209c:dlopen failed, libpx4muorb_skel.so  0727  rtld.c
[08500/02]  01:20.907  99:uimg not supported  0527  map_object.c
[08500/02]  01:20.916  109a:uimg not supported  0527  map_object.c
[08500/03]  01:20.992  409f:undefined PLT  symbol #1114 usleep in libpx4.so  0354  symbol.c
[08500/03]  01:20.992  409f:undefined PLT  symbol #515 sem_wait in libpx4.so  0354  symbol.c
[08500/03]  01:20.992  409f:undefined PLT  symbol #896 sem_post in libpx4.so  0354  symbol.c
[08500/03]  01:20.992  409f:undefined PLT  symbol #317 __hexagon_sqrtf in libpx4.so  0354  symbol.c
[08500/03]  01:20.993  409f:undefined PLT  symbol #880 pthread_mutex_unlock in libpx4.so  0354  symbol.c
[08500/03]  01:20.993  409f:undefined PLT  symbol #968 pthread_mutex_lock in libpx4.so  0354  symbol.c
[08500/03]  01:20.993  409f:undefined PLT  symbol #825 pthread_attr_init in libpx4.so  0354  symbol.c
[08500/03]  01:20.995  409f:undefined PLT  symbol #1159 pthread_attr_setstacksize in libpx4.so  0354  symbol.c
[08500/03]  01:20.995  409f:undefined PLT  symbol #630 pthread_create in libpx4.so  0354  symbol.c
[08500/03]  01:20.995  409f:undefined PLT  symbol #1437 pthread_attr_destroy in libpx4.so  0354  symbol.c
[08500/03]  01:20.995  409f:undefined PLT  symbol #708 pthread_join in libpx4.so  0354  symbol.c
[08500/03]  01:20.995  409f:undefined PLT  symbol #1335 tcgetattr in libpx4.so  0354  symbol.c
[08500/03]  01:20.995  409f:undefined PLT  symbol #879 cfsetispeed in libpx4.so  0354  symbol.c
[08500/03]  01:20.995  409f:undefined PLT  symbol #1322 cfsetospeed in libpx4.so  0354  symbol.c
[08500/03]  01:20.995  409f:undefined PLT  symbol #245 tcsetattr in libpx4.so  0354  symbol.c
[08500/03]  01:20.995  409f:undefined PLT  symbol #813 fsync in libpx4.so  0354  symbol.c
[08500/03]  01:20.995  409f:undefined PLT  symbol #796 ioctl in libpx4.so  0354  symbol.c
[08500/03]  01:20.996  409f:undefined PLT  symbol #710 sem_destroy in libpx4.so  0354  symbol.c
[08500/03]  01:20.996  409f:undefined PLT  symbol #1188 sem_init in libpx4.so  0354  symbol.c
[08500/03]  01:20.996  409f:undefined PLT  symbol #866 sem_getvalue in libpx4.so  0354  symbol.c
[08500/03]  01:20.996  409f:undefined PLT  symbol #1467 pthread_condattr_init in libpx4.so  0354  symbol.c
[08500/03]  01:20.996  409f:undefined PLT  symbol #119 pthread_cond_init in libpx4.so  0354  symbol.c
[08500/03]  01:20.997  409f:undefined PLT  symbol #864 pthread_mutexattr_init in libpx4.so  0354  symbol.c
[08500/03]  01:20.997  409f:undefined PLT  symbol #1385 pthread_mutexattr_settype in libpx4.so  0354  symbol.c
[08500/03]  01:20.997  409f:undefined PLT  symbol #583 pthread_mutex_init in libpx4.so  0354  symbol.c
[08500/03]  01:20.997  409f:undefined PLT  symbol #891 pthread_cond_timedwait in libpx4.so  0354  symbol.c
[08500/03]  01:20.997  409f:undefined PLT  symbol #933 pthread_cond_wait in libpx4.so  0354  symbol.c
[08500/03]  01:20.998  409f:undefined PLT  symbol #256 pthread_cond_signal in libpx4.so  0354  symbol.c
[08500/03]  01:20.998  409f:undefined PLT  symbol #1107 clock_gettime in libpx4.so  0354  symbol.c
[08500/03]  01:20.998  409f:undefined PLT  symbol #171 cfsetspeed in libpx4.so  0354  symbol.c
[08500/03]  01:20.998  409f:undefined PLT  symbol #227 _FDclass in libpx4.so  0354  symbol.c
[08500/03]  01:20.998  409f:undefined PLT  symbol #585 pthread_attr_getschedparam in libpx4.so  0354  symbol.c
[08500/03]  01:21.000  409f:undefined PLT  symbol #847 pthread_attr_getstacksize in libpx4.so  0354  symbol.c
[08500/03]  01:21.000  409f:undefined PLT  symbol #992 pthread_attr_setschedparam in libpx4.so  0354  symbol.c
[08500/03]  01:21.000  409f:undefined PLT  symbol #851 pthread_self in libpx4.so  0354  symbol.c
[08500/03]  01:21.000  409f:undefined PLT  symbol #1221 pthread_exit in libpx4.so  0354  symbol.c
[08500/03]  01:21.000  409f:undefined PLT  symbol #194 pthread_cancel in libpx4.so  0354  symbol.c
[08500/03]  01:21.000  409f:undefined PLT  symbol #150 pthread_kill in libpx4.so  0354  symbol.c
[08500/03]  01:21.000  409f:dlopen failed, libpx4muorb_skel.so  0727  rtld.c
[08500/03]  01:37.805  failed to enqueue msg 2997 3004 3 4020200 980004000 8192  0079  fastrpc_port.c
[08500/03]  01:37.805  failed to enqueue msg 2997 3004 e6e10160 1000000 00000000 4096  0079  fastrpc_port.c
[08500/03]  01:37.806  failed to enqueue msg 2997 3004 e6e10160 1000000 00000000 4096  0079  fastrpc_port.c
[08500/03]  01:37.807  failed to enqueue msg 2997 3004 e6e10160 1000000 00000000 4096  0079  fastrpc_port.c
[08500/03]  01:37.808  failed to enqueue msg 2997 3004 e6e10160 1000000 00000000 4096  0079  fastrpc_port.c

```

**Comment by LorenzMeier** [comment]
@RomanBapst I think we should untangle it and rather fix 820 independent of a build system rework.

**Comment by dagar** [comment]
> @dagar I'm struggling with this. I still get tons of undefined symbols on the qurt side.
> I think we should avoid such massive changes that mix config cleanup with fundamental build system 

Generally I'd agree, but this was too confusing to handle.

I need to get a working excelsior docker container.

**Pull request closed without merging**
