### PR TITLE
mission: add heading towards ROI mode for multicopters

### PR DESCRIPTION
**Pull request by ndepal**
This adds the functionality for a multicopter to face towards a ROI (set by `MAV_CMD_NAV_ROI` or `MAV_CMD_DO_SET_ROI`). Useful e.g. for vehicles with a camera that does not have a yaw gimbal.

Tested in SITL and on a PixRacer.

### CODE REVIEW

**Comment by dagar** [comment]
Looks right, but I'm wondering about the structure.

Currently commander handles vehicle commands CMD_NAV_ROI/CMD_DO_SET_ROI and then publishes the orb message vehicle_roi. Wouldn't it be simpler to handle that vehicle command directly in navigator, use the resulting vehicle_roi lat/lon, and publish vehicle_roi for vmount? I'd happily help gut this from commander.

Navigator already checks vehicle_commands, we'd only need to move
https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L1157-L1183
to
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/navigator_main.cpp#L531

**Comment by dagar** [comment]
If you agree and can easily verify I could do it quickly. The vehicle_roi handling seemed out of place and I wanted to move it as part of the commander rewrite. https://github.com/PX4/Firmware/pull/7517

**Comment by ndepal** [comment]
Thanks for the input, @dagar . I have no objections and I'm happy to test.

**Comment by dagar** [comment]
Untested PR here - https://github.com/ndepal/Firmware/pull/1

I need to verify some of the vehicle command acknowledgement.

**Comment by dagar** [comment]
Merged via rebase. https://github.com/PX4/Firmware/commit/a6ce2b320c8b92c19ff00ef85c461786f2bf0e14

**Pull request closed without merging**
