### PR TITLE
Increase max yawrate default parameters for standard delta VTOL

### PR DESCRIPTION
**Pull request by bresch**
MC_YAWRATE_MAX 20  => 50

Signed-off-by: bresch <brescianimathieu@gmail.com>

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I'm not sure we want this in. This can lead to wing twist, which in turn makes the control system unstable.

**Comment by bresch** [comment]
I'll do a new specific config file for the Flywings VTOL I have since I can increase the value much more without having significant wing twist. 
However, I still think that a value of 20 is really too low, you can't turn.

**Comment by LorenzMeier** [comment]
@bresch Can you please share a log? 20 degrees per second isn't nothing. Are you maybe experiencing a poorly tuned yaw rate controller and by increasing the target yaw rate you're increasing the error enough so it actually turns?

**Comment by bresch** [comment]
Here you have one:
http://logs.px4.io/plot_app?log=56d737ab-88eb-4ff0-96e1-f722b2276ff9

**Comment by LorenzMeier** [comment]
It is slow, but this a foam airplane config. As soon as you have some wing loading anything higher than 50 makes it unstable.

**Pull request merged**
