### PR TITLE
Param unit cleanup

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
@LorenzMeier @DonLakeFlyer ready for review please

Current @unit usage

      4  * @unit 1/s
      1  * @unit A
      1  * @unit bit/s
     44  * @unit boolean
     40  * @unit deg
      4  * @unit deg * 1e7
     19  * @unit deg/s
     54  * @unit enum
      1  * @unit Gauss
      1  * @unit Gauss/s
      1  * @unit hPa
      5  * @unit Hz
      1  * @unit kg
      3  * @unit kg*m^2
     47  * @unit m
      1  * @unit m^2
      1  * @unit mA
      1  * @unit min
      1  * @unit m/m
     12  * @unit ms
      1  * @unit m-s
     35  * @unit m/s
      2  * @unit (m/s)-s
     10  * @unit m/s/s
      1  * @unit (m/s/s)-s
      1  * @unit rad
      8  * @unit rad/s
     26  * @unit s
      7  * @unit SD
     66  * @unit us
      3  * @unit V
      1  * @unit W

**Comment by DonLakeFlyer** [comment]
I'd probably change the seconds ones to secs, msecs, usecs. A little more clear. What is SD?

**Comment by dagar** [comment]
It's in ekf2 so I left it alone. Standard deviation?
https://github.com/PX4/Firmware/blob/cecec86081566f243a0dec33b9dedc3dd1624f58/src/modules/ekf2/ekf2_params.c#L316

**Comment by dagar** [comment]
I used s, ms, us to stick to SI, but if you want the abbreviation I'll change them.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
