### PR TITLE
Couple of small fixes

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by erikd** [comment]
This is failing in Travis, but I can't see why.

**Comment by andre-nguyen** [comment]
Bad formatting, run ./Tools/fix_code_style.sh

**Comment by erikd** [comment]
Ah, thanks @andre-nguyen. Unfortunately, the newest version of astyle available in Debian is 2.04, and the `Tools/fix_code_style.sh` script seems to have a hard-coded requirement for 2.05.1. Is that really necessary?

**Comment by erikd** [comment]
Ok, the release notes ( http://astyle.sourceforge.net/notes.html ) suggest that 2.05.1 might be necessary.

**Comment by mhkabir** [comment]
www.github.com/PX4/astyle

**Comment by erikd** [comment]
Thanks @mhkabir , got it. Its still a bit of the pain in the neck 'cause there is no obvious documentation on how to build it. I had to go digging around in the source tree :-/ .

**Comment by erikd** [comment]
Just rebased it against the current `driver_framework` branch.

**Pull request closed without merging**
