### PR TITLE
shadow declaration issue.

### PR DESCRIPTION
**Pull request by shivam5594**
just changed variable external to externalL.

### CODE REVIEW

**Comment by dagar** [comment]
Where are you catching this? I'm wondering why the CI system isn't hitting it. We should have -Wshadow enabled everywhere. https://github.com/PX4/Firmware/blob/master/cmake/common/px4_base.cmake#L330

**Comment by shivam5594** [comment]
Just after cloning the repo, I tried make command and got python packages error. solved it hit make again. had to make distclean once, then after it flashed me this error. but yeah you have a point. it should consider this while building and I checked my px4_base.cmake has that line. It is untouched.

**Comment by dagar** [comment]
What's your build environment?

**Comment by dagar** [comment]
Which compiler version?

**Pull request merged**
