### PR TITLE
ported vtol module to posix

### PR DESCRIPTION
**Pull request by tumbili**
VTOL code now also runs on posix.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesome!

**Comment by LorenzMeier** [comment]
@tumbili Note the Travis failure. Did you register an account by now with Travis?

**Comment by LorenzMeier** [comment]
@tumbili You probably should rebase your VTOL work branch against this one. You might need to run the formatter there as well before rebasing.

**Comment by LorenzMeier** [comment]
@tumbili Shall we merge this?

**Comment by tumbili** [comment]
@LorenzMeier No, SITL is not behaving with this, the VTOL does not stabilize itself. Haven't found out the problem yet, need to check in the lab where SITL is running without issues.

**Comment by tumbili** [comment]
@LorenzMeier This has been tested in SITL, merging.

**Pull request merged**
