### PR TITLE
In progress

### PR DESCRIPTION
**Pull request by mcharleb**
@LorenzMeier This builds PX4 with the -fpic flag set and sets for now uses a dummy IDL file until the code can be refactored to use the muorb IDL file.

Includes fixes for unused variables found by clang.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
There are bits missing for NuttX in DriverFramework it seems: https://travis-ci.org/PX4/Firmware/jobs/101373177#L1243

**Comment by mcharleb** [comment]
It seems NuttX doesn't have the config option set for mutex types.

**Comment by LorenzMeier** [comment]
Do we need them or can we just factor them out? So change code or NuttX options?

**Comment by LorenzMeier** [comment]
Superseded by https://github.com/PX4/Firmware/pull/3484 which integrates these changes. Thanks!

**Pull request closed without merging**
