### PR TITLE
Basic uNode board support - review

### PR DESCRIPTION
**Pull request by crashmatt**
ADDS: makefiles, nuttx config and board drivers for uNode board
Adds early (not working) driver for MAX21100 6dof IMU sensor.

MODIFIES mtd.c and rcS
mtd.c support for W25 memory with extra fat partition simulating /fs/microsd
rcS modified to start mtd early if microsd start fails

RISKS: Biggest risks are in mtd.c code changes.  #define has been used to isolate original code from changes when W25 memory is not used.  This could be taken further if deemed necessary.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesome! Very much looking forward to have this board supported, and some photos / docs on the wiki would be great. In general it looks good, I would actually prefer a bit less BOARD config specific ifdefs (e.g. in the MTD driver) and rather conditional logic (e.g. command line options). I wouldn't be surprised if we want to adopt your flash memory approach at some point, and so I'd rather have flash vs. sdcard instead of FMU vs. uNode.

**Comment by crashmatt** [comment]
I will review how the defines are done. You might even want flash and sdcard.
The build tests failed so I need to find where that went wrong. Maybe I have specified a uNode board test that will fail.
I prefer to get basics running before I get distracted by presenting it to the forums.  I have yet to get a debugger working.

**Comment by crashmatt** [comment]
I will review how the defines are done. You might even want flash and sdcard.
The build tests failed so I need to find where that went wrong. Maybe I have specified a uNode board test that will fail.
I prefer to get basics running before I get distracted by presenting it to the forums.  I have yet to get a debugger working.

**Comment by crashmatt** [comment]
@LorenzMeier I checked the mtd code.  It doesn't use the board type definition at all.  It uses the memory type instead.  I didn't like doing it this way but it was the best I could think of at the time that didn't make wider reaching changes.
The only places I have used board dependent code is where that is used already.  One piece of code I should not have modified is px4io.c because that module should never be included with uNode anyway.  I will tidy this up.

**Pull request closed without merging**
