### PR TITLE
add unit test for Dcm.renormalize() in matrix submodule

### PR DESCRIPTION
**Pull request by kd0aij**
dependent on https://github.com/PX4/Matrix/pull/31

### CODE REVIEW

**Comment by kd0aij** [comment]
unit test is in matrix submodule

**Comment by dagar** [comment]
We can keep both. Within the PX4 tests command it can actually run on each platform (nuttx, qurt, posix, etc) built with the same compiler and options as flight code.

**Comment by kd0aij** [comment]
@dagar Any idea why the new test fails with clang? I built and tested locally with gcc 4.9.3

**Comment by dagar** [comment]
1: INFO  [tests] RUNNING TEST: dcmRenormTests
    1: ERROR [modules__unit_test] Assertion failed: test - err < eps (../src/systemcmds/tests/test_matrix.cpp:721)
    1: ERROR [tests] TEST FAILED: dcmRenormTests

It's xcode clang on OSX. Print the values to see what's going on?

Alternatively you could extend our unit_test framework with a few handy asserts that would also print the values in the event of a failure. https://github.com/PX4/Firmware/blob/master/src/modules/unit_test/unit_test.h#L133

assert_lt
assert_gt
assert_near
assert_float_eq
assert_double_eq

**Comment by kd0aij** [comment]
Interesting. With gcc 4.9.3 the renorm error prints as 0, but with clang it is > 3e-7. 
I increased eps from 1e-7 to 1e-6, but I'd think the results should be identical assuming both machines are using IEEE754 math.

**Comment by dagar** [comment]
Squash these into a single commit and merge?

**Comment by LorenzMeier** [comment]
@kd0aij Compilers do optimize math so differences are indeed possible and expected.

**Comment by kd0aij** [comment]
1e-6 is indeed the correct value for eps, since 1 lsb is about 1.2e-7

**Pull request merged**
