### PR TITLE
commander refactor: initial class structure

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This looks great!

**Comment by mrpollo** [comment]
@dagar did we discuss this on the past dev call? if not can we cover it on the next one? (Wednesday 19th)

**Comment by dagar** [comment]
No we didn't get to it. I'll be on a plane tomorrow during the dev call. This is only a tiny piece of the commander rewrite. My thought was to get smaller chunks like this reviewed, tested, and merged before moving onto the next.

**Comment by mrpollo** [comment]
Ok, I'm moving this to the next week dev call then, thanks, @dagar and good flight!

**Comment by LorenzMeier** [comment]
@PX4TestFlights Could you please test this?

**Comment by LorenzMeier** [comment]
@dagar Please tag and ping the test flights team for anything that is reasonably solid.

**Comment by Avysuarez** [comment]
flights with pixahawk 1(v3); Good flight, but rejects the mission
http://review.px4.io/plot_app?log=835144dc-b0d6-454f-ac8c-d0b70d6295fd
http://review.px4.io/plot_app?log=76c67419-b047-4f6f-9e0d-5c5b0f65667b

**Comment by dagar** [comment]
Thanks @Avysuarez. Could you expand on the mission rejection and what messages you saw? Did you create a new mission and upload it with QGC or did it try to use an existing mission? If you clicked sync in QGC did you get any messages?

**Comment by santiago3dr** [comment]
flight with pixracer (V4)
http://logs.px4.io/plot_app?log=9b146241-7989-4bf3-bd41-cc1d2f71f507

manual take-off; auto engaged; nice tracking; good hold; rc failsafe successful; battery warning alerted but battery failsafe did not kick in at expected battery level

**Comment by LorenzMeier** [comment]
@dagar Did you have a chance to look into a potential fix? Could you also please rebase?

**Comment by dagar** [comment]
Nasty rebase, standby.

**Comment by LorenzMeier** [comment]
@dagar Do you need additional support? Git merge squash?

**Comment by LorenzMeier** [comment]
@dagar How is the rebase for this looking?

**Comment by dagar** [comment]
Let's get https://github.com/PX4/Firmware/pull/7842, https://github.com/PX4/Firmware/pull/7764, and possibly https://github.com/PX4/Firmware/pull/7875 in, then do a single rebase, focused testing + any fixes, then finally merged this.

**Comment by dagar** [comment]
Moving ROI handling completely out of commander. https://github.com/PX4/Firmware/pull/7939

**Comment by dagar** [comment]
One more PR test/review (https://github.com/PX4/Firmware/pull/7764) then let's get this through!

**Comment by LorenzMeier** [comment]
I've merged the other PR, so we can continue now here.

**Comment by dagar** [comment]
Great! I'll likely only use this as a reference for improvements to pick off, but let's keep it open for now.

**Pull request closed without merging**
