### PR TITLE
WIP: commander re-evaluate RC mode switch when local position becomes valid

### PR DESCRIPTION
**Pull request by dagar**
@MaEtUgR I wanted to extend the RC mode switch re-evaluation logic for a multicopter with optical flow to enter position control mode as soon as possible on bootup.

Now that I look at this logic again I'm wondering if it should be limited to prevent forcing the re-evaluation in a failsafe scenario after position validity is regained.

### CODE REVIEW

**Comment by dagar** [comment]
One idea would be to limit it to when disarmed or landed.

**Comment by dagar** [comment]
@MaEtUgR thoughts on this one?

**Comment by julianoes** [comment]
@dagar still draft or good to go?

**Comment by mrpollo** [comment]
This came up during the October 9, 2019 dev call.

@MaEtUgR can you please drive this forward?

**Pull request merged**
