### PR TITLE
Pr 820 posix

### PR DESCRIPTION
**Pull request by RomanBapst**
Changes that were necessary to build PX4 for the posix side of the 820 board.
@dagar FYI

### CODE REVIEW

**Comment by RomanBapst** [comment]
@LorenzMeier It probably does not have the correct SDK yet.

**Comment by RomanBapst** [comment]
Current status:
I can build for both posix and qurt and upload it via
```
make excelsior_default upload
```

Both linux and qurt side start fine but a while after the first topic from the qurt side gets to the linux side (something like 20 seconds) I get the error
```
ERROR [muorb] ERROR: Getting Bulk data from fastRPC link
```
and I lose the connection to the dsp.

**Comment by dagar** [comment]
Do you know of any specific SDK version requirements?

Let's get the docker image working, including having CI create a PX4 package that actually works.

**Comment by RomanBapst** [comment]
Continued in #9494

**Pull request closed without merging**
