### PR TITLE
WIP: Nuttx sim target

### PR DESCRIPTION
**Pull request by jgoppert**
This is in response to #4632 to see if nuttx sim is now worthwhile to implement.

build target
```bash
make nuttx_sim_default
```

Current state after just stupidly copying px4fmu-v2 config to sim config, fails to compile with this error:

```bash
PX4 CONFIG: nuttx_sim_default
[10/375] Building C object src/platforms/common/CMakeFiles/platforms__common.dir/px4_getopt.c.obj
FAILED: /usr/bin/arm-none-eabi-gcc  -DCONFIG_ARCH_BOARD_SIM -D__DF_NUTTX -D__PX4_NUTTX -I../src -I. -Isrc -I../src/modules -I../src/include -I../src/lib -I../src/platforms -I../src/drivers/boards/sim -Isrc/modules/px4_messages -Isrc/modules -I../mavlink/include/mavlink -I../src/lib/DriverFramework/framework/include -I../src/lib/matrix -Isim/NuttX/nuttx-export/include -Isim/NuttX/nuttx-export/include/cxx -Isim/NuttX/nuttx-export/arch/chip -Isim/NuttX/nuttx-export/arch/common -Iexternal/Install/include -g -std=gnu99 -fno-common -Wall -Werror -Wextra -Wno-sign-compare -Wshadow -Wfloat-equal -Wpointer-arith -Wmissing-declarations -Wno-unused-parameter -Werror=format-security -Werror=array-bounds -Wfatal-errors -Werror=unused-variable -Werror=reorder -Werror=uninitialized -Werror=init-self -Werror=unused-but-set-variable -Wformat=1 -Wdouble-promotion -Werror=double-promotion -Wbad-function-cast -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wold-style-declaration -Wmissing-parameter-type -Os -fno-strict-aliasing -fomit-frame-pointer -funsafe-math-optimizations -ffunction-sections -fdata-sections -fno-strength-reduce -fno-builtin-printf -fvisibility=hidden -include visibility.h -nodefaultlibs -nostdlib -O2 -g -DNDEBUG   -Wframe-larger-than=1024 -MMD -MT src/platforms/common/CMakeFiles/platforms__common.dir/px4_getopt.c.obj -MF src/platforms/common/CMakeFiles/platforms__common.dir/px4_getopt.c.obj.d -o src/platforms/common/CMakeFiles/platforms__common.dir/px4_getopt.c.obj   -c ../src/platforms/common/px4_getopt.c
In file included from sim/NuttX/nuttx-export/include/pthread.h:51:0,
                 from sim/NuttX/nuttx-export/include/nuttx/sched.h:50,
                 from sim/NuttX/nuttx-export/include/sched.h:47,
                 from sim/NuttX/nuttx-export/include/stdio.h:47,
                 from ../src/platforms/common/px4_getopt.c:40:
sim/NuttX/nuttx-export/include/unistd.h:166:16: error: conflicting types for built-in function 'execl' [-Werror]
 EXTERN int     execl(FAR const char *path, ...);
                ^
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
[10/375] Building C object src/modules/px4iofirmware/CMakeFiles/px4io-v2.dir/__/__/drivers/stm32/drv_io_timer.c.obj
ninja: build stopped: subcommand failed.
Makefile:142: recipe for target 'nuttx_sim_default' failed
make: *** [nuttx_sim_default] Error 1
```

### CODE REVIEW

**Comment by jgoppert** [comment]
New build error after rebase on nuttx_v3

```bash
[48/502] Building CXX object CMakeFiles/msg_gen.dir/topics_sources/att_pos_mocap.cpp.obj
FAILED: /usr/bin/arm-none-eabi-g++   -DBUILD_URI=localhost -DCONFIG_ARCH_BOARD_SIM -D__DF_NUTTX -D__PX4_NUTTX -I../src -I. -Isrc -I../src/modules -I../src/include -I../src/lib -I../src/platforms -I../src/drivers/boards/sim -Isrc/modules/px4_messages -Isrc/modules -I../mavlink/include/mavlink -I../src/lib/DriverFramework/framework/include -I../src/lib/matrix -Isim/NuttX/nuttx-export/include -Isim/NuttX/nuttx-export/include/cxx -Isim/NuttX/nuttx-export/arch/chip -Isim/NuttX/nuttx-export/arch/common -Isim/NuttX/nuttx-export/arch/armv7-m -Iexternal/Install/include -g -fno-exceptions -fno-rtti -std=gnu++0x -fno-threadsafe-statics -DCONFIG_WCHAR_BUILTIN -D__CUSTOM_FILE_IO__ -fcheck-new -Wall -Werror -Wextra -Wno-sign-compare -Wshadow -Wfloat-equal -Wpointer-arith -Wmissing-declarations -Wno-unused-parameter -Werror=format-security -Werror=array-bounds -Wfatal-errors -Werror=unused-variable -Werror=reorder -Werror=uninitialized -Werror=init-self -Werror=unused-but-set-variable -Wformat=1 -Wdouble-promotion -Werror=double-promotion -Wno-missing-field-initializers -Os -fno-strict-aliasing -fomit-frame-pointer -funsafe-math-optimizations -ffunction-sections -fdata-sections -fno-strength-reduce -fno-builtin-printf -fvisibility=hidden -include visibility.h -mcpu=cortex-m4 -mthumb -march=armv7e-m -mfpu=fpv4-sp-d16 -mfloat-abi=hard -nodefaultlibs -nostdlib -O2 -g -DNDEBUG -MMD -MT CMakeFiles/msg_gen.dir/topics_sources/att_pos_mocap.cpp.obj -MF CMakeFiles/msg_gen.dir/topics_sources/att_pos_mocap.cpp.obj.d -o CMakeFiles/msg_gen.dir/topics_sources/att_pos_mocap.cpp.obj -c topics_sources/att_pos_mocap.cpp
In file included from /usr/include/newlib/sys/reent.h:15:0,
                 from /usr/include/newlib/math.h:5,
                 from ../src/platforms/px4_defines.h:43,
                 from ../src/drivers/drv_orb_dev.h:43,
                 from topics_sources/att_pos_mocap.cpp:38:
/usr/include/newlib/sys/_types.h:76:5: error: 'wint_t' does not name a type
     wint_t __wch;
     ^
compilation terminated due to -Wfatal-errors.
ninja: build stopped: subcommand failed.
Makefile:142: recipe for target 'nuttx_sim_default' failed
make: *** [nuttx_sim_default] Error 1
```

**Comment by dagar** [comment]
This is interesting. How is it different than posix_sitl at this point?

**Comment by jgoppert** [comment]
It uses nuttx instead of posix, so closer to what we are running on the
hardware.

**Comment by LorenzMeier** [comment]
I'm closing this for now since we have POSIX and a lot of our future targets are Linux targets. We need someone to really drive this effort and I'm concerned that we don't have enough bandwidth. I'll leave the branch alive for now.

**Pull request closed without merging**
