### PR TITLE
New Look for jMAVSim

### PR DESCRIPTION
**Pull request by bkueng**
This brings the jMAVSim upgrade from https://github.com/PX4/jMAVSim/pull/62 with better textures and improved rendering settings:

jmavsim_new_texture1

@hamishwillee fyi

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @bkueng - looks cool. I'll update images in https://github.com/PX4/Devguide/issues/330

**Comment by LorenzMeier** [comment]
@bkueng @dagar CI mission tests are failing.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by bkueng** [comment]
Jenkins is using gazebo, right? It has been flaky for me several times lately.

**Comment by hamishwillee** [comment]
@bkueng Just ran `make posix jmavsim` off master. As you can see the sky texture is not displaying. Worse, when you fly up this makes the compass invisible, as it is white.


image

**Comment by LorenzMeier** [comment]
It worked for me on Mac OS.

**Comment by bkueng** [comment]
@hamishwillee the texture could be too large to fit into video memory. We can fallback to the other in that case. Do you see an error message, like `Error, could not load texture` on the console?

**Comment by hamishwillee** [comment]
Hi @bkueng, 

This is on a ubuntu VM running in windows ... so it is possible. I didn't get that error, but I did get some libEGL warnings ...
```
BUILD SUCCESSFUL
Total time: 0 seconds
Options parsed, starting Sim.
Starting GUI...
3D [dev] 1.6.0-pre12-daily-experimental daily

libEGL warning: bad surface attribute 0x3080
libEGL warning: bad surface attribute 0x3080
libEGL warning: bad surface attribute 0x3080
libEGL warning: bad surface attribute 0x3080
Init MAVLink
INFO  [simulator] Got initial simulation data, running sim..
INFO  [pwm_out_sim] MODE_8PWM
INFO  [tone_alarm] startup
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14556 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14557 remote port 14540
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
INFO  [logger] logger started (mode=all)
INFO  [logger] log root dir created: rootfs/fs/microsd/log
pxh> INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2017-10-31/22_41_20.ulg
INFO  [lib__ecl] EKF aligned, (pressure height, IMU buf: 15, OBS buf: 14)
WARN  [lib__ecl] EKF stopping navigation
```

**Comment by MaEtUgR** [comment]
> sky texture is not displaying
Sorry to say: I have the exact same problem in my VMWare Ubuntu 16.04 setup.
white sky

**Comment by MaEtUgR** [comment]
I use a VMWare graphics library workaround: `export SVGA_VGPU10=0` because otherwise gazebo doesn't start. I just tried to set the flag to 1 but this makes everything worse: I get error messages on simulator start, almost the entire picture is white and java even crashes shortly after without any user input.

**Comment by hamishwillee** [comment]
Time for a proper issue. Created above as #8229

**Pull request merged**
