### PR TITLE
Control state

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by tumbili** [comment]
@yyassa I added the last missing piece and tested this in SITL. Merging after the checks have passed.

**Comment by jgoppert** [comment]
This merge broke SITL for me. Still trying to debug, attitude estimator goes unstable on launch and won't give throttle.

**Comment by jgoppert** [comment]
I'm looking at the patch now, was this intended:
```bash
-	_att.rollspeed = _LP_att_P.apply(_ekf->dAngIMU.x / _ekf->dtIMU) - _ekf->states[10] / _ekf->dtIMUfilt;
-	_att.pitchspeed = _LP_att_Q.apply(_ekf->dAngIMU.y / _ekf->dtIMU) - _ekf->states[11] / _ekf->dtIMUfilt;
-	_att.yawspeed = _LP_att_R.apply(_ekf->dAngIMU.z / _ekf->dtIMU) - _ekf->states[12] / _ekf->dtIMUfilt;
+	_att.rollspeed = _ekf->dAngIMU.x / _ekf->dtIMU - _ekf->states[10] / _ekf->dtIMUfilt;
+	_att.pitchspeed = _ekf->dAngIMU.y / _ekf->dtIMU - _ekf->states[11] / _ekf->dtIMUfilt;
+	_att.yawspeed = _ekf->dAngIMU.z / _ekf->dtIMU - _ekf->states[12] / _ekf->dtIMUfilt;
 ```

It looks like you are removing the low pass filter. Is this because the controllers are suppose to be using control state now? What is the motivation of this patch, that the actual estimator states are not smooth enough for control? Or is it just for logging?

**Comment by yyassa** [comment]
The filters are removed here and added to the control state rates. The idea is to keep the attitude topic with the true estimate and use filtered rates only for controllers (from the control state). It should be only architectural, no functionality change..

If you provide logging, maybe I can try to help debugging.

@tumbili, you had reported sane behaviour in SITL, which estimator were you using?

**Pull request merged**
