### PR TITLE
New logger2 - ready to merge

### PR DESCRIPTION
**Pull request by bkueng**
This rebases newLogger2 on current master. Tested on SITL & pixracer.

Replaces #4365 

@julianoes or @tumbili can you test this on Snapdragon?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@julianoes If you test this you can go straight ahead and merge it.

**Comment by julianoes** [comment]
Will test later. What about jenkins?

**Comment by LorenzMeier** [comment]
@julianoes I'll merge once you have tested it.

**Comment by LorenzMeier** [comment]
@dagar I think its your new test which is failing here. Would you be interested to have a look?

**Comment by julianoes** [comment]
logger_on_snappy

Logger on Snappy is happy!

**Comment by dagar** [comment]
Rebased on master and fixed param_test.

**Comment by dagar** [comment]
@LorenzMeier are you aware we had to restore px4fmu-v2_lpe? Even without logger lpe no longer fits.

**Comment by davids5** [comment]
I may have bought us back ~5K see https://github.com/PX4/Firmware/pull/4537

**Comment by dagar** [comment]
Thanks @davids5 
I cherry-picked the nuttx change and re-enabled lpe.

    region `flash' overflowed by 2728 bytes

So close...

**Comment by davids5** [comment]
strings firmware_nuttx.bin

Anything we can shrink?

**Comment by NaterGator** [comment]
FW EKF v1 was a big offender. Has it been looked at?

**Comment by LorenzMeier** [comment]
Yes, but we can only strip it when EKF2 is up to the state of the art.

**Comment by LorenzMeier** [comment]
Rebased, applied, thanks everybody!

**Pull request closed without merging**
