### PR TITLE
WIP: Altitude message

### PR DESCRIPTION
**Pull request by AndreasAntener**
@LorenzMeier I implemented the new altitude message, primary interest is @tumbili 's terrain altitude :). Current state is working, but I don't know what should be used for the monotonic altitude. Any hints?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I would advise the pressure altitude for monotonic as an initial stopgap.

**Comment by LorenzMeier** [comment]
We can add that to the global pos topic btw. and copy it in by the estimator.

**Comment by AndreasAntener** [comment]
Sounds good. I added the field, should I leave it to the estimator specialists to fill it? I can add it directly from the sensors message but I guess this doesn't make sense.

**Comment by AndreasAntener** [comment]
@LorenzMeier I filled the fields in the estimators. EKF has a filtered pressure altitude, but LPE and INAV don't. Not sure if what I added there makes sense.

**Comment by LorenzMeier** [comment]
Don't forget to update the mavlink submodule and commit it 8)

**Comment by AndreasAntener** [comment]
Will do in a sec. What to you thing about the change for LPE and INAV in https://github.com/UAVenture/Firmware/commit/f40e5e6f031a65e1d1dc07cb5e41fb2d1f8eb493 ?

**Comment by AndreasAntener** [comment]
The still open question is if the direct pressure alt readout in LPE and INAV are ok as a stopgap. Otherwise I updated and tested it again with the new timestamp.

**Pull request merged**
