### PR TITLE
WIP: Ekf2 airspeed

### PR DESCRIPTION
**Pull request by tumbili**
This is the branch needed if you want to try out ekf2 on fixed wing.
It supports wind estimation using an airspeed sensor.

### CODE REVIEW

**Comment by tumbili** [comment]
Jenkins: test this please

**Comment by AndreasAntener** [comment]
Jenkins: test this please

**Comment by tumbili** [comment]
Jenkins: test this please

**Comment by tumbili** [comment]
Merged!

**Pull request merged**
