### PR TITLE
Write rosbags during SITL tests

### PR DESCRIPTION
**Pull request by AndreasAntener**
Adds rosbag for CI tests, writing PX4 `vehicle_local_position` where it makes sense.

@LorenzMeier did you have anything else in mind in addition to position?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Position / desired position and velocity?

**Comment by AndreasAntener** [comment]
Hm, setpoints.. In case of the MAVROS tests, we also have 2 levels, I can log position and setpoints at MAVROS or/and at PX4 level.

**Comment by AndreasAntener** [comment]
I guess I'll add a few more topics, and we'll see what we want to use then.

**Comment by AndreasAntener** [comment]
This logs the same px4 topics for different tests, and published MAVROS messages where it makes sense. Should be good to go.

**Comment by AndreasAntener** [comment]
So we have these topics:
px4/vehicle_attitude               
px4/vehicle_attitude_setpoint      
px4/vehicle_local_position         
px4/vehicle_local_position_setpoint

Plus where it makes sense:
mavros/setpoint/att_throttle
mavros/setpoint/attitude
px4/position_setpoint_triplet      
mavros/setpoint/local_position

**Comment by AndreasAntener** [comment]
Rebased

**Pull request merged**
