### PR TITLE
Add sbus driver for Linux based autopilot and fix errors of linux_pwm_out

### PR DESCRIPTION
**Pull request by crossa**
1.Add sbus driver for linux . This driver can be used to read the
inverted S.bus signal and fetch the data of each channel and publish it

2. Fix the bug of linux_pwm_out, when the protocol is pca9685,
after the init method is executed,the method of determining the return
value of init method is incorrect,this will cause the driver to fail

3. Add linux_sbus driver to other posix prefixes cmake file

### CODE REVIEW

**Comment by crossa** [comment]
@TSC21  Ok , now you can see the commit .

**Comment by crossa** [comment]
@TSC21   Here‘s the video.   Youtube is blocked by Great Fire Wall -_-!  So I published it on youku

http://v.youku.com/v_show/id_XMjk3Njg5ODEzMg==.html?spm=a2h3j.8428770.3416059.1

**Comment by TSC21** [comment]
I'm unable to see the video after opening the link.

**Comment by crossa** [comment]
@TSC21  https://youtu.be/wgkkp-SEo_4
Ok. Last month the corp asked my family to drink coffee just because I purchase the aircraft  6 months ago. -_-!

**Comment by TSC21** [comment]
The video does not load, even on youtube.

**Comment by crossa** [comment]
@TSC21 https://raw.githubusercontent.com/crossa/raspx4-sbus-rc-in/master/LinuxSbus.mp4

download it

**Comment by TSC21** [comment]
> @TSC21 https://raw.githubusercontent.com/crossa/raspx4-sbus-rc-in/master/LinuxSbus.mp4

Looks good. Thanks @crossa. For me is a go to merge.

**Comment by TSC21** [comment]
Apllied @crossa. Thanks

**Pull request merged**
