### PR TITLE
Enable ms5611 driver and fix build errors.

### PR DESCRIPTION
**Pull request by SimonWilks**
This fixes:
- what appears to be a path error in the sitl_run script (we need a non sitl script?)
- general compile errors
- converts errx to PX4_WARN
- fixes the find_bus() calls

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! There is a merge conflict with the branch you're trying to merge in. Did you coordinate with Roman?

**Comment by LorenzMeier** [comment]
Otherwise if this is the cleaned up version of that other PR please send it against master.

**Comment by SimonWilks** [comment]
@LorenzMeier yes, we've been looking at this together over the weekend and I set it up against his PR for visibility (despite the conflict) last night. It can be merged on its own but I'll wait for Roman to get back online first then we can decide how to proceed.

Should be resolved this morning.

**Comment by LorenzMeier** [comment]
ok - can we document the Raspian setup somewhere (if not already done?)

**Comment by SimonWilks** [comment]
I'm documenting as I go :) https://pixhawk.org/modules/linux/navio-raspberry


--
UAVenture AG
http://www.uaventure.com

**Comment by SimonWilks** [comment]
Closing in favor of #2711

**Pull request closed without merging**
