### PR TITLE
Vtol virtual attitude setpoint

### PR DESCRIPTION
**Pull request by tumbili**
This introduces virtual attitude setpoints for vtol:
The mc/fw control modules should publish on virtual attitude setpoint topics.
The vtol att control modules subscribes on these topics and will then publish on the real attitude setpoint topic. This moves the entire attitude setpoint logic into the vtol module and allows us to integrate tailsitters more conveniently (where we need to generate att setpoints for the transition).

Things we still need to look at:

1) The attitude setpoint generation should be removed out of the fw_att control module. At the moment it will use it's own attitude setpoint e.g. in manual mode.

2) At the moment the vtol module is driven by actuator controls from the attitude controllers. Maybe we should instead use attitude setpoints or both in separate loops.

3) The attitude transformation for tailsitters (90 degrees rotation) in the fw_att_control module should be removed. It's much cleaner to rotate the desired attitude in the vtol module.

### CODE REVIEW

**Comment by tumbili** [comment]
@LorenzMeier We should have a talk about this soon. Without this I will not be able to integrate the tailsitter work from @davidvor

**Comment by LorenzMeier** [comment]
Well as I said earlier it looks good. The key is to get this tested and verified and then move on. Its obvious by now that we need to fix simulation, you can't go out testing for every small code change.

**Comment by LorenzMeier** [comment]
And please fix Travis, as always..

**Comment by tumbili** [comment]
This is bench tested in manual mode for mc and fw.

Log:
http://logs.uaventure.com/view/2V7WBAoujGKscJ6XX2Xtxn

**Comment by tumbili** [comment]
Closing in favour of #3090

**Pull request closed without merging**
