### PR TITLE
uavcan : start before sensors

### PR DESCRIPTION
**Pull request by mhkabir**
Allows uavcan interfaced sensors (e.g mag) to work as primary.

This probably needs to go into release as well if we want a proper UAVCAN setup running on it.

Tested.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This will register the UAVCAN sensors even when not present, correct? In that case we would need a different approach.

**Comment by mhkabir** [comment]
@LorenzMeier yes. 
I think we need a better approach in general, for selecting a particular sensor as default.

**Comment by LorenzMeier** [comment]
@mhkabir We have that approach already, I just forgot. There is a priority argument in orb_advertise_multi(). We just need to make sure UAVCAN has the max priority. Then the sensors app needs to cycle through the publications for all sensors every second or so and check if there is now one with higher priority. That would make it completely independent of boot timing.

**Comment by LorenzMeier** [comment]
@mhkabir I'll close this. I would appreciate if you could look into using the orb priority (https://github.com/PX4/Firmware/blob/master/src/modules/uORB/uORB.h#L331-L341) in the sensors app to select which sensor to use as primary. This will fix the ordering for good, and will allow us to launch uavcan by default and after the normal sensors.

**Pull request closed without merging**
