### PR TITLE
[WIP] Posix sitl ci

### PR DESCRIPTION
**Pull request by dagar**
See #3149

### CODE REVIEW

**Comment by dagar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fGLn4TaK&#x2F;722-px4-testing"> PX4 testing</a>

**Comment by LorenzMeier** [comment]
Where is this standing?

**Comment by dagar** [comment]
I've been dragging my feet getting the container stuff working locally. If anyone is in a position to finish this off now, please don't let me get in the way.

Do we currently have the ability to script a mission and check the success? I'm looking forward to having lots of automated testing. Could logmuncher handle the load if we had each test mission upload?

**Comment by AndreasAntener** [comment]
@dagar @LorenzMeier I cleaned up the whole POSIX-ROS launch files which can be used as standalone ROS wrappers now, and also cleaned out the old direct tests which are not necessary really. This is now running nicely locally.

I haven't removed/cleaned out the old ROS launch files for the multiplatform SITL. Although I'd like to actually, but I see stuff there that I don't know, like multi-uav support. It's just a bit confusing now, I will update at least the ROS interfacing docs.

**Comment by AndreasAntener** [comment]
If Travis is happy I'm going to merge this so I can switch Jenkins over to these tests.

**Comment by AndreasAntener** [comment]
@dagar Log Muncher upload and mission checks are now todos on the general issue for this, I'll probably add separate issues for that later.

Mission checking: basically we just need a script to upload a mission via mavlink and then run it. We already have a Dronekit test that needs to be integrated as well. But I would suggest to also do a mission test without Dronekit. If we can wrap this in Python tests under ROS, everything to check and report is already available.

**Comment by AndreasAntener** [comment]
Jenkins: test this please

**Comment by AndreasAntener** [comment]
Jenkins: test this please

**Comment by AndreasAntener** [comment]
Yay, SITL tests running!

**Pull request merged**
