### PR TITLE
Master serial break

### PR DESCRIPTION
**Pull request by davids5**
This backports Enabled Support BSD compatible breaks on stm32 U[S]ART from upstream Nuttx
which adesses https://github.com/PX4/NuttX/pull/72#issuecomment-218725226

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I'm going to let this rot a bit until I understand the risk involved in updating this - since we don't actually use this in any system / product I'm aware of.

**Comment by LorenzMeier** [comment]
@davids5 Can you rebase on master? Then we can test and get it in.

**Comment by LorenzMeier** [comment]
Needs config against new NuttX.

**Comment by davids5** [comment]
@LorenzMeier - this is in all the board configs it should be in on PX4/Firmware master.

**Pull request closed without merging**
