### PR TITLE
debug setup for Caipirinha vtol

### PR DESCRIPTION
**Pull request by kd0aij**
@tumbili this is my Caipi configuration rebased on latest master
I now have motor control immediately after arming in manual MC mode, but servos do not respond to transmitter controls. But now I can't disarm via RC, and the elevons don't act to stabilize the aircraft.
I'll try to rule out hardware problems next.

### CODE REVIEW

**Comment by tumbili** [comment]
Are you using something similar to a Pixhawk?

**Comment by kd0aij** [comment]
Yes, the Caipi and Acromaster each have an AUAVX2, which differs from Pixhawk FMUv2 in only minor respects (no onboard RGB LED, no high voltage buzzer driver, different voltage regulators and connector types)
Just verified that ESCs and servos respond correctly to "pwm test"

**Comment by tumbili** [comment]
Can you check the signals in the terminal with "px4io monitor"?

**Comment by LorenzMeier** [comment]
I'm closing this for now, assuming that we need to re-do the PR to check what is going on or even have resolved this.

**Pull request closed without merging**
