### PR TITLE
WIP:Do Not Merge - px4fmu V4 Pro

### PR DESCRIPTION
**Pull request by davids5**
Importing @klopezal work on PX4FMUV4 Pro 

FYI @LorenzMeier 

This is for board bring up and vetting. There is some cross pollination of V4 code that needs to be looked at. Pin map needs to be updated with  FMU usage and board_config need to match it.

### CODE REVIEW

**Comment by davids5** [comment]
@klopezal 

Spi device are now tested from command line - need ROMFS/px4fmu_common/init.d/rc.sensors keyed off of PX4FMU_V4PRO to set rotations correctly.

Next USB and SDIO

**Comment by LorenzMeier** [comment]
Please rebase, thanks!

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by davids5** [comment]
@klopezal - USB should is now enumerating and connecting. However, I noticed that the data stops after a while. So I need to investigate that and fix it. 

Next SD card....

**Comment by davids5** [comment]
@klopezal 

SDIO issue is resolved. The use of the SAI pll changes the clock phase.

image

Was:
image

Is:
image

**Comment by davids5** [comment]
@LorenzMeier @klopezal 

After - Bugfix:Nuttx - STM32F469 had wrong RAM size, I  tested on Bench with QGC and did calibration so let's continue dev on nuttx_v3

**Pull request merged**
