### PR TITLE
delete mavlink v1.0 submodule and legacy snapdragon pwm bridge (pwm_out_rc_in/snapdragon_rc_pwm)

### PR DESCRIPTION
**Pull request by dagar**
https://github.com/PX4/Firmware/pull/8610

@julianoes Ok to drop the Snapdragon PWM bridge to Pixhawk?

@ChristophTobler Input from your side on Snapdragon?

### CODE REVIEW

**Comment by TSC21** [comment]
@dagar it seems to be failing on the CRCs init.

**Comment by TSC21** [comment]
@dagar shouldn'r `static const uint8_t mavlink_message_crcs[256] = MAVLINK_MESSAGE_CRCS;` be `static const uint8_t mavlink_message_crcs[][256] = MAVLINK_MESSAGE_CRCS;`?

**Comment by dagar** [comment]
I'm waiting to see if we need to keep those modules at all.

**Comment by TSC21** [comment]
def of v1: https://github.com/mavlink/c_library_v1/blob/191029c48227f7a5b0900493c54ee831080183f5/common/common.h#L27
def of v2: https://github.com/mavlink/c_library_v2/blob/0667deeba1b156681a843ce40f77d1fd0d735513/common/common.h#L27
So I guess the above will fix it anyway.

**Comment by ChristophTobler** [comment]
@dagar I don't see any issues for Snapdragon. We don't use these modules anymore...
We use `snapdragon_pwm_out` and `spektrum_rc`

**Comment by julianoes** [comment]
Yes please delete all the code 😄 less is more.

**Pull request merged**
