### PR TITLE
sensors: no temperature compensation in HITL

### PR DESCRIPTION
**Pull request by julianoes**
Temperature compensation is not supported in HITL. Therefore, don't try and fail. This basically removes the confusing error message that we get in HITL.

### CODE REVIEW

**Comment by dagar** [comment]
Instead of checking if hil is enabled every single orb copy I think it can be done once initially.

**Comment by dagar** [comment]
What about disabling here? https://github.com/PX4/Firmware/blob/master/src/modules/sensors/temperature_compensation.cpp#L50
Treating it the same as if TC_{A, B, G}_ENABLE is set.

**Comment by julianoes** [comment]
@dagar I don't get how exactly you want to change it. Feel free to revert my commit and fix it your way.

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/compare/master...dagar:fix-hil-temp-calibration?expand=1

The idea is to minimize the number of special cases (hil_enabled) scattered throughout the code. Instead HITL enabled does the same as if TC was disabled via param. It's simpler and avoids checking the flag several thousand times per second.

**Comment by dagar** [comment]
Continued in https://github.com/PX4/Firmware/pull/10020

**Comment by julianoes** [comment]
Thanks @dagar.

**Pull request closed without merging**
