### PR TITLE
STM32H7 FDCAN support for UAVCAN

### PR DESCRIPTION
**Pull request by JacobCrabill**
Continuation of the work done in https://github.com/PX4/Firmware/pull/14966 / https://github.com/PX4/Firmware/pull/14928

FDCAN1 is fully working; still need to do some debugging on CAN2.

Also note, this work will require this PR of NuttX: https://github.com/PX4/NuttX/pull/101/files

FYI @dagar , @dakejahl

### CODE REVIEW

**Comment by bys1123** [comment]
Will Holybro Durandal support this feature too?

**Comment by dagar** [comment]
> Will Holybro Durandal support this feature too?

Yes, all stm32h7.

**Comment by JacobCrabill** [comment]
Just fixed FDCAN2 not working; as I suspected I had a bug in my message RAM addressing.  Both CAN ports are now working with UAVCAN.

**Comment by mirkix** [comment]
Tested successful with HereFlow

**Comment by dagar** [comment]
I'm happy to merge this if you can rebase and get it through CI cleanly.

**Comment by JacobCrabill** [comment]
> get it through CI cleanly.
Besides the ever-present SITL issues :roll_eyes: 

Rebased; should pass all tests shortly.

**Comment by dagar** [comment]
> Also TODO: Configure CAN filters.  Right now there are no filters; all
> incoming messages are accepted.

We'll need this to consider it fully supported, but I see no harm in merging as is.

**Comment by dagar** [comment]
Great work on this @JacobCrabill.

**Comment by thopiekar** [comment]
Would be great if someone could help on #15608. As far as I can see from the build log the compiler misses definitions of the drivers' timer. How do I know which timer to take for my hardware?
Hope we can continue the discussion there :wink:

**Comment by henrykotze** [comment]
https://github.com/PX4/PX4-Autopilot/pull/21701 Would be awesome if some with more experience can have a look at the Can filter implementation.

**Pull request merged**
