### PR TITLE
Change mission to new format and reset defaults

### PR DESCRIPTION
**Pull request by sanderux**
MissionCheck.py runs fine with defaults on gazebo_standard_vtol 
I made a few changes because the standard mission was in old format
@AndreasAntener you can use this for sitl CI
/cc @dagar

### CODE REVIEW

**Comment by AndreasAntener** [comment]
Cool, @sanderux could you the script and mission file to `/integrationtests/python_src/px4_it/dronekit` (new folder)?
The next step for this will be to use a test framework, for example Pythons `unittest` so it will generate the necessary test feedback to integrate in Jenkins.

**Comment by sanderux** [comment]
@AndreasAntener: done

**Comment by sanderux** [comment]
@LorenzMeier this is ready to merge

**Comment by AndreasAntener** [comment]
Rebased and applied

**Pull request closed without merging**
