### PR TITLE
WIP: Fix mRO and HK Pixhawk and Pixhack

### PR DESCRIPTION
**Pull request by LorenzMeier**
This works on a Pixhawk Mini and should boot now as well on mRobotics, HK and Pixhacks.

[px4fmu-v3_default.px4.zip](https://github.com/PX4/Firmware/files/1596218/px4fmu-v3_default.px4.zip)

@PX4TestFlights Please bench and flight test.

When testing

  - Please share the output of `ls /dev` and verify that all sensors on the board are present.
  - Please share the output of `ver all`

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Build: [px4fmu-v3_default.px4.zip](https://github.com/PX4/Firmware/files/1596163/px4fmu-v3_default.px4.zip)

**Comment by LorenzMeier** [comment]
@PX4TestFlights Please test.

**Comment by pkocmoud** [comment]
@LorenzMeier,

Testing on a mRo Pixhawk1 was successful. 

The outputs you requested:

nsh> ls /dev
/dev:
 accel0
 accel1
 adc0
 baro0
 console
 gyro0
 gyro1
 l3gd20
 led0
 lsm303d_accel
 lsm303d_mag
 mag0
 mmcsd0
 mpu6000_accel
 mpu6000_gyro
 ms5611_spi_int
 mtdblock0
 mtdblock1
 null
 pipe0
 pipe1
 pwm_output0
 px4io
 ram0
 rgbled0
 tone_alarm0
 ttyACM0
 ttyS0
 ttyS1
 ttyS2
 ttyS3
 ttyS4
 ttyS5
 ttyS6
nsh> 

nsh> ver all
HW arch: PX4FMU_V2
HW type: V2
HW version: 0x00090008
HW revision: 0x00000000
FW git-hash: f34798a878932511657b5a5daa538a76b282456d
FW version: 1.7.2 0 (17236480)
OS: NuttX
OS version: Release 7.22.0 (118882559)
OS git-hash: b18053574bf41712cef93e31bf178518f451a350
Build datetime: Jan  1 2018 16:41:51
Build uri: localhost
Toolchain: GNU GCC, 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
MFGUID: 353339383036510900510035
MCU: STM32F42x, rev. 3
UID: 510035:30365109:35333938 
nsh>

**Comment by Avysuarez** [comment]
Test with mRo pixhawk1
https://review.px4.io/plot_app?log=fae31bb5-cb5f-422b-9f49-9cffa229c909

lsdev

verall

**Comment by LorenzMeier** [comment]
This is good to go once CI passes.

**Comment by dagar** [comment]
Pixhack v3 accel and gyro checkout.

**Pull request merged**
