### PR TITLE
[WIP] Mavlink: implement geofence & rally mission protocol

### PR DESCRIPTION
**Pull request by bkueng**
This implements the new geofence and rally mission protocol (see https://github.com/mavlink/mavlink/pull/683).

### Current state
- protocol extensions fully implemented, storage & retrieval of data to/from dataman
- navigator geofence updated to handle multiple polygons, notification on geofence update

### Implementation details & further steps
- Combination logic of having multiple polygons is as following:
```
The check passes if: (inside(polygon_inclusion_1) || inside(polygon_inclusion_2) || ... ) &&
                      !inside(polygon_exclusion_1) && !inside(polygon_exclusion_2) && ...
```
@DonLakeFlyer I think we should add this to the mavlink spec.
- Only MAV_FRAME_GLOBAL(_INT) is supported
- Only one transmission at a time is possible (no interleaving)
- Handling of rally points is not done yet and needs to be added at the appropritate places.
- MAV_CMD_NAV_FENCE_RETURN_POINT needs to be handled too
- unlike the missions, geofence and rally points do not switch between 2 datasets. If needed this can be added.

### Open Questions
- What is the altitude used for in the polygon vertex? Is it a minimum or a maximum? How should it be interpolated? If we leave this open now, should we set it to NaN for now? Current implementation just ignores it.
- Can polygons be complex (self-intersecting)? The current implementation cannot handle this and I don't think it's needed (a user could just specify multiple polygons to get the same result). If we don't need it, it should be stated in the mavlink spec and the UI must not allow to draw (or upload) such polygons.

Needs a client implementation for testing.
@DonLakeFlyer

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
> What is the altitude used for in the polygon vertex?

There is no altitude in the polygon vertex. Fences are assumed to be from ground to infinity.

**Comment by DonLakeFlyer** [comment]
> Can polygons be complex (self-intersecting)?

No

> unlike the missions, geofence and rally points do not switch between 2 datasets.

Not sure what this means?

> Only MAV_FRAME_GLOBAL(_INT) is supported

On which items?

**Comment by bkueng** [comment]
> There is no altitude in the polygon vertex. Fences are assumed to be from ground to infinity.

Ah I was looking at `MAV_CMD_NAV_FENCE_RETURN_POINT`

> On which items?

The polygons

> Not sure what this means?

Our mission storage supports uploading a new mission while the previous one is still in use.

**Comment by DonLakeFlyer** [comment]
> Our mission storage supports uploading a new mission while the previous one is still in use.

How does that work? Do you need to switch between sets somehow?

**Comment by bkueng** [comment]
> Do you need to switch between sets somehow?

Exactly. But this is all done internally, it does not affect the protocol.

**Comment by LorenzMeier** [comment]
@bkueng Needs a rebase.

**Comment by julianoes** [comment]
@bkueng see my commit/bug I found.

**Comment by sanderux** [comment]
> What is the altitude used for in the polygon vertex? Is it a minimum or a maximum? How should it be interpolated? If we leave this open now, should we set it to NaN for now? Current implementation just ignores it.

It seems to me the most complete implementation would have both an alt_min and alt_max. This would allow a corridor to be defined where the takeoff and landing site could be less narrow then the flight path.

**Comment by LorenzMeier** [comment]
Closing, but not deleting the branch.

**Pull request closed without merging**
