### PR TITLE
Add force param_find for missing sensor parameters to fix load/save l…

### PR DESCRIPTION
**Pull request by anton-matosov**
…oss of calibration data

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Can you also add MAG2, ACC2 since we're doing this for 0 and 1 already?

**Comment by anton-matosov** [comment]
Sure

**Comment by anton-matosov** [comment]
Circle-CI failed here:
```
Action failed: docker pull px4io/px4-dev-nuttx-gcc_next:2016-10-20
```
@LorenzMeier can you restart tests check please?

**Comment by julianoes** [comment]
@anton-matosov you can also trigger the tests by doing a `git rebase origin/master` and then force push to this feature branch.

**Comment by dagar** [comment]
This is becoming a regular problem with circleci. Build restarted.

**Comment by anton-matosov** [comment]
Ok, but I have merged master previously with "update branch" rebate can mess it up a bit and will lose track of comments for PR.

**Comment by anton-matosov** [comment]
All tests have passed BTW, so this branch is good to merge

**Pull request merged**
