### PR TITLE
Add camera attitudes to log

### PR DESCRIPTION
**Pull request by moreba1**
https://github.com/mavlink/qgroundcontrol/issues/8257

### CODE REVIEW

**Comment by dagar** [comment]
This doesn't look right. What are you trying to do?

**Comment by moreba1** [comment]
> 
> 
> This doesn't look right. What are you trying to do?

i try to add roll , pitch and yaw to camera feedback .

**Comment by dagar** [comment]
> > This doesn't look right. What are you trying to do?
> 
> i try to add roll , pitch and yaw of vehicle (camera) to camera feedback .

You can get the roll, pitch, and yaw from the quaternion.

**Comment by julianoes** [comment]
@moreba1 the mavlink headers have helper functions to do this:
https://github.com/mavlink/c_library_v2/blob/4fae56bee9e123d61290346c948223c250009b28/mavlink_conversions.h#L103-L108

**Pull request closed without merging**
