### PR TITLE
NuttX include Kconfiglib (python) and compress all defconfigs

### PR DESCRIPTION
**Pull request by dagar**
1. NuttX build include and use Kconfiglib (python) https://github.com/ulfalizer/Kconfiglib
     * This is a bit more convenient and portable than relying on kconfig-frontends (https://bitbucket.org/nuttx/tools/src/3b40b5bac4d6797aa7a63529e0255420fdbba942/kconfig-frontends/?at=master) which is not widely packaged and has various issues on Windows.
     * We can also start utilizing this library directly to make simple Kconfig changes as needed (eg stackcheck builds) rather than maintaining nearly duplicate configs.
2. Compress all in tree defconfigs

### CODE REVIEW

**Comment by dagar** [comment]
This is worth including in v1.9.0 as it's the first release that includes the larger board consolidation effort (a fair amount of churn). Overall these changes can help to significantly reduce the perceived complexity new developers often report when adding a custom board (commonly a small variation of an existing board).

**Comment by LorenzMeier** [comment]
I agree, but it is quite a diff (or rather change). Have you run binary output comparisons to see if it generates the same output? That would seem to be the easiest way to ensure we're not missing critical config options. We have been bitten in the past, so we need to be very diligent here.

**Comment by dagar** [comment]
I did a close comparison of the .config, nuttx/config.h, and overall binary for px4_fmu-v2 and px4_fmu-v5 (see Jenkins http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/detail/PR-11672/4/pipeline/23). 

I also diff'd the nuttx/config.h across every board we support. The only difference (present on all the STM32F4 boards) is the removal of `CONFIG_STM32_HAVE_DAC2`, which we don't use.

image

**Comment by davids5** [comment]
@dagar - a CONFIG_STM32_HAVE_DAC2 is from the CPU Kconfig.  A has is option enabler. Did you run make oldconfig on all the defconfigs?

**Comment by ulfalizer** [comment]
Might be due to https://github.com/PX4/NuttX/commit/a20e874883fb55657f96e576a19e4c0d7106e166. Running an `oldconfig` will also get rid of those settings in that case.

Feel free to try out the menuconfig too. It has more features than the C version. :)

Cheers,
Kconfiglib guy

**Comment by dagar** [comment]
Thanks @ulfalizer, and yes that's been verified. I'm also interested in migrating to Kconfiglib entirely, but need to figure out the right way to integrate on top of NuttX. Personally I still like using qconfig over menuconfig.

I think we're good to merge here.

**Comment by ulfalizer** [comment]
> Thanks @ulfalizer, and yes that's been verified. I'm also interested in migrating to Kconfiglib entirely, but need to figure out the right way to integrate on top of NuttX. Personally I still like using qconfig over menuconfig.

What things do you miss from `qconfig` by the way?

I've mostly used the terminal menuconfigs. Kconfiglib's menuconfig has `xconfig` features like jumping directly to a symbol, showing hidden symbols, and showing symbol help texts at the bottom at least.

One thing I wish I could add is mouse support, but then I'd want scroll wheel support too, and unfortunately there's no way to get scroll wheel events with Python's `curses` module (even when the underlying ncurses supports it).

**Comment by dagar** [comment]
> > Thanks @ulfalizer, and yes that's been verified. I'm also interested in migrating to Kconfiglib entirely, but need to figure out the right way to integrate on top of NuttX. Personally I still like using qconfig over menuconfig.
> 
> What things do you miss from `qconfig` by the way?
> 

@ulfalizer I think it's mostly that I don't actually use either that often, but when I do I often like to look around. Things like expanding or collapsing parts of the tree to see as much or as little as I want or even find that also expands the relevant section when browsing each option are the minor niceties that make it preferable for the casual user.

**Comment by ulfalizer** [comment]
@dagar 
Yeah, maybe some alternate mode like that could be added to the terminal menuconfig. Bundling some graphical menuconfig would be nice too.

One thing I worry a bit about is that the code might become complex enough that people will be scared off from making their own menuconfig. :)

**Comment by ulfalizer** [comment]
@dagar 
There's now a `qconfig`-like menuconfig as well by the way. See `guiconfig.py` in https://github.com/ulfalizer/kconfiglib#menuconfig-interfaces.

If you try it out, tell me if you spot any issues or have any interface nits.

**Pull request merged**
