### PR TITLE
Home on takeoff

### PR DESCRIPTION
**Pull request by LorenzMeier**
@DonLakeFlyer This is what you were suggesting.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@DonLakeFlyer It now also sets the takeoff yaw angle for RTL, so it should come back in the exact same orientation as it took off.

**Comment by LorenzMeier** [comment]
@tumbili Could you test this in sim?

**Comment by LorenzMeier** [comment]
It should RTL in direction of HOME, then turn into the direction it took off with once it descends.

**Comment by LorenzMeier** [comment]
@tumbili Please merge once tested in SITL. This shouldn't require an outdoor flight since its just logic changes. Please RTL from different heights over ground / home ( e.g. 1 m and 30 m) and ensure it turns back to the correct orientation both times.

**Comment by tumbili** [comment]
Works fine, merging!

**Pull request merged**
