### PR TITLE
EKF gains

### PR DESCRIPTION
**Pull request by LorenzMeier**
Discussion in #2476.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@sjwilks This is the change discussed on the mailing list.

**Comment by LorenzMeier** [comment]
@sjwilks You will need / want to set the two changed params manually. None of the changes here would reset a hand-tuned / set param.

**Comment by LorenzMeier** [comment]
@kd0aij Flashing this on your plane would be fantastic!

**Comment by kd0aij** [comment]
@LorenzMeier I flashed this branch on my Ninox using the latest QGC daily build, and verified that ekf_att_pos_estimator is running.
The nsh console shows a number of EKF* parameters, but I can't find them in QGC. Is this right?
```
nsh> param show EKF*                                                            
Symbols: x = used, + = saved, * = unsaved                                       
    EKF_ATT_ENABLED [-1,30] : 1                                                 
    EKF_ATT_V4_R2 [-1,31] : 100.000000                                          
    EKF_ATT_V4_R1 [-1,32] : 10000.00000000                                      
    EKF_ATT_V4_R0 [-1,33] : 0.0008                                              
    EKF_ATT_V3_Q3 [-1,34] : 0.0050                                              
    EKF_ATT_V3_Q2 [-1,35] : 0.0090                                              
    EKF_ATT_V3_Q1 [-1,36] : 0.0800                                              
    EKF_ATT_V3_Q0 [-1,37] : 0.0001                                              
 ```

**Comment by LorenzMeier** [comment]
These are for the other EKF. The ones you're looking for start with PE

**Comment by kd0aij** [comment]
I set the PE params to the FW defaults in the commit above. 
PE_POSD_NOISE = 1
and PE_VELD_NOISE = 0.35 
still show up in yellow in QGC. I assume this means the metadata wasn't changed to agree with the new defaults.

**Comment by LorenzMeier** [comment]
QGC only gets metadata when you flash via it. Don't expect it to do something magic for developers 8)

**Comment by kd0aij** [comment]
Repeat: "I flashed this branch on my Ninox using the latest QGC daily build"

**Comment by LorenzMeier** [comment]
Sorry, I was reading this on my mobile which stripped me of the context. QGC uses the default param value to compare, it doesn't know about platform level defaults, which I think is fine for a low-level thing like a param editor.

**Comment by kd0aij** [comment]
flew this branch on a Ninox today. No obvious problems. https://drive.google.com/open?id=1EFi-o6Nw8fbm7yQqSjF9PdwoJ49KEiRGjx9wz0Q3xDs&authuser=0

**Comment by kd0aij** [comment]
@LorenzMeier In a comment above, you mentioned "platform level defaults". Looking at the comments in ekf_att_pos_estimator, I see that there are 3 defaults referenced; generic, multicopter and ground vehicles. But, since PARAM_DEFINE_FLOAT can accept only a single default value, the metadata does not convey to the QGC user all of the info in the comments. This to get, the code one must read. If the metadata were expanded to include the platform default values (and to add fixed wing to the list), QGC could display relevant information to the user, instead of stating that the parameter values are not at the correct defaults.

**Comment by LorenzMeier** [comment]
I think we have a different view on the system. On our current view on the system, there are two levels: Either you're a developer with a reasonable high level of understanding of the system (essentially happy to read code and header docs right now), and you can modify tuning params. Or you are an end user, and you use canned configs + 3-4 sliders (which we yet have to implement, so that's where some of the difference of our views on the system might originate).

Fundamentally the param editor in QGC is REGEDIT in Windows, and there is only one system level default. Maybe the yellow color should be changed to something more subtle to reflect this.

Your view on the system is that the param editor is the tool for prosumers and flight-code developers to tune the system, and its use is common.

I agree that we fall short of providing integrators (and our pro users) enough docs. I find myself needing to go back into code for some of the params. But I don't think that making the param default mapping more fancy will really help there, because there is no default which fits all airframes.

I think what we really need are better docs which relate some relevant tuning params to physics, and explain their derivation and relation. That would also explain what values to expect on different airframes. In addition, I will extend the param metadata to mention per-platform defaults.

@DonLakeFlyer Open to make the non-default flag in QGC a shade of grey instead of yellow? Its not something which requires user attention, but right now it looks like it would.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer One option would be to have @default_multicopter, @default_fixedwing flags. But I lack the bandwidth to pull this off right now.

**Comment by DonLakeFlyer** [comment]
Can you point me to where this is in the firmware source?

**Comment by kd0aij** [comment]
Hi Don. The source parser (srcparser.py) is in Tools/px4params.

**Comment by DonLakeFlyer** [comment]
I know that. I need an example of a parameter that doesn't work correctly with defaults in QGC since it has multiple defaults based on airframe type. Looking for a pointer into the firmware for a parameter as well as where it says what they multiple defaults are.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer The multi defaults are in the startup scripts. And really, I don't intend to maintain those, because it doesn't make sense. With the reason that any airframe has different tuning gains.

The right fix for this problem is to not show changed values in a safety color (yellow) and to provide developers docs for them to understand how to use parameters.

Even if QGC would have the best visual menu, you still need to understand what a PID controller does, and the defaults / non defaults thing is not helping you there.

**Comment by kd0aij** [comment]
example of parameter with platform-dependent defaults: https://github.com/PX4/Firmware/blob/master/src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_params.c#L164

**Comment by LorenzMeier** [comment]
Yes, but that depends on the dynamics of the vehicle and sensors used. So there are 3+ valid values

**Comment by DonLakeFlyer** [comment]
Ah, I see these are really tuning params. So in some sense the defaults are just starting points not quite defaults. I think the real fix would be to disregard the fact that there are default values for these types of params somehow. Pretty low on the priority list though.

**Pull request merged**
