### PR TITLE
Sensirion SDP31 pressure sensor driver

### PR DESCRIPTION
**Pull request by LorenzMeier**
General specs: Good from 0 m/s (it can register 1 m/s) up to 25 m/s / 60 mph / 100 km/h. Impressive sensitivity, virtually no offset. This should not require in-field calibration any more.

The graph below shows a log where I walked about 8 meters indoor from one table to another and put the sensor down. You can even see when I approached the desk at the end of the log - just moving close to it triggered some air circulation.

screen shot 2017-06-10 at 14 51 44

### CODE REVIEW

**Comment by dagar** [comment]
What do you think about using DriverFramework for these?

**Comment by LorenzMeier** [comment]
@dagar The DriverFramework first needs some overhaul to really fully fit into the architecture. E.g. it needs its HRT and other facilities to be fully integrated.

**Comment by LorenzMeier** [comment]
This is good to go. I actually had to tweak the system quite a bit to allow for the very low noise we're seeing here.

**Comment by njoubert** [comment]
Any reason you chose this SPD31 over the SPD810 series? They seem almost identical, but the SPD810 is a bit easier to work with, since it's a bit larger! Ths SPD31 is truly miniscule :)

**Comment by LorenzMeier** [comment]
We have access to a non-listed part that has a better dynamic range.

**Comment by njoubert** [comment]
@LorenzMeier Are you implying it has a larger pressure range? We'd be interested in a sensor that can get up to 2kPa, then we'd throw away out current solution! What's the specs of the unit you've got?

**Pull request merged**
