### PR TITLE
EKF2 add perf counters

### PR DESCRIPTION
**Pull request by dagar**
image

~ 100 us to copy all data, and 250-300 us to run the EKF update.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
On first pass we might want to check if the priority is set correctly.

**Comment by dagar** [comment]
Once both local and global are valid the cpu usage for EKF2 is around 14%, which means everything that happens after _ekf.update() is something like 4% of the total cpu usage.

**Comment by dagar** [comment]
Dropped the vehicle_local_position and vehicle_global_position prints to save flash on fmu-v2.

**Comment by dagar** [comment]
Current Priorities

| module | priority |
| ------------- |:-------------:| 
| mc_att_control | 251 |
| fmu | 251 |
| mc_pos_control | 250 |
| EKF2 | 250 |
| sensors | 249 |
| hpwork| 249 |

**Pull request merged**
