### PR TITLE
Zehortigoza aero stuck

### PR DESCRIPTION
**Pull request by davids5**
@zehortigoza 

I continued your work here. This fixes the build.

There are many levels of crash support. 
APP
- OS 
---STM32
---STM32F7

This is why we do not hand edit the defconfig file

You can see what I meant by arch agnostic in common.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@zehortigoza Can you re-test on hardware?

**Comment by davids5** [comment]
Rebased on master

**Comment by LorenzMeier** [comment]
@zehortigoza Let us know if you got a chance to test on hardware.

**Comment by zehortigoza** [comment]
This looks good if appended with this patch to make AeroFC reboot after a crash: https://github.com/zehortigoza/PX4Firmware/commit/5edf3e679ff8725f5f57932e262a4b0ef9938b95
Tested in AeroFC and everything is working.

**Comment by LorenzMeier** [comment]
Can you send a PR for that patch?

**Comment by zehortigoza** [comment]
> Can you send a PR for that patch?

Done https://github.com/PX4/Firmware/pull/6421

**Comment by zehortigoza** [comment]
Thanks

**Pull request merged**
