### PR TITLE
Support 16 channels on IO via S.BUS

### PR DESCRIPTION
**Pull request by LorenzMeier**
This enables 16 channels via S.BUS. Ready for bench-testing.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This fixes #1819

**Comment by hsteinhaus** [comment]
Hi Lorenz,

any issues with this code that prevent merging? I am flying it intensively since a few weeks with ArduCopter 3.2.1 (backported to https://github.com/diydrones/PX4Firmware/tree/ArduCopter-3.2.1) and did not find any adverse effects (controlling my STORM32 gimbal with channels 9..13).

IMHO the higher channels of S.BUS are very valuable for payload control (which is the probably the main scenario for S.BUS out), as the lower channels usually needed for vehicle control.

**Comment by LorenzMeier** [comment]
No, just was waiting for test feedback ;-). Thanks! Merged.

**Comment by severinleuenberger** [comment]
this is not fixed yet. We would appreciate, if anyone could look after that issue. Currently there are only 8 woring chanels

**Comment by hsteinhaus** [comment]
I am flying with PR #1819 with ArduPilot since a few months now as I need channel 9..12 on SBus for gimbal control. I did not notice any adverse effects so far.

**Comment by severinleuenberger** [comment]
@hsteinhaus Do you use it in combination with a *.mix file or just as plain passthrough chanels?

**Pull request merged**
