### PR TITLE
8266 dynamic enable & factory reset features

### PR DESCRIPTION
**Pull request by LorenzMeier**
@kd0aij This is your PR rebased on master.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@pkocmoud The main concern with the current default is that this will disable wifi as people arm by default. I think we will need to change the default to always on and educate users (because folks flying with a tablet will else have a drone with no control, which seems dangerous).

**Comment by LorenzMeier** [comment]
@dogmaphobic I have added GPIO0 toggling - does this look right to you / workable? Can you test?

**Comment by kd0aij** [comment]
@LorenzMeier Thanks for rebasing this. I hadn't considered the ramifications of wifi-only control. Perhaps the only way to ensure safety would be to disallow arming under specific conditions. In any case, since wifi has very limited range, the system must be safe by design even with an unreliable primary control link. We should implement a means of testing failsafe actions while a reliable RC link is still available.

**Comment by dogmaphobic** [comment]
> I have added GPIO0 toggling - does this look right to you / workable? Can you test?

Sure! Once this gets merged I'll take a look. I need to add a button within QGC to activate it.

What about the WIFI_TX_MODE param? Will it make to the main UI or stay only within the Parameters Dialog?

> because folks flying with a tablet will else have a drone with no control, which seems dangerous

From the QGC side, we know if *Tablet* joystick mode is enabled. QGC could make sure WIFI_TX_MODE is always == 2 in those cases, though it would be safer if the flight controller would handle this.

**Comment by dogmaphobic** [comment]
Hmm, looking at the code (ESP8266 Firmware), the pin is active low. It has a pullup resistor setup. The code below looks like active high:
```
#ifdef WIFI_FACTORY_DEFAULTS
 	WIFI_FACTORY_DEFAULTS(1);
 	usleep(500);
 	WIFI_FACTORY_DEFAULTS(0);
 #endif
```
I can invert the logic within the ESP8266 firmware but that will require existing users to update their firmware.

**Comment by dogmaphobic** [comment]
Also, this looks suspicious:
```
#define WIFI_FACTORY_DEFAULTS(_s) px4_arch_gpiowrite(GPIO_8266_GPIO0, _s)
```
The proper pin is GPIO02 not GPIO0

**Comment by dogmaphobic** [comment]
screen shot 2016-05-29 at 11 29 00 am

**Comment by kd0aij** [comment]
Which schematic is that? Looks like it may be for an early beta hardware version.

**Comment by dogmaphobic** [comment]
> Which schematic is that? Looks like it may be for an early beta hardware version.

From the bottom of this page. If that's the case, the page needs to be updated.

https://pixhawk.org/modules/pixracer

Regardless, the *Reset To Factory* pin is GPIO2, not GPIO0.

**Comment by kd0aij** [comment]
I was just confused, since I was looking at the serial IO page of the schematic, and missing your point about it being active low.

**Comment by dogmaphobic** [comment]
The "Active Low" part is on the ESP8266 side. The (ESP8266 Firmware) code currently sets up a pullup on GPIO2 and the reset is handled by an interrupt when the pin is brought to LOW.

**Comment by kd0aij** [comment]
I should go back to bed :)

**Comment by LorenzMeier** [comment]
@kd0aij Would you have bandwidth to rebase and fix / finish this?

**Comment by kd0aij** [comment]
I'll try rebasing and addressing Gus's comments on your reset addition.

**Comment by kd0aij** [comment]
@dogmaphobic I rebased and made the changes to GPIO2 that you called out. If the CI checks pass, would you test please?

**Comment by LorenzMeier** [comment]
@dogmaphobic @kd0aij Can you pick up the testing of this so we can get this into 1.4?

**Comment by LorenzMeier** [comment]
@dogmaphobic Would it be possible to rebase this on master and test it on hardware?

**Comment by kd0aij** [comment]
stale

**Comment by devbharat** [comment]
Is there a replacement PR for turning WiFi off when Armed? Or is this still open?

**Comment by mhkabir** [comment]
@devbharat There isn't.

**Pull request closed without merging**
