### PR TITLE
HIL/SITL multirotor actuator range fixes

### LINKED ISSUE #5305: hardware in the loop test problem
Hi
I have a problem with hil test. I have changed the SYS_AUTOSTART parameter to 1001. Then I run the jMAVSim in HITL mode and start the QGC(v.2.9.7). I send the missions to vehicle. But when I armed the system, it just rises indefinitely not going to waypoints. I have also done the sensor calibration.

### PR DESCRIPTION
**Pull request by julianoes**
Instead of sending actuator controls from -1..1 for SITL, we should send
0..1 like we already do for HIL. This will enable negative thrust in the
future, e.g. for pusher props that spin backwards, or for vehicles with
variable pitch propellers.

This resolves #5305.

This depends on https://github.com/PX4/jMAVSim/pull/45 and https://github.com/PX4/sitl_gazebo/pull/57

Please review @LorenzMeier.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I'm not sure if this isn't a step backwards to be honest. All mixer outputs in PX4 are eventually -1..1, including multi rotor motor outputs. You just introduced a lot of special case logic.

**Comment by LorenzMeier** [comment]
The right fix would be to fix HIL to send -1..+1 for all airframes.

**Comment by julianoes** [comment]
> All mixer outputs in PX4 are eventually -1..1, including multi rotor motor outputs. 

Correct and that's the interface (as descibed in the mavlink docs as well) for jMAVSim and Gazebo. The current multirotor actuators need to be 0..1 because they never output negative thrust. If they did, the protocol is already there and correct.

**Comment by LorenzMeier** [comment]
Travis passed but failed to report (the internet is still broken..).

**Comment by julianoes** [comment]
> the internet is still broken

Sadly true.

**Comment by julianoes** [comment]
@LorenzMeier I rebased sitl_gazebo and this branch again. If we feedforward merge jMAVSim and sitl_gazebo on the console (and not github), we can get this in as is without wrong references to submodules.

**Comment by julianoes** [comment]
@LorenzMeier let's get this in, I rebased once again.

**Pull request merged**
