### PR TITLE
board power button notification API

### PR DESCRIPTION
**Pull request by davids5**
@bkueng , @LorenzMeier 

1) Defined types and interface to support a notification call back on power button events.
2) tap: Added support for notification call back on power button events with the a default handler.

### CODE REVIEW

**Comment by davids5** [comment]
>I have some questions/concerns:

I agree we need a consolidation and feel free to rename or rework any of it. Let me just share my perspective and some of the issue I see. I am using commander as the point of control below but that can be any HLL module.

> is there a semantic difference between px4_board_pwr and board_shutdown? Do we really need both?

There is at the moment. We have HW that has a single GPIO control that works to Power On and Off the system. 

We have other HW that has a GPIO to control the power ON of the system. But can not control the power down other than to, signal the bootloader, release its hold on that GPIO and to a reset, then rely on the bootloader to not re-enable the power. 

We will also have smart battery control that will be different.

We probably need to further define and decouple things a bit.

We should remove px4_board_pwr as a public API point. 

In it place we will have board_set_power(bool on_true) - it just controls the GPIO and may or may not be used by higher level code.

Based on the defines  BOARD_HAS_POWER_CONTROL and BOARD_HAS_POWER_SWITCH we have different operational scenarios. I am not clear on if the board will define anything for smart battery.

When BOARD_HAS_POWER_CONTROL is defined the board can turn on / off the system
It provides:
           board_shutdown() - this may just call board_set_power(on_true) or do other heroics. 
           board_set_power(bool on_true) - simple power control of an GPIO.


When BOARD_HAS_POWER_SWITCH is defined the board can notify the system of a power switch state 
It  provides:
         board_register_power_state_notification_cb - registration of the receiver of the call back. (see below)
         it call out to that call back with non filtered the button states and does the timer work needed for a button up sending a PWR_BUTTON_REQUEST_SHUT_DOWN .

>I think the callback will always be the same for the whole system (initially just waiting for the logger, later maybe more). Thus the question: do we need it? Or would a fixed funtion do it?

Yes. - I think we do need it. Because the phases the system comes up in, dictates a staging.
Power on
V
--------> 1) We can only set GPIO
--------------->2) OS init
---------------> 3) hook and arm GPIO based ISR.
---------------------->4) Init the cpp
----------------------------->5) run init and rcS
------------------------------------------>6) Commander ready

1) It would not be good for an ISR to call into high level code until it is fully initialized (post 6). While I imagine that the HLL code could be programed with a defensive, a simpler fool proof approach is to have that HLL code register when it can control the system. 2) Until then the default int the board code will take care of a shut down if thing do not go well we can still power off.

I think we should also add a `time threshold` to  `board_register_power_state_notification_cb` that replaces the hard coded constant MS_PWR_BUTTON_DOWN in the timer. MS_PWR_BUTTON_DOWN would be the default until the registration is called. Then the app can dictate the button held down time before the  PWR_BUTTON_REQUEST_SHUT_DOWN is sent on the button up.

> This also does not consider other calls, such as the px4_board_pwr call from commander 

When BOARD_HAS_POWER_CONTROL is defined the commander can call board_shutdown(false, false) and it will power down the system. 

If a system has a smart battery, then it is a different level of control and not in the purview of the board code.  

If a system does not have BOARD_HAS_POWER_CONTROL lit, or a smart battery, I think commander needs to deal with it differently. If commander just calls board_shutdown(false, false) and a board does not support power control. I guess it could just return and commander will have to deal with it (yeah no if def!), or the board code could just disable interrupts and halt, but I think it is better not to make a decision like that in low level board code. If the board code to just rest, when the system hits a low battery conditions or the system just keep resetting. (That may just happen anyway as the battery rolls off)

Also keep in mind that on FMUv5 we are supposed to log the system voltages including the CPU falling into power fail. The power going down will have to interrupt the CPU. Then the CPU has to get that event logged. If we have sufficient hold up time (TBD), we can use the normal logging channels. If not we need to use bbsram, like we do for hard faults. Then recover and log that data on the next power up.

>and px4_systemreset (reboot.c command, calling board_system_reset). They should IMO also use the callback.
> Are you referring to board_shutdown(bool, bool)?

Nuttx now provides an arch specific reset API. I would like to use it. But we need 2 steps. The first step conditions the reset with `board_set_bootload_mode` the second phase calls the arch specific reset API. This can be wrapped with any api you would like, board_shutdown(bool, bool) would work, but what does board_shutdown(false, false) do on HW with no BOARD_HAS_POWER_CONTROL?

Just keep in mind ALL PX4 systems will support the reset at the board API and be able to enter the bootloader. Not all PX4 systems will support power control, or switch notification.  

Thoughts?

**Comment by bkueng** [comment]
If the callback is used to ensure correct initialization order, then I agree it's a good way to do it.

If the system does not have BOARD_HAS_POWER_CONTROL, then I think so too, board_shutdown(false, false) should return an error and higher level code should deal with it. If the system does not provide the functionality, it simply cannot satisfy the request, and it depends on the situation what the best alternative is.
With that, I then see nothing standing in the way of a combined API `int px4_shutdown_request(bool, bool)`. The power button callback would then just call this with (false, false).

> Also keep in mind that on FMUv5 we are supposed to log the system voltages including the CPU falling into power fail.

Interesting, I didn't know that. But I think it should not confict with the proposed API.

Thanks for the info. I'll rework this then.

**Comment by bkueng** [comment]
@davids5 I reworked and extended this, please have a look. There is now a single public API call `px4_shutdown_request(bool reboot, bool to_bootloader)` which maps to the lower-level board API calls `board_shutdown` and `px4_systemreset`. `px4_board_pwr` got removed.

In addition, modules can register a shutdown hook, currently used by the logger. It takes around 40ms for the logger to properly shutdown, so I set a max timeout of 300ms.

The power button callback still needs to be tested on HW.

**Comment by davids5** [comment]
@bkueng, It looks perfect!

**Comment by bkueng** [comment]
Thanks! I just saw the CI error:
```
../src/platforms/common/shutdown.cpp:49:22: error: variable 'work_s shutdown_work' has initializer but incomplete type
 static struct work_s shutdown_work = {};
```
for `px4cannode-v1_default`. Seems the work queue is not enabled there and we have to ifdef it... unless you see a better alternative?

**Comment by davids5** [comment]
@bkueng - The px4cannode is the minimal uavcan node. It has RAM/FLASH limitations and does not support the worker queue. It has to use the system reset to reset the node to do the UAVCAN upgrade.  
So I think I think the high level code need to be optional.

**Comment by bkueng** [comment]
I ifdefed the work queue and tested the power notification callback.

**Pull request merged**
