### PR TITLE
aerofc: revert the use of logger by default

### PR DESCRIPTION
**Pull request by lucasdemarchi**
This increases the rate of the mavlink channel which will need changes on the Linux side.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@lucasdemarchi I don't understand your comment - I presume we're reverting until we have TX DMA on the UART?

**Comment by LorenzMeier** [comment]
@davids5 How far out is TX DMA?

**Comment by lucasdemarchi** [comment]
We need changes on both Nuttx and Linux sides. My comment was more regarding the changes on the Linux side than on Nuttx.

**Comment by LorenzMeier** [comment]
Got it.

**Comment by davids5** [comment]
@LorenzMeier - it is a ways out. I would expect mid-end Jan if we get nuttx_upgrade merged smoothly

**Pull request merged**
