### PR TITLE
simulator: publish 2 instances of accel/baro/gyro/mag

### PR DESCRIPTION
**Pull request by dagar**
The data is currently duplicated, so we could handle it differently for the sake of testing later.

Broken out of https://github.com/PX4/Firmware/pull/14650.

### CODE REVIEW

**Review by Jaeyoung-Lim — APPROVED** [review]
LGTM on my side as it just seems to duplicate streams.

Might not be relevant to this PR, but related: It would be great if we can define a primary sensor - and we can probably scale this to having multiple streams of HIL_SENSOR messages(probably by addind an ID field in the mavlink message), so that we can have multiple sensor support for sensors like IMUs/Airspeed sensors.

**Comment by dagar** [comment]
> It would be great if we can define a primary sensor 

In what sense? On the PX4 side you can now do that by setting the corresponding priority.

 - CAL_ACCx_PRIO/CAL_GYROx_PRIO/CAL_MAGx_PRIO

**Comment by Jaeyoung-Lim** [comment]
@dagar because lockstep depends on the HIL_SENSOR message, and multiple instances of this would confuse lockstep. (but I think this is not really relevant for this PR)

I have created https://github.com/mavlink/mavlink/pull/1468 so that we can wire each sensor instance to different IMUs in the Sim

**Comment by dagar** [comment]
> @dagar because lockstep depends on the HIL_SENSOR message, and multiple instances of this would confuse lockstep. (but I think this is not really relevant for this PR)
> 
> I have created [mavlink/mavlink#1468](https://github.com/mavlink/mavlink/pull/1468) so that we can wire each sensor instance to different IMUs in the Sim

Ah right. No it's not yet a lockstep issue, but it will be soon™. https://github.com/PX4/Firmware/pull/14650

**Comment by Jaeyoung-Lim** [comment]
@dagar Cool!

**Pull request merged**
