### PR TITLE
Working on uavcan building.

### PR DESCRIPTION
**Pull request by jgoppert**
Work in progress. Need to figure out how to pass extra link flags into external project in cmake.

### CODE REVIEW

**Comment by jgoppert** [comment]
@LorenzMeier, @pavel-kirienko this is basically done, the library is built and installed, just need to add the module source and link to it.

**Comment by jgoppert** [comment]
@LorenzMeier @pavel-kirienko just waiting for pavel to test the latest changes and push them upstream so we can set the submodule back to his repo.

**Comment by pavel-kirienko** [comment]
> what remote should I use to get commits? Your forks of libuavcan and PX4 have not been updated in 2 days, git says, and I have already tested that yesterday

**Comment by jgoppert** [comment]
@pavel-kirienko The links are correct, I just rebased the commits, so the date shows the date of the first commit on the rebase.

**Comment by pavel-kirienko** [comment]
Works for me.

**Comment by jgoppert** [comment]
@pavel-kirienko Thanks! Can we get my libuavcan branch merged with master so I can set the link back to your repo?

**Comment by LorenzMeier** [comment]
I'm going to merge this for PX4 tonight, would be great to have uavcan still pointing to master and not a fork. I would like to avoid starting to have to maintain a fork / custom version.

**Comment by pavel-kirienko** [comment]
@jgoppert any chance to address the issues I raised with your PR?

**Comment by jgoppert** [comment]
I believe I addressed them last night, what is still bothering you? @pavel-kirienko

**Comment by pavel-kirienko** [comment]
@jgoppert 

1. Toolchain file is still there
2. Extra include https://github.com/jgoppert/libuavcan/blob/cmake-cross/libuavcan_drivers/stm32/driver/CMakeLists.txt#L2

**Comment by jgoppert** [comment]
Ok, include directory was needed, broke when I removed it. Will remove the tool chain file.

**Comment by jgoppert** [comment]
Ah src, not include, will try that

**Comment by jgoppert** [comment]
@pavel-kirienko Done.

**Comment by jgoppert** [comment]
@pavel-kirienko, can you merge now?

**Comment by pavel-kirienko** [comment]
Sorry, still not good enough.

Linux build is broken now. The build script must be able to detect that the current platform is Linux, and adjust the build automatically. It used to be implemented here: https://github.com/UAVCAN/libuavcan/blob/master/CMakeLists.txt#L28

```cmake
#
# libuavcan drivers
#
if (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    message(STATUS "Adding Linux support library")
    add_subdirectory(libuavcan_drivers/posix)
    add_subdirectory(libuavcan_drivers/linux)
endif ()
```

Also, `USE_CPP03` has been renamed to `UAVCAN_USE_CPP03`, which is OK, but it should be updated everywhere, including https://github.com/UAVCAN/libuavcan/blob/master/libuavcan/CMakeLists.txt#L50.

Also, adding POSIX drivers for every build will break ChibiOS/LPC11C24 builds, it should be conditional too. See https://github.com/jgoppert/libuavcan/blob/cmake-cross/CMakeLists.txt#L69

**Pull request merged**
