### PR TITLE
LPE altitude handling imrpovements

### PR DESCRIPTION
**Pull request by jgoppert**
LPE altitude related ease of use improvements:
* resets altitude above home on arming to zero
* prevents changes of position estimate while landed state is true

### CODE REVIEW

**Comment by mhkabir** [comment]
> prevents changes of position estimate while landed state is true

I'm wondering if this can cause weird artifacts. So on the ground, since the estimate isn't updated, once you takeoff, the GPS could be telling you its somewhere else, and the estimate would suddenly jump. Am I correct?

**Comment by jgoppert** [comment]
@mhkabir I agree, I had to make this changes for indoors so that my local z was accurate when I was collecting some data, but not a good end solution. Since we update home position on arming, it is possible for a user to sit on the ground for awhile in armed state. During this time, the gps and baro can cause the global position estimate to drift. This is undesirable since any drifts end up directly in our local position estimate. So we almost need to update home again when we takeoff and are not landed anymore and reset local x, y , z to zero.

**Comment by mhkabir** [comment]
I think updating "home" and the "local origin" are two different things we need to care about. As I understand it : 
1. **Home Position** is the location set on takeoff (or arm?), where the copter RTLs to, or in missions or whatever. This isn't used in any control loops.
2. **Local frame origin** is the reference with respect to which we navigate. We also it to transform our GNSS observations into the local frame. This origin _should never drift_ (or be reset) because that's just bad. We do not ever want to be messing with our reference origin. It should be set when (and where) the estimator receives its first observation.

I'm trying to understand what exactly led you to introduce the "prevents changes of position estimate while landed state is true" so that we can work towards a more portable/optimal solution.

**Comment by jgoppert** [comment]
There is currently no separate local frame origin in the code. When you arm it sets home as current estimate and set x y z to 0.

The motivation here is that we used to use agl as local z, but Lorenz pointed out that isn't the best idea. However,  agl was very solid indoors because it just measured the distance above ground and was not influenced by baro drift. 

If we instead publish local z, our best estimate of altitude above home position, this now introduces baro drift. While sitting on the ground, this effectively lets the local frame slide around with baro, so when you take off, and the lidar says you are 1 m above ground, your altitude estimate might say 3 m, because baro had drifted 2 m since your home position and local frame origin were set. This is unacceptable for indoor flight, and that is why you currently have to set MPC_ALT_MODE = terrain following. I want to be able to fly MPC_ALT_MODE = altitude following indoors and it not be off.

**Comment by jgoppert** [comment]
Here is the reference in the code where home is reset on arming: https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L2719

**Comment by ecmnet** [comment]
@jgoppert Do you think that solves the drift? As lidar/sonar are valid at certain altitude only, baro drift could still influence the position while talking off.

**Comment by ecmnet** [comment]
@jgoppert What about taking the first observationen of baro alt as local origin, but decreasing its influence at low altitudes with takeoff, increasing it ägäis with the altitude achieved.

**Comment by jgoppert** [comment]
While landed, we are basically estimating home position since whenever we takeoff home is reset and local position is zeroed. In LPE home position is local origin.

@ecmnet It is true that there could still be some drift from takeoff till when sufficient altitude for sonar/lidar to init is achieved, but I think this is insignificant. If we just take the first baro reading as local origin, this will deviate significantly from what the baro pressure of home is on takeoff, so I think it is best we keep it estimating alt of home before takeoff.

**Comment by ecmnet** [comment]
@jgoppert Baro sometimes shows significant 'jumps'. If you are taking off at that point of time, the influence could be quite high. But I agree, this implementation will decrease the drift in mans cases.

**Comment by jgoppert** [comment]
@tumbili In EKF2 how do you guys handle drift before take-off in the local frame. Do you just set x, y, z = 0 on takeoff?

**Comment by AndreasAntener** [comment]
I don't have context for the full issue here, but the local reference should never reset (https://github.com/PX4/Firmware/pull/3403). This is really undesirable if you control the vehicle with local position.

**Comment by jgoppert** [comment]
@AndreasAntener thanks, I will have to change LPE to follow suite.

**Pull request closed without merging**
