### PR TITLE
mavlink message move more streams to separate headers

### PR DESCRIPTION
**Pull request by dagar**
I've also started adding include guards which allow us to trivially exclude streams when the time comes.

### CODE REVIEW

**Comment by dayjaby** [comment]
Maybe this helps: https://github.com/PX4/Firmware/pull/14259/commits/1f97debf3b8e40d8e2cf91dae2a2acfb877f2f23

Are you sure about the file names being in capital letters?

**Comment by dagar** [comment]
> Maybe this helps: [1f97deb](https://github.com/PX4/Firmware/commit/1f97debf3b8e40d8e2cf91dae2a2acfb877f2f23)
> 
> Are you sure about the file names being in capital letters? And I would recommend keeping the constexpr as it had some advantage regarding the final size of the firmware iirc.

Thanks @dayjaby, I'll take a look.

For naming I try to keep things in whatever form is closest to the source. In the Mavlink spec all of the names are uppercase.
 https://mavlink.io/en/messages/common.html#ESC_STATUS

**Comment by dayjaby** [comment]
> > I would recommend keeping the constexpr as it had some advantage regarding the final size of the firmware iirc.
> 
> Where? I didn't intentionally drop it.

Oops, false accusation. You moved the functions down.

About the file names: if you consider my commit, all file names are the lowercase version of the corresponding MAVLink message, so if you consider adding automatic links from MAVLink to PX4 or vice-versa for documentation or whatever, then it's just one function call.

**Comment by dagar** [comment]
> About the file names: if you consider my commit, all file names are the lowercase version of the corresponding MAVLink message, so if you consider adding automatic links from MAVLink to PX4 or vice-versa for documentation or whatever, then it's just one function call.

At the risk of bikeshedding, I guess I just don't see the benefit of having it named differently at all. Anyway, I'd be happy to not repeat the work you've already done. Would you like to open a PR?

**Comment by dagar** [comment]
@dayjaby I'm going to keep going with this, but if you're interested in preserving your changes please open a PR. Feel free to replace the separate headers with yours (I'm fine with the naming either way).

**Pull request merged**
