### PR TITLE
Add missing vibration data to estimator-status uORB topic

### PR DESCRIPTION
**Pull request by priseborough**
Required for  https://github.com/PX4/ecl/pull/203

Flight data was logged using the new ulog format and analysed using the following script https://github.com/priseborough/pyulog/commit/149671fdf8ec1a8192350f5737ec5074a42f8134

Here are the vibe levels.

screen shot 2016-10-18 at 5 31 10 pm

Threshold test limits will be added to the analysis script  when more log data is available to set them.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@priseborough Can you rebase on master? Otherwise looking good.

**Comment by priseborough** [comment]
Waiting for the ecl side to be merged first

**Comment by priseborough** [comment]
@LorenzMeier  The ecl PR has been merged and I've rebased this one.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Pull request merged**
