### PR TITLE
Remove mixer for virtual elevator and add pitch control mixer to elevons

### PR DESCRIPTION
**Pull request by lum-supakorn**
**Describe problem solved by this pull request**
This PR, together with [this one](https://github.com/PX4/sitl_gazebo/pull/521), allows the tailsitter SITL model to fly without a virtual elevator (pitch control is handled by the elevons, just like real life).

**Describe your solution**
This was done by implementing the effect of the elevon to the pitching moment of a wing. The code that made this possible is in [sitl_gazebo](https://github.com/PX4/sitl_gazebo) (awaiting PR merge), but the mixer file in the repo needed modifications as well.

**Describe possible alternatives**
No alternatives.

**Test data / coverage**
The flight log for tailsitter SITL MR takeoff, FW loiter, MR return to home, and MR land can be found [here](https://review.px4.io/plot_app?log=9ce700e6-aa23-4d41-9834-9047aed8601d). Before this commit, this flight wouldn't be possible without a virtual elevator.

**Additional context**
The reference airfoil is MH60 with 0% static margin analyzed with XFLR5 VLM2. Additional information can be found [here](https://aviation.stackexchange.com/questions/78908/is-there-any-non-experimental-way-to-obtain-cl-cd-and-cm-as-a-function-of-the).

### CODE REVIEW

**Comment by lum-supakorn** [comment]
@xdwgood The model should still have 4 rotors for attitude and position control in the MR mode. I'm working on modeling slipstream dynamics similar to that in the [PhoenixDrone project](https://github.com/utiasSTARS/PhoenixDrone) so that we can use dual-rotor models. But for now the current tailsitter model need 4 rotors.

**Comment by xdwgood** [comment]
@lum-supakorn  thank you
So, I can understand that this pr solves the simulation error(pitch control is handled by the elevons) of tailsitter drone in fixed-wing mode?

**Comment by lum-supakorn** [comment]
@xdwgood Yes. This PR and [this one](https://github.com/PX4/sitl_gazebo/pull/521) makes the actuators of the quad-rotor tailsitter model (`gazebo_tailsitter`) more realistic.

**Comment by lum-supakorn** [comment]
@Jaeyoung-Lim Wonderful observation! I have reduced `MC_PITCH_P` from the default value of 6 to 5 and the vibration metric drops to the green zone during transition from FW to MR. `MC_PITCH_P` of 4 seems to be a little worse than `MC_PITCH_P` of 5.

**Flight logs:**
- [Pitch P gain of 6](https://review.px4.io/plot_app?log=f511e53d-bf79-4bba-bb1e-c4a832ad6cb8)
- [Pitch P gain of 5](https://review.px4.io/plot_app?log=f3b196e4-db05-4531-b114-e6350394ee03)
- [Pitch P gain of 4](https://review.px4.io/plot_app?log=94ec4192-2636-4ed5-a2f6-7d744d21960f)

Is the current vibrational performance satisfactory (pitch P gain of 5), or can we reduce the vibration further?

**Comment by Jaeyoung-Lim** [comment]
@lum-supakorn I think the overshoot is actually coming more from the pitch rate gains (e.g. `MC_PITCHRATE_P `) - See the oscillations in the pitch rate.

Otherwise I think this is good to go.

**Comment by lum-supakorn** [comment]
@Jaeyoung-Lim I have tried adjusting `MC_PITCHRATE_P` but it didn't help that much. Reducing `MC_PITCH_P` resulted in much less pitch rate vibration.

**Flight logs:**
- [Pitch rate P gain of 0.15](https://review.px4.io/plot_app?log=b8711058-0bad-4b45-93a2-0ed48ceb8e1a)
- [Pitch rate P gain 0f 0.1](https://review.px4.io/plot_app?log=8dcd592e-b833-4f34-a9f7-837203d06103)
- [Pitch rate P gain of 0.05](https://review.px4.io/plot_app?log=c790cb3b-dd5d-4d15-8c8e-4bdf70d89279)

**Comment by Jaeyoung-Lim** [comment]
@lum-supakorn Any chance that the deflection-moment (cm_delta) is too large?

**Comment by lum-supakorn** [comment]
@Jaeyoung-Lim You're absolutely right. Reducing `cm_delta` from `-0.573` to `-0.3` eliminates the vibration during back transition (the PID gains are the same). Here is the [flight log.](https://review.px4.io/plot_app?log=f7431e2d-f206-44ce-a1a4-2c9f00dbfefd) The vibration metric during back transition is now below 2e-3.

**Comment by Jaeyoung-Lim** [comment]
@lum-supakorn Awesome, thanks. Could you update this on https://github.com/PX4/sitl_gazebo/pull/521? Then it should be good to go

**Comment by lum-supakorn** [comment]
@Jaeyoung-Lim Could you please merge this one as well? Without this mixer change the merged tailsitter model would not work.

**Comment by TSC21** [comment]
This also requires a subsequent `sitl_gazebo` submodule update, also in order to test these changes in CI.

**Pull request merged**
