### PR TITLE
Missing zero in timesync

### PR DESCRIPTION
**Pull request by mhkabir**
Sorry about this. Missing a zero. Never caught this out before as I didn't put the Pixhawk in the fridge :smiling_imp:

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Could you suffix these constants please with LL to make them an int64? thanks!

**Comment by LorenzMeier** [comment]
And please rebase on master if you haven't already - we're trying to cut down the number of merge commits as far as possible to avoid a non-linear history whenever possible.

**Comment by mhkabir** [comment]
Ok. Alright.

Something is still wrong. I tested, and sync keeps resetting. Let me look into this a bit later when I'm free.

Oh, and this is already on master.

**Comment by mhkabir** [comment]
@LorenzMeier Done. Please merge.

**Pull request merged**
