### PR TITLE
[WIP] NXP UCANS32K PWM support

### PR DESCRIPTION
**Pull request by jarivanewijk**
@igalloway asked me to try enable PWM output for the NXP S32K1XX platform and specifically the NXP UCANS32K can node board. The build for this board was completely stripped and only has some of the basic components of PX4. The upcoming revision of the board will have a dedicated PWM/servo header so we would like to re-enable the relevant components to support this PWM output.

The platform-specific code does not seem to be the most straightforward and well documented part of PX4, so I'm having some issues figuring out how everything is related and what parts are still missing. Luckily, @davids5 pointed me in the right direction a few weeks ago. However, some additional guidance would be really appreciated. The time I can spend on this is very limited, so I would rather be writing code than figuring out how everything fits together.

What is included right now:
- The high resolution timer can now be configured to use any channel of any FlexTimer peripheral. I put it on FTM5, because we don't use that one for anything else right now. The initial version of the HRT was adapted from the Kinetis platform by @PetervdPerk-NXP. However the amount of FlexTimer peripherals and channels per timer has been significantly expanded on S32K1XX.
- An initial attempt at a timer_config. We only need one timer/channel for the PWM servo header (which is not on the current board yet, so I used a different timer/channel for now).
- I started adapting some of the other timer files. They were copied from the Kinetis platform which also uses the FlexTimer peripheral, but we will need to make some changes. An interesting one is that the S32K1XX now has 6 separate interrupts per FlexTimer peripheral, while there was only one for Kinetis.

Note: This depends on changes to the S32K1XX architecture in NuttX that are in https://github.com/PX4/NuttX/pull/102

So I understand am not there yet. It's not yet possible to build the firmware for UCANS32K with the pwm_out driver enabled. I think it complains about invalid or missing values for some parameters. Probably makes sense because as far as I know the parameter subsystem is not even operational right now. So maybe we need to get that working first...?

### CODE REVIEW

**Comment by jarivanewijk** [comment]
It builds without errors when the pwm_out driver is disabled. However when I uncomment it in the rddrone-uavcan146 default.cmake file, I get errors when it tries to build the mixer module. Something about a parameter MOT_SLEW_MAX missing? I'm not sure why this is missing and how to add it.

```
[275/316] Building CXX object src/lib/mixer_module/CMakeFiles/mixer_module.dir/mixer_module.cpp.obj
FAILED: src/lib/mixer_module/CMakeFiles/mixer_module.dir/mixer_module.cpp.obj 
/usr/bin/ccache /opt/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-g++  -DAPP_VERSION_MAJOR=0 -DAPP_VERSION_MINOR=1 -DCONFIG_ARCH_BOARD_NXP_RDDRONE_UAVCAN146 -DHW_UAVCAN_NAME=\"org.nxp.rddrone-uavcan146\" -DHW_VERSION_MAJOR=1 -DHW_VERSION_MINOR=0 -DMODULE_NAME=\"mixer_module\" -D_SYS_CDEFS_H_ -D_SYS_REENT_H_ -D__CUSTOM_FILE_IO__ -D__PX4_NUTTX -D__STDC_FORMAT_MACROS -I../../boards/nxp/rddrone-uavcan146/src -I../../platforms/nuttx/src/px4/common/include -I. -Isrc/lib -I../../platforms/nuttx/src/px4/nxp/s32k14x/include -I../../platforms/common/include -I../../src -I../../src/include -I../../src/lib -I../../src/lib/matrix -I../../src/modules -INuttX/nuttx/arch/arm/src/armv7-m -INuttX/nuttx/arch/arm/src/chip -INuttX/nuttx/arch/arm/src/common -INuttX/apps/include -Iexternal/Install/include -isystem ../../platforms/nuttx/NuttX/include/cxx -isystem NuttX/nuttx/include/cxx -isystem NuttX/nuttx/include -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -Os -DNDEBUG   -g -fdata-sections -ffunction-sections -fomit-frame-pointer -fmerge-all-constants -fno-signed-zeros -fno-trapping-math -freciprocal-math -fno-math-errno -fno-strict-aliasing -fvisibility=hidden -include visibility.h -Wall -Wextra -Werror -Warray-bounds -Wcast-align -Wdisabled-optimization -Wdouble-promotion -Wfatal-errors -Wfloat-equal -Wformat-security -Winit-self -Wlogical-op -Wpointer-arith -Wshadow -Wuninitialized -Wunknown-pragmas -Wunused-variable -Wno-missing-field-initializers -Wno-missing-include-dirs -Wno-unused-parameter -fdiagnostics-color=always -fno-builtin-printf -fno-strength-reduce -Wformat=1 -Wunused-but-set-variable -Wno-format-truncation -fcheck-new -fno-exceptions -fno-rtti -fno-threadsafe-statics -Wreorder -Wno-overloaded-virtual -nostdinc++ -fno-sized-deallocation -std=gnu++14 -MD -MT src/lib/mixer_module/CMakeFiles/mixer_module.dir/mixer_module.cpp.obj -MF src/lib/mixer_module/CMakeFiles/mixer_module.dir/mixer_module.cpp.obj.d -o src/lib/mixer_module/CMakeFiles/mixer_module.dir/mixer_module.cpp.obj -c ../../src/lib/mixer_module/mixer_module.cpp
In file included from ../../platforms/common/include/px4_platform_common/param.h:42:0,
                 from ../../platforms/common/include/px4_platform_common/module_params.h:44,
                 from ../../src/lib/mixer_module/mixer_module.hpp:42,
                 from ../../src/lib/mixer_module/mixer_module.cpp:34:
../../src/lib/mixer_module/mixer_module.hpp:276:28: error: 'MOT_SLEW_MAX' is not a member of 'px4::params'
   (ParamFloat<px4::params::MOT_SLEW_MAX>) _param_mot_slew_max,
                            ^
../../platforms/common/include/px4_platform_common/param_macros.h:239:18: note: in definition of macro 'REM'
 #define REM(...) __VA_ARGS__
                  ^~~~~~~~~~~
../../platforms/common/include/px4_platform_common/param.h:58:40: note: in expansion of macro 'PAIR'
  do_not_explicitly_use_this_namespace::PAIR(x);
                                        ^~~~
../../platforms/common/include/px4_platform_common/param_macros.h:47:46: note: in expansion of macro '_DEFINE_SINGLE_PARAMETER'
 #define APPLY4(t, aaa, aab, aac, aad) t(aaa) t(aab) t(aac) t(aad)
                                              ^
../../platforms/common/include/px4_platform_common/param_macros.h:197:33: note: in expansion of macro 'APPLY4'
 #define APPLY_ALL_H3(t, n, ...) APPLY##n(t, __VA_ARGS__)
                                 ^~~~~
../../platforms/common/include/px4_platform_common/param_macros.h:198:33: note: in expansion of macro 'APPLY_ALL_H3'
 #define APPLY_ALL_H2(t, n, ...) APPLY_ALL_H3(t, n, __VA_ARGS__)
                                 ^~~~~~~~~~~~
../../platforms/common/include/px4_platform_common/param_macros.h:199:27: note: in expansion of macro 'APPLY_ALL_H2'
 #define APPLY_ALL(t, ...) APPLY_ALL_H2(t, NUM_ARGS(__VA_ARGS__), __VA_ARGS__)
                           ^~~~~~~~~~~~
../../platforms/common/include/px4_platform_common/param.h:79:2: note: in expansion of macro 'APPLY_ALL'
  APPLY_ALL(_DEFINE_SINGLE_PARAMETER, __VA_ARGS__) \
  ^~~~~~~~~
../../src/lib/mixer_module/mixer_module.hpp:274:2: note: in expansion of macro 'DEFINE_PARAMETERS'
  DEFINE_PARAMETERS(
  ^~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
[279/316] Building CXX object src/drivers/pwm_out/CMakeFiles/drivers__pwm_out.dir/PWMOut.cpp.obj
FAILED: src/drivers/pwm_out/CMakeFiles/drivers__pwm_out.dir/PWMOut.cpp.obj 
/usr/bin/ccache /opt/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-g++  -DAPP_VERSION_MAJOR=0 -DAPP_VERSION_MINOR=1 -DCONFIG_ARCH_BOARD_NXP_RDDRONE_UAVCAN146 -DHW_UAVCAN_NAME=\"org.nxp.rddrone-uavcan146\" -DHW_VERSION_MAJOR=1 -DHW_VERSION_MINOR=0 -DMODULE_NAME=\"pwm_out\" -DPX4_MAIN=pwm_out_app_main -D_SYS_CDEFS_H_ -D_SYS_REENT_H_ -D__CUSTOM_FILE_IO__ -D__PX4_NUTTX -D__STDC_FORMAT_MACROS -I../../boards/nxp/rddrone-uavcan146/src -I../../platforms/nuttx/src/px4/common/include -I. -Isrc/lib -I../../platforms/nuttx/src/px4/nxp/s32k14x/include -I../../platforms/common/include -I../../src -I../../src/include -I../../src/lib -I../../src/lib/matrix -I../../src/modules -INuttX/nuttx/arch/arm/src/armv7-m -INuttX/nuttx/arch/arm/src/chip -INuttX/nuttx/arch/arm/src/common -INuttX/apps/include -Iexternal/Install/include -isystem ../../platforms/nuttx/NuttX/include/cxx -isystem NuttX/nuttx/include/cxx -isystem NuttX/nuttx/include -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -Os -DNDEBUG   -g -fdata-sections -ffunction-sections -fomit-frame-pointer -fmerge-all-constants -fno-signed-zeros -fno-trapping-math -freciprocal-math -fno-math-errno -fno-strict-aliasing -fvisibility=hidden -include visibility.h -Wall -Wextra -Werror -Warray-bounds -Wcast-align -Wdisabled-optimization -Wdouble-promotion -Wfatal-errors -Wfloat-equal -Wformat-security -Winit-self -Wlogical-op -Wpointer-arith -Wshadow -Wuninitialized -Wunknown-pragmas -Wunused-variable -Wno-missing-field-initializers -Wno-missing-include-dirs -Wno-unused-parameter -fdiagnostics-color=always -fno-builtin-printf -fno-strength-reduce -Wformat=1 -Wunused-but-set-variable -Wno-format-truncation -fcheck-new -fno-exceptions -fno-rtti -fno-threadsafe-statics -Wreorder -Wno-overloaded-virtual -nostdinc++ -fno-sized-deallocation -Wframe-larger-than=2048 -std=gnu++14 -MD -MT src/drivers/pwm_out/CMakeFiles/drivers__pwm_out.dir/PWMOut.cpp.obj -MF src/drivers/pwm_out/CMakeFiles/drivers__pwm_out.dir/PWMOut.cpp.obj.d -o src/drivers/pwm_out/CMakeFiles/drivers__pwm_out.dir/PWMOut.cpp.obj -c ../../src/drivers/pwm_out/PWMOut.cpp
In file included from ../../platforms/common/include/px4_platform_common/param.h:42:0,
                 from ../../platforms/common/include/px4_platform_common/module_params.h:44,
                 from ../../src/lib/mixer_module/mixer_module.hpp:42,
                 from ../../src/drivers/pwm_out/PWMOut.hpp:48,
                 from ../../src/drivers/pwm_out/PWMOut.cpp:34:
../../src/lib/mixer_module/mixer_module.hpp:276:28: error: 'MOT_SLEW_MAX' is not a member of 'px4::params'
   (ParamFloat<px4::params::MOT_SLEW_MAX>) _param_mot_slew_max,
                            ^
../../platforms/common/include/px4_platform_common/param_macros.h:239:18: note: in definition of macro 'REM'
 #define REM(...) __VA_ARGS__
                  ^~~~~~~~~~~
../../platforms/common/include/px4_platform_common/param.h:58:40: note: in expansion of macro 'PAIR'
  do_not_explicitly_use_this_namespace::PAIR(x);
                                        ^~~~
../../platforms/common/include/px4_platform_common/param_macros.h:47:46: note: in expansion of macro '_DEFINE_SINGLE_PARAMETER'
 #define APPLY4(t, aaa, aab, aac, aad) t(aaa) t(aab) t(aac) t(aad)
                                              ^
../../platforms/common/include/px4_platform_common/param_macros.h:197:33: note: in expansion of macro 'APPLY4'
 #define APPLY_ALL_H3(t, n, ...) APPLY##n(t, __VA_ARGS__)
                                 ^~~~~
../../platforms/common/include/px4_platform_common/param_macros.h:198:33: note: in expansion of macro 'APPLY_ALL_H3'
 #define APPLY_ALL_H2(t, n, ...) APPLY_ALL_H3(t, n, __VA_ARGS__)
                                 ^~~~~~~~~~~~
../../platforms/common/include/px4_platform_common/param_macros.h:199:27: note: in expansion of macro 'APPLY_ALL_H2'
 #define APPLY_ALL(t, ...) APPLY_ALL_H2(t, NUM_ARGS(__VA_ARGS__), __VA_ARGS__)
                           ^~~~~~~~~~~~
../../platforms/common/include/px4_platform_common/param.h:79:2: note: in expansion of macro 'APPLY_ALL'
  APPLY_ALL(_DEFINE_SINGLE_PARAMETER, __VA_ARGS__) \
  ^~~~~~~~~
../../src/lib/mixer_module/mixer_module.hpp:274:2: note: in expansion of macro 'DEFINE_PARAMETERS'
  DEFINE_PARAMETERS(
  ^~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
ninja: build stopped: subcommand failed.
Makefile:198: recipe for target 'nxp_rddrone-uavcan146_default' failed
make: *** [nxp_rddrone-uavcan146_default] Error 1
```

**Comment by davids5** [comment]
> It builds without errors when the pwm_out driver is disabled. However when I uncomment it in the rddrone-uavcan146 default.cmake file, I get errors when it tries to build the mixer module. Something about a parameter MOT_SLEW_MAX missing? I'm not sure why this is missing and how to add it.
> 
> ```
> [275/316] Building CXX object src/lib/mixer_module/CMakeFiles/mixer_module.dir/mixer_module.cpp.obj
> FAILED: src/lib/mixer_module/CMakeFiles/mixer_module.dir/mixer_module.cpp.obj 
> /usr/bin/ccache /opt/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-g++  -DAPP_VERSION_MAJOR=0 -DAPP_VERSION_MINOR=1 -DCONFIG_ARCH_BOARD_NXP_RDDRONE_UAVCAN146 -DHW_UAVCAN_NAME=\"org.nxp.rddrone-uavcan146\" -DHW_VERSION_MAJOR=1 -DHW_VERSION_MINOR=0 -DMODULE_NAME=\"mixer_module\" -D_SYS_CDEFS_H_ -D_SYS_REENT_H_ -D__CUSTOM_FILE_IO__ -D__PX4_NUTTX -D__STDC_FORMAT_MACROS -I../../boards/nxp/rddrone-uavcan146/src -I../../platforms/nuttx/src/px4/common/include -I. -Isrc/lib -I../../platforms/nuttx/src/px4/nxp/s32k14x/include -I../../platforms/common/include -I../../src -I../../src/include -I../../src/lib -I../../src/lib/matrix -I../../src/modules -INuttX/nuttx/arch/arm/src/armv7-m -INuttX/nuttx/arch/arm/src/chip -INuttX/nuttx/arch/arm/src/common -INuttX/apps/include -Iexternal/Install/include -isystem ../../platforms/nuttx/NuttX/include/cxx -isystem NuttX/nuttx/include/cxx -isystem NuttX/nuttx/include -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -Os -DNDEBUG   -g -fdata-sections -ffunction-sections -fomit-frame-pointer -fmerge-all-constants -fno-signed-zeros -fno-trapping-math -freciprocal-math -fno-math-errno -fno-strict-aliasing -fvisibility=hidden -include visibility.h -Wall -Wextra -Werror -Warray-bounds -Wcast-align -Wdisabled-optimization -Wdouble-promotion -Wfatal-errors -Wfloat-equal -Wformat-security -Winit-self -Wlogical-op -Wpointer-arith -Wshadow -Wuninitialized -Wunknown-pragmas -Wunused-variable -Wno-missing-field-initializers -Wno-missing-include-dirs -Wno-unused-parameter -fdiagnostics-color=always -fno-builtin-printf -fno-strength-reduce -Wformat=1 -Wunused-but-set-variable -Wno-format-truncation -fcheck-new -fno-exceptions -fno-rtti -fno-threadsafe-statics -Wreorder -Wno-overloaded-virtual -nostdinc++ -fno-sized-deallocation -std=gnu++14 -MD -MT src/lib/mixer_module/CMakeFiles/mixer_module.dir/mixer_module.cpp.obj -MF src/lib/mixer_module/CMakeFiles/mixer_module.dir/mixer_module.cpp.obj.d -o src/lib/mixer_module/CMakeFiles/mixer_module.dir/mixer_module.cpp.obj -c ../../src/lib/mixer_module/mixer_module.cpp
> In file included from ../../platforms/common/include/px4_platform_common/param.h:42:0,
>                  from ../../platforms/common/include/px4_platform_common/module_params.h:44,
>                  from ../../src/lib/mixer_module/mixer_module.hpp:42,
>                  from ../../src/lib/mixer_module/mixer_module.cpp:34:
> ../../src/lib/mixer_module/mixer_module.hpp:276:28: error: 'MOT_SLEW_MAX' is not a member of 'px4::params'
>    (ParamFloat<px4::params::MOT_SLEW_MAX>) _param_mot_slew_max,
>                             ^
> ../../platforms/common/include/px4_platform_common/param_macros.h:239:18: note: in definition of macro 'REM'
>  #define REM(...) __VA_ARGS__
>                   ^~~~~~~~~~~
> ../../platforms/common/include/px4_platform_common/param.h:58:40: note: in expansion of macro 'PAIR'
>   do_not_explicitly_use_this_namespace::PAIR(x);
>                                         ^~~~
> ../../platforms/common/include/px4_platform_common/param_macros.h:47:46: note: in expansion of macro '_DEFINE_SINGLE_PARAMETER'
>  #define APPLY4(t, aaa, aab, aac, aad) t(aaa) t(aab) t(aac) t(aad)
>                                               ^
> ../../platforms/common/include/px4_platform_common/param_macros.h:197:33: note: in expansion of macro 'APPLY4'
>  #define APPLY_ALL_H3(t, n, ...) APPLY##n(t, __VA_ARGS__)
>                                  ^~~~~
> ../../platforms/common/include/px4_platform_common/param_macros.h:198:33: note: in expansion of macro 'APPLY_ALL_H3'
>  #define APPLY_ALL_H2(t, n, ...) APPLY_ALL_H3(t, n, __VA_ARGS__)
>                                  ^~~~~~~~~~~~
> ../../platforms/common/include/px4_platform_common/param_macros.h:199:27: note: in expansion of macro 'APPLY_ALL_H2'
>  #define APPLY_ALL(t, ...) APPLY_ALL_H2(t, NUM_ARGS(__VA_ARGS__), __VA_ARGS__)
>                            ^~~~~~~~~~~~
> ../../platforms/common/include/px4_platform_common/param.h:79:2: note: in expansion of macro 'APPLY_ALL'
>   APPLY_ALL(_DEFINE_SINGLE_PARAMETER, __VA_ARGS__) \
>   ^~~~~~~~~
> ../../src/lib/mixer_module/mixer_module.hpp:274:2: note: in expansion of macro 'DEFINE_PARAMETERS'
>   DEFINE_PARAMETERS(
>   ^~~~~~~~~~~~~~~~~
> compilation terminated due to -Wfatal-errors.
> [279/316] Building CXX object src/drivers/pwm_out/CMakeFiles/drivers__pwm_out.dir/PWMOut.cpp.obj
> FAILED: src/drivers/pwm_out/CMakeFiles/drivers__pwm_out.dir/PWMOut.cpp.obj 
> /usr/bin/ccache /opt/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-g++  -DAPP_VERSION_MAJOR=0 -DAPP_VERSION_MINOR=1 -DCONFIG_ARCH_BOARD_NXP_RDDRONE_UAVCAN146 -DHW_UAVCAN_NAME=\"org.nxp.rddrone-uavcan146\" -DHW_VERSION_MAJOR=1 -DHW_VERSION_MINOR=0 -DMODULE_NAME=\"pwm_out\" -DPX4_MAIN=pwm_out_app_main -D_SYS_CDEFS_H_ -D_SYS_REENT_H_ -D__CUSTOM_FILE_IO__ -D__PX4_NUTTX -D__STDC_FORMAT_MACROS -I../../boards/nxp/rddrone-uavcan146/src -I../../platforms/nuttx/src/px4/common/include -I. -Isrc/lib -I../../platforms/nuttx/src/px4/nxp/s32k14x/include -I../../platforms/common/include -I../../src -I../../src/include -I../../src/lib -I../../src/lib/matrix -I../../src/modules -INuttX/nuttx/arch/arm/src/armv7-m -INuttX/nuttx/arch/arm/src/chip -INuttX/nuttx/arch/arm/src/common -INuttX/apps/include -Iexternal/Install/include -isystem ../../platforms/nuttx/NuttX/include/cxx -isystem NuttX/nuttx/include/cxx -isystem NuttX/nuttx/include -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -Os -DNDEBUG   -g -fdata-sections -ffunction-sections -fomit-frame-pointer -fmerge-all-constants -fno-signed-zeros -fno-trapping-math -freciprocal-math -fno-math-errno -fno-strict-aliasing -fvisibility=hidden -include visibility.h -Wall -Wextra -Werror -Warray-bounds -Wcast-align -Wdisabled-optimization -Wdouble-promotion -Wfatal-errors -Wfloat-equal -Wformat-security -Winit-self -Wlogical-op -Wpointer-arith -Wshadow -Wuninitialized -Wunknown-pragmas -Wunused-variable -Wno-missing-field-initializers -Wno-missing-include-dirs -Wno-unused-parameter -fdiagnostics-color=always -fno-builtin-printf -fno-strength-reduce -Wformat=1 -Wunused-but-set-variable -Wno-format-truncation -fcheck-new -fno-exceptions -fno-rtti -fno-threadsafe-statics -Wreorder -Wno-overloaded-virtual -nostdinc++ -fno-sized-deallocation -Wframe-larger-than=2048 -std=gnu++14 -MD -MT src/drivers/pwm_out/CMakeFiles/drivers__pwm_out.dir/PWMOut.cpp.obj -MF src/drivers/pwm_out/CMakeFiles/drivers__pwm_out.dir/PWMOut.cpp.obj.d -o src/drivers/pwm_out/CMakeFiles/drivers__pwm_out.dir/PWMOut.cpp.obj -c ../../src/drivers/pwm_out/PWMOut.cpp
> In file included from ../../platforms/common/include/px4_platform_common/param.h:42:0,
>                  from ../../platforms/common/include/px4_platform_common/module_params.h:44,
>                  from ../../src/lib/mixer_module/mixer_module.hpp:42,
>                  from ../../src/drivers/pwm_out/PWMOut.hpp:48,
>                  from ../../src/drivers/pwm_out/PWMOut.cpp:34:
> ../../src/lib/mixer_module/mixer_module.hpp:276:28: error: 'MOT_SLEW_MAX' is not a member of 'px4::params'
>    (ParamFloat<px4::params::MOT_SLEW_MAX>) _param_mot_slew_max,
>                             ^
> ../../platforms/common/include/px4_platform_common/param_macros.h:239:18: note: in definition of macro 'REM'
>  #define REM(...) __VA_ARGS__
>                   ^~~~~~~~~~~
> ../../platforms/common/include/px4_platform_common/param.h:58:40: note: in expansion of macro 'PAIR'
>   do_not_explicitly_use_this_namespace::PAIR(x);
>                                         ^~~~
> ../../platforms/common/include/px4_platform_common/param_macros.h:47:46: note: in expansion of macro '_DEFINE_SINGLE_PARAMETER'
>  #define APPLY4(t, aaa, aab, aac, aad) t(aaa) t(aab) t(aac) t(aad)
>                                               ^
> ../../platforms/common/include/px4_platform_common/param_macros.h:197:33: note: in expansion of macro 'APPLY4'
>  #define APPLY_ALL_H3(t, n, ...) APPLY##n(t, __VA_ARGS__)
>                                  ^~~~~
> ../../platforms/common/include/px4_platform_common/param_macros.h:198:33: note: in expansion of macro 'APPLY_ALL_H3'
>  #define APPLY_ALL_H2(t, n, ...) APPLY_ALL_H3(t, n, __VA_ARGS__)
>                                  ^~~~~~~~~~~~
> ../../platforms/common/include/px4_platform_common/param_macros.h:199:27: note: in expansion of macro 'APPLY_ALL_H2'
>  #define APPLY_ALL(t, ...) APPLY_ALL_H2(t, NUM_ARGS(__VA_ARGS__), __VA_ARGS__)
>                            ^~~~~~~~~~~~
> ../../platforms/common/include/px4_platform_common/param.h:79:2: note: in expansion of macro 'APPLY_ALL'
>   APPLY_ALL(_DEFINE_SINGLE_PARAMETER, __VA_ARGS__) \
>   ^~~~~~~~~
> ../../src/lib/mixer_module/mixer_module.hpp:274:2: note: in expansion of macro 'DEFINE_PARAMETERS'
>   DEFINE_PARAMETERS(
>   ^~~~~~~~~~~~~~~~~
> compilation terminated due to -Wfatal-errors.
> ninja: build stopped: subcommand failed.
> Makefile:198: recipe for target 'nxp_rddrone-uavcan146_default' failed
> make: *** [nxp_rddrone-uavcan146_default] Error 1
> ```

@jarivanewijk Thank you for all your work! I will have a look at this by mid next week. I will upstream the NuttX work, back port what is need be and finish this branch.

**Comment by jarivanewijk** [comment]
@davids5 Thanks! Please let me know if there is anything I can do.

I came across a few things in the code that might need some extra effort. I started keeping a list of these things, to look at again later.

* Duplication of definitions of the FlexTimer base address:
/platforms/nuttx/src/px4/nxp/s32k1xx/include/px4_arch/hw_description.h (+/- line 80)
/platforms/nuttx/src/px4/nxp/s32k1xx/include/px4_arch/io_timer_hw_description.h (+/- line 150)

* The code that maps a port and pin number to the right pinmux setting for a FlexTimer channel is complex and difficult to check. It is not complete and it might not even work for all MCUs in the S32K1XX family. It might have worked for Kinetis, because it has a simpler FlexTimer setup (less timers and channels), but I think we need a different solution for S32K.
/platforms/nuttx/src/px4/nxp/s32k1xx/include/px4_arch/io_timer_hw_description.h (+/- line 60)

* There are "register accessor" macros defined in multiple files that use FlexTimer. These are just copied between files. We should consider adding some additional macros to hardware/s32k1xx_ftm.h in NuttX, to avoid duplication.
/platforms/nuttx/src/px4/nxp/s32k1xx/hrt/hrt.c
/platforms/nuttx/src/px4/nxp/s32k1xx/io_pins/io_timer.c
/platforms/nuttx/src/px4/nxp/s32k1xx/led_pwm/led_pwm.cpp
… probably more?

* I added some "TO DO" comments of my own, but I also found many that were already in the code. Probably left in there when you were developing the code for the Kinetis.

**Comment by PetervdPerk-NXP** [comment]
Please note that this PR the C++ initialized variables is broken (they're stuck to zero). In this other PR it's fixed by changing the linker script https://github.com/PX4/Firmware/commit/820ae6631b9fe7b15c321fa7c274d613f0e80270#diff-c08a6348bd22f1a64eb3b8f4160623f0

**Comment by davids5** [comment]
Thank you @PetervdPerk-NXP, for the linker fix. This PR is on my next week's to do list. 

On the C++ static initializers we need to ensure static class initialization is not needed before board_app_initialize is called. That is: no C++ code is called prior to board_app_initialize.

**Comment by davids5** [comment]
@jarivanewijk  My apologies on this taking so long. You did all the heavy lifting and and you did it very well! Thank you! 

Continued here https://github.com/PX4/Firmware/pull/15850

**Pull request closed without merging**
