### PR TITLE
improve mavlink set_attitude_target handling

### LINKED ISSUE #1921: Mavlink receiver: fix attitude sp logic
Port https://github.com/PX4/Firmware/pull/1920 to mavlink receiver

### PR DESCRIPTION
**Pull request by thomasgubler**
port #1920 to mavlink_receiver
fixes #1921 

untested

@AndreasAntener please review

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I did a forced update to re-trigger the CI tools. They should be behaving now again.

**Comment by LorenzMeier** [comment]
@AndreasAntener Good to go?

**Comment by AndreasAntener** [comment]
Looks ok. Isn't there someone who does attitude control? ;)

**Comment by AndreasAntener** [comment]
@dvorak0 did a test with this.
> I've pulled #1983 locally. During my test(set attitude and thrust through mavros) it works well. Maybe it's time to merge it.

**Comment by LorenzMeier** [comment]
@thomasgubler Could you rebase and apply this to master? Thanks!

**Comment by LorenzMeier** [comment]
Applied, closing, thanks!

**Pull request closed without merging**
