### PR TITLE
This kills some annoying processes that might still be around.

### PR DESCRIPTION
**Pull request by jgoppert**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
We have more than one Java tool, so not sure this is a good idea.

**Comment by jgoppert** [comment]
Yeah, it would be nice if the process name for jmavsim was jmavsim instead of java. Any chance we can do that @DrTon .

**Comment by jgoppert** [comment]
@DrTon  I think this latest commit accomplishes what I wanted, so don't worry about it.

**Comment by LorenzMeier** [comment]
Applied via rebase, thanks!

**Pull request closed without merging**
