### PR TITLE
WIP: Runway takeoff and landing with terrain estimator

### LINKED ISSUE #2844: FW auto landing with range finder
Tested auto landing with lidar lite range finder.
In general auto landing worked but the terrain altitude estimate from the ekf stays constant at the inititial value. Looks like the range state of the ekf is always zero.
Is there some parameter which I have overseen?

Log:
http://logs.uaventure.com/view/LRaKGWPLiPz6e34wwsi3jn

### LINKED ISSUE #2964: FW auto takeoff and landing on runway
This should sum up the last TODO/issues that need to be taken care of before we merge runway takeoff and runway landing with terrain estimator.

There is a new branch with the state we flew today: https://github.com/PX4/Firmware/tree/runway_takeoff_before

All in all it worked really well!

**TODOs:**
- [x] steer on the ground after landing, including using rudder from the flaring point (and use the navigator with a virtual waypoint ahead, like for takeoff and posctl)
- [x] parameter for target landing airspeed (factor)
- [x] do a proper groundspeed scaling for the wheel controller
- [x] add flaps (could also be done later)
- [x] rename AERTW mixer and update comments

**Optional / second iteration**
- [ ] 2 step flaps (a: at second last waypoint, b: on slope)

**Issues:**
- [x] after landing it throttles up again for a brief moment
- [ ] the switch to mission has to be really fast for the takeoff to work, if assisted is triggered in between it doesn't work
- [x] fix issues reported on old runway PR
- [ ] in manual, flaps are set 50% when RC switches are not assigned
- [x] starting point for navigation on takeoff with WP heading is wrong
- [x] navigation with virtual heading results in a heading that points more north or south (same calculation as for posctl, open a separate issue)
- [x] integrator for wheel controller is reset as well during takeoff, reset must be separated
- [ ] after climbout, TECS pitches down first before it starts tracking altitude again
- [x] terrain altitude valid flag was set to true although laser had no values anymore

**Issues in existing code**
- [x] disabling navigation on landing happens too early and is triggered by WP distance instead of height (land_heading_hold_horizontal_distance)
- [x] rudder has non-zero output in stabilized, not sure where this comes from yet
- [x] some condition makes the plane fly over the landing slope but not descend
(this was caused by the terrain estimate being used although it was wrong. the range finder had a timeout and the valid flag was not set to false.)
- [x] during a landing the fixed wing position controller always sticks to using the terrain estimate if enabled even if the estimate is not valid any more. This has to be rethought because if the estimate is just wrong then the landing won't be nice. Either we switch back to using the normal estimate based on gps and baro or we handle this as failure and do e.g a climbout.
See here https://github.com/PX4/Firmware/blob/master/src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp#L966
@thomasgubler What do you think?

@tumbili please update if I forgot things

### PR DESCRIPTION
**Pull request by AndreasAntener**
@tumbili new branch, let's push everything here now.

Fixes #2964, fixes #2844

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@AndreasAntener I have verified the current state of master: There was an issue with high CPU load which I have fixed, and there seems to be a potential bug in the PWM input driver. There are no reports of issues with master when no Lidar-Lite is connected.

The PWM input hasn't seen any relevant changes according to my code review, so I suspect that master is exposing a race condition which was present all along, but because we never were at maximum load before it didn't show.

**Comment by AndreasAntener** [comment]
Thanks! We can take #2968 in then for another test. We noticed the high EKF load as well but it still had enough margin (we thought).

**Comment by LorenzMeier** [comment]
It didn't have enough margin because on arming the logging will draw another 20%, plus the failed PWM driver consumed another 27% - so you were flat out.

**Comment by tumbili** [comment]
@AndreasAntener @SimonWilks Good morning guys. Just pushed all the changes to this branch, sorry for being that late. Once I'm at the office we can bench test this, especially the flaps and the flaperons. We can use switches in manual mode to make sure that everything is moving in the right direction. The changes are the following:
1) Flaps are engaged as soon as the waypoint previous to the landing waypoint is reached. The pos controller sets a flag to let the attitude controller know that he should apply the flaps. I might add some code to make the flaps being added continuously, looks much  better and gives the attitude controller more time to compensate pitching moment via the integrator.
The mixer for the ailerons had to be divided into two parts since we cannot use one Y cable for two servos anymore.

2) As soon as the plane enters flaring stage the wheel controller is activated by the pos controller.
The desired yaw is taken to be heading between the last waypoint and the landing waypoint.

3) I added the parameter "airspeed_scale" which is multiplied by min_airspeed to get the takeoff/landing speed. The only thing left there is to also use it for the takeoff code which I haven't done yet. So today we can also experiment with slightly different airspeeds for the landing approach.

**Comment by tumbili** [comment]
@AndreasAntener @SimonWilks Also as I mentioned before I had a look at the throttle rise problem after landing. I believe if we set the parameter "FW_LND_THROTTLE_MAX" to 0 or some small value then we should be fine. This parameter was 1 until now.

**Comment by tumbili** [comment]
@AndreasAntener Hi Ada, rushing off now! I added functions in geo.c which allow to compute waypoints on a line correctly. If you want you can have a look at that and see if you can find an error.
Ideally, we can test it in HIL quickly. It's the second last commit and I'm using the functionality in the last commit. See you soon :-)

**Comment by tumbili** [comment]
@SimonWilks Could you upload the last shaky video of the auto landing from yesterday :-)

**Comment by SimonWilks** [comment]
- Takeoff: https://youtu.be/1iBM0kUG4dI
- Landing 1 with 10m/s landing speed and 2.5m flare (quite good actually, the front wheel was just loose): https://youtu.be/MBL0KCpCeBw
- Landing 2 with 11m/s and 2.5m flare: https://youtu.be/rEZTDZ_LzqI

**Comment by LorenzMeier** [comment]
@tumbili This fails on Eigen math in SITL. Can you work around that?

**Comment by LorenzMeier** [comment]
James has a new Matrix lib for this corner case, but I'd like to avoid pulling it in untested: https://github.com/PX4/Firmware/pull/2969

**Comment by AndreasAntener** [comment]
Integrated via #3143

**Pull request closed without merging**
