### PR TITLE
SF20/LW20 Support

### LINKED ISSUE #7899: MC: Add Lightware SF/LW 20 Support
**Feature Request**

Lightware is actually selling a very small and yet powerful (100m Range, 10gr) LIDAR for Altitude Measurements the SF20 (or LW20 that is in a Metall housing and weatherproof) that would be very convenient for UAV usage. It would be nice to have support for this in upcoming PX4 Releases. It is available as Serial and I2C Variant. I prefer the I2C Variant as Serial Interfaces are not easily sharable and scarce if some auxillaries are connected already. As there is I2C Support with the SF1xx Driver already this should not be too hard to implement.

### PR DESCRIPTION
**Pull request by tops4u**
Added basic support for SF20/LW20 I2C connected Lidar from Lightware. 

This would fix #7899

### CODE REVIEW

**Comment by tops4u** [comment]
@dagar Next try, I hope this will be better...

**Comment by TSC21** [comment]
@tops4u does this work out-of-the-box on the I2C bus as is?

**Comment by tops4u** [comment]
@TSC21 yes. The I2C Bus Communication seems to be identical to the previous Models from Lightware. It worked on my AUAV-X2 right away. Most probably it would also work if the correct properties are made to the SF0X Driver for the Serial Connection.

**Comment by TSC21** [comment]
> @TSC21 yes. The I2C Bus Communication seems to be identical to the previous Models from Lightware. It worked on my AUAV-X2 right away. Most probably it would also work if the correct properties are made to the SF0X Driver for the Serial Connection.

Great. One thing I ask you - would you mind updating https://dev.px4.io/en/sensor/sf1xx_lidar_setup.html? So basically would be adding the info about the support for the SF20 and also stating that it should also work with serial. BTW did you try the serial connection and check if it works also? If not, would you mind confirming it? Thanks.

**Comment by TSC21** [comment]
Also CI is failing due to code style. Can you please run `Firmware/Tools/astyle/fix_code_style.sh`?

**Comment by tops4u** [comment]
@TSC21 I'll try to do this today evening. I must see if I can check Serial functionality as well, since my AUAV-X2 is already  somewhat short on serial Interfaces. 
As obvisously I'm net yet very skilled with the PX4 Dev Environment and GIT, can I change a pending PR?

**Comment by dagar** [comment]
Change looks good, but I don't have one of these to test. For serial it should be the same change.

**Comment by tops4u** [comment]
@dagar I'll try to test, but I had some trouble with the Serial Config on my AUAV-X2 in the past. I did not yet Testflight the SF20 Lidar, but I can confirm that the Data gets recognized by PX4 and is Transfered to QGC as DISTANCE MEASUREMENT (AFAIR). I'll try to do a Test flight shortly. As there is not much info, could you tell me where the Distance is taken into consideration in order to keep ground Clearance? PosHold and/or Mission only? I assume in Stabilized it will be ignored?

**Comment by TSC21** [comment]
The `DISTANCE_SENSOR` data is taken into account for position estimation also. So even in Stabilize you will have the sensor readings being fed into the position estimator. @tops4u did you had the chance to test the serial configuration + flight test it?

**Comment by tops4u** [comment]
@TSC21 thanks for you Comment. I assume this the LIDAR Measurement is also fusioned into EKF when EKF2_HGT_MODE is set to Baro or GPS, or does it need to be set to primary? As well as MPC_ALT_MODE will also influence the behaviour. 
I did not yet have the chance for a test flight as I have been busy. I hope for a chance tomorrow (but weather forecast doesn't look too good).

**Comment by tops4u** [comment]
Successfull Test Flight with I2C Connection can be seen here: https://logs.px4.io/plot_app?log=f7673307-89c9-49ac-b1d6-be4e523360f9

Alt Jumps during the Path to the east are due to a full grown Corn field where the lidar was confused by the >2m high Plants. 

Not sure when I can check the Serial Connection, but this would end up in any case in a separate PR.

**Comment by tops4u** [comment]
I just attached it and it started showing Values on MAVLINK Distance. 

I'm still somewhat confuesed about EKF2_HGT_MODE and MPC_ALT_MODE. Despite MPC_ALT_MODE not being set to follow Terrain, it followed terrain when EKF2_HGT_MODE is set to Range Finder. So these two probably influence each other.

**Comment by TSC21** [comment]
> Not sure when I can check the Serial Connection, but this would end up in any case in a separate PR.

Please do it when able. Thanks.

**Pull request merged**
