### PR TITLE
multiplatform: improve param api

### LINKED ISSUE #1710: multiplatform parameters: add similar (C++) abstraction layer as for topics/messages

### PR DESCRIPTION
**Pull request by thomasgubler**
This adds an additonal layer for the parameters in the multiplatform apps. The example subscriber app is fully ported and tested on ROS and NuttX

includes #1754

fixes #1710

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesome!

**Comment by LorenzMeier** [comment]
:shipit:

**Comment by thomasgubler** [comment]
Now the att ctrl and pos ctrl apps use the new param api as well. Tested in sitl and hil. Also most of the multiplatform macros have been removed.

**Comment by thomasgubler** [comment]
@AndreasAntener I just tried again to test with my Ubuntu VM. But gazebo (maybe the VM in general) is too slow to do any serious work. I will attempt to get the docker setup running soon.

In case you find time the merge and ubuntu test order is 

- https://github.com/PX4/euroc_simulator/pull/4 with https://github.com/PX4/Firmware/pull/1754
- independently: 
    - https://github.com/PX4/euroc_simulator/pull/5
    - https://github.com/PX4/Firmware/pull/1763  ( <-- this is this PR here which includes #1754)

**Comment by LorenzMeier** [comment]
@AndreasAntener I've merged PX4/euroc_simulator#4 and #1754, so only PX4/euroc_simulator#5 and this PR remain to be tested.

**Comment by LorenzMeier** [comment]
Sounded like Andreas has tested it - should we merge this?

**Comment by thomasgubler** [comment]
@AndreasAntener did you?

**Comment by AndreasAntener** [comment]
Yes, but to be honest, I compiled it together with https://github.com/PX4/euroc_simulator/pull/5 and ran gazebo_risi_empty_world but I didn't fly with it.

**Comment by LorenzMeier** [comment]
@AndreasAntener If you could fit a quick flight with it today in SITL that would be awesome, as we can merge all of this then!

**Comment by AndreasAntener** [comment]
@LorenzMeier @thomasgubler I can't arm with this anymore.
I tested now the following combination: this branch merged with latest master and px4_nodes from euroc_simulator

**Comment by AndreasAntener** [comment]
Well I guess I mean it doesn't move it's props. The topic /px4_multicopter/actuator_armed gives me the following output when try to arm:
```
timestamp: 40125000
armed: True
ready_to_arm: False
lockdown: False
force_failsafe: False
```
But nothing moves. @thomasgubler this is the same behaviour I had with the script when I didn't publish on /iris/joy. But I'm testing with a real joystick ATM ;)

**Comment by AndreasAntener** [comment]
Just tested PX4/euroc_simulator#4 with #1754 , that combination still worked.

**Comment by AndreasAntener** [comment]
PX4/euroc_simulator#5 with #1754 breaks it

**Comment by AndreasAntener** [comment]
Ok, so this (#1763, merged with current master) together with PX4/euroc_simulator#4 (PX4/euroc_simulator/px4_nodes_upstreammerge2) is working for me.

**Comment by LorenzMeier** [comment]
Many thanks!

**Pull request merged**
