### PR TITLE
RC override enabled by default

### PR DESCRIPTION
**Pull request by MaEtUgR**
**Describe problem solved by the proposed pull request**
As a follow up to https://github.com/PX4/Firmware/pull/12346 I separated enabling RC override by default from the auto disarm default. To implement the suggestion from https://github.com/PX4/Firmware/pull/12346#issuecomment-506960499 I refactored the conditions to be more readable and when I asked @RomanBapst some questions about VTOL and fixed wing and the result was that he doesn't understand why the feature should not be also useful for fixed wing use. Can we discuss that in the dev call tomorrow?

**Additional context**
Mildly related to https://github.com/PX4/Firmware/issues/12361

### CODE REVIEW

**Comment by MaEtUgR** [comment]
We discussed this yesterday in the dev call and realized there were some misunderstandings. The result was that this functionality is only useful for multicopter flying since it's a big safety hazard to accidentally bring a fixed wing out of a mission and fly away in a straight line or into an obstacle. I will adjust the implementation accordingly.

**Comment by MaEtUgR** [comment]
I SITL tested and it works like expected:
- RC override works on multicopter
- RC override works on VTOLs in multicopter mode
- no effect on Planes or VTOLs in fixed wing mode

And the feature is now on by default. Can anyone review?

**Comment by hamishwillee** [comment]
@MaEtUgR 

1. I presume value here of "1" means "enabled"? Certainly worth clarifying that 1 means enabled. Might be worth also providing min, max, increment so that this is forced to 1 or 0. 
  
2. So if you're in auto, land, mission, takeoff, hold, and you move the sticks, then you change to position control mode?

**Comment by MaEtUgR** [comment]
@hamishwillee 
1. The parameter is tagged with `@boolean` in the definition which implies it can only be enabled and disabled. JFYI the actual implementation takes all non-zero values as enabled. Could it be that the automatic parameter reference generation doesn't support the boolean tag as you expect?
2. For multicopters and VTOLs in multicopter mode only the vehicle switches out of any auto mode (the ones you listed) into position mode if it's not in a critical battery action (because you might accidentally switch out) when you clearly move any of the main sticks (x,y,z,yaw).

**Comment by hamishwillee** [comment]
Thanks @MaEtUgR . I've created https://github.com/PX4/Firmware/issues/12546 for the rendering of booleans.

IF someone moves the sticks in hold mode (say), won't their RC control be left in an inconsistent state - where moving back to hold is messy because the switch is in hold mode position while vehicle is in position mode?

**Pull request merged**
