### PR TITLE
use thrust scale parameter for vtol pusher support

### PR DESCRIPTION
**Pull request by AndreasAntener**
Probably got lost in translation..

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Can you rebase on master and see if that fixes CI?

**Comment by AndreasAntener** [comment]
@LorenzMeier Still fails, I don't understand why. I can successfully run the check commands locally

**Comment by dagar** [comment]
Something weird on travis-ci? I restarted the job to see if it's consistent.

**Comment by LorenzMeier** [comment]
Rebased again - lets see.

**Pull request merged**
