### PR TITLE
report preflight check errors

### PR DESCRIPTION
**Pull request by kd0aij**
- [x] report sensor initialization failure
- [x] report low battery voltage lockdown

### CODE REVIEW

**Comment by kd0aij** [comment]
this tests OK on FMUv4

**Comment by LorenzMeier** [comment]
Nice! If you intentionally break the sensor / mag config, does it still report right now? Does it now spam in QGC?

**Comment by kd0aij** [comment]
It reports low battery lockdown each time you attempt to arm.

Since you asked, I rechecked the sensor failure reporting:
It reports a forced sensor init failure correctly at 1Hz, unless a HIL airframe is selected, then it complains that all sensors are uncalibrated. I guess HIL_STATE_OFF is true when you first boot a HIL airframe.

I'm sure I'd rather spam the console than waste time because a failure is not reported, but I'll have to figure out how to suppress the warning for HIL configurations. Perhaps there's a better state indicator for that purpose than HIL_STATE_OFF?

**Comment by LorenzMeier** [comment]
@kd0aij The only way to suppress the HIL message would be to eval the SYS_AUTOSTART param and suppress it accordingly. IIRC we're doing that already, which suggests that the param might be read too late.

**Comment by LorenzMeier** [comment]
Rebased and applied, thanks!

**Pull request closed without merging**
