### PR TITLE
CMake support from @jgoppert and @mcharleb

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by dagar** [comment]
You should consider using the Ninja generator (cmake -GNinja) in the user friendly Makefile wrapper. For big projects like this it's noticeably faster during incremental builds.

**Comment by LorenzMeier** [comment]
@dagar Ninja sounds interesting. I will focus first on making this build all targets successfully, but it would be great if someone could play with Ninja and see where we get. Maybe add a build time counter as a first step, so we see the differences easily?

**Comment by LorenzMeier** [comment]
@jgoppert Can we default to -j or something similar to enable parallel build by default?

**Comment by LorenzMeier** [comment]
@jgoppert Can we condition the ROMFS generation on the last change timestamp of files in there? Right now it doesn't get rebuild if I edit files.

**Comment by LorenzMeier** [comment]
The NuttX boot crashes I'm seeing seem to be related to something generally being wrong with the OS initialisation. Its not something specific to one particular driver / application.

**Comment by LorenzMeier** [comment]
Mac OS SITL CMake config fails from the start now. Its a bit frustrating we have these wild swings still. We might need to add Mac OS to the Travis setup. @dagar Is there a better way to configure the build matrix than using the env variables like you did for QGC?

```
Lorenzs-MacBook-Pro:~/src/Firmware (cmake-2)$ make posix_sitl_simple
mkdir -p /Users/lorenzmeier/src/Firmware/build_posix_sitl_simple && cd /Users/lorenzmeier/src/Firmware/build_posix_sitl_simple && cmake .. -DCONFIG=posix_sitl_simple
CMake Error at cmake/toolchains/Toolchain-native.cmake:6 (message):
  could not find objcopy
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.3.1/share/cmake/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt:141 (project)
```

**Comment by LorenzMeier** [comment]
@mcharleb Mac OS clang does not support aliases, so this here doesn't work. Do you really need this still?
```
extern const struct px4_parameters_t px4_parameters __attribute__((alias("px4_parameters_impl")));
```

**Comment by jgoppert** [comment]
I tested out params on nuttx, nice job @LorenzMeier @mcharleb.

```bash
    EXFW_ROLL_P [-1,658] : 0.2000
    EXFW_PITCH_P [-1,659] : 0.2000
  + RV_YAW_P [-1,660] : 0.2000

 661 parameters total, 7 used.
nsh> param set RV_YAW_P 0.1
+ RV_YAW_P: curr: 0.2000 -> new: 0.1000
nsh> param save
nsh> 
```

**Comment by LorenzMeier** [comment]
Thanks for the cross testing! I did also test it on OS X and NuttX.

**Comment by LorenzMeier** [comment]
@mcharleb Now that params are resolved I would like to get Snapdragon flight support to Travis. We will continue to break the QuRT build if we have no way to perform integration testing constantly.

**Comment by LorenzMeier** [comment]
@mcharleb OS X "almost" works. Publications currently block indefinitely, everything else seems to work.

**Comment by LorenzMeier** [comment]
BTW: I restored the "make posix" and "make sitl_quad" convenience targets.

**Comment by mcharleb** [comment]
@LorenzMeier The HexagonTools are proprietary but available upon request now. If I can get permission to get a copy for Travis CI, how would I make them available to Travis so they are restricted to use in Travis?

**Comment by mcharleb** [comment]
@LorenzMeier I'd rather see "make sitl_quad" be "make run_sitl_quad". When you look at the available make targets its confusing what is a command and what is a build target.

**Comment by mcharleb** [comment]
@LorenzMeier Regarding the use of "alias", I was trying to leave the data as static in case that was important for NuttX and I had no way to test it. Its fine to remove the alias and make px4_marameters global.

**Comment by LorenzMeier** [comment]
@dagar Do you have experience with proprietary tools? Per se the Travis instance's content is not public, only the console output and anything we upload is accessible.

**Comment by dagar** [comment]
@mcharleb You could host it somewhere and encrypt the credentials in travis.

**Comment by LorenzMeier** [comment]
Ok - they are already global now. How do I debug the never-returning advertise / publish call?

**Comment by mcharleb** [comment]
@LorenzMeier the posix build is dead and the error is not so informative. 
```
$ make posix_sitl_simple 
mkdir -p /Dronecode/cmake/Firmware/build_posix_sitl_simple && cd /Dronecode/cmake/Firmware/build_posix_sitl_simple && cmake .. -DCONFIG=posix_sitl_simple
CMake Error at CMakeLists.txt:145 (cmake_policy):
  Policy "CMP0054" is not known to this version of CMake.


-- OS=posix BOARD=sitl LABEL=simple
Scanning source path /Dronecode/cmake/Firmware/src
Creating XML file parameters.xml
All done!
-- GIT_DESC = "e697cabb6ad3c2ac8704aadf22f132b32a095ae5"
-- Configuring incomplete, errors occurred!
See also "/Dronecode/cmake/Firmware/build_posix_sitl_simple/CMakeFiles/CMakeOutput.log".
Makefile:82: recipe for target 'posix_sitl_simple' failed
make: *** [posix_sitl_simple] Error 1
```

**Comment by LorenzMeier** [comment]
@jgoppert That was your policy change. Can we pretty please get back to vanilla CMake as much as possible?

**Comment by mcharleb** [comment]
@LorenzMeier You should be able to gdb attach to the running process to see where the threads are.

**Comment by LorenzMeier** [comment]
This commit broke it, and I believe by reverting the addition of the policy and the quotes in the location I marked below it should come back to life.

https://github.com/PX4/Firmware/commit/68a78b0580682af83c7c7f45dfb23d699a333e25

**Comment by LorenzMeier** [comment]
There is no gdb. Can we settle for the LLVM debugger and also linker for Linux? We have an unmaintainable array of tools right now.

**Comment by mcharleb** [comment]
lldb should work as well. I have not attached to a running process with lldb.

**Comment by LorenzMeier** [comment]
@mcharleb Alternatively you could try building by just removing the policy and nothing else.

**Comment by dagar** [comment]
> @mcharleb You could host it somewhere and encrypt the credentials in travis.

On second thought that's a bad idea. Anyone could open a pull request that modifies .travis.yml to grab a copy of HexagonTools and upload it somewhere else. 

I have no idea what HexagonTools is, but could it be used in a separate job only on sitl01.dronetest.io?

**Comment by mcharleb** [comment]
HexagonTools is the toolchain (compiler, linker, c-lib, etc)

**Comment by LorenzMeier** [comment]
@dagar No, that's not the case. If this were true our S3 keys would be at risk as well. The S3 keys are only accessible to maintainers with credentials.

**Comment by dagar** [comment]
> @dagar No, that's not the case. If this were true our S3 keys would be at risk as well. The S3 keys are only accessible to maintainers with credentials.

Not the keys, but the contents of HexagonTools on the travis-ci instance.

**Comment by LorenzMeier** [comment]
@dagar It has one side effect though: External pull requests cannot be checked against Hexagon. It has to come from the core team.

**Comment by LorenzMeier** [comment]
@dagar The travis instance can't download it in the first place (if we use the download to gate, which would work)

**Comment by dagar** [comment]
Nevermind - "Please note that encrypted environment variables are not available for pull requests from forks."

**Comment by jgoppert** [comment]
@mcharleb @LorenzMeier 

The policy issue is fixed on my branch. That policy only existed after 3.1. I had to include that because after the changes from Mark last night my CMake (3.2.2) was throwing policy warnings everywhere.

I agree that we should keep changes to a minimum until we can get CI up, you guys are breaking my builds as well :-P.

**Comment by LorenzMeier** [comment]
What does "on your branch" mean? Could you push the fix here?

**Comment by jgoppert** [comment]
@LorenzMeier It is on my cmake-2 pull request, I'll cherry pick it and push as a new PR. It might be a good idea to include 2 cmake versions (2.8, 3.2) in the CI. With cmake 2.8 there isn't much error checking. In cmake 3.0 they fixed a lot of this, but ubuntu 14.04 is still using 2.8 by default.

**Comment by mcharleb** [comment]
Ubuntu 15.04 is using cmake 3.0.2

**Comment by LorenzMeier** [comment]
@mcharleb does this build now for you? Note my comment on the compile flag change

**Comment by mcharleb** [comment]
@LorenzMeier Yes, it builds now. Can we decide on what versions of CMake are supported and how to test whether a change breaks other versions? It sees very fragile.

**Comment by jgoppert** [comment]
@mcharleb, @LorenzMeier  I agree that in this rapid development phase if we were all using the same versoin of cmake it would be very useful. I vote for 3.2, I already am using the ppa for it on ubuntu 14.04 and it works fine.

**Comment by LorenzMeier** [comment]
The reality is that we can't ask people to reconfigure their whole system. I want to support Ubuntu 14.04, 15.04, Mac OS 10.10 and the Windows PX4 toolchain. Everybody else will need to fit it or switch to a supported system.

**Comment by LorenzMeier** [comment]
@dagar I'd love to add this build to Mac OS Travis (10.10, as on QGC). I've seen the build matrix settings you used there - do we have to go with a shell script and env vars, or is there a syntactically simpler approach to use different settings for the build matrix? At any rate a stab on a branch based on this branch would be great for Mac OS. I can help to get the dependencies right if you could lend me a hand on setting up Travis to start building.
https://pixhawk.org/dev/toolchain_installation_mac

**Comment by dagar** [comment]
@LorenzMeier - travis-ci osx started in PR #2854. I'll keep it rebased on cmake-2.

**Comment by LorenzMeier** [comment]
@mcharleb Non-zero int32 params seem to have issues:
```
nsh> param show MAV*
Symbols: x = used, + = saved, * = unsaved
x   MAV_SYS_ID [111,142] : 1065353216
x   MAV_COMP_ID [112,143] : 1065353216
x   MAV_RADIO_ID [113,144] : 0
x   MAV_TYPE [114,145] : 1065353216
x   MAV_USEHILGPS [115,146] : 0
x   MAV_FWDEXTSP [116,147] : 1065353216
x   MAV_TEST_PAR [117,148] : 1065353216

 657 parameters total, 394 used.
```

**Comment by LorenzMeier** [comment]
Float values look good:
```
nsh> param show MC*
Symbols: x = used, + = saved, * = unsaved
    MC_ROLL_P [-1,159] : 6.5000
    MC_ROLLRATE_P [-1,160] : 0.1500
    MC_ROLLRATE_I [-1,161] : 0.0500
    MC_ROLLRATE_D [-1,162] : 0.0030
    MC_ROLLRATE_FF [-1,163] : 0.0000
    MC_PITCH_P [-1,164] : 6.5000
    MC_PITCHRATE_P [-1,165] : 0.1500
```

**Comment by LorenzMeier** [comment]
Logging here for reference: I got still these unresolved weak symbols:

```
$ arm-none-eabi-nm build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx | grep " w "
         w sem_initialize
         w timer_deleteall
         w timer_initialize
```

**Comment by vooon** [comment]
Just an idea: add to `px4_add_module()` macro `PARAMS` arg for parameter files.

**Comment by LorenzMeier** [comment]
@jgoppert Where are we standing with this?

**Comment by jgoppert** [comment]
I think we have something ready for testing with sitl/ hil, then real flights. Only missing module is uavcan. IO firmware is building, just need to add it to the px4 bundle. Next, need to add more board configuration to complete the switch.

**Comment by LorenzMeier** [comment]
@mcharleb The Mac OS SITL build blocks here indefinitely:
```
pxh> param set SYS_AUTOSTART 123
Process 3672 stopped
* thread #1: tid = 0x1041f, 0x00007fff924b97ba libsystem_kernel.dylib`sem_wait + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fff924b97ba libsystem_kernel.dylib`sem_wait + 10
libsystem_kernel.dylib`sem_wait:
->  0x7fff924b97ba <+10>: jae    0x7fff924b97c4            ; <+20>
    0x7fff924b97bc <+12>: movq   %rax, %rdi
    0x7fff924b97bf <+15>: jmp    0x7fff924b3c78            ; cerror
    0x7fff924b97c4 <+20>: retq 
```
backtrace:
```
(lldb) bt
* thread #1: tid = 0x1041f, 0x00007fff924b97ba libsystem_kernel.dylib`sem_wait + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007fff924b97ba libsystem_kernel.dylib`sem_wait + 10
    frame #1: 0x0000000100009238 mainapp`device::Device::lock(this=<unavailable>) + 40 at vdev.h:183
    frame #2: 0x000000010000582b mainapp`device::VDev::open(this=0x00000001005000c0, filep=0x00000001002063c0) + 15 at vdev.cpp:226
    frame #3: 0x00000001000060c4 mainapp`px4_open(path=<unavailable>, flags=0) + 486 at vdev_posix.cpp:103
    frame #4: 0x000000010001ba23 mainapp`uORB::Manager::node_advertise(this=<unavailable>, meta=<unavailable>, instance=<unavailable>, priority=<unavailable>) + 41 at uORBManager_posix.cpp:200
    frame #5: 0x000000010001b8bd mainapp`uORB::Manager::node_open(this=<unavailable>, f=PUBSUB, meta=0x00000001000ccfd0, data=<unavailable>, advertiser=<unavailable>, instance=0x0000000000000000, priority=<unavailable>) + 189 at uORBManager_posix.cpp:282
    frame #6: 0x000000010001b6e3 mainapp`uORB::Manager::orb_advertise_multi(this=<unavailable>, meta=0x00000001000ccfd0, data=0x00007fff5fbff310, instance=<unavailable>, priority=<unavailable>) + 45 at uORBManager_posix.cpp:99
    frame #7: 0x000000010001e08b mainapp`param_notify_changes + 49 at param.c:245
    frame #8: 0x000000010001df6e mainapp`param_set_internal(param=<unavailable>, val=<unavailable>, mark_saved=<unavailable>, notify_changes=<unavailable>) + 586 at param.c:576
    frame #9: 0x00000001000113aa mainapp`do_set(name=<unavailable>, val=<unavailable>, fail_on_not_found=<unavailable>) + 500 at param.c:455
    frame #10: 0x0000000100001dfe mainapp`run_cmd(appargs=<unavailable>, exit_on_fail=true) + 260 at main.cpp:94
    frame #11: 0x0000000100001ce0 mainapp`process_line(line=<unavailable>, exit_on_fail=<unavailable>) + 510 at main.cpp:131
    frame #12: 0x000000010000185d mainapp`main(argc=<unavailable>, argv=<unavailable>) + 1577 at main.cpp:210
    frame #13: 0x00007fff8c91f5c9 libdyld.dylib`start + 1
```

**Comment by LorenzMeier** [comment]
ok, I think I found the root cause:
http://heldercorreia.com/blog/semaphores-in-mac-os-x

What about QuRT?

**Comment by mcharleb** [comment]
POSIX semaphores are implemented for QURT AFAIK. I'm still writing a full
fledged unit test for vdev and poll.

-Mark

**Comment by LorenzMeier** [comment]
@jgoppert What is the state of IO Firmware building and upgrading? I don't think its in this branch yet, right?

**Comment by jgoppert** [comment]
@mcharleb, @LorenzMeier, @vooon, @dagar  In my latest PR: https://github.com/PX4/Firmware/pull/2881 I have cmake doing a complete build for px4fmu-v2_default and it appears fully functional to me. I think it is time for HIL testing and then some flight testing.

**Comment by LorenzMeier** [comment]
CPU load for fixed wing config with CMake:
```
Processes: 21 total, 3 running, 18 sleeping
CPU usage: 83.53% tasks, 0.67% sched, 15.80% idle
Uptime: 850.043s total, 159.775s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE 
   0 Idle Task                  159774 15.797     0/    0   0 (  0)  READY 
   1 hpwork                      20730  2.459   892/ 1792 192 (192)  w:sig 
   2 lpwork                       2542  0.223   572/ 1792  50 ( 50)  READY 
   3 init                         1483  0.000  1316/ 2992 100 (100)  w:sem 
   6 nshterm                         0  0.000   684/ 1496  70 ( 70)  w:sem 
 109 commander_low_prio            288  0.000   740/ 2592  50 ( 50)  w:sem 
  80 dataman                        23  0.000   652/ 1496 100 (100)  w:sem 
  94 sensors_task               144709 17.362  1548/ 1992 250 (250)  w:sem 
 100 gps                          1543  0.149   708/ 1496 220 (220)  w:sem 
 103 commander                    3498  0.372  3068/ 3392 215 (215)  w:sig 
 105 px4io                       28579  3.353  1028/ 1792 240 (240)  w:sem 
 183 top                           189  2.086  1252/ 1696 100 (100)  RUN   
 111 mavlink_if0                  7476  0.968  2092/ 2392 100 (100)  w:sig 
 113 mavlink_rcv_if0               241  0.000  1092/ 2096 175 (175)  w:sem 
 122 sdlog2                       2104  0.223  2092/ 2992  70 ( 70)  w:sig 
 136 fmuservo                     1465  0.074   476/ 1192 100 (100)  w:sem 
 148 ekf_att_pos_estimator      437655 52.011  3524/ 4792 235 (235)  w:sem 
 150 fw_att_control              18505  2.160   876/ 1592 250 (250)  w:sem 
 152 fw_pos_control_l1            4316  0.447   768/ 1592 250 (250)  w:sem 
 155 land_detector                1566  0.149   500/  992 100 (100)  w:sig 
 157 navigator                   12767  1.490   876/ 1496 105 (105)  w:sem 
nsh> 
```

CPU load with master build is slightly higher. However, both seem kind of high for the estimator - I presume its running faster than intended currently.

**Comment by jgoppert** [comment]
I just did a flight test, when power module is connected I get some weird behavior (battery voltage reading low, see below), when I removed power module and enabled circuit breaker for power check all was fine, flew manual, stabilized, and auto:

Power module reading fine on master:
master

Power module not reading correctly on cmake-2:
cmake-2

**Comment by jgoppert** [comment]
What is holding cmake up right now, just the power module issue? Can anyone else confirm this? It would be nice to wrap this up.

**Comment by LorenzMeier** [comment]
This is unbelieveable - the Github UI just merged this from scrolling the page. I never actually clicked the touchpad. Now I got to work out how to fix this.

**Comment by mcharleb** [comment]
The cosmos just really wants you to merge this :)

**Pull request merged**
