### PR TITLE
param_get() simple c++ wrapper

### PR DESCRIPTION
**Pull request by dagar**
This PR adds a float and int32 param_get() c++ wrapper. I'm not sure if this is worth merging, but I noticed the common param_get() usage was prone to subtle errors and this seemed like a good way to at least discuss alternatives.
``` C
__EXPORT bool param_get(param_t param, float &val);
__EXPORT bool param_get(param_t param, int32_t &val);
```

For example

``` C
    param_get(_params_handles.mc_airspeed_min, &_params.mc_airspeed_min);
```

If the parameter mc_airspeed_min were an int32, but _params.mc_airspeed_min a float this won't produce an error, but the value of _params.mc_airspeed_min will be bogus.

This also changes the return value to bool to encourage actually checking, including multiple successive param_get() calls.

param.cpp could be used as a base to build out a newer c++ param and type safe API.

### CODE REVIEW

**Comment by dagar** [comment]
Another example.

    param_get(_param_sys_type, &(status.system_type));


https://github.com/PX4/Firmware/blob/5c524e15f8e1a16cabe1dba3400cb91fa314ef83/src/modules/commander/commander.cpp#L1643


status.system_type is a uint8_t, but the param_get call is copying the full param (MAV_TYPE 32 bits) starting at this address. In this case it doesn't cause serious problems because the fields after system_type are bools that are updated.

**Comment by LorenzMeier** [comment]
Sorry for realising this only now, but we can't merge this as is: You've created a C++ variant of param_get with an inverted return value: `bool` vs `int` and the meaning of `if (param_get())` is inverted.

I think there are two optimal solutions:

  * Have the C++ wrapper mimic the C API and just making it safer
  * Allow the use of BlockParam (which is very clean and nice) outside of a SuperBlock class

I would vote for doing 1) in this PR.

**Comment by dagar** [comment]
I agree that was shady, but thought it might be acceptable given how rarely we're checking return values.

What about a new name for the c++ version and keep the bool? The use of int return on its own can cause confusion, so if possible I'd like to try to move away from it.

param_update, param_fetch, param_copy?

**Comment by bkueng** [comment]
I'm very much in favour of type-safety. The existing API was designed to be easy-to-use. But I think by adding more API calls, I probably would be confused as a novice/irregular contributor as to which one I should use.

We already have a separate API, the BlockParam, more suited for C++ (It has a different drawback, as it needs 50% more memory per parameter, because it's based on a linked list).

**Comment by dagar** [comment]
I agree, I'm just concerned by the accidental misuse of param_get() I've already seen.

I generally like using controllib. Is it feasible to gradually move everything in that direction or do we need/want a solution without a Superblock (and additional overhead)?

**Comment by bkueng** [comment]
> Is it feasible to gradually move everything in that direction or do we need/want a solution without a Superblock (and additional overhead)?

If the overhead is gone, it would be the superior solution. When used within the whole system, the overhead is quite noticeable: https://github.com/PX4/Firmware/commit/7c6d99d30f2cb83fbf

**Pull request closed without merging**
