### PR TITLE
fix broken windows build

### PR DESCRIPTION
**Pull request by dagar**
srcscanner.py replace windows slashes

Reported here - https://groups.google.com/forum/#!topic/px4users/68J1lm_X3ws

### CODE REVIEW

**Comment by dagar** [comment]
I'm still surprised by the number of windows developers...
https://groups.google.com/forum/#!topic/px4users/3vM6QTd4oiM

**Comment by mhkabir** [comment]
Most people in Asia use Windows.

**Comment by dagar** [comment]
So do most people in North America. I'm just surprised they use it for PX4
development given how painful it can be. Without exaggeration a build takes
something like 5x longer compared with Ubuntu on the same machine.

**Comment by LorenzMeier** [comment]
Rebased and applied

**Comment by dagar** [comment]
@LorenzMeier you might want to cherry-pick this to beta/stable so that the 1.3.0 release is buildable on windows.

**Pull request closed without merging**
