### PR TITLE
Startup Tune Suggestions

### PR DESCRIPTION
**Pull request by MaEtUgR**
The current startup sound is well known among developers but probably gets disabled by users quite quickly. At least I had to switch it for something shorter to not get annoyed.

I open this pr to paste suggestions in the different commits. Comments welcome. Something small and catchy would be the goal which is neither annoying long after a lot of reboots nor to short to be maybe played as ad for PX4.

First there are 3 well known tones which I think would fit pretty well. Let's mix them up and compose something unique.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Cool!

**Comment by mhkabir** [comment]
Can we create some documentation on how to create these tunes?

**Comment by hamishwillee** [comment]
Re docs on creating tunes: https://github.com/PX4/Firmware/pull/9538#issuecomment-392380458

Answers to:
- What are tunes
- What the default tunes (and are there non-default tunes?)
- Where are they defined?
- What is the tune format?
- How are they mapped to events?
- What else would you like to know ....

**Comment by hamishwillee** [comment]
@MaEtUgR Nope, whole sentence typo. Fixed :-)

**Comment by LorenzMeier** [comment]
@MaEtUgR Would you have time to contribute the tune docs?

I tested the tune meanwhile a little more and I think a slightly shorter variant might be interesting to try.

**Comment by MaEtUgR** [comment]
@LorenzMeier I add the pointers I know to the issue https://github.com/PX4/Devguide/issues/528
I had an idea for a short sound, just need to write it down and test.

**Comment by junwoo091400** [comment]
This Amazing PR should be resurrected!!

**Pull request closed without merging**
