### PR TITLE
Tools: Update python files to work with python3

### PR DESCRIPTION
**Pull request by kylemanna**
* The `print """` syntax appears invalid in python3 which is the default
  for the python binary on my system (and soon many more).
* Explicitly request python2 until some one with more python-fu can
  bring this up to speed.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@mcharleb could you have a look?

**Comment by kylemanna** [comment]
Updated branch to a proper fix using the Python `2to3` utility.  Tests fine on my system.

**Comment by LorenzMeier** [comment]
Can you then remove the shebang changes and see if it still works for you?

**Comment by kylemanna** [comment]
Sorry, changed to python2 for testing and forgot to remove after.  Removed now and tested again.

**Comment by LorenzMeier** [comment]
Awesome! Thanks for making the extra effort to get this into a mainline-able fashion. Merging!

**Pull request merged**
