### PR TITLE
commander FW don't allow entering FOLLOW or OFFBOARD

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by AndreasAntener** [comment]
But isn't there FW offboard attitude control now? Or didn't this go in

**Comment by dagar** [comment]
Doesn't stabilized mode get in the way of offboard attitude?
It seemed easy (and safer) to remove it now and turn it back on if/when we know it actually works.

**Comment by AndreasAntener** [comment]
What I was referring to is here: https://github.com/PX4/Firmware/pull/6112

**Comment by dagar** [comment]
Yes, you just made me stop to wonder if an offboard attitude setpoint could still slip through somehow. The other types were more obviously not possible.

**Comment by AndreasAntener** [comment]
The FW offboard PR has one problem: when you switch into offboard but send position targets then no one will send attitude setpoints again.

**Comment by AndreasAntener** [comment]
Scratch that, it would then act as it's in POSCTL

**Comment by dagar** [comment]
Review/merge this now and we'll continue discussion in the offboard PR? I'll push a commit to undo it there.
There are FW users that click on these modes simply because they're available to select. In air...

**Comment by AndreasAntener** [comment]
Makes sense.

**Pull request merged**
