### PR TITLE
Intel aero: config updates

### PR DESCRIPTION
**Pull request by bkueng**
- parameter tuning from https://github.com/PX4/Firmware/issues/5955
- make sure logging works

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice, do you have a video / log?

**Comment by bkueng** [comment]
No video, but logs are in #5955:
acro + manual: http://logs.px4.io/plot_app?log=6699704e-c84b-454a-8e0c-eb0b199c4e30
manual + position: http://logs.px4.io/plot_app?log=60252e13-2a75-4a18-aa2c-c6babe43d0ae

**Comment by LorenzMeier** [comment]
Woah, the thing has a big issue with the mag. @jgoppert That explains why LPE is struggling.

mag_norm

**Comment by mindThomas** [comment]
Have this magnetometer issue been resolved or improved on the released Intel Aero drone and with improvements in the firmware?
If so, which branch should we use when reflashing PX4 on the Intel Aero and what about the tuned parameters?

**Pull request merged**
