### PR TITLE
Nuttx Update to 7.x

### PR DESCRIPTION
**Pull request by LorenzMeier**
Thanks to the efforts of David Sidrane, a first candidate is available for wider testing. The NuttX update per se only provides bugfixes to existing functionality, but will allow to build:

  * USB mass storage: Faster / convenient access to logs when connected to a computer
  * Smaller time slices: Optimization to scheduling to allow more accurate prioritisation for critical control tasks
  * Support for new devices like the CC3000 wifi module (which might be of interest)
  * We are using a commit from upstream + some minor patches, so we're back to mainline.

Main validation areas:

  * Check that none of the fixed I2C issues resurfaces. Current NuttX employs all of the fixes developed for PX4 in the past, but not using the very same code, so soak testing is required.

Changes before merge:

This PR will be rebased, so for review only. We will squash a lot of the commits and get rid of merge commits.

### CODE REVIEW

**Comment by Zefz** [comment]
@LorenzMeier I get a compile error:
```
In file included from /home/foxie/Desktop/haukr/Firmware/src/modules/px4iofirmware/px4io.c:60:0:
/home/foxie/Desktop/haukr/Firmware/src/modules/px4iofirmware/px4io.c: In function 'show_debug_messages':
/home/foxie/Desktop/haukr/Firmware/src/modules/px4iofirmware/px4io.h:66:40: error: 'LOG_DEBUG' undeclared (first use in this function)
 # define debug(fmt, args...) lowsyslog(LOG_DEBUG,fmt "\n", ##args)
                                        ^
/home/foxie/Desktop/haukr/Firmware/src/modules/px4iofirmware/px4io.c:119:4: note: in expansion of macro 'debug'
    debug("%s", msg[msg_next_out]);
```

**Comment by Zefz** [comment]
Hold on. I forgot to make archives.

**Comment by Zefz** [comment]
Okay, it compiles after removing uavcan from the make:
```
make[2]: *** No rule to make target `/home/foxie/Desktop/haukr/Firmware/Build/px4fmu-v2_default.build/nuttx-export/include/nuttx/spi.h', needed by `/home/foxie/Desktop/haukr/Firmware/src/lib//uavcan/libuavcan_drivers/stm32/driver//src/uc_stm32_can.cpp.o'.  Stop.
```

**Comment by LorenzMeier** [comment]
If UAVCAN compilation fails, delete the UAVCAN dir and run Git submodule update again.

**Comment by LorenzMeier** [comment]
@davids5 HW test says it didn't get any serial data - does this state boot fine for you?

**Comment by davids5** [comment]
Boots fine (with pio error)
[boot] Initialized SPI port 1 (SENSORS)
[boot] Initialized SPI port 2 (RAMTRON FRAM)
[boot] Initialized SPI port 4
[boot] Initialized SDIO
[i] Looking for microSD...
[i] microSD mounted: /fs/microsd
[i] Init script not found: /fs/microsd/etc/rc.txt
[i] AUTOSTART mode
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
nshterm [6:70]
[uorb] ready
param: selected parameter default file /fs/mtd_params
[param] Loaded: /fs/mtd_params
[rgbled] on I2C bus 2 at 0x55
nsh: pca8574: command not found
 1:   SYS_USE_IO: match
 0:   SYS_AUTOSTART: match
[i] No autostart
[i] Config not found: /fs/microsd/etc/config.txt
[PX4IO::checkcrc] check CRC failed - -1
px4io: px4io is not started, still attempting upgrade
[PX4IO] using firmware from /etc/extras/px4io-v2_default.bin
[PX4IO] found bootloader revision: 4
[PX4IO] erase...
[PX4IO] programming 43620 bytes...
[PX4IO] verify...
[PX4IO] update complete
**[PX4IO::checkcrc] check CRC failed - -1**
[i] ERROR: PX4IO not found
[i] ERROR: PX4IO not found, disabling output
dataman: Unknown restart
dataman: Initialized, data manager file '/fs/microsd/dataman' size is 101504 bytes
commander: loaded mission state: dataman_id=0, count=0, current=0
mavlink_if0: mode: 0, data rate: 1000 B/s on /dev/ttyS1 @ 57600B
ver hwcmp match: PX4FMU_V2
[MS5611_SPI] on SPI bus 1 at 3
<adc> init done
mpu6000: driver start failed
[MPU6000] on SPI bus 1 at 4
<L3GD20> probe failed
l3gd20: driver start failed
[L3GD20] on SPI bus 1 at 1
hmc5883: no device on bus 2
hmc5883: no device on bus 1
[HMC5883_SPI] on SPI bus 1 at 5
hmc5883: no device on bus 3
hmc5883: driver start failed
ver hwcmp match: PX4FMU_V2
<LSM303D> probe failed
lsm303d: SPI init failed
lsm303d: driver start failed
[LSM303D] on SPI bus 1 at 2
[MS5611_SPI] on SPI bus 4 at 2
ms5611: interface init failed
meas_airspeed: no MS4525 airspeed sensor connected
ets_airspeed: no ETS airspeed sensor connected
ets_airspeed: no ETS airspeed sensor connected
px4flow: driver start failed
preflight_check [63:100]
Start sdlog2 at 200Hz
[i] Start GPS
navigator: Initializing..
[i] No autostart ID found
[i] No addons script: /fs/microsd/etc/extras.txt

NuttShell (NSH)
nsh> navigator: Could not clear geofence
navigator: offboard mission updated: dataman_id=0, count=0, current_seq=0
preflight_check: magnetometer calibration is for a different device - calibrate magnetometer first
preflight_check: PREFLIGHT CHECK ERROR! TRIGGERING ALARM
sdlog2: log buffer size: 22528 bytes

nsh>


Second boot:

[boot] Initialized SPI port 1 (SENSORS)
[boot] Initialized SPI port 2 (RAMTRON FRAM)
[boot] Initialized SPI port 4
[boot] Initialized SDIO
[i] Looking for microSD...
[i] microSD mounted: /fs/microsd
[i] Init script not found: /fs/microsd/etc/rc.txt
[i] AUTOSTART mode
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
nshterm [6:70]
[uorb] ready
param: selected parameter default file /fs/mtd_params
[param] Loaded: /fs/mtd_params
[rgbled] on I2C bus 2 at 0x55
nsh: pca8574: command not found
 1:   SYS_USE_IO: match
 0:   SYS_AUTOSTART: match
[i] No autostart
[i] Config not found: /fs/microsd/etc/config.txt
[PX4IO::checkcrc] CRCs match
dataman: Unknown restart
dataman: Initialized, data manager file '/fs/microsd/dataman' size is 101504 bytes
commander: loaded mission state: dataman_id=0, count=0, current=0
[px4io] default PWM output device
[i] PX4IO started
[i] Set PX4IO update rate limit:
mavlink_if0: mode: 0, data rate: 1000 B/s on /dev/ttyS1 @ 57600B
ver hwcmp match: PX4FMU_V2
[MS5611_SPI] on SPI bus 1 at 3
<adc> init done
mpu6000: driver start failed
[MPU6000] on SPI bus 1 at 4
<L3GD20> probe failed
l3gd20: driver start failed
[L3GD20] on SPI bus 1 at 1
hmc5883: no device on bus 2
hmc5883: no device on bus 1
[HMC5883_SPI] on SPI bus 1 at 5
hmc5883: no device on bus 3
hmc5883: driver start failed
ver hwcmp match: PX4FMU_V2
<LSM303D> probe failed
lsm303d: SPI init failed
lsm303d: driver start failed
[LSM303D] on SPI bus 1 at 2
[MS5611_SPI] on SPI bus 4 at 2
ms5611: interface init failed
meas_airspeed: no MS4525 airspeed sensor connected
ets_airspeed: no ETS airspeed sensor connected
ets_airspeed: no ETS airspeed sensor connected
px4flow: driver start failed
preflight_check [63:100]
Start sdlog2 at 200Hz
[i] Start GPS
navigator: Initializing..
[i] No autostart ID found
[i] No addons script: /fs/microsd/etc/extras.txt

NuttShell (NSH)
nsh> navigator: Could not clear geofence
navigator: offboard mission updated: dataman_id=0, count=0, current_seq=0
preflight_check: magnetometer calibration is for a different device - calibrate magnetometer first
preflight_check: PREFLIGHT CHECK ERROR! TRIGGERING ALARM
sdlog2: log buffer size: 22528 bytes

nsh>

**Comment by Zefz** [comment]
Having trouble compiling latest. Says I'm missing a math.h file for nuttx?

**Comment by davids5** [comment]
The new build does build time patching. Please try a make distclean followed by make archives.
the do a git status in the NuttX folder

You should see something like:

 On branch upstream_to_greg
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   nuttx/include/signal.h
#       modified:   nuttx/include/stdio.h
#       modified:   nuttx/include/stdlib.h
#       modified:   nuttx/include/sys/stat.h
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       nuttx/.patchedpx4common
#       nuttx/arch/arm/include/math.h

**Comment by Zefz** [comment]
Yes now it works. Had to manually clean (delete) the NuttX folder and run everything again.

**Comment by davids5** [comment]
To keep the build process reliable, I would suggest that we should always run **make distclean** before switching to/from master(or a child) and nuttx_bringup

**Comment by davids5** [comment]
HI 6dc834d fixes The USB issue 

```
Jan 28 12:47:48 ast1 kernel: ohci_hcd 0000:00:0f.4: wakeup
Jan 28 12:47:49 ast1 kernel: usb 2-2: new full speed USB device using ohci_hcd and address 109
Jan 28 12:47:49 ast1 kernel: usb 2-2: config 1 has an invalid descriptor of length 36, skipping remainder of the config
Jan 28 12:47:49 ast1 kernel: usb 2-2: config 1 has 0 interfaces, different from the descriptor's value: 2
Jan 28 12:47:49 ast1 kernel: usb 2-2: configuration #1 chosen from 1 choice

```

(and what may be a lot of issues). the assembly language memcpy did not return dest in r0 and when the stack checking was turned off  the compiler was assuming r0 was valid. In the case of the USB issue this created a jumbled up descriptor.

**Comment by LorenzMeier** [comment]
Replaced by #1758.

**Pull request closed without merging**
