### PR TITLE
Allow more than 4 MC motors in VTOL Simulator

### PR DESCRIPTION
**Pull request by irsdkv**
**Describe problem solved by the proposed pull request**
In the SITL MAVLink module, the outputs are scaled based on the number of motors determined from the vehicle type. For tiltrotors and some other types of VTOLs, the vehicle type is not sufficient to determine the number of motors.

**Describe your preferred solution**
The VT_PSH_MOT_COUNT (push / pull motors count) parameter specifies the number of pushing / pulling motors for the copter. This new parameter together with VT_MOT_COUNT used to define total amount of motors in VTOL vehicle.

The default value is 1, so the old description files will be valid in case of reuse it to describe the new VTOL copters.

This parameter is necessary because of without it you can't give a full description of the nonstandard VTOL vehicle type with several push or pull engines.

For the new parameter used reserved vehicle type MAV_TYPE_VTOL_RESERVED3, which may coverage most of future nonstandard VTOL types.

**Additional context**
Thanks to @jlecoeur for https://github.com/PX4/Firmware/pull/11287.

### CODE REVIEW

**Comment by jlecoeur** [comment]
You are welcome, this is a cleaner solution. Feel free to close my PR when this is in.

Regarding the parameters, what about this:
- rename VT_MOT_COUNT to VT_MC_MOT_COUNT
- rename VT_PSH_MOT_COUNT to VT_FW_MOT_COUNT
?

**Comment by irsdkv** [comment]
> * VT_MC_MOT_COUNT

Hello

Thank you, I think that new names will be clearer.

Just for clarification, should I rename all occurrences of VT_MOT_COUNT in config files (for example in ROMFS/.../1040_standard_vtol) too? I sure yes, but I worry about backward compatibility for configs.

**Comment by irsdkv** [comment]
@jlecoeur should I do any additional improvements? 
Or may be need to revoke commit [MAVLink impl](https://github.com/PX4/Firmware/pull/12166/commits/a2aa61ca67b0d75c4464890a2df8f9aa25e4493a) and later?

**Comment by a6a3uh** [comment]
This is the PR we are looking for to be merged. 4 MC motors for VTOL is an annoying restriction. Dear maintainers pls let us know how do you see the change like this could be accepted..

**Comment by dagar** [comment]
We generally try to avoid renaming parameters because it breaks existing setups.

This feels like it could be a piece of metadata we should just be getting from a mixing system rather than a simple motor count (that's kind of a leaky abstraction).

**Comment by a6a3uh** [comment]
> We generally try to avoid renaming parameters because it breaks existing setups.
> 
> This feels like it could be a piece of metadata we should just be getting from a mixing system rather than a simple motor count (that's kind of a leaky abstraction).

Hi, @dagar! Does that means you want to get rid of VT_MOT_COUNT as well? The solution proposed just extends the approache used before with VT_MOT_COUNT. So it is based on the architecture already used in the code. 

I see 5 variants to solve this situation:
1) Approach proposed in this PR with one new parameter `VT_FW_MOT_COUNT` and renaming one existent (`VT_MOT_COUNT` -> `VT_MC_MOT_COUNT`).
2) Leaving previous parameter name `VT_MOT_COUNT` for compatibility but introduce new parameter `VT_FW_MOT_COUNT`.
3) Hardcode the number of VT_FW_MOT_COUNT as it was hardcoded before to 1, but infer MC motors count from `VT_MOT_COUNT` instead of hardcoded number 4.
4) Infer both MC motors count and FW motors count from mixers and get rid of `VT_MOT_COUNT` at all.
5) Infer only FW motor count from mixer while leaving `VT_MOT_COUNT` for compatibility.

Could you pls let us know which variant is acceptable for you? Or suggest another approach?

**Comment by jlecoeur** [comment]
@a6a3uh I think your problem was solved in https://github.com/PX4/Firmware/pull/12352

**Comment by a6a3uh** [comment]
> @a6a3uh I think your problem was solved in #12352

The problem was not solved I believe. Or putting it differently that PR solves different kind of problem. 

The main problem we had was simulator does not support more than 4 MC motors for standard VTOL. Number 4 is hardcoded in `mavlink_messages.cpp`. Thus VTOL with more than 4 MC motors was producing incorrect thrust on motors with index > 5.

Some other downsides of approach in the PR you mentioned. No more than 8 MC motors are possible for VTOL. And in order to get quantity of MC motors one have to extract that number from VT_MOT_ID in some inconvenient way.

**Comment by jlecoeur** [comment]
You are right @a6a3uh, this is not completely solved.

What I suggest:
- convert VT_MOT_ID to a 16bits bitmask (for a maximum of 16 actuators)
- add param VT_FW_MOT_ID
- fix `mavlink_messages.cpp` and `simulator_mavlink.cpp` to scale the outputs based on the 2 parameters above

**Comment by irsdkv** [comment]
Will create new PR used `VT_MOT_ID` after https://github.com/PX4/Firmware/pull/12277 will done.

**Pull request closed without merging**
