### PR TITLE
logger serialization

### PR DESCRIPTION
**Pull request by dagar**
FYI @bkueng 

This PR removes all the alignment hacks from newLogger2 and has my work in progress serialization code.

TODO
 - [ ] ~~generate packed size to use in logger~~
 - [x] TEST

### CODE REVIEW

**Comment by kd0aij** [comment]
this branch doesn't work on fmu-v4: something broken with parameters:
```
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
[i] microSD mounted: /fs/microsd 
param: selected parameter default file /fs/mtd_params
[param] Loaded: /fs/mtd_params 
rgbled: no RGB led on bus #1
blinkm: I2C init failed
blinkm: init failed
param: Error: Parameter SYS_AUTOCONFIG not found.
param: Error: Parameter SYS_USE_IO not found.
param: Error: Parameter INAV_LIDAR_ERR not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
ver hwcmp match: PX4FMU_V4
dataman: Power on restart, data manager file '/fs/microsd/dataman' size is 103090 bytes
MS5611_SPI on SPI bus 2 at 3 (20000 KHz)
bst: no devices found
adc init done
ver hwcmp match: PX4FMU_V4
HMC5883_I2C on I2C bus 1 at 0x1e (bus: 100 KHz, max: 400 KHz)
lis3mdl: no device on bus 2
LIS3MDL bad ID: 3cLIS3MDL_SPI on SPI bus 1 at 7 (11000 KHz)
lis3mdl: no device on bus 3
LIS3MDL bad ID: ffHMC5883_SPI on SPI bus 1 at 5 (11000 KHz)
MPU6000 on SPI bus 1 at 6 (1000 KHz)
MPU9250 on SPI bus 1 at 4 (1000 KHz)
meas_airspeed: no MS4525 airspeed sensor connected
ets_airspeed: no ETS airspeed sensor connected
ets_airspeed: no ETS airspeed sensor connected
nsh: sf10a: command not found
error finding param: BAT_V_EMPTY
error finding param: BAT_V_CHARGED
error finding param: BAT_N_CELLS
error finding param: BAT_CAPACITY
error finding param: BAT_V_LOAD_DROP
error finding param: BAT_LOW_THR
error finding param: BAT_CRIT_THR
sensors: RC chan 0 not sane, scaling:      NaN, rev: 0
sensors: RC chan 1 not sane, scaling:      NaN, rev: 0
sensors: RC chan 2 not sane, scaling:      NaN, rev: 0
sensors: RC chan 3 not sane, scaling:      NaN, rev: 0
sensors: RC chan 4 not sane, scaling:      NaN, rev: 0
sensors: RC chan 5 not sane, scaling:      NaN, rev: 0
sensors: RC chan 6 not sane, scaling:      NaN, rev: 0
sensors: RC chan 7 not sane, scaling:      NaN, rev: 0
sensors: RC chan 8 not sane, scaling:      NaN, rev: 0
sensors: RC chan 9 not sane, scaling:      NaN, rev: 0
sensors: RC chan 10 not sane, scaling:      NaN, rev: 0
sensors: RC chan 11 not sane, scaling:      NaN, rev: 0
sensors: RC chan 12 not sane, scaling:      NaN, rev: 0
sensors: RC chan 13 not sane, scaling:      NaN, rev: 0
sensors: RC chan 14 not sane, scaling:      NaN, rev: 0
sensors: RC chan 15 not sane, scaling:      NaN, rev: 0
sensors: RC chan 16 not sane, scaling:      NaN, rev: 0
sensors: RC chan 17 not sane, scaling:      NaN, rev: 0
sensors: WARNING     WARNING     WARNING

RC CALIBRATION NOT SANE!

```

**Comment by kd0aij** [comment]
I can't see how any of the changes here would have broken parameters, so I'm stuck. Any suggestions?

**Comment by LorenzMeier** [comment]
@kd0aij I recommend to run a clean build. You might be stretching the build system's capability for clean builds.

**Comment by kd0aij** [comment]
@LorenzMeier Thanks, a fresh clone of git://github.com/dagar/Firmware.git newLogger2
starts up OK. I'm not sure how to do a cleaner build in my own repo though, short of deleting it.

**Comment by kd0aij** [comment]
OK, looks good.  I'll do more testing on this tomorrow to see if I can get it to fault.

**Comment by dagar** [comment]
Closing in favor of #4449

**Pull request closed without merging**
