### PR TITLE
Cmake hexagon update

### PR DESCRIPTION
**Pull request by mcharleb**
cmake_hexagon was updated and all the files used with it were correspondingly updated.

### CODE REVIEW

**Comment by mcharleb** [comment]
@LorenzMeier Any objections to this being merged?

**Comment by LorenzMeier** [comment]
@julianoes @tumbili Can you compile and fly this on the target? Just want to be sure we're very diligent as long as Travis is not compiling it yet (which we should change ASAP).

**Comment by julianoes** [comment]
There seems to be yet another [commit](da4d6e7898880ce370dca21dac1362cd56274a79) that we should include from [cmake_hexagon](https://github.com/ATLFlight/cmake_hexagon/commits/master
).

Also I need to chase up why there we suddenly need the fsync() stub for QURT.

**Comment by LorenzMeier** [comment]
Rebased, applied and updated the cmake_hexagon version hash to the HEAD of that repo.

**Pull request closed without merging**
