### PR TITLE
changes needed for fake gps

### PR DESCRIPTION
**Pull request by ChristophTobler**
there is a new mode in mavlink for fake gps. and there is a disabling flag for mocap in inav which can be set in qgc (we don't want to use mocap data for estimation, while we simulate gps). (the gps re-init commit is nothing)

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice!

**Comment by nabilneh** [comment]
Hello,

Can we use this version to send false GPS data with Mavlink ? We want to do an indoor application without GPS and send false  earth-fixed coordinate.

Thank you for your help with our project.

**Comment by LorenzMeier** [comment]
Yes, you can do that with MAVROS now.

**Comment by ChristophTobler** [comment]
Forgot to push it to mavros... just did it right now.

**Comment by nabilneh** [comment]
Thanks for your answer.

I were using an Arduino sending MAVLink packets to the Pixhawk to simulate the fake GPS. Everything works fine to read usual values like pitch, yaw, roll, but the PixHawk doesn't change the differents coordinates I ​​send.

I will now try to do it with MAVROS. If it works well, I might retry to do it directly from the Arduino.

**Pull request merged**
