### PR TITLE
WIP: Rate mode 3d attitude control

### PR DESCRIPTION
**Pull request by kd0aij**
change attitude setpoint from Euler angles to full rotation matrix to facilitate specification of arbitrary orientations

looks like a new mixer will be required to handle inverted orientations

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I'm closing this for now because we have the issue of acceleration artefacts in attitude mode without GPS, and racers often have sketchy GPS (which is why we need to stop gyro bias estimation). I'm not generally rejecting the idea, but it seems like a tight tuning of the rate loop is the more robust approach.

**Comment by kd0aij** [comment]
This would be interesting to test by flying an autopilot-controlled path defined by maintaining constant roll/pitch angles and constant yaw rate (with no input from GPS). One would expect to observe changing roll/pitch angles as the attitude estimation error builds.

This is another case in which it would be nice to have mocap data to quantify actual estimation error. So far, I haven't observed significant attitude errors when flying non-GPS quads around in stabilized mode.

**Comment by kd0aij** [comment]
@LorenzMeier 
> sketchy GPS (which is why we need to stop gyro bias estimation)

I had no GPS installed on the S250AQ that I was using to test ACRO mode.

**Comment by kd0aij** [comment]
replaced by https://github.com/PX4/Firmware/pull/5372

**Pull request closed without merging**
