### PR TITLE
allow direct transition in standard vtol when landed

### PR DESCRIPTION
**Pull request by AndreasAntener**
@sanderux what you were looking for

### CODE REVIEW

**Comment by sanderux** [comment]
Nice, i'll bench test

**Comment by LorenzMeier** [comment]
@sanderux Time for testing today? 8)

**Comment by sanderux** [comment]
Nope, drive trouble.
next window is thuesday

**Comment by AndreasAntener** [comment]
Fixed and tested on our release, shouldn't be a problem to take it in master.

**Comment by AndreasAntener** [comment]
Also rebased and updated Tailsitter and Tiltrotor

**Comment by LorenzMeier** [comment]
Can you look at the build failure?

**Comment by AndreasAntener** [comment]
If I build locally for v2 with GCC 4.8.4 I get a flash overflowed error.

**Comment by AndreasAntener** [comment]
Jenkins test this please

**Comment by LorenzMeier** [comment]
@AndreasAntener If the local build issue persists on master please let me know.

**Pull request closed without merging**
