### PR TITLE
delete unused RC_DSM_BIND param

### PR DESCRIPTION
**Pull request by dagar**
QGC initiates the bind over mavlink.

### CODE REVIEW

**Comment by dagar** [comment]
Tested on a pixracer.

**Comment by TSC21** [comment]
Jenkins test this please.

**Comment by TSC21** [comment]
@dagar so this automates DSM binding from QGC without the need of a parameter?

**Comment by dagar** [comment]
I believe the param method was a bit of a hack, but QGC has used the Mavlink method for a long time.

**Comment by TSC21** [comment]
What Receiver did you test?

**Pull request merged**
