### PR TITLE
Move cpu load out of vehicle_status (cherry-picked)

### PR DESCRIPTION
**Pull request by julianoes**
These are the cherry-picked commits from #3882.

The load computation is moved out of vehicle status and the commander.

Still to do:
- [x]  Move it to the work queue instead of its own task

### CODE REVIEW

**Comment by julianoes** [comment]
This is now working using the work queue on Pixhawk. 

@LorenzMeier can you please review the changes, especially the ones in sdlog2, thanks.

Is the load used anywhere else then on NuttX, and how would I use/test it there?

**Comment by LorenzMeier** [comment]
The commander uses it and sets LEDs if it sees overload. And it gets sent via MAVLink.

**Comment by julianoes** [comment]
But is it used on POSIX for instance?

**Comment by julianoes** [comment]
@LorenzMeier I just checked and the CPU load still arrives correctly in commander and it gets sent over mavlink correctly as well.

**Comment by julianoes** [comment]
The sdlog2 fixes alone are now done in #4402.

**Comment by julianoes** [comment]
I've rebased this branch on master since #4402 has gone in and resolved all the merge conflicts.

Tested on Pixhawk. CPU load shows correctly in mavlink, sdlog2 and top.

**Comment by julianoes** [comment]
Please review @LorenzMeier.

**Comment by julianoes** [comment]
When will this go in?

**Comment by julianoes** [comment]
Fixed merge conflicts once again.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
