### PR TITLE
Mavlink statustext relaying

### PR DESCRIPTION
**Pull request by sanderux**
This enables onboard computers to send statustext messages to connected GCS's
Tested both in SITL and with radio telemetry modules

/cc @AndreasAntener

### CODE REVIEW

**Comment by mhkabir** [comment]
Why don't you just turn on forwarding in the Mavlink app instead of creating this special case?

**Comment by sanderux** [comment]
There are a number of issues when having everything forwarded at least when using dronekit. For one it doesnt understand the heartbeat sent from the gcs.

But perhaps this is something that should be resolved on that side. Maybe it's better to change this to enable regular forwarding on a parameter

**Comment by LorenzMeier** [comment]
@sanderux Sounds like something is not set up correctly in the forwarding module then.

**Comment by sanderux** [comment]
Why, should it not forward all messages then? I think the issue is in dronekit in this case, it should ignore heartbeats from non-fc's or really bind to one fc instance

**Comment by LorenzMeier** [comment]
It should forward all messages. Also: The heartbeat from Dronekit should not be an issue as long as you have set the same system ID and a different component ID. If you didn't then Dronekit is not configured correctly or the forwarding masking has an issue that needs to be fixed.

**Comment by sanderux** [comment]
The issue is not the heartbeat from dronekit, it's the heartbeat from QGC that confuses dronekit

**Comment by LorenzMeier** [comment]
We can put a hack into the forwarding code to work around it, but that just means we need to fix the API @mrpollo.

**Comment by sanderux** [comment]
@mrpollo this is a simple hack to ignore groundstation heartbeats:

image

Probably not the best way but it seems to work.
Next issue is parameters not getting loaded (most likely QGC issues a HASH_CHECK for params requested by dronekit)

**Pull request closed without merging**
