### PR TITLE
SDP3X : correct scales

### PR DESCRIPTION
**Pull request by rde-mato**
I think the scales defines for the sdp3x airspeed sensors aren't correct.
Please review !

http://www.mouser.fr/ds/2/682/Sensirion_Differential_Pressure_Sensors_SDP3x_Digi-953230.pdf page 10
image

https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/8_Differential_Pressure/Sensirion_Differential_Pressure_Sensors_SDP33_Datasheet.pdf page 10
image

### CODE REVIEW

**Comment by dagar** [comment]
Thanks @rde-mato, have you done any testing with the actual sensors?

**Comment by rde-mato** [comment]
Not on PX4 Frimware,
I'm working on sdp3x driver for Ardupilot, made a test bench to compare
values, seems to be right.
When i copy/paste the code from PX4 to Ardupilot, i saw this error.
PX4 use their defines to get id device ? Am i right ? Nothing change on
sensor reading values ...

if you have any suggestions, tell me !

Remi

2017-10-11 16:25 GMT+02:00 Daniel Agar <notifications@github.com>:

**Comment by dagar** [comment]
@LorenzMeier or @AndreasAntener could you take a look at this or recommend someone that can?

**Comment by LorenzMeier** [comment]
Yes, this is correct. The define is used no-where in the driver for actual data conversion (only to store the sensor type), so it could have slipped through without de-railing the sensor performance.

**Pull request merged**
