### PR TITLE
fix voltage & current scaling for H7

### PR DESCRIPTION
**Pull request by bkueng**
Fixes the scaling on h7 boards: the ADC has 16 bits resolution (vs 12 bits on F4/F7). Otherwise the logic on the durandal is the same as on fmu-v5, therefore the board-specific scalings do not need to be changed.

I also wanted to remove  `BAT_CNT_V_VOLT` and `BAT_CNT_V_CURR` completely, as I don't think they are required. But it would conflict with  #12551 even more.
@ItsTimmy fyi

### CODE REVIEW

**Comment by LorenzMeier** [comment]
They are required for things like the Mauch power modules IIRC. A lot of adopters rely on those custom setups.

**Comment by bkueng** [comment]
You can directly use `BAT_A_PER_V` and `BAT_V_DIV`. The formulas are:
```
(buf_adc[i].am_data * _parameters.battery_voltage_scaling) * _parameters.battery_v_div;
((buf_adc[i].am_data * _parameters.battery_current_scaling)
		  - _parameters.battery_current_offset) *_parameters.battery_a_per_v;
```
And thus there's a redundancy.

**Comment by bkueng** [comment]
So you want me to change that as well? Personally I would keep that for now until we actually have a board that is different.

**Comment by davids5** [comment]
Since we are making this better, yes because it is just more things to forget later and is bad to have buried magic number.  

#define BOARD_ADC1_POS_REF_VOLTAGE
#define BOARD_ADC2_POS_REF_VOLTAGE
#define BOARD_ADC3_POS_REF_VOLTAGE

**Comment by bkueng** [comment]
Alright, done.

I also added the durandal (and others) to the list of supported boards in the README.

**Pull request merged**
