### PR TITLE
Excelsior Config Changes

### PR DESCRIPTION
**Pull request by jywilson**
Adding support to build PX4 Firmware to run on the Excelsior board.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@julianoes Please review and merge.

**Comment by julianoes** [comment]
@jywilson The changes look good on a first pass. However, I'm really quite confused about what this all is? Future readers that are not informed about Snapdragon, Eagle, etc. will be struggling even more.

Could you add some comments that explain what `sdflight`, `eagle`, and `excelsior` mean? Thanks.

**Comment by jywilson** [comment]
@julianoes The Eagle board is our first generation Snapdragon Flight board.  We are currently in development on another board, code named Excelsior.

We want to be sure that PX4 is supported at the moment Excelsior is released, and we will be pushing changes to address any issues we find.  My hope is that they are *not* Excelsior specific issues and that anything we upstream will also benefit the Eagle board.  We needed these config files though to address a few build differences.

**Comment by LorenzMeier** [comment]
@julianoes Could you test on hardware including arming and add comments? I hope that I have the param fix on master by the time @davids5 Has his fixes in.

**Comment by julianoes** [comment]
@LorenzMeier yes will do.

**Comment by julianoes** [comment]
Closing this PR, the commits have been rebased in #4442.

**Pull request closed without merging**
