### PR TITLE
adding avioneo's airframe geometry VTOL Penta Tiltwings

### PR DESCRIPTION
**Pull request by yvescharles**
+ avioneo's airframe doc init.d 13015 + CMakeLists
+ avioneo's airframe mixers main + aux
+ avioneo's airframe penta tiltwings geometry + CMakeLists
+ px4airframes Tools srcparser
svg also pull in docs&qgc

first commit for a newbie :)

### CODE REVIEW

**Comment by hamishwillee** [comment]
This error means often means the flash is too big (>1MB). It could mean that you're not using the right compiler https://dev.px4.io/en/setup/building_px4.html#building_nuttx or that you've added too much to the Firmware, so that it has overflowed. I'd confirm that you're using the right compiler and that a "bog standard" build works first.

**Comment by yvescharles** [comment]
Was talking about the Jenkins test supposed to have the right compiler. The building process seems to be ok (W/O fatal error on my own docker)
testing into the pixhawk....
Thanks

**Comment by yvescharles** [comment]
As I said before,  the building run of px4fmuv3 on my local docker is ending fine w/o error. fmuv2 seems to be a common failure, so please help me to fix I you have any idea !

**Comment by hamishwillee** [comment]
@bkueng Your advice appreciated.
1. There is a jenkins failure that appears unrelated to these changes. 
2. Apparently FMUv3 builds, but FMUv2 fails (I *think*) when using the correct compiler. I think they means they will need to remove a module to get this in. Any thoughts on what.

**Comment by yvescharles** [comment]
@hamishwillee @bkueng at this point the fmuv3 I build doesn't work correctly with probably a bug somewhere (Missing Params : -1:FW_ARSP_MODE Preflight fail on QGC : compass Sensor 0 missing)
Any help will be appreciated

**Comment by yvescharles** [comment]
@TSC21 got the "ccache permission issues, disabling" mess from entrypoint.sh you contribute on. Anything to do ? Thx

**Comment by TSC21** [comment]
@yvescharles I have no idea of what are you talking about

**Comment by yvescharles** [comment]
@TSC21 Find file containers/docker/px4-dev/scripts/entrypoint.sh line 16, you seem to be list in the 2 contributors ?

**Comment by TSC21** [comment]
I never messed with the ccache part of the script. But as it says, you probably have permissions issues when accessing the ccache. But why is that even relevant you?
Also if you want to see who has done what on a file, you have a button on the top left corner of the page where you have the file opened called "Blame" ;)

**Comment by yvescharles** [comment]
OK should ask @daga, Daniel could you help ? Thx

MacBook-Air-de-Yves:Firmware yv$ sudo ./Tools/docker_run.sh "make airframe_metadata"
Password:
guessing PX4_DOCKER_REPO based on input
PX4_DOCKER_REPO: px4io/px4-dev-nuttx:2018-11-22
Starting with UID : 0
**chown: changing ownership of '/Users/yv/.ccache': Operation not permitted
ccache permission issues, disabling**
ninja: Entering directory `/Users/yv/Docker/Px4/src/Firmware/build/px4_sitl_default'
[0/1] Re-running CMake...
-- PX4 config file: /Users/yv/Docker/Px4/src/Firmware/boards/px4/sitl/default.cmake
-- PX4 config: px4_sitl_default
-- PX4 platform: posix
-- PX4 version: v1.8.0-1828-g0c2c8cad22
-- cmake build type: RelWithDebInfo
-- PX4 ECL: Very lightweight Estimation & Control Library v0.9.0-608-gacde4eb
-- Configuring done
-- Generating done

**Comment by yvescharles** [comment]
> I never messed with the ccache part of the script. But as it says, you probably have permissions issues when accessing the ccache. But why is that even relevant you?
> Also if you want to see who has done what on a file, you have a button on the top left corner of the page where you have the file opened called "Blame" ;)
trying to understand to find the bug origin
at this point the fmuv3 I build doesn't work correctly with probably a bug somewhere (Missing Params : -1:FW_ARSP_MODE Preflight fail on QGC : compass Sensor 0 missing)
Any help will be appreciated

**Comment by TSC21** [comment]
@yvescharles do you know what ccache is for? Even if you get ccache disabled, it's not relevant for your problem.

**Comment by yvescharles** [comment]
@TSC21 thanks; as it written in the top it's my first commit from a newbie ;) Thx for your help, I apprericate

**Comment by TSC21** [comment]
Btw: this is supposedly a pull request to add an airframe configuration upstream. So where are the config files? Why are you constantly reverting and readding the files on commits.

**Comment by yvescharles** [comment]
@TSC21 Nuno, I probably misunderstanding something simple for you somewhere for sure ! Indeed, this conversation is for me attached to a pull request where the config files commited can be seen here : https://github.com/PX4/Firmware/pull/10931/commits/6b91be99bd62d7a22ddc5813cb5caeb2d1eecf25
where I'm wrong ?

**Pull request closed without merging**
