### PR TITLE
Tune down solo attitude rate controller

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Describe problem solved by this pull request**
The solo model was showing visible oscillations while flying. 

**Describe your solution**
Tuning down the rate controller removes the oscillations. 

**Test data / coverage**
Before PR: 
ezgif com-video-to-gif
Log: https://review.px4.io/plot_app?log=4bd411a0-818e-4cdc-96d7-27f796088eb3

After PR: 
Log: https://review.px4.io/plot_app?log=9aafa587-8c42-4d85-bddb-8a3768d7171e

**Additional Context**
Fixes https://github.com/PX4/Firmware/issues/11405

### CODE REVIEW

**Comment by dagar** [comment]
Quick pass over the multicopter position controller while you're at it?

Screenshot from 2020-05-21 09-40-26


Could we also do something to only send differential pressure when it's appropriate?

Screenshot from 2020-05-21 09-41-36

**Comment by jungx148** [comment]
A very similar problem happens with a Typhoon h480 hexacopter as shown in the following video clip.

ezgif com-video-to-gif

Tried to fix the issue by referring to the following link and lowering values of MC_PITCHRATE_P and MC_ROLLRATE_P, but did not succeed yet.

[https://github.com/PX4/PX4-Autopilot/pull/14952/commits/62d005434fcba70faa144a1a0e9cf7621c88f6df](url)

**Comment by Jaeyoung-Lim** [comment]
@jungx148 That seems like a separate issue, please create a new issue for it

**Comment by jungx148** [comment]
Okay thanks for a quick response. I opened a new topic.

https://discuss.px4.io/t/oscillations-occurs-during-hovering-typhoon-h480-hexacopter/19584

**Pull request merged**
