### PR TITLE
InvenSense ICM-42688-P IMU driver

### PR DESCRIPTION
**Pull request by dagar**
This is a new InvenSense sensor with max output data rate of 32 kHz (both accel & gyro), on board anti-aliasing filter, and optional higher resolution output (18 bit accel, 19 bit gyro).

TODO:
 - [x] add temperature readings
 - [x] use FIFO watermark (verify INT1 & INT2) 
 - [x] consider using high resolution accel (18 bit) & gyro (19 bit)
 - [x] review onboard filter settings (notch and anti-aliasing)
 - [x] testing

### CODE REVIEW

**Comment by dagar** [comment]
Bench tested.

Screenshot from 2020-03-19 15-26-39

**Comment by dagar** [comment]
I've left the notch and anti-aliasing filter settings default for now.

**Comment by dagar** [comment]
@modaltb this is good to go from my perspective. The cpu load from this alone will be quite high (~ 30%) until we enable SPI DMA (shortly https://github.com/PX4/Firmware/pull/14356).

**Comment by modaltb** [comment]
legit, I'l get into some flight testing early next week with this, I appreciate the effort from you on this, very helpful!

**Comment by dagar** [comment]
Merging this now so that we can include it in the big refactor (https://github.com/PX4/Firmware/pull/14438).

@modaltb if you have an issue it can be trivially disabled temporarily by commenting it out here. https://github.com/PX4/Firmware/blob/b483fd5c9896a4608cd756d9708e2b78bbc67ac1/boards/modalai/fc-v1/default.cmake#L29

**Comment by modaltb** [comment]
All good we'll use it and provide testing, much appreciated!

**Comment by Andrew-546** [comment]
it's wonderful! but could you introduce how to use the timestamp？

**Comment by dagar** [comment]
> it's wonderful! but could you introduce how to use the timestamp？

@Andrew-546 do you mean the clock input?

**Comment by Andrew-546** [comment]
it's mean that we get IMU data by using FIFO, which has a TIMESTAMP INTERVAL SCALING. how to use TIMESTAMP INTERVAL SCALING, or it's not necessary to use it.

**Comment by dagar** [comment]
> it's mean that we get IMU data by using FIFO, which has a TIMESTAMP INTERVAL SCALING. how to use TIMESTAMP INTERVAL SCALING, or it's not necessary to use it.

I don't think it's necessary to use because we know how it's been configured and we collect every sample. I'd also like to start using the clock input on this part where it's available.

**Comment by Andrew-546** [comment]
thank you very much. I will make a try.

**Pull request merged**
