### PR TITLE
BST (Black Sheep Telemetry) protocol support

### PR DESCRIPTION
**Pull request by DrTon**
Driver for BST devices connected to I2C port. Tested with [TBS Crossfire RX](http://www.team-blacksheep.com/products/prod:crossfire_8chrx).

Driver sends the following messages:

- Attitude (not yet supported by Crossfire TX)
- Battery
- GPS

TBS Crossfire TX converts these messages to mavlink and sends via Bluetooth to groundstation.

I had to change `rc.scripts` to avoid starting ms5611 driver on I2C port, it detects Crossfire RX as ms5611 chip because of the same device ID. Maybe it's possible to return it back if make chip detection more smart.

Tested in flight, battery and GPS work fine. Need more testing and adding more BST messages.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@DrTon I just pushed 0490046 to master which increases the robustness of the MS5611 detection. Could you try if that allows you to remove the -s flag for the MS5611? Otherwise we could condition it on the board and only use the -s flag for FMUv2, as done here: https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rc.sensors#L14

Could you rebase on master in the process?

**Comment by LorenzMeier** [comment]
Does the driver have the ability to scan the bus for the BST device? It would be great if we could auto-start it.

**Comment by LorenzMeier** [comment]
@DrTon Does it still wrongly detect the MS5611?

**Comment by LorenzMeier** [comment]
@DrTon Ping - I'd love to merge this, but I need to know what we do about the MS5611.

**Comment by DrTon** [comment]
> @DrTon I just pushed 0490046 to master which increases the robustness of the MS5611 detection. Could you try if that allows you to remove the -s flag for the MS5611? Otherwise we could condition it on the board and only use the -s flag for FMUv2, as done here: https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rc.sensors#L14

I can but only after two weeks, I'm away from all my toys now :(

**Comment by DrTon** [comment]
> Does the driver have the ability to scan the bus for the BST device? It would be great if we could auto-start it.

Yes, but if ms5611 driver is already running during bus scan then scan fails.

**Comment by LorenzMeier** [comment]
Well, then we can scan for this one first, if we don't find it we scan for the MS5611 via I2C. FMUv1 has it on I2C. We could also condition on the board ID.

**Comment by LorenzMeier** [comment]
I've rebased this on master, fixed the collision with the MS5611 on FMUv1 and added the code to auto-start the sensor. This needs cross-testing.

**Comment by LorenzMeier** [comment]
Binary is here:
https://dl.dropboxusercontent.com/u/87745816/nuttx-px4fmu-v2-default.px4

**Comment by dogmaphobic** [comment]
Connected the Crossfire using I2C and loaded the firmware above. For what's worth, battery data is coming through SYS_STATUS but not as BATTERY_STATUS.

screen shot 2015-12-04 at 10 58 45 am

**Comment by LorenzMeier** [comment]
Thanks @dogmaphobic! Now I could finally merge it thanks to your testing. Rebased and applied.

**Pull request closed without merging**
