### PR TITLE
Mixer for H configuration

### PR DESCRIPTION
**Pull request by DroneBuster**
Mixer for new frame type H-quad

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice, thanks!

**Comment by kd0aij** [comment]
I must be missing something... How does the new config differ from the X config?

**Comment by LorenzMeier** [comment]
Opposite rotors are on the same side. Which means that if your arms have an H layout the torque is transmitted through the stiffer mechanical part.

@sjwilks @AndreasAntener You will want to use this new config if you don't plan for an X frame for your VTOL.

**Comment by kd0aij** [comment]
That is also true for the X config, isn't it?

**Comment by LorenzMeier** [comment]
No its not if your frame shape resembles an H.

**Comment by DroneBuster** [comment]
This frame could be used on frames which suffer from flexing arms which counteracts yaw motion

**Comment by kd0aij** [comment]
Do you plan to add a diagram to this page? https://pixhawk.org/platforms/multicopters/start
A picture would be worth... a lot.

**Pull request merged**
