### PR TITLE
Driver framework latest

### PR DESCRIPTION
**Pull request by mcharleb**

### CODE REVIEW

**Comment by mcharleb** [comment]
@LorenzMeier I've spent about 4h trying to get the cmake deps for the nuttx build correct. I had to conditionally not include src/lib/DriverFramework for nuttx build. It doesn't link, but if I add the  src/lib/DriverFramework dir, it doesn't build for nuttx because it tries to build before the export dir is created.

**Comment by jgoppert** [comment]
@mcharleb I'll try to take a look tomorrow.

**Comment by LorenzMeier** [comment]
Awesome, thanks James!

**Comment by erikd** [comment]
I can recreate the problem by cloning @mcharleb's https://github.com/mcharleb/Firmware repo and then checking out the `driver_framework_latest` branch, followed by `make px4fmu-v2_default` which results in:

```
[100%] Linking CXX executable firmware_nuttx
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: cannot find -ldf_driver_framework
collect2: error: ld returned 1 exit status
src/firmware/nuttx/CMakeFiles/firmware_nuttx.dir/build.make:181: recipe for target 'src/firmware/nuttx/firmware_nuttx' failed
make[3]: *** [src/firmware/nuttx/firmware_nuttx] Error 1
CMakeFiles/Makefile2:5552: recipe for target 'src/firmware/nuttx/CMakeFiles/firmware_nuttx.dir/all' failed
make[2]: *** [src/firmware/nuttx/CMakeFiles/firmware_nuttx.dir/all] Error 2
```

**Comment by erikd** [comment]
I don't think I understand the problem well enough to be of any help yet.

**Comment by LorenzMeier** [comment]
@erikd I presume you can run this fine without a segfault?
```
make posix jmavsim
```

**Comment by davids5** [comment]
@mcharleb 

Have a look at nuttx_next_cmake version of [px4_nuttx_add_export] (https://github.com/PX4/Firmware/blob/925fd41be0c703497bd53dfc9075fc2fb6e61fcd/cmake/nuttx/px4_impl_nuttx.cmake#L251-L327) it may hep.

**Comment by erikd** [comment]
@LorenzMeier `make posix jmavsim` fails with:

```
Unable to checkout '94188fb83ab6b2da59eb9a8c8596ab49b67c42f6' in submodule path 'src/lib/dspal'
Makefile:143: recipe for target 'posix_sitl_simple' failed
```

**Comment by LorenzMeier** [comment]
Try ```git submodule sync```

**Comment by erikd** [comment]
Yep, that worked. Thanks.

**Comment by erikd** [comment]
And `make posix jmavsim` runs fine for me. The graphics in the Java (?) window don't update but the simulator does a bunch of stuff and then finishes with `WARN  mission ok` at which point I can issue a `shutdown` command.

**Pull request merged**
