### PR TITLE
FW att refactor

### PR DESCRIPTION
**Pull request by dagar**
This splits the single large FW attitude controller cpp into a separate header, implementation, and helper to start the module. This makes it easier to navigate and view the header simultaneously without significant scrolling or jumping. It also seems to be less confusing to most IDEs.

There should be no functional difference. Tested in SITL.

### CODE REVIEW

**Comment by dagar** [comment]
On top of this branch I've refactored fw_att_control to use controllib for params and uorb, but I'll try to bring it in incremental if everyone is okay with this direction.

Memory usage stayed about the same (stack decreased slightly), CPU usage decreased, and it's less code.
https://github.com/dagar/Firmware/compare/fw_att_refactor...dagar:fw_att_control_cleanup?expand=1

**Comment by jgoppert** [comment]
Looking good. Glad to see some more use of controllib. Have always thought it makes things more readable.

**Comment by Stifael** [comment]
@dagar I did a similar refactor for the position controller, but my goal was mainly to separate the app from the position controller class. I did that because I would like to call the position controller by itself and then do unit tests against its interface (at least for the beginning). 
Do you think that is a good idea / bad idea  to do? Because if you agree, then you could do the same for the fw, which basically has the same structure.

**Comment by dagar** [comment]
@Stifael like this? https://github.com/dagar/Firmware/blob/fw_att_control_cleanup/src/modules/fw_att_control/fw_att_control_main.cpp#L121

That's what I'm actually working towards, which is in the style of lpe and @jgoppert's mc_att_control rewrite that never merged. Let know what you have in mind for unit tests and we could do FW at the same time.

**Comment by dagar** [comment]
I'll reopen this once I'm done with the controllib refactor since it builds off of this and still ends up changing nearly every line.
https://github.com/dagar/Firmware/blob/fw_att_control_cleanup/src/modules/fw_att_control/fw_att_control_main.cpp#L121

**Pull request closed without merging**
