### PR TITLE
mavlink_shell.py: implement a simple shell with history

### PR DESCRIPTION
**Pull request by bkueng**
@tumbili this one is for you :)

### CODE REVIEW

**Comment by tumbili** [comment]
@bkueng Not so fast please, I first need to feel the joy of being able to use the NSH over mavlink ;-)

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Comment by julianoes** [comment]
@bkueng you should have copied it from the later history implementation of the pxh shell ;) :
https://github.com/PX4/Firmware/blob/feature_shell/src/platforms/posix/px4_daemon/history.cpp
https://github.com/PX4/Firmware/blob/feature_shell/src/platforms/posix/px4_daemon/pxh.cpp#L162

**Comment by bkueng** [comment]
why, because of the current line saving?

**Comment by julianoes** [comment]
Yes, and because I think it's nicer :)

**Pull request closed without merging**
