### PR TITLE
add GPS glitch detection based on the implementation in AP_NavEKF

### PR DESCRIPTION
**Pull request by kd0aij**
checks for abrupt change in GPS horizontal position; if detected the current North and East innovations are added to gpsPosGlitchOffsetNE, and this offset is subsequently added to the GPS posNE vector to form the observation vector. gpsPosGlitchOffsetNE is decayed radially to zero at a hardcoded rate.

Testing indicates that this eliminates attitude estimate glitches caused by GPS glitches. Not sure what the effect is on EKF position estimation accuracy, but no position glitches have been observed (yet) to be caused by this change.

### CODE REVIEW

**Comment by Zefz** [comment]
Cool, I will give this feature a try. Would it be worthwhile to simulate glitches while flying? (similar to testing GPS loss AUX1 could be mapped to induce a GPS glitch of about 10 meters instead)

Does the glitch detector not apply to vertical velocity estimates?

**Comment by LorenzMeier** [comment]
@Zefz Simulated glitches would certainly help. The Z velocity is always more noisy and if the GPS glitches it does essentially always in 3D. So the 2D implementation seems to make perfect sense.

**Comment by kd0aij** [comment]
no glitch detected in this log: http://dash.oznet.ch/view/pR9cRSDYfixhvUzzqTyRz4
and both ALTCTL and POSCTL seemed to work well.

But there are some discrepancies between onboard and test harness filter results:
attitude
Comments would be appreciated.

**Comment by kd0aij** [comment]
Glitch simulation is a great idea. I'll add a mechanism to do that

**Comment by LorenzMeier** [comment]
@kd0aij If you look at the parts where the yaw axis has a lot of motion you can clearly see that the red curve (onboard) is generally more dynamic and moves faster. One possible explanation is a different gyro bias estimate between the two and/or the test harness having a gyro scaling error or not fusing the gyro at all. I would plot the atan2(mag.y, mag.x) and gyro z to see how the input behaves. In particular the period at second 150 seems suitable to work out who is right and who is wrong.

**Comment by kd0aij** [comment]
looks like the yaw disagreement is a steady-state offset, but roll/pitch could be due to gyro scaling differences
onb_vs_test

**Comment by LorenzMeier** [comment]
I come to a different conclusion: The roll and pitch angle differences are offsets, not scaling. If they were scaling they would be symmetrical, however, they seem to disagree into one direction and independent of the magnitude.

It might be worthwhile starting the log at second 0.0 so that the bias estimation can work the same onboard and off board.

**Comment by kd0aij** [comment]
onb_vs_test2

**Comment by LorenzMeier** [comment]
Ok, now it indeed looks like the remaining effects are scaling. The yaw curves even have a different dynamic, and the red one seems to follow the gyro dynamic more.

I don't understand yet why they disagree. Maybe offset learning for the mag is enabled through the condition checks in one and disabled in the other?

**Comment by kd0aij** [comment]
Could you provide a hint as to where those condition checks are coded?

**Comment by LorenzMeier** [comment]
Its the inhibitmagstates variable here:
https://github.com/PX4/Firmware/blob/master/src/modules/ekf_att_pos_estimator/estimator_22states.cpp#L1265

**Comment by LorenzMeier** [comment]
Which is set here:
https://github.com/PX4/Firmware/blob/master/src/modules/ekf_att_pos_estimator/estimator_22states.cpp#L2542

**Comment by LorenzMeier** [comment]
@kd0aij I presume to unblock this I would need to run your dataset and see if I can identify the source of the last few differences? Could you upload your dataset to dropbox?

**Comment by kd0aij** [comment]
@LorenzMeier I had shifted focus to the flight problems and PX4Flow while waiting to hear back from Paul. My last email to him asked whether he'd prefer Skype/similar or email for discussion and I'm still waiting for a reply. May have gotten lost in the shuffle, but I feel that my understanding of the EKF is inadequate at this stage for high-level work on it. I had posted a few concerns and questions somewhere which need to be answered next; things like "why does the sign of the innovation seem wrong to me".
I'll work on getting my dataset up where you can see it.

**Comment by kd0aij** [comment]
@LorenzMeier I pushed my current code state to https://github.com/kd0aij/InertialNav/tree/gpsGlitchDetection and compressed the entire code and scripts folders to put on Dropbox. The state of those compressed folders should be correct for running my latest dataset, plus there are several others which might be of interest. The Dropbox link is https://www.dropbox.com/sh/x0znftxwebjks2z/AAC7eQJkhq7Qa4oOZs1g5gHta?dl=0 and the upload should complete in a few minutes.

**Pull request closed without merging**
