### PR TITLE
Prevent height set-point variations due to bad GPS

### PR DESCRIPTION
**Pull request by LorenzMeier**
Fixes: #6193

TODO

Code review
Compatibility testing with LPE

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by jgoppert** [comment]
image


I still get a momentary spike in sitl if I:
1. stop gpssim
2. stop lpe
3. start lpe
4. takeoff (momentary spike back to command alt 0,  probably unrelated to this issue, maybe should fix)
4. start gpssim (no spikes)

**Comment by LorenzMeier** [comment]
This keeps failing on the SITL CI. Needs inspection.

**Comment by Stifael** [comment]
ci/sitl/pr: cannot see output since job cannot be found

**Comment by ChristophTobler** [comment]
@LorenzMeier I don't think the whole ```update_ref()``` is needed at all. ```update_ref()``` as it currently is in master has the following two effects: 
* drifting during the phase where we got GPS but it's not yet initialized (```[lib__ecl] EKF commencing GPS fusion```) because the setpoint moves with the quad position
* a jump in position (x,y and z) after initialization because the setpoints will be shifted the same amount like they currently are from 0

This happens e.g. if you start with flow and then start to use GPS. The result is a sudden movement which is never desired. Removing ```update_ref()``` also fixes the problem with the height.

**Comment by ChristophTobler** [comment]
Not fully true... I guess https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L866-L867 are needed. But I'm happy someone could explain me why we need the rest.

**Comment by LorenzMeier** [comment]
We need this definitely in. Its part of the recent flakiness of RTL.

**Comment by dagar** [comment]
Rebased on master.

**Comment by LorenzMeier** [comment]
I've changed this to reflect what I think it should be - which makes this PR a no-op. It just improves documentation and EKF status reporting.

**Pull request merged**
