### PR TITLE
cmake update nuttx bloaty_compare_master helper to use new paths

### PR DESCRIPTION
**Pull request by dagar**
`make px4_fmu-v2_default bloaty_compare_master`

### CODE REVIEW

**Comment by hamishwillee** [comment]
Does this need docs? If so.
- Can anyone use if from anywhere
- What does it do/what is it for
-  Is it listed in `make px4_sitl list_vmd_make_targets` ?

**Comment by dagar** [comment]
It downloads the last successful master build and uses (bloaty)[https://github.com/google/bloaty} to compares with your local build. It can help you get a better understanding of code size, in particular when dealing with things like px4_fmu-v2_default hitting the 1MB flash limit.

For example, let's say I wanted to see the impact of removing the mpu9250 driver from px4_fmu-v2_default.

``` console
 % git diff
diff --git a/boards/px4/fmu-v2/default.cmake b/boards/px4/fmu-v2/default.cmake
index 40d7778..2ce7972 100644
--- a/boards/px4/fmu-v2/default.cmake
+++ b/boards/px4/fmu-v2/default.cmake
@@ -36,7 +36,7 @@ px4_add_board(
                imu/l3gd20
                imu/lsm303d
                imu/mpu6000
-               imu/mpu9250
+               #imu/mpu9250
                #iridiumsbd
                #irlock
                #magnetometer # all available magnetometer drivers
```

**Comment by dagar** [comment]
The bloaty helper target only exist if you have bloaty in the environment. It's not a tool most will ever use, but it is in the docker containers.

**Comment by hamishwillee** [comment]
I tried this on ubuntu 16.04 after first building px4_fmu-v2_default successfully, and then building bloaty and copying it usr/local/bin as shown in the [docker container](https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_nuttx#L45)
```
ubuntu@ubuntu:~/src/Firmware$ make px4_fmu-v2_default bloaty_compare_master
ninja: Entering directory `/home/ubuntu/src/Firmware/build/px4_fmu-v2_default'
ninja: error: unknown target 'bloaty_compare_master'
Makefile:171: recipe for target 'px4_fmu-v2_default' failed
make: *** [px4_fmu-v2_default] Error 1
ubuntu@ubuntu:~/src/Firmware$ 
```

What do I have to do to register bloaty so that the toolchain can find it?

I do appreciate that not everyone would use it, but might as well document anyway.

**Comment by dagar** [comment]
It has to be in your path and found and cmake configure time.

Try

``` Console
while bloaty
make clean
make px4_fmu-v2_default bloaty_compare_master
```

**Comment by hamishwillee** [comment]
Thanks, working now. For your review in https://github.com/PX4/Devguide/pull/678

**Pull request merged**
