### PR TITLE
Perf improvements for SITL

### PR DESCRIPTION
**Pull request by bkueng**
This shows the CPU cycles used in SITL, master (user-space only):
perf_improvement_before

The top one px4_ioctl is called by orb_check. Then the other top contributers come from locking, namely 2 places: `hrt_absolute_time` and the DriverFramework, they all use `pthread_mutex_lock`:
perf_improvement_locking

The VDev::getDev() call is called from px4_access, which is called from orb_exists.

This PR improves the VDev::getDev() call by using a std::map (the following includes https://github.com/PX4/DriverFramework/pull/220 as well):
perf_improvement_after

There is still room for improvements, especially in the DriverFramework and `hrt_absolute_time`.

### CODE REVIEW

**Comment by TSC21** [comment]
@dagar was concerned about the orb_check() performance issues. Maybe we can do something more regarding its usage?

**Comment by nicolaerosia** [comment]
@bkueng what are you using to generate the graphs?

**Comment by dagar** [comment]
@nicolaerosia that's kcachegrind. https://github.com/PX4/Firmware/pull/6521

**Comment by bkueng** [comment]
Exactly. Run it with `ninja jmavsim___callgrind` to generate the data.

**Comment by bkueng** [comment]
@nicolaerosia CI fails with:
```
../src/lib/DriverFramework/framework/src/DevMgr_Nuttx.cpp:116:91: error: no 'int DriverFramework::DevMgr::waitForUpdate(DriverFramework::UpdateList&, DriverFramework::UpdateList&, unsigned int)' member function declared in class 'DriverFramework::DevMgr'
 int DevMgr::waitForUpdate(UpdateList &in_set, UpdateList &out_set, unsigned int timeout_ms)
```
Could you have a look, as you did some cleanup there?

**Comment by nicolaerosia** [comment]
@bkueng could you please add a commit which nukes `DevMgr::waitForUpdate` from `DriverFramework/framework/src/DevMgr_Nuttx.cpp` ? Somehow this slipped DriverFramework CI

**Comment by bkueng** [comment]
> @bkueng could you please add a commit which nukes DevMgr::waitForUpdate from DriverFramework/framework/src/DevMgr_Nuttx.cpp ?

Done. Was simpler than I expected.

**Pull request merged**
