### PR TITLE
Adding analog sonar sensor. closes #7664

### LINKED ISSUE #7664: Maxbotix sonar sensor not working
Hi,

I would like to use maxbotix MB1240 sonar sensor with px4, but unfortunately it's not working.

I've connected the sonar according to [this](http://ardupilot.org/copter/docs/common-rangefinder-maxbotix-analog.html) guide. I hear the sonar, so it should work. Then I uncommented line **#drivers/mb12xx** in **nuttx_px4fmu-v2_default.cmake** file. After that I just compiled the whole thing with `make px4fmu-v2_default` command and uploaded it with `make px4fmu-v2_default upload`. Finally I enabled the **SENS_EN_MB12XX** parameter.

But when I try to display the **distance_sensor** message in MAVLink inspector, I can't see it.

I'm using px4 firmware v1.6.5 with QGroundControl v3.2.1.

Does anybody know what's going on? Did I something wrong or am I missing something?

Thank you for answer.

### PR DESCRIPTION
**Pull request by L4ncelot**
Adding driver for analog sonar sensors. Tested with maxbotix mb1240 sonar.

### CODE REVIEW

**Comment by TSC21** [comment]
@L4ncelot can you fix the conflicts?

**Comment by L4ncelot** [comment]
@TSC21 sure, only how to do that? I'm using CLion for this and in the VCS menu the `resolve conflicts ` is greyed out. I think I need to do `git pull` or something but I'm not sure, I've never done that before.

**Comment by TSC21** [comment]
`git pull` master to your branch and resolve the cobflicts manually. Then commit the changes again.

**Comment by L4ncelot** [comment]
@TSC21 what if I was working on v1.6.5? Should I change the pull request to merge the v1.6.5 tag? Because when I pulled the master branch, I see that some code in firmware has changed. Or should I resolve it so it works in master? Please excuse my lack of knowledge about git :).

**Comment by TSC21** [comment]
If the master branch has changes that are incompatible with the changes you have on the branch you used, you will have to rebase on master and apply the changes. I advise you to redo those changes against master or rebase and change the conficts.

**Comment by L4ncelot** [comment]
@TSC21 , the problem should be fixed now. But I'm not sure, I kind of lost myself in git along the way :). But now the code should compile under the master branch (if I did the rebase of my forked repository correctly).

**Comment by TSC21** [comment]
Can you `squash` the commits into one please? (https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/)

**Comment by L4ncelot** [comment]
@TSC21 , I don't know if I made it worse...

**Comment by TSC21** [comment]
> @TSC21 , I don't know if I made it worse...

What's the output of `git rebase -i HEAD~8`?

**Comment by L4ncelot** [comment]
```
pick ae1f838 disable uavcan build to make space for other modules
pick 98bd6e4 SDP3x: Add model for pitot pressure drop
pick c44322c MAVLink app: Use more advanced forwarding logic
pick 9124617 MAVLink: Always enable forwarding for companion link
pick 7612b94 Allow relaying from same system ID or with target component 0
pick 1eda66c Code format
pick dc8caea MAVLink: Default to standard stream config
pick 82f9d46 # This is a combination of 2 commits. # The first commit's message is:

# Rebase f746f9a..82f9d46 onto f746f9a (8 command(s))
```

**Comment by TSC21** [comment]
yeah since you merged master, now the commit history is mixed with yours. Better to close this one and create a new PR with a clean commit history.

**Comment by L4ncelot** [comment]
Ok, I'll do it. Hope this time the right way...

**Pull request closed without merging**
