### PR TITLE
Update submodule ecl to latest Thu Feb  6 00:39:33 UTC 2020

### PR DESCRIPTION
**Pull request by dagar**
- ecl in PX4/Firmware (a95f1c88fc011a46e8c7c130f8304ea17399103e): https://github.com/PX4/ecl/commit/ed260c4f1db8545d8ad3aa7f05d951857436ef87
    - ecl current upstream: https://github.com/PX4/ecl/commit/89bcebd631024a1a91babb7b68f197dc3b6e5ca8
    - Changes: https://github.com/PX4/ecl/compare/ed260c4f1db8545d8ad3aa7f05d951857436ef87...89bcebd631024a1a91babb7b68f197dc3b6e5ca8

    89bcebd 2020-01-30 Paul Riseborough - EKF: Prevent covariance initialisation overwriting yaw variance
    a3347b7 2020-01-30 Paul Riseborough - EKF: Use more conservative value for delta velocity bias process noise
    21054a4 2020-01-30 Paul Riseborough - EKF: Fix bug causing incorrect covariance initialisation

### CODE REVIEW

**Comment by dagar** [comment]
@priseborough @RomanBapst any testing you'd like to see here before the ecl update with the covariance initialization fix (https://github.com/PX4/ecl/pull/739) goes into PX4/Firmware master?

**Comment by jorge789** [comment]
### Tested on PixRacer V4

**Indoor Flight Test**
Modes Tested
Stabilized Mode: Good.

**Procedure**
Arm and Take off in stabilized mode.

**Notes**
No issues noted, good flight in general.

**Log**   https://review.px4.io/plot_app?log=11153d21-ec17-4dfc-8bb6-c161131f06a1

### Tested on CUAV nano V5

**Indoor Flight Test**
Modes Tested
Stabilized Mode: Good.

**Procedure**
Arm and Take off in stabilized mode.

**Notes**
No issues noted, good flight in general.

**Log**   https://review.px4.io/plot_app?log=9fd00bfb-68e0-4e9a-a7ad-6f519f0b9707

**Comment by dannyfpv** [comment]
Tested on pixhawk4 v5 f-450
Indoor Flight Test
Modes Tested
Stabilized Mode: Good.

Procedure
Arm and Take off in stabilized mode.

Notes
No issues noted, good flight in general.

Log
https://review.px4.io/plot_app?log=f06345f6-8b34-4882-9fcd-74388ad8648d

**Comment by dagar** [comment]
Closing in favor of https://github.com/PX4/Firmware/pull/14147.

**Pull request closed without merging**
