### PR TITLE
ROI - move handling to Navigator

### PR DESCRIPTION
**Pull request by dagar**
-  moves all ROI handling (VEHICLE_CMD_NAV_ROI/VEHICLE_CMD_DO_SET_ROI) out of commander and into navigator
 - add vehicle_command_ack for navigator handled vehicle_commands
 - change vehicle_status system_id and component_id to proper size

### CODE REVIEW

**Comment by dagar** [comment]
@ndepal please check that this doesn't break your new ROI behaviour.

**Comment by ndepal** [comment]
Tested in SITL, something is broken.
The navigator exits when the vehicle reaches a `MAV_CMD_NAV_ROI` and the vehicle just stays where it is.

Reproducible with this mission: https://pastebin.com/EfsAW6Qk

**Comment by dagar** [comment]
Thanks for testing, there was an extra break in the command handling.

Thinking about this a little more we probably don't actually need the vehicle_roi uORB message. Navigator could be handling ROI mission/vehicle commands, then republishing MOUNT commands. That's probably worth doing if anyone ever wants the other parts of ROI implemented (wp index, roi target ids).

**Comment by dagar** [comment]
@ndepal would you mind giving this another quick test?

**Comment by ndepal** [comment]
Tested this again. Works as expected. Except that the ROI mission item now must not be in `MAV_FRAME_MISSION`. This was not required before. Is this a deliberate requirement?

**Comment by dagar** [comment]
Yes, it will be important to specify the frame on the QGC side.

image

**Comment by ndepal** [comment]
Fair enough

**Pull request merged**
