### PR TITLE
[WIP] new logger continued

### PR DESCRIPTION
**Pull request by bkueng**
Changes to the new logger. Some things I plan to do:
- add a file header magic
- support for nested topics
- add a dropout message so a reader can detect where dropouts occured.

Needs to be in sync with https://github.com/DrTon/FlightPlot/pull/67

I'd like to finalize the on-disk format so work on the logger/reader/replay can continue independently.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Comment by kd0aij** [comment]
@bkueng It looks like some of these changes aren't yet handled by https://github.com/DrTon/FlightPlot/pull/67

**Comment by bkueng** [comment]
@kd0aij which ones?

**Comment by kd0aij** [comment]
Didn't you change the order of some of the fields in the log?

**Comment by bkueng** [comment]
Yes and I updated the reader as well: https://github.com/PX4/jMAVlib/commit/99697d78fe1c5577c8bf70b86c8c2615ce416b51
The current reader is able to parse the logs of this branch.

**Comment by kd0aij** [comment]
Sorry, I must have been looking at my own fork, instead of yours.

**Comment by kd0aij** [comment]
@bkueng This is looking great! It would be great if we could add some log entries for Mission state, such as current WP and a list of all WPs, to make it possible to annotate a KML track. Similar to this: https://github.com/DrTon/FlightPlot/issues/46

**Comment by LorenzMeier** [comment]
Mission state is easy, we can just use the mission topic. @bkueng Mission items can be pulled out of the data manager, using the information from the mission topic. So when it updates we could just fit stuff into the log.

**Comment by bkueng** [comment]
Can we publish mission items via orb as well?

**Comment by LorenzMeier** [comment]
Now with buffering we could think about an API change. Maybe the first step would be to publish them at a throttled rate and not touch any of the navigation logic - so only for logging.

**Pull request closed without merging**
