### PR TITLE
Correct thrust magnitude to apply controller's desired vertical thrust despite attitude tracking errors.

### PR DESCRIPTION
**Pull request by devbharat**
Make sure that at transients when pitch and roll angles are different from setpoints, these errors don't pour into altitude and altitude rate control.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@AndreasAntener @dagar Jenkins seems to have an issue.

@MaEtUgR Please review.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by devbharat** [comment]
Hold on, sign error, I'll fix.

**Comment by LorenzMeier** [comment]
@devbharat My expectation is that you've tested and proven this in simulation before you propose a PR 8).

**Comment by MaEtUgR** [comment]
I'm not entirely sure if I get your idea.
So the goal in my opinion should be to project the thrust force set point 3D vector onto the 3D direction that we are actually able to produce total thrust with the multicopter because of its momentary attitude. So we do not produce thrust in the wrong direction but rather first get to the right attitude.

The calculation you wrote dividing by R(2,2):
- assumes that the thrust force set point element `thrust_sp(2)` does always point in the negative z-direction of the world frame (straigt upwards to the sky)
- does increase the thrust if we have a wrong alignment instead of decreasing like a projection would do

The results would then be additional thrust into the wrong direction just to keep up the thrust force set point in the negative world z-direction.
So please correct me if I got something wrong but if I understand it correctly it's not the approach I expected. Just imagine a steep tilt angle occurs then you would give full thrust (divide by a small number).

**Comment by Stifael** [comment]
I agree with @MaEtUgR. In addition, I dont see why increase the thust magnitude if the tilt is large.

**Comment by devbharat** [comment]
> I agree with @MaEtUgR. In addition, I dont see why increase the thust magnitude if the tilt is large.

I think we do need to cap the increase. Ideally though, if you have a model for the 'lift'(i am mostly thinking as a tailsitter) at very high tilt angle, the demanded thrust_sp(2) would be very low to begin with (tending to zero). But I see that it could be an ugly 0/0 scenario.

> So the goal in my opinion should be to project the thrust force set point 3D vector onto the 3D direction that we are actually able to produce total thrust with the multicopter because of its momentary attitude.

I don't think it is possible to produce the desired thrust components in all three directions simultaneously if attitude and attitude directions are different. Thus, scaling `thrust_abs` here by `_R(2, 2)` ensures that the vertical component of the produced thrust is just right, producing more/less thrust in the horizontal plane depending on how bad the attitude tracking is. It's like sacrificing xy velocity tracking at transients for rejecting induced disturbance in velocity z tracking.

> assumes that the thrust force set point element thrust_sp(2) does always point in the negative z-direction of the world frame (straigt upwards to the sky)
thrust_sp(2) is vertical though, but could be up or down depending on the sign. If desired `thrust_sp(2)` and `_R(2, 2)` are both pointing in the same direction up or down, the scaling is correct. If they are opposite though, (which would be a huge tilt angle tracking error), I do see a problem.

Another problem I see here, which is more for tailsitters than quads, is the response time of thrust. Pitch, when actuated by flaps, can oscillate much faster than throttle with their motor constants, scaling one with the other at high frequency could induce instabilities.

**Comment by MaEtUgR** [comment]
Sorry but I'm always thinking in multicopter terms because this controller will be extensively used with multicopters. And regardless of any improvement to altitude tracking when in near hovering state or using a VTOL, a multicopter could go unstable if it ever encounters a big tilt angle (even its just for a short time). Also I don't see how this would improve multicopter flight. I can not speak for VTOL... sorry for that.
I have to give it a try in SITL.

**Comment by MaEtUgR** [comment]
I have to revise my comments after extensive testing in STIL.
I can not explain why but your change produced the best behavior in all my testing with extreme position tilting with the iris.
The only difficulty I saw was slow recovery from very steep tilt angles but the original implementation was already wobbling unpredictable in the same situation.
So as a conclusion it works and I can not explain why.

**Comment by devbharat** [comment]
@MaEtUgR We just flew it in outdoor tests today. My suspicion was right in that although it produced better altitude tracking with tilt errors, sometimes it got thrust into rapid oscillations with Pitch. We'll have to modify it a little about how we compensate (like using low passed pitch @yyassa suggested, or only doing it when tilt error goes beyond some bounds. I'll add some flight test results here).

**Comment by MaEtUgR** [comment]
Interesting because in SITL I observed less oscillations with the parameters I use... so then the real world test is not passed...

**Comment by julianoes** [comment]
I think you can only do this if `_R(2, 2) > FTL_MIN` even if you have the `constrain` around it, right?

**Comment by devbharat** [comment]
@julianoes yes.

**Comment by devbharat** [comment]
This graph shows mc_pos_ctrl's desired vertical thrust thrust_sp(2) in _green_, the actual applied vertical thrust in _red,_ and the pitch tracking error _blue._ The tailsitter was essentially 'cruising' in hover with a pitch angle of around 75-80 degrees.
image

**Comment by Stifael** [comment]
In my opinion there are two different adjustment necessary to the desired thrust value:
1.) adjust for aerodynamic forces such as drag and lift
2.) adjust for attitude error

Point 1.) applies more for a tailsitter than for a quadrocopter. I think your pull requests is supposed to tackle this poblem by scaling the thrust value for large tilt angle. @devbharat, you already mentioned that some sort of lift estimation would be beneficial to solve that problem more optimally.

Point 2.) applies to tailisitter and quads as well. The approach that me and @MaEtUgR were thinking of is that if there is large attitude error, then the quad should try to minimize the error as quickly as possible such that the thrust vector and desired attitude align. Ona approach to achieve that is by projecting the desired thrust value onto the current body z axis. Doing so the desire thrust value decreases for large attitude error (where large angulare rate is required) and keeps its value if body z axis aligns with desired thrust vector. 

The control structure that I suggest should more look like this picture:
flow_chart_modified_simple, where the desired thrust vector is adjusted with an aerodynamic force vector estimate, and the thrust magnitude farther adjusted based on attitude error.

**Comment by devbharat** [comment]
@Stifael I totally agree about compensating for the lift/drag, that works well if you can get a good model from the flight data.

For compensating for the attitude error, I quickly sketched what we currently have on master(1st pic), my approach(pic 2) and the one I understand about what you are proposing(3rd pic).

What you see is the longitudinal plane with world_z(up) in _black_, body_z in _green_ corresponding to current pitch angle, desired body_z in _red_ corresponding to pitch setpoint. The way we currently have on master, the entire length of thrust vector is rotated onto the body_z, which results in excess vertical thrust (if pitch is < pitch_sp, less vertical thrust if pitch > pitch_sp).
image

In my proposal, I scale the length of the thrust vector until its projection on world_z is exactly equal to desired vertical thrust. Ideally, this would totally decouple vertical pos/velocity tracking from pitch tracking error.
image

The last figure is what I get about what you are proposing, to project the desired thrust vector onto body_z, that still seems to me to have excess vertical thrust.
image

**Comment by Stifael** [comment]
@devbharat, thank you for the pictures.
The question now is which projection makes more sense: the projection onto the body z axis or the projection where the world z component is preserved. 
The idea behind projecting onto the body z axis directly is that the quad's thrust direction is always along the body z axis, and not along the world z axis. So for me I considered the excess thrust as the difference between the green and yellow vector (2. picture). For instance, if I had a propeller which also can rotate, then I first rotate them such that the direction of thrust aligns with the desire thrust vector. However, since the direction of the props are fixed and point in the body z axis, I correct for it by projecting it onto the  body z axis.
In your case, you consider the excess as the difference in thrust vector along the world z axis. IMHO, I still prefer the approach that me and @MaEtUgR suggested, but It probably makes most sense to test both and evaluate which strategy works better. I will try to do that tomorrow.

**Comment by devbharat** [comment]
@Stifael I would disagree with your definition of excess thrust. The aim of the PR was to make sure (world) Z tracking is largely unaffected by pitch/roll tracking errors. The way to improve that would be to ensure that we apply exactly the amount of vertical thrust (world Z direction) as the controller demands based of required vertical acceleration. 

There is no way we can have pitch/roll tracking at transients to not have tracking error (there will always be some rise time). During this period, the actual vertical thrust applied and the desired vertical thrust (both in world Z direction) will differ (the excess vertical thrust in fig 2), which will cause the aircraft to ascend/descend until the integrals catch up. It is during this period we need to compensate the excess thrust but tolerating slower transient response in vel X, vel Y, but keeping vel Z's desired thrust perfect.

@julianoes how about I enable it only until _R(2 ,2) represents the tilt_max.

**Comment by julianoes** [comment]
@devbharat sure, or maybe further. It just needs to have some check.

**Comment by devbharat** [comment]
The oscillations that are reported in the plot i mentioned earlier 

image

are due to the coupling between the throttle and pitching moment for tailsitter with flaps in the downwash. (This can be modeled but isn't right now). This coupling does not exist for quads and so shouldn't be a problem for multirotors. In my opinion this is good to go for flight tests.

**Comment by julianoes** [comment]
> `_R(2, 2) + FLT_EPSILON`

Can `_R(2, 2)` be < 0. And if yes, can it be ` == -FLT_EPSILON`?

**Comment by devbharat** [comment]
@julianoes its all very unlikely, but sloppy indeed. I'll push a proper fix.

**Comment by julianoes** [comment]
I have seen things fall out of the sky plenty of times because of NaN and Inf, that's why I'm so fussy about it.

**Comment by LorenzMeier** [comment]
@MaEtUgR Thanks! Closing.

**Pull request closed without merging**
