### PR TITLE
do not modify attitude setpoint in velocity controlled mode

### LINKED ISSUE #4904: Position control with large yaw errors
@tumbili is it possible that we throw the velocity controller off with rotating the attitude setpoint to actual yaw? Lost it in position control twice when the yaw error got large. The system is also on its limits when it happens so saturation plays in as well.

The effect is observable right before I switch our of POSCTL:
http://logs.uaventure.com/view/WmMtyfDAmhmDDKr5nQt9qf
http://logs.uaventure.com/view/HPRbSQ3RhAuHfPfNBpabGM

### PR DESCRIPTION
**Pull request by AndreasAntener**
@tumbili probably resolves #4904, would be cool if you can double check
I can easily destabilize SITL on my older branch without this, but master SITL seems to be pretty resilient.. (that deltaquad is a magical contraption ;))

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looks indeed like its needed.

**Comment by LorenzMeier** [comment]
Rebasing should fix your CI error.

**Comment by AndreasAntener** [comment]
It's up-to-date, was the mavlink commit not there yet when I pushed?

**Comment by AndreasAntener** [comment]
Amended the commit message to re-force

**Comment by tumbili** [comment]
@AndreasAntener Yeah you are totally right :-)

**Pull request merged**
