### PR TITLE
lis3mdl driver refactor

### PR DESCRIPTION
**Pull request by dakejahl**
Did an overhaul of the structure and organization of this magnetometer driver. Fixed temperature calculations, increased data rate, and optimized device register values. Removed useless code (artifacts of copy/paste from previous drivers), standardized functions, and in general improved the readability of the driver.

### CODE REVIEW

**Comment by mcsauder** [comment]
@dagar, The refactoring work in Jake's pull request here is essentially a template we'd like to continue instituting in the other imu drivers.  The current lis3mdl driver copied/pasted a lot of irrelevant and dead code.  We've effectively created a clean start to this driver and verified functionality.

Let us know if you have feedback/questions.

-Mark

**Comment by mhkabir** [comment]
@mcsauder @dakejahl Awesome work!

**Comment by mcsauder** [comment]
Also, just so anyone utilizing the lis3mdl is aware, the lis3mdl shows huge bias shifts with temperature changes and this is a known issue with the sensor: [https://community.st.com/docs/DOC-1428-faq-lis3mdl-offset-thermal-drift](https://community.st.com/docs/DOC-1428-faq-lis3mdl-offset-thermal-drift)

-Mark

**Comment by mcsauder** [comment]
P.S.anyone using the lis3mdl should aggressively move to switch away from that sensor!

-Mark

**Comment by LorenzMeier** [comment]
Looking good, thanks for helping to tidy up!

**Pull request merged**
