### PR TITLE
commander: update parameter strings to class enum

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
Saves a little bit of flash as well.

image

**Comment by MaEtUgR** [comment]
This somehow breaks commander parameters. As a symptom I get a lot of errors in QGC even when just running SITL. It says `COM_...` parameters are missing and shows the vehicle needs setup before flying. Probably `param_handle()` does not replace `param_find()` and the parameters are not discovered and added to the list anymore?

**Comment by dagar** [comment]
Reverted for now.
https://github.com/PX4/Firmware/commit/a5895e5a99979808046841f524edf7d434e1d1ff
https://github.com/PX4/Firmware/commit/f885d2274a563278b5ca501e4c19365ad0cd790d

**Comment by BazookaJoe1900** [comment]
@dagar - how about using param_set_used() in param_handle()?

**Comment by bkueng** [comment]
@BazookaJoe1900 that API was not designed for that purpose. It's better to use the C++ classes (`ParamFloat` etc.)

**Comment by BazookaJoe1900** [comment]
@bkueng the issue is that are about ~500 places with param_find("XXX"). and about 200 places where the parameter name build on real time. a better way is moving them to the c++ method, but that can be too hard to do.

more importantly here are spot that I found that try to read parameters that are not exist, on certain compilation:
`camera_trigger/camera_trigger.cpp/275: _p_cam_cap_fback = param_find("CAM_CAP_FBACK"); 
linux_pwm_out/linux_pwm_out.cpp (4 matches)/144: param_t param_handle_mc_airmode = param_find("MC_AIRMODE"); 
linux_pwm_out/linux_pwm_out.cpp (4 matches)/558: param_get(param_find("PWM_DISARMED"), &linux_pwm_out::_pwm_disarmed); 
linux_pwm_out/linux_pwm_out.cpp (4 matches)/559: param_get(param_find("PWM_MIN"), &linux_pwm_out::_pwm_min); 
linux_pwm_out/linux_pwm_out.cpp (4 matches)/560: param_get(param_find("PWM_MAX"), &linux_pwm_out::_pwm_max); 
px4io/px4io.cpp (3 matches)/1,138: parm_handle = param_find("FW_MAN_R_SC"); 
px4io/px4io.cpp (3 matches)/1,145: parm_handle = param_find("FW_MAN_P_SC"); 
px4io/px4io.cpp (3 matches)/1,152: parm_handle = param_find("FW_MAN_Y_SC"); 
uavcanesc/uavcanesc_main.cpp (2 matches)/474: (void)param_get(param_find("ESC_NODE_ID"), &node_id); 
uavcanesc/uavcanesc_main.cpp (2 matches)/475: (void)param_get(param_find("ESC_BITRATE"), &bitrate); 
modules/camera_feedback/camera_feedback.cpp/60: _p_camera_capture_feedback = param_find("CAM_CAP_FBACK"); 
commander/Commander.cpp/1,240: param_t _param_airmode = param_find("MC_AIRMODE"); 
commander/PreflightCheck.cpp/918: param_get(param_find("FW_ARSP_MODE"), &optional); 
commander/rc_calibration.cpp (3 matches)/72: param_t param_fw_man_r_sc = param_find("FW_MAN_R_SC"); 
commander/rc_calibration.cpp (3 matches)/73: param_t param_fw_man_p_sc = param_find("FW_MAN_P_SC"); 
commander/rc_calibration.cpp (3 matches)/74: param_t param_fw_man_y_sc = param_find("FW_MAN_Y_SC"); 
fw_att_control/FixedwingAttitudeControl.cpp/382: if (param_get(param_find("VT_TYPE"), &vt_type) == PX4_OK) { 
fw_pos_control_l1/FixedwingPositionControl.cpp (2 matches)/345: _parameter_handles.airspeed_trans = param_find("VT_ARSP_TRANS"); 
fw_pos_control_l1/FixedwingPositionControl.cpp (2 matches)/346: _parameter_handles.vtol_type = param_find("VT_TYPE"); 
land_detector/MulticopterLandDetector.cpp (4 matches)
land_detector/76: _paramHandle.landSpeed      = param_find("MPC_LAND_SPEED"); 
land_detector/77: _paramHandle.minManThrottle = param_find("MPC_MANTHR_MIN"); 
land_detector/78: _paramHandle.minThrottle    = param_find("MPC_THR_MIN"); 
land_detector/79: _paramHandle.hoverThrottle  = param_find("MPC_THR_HOVER"); 
mc_att_control/mc_att_control_main.cpp/164: if (param_get(param_find("VT_TYPE"), &vt_type) == PX4_OK) { 
navigator/navigator_main.cpp (2 matches)/106: _handle_back_trans_dec_mss = param_find("VT_B_DEC_MSS"); 
navigator/navigator_main.cpp (2 matches)/107: _handle_reverse_delay = param_find("VT_B_REV_DEL"); 
precland.cpp (2 matches)/66: _handle_param_acceleration_hor = param_find("MPC_ACC_HOR"); 
precland.cpp (2 matches)/67: _handle_param_xy_vel_cruise = param_find("MPC_XY_CRUISE"); 
sensors/parameters.cpp (2 matches)/187: (void)param_find("TRIG_MODE"); 
sensors/parameters.cpp (2 matches)/188: (void)param_find("UAVCAN_ENABLE"); 
systemcmds/config/config.c (3 matches)/199: param_get(param_find("CAL_GYRO0_ID"), &(calibration_id)); 
systemcmds/config/config.c (3 matches)/253: param_get(param_find("CAL_MAG0_ID"), &(calibration_id)); 
systemcmds/config/config.c (3 matches)/297: param_get(param_find("CAL_ACC0_ID"), &(calibration_id)); `

**Comment by bkueng** [comment]
> @bkueng the issue is that are about ~500 places with param_find("XXX"). and about 200 places where the parameter name build on real time. a better way is moving them to the c++ method, but that can be too hard to do.

Yes that is why we have both interfaces. I don't see a problem with `param_find` at a few places. It's slower, but it has logarithmic runtime.

**Pull request merged**
