### PR TITLE
Adaptive EKF noise

### PR DESCRIPTION
**Pull request by Zefz**
Implements adaptive noise for GPS observations. This makes the EKF weigh the GPS position/velocity data more or less depending on the fix accuracy.

This has been flight tested, but should not be merged until we can somehow verify that this has an positive effect on the state estimations of the EKF.

### CODE REVIEW

**Comment by Zefz** [comment]
Also the EKF weight parameters for fusing GPS data should be reviewed. What role should they have in adaptive gains? Currently they function as a scaling constant to the measured GPS accuracy.

**Comment by LorenzMeier** [comment]
Nice! looking forward to some flight results.

**Comment by LorenzMeier** [comment]
@Zefz Do we want to pull in your first commit sooner? It looks pretty sane to me and should clearly help.

**Comment by Zefz** [comment]
Sure. The first commit should be completely safe, assuming that the other non-ublox GPS drivers set this flag correctly.

**Comment by LorenzMeier** [comment]
Ok, cherry picked.

**Comment by LorenzMeier** [comment]
@Zefz The only way I can see to test this properly is to walk between tall buildings, both time in the center between the buildings, with and without this patch. If our theory is correct the walk with the adaptive noise should be less influenced by multi path reflections.

**Comment by Zefz** [comment]
I got some tall buildings on campus. I can see if I have the time to make some logs. (although 'tall' is a relative term, Norway isn't famous for its skyscrapers - mountains though ;))

I've been flying the adaptive gains in normal conditions and I cannot see any evident loss of performance.

**Comment by LorenzMeier** [comment]
@Zefz Any news on this one?

**Comment by Zefz** [comment]
Sorry no. I haven't been active with PX4 development due to family matters the last two weeks.

**Comment by tumbili** [comment]
@Zefz Have you had some time to look at the rest of this?

**Comment by LorenzMeier** [comment]
Superseded by EKF2.

**Pull request closed without merging**
