### PR TITLE
osx fix and enable tests

### PR DESCRIPTION
**Pull request by dagar**
Run `make tests` on OSX.

### CODE REVIEW

**Comment by dagar** [comment]
@LorenzMeier are you aware of any time issues on OSX?
tests uorb and tests hysteresis are failing on OSX and both seem to be time related.

` tests uorb`

    uORB note: Testing multi-topic 2 test (queue simulation)
    uORB FAIL: Timestamp not increasing! (3768870 >= 3768848)

`tests hysteresis` - FYI @julianoes 

    ERROR [modules__unit_test] Assertion failed: result not false - hysteresis.get_state() (../src/systemcmds/tests/test_hysteresis.cpp:82)
    ERROR [tests] TEST FAILED: _change_after_time

**Comment by LorenzMeier** [comment]
```bash
make tests
...
################################################################################

     T E S T    S U M M A R Y

  ______     __         __            ______     __  __    
 /\  __ \   /\ \       /\ \          /\  __ \   /\ \/ /    
 \ \  __ \  \ \ \____  \ \ \____     \ \ \/\ \  \ \  _"-.  
  \ \_\ \_\  \ \_____\  \ \_____\     \ \_____\  \ \_\ \_\ 
   \/_/\/_/   \/_____/   \/_____/      \/_____/   \/_/\/_/ 

 All tests passed (19 of 19)

Shutting down
Restoring terminal
 All tests passed (19 of 19)
```

**Comment by LorenzMeier** [comment]
If you ask me then the relatively underpowered CI machine is at fault. We might need to widen the thresholds for it.

**Comment by LorenzMeier** [comment]
Closing in favour of #5269.

**Pull request closed without merging**
