### PR TITLE
Fix out of range crash when looking for .ulg file

### PR DESCRIPTION
**Pull request by vincedjango**
**Test data / coverage**

**_Crash_**
**After seeing all the build of this PR fails due to something completely unrelated to his PR, I filed a bug report stating that the current CI script is broken https://github.com/PX4/Firmware/issues/11440**

```
[ROSTEST]-----------------------------------------------------------------------

[px4.rosunit-trabuco_basic_waypoint_plan_with_RTL/test_mission][ERROR]----------
list index out of range
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/dev/workspace/US380-1-Master@2/integrationtests/python_src/px4_it/mavros/mission_test.py", line 295, in test_mission
    last_log = get_last_log()
  File "/home/dev/workspace/US380-1-Master@2/integrationtests/python_src/px4_it/mavros/mission_test.py", line 68, in get_last_log
    last_log = sorted(glob.glob(os.path.join(last_log_dir, '*.ulg')))[-1]
--------------------------------------------------------------------------------
```

**Describe problem solved by the proposed pull request**
As shown in the logs above this section, the script _mission_test.py_ crashes when .ulg log file is not found.

In tag 1.8, the ulg logs were saved in folders following this pattern _.ros/rootfs/fs/microsd/log/YYYY-MM-DD/***.ulg_. Now, the ulg logs are saved directly under _.ros_.

The issue is that .ros may contain other items than folder with ulg file. It may result in returning a item that does not contain a ulg file which will cause a crash.

Initialy, those line of code in _mission_test.py_ would:

1. Find latest item created in _.ros/log directory_
2.  Find the .ulg file in the path found above.

```
    1. last_log_dir = sorted(glob.glob(os.path.join(log_path, '*')))[-1]
    2. last_log = sorted(glob.glob(os.path.join(last_log_dir, '*.ulg')))[-1]
```
This is the content of my .ros/log folder:
```
dev@px4-build:~/workspace/PX4/.ros/log$ ls -l
total 92
drwxr-xr-x 2 root root  4096 Feb 11 11:18 2019-02-11
drwxr-xr-x 2 root root  4096 Feb 11 11:18 dd9bbb30-2e31-11e9-a3ed-0242ac110003
lrwxrwxrwx 1 root root    75 Feb 11 11:18 latest -> /home/dev/workspace/PX4/.ros/log/dd9bbb30-2e31-11e9-a3ed-0242ac110003
-rw-r--r-- 1 root root 78829 Feb 11 11:18 rostest-01c0267156c2-6008.log
```
Using the following folder, what _last_log_dir_ will return is _rostest-01c0267156c2-6008.log_
Since this file does not contain a _ulg_, the _last_log_ command line will crashes with an out of range error.

**Describe your preferred solution**
My solution is to replace line _1._ and _2._ above by simply:
`last_log = sorted(glob.glob(os.path.join(log_path, '*/*.ulg')))[-1]`

This way, last_log will always have the latest .ulg file created.

### CODE REVIEW

**Comment by dagar** [comment]
Your overall diff is empty.

**Comment by vincedjango** [comment]
> Your overall diff is empty.

This is very strange because if you click on my latest commit, you can see that.

**Comment by mrpollo** [comment]
@vincedjango as noted on Slack, your branch is out of date with PX4:master, please rebase or create a new PR from a new branch with your commits.

**Comment by LorenzMeier** [comment]
We still would love to get the fix, but this PR isn't working - closing it.

**Pull request closed without merging**
