### PR TITLE
Last touchups on params.c

### PR DESCRIPTION
**Pull request by davids5**
@LorenzMeier  Added assertion on allocation failure for parameter change storage.
Removed magic numbers

### CODE REVIEW

**Comment by LorenzMeier** [comment]
If the ASSERT macro is standard C++, this might be missing a header or compiler flag for the unit tests? ```make tests``` should exhibit the same kind of failure.

**Comment by davids5** [comment]
@LorenzMeier  I think I found a good home for it.

**Comment by davids5** [comment]
@LorenzMeier Travis - liked it! Please merge if you do.

**Comment by LorenzMeier** [comment]
Is the assert a runtime assert or a compile time assert? On which build config options does it depend? I don't want the user-level build to assert, but to essentially return an error due to low mem. We can run the system without params, but it shouldn't crash.

**Comment by davids5** [comment]
@LorenzMeier It is a run time assert. The code will crash down stream of the init if the 65 ish bytes can not be allocated. The assert is a graceful of telling them the problem as opposed to a crash down stream on a null pointer. We would need a guard on failed allocation and have to return ??? for all params.

We could change it to DEBUGASSERT - only enabled during debug - 

I am not sure what running without param look like. Skye to discuss?

**Comment by LorenzMeier** [comment]
The issues with a run time assert is that it doesn't make it to the user. It means we have a user which reports a "dead board" and there is no way for us to infer what caused his "dead board" so I prefer error handling which escalates the error further up until a user-presentable error message can be generated.

**Comment by davids5** [comment]
@LorenzMeier I have added the logic to fail not assert. Would you please review it.

**Comment by davids5** [comment]
@LorenzMeier 

Below is the output of a forced failure using 40abc2f

```
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
[i] microSD mounted: /fs/microsd
nshterm [6:70]
param: selected parameter default file /fs/mtd_params
[param] Loaded: /fs/mtd_params
[rgbled] on I2C bus 2 at 0x55 (bus: 100 KHz, max: 100 KHz)
nsh: pca8574: command not found
param: Error: Parameter SYS_AUTOCONFIG not found.
param: Error: Parameter SYS_USE_IO not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
param: Error: Parameter SYS_AUTOSTART not found.
dataman: Power on restart, data manager file '/fs/microsd/dataman' size is 101504 bytes
[MS5611_SPI] on SPI bus 4 at 2 (11000 KHz)
ms5611: no device on bus 4
[MS5611_SPI] on SPI bus 1 at 3 (11000 KHz)
ms5611: no device on bus 1
ms5611: no device on bus 2
<adc> init done
ver hwcmp match: PX4FMU_V2
hmc5883: no device on bus 2
hmc5883: no device on bus 1
mpu6000: driver start failed
[MPU6000] on SPI bus 1 at 4 (1000 KHz)
[L3GD20] on SPI bus 1 at 1 (11000 KHz)
[LSM303D] on SPI bus 1 at 2 (11000 KHz)
meas_airspeed: no MS4525 airspeed sensor connected
ets_airspeed: no ETS airspeed sensor connected
ets_airspeed: no ETS airspeed sensor connected
px4flow: no PX4 FLOW connected
sensors: RC chan 0 not sane, scaling:      NaN, rev: 0
sensors: RC chan 1 not sane, scaling: Infinity, rev: 0
sensors: RC chan 2 not sane, scaling: 0.375000, rev: 0
sensors: RC chan 3 not sane, scaling: -0.437500, rev: 0
sensors: RC chan 4 not sane, scaling: 0.000000, rev: 0
sensors: RC chan 5 not sane, scaling: Infinity, rev: 0
sensors: RC chan 6 not sane, scaling: Infinity, rev: 0
sensors: RC chan 7 not sane, scaling: Infinity, rev: 0
sensors: RC chan 8 not sane, scaling:      NaN, rev: 0
sensors: RC chan 9 not sane, scaling:      NaN, rev: 0
sensors: RC chan 10 not sane, scaling: -0.000000, rev: 0
sensors: RC chan 11 not sane, scaling: -0.000000, rev: 0
sensors: RC chan 12 not sane, scaling: 8.000000, rev: 0
sensors: RC chan 13 not sane, scaling:      NaN, rev: 0
sensors: RC chan 14 not sane, scaling: 0.000000, rev: 0
sensors: RC chan 15 not sane, scaling:      NaN, rev: 0
sensors: RC chan 16 not sane, scaling:      NaN, rev: 0
sensors: RC chan 17 not sane, scaling: 0.454545, rev: 0
sensors: WARNING     WARNING     WARNING

RC CALIBRATION NOT SANE!


sensors: qnh could not be set
sensors_task: RC chan 0 not sane, scaling:      NaN, rev: 0
sensors_task: RC chan 1 not sane, scaling: Infinity, rev: 0
sensors_task: RC chan 2 not sane, scaling: 0.375000, rev: 0
sensors_task: RC chan 3 not sane, scaling: -0.437500, rev: 0
sensors_task: RC chan 4 not sane, scaling: 0.000000, rev: 0
sensors_task: RC chan 5 not sane, scaling: Infinity, rev: 0
sensors_task: RC chan 6 not sane, scaling: Infinity, rev: 0
sensors_task: RC chan 7 not sane, scaling: Infinity, rev: 0
sensors_task: RC chan 8 not sane, scaling:      NaN, rev: 0
sensors_task: RC chan 9 not sane, scaling:      NaN, rev: 0
sensors_task: RC chan 10 not sane, scaling: -0.000000, rev: 0
sensors_task: RC chan 11 not sane, scaling: -0.000000, rev: 0
sensors_task: RC chan 12 not sane, scaling: 8.000000, rev: 0
sensors_task: RC chan 13 not sane, scaling:      NaN, rev: 0
sensors_task: RC chan 14 not sane, scaling: 0.000000, rev: 0
sensors_task: RC chan 15 not sane, scaling:      NaN, rev: 0
sensors_task: RC chan 16 not sane, scaling:      NaN, rev: 0
sensors_task: RC chan 17 not sane, scaling: 0.454545, rev: 0
sensors_task: WARNING     WARNING     WARNING

RC CALIBRATION NOT SANE!


sensors_task: qnh could not be set
commander: ERROR: 1 config error(s) for RC channel 1.
commander: ERROR: 1 config error(s) for RC channel 2.
commander: ERROR: 1 config error(s) for RC channel 3.
commander: ERROR: 1 config error(s) for RC channel 4.
commander: ERROR: 1 config error(s) for RC channel 5.
commander: ERROR: 1 config error(s) for RC channel 6.
commander: ERROR: 1 config error(s) for RC channel 7.
commander: ERROR: 1 config error(s) for RC channel 8.
commander: ERROR: 1 config error(s) for RC channel 9.
commander: ERROR: 1 config error(s) for RC channel 10.
commander: ERROR: 1 config error(s) for RC channel 11.
commander: ERROR: 1 config error(s) for RC channel 12.
commander: ERROR: 1 config error(s) for RC channel 13.
commander: ERROR: 1 config error(s) for RC channel 14.
commander: ERROR: 1 config error(s) for RC channel 15.
commander: ERROR: 1 config error(s) for RC channel 16.
commander: ERROR: 1 config error(s) for RC channel 17.
commander: ERROR: 1 config error(s) for RC channel 18.
telem> PREFLIGHT FAIL: MAG #0 UNCALIBRATED
telem> PREFLIGHT FAIL: ACCEL #0 UNCALIBRATED
telem> PREFLIGHT FAIL: ACCEL #1 UNCALIBRATED
telem> PREFLIGHT FAIL: GYRO #0 UNCALIBRATED
telem> PREFLIGHT FAIL: GYRO #1 UNCALIBRATED
[fmuservo] default PWM output device
<fmuservo> MODE_6PWM
<fmuservo> set_pwm_rate 0 50 50
[fmuservo] starting
<fmuservo> adjusted actuator update interval to 20ms
[i] FMU mode_pwm started
mavlink_if0: mode: 0, data rate: 1000 B/s on /dev/ttyS1 @ 57600B
ver hwcmp match: PX4FMU_V2
param: Error: Parameter SYS_COMPANION not found.
param: Error: Parameter SYS_COMPANION not found.
param: Error: Parameter UAVCAN_ENABLE not found.
error finding param: GF_MODE
error finding param: GF_ALTMODE
error finding param: GF_SOURCE
error finding param: GF_COUNT
error finding param: GF_MAX_HOR_DIST
error finding param: GF_MAX_VER_DIST
error finding param: MIS_ONBOARD_EN
error finding param: MIS_TAKEOFF_ALT
error finding param: MIS_DIST_1WP
error finding param: MIS_ALTMODE
error finding param: MIS_YAWMODE
error finding param: RTL_RETURN_ALT
error finding param: RTL_DESCEND_ALT
error finding param: RTL_LAND_DELAY
error finding param: NAV_RCL_LT
error finding param: NAV_DLL_CH_T
error finding param: NAV_DLL_CH_LAT
error finding param: NAV_DLL_CH_LON
error finding param: NAV_DLL_CH_ALT
error finding param: NAV_AH_LAT
error finding param: NAV_AH_LON
error finding param: NAV_AH_ALT
error finding param: NAV_DLL_AH_T
error finding param: NAV_DLL_N
error finding param: NAV_DLL_CHSK
error finding param: NAV_GPSF_LT
error finding param: NAV_GPSF_R
error finding param: NAV_GPSF_P
error finding param: NAV_GPSF_TR
error finding param: NAV_LOITER_commander: ERROR: 2 config errorRAD
(s) for RC channel 1.
error finding param: NAV_ACC_RAD
error finding param: NAV_DLL_OBC
error finding param: NAV_RCL_OBC
[i] No autostart ID found
commander: ERROR: 2 config error(s) for RC channel 2.

NuttShell (NSH)
nsh> navigator: Could not clear geofence
navigator: offboard mission updated: dataman_id=0, count=0, current_seq=0
sdlog2: log buffer size: 22528 bytes
commander: ERROR: 2 config error(s) for RC channel 3.
commander: ERROR: 2 config error(s) for RC channel 4.
commander: ERROR: 2 config error(s) for RC channel 5.
commander: ERROR: 2 config error(s) for RC channel 6.
mavlink_if0: DISABLING HARDWARE FLOW CONTROL
commander: ERROR: 2 config error(s) for RC channel 7.
commander: ERROR: 2 config error(s) for RC channel 8.
commander: ERROR: 2 config error(s) for RC channel 9.
commander: ERROR: 2 config error(s) for RC channel 10.
commander: ERROR: 2 config error(s) for RC channel 11.
commander: ERROR: 2 config error(s) for RC channel 12.
commander: ERROR: 2 config error(s) for RC channel 13.
commander: ERROR: 2 config error(s) for RC channel 14.
commander: ERROR: 2 config error(s) for RC channel 15.
commander: ERROR: 2 config error(s) for RC channel 16.
commander: ERROR: 2 config error(s) for RC channel 17.
commander: ERROR: 2 config error(s) for RC channel 18.
commander: ERROR: 2 config error(s) for RC channel 1.
commander: ERROR: 2 config error(s) for RC channel 2.
commander: ERROR: 2 config error(s) for RC channel 3.
commander: ERROR: 2 config error(s) for RC channel 4.
commander: ERROR: 2 config error(s) for RC channel 5.
commander: ERROR: 2 config error(s) for RC channel 6.
commander: ERROR: 2 config error(s) for RC channel 7.
commander: ERROR: 2 config error(s) for RC channel 8.
commander: ERROR: 2 config error(s) for RC channel 9.
commander: ERROR: 2 config error(s) for RC channel 10.
commander: ERROR: 2 config error(s) for RC channel 11.
commander: ERROR: 2 config error(s) for RC channel 12.
commander: ERROR: 2 config error(s) for RC channel 13.
commander: ERROR: 2 config error(s) for RC channel 14.
commander: ERROR: 2 config error(s) for RC channel 15.
commander: ERROR: 2 config error(s) for RC channel 16.
commander: ERROR: 2 config error(s) for RC channel 17.
commander: ERROR: 2 config error(s) for RC channel 18.
telem> Not ready to fly: Sensors need inspection
commander: INVAL: ARMING_STATE_STANDBY_ERROR - ARMING_STATE_STANDBY
```

**Pull request closed without merging**
