### PR TITLE
Moved sitl targets to cmake to easily support more board configs.

### PR DESCRIPTION
**Pull request by jgoppert**
Also adds  make px4fmu-v2_default config     etc... This allows you to pull up the cmake gui configuration tool easily.

### CODE REVIEW

**Comment by jgoppert** [comment]
Example of new usage:
```bash
make posix_sitl_default run_sitl_quad 
```

**Comment by jgoppert** [comment]
Example debugger usage:

Command line:
```bash
DEBUGGER=gdb make posix_sitl_default
make posix_sitl_default run_sitl_quad
```

Cmake GUI:
```bash
make posix_sitl_default
make posix_sitl_default config (--> select your debugger from DEBUGGER drop down list)
make posix_sitl_default run_sitl_quad
```

**Comment by jgoppert** [comment]
@mcharleb, @tumbili, @LorenzMeier Any input on this PR?

**Comment by LorenzMeier** [comment]
I'm slightly confused by the instructions? How do I run a pure simulation run? I'm not sure if you're trying to show that I can run multiple make targets or are the multi-line things needed to run debug?

**Comment by jgoppert** [comment]
@LorenzMeier  The multi-line is just for debug. To run a pure simulation including building it, just type:

```bash
make posix_sitl_default run_sitl_quad
```

This sticks to the existing structure for the makefile controlling cmake of:
```bash
make BOARD_NAME TARGET
```

**Comment by jgoppert** [comment]
Now in master.

**Pull request closed without merging**
