### PR TITLE
refactor sensors: split source into separate classes

### PR DESCRIPTION
**Pull request by bkueng**
sensors.cpp got too large. This splits the source file into separate classes.

Bench tested on pixracer including calibration. Needs to be flight tested.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Will merge this only after 1.4 release.

**Comment by LorenzMeier** [comment]
@bkueng Can you rebase and fix CI failure?

**Comment by bkueng** [comment]
rebased & bench tested

**Comment by julianoes** [comment]
Reviewed. I wonder how many conflicts there are now though.

**Comment by LorenzMeier** [comment]
@bkueng Can you rebase and get in?

**Comment by bkueng** [comment]
Rebased with lots of conflicts. SITL & bench tested (including sensors & RC calibration), which went fine.

**Comment by bkueng** [comment]
Flight tested on the Aero, didn't notice any problems

**Pull request merged**
