### PR TITLE
KakuteF7: enable SPI DMA for SPI 4

### PR DESCRIPTION
**Pull request by bkueng**
DMA for SPI 1 left disabled because the SD card does not work when enabling it.

### CODE REVIEW

**Comment by dagar** [comment]
Out of curiosity you might want to take a quick look at the load with and without SPI DMA at 2 and 4 kHz.

**Comment by bkueng** [comment]
@ 2khz:
- DMA: 24.4% idle
- no DMA: 12.8% idle

@ 4khz: no chance of running in both cases, CPU is maxed out.
BTW it's not easy for an end-user to recover from this, as you don't get MAVLink anymore.

**Comment by dagar** [comment]
Interesting, I thought a simplified kakutef7 might have a chance.

On v5 with only the icm20602 running it's ~ 12% idle (IMU_GYRO_RATEMAX=4000 SYS_AUTOSTART=4001).
``` Console
 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
   0 Idle Task                   61288 12.972   244/  512   0 (  0)  READY  3
   1 hpwork                          0  0.000   344/ 1260 249 (249)  w:sig  3
   2 lpwork                          0  0.000   344/ 1612  50 ( 50)  w:sig  3
   3 init                          905  0.000  2200/ 2668 100 (100)  w:sem  3
   4 wq:manager                      1  0.000   408/ 1252 255 (255)  w:sem  3
 435 mavlink_rcv_if0              1400  0.257  2376/ 3908 175 (175)  READY  4
  16 wq:hp_default                5614  1.202  1160/ 1900 241 (241)  READY  3
  18 dataman                       365  0.085   760/ 1204  90 ( 90)  w:sem  4
  20 wq:lp_default                 542  0.171   812/ 1700 205 (205)  READY  3
  29 wq:I2C1                      3577  0.773   820/ 1396 246 (246)  READY  3
 127 wq:SPI1                    129868 27.319  1968/ 2364 253 (253)  w:sem  3
 152 wq:I2C3                      2880  0.601   820/ 1396 244 (244)  READY  3
 154 wq:SPI4                      1607  0.343   904/ 2364 250 (250)  w:sem  3
 176 wq:att_pos_ctrl             84270 17.783  5024/ 7196 242 (242)  READY  3
 177 wq:rate_ctrl               100583 21.219  1052/ 1596 255 (255)  w:sem  3
 182 commander                    5162  1.116  1280/ 3212 140 (140)  READY  6
 183 commander_low_prio              9  0.000   716/ 2996  50 ( 50)  w:sem  6
 189 mavlink_if0                 16116  3.264  1832/ 2572 100 (100)  READY  4
 235 gps                           913  0.171  1016/ 1676 208 (208)  w:sem  4
 270 mavlink_if1                  5912  1.202  1888/ 2484 100 (100)  READY  4
 271 mavlink_rcv_if1              1573  0.343  2384/ 3908 175 (175)  READY  4
 290 px4io                       14391  3.006   936/ 1484 240 (240)  w:sem  4
 422 navigator                     697  0.171  1040/ 1764 105 (105)  w:sem  5
 453 log_writer_file                 0  0.000   368/ 1164  60 ( 60)  w:sem  3
 444 logger                       1788  0.343  2184/ 3644 233 (233)  w:sem  3
 456 top                         13710  2.920  1552/ 2028 248 (248)  RUN    3

Processes: 26 total, 12 running, 14 sleeping, max FDs: 15
CPU usage: 82.30% tasks, 4.73% sched, 12.97% idle
DMA Memory: 5120 total, 1024 used 1024 peak
Uptime: 476.641s total, 61.289s idle
```



> BTW it's not easy for an end-user to recover from this, as you don't get MAVLink anymore.

Yes, and it can even be bad enough you the serial console isn't usable. At the moment `IMU_GYRO_RATEMAX` is limited to 2 kHz with param metadata. Earlier on it was also limited to 2 kHz in each driver. I've thought about another watchdog at various levels (each driver, WQ, system wide), but I'm not sure if it's worth it. Thoughts?

**Comment by bkueng** [comment]
Yes it's DShot that uses a bit more. It's worth having another look at that.

> I've thought about another watchdog at various levels (each driver, WQ, system wide), but I'm not sure if it's worth it. Thoughts?

Probably something on the system level, but it could easily do more harm than good. We can see if it becomes an issue in practise, and add something if really needed.

**Pull request merged**
