### PR TITLE
Add _position_lock_gained bool and associated logic remaining to close PR #6523.

### PR DESCRIPTION
**Pull request by mcsauder**
**Describe problem solved by the proposed pull request**
Nearly all of the changes proposed in PR #6523 have been incorporated in PX4:master at this point.  This PR captures the only work remaining from PR #6523 so that it can be closed without losing the remaining work.

**Test data / coverage**
The changes in this PR affect the state of the local bools `some_switch_changed` and  `should_evaluate_rc_mode_switch` in `Commander::set_main_state_rc()`.  If `position_lock_gained` is false, the bool `should_evaluate_rc_mode_switch` will evaluate false and the method will return `TRANSITION_NOT_CHANGED`.

Anytime `position_lock_gained` is true, the results in Commander will be unchanged.  The instances of `position_lock_gained = false` need careful examination.  (I **_believe_** I have captured @LorenzMeier's original intent, but the logic in Commander.cpp has changed quite a lot from when the PR was originally proposed so I could use a hand ensuring this logic is correct.)

Flight tests on a 250 quad and pixhawk 4 mini performed identical to PX4:master, position lock is identified, the position tone plays and led color change is observable in the same way as upstream, and flight mode changes are obeyed from the RC transmitter:
 - https://review.px4.io/plot_app?log=4870bdba-a04f-4ddc-9e1f-3a164aa71221
 - https://review.px4.io/plot_app?log=a663dcce-1dcb-4397-bfb5-c38b8c7d7e0b
 - https://review.px4.io/plot_app?log=286ec337-956d-4073-8a1a-1bde797d70ae

**Additional context**
See PR #6523.  @dagar and @julianoes , this PR is as we discussed in the dev call.

Hi @LorenzMeier , would you be willing to look this PR over and see if I've captured your intent?  

All, please feel free to close this PR, (and #6523), if these changes are no longer required.

Thanks!

-Mark

### CODE REVIEW

**Comment by mcsauder** [comment]
Hi @MaEtUgR , would you be willing to have a look at this PR and let me know if these proposed changes should be held on to? (If not please feel free to close this PR or let me know to do so!)  Thank you!

**Comment by mcsauder** [comment]
Hi @MaEtUgR , what do you think, should we pursue these changes from PR #6523 or just let them go?

**Comment by mcsauder** [comment]
Closing per devcall discussion.  Thanks everyone!

**Comment by MaEtUgR** [comment]
I think that was added in #11915

**Pull request closed without merging**
