### PR TITLE
add new parameter to set "hysteresis" for RC arm/disarm commands

### PR DESCRIPTION
**Pull request by kd0aij**
default value is 1000msec, same as the original hardwired value, but pilots may choose to decrease it if desired. Tested on fmu-v2 at 100msec

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by LorenzMeier** [comment]
Parameters should be updated here:
https://github.com/kd0aij/Firmware/blob/288733fbe939427d4e47962d5074938025877444/src/modules/commander/commander.cpp#L1650

**Comment by kd0aij** [comment]
Isn't it OK where it is?
https://github.com/kd0aij/Firmware/blob/288733fbe939427d4e47962d5074938025877444/src/modules/commander/commander.cpp#L1623

**Comment by LorenzMeier** [comment]
Sorry, missed that in the diff. Yes, its alright.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
