### PR TITLE
fmu:Add MODE_4PWM1CAP, MODE_5PWM, MODE_5PWM1CAP

### PR DESCRIPTION
**Pull request by davids5**
This extends the  Capture support for FMU
   CHAN 5 and 6.

FYI @DanielePettenuzzo, @mhkabir this is needed for  https://github.com/PX4/Firmware/pull/10295#discussion_r215021176

I will do a PR against your pr with the IOCTL code in it. I tested this on a FMUv2 (2MB) on FMU_CH6 as trigger.

### CODE REVIEW

**Comment by dagar** [comment]
Module documentation build failure - http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/detail/master_fmu_more_cap_modes/2/pipeline


    Warning: undocumented command 'mode_pwm5cap1' in drivers/px4fmu

    Warning: undocumented command 'mode_pwm4cap1' in drivers/px4fmu

**Comment by davids5** [comment]
@DanielePettenuzzo fyi:

testing fmu mode_pwm5cap1
FMUv4          - 100,000 Hz on chan 6 (no call out*) from 37.5 % to 62.5 %
FMUv5-mini - 100,000 Hz on chan 6 (no call out*) from 30.5 % to 39.25 %

*you would add your cycle count when the call out is in place for what it adds to the isr.

**Comment by davids5** [comment]
@dagar changes pushed. Is CI fail VTOL_tailsitter independant?

**Comment by dagar** [comment]
> @dagar changes pushed. Is CI fail VTOL_tailsitter independant?

Yes, but it's a very real failure. @RomanBapst FYI

**Comment by LorenzMeier** [comment]
Issue filed here for the CI test: https://github.com/PX4/Firmware/issues/10590

Roman is out of office, so we'll have to rely on Mathieu to get that out of the way most likely.

**Pull request merged**
