### PR TITLE
SITL integration test demo

### PR DESCRIPTION
**Pull request by AndreasAntener**
@thomasgubler @LorenzMeier 
**Not to merge.** Opening this PR for discussing next steps/issues. The demo simulates joystick input to arm and uses a hack to force it into offboard, which will all be obsolete once offboard is in for real.

It contains 2 simple Python unittests and ROS launch files that can be executed either with `rostest` or `catkin_make test`. See here: http://youtu.be/Qedhq5O0mYM :)

**Launch files:** I had to pull up all the iris_empty_world stuff into our top-level launch file to expose the Gazebo arguments (for headless testing). This works of course, but if you like to leave these part in euroc_simulator, the launch files there need to be modified instead. What's best?

**Automated testing:** I also have a setup ready for a build server with Docker support :) But for that we should take the Docker files out of the PX4 repository. The Docker hub builds the image on every push which makes no sense. I suggest to add a new repository for "container" related stuff (Docker, Vagrant, etc). Something like this: https://github.com/UAVenture/containers
For running the integration tests I added a new container that is based off the existing px4-ros-full: https://github.com/UAVenture/containers/tree/master/docker/ros-indigo/sitl-testing . There we can add other things, like pre-built source dependencies to speed-up the test. I'm thinking of everything except Firmware. But how is it with euroc_simulator and mav_comm? Since they are private, I'm not just going to include them then in a public build ;)

This is how it's supposed to work:
sitl integration test setup

Cheers
ada

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesomeness!

@AndreasAntener I have inquired on the simulator release date. Which parts are still missing for the automatic flight CI from your perspective? I very much would love to push this, we just had a case where a change in the controller introduced non-working offboard control issues, and the faster we can get this up and running the less debugging we have to do ;-).

**Comment by AndreasAntener** [comment]
At the current state it's basically ready for running on a CI server that supports Docker. But there are open items before it's really usable:
  * integrate offboard work from Thomas, so the hacks are not necessary anymore
  * also add mavros to the container so people can test that stuff too
  * write some decent example tests that show a proper test setup, e.g.
    * one directly working with SITL
    * one controlling it over mavros
  * check if the output from unittest/gtest is already suitable to be integrated with the build server that's going to be used, probably needs some configuration work still

**Comment by thomasgubler** [comment]
uber cool!

> Launch files: I had to pull up all the iris_empty_world stuff into our top-level launch file to expose the Gazebo arguments (for headless testing). This works of course, but if you like to leave these part in euroc_simulator, the launch files there need to be modified instead. What's best?


As long as the changes don't interfere with normal operation I see no reason why we should not make the launch files test compatible.

**Comment by LorenzMeier** [comment]
@AndreasAntener I think I lack enough insight and context to really comment on the details, but I would like to encourage to move forward with what you have suggested and push hard to get an initial version up and running. I'd be happy to lend a hand on the weekend. I think this will greatly improve the code quality / stability and we will benefit even from a very basic implementation immediately.

**Comment by AndreasAntener** [comment]
@LorenzMeier you were talking about the possibility to get an AWS instance for this once :) If we have one I could already prepare the test runtime. (with Jenkins and Docker)
I guess it would need 4Gb memory, 10Gb storage for system plus maybe 10Gb to start with for Docker and test execution.
Or have you had something else in mind?

**Comment by LorenzMeier** [comment]
I will get you this over the weekend. I really want to move on it, yes.

**Comment by AndreasAntener** [comment]
Closing in favour of #1831

**Pull request closed without merging**
