### PR TITLE
Pr airspeed fusion rebased

### PR DESCRIPTION
**Pull request by CarlOlsson**
@tumbili 
I rebased and fixed up the [pr](https://github.com/PX4/Firmware/pull/4615) for airspeed threshold, hope it was ok to do it this way.
The logic seems to work in SITL, handheld and I did one flight with rpl logging. What logs do you need to merge this?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@CarlOlsson Could you please address the CI failures?

**Comment by tumbili** [comment]
@CarlOlsson Can you post the replay log?

**Comment by CarlOlsson** [comment]
replay log with ekf2_arsp_thr = 5 m/s is [here](http://logs.uaventure.com/view/dG4YsKyJVEbJAmEYEDkDz8)

**Comment by LorenzMeier** [comment]
Have you looked at the replay log? I see no airspeed being estimated there. Can you please a working replay log?

**Comment by CarlOlsson** [comment]
Hi, no the airspeed is not yet activated in the ecl library, see https://github.com/PX4/ecl/pull/158
This pr just enables the logic for it. Until the above pr to the ecl library is merged the new parameter will not have any effect

**Comment by CarlOlsson** [comment]
For testing the logic of this pr I manually activated the fusion in the library, by doing the same as here https://github.com/PX4/ecl/pull/158

**Comment by tumbili** [comment]
@CarlOlsson I assume this log is from a Pixracer with the baro not being shielded. Have a look at the barometer values in the replay topics. RPL1.b_alt, those values are jumping around. At one point the filter even did a reset because baro innovations were rejected for longer times. So I think we should have a look at the setup again. We should 3D print covers for the Pixracer.

**Comment by CarlOlsson** [comment]
Hm yea you are right, the pixracer is in the body but there is no further shielding. We should figure out the easiest way of shielding it, with some foam on just the sensor or as you said, a 3D printed cover would be nice. Anyway, the log is still sufficient to test this pr right? (It's just logic)

**Comment by tumbili** [comment]
@CarlOlsson I think in order to finalize airspeed fusion we need two things:
1) Flight with replay logging enabled and airspeed fusion activated
2) Flight without replay logging enabled

You have to make sure that the baro of the Pixracer is well covered otherwise we can't evaluate if the airspeed fusion is working well.

**Comment by CarlOlsson** [comment]
Thanks for the comments. Yes I agree. For the first point the log above is sufficient, airspeed fusion doesn't have to be enabled in the actual flight as long as it is possible to activate it while replaying. If we merge this pr it is possible for anyone (e.g. beta testers) to do a replay flight without airspeed fusion active and we can evaluate the performance of the airspeed while post processing.

**Pull request closed without merging**
