### PR TITLE
Removes #ifdef for GPS access within QURT since the termios API is no…

### PR DESCRIPTION
**Pull request by LorenzMeier**
…w supported.

### CODE REVIEW

**Comment by julianoes** [comment]
```
FAILED: /home/docker1000/Qualcomm/HEXAGON_Tools/7.2.12/Tools/bin/hexagon-clang++   -DCONFIG_ARCH_BOARD_EAGLE -DMODULE_NAME=\"gps\" -DPX4_MAIN=gps_app_main -D__DF_QURT -D__PX4_POSIX -D__PX4_QURT -D__PX4_QURT_EAGLE -D__QAIC_SKEL_EXPORT=__EXPORT -D__STDC_FORMAT_MACROS -I/home/docker1000/Qualcomm/Hexagon_SDK/3.0/incs -I/home/docker1000/Qualcomm/Hexagon_SDK/3.0/incs/stddef -I/home/docker1000/Qualcomm/Hexagon_SDK/3.0/libs/common/rpcmem/inc -I/home/docker1000/Qualcomm/Hexagon_SDK/3.0/libs/common/qurt/ADSPv5MP/include -I../src -I. -Isrc -I../src/modules -I../src/include -I../src/lib -I../src/platforms -I../src/drivers/boards/eagle -Isrc/modules/px4_messages -Isrc/modules -I../mavlink/include/mavlink -I../src/lib/DriverFramework/framework/include -I../src/lib/matrix -I../src/lib/DriverFramework/dspal/include -I../src/lib/DriverFramework/dspal/sys -I../src/lib/DriverFramework/dspal/sys/sys -I../src/lib/DriverFramework/dspal/mpu_spi/inc -I../src/lib/DriverFramework/dspal/uart_esc/inc -I../src/platforms/qurt/include -I../src/platforms/posix/include -Iexternal/Install/include -g -fno-exceptions -fno-rtti -std=gnu++0x -fno-threadsafe-statics -DCONFIG_WCHAR_BUILTIN -D__CUSTOM_FILE_IO__ -Wall -Werror -Wextra -Wno-sign-compare -Wshadow -Wfloat-equal -Wpointer-arith -Wmissing-declarations -Wno-unused-parameter -Werror=format-security -Werror=array-bounds -Wfatal-errors -Werror=unused-variable -Werror=reorder -Werror=uninitialized -Werror=init-self -Wno-missing-field-initializers -fvisibility=hidden -include visibility.h -O0 -O2 -fno-strict-aliasing -fomit-frame-pointer -funsafe-math-optimizations -ffunction-sections -fdata-sections -fPIC -fPIC   -D __QURT -D _PID_T -D _UID_T -D _TIMER_T -D _HAS_C9X -D restrict=__restrict__ -D noreturn_function= -include visibility.h -O2 -fno-strict-aliasing -fomit-frame-pointer -funsafe-math-optimizations -ffunction-sections -fdata-sections -fPIC -MMD -MT src/drivers/gps/CMakeFiles/drivers__gps.dir/gps.cpp.o -MF src/drivers/gps/CMakeFiles/drivers__gps.dir/gps.cpp.o.d -o src/drivers/gps/CMakeFiles/drivers__gps.dir/gps.cpp.o -c ../src/drivers/gps/gps.cpp
../src/drivers/gps/gps.cpp:49:10: fatal error: 'termios.h' file not found
#include <termios.h>
```

**Comment by LorenzMeier** [comment]
@jywilson @bharath374 Any insights why this change is not working? Where is the termios header?

**Comment by jywilson** [comment]
Okay, I will take a look at this.  It might be related to a dependency on the latest cmake_hexagon on ATLFlight.

**Comment by LorenzMeier** [comment]
@jywilson Did you find out anything?

**Comment by LorenzMeier** [comment]
@jywilson @bharath374 This is still stuck.

**Comment by LorenzMeier** [comment]
@jywilson @devbharat Still stuck until further updates from CI system and your side.

**Comment by jywilson** [comment]
@LorenzMeier @julianoes 
I will take a look at this next week.  Thanks for the reminder.

**Comment by LorenzMeier** [comment]
@jywilson Can you rebase and re-test?

**Comment by LorenzMeier** [comment]
Not required, this is already applied.

**Pull request closed without merging**
