### PR TITLE
Replace TECS controller with a new version from ECL library

### PR DESCRIPTION
**Pull request by LorenzMeier**
This change replaces the existing TECS controller with a new implementation from the TECS library.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@PX4TestFlights This needs fixed wing test flights.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by dagar** [comment]
The actual body of the license didn't change, but should now be recognized by github for display in the top right corner.

**Comment by dagar** [comment]
I deleted mtecs as we haven't compiled it for about a year an a half. It should be easy enough to find in the history if anyone's interested in it later.

**Comment by dagar** [comment]
SITL test - https://logs.px4.io/plot_app?log=93f2fd22-4571-4404-ac46-31e757904a04

image

image

**Comment by dagar** [comment]
Once ready https://github.com/PX4/ecl/pull/342 needs to be merged first, then this PR needs to update src/lib/ecl to master.

**Comment by dagar** [comment]
ECL updated to master.

**Pull request merged**
