### PR TITLE
Am stable v1.0.1

### PR DESCRIPTION
**Pull request by edkoch**
Here are the changes I made to support the vision based localization and control test package that we are about to release. I made them off a branch of version 1.0.1 to insure we could do flight testing using a stable branch. As you can see the changes consist of a couple new parameters and a new telemetry stream to aid in debugging vision based systems. The one substantive change I made was a new fail safe system in commander.cpp, but after I saw the recent changes to commander.cpp I backed the change out and am now relying upon the fail safe systems in the commander.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@edkoch Could you rebase this? In general PRs should not contain merge commits. https://help.github.com/articles/about-git-rebase/

**Comment by edkoch** [comment]
Hi Lorenz,

Is your objective for me to rebase against the master or to simply squash all the commits in my branch to a single commit?


thanks,

-ed

**Comment by LorenzMeier** [comment]
Still the missing rebase on master here. Moving to next release.

**Comment by dagar** [comment]
This is likely going to be an ugly rebase. If you don't care about the individual commits then I'd recommend you squash your commits together and then cherry pick onto a clean branch.

**Comment by edkoch** [comment]
I’m going to acquire a recent master and move them over by doing a manual merge.

-ed

**Comment by LorenzMeier** [comment]
We're moving to EKF2 and we're now pushing marker localisation ourselves. Feel free to join, but we need to work off master and be agile.

**Pull request closed without merging**
