### PR TITLE
Send PDOP to EKF

### PR DESCRIPTION
**Pull request by bresch**
EKF2 has a GDOP check available but we currently don't send GDOP to it. As we only have VDOP and HDOP (an not TDOP, that should be part of GDOP), we can still compute PDOP and send it to the EKF:

`PDOP = sqrt(VDOP^2 + HDOP^2)`

requires https://github.com/PX4/ecl/pull/673

ref: https://web.archive.org/web/20141122153439/http://www.gmat.unsw.edu.au/snap/gps/gps_survey/chap1/149.htm

### CODE REVIEW

**Comment by kamilritz** [comment]
From a code perspective this seems fine. 
I have computed the GDOP with values from Today's flight with the scheme you suggested. (HDOP = 1.3, VDOP = 0.7)
This gives me GDOP value around to 1.7. This is already close to 2.0, which is the limit for passing GDOP checks in ECL. How do you think about this?

**Comment by priseborough** [comment]
From memory this was put there to check the combined geometric dilution of precision and prevent taking off with poor satellite geometries that can be caused when there is blockage from adjacent structures, etc. As such there is no need to include the TDOP so sqrt(HDOP**2_VDOP**2) should be sufficient.

**Comment by bresch** [comment]
Todo:
- [ ] remove artificial TDOP
- [ ] send PDOP instead of GDOP and rename setter, parameter etc.

**Comment by bresch** [comment]
> Is there a need to update the default PDOP test limit?

From a VDOP=1.3, HDOP=0.8, this gives a PDOP of 1.48; I think it is far enough from the default test limit value of 2.5. (https://dev.px4.io/master/en/advanced/parameter_reference.html#EKF2_REQ_GDOP)
Anyway, the check isn't active in the bitmask (https://dev.px4.io/master/en/advanced/parameter_reference.html#EKF2_GPS_CHECK). I'll conduct a few experiments to see if the default value makes sense

**Comment by bresch** [comment]
@dagar I think the `make tests` times out on `shutdown`. When I run it locally, I have:
```
      Start 45: shutdown
45/49 Test #45: shutdown .........................   Passed   23.51 sec
      Start 46: dyn
46/49 Test #46: dyn ..............................   Passed    0.07 sec
      Start 47: posix_hrt_test
47/49 Test #47: posix_hrt_test ...................   Passed    3.13 sec
      Start 48: posix_cdev_test
48/49 Test #48: posix_cdev_test ..................   Passed    3.15 sec
      Start 49: posix_wqueue_test
49/49 Test #49: posix_wqueue_test ................   Passed    3.14 sec

100% tests passed, 0 tests failed out of 49
```
And I guess there is a timeout smaller than 23 seconds for a test.

**Comment by bresch** [comment]
Merging as this is only renaming a parameter that is rarely used and the check isn't enabled by default

**Pull request merged**
