### PR TITLE
NuttX submodule: Update to version performing yield as part of queue exe...

### PR DESCRIPTION
**Pull request by LorenzMeier**
...cution.

@davids5 Review appreciated. This has the potential to help with worst-case latencies as it breaks back-to-back work queue runs into smaller pieces in case a higher priority task becomes ready while one entry is being handled.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This builds against this PR:
https://github.com/PX4/NuttX/pull/55

**Comment by davids5** [comment]
Given the use case for the worker queue: 1) Where the items are scheduled, **once**, and are supposed to be **short** threads of execution, I would think this not necessary.  If the code exec-ed by the queue is long, and it should not be, then normal preemption would run the higher priority task, on the next tick. So I just do not see why we would need unless we are misusing the worker queue.

**Comment by LorenzMeier** [comment]
I need to go back and inspect some of the drivers more closely to understand what their effective runtime is. But since some of them are I2C and relatively slow, it can easily get the worker queue into a relatively busy state. What would you propose for the I2C transfers?

**Comment by nuttx** [comment]
Remember that sched_yield(), in general does nothing.  It will not stop execution of the high priority worker thread; it will not relinquish the CPU.

Nuttx is a strict priority RTOS:  If there is a higher priority task than the high priority worker thread, then it will run immediately in any case.  If there a lower priority task pending, calling sched_yield() will *not* allow it to run.  sched_yield() only has a place in round-robin scheduling where tasks of EQUAL priority can share time slices.

There should never be any round robin scheduling with the high priority worker thread.  That would ruin your real time performance.

Needless to say, this change will never be accepted upstream.

**Comment by nuttx** [comment]
By definition anything that is scheduled in the high priority work queue should be the very highest priority thing to do you in your system.  It should never, never, never yield.

If the high priority work queue is doing something that it should not, then you are not using it correctly.  That is why there is also a low priority work queue.  If the high priority work queue if being filled with high priority tasks -- well you are just screwed.

But if the high priority work queue is being filled with low priority work, then that work should be going to the low priority work queue.

I want to emphasize that yielding with never ever be accepted upstream.  That is flat wrong and violates every concept of realtime programming.  You should not pursue that because you a going in the wrong direction.  You are forcing NuttX behave like non-realtime cooperative scheduler.

**Comment by LorenzMeier** [comment]
Thanks Greg. I'm fully aware of the implications and I didn't submit this upstream, nor did I plan to. You're most welcome to engage in the discussions on Github, but please do not assume that everything which is discussed here will end up in an upstream patch set - much of it is experimental or for discussion (like this one).
The ones which survived this vetting process will end up in patch sets sent to you and/or the NuttX mailing list.

We're not using the work queue wrong, nor does the patch seem to be needed after a discussion with David. I did miss that the higher priority task I want to be running is most likely already running, and the timing jitter I'm chasing must have another source - so next up is doing more / better measurements. Right now I mostly suspect one of the drivers not behaving like it should.

**Comment by nuttx** [comment]
Using sched_yield() will, in general, introduce jitter not reduce it.  jitter is usually the result non-deterministic behavior -- more or less by definitiona (but can also happen if you exceed your processing bandwidth momentarily).  There are a few standard OS interfaces that if you use them, then you will lose determinism.  sched_yield() is one of them.  There are others.  Some of these interfaces are unavoidable -- like sem_wait() or irqsave() or sched_lock() or anything that waits or blocks other tasks.  But sched_yield is avoidable and should never be necessary in a properly designed realtime system.

A properly designed realtime for one, should have a unique priority for every thread.  If you have two threads with the same priority, then you lose determinism (because the threads can execute in arbitrary order and hence arbitrarily change the outcome).  sched_yield does not fix that inherent priority problem.  The only fix is unique priorities.  And, if the priorities are unique, then sched_yield() is a NO_OP anyway.

Greg

**Comment by nuttx** [comment]
If you have jitter, then you must not have a correct implementation of a realtime system.  Since by definition, a realtime has system is deterministic (i.e., no jitter).  An RTOS gives you the tools create a deterministic system, but does no guarantee that your implementation is deterministic.  That depends on many more factors than just the OS.

If I were trying to reduce jitter, there are two things I would examine first:  (1) as I mentioned above, make sure that each thread has a unique priority so that they always response in the same way, and (2) share as few resources as possible between threads.  Shared resources means that there will be locks and locking cause blocking and... jitter.

The worst shared resources might be things like the syslog or the serial console.  Accesses to these all cause non-prioritized serialization of activities.  If all tasks write to the syslog(), for example, then you will have a lot of trouble getting real time performance since the currently logging thread blocks all of the other threads that want to log -- even the higher priority threads.  Such commonly shared resources really trash real-time performance.

So, for the case of something like the syslog(), I would not permit task to write directly to the syslog -- certainly NOT any high priority tasks.  I would do something like have a single low priority, funnel task that does all syslog writing.  High priority, time critical tasks would not compete with other tasks for syslog() access, but would queue the output and continue.

I'm not saying that syslog() is a problem for you (although I suspect it is because of other discussions that David and I have had about logging to an SD card).  I do not know the causes of your jitter.

**Pull request closed without merging**
