### PR TITLE
FlightTasks incremental introduction

### PR DESCRIPTION
**Pull request by MaEtUgR**
This is the follow up to #8874 and the first increment for the more clear introduction of the flight task architecture as discussed in the dev call. ~~Instead of cherry-picking the intricate history of everything I started to just port over file by file such that it should be clear what the different changes really are.~~

~~We should also try to preserve the authors at least on a file by file basis.~~

**EDIT:**
I figured out a different way which very likely results in the least total work:
- All the commits until `PositionControl: comment fix + unused parameter removal` are the entire history of the flight task development but without any changes to the file `mc_pos_control.cpp`. This is the key of the method because it kills all conflicts and the changes to this file can be done afterwards.
- `Revert "Subscription remove unused instance class member"` was necessary because @dagar removed two memebrs which @bkueng used for the subscription_array implementation. This will change again anyways but we need these members for compatibility right now.
- `FlightTasks: comment out mavlink command processing` disables the mavlink command functionality to control tasks because there is no common mavlink message definition for this yet. Sorry if this is not a nice way to just comment it but otherwise dependencies do not make sense anymore and we want this feature available in the future.
- `mc_pos_control: refactor ...` are commits which port necessary refactorings into functions with the only logical change of using the matrix library instead of the math library in one place.
- `mc_pos_control: refactor, indent control block` is an extra commit to only indent the else block for legacy functionality such that the diff of the commit just after gets readable
- `mc_pos_control: enable flight tasks` is the commit finally enabling all the new functionality but only if the pilot sets the parameter `MPC_FLT_TSK` for beta testing like we discussed in the dev call. This probably needs the most careful review to check if anythong legacy might be broken.

### CODE REVIEW

**Comment by MaEtUgR** [comment]
@LorenzMeier @bkueng @dagar @RomanBapst 
The stuff should be all ported now and testable by setting parameter `MPC_FLT_TSK = 1`.

**BUT** I have a flash memory problem here with
```
aerocore2 5315 bytes
px4fmu-v2 12941 bytes
```
see http://ci.px4.io:8080/blue/organizations/jenkins/Firmware/detail/PR-8933/17/pipeline/40/ for CI without the eagle fix and the last random memory saving commit.

There should be no excess memory usage with the flight tasks but the problem is we duplicate position controller functionality in the new structure and only want to start deleting legacy code after the same functionality in the new structure is completed and tested.

Can we get it in like that? Can we somehow save some flash memory in the meantime or do we need to go through a tedious task by task compilation and legacy replacement procedure?

**Comment by Stifael** [comment]
How should we proceed with this PR? 
I suggest to test this PR quickly, merge it and then follow up with #4845 and  #9115. I also have another large PR for Auto which requires this PR to get merged.

**Comment by Stifael** [comment]
Do we have a solution for the RAM problem?

**Comment by dagar** [comment]
I'm getting closer with a solution to the flash shortage. If someone could fully convert mc_att_control and mc_pos_control to the matrix lib it would help.

**Comment by MaEtUgR** [comment]
I'll do mc_att_control as I wrote here: https://github.com/PX4/Firmware/pull/9113#issuecomment-374879830

**Comment by MaEtUgR** [comment]
**I rebased on master** FYI @bkueng @Stifael @RomanBapst 
I agree with @Stifael. I have nothing against improving the architecture further before replacing the legacy functionality completely getting rid of the test parameter `MPC_FLT_TSK`. But I would merge this pr before finding the perfect solution because otherwise it takes unproportionally more maintenance effort for the branch and all the suggested changes.

I would say that mainly we need **enough flash such that it works on the v2 hardware**, some basic tests that nothing is broken which we were already conducting but should repeat just before merging and then it **should get in for further improvements** like #9064 and @Stifael 's auto logic.

**Comment by RomanBapst** [comment]
@MaEtUgR @Stifael I think it's fine if you merge it like this and then we can iterate from there.

**Comment by MaEtUgR** [comment]
@RomanBapst Sounds good, I can rebase but we still need to get around the flash memory shortage.

**Comment by MaEtUgR** [comment]
This pr currently uses 5.6kb too much flash on fmu v2, I'll rebase today and the memory savings @dagar mentioned sound like they will solve the problem. Memory usage will not be permanent, only until legacy functionality is tested to be completely replaced.

**Comment by dagar** [comment]
Getting closer...

image

**Comment by dagar** [comment]
Currently fitting in all builds.

For reference this is how the px4fmu-v2_default binary has changed relative to current master. You can now find this information in the CI system by expanding the px4fmu-v2 build.

image

**Comment by MaEtUgR** [comment]
@bkueng No, there was only small bugfix, refactoring and rebasing going on since I created the pr.
I think it's good to go but will quickly do a last SITL test now.

**Comment by MaEtUgR** [comment]
According to my SITL tests nothing changed/broke since last time I tested. Even with the parameter `MPC_FLT_TSK` enabled (disabled by default) or toggeled in flight everything works as expected e.g. unported things and failsafes.

-> **In my opinion good to go and iterate on.**

While testing flight tasks in position mode smoothing is disabled because it had some bugs, I think @Stifael already fixed them and will follow up.

**Pull request merged**
