### PR TITLE
Tunes library implementation

### PR DESCRIPTION
**Pull request by simonegu**
**Do not merge for the moment**

This adds a tunes library a CLI for the tunes and the implementation of the library in the `tone_alarm` driver

To Do:
- [ ] Extensive testing
~~replace implementation on Mavlink play tune https://github.com/PX4/Firmware/commit/1b7838c2fe67b8df5aefe6e530f8810b4499af67~~ Works already

### CODE REVIEW

**Comment by TSC21** [comment]
@simonegu what's the test status of this?

**Comment by simonegu** [comment]
@TSC21 @mrivi help me out getting this in shape. She did also some testing on a PixRacer.

**Comment by TSC21** [comment]
What's the stack overhead after adding this?

**Comment by TSC21** [comment]
@simonegu updates?

**Comment by simonegu** [comment]
@TSC21 sorry for not coming back to you. At moment I'm quite busy, but I will reserve me some time next week to check the stack overhead.

**Comment by TSC21** [comment]
@simonegu sure thing - also if you manage to follow @davids5 suggestion, great.

**Comment by TSC21** [comment]
@simonegu did you get the chance to make some progress here?

**Comment by mrivi** [comment]
@TSC21 there is no stack overhead since it's only another way to handle tunes

**Comment by davids5** [comment]
>@simonegu - Should we consider one more thing here?
Isolating the stm32 arch specific code from the arch agnostic code.

>As it is in master_new_arch_nuttx_update there are copies of the common code.

> Even if the first pass is to move all the code that touches HW to the bottom of the file.

@simonegu - let's not delay getting this PR in but let's Open an issue for the clean up.

**Comment by dagar** [comment]
CI failure. http://ci.px4.io:8080/blue/organizations/jenkins/Firmware/detail/PR-7316/7/pipeline
Need to explicitly handle case fallthrough with GCC7.

**Comment by simonegu** [comment]
@dagar thanks for the rebase. I was  waiting after release to get this merged. I add the fallthrough.

**Comment by dagar** [comment]
@simonegu is there anything I can do to help get this in?

**Comment by simonegu** [comment]
@dagar We did only test it on a pixracer, do you think it would be good to test it on other platforms?
If you have time for a review would also be great.

**Comment by LorenzMeier** [comment]
Rebased version: https://github.com/PX4/Firmware/pull/8679

**Pull request closed without merging**
