### PR TITLE
Add auav-x21_default  to the qgc firmware for distribution

### PR DESCRIPTION
**Pull request by davids5**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This will not actually make it available. You still need to send a QGC PR. Will merge this one when the QGC PR is in.

**Comment by davids5** [comment]
@pkocmoud is working the QGC side of things.

**Comment by pkocmoud** [comment]
I am working on this with Don. Getting this merged will be one more item off my list.

**Comment by dagar** [comment]
Travis-ci keeps getting worse. Might be time to move the QGC firmware build + upload to s3 over to semaphore.

**Comment by pkocmoud** [comment]
@LorenzMeier 

https://github.com/mavlink/qgroundcontrol/pull/4501 

Can you please merge so I can finish my QGC testing?

**Pull request merged**
