### PR TITLE
Commander: Add file based USB detection workaround for X2

### PR DESCRIPTION
**Pull request by LorenzMeier**
@kd0aij This is for you. Please cross-test.

### CODE REVIEW

**Comment by kd0aij** [comment]
Branch usbdetect on X2, and branch joystickfix of QGC:
able to arm when powered via USB or LiPo

**Comment by LorenzMeier** [comment]
Could you look at the diff and see if you can work out what's at miss?

**Comment by LorenzMeier** [comment]
There is a typo. It should be dev ttyacm 0, not double null. I did that for testing and forgot to remove. Try with one zero.

**Comment by kd0aij** [comment]
no longer able to arm when connected to USB
will flight test soon

**Comment by kd0aij** [comment]
reports "configuration error" when powered from LiPo... debugging

**Comment by kd0aij** [comment]
stat("/dev/ttyACM0", &buffer) is returning zero regardless of whether USB is connected

**Comment by LorenzMeier** [comment]
Coming up with a workaround, sec.

**Comment by LorenzMeier** [comment]
Fixed on master, closing.

**Pull request closed without merging**
