### PR TITLE
Add updated ccache for Ubuntu 16.04 dev scripts

### PR DESCRIPTION
**Pull request by hamishwillee**
This adds the ccache update suggested by @jkflying https://github.com/PX4/Firmware/pull/12827#issuecomment-527953817 for Ubuntu 16.04 only.

Note this layers on top of the existing cmake installation, and only applies for Ubuntu 16.04.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@jkflying @julianoes This works for Jmavsim but not for NuttX targets. I get error below - suggestions?:
```
ubuntu@ubuntu:~/github/Firmware$  make px4_fmu-v4
-- PX4 config file: /home/ubuntu/github/Firmware/boards/px4/fmu-v4/default.cmake
-- PX4 config: px4_fmu-v4_default
-- PX4 platform: nuttx
-- PX4 lockstep: disabled
-- PX4 version: v1.9.0-822-gc75954f
-- cmake build type: MinSizeRel
-- The CXX compiler identification is unknown
-- The C compiler identification is unknown
-- The ASM compiler identification is unknown
-- Found assembler: arm-none-eabi-gcc
CMake Error at CMakeLists.txt:263 (project):
  The CMAKE_CXX_COMPILER:

    arm-none-eabi-g++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:263 (project):
  The CMAKE_C_COMPILER:

    arm-none-eabi-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:263 (project):
  The CMAKE_ASM_COMPILER:

    arm-none-eabi-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM" or the CMake cache entry CMAKE_ASM_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Warning: Did not find file Compiler/-ASM
-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/github/Firmware/build/px4_fmu-v4_default/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/github/Firmware/build/px4_fmu-v4_default/CMakeFiles/CMakeError.log".
Error: /home/ubuntu/github/Firmware/build/px4_fmu-v4_default is not a directory
Makefile:200: recipe for target 'px4_fmu-v4' failed
make: *** [px4_fmu-v4] Error 1
```

**Comment by hamishwillee** [comment]
I add a note at the end to echo "Reboot computer before attempting to build NUTTX targets"

@dagar Can you merge this. Approving is not enough as I don't have the power to do so.

**Comment by jkflying** [comment]
Thanks @hamishwillee !

**Comment by julianoes** [comment]
Thanks @jkflying

**Pull request merged**
