### PR TITLE
Enable FTP on companion link

### PR DESCRIPTION
**Pull request by mhkabir**

### CODE REVIEW

**Comment by AndreasAntener** [comment]
@mhkabir :+1: 
But, did you get this working with MAVROS? I just tried it last week, I could not get the FTP connection up over the serial link (custom mavlink startup, with -x flag of course), it only worked over USB.

**Comment by LorenzMeier** [comment]
@mhkabir What is the testing state here?

**Comment by mhkabir** [comment]
Untested. Didn't get a chance.

**Comment by LorenzMeier** [comment]
I appreciate your contributions, in general it would be great though if we could focus on tested PRs (including providing some test output), and when that's not possible, to indicate boldly they are untested.

**Comment by mhkabir** [comment]
@AndreasAntener @LorenzMeier 
For now, this isn't functioning as expected, and I cannot get a file list even in QGC (direct connection) or mavros. 
The error is : ```Error: timeout waiting for ack```, which I believe Andreas was facing. 
I will get a chance to check further early this week.

**Comment by DonLakeFlyer** [comment]
I'll look and see what's going on with FTP ack thing. Probably not till tonight though.

**Comment by DonLakeFlyer** [comment]
> The error is : Error: timeout waiting for ack, which I believe Andreas was facing.

Are you talking about getting this with your new code or normal connection over USB.

**Comment by AndreasAntener** [comment]
When I tried over serial (912600), it always timed-out on the MAVROS side (mavlink with x flag started). This was the error PX4 threw: https://github.com/PX4/Firmware/blob/6fae021a0091a6706b3cb0d4892b0f6891489dc2/src/modules/mavlink/mavlink_ftp.cpp#L97
It generally worked for me over USB though (at least listings, not getting logs)

**Comment by vooon** [comment]
FYI: you can enable ftp client debugging messages and see what mavros trying to do. Key for sthat `mavros.ftp` (better check results of `/mavros/get_loggers`), setup may be done via rosconsole.yaml file (see docs) or by calling `/mavros/set_logger_level`.

**Comment by mhkabir** [comment]
@DonLakeFlyer 
Using a FTDI USB-UART connected to TELEM2 for all tests. Tried using FTP in QGC through it, but I get the above error.
With mavros, ```mavftp``` crashes with a timeout.

**Comment by DonLakeFlyer** [comment]
This is all working fine over standard USB connection for me.

**Comment by LorenzMeier** [comment]
Closing this for now until its validated.

**Pull request closed without merging**
