### PR TITLE
Disable a set of warnings for NuttX that are new in GCC 6

### PR DESCRIPTION
**Pull request by LorenzMeier**
This doesn't compile in GCC 6 yet to the end, but its a start.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
The culprit is that `<functional>` depends now on `<string>` and we would need to stub that complete header or maybe rather provide our own functional. I'm stopping here for now.

```sh
/interfaces/src/pwm.cpp
In file included from /usr/local/Cellar/gcc-arm-none-eabi-62/20161221/arm-none-eabi/include/c++/6.2.1/string:52:0,
                 from /usr/local/Cellar/gcc-arm-none-eabi-62/20161221/arm-none-eabi/include/c++/6.2.1/stdexcept:39,
                 from /usr/local/Cellar/gcc-arm-none-eabi-62/20161221/arm-none-eabi/include/c++/6.2.1/array:39,
                 from /usr/local/Cellar/gcc-arm-none-eabi-62/20161221/arm-none-eabi/include/c++/6.2.1/tuple:39,
                 from /usr/local/Cellar/gcc-arm-none-eabi-62/20161221/arm-none-eabi/include/c++/6.2.1/functional:55,
                 from ../src/include/../platforms/px4_subscriber.h:42,
                 from ../src/include/../platforms/px4_nodehandle.h:42,
                 from ../src/include/px4.h:46,
                 from /Users/lorenzmeier/src/Firmware/src/drivers/camera_trigger/interfaces/src/pwm.cpp:1:
/usr/local/Cellar/gcc-arm-none-eabi-62/20161221/arm-none-eabi/include/c++/6.2.1/bits/basic_string.h: In function 'float std::__cxx11::stof(const string&, std::size_t*)':
/usr/local/Cellar/gcc-arm-none-eabi-62/20161221/arm-none-eabi/include/c++/6.2.1/bits/basic_string.h:5439:31: error: 'strtof' is not a member of 'std'
   { return __gnu_cxx::__stoa(&std::strtof, "stof", __str.c_str(), __idx); }
                               ^~~
compilation terminated due to -Wfatal-errors.
```

**Comment by LorenzMeier** [comment]
@davids5 It would be interesting to find out if we can better co-exist with something more flexile like CLANG.

**Comment by LorenzMeier** [comment]
Merging but doesn't fix it.

**Comment by davids5** [comment]
@LorenzMeier 

re: Disable a set of warnings for NuttX that are new in GCC 6

Depending on how widespread this is we can handle it in the nuttx-patches like we do the shadow warnings.

On the second one, it looks like we are pulling in foreign header files. That could prove to be a binary compatibility nightmare.

**Pull request merged**
