### PR TITLE
fix loiter yaw error for multirotor(#10262)

### LINKED ISSUE #10262: offboard failsafe to loiter, but the yaw is not stable
i set my failsafe mode to hold, and with no RC, it did turn to hold, but i.m guessing the yaw setpoint is unstable so the drone can't hold its heading, just turning at random. 

i searched the problem and it's said that bad gps can cause the problem, but when i tried HITL simulation with accurate GPS information it still appeared, so is there any better way to hold the heading in loiter mode?

### PR DESCRIPTION
**Pull request by KeyneZzz**
**Test data / coverage**
before fix
https://logs.px4.io/plot_app?log=58f3d121-cc66-4b11-9436-3ec3136b23c3
after fix
https://logs.px4.io/plot_app?log=8a210ac9-fd87-4f63-8421-03a710e24153

fixes #10262

### CODE REVIEW

**Comment by dagar** [comment]
@KeyneZzz could you explain why this is needed? I think the multicopter position controller should be handling yaw setpoints properly.

**Comment by Stifael** [comment]
In principle it should be possible to set `yaw` to NAN and then the vehicle should keep its heading (https://github.com/PX4/Firmware/blob/master/msg/position_setpoint.msg#L36). 
In the case of loier, I think that is what's happening:
- yaw-setpoint is set to NAN (https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission_block.cpp#L604) with the intention that yaw is hold
- in FlightTaskAuto, the heading is mapped as follow: 
  - Triplet yaw-flag is valid (https://github.com/PX4/Firmware/blob/master/src/lib/FlightTasks/tasks/Auto/FlightTaskAuto.cpp#L201): the `yaw_setpoint` will be set to whatever triplet is, even if it is NAN. If the triplet has a finite yaw, then everything willl be handled as expected. If the triplet yaw is NAN (despite the valid yaw-flag), the the position-controller will set the yaw-setpoint to the current yaw (https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/PositionControl.cpp#L195)
  - Triplet yaw-flag is not valid: the heading will be set according to `MPC_YAW_MODE`: https://github.com/PX4/Firmware/blob/master/src/lib/FlightTasks/tasks/Auto/FlightTaskAuto.cpp#L223-L277 where a yaw-lock is applied if the vehicle is withing the acceptance radius

Based on the above logic, I think one of the problems here is similar to https://github.com/PX4/Firmware/pull/10294, that  the yaw-valid-flag might be true, but the actual setpoint might still be infinite.

**Comment by KeyneZzz** [comment]
In my case, i'm not giving any yaw setpoint, but giving a yawspeed setpoint as 0.
I'm not sure if the yaw-valid-flag stuff can solve the problem I met. But the changes I commited can be one of the valid ways to solve it.

In fact, my upper FC is always controlling the yaw by sending yawspeed setpoint.
Is it better to use yaw_sp than to ues yawspeed_sp?

**Comment by MaEtUgR** [comment]
@KeyneZzz Is this an extended fixed wing/vtol fix for https://github.com/PX4/Firmware/pull/10291?

> better to use yaw_sp than to ues yawspeed_sp?

For holding the heading it's better to have a constant yaw setpoint because a yawspeed setpoint can in principle drift.

**Comment by dagar** [comment]
Has this been resolved?

**Comment by MaEtUgR** [comment]
Let's track if the issue was resolved in #10262. I don't think this pr would fix the root cause of the issue because of the same reasons that were already explained in https://github.com/PX4/Firmware/pull/10297#issuecomment-421909966

**Pull request closed without merging**
