### PR TITLE
[DO NOT MERGE] ROS mission tests pwm out sim debugging

### PR DESCRIPTION
**Pull request by dagar**
Debugging pwm_out_sim for the ROS based mission tests.

@lamping7

### CODE REVIEW

**Comment by dagar** [comment]
First failure. http://ci.px4.io:8080/blue/organizations/jenkins/Firmware/detail/PR-8699/5/pipeline/697

**Comment by dagar** [comment]
Update - it appears that one of the problems here is the commander local position validity probation time is ramping up.

**Comment by dagar** [comment]
@PX4BuildBot rebase

**Comment by lamping7** [comment]
Another one with no actuator outputs:
http://ci.px4.io/blue/organizations/jenkins/Firmware/detail/master/309/pipeline/703
https://logs.px4.io/plot_app?log=ec2e8da2-df16-4f2e-89bc-d49ad017c944

**Comment by lamping7** [comment]
Another:
ROStest XML log: https://pastebin.com/pbUg7knq
ulog: https://logs.px4.io/plot_app?log=98dd6281-d917-4115-a7b8-5540c9447faf

**Pull request closed without merging**
