### PR TITLE
vmount: Implement ROI_WPNEXT_OFFSET

### PR DESCRIPTION
**Pull request by bkueng**
@DonLakeFlyer can you cross-test this?

Assumes the offset angle from the mavlink message is in degrees (the message does not specify it).

fixes https://github.com/PX4/Firmware/issues/9082

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Awesome, will do.

**Comment by DonLakeFlyer** [comment]
Testing using attached plan file and ```make posix gazebo_typhoon_h480```. The plan sets the roi to a yaw offset of 90 degrees at waypoint 2 and turns it off at waypoint 4.

Results:
* MIS_MNT_YAW_CTL Enabled - Gimbal yawed correctly to 90 degrees after WP 2. At WP 4 it also appeared to cancel and re-center. A little hard to tell since center gimbal on gazebo seems a little flaky positionally.
* MIS_MNT_YAW_CTL DIsabled - Did not work. Vehicle did not yaw 90 degree. Continued pointing to next waypoint.

[roi.plan.txt](https://github.com/PX4/Firmware/files/1816233/roi.plan.txt)

**Comment by LorenzMeier** [comment]
@DonLakeFlyer I don't fully understand the test result yet. Are you saying the first test was ok and the second test failed?

**Comment by DonLakeFlyer** [comment]
There are two modes for ROI style commands. They depend on whether the gimbal on the vehicle supports yaw or not. If the vehicle has a gimbal with yaw support then MIS_MNT_YAW_CTL=Enabled specifies this. In that case any ROI command should just yaw the gimbal to point the camera the right way. The other case if that either the vehicle has no gimbal, or the gimbal it has does not support yaw. In that case the vehicle itself needs to turn to point camera to ROI. This is specified by MIS_MNT_YAW_CTL=Disabled.

The case where MIS_MNT_YAW_CTL=Disabled is not working. The vehicle does not yaw to the ROI offset.

**Comment by bkueng** [comment]
@DonLakeFlyer I wasn't aware that MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET is supposed to affect the vehicle's yaw depending on `MIS_MNT_YAW_CTL`. Anyways, I added that now in the last commit. Can you test it?
I cannot open the plan you provided, QGC tells me the mission file is not compatible (I'm using latest master).

**Comment by DonLakeFlyer** [comment]
MIS_MNT_YAW_CTL DIsabled - working perfectly now.

> I cannot open the plan you provided, QGC tells me the mission file is not compatible (I'm using latest master).

What error are you getting? I can open it in both Stable and master.

**Comment by bkueng** [comment]
> What error are you getting? I can open it in both Stable and master.

It turned out to be the file extension. The downloaded file from github was named `roi.plan.txt`. After renaming to `roi.plan`, it worked fine.

**Pull request merged**
