### PR TITLE
Detect if the pilot is active and trying to take control on an autopilot...

### PR DESCRIPTION
**Pull request by LorenzMeier**
... failure. Sparked by a good discussion with Andrew Tridgell on how to best support taking control on autopilot failures.

@tridge @priseborough You will want to have a look.

UNTESTED!

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@kd0aij Interested in testing? This would allow you to take over manually much faster than currently.

**Comment by kd0aij** [comment]
Sorry, I had forgotten about this PR. To flight test, I take it one would need a GCS connected via RF modem to issue the stop command. I suppose my 6' Telemaster would be a good candidate for this, since it's the only plane I have with an RF modem installed.

**Comment by LorenzMeier** [comment]
I wouldn't recommend to flight test it - I would only recommend a bench test at this point.

**Comment by kd0aij** [comment]
I cherry-picked commit b27fd44 into latest master, "make clean, px4fmu-v2_default". Reflashed and armed then switched to ALTCTL with motors idling. Issued "px4io stop" on console and "commander: nav state: DESCEND" printed on console. Motors stopped, controls went to neutral. But no manual control available on moving TX sticks or mode switch. Second try: console printed "commander: nav state: AUTO_RCRECOVER", motors stopped, controls neutral. Still no response to TX.

**Comment by LorenzMeier** [comment]
Ok, thanks for testing! I need to re-inspect this.

**Comment by LorenzMeier** [comment]
Superseded by immediately override (which is the new default).

**Pull request closed without merging**
