### PR TITLE
WIP: qurt test linking target

### PR DESCRIPTION
**Pull request by dagar**
FYI @karliss

### CODE REVIEW

**Comment by dagar** [comment]
The goal is to have a QuRT test target for catching the majority of symbol resolution issues at build time.

**Comment by karliss** [comment]
Silly question, is there a technical reason for having px4 qurt code split in multiple .so that dynamically link each other instead of single .so(+stuff generated by hexagon SDK and Linux half)?

**Comment by julianoes** [comment]
@dagar can you add some description here? I don't understand how this would be used. Thanks.

**Comment by dagar** [comment]
It's attempting to resurrect something we already had, but weren't using.

Typically the QuRT build produces a dynamic library. This build variant produces a binary (not usable) for the sole purpose of linking and finding unresolvable symbols.

**Comment by dagar** [comment]
> Silly question, is there a technical reason for having px4 qurt code split in multiple .so that dynamically link each other instead of single .so(+stuff generated by hexagon SDK and Linux half)?

I don't know the history, but I'm definitely in support of reviewing (and simplifying) the snapdragon build. For example most of these cmake helper functions like LINUX_APP (https://github.com/PX4/Firmware/blob/master/platforms/posix/CMakeLists.txt#L34) and QURT_LIB (https://github.com/PX4/Firmware/blob/master/platforms/qurt/CMakeLists.txt#L43) could be replaced with regular cmake usage. This would help remove some of the magic and make it a bit easier to understand and maintain going forward.

**Comment by karliss** [comment]
Looks like I mixed up something. Second .so is the automatically generated fastrpc code. I initially thought that there was one more.  Getting rid of it would mean rewriting a portion of cmake_hexagon. Although qurt_lib.cmake and linux_app.cmake didn't look too complicated and half of them was upload code which we don't need. Looking at qurt_lib.cmake i didn't saw an obvious reason for having _skel.so separately, but almost all the qualcom examples are built that way.

While looking at hexagon SDK I noticed so_sym_verify.py.

**Pull request closed without merging**
