### PR TITLE
Fix logger signed unsigned error with GCC 7.3 in Cygwin

### LINKED ISSUE #9920: SITL logger compile error with GCC 7.3
**Bug**
I updated Cygwin to the newest version and it's using GCC 7.3

```
$ gcc --version
gcc (GCC) 7.3.0
```

When I compile SITL by `make posix` I get the following errors which weren't there before on this branch:

```
../../src/modules/logger/logger.cpp:2136:27: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
statfs_buf.f_bavail >= (px4_statfs_buf_f_bavail_t)(min_free_bytes / statfs_buf.f_bsize)) {
~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../src/modules/logger/logger.cpp:2172:26: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
if (statfs_buf.f_bavail < (px4_statfs_buf_f_bavail_t)(50 * 1024 * 1024 / statfs_buf.f_bsize)) {
~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Workaround**
Of course I can just add a `(int)` cast in front of the second operand of the comparison and then it compiles again but I'm writing this issue because there's likely some inconsistency with the types.

Why is `px4_statfs_buf_f_bavail_t` defined once signed, once usigned here? https://github.com/PX4/Firmware/blob/9ce83f22087311df06078edf3a9da640d93ab396/src/platforms/px4_defines.h#L115-L173

### PR DESCRIPTION
**Pull request by MaEtUgR**
Thanks to @bkueng for suggesting this change in #9920 !

closes #9920

### CODE REVIEW

**Comment by dagar** [comment]
Combine for nuttx?

**Comment by dagar** [comment]
QuRT doesn't like it (what a surprise).

**Comment by bkueng** [comment]
> Combine for nuttx?

Yes, and apparently exclude QuRT

**Comment by dagar** [comment]
In that case you might as well do the typedef directly in logger.cpp.

**Comment by MaEtUgR** [comment]
> Combine for nuttx?
> exclude QuRT

I feel somehow not in the loop. Do I look for existing ifdefs and experiment with them such that CI gets happy for qurt and mac? What does it have to do with NuttX? Are you refering to only define it in one spot for all platforms?

**Comment by dagar** [comment]
Sorry, should have been more explicit.

That's pretty close, one last thing I was also suggesting is to use `typedef decltype(statfs::f_bavail) px4_statfs_buf_f_bavail_t;` for both posix and nuttx. QuRT we can ignore entirely because logger isn't even built on that side.

**Pull request merged**
