### PR TITLE
update sitl_gazebo, mavlink, and CI docker tag

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
Something wrong with fastrtps installation, maybe a path issue?

image

**Comment by TSC21** [comment]
Yeah that looks like a path issue. Will take a look

**Comment by TSC21** [comment]
@dagar this is the problem: https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_base#L77. The normal path would be `/bin/fastrtpsgen`. I will readd the line I removed on the last update.

**Comment by dagar** [comment]
Temporarily keeping compile jobs for NuttX (px4fmu-v5_rtps) and armhf (parrot_bebop_default) on the existing tag to work around issues.

**Comment by TSC21** [comment]
We need a new release for the containers though

**Comment by dagar** [comment]
Yes, this is just to see if everything else is working.

**Comment by dagar** [comment]
Here's another issue in px4io/px4-dev-ros-kinetic:2018-11-22

image
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/pr-docker_update/2/pipeline/74

**Comment by TSC21** [comment]
@dagar new tag pushed https://github.com/PX4/containers/releases/tag/2018-11-25. This drops a change I did to the base container where I was removing the ENV_FASTRTPSGEN var. By that time it didn't seemed required but now I saw it `fastrtpsgen` wasn't on the default dir.

**Comment by TSC21** [comment]
> Here's another issue in px4io/px4-dev-ros-kinetic:2018-11-22
>
>image
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/pr-docker_update/2/pipeline/74

Right, let me look at that.

**Comment by dagar** [comment]
This PR is now passing CI everywhere, but keeps a number of containers behind.

 - px4-dev-nuttx on 2018-09-11
    - problem building px4fmu-v5_rtps
 - px4-dev-raspi on 2018-09-11
    - problem building raspberry pi and bebop (cmake package issues)
 - px4-dev-ros-kinetic on 2018-09-11
    - SITL CI mission tests issue with px4tools

This is safe to merge, but let's keep going towards a single docker tag update that works across the board.

**Comment by TSC21** [comment]
Let's bring this in while we tackle the broken containers missing.

**Comment by TSC21** [comment]
>  - px4-dev-raspi on 2018-09-11
    - problem building raspberry pi and bebop (cmake package issues)

This one needs a consideration: do we need Cpack for a cross-compile target?

**Comment by dagar** [comment]
> do we need Cpack for a cross-compile target?

Yes, but it doesn't need to try and pull in library dependencies like it's trying to do now. I believe we can just disable CPACK_DEBIAN_PACKAGE_SHLIBDEPS. https://github.com/PX4/Firmware/blob/master/CMakeLists.txt#L524

**Comment by TSC21** [comment]
> > do we need Cpack for a cross-compile target?
>
>Yes, but it doesn't need to try and pull in library dependencies like it's trying to do now. I believe we can just disable CPACK_DEBIAN_PACKAGE_SHLIBDEPS. https://github.com/PX4/Firmware/blob/master/CMakeLists.txt#L524

Interesting. So can set or unset that based on the target?

**Pull request merged**
