### PR TITLE
EKF Attitude Position Estimator code cleanup

### PR DESCRIPTION
**Pull request by Zefz**
Code style cleanup, no functionality changes.
This is to make the module more readable and consistent with the rest of the system and hopefully make future changes easier for developers.

* Rename FixedwingEstimator to AttitudePositionEstimatorEKF (this module is also used by multirotors)
* Enforces type safety
* Coding style
* Indentation fixes
* Documentation
* Use preferred c++ standard functions

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! Note that the original source file, which we are tracking, is here:
https://github.com/priseborough/InertialNav/blob/optflow_merge/code/estimator_22states.cpp

So the copyright attributions should refer to InertialNav, if any are added. Because that repository contains 60 MiB worth of test data, we didn't pull it in as sub module yet. Getting rid of the test data would deduct from the usefulness of the test harness, so I'm not sure if and how this would be resolved any time soon.

**Comment by LorenzMeier** [comment]
Cool! I need one more day to finish all the code review.

**Comment by LorenzMeier** [comment]
Is this flight tested?

**Comment by Zefz** [comment]
I am going to fly it today. Weather has been bad here preventing me from testing it earlier :)

**Comment by Zefz** [comment]
Rebased onto master, no changes.

**Comment by LorenzMeier** [comment]
Tentatively closing as contained in #1770.

**Pull request closed without merging**
