### PR TITLE
[WIP] Mixer parameters tuning and saving through nsh including unit tests 

### PR DESCRIPTION
**Pull request by crashmatt**
First step towards mavlink tuning of mixers.

- Mixer parameter tuning through nsh commands.  
- Unit tests for MixerGroup include parameter modification and saving mixer to buffer.
- MixerGroup parameter access compatible with mavlink mixer parameters.

[Waiting for this PR into mavlink common](https://github.com/mavlink/mavlink/pull/711)

**TODO**
**Complete mavlink PR**
Update to changes in mavlink parameters

[Description document for mixer parameters](https://docs.google.com/document/d/1LeQC2qtxqdesNuJ3RAWH_MJ_30xjf-PMN3bd5wtUAUo/edit#heading=h.3cs7tuenkkib)

[This is a smaller part of a larger change which was implemented in this closed PR](https://github.com/PX4/Firmware/pull/6960)

**nsh menu**
image

**View parameters - Running sitl**
image

**Setting a parameter and reading back the change**
image

**Showing mixer configuration on screen - A simple quadcopter config**
image

**Saving mixer configuration to file (posix)**
image

**The output mixer file opened in a text editor**
image

### CODE REVIEW

**Comment by crashmatt** [comment]
Closed until further notice

**Comment by dagar** [comment]
Hi Matt, please let us know when you're ready for review or testing.

**Comment by crashmatt** [comment]
@dagar, everything is waiting for the mavlink PR to complete.

https://github.com/mavlink/mavlink/pull/711

**Comment by crashmatt** [comment]
Closing in favor of hard coded application specific mixer based on standard mavlink parameters

**Comment by crashmatt** [comment]
Closing in favor of hard coded application specific mixer based on standard mavlink parameters

**Comment by crashmatt** [comment]
Daniel,
Have stopped support for mixer parameters.  There wasn't the community
backing I was hoping for.  I will hard code a mixer specific to my
requirements and tune it with standard mavlink parameters.

Thanks for your support

/Matt

**Comment by LorenzMeier** [comment]
@crashmatt What drives the conclusion that there was no community backing? There was great interest and people sunk time into talking through the concept and reviewing code and specs. That seems to be the opposite of lack of community backing.

**Comment by dagar** [comment]
@crashmatt what did you need? If you're looking for more input we need to ask on places like gitter, discuss, the dev call, and ping people that have relevant interests. Most aren't even aware of these things because there's generally too much activity on github to follow everything.

**Comment by TSC21** [comment]
I'm interested on this as it seems a very solid PR and a very useful feature. Maybe we can start by reviewing the Mavlink PR?

**Comment by crashmatt** [comment]
A few reasons

I ran out of energy in the face of yet more nagging from the wife.  This has a negative impact on my ability to stay positive about any plan I have.

I was doing something wrong with the mavlink PR. Either I wasn't communicating properly or my idea was not right.  Lack of contact with devs didnt help.

All said, I need to take a mental break. Closing the PRs helps me do that.  With some rest I might come back with an improved mavlink PR.

**Pull request closed without merging**
