### PR TITLE
vehicle_trajectory_waypoint limit unnecessary updates and reduce logging

### LINKED ISSUE #10345: [Logger]: Log size doubled
a few weeks ago, the log size doubled on the same flights.

two 5 minute flight running commit 7c76028 weighing in at 10.9 MB:
https://logs.px4.io/plot_app?log=b0973caa-e51d-4612-8c70-3c13576cd8a8
https://logs.px4.io/plot_app?log=7bdf4aa5-f309-4afa-af1e-31578b82a3a7

same two flights running commit 9a23295 weighing in at 22 MB:
https://logs.px4.io/plot_app?log=0be6630a-0e50-4a23-ad50-561110cdee8a
https://logs.px4.io/plot_app?log=632011ec-1d3b-4eba-82b8-fe6fe85b6fa7

today's master bbc0c28 for reference also weighing in at 22 MB:
https://logs.px4.io/plot_app?log=5af821ab-b9af-4514-9b98-804fdde019a8
https://logs.px4.io/plot_app?log=afa1ca96-1f58-4cfc-9435-2e33be98dc0d

@dagar thoughts?

### PR DESCRIPTION
**Pull request by dagar**
@mrivi could you look at the original issue #10345 and this PR? I'm not sure if it's the right solution, but we need to do something to limit the output. Ideally it would only publish and log noteworthy changes.

 - fixes #10345

### CODE REVIEW

**Comment by mrivi** [comment]
We can publish only when `MPC_OBS_AVOID` is set to 1. 
Furthermore, `vehicle_trajectory_waypoint_desired` could be published only when there is a triplet update.

**Comment by mrivi** [comment]
`vehicle_trajectory_waypoint` has an array of type `trajectory_waypoint` with 5 elemets. Only 2 of those 5 elements are filled with information. We could reduce the array size until we actually need to send/receive more information

**Comment by dagar** [comment]
I would size the trajectory waypoint array to whatever you need in the near future and only publish (and log) data when it's relevant (parameter enabled, updated, etc).

**Comment by dagar** [comment]
@mrivi how about this? The position controller will now only update and publish the vehicle_trajectory_waypoint_desired if the param is enabled and FlightTask has an updated version.

**Comment by mrivi** [comment]
@dagar I have tested in SITL. It works as expected

**Pull request merged**
