### PR TITLE
Make LPE default estimator.

### PR DESCRIPTION
**Pull request by jgoppert**
This switches the default estimation group to attitude estimator q + lpe instead of attitude estimator q + inav.

### CODE REVIEW

**Comment by jgoppert** [comment]
This is mission mode, alt mode, position mode, and manual without flow outdoors with alt mode 0.

http://logs.uaventure.com/view/JJZy8wj76uAEuk59xB9Fr3

**Comment by jgoppert** [comment]
Mission mode with alt mode 1 when no lidar/ flow attached, testing that it defaults back to alt mode 0.

http://logs.uaventure.com/view/E9bhG3f8qMSVbEtH6dBoPB

**Comment by jgoppert** [comment]
## First ever mission with px4flow for position!

http://logs.uaventure.com/view/xQ5N9uvGBEKec4FLGsZa86

Note, had to lower MPC_XY_P to 0.2 to avoid large tilt angles and set max takeof alt to 1, and set all altitudes for waypoints to 2 m.

**Comment by LorenzMeier** [comment]
@tumbili Can you please add this to your testing?

@kd0aij Do you have an opportunity to flight-test this including a mission?

**Comment by LorenzMeier** [comment]
@jgoppert Definitely something we should make the default for 1.4!

**Comment by jgoppert** [comment]
@LorenzMeier Sounds good. I will get in some more testing as well.

**Comment by kd0aij** [comment]
@jgoppert Regarding flight testing of the attitude estimate: has anyone run multiple estimators in parallel and logged the results at high rates for comparison? I've done that in the past to validate the MPU6000 when it was first added to the UDB series. I'd really like to quantify the accuracy issues e.g. with and without GPS for acceleration compensation.

I've been hoping to see tests done with mocap data for ground-truth, but those are either private or non-existent.

**Comment by jgoppert** [comment]
@kd0aij The attitude estimator here is just attitude estimator q. It would be good to see some mocap results.

**Comment by kd0aij** [comment]
Yes, I was thinking of running two copies of the Q estimator, one with GPS feedback disabled (it looks like parameter ATT_ACC_COMP controls that), then flying a pattern designed to demonstrate the need for acceleration compensation.

**Comment by jgoppert** [comment]
@LorenzMeier, @tumbili  Let's merge this. INAV is just causing us more headaches than it is worth at this point. I spent a day debugging an issue that didn't exist on LPE and was really an INAV bug because of end user confusion.

**Comment by jgoppert** [comment]
This diff is just 1 character so should be easy :-).

**Comment by mhkabir** [comment]
@jgoppert nice diff ;) 

@LorenzMeier Let's get this in ASAP. I've been referring all the people who've been trying optical flow to LPE, and we've achieved that level of "it just works!".

**Comment by mhkabir** [comment]
For reference,  this is the result a student (with no prior PX4 experience) got, just after taping a PX4Flow to his Iris and setting this param. 
https://www.youtube.com/watch?v=TtTVMpdwHJI

**Comment by kd0aij** [comment]
fluorescent lights?

**Comment by jgoppert** [comment]
Type of lighting isn't critical, have flown with 180 lumen led work light outside  at night. Also daylight outdoors or led/incandescent indoors works.

**Comment by kd0aij** [comment]
I thought there was a stong strobe effect with fluorescents.
Is there any need to tune parameters for LPE for different size quads?

**Comment by jgoppert** [comment]
Haven't flown under fluorescent myself. No changes necessary for different size quads.

**Comment by jgoppert** [comment]
@kd0aij @pkocmoud @LorenzMeier  I plan to do some flying tomorrow morning with lidar on my iris so we can quantify the qualitative improvements we have been making with the altitude parameters without lidar. I will add a parameter so that the lidar doesn't go into the correction but is still recorded, similar to LPE_GPS_ON, probably LPE_LDR_ON so we can use it as a baseline.

I would like to see this merged with master this weekend if possible, so if you guys have time for a final flight for a thumbs up, would be appreciated.

**Comment by jgoppert** [comment]
Just tested with optical flow outdoors, works even better with latest updates to LPE, I flew at 2m and 3m above the ground with few issues. I did make the following gain changes to make the optical flow more manageable:

## Comparison vs. GPS

image

image

## Params

MPC_ALT_HOME =  1 (Terrain following)
MPC_XY_VEL_MAX = 2
MPC_XY_P = 0.5

## Video:

https://www.youtube.com/watch?v=Ttfq0-2K434

## Log:

http://logs.uaventure.com/view/KwTFDaheRueMNmFRJQ3huH

**Comment by rawk-v** [comment]
@jgoppert  I think MPC_ALT_HOME should be MPC_ALT_MODE.

**Comment by jgoppert** [comment]
Yes, sorry for the typo.

**Comment by LorenzMeier** [comment]
@ecmnet @ilia-sheremet @kd0aij Tests with LPE and the latest beta branch would be much appreciated. Please also fly INAV with the same mission.

**Comment by ilia-sheremet** [comment]
@LorenzMeier Last time I had this [issue](https://github.com/PX4/Firmware/issues/5060) and nobody closed it yet. Will fly next week to try the latest firmware on different estimators.

**Comment by jgoppert** [comment]
@LorenzMeier I'm working on getting SITL to the point I can verify LPE is behaving correctly over various terrains and with optical flow. That should allow me to close open issues such as from @ilia-sheremet and @ecmnet  and get to the point they can flight test confidently. I will try to get it wrapped up in the next few days.

**Pull request merged**
