### PR TITLE
fw_pos_control_l1 reset internal takeoff and landing state when arming

### PR DESCRIPTION
**Pull request by dagar**
Continuation of https://github.com/PX4/Firmware/pull/11738

### CODE REVIEW

**Comment by ryanjAA** [comment]
I’m going to have 11738 flown today. Do you want this instead?

**Comment by ryanjAA** [comment]
Works as intended. Able to arm disarm and fly more missions. Logs to follow.

**Comment by ryanjAA** [comment]
https://review.px4.io/plot_app?log=0bb45d23-a942-48ab-8e06-1513b4355ece - Flight 1
https://review.px4.io/plot_app?log=d1958d32-4937-4da0-ad65-5169a87b3236 - Arm - Disarm
https://review.px4.io/plot_app?log=0162574a-1a34-4465-9d32-6d4aa4c0a0af - Flight 2

No reboots needed - all working.

**Comment by julianoes** [comment]
Great @dagar, thanks for testing @ryanjAA!

**Comment by ryanjAA** [comment]
Anytime - thanks @julianoes and @dagar.

**Pull request merged**
