### PR TITLE
geo remove global conversion and cleanup mavlink receiver

### PR DESCRIPTION
**Pull request by dagar**
The global map projection reference was only being used by the mavlink messages local_position_ned_cov and gps_global_origin and can be replaced with a local reference in mavlink receiver. Should we get rid of it? This saves some flash and ram.

### CODE REVIEW

**Comment by TSC21** [comment]
I am planning to add support for global_origin in the Firmware, as opposed to the local_origin (multiple systems may share a global origin while the local origin is the same for them). So I would also require a local projection. Also the loca_ned_cov is being used currently by external apps (MAVROS odometry plugin for example). @jgoppert for example is using it for a specific project in a company. The right way would be having covariances on the visual_position_estimate msgs as I proposed on the Mavlink repo, but currently is staled as Lorenz prefers not to add cov matrices to those msgs.

**Comment by TSC21** [comment]
Here's is the issue related to the global_origin - https://github.com/PX4/Firmware/issues/7368

**Comment by dagar** [comment]
I should clarify that this shouldn't break any current functionality (including mavlink local_position_ned_cov -> uorb vehicle_vision_position), but simply gets rid of the global variables and unused code.

I'm not up to speed with your issue, but we could discuss options for how to handle it in PX4 architecturally.

**Comment by TSC21** [comment]
> I'm not up to speed with your issue, but we could discuss options for how to handle it in PX4 architecturally.

Sure. Mostly I have the idea explained on #7368. It would be a similar thing to the home_position I guess

**Comment by dagar** [comment]
This saves a couple thousand bytes of memory on a pixracer, but shouldn't have any functional change.

**Pull request closed without merging**
