### PR TITLE
cmake toolchain enable double fpu for cortex-m7

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This needs good validation, but nothing that would prevent it from being merged.

**Comment by dagar** [comment]
Microbenchmark double floating point (https://github.com/PX4/Firmware/pull/9810).

**Before**

	INFO  [tests] RUNNING TEST: time_double_prevision_float
	double add: 1000 events, 742us elapsed, 0.74us avg, min 1us max 2us 0.440us rms
	double sub: 1000 events, 863us elapsed, 0.86us avg, min 1us max 2us 0.364us rms
	double mul: 1000 events, 673us elapsed, 0.67us avg, min 1us max 1us 0.469us rms
	double div: 1000 events, 2244us elapsed, 2.24us avg, min 2us max 3us 0.430us rms
	double sqrt: 1000 events, 2481us elapsed, 2.48us avg, min 2us max 5us 0.567us rms
	INFO  [tests] TEST PASSED: time_double_prevision_float

	INFO  [tests] RUNNING TEST: time_double_prevision_float_trig
	sin(): 1000 events, 8072us elapsed, 8.07us avg, min 7us max 10us 0.474us rms
	cos(): 1000 events, 9281us elapsed, 9.28us avg, min 7us max 13us 1.031us rms
	tan(): 1000 events, 16843us elapsed, 16.84us avg, min 16us max 21us 0.738us rms
	acos(): 1000 events, 2340us elapsed, 2.34us avg, min 2us max 5us 0.511us rms
	asin(): 1000 events, 2446us elapsed, 2.45us avg, min 2us max 4us 0.558us rms
	atan2(): 1000 events, 13979us elapsed, 13.98us avg, min 13us max 16us 0.522us rms
	sqrt(): 1000 events, 2471us elapsed, 2.47us avg, min 2us max 5us 0.565us rms
	INFO  [tests] TEST PASSED: time_double_prevision_float_trig


**After**

	INFO  [tests] RUNNING TEST: time_double_prevision_float
	double add: 1000 events, 447us elapsed, 0.45us avg, min 1us max 1us 0.497us rms
	double sub: 1000 events, 454us elapsed, 0.45us avg, min 1us max 1us 0.498us rms
	double mul: 1000 events, 464us elapsed, 0.46us avg, min 1us max 1us 0.499us rms
	double div: 1000 events, 636us elapsed, 0.64us avg, min 0us max 1us 0.481us rms
	double sqrt: 1000 events, 456us elapsed, 0.46us avg, min 0us max 1us 0.498us rms
	INFO  [tests] TEST PASSED: time_double_prevision_float

	INFO  [tests] RUNNING TEST: time_double_prevision_float_trig
	sin(): 1000 events, 1795us elapsed, 1.79us avg, min 1us max 3us 0.421us rms
	cos(): 1000 events, 1356us elapsed, 1.36us avg, min 1us max 3us 0.481us rms
	tan(): 1000 events, 2123us elapsed, 2.12us avg, min 2us max 4us 0.338us rms
	acos(): 1000 events, 1229us elapsed, 1.23us avg, min 1us max 2us 0.420us rms
	asin(): 1000 events, 1463us elapsed, 1.46us avg, min 1us max 2us 0.499us rms
	atan2(): 1000 events, 2426us elapsed, 2.43us avg, min 2us max 4us 0.509us rms
	sqrt(): 1000 events, 578us elapsed, 0.58us avg, min 0us max 1us 0.494us rms
	INFO  [tests] TEST PASSED: time_double_prevision_float_trig

**Comment by dagar** [comment]
top

Not a huge difference overall.

**Before**

	 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
	   0 Idle Task                   58392 56.818   504/  748   0 (  0)  READY  3
	   1 hpwork                       1615  1.660   864/ 1780 249 (249)  w:sem 13
	   2 lpwork                        298  0.262   640/ 1780  50 ( 50)  w:sig 10
	   3 init                        13534  0.000  1760/ 2484 100 (100)  w:sem  3
	 399 mavlink_shell                4793  0.000   880/ 2020 100 (100)  w:sem  3
	 105 dataman                       104  0.000   728/ 1180  90 ( 90)  w:sem  4
	 109 gps                           174  0.174   960/ 1580 220 (220)  w:sem  5
	 154 sensors                      8258  3.933  1148/ 1964 249 (249)  w:sem 17
	 156 commander                     808  0.874  2144/ 3212 140 (140)  w:sig 29
	 157 commander_low_prio              2  0.000   552/ 2996  50 ( 50)  w:sem 29
	 168 px4io                        1934  2.097   920/ 1484 251 (251)  w:sem 11
	 176 mavlink_if0                  2146  2.185  1712/ 2540 100 (100)  w:sig 34
	 177 mavlink_rcv_if0               385  0.349  1056/ 2836 175 (175)  w:sem 34
	 181 mavlink_if1                  1439  1.486  1712/ 2572 100 (100)  w:sig 34
	 182 mavlink_rcv_if1               382  0.437  1232/ 2836 175 (175)  w:sem 34
	 198 mavlink_if2                   793  0.786  1704/ 2532 100 (100)  w:sig 29
	 199 mavlink_rcv_if2               355  0.437  1080/ 2836 175 (175)  w:sem 29
	 394 log_writer_file                 0  0.000   360/ 1068  60 ( 60)  w:sem 38
	 236 mavlink_if3                  6848  7.692  1792/ 2532 100 (100)  READY 37
	 238 mavlink_rcv_if3               393  0.524  1456/ 2836 175 (175)  w:sem 37
	 276 fmu                          1444  1.573   784/ 1324 251 (251)  w:sem  7
	 318 ekf2                         8101  8.741  4592/ 6572 250 (250)  w:sem 20
	 324 mc_att_control               3211  3.496   736/ 1660 251 (251)  w:sem 17
	 331 mc_pos_control               3248  3.846  1016/ 1876 250 (250)  w:sem 12
	 339 navigator                     120  0.174   816/ 1764 105 (105)  w:sem 15
	 379 logger                       1052  1.048  1256/ 3540 245 (245)  w:sem 38
	 434 top                           333  0.961  1320/ 1684 255 (255)  RUN    3

**After**

	 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
	   0 Idle Task                  132018 61.032   512/  748   0 (  0)  READY  3
	   1 hpwork                       3120  1.423   688/ 1780 249 (249)  w:sig 13
	   2 lpwork                        631  0.266   640/ 1780  50 ( 50)  w:sig 10
	   3 init                        27304  0.000  1760/ 2484 100 (100)  w:sem  3
	 399 mavlink_shell                 710  0.000   856/ 2020 100 (100)  w:sem  3
	 105 dataman                       132  0.000   728/ 1180  90 ( 90)  w:sem  4
	 109 gps                           359  0.177   968/ 1580 220 (220)  w:sem  5
	 154 sensors                     13135  4.181  1148/ 1964 249 (249)  w:sem 17
	 156 commander                    1603  0.711  2144/ 3212 140 (140)  w:sig 29
	 157 commander_low_prio              5  0.000   552/ 2996  50 ( 50)  w:sem 29
	 168 px4io                        4232  2.046   976/ 1484 251 (251)  w:sem 11
	 176 mavlink_if0                  4807  2.402  1712/ 2540 100 (100)  w:sig 34
	 177 mavlink_rcv_if0               684  0.266  1072/ 2836 175 (175)  w:sem 34
	 181 mavlink_if1                  3201  1.423  1712/ 2572 100 (100)  w:sig 34
	 182 mavlink_rcv_if1               697  0.355  1232/ 2836 175 (175)  w:sem 34
	 198 mavlink_if2                  1696  0.711  1712/ 2532 100 (100)  w:sig 29
	 199 mavlink_rcv_if2               687  0.355  1112/ 2836 175 (175)  w:sem 29
	 394 log_writer_file                 0  0.000   360/ 1068  60 ( 60)  w:sem 38
	 236 mavlink_if3                 14697  7.740  1792/ 2532 100 (100)  READY 37
	 238 mavlink_rcv_if3               747  0.355  1456/ 2836 175 (175)  w:sem 37
	 276 fmu                          1656  0.800   816/ 1324 251 (251)  w:sem  7
	 318 ekf2                        15164  7.384  4584/ 6572 250 (250)  w:sem 20
	 324 mc_att_control               6771  3.291   736/ 1660 251 (251)  w:sem 17
	 331 mc_pos_control               4659  2.402   968/ 1876 250 (250)  w:sem 12
	 339 navigator                     256  0.088   808/ 1764 105 (105)  w:sem 15
	 379 logger                       1533  0.711  1256/ 3540 245 (245)  w:sem 38
	 409 top                            30  0.800  1240/ 1684 255 (255)  RUN    3

	Processes: 27 total, 3 running, 24 sleeping, max FDs: 54
	CPU usage: 37.90% tasks, 1.07% sched, 61.03% idle
	DMA Memory: 5120 total, 1024 used 1024 peak
	Uptime: 211.949s total, 132.018s idle

**Comment by dagar** [comment]
sensors module loop perf before and after

    sensors: 37746 events, 23736067us elapsed, 628.84us avg, min 62us max 1801us 232.857us rms
    sensors: 82094 events, 43028308us elapsed, 524.13us avg, min 68us max 1726us 216.962us rms

**Pull request merged**
