### PR TITLE
mavlink: set protocol to TCP when using TCP

### PR DESCRIPTION
**Pull request by nicolaerosia**
Signed-off-by: Nicolae Rosia <nicolae.rosia@gmail.com>

### CODE REVIEW

**Comment by bkueng** [comment]
This is not correct. `-t` is used to specify the partner IP, not TCP. TCP is not implemented as a transport layer for mavlink.
See https://dev.px4.io/en/middleware/modules_communication.html#mavlink

**Comment by nicolaerosia** [comment]
correct. @bkueng do you have this on your pipeline?

**Comment by bkueng** [comment]
No, we don't have plans for that as far as I know. Since mavlink is designed for links that can drop packets, UDP is fine for our use-cases.

**Comment by nicolaerosia** [comment]
ok, thanks

**Pull request closed without merging**
