### PR TITLE
attitude_estimator_q: correctly handle loss of external yaw estimation

### PR DESCRIPTION
**Pull request by ArkadiuszNiemiec**
Q Estimator in the LPE is not handling the situation when external yaw estimation stops being published so the `ATTITUTDE.yaw` is converging to the last received data even if it's very old.

Bug reported in #11433.

This fix makes the Q Estimator always check if the external estimation is not too old and not only if new data is present. Tested in flight, works great in indoor situations with no GPS, mag sensors and with unstable external estimator.

### CODE REVIEW

**Comment by mhkabir** [comment]
Why does the current check on the actual data timestamp not work for you?

This "fix" seems to be wrong.

**Comment by ArkadiuszNiemiec** [comment]
@mhkabir because it's only executed 'if (vision_updated)'. If vision is not updated it never sets '_ext_hdg_good' to 'false'.

**Comment by mhkabir** [comment]
Okay, can you init ext_hdg_good to false outside the block every iteration.

**Comment by ArkadiuszNiemiec** [comment]
@mhkabir I don't think this is a good idea. My external estimator is publishing the data at max. 10 Hz and depending on how often `AttitudeEstimatorQ::task_main()` is executed it would not fuse the data for most of the time.
The `500000 us` in `_ext_hdg_good = time_topic > 0 && (hrt_elapsed_time(&time_topic) < 500000);` is based on previous version of this code and is perfect in my situation.

**Comment by mhkabir** [comment]
I don't see the issue. As long as you're sending data at more than 2Hz, my scheme should work fine.

The main loop is polling on the IMU (250Hz).

**Comment by ArkadiuszNiemiec** [comment]
> I don't see the issue. As long as you're sending data at more than 2Hz, my scheme should work fine.
> 
> The main loop is polling on the IMU (250Hz).

To set `_ext_hdg_good` to `true` it would require the `if (vision_updated)` to be `true`, right? Doesn't it mean that `_ext_hdg_good` would be `true` only for max. `1/250 s` and then `false` until next `vision_updated`? 

diagram

**Comment by mhkabir** [comment]
> Doesn't it mean that `_ext_hdg_good` would be `true` only for max. `1/250 s` and then `false` until next `vision_updated`?

Yes and what is the problem with this? The update step happens in the same loop and the measurement in fused. You don't want the same measurement being fused multiple times.

**Comment by ArkadiuszNiemiec** [comment]
> > Doesn't it mean that `_ext_hdg_good` would be `true` only for max. `1/250 s` and then `false` until next `vision_updated`?
> 
> Yes and what is the problem with this? The update step happens in the same loop and the measurement in fused. You don't want the same measurement being fused multiple times.

Oh, ok. My assumptions were wrong:
https://github.com/PX4/Firmware/blob/f1d17c9003280498724211310c6e5601b1df44da/src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp#L589

I will test it tomorrow and make a new commit. Thanks.

**Comment by ArkadiuszNiemiec** [comment]
I have tested your solution and it's working but I was right: the convergence is very slow. I understand that we should not fuse the same value multiple times but this solution makes the external yaw value to be valid for only few ms and then to be ignored. The `corr` variable is redefined every iteration: https://github.com/PX4/Firmware/blob/d114a37d85cbfcbac0c17b42384b06658e3c67a6/src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp#L588.

I have prepared a test setup:
1. `ATT_W_EXT_HDG` set to `0.6`.
1. Test the convergence time of `ATTITUDE.yaw` to the value reported by external vision system. These values are 90 degrees off.
2. Turn off external vision system and rotate the autopilot 90 degree to the left and then 90 degree to the right to see if the bug reported by me is fixed.

Here are results (look at the `Yaw Angle`):
1. Current master: https://logs.px4.io/plot_app?log=eb150016-0a07-4127-af6e-dba089f57d1f
- yaw converged to -90 degree in around 5 seconds (from 0:16 to 0:21)
- you can clearly see the bug at around 0:38 where I rotate the autopilot +90 degree but it converges back to value of -60 degree
2. Solution proposed by @mhkabir: https://logs.px4.io/plot_app?log=f8f0ea97-6a1f-4cd2-90ad-9742f3a7c1d4
- yaw converged to +90 degree in around 34 seconds (from 0:14 to 0:48)
- the bug is fixed, the yaw value stays at the correct angle
3. My solution: https://logs.px4.io/plot_app?log=0192e0ea-4168-4602-91e4-9a6318012fc7
- yaw converged to +90 degree in around 4 seconds (from 0:10 to 0:14)
- the bug is fixed, the yaw value stays at the correct angle

Solution in which I initialize `_ext_hdg_good` to `false` every loop is unusable even with `ATT_W_EXT_HDG` set to `1.0`. We will stick to my branch for now.

**Comment by mhkabir** [comment]
You solution only converges faster because you're artifically increasing the "actual" weightage of the measurement by fusing the same (stale) one every iteration.

Increase `ATT_W_EXT_HDG` appropriately and you will see similar behavior with my proposal.

**Comment by ArkadiuszNiemiec** [comment]
Ok, I understand. Reverted my changes and committed a new one. I think that the `1.0` as the max value should be increased in QGroundControl or the weight should be scaled inside the PX4.

**Comment by ArkadiuszNiemiec** [comment]
Current version tested in flight with `ATT_W_EXT_HDG` set to `40`. Everything OK, thanks @mhkabir.

**Pull request merged**
