### PR TITLE
Muorb orb exists 2

### PR DESCRIPTION
**Pull request by mcharleb**
This adds support for orb_exists synchronization across the apps processor and the DSP on Eagle platform.  There is also a new builtin: wait_for_topic with will poll for the specified topic to be advertised before continuing. A timeout of 0 means wait forever.

### CODE REVIEW

**Comment by bkueng** [comment]
I think it would make sense to move `wait_for_topic` to systemcmds. And I would avoid using orb internal datastructures (`orb_metadata`), it can easily lead to bugs when either `orb_metadata` or `orb_exists` change. There is `orb_get_topics()`.

`orb_exists` also returns 0 if another subscriber already exists. I recently got surprised by that as well, see https://github.com/PX4/Firmware/pull/5307/commits/6e35cf00b7c5b218779cf89a27017553d7728fb9

**Comment by LorenzMeier** [comment]
Sounds like we should a call orb_published() (note that there is a call to get the last timestamp, orb_stat(), so it would be rather a convenience call).

**Comment by LorenzMeier** [comment]
@mcharleb Could you please resolve the CI fails? That might require a rebase on master.

**Comment by LorenzMeier** [comment]
Please rebase on master to fix CI.

**Comment by mcharleb** [comment]
Yes, I'll rebase.

**Comment by LorenzMeier** [comment]
Jenkins add to whitelist.

**Comment by LorenzMeier** [comment]
@mcharleb Can you rebase now?

**Comment by LorenzMeier** [comment]
@mcharleb Could you rebase this?

**Comment by mcharleb** [comment]
@LorenzMeier Yes, will do.

**Comment by mcharleb** [comment]
@LorenzMeier Rebased.

**Comment by julianoes** [comment]
I see CI complaining:
```
FAILED: /usr/lib/ccache/c++   -DBUILD_URI=localhost -DCONFIG_ARCH_BOARD_SITL -D__DF_LINUX -D__PX4_LINUX -D__PX4_POSIX -D__STDC_FORMAT_MACROS -Dnoreturn_function="__attribute__((noreturn))" -I. -Isrc -Isrc/modules -Isrc/modules/px4_messages -I../mavlink/include/mavlink -I../src -I../src/drivers/boards/sitl -I../src/include -I../src/lib -I../src/lib/DriverFramework/framework/include -I../src/modules -I../src/platforms -I../src/lib/matrix -I../src/modules/systemlib -I../src/lib/eigen -I../src/platforms/posix/include -Iexternal/Install/include -Isrc/firmware/posix -g -fno-exceptions -fno-rtti -std=gnu++0x -fno-threadsafe-statics -DCONFIG_WCHAR_BUILTIN -D__CUSTOM_FILE_IO__ -fcheck-new -Wall -Werror -Wextra -Wno-sign-compare -Wshadow -Wfloat-equal -Wpointer-arith -Wmissing-declarations -Wno-unused-parameter -Werror=format-security -Werror=array-bounds -Wfatal-errors -Werror=unused-variable -Werror=reorder -Werror=uninitialized -Werror=init-self -Werror=unused-but-set-variable -Wformat=1 -Wdouble-promotion -Werror=double-promotion -Wno-missing-field-initializers -fvisibility=hidden -include visibility.h -pthread -O2 -fno-strict-aliasing -fomit-frame-pointer -funsafe-math-optimizations -ffunction-sections -fdata-sections -fno-strength-reduce -fno-builtin-printf   -include visibility.h -O2 -fno-strict-aliasing -fomit-frame-pointer -funsafe-math-optimizations -ffunction-sections -fdata-sections -fno-strength-reduce -fno-builtin-printf -MMD -MT src/firmware/posix/CMakeFiles/px4.dir/apps.cpp.o -MF src/firmware/posix/CMakeFiles/px4.dir/apps.cpp.o.d -o src/firmware/posix/CMakeFiles/px4.dir/apps.cpp.o -c src/firmware/posix/apps.cpp
src/firmware/posix/apps.cpp: In function 'int wait_for_topic(int, char**)':
src/firmware/posix/apps.cpp:205:3: error: 'cout' was not declared in this scope
   cout << "Usage: wait_for_topic <topic> [timeout_sec]" << endl;
   ^
compilation terminated due to -Wfatal-errors.
```

**Comment by mcharleb** [comment]
@julianoes I'll change it to printf and try again.

**Comment by LorenzMeier** [comment]
@mcharleb still failing

**Comment by mcharleb** [comment]
@LorenzMeier I am testing the build for posix and qurt and they worked for me. I'll have a look.

**Pull request merged**
