### PR TITLE
Add configuration files for Zephyr sitl

### PR DESCRIPTION
**Pull request by hsu**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@hsu Nice! We're lagging on this a bit but will come back.

**Comment by LorenzMeier** [comment]
Please rebase on master to fix CI.

**Comment by hsu** [comment]
git rebase with my bad submodule changes along the way is beyond my git skills... so I reset the source branch with brand new commits.

**Comment by LorenzMeier** [comment]
Awesome, thanks! We're still lagging in the integration, but getting there.

**Comment by bkueng** [comment]
Thanks @hsu, I cherry-picked this into https://github.com/PX4/Firmware/pull/5389

**Pull request closed without merging**
