### PR TITLE
sitl_gazebo: update submodule

### LINKED ISSUE #11144: PX4 SITL mission tests intermittent failures
Examples
 - http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-11136/4/pipeline/
 - http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-11136/3/pipeline
 - http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/pr-lndmc-takeoff/1/pipeline

### PR DESCRIPTION
**Pull request by julianoes**
This should fix the CI failures where we intermittently saw SIGABRT.

Fixes #11144.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Ci failed.

**Comment by LorenzMeier** [comment]
Looks like a CI internal failure.

**Comment by julianoes** [comment]
DronecodeSDK CI fails because of "out of space".

**Comment by dagar** [comment]
CI should be working now.

**Comment by julianoes** [comment]
Jenkins: test this please!

**Pull request merged**
