### PR TITLE
CI: convert missions to QGC plan format

### PR DESCRIPTION
**Pull request by lamping7**
@dagar Do we want to modify/remove vtol_old_3? It was failing CI because the mission doesn't include landing, preventing the current sequence from resetting to 0. I've fixed how the end of the mission is detected, but now, because there is not another mission item, the vehicle begins to steer away from the WP, to loiter around it, causing a "yaw error mean" failure in the post mission check. What makes this mission different from the others is that it uses MAV_CMD_NAV_WAYPOINT to takeoff and goto the first WP.

### CODE REVIEW

**Comment by lamping7** [comment]
I added the mission descriptions here: https://github.com/PX4/Firmware/pull/8915

Also, If we can now assume that all missions will have a `.plan` file extension, I can remove the hack in the Jenkinsfile that renames the XML test result files.

**Comment by dagar** [comment]
Yes let's assume it's .plan only from this point on.

**Comment by lamping7** [comment]
If this looks good to you I'll squash it and we can continue to iterate over: https://github.com/PX4/Firmware/pull/8887, https://github.com/PX4/Firmware/pull/8799, and https://github.com/PX4/Firmware/pull/8915

**Comment by dagar** [comment]
Thanks, this is much better.

**Comment by dagar** [comment]
Thanks, this is much better.

**Pull request merged**
