### PR TITLE
implement MAV_CMD_NAV_LOITER_TO_ALT and general mission cleanup

### PR DESCRIPTION
**Pull request by dagar**
This PR implements MAV_CMD_NAV_LOITER_TO_ALT and has some general mavlink mission cleanup that I came across while implementing and testing.

The mavlink mission handling had some holes and was difficult to follow and extend so I refactored it to only handle what we actually implement. I can split that off into another PR if desired.

screenshot from 2016-07-05 17-17-38

QGC side: https://github.com/mavlink/qgroundcontrol/pull/3730

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looks good from sifting through it. But I need another pass to check line by line.

**Comment by dagar** [comment]
Some additional testing from other developers might be prudent here. I did a few tests of creating/loading/retrieving random missions and diffed what QGC received. I didn't test MC or VTOL.

**Comment by LorenzMeier** [comment]
@sanderux @tumbili Can you cross test here?

**Comment by dagar** [comment]
FYI I've been flying this SITL, HIL, and outside for the past week. Typical FW missions with takeoff, loiter, waypoint, jump, loiter_to_alt, land.

**Comment by LorenzMeier** [comment]
That changes things considerably. Let me have another pass.

**Comment by LorenzMeier** [comment]
Rebased and applied, thanks!

**Pull request closed without merging**
