### PR TITLE
Set EKF2 as default estimator

### PR DESCRIPTION
**Pull request by LorenzMeier**
This needs more discussion and coordination. But we need to focus our maintenance efforts and also discuss how we can pull the EKF and LPE estimator implementations closer together.

### CODE REVIEW

**Comment by jgoppert** [comment]
I'm looking forward to having all of our effort focused in one direction. Here are some things about LPE that I would like to see incorporated:

## Things to merge from LPE:

1. Chi-squared fault detection with beta lookup table so faults can be set based on false-alarm rate.
2. Measurements are modular and separated by source file.
3. To add a state or measurement to LPE once extends the state/measurement enum, the rest is handled automatically to resize the matrices and the jacobians are automatically updated since they are set sparsely by the  state enum. This allows anyone to modify the estimator. If we are going to rely on a symbolic jacobian calculation, I would like to see it done in something like sympy so it can be released publicly for use by people without a matlab license.

## Some things from EKF2 that I'm looking forward to

1. Replay logging support.
2. Attitude state covariance (since LPE uses attitude_estimator q).

## Some concerns about EKF2 that I would like to see addressed.

1. CPU load.
2. Transition from local navigation (using optical flow/ vision etc) to GPS navigation.
3. Does the cross covariance from the attitude states actually help with the state estimation. I would like to see a comparison because we are paying a lot to do that computation. Maybe a separate state/ attitude ekf is still better.
4. API bloat. We currently have to translate all calls from the px4 param server to the ECL api, see notes about ROS2 below.

## Long term plans

1. What is the long term goal for the project? I think eventually we will all be using ROS to do the estimation in some form when ROS2 is working. I think we should align with this to the best of our ability with this new combined estimator. I would like to see it very closely resemble a ros node with params accessed through a clean param interface etc. EKF2's goal was to use ECL to separate it from the environment, but I think it should be written for ROS2 in the future, so all of the ECL interface will get in the way.

**Comment by jgoppert** [comment]
I will test out EKF2 for my systems, if it works OK I think just switching to EKF2 default for now is best. We can worry about the long term goals later.

**Comment by jgoppert** [comment]
@LorenzMeier  In SITL I can't do a mission if I set (GPS false, vision_pos true, flow true). So some work is needed there before I could use ekf2. Hast anyone test flown these combinations?

**Comment by LorenzMeier** [comment]
@jgoppert I'll table this for now and coordinate with you first. My bad to not align in a call first.

**Comment by LorenzMeier** [comment]
Removed from 1.5.1 for now.

**Comment by LorenzMeier** [comment]
@jgoppert Moved your suggestions to a new issue for 1.6: https://github.com/PX4/Firmware/issues/5947

**Pull request closed without merging**
