### PR TITLE
Landing persistence

### PR DESCRIPTION
**Pull request by sanderux**
Added a parameter to enforce persistence of the landing state for x seconds.
Fixes https://github.com/PX4/Firmware/issues/6730

### CODE REVIEW

**Comment by Stifael** [comment]
@sanderux: this is not needed since there is a hysteresis used for booleans which is applied to groundcontact and landed state. Right now the landing state has to be true for about 2 seconds.

**Comment by Stifael** [comment]
Maybe I need to be more clear.: in order to enter the landing state, the criteria for landing has to be satisfied for about 2  seconds. This logic is done within the hysteresis

**Comment by sanderux** [comment]
The hysteresis is set to 1.5 secs from moving from !landed to landed
This is a constant value that is clearly too low for vtol's

What would be wrong with adding a user defined minimum time that the condition has to hold?

**Comment by Stifael** [comment]
In my opinion I prefer a value that works for all vehicles. If 1.5 seconds is too low, then I suggest to increase it to be on the conservative side. What we definitely not want is a mid-air land detection as you have experienced.

**Comment by LorenzMeier** [comment]
@Stifael I don't think the generic time exists. If you make it too long you kill usability for some platforms that don't require such a long hysteresis.

@sanderux Can you please use the hysteresis object instead? Here is how ground contact is done. You an do the same for landing.
https://github.com/PX4/Firmware/blob/57f546e2e06e3cec3df7c71ede958b4852cccc8d/src/modules/land_detector/LandDetector.cpp#L207

**Comment by Stifael** [comment]
@LorenzMeier. Landing already uses it.

**Comment by Stifael** [comment]
If you want to add param, then just substitute the constant value used within the landing hysteresis with a param.

**Comment by Stifael** [comment]
And if you add one for landing, then we also should add one for groundcontact

**Comment by Stifael** [comment]
I even think that a param for groundcontact would make more sense since that is entered before land detection.

**Comment by sanderux** [comment]
I think before we start making a lot of changes we should get clear on the problem and have a good think about how to solve it. The following illustrates the problem:
image

The sequence of the (autonomous) back transition is as follows:
1. Transition back to MC while gliding
2. Navigate as MC to the landing position (only if required)
3. Land

As we are tuning the back transition to perfection the following happens:
- The glide in back transition holds perfect altitude and makes sure it ends exactly above the landing spot.
- When well tuned it will have almost no more speed when comming out of back transition
- In order to hold altitude it holds the pitch angle ideal for FW so there will be a slight pitch up
- As a good practice we land against the wind, in combination with the pitch angle that could produce lift even without horizontal movement.

Given the above conditions the vehicle is;
- In landing mode
- Not moving in any direction (horizontal or vertical)
- For a few moments no thrust is required for the vehicle to hold altitude

The MC land detector is not built for this situation as this behavior is unlikely/impossible on a regular MC.

So that leaves us with a challenge where we need to make a few decisions;
1. Should MC and VTOL share a common land detector
2. Should more factors other then motion and thrust be factored in (e.g. current altitude or time spent actually landing)
3. Should the vehicle behave differently in case of a false positive from the land detector (aka not falling out of the sky). We could consider using the free-fall detector to verify our situation.

Perhaps @AndreasAntener @tumbili @dagar care to pitch in

**Comment by Stifael** [comment]
@sanderux
Would it be possible to apply mc landdetection once transition is finished or some time after successful transition? And for detection during transition, which probably does not occur very often I hope, the vtol needs to use a different logic.

**Comment by dagar** [comment]
What if the VTOL land detector simply wrapped both FW and MC detectors and switched between them?

**Comment by sanderux** [comment]
The issue is that at the danger point, transition has already finished and, for all intents and purposes, it is an MC trying to land. So there is no need for land detection during transition. The land detector only becomes active in step 3, at that point the vehicle is no longer in transition.

> ... or some time after successful transition

That's an option. But then the question is, how long after transition? Also during the decent it is possible for wind to come under the wings and provide lift. If that hits at just the right angle we would have the same problem as the danger zone

**Comment by dagar** [comment]
I understand now. I was going to suggest VTOL would extend MC and include airspeed, but that appears to already be the case, and obviously doesn't help you.

It sounds like VTOL without airspeed optionally needs a more conservative land detector, which you could achieve by parameterizing these - https://github.com/PX4/Firmware/blob/9c2dd48814a6ade179a734381e44f126ec7bea41/src/modules/land_detector/LandDetector.h#L142

**Comment by Stifael** [comment]
What about extending the transition state to the point when the vehicle becomes a true mc?

**Comment by sanderux** [comment]
@Stifael if you look closely at the image, it IS doing that.
The problem is that as soon as it considers itself a complete MC and starts landing it might still have lift. This problem is not only right after transition but remains throughout the entire landing procedure as lift could always be generated through wind.

**Comment by Stifael** [comment]
ok I had now finally my computer available to look at the log file. 
It turns out that you did not have a mid-air land detection, but rather ground contact was detected. 
vtol_land_mid-air (position in z was scaled). Land detection occurs at the end of the flight. 
Ground contact always happens before landdetection and only includes thrust and velocity as criteria for detection (https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/MulticopterLandDetector.cpp#L189-L190). It only needs to satisfy the criteria for 1s (https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/LandDetector.h#L145).
During groundcontact, the positioncontroller ignores thrust setpoint correction in the xy-body direction. Groudcontact was introduced as a prestate for the landing, since in the past the problem was mainly that landing was not detected at all due to attitude and position correction on ground.

**Comment by Stifael** [comment]
@sanderux: I looked at this log file: http://logs.uaventure.com/view/t293nDhydn76rU94mnoZRL

Is that file really the one with the mid-air landdection? becuase not even groundcontact will be met when looking at that log...

**Comment by sanderux** [comment]
@Stifael sorry, wrong log: http://logs.uaventure.com/view/qSiQiq3uZ2LzZ7FSGend8a

**Comment by LorenzMeier** [comment]
@sanderux Can you please use the hysteresis class?

**Comment by Stifael** [comment]
@sanderux  would you agree with @dagar to parametrize the time for landdetection? It would be a fix for now.

**Comment by sanderux** [comment]
Yes, i had it on my todolist

**Comment by dagar** [comment]
Reopen as a parameter for the existing land detector hysteresis.

**Pull request closed without merging**
