### PR TITLE
Firefly hovering mode

### PR DESCRIPTION
**Pull request by Austriker**
Corrected a condition preventing the autopilot to stay in a VTOL mode.
Changed the mixer configuration for the gears.

### CODE REVIEW

**Comment by kd0aij** [comment]
If manual_control_sp is the RC input, the difference between (aux1 >= 0) and (aux1 == 0) is "down in the noise" isn't it?

**Comment by LorenzMeier** [comment]
Thanks! If you look at your pull request you might want to start using rebase. I've applied all your changes via the last commits on master, so closing this PR.
https://help.github.com/articles/about-git-rebase/

**Comment by LorenzMeier** [comment]
@kd0aij Yes, thanks for noting. Roman said he would be adding a deadband. Keeking this PR open as a reminder.

**Comment by Austriker** [comment]
Ok thank you. I will use rebase next time.

**Pull request closed without merging**
