### PR TITLE
fix waypoint handling in position control

### LINKED ISSUE #3082: Line calculation for POSCTL, convergence north/south
@tumbili as discussed

I've observed this previously but didn't follow up on it (https://github.com/PX4/Firmware/issues/2299). When testing variations on runway takeoff we also used the same calculation to draw a line with current heading. It resulted in a wrong actual heading during takeoff:

screen shot 2015-10-21 at 08 47 56

The blue lines were calculated by the posctl method, the red line is were it actually should be. Note that both lines match for 90 degrees.

Example calculations (posctl method):
```
Origin: 47.389492,8.0317354

160:
Point behind:
47.389492 - cos(160degrees) * 100/1e6 = 47.3895859693
8.0317354 - sin(160degrees) * 100/1e6 = 8.03170119799

Point ahead:
47.389492 + cos(160degrees) * 3100/1e6 = 47.3865789529
8.0317354 + sin(160degrees) * 3100/1e6 = 8.03279566244

90:
Point behind:
47.389492 - cos(90degrees) * 100/1e6 = 47.389492
8.0317354 - sin(90degrees) * 100/1e6 = 8.0316354

Point ahead:
47.389492 + cos(90degrees) * 3100/1e6 = 47.389492
8.0317354 + sin(90degrees) * 3100/1e6 = 8.0348354
```

Solution:
The calculation we actually want can be found here (great circle distance): http://www.movable-type.co.uk/scripts/latlong.html (part "Destination point given distance and bearing from start point")

We can update posctl to do the following:
- calculate the 2 waypoints with bearing and constant distance (a few hundred m)
- before we reach it, calculate new actual bearing at the end of the line
- use the new bearing for the next pair of waypoints

### PR DESCRIPTION
**Pull request by tumbili**
This fixes waypoint handling for fw in position control.
Tested in SITL with jsbsim but needs further testing in simulation.

Fixes #3082

### CODE REVIEW

**Comment by tumbili** [comment]
@AndreasAntener Remember this one? :-)

**Comment by AndreasAntener** [comment]
Yes :) just completely forgot where it stands.. so the underlying calculations are working then. My phantom would be the perfect test because the course deviation from the old calculation always made it loose heading lock.

**Comment by tumbili** [comment]
@LorenzMeier What is the problem here?
```
Traceback (most recent call last):

  File "dsdl_compiler/libuavcan_dsdlc", line 59, in <module>

    from libuavcan_dsdl_compiler import run as dsdlc_run

  File "/home/travis/build/PX4/Firmware/src/modules/uavcan/libuavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 17, in <module>

    from uavcan import dsdl

ImportError: No module named uavcan
```

**Comment by LorenzMeier** [comment]
Git submodule init && update are missing.

**Comment by tumbili** [comment]
@LorenzMeier Tried this before, still the same issue.

**Comment by LorenzMeier** [comment]
Rebased, should build now

**Comment by tumbili** [comment]
Delta angle x bias with standard deviation envelope.

d_ang_bias

Baro innovation with standard deviation envelope.
baro_innovation

Mag innovations
mag_innovations

**Comment by LorenzMeier** [comment]
Rebased and applied, thanks!

**Comment by AndreasAntener** [comment]
POSCTL looked good on the FX-61 now: http://logs.uaventure.com/view/zd5io9Ar2VRDD5ALB8ZRDH :+1:

**Pull request closed without merging**
