### PR TITLE
WIP: Eclipse code analysis

### PR DESCRIPTION
**Pull request by kd0aij**
@dagar Would you take a look at this Eclipse project (including the .settings) and let me know if you find any symbols or methods which are actually unresolved? I've done a fair amount of inspection, and the only resolution issues I see are ambiguities: the editor often sees many candidates, but it seems the right one is always in the list.

I've added some variable inits and changed some destructors to virtual to eliminate all but 45 "unused declaration" warnings. Let me know if you see additional warnings or errors.

### CODE REVIEW

**Comment by kd0aij** [comment]
This Eclipse project was created using the latest version of Eclipse running on Ubuntu 15.04
Eclipse version: Mars Release (4.5.0)
CDT version: 8.7.0.201506070905

**Comment by dagar** [comment]
There's already a .cproject in master, but it hasn't made it to beta yet. Can you either reopen this PR on master or cherry-pick those changes into your branch first? Otherwise we're going to have a nasty merge later.

I'll also try your changes.

**Comment by kd0aij** [comment]
@dagar @AndreasAntener Sorry, I meant to ping Daniel, not Andreas on this.

All I'm trying to do here is determine whether the CDT indexer/code analyzer is working properly. I'll delete this branch and start over on master if we decide the code analysis is useful.

**Comment by kd0aij** [comment]
It seems that the "Show All" filter for the Problems tab doesn't discover/display errors/warnings until you open the offending source file. I'm still looking for a way to get a summary of the code analysis results.

**Comment by kd0aij** [comment]
To run a full code analysis, right-click on project in Project Explorer and select "Run C/C++ Code Analysis" (then wait a while) 
Showing over 900 warnings at 5% complete right now...

**Comment by dagar** [comment]
My goal was to make eclipse more useful than a plain text editor. Eg jumping around commander, etc and able to look most things up. If we truly wanted eclipse working perfectly it might be better to invest the time in moving to CMake, but that's a huge effort at this point.

Here's an abandoned attempt to move to CMake
https://github.com/PX4/Firmware/pull/1696

**Comment by TSC21** [comment]
>Here's an abandoned attempt to move to CMake
>#1696

It's not abandoned. It's wip. @jgoppert ping

**Comment by dagar** [comment]
I must be missing something here, because I'm getting vastly different
results. Still seeing thousands of errors after importing your project,
building, and running full code analysis.
When I pulled in my changes (mostly just important include paths) I got
much better results after a full compile. I'm really not sure what to do
here.

If you start with my changes in master and add your changes do we end up
with something that mostly works for both of us?

**Comment by kd0aij** [comment]
It looks like the CDT codan settings aren't specified in either .cproject or .settings
So we're not using the same parameters, and hence seeing different results.
I've been unable to find any metadata which reflects the workspace or project specific settings for "C/C++ General"/"Code Analysis" in either Luna or Mars. Worse, Mars is telling me "invalid settings" for that page. I've reverted to Luna since it doesn't complain about that, but still can't figure out where the settings are recorded.

**Comment by kd0aij** [comment]
Ran code analysis with the same codan settings (close to default, I think), with and without the extra include paths.
My result with Eclipse Luna was 28,567/793 errors/warnings with the includes and 46,217/862 without.
So the additional includes helped some, but I still see tens of thousands of errors and there must be some other major difference between my environment and @dagar 
On the plus side, I'm seeing the cdt.codan preferences file change in my .settings directory today, so I must have been confused on that last post. Will edit it to reduce confusion.

**Comment by dagar** [comment]
It's initiating the full compile within eclipse that fixes most of the rest
for me.

**Comment by kd0aij** [comment]
Unable to reproduce your results:
Just reran code analysis on master after distclean/make archives/clean/make px4fmu-v2_default and got over 10K errors. Repeating the compilation did not change the number of errors.

**Comment by dagar** [comment]
New CMake activity - https://github.com/jgoppert/Firmware/pull/24

With CMake we'll be able to generate a perfect Eclipse project.

    cmake -G"Eclipse CDT4 - Unix Makefiles"

**Comment by kd0aij** [comment]
That sounds very promising. I'm finding that some of the codan errors are correct, but in source files which aren't pulled in for a default build. But other "errors" seem to be due to having multiple definitions and others look like bugs in codan. Will be interesting to see what CMake generates for project settings.

**Comment by LorenzMeier** [comment]
Is this here still WIP?

**Comment by kd0aij** [comment]
replaced by https://github.com/kd0aij/Firmware/pull/3

**Pull request closed without merging**
