### PR TITLE
better description for caipirinha vtol mixer

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by julianoes** [comment]
I would also add a description about which pin is connected to what? Or is this somewhere else?

**Comment by LorenzMeier** [comment]
@tumbili Please add meta data like in here: https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/2106_albatross#L1-L21

**Comment by LorenzMeier** [comment]
Can you rebase on master?

**Comment by LorenzMeier** [comment]
I did apply the equivalent to master in a new commit without the type renaming, which would have killed the QGC system list.

**Pull request closed without merging**
