### PR TITLE
flight task failure catch

### PR DESCRIPTION
**Pull request by ChristophTobler**
The current failure catching doesn't work as the nav state doesn't change and the tasks will be switched every iteration -> vehicle drifts.
I used the vehicle command to let the commander know to switch tasks. Not sure if this will be needed in the long term solution but with the current implementation it's needed.

### CODE REVIEW

**Comment by ChristophTobler** [comment]
```
remote file operation failed: /tmp/jenkins/workspace/ile_pr-mpc_send_cmd_failure-6EUKRMYOAT4GYQBMGSRRKAW5DHSIBWK4VWSXC7KCNPQZMMK4IX6Q at hudson.remoting.Channel@5091720a:ec2_docker_slave (i-0f4609fcc1348a59d): java.nio.file.FileSystemException: /tmp/jenkins/workspace/ile_pr-mpc_send_cmd_failure-6EUKRMYOAT4GYQBMGSRRKAW5DHSIBWK4VWSXC7KCNPQZMMK4IX6Q: No space left on device
```
@dagar FYI

**Comment by dagar** [comment]
Jenkins should be fixed now.

**Comment by dagar** [comment]
What are the reasons for failure?

**Comment by ChristophTobler** [comment]
>What are the reasons for flighttask failure?

If a flight task is missing information (e.g. triplets are invalid, faulty radius or center for orbit, etc.) but also a bug could lead to a failure -> things commander doesn't know of

>How will a user know what's going on?

I guess we could add a mavlink msg like this one https://github.com/PX4/Firmware/pull/10237/files#diff-fc77c3ef569029d45764664c75d4b0c1R1109

**Comment by Stifael** [comment]
> If a flight task is missing information (e.g. triplets are invalid, faulty radius or center for orbit, etc.) but also a bug could lead to a failure -> things commander doesn't know of

You are only checking for navigation state position, altitude and stabilized. If triplets are not valid, the navigation state will remain in auto and the commander will not get notified that auto failed...

**Pull request merged**
