### PR TITLE
drivers/gps: fix segfault when parsing arguments

### PR DESCRIPTION
**Pull request by nicolaerosia**
running gps command without parameters results in segfault
due to illegal access to unallocated memory

Signed-off-by: Nicolae Rosia <nicolae.rosia@gmail.com>

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! Looks like the build test failed though.

**Comment by nicolaerosia** [comment]
Style problems. I'll get back later.

**Comment by nicolaerosia** [comment]
@LorenzMeier the failure is not related?

**Comment by LorenzMeier** [comment]
Applied, thanks!

**Pull request closed without merging**
