### PR TITLE
Change mavlink version for simulator

### PR DESCRIPTION
**Pull request by stmoon**
Hi,

I found that the mavlink version of simulator module was old.
So, I change the mavlink version for simulator (1.0 -> 2.0)

Thanks 

SungTae Moon

### CODE REVIEW

**Comment by dagar** [comment]
I'm wondering if we can drop the v1.0 submodule entirely. The only other uses are in the pwm_out_rc_in and snapdragon_rc_pwm drivers.

**Comment by TSC21** [comment]
Is this tested with the supported simulators? ie. jMAVSim and `sitl_gazebo`?

**Comment by LorenzMeier** [comment]
Now that jMAVSim is updated we can. The two Snapdragon drivers can probably be dropped since Snapdragon works natively now.

**Comment by LorenzMeier** [comment]
@julianoes Ok to drop the Snapdragon PWM bridge to Pixhawk?

**Comment by LorenzMeier** [comment]
@ChristophTobler Input from your side on Snapdragon?

**Comment by LorenzMeier** [comment]
Merging this as-is as the others can be done in a separate PR.

**Comment by dagar** [comment]
PR to fully remove mavlink v1.0.

**Pull request merged**
