### PR TITLE
Adding ntest for unit testing on NuttX

### PR DESCRIPTION
**Pull request by julianoes**
This brings the capability to run gtest tests on NuttX.

I looked at various ways to get the gtest tests onto NuttX/Pixhawks:

* Get the the C++ STL [libcxx](https://github.com/PX4/libcxx/) to run on NuttX and build gtest. I got this working but it's [quite messy](https://github.com/PX4/Firmware/compare/master...julianoes:pr-build-gtest-for-pixhawk-with-libcxx) and will need further work and discussions.
* Use another C++ testing framework such as [cpputest](https://github.com/cpputest/cpputest) or [catch2(https://github.com/catchorg/Catch2/blob/master/single_include/catch2/catch.hpp), however both seem to use the C++ STL like gtest.
* Use some C unit testing harness. I didn't find this too useful or exciting, so I skipped that.
* Replace the minimal functionality of gtest that we actually require. That's what I tried and called ntest.

Currently we support `ASSERT_EQ`, `EXPECT_EQ`, `ASSERT_TRUE`, `EXPECT_TRUE`, `ASSERT_FALSE`, `EXPECT_FALSE`.

The output looks like this for failures:

```
nsh> ntest all
[==========] Running 9 tests from 3 test cases.
[----------] 1 test from TakeoffTest
[ RUN      ] TakeoffTest.Initialization
/home/julianoes/src/Firmware/src/modules/mc_pos_control/Takeoff/TakeoffTest.cpp:47 Failure
Expected equality of these values:
 foo
   Which is: 42
 99
   Which is: 99
[  FAILED  ] TakeoffTest.Initialization
[----------] 1 test from TakeoffTest
[----------] 1 test from AttitudeControlTest
[ RUN      ] AttitudeControlTest.AllZeroCase
[       OK ] AttitudeControlTest.AllZeroCase
[----------] 1 test from AttitudeControlTest
[----------] 7 tests from Hysteresis
[ RUN      ] Hysteresis.TakeChangeBack
[       OK ] Hysteresis.TakeChangeBack
[ RUN      ] Hysteresis.ChangeAfterMultipleSets
[       OK ] Hysteresis.ChangeAfterMultipleSets
[ RUN      ] Hysteresis.HysteresisChanged
[       OK ] Hysteresis.HysteresisChanged
[ RUN      ] Hysteresis.ChangeAfterTime
[       OK ] Hysteresis.ChangeAfterTime
[ RUN      ] Hysteresis.Zero
[       OK ] Hysteresis.Zero
[ RUN      ] Hysteresis.InitTrue
[       OK ] Hysteresis.InitTrue
[ RUN      ] Hysteresis.InitFalse
/home/julianoes/src/Firmware/src/lib/hysteresis/HysteresisTest.cpp:54 Failure
Value of: hysteresis.get_state()
 Actual: false
Expected: true
[  FAILED  ] Hysteresis.InitFalse
[----------] 7 tests from Hysteresis
[==========] 9 tests from 3 test cases ran.
[  PASSED  ] 7 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] TakeoffTest.Initialization
[  FAILED  ] Hysteresis.InitFalse
```

And if successful:

```
nsh> ntest all
[==========] Running 9 tests from 3 test cases.
[----------] 1 test from TakeoffTest
[ RUN      ] TakeoffTest.Initialization
[       OK ] TakeoffTest.Initialization
[----------] 1 test from TakeoffTest
[----------] 1 test from AttitudeControlTest
[ RUN      ] AttitudeControlTest.AllZeroCase
[       OK ] AttitudeControlTest.AllZeroCase
[----------] 1 test from AttitudeControlTest
[----------] 7 tests from Hysteresis
[ RUN      ] Hysteresis.TakeChangeBack
[       OK ] Hysteresis.TakeChangeBack
[ RUN      ] Hysteresis.ChangeAfterMultipleSets
[       OK ] Hysteresis.ChangeAfterMultipleSets
[ RUN      ] Hysteresis.HysteresisChanged
[       OK ] Hysteresis.HysteresisChanged
[ RUN      ] Hysteresis.ChangeAfterTime
[       OK ] Hysteresis.ChangeAfterTime
[ RUN      ] Hysteresis.Zero
[       OK ] Hysteresis.Zero
[ RUN      ] Hysteresis.InitTrue
[       OK ] Hysteresis.InitTrue
[ RUN      ] Hysteresis.InitFalse
[       OK ] Hysteresis.InitFalse
[----------] 7 tests from Hysteresis
[==========] 9 tests from 3 test cases ran.
[  PASSED  ] 9 tests.

```

### CODE REVIEW

**Comment by julianoes** [comment]
Please review @dagar @bkueng.

**Comment by dagar** [comment]
This looks promising, I'd just like to see if we can do it without the linking and module ordering hacks.

**Comment by julianoes** [comment]
> This looks promising, I'd just like to see if we can do it without the linking and module ordering hacks.

Do you have an idea how? Otherwise this will probably rot here.

**Comment by dagar** [comment]
FYI @LukasWoodtli

**Comment by julianoes** [comment]
Note to myself: I should change this to have separate binaries and then list them at build time for the test script to run them using serial:
https://github.com/PX4/Firmware/blob/master/Tools/HIL/run_tests.py

**Comment by julianoes** [comment]
As discussed on the dev call we would rather want to use gtest using STL on NuttX in the future, closing.

**Pull request closed without merging**
