### PR TITLE
Added support for external shared libraries

### PR DESCRIPTION
**Pull request by mcharleb**
The FC_ADDON drivers are shared libraries that have PX4 wrappers.
The wrappers are built as modules which are static libraries and
cannot have shared library dependencies.

The shared libraries are required to resolve the symbols at runtime
and need to be linked with the libmainapp shared library.

Signed-off-by: Mark Charlebois <charlebm@gmail.com>

### CODE REVIEW

**Comment by mcharleb** [comment]
The corresponding wrapper driver changes are at https://github.com/ATLFlight/px4_legacy_driver_wrapper/commit/bbfedba307253825c6880a6a865fb6ee67062245

**Comment by mcharleb** [comment]
And this change: https://github.com/ATLFlight/px4_legacy_driver_wrapper/commit/f010e186f0902cf224cb9257b5aa0bf27e948164

**Comment by mcharleb** [comment]
@LorenzMeier Is there anything blocking this merge?

**Comment by LorenzMeier** [comment]
@mcharleb Yes, I'd like to have the DF integration resolved which Julian is testing with you on master.

**Comment by mcharleb** [comment]
@LorenzMeier px4_legacy_driver_wrapper is a temporary need for the SDFlight release until the binary drivers can be completely replaced with open source versions. At that point the px4_legacy_driver_wrapper will not be needed. The PX4 additions in the PR simply enable PX4 to define modules that have dependencies on external prebuilt libraries.

**Comment by mcharleb** [comment]
Would the name _module_prebuilt_shared_libraries_ be preferable and more informative than _module_shared_libraries_? If so I can make that change.

**Comment by LorenzMeier** [comment]
@julianoes Can you test-build this with our upstream config?

**Comment by mcharleb** [comment]
@julianoes Does Firmware/src/drivers/uart_esc replace the driver in the FC_ADDON? I have an updated branch rebased on upstream. I will close this PR and open the new branch. It enables the rc_receiver.

**Comment by mcharleb** [comment]
Closing. Rebased version is https://github.com/PX4/Firmware/pull/4453

**Pull request closed without merging**
