### PR TITLE
[WIP] Jenkins retry mac build failures to work around flaky infrastructure

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
This is kind of lame, but should work around the periodic annoyances of the mac build slaves.

**Comment by lamping7** [comment]
Do we want to delete the workspace in the retry block?

**Comment by dagar** [comment]
That's a good idea.

**Comment by dagar** [comment]
Now if only we had a real mac failure to test.

**Comment by dagar** [comment]
Looks like we can't delete the workspace because the failure is so early. We're failing at failing!

image

**Comment by dagar** [comment]
Need to drop `make distclean` from finally as well.

**Comment by lamping7** [comment]
Ha! Ok. There's a different way to do this.

**Comment by lamping7** [comment]
I don't think we can fix this in a pipeline easily... What is happening is described here: https://wiki.jenkins.io/display/JENKINS/Remoting+issue. The problem with the "retry" block is that the same agent is used and the job is essentially continued. This won't work because the state of the agent is still junk. What we need to do is stop the job on the agent completely before starting again. The workaround I see is aborting the job (this means all steps) and retrying the whole job (i.e. job 1 is canceled and job 2 starts, restarting the whole process of the compile job).

Error from the build you captured above:
```
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2675)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3150)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:859)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:355)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on dronecode-macmini failed. The channel is closing down or has closed down
```

**Comment by lamping7** [comment]
I'll like to see a log from the slave to see if we can fix the root issue.

**Comment by dagar** [comment]
Which log? We don't seem to have anything useful to go on during these failures.
http://ci.px4.io:8080/computer/dronecode-macmini/log

**Comment by lamping7** [comment]
Log on the slave itself.

```
Failure mode on the client: Collect slave node jenkins-*.out.log and jenkins-*.err.log. This is where stdout and stderr from a JNLP slaves go.
```

**Comment by LorenzMeier** [comment]
@thomasgubler Let's set up a Mac Mini in the office and see if we can build a proper "rack" to get this stable.

**Comment by lamping7** [comment]
How should we move forward here?
-  Have the TCP settings been configured properly on the mac slaves?: https://www.gnugk.org/keepalive.html
- This describes the remote working dir for logs on the slaves: https://github.com/jenkinsci/remoting/blob/master/docs/workDir.md and https://github.com/jenkinsci/remoting/blob/master/docs/logging.md
- Do we want to abort the job and restart it on a failure like this?

**Comment by dagar** [comment]
I'd like to make sure removing an ec2 slave ultimately results in its deletion ec2 side, but otherwise I think this is good to go.

**Comment by lamping7** [comment]
Yes... This needs more testing.

**Comment by lamping7** [comment]
Here's what this PR evolved to do:
- A separate job in Jenkins was created, `PX4_misc/check-slaves`, to evaluate the connection state of all the slaves. It does:
    1. Check connected status with Jenkins master
        - If this fails (i.e. not connected), it connects (with a timeout of 30 sec) and proceeds to 2. if connection is successful.
        - Slaves marked "temporarily offline", as you would set manually though the Jenkins interface, are skipped/ignored as they don't hurt the build.
        - If the slave is an ec2 slave, it is removed rather than trying to reconnect. Trying to reconnect was tested, and it fails, so it is better to remove it so Jenkins can provision another to speed up builds.
        - This means SSH slaves, such as the mac boxes, are triggered online if they went to sleep from being idle. Hopefully this will prevent any issues with bringing these slaves up, by connecting before we try to hammer it with builds.
    2. Fetch the environment from the slave
        - This ensures we can actually communicate both ways with the slave. Specifically, it makes sure the `PATH` env var on the slave is not null.
        - If this fails, the slave is disconnected, reconnected, and 2. repeats just once (if the reconnect succeeds). This will hopefully catch and resolve a funky communication state (such as those where one side isn't communicating, but the other believes to be connected).
- This new job can be triggered by other Jenkins jobs, set at the beginning of their Jenkinsfile.
- The original `retry` added in this PR was changed to only wrap the git checkout step, not the whole build.
    - This will catch issues dealing with messed up workspaces, which has shown to be another problem area.
    - A problem with this step will clear the workspace and try again (set to 3 ties).

Setting it up this way is the best way to handle the two failures we've been seeing with this infrastructure. Above when "failing at failing" we were attacking the connection problem with the fix for a workspace issue. I believe this will take care of both properly and independantly.

What I'd like to do still:
- [ ] Incorporate a check (into the `check-slaves` job) for remaining free disk space and clear out old workspaces if the space is below some threshold. 1GB? Thoughts on a number here? Because we're doing this we might as well automate another potential area for issues that we've had to deal with in the past (normally fixed manually).
- [ ] Check the state of ec2 slaves upon removal. What happens here? I.e. Why does Jenkins show them disconnected? Does AWS pull them offline first?

**Comment by lamping7** [comment]
I rebased this so we can re-evaluate. I assume there is some kind of control panel for monitoring the EC2 account. It would be great to watch this from both ends to confirm it works properly. The disk space doesn't seem to be the problem for now, so I've crossed that off. A separate PR can tackle that if necessary.

**Comment by dagar** [comment]
Let's give this a try. Merging on CI pass.

**Comment by dagar** [comment]
Actually, let's keep check-slaves out of this incase other people want to use the pipeline without our infrastructure. We could run check-slaves periodically on jenkins itself.

**Comment by lamping7** [comment]
We're doing this periodically through Jenkins instead.

**Pull request closed without merging**
