### PR TITLE
for multicopter landings make sure that the copter moves

### PR DESCRIPTION
**Pull request by tumbili**
to the landing waypoint first before the descending phase starts

Fixes https://github.com/PX4/Firmware/issues/3388

### CODE REVIEW

**Comment by tumbili** [comment]
@LorenzMeier @AndreasAntener This makes sure that the copter first moves to the landing waypoint before it starts to descend. For the approach it will used the altitude specified in the landing waypoint.
I'm not very sure if this is the correct altitude. What is the meaning of the landing waypoint altitude?

**Comment by sanderux** [comment]
From a user standpoint i would agree that the altitude in a land command would mean 'go here at this altitude and then land'. 0 altitude could be interpreted as 'keep current altitude'

**Comment by tumbili** [comment]
@sanderux Thanks for your feedback! Makes sense, I can add the logic for the zero case.

**Comment by AndreasAntener** [comment]
@sanderux @tumbili We should be careful with special cases that are not clearly documented/specified. It could as well be that 0 is a valid relative landing WP altitude if the target landing point is below home. Because the user always specifies the altitude for a normal WP I would just keep that behaviour consistent as Roman described.

**Comment by tumbili** [comment]
@AndreasAntener Yes, good argument.

**Comment by sanderux** [comment]
Yes, true. QGC (and most GCS i think) maintain the altitude of the last WP when planning a mission so it should not be needed.

**Comment by AndreasAntener** [comment]
Tested and working. But before the yaw setpoint changed back to what it had at home for the landing. We can probably take this because we need to have a look at yawing during missions anyway.

**Pull request closed without merging**
