### PR TITLE
boards: add px4_fmu-v4 and px4_fmu-v5 optimized (-O3) build variants

### PR DESCRIPTION
**Pull request by dagar**
This pull request adds optimized px4_fmu-v4 and px4_fmu-v5 builds that are compiled at O3 (both PX4 and Nuttx). I'm not suggesting we pursue increasing the default optimized level (Os), but this is interesting to identify potential areas for manual optimization and extremely high performance configurations (eg stm32f4 quadcopter with 4 kHz loops).

On an fmu-v4 cpu usage is lower by ~ 15%.

### CODE REVIEW

**Comment by dagar** [comment]
Large differences to investigate later.

```
ekf2: update: 13292 events, 5972223us elapsed, 449.31us avg, min 19us max 2064us 505.221us rms  <- px4_fmu-v4_default
ekf2: update: 22638 events, 5527731us elapsed, 244.18us avg, min 7us max 1324us 293.125us rms  <- px4_fmu-v4_optimized
```

**Comment by dagar** [comment]
The Matrix pseudo inverse is drastically faster (fmu-v4). FYI @jlecoeur @RomanBapst 

px4_fmu-v4_default
```
matrix 6x16 pseudo inverse (all non-zero columns): 1000 events, 439783us elapsed, 439.78us avg, min 439us max 440us 0.412us rms
matrix 6x16 pseudo inverse (4 non-zero columns): 1000 events, 320857us elapsed, 320.86us avg, min 262us max 440us 71.611us rms
```

px4_fmu-v4_optimized
```
matrix 6x16 pseudo inverse (all non-zero columns): 1000 events, 160613us elapsed, 160.61us avg, min 160us max 161us 0.487us rms
matrix 6x16 pseudo inverse (4 non-zero columns): 1000 events, 135430us elapsed, 135.43us avg, min 135us max 136us 0.495us rms
```

**Comment by LorenzMeier** [comment]
It might make sense to run Matrix -O3 and the rest -Os

**Comment by dagar** [comment]
> It might make sense to run Matrix -O3 and the rest -Os

It's a bit awkward as a header only library, but we can consider doing it with a pragma or more targeted optimization levels per module or even file.

**Pull request merged**
