### PR TITLE
rcS: update comment on mavlink for FMUv4

### PR DESCRIPTION
**Pull request by ChristophTobler**
Comment was a contradiction.

fixes https://github.com/PX4/Firmware/issues/8720

### CODE REVIEW

**Comment by ChristophTobler** [comment]
Just realized that it also says
```
# Start MAVLink on Wifi (ESP8266 port)
mavlink start -r 20000 -b 921600 -d /dev/ttyS0
```
and `/dev/ttyS0` should be debug according to https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rcS#L18

**Comment by bkueng** [comment]
Since the Pixracer does not have an IO, the port seems to be used for the ESP8266 instead. This comment should be updated as well then.

**Comment by ChristophTobler** [comment]
@bkueng But the Pixracer has a debug port. Or is that not the same?

**Comment by bkueng** [comment]
Yes, but it's not the same. On the Pixhawk there are 2 debug ports: an IO-DEBUG & an FMU-DEBUG.

**Pull request merged**
