### PR TITLE
Fixes #7313: Invalid setpoint yaw after takeoff

### LINKED ISSUE #7313: Invalid setpoint yaw after takeoff
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission_block.cpp#L528

I believe sp.yaw_valid should be set correctly in the MissionBlock::mission_item_to_position_setpoint according to (mission) item->yaw.
When yaw_valid is already true (in my case it was set when taking off using MAV_CMD_NAV_TAKEOFF) and mission_item_to_position_setpoint is called with mission item containing yaw=NAN (is happens whan take-off is finished: https://github.com/PX4/Firmware/blob/master/src/modules/navigator/takeoff.cpp#L95), the yaw remains set to NAN and the yaw_valid remains true. When I switch to offboard (without valid yaw set), NAN value from yaw propagates thru the control and causes invalidating attitude setpoint (most values are set to NAN). This leads to instant crash.

### PR DESCRIPTION
**Pull request by Seanmatthews**

### CODE REVIEW

**Comment by mhkabir** [comment]
Code style fail. Please run `make format`.

**Comment by Seanmatthews** [comment]
@mhkabir Are these new code style checks? `make format` gives me "ASTYLE_VER_REQUIRED: unbound variable". Given that I changed one line that involves an existing variable, I don't see how I introduced an inbound variable. Let me know how you generally fix these errors please.

**Comment by Seanmatthews** [comment]
> ../src/modules/navigator/mission_block.cpp:522:38: error: 'isnanf' was not declared in this scope
>      sp->yaw_valid = !isnanf(item->yaw);

**Comment by mhkabir** [comment]
> make format gives me "ASTYLE_VER_REQUIRED: unbound variable".

Looks like you don't have astyle installed. Install astyle 2.06 or newer. The warning is broken somehow though. @dagar any ideas?

> isnanf is linux-specific and causes trouble with a few of the integration testing services.

Yes, isnan is not usable from a code portability perspective. Please remove it and use `PX4_ISFINITE()` instead.

**Comment by mhkabir** [comment]
`astyle` to have formatted files way beyond the scope of this PR. What is your astyle version?

**Comment by mhkabir** [comment]
Yeah we should. Please use 2.06 : 
```
Kabirs-MacBook-Pro:Firmware kabir$ astyle --version
Artistic Style Version 2.06
```

**Comment by Seanmatthews** [comment]
It appears that 3.0 works as well, FYI.

**Comment by mhkabir** [comment]
Works, but the diff is horrible : https://github.com/PX4/Firmware/pull/7400/files

**Pull request closed without merging**
