### PR TITLE
Use Python 3 everywhere

### PR DESCRIPTION
**Pull request by julianoes**
Since Python 2 is retired in 4 months, we should move everything to 3.

Closes #12788.

@MaEtUgR do you mind checking appveyor? :smile:

### CODE REVIEW

**Comment by cclauss** [comment]
At least 6 Python 3 syntax errors to cleanup...
[flake8](http://flake8.pycqa.org) testing of https://github.com/PX4/Firmware on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./platforms/nuttx/Debug/Nuttx.py:394:6: F632 use ==/!= to compare str, bytes, and int literals
		if regs is 0:
     ^
./platforms/nuttx/Debug/Nuttx.py:419:14: F821 undefined name 'regmap'
		for reg in regmap:
             ^
./platforms/nuttx/Debug/Nuttx.py:420:24: F821 undefined name 'regmap'
			hex_addr= hex(int(a[regmap[reg]]))
                       ^
./platforms/nuttx/NuttX/tools/oldconfig.py:33:13: F821 undefined name 'raw_input'
    input = raw_input
            ^
./Tools/geotag_images_ulog.py:41:69: E999 SyntaxError: invalid syntax
    print "Usage: python geotag_images_ulog.py [logfile] [image dir]"
                                                                    ^
./Tools/fetch_file.py:85:19: E999 SyntaxError: invalid syntax
    print "Get %s:" % fn,
                  ^
./Tools/upload_log.py:43:15: F821 undefined name 'raw_input'
        ret = raw_input(ask_string)
              ^
./Tools/run-clang-tidy.py:57:57: E999 SyntaxError: invalid syntax
      print 'Error: could not find compilation database.'
                                                        ^
./Tools/px4moduledoc/srcparser.py:350:23: F821 undefined name 'reduce'
        getopt_args = reduce(lambda a, b: a + b[1], getopt_args, '').replace(':', '')
                      ^
./Tools/uorb_graph/create.py:521:36: E999 TabError: inconsistent use of tabs and spaces in indentation
	graph.render(file_name, view=False)
                                   ^
./integrationtests/python_src/px4_it/mavros/mavros_offboard_attctl_test.py:126:18: F821 undefined name 'xrange'
        for i in xrange(timeout * loop_freq):
                 ^
./integrationtests/python_src/px4_it/mavros/mavros_offboard_posctl_test.py:133:18: F821 undefined name 'xrange'
        for i in xrange(timeout * loop_freq):
                 ^
./integrationtests/python_src/px4_it/mavros/mavros_offboard_posctl_test.py:172:18: F821 undefined name 'xrange'
        for i in xrange(len(positions)):
                 ^
./integrationtests/python_src/px4_it/mavros/mavros_test_common.py:173:18: F821 undefined name 'xrange'
        for i in xrange(timeout * loop_freq):
                 ^
./integrationtests/python_src/px4_it/mavros/mavros_test_common.py:203:18: F821 undefined name 'xrange'
        for i in xrange(timeout * loop_freq):
                 ^
./integrationtests/python_src/px4_it/mavros/mavros_test_common.py:234:18: F821 undefined name 'xrange'
        for i in xrange(timeout * loop_freq):
                 ^
./integrationtests/python_src/px4_it/mavros/mavros_test_common.py:257:18: F821 undefined name 'xrange'
        for i in xrange(timeout * loop_freq):
                 ^
./integrationtests/python_src/px4_it/mavros/mavros_test_common.py:285:18: F821 undefined name 'xrange'
        for i in xrange(timeout * loop_freq):
                 ^
./integrationtests/python_src/px4_it/mavros/mavros_test_common.py:308:18: F821 undefined name 'xrange'
        for i in xrange(timeout * loop_freq):
                 ^
./integrationtests/python_src/px4_it/mavros/mavros_test_common.py:341:18: F821 undefined name 'xrange'
        for i in xrange(timeout * loop_freq):
                 ^
./integrationtests/python_src/px4_it/mavros/mavros_test_common.py:377:18: F821 undefined name 'xrange'
        for i in xrange(timeout * loop_freq):
                 ^
./integrationtests/python_src/px4_it/mavros/mission_test.py:190:18: F821 undefined name 'xrange'
        for i in xrange(timeout * loop_freq):
                 ^
./integrationtests/python_src/px4_it/dronekit/MissionCheck.py:61:18: E999 SyntaxError: invalid syntax
print "Connecting"
                 ^
./src/lib/parameters/px4params/markdownout.py:50:20: F632 use ==/!= to compare str, bytes, and int literals
                if long_desc is not '':
                   ^
./src/modules/mavlink/mavlink_tests/mavlink_ftp_test_data.py:2:26: E999 SyntaxError: invalid syntax
print 'Arguments: file - ' + sys.argv[1] + ', length - ' + sys.argv[2]
                         ^
./msg/tools/uorb_rtps_classifier.py:198:27: F821 undefined name 'errno'
            if e.errno == errno.ENOENT:
                          ^
./msg/tools/uorb_rtps_classifier.py:199:31: F821 undefined name 'errno'
                raise IOError(errno.ENOENT, os.strerror(
                              ^
./msg/tools/uorb_rtps_classifier.py:200:21: F821 undefined name 'errno'
                    errno.ENOENT), yaml_file)
                    ^
./msg/tools/uorb_to_ros_rtps_ids.py:79:23: F821 undefined name 'errno'
        if e.errno == errno.ENOENT:
                      ^
./msg/tools/uorb_to_ros_rtps_ids.py:80:27: F821 undefined name 'errno'
            raise IOError(errno.ENOENT, os.strerror(errno.ENOENT), file)
                          ^
./msg/tools/uorb_to_ros_rtps_ids.py:80:53: F821 undefined name 'errno'
            raise IOError(errno.ENOENT, os.strerror(errno.ENOENT), file)
                                                    ^
./msg/tools/uorb_to_ros_rtps_ids.py:97:20: F821 undefined name 'basestring'
                v, basestring) else v for k, v in dictionary.iteritems()}
                   ^
./msg/tools/uorb_to_ros_rtps_ids.py:129:23: F821 undefined name 'errno'
        if e.errno == errno.ENOENT:
                      ^
./msg/tools/uorb_to_ros_rtps_ids.py:130:27: F821 undefined name 'errno'
            raise IOError(errno.ENOENT, os.strerror(errno.ENOENT), file)
                          ^
./msg/tools/uorb_to_ros_rtps_ids.py:130:53: F821 undefined name 'errno'
            raise IOError(errno.ENOENT, os.strerror(errno.ENOENT), file)
                                                    ^
./msg/tools/generate_microRTPS_bridge.py:246:25: F821 undefined name 'raw_input'
        _continue = str(raw_input("\nFiles in " + agent_out_dir +
                        ^
./msg/tools/generate_microRTPS_bridge.py:256:25: F821 undefined name 'raw_input'
        _continue = str(raw_input(
                        ^
6     E999 SyntaxError: invalid syntax
2     F632 use ==/!= to compare str, bytes, and int literals
29    F821 undefined name 'reduce'
37
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by lamping7** [comment]
The current linting for the stuff I've touched with testing was done with _yapf_. We've never created a standard here for linting in python as we have with astyle. Some of these things are part of the ROS integration tests which will stay at 2.7. This explains the `xrange` issues too. The print statement should be functions (`from __future__ import print_function`) and other similar issues.

**Comment by cclauss** [comment]
1. The conflicts should be fixed.
2. It is not best practice to solve all Python 3 compatibility issues is a single pull request (unless the codebase is trivial) so if these changes do not break Python 2 compatibility and improve Python 3 compatibility then they should be reviewed favorably and landed.  75 days until Python 2 end of life.

**Comment by lamping7** [comment]
@cclauss Can you open an issue with your comments here. I don't think they fall in line with what the purpose of this PR was -- python 3 for the build process -- and I don't want to drag it down.

**Comment by cclauss** [comment]
Agreed.  Conflicts must be resolved and tests must pass.

**Comment by TSC21** [comment]
I am not sure what's happening but I am totally confident that `jinja2` is installed on the containers: http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2Fcontainers/detail/master/150/pipeline#step-32-log-724

**Comment by cclauss** [comment]
In several of these files we need to make the same text change numerous times.  Would it be possible instead to define a variable that can be reused multiple times so that future modifications are simpler to make and to review?

**Comment by TSC21** [comment]
> In several of these files we need to make the same text change numerous times. Would it be possible instead to define a variable that can be reused multiple times so that future modifications are simpler to make and to review?

Are you referring to the container tags? The thing about it is that it's not mandatory that we update all the containers tag at the same time. There could even be situations where that doesn't happen.

**Comment by cclauss** [comment]
> I am totally confident that jinja2 is installed on the containers
__pip2 install Jinja2__ makes enables that module for Python 2 but not for Python 3.
__pip3 install Jinja2__ makes enables that module for Python 3 but not for Python 2.

**Comment by TSC21** [comment]
> > I am totally confident that jinja2 is installed on the containers
> > **pip2 install Jinja2** makes enables that module for Python 2 but not for Python 3.
> > **pip3 install Jinja2** makes enables that module for Python 3 but not for Python 2.

@cclauss what's your point here? The containers were updated: https://github.com/PX4/containers/blob/master/docker/Dockerfile_base-bionic#L60-L63

**Comment by TSC21** [comment]
> > > I am totally confident that jinja2 is installed on the containers
> > > **pip2 install Jinja2** makes enables that module for Python 2 but not for Python 3.
> > > **pip3 install Jinja2** makes enables that module for Python 3 but not for Python 2.
> 
> @cclauss what's your point here? The containers were updated: https://github.com/PX4/containers/blob/master/docker/Dockerfile_base-bionic#L60-L63

Looks like we missed Python3 in the first place: https://github.com/PX4/containers/pull/211/files

**Comment by MaEtUgR** [comment]
@julianoes Good call. Well I never checked anything Python 3 for the Windows toolchain because at the time it was completely unsupported by the build. Now I could change the toolchain installation procedure to only include 3.

**Comment by TSC21** [comment]
@julianoes we have a major issue here: `genmsg` and `gencpp` seem to use Python 2 instead of Python 3. We need to update our fork on those as well.

**Comment by TSC21** [comment]
Actually, we have already Python 3 compatibility added here: https://github.com/PX4/genmsg/pull/1/commits/1ad8e136cd6311c6af12256fc39362334ca23988. This just needs to get it and we should update both `genmsg` and `gencpp` modules.

**Comment by MaEtUgR** [comment]
@julianoes I found the necessary Cygwin toolchain changes locally. I can create a pr on the toolchain repository and let CI generate a new toolchain installer soon. I'm assuming that I need to keep backward compatibility and leave python 2 working like before as well.

**Comment by MaEtUgR** [comment]
I
- adjusted the Cygwin Toolchain according to my findings: https://github.com/PX4/windows-toolchain/commit/5f60b57ad7ce2dad46b9f84e3f198fe654e2922c
- made a new installer version 0.7: https://github.com/PX4/windows-toolchain/releases/tag/v0.7
- rebased this pr on master such that appveyor builds the merge again without conflict
- added a commit for appveyor to use that new toolcahain version: https://github.com/PX4/Firmware/pull/12809/commits/04422952a4f4431e2279cdb59aba2ee9b0701db0

@julianoes I would say the Windows Toolchain/CI is ready (first) 😉

**Comment by julianoes** [comment]
This has been replaced by #13572 and #13949, closing.

**Pull request closed without merging**
