### PR TITLE
update matrix and fix test_matrix

### PR DESCRIPTION
**Pull request by dagar**
For https://github.com/PX4/Firmware/pull/6513

### CODE REVIEW

**Comment by jgoppert** [comment]
@dagar thanks for doing this

**Comment by dagar** [comment]
@jgoppert can you look at the semaphore failure when you have a minute? We need an include for PX4_ISFINITE, but I'm not sure how you'd want to handle it on the matrix side?
The only we'd need to handle is using the builtin for qurt - https://github.com/PX4/Firmware/blob/master/src/platforms/px4_defines.h#L185

**Comment by jgoppert** [comment]
There are already some ugly #defines in the matrix header, so we can add the include there.

**Comment by dagar** [comment]
Matrix update for QuRT merged. Rebased with latest submodule.

**Comment by dagar** [comment]
@jgoppert merge if ready. Test change is trivial, but just wanted to double check with you that updating to the latest Matrix is safe.

**Comment by jgoppert** [comment]
Yes, matrix master should be fine.

**Pull request merged**
