### PR TITLE
Fixes for sitl gazebo ground truth.

### PR DESCRIPTION
**Pull request by jgoppert**
This fixes some errors in ground truth recording and also updates sitl gazebo to fix ground truth frame issues there. This is towards closing #5931.

### CODE REVIEW

**Comment by jgoppert** [comment]
@bkueng @LorenzMeier please review.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by LorenzMeier** [comment]
Jenkins test this please

**Comment by LorenzMeier** [comment]
Please rebase, thanks!

**Pull request merged**
