### PR TITLE
Flow est default apps

### PR DESCRIPTION
**Pull request by jgoppert**
The flow position estimator is very useful indoors and warrants being a default app in  my opinion.

### CODE REVIEW

**Comment by mhkabir** [comment]
@jgoppert What's wrong in using inav? What'd be the use case for this?

**Comment by jgoppert** [comment]
My use case: Indoor highly accurate dead-reckoning with optical flow for local waypoints sent via mavros. I've been flight-testing a sky-hero and dji f450 everyday for the past week.

Position Estimator INAV:
* Altitude: Accel/ Baro/ Sonar fused (Attempted surface detection). Significant drifts of several meters in baro altitude observed. Accel prediction not helpful near ground, doesn't trust sonar enough.
* Poor launch detection logic, flow starts estimating even when landed

Flow Position Estimator:
* Altitude: Sonar only, no significant altitude drifts observed
* Flow seems more accurate, since flow is my main x,y sensor, the logic in position estimator inav to adjust the weighting seems to hurt more than help.

Here are pictures to justify my claims, both taken just now with the exact same vehicle, tracing the exact same 1.5 m x 2 m patterned rug several times at 2 m and several times at 1 m with high powered halogen work lights. I've found that lighting is also crucial. These were taken by walking the drone. I will be doing some more flight tests in position hold tomorrow and will try to share some results.

With Flow Position Estimator:
flow_pos_est_alt
flow-pos-est

With Position Estimator INAV:
inav-alt
Notice the altitude is horrible.

inav
Notice the significant drift when the floor is less in focus at the lower altitude.

**Comment by LorenzMeier** [comment]
Interesting. Note that the 22 state att-pos EKF also supports flow and might be the perfect compromise long term.

**Comment by mhkabir** [comment]
I also noticed similar behaviour with inav before switching to the offboard EKF. Never pursued it though.

**Pull request merged**
