### PR TITLE
FW position controller: move from global to local position

### PR DESCRIPTION
**Pull request by sfuhrer**
With this PR the fixed-wing position controller is changed to consume local instead of global position updates wherever possible (global position is still required for lat/long estimation feedback and thus for lateral position control). It thus enables the use of the altitude control flight mode for fixed-wing/VTOL systems that don't have a GPS sensor, or the GPS fails (thus eg fixes https://github.com/PX4/Firmware/issues/14243). 

**Describe problem solved by this pull request**
Have a working fw altitude controller without global pos updates.

**Describe your solution**
Move subscription of fw pos controller from global to local pos where possible.

**Test data / coverage**
Sitl tested with a VTOL and plane.

**Additional context**
All credits to @dagar for initializing and implementing this!

### CODE REVIEW

**Comment by sfuhrer** [comment]
I've done a first test flight with it, no differences noted while flying (with GPS) in altitude and position controlled modes.  https://review.px4.io/plot_app?log=d9e52168-b126-4b33-8321-a7644018a891

@PX4/testflights could you fly this PR on a VTOL and/or fixed-wing vehicle? There isn't something in particular to test, it should just handle the same as before (assuming you have a GPS receiver on the vehicle). So fly it in altitude, position and mission mode, while doing transitions (if it's a VTOL) or auto-starts /-landings (if it's a fixed-wing). 
Please also do a flight in altitude flight mode with GPS disabled (you can do that by deselecting GSP fusion in the  EKF_AID_MASK parameter).

**Comment by mrpollo** [comment]
TODO: figure out CI testing.

**Comment by dannyfpv** [comment]
tested on pixhawk1 v3 fixed wing
take off: no issues
mission: no issues
stabilize: no issues

pr log:
https://review.px4.io/plot_app?log=c08f8847-5700-4707-839f-0200ee2048ca

pr no gps log:
https://review.px4.io/plot_app?log=430276da-de86-4380-b7b6-d66c59a2af49

**Comment by sfuhrer** [comment]
Thanks a lot @dannyfpv for the testflights. For me the logs look good, the throttle drop when in headwind is expected to control airspeed. 
I've squashed and rebased, and then did some thorough sitl testing with VTOL, plane and plane_catapult. No differences to master noted (expect that you can now fly in Alt mode without GPS fusion, as the testing team also showed on the real vehicle. 
@dagar @bresch a review from one of you would be nice, maybe you see something that didn't surface functionality-wise.

**Pull request merged**
