### PR TITLE
sitl_gazebo: updated submodule

### PR DESCRIPTION
**Pull request by julianoes**
This includes the new basic camera control.

https://github.com/PX4/sitl_gazebo/pull/181

### CODE REVIEW

**Comment by julianoes** [comment]
Needs a compile fix:
```
/home/julianoes/src/Firmware/Tools/sitl_gazebo/src/gazebo_geotagged_images_plugin.cpp: In member function ‘void gazebo::GeotaggedImagesPlugin::_send_capture_status(sockaddr*)’:
/home/julianoes/src/Firmware/Tools/sitl_gazebo/src/gazebo_geotagged_images_plugin.cpp:569:20: error: expected initializer before ‘==’ token
     float interval == CAPTURE_ELAPSED ? (float)_captureInterval : 0.0f;
                    ^~
/home/julianoes/src/Firmware/Tools/sitl_gazebo/src/gazebo_geotagged_images_plugin.cpp:584:9: error: ‘interval’ was not declared in this scope
         interval,                               // image interval
         ^~~~~~~~
/home/julianoes/src/Firmware/Tools/sitl_gazebo/src/gazebo_geotagged_images_plugin.cpp:584:9: note: suggested alternative: ‘itimerval’
         interval,                               // image interval
         ^~~~~~~~
         itimerval
```

**Comment by TSC21** [comment]
Shouldn't this be caught on sitl_gazebo CI?

**Comment by julianoes** [comment]
@TSC21 should have but didn't:
https://travis-ci.org/PX4/sitl_gazebo/builds/343296263#L667-L672

I'll fix the error and CI.

**Comment by TSC21** [comment]
He caught the error but returned good. Strange. @dagar any idea why this may happen?

**Comment by julianoes** [comment]
@TSC21 https://github.com/PX4/sitl_gazebo/pull/185

**Comment by dagar** [comment]
Enable warnings as errors (-Werror). 
image

**Pull request merged**
