### PR TITLE
Fixes to log download

### PR DESCRIPTION
**Pull request by dogmaphobic**
Added code to delete those "msgs_*" files in addition to log files when a *Delete All Logs* command is received.

Changed the burst count to a number of bytes instead of a number of packets. It's currently set to an arbitrary count of 64k in one go. The reason was simply to make it consistent between log listing and log data and it the assumption that eventually the log data packet (payload) would increase (for performance reasons) making the "packet count" rather meaningless.

With all that said, performance is still abysmal, which I can only assume is a result of the minute payload size, which is currently set to 90 bytes. Even when I set the max count to 1M, the code sits in `MavlinkStream::send()` sending packets non stop. That would suggest the bottleneck is the number of (tiny) packets.

### CODE REVIEW

**Comment by dogmaphobic** [comment]
```
ERROR: Timeout after 10 minutes
FATAL: Command "git submodule update --init --recursive" returned status code 143:
```
I assume this is CI being messed up?

**Comment by AndreasAntener** [comment]
Not sure yet why this happens lately..
Jenkins test this please

**Comment by AndreasAntener** [comment]
Jenkins test this please

**Comment by bkueng** [comment]
@dogmaphobic this contains a huge diff with tabs -> spaces replacement, which is wrong. Can you create a new PR with tabs only? I know, it's an annoyance when switching between QGC and FW code.

**Comment by dogmaphobic** [comment]
> I know, it's an annoyance when switching between QGC and FW code.

I (obviously) noticed it :) I assumed the original file had the problem. Why the discrepancy between QGC and FW? Couldn't it be made consistent?

**Comment by bkueng** [comment]
I guess for historic reasons. And once you have a large project, you don't want to change this anymore.

**Pull request merged**
