### PR TITLE
Added support for TFmini-LiDAR

### PR DESCRIPTION
**Pull request by LorenzMeier**
Rebased version of https://github.com/PX4/Firmware/pull/8537

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@ayushgaud Could you please test the autostart (last commit)?

**Comment by dagar** [comment]
I deleted the old IOCTLs that were removed from master recently, but otherwise looks fine. I would prefer if we stopped putting the class declaration in the cpp file thought.

I don't have this hardware to actually test.

The hard coded serial port is a problem for other boards, but we don't have a good solution for that at the moment.

```C
#define TFMINI_DEFAULT_PORT		"/dev/ttyS6"
```

**Comment by ayushgaud** [comment]
@LorenzMeier Tested 3e8e85b commit. Autostart working correctly.

**Comment by hamishwillee** [comment]
It is a good habit to update our docs whenever you add new hardware - or at least create an issue in the user guide.

A new rangefinder results in an update to [PX4 User Guide > Rangefinders](https://docs.px4.io/en/sensor/rangefinders.html). I have crated this as https://github.com/PX4/px4_user_guide/pull/124

**Pull request merged**
