### PR TITLE
EKF2: Add support for external vision observations

### PR DESCRIPTION
**Pull request by priseborough**
Replaces https://github.com/PX4/Firmware/pull/4382

Required for https://github.com/PX4/ecl/pull/153 - see that PR for test results.

Has been rebased and commits consolidated. See https://github.com/PX4/Firmware/pull/4382 and https://github.com/PX4/ecl/issues/141 for reference.

No further work required.

### CODE REVIEW

**Comment by priseborough** [comment]
rebased

**Comment by priseborough** [comment]
@devbharat did you want to give this a test on your set-up or are you happy for us to merge it based on the test results from PX4/ecl#153 ?

**Comment by devbharat** [comment]
I am happy to merge since already tested on the ev logs (even though not mine). My setup is almost ready again and I'll test the PR myself, and if their are addition issues they can be tracked over it.

**Comment by priseborough** [comment]
@julianoes can we get this pulled in?

**Comment by julianoes** [comment]
@priseborough I have no idea, sorry. Should I review it?

**Comment by priseborough** [comment]
@julianoes yes please - it has been tested, but rebased a couple of times since.

**Comment by LorenzMeier** [comment]
Reviewed, rebased and applied, thanks!

**Pull request closed without merging**
