### PR TITLE
Reduce USART1 tx buffer by 8 bytes to fix aligment issue

### PR DESCRIPTION
**Pull request by davids5**
The recent changes to the timers increased memory by 8 bytes.
   and should have ONLY added 8 bytes
   was  20000dc0	40	20000E00
   is:  20000dc8	40	20000E08
   s/b  20000E08       1f3      next symbol

   But for some unknown reason the linker skipped to the next alignment
   of 256 and wasted 246 bytes.

   20000F00     1f3     next symbol

   Even with .align 8 in the .S file and . = ALIGN(4); in the linker
   script I could not move the allocation back only up to the next
   512 alighment.

   So this is a hack to shift things back 8 bytes.

### CODE REVIEW

**Comment by davids5** [comment]
FFR:The PX4IO ran out of memory - you will be able to tell if this happens. Instead of the Blue LED Blinking and the Orange LED Solid - you will see The Blue and  Orange LED alternating - this indicates the PX4IO is out of memory.

**Comment by mhkabir** [comment]
@davids5 Tested on v4pro. PX4IO functions again, but I get low stack warnings.

**Comment by davids5** [comment]
Is that after the firmware download only or on every reboot?

**Comment by mhkabir** [comment]
Not on every reboot, it's intermittent.

**Pull request merged**
