### PR TITLE
Improve commander status

### PR DESCRIPTION
**Pull request by stmoon**
The print_status() in commander  is very useful when checking the status.

However, I found some item was represented just as number which cannot understand directly.
So I change the number to text. 

In addition, I think there is an unnecessary subscription in print_status(). so I remove it.

Thanks

SungTae Moon

### CODE REVIEW

**Comment by dagar** [comment]
I believe we had this before, but it was dropped to save space.

**Comment by stmoon** [comment]
Hi, @dagar 

Good advice!! I will check it.
Nevertheless, I think the string is useful for newbie like me if the left space is possible.

So, could you tell me how I can check the left space?  (the STACK_MAX of commander is 2450)
I think I can reduce the used space for that, if you want.

Thanks

SungTae Moon

**Comment by stmoon** [comment]
Hi @dagar 

I tested it with fmu_v2 and fmu_v3. 

When I compile and upload  fmu_v2, the overflow happen because of memory space problem. (+ 240 byte)
So I decide to remove the string name again and just optimize the print_status().
As a result, I can reduce the memory space in case of fmu_v3  (-14 byte)
from
```
Loaded firmware for 9,0, size: 1488629 bytes, waiting for the bootloader...
```
to
```
Loaded firmware for 9,0, size: 1488605 bytes, waiting for the bootloader...
```

Would you know how to compile it separately using #ifdef ? 
You know , current px4 hardware is enough to use it. 
So If it is possible, I want to compile it separately.

Thanks. 

SungTae Moon

**Comment by dagar** [comment]
We should keep board specific defines out of the main modules.

**Comment by stmoon** [comment]
Hi @dagar,

Yes, you're right. 
So I removed the extra codes and just improved the print_status().

**Comment by dagar** [comment]
Could you reuse the strings that are already here? https://github.com/PX4/Firmware/blob/master/src/modules/commander/state_machine_helper.cpp#L96

**Comment by stmoon** [comment]
Hi @dagar 

great idea!! I miss it.

I will use it. Thanks..

**Comment by stmoon** [comment]
Hi @dagar ,

Based on your advice, I modified the codes.

Please check it.

Thanks

SungTae Moon

**Comment by dagar** [comment]
Thank you!

**Pull request merged**
