### PR TITLE
Add dynamic modules on Posix.

### PR DESCRIPTION
**Pull request by m-ou-se**
You can now add `DYNAMIC` as an option to `px4_add_module`, which will
cause that module to no longer be compiled into the px4 executable, but
instead produce a separate shared library file, which can be loaded and
executed with the new `dyn` command:

    pxh> dyn ./hello.px4mod start

This will load the shared object file `hello.px4mod` if it wasn't
already loaded, and execute its main function with the given arguments.

### CODE REVIEW

**Comment by dagar** [comment]
Somewhat relevant - external applications on NuttX. https://www.youtube.com/watch?v=oL6KAgkTb8M

**Comment by m-ou-se** [comment]
`systemcmds/dyn` should work as is on NuttX by the way, but I have not tested it. The `DYNAMIC` option of `px4_add_module` needs to be extended a bit to work for NuttX as well, but I have no working NuttX system running here to test anything.

**Comment by dagar** [comment]
Did you consider adding it to the list of existing apps and then interacting with it normally?
https://github.com/PX4/Firmware/blob/master/src/platforms/apps.h.in


    pxh> dyn ./hello.px4mod
    pxh> hello start

**Comment by m-ou-se** [comment]
@dagar Yes, but then I realized that doesn't change anything for the `dyn` command: The loaded module should just call `add_app(...)` or something from its `px4_module_main` function (which is run by `dyn`). It's then up to the module to add as many commands as it wants and do whatever it likes when it is loaded by the `dyn` command.

**Comment by m-ou-se** [comment]
Of course, the `dyn` command could also do that for the module, but letting the module do it itself makes it a bit more flexiple. The module could then also register multiple command names, display a message, start or load dependencies, perform some checks before registering commands, etc. etc.

**Comment by dagar** [comment]
Thanks for the explanation. I could see going in a few different directions with this idea, but for right now my only request is that you add a simple test that runs in the CI system. These neat little side features can end up breaking inadvertently.

**Comment by m-ou-se** [comment]
@dagar I could use some help with that. Right now Ihave no idea how the CI system works and what it runs. I can add a 'dyn-hello' dynamic module on Posix to test with `dyn`, and then the Posix CI run will need to run `dyn ./dyn-hello.px4mod` in its test init script or something.

**Comment by hamishwillee** [comment]
> Looks like there's more to update in that document. The part on the client/daemon FIFOs is no longer true. Will send a PR to that repository when I find the time.

Thanks! https://github.com/PX4/Devguide/issues/656 created for tracking. Do you think I could get an ETA on when to try nag you for this? So very easy for documentation to get out of sync.

**Comment by dagar** [comment]
@m-ou-se as a start you could ignore CI and just think about a simple test that would live in the repo. How would you build it, how would you run it, and how would you determine success?

From there we could either add it as a simple standalone job in the main Jenkins pipeline (http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/detail/master/372/pipeline - https://github.com/PX4/Firmware/blob/master/Jenkinsfile), or see if it will fit with the other SITL tests (http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/master/377/pipeline - https://github.com/PX4/Firmware/blob/master/.ci/Jenkinsfile-SITL_tests).

**Comment by m-ou-se** [comment]
@dagar Ah perfect, those were the things I was looking for. Will probably work on it tomorrow.

**Comment by m-ou-se** [comment]
I've added a test.

Now working on getting it it to pass on Cygwin and Mac. Shared libraries work differently on Linux, Cygwin, and Mac. (And I only have a Linux box here to test things locally.)

**Comment by m-ou-se** [comment]
Seems to work now on mac :tada:

Cygwin might be tricky, as Windows shared libraries (DLL files, or more specifically the PE format) don't allow undefined symbols. Since the modules need to refer to symbols inside the `px4` executable, the modules will need to link against an import library based generated alongside that executable.

**Comment by m-ou-se** [comment]
Looks like that worked! :tada:

Cygwin:

    ...
     [701/701] Linking CXX shared library platforms__posix__tests__dyn_hello.px4mod
    ...
          Start 31: dyn
    31/35 Test #31: dyn ..............................   Passed    0.26 sec
    ...

**Pull request merged**
