### PR TITLE
Wind & airspeed scale estimator

### PR DESCRIPTION
**Pull request by LorenzMeier**
@priseborough It would be great if you could comment on the merit of a standalone estimator. Could scale be also added to ECL easily?

### CODE REVIEW

**Comment by priseborough** [comment]
We could add an additional state, but I'm in favour of leaving this as a standalone calibration tool due to the impact of adding states to the main estimator in terms of resource utilisation. It is not something that would be left running all the time as the scale factor is mainly a function of the pitot static probe location  after density corrections have been performed.

**Comment by priseborough** [comment]
I'll check this out and rebase it. It will be required to take advantage of the accuracy we get from https://github.com/PX4/Firmware/pull/7702

**Comment by LorenzMeier** [comment]
@priseborough I suggest to do this:

```
git fetch upstream
git checkout upstream/master -b pr-wind-estimator
git merge --squash tumbili-wind_estimator
```

That will still yield conflicts, but on a more manageable scale.

**Comment by priseborough** [comment]
Replaced by https://github.com/PX4/Firmware/pull/7721

**Pull request closed without merging**
