### PR TITLE
Bring up BMI160 for px4fmu-v4 targets

### PR DESCRIPTION
**Pull request by eyeam3**
This adds chip select for BMI160 sensors on px4fmu-v4 targets and starts it in rc.sensors.

### CODE REVIEW

**Comment by kd0aij** [comment]
This is confusing me. You are starting both MPU9250 and BMI160 drivers, even though both parts use the same chip select?

**Comment by eyeam3** [comment]
I have an experimental board that has a Bosch BMI160 sensor instead of the MPU9250. So, only one of them is actually connected with the SPI bus or the chip select pin. I then try to start both sensors, but the incorrect driver will fail during initialization because of a wrong WHO_AM_I register value. Thus, during runtime only the driver which matches the hardware is running. Moreover, the connected hardware defines the started driver without the need of a parameter or flag.

**Comment by kd0aij** [comment]
Do we have a "standard" that says the WHOAMI register must be implemented? It would be nice if we could reliably do runtime device enumeration on SPI.

**Comment by eyeam3** [comment]
I checked the affected sensors and both have the WHOAMI implemented. And I would expect that this is done for all SPI drivers but cannot guarantee it is the case.

I agree, runtime enumeration would be nice.

**Comment by kd0aij** [comment]
I guess this is OK, but your last comment should probably be documented somewhere before it goes into master. Otherwise it looks a lot like a subtle coding error.

**Comment by LorenzMeier** [comment]
@eyeam3 Can you add the comment as suggested?

**Comment by eyeam3** [comment]
I added some comments. Do they help to understand the changes?

**Comment by julianoes** [comment]
Jenkins: test this please

**Comment by LorenzMeier** [comment]
CI is broken. Merging this.

**Pull request merged**
