### PR TITLE
commander refactor position velocity validity checks

### PR DESCRIPTION
**Pull request by dagar**
There's a bug in here causing most of the periodic ROS mission test failures. 

@lamping7 FYI

The actual parameter values (COM_POS_FS_DELAY and COM_POS_FS_PROB) were being ignored. @antiheavy

### CODE REVIEW

**Comment by dagar** [comment]
@LorenzMeier good to go, but please review again. I moved the commander status flags into the vehicle_status_flags message to log them directly, instead of packing bits. They're extremely useful for debugging a wide range of issues and the additional size is negligible for a low rate message.

**Comment by dagar** [comment]
I'll open a separate PR for the vehicle status flags change.

**Comment by Antiheavy** [comment]
@dagar is this the real root cause of Loss of Global Position failsafe triggering immediately?  A while ago I was led to believe it was eph,epv,evh thresholds in commander being exceeded in flight.  Existing issue here:
https://github.com/PX4/Firmware/issues/8260  actually looking at the code closer maybe it wasn't the eph,epv,evh thresholds?

**Comment by dagar** [comment]
I think it's the root cause in some of the cases, but it depends how it actually failed. If the EKF stops publishing a global position it will trigger immediately. If it continues to publish but with growing eph, epv, evh, then we can tolerate significantly more error on FW.

**Pull request merged**
