### PR TITLE
Add Rover Simulation and sim config

### PR DESCRIPTION
**Pull request by LorenzMeier**
This adds a full rover simulation for SITL and Gazebo. The physical config will follow this week for a Traxxas Stampede. This is to enable student projects at ETH.

Running it: `make posix gazebo_rover`

It kind of works already (tested manual and missions), needs further fine-tuning here and there. But I'm confident we can drive this outdoors already.

screen shot 2017-02-19 at 13 27 21

screen shot 2017-02-19 at 13 45 24

### CODE REVIEW

**Comment by LorenzMeier** [comment]
screen shot 2017-02-19 at 13 45 24

**Comment by mhkabir** [comment]
Sexy rover model there ;)

**Comment by dagar** [comment]
Likely not helpful here, but FYI there'a an old abandoned PR for adding ground firmware here - https://github.com/PX4/Firmware/pull/6050

**Comment by marcozorzi** [comment]
I'm trying to test this and having issues. I cloned the pr-rover branches of both Firmware and sitl_gazebo and I get the same errors as above here:
[ 36%] Building C object px4/src/systemcmds/pwm/CMakeFiles/systemcmds__pwm.dir/pwm.c.o
/job/catkin/src/px4/src/systemcmds/pwm/pwm.c: In function 'pwm_main':
/job/catkin/src/px4/src/systemcmds/pwm/pwm.c:637:9: error: ignoring return value of 'read', declared with attribute warn_unused_result [-Werror=unused-result]
     read(0, &c, 1);
         ^
compilation terminated due to -Wfatal-errors.

This can be asily fixed by changing line 637 of src/systemcmds/pwm/pwm.c storing the return in a variable (I used ret as done below).

After that the simulation compiles and runs but I encur in errors saying:

[Err] [gazebo_mavlink_interface.cpp:933] joint_control_type[velocity_kinematic] undefined.

These disappear if the joint type in rover.sdf are changed to velocity instead of velocity_kinematic. In this case, the simulation is not working, I'm still working on a fix.

**Comment by LorenzMeier** [comment]
@marcozorzi Worth re-trying. I removed the special joint type and added a velocity PID controller (which is also closer to what is around in HW).

**Comment by marcozorzi** [comment]
@LorenzMeier Yes now it's working perfectly

**Comment by Kiwa21** [comment]
Interesting pull request here ! It really is beginning to look like ROS/Gazebo simulations :) 
I don't have a deep knowledge of the APM Rover stack. Do we have some kind of Lidar avoidance like we have in Copter with the SF40 ?

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by LorenzMeier** [comment]
@Kiwa21 The rover parts right now are mostly for driving the vehicle. High-level navigation should be done in a higher-level software component.

**Comment by julianoes** [comment]
@coveralls took a while :smile:.

**Comment by sarahToonsi** [comment]
Hi everyone! 

I was trying to test this simulator, however I could not manage to publish  /rc/override  through mavros, any idea about what kind of parameters or things I need to change?

**Comment by julianoes** [comment]
@sarahToonsi please don't necro-bump. Open a new issue an properly describe your issue, thank you.

**Comment by sarahToonsi** [comment]
> @sarahToonsi please don't necro-bump. Open a new issue an properly describe your issue, thank you.

Sorry :)

**Pull request merged**
