### PR TITLE
Update submodule sitl_gazebo to latest Tue Dec 24 12:39:15 UTC 2019

### PR DESCRIPTION
**Pull request by dagar**
- sitl_gazebo in PX4/Firmware (0e70578052d938ea87c70837a15185b99dbb2309): https://github.com/PX4/sitl_gazebo/commit/073da14f6e62d3b3c45e40eda556c0523f86d870
    - sitl_gazebo current upstream: https://github.com/PX4/sitl_gazebo/commit/25ab469cb1d9b0ca303f64f0e5ab94d6563d852a
    - Changes: https://github.com/PX4/sitl_gazebo/compare/073da14f6e62d3b3c45e40eda556c0523f86d870...25ab469cb1d9b0ca303f64f0e5ab94d6563d852a

25ab469 2019-12-24 Julian Oes - travis: reduce CI load, only build master branch
2b16eab 2019-12-24 Julian Oes - travis: update docker tags
7a0a462 2019-11-21 TSC21 - Travis: bump container tags to 2019-11-20
3d23283 2019-11-19 TSC21 - scripts: xacro.py: fix style for readable content
502b476 2019-11-18 TSC21 - Travis: MacOS stage: install Python 3 dependencies
88c3489 2019-11-18 TSC21 - scripts: format and clean
4b63700 2019-11-18 TSC21 - CMake: look for Python3
24e9902 2019-11-18 TSC21 - scripts: make usage of Python3 only
ad84d48 2019-12-19 bresch - Iris_base: update ADIS16448 gyro and accel noise density to with values from Kalibr

### CODE REVIEW

**Comment by dagar** [comment]
Broken waiting on python update.

**Comment by Jaeyoung-Lim** [comment]
@dagar Anychange that this will get merged?

**Comment by TSC21** [comment]
@Jaeyoung-Lim this was brought in already

**Comment by julianoes** [comment]
Let's wait for the next update which includes the macOS fixes.

**Comment by julianoes** [comment]
Fixes #13950.

**Pull request merged**
