### PR TITLE
Add second battery in SITL

### PR DESCRIPTION
**Pull request by julianoes**
This is a quick and dirty addition of a second battery in SITL.

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
If I understand this correctly, does this make all the models have two batteries?

**Comment by TSC21** [comment]
> I'm not sure if this is over thinking it, but shouldn't we have a single instance only as the default (like most setups) + some models with multiple?

Yep I agree

**Comment by julianoes** [comment]
Yes, that would make sense.

**Comment by julianoes** [comment]
Looks like this is not needed as is, closing.

**Comment by hamishwillee** [comment]
Waaa. I liked the idea of easy 2nd battery testing in simulator (but have hardware to test this anyway now)

**Pull request closed without merging**
