### PR TITLE
Support for synthetic sideslip measurements in EKF2

### PR DESCRIPTION
**Pull request by CarlOlsson**
Goes together with https://github.com/PX4/ecl/pull/178

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Please rebase on master to fix CI.

**Comment by CarlOlsson** [comment]
rebased on master. But it also needs https://github.com/PX4/ecl/pull/178 to compile

**Comment by LorenzMeier** [comment]
@CarlOlsson @priseborough Where is this standing?

**Comment by priseborough** [comment]
I have tested the patches using replay on this log and fixed up some problems. It is providing a stable airspeed estimate with and without airspeed sensing. I have opened a replacement PR for it here: https://github.com/PX4/Firmware/pull/5763

**Pull request closed without merging**
