### PR TITLE
[For Discussion] FlightTask: remove local position dependency for activating a task

### PR DESCRIPTION
**Pull request by bkueng**
Some vehicles such as racers don't have a local position.

So this removes the requirement from the base task, but we should discuss alternative options. I suggest something like:
- Requirement for a valid attitude in the base task
- Requirement for a valid altitude in alt control
- Requirement for a valid local pos in auto & pos ctrl modes

@Stifael what do you think?

### CODE REVIEW

**Comment by dagar** [comment]
Really what we need is to be explicit about the requirements for every single FlightTask.

> Requirement for a valid attitude in the base task

Stabilize mode is a FlightTask, although perhaps it shouldn't be.

**Comment by Stifael** [comment]
what are you trying to solve?
In the base class, the only thing that is currrently done is to set position and velocity estimate if available
https://github.com/PX4/Firmware/blob/master/src/lib/FlightTasks/tasks/FlightTask/FlightTask.cpp#L90-L96

**Comment by Stifael** [comment]
For racers, I guess this line could be a potential problem:
https://github.com/PX4/Firmware/blob/master/src/lib/FlightTasks/tasks/FlightTask/FlightTask.cpp#L122

where yaw is always set...
For `Altitude` there is no need to have a valid position in xy (we fly Altitude indoors). For `Stabilized` there is also no need to have position nor velocity valid

**Comment by bkueng** [comment]
> what are you trying to solve?

The error I see is that the task activation for stabilized fails. The reason is that the task switch (`FlightTasks::switchTask`) calls and checks `updateInitialize()`, which fails because of the local position requirement.

> where yaw is always set...

That is also an issue, though it seems to work.

**Comment by Stifael** [comment]
> calls and checks updateInitialize(), which fails because of the local position requirement.

There is no local  position requirement for stabilized... the only thing it requires is currently to receive manual-setpoints withing a certain time-delta and yaw. 
https://github.com/PX4/Firmware/blob/master/src/lib/FlightTasks/tasks/ManualStabilized/FlightTaskManualStabilized.cpp#L56-L58

**Comment by Stifael** [comment]
@bkueng 
the only think required in FlightTaskManual is to receive the manual-setpoints within a certain time delta:
https://github.com/PX4/Firmware/blob/master/src/lib/FlightTasks/tasks/FlightTask/FlightTask.cpp#L87

There is no position nor velocity requirement. The `evaluatelocalposition` method is literally just a mapping method

**Comment by Stifael** [comment]
Ok, now I understand what you mean.
Yes, the structure vehicle_local_position is required within the time delta (at least in the current implementation), but position and velocity do not have to be valid. Your suggestion that each individual task checks for the required data is already implemented. Stabilized does not require a valid position. 
If I understand you now correctly, then the only thing required is to remove the delta timing check

**Comment by Stifael** [comment]
The time delta check is just for checking if the vehicle_local_position structure is received. 
I suggest the following: 
If the estimator position/velocity flag is valid, then the topic 'vehicle_local_position' has to be received within the time delta

**Comment by bkueng** [comment]
> If I understand you now correctly, then the only thing required is to remove the delta timing check

Correct. Plus `_yaw` needs to come from the attitude or we need to remove the yaw dependency in Stabilized. But I'll have some other changes regarding that, I'll bring it up in a separate PR.

> If the estimator position/velocity flag is valid, then the topic 'vehicle_local_position' has to be received within the time delta

I think it's better to remove the dependency entirely from the base class. In case the position estimate stops being published (for whatever reason), we still want to be able to switch into Stabilized.
For example by ignoring the return value from `_evaluateVehicleLocalPosition` in `FlightTask::updateInitialize`.

**Comment by Stifael** [comment]
> I think it's better to remove the dependency entirely from the base class. In case the position estimate stops being published (for whatever reason), we still want to be able to switch into Stabilized.

What I meant is that you do not require to receive the topic within a time-delta time, but require it to have a valid position/velocity. For instance, what I did here:
https://github.com/PX4/Firmware/blob/flighttask-remove-delta-time-check/src/lib/FlightTasks/tasks/FlightTask/FlightTask.cpp#L88-L133

For the yaw issue: I think the correct solution is what @dagar suggested and what @MaEtUgR and me are supporting as well: move the the thrust-to-attitude method to the attitude controller https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L743

**Comment by bkueng** [comment]
> What I meant is that you do not require to receive the topic within a time-delta, but require it if there is a valid position/velocity estimate. For instance, what I did here:

Ok, same result, that looks good. Can you open a PR for that?
Closing this then.

**Pull request closed without merging**
