### PR TITLE
IMU-Camera Synchronised Triggering

### PR DESCRIPTION
**Pull request by mhkabir**
This PR adds support for triggering of external cameras (e.g PointGrey Firefly MV) using the FMU auxillary pins as GPIOs.

For now,
```
nsh> fmu mode_gpio
nsh> camera_trigger start
```
Will start the triggering system on AUX 1 with default polarity ```ACTIVE_LOW```. Parameters need to be adapted to different cameras. Currently set to sensible defaults for Firefly MV.

TODO: 
- [x] Add mavlink message for ```CAMERA_TRIGGER``` with a sequence field and a timestamp for the image frame. ( https://github.com/mavlink/mavlink/pull/368/ )
- [x] Use command instead of parameter for trigger enabling or disabling. 
- [ ] Add mavlink stream for ```CAMERA_TRIGGER``` using the camera_trigger topic.
- [ ] Set a bitmap which by default enables some FMU pins as GPIOs, and some as PWM as required. during startup.

### CODE REVIEW

**Comment by mhkabir** [comment]
@LorenzMeier I'm beginning to think if we should use a command to enable/disable the trigger, since a parameter doesn't seem quite right for this application?
We'd want the companion system to enable/disable the trigger at will. Ideally, it would enable the trigger once the cameras + driver is initialised and ready. Then assuming that we don't lose the first frame, it would be possible to synchronise the IMU and camera streams and accordingly compensate for lost image frames (by enabling the image sequence feature on the camera itself)

**Comment by LorenzMeier** [comment]
Nice! Could you rebase against master please?

**Comment by LorenzMeier** [comment]
Upon closer inspection this driver should at least run in the HP work queue, and most likely it should run as HRT callback, as the jitter and timing will be much better in that case. Since that concept is quite similar to a work queue, I recommend doing the change now as it should be fairly easy:

Starting:
https://github.com/PX4/Firmware/blob/master/src/drivers/mpu6000/mpu6000.cpp#L1478-L1479

Stopping:
https://github.com/PX4/Firmware/blob/master/src/drivers/mpu6000/mpu6000.cpp#L1482-L1486

Trace the _call variable in the driver to get a feel for what's required. Note that you can't use printf / warns in interrupt context, but you can use orb_publish() and orb_copy().

**Comment by mhkabir** [comment]
I'll get this re-written to C++ which should make everything to much easier. Will take some time though.

**Comment by mhkabir** [comment]
@LorenzMeier This isn't working out. Closing for now.

**Pull request closed without merging**
