### PR TITLE
rc.board_sensors: probe for external qmc5883

### PR DESCRIPTION
**Pull request by bkueng**
@copterspace can you test this please?

fixes https://github.com/PX4/Firmware/issues/11736

### CODE REVIEW

**Comment by copterspace** [comment]
> 
> 
> @copterspace can you test this please?
> 
> fixes #11736

I tested boards/px4/fmu-v4/init/rc.board_sensors  - because I have Pixracer and build px4_fmu-v4_default.
It starts, calibrates and flies OK.
Other boards - I do not have this hardware for test, but changes in code are the same, looks like it should work same good for other boards.
And perhaps also same line
`qmc5883 -X start`
 should be added to https://github.com/PX4/Firmware/blob/master/boards/px4/fmu-v2/init/rc.board_sensors , because it has autostart for hmc5883, and does not yet have autostart for qmc5883

**Comment by bys1123** [comment]
@dlwalter Hey, here is new PR about QMC5883. Is there anything you think need to add to this driver recently. 
Thanks for your work!

**Comment by dagar** [comment]
It should probably be added to any board with external I2C.

  - airmind_mindpx-v2
  - auav_x21
  - av_x-v1
  - emlid_navio2
  - nxp_fmuk66-v3
  - omnibus_f4sd ?

Or we could look at centralizing startup for all the optional external peripherals.

**Comment by jorge789** [comment]
Tested on Pixhawk v2 Cube:

- Armed form QGC.
Took-off on mission plan mode
Note that commands were sent form QGC (Armed and takeoff)
Once all waypoint completed vehicle switched to RTL and landed as expected.
NOTE:Note: **The vehicle, approximately half of a mission, left its trajectory and then resumed.**

https://review.px4.io/plot_app?log=3db2eb24-bc22-40a1-a8a5-712e8b7577c0

Tested on PixRacer

- Modes Tested
Position Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

- Procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.
Good flight in general.

https://review.px4.io/plot_app?log=acc6ce69-9182-4fd0-be56-2da1ed7cf310

**Comment by dannyfpv** [comment]
Testing onPixhawk 4 v5   fail , successful upload firmware  not telemetry and USB connection not arming
https://youtu.be/sas88oGGJHg

**Comment by bys1123** [comment]
@dannyfpv Your motor sounds pretty cool!

**Comment by dlwalter** [comment]
@Tony3dr I ran into a lot of issues with the v5 and an external compass where the whole system would lockup (looked like some kind of i2c collision between the external mag and the rgb_led).

For those having "PRIMARY COMPASS NOT FOUND" is the compass successfully starting up at boot? Can you try manually starting it with "qmc5883 -X start" over the Mavlink console?

**Comment by dannyfpv** [comment]
@dlwalter, we loaded the PR then tried to enter the command "qmc5883-X start" on Mavlink console but it was unsuccessful, then we proceded to load Master and followed same steps on Mavlink console, the screenshot attached is from the response the console gave on Master.
Screen Shot 2019-04-09 at 10 50 15 AM

**Comment by dlwalter** [comment]
@dannyfpv I just saw your video - doesn't that Holybro NEO GPS module have an IST8310 compass in it?  The qmc5883 -X start command wouldn't work in that case.

**Comment by bys1123** [comment]
Yes, pixhawk4's GPS is using ist8310

**Comment by bkueng** [comment]
Thanks for testing.
> NOTE: It did not arm and a pop-up message that said PRIMARY COMPASS NOT FOUND.

@jorge789 I cannot reproduce. I have a cube with an external ist8310, which works. Can you attach the console and share the boot output? Also the output of `sensors status`? Which GPS and external mag are you using?
I rebased, can you try again?

**Comment by jorge789** [comment]
Tested on Pixhawk2 Cube v3:
Modes Tested

Takeoff: Good
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.
Pre-flight Procedure:

Flash firmware through QGC ✓
Arm vehicle ✓
Calibrations ✓
Parameter check ✓
Flight Test:

Arm and Take off in position mode ✓
Throttle Test ✓
Pitch, Roll, Yaw ✓
Mode Switch ✓
RTL ✓
Notes:
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint turn off RC to trigger Failsafe RTL and see landing behavior.
NOTE:No Primary Comppas error found.

https://review.px4.io/plot_app?log=c76a2380-bb51-40bc-b9d3-ac8bb19c8851

Tested on Pixhawk 2 Cube v3
Modes Tested

Takeoff: Good
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.
Pre-flight Procedure:

Flash firmware through QGC ✓
Arm vehicle ✓
Calibrations ✓
Parameter check ✓
Flight Test:

Arm and Take off in position mode ✓
Throttle Test ✓
Pitch, Roll, Yaw ✓
Mode Switch ✓
RTL ✓
Notes:
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint turn off RC to trigger Failsafe RTL and see landing behavior.

NOTE:
Vehicle was tested previously 3 times and there was no issue, but once the 4th flight started, we had the following issues: **During Failsafe RTL vehicle started descending in pauses, then once it hit the ground started jumping until disarmed form QGC.**

https://review.px4.io/plot_app?log=e978fd57-594c-4b41-b8bb-7e8f6b178b51

**Comment by bkueng** [comment]
> During Failsafe RTL vehicle started descending in pauses, then once it hit the ground started jumping until disarmed form QGC.

@jorge789 these are in-air ground-contact detections. Can you set `MPC_THR_HOVER` correctly, and maybe increase `MPC_Z_VEL_I` (to something like 0.08)?

Merging, as the issue is unrelated.

**Comment by dlwalter** [comment]
>then once it hit the ground started jumping until disarmed form QGC.

@jorge789 I've run into this issue when the autopilot isn't sufficiently isolated from wind/prop wash.  The prop wash near the ground causes the autopilot to not detect landing correctly - you can see the pressure change the barometer plots.  

Often times you can get around this by setting EKF2_HGT_MODE to 1 (GPS) if you have a good GPS coverage.

**Pull request merged**
