### PR TITLE
Inav opt flow lidar

### PR DESCRIPTION
**Pull request by ChristophTobler**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice! Test flown?

**Comment by tumbili** [comment]
@LorenzMeier I will do that.

**Comment by ecmnet** [comment]
I flew - at least in ALTCTL mode - with it. XY position estimation works quite well. One thing I noticed was, that XY position was drifting significantly at very low altitude. This seems to be the result of the limitation of the flow estimation at 0.2m.

**Comment by ilia-sheremet** [comment]
Does this PR should solve the issue with altitude estimation for the LidarLite2 only, without px4flow connected? I tried to compile from your https://github.com/ChristophTobler/Firmware/tree/inav_opt_flow_lidar branch and it didn't work in my case (LidarLite2 connected via i2c, the data of which is being send properly over the mavlink). I will try to recompile and test it out again. Will send you the log if you are interested.

**Comment by ChristophTobler** [comment]
@ilia-sheremet The altitude estimation with the LidarLite has nothing to do with the PX4Flow. Have you enabled the lidar messages (SENS_EN_LL40LS = 1)? And have you enabled lidar altitude estimation in the qgc params (I think the name is inav_lidar_est or something similar)?

**Comment by ChristophTobler** [comment]
@ecmnet Thank you for testing. What firmware have you got on the PX4Flow? This is the good one: https://github.com/PX4/Flow/commit/4a314cfdb099aed9795b825e7518203771207fbb
What is the flow quality when you fly at 0.2m? How did you focus your lens? If you often fly at that height, maybe I would adjust it.

**Comment by ilia-sheremet** [comment]
@ChristophTobler Aren't they use the same topic within the INAV? Hehe:

**Comment by ChristophTobler** [comment]
@ilia-sheremet No they are separated. The optical flow calculation is dependent on the distance but not vice versa.

**Comment by ecmnet** [comment]
@ChristophTobler I have the latest Firmware installed. The issue seems more related to the case pixflow does not provide sufficient data. In that case, is acc integrated to estimate position? This might explain the effect.

**Comment by ecmnet** [comment]
By the way. Drift at that height is Bad for accurate landings

**Comment by ChristophTobler** [comment]
@ecmnet Ok. Not sure which is the latest version. Just make sure it's the camfix and not KLT. No, acc alone does never estimate the position. Yes, that's right...

**Comment by ecmnet** [comment]
As far as I remember, the drift occurred also, when the copter did not move at all.

**Comment by ecmnet** [comment]
Just to let you know, what I mean by drift: XY plot:

drift

**Comment by tumbili** [comment]
@ChristophTobler @LorenzMeier Tested this today, will upload logs and give feedback tomorrow.
Pretty nice!

**Comment by ChristophTobler** [comment]
@tumbili cool, thanks! @ecmnet Ok so this happened while hovering (pos hold)? What's the time period?  What do you mean with invalid? Is the flow quality low? I mean a small drift can happen... How did you attach the PX4Flow? Because the biggest error comes from the PX4Flow gyroscope during position hold and you can minimize this by attaching the PX4Flow in a shielded spot. Another thing is the firmware (KLT has more drift/noise) but I already mentioned that.

**Comment by ecmnet** [comment]
@ChristophTobler: No, this was not pos-hold. It started during landing (manually) and continued after being landed. My PX4Flow is mounted centrally between the landing gear (about 8 cm over ground), connected with twisted I2C cables and shielded. As soon I find any spare time, I will look for any correlations between flow raw data and estimation (speed) and let you know.

**Comment by ChristophTobler** [comment]
@ecmnet Ok, thanks! Ah I just saw that it will actually predict position with just acc data for a short time if sensor data is not available (I'm no fan of it). Will have a look at it and discuss it with Lorenz.

**Comment by ecmnet** [comment]
XY Flow and XY Speed (not flying - holding vehicle at about 20cm):

drift2

**Comment by SimonWilks** [comment]
I gave this a quick test flight today in ALTCTL only as the Lidar Lite we have kills GPS. Worked nicely. 

The only two things I've noticed so far are:
- The INAV_LIDAR_EST doesn't show up in QGC even though I flashed using it (I don't have the most recent QGC version though).
- At one point when flying over a large rock it didn't pick the rise but did get the fall and ended up closer to the ground after the rock than it was before.

Will test some more but this is looking good.

**Comment by ChristophTobler** [comment]
@SimonWilks thanks for testing! Have you looked for INAV_LIDAR_EST in the default category? Maybe it's in there.
The altitude change might be because the drop/edge of the rock was not clear enough. Probably the correction threshold can be lowered (currently its 0.5m)

**Comment by SimonWilks** [comment]
Actually I didn't have a default category at all which is odd. So I suspect I need to update QGC (will do tomorrow).

**Comment by ecmnet** [comment]
@ChristophTobler : Here a plot of Flow (lower graph) vs. NED XY-speed (upper graph). Seems not to correlate.

nedspeed

**Comment by mhkabir** [comment]
@ecmnet I shouldn't be hijacking this thread, but could you try a flight with LPE (#3209) and see how flow performance compares directly to inav?

**Comment by ecmnet** [comment]
@mhkabir I would like to. Does LPE support altitude estimation by Laser rangefinders?

**Comment by mhkabir** [comment]
Yes, it does just fine. You just need to use that PR of mine.

You'll probably find the altitude estimation performance to be on par with
or better than that with INAV.

**Comment by ChristophTobler** [comment]
@ecmnet Ok, yes. If I look a the flow graph I presume the quad already landed (or not flying), right? So what is the height at that moment?

**Comment by ecmnet** [comment]
@ChristophTobler Yes it was going down from about 0.7m.

**Comment by ChristophTobler** [comment]
@ecmnet Could you please upload your log on http://logs.uaventure.com/ so that I can have a detailed look at it? Thanks

**Comment by ChristophTobler** [comment]
with the new additions position hold is now very stable (video: https://www.youtube.com/watch?v=Ih8FVXKHRFQ)

**Comment by kd0aij** [comment]
[image: Screenshot from 2016-02-04 08-18-03.png]

**Comment by LorenzMeier** [comment]
Closing this in favour of #3693.

**Pull request closed without merging**
