### PR TITLE
Fix failure to failsafe when GPS is disconnected

### PR DESCRIPTION
**Pull request by priseborough**
This ensures that a mode change will occur immediately when the EKF reports the solution as invalid following GPS disconnection. Addresses https://github.com/PX4/Firmware/issues/7185#issuecomment-299170451

### CODE REVIEW

**Comment by priseborough** [comment]
This was tested in jmavsim SITL by entering  'commander takeoff' followed by  'gpssim stop'. The vehicle immediately transitioned into land mode.

**Comment by ChristophTobler** [comment]
This does work in gazebo with `commander takeoff` followed by `gpssim stop`. But it does not work if it is in position mode. For example taking off manually and then switch to position follow by `gpssim stop` does not trigger a landing. Also `commander takeoff` followed by a position switch and `gpssim stop` does not work.

**Comment by ChristophTobler** [comment]
I discussed this with @Stifael and the error seems to be that the commander state is in manual but failsafe only works in auto... because it does land once you switch to hold for example

**Comment by priseborough** [comment]
The failsafe transition from position mode is by design into alt-hold, not land. IF the pilot has stick control, why would you take it away?

**Comment by Stifael** [comment]
I agree with @ChristophTobler that at least we should provide the option to do failsafe in manual position controlled mode.

**Comment by priseborough** [comment]
The majority of flying in position control, particularly during takeoff which is when the loss due to bad magnetic heading is likely to occur will be with hands on sticks. My experience working on a previous consumer drone project is that changing the vehicle from a stick control mode to a non-stick control mode when the user has hands on stick results in crashes because users are too slow to recognise they need to change to a mode that gives them control.

Therefore it is logical to make the failsafe from position to land the exception, not the default, and selectable by parameter.

**Comment by priseborough** [comment]
If an unattended position hold is required, then the vehicle should be really be placed into loiter mode.

**Comment by priseborough** [comment]
There is a vulnerability to timeouts on global and local position messages, so I will add protection for that also.

**Comment by priseborough** [comment]
I've tested this in SITL turning GPS off and on using the gpssim stop/start command in TAKEOFF, POSCTL, AUTO, HOLD and ALTITUDE modes. 

When flying in POSCTL mode if the COM_POSCTL_NAVL parameter was set to 0, the vehicle transitioned to ALTITUDE mode  and if it was set to 1 it transitioned to land .

In all other modes it transitioned to LAND.

**Pull request merged**
