### PR TITLE
allow boards to supply an rc.board init

### PR DESCRIPTION
**Pull request by dagar**
So far this saves 4 KB of flash on fmu-v2.

TODO: DATAMAN_OPT is broken in master and still broken in this PR

### CODE REVIEW

**Comment by dagar** [comment]
- fixes #10961

**Comment by dagar** [comment]
TODO (later): push pixracer i2c and spi resets (currently in fmu) into board init.

**Comment by hamishwillee** [comment]
@dagar What would you say about this in http://dev.px4.io/en/hardware/porting_guide.html ?
- What sorts of init is done at board level
- Where does it have to live in the build tree?

**Comment by dagar** [comment]
@hamishwillee mainly used for starting things that only exist on that particular board (sensors), but it can also be used for board default parameters and any other special cases.

FMUv5 example - https://github.com/PX4/Firmware/blob/master/boards/px4/fmu-v5/init/rc.board
You can see all the pixhawk 4 sensors being started, but it also sets a larger LOGGER_BUF, and in fresh setups (AUTOCNF section) it sets the SYS_FMU_TASK parameter.

This file is automatically included in the startup scripts if in the board directory at `init/rc.board`.

**Comment by bkueng** [comment]
@dagar this broke HIL as `rc.sensors` was only executed if `SYS_HITL != 1`

**Comment by dagar** [comment]
Thanks @bkueng I'll fix it.

We should get something simple on Jenkins testing HITL with Gazebo if it's working reasonably well.

**Pull request merged**
