### PR TITLE
Nuttx upgrade

### PR DESCRIPTION
**Pull request by LorenzMeier**
Continuation of https://github.com/PX4/Firmware/pull/6046.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@PX4TestFlights your test binary:
[nuttx-px4fmu-v3-default.px4.zip](https://github.com/PX4/Firmware/files/662022/nuttx-px4fmu-v3-default.px4.zip)

**Comment by santiago3dr** [comment]
http://review.px4.io/plot_app?log=08c15367-2a0c-445e-9d55-2bd649978d7f

very smooth takeoff and attitude control in stabilize and altitude
having problems in position mode from low sat count

**Comment by LorenzMeier** [comment]
@santiago3dr Please make sure to get as many flights on this as you can today. We need flight time on this as much as we can.

**Comment by priseborough** [comment]
I built this after a 'make distclean' for the px4fmu-v4_default target (pixracer)

After loading and connecting to the board via usb, I got the following QGC warnings

screen shot 2016-12-20 at 9 04 35 pm

**Comment by LorenzMeier** [comment]
You need to re-calibrate and then it should go away. The sensor id of the 9250 had a bug which set it to zero, the fix leads to this result.

**Comment by priseborough** [comment]
That fixed it

**Comment by santiago3dr** [comment]
three flights from this morning, stabilize, altitude, position, auto, rtl and land all working properly

http://review.px4.io/plot_app?log=ab2657b2-e8c2-4471-8b7f-0d336c10df62
http://review.px4.io/plot_app?log=5f17a59a-5821-411b-9de8-689e84e7d8b7
http://review.px4.io/plot_app?log=cc37d028-6870-42db-9365-25f55e12f2e4

**Comment by francisco3dr** [comment]
Additional flight logs here:

http://review.px4.io/plot_app?log=1c10b2dc-47ea-46f6-bd08-79eac60239de
http://logs.px4.io/plot_app?log=a9cbd92d-f00d-4275-8cae-cd13a95c247a
http://review.px4.io/plot_app?log=015b95dc-27a1-437d-999e-a3d5db383821

**Comment by santiago3dr** [comment]
Set THR_MDL_FAC to 0.65

http://review.px4.io/plot_app?log=5387f0af-8576-4419-bed2-f799919331bb
http://review.px4.io/plot_app?log=da33e428-8456-4cde-9aff-1452b8d4388a

**Comment by kd0aij** [comment]
S250AQ with LPE/Q estimator: http://review.px4.io/plot_app?log=e5efc160-7559-4cb4-b2b3-4c646728284d

**Comment by francisco3dr** [comment]
Additional flight logs

Set THR_MDL_FAC to 0.65

http://review.px4.io/plot_app?log=10b69a65-c56e-476c-9d60-dbf101911ab8
http://review.px4.io/plot_app?log=3adc4d89-af34-45db-83aa-fe43ef1558b3
http://review.px4.io/plot_app?log=21729f59-031b-484e-adaf-43015101e87c

**Comment by LorenzMeier** [comment]
Its in! Thanks for all the hard work @davids5

**Pull request merged**
