### PR TITLE
FlightTask : PositionSmoothVel and AutoSmoothVel - Handle XY reset

### PR DESCRIPTION
**Pull request by bresch**
When the EKF resets its position, the `xy_reset_counter` is incremented. When a reset happens, the flight task has to take care about this prevent dangerous behaviors. 
This is already handled in the other position control flight tasks, but not in that one.

Flight test: GPS and optic flow fusion, with a switch that controls GPS fusion
1. Fly with GPS
2. Disable GPS fusion (fuse OF only)
2. Navigate with optic flow and yaw a lot to force position drift
3. Reactivate GPS fusion

Before that PR, the drone tried to suddenly correct for the jump in position: 
https://logs.px4.io/plot_app?log=4e981506-0c42-48cd-92eb-702ce321dc6f

With that PR, the drone stays at the current position:
https://logs.px4.io/plot_app?log=989150c7-6d5b-4347-910a-6fe366bd0e9a

@AnnaDaiZH FYI

### CODE REVIEW

**Comment by mhkabir** [comment]
Can this be added for offboard as well?

**Comment by LorenzMeier** [comment]
Please check the build failure.

**Comment by bresch** [comment]
v2 flash overflow...

**Comment by bresch** [comment]
@dagar  we're missing 329 bytes to fit that into v2. Can we do something?

**Pull request merged**
