### PR TITLE
inav lidar altitude estimation + fix in flow yaw compenstion

### PR DESCRIPTION
**Pull request by ChristophTobler**
I decoupled the lidar from flow and added a altitude estimation which can be enabled as a parameter.
I tested it with objects in gazebo, but a real test would probably be good/better.

### CODE REVIEW

**Comment by ChristophTobler** [comment]
also fixed a mistake in flow yaw compensation

**Comment by ChristophTobler** [comment]
Here's a log of a test flight indoors (altitude estimation with lidar).
http://logs.uaventure.com/view/TfPrfZrqZQtYrUrPtkuFrR#Local_Z_PLOT

**Comment by mhkabir** [comment]
@ChristophTobler How did you run tests in Gazebo? I can't see it simulating a rangefinder? Thanks!

**Comment by ChristophTobler** [comment]
@mhkabir The camera model with optical flow plugin and the lidar model are not yet part of master. (Hopefully they are soon :)) If you need it, I can send you the files tomorrow.

**Comment by mhkabir** [comment]
@ChristophTobler That'd be great :) Please do. 
It would make my work on LPE so much easier. Thanks!

**Comment by LorenzMeier** [comment]
@ChristophTobler Is this the final state and ready to go in?

**Comment by ChristophTobler** [comment]
@LorenzMeier Added missing changes that were in a different pull request. Now it is ready, yes.

**Comment by ChristophTobler** [comment]
Closed. Changes are in https://github.com/PX4/Firmware/pull/3532

**Pull request closed without merging**
