### PR TITLE
Update submodule micro-CDR to release 1.0.0

### PR DESCRIPTION
**Pull request by dagar**
- micro-CDR in PX4/Firmware (e5d7612404cbf8404aceee0a65f6e793a1447b47): https://github.com/eProsima/micro-CDR/commit/f325c4f7731a5d10c474e1a30f7407c220d97b54
    - micro-CDR current upstream: https://github.com/eProsima/micro-CDR/commit/f10f78b16b06689d42b027665f3ff9f86f37ee54
    - Changes: https://github.com/eProsima/micro-CDR/compare/f325c4f7731a5d10c474e1a30f7407c220d97b54...f10f78b16b06689d42b027665f3ff9f86f37ee54

f10f78b 2018-10-19 Luis Enrique Muñoz Martín - Release 1.0.0 (#15)

### CODE REVIEW

**Comment by dagar** [comment]
@TSC21 opening this as more of an FYI. I'm not sure how extensive the changes are.

**Comment by TSC21** [comment]
> @TSC21 opening this as more of an FYI. I'm not sure how extensive the changes are.

Quite big. Have to test first.

**Comment by TSC21** [comment]
They've added `ucdr_` prefix is their serialization and deserialization functions, so that needs to be addressed as well on our templates as well. I will handle it this weekend.

**Comment by TSC21** [comment]
Superseded by https://github.com/PX4/Firmware/pull/10954

**Comment by TSC21** [comment]
Thanks @dagar! Continued in https://github.com/PX4/Firmware/pull/10954

**Pull request closed without merging**
