### PR TITLE
Implemented GND_W_RMAX param.

### PR DESCRIPTION
**Pull request by SalimTerryLi**
Please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/) to align on pull requests if necessary. You can then open draft pull requests to get early feedback.

**Describe problem solved by the proposed pull request**
My differential rover turns around too quickly so I make use of GND_W_RMAX parameter to limit its steering rate.

**Test data / coverage**
Tested through gazebo. It worked.

**Additional context**
This solution creates a limiter on pid output of yaw control. So this parameter ranges from 0 to 1. For normal rovers, this value may be set to 1.0 . For differential ones, a value of 0.5 works fine.

### CODE REVIEW

**Comment by dagar** [comment]
Can you check the test failure? Minor code style changes. Try `make check_format` locally.

Screen Shot 2019-05-18 at 4 54 28 PM


http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/detail/PR-12041/1/pipeline

**Comment by SalimTerryLi** [comment]
> Can you check the test failure? Minor code style changes. Try `make check_format` locally.
> 
> Screen Shot 2019-05-18 at 4 54 28 PM
> 
> http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/detail/PR-12041/1/pipeline

Done.

**Comment by julianoes** [comment]
@SalimTerryLi thanks a lot, that's great. If this is ready to be merged you can remove the "draft" and make it a real pull request. 

@ItsTimmy would be good if you can review and test this.

**Comment by SalimTerryLi** [comment]
> @SalimTerryLi thanks a lot, that's great. If this is ready to be merged you can remove the "draft" and make it a real pull request.
> 
> @ItsTimmy would be good if you can review and test this.

But there is another problem. There would be some changes on QGC and document side such as the description and default values of this parameter. If not, nobody can turn it correctly. I don' t know how to make such a change of QGC.
Such as this [one](https://dev.px4.io/master/en/advanced/parameter_reference.html#gnd-attitude-control).

**Comment by julianoes** [comment]
> I don' t know how to make such a change on QGC.

The way this works is that the param needs to be described correctly here:
https://github.com/PX4/Firmware/blob/b984411770da07f757ebaa2f72c5600386e81892/src/modules/gnd_att_control/gnd_att_control_params.c#L127-L140

It will then appear in QGC after a release.

**Comment by SalimTerryLi** [comment]
> > I don' t know how to make such a change on QGC.
> 
> The way this works is that the param needs to be described correctly here:
> 
> https://github.com/PX4/Firmware/blob/b984411770da07f757ebaa2f72c5600386e81892/src/modules/gnd_att_control/gnd_att_control_params.c#L127-L140
> 
> It will then appear in QGC after a release.

Thank you. I' ve added it.

**Pull request closed without merging**
