### PR TITLE
Add more GPS checks for LPE

### PR DESCRIPTION
**Pull request by jgoppert**
This adds checks for fix type and EPV to GPS for LPE.

### CODE REVIEW

**Comment by jgoppert** [comment]
Here is a flight log of this PR: http://logs.uaventure.com/view/4RFQF4wAGZjLDe9koXhJ5m

Again this is a trivial change, so will just merge after CI completes.

**Comment by LorenzMeier** [comment]
@jgoppert Why is the global position altitude different from the GPS altitude?
http://logs.uaventure.com/view/4RFQF4wAGZjLDe9koXhJ5m#Altitude_PLOT

**Comment by jgoppert** [comment]
@LorenzMeier The baro is the first sensor to initialize in LPE so it sets the offsets for the other sensors, you can see it here: 

image

I added a check to see if the flag LPE_GPS_ON is set, if it is, it will force altitude initialization with baro.

**Comment by jgoppert** [comment]
@LorenzMeier  think this is ready to merge, can you confirm, here are plots and logs:

image

image

http://logs.uaventure.com/view/fL3RMGzhUmp6mZGDFM2TQU

**Comment by jgoppert** [comment]
Merging this since it is already test flown, has no impact on other estimators, and passed the CI tests.

**Pull request merged**
