### PR TITLE
LPE land bug fix and switch to fusion bit mask.

### PR DESCRIPTION
**Pull request by jgoppert**

### CODE REVIEW

**Comment by jgoppert** [comment]
Now with groundtruth we can actually test optical flow performance, @LorenzMeier @priseborough @ecmnet 

http://logs.px4.io/plot_app?log=3a059d50-71ad-40e2-8a92-669ae71d2ee0

image

image


To reproduce this:

```bash
make posix_sitl_default gazebo_iris_opt_flow
```

Log files are in px4/build_posix_sitl_default/tmp/rootfs/fs/microsd/log/

**Comment by ecmnet** [comment]
Why not making Baro Fusion possible as well?

**Comment by ecmnet** [comment]
@jgoppert Some additional thoughts on LPE regarding vision: Vision based Z estimation, at least in my case, is quite bad due to a low resolution in that direction. Even when setting the std.dev. to the maximum, it has an influence on altitude. It would be great if it is possible to switch vision based Z estimation completely off . Second point is, that accuracy of vision depends strongly on the distance of the objects used to estimate position. So publishing the std.dev. along with the position estimation could also help here, giving e.g. flow more weight, if the vision position estimate is bad. On the other hand, in situations, when objects are quite near and vision position estimate is very precise, vision could have more impact on LPE's estimation.

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by jgoppert** [comment]
@ecmnet I will add the baro disable. I think the easiest thing to do is increase the LPE_VIS_Z stddev up high. That should have the same effect as me removing the correction and not require any code changes.

**Comment by ecmnet** [comment]
@jgoppert Thanks for adding the baro switch. Would it make sense to increase the maximum of LPE_VIS_Z as 2m seems to have still an influence?

**Comment by jgoppert** [comment]
@ecmnet, sure, will do that.

**Comment by LorenzMeier** [comment]
@jgoppert can we re-run and rebase?

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by LorenzMeier** [comment]
@jgoppert Rebased on master and force-pushed. If SITL continues to fail you'll have at least the plot links to figure out how it fails.

**Comment by jgoppert** [comment]
@bkueng, @AndreasAntener  Any idea why all of the flight review logs show ekf2 as estimator, when 2/7 of the flights are with LPE?

http://sitl01.dronetest.io/job/PX4%20Firmware%20POSIX%20SITL%20PRs/3346/consoleFull

http://logs.px4.io/plot_app?log=8a5d4e64-17b5-4609-8bf5-7bcea2a93c41

**Pull request merged**
