### PR TITLE
mavlink: correctly fill LOCAL_POSITION_NED_COV message

### PR DESCRIPTION
**Pull request by okalachev**
Right now it's impossible to get estimated covariances and accelerations with MAVROS.

In this PR I fill out `LOCAL_POSITION_NED_COV` message fields correctly. I get data from `vehicle_local_position` topic, because `estimator_status` fields are not actually formalised and have different values for EKF2 and LPE.

I created a corresponding in MAVROS (https://github.com/mavlink/mavros/pull/1142), so this info can actually be used.

Right only possibility to enable this message is only by the code. But it can be a configurable parameter.

But actually, only `LOCAL_POSITION_NED_COV` can be used instead of `LOCAL_POSITION_NED` as it contains all the information. The only problem is its giant size.

### CODE REVIEW

**Comment by TSC21** [comment]
@okalachev this message was dropped some time ago for a purpose: the ODOMETRY msg is going to be used to get the feedback, instead of LOCAL_POSITION_NED_COV, which will probably be deprecated.

**Comment by TSC21** [comment]
And the reference plugin: https://github.com/PX4/Firmware/pull/9895

**Comment by okalachev** [comment]
So is `ODOMETRY` is going to replace the `LOCAL_POSITION_NED`? Is there any point to fix `LOCAL_POSITION_NED` for now, as `ODOMETRY` is not yet implemented?

**Comment by TSC21** [comment]
No. ODOMETRY is not going to replace LOCAL_POSITION_NED. it has a different purpose. But eventually LOCAL_POSITION_NED_COV will be deprecated. So this is not a matter of fixing. It kust doea not make sense to support LOCAL_POSITION_NED_COV.

**Comment by okalachev** [comment]
> #10510 is already opened so to have the ODOMETRY loopback

`LOCAL_POSITION_NED_COV` is not actually a loopback. It's the estimated data from the estimator.

Also `ODOMETRY` doesn't have accelerations.

**Comment by TSC21** [comment]
When I refer to loopback, I mean the estimated pose and velocity from the FCU. And we don't propagate the accelerations either way.

**Comment by okalachev** [comment]
Why to use `ODOMETRY` to get the estimated state?

First, it doesn't have accelerations. How I can the accelerations from the FCU thought MAVLink then?

Also, it has redundant `rollspeed`, `pitchspeed`, `yawspeed`, which are already present in `ATTITUDE_QUATERNION`.

**Comment by TSC21** [comment]
Either way, this PR has good intention but it does not fit the current defined odometey pipeline and message set. This message was also dropped some time ago for that same reason. So feel free to close it. I will ping you soon when I open the PR with the ODOMETRY stream support

**Comment by okalachev** [comment]
How do I get estimated accelerations from the FCU with `ODOMETRY` message?

**Comment by TSC21** [comment]
@okalachev read #9895 and you will understand the pipeline. This fita ROS REP 105. The accels will be supported as soon as we also have the OdometryWithAccel msg support on ROS, which is also planned by ROS developers.

**Comment by TSC21** [comment]
If you are really using the accelerations on the other side, just apply a derivative the the velocity, which is actually what the ax, ay and az fields on the `vehicle_local_position` are.

**Comment by okalachev** [comment]
> When I refer to loopback, I mean the estimated pose and velocity from the FCU

Then, `ODOMETRY` should be the replacement for `LOCAL_POSITION_NED`, I guess. But the lack of accelerations data is still not cool.

> Just apply a derivative of the velocity

No, that's ugly. Why I should calculate what is already is known actually?

**Comment by TSC21** [comment]
@okalachev the accell estimation you think you have is nothing more that the derivative. Check the `vehicle_local_position` accel fields description.

**Comment by TSC21** [comment]
ODOMETRY does not have to be a replacement for LOCAL_POSITION_NED. There are systems where you don't need covariances or velocities. Just the estimated pose from the FCU. Example: closed loop offboard control. For more complex systems like SLAM, then ODOMETEY will be used.

**Comment by TSC21** [comment]
@okalachev maybe this is something it may interest you for future reference: https://github.com/mavlink/mavlink/pull/880

**Comment by mhkabir** [comment]
Pitching in here : currently the accel "estimates" published on the PX4 side is just the raw accelerometer data minus the estimated bias.

**Comment by jgoppert** [comment]
True, there is no good way to get the accel bias. Odom with accel is also talked about in the rep above. Maybe we should support that as well?

**Comment by okalachev** [comment]
I've read anything above, and my proposal:

1. Merge this one, because it's not obvious, that all the `ODOMETRY` thing will be out soon. And the code in my branch is definitely more correct, than the existing. As soon as the `ODOMETRY` thing will be done, this code may be deleted.

    The fact, that accels in `vehicle_local_position` are not the "real" estimation, but the data from IMU (minus gravity) is not actually a problem. The MAVLink protocol says, that `ax`, `ay`, `az` are the estimation of the FCU filter. But it does not say, that the filter cannot "estimate" the accels by just taking the IMU data. And knowing what the estimator thinks about the accels is nessesary for debugging.

    Also, there can be other estimators, that can place real accel estimations in `vehicle_local_positions` later.

2. Merge the corresponding MAVROS PR, because technicaly it does correct handling of `LOCAL_POSITION_NED_COV` message. And this message can be used by some other flight controllers.

    Later the plugin can be extended with `ODOMETRY` message handling as well.

**Comment by okalachev** [comment]
@mhkabir

> currently the accel "estimates" published on the PX4 side is just the raw accelerometer data minus the estimated bias.

Also minus gravity. It's useful info, even in this form.

**Comment by jgoppert** [comment]
I agree the old code is just wrong it was a hack to get some real-time estimator state debugging, but I think if we start supporting this message and pipe all that info through it, people will start using it and be upset when we switch to the odom msg style. I think the odom is lighter because it doesn't keep all the cross covariances. Adding a temporary odom with accel msg until it is merged into ros seems like another option. And all this only seems worthwhile if you actually need accel for your application. Otherwise let's just delete the code entirely.

**Comment by TSC21** [comment]
@okalachev just propose an extension for ODOMETRY with accelerations. This is not going to be merged just because you need it imediately for your application. When merging things, we need see the full spec and the planned architecture, not what feels convinient for use. It does not make sense to merged this and then imediately drop it again. This was dropped once for a purpose. Does not make sense to bring it back again.
So please, if you do need support to this purpose an extension for ODOMETRY to add accels and then we can work from there. The MAVROS PR is a different story and can be of course reviewed and merged since is made for other flight stacks as well, but it won't benefit from the approach we are taking on PX4 for a VIO pipeline.
Though stay tunned as I am bringing the ODOMETRY support next couple of days. Though it won't be with accels as you want. Again, please propose the message extension on the Mavlink side.

**Comment by mhkabir** [comment]
I'm not sure if we have space for accel in the mavlink ODOMETRY message though.

@TSC21 is this new "message flow" with the ODOMETRY message documented somewhere?

**Comment by TSC21** [comment]
> @TSC21 is this new "message flow" with the ODOMETRY message documented somewhere?

The docs are ongoing. Part of it is already in https://dev.px4.io/en/ros/external_position_estimation.html. But you can track the different parts of it in:
- https://github.com/PX4/Firmware/pull/9895 (implementation of the flow to the OBC to the estimator)
- https://github.com/PX4/Firmware/issues/10510
- https://github.com/PX4/Firmware/issues/10511
- https://github.com/PX4/Firmware/issues/10512
- https://github.com/PX4/Firmware/issues/10513

**Comment by TSC21** [comment]
This PR is superseded by https://github.com/PX4/Firmware/pull/11084.

**Pull request closed without merging**
