### PR TITLE
update discovery tree to master, NOT WORKING AT THE MOMENT

### PR DESCRIPTION
**Pull request by nopeppermint**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
There are too many commits in this PR - could you run a rebase against master? It should only hold discovery commits, not all the other ones as well.

**Comment by nopeppermint** [comment]
ok, maybe thats also easier to find errors...

**Comment by nopeppermint** [comment]
ok, as I deleted the whole thing, I will start again (as I don't see a way to restore this)
So I will update the discovery tree, then there will be an actual firmware at the moment of doing this and it doesn't interrupt the master tree.

**Comment by nopeppermint** [comment]
#2034 is therefore no longer needed

**Pull request closed without merging**
