### PR TITLE
DO NOT MERGE:Experimental:Adding -ffast-math

### PR DESCRIPTION
**Pull request by davids5**

### CODE REVIEW

**Comment by davids5** [comment]
This PR will require extensive testing! @PX4TestFlights 

See Compiler is not emitting vsqrt.f32 on ARM Cortex M4F targets #6838
The replacements with -ffast-math

```
8008654:       eeb1 7ae7       vsqrt.f32       s14, s15
 800ac76:       eef1 7ac7       vsqrt.f32       s15, s14
 800b284:       eeb1 7ae7       vsqrt.f32       s14, s15
 800b3f8:       eeb1 7ae7       vsqrt.f32       s14, s15
 800d114:       eeb1 7ae7       vsqrt.f32       s14, s15
 8030960:       eef1 0ae0       vsqrt.f32       s1, s1
 8032be8:       eef1 7ac7       vsqrt.f32       s15, s14
 8032c9e:       eef1 7ac7       vsqrt.f32       s15, s14
 8042488:       eeb1 7ae7       vsqrt.f32       s14, s15
 8043202:       f0ba fa19       bl      80fd638 <sqrt>
 8047e90:       eeb1 0ac0       vsqrt.f32       s0, s0
 8047f62:       eef1 6ac6       vsqrt.f32       s13, s12
 80480e6:       eeb1 8ac0       vsqrt.f32       s16, s0
 80488b8:       eeb1 0ac0       vsqrt.f32       s0, s0
 8048924:       eef1 7ae6       vsqrt.f32       s15, s13
 804898a:       eeb1 7ae7       vsqrt.f32       s14, s15
 80489ee:       eef1 7ae6       vsqrt.f32       s15, s13
 8048a3c:       eeb1 7ae7       vsqrt.f32       s14, s15
 8049556:       eef1 6ac6       vsqrt.f32       s13, s12
 8049d86:       eeb1 aae7       vsqrt.f32       s20, s15
 804a4f8:       eef1 6ae7       vsqrt.f32       s13, s15
 804f120:       eeb1 7ae7       vsqrt.f32       s14, s15
 804f1a8:       eef1 7ac7       vsqrt.f32       s15, s14
 80523f0:       eeb1 0ac0       vsqrt.f32       s0, s0
 8052a1c:       eeb1 0ac0       vsqrt.f32       s0, s0
 8052ba4:       eeb1 8ae7       vsqrt.f32       s16, s15
 80537d8:       eeb1 0ac0       vsqrt.f32       s0, s0
 8054014:       eef1 7ac0       vsqrt.f32       s15, s0
 80540be:       eeb1 7ae7       vsqrt.f32       s14, s15
 80545ae:       eeb1 7ae7       vsqrt.f32       s14, s15
 80545f0:       eeb1 7ae7       vsqrt.f32       s14, s15
 805601c:       f0a7 fb0c       bl      80fd638 <sqrt>
 8057ed2:       eeb1 7ae7       vsqrt.f32       s14, s15
 8057fba:       eeb1 7ae7       vsqrt.f32       s14, s15
 80580ca:       eeb1 7ae7       vsqrt.f32       s14, s15
 805f98c:       eeb1 7ae7       vsqrt.f32       s14, s15
 805f9be:       eeb1 7ae7       vsqrt.f32       s14, s15
 806109c:       eeb1 5ae4       vsqrt.f32       s10, s9
 80612b8:       eeb1 6ac7       vsqrt.f32       s12, s14
 80612f0:       eeb1 7ae7       vsqrt.f32       s14, s15
 80612fe:       eeb1 7ac5       vsqrt.f32       s14, s10
 8061306:       eeb1 7ae5       vsqrt.f32       s14, s11
 80614d4:       eef1 5ac4       vsqrt.f32       s11, s8
 8061782:       eeb1 eae7       vsqrt.f32       s28, s15
 80617c8:       eeb1 7ae7       vsqrt.f32       s14, s15
 80617d6:       eeb1 7ac9       vsqrt.f32       s14, s18
 80617de:       eeb1 7ae6       vsqrt.f32       s14, s13
 8064c74:       eef1 6ae7       vsqrt.f32       s13, s15
 8064fa8:       eeb1 6ac7       vsqrt.f32       s12, s14
 80651f0:       eef1 7ac7       vsqrt.f32       s15, s14
 806f312:       eeb1 7ae7       vsqrt.f32       s14, s15
 806f4a0:       eeb1 7ae7       vsqrt.f32       s14, s15
 8071adc:       eeb1 7ae7       vsqrt.f32       s14, s15
 8071b0e:       eef1 7ac7       vsqrt.f32       s15, s14
 8072d8e:       eeb1 7ae7       vsqrt.f32       s14, s15
 807bf7c:       eef1 8ae7       vsqrt.f32       s17, s15
```

**Comment by pavel-kirienko** [comment]
One would expect a more significant performance increase. Or am I reading
this wrong?

Also, David, could you please note where the double precision sqrt is
invoked from? It might be bugs.

**Comment by davids5** [comment]
@pavel-kirienko  Here are the last 2 where double precision sqrt is used

```
080431e4 <control::BlockStats<float, 1u>::getStdDev()>:
 80431e4:       b513            push    {r0, r1, r4, lr}
 80431e6:       4604            mov     r4, r0
 80431e8:       4668            mov     r0, sp
 80431ea:       f7ff ffbd       bl      8043168 <control::BlockStats<float, 1u>::getVar()>
 80431ee:       4620            mov     r0, r4
 80431f0:       f7ff ff58       bl      80430a4 <matrix::Matrix<float, 1u, 1u>::Matrix()>
 80431f4:       4b08            ldr     r3, [pc, #32]   ; (8043218 <control::BlockStats<float, 1u>::getStdDev()+0x34>)
 80431f6:       6023            str     r3, [r4, #0]
 80431f8:       9801            ldr     r0, [sp, #4]
 80431fa:       f0bf ff0d       bl      8103018 <__aeabi_f2d>
 80431fe:       ec41 0b10       vmov    d0, r0, r1
 8043202:       f0ba fa19       bl      80fd638 <sqrt>
--
 8055fe6:       692b            ldr     r3, [r5, #16]
 8055fe8:       4e2c            ldr     r6, [pc, #176]  ; (805609c <MatrixTest::vectorTests()+0x1f4>)
 8055fea:       3301            adds    r3, #1
 8055fec:       612b            str     r3, [r5, #16]
 8055fee:       ce0f            ldmia   r6!, {r0, r1, r2, r3}
 8055ff0:       ac0d            add     r4, sp, #52     ; 0x34
 8055ff2:       c40f            stmia   r4!, {r0, r1, r2, r3}
 8055ff4:       6833            ldr     r3, [r6, #0]
 8055ff6:       6023            str     r3, [r4, #0]
 8055ff8:       a90d            add     r1, sp, #52     ; 0x34
 8055ffa:       a824            add     r0, sp, #144    ; 0x90
 8055ffc:       f7fc fe26       bl      8052c4c <matrix::Matrix<float, 5u, 1u>::Matrix(float const*)>
 8056000:       4640            mov     r0, r8
 8056002:       f8cd b090       str.w   fp, [sp, #144]  ; 0x90
 8056006:       ac25            add     r4, sp, #148    ; 0x94
 8056008:       f7ff ff3e       bl      8055e88 <matrix::Matrix<float, 5u, 1u>::Matrix()>
 805600c:       f8cd b0a8       str.w   fp, [sp, #168]  ; 0xa8
 8056010:       f854 0b04       ldr.w   r0, [r4], #4
 8056014:       f0ad f800       bl      8103018 <__aeabi_f2d>
 8056018:       ec41 0b10       vmov    d0, r0, r1
 805601c:       f0a7 fb0c       bl      80fd638 <sqrt>
```

**Comment by davids5** [comment]
@priseborough @pavel-kirienko 

Just an FYI:Here is one path that is still is calling __ieee754_sqrtf

image

**Comment by davids5** [comment]
Given @NaterGator [Benchmark](https://github.com/PX4/Firmware/issues/6838#issuecomment-287896838)

This looks like a dead end. @pavel-kirienko do see any merit in pursuing this?

**Comment by pavel-kirienko** [comment]
> Here is one path that is still is calling __ieee754_sqrtf

This seems to be invoked from the library, whose code is probably not affected by the optimization flags.

Concerning whether we should pursue this further I will reply in the original issue thread.

**Comment by LorenzMeier** [comment]
We had -ffast-math enabled earlier and it probably got rather accidentally dropped.

**Comment by davids5** [comment]
@LorenzMeier 

> We had -ffast-math enabled earlier and it probably got rather accidentally dropped.

That history puts me a bit at ease. 

 I am not sure when or why it was dropped. I looked for it back in a pre cmake version from Nov 2014. As noted above I only found  ```-funsafe-math-optimizations```

There is one notable change that I think came about in the cmake transition. 
Pre cmake, we carried version of [matherr](http://man7.org/linux/man-pages/man3/matherr.3.html) that  always returned 1 in the fmu_init.c file.
>If the matherr() function returns a nonzero value, then the system
       does not set errno, and doesn't print an error message.:
image

Post cmake that was removed and the current definition (irrespective of -ffast-math):
> If the matherr() function returns zero, then the system sets errno as
       described above, and may print an error message on standard error
       (see below).

image

@jgoppert can you shed some light on this? 


Strictly by the numbers --ffast-math

Gives us a smaller build saving 4736 bytes. (master:1440572  master_hw_fpu:1435836)  and better math performance. 

So this PR, once vetted will help on 2 fronts.

**Comment by NaterGator** [comment]
I have concerns regarding fast-math's implicit enabling of finite-math-only. We need to be certain we don't use NaNs anywhere in firmware to detect numeric instability or uninitialized values.

**Comment by francisco3dr** [comment]
Went to try this in the field with a DJI F450.
- Connected battery
- Drone acquired GPS
- Activated safety switch
- Motors turned on by themselves (No arming sequence on Radio)
- Drone started gaining altitude real fast, I tried to recover it but it was out of control, eventually had to enable the killswitch and lost the vehicle (flyaway)

**Comment by dagar** [comment]
Closing as stale, but keeping the branch. There's actually a lot more to discuss here before we do anything.

**Pull request closed without merging**
