### PR TITLE
TECS init

### PR DESCRIPTION
**Pull request by LorenzMeier**
@kd0aij Could you test this first in HIL and then on one of your planes? It should address the symptoms in your acromaster log:
http://dash.oznet.ch/view/nxeFofFiRpQtj5ZiqswWsX

I'm really short on testing time and I did change more than I'm comfortable with, are you willing to lend a hand in coding and code review? It doesn't require a full understanding of TECS, just the init sequence and the way rate limits are calculated need to be checked.

### CODE REVIEW

**Comment by kd0aij** [comment]
log file: http://dash.oznet.ch/view/vuXtjZyheDsbhvBx7EF3Gi

initial transient on entry to altctl mode:
engage_altctl

full throttle dive at full down pitch:
dive

discontinuity in throttle command:
throttle_discontinuity

**Comment by kd0aij** [comment]
@LorenzMeier This hack eliminated the dive problem as you suspected (note that MANUAL_THROTTLE_CLIMBOUT_THRESH = 0.85):
```
diff --git a/src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp b/src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp
index 33a78f3..ff2c853 100644
--- a/src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp
+++ b/src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp
@@ -1008,6 +1008,8 @@ bool FixedwingPositionControl::update_desired_altitude(float dt)
 		was_in_deadband = true;
 	}
 
+	// check whether this causes the dive problem
+	climbout_mode = false;
 	return climbout_mode;
 }
```

**Comment by kd0aij** [comment]
http://dash.oznet.ch/view/mUuGHwrqWeekvGUx64T5tN

**Comment by kd0aij** [comment]
This looks good in HIL with the increased gains from #2632

**Comment by kd0aij** [comment]
HILsim log: https://copy.com/B2kkKQS7MoxmTS3L

Plot of initial pitch transient/oscillation and response to subsequent speed and climb/descend commands:
transient

**Comment by LorenzMeier** [comment]
Rebased and applied via beta.

**Pull request closed without merging**
