### PR TITLE
CollisionPrevention only process distance_sensor updates

### PR DESCRIPTION
**Pull request by dagar**
In current master `distance_sensor` will be uninitialized garbage for the unpublished instances. This will also limit the update work to only process new messages.

### CODE REVIEW

**Comment by mhkabir** [comment]
This broke things

**Comment by dagar** [comment]
What are you running exactly? What rate is new distance_sensor data coming in at (`uorb top`)?

**Comment by mhkabir** [comment]
Sensors are running at 20Hz. The issue is, since we re-initialize the struct every iteration (50Hz), the timestamp is uninitialized (since distance sensors aren't updated) for 3/5 iterations.

**Comment by mrivi** [comment]
@mhkabir do you have a fix or should we only revert this PR for the time being?

**Comment by mhkabir** [comment]
Have a fix - I'll push it up later today.

**Pull request merged**
