### PR TITLE
RTL mode switching: Allow to flick to RTL in any mode.

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Does this affect any of the QGC flight mode setup. Especially with respect to mapping multiple modes to the same channel?

**Comment by LorenzMeier** [comment]
No, it shouldn't affect the setup as far as I can tell.

**Comment by thomasgubler** [comment]
I updated the docs. Whoever merges this please update the wiki: https://pixhawk.org/users/system_modes
rc_mode_switch

originally the idea was probably to have room for setting a different mode with the return switch when in MANUAL. I agree with the previous posters however that this proved to be non-intuitive.

Testers: please verify that you can still fly without a RTL switch configured.

**Comment by AndreasAntener** [comment]
@LorenzMeier Just did a HIL test, it seems when I hit the RTL switch now, it just "switches" into the state it's already in (so no switch actually happens). If I look at the code I think it goes through the RTL check but switches back to whatever is set with the mode switches again.

**Comment by DonLakeFlyer** [comment]
Still wondering whether QGC is affected. This multi-switch flight mode stuff made my head hurt when I coded it. It is coded according to this flow chart. Which would seem to be different now?
rc_mode_switch_flow

I believe it is affected. First their are naming issues like this single switch configuration:
screen shot 2015-04-20 at 12 48 30 pm

Second the allowed configurations are different now. For example this configuration has Return and PosCtl on the same switch which as far as I understand used to be allowed. Which would no longer be allowed right? There area likely other disallowed combination now.
screen shot 2015-04-20 at 12 49 27 pm

Then lastly if I"m correct about the above how does QGC know which version of firmware it is running against so that it can support both old and new.

**Comment by LorenzMeier** [comment]
Thanks Andreas. Could you re-test? I've fixed the issue I think.

**Comment by AndreasAntener** [comment]
@DonLakeFlyer @thomasgubler What we just discussed in the dev call is relevant I guess: there are these "functions", like RTL (also LOITER IMHO), that are not actually flight modes. The implementation still treats these as sub-modes of AUTO, but the user can enable request to enable them directly. This of course then impacts the user front end directly (and the docs ;)).

**Comment by DonLakeFlyer** [comment]
Could someone make me a new one of those flowcharts which matches this implementation and then I can update QGC to it? Still need to solve the "Which version of firmware am I running?" problem. Even if to just disable FM setup for older firmwares instead of trying to support two "modes".

**Comment by AndreasAntener** [comment]
@LorenzMeier cool, works in HIL :) also works if I don't have an RTL switch mapped.

**Comment by LorenzMeier** [comment]
What do you mean also works if you don't have one mapped? That sounds a bit like a failure mode?

**Comment by LorenzMeier** [comment]
@DonLakeFlyer First disclaimer: This is a PR and a proposal. So you can still oppose it and propose a different approach or make the point that its more consistent like it was before. So please be critical.

Now I realize what you mean. Yes, it might need a different category, the same way as the off board switch is a different category. The logic there is: If off board switch is on, then off board control is enabled. If not, then if RTL switch is on, RTL is enabled. If neither are on, normal flight modes apply.

You can think of off board and RTL as cruise-control functions in a car: You enable them with a momentary switch (or you hold the momentary switch in the on position) and as long as their conditions are met, they are executing. Whereas the other flight modes are more the difference between "sport" and "convenience" modes of your suspension system.
I could also see that off board and RTL map to pushbuttons (off board: "Do Video shot", RTL: "Home").

Offboard and RTL switches need to be at a unique position. This means for the single-channel case that they need to be the first two entries if enabled (top off board, then Return, then the rest of the modes). This is actually the same as you have it for auto right now, with the addition of the off board switch.
For the single-channel layout it means that off board and RTL need to be on their own unique switches.

Sorry about the confusion and the impact. I think its just a lot more understandable now this way. If you call your system to RTL, its more like sending a command.

**Comment by AndreasAntener** [comment]
> What do you mean also works if you don't have one mapped? That sounds a bit like a failure mode?

;) sry, in this case I meant, flying still works without an RTL switch mapped. (Referring to Thomas' comment above)

**Comment by DonLakeFlyer** [comment]
> So please be critical.

I think it's fine. Definitely a bit odd that you can't just throw a switch to return no matter what mode. You're description gives me what I need to implement. I can add off board as well. Then change to require RTL and Offboard to always be on separate switches unless you have everything on one channel. I think that works for old and new.

**Comment by LorenzMeier** [comment]
Ok. Should off board and RTL be on the one-switch setup or should they just be a different class and always have their own switch? Does that make things easier / more consistent?

**Comment by LorenzMeier** [comment]
@AndreasAntener Merging this then after your test flight.
@DonLakeFlyer I don't think we need to support the old-style setup in new QGC builds. We'll do the first full release with the new-style RTL switch and our beta testers can deal with it.

**Comment by DonLakeFlyer** [comment]
> Should off board and RTL be on the one-switch setup or should they just be a different class and always have their own switch?

Doesn't matter to QGC. I can code it either way. But since it is an override kind of switch it think it would make more sense to be on it's own separate switch/channel.

**Comment by DonLakeFlyer** [comment]
Yup fixes size 50 char buffer:

static inline uint16_t mavlink_msg_statustext_pack(uint8_t system_id, uint8_t component_id, mavlink_message_t* msg,
						       uint8_t severity, const char *text)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
	char buf[MAVLINK_MSG_ID_STATUSTEXT_LEN];
	_mav_put_uint8_t(buf, 0, severity);
	_mav_put_char_array(buf, 1, text, 50);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), buf, MAVLINK_MSG_ID_STATUSTEXT_LEN);
#else
	mavlink_statustext_t packet;
	packet.severity = severity;
	mav_array_memcpy(packet.text, text, sizeof(char)*50);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), &packet, MAVLINK_MSG_ID_STATUSTEXT_LEN);
#endif

	msg->msgid = MAVLINK_MSG_ID_STATUSTEXT;
#if MAVLINK_CRC_EXTRA
    return mavlink_finalize_message(msg, system_id, component_id, MAVLINK_MSG_ID_STATUSTEXT_LEN, MAVLINK_MSG_ID_STATUSTEXT_CRC);
#else
    return mavlink_finalize_message(msg, system_id, component_id, MAVLINK_MSG_ID_STATUSTEXT_LEN);
#endif
}

**Comment by LorenzMeier** [comment]
Rebased and merged, thanks!

**Comment by kd0aij** [comment]
I just discovered that this PR breaks the "Dual-channel, 3-3 configuration" flight mode switching setup:
https://pixhawk.org/users/system_modes/mode_switch_config

**Comment by DonLakeFlyer** [comment]
Don't know about the firmware but QGC now enforces Return and Offboard switches to be on their own channel.

**Comment by kd0aij** [comment]
Guess I don't mind now that I'm using a 16 channel system.
And that explains why my RC parameters seemed completely hosed after RC calibration.
That procedure didn't say anything about Return or Offboard switches, or I didn't notice it.

**Comment by DonLakeFlyer** [comment]
Radio setup doesn't set Flight Mode switches. Flight Mode setup does. Wrong button.

**Comment by kd0aij** [comment]
Where are AUX1 and AUX2 documented?

**Comment by AndreasAntener** [comment]
I can see why the 3-3 dual chan doesn't work anymore.. we could change the precondition for RTL so that it only directly goes to RTL if it's really assigned to a separate channel. Else, the default behaviour would count (like it was before).

Or, 3-3 channel config needs to go. But this would contradict why I wanted RTL on a separate switch in the first place, because some radios don't allow for complicated mixing. 3-3 chan is a nice way if you cannot do mixing with your radio and are limited on channels. Opinions?

**Comment by DonLakeFlyer** [comment]
Channels/Switches need for various setups:
1) Main Mode - 3 position
2) Loiter/Pos Ctl - two position
3) Return - two/three position 
4) Offboard - two/three position

You can get a full setup without offboard with three extra channels. So a 7 channel radio gets you a pretty full set of control. That seems ok to me. Even add off board takes you to 8 which is a pretty common radio. Get fancier and add flaps and so forth you’ll need a nice radio but that still seems reasonable to me.

**Comment by AndreasAntener** [comment]
Ok, I think we'll just go ahead with this. I updated the docs for 3-3 dual channel: https://pixhawk.org/users/system_modes/mode_switch_config
And added the new image from Thomas to https://pixhawk.org/users/system_modes

**Comment by kd0aij** [comment]
I just noticed the comment above saying "beta testers can deal with it" :) Guess I should have been paying better attention to this PR.

It was probably an oversight to merge this before updating the wiki, since that will obviously cause confusion for users both new, old and "beta"

The wiki still talks about single-channel configuration, which is now impossible, and I suppose the dual-channel config should be renamed 3-channel config. Also, I'm guessing the reference to LOITER_SW in the new warning box should be RETURN_SW... and the threshold should be .5

**Comment by kd0aij** [comment]
Wait wait... This isn't in "stable", right? Changing the wiki will confuse "users"
I guess there should instead be a "beta wiki" and "beta users" should be warned that this PR breaks existing configurations.

**Comment by AndreasAntener** [comment]
Thanks for having a look. I fixed the warning box.

> The wiki still talks about single-channel configuration, which is now impossible

This is still possible as RTL will be the last one to trigger. Regarding support from QGC, IMHO these configurations are advanced and don't require "front end" support.

> I guess there should instead be a "beta wiki" and "beta users" 

Well we shouldn't go overboard with this? ;) I think that would make sense if master and stable diverge over a huge timeframe. But with good QGC support the users should be fine?

**Comment by kd0aij** [comment]
Sorry, I didn't notice that the single-channel thresholds had changed. I guess I can keep my 3-3 config using TX mixing. Perhaps it would be good to reorder the tables so that the threshold is monotonically increasing.
And there needs to be a head-up to testers when a commit is going to break their configuration. Could be a safety issue there.

**Comment by sjwilks** [comment]
I'm not sure it was known that this would break something. My approach is
that when testing master I don't assume all safety features and core
functionality are intact and have a short mental pre-flight or pre-extended
flight checklist. I should (though rarely do) test the important ones
before flying off, such as mag (rotate 360 deg. checking for jumps and
false headings) then hovering and testing althold, posctl, RTL.

**Comment by kd0aij** [comment]
Good advice. I did discover the breakage on the bench, but it took me a while to figure out that "Return and Offboard switches to be on their own channel." Would have saved me some time and confusion if I had known that in advance.

**Pull request closed without merging**
