### PR TITLE
Update submodule matrix to latest Thu Oct 31 12:40:12 UTC 2019

### PR DESCRIPTION
**Pull request by dagar**
- matrix in PX4/Firmware (403c157e2f66f1c4275c6bc835d85c8b101db7d1): https://github.com/PX4/Matrix/commit/92d1c8761ec8e5dbe9ba3f756cebd5e90956a1b2
    - matrix current upstream: https://github.com/PX4/Matrix/commit/215203fc6fcb87d79a1ad8ef390fd243e6306d08
    - Changes: https://github.com/PX4/Matrix/compare/92d1c8761ec8e5dbe9ba3f756cebd5e90956a1b2...215203fc6fcb87d79a1ad8ef390fd243e6306d08

    215203f 2019-10-23 Julian Kent - Automatic Differentiation 'Dual' Type (#100)

### CODE REVIEW

**Comment by dagar** [comment]
The build failures are real.

image

**Comment by jkflying** [comment]
This is actually choking the C preprocessor, crazy.

When I hack in a (completely invalid) change from:
```C++
template <typename Scalar, size_t N>
bool isnan(const Dual<Scalar, N>& a)
{
    return isnan(a.value);
}
```
to
```C++
template <typename Scalar, size_t N>
bool isnan(Dual a)
{
    return isnan(a.value);
}
```
It gets past the preprocessor at least, and the preprocessed output is:
```C
template <typename Scalar, size_t N>
bool 
# 238 "../../src/lib/matrix/matrix/Dual.hpp" 3 4
    (((sizeof(
# 238 "../../src/lib/matrix/matrix/Dual.hpp"
    Dual a
# 238 "../../src/lib/matrix/matrix/Dual.hpp" 3 4
    ) == sizeof(float)) ? __fpclassifyf(
# 238 "../../src/lib/matrix/matrix/Dual.hpp"
    Dual a
# 238 "../../src/lib/matrix/matrix/Dual.hpp" 3 4
    ) : __fpclassifyd(
# 238 "../../src/lib/matrix/matrix/Dual.hpp"
    Dual a
# 238 "../../src/lib/matrix/matrix/Dual.hpp" 3 4
    )) == 0)

# 239 "../../src/lib/matrix/matrix/Dual.hpp"
{
    return 
# 240 "../../src/lib/matrix/matrix/Dual.hpp" 3 4
          (((sizeof(
# 240 "../../src/lib/matrix/matrix/Dual.hpp"
          a.value
# 240 "../../src/lib/matrix/matrix/Dual.hpp" 3 4
          ) == sizeof(float)) ? __fpclassifyf(
# 240 "../../src/lib/matrix/matrix/Dual.hpp"
          a.value
# 240 "../../src/lib/matrix/matrix/Dual.hpp" 3 4
          ) : __fpclassifyd(
# 240 "../../src/lib/matrix/matrix/Dual.hpp"
          a.value
# 240 "../../src/lib/matrix/matrix/Dual.hpp" 3 4
          )) == 0)
# 240 "../../src/lib/matrix/matrix/Dual.hpp"
                        ;
}
```

So, it seems the `isnan` macro is replacing the function definition, then trying to pass in the function arguments with all their spaces into things like `sizeof`. Fantastic.

I'm not sure why I don't see this on other (eg. desktop) versions of GCC, but I'll make non-standard overload names for these particular functions so we can get around this.

**Comment by dagar** [comment]
There's quite a significant increase in flash with this update.

### Overflowing on fmu-v2.
image

### ~10.2KB increase on fmu-v5
http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/detail/PR-13336/7/pipeline/28

image

**Comment by dagar** [comment]
It's the additional work in the constructor.

image

**Comment by dagar** [comment]
We don't need to support GCC 4.8 if we bump the raspberry pi toolchain. https://github.com/PX4/containers/blob/master/docker/Dockerfile_raspi

**Pull request merged**
