### PR TITLE
Add missing sdlog and mavlink EKF status data

### PR DESCRIPTION
**Pull request by priseborough**
Fully populates the mavlink ESTIMATOR_STATUS message when using ekf2.
Requires https://github.com/PX4/ecl/pull/196 to be pulled in first.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Can you rebase on master? That should fix it.

**Comment by LorenzMeier** [comment]
And update the ECL submodule, of course.

**Comment by priseborough** [comment]
Done

**Comment by LorenzMeier** [comment]
So this is gated on test-flights. I'll arrange those.

**Comment by priseborough** [comment]
I performed a quick Indoor (with GPS) Flight test using a pixracrer board on a 250 class quad. The dataflash log is here:

http://logs.uaventure.com/view/GssDoEpRWgPkiLKBR4oaEU

**Pull request merged**
