### PR TITLE
WIP: New concept for unused parameters

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
This is a WIP to discuss a new mechanism for reducing the parameters which are sent across the wire. The current mechanism is too unstable. With the new parameter download speed, the driver behind this proposal is not to reduce load speed. The driver is usability. If we change to sending all params across the wire to fix stability then the user will get fixed wing params when they are flying multi-rotor. Not the end of the world, but somewhat confusing.

The basic idea is to reverse the state of unused parameters. Right now you need to reference a parameter to mark it used. My proposal is to reverse that and instead explicitly mark parameters as unused. But do it in such a way that is not a pain in the ass or inherently unstable.

First step is to make the parameter group be a first class value in the param struct as opposed to comment meta data. This pull is an example of one possible way to do this. This does two things:
1) It validates required group setting at compile time
2) It allows you to reference an entire set of parameters at once with a single value

Second step is to implement a param api which marks an entire group of parameters as unused using these new group identifiers.

Third step is create small apps, that when run, use the above new api to mark the appropriate parameter groups as unused. One app each for fixed wing, multi-rotor and vtol. For example the multi-rotor would use the new api to mark the FW_ATTITUDE_CONTROL_PARAMS group from this pull as unused, amoung others. After marking the correct groups as unused they would just exit.

Third step is to modify the rc.*_apps to call the apps created above appropriately.

This would provide a highly visible mechanism to reduce the parameters to the appropriate set based on airframe. Also if something went wrong with ordering with respect to responding to the PARAM_GET mavlink message, more parameters than necessary would come across the pipe. Which is better than the opposite which is currently the case. For folks creating fully custom airframes with scripts, they are more likely to include params they don't need instead of forget to reference ones they do need. Once again the opposite of the current state.

Putting this up as conceptual WIP. I'll be happy to finish it if there is agreement on the approach.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Should I give up on this concept or keep going?

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Leave the PR in, but I'd like to first address something else, which is the root cause of user complaints: Essentially all the complaints you received in the last days are because of an aborted system boot. I'm signalling this now to the user with a critical text message. However, the critical message just turns an icon red, while the missing parameters create a modal dialog. This is absolutely not user-friendly, because the modal dialog is there for a pure technical reason (because the param subsystem signals an error in QGC).

This leads to the user thinking there is an issue with the parameters, instead of learning that his boot was aborted (which is in 90% of the cases because of custom stuff he put into text files and forgot).

We need to drive the UI from the user perspective instead - step one would be to present critical system warnings in a way which is impossible to miss from a user perspective. *All* of them need user intervention of some sort, so they should be really, really hard to miss.
I burn each day 30 minutes for unnecessary user support because they don't realise these messages are there. @dogmaphobic I presume you're busy as well, so just FYI.

**Comment by dogmaphobic** [comment]
The existing code within QGC is quite blunt when handling different message types. It only recognizes three types: *Error*, *Warning*, and *Normal*:

```
   switch (severity)
    {
    case MAV_SEVERITY_EMERGENCY:
    case MAV_SEVERITY_ALERT:
    case MAV_SEVERITY_CRITICAL:
    case MAV_SEVERITY_ERROR:
        <... handle "error" message ...>
        break;
    case MAV_SEVERITY_NOTICE:
    case MAV_SEVERITY_WARNING:
        <... handle "warning" message ...>
        break;
    default:
        <... handle "normal" message ...>
        break;
    }
```

I just need to know what is the desired behavior for the (currently consolidated) types and I can add the code to handle it. In summary, what should happen when an *Emergency*, *Alert*, *Critical*, and *Error* message arrives? Are *Notice* and *Warning* truly the same?

**Comment by LorenzMeier** [comment]
Warning should just light the icon in yellow, but everything else should result something non-modal pop up.
Maybe the OS notification system like on Mac OS? Happy to reduce number of messages above warning in return.

**Comment by dogmaphobic** [comment]
I will spend some time this weekend paying more attention to the messages. It's common for me to see dozens of *Error* messages even though there is nothing truly *erroneous* about the system. I will also see what I can come up with regarding some kind of pop up dialog. Note that there is no concept of "non modal" for mobile platforms.

**Comment by DonLakeFlyer** [comment]
Wait till I have time to reply to this

**Comment by DonLakeFlyer** [comment]
I think the thing to do is use the existing parameter load/fail as a vehicle end boot trigger. When that triggers, go to MavManager and collect up the mavlink messages above a certain  MAV_SEVERITY_* threshold. I'm not sure what that threshold is as far as MAV_SEVERITY goes? If there are messages, indicate the possibility of incorrectly configured firmware or possible firmware issue and show the user those messages. If there are not mavlink messages then show just the usual parameter error. Prior to arming in this boot stage I think you need to put up something modal. You need to hit the user over the head with the information otherwise nobody pays attention. In this state it's a bad idea to fly.

After you are past this initial boot trigger sequence. Then you fall into the mode of some new way to display critical stuff to the user as it comes up using a non-modal mechanism.

**Comment by LorenzMeier** [comment]
Not doing this for now, but please retain the branch.

**Pull request closed without merging**
