### PR TITLE
commander add parameters for eph, eph, evh thresholds

### PR DESCRIPTION
**Pull request by dagar**
This PR adds separate parameters for required eph, eph, evh thresholds. Previously eph and epv thresholds were set from COM_HOME_H_T and COM_HOME_V_T.

COM_POS_FS_EPH

COM_POS_FS_EPV

COM_VEL_FS_EVH

https://github.com/PX4/Firmware/issues/8260

### CODE REVIEW

**Comment by priseborough** [comment]
Can you provide a link to an issue or a brief description of the problem this solves.

**Comment by dagar** [comment]
This is in response to issue https://github.com/PX4/Firmware/issues/8260.

**Comment by dagar** [comment]
TODO: add parameter descriptions and test

**Comment by dagar** [comment]
We should also start thinking about how to handle VTOL differently. @sanderux @bresch FYI

**Comment by sanderux** [comment]
If we make these params FW and MC i think we solve both problems at once and allow setting suitable standards for both

**Comment by dagar** [comment]
Ok, let's think about a good way to introduce this kind of thing to the system for VTOL. We don't want tons of parameters to be split FW/MC where possible.

Is there some other architecture that really defines what's needed? For example could the position controller be the one stating the required position and velocity error thresholds?

**Comment by sanderux** [comment]
How about scaling it on ground speed?

**Comment by dagar** [comment]
@sanderux some kind of scaler might work short term, but there's a lot more we're going to need to do in this area.

@priseborough my suggestion above may also (inadvertently) let us jump straight into changing the thresholds based on context.

FW
 - takeoff (at different stages)
    - includes pretakeoff (on the ground about to arm and then launch)
 - general cruise flight (waypoints at sufficient altitude)
 - landing (at different stages)
MC
 - takeoff
 - general navigation
 - regular landing
 - descend (landing velocity only in a failsafe)
VTOL
 - need to think about transitions only
 - otherwise respects regular MC or FW

With all of this information we can set the thresholds appropriately based on vehicle type and the specific situation. We need to get the architecture right to handle all of this without commander complexity continuing to explode.

**Comment by Antiheavy** [comment]
I like the direction this conversation is heading.  Is it worth setting thresholds based on vehicle type or is scaling according to actual dynamics both simpler and more appropriate?  My guess is ground speed and/or acceleration would be useful in modeling appropriate error thresholds.

**Comment by dagar** [comment]
What if we added a new message that's something along the lines of "navigation requirements".

**navigation_requirements**
 - maximum eph
 - maximum epv
 - maximum evh

This could either come from the currently active position controller, or from the land detector, which has effectively turned into "vehicle model". It's now also publishing things like a maximum altitude (based on remaining battery capacity) for limiting navigation altitude. We could also finally rename land_detector -> vehicle_model.

**Comment by priseborough** [comment]
That moves us closer to context based thresholds which is where we should be aiming.

**Comment by priseborough** [comment]
Agree

**Comment by Antiheavy** [comment]
@dagar @priseborough here is a fixed wing flight log that shows a short period of "loss of global position" 

https://logs.px4.io/plot_app?log=99e99083-379d-43fe-869c-f0e41b77ba3b

I don't see anything obvious in the logs as to why, but there is a growth in vert and horz accuracy coinciding with a change in "GPS Fix" from 4 to 3.
image

Is this loss of global position failsafe kicking in too prematurely?  
Would the new params in the PR be an appropriate method to improve this?

**Comment by dagar** [comment]
@Antiheavy that looks like an actual loss of GPS (temporary). For about 10 seconds there was no data published from the GPS.

image


image

This triggered the loss of GPS nav state (fixed bank loiter). These GPS checks were only just removed recently (https://github.com/PX4/Firmware/pull/8914). If the same thing were to happen again the failure state would only trigger as a result of estimated position error (green & red above). So coming back to this PR you can now tolerate a loss of GPS until the errors passes a defined threshold, and that threshold is now by default set much larger for FW.

**Comment by dagar** [comment]
I've rebased on master to resolve the conflicts.

@priseborough could you please review?

**Comment by priseborough** [comment]
The changes look OK. How have you tested it (noting that our CI does not appear to include tests for these types of failsafe events)?

**Comment by dagar** [comment]
Going through some testing in SITL by killing GPS and condition_local_position_valid is going to false very quickly.

image

**Comment by dagar** [comment]
About 1 second after GPS loss, the EKF reports vehicle_local_position xy isn't valid. 

image


@priseborough should commander bother using the valid flags? 

https://github.com/PX4/Firmware/blob/877d212a335e9113c8ddd8f133c27794504cf9fc/src/modules/commander/commander.cpp#L2012-L2013

**Comment by priseborough** [comment]
Make sure you have sideslip and airspeed fusion running so it can dead reckon

**Comment by dagar** [comment]
It looks like it wasn't defaulting on for SITL.

**Comment by dagar** [comment]
Rebased and updated the plane SITL model to enable EKF2 airspeed and synthetic sideslip fusion.

**Comment by dagar** [comment]
SITL test flight with GPS stopped (:52), restarted (05:45), and stopped again (06:35).

https://logs.px4.io/plot_app?log=8c3267bd-91b5-4031-93d4-6c81d58f587f

**Comment by dagar** [comment]
Questions
 - why didn't vehicle_global_position deadreckoning ever change?
 - why did the commander flags for local position and local velocity validity change so frequently?

image

image

**Comment by dagar** [comment]
@priseborough I did some debugging and the consistent blips of !xy_valid and !v_xy_valid are the result of the time between each synthetic side slip measurement (https://github.com/PX4/ecl/blob/041886a28957c17505b19367eb8703444123a4c3/EKF/control.cpp#L1119), and the no aid timeout max check in Ekf::inertial_dead_reckoning() (https://github.com/PX4/ecl/blob/041886a28957c17505b19367eb8703444123a4c3/EKF/ekf_helper.cpp#L1259). 

What would you recommend? Is it appropriate to increase the timeout for last beta fuse?

**Comment by dagar** [comment]
Increasing the synthetic sideslip fusion frequency would also work.

**Comment by priseborough** [comment]
I think increasing the frequency of fusion is the answer. I would reduce beta_avg_ft_us from 1000000 to 150000 (avoid 5 and 10Hz because it is used by other sensors)

**Comment by dagar** [comment]
ECL PR decreasing synthetic sideslip fusion interval. https://github.com/PX4/ecl/pull/407

**Comment by dagar** [comment]
That's better. https://logs.px4.io/plot_app?log=ac75a8f5-07fe-4dcb-9adc-c94e7175952b

GPS is killed (gpssim stop), and you can watch eph grow until it exceeds 62.5 (2.5 * COM_POS_FS_EPH), then the plane enters the fixed bank angle.

image

**Comment by dagar** [comment]
Here's vehicle_global_position (estimated global position) vs gazebo groundtruth.

image

image

**Comment by dagar** [comment]
Here's another one after the last two commits. https://logs.px4.io/plot_app?log=05010450-ac7c-4336-b720-7e2712eed991

Condition flags plotted with small offsets for visualization.

image

**Comment by dagar** [comment]
@priseborough @RomanBapst this should be good to go, please review again.

**Comment by Avysuarez** [comment]
flight with pixhawk 3 pro V4pro. Good flight no isuuses.
https://review.px4.io/plot_app?log=4b8c5f52-53a1-4c52-8ef8-ea5e45400cfc

Flight with pixhawk 2.1 V3.  Good flight, no issues.
https://review.px4.io/plot_app?log=9025fe1c-dd95-4bf8-8128-5bcbe4cf0387

**Comment by santiago3dr** [comment]
Few flights on a Pixracer (v4)
indoor flight after a full reset and a re-calibration using all default parameters:
https://logs.px4.io/plot_app?log=3a548922-1207-42fb-875d-16113efd2c80

full outdoor test using all default parameters:
https://logs.px4.io/plot_app?log=7328b415-8e37-4edf-b0f2-4901df44eb16
manual take-off; good manual flight; seamless transition from stabilized to altitude mode; very abrupt cornering in auto

https://logs.px4.io/plot_app?log=3e064843-776f-408e-90dd-2a56f882272b
adjusted a few MC and MPC values; improved cornering; good flight but I feel it could still be improved by changing some of the default parameters for the Flamewheel F450 frame

**Comment by r0gelion** [comment]
FW testing pending

**Comment by dannyfpv** [comment]
flight pixmini v3 great:
https://logs.px4.io/plot_app?log=7fd2af8e-b8b7-48e6-8f34-f3729148167c

**Comment by priseborough** [comment]
Normal flight testing is not sufficient for these changes. It requires SITL or flight testing with a rotated magnetometer or incorrect declination value to induce a loss of navigation.

**Comment by dagar** [comment]
That's what my SITL testing above was trying to accomplish. Killing the simulated GPS and explicitly testing commander failsafe thresholds that are now parameterized. I also found and fixed a few other minor check_posvel_validity issues along the way.

I requested additional flight testing to catch any other general regressions given the amount of commander churn.

**Comment by priseborough** [comment]
Was that testing restricted to FW?

**Comment by dagar** [comment]
Above was FW with dead reckoning, but I also tried MC briefly. Commander almost immediately changes the validity flag once GPS is lost because the EKF local position reports `xy_valid = false`.

image

**Comment by priseborough** [comment]
That is current behaviour. Given the  inability of the nav to dead reckon without airspeed and sideslip constraints we could extend it by 5 seconds.  Are you stopping GPs lock using the  'gpssim set -t 0' command or stopping data completely?

**Comment by dagar** [comment]
Stopping GPS entirely, although `gpssim set -t 0` looks about the same.

image

**Comment by priseborough** [comment]
The timeout to report position invalid after a period of inertial deadreckoning is set by a no_aid_timeout_max parameter inside the EKF. It is currently set to 1 second (1000000 uSec)

It could be added to the list of tuneable parameters in ekf2_main.cpp

**Comment by priseborough** [comment]
I will submit a PR with the ekf2 module changes required to adjust it. I think a default value of 5 seconds would be acceptable for most applications. If required for indoor experiments, a  smaller value can be set.

**Comment by priseborough** [comment]
Would it make more sense to add the patch to this PR?

**Comment by dagar** [comment]
Yes we might as well test it altogether.

**Comment by priseborough** [comment]
When I try building this branch, it is unable to access the mavlink submodule reference:

Submodule ‘mavlink/include/mavlink/v2.0’ (https://github.com/mavlink/c_library_v2.git) registered for path ‘../../../mavlink/include/mavlink/v2.0’
error: Server does not allow request for unadvertised object 37d14af47d783eb516959cc10e4cf70d66e927c0
Fetched in submodule path ‘../../../mavlink/include/mavlink/v2.0’, but it did not contain 37d14af47d783eb516959cc10e4cf70d66e927c0. Direct fetching of that commit failed.
error: Server does not allow request for unadvertised object 37d14af47d783eb516959cc10e4cf70d66e927c0
Fetched in submodule path ‘../../../mavlink/include/mavlink/v2.0’, but it did not contain 37d14af47d783eb516959cc10e4cf70d66e927c0. Direct fetching of that commit failed.

**Comment by dagar** [comment]
There are no mavlink changes in this PR. I would try `make distclean` followed by `make submodulesclean`. If you're using a git gui it might be different.

**Comment by dagar** [comment]
You might also have an old reference, this branch has been rebased and force pushed multiple times.

**Comment by priseborough** [comment]
Thanks. The usual 'make distclea'n and 'make submodulesclean' didn't work, so I ended up deleting all files in the Firmware directory and checking out the branch and all submodules again.

**Comment by santiago3dr** [comment]
Flight on flying wing running pixhawk mini (v3)
https://logs.px4.io/plot_app?log=12c76c64-2028-4ff6-b115-8d5eda4bfe0b

roll input was not responsive in stabilized, had to opt out with manual

**Comment by dagar** [comment]
@santiago3dr that's unrelated to this PR.

You need to reset the fixedwing maximum rollrate (FW_R_RMAX). There's a somewhat recent change in master that means 0 is now interrupted as maximum rate of 0 (disabled).

I would try to periodically reset all of your parameters from the stock airframes so that any bogus setting don't persist.

image

**Comment by santiago3dr** [comment]
Fresh flash; reset parameters and it seems the default for Generic Flying Wing is 70 deg but when loading the frame for Phantom FPV Flying Wing is 0.0 by default

Can we check other fixed wing configurations to assure said parameter does not default to 0.

**Comment by dagar** [comment]
@santiago3dr that's definitely wrong. Fixed here https://github.com/PX4/Firmware/pull/9135
I also did a quick sanity check of the other airframes and didn't see anything else quite that egregious.

**Comment by priseborough** [comment]
The priority test to conduct in SITL is to verify for multirotor platform types that the system correctly failsafes into land following takeoff initiated by console command 'commander takeoff' when the magnetometer is misaligned by a large amount. 

In the past for SITL testing I have tested with yaw misalignments of 45, 90, 135 and 180 degrees but ended up applying the rotation in the ekf2_main.cpp file because the SITL mag driver does not support use of the CAL_MAG*_ROT parameter. I have performed the 90 and 180 degree tests with this branch and both transitioned to land as expected with the following console output:

screen shot 2018-03-22 at 11 57 19 am

However neither case disarmed after landing which was unexpected. This behaviour was present for master so is not a problem with this PR. If the landing was commanded from the console, then the vehicle does disarm, so there is something inside commander to investigate as a separate issue.

**Comment by dagar** [comment]
Rebased on latest PX4 master requiring a switch to the new parameter wrappers.

TODO
 - mag sim add rotation
 - investigate land detector issue (https://github.com/PX4/Firmware/pull/8771#issuecomment-375146157)
 - investigate GCS altitude display/update after loss of valid position
 - SITL test multicopter with mag rotation

**Comment by dagar** [comment]
Requires https://github.com/PX4/ecl/pull/413.

**Comment by dagar** [comment]
Magnetometer sim driver rotation is ignored because the system thinks it's internal.

**Comment by dagar** [comment]
Multicopter SITL test with mag driver rotated yaw 90 degrees. 

https://logs.px4.io/plot_app?log=05a0600d-75c9-4377-94e7-9194e304dcc3

image

**Comment by dagar** [comment]
> However neither case disarmed after landing which was unexpected. This behaviour was present for master so is not a problem with this PR. If the landing was commanded from the console, then the vehicle does disarm, so there is something inside commander to investigate as a separate issue.

Land detector debugging - https://github.com/PX4/Firmware/pull/9157

**Comment by dagar** [comment]
vehicle_global_position dead reckoning flag still not reporting correctly.

This is after `gpssim stop` with gazebo plane.
image

**Comment by dagar** [comment]
Small issues with vehicle_global_position continuing to publish briefly after "EKF stopping navigation" with eph and epv set to 0. This makes commander think global is valid again temporarily.

image

**Comment by priseborough** [comment]
Can you describe the steps you followed to produce that result? I have tried with the MC sim and was unable to.

**Comment by priseborough** [comment]
I tested using the FW sim using the following procedure:

'make posix gazebo_plane'
'commander takeoff'
switch to attitude control and climb to 250m
switch back to hold mode
turn off gps using 'gpssim stop'
switch to attitude mode and glide down.

The EKF does stop air data dead reckoning eventually because the numerical stability of the air data fusion deteriorates over time. I will raise a bug report for it and fix.

screen shot 2018-03-26 at 12 23 28 pm

**Comment by dagar** [comment]
Updated ECL (https://github.com/PX4/ecl/pull/413) and rebased on master.

**Comment by JonReacher** [comment]
For FW at the moment, would it be beneficial to change to COM_POS_FS_EPH 25 and COM_POS_FS_EPV 50 for now until this gets merged? 
Same for change to EKF2_MAG_TYPE 1 with EKF2_MAG_ACCLIM 0 and EKF2_MAG_YAWLIM 0?

**Comment by dagar** [comment]
Rebased on master.

**Comment by priseborough** [comment]
The orb_copy(ORB_ID(airspeed), _airspeed_sub, &airspeed) function call in ekf2_main is returning false

**Comment by dagar** [comment]
The orb_copy check was wrong. It returns OK (0) on success, which is completely wrong when treated like a bool.

Once this settles we should talk about CI tests covering a range of core features. For example in this case we could enable wind in gazebo plane, run a basic mission test, then once it's finished validate from the ulg (EKF control status, wind estimate matches gazebo configuration, etc).

**Comment by priseborough** [comment]
I found the bug in ecl causing the failure and have pushed the fix to https://github.com/PX4/ecl/pull/413

**Comment by dagar** [comment]
FW test (gps stop) - https://logs.px4.io/plot_app?log=876c333b-a9cf-4290-8c7a-465f4a23142c

image

We're still slightly out of sync with local_position xy_valid.

image

**Comment by dagar** [comment]
@priseborough there are still minor issues here, but to be honest this is still much better than what's currently in master. I think we should consider merging and then continue iterating (https://github.com/PX4/Firmware/pull/9363).

**Comment by dagar** [comment]
https://github.com/PX4/ecl/pull/413 is merged, I updated this branch to ecl master and squashed into 
8caf3ae.

**Pull request merged**
