### PR TITLE
Multicopter mixer saturation handling strategy

### PR DESCRIPTION
**Pull request by bresch**
After having some issues just after back-transition with a standard VTOL, I found that the problem came from the multicopter mixer.
Since after back-transition the wings can still produce quite a lot of lift with high AOA and high-lift wings, the multicopter thrust is close to zero and the motors are directly saturated when trying to compensate attitude errors. In this special case, the initial 'boost' technique - a gain applied to the thrust - is ineffective:
- If thrust is close to zero, `thrust * thrust_increase_factor` is also close to zero...

The 2nd issue highlighted by @sanderux in #7871 is that when the altitude control is active, the thrust saturates the outputs and attitude control becomes sloppy. 

I made several passes to first simplify the code and finally rewrite the saturation handling process in order to get rid of the arbitrary boost gains and make the attitude control the highest priority.

Before implementing in PX4, I first made a python script to simulate the different cases, you can try here:
https://gist.github.com/bresch/8ea4232452bc64de1ed780bcfbee3564

Be aware that I never tested this PR in reality and that the mixer code is critical. Be careful when testing!

### CODE REVIEW

**Comment by bresch** [comment]
@eyeam3 Please also try this PR on the Falcon Vertigo if you have time.

**Comment by dagar** [comment]
That's certainly much simpler. Does anyone know how the current mixer evolved? What do you think @Stifael @MaEtUgR?

I'm not necessarily suggesting it here, but one thing to be aware of is we could have special multicopter mixer classes for quadplanes if needed.

**Comment by Stifael** [comment]
not sure if an additional mixer is needed for quadplanes, unless people are very happy with the current multi-copter mixer. My personal opinion agrees with what @bresch is suggesting to have attitude highest priority to allow full attitude control even at zero thrust (which is currently not the case). However I know that opinions tend to differ sharply and depends a lot on the use case (someone who flies a racer would definitely prefer full attitude control).

**Comment by dagar** [comment]
Right, I mainly want people to understand the possible level of flexibility we have here. It would be easy to have a couple different implementations that extend MultirotorMixer and only make minor changes.

Would unit tests help verify intended mixer functionality and any edge cases? 
@diegoeck I believe you offered to help write mixer testing a long time ago. What do you think?

**Comment by diegoeck** [comment]
Hi @dagar! Sure I can help. I have already study the mixer some time ago (and corrected some bugs), and I was planing to simplify the code in the next weeks with one of my students. I think that the code is very complicated, and it would be nice to better understand how it evoluted. Sometimes I think that a really simple mixer (with no priorities) would perform better, but it is difficult to say. Sometimes altitude should have larger priority, sometimes attitude, so maybe no priority would work.. Many will say that's not the way. My idea was to test in simulation many scenarios and compare performance, but I have only experience with quads and I would need help with VTOL.

**Comment by sanderux** [comment]
It seems to me that (at least at a certain point) prioritizing altitude over attitude would be pointless. When the vehicle is at a 25 percent bank angle there seems to be little point in increasing thrust to gain altitude. I think it would be much more efficient to prioritize the attitude and as soon as we are level try altitude.

@AndreasAntener thoughts?

**Comment by mrpollo** [comment]
@dagar should we have @PX4TestFlights test this PR?

**Comment by bkueng** [comment]
I think I hit that problem as well recently: https://logs.px4.io/plot_app?log=6c4e8474-63dc-4a54-b2ca-9f9ee05566e0
This is on a normal quad. You can see several very large overshoots in roll/pitch angle (going over 90 degrees), for example the roll angle at 5:10. It can be quite easily reproduced by tilting in one direction to the maximum, then quickly tilt towards the other direction and at the same time reduce throttle to zero. The attitude will then overshoot.
To me, it looks like it is due to the same problem: thrust is too low so that the attitude is not corrected anymore.

@mrpollo I think we should first do more SITL/HITL testing, before putting this on a vehicle. If you are brave enough, then sure, flash it! :) But keep the kill switch ready.

**Comment by LorenzMeier** [comment]
@PX4TestFlights Could you please do a careful test with kill switch ready?

**Comment by santiago3dr** [comment]
couple flights with the pixracer (V4)
indoor test:
https://logs.px4.io/plot_app?log=bb16acb6-6c11-4709-9f9e-3ca3e21b93a6

full outdoor test:
https://logs.px4.io/plot_app?log=39645de4-118e-486b-ac0d-d24b1a797885

**Comment by dagar** [comment]
@diegoeck would a mixer unit test be helpful or should we do it within a larger simulation? How would you compare performance or identify failures?

**Comment by sanderux** [comment]
I can perform the same test i did before, it is repeatable and quite obvious when it happens. Just need to wait untill the weather becomes a bit calmer. Expected for this weekend.

**Comment by bkueng** [comment]
I tested this as well, first in HIL and then on a quad with pixracer. I mapped aux1 to the previous behavior to switch in-flight (see branch  [manual_input_rework_mixer_rework](https://github.com/bkueng/Firmware/tree/manual_input_rework_mixer_rework), which is on top of #7940).

Tested:
- full/zero throttle (free fall)
- fast roll & pitch changes, including yawing
- I set the minimum throttle to 0% and the max to 100% (`MPC_MANTHR_MIN` and `MPC_MANTHR_MAX`), in all the logs.

Logs:
- https://logs.px4.io/plot_app?log=91bab7bb-ada3-4f41-a9ac-b6e9a5e35f3c
- https://logs.px4.io/plot_app?log=c188ea0c-be3b-4056-9791-2d9449f74a59
- https://logs.px4.io/plot_app?log=02c01bd8-b04d-44f4-b9c8-b4d2ada35660
- https://logs.px4.io/plot_app?log=3577dc70-49f6-40a4-bd55-a1c29d091e98

Observations:
- the large angle overshoot when reducing throttle to 0 (see above post), does not happen anymore. In fact when I tested with the old behavior, it overshot by so much, that it did a full 360 degree roll rotation (first log, 4:37). Thus answering the question whether PX4 can handle flips: yes it can 😃 
roll_flip
- roll & pitch stay controllable in freefall even with 0 throttle (I tested with the previous as well: the vehicle just tips over). However yaw is not controllable.
- you can safely go to 100% throttle.

Conclusion: I'm confident flying this, it behaves as it should, but I can't say that I covered all the corner cases.

**Comment by sanderux** [comment]
We will be flying this this weekend and will duplicate the behavior in #7871

**Comment by r0gelion** [comment]
Unassigned @PX4TestFlights, reassign if needed.

**Comment by MaEtUgR** [comment]
You were faster! 😄 
Pretty much the same changes I had on my list to propose. Here I posted the code before: https://github.com/PX4/Firmware/issues/4221#issuecomment-292164694

I want to share with you the **only** reason why I did not make a pr for my version yet:

While the logic behind this calculation is pretty simple and increases performance drastically you also have to consider flying safety. As long as the vehicle is in a normal state and the actuators effectuate in the desired way it only helps. But as soon as there is something wrong this logic can make a bad situation like unstable flight a lot worse like uncontrolled full throttle shootout.

For most of the flights this might be no concern and even when the vehicle crashes anyways you might not bother. The situation I have in mind where you would like to have a "safe mode" is if you build for example a >20" prop size multicopter, you build everything, do your first flight test and something in the configuration is wrong (too high gains, wrong prop orientation whatever...), you realize it and go to low throttle but the controller goes unstable and the mixer puts out a high total thrust, until you disarm a lot can go wrong...

Maybe I'm overcautious but I wanted to find a solution to this problem before proposing a change like this. Now you were faster and I'm at least not responsible for the crashes 😉

**Comment by bresch** [comment]
@MaEtUgR I'm fine contributing to natural selection :) 
I'm joking, I'm fully aware that the boosting can be dangerous is something is wrong in the setup but I don't think that the mixer is the correct place to make any safety intelligence. In my mind, the mixer should just do its best to make the response of your quad as close as possible to the desired controller output. If your controller makes your system unstable, it's not the mixer job to do anything against that.
Furthermore, for the mixer point of view, a flip recovery looks the same as an unstable controller and it should not limit it.

**Comment by MaEtUgR** [comment]
@bresch I like your joke xD I totally agree and just didn't want to strike the ideology which I read out from the old implementation. At least not by default. As I say probably my thinking was too cautious.

On topic: We did some tests today with the new mixer on a 450 and a 210 racer and for LOS (line of sight) attitude controlled flight it reacts as expected a lot better when having low throttle. You can also hear the motor speeds of the racer reacting very fast to change attitude when not giving any throttle similar to KISS FC and co. Yaw tracking still has room to improve, I think you concentrated on roll pitch here right? I would have some logic to test also for yaw boosting.

The thing I found strange is I did a test flying the racer FPV (first person view) with live video and there you can do a lot more acro stuff because you can easily see the orientation also when being high up and further away. In these tests when I went off the throttle in acro mode the racer got nearly uncontrollable and sometimes even flipped. Don't get me wrong it feels better than before but not completely as I was expecting coming from other race controllers... I have to investigate the logs tomorrow to see if I can find out why exactly that happened. In principle it could be an idle motor speed problem or alike...

**Comment by MaEtUgR** [comment]
Here are the two FPV racer test logs. There's always a big junk acro in the middle. The first log had the old mixer for comparison enabled until 10:14 where you can see the logged message of the switch.
https://logs.px4.io/plot_app?log=2a61b748-e306-40b8-bb01-887fd56a0e77
https://logs.px4.io/plot_app?log=9e29a05d-9c4a-4955-ba9d-c4d2028cd4b4

I had a look at the logs and it's a bit harder to get a feel of what happened than when you actually see it while flying but when looking at the roll rate and pitch rate plot I can clearly see that it's not always following correctly. I maybe need to overlay this with the actual thrust value...

**Conclusion:** In normal flight these mixer changes only improve performance but in my tests it wasn't perfect yet.

**Comment by sanderux** [comment]
Concerns raised in the devcall by me and @julianoes:
1. Landing on uneven slope
2. Overshooting due to high integrators could lead to flyaway

**Comment by bresch** [comment]
## "Landing on uneven slope"
For this first concern, only a tightly tuned multicopter with a strong integrator can compensate the torque produced by the weight of the drone when touching one leg on the ground. This can be simply represented as follows: 
- When the drone is flying normally or on free-fall, the pivot point is the CG and the attitude controller makes the drone turn around this point.
- When the drone touches the ground (with a leg not under the CG), the pivot point the shifts to the contact point and the mass of the drone appears in the moment equation as a constant value. This can be seen as a constant disturbance and can be compensated if the controller has an integral part that can grow enough to lift the mass of the drone (the inertia also increases but that's not important for this static analysis).

From this, it should be highlighted that:
- A tightly tuned controller with high disturbance rejection performance is theoretically capable of leveling the drone while being on a slope already without the mixer modifications. The new saturation handling in this PR however makes this effect easier to achieve (which is not desirable if you want to land)
- Most of the drones using PX4 have only a small integrator and its effect is clamped to a low value. Such a behavior is then unlikely to happen except for overpowered drones and those using different more robust controllers.

After discussing with a Racer pilot and having a look at the mixer code of [BetaFlight](https://github.com/betaflight/betaflight/blob/c612280c1a7b34fde623faf6a2af8a8cc4e1be30/src/main/flight/mixer.c#L734), I saw that on racing autopilots, one can set a parameter (i.e.:`airMode`) to enable or disable saturation handling if the total desired thrust is below a specified value. 
This solution will remove the landing problem on those highly stable drones during landing while still having the benefit of the high-saturation part handling of this PR (safely go to full throttle).

A second solution that should be investigated is on the land-detector side. (Maybe @MaEtUgR can help with this). After a ground touch detected, the land-detector could tell the controller to gently decrease its authority (is it possible or the rolling/pitching movement will make the land-detector quit the ground touch state?)

## "Overshooting due to high control gains could lead to flyaway"
I don't really see how an unstable drone can fly away. The boosting part cannot create more thrust than required to exactly unsaturate a motor. It means that it can help the drone to turn around its CG but will not generate lift.
Furthermore, one should always be aware that playing with control loops parameters is dangerous and can lead to damages and should have a kill-switch ready.

Am I missing anything? Could you comment on this @sanderux @Stifael @MaEtUgR so we can move forward?

**Comment by Stifael** [comment]
about landing on uneven ground:
the landdetector goes through three states, where at each states the thrust setpoint is adjusted within the mc_pos_controller. For instance, at ground_contact, the mc_pos_control sets the thrust_setpoint along Body x and y to zero. Maybe it would make sense to move this kind of logic to the attitude controller instead.

**Comment by julianoes** [comment]
> I don't really see how an unstable drone can fly away. The boosting part cannot create more thrust than required to exactly unsaturate a motor. It means that it can help the drone to turn around its CG but will not generate lift.

If the oscillating thrust on either side + minimum throttle is higher than hover thrust, it will rise up uncontrollable, I think. You are right that "safe" PID gains would prevent that but I'm mostly worried about the case where somebody flies the first time with gains that are too aggressive.

I think we could try this out here and see how easy it is to reproduce (if at all 😄 ).

**Comment by bresch** [comment]
I did a free-fall test with a delta wing VTOL (Falcon Vertigo) without this PR and with this PR, the difference is huge.

With old mixer:
https://logs.px4.io/plot_app?log=f2642235-c6f2-49b5-a781-ae3f4138c904

With this PR:
https://logs.px4.io/plot_app?log=6af9c861-c775-44be-8124-1e0190345b5a

@MaEtUgR Do you convert the requested thrust for a motor with a square root before sending it to the output? That will help to linearize the system and could make the quad more stable at low RPM.

**Comment by dagar** [comment]
@bresch there's a motor thrust adjustment here (just below the code changed in this PR) -
 https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/mixer/mixer_multirotor.cpp#L356
When output is through the px4io or px4fmu it's set from the THR_MDL_FAC param.

**Comment by bresch** [comment]
@dagar True, but the default value is 0.0, I don't know if it's widely used; do you know if it works properly? I'm not completely convinced by this equation.

**Comment by dagar** [comment]
I doubt it's widely used, and I haven't verified it. Here's the original PR - https://github.com/PX4/Firmware/pull/5287

**Comment by MaEtUgR** [comment]
@bresch Sorry for the response delay.
- **Uneven slope:** My KISS racer with airmode stays level when I land on uneven slope until I disarm. I never land on strong slopes or then I would disarm when I'm just above the ground. The default on KISS was that it stops to give authority when you give very low percentage of thrust but I crashed once because of that because you usually go low un thrust during loopings because you don't want to linearly accelerate while being upside down and it stops to turn further when you go too low on thrust, scary moment...
I think we should have an "airmode" way to disable the feature and in KISS it's done by setting the minimal throttle to the actual minimal throttle which you would never do without airmode. A land detector based automatic check would be possible and nice but needs a lot of testing and is hence a whole new feature in my eyes.
- **Too high control gains:** The thing is is you have for example too high roll/pitchrate D you can easily get into an oscillation where the controller constantly wants to compensate the error and rises the quad all the time, it's also achievable with current PX4 if you push the gains hard, I went to the limits with the PX4 racer once and the thing you do in this moment is go off the throttle and it comes out of this oscillation but if you allow it to turn up throttle automatically you could risk that it continues building up altitude in this state and you can only stop by killing. I agree that you anyways need to know what you're doing when you're tuning the gains because you can screw up in so many ways that I don't think airmode would make it worse. I would probably disable for intial tuning and therefore by default and add documentation?
- **Another "yaw" case** I ran into using airmode with my KISS racer is: I disabled the stick gesture disarming because you can accidentally disarm like this while fully yawing with no throttle (hapened with PX4 before right @julianoes ;) and when I don't remember this and doo the gesture it demands such a high yaw rate that the quad goes up in a spiral (with the stick on zero thrust) and I never broke anything like that but it's unexpected.
- **Square root throttle output:** Yes I had this for my master thesis because the bebop 1 frame I used had much more linear throttle response, it wasn't optimal because the function is in practise maybe not exactly quadratic but it was a lot better than linearly applying motor speeds. I think we need to have such a feature not for racing but for general use because the resulting torque and therefore the control gains are also dependent on the current total thrust (see TPA workarounds), @bkueng also told me there is already the one @dagar mentioned above I didn't try it until now because of the reasons @bresch wrote.
- **Todays Test:** I want to inform that I tested my new pr for acro stick curve enhancements https://github.com/PX4/Firmware/pull/8036 today rebased on this pr and crashed, I don't know yet where the problem was but it suddenly disarmed...
- **Simulation testing:** I found a very good way for me to test theoretical control response while testing my RC curve pr in simulation. I run SITL with jmavsim, use a joystick over QGC, set jmavsim to FPV camera mode (press F1 for help), reduce my display resolution because it highly improves the delay of stick to picture (even if I had high framerates and smooth 3D before). I will do some tests of this mixer and my mixer like this because you can not really damage anything like this and hopefully already see some improvements, problems.

**Comment by diegoeck** [comment]
Hi @bresch! I just had a crash friday that I believe it was caused by the "oficial" mixer in our big drone (25 kg).
https://logs.px4.io/plot_app?log=0b3b2179-f31f-4e23-8972-0cc42b07536e
It seems to me that there was a wind gust, the pilot decided to reduce thrust to land but the attitude controller didn't had power to correct the angle and started to turn. For safety the pilot killed the drone (kill switch) and the drone crashed upsidedown :(.
Could you please check the log to see if you agree with my point?
If we agree I'll completely revise your new "mixer" and maybe propose some ideas. I think we should implement this PR soon.

**Comment by bresch** [comment]
Hi @diegoeck ,

First I'm sorry to hear that you had a crash, I hope it's not too bad.

I just had a look at your log and the first thing I can tell you is that you have huge vibration on your drone. I'm working on a drone of 25kg too, we also have high vibrations but smaller than on yours (and we know that it's already too high). Also, if you check the output of the controller, you can see that the noise from the gyros is directly fed back into the motors. If you can't reduce the vibrations, I would suggest you to reduce the inner loop gains in order to avoid noise sustain or amplification due to the feedback loop.
I can't say that the mixer is the main problem, but having this PR would help a lot when the rotorcraft is close to the lower saturation bound. As I can see in the log, the system can hover at 30% thrust which makes you closer to the lower saturation compared to common setups.

How did you tune the drone? Test on a bench? Was is able to reject properly external disturbances?

I would suggest you to make sure the props are properly balanced. If they are and you can't do anything against vibrations, reduce the P gain of the outer loop and of the inner loop. Once this PR can be merged, I would suggest to add it to your firmware too.

**Comment by BazookaJoe1900** [comment]
I am facing similar issues of saturation of commands to the motors that led very low (zero) and high commands.
I think that like @bkueng mantioned, the problem is that too low command leads the motor and props to produced low RPM without thrust, which is not good when the motor needs to go high again, it takes much more response time to generate thrust from 0.
I don't see that this PR faces with case of low commands.
There is the idle_speed parameter that fixes that issue, it doesn't allow the motor to go to too low. I think that there problem with this mixer parameter because it in the end of the logic and by changing it its like to change all the most inner loop gains. I think that parameter should have been just a clamping effect than a scalling effect. (does that what PWM_MIN should be used for?)

Also, it make reasonable to limit each control by it self, meaning – if after the PID math is done for one axis and get very high command, it should be clammped.  I think that this limit should be on the mc_att_control level, not on the mixer.

**Comment by bkueng** [comment]
Yes! We should either merge it as is or discuss what needs to be done to bring it in.
@RomanBapst fyi

**Comment by bkueng** [comment]
I managed to get into the deadly zone where the copter oscillated and gained altitude even though I reduced throttle to zero, and I had to use the kill-switch: https://logs.px4.io/plot_app?log=dea5a3ed-2473-4885-8d44-89f3a0e5d1af. This was during PID tuning with considerable too high P and zero D gain.

So I think we should make this a parameter, and you just disable this for setup/vehicle tuning.
@bresch is that ok with you and can you do that, or should I do it?

**Comment by julianoes** [comment]
@bkueng I think people will try to tune without setting the param anyway, and also they won't have a kill switch configured which looks very bad.
I think there needs to be some kind of protection for this case that kicks in and scales everything down.

**Comment by bkueng** [comment]
> I think people will try to tune without setting the param anyway

My idea was to have a parameter which is not set in the beginning, and then you would need to actively activate it (after tuning). This can be documented, and maybe there can even be a button in QGC.
For finished airframes, like aerofc, the param can be set in the airframe config, since we know it's already tuned & safe.

**Comment by julianoes** [comment]
@bkueng ok that way makes more sense, yes.

**Comment by bresch** [comment]
> So I think we should make this a parameter, and you just disable this for setup/vehicle tuning.
@bresch is that ok with you and can you do that, or should I do it?

@bkueng I absolutely agree, we need a parameter for this. 
Is it the best way to set a parameter by adding a method similar to `set_trim` of the standard mixer (`px4io` -> `mixer_group` -> `mixer_multirotor`)?

**Comment by dagar** [comment]
@bresch yes, unfortunately.

**Comment by bresch** [comment]
- [x] FMU
- [x] IO
- [x] UAVCAN
- [ ] Linux
- [ ] Sim
- [ ] Snapdragon

**Comment by dagar** [comment]
Let me think about a way we might be able to achieve this without introducing vehicle type specific parameters in every single output module.

**Comment by bkueng** [comment]
I added the remaining output modules already here: https://github.com/bkueng/Firmware/commits/pr-multi-mix-sat. @bresch can you pull the branch?

@dagar Yes, a nice solution would indeed be good here. I was thinking that the Linux, Snapdragon & Sim drivers can just be merged. The linux driver already supports multiple backends.

**Comment by bresch** [comment]
@bkueng  Done

**Comment by nanthony21** [comment]
I gave this PR a test today with a quadcopter and after two successful flights I had one flight where things went wrong resulting in a gentle crash. I'm not certain that the issue was caused by this PR but I wanted to post the log here in case it is helpful.

After taking off I went full throttle and full pitch forward in manual mode. After building up some speed I then let of the controls and switched to position mode. At first it looked like it was doing a good job of recovering, then it started to quickly drop. The motors were still running and the attitude was controlled, but despite putting the throttle stick all the way up the thrust wouldn't go high enough to maintain altitude.

Issues I see in the log:
1: Pitch oscillation after switching to position mode. I am using the default "Generic 250 Racer" pid settings and I have never seen oscillation before. I can see that the actuator outputs were saturated, could this be caused by the way that this PR handles saturation?

2: Shortly after switching to position mode the commander reported a loss of local position and switched to altitude mode. I have no idea why this happened. Although the altitude estimate seems fairly accurate the "Local position Z" plot seems to think that the vehicle was ascending all the way up until it crashed.

Log here:
https://review.px4.io/plot_app?log=53b9938b-ad16-453a-b6f5-e0d5637eba66

**Comment by nanthony21** [comment]
After going through the new mixing strategy for roll  and pitch the mixer then uses the old reduction-only approach for yaw. This means that yaw will still be totally uncontrolled for low throttle. 

Would it make sense to use the new mixing strategy for yaw as well, possibly with a limit so that yaw can only make a small adjustment to thrust?

**Comment by bresch** [comment]
Hi @nanthony21 and thank you for testing this PR. By investigating the log, I can see that your crash is most likely due to divergence in the EKF solution. The throttle is in fact cut by the altitude controller since the estimator reports that the drone is climbing (you can see that in the first graph of review.px4.io that the estimated height, in blue, increases much more than the baro and GPS measured altitudes).

From the EKF repost, it looks that:
1. the velocity innovations are growing
2. then the velocity aiding is rejected because the normalized velocity innovation is larger than 1.0, 
3. position innovations are growing
4. position aiding (GPS x,y + baro) in rejected because the normalized velocity innovation is larger than 1.0
5. after rejecting the updates for a few seconds, altitude is reset to baro measurement (at 18:30) and x,y position is reset to GPS position. However, this is too late and the drone crashes at the same time.

vertical_innov

norm_innov_test

Here is the full EKF report: 
[mixer_throttle_cut.ulg.pdf](https://github.com/PX4/Firmware/files/1802207/mixer_throttle_cut.ulg.pdf)

What I can't tell you is the cause of the initial velocity innovation growth. IMU vibrations? Bad GPS? Maybe @RomanBapst could give further explanations.

**Comment by bresch** [comment]
@bkueng @MaEtUgR I just reintroduced the "safe tuning mode". When not in air-mode, during attitude tuning for example, if the controller starts to diverge, reducing the throttle will reduce the outputs and stop the oscillations. No possible flips on the ground! :)

**Comment by bkueng** [comment]
> This means that yaw will still be totally uncontrolled for low throttle.

This is correct, and yes we can extend this, for example by adding another value for the `MC_AIRMODE` param. But it will require the use of a separate (dis)arming switch.

**Pull request closed without merging**
