### PR TITLE
timesync: Add uORB topic, general fixes

### PR DESCRIPTION
**Pull request by mhkabir**
Added uORB topic so that the time offset is accessible globally. Some general fixes added too.

Don't merge this yet, I wanted to do a couple of things which I'm forgetting now, I think.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@mhkabir What is the plan here? I'd prefer to have PRs for things that can be merged, and somehow it seems some sort of Todo?

**Comment by mhkabir** [comment]
@LorenzMeier You can merge this in.
I wanted to modify the estimators such that the synchronization is actually used, but that's probably for a later PR.

**Comment by LorenzMeier** [comment]
What is the use case for this?

**Comment by mhkabir** [comment]
I'm reopening this. I'll add a sdlog2 field for the sync offset such that we can track it.

This should also fix the issue with ```attitude_estimator_ekf``` timestamps. Now, the synchronised stamp stays in timestamp_computer, so the estimator can use it if it wants to, and otherwise use boot time.

**Pull request merged**
