### PR TITLE
added LP filters (10Hz) on attitude rates in estimator

### PR DESCRIPTION
**Pull request by LorenzMeier**
@tumbili This would be great to flight-test. I presume it allows to set higher rate gains on fixed wing and leads to a smoother servo response / less wear.

### CODE REVIEW

**Comment by kd0aij** [comment]
Won't this add latency inside the rate PID loops, and isn't that generally a "bad thing" which will actually increase the tendency to oscillate at higher P gain?

**Comment by LorenzMeier** [comment]
Your servo is much slower than this, which is the effective lowpass. So rather than it being the mechanical lowpass, this reduces the rate demand on your servo. Your comment about estimation and the linkage to control is valid though in that the reason for this PR is the actuator response, not the estimation itself. So one could make the argument that we should move these filters into the fixed wing controller, which would also ensure there is no regression on multicopters. With the rate increase from 100 to 250 Hz sitting in the other branch I'm quite confident that this filter will perform much better for multicopters as well.

**Comment by kd0aij** [comment]
I know we don't support "standard" helicopters yet, but here's a servo designed for controlling tail rotor pitch: http://www.mksservosusa.com/product.php?productid=180&cat=19&page=1
Intended for yaw rate PID loop running at 560Hz...
Operating Speed (8.4V) 	0.031 sec/60° degrees at no load

**Comment by LorenzMeier** [comment]
@yyassa These are some really good comments. What do you think about a new topic where we publish smoothed rates and accelerations? These could be smoothed specific to a particular airframe dynamic. If you're happy to take this on, it would be great if it would be done in a small helper class in the ECL lib, similar to this one: https://github.com/PX4/Firmware/pull/2438/files. It might be more scalable than to smooth the angular estimate.

**Comment by tumbili** [comment]
@LorenzMeier This is probably something that could be flight tested soon.

**Comment by LorenzMeier** [comment]
Yes. I propose to bring it in as stop-gap, and then to use the control state topic after a refactoring.

**Comment by LorenzMeier** [comment]
Integrated in the new PR, closing.

**Pull request closed without merging**
