### PR TITLE
VTOL: check mission feasibility as rotary wing

### PR DESCRIPTION
**Pull request by sanderux**
VTOL mission feasibility can be validated on rotary wing basis so no fixed wing landing feasibility will fail the mission

### CODE REVIEW

**Comment by tumbili** [comment]
@sanderux Did you test this! If yes I will rebase and merge, looks good.

**Comment by sanderux** [comment]
Yes, tested and works. I should note that it does now allow a mission where fw flight flies at very low altitudes when vtol

**Comment by AndreasAntener** [comment]
@tumbili Roman I think we can pull this in. Need to think about further mission check strategies for vtol

**Comment by LorenzMeier** [comment]
Cherry-picked.

**Pull request closed without merging**
