### PR TITLE
deprecate parrot bebop board support

### PR DESCRIPTION
**Pull request by dagar**
This target was never fully supported and is heavily dependent on a number of DriverFrameowork drivers that have no in tree equivalents (bebop bus, bebop rangefinder, etc). This will make it easier to fully deprecate DriverFramework in the near future.

### CODE REVIEW

**Comment by hamishwillee** [comment]
By "Deprecate" you mean "remove", right?

**Comment by dagar** [comment]
Yes I suppose that isn't quite right. I was trying to make it sound nicer than "purge" :smirk:.

**Comment by mhkabir** [comment]
The Purge has begun.

**Comment by hamishwillee** [comment]
Viva la revolución

**Pull request merged**
