### PR TITLE
Remove old toolchain

### PR DESCRIPTION
**Pull request by mcharleb**
Rebased on fix for updateBatteryStatus

### CODE REVIEW

**Comment by mhkabir** [comment]
Good to go. Please merge when ready!

**Comment by LorenzMeier** [comment]
@julianoes Please test-fly and merge. I reviewed the changes and the submodule revisions.

**Comment by julianoes** [comment]
Bench tested on Snapdragon, seems still to be working.

**Comment by mhkabir** [comment]
Yeah I tested on Snapdragon as well. 

As such, there's no reason for things to change. Everything's the same, the Cmake just uses the toolchain file from a different directory.

**Comment by julianoes** [comment]
Applied to master.

**Pull request closed without merging**
