### PR TITLE
Add const specifiers to posix and nuttx I2C class constructors and transfer() methods

### PR DESCRIPTION
**Pull request by mcsauder**
**Describe problem solved by the proposed pull request**
This PR adds `const` specifiers to the posix and nuttx I2C class constructors and transfer() method arguments.  Currently, a few of the arguments have `const specifiers` and this work adds `const` to the remaining arguments.

**Test data / coverage**
This PR was test flown on a 250 quad with pixhawk 4 mini. (The pixhawk mini primary mag, the IST8310, is I2C.)
image

Flight tests perform the same as current PX4:master branch
 - https://review.px4.io/plot_app?log=e26208b0-a13a-4f88-8004-273bd996a6d6

Please let me know if you have any questions on this PR! Thanks!

-Mark

### CODE REVIEW

**Comment by dagar** [comment]
The receive buffer shouldn't be const.

**Comment by mcsauder** [comment]
> The receive buffer shouldn't be const.

Yes. Agreed. But we can expect the pointer to the buffer to not change during the execution of the method, though, right?

**Comment by dagar** [comment]
Declare a pointer to a const uint8_t type.
``` C
const uint8_t * buf
```

Declare a const pointer to a uint8_t type.
``` C
const * uint8_t buf
```

Both.
``` C
const * uint8_t * buf
```

**Comment by mcsauder** [comment]
Thanks for pointing that out @dagar, I've removed the `const` specifiers from the receive buffers added in the previous commit, specifying them the right (intended) way is just really ugly.

I'm still curious how that worked at all:
image

Let me know if you'd like to see anything else done with this PR!  Thanks!

**Comment by mcsauder** [comment]
Rebased and commits squashed.  Thanks for the ping @TSC21 !

**Comment by mcsauder** [comment]
Closing, merged with PR #12695.

**Pull request closed without merging**
