### PR TITLE
Intel Aero: Start external mags first

### PR DESCRIPTION
**Pull request by LorenzMeier**
In theory the start order shouldn't matter, but this is worth a try @lucasdemarchi @lfelipe.

### CODE REVIEW

**Comment by bkueng** [comment]
I cannot reproduce this without props. I'll need to test outdoors.

The priority is set, https://github.com/PX4/Firmware/blob/master/src/drivers/hmc5883/hmc5883.cpp#L1023 if `sensor_is_onboard` is correct.

**Comment by LorenzMeier** [comment]
If should always report external on the HMC driver, which is incorrect (since the Aero has no external HMC sensor - the only external sensor is an IST8310):
https://github.com/PX4/Firmware/blob/master/src/drivers/hmc5883/hmc5883_i2c.cpp#L116-L128

I need to re-check the Aero FC schematics, but we need to make sure that if it has an HMC populated that it reports internal.

**Comment by bkueng** [comment]
This is the output of ls /dev:
```
ls /dev
/dev:
 accel0
 baro0
 console
 gyro0
 hmc5883_int
 ist8310_ext
 led0
 mag0
 mag1
 mpu6500_accel
 mpu6500_gyro
 ms5611_int
 null
 pipe0
 pipe1
 pwm_output0
 px4fmu
 ram0
 tap_esc
 ttyACM0
 ttyS0
 ttyS1
 ttyS2
 ttyS3
 ttyS4
 ttyS5
```
So it reports as internal.

**Comment by LorenzMeier** [comment]
Ok. The fix is then not this PR (can be closed) but to put a define for the external bus in src/drivers/boards/aero/board.h and to check for == external ID in the HMC driver. It might require putting this define into all board configs.

I want to avoid having more ifdefs in the drivers. That's horrible.

**Pull request closed without merging**
