### PR TITLE
Changed Mavstation Loader file to be compatible with Change in Bootloader to 12k Bootloader space

### PR DESCRIPTION
**Pull request by kbrtny**
This is compatible with this Bootloader commit: 
https://github.com/PX4/Bootloader/commit/3918d7b832fc6e1dbfd49061ac372e04a2091eb4

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@kbrtny Could you have a look at the travis fail and resolve it?

**Comment by kbrtny** [comment]
@LorenzMeier It looks like there is an issue with several other modules where mbstate_t isn't declared.  There may have been a related change that isn't working right..

**Comment by davids5** [comment]
Could this be that the nuttx patches are not applied and the correct math.h is not being used?

**Comment by LorenzMeier** [comment]
I'm not sure what it is yet. I need to look closer.

**Pull request merged**
