### PR TITLE
Ekf2 parameters

### PR DESCRIPTION
**Pull request by tumbili**
@LorenzMeier I cleaned this up and made sure everything is isolated in specific commits.
I haven't had a chance to talk to Paul yet but I think in the meanwhile this could go in as it helps to keep us all on master.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I don't think you understood what I meant. Boilerplate code is code that is massively duplicated all doing the same thing. The C param API you're using is a massive amount of boilerplate code. You need to change things in 3 locations to add a param. If you forget it, it won't load properly.

The BlockParam API does away with that:
https://github.com/PX4/Firmware/blob/afb68cb0abee4034582f93d7f383c287b9c9a109/src/modules/navigator/rcloss.h#L68
and
https://github.com/PX4/Firmware/blob/afb68cb0abee4034582f93d7f383c287b9c9a109/src/modules/navigator/rcloss.cpp#L60
and this is how you refresh params:
https://github.com/PX4/Firmware/blob/afb68cb0abee4034582f93d7f383c287b9c9a109/src/modules/navigator/rcloss.cpp#L86

That's all. We might want to consider using it instead of the boilerplate code.

**Comment by tumbili** [comment]
@LorenzMeier Ok, I wasn't sure if this is the preferred method since many modules don't use it. But it makes sense to use it apparently. I'm discussing this with Paul now and will implement it after.

**Comment by LorenzMeier** [comment]
Let me know what the two of you prefer. We can do both, but I want to make sure it best supports the filter development and doesn't look or feel like bloat or complex.

**Comment by priseborough** [comment]
I discussed this with Ramon, and provided the BlockParam API can be extended so that the calling program knows if a parameter has been changed, then it makes sense to use it.

**Comment by tumbili** [comment]
@LorenzMeier Yes, currently this BlockParam interface calls the updateParameters function which does not tell you if there has been an update or not. We would need to know this because we don't want to copy all parameters on every iteration. Would it make sense for this function to return a flag indicating if an update has taken place?

**Comment by tumbili** [comment]
We also discussed moving the BlockParam instances into the base class so that we don't need to copy around the values at all. But then we are introducing new dependencies with it.

**Comment by LorenzMeier** [comment]
The right way to do this is to extend BlockParam so you can give it a pointer to the data structure it should update itself. That way you never have to update it. The param update is done through the uORB param update publication.

**Comment by tumbili** [comment]
Closing in favour of #3485

**Pull request closed without merging**
