### PR TITLE
PX4 on nuttx 7.27+

### PR DESCRIPTION
**Pull request by davids5**
All: All board configs have been upgraded. This is not complete in that the compressed defconfigs are a WIP. Not all boards have been bench vetted. 

The Branch will be force pushed to do not relay on it!

@PX4/testflights - Please bench test as many builds - if it seems OK it can be tested on the ground but please do not assume it is safe, until it earns your trust.

### CODE REVIEW

**Comment by dagar** [comment]
Compressed ROMFS savings

image

**Comment by Avysuarez** [comment]
@dagar In the place where we do the tests the gps does not work

**Comment by dagar** [comment]
Flash comparison of px4io-v2 to master.

image

**Comment by dagar** [comment]
@davids5 here's an example showing how to compress the defconfig in cmake that produces the same output as the NuttX helpers. https://github.com/PX4/NuttX/blob/a87082007a85fcf06ff1040dce472bc4bc48c827/cmake/defconfig.cmake#L146-L174

To reconstitute you just need to run `APPSDIR=${NUTTX_APPS_DIR} kconfig-conf --olddefconfig Kconfig`. https://github.com/PX4/NuttX/blob/a87082007a85fcf06ff1040dce472bc4bc48c827/cmake/defconfig.cmake#L75-L88

**Comment by dagar** [comment]
@PX4/testflights could you expand testing a bit? Again take it very slow, but try something outdoors with GPS and also try both a pixhawk 4 and pixhawk 4 mini.

**Comment by davids5** [comment]
> @davids5 here's an example showing how to compress the defconfig in cmake that produces the same output as the NuttX helpers. https://github.com/PX4/NuttX/blob/a87082007a85fcf06ff1040dce472bc4bc48c827/cmake/defconfig.cmake#L146-L174
> 
> To reconstitute you just need to run `APPSDIR=${NUTTX_APPS_DIR} kconfig-conf --olddefconfig Kconfig`. https://github.com/PX4/NuttX/blob/a87082007a85fcf06ff1040dce472bc4bc48c827/cmake/defconfig.cmake#L75-L88

@dagar lovely! I will pull this in today and get the reset of the config converted.

**Comment by Avysuarez** [comment]
Tested with Pixhawk 4. good flights, no issues.
Flight on stabilized, altitude and position mode.
https://review.px4.io/plot_app?log=4d601a56-aabb-49d3-af9f-c92e8a8faa47

Flight on auto mode.
https://review.px4.io/plot_app?log=a9d3ce11-9fb3-4af5-a9cf-e94ec3b4e88b

**Comment by Avysuarez** [comment]
Tested on pixhawk 4 mini. good flight, no issues.
https://review.px4.io/plot_app?log=1a2b42bb-ea49-499d-9432-9059e8765d7e

**Comment by dagar** [comment]
Sidenote related to the last pixhawk 4 mini test (https://review.px4.io/plot_app?log=1a2b42bb-ea49-499d-9432-9059e8765d7e)

CPU Spikes in the pixhawk 4 mini log
image

Not present in the pixhawk 4 logs
https://review.px4.io/plot_app?log=4d601a56-aabb-49d3-af9f-c92e8a8faa47
image

https://review.px4.io/plot_app?log=a9d3ce11-9fb3-4af5-a9cf-e94ec3b4e88b
image

@Avysuarez @Tony3dr as a quick test could you try swapping sdcards between the pixhawk 4 and 4 mini?

**Comment by Avysuarez** [comment]
Pixhawk 4 mini with the sd card of the pixhawk 4.
https://review.px4.io/plot_app?log=c4f66038-db08-41f3-a5bb-21ddfd021037

**Comment by davids5** [comment]
> Pixhawk 4 mini with the sd card of the pixhawk 4.
> https://review.px4.io/plot_app?log=c4f66038-db08-41f3-a5bb-21ddfd021037

@Avysuarez - thank you!, @dagar I guess that kills the SD theory. Let's list all the other key differences are:

1.  FMU driver

**Comment by davids5** [comment]
@dagar - current status: All Nuttx build building locally. Not  necessarily running! 
Next step for me bench testing and comparing to master's resource usage. That will most likely lead to on more pass on the defconfigs. Then I can compress them,

**Comment by davids5** [comment]
@dagar this has my first cut at the compressed config.  We can not build with compressed config yet due to cmake needs for CONFIG_ARCH_FAMILY and CONFIG_ARCH_CHIP and something else that causes
image

You can debug that here:  https://github.com/PX4/Firmware/pull/11086 

I have checked that uncompressed  .config in the build tree will be == to the defconfig found in this pr.

**Comment by davids5** [comment]
@PX4/testflights See https://github.com/PX4/Firmware/pull/11013#issue-237456265 - please expand testing to all Nuttx boards:

- [ ] px4_fmu-v2
- [ ] px4_fmu-v3
- [ ] px4_fmu-v4
- [ ] px4_fmu-v4pro @klopezal - please give this a test.
- [ ] px4_fmu-v5
- [ ] auav_x21 @pkocmoud  - please give this a test.
- [ ] bitcraze_crazyflie
- [ ] nxp_fmuk66-v3 @igalloway  - please give this a test.
- [ ] airmind_mindpx-v2 @rolandash - please give this a test.
- [ ] av_x-v1 @dagar please give this a test.
- [ ] intel_aerofc-v1 
- [ ] omnibus_f4sd


- [ ] gumstix_aerocore2
- [ ] atmel_same70xplained 
- [ ] stm_nucleo-F767ZI
- [ ] stm_32f4discovery

**Comment by davids5** [comment]
@dagar @PX4/testflights I have bench tested some of the Boards and indicated the results of `boot`, `sensors status`, `free` and `px4io status` iff applicable In https://github.com/PX4/Firmware/pull/11013#issuecomment-449523256 

Please begin cautions bench testing of as many builds as you have HW for. If it seems OK it can be tested on the ground but please do not assume it is safe, until it earns your trust.

**Comment by davids5** [comment]
@dagar, @PX4/testflights Where are we on flight testing?

**Comment by Tony3dr** [comment]
@davids5 The Team is out in the field today and will conduct the Flight Test.

**Comment by dannyfpv** [comment]
tested on pixhawk v4 pro
https://review.px4.io/plot_app?log=e609dec4-dd7d-491b-bba4-c8225badbbc2
https://review.px4.io/plot_app?log=b513530b-6651-4a09-a163-c6cb555356e9

**Comment by dagar** [comment]
Logs seem good so far. A few minor things with the vehicles themselves, but nothing different than with current master.

**Comment by dannyfpv** [comment]
tested on pixhawk4 mini v5
https://review.px4.io/plot_app?log=75c1681d-771f-4366-b9c2-86770e16a86e

**Comment by dagar** [comment]
Everything is looking quite good so far. I've rebased on master to keep it current. I'd like to spread out the testing a bit more.

**Comment by davids5** [comment]
@dagar I realize it would reset testing but I think we should consider another update from upstream Nuttx.

https://bitbucket.org/nuttx/nuttx/commits/d7f1dc56cf377edb84219b8be3510947d1e89c96
https://bitbucket.org/nuttx/nuttx/commits/70efabd0adbdaf582307593d03d2e1d5de3b4e2e

What is your opinion?

**Comment by Tony3dr** [comment]
@davids5 @dagar, we are expecting replacement FC for the following platforms:
- Pixhawk 1
- Pixhawk 2.1(cube)
- Pixracer
- Pixhawk 4
The replacement boards should arrive by the end of the week, to finalize the Testing for this PR.

**Comment by dagar** [comment]
> @dagar I realize it would reset testing but I think we should consider another update from upstream Nuttx.
> 
> https://bitbucket.org/nuttx/nuttx/commits/d7f1dc56cf377edb84219b8be3510947d1e89c96
> https://bitbucket.org/nuttx/nuttx/commits/70efabd0adbdaf582307593d03d2e1d5de3b4e2e
> 
> What is your opinion?

Yes, let's do another bump.

**Comment by dagar** [comment]
Branch updated to latest NuttX and latest Firmware.

**Comment by dagar** [comment]
@bkueng or @bresch if either of you have a chance this week could you quick this branch a quick flight on something with an Omnibus?

@dakejahl a quick flight test on a Teal One couldn't hurt.

**Comment by bkueng** [comment]
Omnibus does not boot with this - no QGC connection via USB. Tested on 2 different boards (BetaFPV + Hobbywing Omnibus board). It will need more investigation, I don't have a boot output atm.

**Comment by davids5** [comment]
Tracking NuttX changes since jumping off point https://github.com/PX4/NuttX/issues/47

**Comment by davids5** [comment]
@bkueng - Would you please see if the (educated guess) ee582f6 Solved the boot issue.

**Comment by dagar** [comment]
Rebasing on PX4/Firmware master to minimize any differences during testing.

**Comment by bkueng** [comment]
> @bkueng - Would you please see if the (educated guess) ee582f6 Solved the boot issue.

No, still the same.

**Comment by dagar** [comment]
NuttX version bumped to 7.28. Let's continue in https://github.com/PX4/Firmware/pull/11256.

**Pull request closed without merging**
