### PR TITLE
Add compensation for IMU and Barometer thermal drift

### PR DESCRIPTION
**Pull request by priseborough**
Draft implementation for comment and review.

See https://docs.google.com/document/d/1GHzjsPTfSUAxYGPNlXSL7FYkxFcq76jTfsaquc57Rww for previous discussion.

A separate PR's will be submitted for the on-board logging and calibration function.

TODO:

Assignment of unique ID's to baro sensors to enable multiple Baros to be used with calibration.
Better method of assigning unique ID's to gyro and accel sensors.

### CODE REVIEW

**Comment by dagar** [comment]
Overflow on px4fmu-v2_default. You can comment drivers/iridiumsbd.
https://github.com/PX4/Firmware/blob/master/cmake/configs/nuttx_px4fmu-v2_default.cmake#L53

**Comment by priseborough** [comment]
Unfortunately that doesn't free up enough to fit within the lower half of the flash.

**Comment by dagar** [comment]
On the build system it now (just barely) fits.

       text	   data	    bss	    dec	    hex	filename
    1025356	   5180	  19364	1049900	 10052c	build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx

The builds are using GCC 5.4 which seems to do a better job of size optimization.

    arm-none-eabi-g++ (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]

https://dev.px4.io/starting-installing-linux-boutique.html#toolchain-installation

**Comment by priseborough** [comment]
This has been superceded by #6363

**Pull request closed without merging**
