### PR TITLE
Send best sensor values in HIGHRES_IMU

### PR DESCRIPTION
**Pull request by mhkabir**
@julianoes This is my version of #4702 

Could you please review and cross-test on Snappy. I'm on holiday, so I was just able to test on a Pixhawk and confirm that nothing broke. Wasn't able to test failover since I had no console cable.

### CODE REVIEW

**Comment by julianoes** [comment]
@mhkabir: Reviewed, looks good to me. When can you test it?

**Comment by LorenzMeier** [comment]
@mhkabir Where are we with testing of this?

**Comment by bkueng** [comment]
I don't think we need this, as we will move voting into the `sensors` module, together with the changes in https://github.com/PX4/Firmware/issues/4861

**Comment by mhkabir** [comment]
@julianoes @LorenzMeier Was the plan not to remove the sensors module entirely, and have voting in the estimators?

**Comment by julianoes** [comment]
I agree with @mhkabir I think because estimators could have their own voting logic, or could even use redundant sensor data.

**Comment by mhkabir** [comment]
@julianoes Could you quickly try this on a Pixhawk? I tested it, and the core functionality seems to work, but intermittently found some spikes in QGC when plotting HIGHRES_IMU.

**Comment by mhkabir** [comment]
Interesting. This is only with the MPU6000 not running. I wonder if it's a bug in one of the other sensor drivers which we've never caught, or some sort of a voter artifact.

With MPU6000 :
screenshot from 2016-06-25 21 35 49

With MPU6000 turned off : 
screenshot from 2016-06-25 21 37 21

**Comment by julianoes** [comment]
Interesting, can you just disable the voter and debug it further?

**Comment by LorenzMeier** [comment]
Closing this as we refactored the sensors app and sensors combined topics since.

**Pull request closed without merging**
