### PR TITLE
Remove on arming reset, be less verbose in normal conditions output

### PR DESCRIPTION
**Pull request by LorenzMeier**
@julianoes Can you review? This should fix all remaining LPE output challenges.

### CODE REVIEW

**Comment by jgoppert** [comment]
Looks good.

**Comment by ecmnet** [comment]
@LorenzMeier @jgoppert I am just wondering whether it might be reasonable to use the parameter LPE_GPS_ON to determine, whether an LPOS-XY reset should be performed when arming, as Lorenz mentioned in the comments.

**Comment by jgoppert** [comment]
@ecmnet We just had a phone conversation about this. I think we are headed towards a flag that describes what specific use case you are doing and then modifies vehicle parameters accordingly. So maybe if flag==indoor_optical_flow .. then make the follow changes etc.

**Comment by LorenzMeier** [comment]
jenkins test this

**Comment by LorenzMeier** [comment]
Jenkins test this please

**Pull request merged**
