### PR TITLE
Enable Simulation of the Hippocampus (AUV from TUHH)

### PR DESCRIPTION
**Pull request by NRottmann**
Adding files which enable a simulation with the autonomous underwater
vehicle (AUV) from the Technical University Hamburg-Harburg.

For safety reasons I just added files (only had to add some lines to the CMakeFile in sitl_gazebo and to the config file posix_sitl_default). I have tested the simulation with gazebo-ROS and it works fine. There is still one small problem as described here http://discuss.px4.io/t/pwm-out-sim-does-not-mix-the-pitch-signal-correctly/3670 .

### CODE REVIEW

**Comment by dagar** [comment]
Looks good we just need to get it passing CI.
I like your naming, but it's hard to google! What do you think about naming the example app and launch file more descriptively?

**Comment by NRottmann** [comment]
Hi, yes I can rename the example app as well as the launch file. I would suggest something like AUV_example_app and AUV.launch.

**Comment by LorenzMeier** [comment]
Could you try to rebase & fix CI? The contribution is certainly welcome.

**Comment by NRottmann** [comment]
@LorenzMeier 
Hi, yes I can do that, but I think that first it is necessary to merge the changes in the sitl_gazebo submodule. I rebased this submodule and have done a pull request (https://github.com/PX4/sitl_gazebo/pull/106). Is this correct?

**Comment by LorenzMeier** [comment]
Plugin is rebased and merged - happy to bring this in as well. Would be awesome if you could rebase, thanks!

**Comment by NRottmann** [comment]
@LorenzMeier 
Hi somehow I could not fixed the issue with the submodule in this case. Thus I created a new branch and rebased this. I then started a new pull request regarding this branch:
https://github.com/PX4/Firmware/pull/7771

There should be everything fine. I hope we can now merge this.

**Comment by TSC21** [comment]
Succeeded by #7771

**Pull request closed without merging**
