### PR TITLE
Nuttx Update to 7.10+ With Hard Fault Logging, and lots more.....

### PR DESCRIPTION
**Pull request by davids5**
Hard Fault Logging

The PR uses a non volatile file system added to Nuttx, that is backed by the STM32's Battery backed up ram in the BKP (same as RTC) domain to store the data from a hard fault or an assertion failure and reboots the system. 

On boot up, if there is valid hard fault data, it will be written to the micro SD card. Then the system will be re-armed to capture any new hard faults. 

Fault logs capture the context of the CPU at the time of the failure.  They contain different information depending on the cause of the failure. Assertion or hardfault. The common elements of the fault log include the time and date of the fault  the type of the fault, and information about the build such as the git hash and build time and date.

For an assertion failure  the log will contain the file and line the assertion failed on and a dump of the users stack.
For a hard fault failure the log will contain a copy of the users stack, the interrupt stack, and the processors registers.

Since we want to capture the initial cause of the failure, once a hard fault has been committed to BBSRAM it can will not be overwritten by a subsequent hard faults until it is rearmed. 

The Normal path is Fault--Save to BBSRAM ---Reboot---Save to SD card -- Rearm--- boot --- run

```
[boot] 4 Battery Backed Up File(s)
[hardfault_log] Fault Log info File No 3 Length 3257 flags:0x00 state:0
[hardfault_log] Fault Logged on 2011-02-20-14:20:11 - Valid
[hardfault_log] Saving Fault Log file /fs/microsd/fault_2011_02_20_14_20_11.log
[hardfault_log] Fault Log is Armed
[hardfault_log] Done saving Fault Log file
```
In the case that the system cannot save the fault data to permanent storage due to A) Infinite reboot loop or B) SDIO not mountable. The system will behave as follows: Reboots with a valid hard fault record in the non volatile file system are counted (also in a non volatile file). Once this count is greater than 2, it means we have rebooted before the Normal path above has completed and committed the fault log to the SD card. This implies that flight cannot be continued or resumed. Therefore on each boot, where there is a valid fault log in BBSRAM, with the count greater than 2 the fault log will be dumped to the debug console and the system will prompt with the menu shown below. 
To retrieve the log, connect the debug terminal and re boot (If the count is less than  2: reboot with the space bar held down.) 

The log will be output to the terminal. You will be presented with a menu:

```
Enter B - Continue booting
Enter C - Clear the fault log
Enter D - Dump fault log
```
To recapture the log use D then C to rearm the system.

Debugging:

Debugging an unstable system that resets it's self can be a real pain!

GDB/JTag:

If you use a Jtag place a break point on up_assert to catch the hard fault or assertion before it is logged and the system rebooted in the call out to the ```void board_crashdump(uint32_t currentsp, void *tcb, uint8_t *filename, int lineno)``` located in px4fmu2_init.c
Hint:If you set the pc = the lr you may be able to walk back up the stack to the code that caused the fault.

You may also place a break point on for ```(int c ='>'; !dbgContinue; c= getchar())```  in px4fmu2_init.c and set dbgContinue = 1  to continue debugging.

Printf Debugging

On a debug console hold the space bar down at boot to see the debug output and stop a infinite reboot cycle.

How to use a fault log:

Assertion failure:

The line and file that the assertion failed at will be listed 

```
up_assert: Assertion failed at file:ystemcmds/hardfault_log/hardfault_log.c line: 118 task: hardfault_log
up_dumpstate: sp:     20025e84
up_dumpstate: IRQ stack:
up_dumpstate:   base: 20009d90
up_dumpstate:   size: 00000800
up_dumpstate:   used: 0000015c
```
Hard fault failure:

Use the comand arm-none-eabi-nm -n <path to from git hash listed in dump>/firmware.elf > fw.map

Use the value of the pc,lr or values from the stacks to find the closest address in fw.map file.

```
Type:Hard Fault in file:armv7-m/up_hardfault.c at line: 183 running task: hardfault_log
 FW git-hash: db15eaa4a6a33fe02d336a75024d68d9de2ca19b
 Build datetime: Mar  3 2015 16:23:42
 Processor registers: from 0x20025dac
 r0:0x00000000 r1:0x00000001  r2:0x00000000  r3:0xe000ed14  r4:0x00000000  r5:0x20005e48 r6:0x20025ef4 r7:0x00000003
 r8:0x00000000 r9:0x00000000 r10:0x00000000 r11:0x00000000 r12:0x00000000  sp:0x20025e80 lr:0x0807e82b pc:0x08073c38
 xpsr:0x41000000 basepri:0x000000f0 control:0x00000004
 exe return:0xffffffe9
 IRQ stack:
  top:    0x20009d90
  sp:     0x20009d34
  bottom: 0x20009590
  size:   0x00000800
 User stack:
  top:    0x20025ef0
  sp:     0x20025e80
  bottom: 0x20025b1c
  size:   0x000003d4
```

It is expected that there will be a tool that will automate the above-mentioned process.

This PR supersedes  https://github.com/PX4/Firmware/pull/1758

### CODE REVIEW

**Comment by davids5** [comment]
Force Hans

**Comment by davids5** [comment]
Nuttx next now has the uavcan updates in support of Dynamic Node Allocation and File support for bootloaders

**Comment by davids5** [comment]
@LorenzMeier nuttx_next is updated with master as of @mcharleb 's Bringup m1 @bcc49268ca4979a398e324344e3bf9cfe2a77d98

In addition it has the uavcan bare metal on nuttx bootloader builds for the the px4cannode and @bendyer 's sc2740vc.

All ISR stack sizes have been confirmed and px4cannode has bootloaded it's app from SD.

# Next up - 
1. Update to nuttx 7.10+ 
2. Latest uavcan (with submodules)
3. Bifurcate uavcan_main into the low priority and high priority threads per [this issue] (https://github.com/UAVCAN/libuavcan/issues/37)
4. Pull in PX4ESC once @pavel-kirienko discusses it with @LorenzMeier

**Comment by LorenzMeier** [comment]
I'm closing this since we have the CMake branch.

**Pull request closed without merging**
