### PR TITLE
add RC kill switch

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by kd0aij** [comment]
Since forcing lockdown this way seems to put commander in an inconsistent state, it might be better to force an immediate transition to the disarmed state. Is there an existing state transition diagram for arming states? If not, I should make and validate one.

**Comment by kd0aij** [comment]
px4fmu-v4: verified that PWM output is valid at 900usec pulse width, 400Hz when RC kill switch is ON
Need to verify for fmu-v2 also.

**Comment by kd0aij** [comment]
testing on fmu-v2 shows a delay of about 2 seconds from flipping kill switch to motors stopping. Need to find an eliminate the source of that latency.

**Comment by LorenzMeier** [comment]
@kd0aij Did you fix the latency on FMUv2? Else we could get this in as its operational on Pixracer / FMUv4.

**Comment by LorenzMeier** [comment]
Superseded by rc_kill_sw2 branch and PR.

**Pull request closed without merging**
