### PR TITLE
Sensor cal updates

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Smaller changes:
- Added new calibrate_from_orientation worker routines which is used by both mag and accel cal. It waits for the vehicle to be put into an orientation and then calls a worker routine to do the actual calibration. It will time out after 10 failed tried at detected an orientation
- Many updates/fixes to log messages

New mag calibration:
- All available mags are calibrated at the same time
- Calibration points are collected one side at a time. You need to get points from 3 sides to form the sphere.
- There a now two progress indicators: The overall progress indicator as well as the progress indicator for a specific side. The reason for this if for QGC to be able to display both of these separately.

I tested these changes on my Iris+ and also ran calibration from the current master. Both runs have nearly identical calibration values. That said this is a fairly major changes to mag cal, and some smaller changes to accel cal. They both could use some testing by someone other than me before this gets merged.

### CODE REVIEW

**Comment by Zefz** [comment]
@DonLakeFlyer I've tried your new mag calibration. Nice work I was planning to implement something similar to make mag calibration faster and less tedious.

I get an error calibrating with this new routine however:
```
mag #0 off: x:0.23 y:-0.05 z:-0.08 Ga
mag #0 scale: x:1.04 y:0.92 z:0.94
mag #1 off: x:-0.19 y:0.26 z:0.29 Ga
mag #1 scale: x:1.00 y:1.00 z:1.00
mag calibration: done
SENSOR FAIL: MAG CAL ID
```

**Comment by DonLakeFlyer** [comment]
Looks like I need to restructure the way I'm writing the CA_MAG#_ID param. Thanks. I'll fix it.

**Comment by DonLakeFlyer** [comment]
@Zefz Can you give this a try again?

**Comment by Zefz** [comment]
I will try again after the weekend (monday).

**Comment by LorenzMeier** [comment]
Tested and applied, thanks!

**Pull request closed without merging**
