### PR TITLE
[bug fix] Covariance check on INAV and AEQ

### PR DESCRIPTION
**Pull request by TSC21**
After some review, I realized that some of the covariance checks on the AEQ and INAV weren't properly done. This fixes it.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Do you have test data? I just want to make sure the fix is validated.

**Comment by TSC21** [comment]
Will send some SITL testing today.

**Comment by TSC21** [comment]
@LorenzMeier takeoff and landing with Vision set on LPE+AEQ: https://review.px4.io/plot_app?log=bcc69b12-26ec-4428-af66-da464aa58c5c. Same on EKF2 with vision yaw fused: https://review.px4.io/plot_app?log=17246819-f0ff-47b2-9819-3e66ab6c2945.

@LorenzMeier @bkueng I added a new commit which actually does set the proper parameters to `iris_vision` and also makes independent of the `iris_opt_flow` POSIX SITL config. The above logs show good results of these changes on the `iris_vision` config for both EKF2 and LPE+AEQ.

**Comment by TSC21** [comment]
Also these required a fix on the quaternion rotation of the vision data: https://github.com/PX4/sitl_gazebo/pull/248

**Comment by TSC21** [comment]
@bkueng @LorenzMeier can you merge it, please? I don't have write permissions. Thank you

**Comment by LorenzMeier** [comment]
I’ve reviewed the logs, thanks!

**Comment by TSC21** [comment]
@LorenzMeier no problem and thanks as well. For this to work though, we need https://github.com/PX4/sitl_gazebo/pull/248 as well.

**Pull request merged**
