### PR TITLE
Compilation fixes for GCC 8.0.1

### PR DESCRIPTION
**Pull request by bkueng**
GCC 8.0.1 brings some new warnings. None of these is an important fix though.

@julianoes I'm surprised that you haven't hit these yet.

### CODE REVIEW

**Comment by jlecoeur** [comment]
With GCC 8.1.0, I have another error:
```
In file included from ../../mavlink/include/mavlink/v2.0/standard/standard.h:30,
                 from ../../mavlink/include/mavlink/v2.0/standard/mavlink.h:32,
                 from ../../src/modules/mavlink/mavlink_bridge_header.h:87,
                 from ../../src/modules/mavlink/mavlink_ftp.h:46,
                 from ../../src/modules/mavlink/mavlink_ftp.cpp:45:
../../mavlink/include/mavlink/v2.0/standard/../common/./mavlink_msg_heartbeat.h: In function ‘uint8_t mavlink_msg_heartbeat_get_type(const mavlink_message_t*)’:
../../mavlink/include/mavlink/v2.0/standard/../protocol.h:247:91: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
 #define _MAV_RETURN_uint8_t(msg, wire_offset) (const uint8_t)_MAV_PAYLOAD(msg)[wire_offset]
                                                                                           ^
../../mavlink/include/mavlink/v2.0/standard/../common/./mavlink_msg_heartbeat.h:262:12: note: in expansion of macro ‘_MAV_RETURN_uint8_t’
     return _MAV_RETURN_uint8_t(msg,  4);
            ^~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
```
which I fixed with `-Wno-ignored-qualifiers` in px4_base.cmake.

**Comment by bkueng** [comment]
@jlecoeur I got this one as well, but have not come around to create a PR for that.

My mavlink diff:
```diff
diff --git a/mavlink_helpers.h b/mavlink_helpers.h
index 77c848d5..6dbfe833 100644
--- a/mavlink_helpers.h
+++ b/mavlink_helpers.h
@@ -107,6 +107,10 @@ MAVLINK_HELPER uint8_t _mav_trim_payload(const char *payload, uint8_t length)
 /**
  * @brief check a signature block for a packet
  */
+	union tstamp_u {
+	    uint64_t t64;
+	    uint8_t t8[8];
+	};
 MAVLINK_HELPER bool mavlink_signature_check(mavlink_signing_t *signing,
 					    mavlink_signing_streams_t *signing_streams,
 					    const mavlink_message_t *msg)
@@ -133,10 +137,10 @@ MAVLINK_HELPER bool mavlink_signature_check(mavlink_signing_t *signing,
 
 	// now check timestamp
 	bool timestamp_checks = !(signing->flags & MAVLINK_SIGNING_FLAG_NO_TIMESTAMPS);
-	union tstamp {
-	    uint64_t t64;
-	    uint8_t t8[8];
-	} tstamp;
+	//../../mavlink/include/mavlink/v2.0/common/../mavlink_helpers.h: In function ‘bool mavlink_signature_check(mavlink_signing_t*, mavlink_signing_streams_t*, const mavlink_message_t*)’:
+	//../../mavlink/include/mavlink/v2.0/common/../mavlink_helpers.h:139:4: error: conflicting C language linkage declaration ‘mavlink_signature_check(mavlink_signing_t*, mavlink_signing_streams_t*, const mavlink_message_t*)::tstamp_u tstamp’ [-Werror]
+	//  } tstamp;
+	union tstamp_u tstamp;
 	uint8_t link_id = psig[0];
 	tstamp.t64 = 0;
 	memcpy(tstamp.t8, psig+1, 6);
@@ -168,7 +172,7 @@ MAVLINK_HELPER bool mavlink_signature_check(mavlink_signing_t *signing,
 		signing_streams->stream[i].link_id = link_id;
 		signing_streams->num_signing_streams++;
 	} else {
-		union tstamp last_tstamp;
+		union tstamp_u last_tstamp;
 		last_tstamp.t64 = 0;
 		memcpy(last_tstamp.t8, signing_streams->stream[i].timestamp_bytes, 6);
 		if (timestamp_checks && tstamp.t64 <= last_tstamp.t64) {
diff --git a/protocol.h b/protocol.h
index 8f539709..5c09761a 100644
--- a/protocol.h
+++ b/protocol.h
@@ -242,9 +242,14 @@ _MAV_PUT_ARRAY(int64_t,  i64)
 _MAV_PUT_ARRAY(float,    f)
 _MAV_PUT_ARRAY(double,   d)
 
-#define _MAV_RETURN_char(msg, wire_offset)             (const char)_MAV_PAYLOAD(msg)[wire_offset]
-#define _MAV_RETURN_int8_t(msg, wire_offset)   (const int8_t)_MAV_PAYLOAD(msg)[wire_offset]
-#define _MAV_RETURN_uint8_t(msg, wire_offset) (const uint8_t)_MAV_PAYLOAD(msg)[wire_offset]
+/*
+../../mavlink/include/mavlink/v2.0/common/./mavlink_msg_heartbeat.h: In function ‘uint8_t mavlink_msg_heartbeat_get_type(const mavlink_message_t*)’:
+../../mavlink/include/mavlink/v2.0/common/../protocol.h:247:91: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
+ #define _MAV_RETURN_uint8_t(msg, wire_offset) (const uint8_t)_MAV_PAYLOAD(msg)[wire_offset]
+ */
+#define _MAV_RETURN_char(msg, wire_offset)             (char)_MAV_PAYLOAD(msg)[wire_offset]
+#define _MAV_RETURN_int8_t(msg, wire_offset)   (int8_t)_MAV_PAYLOAD(msg)[wire_offset]
+#define _MAV_RETURN_uint8_t(msg, wire_offset) (uint8_t)_MAV_PAYLOAD(msg)[wire_offset]
 
 #if MAVLINK_NEED_BYTE_SWAP
 #define _MAV_MSG_RETURN_TYPE(TYPE, SIZE) \

```

The first one is a strange error:
```
../../mavlink/include/mavlink/v2.0/common/./mavlink_msg_heartbeat.h: In function ‘uint8_t mavlink_msg_heartbeat_get_type(const mavlink_message_t*)’:
+../../mavlink/include/mavlink/v2.0/common/../protocol.h:247:91: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
```
for `union tstamp_u tstamp;`. Did you get that as well?

**Comment by jlecoeur** [comment]
@bkueng no I had no error on `tstamp_u`

**Comment by julianoes** [comment]
Thanks @bkueng. I might not have updated recently. And I'm not currently using my Arch box.

**Pull request merged**
