### PR TITLE
CI: update px4-dev-snapdragon container tag

### PR DESCRIPTION
**Pull request by TSC21**
Updates the container tag to 2019-01-04.

### CODE REVIEW

**Comment by TSC21** [comment]
@LorenzMeier I am not sure that the snapdragon containers are set to autobuild and I cannot verify the build state. Do you mind taking a look at this? Thanks!

**Comment by dagar** [comment]
Did you try building this container locally?

**Comment by TSC21** [comment]
> Did you try building this container locally?

Yes. Just updated the base tag to `2019-01-19` tag as well - https://github.com/Auterion/px4-dev-snapdragon/commit/7b98942f2b1e412d82acbd3bf3b845e17855f47f. Here's the output:
```sh
Sending build context to Docker daemon  130.6kB
Step 1/10 : FROM px4io/px4-dev-base:2019-01-25
2019-01-25: Pulling from px4io/px4-dev-base
38e2e6cd5626: Pull complete 
705054bc3f5b: Pull complete 
c7051e069564: Pull complete 
7308e914506c: Pull complete 
2dbfcb1385a6: Pull complete 
b940adb8bb9a: Pull complete 
841d62a854d4: Pull complete 
ffc2638d657c: Pull complete 
fd7283dcd3a4: Pull complete 
9e2b5309b999: Pull complete 
bc6485225dc0: Pull complete 
Digest: sha256:3f35db96c1f196a054c9bc274b4fc3122650ea2a7ec4eabcc14a00ee9d2fa1e1
Status: Downloaded newer image for px4io/px4-dev-base:2019-01-25
 ---> ed57c3d9f910
Step 2/10 : MAINTAINER Julian Oes <julian@oes.ch>
 ---> Running in 0fd5b2dc667c
Removing intermediate container 0fd5b2dc667c
 ---> b58dd9878741
Step 3/10 : RUN apt-get update 	&& DEBIAN_FRONTEND=noninteractive apt-get -y --quiet --no-install-recommends install 	android-tools-adb 	&& apt-get -y autoremove 	&& apt-get clean autoclean 	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*
 ---> Running in 353bbf6a5b07
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [638 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [910 kB]
Fetched 1800 kB in 2s (1088 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  adb android-libadb android-libbase android-libcutils android-liblog
Recommended packages:
  android-sdk-platform-tools-common
The following NEW packages will be installed:
  adb android-libadb android-libbase android-libcutils android-liblog
  android-tools-adb
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 208 kB of archives.
After this operation, 632 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 android-liblog amd64 1:7.0.0+r33-2 [16.6 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 android-libbase amd64 1:7.0.0+r33-2 [17.6 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/universe amd64 android-libcutils amd64 1:7.0.0+r33-2 [21.3 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/universe amd64 android-libadb amd64 1:7.0.0+r33-2 [78.9 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/universe amd64 adb amd64 1:7.0.0+r33-2 [68.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/universe amd64 android-tools-adb all 1:7.0.0+r33-2 [5406 B]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 208 kB in 1s (270 kB/s)
Selecting previously unselected package android-liblog.
(Reading database ... 33942 files and directories currently installed.)
Preparing to unpack .../0-android-liblog_1%3a7.0.0+r33-2_amd64.deb ...
Unpacking android-liblog (1:7.0.0+r33-2) ...
Selecting previously unselected package android-libbase.
Preparing to unpack .../1-android-libbase_1%3a7.0.0+r33-2_amd64.deb ...
Unpacking android-libbase (1:7.0.0+r33-2) ...
Selecting previously unselected package android-libcutils.
Preparing to unpack .../2-android-libcutils_1%3a7.0.0+r33-2_amd64.deb ...
Unpacking android-libcutils (1:7.0.0+r33-2) ...
Selecting previously unselected package android-libadb.
Preparing to unpack .../3-android-libadb_1%3a7.0.0+r33-2_amd64.deb ...
Unpacking android-libadb (1:7.0.0+r33-2) ...
Selecting previously unselected package adb.
Preparing to unpack .../4-adb_1%3a7.0.0+r33-2_amd64.deb ...
Unpacking adb (1:7.0.0+r33-2) ...
Selecting previously unselected package android-tools-adb.
Preparing to unpack .../5-android-tools-adb_1%3a7.0.0+r33-2_all.deb ...
Unpacking android-tools-adb (1:7.0.0+r33-2) ...
Setting up android-liblog (1:7.0.0+r33-2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up android-libbase (1:7.0.0+r33-2) ...
Setting up android-libcutils (1:7.0.0+r33-2) ...
Setting up android-libadb (1:7.0.0+r33-2) ...
Setting up adb (1:7.0.0+r33-2) ...
Setting up android-tools-adb (1:7.0.0+r33-2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Removing intermediate container 353bbf6a5b07
 ---> f98a361c5646
Step 4/10 : RUN wget -q -c https://s3-us-west-2.amazonaws.com/px4-tools/minimalSDK.tgz -O /tmp/minimalSDK.tgz 	&& tar zxf /tmp/minimalSDK.tgz -C /opt 	&& rm -rf /tmp/*
 ---> Running in 3b3c2b788418
Removing intermediate container 3b3c2b788418
 ---> c47f96ac1834
Step 5/10 : ENV HEXAGON_SDK_ROOT="/opt/Qualcomm/Hexagon_SDK/3.0"
 ---> Running in 030f0654282a
Removing intermediate container 030f0654282a
 ---> 6826fa63d723
Step 6/10 : ENV HEXAGON_TOOLS_ROOT="/opt/Qualcomm/HEXAGON_Tools/7.2.12/Tools"
 ---> Running in 5d14ddcf0f25
Removing intermediate container 5d14ddcf0f25
 ---> 0d10f39d01fd
Step 7/10 : ENV HEXAGON_ARM_SYSROOT="/opt/Qualcomm/qrlinux_v4_sysroot/merged-rootfs"
 ---> Running in 410c6fc95b1e
Removing intermediate container 410c6fc95b1e
 ---> 6307434269be
Step 8/10 : ENV PATH="/usr/lib/ccache:${HEXAGON_SDK_ROOT}/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf_linux/bin":$PATH
 ---> Running in 8d06c3905986
Removing intermediate container 8d06c3905986
 ---> 58ba483dbb00
Step 9/10 : RUN ln -s /usr/bin/ccache /usr/lib/ccache/clang 	&& ln -s /usr/bin/ccache /usr/lib/ccache/clang++ 	&& ln -s /usr/bin/ccache /usr/lib/ccache/arm-linux-gnueabihf-gcc 	&& ln -s /usr/bin/ccache /usr/lib/ccache/arm-linux-gnueabihf-g++
 ---> Running in 485213d3bfa3
Removing intermediate container 485213d3bfa3
 ---> 0a9f76dac007
Step 10/10 : ENV CCACHE_CPP2=1
 ---> Running in 6d7e43f43a96
Removing intermediate container 6d7e43f43a96
 ---> 563c8b0ad138
Successfully built 563c8b0ad138
```

@LorenzMeier would it be possible to you to bring the docker built on your private Docker Hub? Thanks!

**Comment by dagar** [comment]
I think we'll need to find a more accessible solution for this container.

**Pull request closed without merging**
