### PR TITLE
VTOL transition maintain FW_PSP_OFF

### PR DESCRIPTION
**Pull request by sanderux**
Implements https://github.com/PX4/Firmware/issues/6709

From SITL:
image

### CODE REVIEW

**Comment by dagar** [comment]
Looks good, just make sure the att_sp quat is updated properly.

**Comment by sanderux** [comment]
@dagar indeed it wasn't actuated, does seem so now.
(massive values for dramatic effect)

image

**Comment by sanderux** [comment]
In actual flight it dropped massively (5m/s) after back transition.
Not sure if it's related to this.
http://logs.uaventure.com/view/qSiQiq3uZ2LzZ7FSGend8a

**Comment by sanderux** [comment]
@Stifael could your recent landing changes be the cause of this?

**Comment by sanderux** [comment]
It had detected landing, need to have a very good look at that

**Comment by Stifael** [comment]
@sanderux  this alt max did not exist in the past and I introduced it. I changed it from 15 to 100 because the 15 was a value that I set for testing purpose. The alt max is a variable that defines the max altitude that can be reached, and actually has no influence on the landing detection even though its within the landdetector. The reason why we put the alt max logic into the landdetector is because it was the module that already was used by other modules to get the required info. At some point we are planing on changing the landdetector name  to some other name which better represents the task, or even add it this alt max to a geofence module. The bottom line is that this alt max has no effect on the landdetection, especially if you fly below 100m.  @MaEtUgR can u please look at this issue?

**Comment by sanderux** [comment]
i noticed, i tried it with 15m and it would not even pass that altitude during takeoff but just hold at that altitude. Also, when landing above that altitude it gets stuck at that altitude. I think it needs some more reviewing and i would propose to disable it for the moment as it is very confusing and might lead to undesired consequences.

@LorenzMeier any thoughts?

**Comment by Stifael** [comment]
@sanderux. Thats the point of the alt max. It is a limit that should not be exceeded. If you dont want to use it then put it to 1000 or whatever, but definitely not to 15

**Comment by Stifael** [comment]
Or put it to inf

**Comment by sanderux** [comment]
Well, whats unclear to me is;
A. It is supposed to just hover at that altitude if a mission reaches  that altitude in takeoff or land? Doesnt seem safe
B. If it's a landimg param, why is takeoff affected?

**Comment by Stifael** [comment]
It supposed to be not exceeded  no matter what. You can still fly below that altitude. The goal is also to adjust this height depending on battery status at some later point. 
I agree with you that the param should be defined within an other module, but currently the landdetector is the module that is used throughout the firmware and checks flight status. It will be moved or renamed.

**Comment by sanderux** [comment]
Shall we touch this topic quickly on the devcall?

**Comment by LorenzMeier** [comment]
We should. In particular CI testing and flight testing for VTOL. We can't guarantee to not have regressions, but we need to guarantee to catch those early.

**Comment by LorenzMeier** [comment]
@sanderux What is the testing level of this? Do you have a log?

**Comment by sanderux** [comment]
It works very nicely: http://logs.uaventure.com/view/ixvdeSV9oPzEYeoWhsPCA8

**Comment by sanderux** [comment]
Especially the last change giving full weight to MC in back transition seems to have a very good effect. I think this could merge for enhanced transition performance.

**Comment by dagar** [comment]
Log looks pretty good, but I don't think we should immediately give MC full weight. Initial MC thrust starts at MPC_THR_HOVER (60%). I think it's safe to get to full MC much sooner, but not 100% immediately unless we want to look into initializing MPC differently.

Here's a plot during back transition. With full weight MC thrust immediately jumps to 60% (MPC_THR_HOVER), but then settles at 30% (MPC_THR_MIN). Only after about 5 seconds into back transition does the MC throttle need to exceed the minimum. By this point you overshoot the altitude setpoint by 4-5 meters.

back

What if we merged the FW_PSP_OFF portion and moved the MC weight to another PR/discussion?


It recently occurred to me that successful forward transition could be dependant on MC thrust setpoint dropping below a threshold, but only if forward transition kept full MC weight as well. Additionally I think there's no need to blend in FW actuator controls. Without airspeed they're harmless, and giving the FW controller more time to acclimate will only help.

**Comment by sanderux** [comment]
Ok, lets merge the PSP stuff and move MC to a different PR (ill add it again).
For forward transition it also occurred to me that the current fading isnt such a good idea, perhaps we could add some control based on altitude. Also it resets the alt setpoint to where it started transition, that is something i added when fighting altitude drops in front trans but was likely the wrong approach.

**Comment by dagar** [comment]
Where is the altitude setpoint reset?

**Comment by sanderux** [comment]
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission.cpp#L1500

**Comment by sanderux** [comment]
@dagar who is on this now?

**Comment by dagar** [comment]
I thought you were, although I can do it if you're busy.

**Comment by sanderux** [comment]
Can you merge the first 4 commits? i make it a habit of not merging my own commits.

**Comment by dagar** [comment]
Last commit dropped (trivial to recreate). Once the build passes I'll squash and merge.

**Pull request merged**
