### PR TITLE
EKF unfiltered airspeed

### PR DESCRIPTION
**Pull request by LorenzMeier**
@tumbili This is good for testing. It should help with larger altitude control gains.

Please make sure to fly the *very same* mission with this patch set and without.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@tumbili So this was a full success and is good to go?

**Comment by tumbili** [comment]
@LorenzMeier No, this is the only one I haven't managed yesterday due to a storm that came up. I also don't like flying things I didn't look at so I will do this today.

**Comment by tumbili** [comment]
This is a log of a flight where airspeed was filtered:
 http://dash.oznet.ch/view/zhioCobkEQQaVB7Qkt6QZM

This is a log of a flight where airspeed wasn't filtered (after the ekf):
 http://dash.oznet.ch/view/mbwLjLcZyzrAqBrRJ8YpXC

**Comment by LorenzMeier** [comment]
Ok, this is good to go. It will eventually allow tighter tuning gains without oscillation.

**Pull request merged**
