### PR TITLE
fw_pos_control_l1 fix FW_LND_FLALT usage

### LINKED ISSUE #4745: langding bug of fixwing
Today I broke my model.In Hil,landingslope.flare_relative_alt() always equal zero. it lead to can not limt throttle.

### PR DESCRIPTION
**Pull request by dagar**
-fixes #4745

I'm going to do a more thorough check of param usage, but here's a quick fix for issue.

### CODE REVIEW

**Comment by dagar** [comment]
TODO: add mission test to builds that does full auto takeoff, mission, auto land

**Comment by dagar** [comment]
@LorenzMeier what do you think about adding a PX4_WARN here? - https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/param/param.c#L271

**Comment by LorenzMeier** [comment]
Kind of significant enough to try it I guess.

**Comment by LorenzMeier** [comment]
Should have a config option though to disable - on APM this will spam the console.

**Comment by dagar** [comment]
@LorenzMeier After some browsing the ardupilot build with @magicrub's help I don't see any PX4 param stuff being built. Can you verify?

**Comment by dagar** [comment]
Hmm, outside of HIL this is spamming the console. Let's see...

    WARN  [modules__systemlib] Parameter CAL_ACC3_ID not found
    WARN  [modules__systemlib] Parameter CAL_ACC3_ID not found
    WARN  [modules__systemlib] Parameter CAL_MAG3_ID not found

**Comment by dagar** [comment]
Well with the warning I've gone through startup of HIL and real quad, fw, and vtol and there's nothing else critical missing. I'll remove the warning.

**Comment by LorenzMeier** [comment]
Warning is not hurting, so I would leave it in.

**Comment by dagar** [comment]
It's continuous.

screenshot from 2016-06-16 14 57 25

**Comment by LorenzMeier** [comment]
got it.

**Pull request merged**
