### PR TITLE
added offset with rotation matrix and yaw towards target

### PR DESCRIPTION
**Pull request by catch-twenty-two**
Work in progress do not merge

### CODE REVIEW

**Comment by catch-twenty-two** [comment]
First field test was successful:

https://www.youtube.com/edit?o=U&video_id=gWfquFp3zgA

Planning on doing more with larger area to move around in.

**Comment by catch-twenty-two** [comment]
Video here:

https://youtu.be/YXsvk6GKsic

So far, so good!

**Comment by tumbili** [comment]
@catch-twenty-two Not bad. Great gimbal you are using there by the way :-D

**Comment by tumbili** [comment]
@catch-twenty-two Let us know where this stands and when you think it's ready for review.

**Comment by catch-twenty-two** [comment]
@tumbili ha ha, thanks. :)  I have a new pr up to replace this one. It adds more safe guards and some UX customization with params. I am going to go out and test tomrrow, ill let you know how it goes.

https://github.com/PX4/Firmware/issues/4216

**Pull request closed without merging**
