### PR TITLE
Aerocore update

### PR DESCRIPTION
**Pull request by jgoppert**
This merges in the work from: https://github.com/aerocore/Firmware and fixes some C++ warnings.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@jgoppert They just came out with AeroCore 2 - is that the same board? There must be more people working with this..

**Comment by jgoppert** [comment]
Yes, we saw the aerocore 2, we didn't notice any significant changes besides using headers so you don't have to do too much custom cable work. The pain with the aerocore/ aerocore2 is that without the SD card and IO board it is a substantially different design then those currently utilized by PX4 and requires significant code changes. We also didn't find that there was a significant developer base. We recently got our aerocore to the point it could fly but this required substantial hacking. @BMP-TECH has the latest hacks to make it capable of fly a quadrotor.

Example changes:
* there is no safety switch/ io board so we had to hack calibration regardless of the arming state (not safe)
* @BMP-TECH had to do some hacking the servo startup script.

We would like to get this working version committed to master, but it is still quite messy and the safety issues should be addressed.

**Comment by LorenzMeier** [comment]
@jgoppert As long as the concerns with the driver architecture of the AeroCore persist and given the small user base we will hold off merging this. Its your call if you want to address the comments from the original PR or switch gears to a different platform.

**Comment by LorenzMeier** [comment]
@jgoppert I'm closing this PR as its becoming stale - we would love to have better Aerocore support, but I'm not convinced yet that it would be good to pull this in without addressing @px4dev 's comments first.

**Comment by jgoppert** [comment]
No problem, we might have a chance to do this properly at some point, but I don't have the time right now.

**Pull request closed without merging**
