### PR TITLE
Removing @board tag from the PARAM_DEFINE.  Use of this tag prevents …

### PR DESCRIPTION
**Pull request by jywilson**
…the copying of the parameter into the parameters.xml file generated at build time.  I will generate an Issue for this problem.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Are you able to arm with this patch?

**Comment by ChristophTobler** [comment]
@LorenzMeier I'm not able to arm with this patch

**Comment by LorenzMeier** [comment]
@jywilson Still needed? Would need a rebase.

**Comment by LorenzMeier** [comment]
@jywilson @mcharleb @bharath374 Where is this standing?

**Comment by jywilson** [comment]
This PR is no longer needed and has been fixed in other PR's.  The Snapdragon Flight board will now arm without these changes.

Specifically, the params.c file has been deleted, and the line "PARAM_DEFINE_INT32(MAV_TYPE, 2);" has already been removed uart_esc_params.c.

**Pull request closed without merging**
