### PR TITLE
add new rotation

### PR DESCRIPTION
**Pull request by jinchengde**
I haven't find any rotation for ROLL_270_YAW_180, add it

### CODE REVIEW

**Comment by dagar** [comment]
I'm wondering if there's value in trying to keep in sync with mavlink? https://mavlink.io/en/messages/common.html#MAV_SENSOR_ORIENTATION

**Comment by jlecoeur** [comment]
@dagar yes, be careful that the current implementation assumes that enum values are consecutive, without gap. I was tricked last time I added a rotation following MAVLink's enum, which was not equal to last enum value +1. I finally added the rotation at the end of the PX4 enum by pure lazyness.

**Comment by jinchengde** [comment]
and the rotation enum is so disarray, do you wish to arrange?

**Comment by julianoes** [comment]
@jinchengde I think we need this one: https://github.com/mavlink/mavlink/pull/1348

**Comment by julianoes** [comment]
@jinchengde could you update this based on https://github.com/mavlink/mavlink/pull/1348 ?

**Comment by jinchengde** [comment]
@julianoes do you mean modify the enum to 41?

**Comment by julianoes** [comment]
Yes, thanks @jinchengde. And it would be nice to also update the mavlink (c_library_v2) submodule to latest master.

**Comment by julianoes** [comment]
Nevermind, this is already done in https://github.com/PX4/Firmware/pull/14725.

**Comment by dagar** [comment]
The table (rot_lookup[]) needs to align with the enum. Let's quickly add the missing rotations from mavlink.

Screenshot from 2020-04-23 10-50-58

I'm also starting to think we'd be better abstracting the mavlink constants entirely from PX4, but that's a messy change.

**Pull request merged**
