### PR TITLE
FW airspeed mode

### PR DESCRIPTION
**Pull request by dagar**
This pull request introduces fixed wing airspeed mode. Airspeed mode is the minimum manual mode that's appropriate (safe) for an operator without RC experience.
It's a stabilized mode with manual throttle and airspeed controlled with the pitchstick. It feels similar to STAB, but you can't stall the plane.

**Questions**
- ~~where should this fit in with the existing modes and switches?~~
- ~~this mode is much better with the TECS time constant significantly reduced, could it scale automatically?~~ You just need to properly tune TECS
- ~~this doesn't currently work with mTecs, does anyone use it?~~
- ~~should this mode respect FW_THR_MIN/FW_THR_MAX?~~

### CODE REVIEW

**Comment by dagar** [comment]
I tested most combinations of mode transitions to and from airspeed mode HIL today and didn't see any obvious problems.
Log muncher might be broken: http://logs.uaventure.com/view/GcnQdeGGB4qgMJDwX8HQng

Reinitializing TECS between airspeed mode and any other TECS mode is a bit abrupt, I'm going to just changing the parameters instead.

**Comment by SimonWilks** [comment]
Logmuncher is working again for this log. Something odd happened with it.

**Comment by dagar** [comment]
The throttle transition from airspeed mode full throttle to altctl is pretty bad. Rethinking the way I'm abusing TECS.

**Comment by dagar** [comment]
Ok, back to where I started. TECS is completely reset between AIRSPEED and ALTCTL/POSCTL/AUTO. It's no worse than switching from MAN/STAB to those modes.

I still want to think about automatically reducing the TECS time constant just in this mode, but I'm otherwise happy with the state of this during HIL testing and ready for an actual flight test.

@LorenzMeier would you recommend flying master as of today, or should I cherry-pick this to stable?

**Comment by dagar** [comment]
I've cherry-picked to stable for flight testing. https://github.com/PX4/Firmware/compare/stable...dagar:fw_airspeed_mode-stable?expand=1

**Comment by dagar** [comment]
@SimonWilks is this new mode killing logmuncher? http://logs.uaventure.com/view/tNysut35PRAqfF8qe2xhr7

**Comment by dagar** [comment]
Here's a plot from a successful flight of airspeed mode (ported to stable). The plot shows airspeed setpoint changing with elevator input, and manual throttle. This part of the plot was ALTCLT -> AIRSPEED -> ALTCTL with no problems. Altitude is scaled by 0.1.

airspeed_1

@LorenzMeier what are the next steps?

**Comment by AndreasAntener** [comment]
This confused me a bit so I hope you don't mind my questions. I had to look in the code before to understood how this is supposed to work ;).

How is this different from altitude control from the users perspective? Maybe you could explain a bit where the need for this mode is coming from?

Don't you have 2 inputs that have an effect on altitude now? So I'm assuming thrust is your main altitude control now (with speed-weight 2). But also if you change the airspeed setpoint TECS will have to dive/climb (because it has no other means anymore of matching the speed)?

**Comment by dagar** [comment]
Think of it as a safe manual mode. Similar to stabilized mode, but the autopilot maintains a safe airspeed [FW_AIRSPEED_MIN, FW_AIRSPEED_MAX] at all times to prevent the vehicle from stalling. It's very useful for manually landing a UAV. In a locked down configuration for a user this would be their manual mode (which they wouldn't expect to hold altitude).

This airspeed mode is actually what several commercial UAVs and autopilots refer to as manual mode.

You should try it in a simulator with appropriate min, trim, and max airspeeds and possibly reducing the TECS time constant. It feels like flying in stabilize mode, but the pitch responds a bit slower.

**Comment by AndreasAntener** [comment]
Landing, that's interesting. I mean, you have the same problem here as in alt/posctl: you cannot flare. How does the stick movement look for a landing? Wouldn't you want to reduce airspeed AND throttle for a landing?

Naive question: have you tried plain altitude control with a reduced TECS time constant? I know you don't have manual throttle there, just wondering if the control feeling would already be better then.

> This airspeed mode is actually what several commercial UAVs and autopilots refer to as manual mode.

Could you give me an example? (because I'm curious, not because I don't believe you :))

**Comment by dagar** [comment]
Actually you can flare by pulling the pitch stick completely back, assuming you approach above min airspeed. Having direct control over throttle makes this mode much safer than ALTCTL for handling on the ground at launch or landing.

I haven't tried ALTCTL with a reduced TECS time constant, but I generally use it when I want to just stay at the same altitude and not think about it.

The Procerus Kestrel autopilot (acquired by Lockheed) and fixed wing UAVs from AeroVironment refer to this as manual mode.

**Comment by dagar** [comment]
@LorenzMeier @AndreasAntener do you have any other questions? What's the path forward for getting this merged?

**Comment by dagar** [comment]
Rebased and resolved conflict.

**Comment by dagar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IvXjv34B&#x2F;723-px4-airspeed-mode-test"> PX4 airspeed mode test</a>

**Comment by dagar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IvXjv34B&#x2F;723-px4-airspeed-mode-test"> PX4 airspeed mode test</a>

**Comment by LorenzMeier** [comment]
@dagar I can't access that Trello card.

**Comment by dagar** [comment]
Whoops, sorry that's my personal todo list that I had no idea was posting on my behalf.

**Comment by LorenzMeier** [comment]
Another rebase would be great, and more clarity on testing - would it be possible for you to test this, position control, altitude control and an auto mission? I would also love to understand the time constant change you mentioned.

**Comment by dagar** [comment]
I've flown this a couple times and it works as intended with no problems, but the airspeed response isn't great. I've been having a hard time tuning TECS to respond nicely for this mode, but still work well normally.

**Comment by AndreasAntener** [comment]
@dagar What about leaving airspeed control away if within min/max? There is a lot of talk about stall prevention ATM. I believe your reasoning behind this "airspeed" mode is not different from people simply requesting stall prevention methods. Maybe it could be more of a mix, having manual throttle/pitch/roll control, but start limiting pitch/roll when airspeed gets borderline, and use TECS to pitch down if airspeed falls below min.

**Comment by tubeme** [comment]
@dagar Sounds very promising.

@AndersonRayner Here is what the APM is doing about stall:

> when in roll controlled modes the autopilot will monitor your demanded bank angle and airspeed and work out if you have sufficient margin above the stall speed to turn at the demanded bank angle. If you don’t then the turn will be limited to the safe limit, but it will always allow a bank of at least 25 degrees (to ensure you can still maneuver if your airspeed estimate is badly off).

We've seen this technique in other two more simpler controllers and it works.

> when in auto-throttle modes the autopilot will also raise the minimum airspeed in the TECS system to the level at which the current demanded bank angle can be safely achieved. So it will add more engine power or lower the nose to raise the airspeed so that the bank angle that the navigation controller is demanding can be achieved without a stall

They use these two parameters:

> The **STALL_PREVENTION** parameter. If this is set to zero then no stall prevention is done. This may be useful if you have no airspeed sensor and the synthetic airspeed estimate is not good 
> enough
> 
> The **ARSPD_FBW_MIN** parameter, which is the configured minimum airspeed for level flight. It is this value that is scaled with the bank angle to calculate the safe airspeed for any demanded bank angle

I'm not saying we have to copy, but there is not a big choice of approaches toward stall. It is classical physics.

**Comment by dagar** [comment]
@AndreasAntener how would we keep TECS happy/initialized in between?

Hopefully I'll have some time to play around again later this week. I'll provide some plots of pitch input and response. It should be possible to get it to respond nicely when you're within the airspeed limits. Worst case I'll try doing airspeed control with only pitch outside of TECS.

**Comment by dagar** [comment]
Rebased on master. I've been trying to gain a better understanding of TECS so that I can figure out how to make this mode work nicely. Update coming soon.

**Comment by LorenzMeier** [comment]
@dagar Where is this standing?

**Comment by dagar** [comment]
Waiting for me to actually go to the field and fly.

**Comment by jcooper21** [comment]
This looks like a great mode. I may have some spare time coming up to test this mode and provide feedback. Is it in PX4 beta or master build and in the daily build of QGC?

**Comment by dagar** [comment]
TODO - only allow transition to this mode for fixed wing

**Comment by dagar** [comment]
@jcooper21 this hasn't been tested since a large rebase so I need to spend some time at the field.

If you haven't already I'd suggest you thoroughly tune TECS.

https://pixhawk.org/users/fixedwing_pid_tuning#tecs_tuning_altitude

The ArduPlane documentation is good, but many of the params are named differently.
http://ardupilot.org/plane/docs/tecs-total-energy-control-system-for-speed-height-tuning-guide.html

**Comment by jcooper21** [comment]
My tuning should be good. I'll test this when I get back from my vacation in a while. I'd this going to be the new stabalize mode? Also if it controls min air speed how do I land?

**Comment by jcooper21** [comment]
Is this in QGC daily and px4 matter so I can set it up to test?

**Comment by dagar** [comment]
I'll reopen this once I've had a few thorough flight tests with data and it's ready to be merged immediately.

**Pull request closed without merging**
