### PR TITLE
SYS_LOGGER option to disable logging

### PR DESCRIPTION
**Pull request by dagar**
I couldn't test the tap change.

### CODE REVIEW

**Comment by julianoes** [comment]
What about `-1`?

**Comment by dagar** [comment]
That makes more sense.

**Comment by dagar** [comment]
I just tried to rebase I saw sdlog2 completely removed from rcS. Any point keeping it?

**Comment by LorenzMeier** [comment]
Just removed from tap, not from px4fmu.

**Comment by dagar** [comment]
WIP needs rebase

**Comment by LorenzMeier** [comment]
I'm closing this since we move to ulog. If we need it there it should be -1 for the logging rate parameter, not in the rcS.

**Pull request closed without merging**
