### PR TITLE
Multi pub/sub rework

### PR DESCRIPTION
**Pull request by LorenzMeier**
This fixes the uORB interface for multi-topics (e.g. sensors).

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Waiting for test results from Damiano, good to merge after.

**Comment by LorenzMeier** [comment]
@sjwilks If you could this a quick flight test it would be appreciated. It shouldn't change anything.

**Comment by LorenzMeier** [comment]
@pavel-kirienko @hsteinhaus Could you test with your GPS modules?

**Comment by pavel-kirienko** [comment]
I will, stay tuned.

**Comment by pavel-kirienko** [comment]
It boots fine, and works OK with Zubax GNSS connected, but when I connect a Pixhawk ESC to the running system, it crashes:

```
Assertion failed at file:armv7-m/up_hardfault.c line: 184 task: uavcan
sp:     20009294
IRQ stack:
  base: 200092e0
  size: 00000ffc
20009280: 08071e0d 080a4126 20009294 200134e0 08077e99 080a41ec 000000b8 08071e0d
200092a0: 00000010 200065ec 00000003 00000000 08078125 08078111 08083b9b e000ed24
200092c0: 0808182d 00000000 2001329c 00000007 20013298 00000062 08078095 2001317c
sp:     20013250
User stack:
  base: 200134e0
  size: 00000bb4
20013240: 45655000 448f4000 80000010 08066425 00000000 00000000 20010a28 00000001
20013260: 00000000 0808c261 00000007 20013298 20011920 2001195c 20013368 08066325
20013280: 00000000 00000000 200132c0 0806022b 20013368 2001329c 00000000 20013200
200132a0: 00000062 0000e800 00000000 00000002 0000000e 08065ac9 20013338 0000e8c3
200132c0: 0809f358 207a4971 00d90b97 00000000 00000000 00000000 000a0002 20013320
200132e0: 00000000 00000000 000f4240 2001194c 00000001 00000002 00000002 20011930
20013300: 20013368 200133e8 20013458 08065f41 00000001 08064d39 0806020a 00000000
20013320: 2001194c 2001020a 00000001 20013340 00000000 0805fec1 20005b00 0806948d
20013340: 00d90be5 00000000 00000000 20010f88 0000ffff 000000ff 00000004 200109f0
20013360: 00000000 08063d4d 7fff207a 00000000 02590002 01000a08 00000100 ffffffe9
20013380: 00d90be5 00000000 00000000 00000000 20010900 200109f8 00000000 200109f0
200133a0: 200109f8 00000000 00000000 08063e57 00000000 00000001 00000000 00000000
200133c0: 92cc2818 7fff207a 00000000 00000008 00d90be5 00000000 00000000 00000000
200133e0: 00000000 3f747c00 00000000 00000000 00000000 00000000 1000cc48 0807297d
20013400: 1000cc48 00000000 20011b78 08004f2d 08004e71 0809da90 20011b78 00000000
20013420: 00000000 20011c70 00000001 20013498 20013450 20013458 200109e8 0806674f
20013440: 00000000 0807923f 200109f0 200109ec 00000000 00000000 00000000 00000000
20013460: 20011c6c 2000dc70 20011c6c 20011c70 00000001 20011a70 20011780 20011a70
20013480: 00000000 0805d5f1 20011a74 20011c6b 20011c18 2000dd00 00000000 00000000
200134a0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
200134c0: 00000000 00000000 00000000 0805dbfb 0805dbf1 080732dd 00000000 00000000
R0: 20013200 0000000c 20013254 00000002 2001329c 00000007 20013298 00000062
R8: 00000002 20011998 20011930 20013320 00000003 20013250 080663f9 00000062
xPSR: 00000000 BASEPRI: 00000000 CONTROL: 00000000
EXC_RETURN: ffffffe9
```

ELF: https://yadi.sk/d/XYYOuybqeHRHe

I didn't investigate it yet.

**Comment by pavel-kirienko** [comment]
Sometimes it doesn't crash immediately, but a minute or so later.

**Comment by pavel-kirienko** [comment]
Don't laugh but it crashes on master as well.

**Comment by pavel-kirienko** [comment]
And you don't need Zubax ESC to reproduce it - a single Pixhawk ESC is enough. It doesn't have to do anything but publish its status messages.

**Comment by pavel-kirienko** [comment]
Failure can be reproduced only if uavcan is compiled with `-O3`.

`-O1`, `-O2`, `-Os` seem to work reliably.

This was observed on GCC 4.8.4.

**Comment by pavel-kirienko** [comment]
Failure cannot be reproduced with GCC 4.7.4 at any optimization level.

**Comment by pavel-kirienko** [comment]
It fails on GCC 4.9.3 as well. My first guess is that there was a regression in GCC 4.8 optimizer.

**Comment by LorenzMeier** [comment]
@pavel-kirienko Thanks to @davids5 we have fixed a quite nasty memcpy() bug. I would think that your experience is much better now. Could you give this version another try?

**Comment by pavel-kirienko** [comment]
Where can I see the fix? Was it discovered by Coverity?

I'll test it later tonight.

**Comment by LorenzMeier** [comment]
No, coverity didn't help at all here. It was David's skills alone.

**Comment by pavel-kirienko** [comment]
@LorenzMeier @davids5 Amazing, it doesn't fail anymore. Tested with Pixhawk ESC and Zubax GNSS.

**Comment by LorenzMeier** [comment]
@thomasgubler @sjwilks Could you fly this branch?

**Comment by LorenzMeier** [comment]
@kd0aij Flight tests would be great!

**Comment by sjwilks** [comment]
Will test today if possible.

**Comment by hsteinhaus** [comment]
A short hover-only test flight  with APM master using UAVCAN ESCs and GNSS/baro/mag shows no adverse effects (with both gcc 4.8.4 and 4.9.3). 

The general performance of the UAVCAN setup seems to have improved significantly. CPU load of the uavcan stack is in the 2% range now with Arducopter armed and running. 

I also get fast and sinus-shaped oscillations when setting high D gains now. At the time of submitting issue #1417, the oscillations looked rather erratic and did  not nearly reach the frequency observed now  (aliasing?). All tests were done using exactly the same airframe and drive setup.

**Comment by thomasgubler** [comment]
@LorenzMeier Why does actuator_controls still use multiple topics? https://github.com/PX4/Firmware/blob/a381ce37323b08597df637e901099fcdd69c6ec1/src/modules/uORB/topics/actuator_controls.h#L74

**Comment by LorenzMeier** [comment]
I didn't want to become over-optimistic and change too much at once. There is really not other reason than that and a PR addressing those last bits is welcome.

**Comment by LorenzMeier** [comment]
Actually, I take that comment back. We need to think again about these output groups. mag0 / mag1 capture the same dimension, while actuator control group 0..3 are not the same actuators, they do different things. So maybe the right thing is to rename them actuator_controls_attitude, actuator_controls_payload, actuator_controls_passthrough or something like that. Because that would actually capture what they are meant to be.

**Pull request merged**
