### PR TITLE
FMUv4: enable RSSI analog input pin

### PR DESCRIPTION
**Pull request by tridge**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Jenkins test this please.

**Comment by tridge** [comment]
I'm not quite sure what you mean by "jenkins test this", sorry
It has been tested on a pixracer, and multiple users of pixracer on ardupilot have confirmed it works for them

**Comment by LorenzMeier** [comment]
:) I was talking to my build server: https://en.wikipedia.org/wiki/Jenkins_%28software%29

**Comment by tridge** [comment]
yep, I know what jenkins is, I didn't realise you had it setup to look for a trigger string. I thought perhaps you meant I was supposed to write a test for each of these PRs that would work against a real hardware setup integrated with jenkins.

**Comment by LorenzMeier** [comment]
Thanks, applied!

**Pull request closed without merging**
