### PR TITLE
Fixes for building posix target on Linux with clang

### PR DESCRIPTION
**Pull request by mcharleb**
The --start-group and --end-group flags are needed.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by mcharleb** [comment]
@LorenzMeier Make sure this still works for gcc on Apple. I may have been overzealous in my change logic.

**Comment by LorenzMeier** [comment]
The CI system builds on Mac OS. So if this passes its good to go.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
