### PR TITLE
[WIP] Add basic Rally/Safe Points in RTL

### PR DESCRIPTION
**Pull request by bkueng**
This adds a basic implementation for Safe Points in RTL. If there are Safe Points, the vehicle will fly to the closest one (including the home position).

I decided to add it to RTL (versus the Landing mode in navigator), because the Landing is also used in failure cases such as GPS or global position loss.

@DonLakeFlyer I'll need QGC support to test this. From what I see the point upload is not enabled in https://github.com/mavlink/qgroundcontrol/pull/5474 due to https://github.com/mavlink/qgroundcontrol/blob/master/src/MissionManager/RallyPointManager.cc#L42.

@dagar @sanderux

### CODE REVIEW

**Comment by sanderux** [comment]
Looking really good. 
Perhaps we should make a distinction between a commanded RTL or a failsafe RTL. Or even make it a separate mode Land at Safe Point. I would imagine a low battery event set correctly might prefer RTL over Safe Point whereas a QuadChute event would favor Safe Point.

Also when manually switching RTL the Safe Point behavior might not always be the intended behavior.

**Comment by dagar** [comment]
I'm also wondering if we need to distinguish this from explicitly returning to home and how it fits with user expectations for return.

**Comment by LorenzMeier** [comment]
@bkueng I think we should have two distinct behaviours: One option is to fly to a safe point on a new command or failsafe action (need to check if something exists in the MAVLink spec) and the other to treat all equal and to fly to a safe location.

The very likely corner case being that you define safe points but the user is expecting RTL to return the vehicle (like pulling on a leash), not landing it out there. RTL Is right now the only method of conveniently getting a vehicle back that is at the edge of VLOS flight.

**Comment by Antiheavy** [comment]
There is some discussion here: https://github.com/mavlink/qgroundcontrol/issues/5725 and here: https://github.com/PX4/Firmware/issues/8116 about how this Safe/Rally point capability should probably be it's own mode and not part of "Return" mode.  One benefit of this would be the user could select it as a separate failsafe behavior for certain events and still select "Return" as failsafe behavior for other events.

**Comment by TSC21** [comment]
@bkueng do you have a plan to get back to this? Can we start by rebasing? @arwagoner FYI

**Comment by DonLakeFlyer** [comment]
FYI: Rally Points are supported in QGC. They were tested with MockLink which supports all the new mission type protocol.

**Comment by bkueng** [comment]
> @bkueng do you have a plan to get back to this? Can we start by rebasing? @arwagoner FYI

I think we first need to clarify and agree on the behavior that we want and the use-cases.

**Comment by TSC21** [comment]
Sure. What about discussing this in a call?

**Comment by bkueng** [comment]
dev-call?

**Comment by TSC21** [comment]
I am usually not available at the time of the dev calls so that's why I was suggesting an extra one

**Comment by bkueng** [comment]
Ok, can you organize it?

**Comment by Louisdirk** [comment]
@bkueng - Hi, is this PR tested OK with QGC(the latest verision v3.3.2) ?

**Comment by jros92** [comment]
I was trying to use this branch as the basis for a failsafe feature I would like to develop, and checked out the branch, but cannot get it to build due to incompatibilities with submodules (SITL build). Is it possible to use this feature without having to do a complete rebase? Or is anyone working on rebasing this already? Thanks!

**Comment by bkueng** [comment]
You'd have to rebase. But feel free to create a new PR if you have it working, I'm not working on this.
The biggest problem was that we (or at least I) never had a clear view of what the behavior should be.

**Comment by julianoes** [comment]
@bkueng is this still applicable?

**Comment by bkueng** [comment]
Yes, but the branch is just too outdated, so closing.

**Pull request closed without merging**
