### PR TITLE
[DO NOT MERGE] Saves 9640 bytes of FLASH

### PR DESCRIPTION
**Pull request by davids5**
This will save 9640 bytes of FLASH. It is dependant on this breaking (***manageable**) change. https://github.com/mavlink/c_library_v2/pull/2/commits/9b3d6b2b62bf9b4c727d8d84ef507a8dcd0995f1  

Commit 797c52e50287a8734540db5b67350338b3d89bf5 should be dropped if the PR is taken in upstream mavlink.

***The mavlink_inplement. file MUST be included in one and only one source file (.c or .cpp)**

### CODE REVIEW

**Comment by bkueng** [comment]
@davids5 bloaty shows no difference in binary size:
screenshot_20180720_0803212
http://ci.px4.io:8080/blue/organizations/jenkins/Firmware/detail/master_v2_lhf/1/pipeline/40/
Is it correct?

**Comment by davids5** [comment]
Rebased on current master

**Comment by dagar** [comment]
Oh that was the px4io output, jenkins first runs bloaty (+ variations) on the px4io first.

Here's the px4fmu-v2 output.

image

**Comment by bkueng** [comment]
Ah right, thanks!

Nice work @davids5!

**Comment by davids5** [comment]
Thank you @bkueng 
@dagar This just reinforces the Truth....I should not do **any** work before coffee :)

**Comment by dagar** [comment]
Was this all done manually on the generated output or is there an actual https://github.com/mavlink/mavlink change?

**Comment by davids5** [comment]
@dagar the changes are here https://github.com/mavlink/c_library_v2/pull/2  but I did not realize it was generated as @LorenzMeier let me know after the fact. So the changes need to be applied the source but it is a breaking change in that the mavlink_inplement.h file MUST be included in one and only one source file (.c or .cpp) in the application.

**Comment by LorenzMeier** [comment]
@davids5 Daniel brought this in.

**Pull request closed without merging**
