### PR TITLE
ekf2: Tighten preflight GPS quality checks

### PR DESCRIPTION
**Pull request by priseborough**
Enables drift checks and reduce thresholds.
Uses ecl version that activates drift checks when vehicle is carried.

Fixes: https://github.com/PX4/Firmware/issues/9549

**TESTING**

See comments

### CODE REVIEW

**Comment by priseborough** [comment]
Thresholds will need to be tuned through further testing.

**Comment by dagar** [comment]
I'm wondering if this is going to result in additional preflight failure message spam. 

    PREFLIGHT FAIL: GPS QUALITY POOR

Perhaps it only needs to be reported if arming is requested.

**Comment by LorenzMeier** [comment]
@dagar Makes sense.

**Comment by priseborough** [comment]
It's not clear to me what information is available to a preflight check to tell if arming is being requested.

**Comment by LorenzMeier** [comment]
@priseborough Daniel is talking about this:
https://github.com/PX4/Firmware/blob/d3c169b1e0ee488a98704ab4783346c31e1d3e31/src/modules/commander/PreflightCheck.cpp#L647-L661

Which triggers even if GPS is not used by EKF and if the vehicle is not armed. How do we avoid this triggering regularly now?

**Comment by dagar** [comment]
> How do we avoid this triggering regularly now?

The main reason (guessing) is that the check is disabled by default (COM_ARM_WO_GPS). 
If enabled there's a hardcoded time before it starts reporting. https://github.com/PX4/Firmware/blob/d3c169b1e0ee488a98704ab4783346c31e1d3e31/src/modules/commander/PreflightCheck.cpp#L923

For continued discussion - https://github.com/PX4/Firmware/pull/10018

**Comment by priseborough** [comment]
The additional GPS checks enabled checks in the ekf only run when the vehicle is on ground and not being moved. They will not run when in flight/armed or when IMU data detects vehicle movement. The reporting of false positives should  be managed through setting of appropriate threshold levels for the GPS tests set by EKF2_REQ_* and also the is_moving_scaler parameter which at the moment is not user adjustable. The is_moving_scaler parameter controls the sensitivity of the check that looks at IMU disturbance and determines if the user is carrying or otherwise moving the vehicle. When this happens the GPS drift checks are suspended to allow the vehicle to be picked up and relocated or hand carried without causing GPS checks to fail.

If these checks are failing, then the user should be alerted prior to commencement of GPS fusion  because failure will prevent the ekf commencing GPS fusion. We could ignore the bits associated with the drift checks once the EKF has commenced GPS fusion and accept a reduced level of protection.

I will add user adjustment of the is_moving_scaler parameter.

**Comment by priseborough** [comment]
I ran a static test with a Pixhawk4 Autopilot and GPS (Ublox8) with a clear sky view positioned between to buildings and trees with a blockage mask angle between 20 and 45 degrees depending on azimuth. The receiver took 25 seconds to achieve a lock and another 20 seconds for checks to pass. There were no further check failures after that for the duration of the 40 minute test.

screen shot 2018-07-25 at 2 16 33 pm

I will run additional tests  with periodic autopilot movements.

**Comment by priseborough** [comment]
We also need to establish reasonable value for fixed wing operations that usually do not require the same GPS position accuracy.

**Comment by priseborough** [comment]
Here are some results with the autopilot placed initially on the ground partially obscured by a tree with a mask angle of 85 degrees in the S quadrant, and brick structures with a 45 degree masks angle in the N,E,W quadrants.

There were occasional check failures. This is not a location where a reliable GPS position hold can be achieved.

screen shot 2018-07-25 at 2 51 07 pm

At 457 seconds the autopilot was picked up and moved to the location with better mask angle that avoided much of the tree blockage.

screen shot 2018-07-25 at 2 52 53 pm

At 487 seconds it was moved again passing underneath the tree and out into a more open area. Whilst stationary in this more open area there was one short failure of the vertical position drift test controlled by the EKF2_REQ_VDRIFT parameter at 543 seconds. This indicates that the vertical drift test is too strict or there is a problem with the calculation of the filtered drift rate.

At 593 seconds it was picked up and walked around for 40 seconds with no further check failures

I will add some temporary logging of the drift rates used for the tests to determine if  a change to the filtering or thresholds is required.

Logging of the vibe metrics used by the motion test indicates that the test should be simplified to use only the  high frequency gyro and gyro vector length. The high frequency accel metric logged in the estimator_status.vibe[2] message does not have enough margin between resting and moving to be useful:

screen shot 2018-07-25 at 3 43 27 pm

Whereas the high frequency gyro metric does. The default threshold for this metric should be lowered from the current value of 4.0E4 to 1.0E4

screen shot 2018-07-25 at 3 43 57 pm

The plot of gyro length indicates that the length threshold of 0.05 rad/sec is adequately detecting when the vehicle is being hand carried.

screen shot 2018-07-25 at 3 47 02 pm

**Comment by priseborough** [comment]
Ideas for reducing 'message SPAM' suggested so far include:

1) Only print when arming requested
2) Don't print once EKF is using GPS

**Comment by dagar** [comment]
> We also need to establish reasonable value for fixed wing operations that usually do not require the same GPS position accuracy.

Do you want to handle that now or after this is merged? The easy short term fix is updating https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rc.fw_defaults, but if we want to properly handle hybrid VTOLs I think we'll probably need to do it dynamically in ekf2.

**Comment by priseborough** [comment]
@dagar Given that the additional GPS checks are only relevant pre-flight in terms of enabling arming and GPS use, I think applicaton differences can be handled by amending  init.d/rc.fw_defaults

**Comment by priseborough** [comment]
I modified the code to log the horizontal drift, vertical drift and horizontal speed using the estimator_status.vibe[0], [1] and [2] messages respectively:

screen shot 2018-07-26 at 5 49 58 pm

This is from replay of a log recorded in a marginal location between two buildings and overshadowed by a tree. The vertical drift is peaking at 0.2 and the horizontal drift to 0.15

The vehicle was moved at 175 seconds to anclear sky location and then at 280 seconds was moved back to the bad location.

The horizontal drift threshold of 0.1 m/s and vertical drift threshold of 0.2m/s appears to be a OK starting point.

I will add some dedicated log messages to record these drift metrics to help with tuning.

**Comment by priseborough** [comment]
Test on vehicle with noisy GPS at following locations - urban envirnment

1) in top of a ledge in windy conditions where there was some wind induced movement - see events at 45 and 155 seconds where the drift check is temporarily blocked.

2) Relocated to a more open environment at 189 seconds. Checks suspend as expected during relocation.

3) Relocated to a location with more tree and building obstructions at 253 seconds. Checks suspend as expected during relocation. Horizontal drift fails temporarily.

screen shot 2018-08-02 at 11 14 12 am

screen shot 2018-08-02 at 11 53 38 am

GPS receiver reported speed accuracy is high and fails checks when being relocated because this involved waking underneath a tree canopy

screen shot 2018-08-02 at 11 55 36 am

**Comment by priseborough** [comment]
Rebased

**Comment by dagar** [comment]
Looks good to me, although we need to be aware of file descriptor limits in logger (number of topics actively logged).

Do you have a real flight log I could check quickly?

**Comment by priseborough** [comment]
Will try to get one later today when weather (wind) improves.

**Comment by priseborough** [comment]
I ran into issues with flipping on takeoff that were traced to the board orientation parameter being reset to 0 (no idea how that happened, and then a frsky receiver that was jamming the GPS, but after fixing those issues was able to get a short flight in POSCTL done. When checking results, bear in mind that the quad is a small 150 size vehicle and there were high winds and gusts.

See: https://logs.px4.io/plot_app?log=2a117d0c-85e9-424f-b41a-618710ad7329

The GPS receiver used was a 18x18 mm 'mini 8' and due to its small antenna is the noisiest in my collection, so makes a good receiver to check for false positives. The quad was on slightly uneven ground and due to the strong wind there was some rocking that caused running of the drift checks to be momentarily stopped.

screen shot 2018-08-15 at 2 14 05 pm

**Comment by priseborough** [comment]
Repeating the test indoors gave values of eph and epv that were just inside limits and a value of s_variance_m_s that was outside:

screen shot 2018-08-15 at 2 43 03 pm

In this location, GPS position was relatively stable, so calculated drift rates were low example

**Pull request merged**
