### PR TITLE
always recompile sdlog2 and ver command to keep GIT_DESC current

### PR DESCRIPTION
**Pull request by kd0aij**
addresses issue #2148

### CODE REVIEW

**Comment by dagar** [comment]
It's also used in src/modules/uavcan/uavcan_main.cpp (GIT_DESC becomes -DGIT_VERSION).
https://github.com/PX4/Firmware/blob/3f961bf3c60c3ea380dc1dc62684a026667ec0e9/src/modules/uavcan/uavcan_main.cpp#L215

**Comment by LorenzMeier** [comment]
@kd0aij I'd like to avoid shell commands as they are potential cross-platform build horror - or do we use touch already?

**Comment by kd0aij** [comment]
As I said on #2148, I'm pretty inept with make...
I'm sure there's a better way to force recompilation but I'm also sure I wouldn't understand the syntax :)

**Comment by LorenzMeier** [comment]
@mcharleb Could you think of a way to do this with make only?

**Comment by mcharleb** [comment]
Ideally you would not pass -DGIT_VERSION and you would generate a header file that src/modules/sdlog2/sdlog2.c and src/systemcmds/ver/ver.c include to get the definition of the variable.

**Comment by AndreasAntener** [comment]
@kd0aij Lorenz added the solution in the v1.0.0 branch: https://github.com/PX4/Firmware/commit/6d7e063148e2172edc41ebe5432794d4d39206f8

**Comment by AndreasAntener** [comment]
@LorenzMeier I think you fixed it for every module? So we could close this and #2148

**Comment by LorenzMeier** [comment]
Yes, thanks for checking!

**Comment by davids5** [comment]
This approach has another issue. The CC:      /home/david_s5/Desktop/dev/PX4/repos/mainline/Firmware/Build/git_version.c
 is built with the compile time settings of the first target to build it. 

In my case px4fmu-v1_default.build

Then when a lesser target tries to link to the file....

arm-none-eabi-ld: error: Build/git_version.c.o uses VFP register arguments, mainline/Firmware/src/modules/systemlib/module.pre.o does not
arm-none-eabi-ld: failed to merge target specific data of file 
mainline/Firmware/Build/git_version.c.o

**Comment by mcharleb** [comment]
Perhaps this needs to be created in the Build/target dir vs Build/

**Comment by davids5** [comment]
I think it should be an h file that the dependants file include and make should only update the file is the current git shal is not equal to the one in the file.

**Comment by mcharleb** [comment]
Yes, agreed. It should be a header file.

**Comment by davids5** [comment]
I am working on it in nuttx_next and will back port it

**Comment by davids5** [comment]
I think this [commit] (https://github.com/PX4/Firmware/commit/1cb81629ef10a7f9c550d4a4b02285c7545ec808) will fix it.

**Comment by LorenzMeier** [comment]
Superseded in master, closing.

**Pull request closed without merging**
