### PR TITLE
MAVLink: fixes for USB instance

### PR DESCRIPTION
**Pull request by bkueng**
Open the UART after adding the instance to the linked list, instead of before: mavlink_open_uart() might block, and in that case the parent task waiting for mavlink to be started times out.

And while waiting for the USB UART device to come up:
- check for _task_should_exit
- check for check_requested_subscriptions()

Side-effects when USB is not plugged in during boot:
- reduces boot duration by 100ms
- fixes duplicate instance name in 'top':
```
 201 mavlink_if0                     1  0.000  1328/ 2572 100 (100)  w:sig  3
 204 mavlink_if0                   572  4.221  1632/ 2540 100 (100)  w:sig  4
```
- 'mavlink stop-all' now stops the usb instance as well

### CODE REVIEW

**Comment by dagar** [comment]
Is this fixing a regression?

**Comment by bkueng** [comment]
I think part of the problems were not there some time ago, but I'm not sure. It's not something very recent for sure.

**Comment by mhkabir** [comment]
Should we backport this to 1.9? (and port to 1.10)

**Comment by bkueng** [comment]
Yes to 1.10 (https://github.com/PX4/Firmware/pull/13687), but as it's not critical, I don't think we need it on 1.9.

**Comment by mhkabir** [comment]
image

@bkueng I'm seeing the USB mavlink instance even when USB is not connected on master. Is this expected behaviour?

**Comment by bkueng** [comment]
Yes it's that you can still connect USB after booting. It exits once the vehicle arms.

**Comment by kuiskas** [comment]
This way is not possible to use 4 mavlink instances at the same time. How could I disable this USB mavlink instance? Is there a parameter or a file that could be edited?

**Comment by bkueng** [comment]
Mavlink on USB is started in a board-specific startup script, for example here for Pixracer: https://github.com/PX4/Firmware/blob/master/boards/px4/fmu-v4/init/rc.board_mavlink

**Comment by kuiskas** [comment]
Yeah I already tried disabling the PX4 fmuv5 rc.board_mavlink. But then I cannot connect through USB, while only USB power is on. How could I get the same behaviour as before?

**Pull request merged**
