### PR TITLE
Ros install fixes

### PR DESCRIPTION
**Pull request by AndreasAntener**
installation worked like this so far, will now try to run it ;)

### CODE REVIEW

**Comment by AndreasAntener** [comment]
:( tried empty and outdoor, both crashed
Also, for outdoor it mentioned it could not find some models, maybe there is still something missing in the setup.

screen shot 2015-01-16 at 18 31 49
screen shot 2015-01-16 at 18 29 01

**Comment by thomasgubler** [comment]
Ok thanks a lot for your effort. I will test the install again tomorrow using my ubuntu vm to check if it's a setup or vm issue.

**Comment by AndreasAntener** [comment]
:+1: 
what I don't know if the log would give any useful input. the problem is, the log it's referring to does not exist (also no variant of that name). haven't closely looking into the other logs but "gzserver" doesn't appear too often..

**Comment by AndreasAntener** [comment]
ahm, I tried vmware but got this now (catkin_make after cloning everything):
```
[ 54%] Built target mav_joy_interface
Scanning dependencies of target px4
[ 55%] Building CXX object Firmware/CMakeFiles/px4.dir/src/platforms/ros/px4_ros_impl.cpp.o
In file included from /home/ada/catkin_ws/src/Firmware/src/include/px4.h:42:0,
                 from /home/ada/catkin_ws/src/Firmware/src/platforms/ros/px4_ros_impl.cpp:40:
/home/ada/catkin_ws/src/Firmware/src/include/../platforms/px4_includes.h:51:29: fatal error: px4/rc_channels.h: No such file or directory
 #include "px4/rc_channels.h"
                             ^
compilation terminated.
make[2]: *** [Firmware/CMakeFiles/px4.dir/src/platforms/ros/px4_ros_impl.cpp.o] Error 1
make[1]: *** [Firmware/CMakeFiles/px4.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j1 -l1" failed
```

Did anything change in the meantime? Can't find any difference..

**Comment by LorenzMeier** [comment]
@AndreasAntener I updated the HW test system, now this check passes.

**Comment by AndreasAntener** [comment]
@LorenzMeier Thanks! I thought you must be testing something.. Looking forward to see the hardware test system over a webcam ;)
I'm also trying to get a Docker image working for this ROS setup. But I think I have VM-technology unrelated issues with the build.. as soon as the setup is running somehow, we can make the most portable working solution available (e.g. vagrant > vmware ubuntu > docker SITL could be awesome if you want vagrant)

**Comment by thomasgubler** [comment]
@AndreasAntener:
there seems to be a problem with the dependency on our messages, catkin invokes the build before the message headers are finished generating. Just rerun catkin_make. I am trying to find whats wrong in our cmakelists.

**Comment by thomasgubler** [comment]
@AndreasAntener fixed in the ros branch

**Comment by thomasgubler** [comment]
@AndreasAntener I rebased this and merged to the ros branch, I am going to test in the ubuntu vm next, closing

**Pull request closed without merging**
