### PR TITLE
Adaptive quadchute

### PR DESCRIPTION
**Pull request by sanderux**
Adaptive quadchute monitors the negative altitude error for VTOL during transition and fixed wing flight. In contrast to the current quadchute code this looks at the altitude error and not a static altitude threshold. This enables quadchute to be active when missions are flown on large altitude/terrain differences.

### CODE REVIEW

**Comment by dagar** [comment]
The local position setpoint is currently only updated by the multicopter position controller.

Additionally, I strongly suggest we reconsider this pattern of the vtol attitude controller monitoring everything with its own set of acceptability criteria.

Both the FW and MC controllers already know their error, and are in a much better position to tell you if it's problematic or not. Likewise for the roll and pitch limits the controllers already know what the limits are.

One idea is to have each controller publish a status message consisting of simple flags. Then the system state machine can act on this to warn the user, initiate an appropriate failsafe if possible (parachute, quadchute, emergency landing, etc).

**Comment by sanderux** [comment]
> The local position setpoint is currently only updated by the multicopter position controller.

Correct, in this implementation it is only used in MC mode (transition).

I believe the entire safety system is due for an overhaul. Could we get this in for 1.7 and rework the entire system in a next release?

**Comment by dagar** [comment]
I suppose that's fine, but the longer we put it off the worse we break existing setups.

This implementation could be okay for now, but you need to be careful checking that the relevant topics have actually updated and you're in a mode that's even capable of controlling altitude. Doing this in the right spot is actually less work and safer.

**Comment by sanderux** [comment]
I have tested the current implementation extensively in SITL using all flight modes. It performs as expected. 
If you prefer the temp solution implemented another way can you point me to where it should be done? otherwise i propose we get this in for now and do a complete rework of the failsafe system in the next release. Some form of migration or user notification should be in place for that anyway. Maybe QGC can be of help proposing old -> new params when updating.

**Comment by sanderux** [comment]
check altctl mode

**Comment by sanderux** [comment]
tested, no regression: https://logs.px4.io/plot_app?log=7f323da0-8f75-46f1-aba9-f0a68150b691

**Comment by sanderux** [comment]
@dagar can you review?

**Pull request merged**
