### PR TITLE
[WIP] Pr position derivative

### PR DESCRIPTION
**Pull request by Stifael**
based on this pr: https://github.com/PX4/Firmware/pull/7144
Mainly to test if it is beneficial to incorporate the rate of position estimate

TODO: 
Verify that land detection and controller tracking improved

### CODE REVIEW

**Comment by priseborough** [comment]
I flew the branch on a small 250 quad with badly calibrated Z accel bias to test the effect and did notice some discontinuities when commanding small height changes in alt control mode. I reworked the changes you made to blend between the two vertical velocity estimates here:

https://github.com/priseborough/Firmware/tree/position-derivative-wip

Based on a single flight It seemed to improve the smoothness, but I have run out of time today to test it further so will be interested to see what change it makes on your setup.

**Comment by Stifael** [comment]
@priseborough: 
Was it a discontinuity when entering altitude hold or when exiting it or both? 
Do you have a log by any chance?

**Comment by priseborough** [comment]
It was both ways. I will send you the log.

**Comment by Stifael** [comment]
i don't think this is necessary anymore.

**Pull request closed without merging**
