### PR TITLE
sdlog2: Use more appropriate priorities and locking strategies.

### PR DESCRIPTION
**Pull request by LorenzMeier**
@tumbili Please test with 250 Hz on your hardware (you need to apply this change manually below):

```diff
diff --git a/ROMFS/px4fmu_common/init.d/rc.logging b/ROMFS/px4fmu_common/init.d/rc.logging
index 5ba669f..12312a1 100644
--- a/ROMFS/px4fmu_common/init.d/rc.logging
+++ b/ROMFS/px4fmu_common/init.d/rc.logging
@@ -18,7 +18,7 @@ then
                        then
                        fi
                else
-                       if sdlog2 start -r 100 -a -b 12 -t
+                       if sdlog2 start -r 250 -a -b 12 -t
                        then
                        fi
                fi
```

### CODE REVIEW

**Comment by julianoes** [comment]
I think before bumping the priority we need to check all modules' priorities because sdlog2 should never make anything else delay.

**Comment by LorenzMeier** [comment]
Which is what I already did.

**Comment by julianoes** [comment]
Ok, and do I understand correctly that you bumped the priority of the sdlog2_writer task while also changing the param which sets the priority of sdlog2 task?

This means both have higher priorities but the writer itself is still lower than DEFAULT, right?

**Comment by LorenzMeier** [comment]
Yes, that's pretty much the change set

**Comment by julianoes** [comment]
Ok looks good to me then.

**Comment by LorenzMeier** [comment]
@tumbili Does this work in practice?

**Comment by tumbili** [comment]
@LorenzMeier My first test was not promising. Lost lots of data.

**Comment by LorenzMeier** [comment]
Rebased and applied. Will need more work, but certainly better than what we had.

**Pull request closed without merging**
