### PR TITLE
Fix mpu9250 hardfaults

### PR DESCRIPTION
**Pull request by dakejahl**
**Problem**
The mpu9250 driver will cause a system hard fault if the driver is attempted to be started on an already started bus. This is due to the introduction of extraneous bus options in #10116. Specifically the bus options for `MPU_DEVICE_PATH_MPU6500_*` . These options used the name exact CS, path, etc as the non **6500** option, however the `dev` pointer was still NULL, so it tried to start the bus. 

**To reproduce**
This problem behavior can easily be observed by issuing an `mpu9250 start` via the NSH after the system has booted. 

**Solution** 
I've removed the **6500** bus options. These are not necessary, as the device type will be discovered via the **WHOAMI** register (besides, the only difference between the 6500 and 9250 is the mag). I've also removed the extra bus options for the ICM20948 as they do not appear to be used. 

@flochir Could you please test this to make sure everything is still good on your end?

### CODE REVIEW

**Comment by dakejahl** [comment]
@dagar My style check is all jacked up. It forces 
`delete(bus.dev);` 
locally, but jenkins wants 
`delete (bus.dev);`

Also `make format` doesn't work, still getting 
> Error: you're using Artistic Style Version 2.05.1
but should be using Artistic Style Version 2.06, Artistic Style Version 3.0, Artistic Style Version 3.0.1, or Artistic Style Version 3.1 instead

**Comment by dakejahl** [comment]
homer

**Comment by dakejahl** [comment]
ROS tests are failing, not sure what's going on here.

**Comment by dagar** [comment]
This looks fine, but let's do a quick check on the various setups.

 - [ ] pixracer (single mpu9250)
 - [ ] TealOne (mpu9250 + mpu6500)
 - [ ] external Here GPS (icm20948)
 - [ ] crazyflie mpu9250 i2c?

**Comment by dakejahl** [comment]
I just pushed another commit that removes the `register_class_devname` for accel, gyro, and mag. These were unnecessary as `CDev::init()` is already doing this. This was resulting in extra accel, gyro, and mag instances whenever an mpu9250 driver was started. See below:
selection_005

With the removal of these calls, we now see only see 2 devices listed as expected 
selection_007

**An mpu6500** 
accel0
gyro0

**An mpu9250**
accel1
gyro1
mag1

**Comment by flochir** [comment]
No hardfault on Pixhawk Cube, and no problems with ICM20948 on Here GNSS.

**Pull request merged**
