### PR TITLE
CI: unhide .ci directory

### PR DESCRIPTION
**Pull request by bkueng**
Makes it easier to understand the CI structure and find things.

### CODE REVIEW

**Comment by dagar** [comment]
Slight complication because the additional pipelines have to be told where to find the Jenkinsfile.
http://ci.px4.io:8080/job/PX4_misc/job/Firmware-SITL_tests/

**Comment by lamping7** [comment]
I think if you want it unhidden, the natural place for it is in https://github.com/PX4/Firmware/tree/master/integrationtests You can add a "jenkins" dir here, but, I don't think it needs to be in the root.

**Comment by bkueng** [comment]
I'm ok with moving it to integrationtests. @dagar ?

**Comment by dagar** [comment]
In .ci there are separate pipelines for compiling all firmware, SITL tests, ad hardware testing.

The integrationtests folder contains scripts and missions only used by SITL tests.

**Comment by bkueng** [comment]
Can you do the required additional changes then?

**Comment by dagar** [comment]
Do you still want some version of this?

**Comment by lamping7** [comment]
If there is interest I can move it where I suggested and do the necessary changes on the Jenkins side as it all needs to happen at once. If Beat still wants it and no one objects, I'll make the switch.

**Comment by dagar** [comment]
> If there is interest I can move it where I suggested and do the necessary changes on the Jenkins side as it all needs to happen at once. If Beat still wants it and no one objects, I'll make the switch.

If we're going to move anything I'd like to get rid of the top level `integrationtests` and `test_data` (maybe move to within test). I'm also not sure where the compile, compile mac, and hardware pipelines fit.

**Comment by lamping7** [comment]
If we're getting into all this... We should remove dronekit and utils (no longer maintained). The `.test` files could get put in a `rostest` dir inside `test`. The `mavros` for could go in `test`. The jenkinsfiles could go in a `jenkins` folder inside `test`. Delete `integrationtests`. I don't know what `test_data` is used for off the top of my head.

**Comment by lamping7** [comment]
I can show a tree of this in a bit.

**Comment by lamping7** [comment]
@dagar what is this used for -- https://github.com/PX4/Firmware/blob/master/integrationtests/python_src/px4_it/util/manual_input.py

The rest of the script in `utils` look to be untouched for years.

**Comment by lamping7** [comment]
Just an idea --

Screenshot from 2019-07-10 21-15-57

**Comment by dagar** [comment]
Looks good to me! I would delete anything that isn't currently being used.
Are there any rostest conventions for test location we should care about?
I believe there's also some weirdness with the `test_data` directory handling that's crept into a few places. I think ideally it would be an optional part of ROMFS and otherwise not given special handling, but I don't know the full history.

**Comment by lamping7** [comment]
I'll look into dependencies and submit a PR

**Comment by bkueng** [comment]
> Do you still want some version of this?

Yes please

> I think ideally it would be an optional part of ROMFS and otherwise not given special handling, but I don't know the full history.

Right, that is currently not solved nicely: https://github.com/PX4/Firmware/blob/master/Tools/sitl_run.sh#L100

**Comment by lamping7** [comment]
`test_data` is here:

- .vscode/settings.json:21:                        "${workspaceFolder}/test_data"
- .vscode/launch.json:14:                "${workspaceFolder}/test_data"
- .vscode/launch.json:60:                "${workspaceFolder}/test_data"
- .vscode/launch.json:109:                "${workspaceFolder}/test_data"
- Tools/sitl_run.sh:101:	sitl_command="\"$sitl_bin\" $no_pxh \"$src_path\"/ROMFS/px4fmu_test -s \"${src_path}\"/posix-configs/SITL/init/test/${model} -t \"$src_path\"/test_data"
- Tools/sitl_run.sh:103:	sitl_command="\"$sitl_bin\" $no_pxh \"$src_path\"/ROMFS/px4fmu_common -s etc/init.d-posix/rcS -t \"$src_path\"/test_data"
- platforms/posix/src/main.cpp:243:			const std::string required_test_data_path = "./test_data";

**Pull request closed without merging**
