### PR TITLE
[DO NOT MERGE] initial SPI DMA IMU driver (mpu9250) for testing/review/discussion

### PR DESCRIPTION
**Pull request by dagar**
Project board for the larger effort: https://github.com/PX4/Firmware/projects/23

This is an initial prototype mpu9250 driver using SPI DMA on NuttX reading all raw data from the sensor. There's still quite a lot to do before this will be ready for PX4 master, but it should be mostly working on a pixracer (at least for bench testing).

The mpu9250 accel and gyro are read at 4 kHz. In an mpu6500 (or mpu9250 ignoring mag) all 32 kHz of raw gyro data is transferred.

* includes several ideas from the Drivers code cleanup (https://github.com/PX4/Firmware/issues/9279)
* includes ModuleBaseMulti (https://github.com/PX4/Firmware/issues/9143)
* introduces base classes for Accel/Gyro/Mag (calibration, filtering, integration, publishing)

### TODO

* work queue with thread per bus needed https://github.com/PX4/Firmware/issues/8814
  * this is temporarily using a task per mpu9250 instance
* review ModuleBaseMulti and merge separately
* review mpu9250 i2c only mode (crazyflie or external mpu9250)
* review SPI DMA on all desired NuttX boards and mpu9250 fallback mode
* posix and qurt compatibility
* clip counters
* split sensor messages for control (1 kHz gyro publication)
* From Jake: I've got calibration working. I've got more work on my private repo I'll push up Monday. Tackling one last bug before it can fly. I think the problem is a non-atomic `read fifo_count` follow by `read fifo`. If something preempts between those operations I can get an overflow without knowing it. I'll confirm or deny this Monday.
* NuttX side - https://github.com/PX4/NuttX/pull/25

### CODE REVIEW

**Comment by bkueng** [comment]
Awesome! Great to see progress on this.

I see that the filter is applied to the downsampled 1kHz signal. I think it should be done on the raw signal though (at least for the control path).

@dakejahl do you have a log (with high-rate logging)?

**Comment by bkueng** [comment]
> Even with high rate logging the logger only can run at ~250hz. Anything we can do to increase this?

You can reduce the log interval here: https://github.com/PX4/Firmware/blob/master/src/modules/logger/logger.cpp#L283.
Or you can let it directly poll on the topic when starting it manually: `logger start -t -b 14 -p sensor_gyro`. In terms of CPU load I'm not sure how high you can go with the logging rate, we'll probably have to optimize for that.

**Comment by dakejahl** [comment]
selection_009
21% cpu for the 6500 (32khz gyro data) -- (without prefilter it runs at 11%)
11% cpu for the 9250 (only 4khz gyro) -- (without prefilter it runs 9%)

This is running a filter over the raw data before down sampling to 1khz. Floating point math :(
```
			accel_x += _accel_prefilter_x.apply(int_accel_x[i]);
			accel_y += _accel_prefilter_y.apply(int_accel_y[i]);
			accel_z += _accel_prefilter_z.apply(int_accel_z[i]);

			gyro_x += _gyro_prefilter_x.apply(int_gyro_x[i]);
			gyro_y += _gyro_prefilter_y.apply(int_gyro_y[i]);
			gyro_z += _gyro_prefilter_z.apply(int_gyro_z[i]);
```

**Comment by mhkabir** [comment]
Are you adding filtering to the estimator path?

**Comment by dagar** [comment]
This is the design we're working towards while at the same time trying to push all common accel/gyro/mag logic in reusable classes. Ideally this would allow us to move over all the existing IMU drivers, then split sensor_gyro without having to touch every single driver.

The prefiltering should be dropped and we need to look at structuring this such that the integration (estimator path) and filtering (control path) are performed on the raw data (separately).

image

**Comment by dakejahl** [comment]
How do we push the raw data to the rest of the system when we are collecting multiple measurements per cycle inside of the driver?

**Comment by dagar** [comment]
Updated to latest https://github.com/PX4/NuttX/pull/25 and Firmware master.

**Comment by dagar** [comment]
TODO: review NuttX CONFIG_SPI_TRIGGER and HWFEAT_TRIGGER
https://groups.google.com/forum/#!topic/nuttx/I30Wqws7VSc
https://github.com/PX4/NuttX/commit/8328539534785bf2f26dffe9ed66554b30b60998

**Comment by dagar** [comment]
NuttX changes to configure DMA per SPI for both stm32 and stm32f7 have been upstreamed.

**Pull request closed without merging**
