### PR TITLE
extend multicopter landing detector to consider airspeed for vtol

### PR DESCRIPTION
**Pull request by tumbili**

### CODE REVIEW

**Comment by Zefz** [comment]
@tumbili There are currntly 2 separate land detectors: fixedwing and multicopter. Would it not make sense to add a separate vtol land detector as well?

**Comment by tumbili** [comment]
@Zefz I also thought about that in the beginning. But then the landing detector for vtol and multirotor are almost the same and I didn't want any code duplication. What are your arguments against it?

**Comment by LorenzMeier** [comment]
Classic case where the VTOL should inherit from the multicopter and the multicopter should use a function to determine the throttle / airspeed state. Then the VTOL detector could re-implement that function and override it with something custom.

**Comment by tumbili** [comment]
Ok, that sounds fair enough.

**Comment by tumbili** [comment]
@LorenzMeier @Zefz Please review.

**Comment by Zefz** [comment]
@tumbili I see 2 problems with your code.

First of all the superclass functions you are trying to override need to be marked as *virtual*.

Secondly it is good code convention to mark the functions of the subclass as *override*:

```
struct A
{
    virtual void foo();
    void bar();
};
 
struct B : A
{
    void foo() const override; // Error: B::foo does not override A::foo
                               // (signature mismatch)
    void foo() override; // OK: B::foo overrides A::foo
    void bar() override; // Error: A::bar is not virtual
};
```

**Comment by tumbili** [comment]
@Zefz Yep, thanks for the review.

**Comment by tumbili** [comment]
@bansiesta Yes, this is what will happen. Do you see any problems with that?

**Comment by bansiesta** [comment]
@tumbili: ok that seems right.

And why are you using FW landing speed max? Why not min?

**Comment by tumbili** [comment]
@bansiesta This is the definition of the parameter
/**
 * Airspeed max
 *
 * Maximum airspeed allowed in the landed state (m/s)

**Comment by bansiesta** [comment]
Oh that makes perfect sense then!

**Comment by tumbili** [comment]
@Zefz @bansiesta Fixed the problems you have mentioned. Needs to be flight tested now, probably sometime this week.

**Comment by AndreasAntener** [comment]
Flight tested on the FunCub:
http://dash.oznet.ch/view/bgJVKEGhAtkcwqsRd46KE7
http://dash.oznet.ch/view/TJhRTcPsrKPJmUL6EyeSCR

No false landed detections in-air.

**Comment by LorenzMeier** [comment]
The throttle jitter here looks odd:
http://dash.oznet.ch/view/bgJVKEGhAtkcwqsRd46KE7#Thrust_PLOT

But I'm not sure if that is just a general thing or related to this PR.

**Comment by AndreasAntener** [comment]
Yes, on the back transition in alt/control we noticed a throttle pulsing over the transition time where there is a blending happening. Not sure what to make of it yet.

**Comment by AndreasAntener** [comment]
Discussing with Roman now, looks like the attitude setpoint alternates between 2 states.

**Comment by SimonWilks** [comment]
Flight tests look good for VTOL.

@tumbili any chance you can test it on MC and FW during the week? I'll leave this to you to test and merge if that's OK as it's only partially VTOL ;)

**Comment by tumbili** [comment]
@SimonWilks Going for a test now, will put this in too :-)

**Comment by tumbili** [comment]
@SimonWilks Flight tested with a fixed wing, no issues.
Log: http://dash.oznet.ch/view/cAhkuwfwbbbkBWwKN9N9GD

Now it still needs a fligh test with a multicopter.

**Comment by SimonWilks** [comment]
@tumbili have you flown this on multirotor by any chance? If not I'll see if we can do so today.

**Comment by tumbili** [comment]
@SimonWilks No sorry, haven't had a chance yet.

**Comment by SimonWilks** [comment]
@tumbili I just completed a multirotor flight test with this PR and it worked as expected.

**Comment by tumbili** [comment]
@SimonWilks Thanks!

**Comment by LorenzMeier** [comment]
@tumbili What's going on with this one?

**Pull request merged**
