### PR TITLE
Trivial code style cleanup

### PR DESCRIPTION
**Pull request by dagar**
This PR corrects formatting in unittests, nuttx-configs, and any file that only had a single formatting problem.

### CODE REVIEW

**Comment by dagar** [comment]
Remaining improperly formatted files sorted by the number of lines that would be changed by ./Tools/fix_code_style.sh

Format checks failed; please run ./Tools/fix_code_style.sh on each file
2 ./src/drivers/ardrone_interface/ardrone_motor_control.h
2 ./src/drivers/boards/aerocore/aerocore_spi.c
2 ./src/drivers/boards/px4fmu-v1/px4fmu_spi.c
2 ./src/drivers/boards/px4io-v2/board_config.h
2 ./src/drivers/drv_hrt.h
2 ./src/drivers/drv_rgbled.h
2 ./src/drivers/frsky_telemetry/frsky_data.c
2 ./src/drivers/md25/BlockSysIdent.hpp
2 ./src/lib/mathlib/math/Limits.hpp
2 ./src/lib/rc/st24.c
2 ./src/modules/commander/calibration_routines.cpp
2 ./src/modules/controllib/block/BlockParam.hpp
2 ./src/modules/fw_att_control/fw_att_control_params.c
2 ./src/modules/gpio_led/gpio_led.c
2 ./src/modules/land_detector/LandDetector.cpp
2 ./src/modules/land_detector/MulticopterLandDetector.h
2 ./src/modules/mavlink/mavlink_receiver.h
2 ./src/modules/navigator/mission_feasibility_checker.h
2 ./src/modules/navigator/navigator_mode.cpp
2 ./src/modules/navigator/navigator_mode.h
2 ./src/modules/px4iofirmware/px4io.h
2 ./src/modules/systemlib/cpuload.c
2 ./src/modules/systemlib/hx_stream.h
2 ./src/modules/systemlib/mcu_version.h
2 ./src/modules/systemlib/pwm_limit/pwm_limit.h
2 ./src/modules/uORB/topics/geofence_result.h
2 ./src/modules/uORB/topics/home_position.h
2 ./src/modules/uORB/topics/mission_result.h
2 ./src/systemcmds/perf/perf.c
2 ./src/systemcmds/reboot/reboot.c
2 ./src/systemcmds/tests/test_hott_telemetry.c
2 ./src/systemcmds/tests/test_uart_baudchange.c
3 ./src/drivers/airspeed/airspeed.h
3 ./src/drivers/device/i2c.h
3 ./src/examples/subscriber/subscriber_example.h
3 ./src/lib/mathlib/math/Limits.cpp
3 ./src/lib/mathlib/math/test/test.cpp
3 ./src/modules/attitude_estimator_so3/attitude_estimator_so3_params.c
3 ./src/modules/controllib/blocks.hpp
3 ./src/modules/fw_pos_control_l1/mtecs/mTecs.h
3 ./src/modules/mavlink/mavlink_stream.h
3 ./src/modules/mc_att_control_multiplatform/mc_att_control.h
3 ./src/modules/navigator/mission_block.h
3 ./src/modules/px4iofirmware/safety.c
3 ./src/modules/systemlib/mixer/mixer_group.cpp
3 ./src/modules/systemlib/systemlib.c
3 ./src/modules/uavcan/sensors/baro.hpp
3 ./src/modules/uavcan/sensors/gnss.hpp
3 ./src/modules/uavcan/sensors/mag.hpp
3 ./src/modules/uavcan/uavcan_main.hpp
3 ./src/modules/unit_test/unit_test.cpp
3 ./src/modules/uORB/topics/tecs_status.h
3 ./src/modules/uORB/uORB.h
3 ./src/platforms/px4_message.h
3 ./src/platforms/ros/nodes/commander/commander.h
3 ./src/platforms/ros/nodes/position_estimator/position_estimator.cpp
3 ./src/systemcmds/tests/test_adc.c
3 ./src/systemcmds/tests/test_ppm_loopback.c
4 ./src/drivers/boards/px4fmu-v2/px4fmu_spi.c
4 ./src/drivers/device/spi.h
4 ./src/drivers/hott/comms.cpp
4 ./src/drivers/led/led.cpp
4 ./src/drivers/oreoled/oreoled.cpp
4 ./src/lib/ecl/attitude_fw/ecl_yaw_controller.h
4 ./src/modules/attitude_estimator_ekf/codegen/AttitudeEKF.h
4 ./src/modules/controllib/blocks.cpp
4 ./src/modules/mavlink/mavlink_orb_subscription.cpp
4 ./src/modules/mavlink/mavlink_orb_subscription.h
4 ./src/modules/mc_pos_control_multiplatform/mc_pos_control.h
4 ./src/modules/systemlib/param/param.h
4 ./src/modules/systemlib/state_table.h
4 ./src/modules/uORB/topics/vehicle_command.h
4 ./src/platforms/ros/nodes/manual_input/manual_input.cpp
5 ./src/examples/publisher/publisher_example.h
5 ./src/examples/publisher/publisher_start_nuttx.cpp
5 ./src/examples/subscriber/subscriber_start_nuttx.cpp
5 ./src/lib/mathlib/math/Quaternion.hpp
5 ./src/modules/mavlink/mavlink_messages.h
5 ./src/modules/mc_att_control_multiplatform/mc_att_control_start_nuttx.cpp
5 ./src/modules/mc_pos_control_multiplatform/mc_pos_control_start_nuttx.cpp
5 ./src/modules/segway/BlockSegwayController.hpp
5 ./src/modules/systemlib/systemlib.h
5 ./src/modules/uavcan/actuators/esc.hpp
5 ./src/modules/uORB/Publication.hpp
5 ./src/modules/uORB/topics/multirotor_motor_limits.h
5 ./src/modules/uORB/topics/system_power.h
5 ./src/platforms/ros/nodes/demo_offboard_attitude_setpoints/demo_offboard_attitude_setpoints.cpp
5 ./src/platforms/ros/nodes/mc_mixer/mc_mixer.cpp
5 ./src/systemcmds/tests/test_conv.cpp
6 ./src/drivers/boards/px4io-v1/board_config.h
6 ./src/drivers/gps/mtk.cpp
6 ./src/lib/ecl/attitude_fw/ecl_pitch_controller.h
6 ./src/modules/commander/state_machine_helper.h
6 ./src/modules/fw_pos_control_l1/mtecs/limitoverride.cpp
6 ./src/modules/px4iofirmware/adc.c
6 ./src/modules/systemlib/bson/tinybson.h
6 ./src/systemcmds/tests/test_time.c
6 ./src/systemcmds/ver/ver.c
7 ./src/drivers/batt_smbus/batt_smbus.cpp
7 ./src/drivers/mb12xx/mb12xx.cpp
7 ./src/lib/ecl/l1/ecl_l1_pos_controller.h
7 ./src/modules/land_detector/FixedwingLandDetector.cpp
7 ./src/modules/mavlink/mavlink_main.h
7 ./src/modules/segway/BlockSegwayController.cpp
7 ./src/modules/uORB/Publication.cpp
7 ./src/modules/uORB/Subscription.cpp
7 ./src/modules/uORB/Subscription.hpp
8 ./src/drivers/roboclaw/RoboClaw.hpp
8 ./src/modules/commander/airspeed_calibration.cpp
8 ./src/modules/mavlink/mavlink_parameters.cpp
8 ./src/modules/systemlib/err.c
8 ./src/modules/uavcan/sensors/sensor_bridge.cpp
8 ./src/modules/uORB/topics/vehicle_global_position.h
8 ./src/platforms/px4_publisher.h
8 ./src/systemcmds/mtd/24xxxx_mtd.c
8 ./src/systemcmds/tests/test_servo.c
9 ./src/drivers/boards/aerocore/aerocore_init.c
9 ./src/drivers/boards/px4fmu-v2/px4fmu2_init.c
9 ./src/drivers/hmc5883/hmc5883_i2c.cpp
9 ./src/drivers/hott/hott_sensors/hott_sensors.cpp
9 ./src/drivers/pca8574/pca8574.cpp
9 ./src/drivers/sf0x/sf0x.cpp
9 ./src/include/mavlink/mavlink_log.h
9 ./src/modules/commander/commander_params.c
9 ./src/modules/commander/gyro_calibration.cpp
9 ./src/modules/controllib/block/BlockParam.cpp
9 ./src/modules/fixedwing_backside/fixedwing_backside_main.cpp
9 ./src/modules/land_detector/MulticopterLandDetector.cpp
9 ./src/modules/mavlink/mavlink_parameters.h
9 ./src/modules/segway/segway_main.cpp
10 ./src/drivers/boards/aerocore/aerocore_led.c
10 ./src/drivers/boards/px4fmu-v2/px4fmu2_led.c
10 ./src/drivers/device/device.cpp
10 ./src/drivers/md25/md25_main.cpp
10 ./src/examples/px4_simple_app/px4_simple_app.c
10 ./src/modules/px4iofirmware/protocol.h
10 ./src/modules/systemlib/airspeed.c
10 ./src/modules/systemlib/mixer/mixer.h
10 ./src/modules/vtol_att_control/vtol_att_control_params.c
10 ./src/platforms/ros/geo.cpp
10 ./src/systemcmds/tests/test_hrt.c
11 ./src/drivers/device/device.h
11 ./src/examples/rover_steering_control/main.cpp
11 ./src/lib/launchdetection/LaunchDetector.cpp
11 ./src/systemcmds/i2c/i2c.c
12 ./src/drivers/hmc5883/hmc5883_spi.cpp
12 ./src/examples/subscriber/subscriber_example.cpp
12 ./src/modules/fw_pos_control_l1/mtecs/mTecs_blocks.h
12 ./src/modules/uavcan/sensors/sensor_bridge.hpp
12 ./src/modules/unit_test/unit_test.h
12 ./src/platforms/px4_parameter.h
12 ./src/systemcmds/tests/test_sensors.c
13 ./src/drivers/hott/hott_telemetry/hott_telemetry.cpp
13 ./src/lib/launchdetection/CatapultLaunchMethod.cpp
13 ./src/modules/controllib/block/Block.hpp
13 ./src/modules/mavlink/mavlink_mission.h
13 ./src/modules/navigator/navigator.h
13 ./src/modules/systemlib/mixer/mixer_load.c
13 ./src/modules/uORB/topics/mission.h
14 ./src/drivers/md25/md25.cpp
14 ./src/modules/mavlink/mavlink_mission.cpp
14 ./src/modules/mc_att_control/mc_att_control_main.cpp
14 ./src/platforms/px4_subscriber.h
14 ./src/systemcmds/tests/test_float.c
14 ./src/systemcmds/tests/test_uart_loopback.c
15 ./src/drivers/ms5611/ms5611_i2c.cpp
15 ./src/lib/geo_lookup/geo_mag_declination.c
15 ./src/modules/commander/mag_calibration.cpp
15 ./src/systemcmds/mixer/mixer.cpp
16 ./src/drivers/boards/px4fmu-v1/px4fmu_init.c
16 ./src/drivers/px4io/px4io_i2c.cpp
16 ./src/drivers/roboclaw/roboclaw_main.cpp
16 ./src/examples/px4_daemon_app/px4_daemon_app.c
16 ./src/systemcmds/motor_test/motor_test.c
17 ./src/modules/fw_pos_control_l1/mtecs/limitoverride.h
17 ./src/modules/systemlib/mixer/mixer.cpp
17 ./src/modules/systemlib/ppm_decode.c
17 ./src/modules/uavcan/sensors/gnss.cpp
18 ./src/drivers/device/i2c.cpp
18 ./src/modules/systemlib/rc_check.c
18 ./src/modules/systemlib/up_cxxinitialize.c
19 ./src/drivers/hott/messages.cpp
19 ./src/lib/external_lgpl/tecs/tecs.cpp
19 ./src/modules/navigator/mission_block.cpp
19 ./src/modules/systemlib/getopt_long.h
19 ./src/modules/systemlib/hx_stream.c
19 ./src/modules/systemlib/mixer/mixer_multirotor.cpp
19 ./src/systemcmds/tests/test_mount.c
20 ./src/drivers/boards/px4fmu-v1/px4fmu_led.c
20 ./src/drivers/trone/trone.cpp
20 ./src/modules/fw_pos_control_l1/landingslope.h
20 ./src/systemcmds/bl_update/bl_update.c
21 ./src/drivers/frsky_telemetry/frsky_telemetry.c
21 ./src/drivers/meas_airspeed/meas_airspeed.cpp
21 ./src/modules/uavcan/actuators/esc.cpp
21 ./src/platforms/ros/nodes/commander/commander.cpp
21 ./src/systemcmds/preflight_check/preflight_check.c
22 ./src/drivers/device/spi.cpp
22 ./src/drivers/rgbled/rgbled.cpp
22 ./src/modules/uavcan/sensors/baro.cpp
24 ./src/lib/geo/geo.h
24 ./src/modules/mavlink/mavlink_tests/mavlink_ftp_test.h
24 ./src/systemcmds/tests/tests_main.c
25 ./src/drivers/gps/ashtech.cpp
26 ./src/drivers/stm32/drv_pwm_servo.c
26 ./src/examples/fixedwing_control/main.c
26 ./src/modules/mc_att_control_multiplatform/mc_att_control.cpp
26 ./src/modules/systemlib/otp.c
27 ./src/drivers/ms5611/ms5611_spi.cpp
27 ./src/drivers/px4flow/i2c_frame.h
27 ./src/modules/navigator/enginefailure.cpp
27 ./src/modules/px4iofirmware/px4io.c
28 ./src/drivers/stm32/drv_hrt.c
28 ./src/modules/systemlib/mixer/mixer_simple.cpp
29 ./src/drivers/device/cdev.cpp
29 ./src/modules/navigator/mission_feasibility_checker.cpp
30 ./src/lib/ecl/l1/ecl_l1_pos_controller.cpp
30 ./src/modules/px4iofirmware/serial.c
30 ./src/modules/systemlib/mcu_version.c
31 ./src/modules/navigator/gpsfailure.cpp
31 ./src/systemcmds/tests/test_dataman.c
32 ./src/drivers/ardrone_interface/ardrone_interface.c
32 ./src/drivers/ardrone_interface/ardrone_motor_control.c
32 ./src/modules/fixedwing_backside/fixedwing.cpp
32 ./src/modules/mavlink/mavlink_ftp.h
32 ./src/modules/px4iofirmware/i2c.c
33 ./src/modules/fw_pos_control_l1/landingslope.cpp
33 ./src/platforms/px4_nodehandle.h
33 ./src/systemcmds/tests/test_file.c
34 ./src/modules/px4iofirmware/dsm.c
35 ./src/drivers/stm32/adc/adc.cpp
35 ./src/modules/fw_pos_control_l1/mtecs/mTecs.cpp
35 ./src/modules/navigator/rcloss.cpp
35 ./src/modules/uavcan/sensors/mag.cpp
36 ./src/examples/matlab_csv_serial/matlab_csv_serial.c
36 ./src/modules/vtol_att_control/vtol_att_control_main.cpp
37 ./src/drivers/airspeed/airspeed.cpp
38 ./src/drivers/mkblctrl/mkblctrl.cpp
38 ./src/drivers/px4flow/px4flow.cpp
38 ./src/lib/mathlib/math/Matrix.hpp
38 ./src/modules/uavcan/uavcan_main.cpp
39 ./src/modules/commander/accelerometer_calibration.cpp
41 ./src/lib/mathlib/math/filter/LowPassFilter2p.cpp
42 ./src/modules/mavlink/mavlink_main.cpp
42 ./src/modules/position_estimator_inav/position_estimator_inav_main.c
43 ./src/modules/mc_pos_control/mc_pos_control_main.cpp
44 ./src/drivers/device/ringbuffer.h
45 ./src/modules/sdlog2/sdlog2.c
46 ./src/drivers/gps/gps.cpp
47 ./src/lib/mathlib/math/filter/LowPassFilter2p.hpp
47 ./src/modules/sensors/sensors.cpp
48 ./src/lib/geo/geo.c
48 ./src/systemcmds/tests/test_file2.c
49 ./src/drivers/pca9685/pca9685.cpp
49 ./src/platforms/ros/nodes/mavlink/mavlink.cpp
50 ./src/drivers/ets_airspeed/ets_airspeed.cpp
51 ./src/systemcmds/top/top.c
52 ./src/drivers/hott/messages.h
53 ./src/modules/ekf_att_pos_estimator/estimator_utilities.h
54 ./src/drivers/px4io/px4io_uploader.cpp
54 ./src/systemcmds/config/config.c
54 ./src/systemcmds/tests/test_mixer.cpp
55 ./src/modules/px4iofirmware/controls.c
55 ./src/modules/systemlib/param/param.c
56 ./src/systemcmds/esc_calib/esc_calib.c
57 ./src/drivers/px4io/px4io_serial.cpp
57 ./src/systemcmds/tests/test_bson.c
59 ./src/lib/external_lgpl/tecs/tecs.h
60 ./src/lib/mathlib/math/Vector.hpp
60 ./src/modules/navigator/datalinkloss.cpp
60 ./src/systemcmds/reflect/reflect.c
62 ./src/modules/attitude_estimator_ekf/codegen/rtwtypes.h
64 ./src/drivers/pwm_input/pwm_input.cpp
64 ./src/modules/px4iofirmware/mixer.cpp
70 ./src/drivers/ll40ls/ll40ls.cpp
70 ./src/modules/fw_att_control/fw_att_control_main.cpp
75 ./src/drivers/bma180/bma180.cpp
79 ./src/modules/commander/commander.cpp
80 ./src/modules/systemlib/airspeed.h
82 ./src/modules/dataman/dataman.h
82 ./src/modules/ekf_att_pos_estimator/estimator_utilities.cpp
83 ./src/drivers/roboclaw/RoboClaw.cpp
83 ./src/modules/mc_pos_control_multiplatform/mc_pos_control.cpp
85 ./src/systemcmds/nshterm/nshterm.c
87 ./src/modules/systemlib/uthash/utstring.h
90 ./src/drivers/hil/hil.cpp
91 ./src/modules/systemlib/bson/tinybson.c
95 ./src/modules/commander/state_machine_helper.cpp
96 ./src/systemcmds/mtd/mtd.c
98 ./src/systemcmds/boardinfo/boardinfo.c
102 ./src/modules/bottle_drop/bottle_drop.cpp
105 ./src/modules/navigator/mission.cpp
111 ./src/drivers/ms5611/ms5611.cpp
111 ./src/modules/navigator/navigator_main.cpp
113 ./src/examples/flow_position_estimator/flow_position_estimator_main.c
117 ./src/modules/mavlink/mavlink_receiver.cpp
121 ./src/modules/uORB/uORB.cpp
123 ./src/modules/dataman/dataman.c
128 ./src/modules/mavlink/mavlink_ftp.cpp
132 ./src/modules/navigator/rtl.cpp
136 ./src/drivers/px4fmu/fmu.cpp
136 ./src/modules/systemlib/uthash/utarray.h
140 ./src/drivers/stm32/tone_alarm/tone_alarm.cpp
141 ./src/modules/systemlib/perf_counter.c
150 ./src/modules/systemlib/pwm_limit/pwm_limit.c
161 ./src/drivers/gps/ubx.cpp
168 ./src/lib/conversion/rotation.cpp
173 ./src/modules/mavlink/mavlink_tests/mavlink_ftp_test.cpp
175 ./src/drivers/blinkm/blinkm.cpp
199 ./src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp
209 ./src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp
221 ./src/drivers/l3gd20/l3gd20.cpp
229 ./src/drivers/hmc5883/hmc5883.cpp
238 ./src/modules/px4iofirmware/registers.c
257 ./src/systemcmds/pwm/pwm.c
258 ./src/modules/ekf_att_pos_estimator/AttitudePositionEstimatorEKF.h
290 ./src/modules/systemlib/getopt_long.c
315 ./src/drivers/lsm303d/lsm303d.cpp
327 ./src/drivers/mpu6000/mpu6000.cpp
347 ./src/modules/systemlib/uthash/utlist.h
362 ./src/modules/ekf_att_pos_estimator/estimator_22states.h
395 ./src/modules/commander/commander_tests/state_machine_helper_test.cpp
417 ./src/drivers/px4io/px4io.cpp
463 ./src/modules/mavlink/mavlink_messages.cpp
565 ./src/modules/attitude_estimator_ekf/attitude_estimator_ekf_main.cpp
628 ./src/modules/systemlib/uthash/uthash.h
693 ./src/modules/attitude_estimator_so3/attitude_estimator_so3_main.cpp
1495 ./src/modules/attitude_estimator_ekf/codegen/AttitudeEKF.c
4383 ./src/modules/ekf_att_pos_estimator/estimator_22states.cpp

**Comment by dagar** [comment]
I will **very** slowly work through this list.

**Comment by dagar** [comment]
Applied fix_code_style.sh to all examples. My assumption is that everything formatted in this PR will not be a problem to merge downstream.

**Comment by LorenzMeier** [comment]
This makes sense. How far off is the LLVM formatter - is there a common minimal base set?

**Comment by dagar** [comment]
I attempted to use clang-format in PX4/Bootloader, but I don't think it's possible to get it to match astyle exactly. Clang-format still created huge diffs.
It's easy to get the basics matching (braces, pointer position, etc), but there's indentation that differs between astyle and clang-format that falls outside of the configurations.

**Comment by LorenzMeier** [comment]
This is so appreciated! Applied after rebase!

**Pull request closed without merging**
