### PR TITLE
sensors/vehicle_air_data: don't publish if there aren't any healthy sensors remaining

### PR DESCRIPTION
**Pull request by dagar**
Possible fix for https://github.com/PX4/Firmware/issues/15223.

### CODE REVIEW

**Comment by dagar** [comment]
This has been pulled into https://github.com/PX4/Firmware/pull/15235 where the same issue was fixed for magnetometers (and verified).

**Comment by julianoes** [comment]
@dagar this does not actually work. The only output I see is:
```
[px4         ] ERROR [vehicle_air_data] sensor_baro:#0 failed:  STALE!, reconfiguring priorities
```
but nothing regarding switching to GPS.

**Comment by dagar** [comment]
Yes, I debugged and fixed it as part of https://github.com/PX4/Firmware/pull/15235. 

What I discoverd is that the validator group state (overall error) doesn't clear until all the sensors are back to healthy. So instead what I did was only publish the current primary if it's healthy. Thanks for testing it.

https://github.com/PX4/Firmware/blob/42a4f844424ba8269a82ded6680eb92a63b13af1/src/modules/sensors/vehicle_air_data/VehicleAirData.cpp#L192-L194

**Comment by julianoes** [comment]
@dagar when I tested #15235 it didn't work either. I'll try again.

**Comment by julianoes** [comment]
@dagar ok I tried again and I can see that it does fall back but there are two issues with it:
1. It takes about 25 seconds until it switches even though it could do much quicker, right?
2. Once you land and do another flight it climbs indefinitely.

**Comment by julianoes** [comment]
@dagar ok you're right, it works correctly but only if the temperature is also "stuck". I had to fix that with https://github.com/PX4/Firmware/pull/15063/commits/358799b114ea7b67098b7f972f824b57c6559699.

**Pull request closed without merging**
