### PR TITLE
PWM init

### PR DESCRIPTION
**Pull request by LorenzMeier**
This patch changes the way the system boots and forces all GPIO pins to low on boot. This might interfere with triggers / GPIO payloads, but since the level shifter is auto-direction sending not doing this means the pins are in a random state on the output. This way we force a known state.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This fixes the state to something where the pins go down on entering the autopilot code and only start to change once PWM out is enabled.

screen shot 2016-02-17 at 14 35 22

**Comment by LorenzMeier** [comment]
@birchera Please test your PR also against this branch, which changes how the PWM pins are initialised. It might lead to regression.

**Comment by AndreasAntener** [comment]
No regression:
VTOL: http://logs.uaventure.com/view/PcLuicb4v836iZpVz5CnJN
MC: http://logs.uaventure.com/view/wqG48Vi97iHGiKfNeWWymN

**Comment by LorenzMeier** [comment]
Rebased and applied. Thanks for testing!

**Pull request closed without merging**
