### PR TITLE
Uploader fixes

### PR DESCRIPTION
**Pull request by zehortigoza**

### CODE REVIEW

**Comment by julianoes** [comment]
Is this for serial over USB? Because I thought the baudrate would not matter there.

**Comment by LorenzMeier** [comment]
No, for serial - @zehortigoza A quick description in a PR would be appreciated.

**Comment by LorenzMeier** [comment]
Jenkins test this please

**Comment by LorenzMeier** [comment]
Rebased and continued here: Rebased and continued here: https://github.com/PX4/Firmware/pull/5607

**Comment by lucasdemarchi** [comment]
@julianoes the reason is in the commit message:

```
Uploader tool: Reboot board and keep it in bootloader

The Mavlink reboot messages was only requesting the board to reboot.
If the flashed bootloader has a small or no timeout user will
never be able to update firmware.
```

**Pull request closed without merging**
