### PR TITLE
cleanup - removed duplicate const MAX_ACTUATORS definition

### PR DESCRIPTION
**Pull request by BazookaJoe1900**
There are two dupliacate const definitions, one global and one in the class, which is singletone anyway.
The definition is duplicated to _max_actuators

### CODE REVIEW

**Comment by dagar** [comment]
Keep the upper case naming for a constant? MAX_ACTUATORS

**Comment by dagar** [comment]
Hmm, upper case with underscore doesn't look quite right, but let's go with it for now.
This is probably a good example of why we need a coding standard for naming constants, member variables, etc.

Thanks @BazookaJoe1900

**Comment by dagar** [comment]
Google c++ style guide? https://google.github.io/styleguide/cppguide.html#Constant_Names

**Comment by BazookaJoe1900** [comment]
Sorry about the bad coding standard.. I was rushing doing the pr.
I will fix that.... but in two days. Wait with the marging

**Comment by dagar** [comment]
No need to apologize, the problem is there's no (written) coding standard

**Comment by dagar** [comment]
It's still nice to get rid of the duplication and easy to change later. Thanks again.

**Pull request merged**
