### PR TITLE
Update submodule nuttx to latest Sun Sep 23 08:37:24 EDT 2018

### PR DESCRIPTION
**Pull request by dagar**
- nuttx in PX4/Firmware (f3cbd3c744e9224bd55597fbfae23c56ce296544): https://github.com/PX4-NuttX/nuttx/commit/98a89513060c42215e9cd14f52a7fd7dcc08dacc
    - nuttx current upstream: https://github.com/PX4-NuttX/nuttx/commit/e31e94f5bd3cf68b9ed0f010724ac9122730dd21
    - Changes: https://github.com/PX4-NuttX/nuttx/compare/98a89513060c42215e9cd14f52a7fd7dcc08dacc...e31e94f5bd3cf68b9ed0f010724ac9122730dd21

    e31e94f 2018-09-21 David Sidrane - [REJECTED] kinetis:usbdev use CONFIG_KINETIS_USBOTG_PRIO at default

### CODE REVIEW

**Comment by dagar** [comment]
I believe this was unintentionally changed. 
@davids5 @mcsauder

**Comment by mcsauder** [comment]
Thanks @dagar! It was unintended, but I thought I fixed that error immediately following in https://github.com/PX4/Firmware/pull/10543.  I apologize if I didin't get that corrected.

**Comment by mcsauder** [comment]
Weird, it's like the merge of PR #10543 evaporated into the Aether, its not in the commit history of the master branch.  Thank you for fixing that up @dagar!

**Comment by davids5** [comment]
Scarry! I would have hate to see that Kinetis bug creep back in. I would think it was a forced push to the branch without a rebase from current master. 

Thank you both for fixing it!

**Pull request merged**
