### PR TITLE
Resource leak fixes & race condition in 'mavlink stop-all'

### PR DESCRIPTION
**Pull request by bkueng**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Jenkins test this

**Comment by AndreasAntener** [comment]
Jenkins test this please

**Comment by AndreasAntener** [comment]
Something definitely changed here, it's not getting of the ground properly in the SITL tests

**Comment by bkueng** [comment]
The error output is not helpful. How can I reproduce?
Also there is the following error right at the start:
```
libdc1394 error: Failed to initialize libdc1394
```
Is it relevant?

Testing `commander takeoff` after gps is ok in SITL, I get:
```
WARN  TRANSITION_DENIED: ARMING_STATE_INIT - ARMING_STATE_ARMED
```
But master has the same problem (f9df60919e4722edade53b066d25248af9d73fd6). Should I rebase?

**Comment by LorenzMeier** [comment]
Master works. I have this version of Gazebo:

```
gazebo --version
Gazebo multi-robot simulator, version 6.5.1
Copyright (C) 2012-2015 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org
```

**Comment by LorenzMeier** [comment]
@bkueng Please rebase and re-test.

**Comment by bkueng** [comment]
rebased and tested, jmavsim works. Turned out it was a messed up `rootfs/eeprom/parameters` file in my build folder. Let's wait for CI

**Comment by LorenzMeier** [comment]
@bkueng Is this guaranteed to initialise all subs to -1 or just the first one?
https://github.com/PX4/Firmware/blob/1be3c0fe48c08bdc677de3e04a2db217fc14c2cd/src/drivers/pwm_out_sim/pwm_out_sim.cpp#L185

**Comment by AndreasAntener** [comment]
`libdc1394` is irrelevant

Do you have ROS installed and could run the tests? http://dev.px4.io/tutorial-integration-testing.html

Also I set Jenkins to keep the px4logs for the jobs, you can now download them for the last build.

**Comment by bkueng** [comment]
No just the first one. I'll fix it

**Comment by julianoes** [comment]
Great, this fixes a hardfault on `mavlink stop-all` on an old Pixracer that I'm using for Passthrough with Snapdragon.

**Comment by bkueng** [comment]
@AndreasAntener Thanks that would be helpful

**Comment by AndreasAntener** [comment]
@bkueng they're here: http://sitl01.dronetest.io/job/PX4%20Firmware%20POSIX%20SITL%20PRs/857/

**Comment by bkueng** [comment]
Let's see if it works now

**Comment by AndreasAntener** [comment]
Looks good on my machine now, Jenkins should be happy :)

**Pull request merged**
