### PR TITLE
[WIP] delete gencpp and genmsg submodules

### PR DESCRIPTION
**Pull request by dagar**
These are readily available as packages. Submodules are a constant pain point. Let's not use them anymore than needed.

TODO:
 - update docker and test
 - update homebrew and test
 - update documentation

### CODE REVIEW

**Comment by dagar** [comment]
Adding gencpp and genmsg to docker here. https://github.com/PX4/containers/pull/103

The NuttX compiler upgrade is blocking this. https://github.com/PX4/Firmware/pull/8551

**Comment by dagar** [comment]
@gitmate-bot rebase

**Comment by dagar** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by dagar** [comment]
Automated rebase failed! Please rebase your pull request manually via the command line.

Reason:
```
Command: git rebase base/master

Exit Code: 128

Cause:

.git/rebase-apply/patch:86: trailing whitespace.
CheckOptions:    
.git/rebase-apply/patch:1392: trailing whitespace.
# Task file listing 
.git/rebase-apply/patch:1584: trailing whitespace.
    
.git/rebase-apply/patch:1589: trailing whitespace.
        printf "0x%x of 0x%x\n",$cursor,$end 
.git/rebase-apply/patch:1829: trailing whitespace.
			try: 
warning: squelched 1025 whitespace errors
warning: 1030 lines add whitespace errors.
error: Failed to merge in the changes.


```

**Comment by dagar** [comment]
We can come back to this later. I don't have an easy solution for getting these packages installed via homebrew. They're python packages, but not available through pip.

**Comment by MaEtUgR** [comment]
@dagar They could be added manually to pip. http://peterdowns.com/posts/first-time-with-pypi.html

**Pull request closed without merging**
