### PR TITLE
Cam trigger

### PR DESCRIPTION
**Pull request by LorenzMeier**
This improves camera triggering in anticipation of survey support in QGC.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@SimonWilks @AndreasAntener This might be relevant for you.

**Comment by AndreasAntener** [comment]
Thanks, I just added the last missing piece to forward the control command in my mission branch, plus verified do_set_servo.

**Comment by LorenzMeier** [comment]
@boosfelm Has your team seen this? Are they working off this branch?

**Comment by LorenzMeier** [comment]
They need to rebase on master..

**Comment by devbharat** [comment]
I shifted to this branch on xracer to trigger my camera@20fps a couple of days ago, though I haven't analyzed if there is any difference (I hope if there were any latency between the output edge and the timestamp, this branch clears it). Works fine for me.

**Comment by LorenzMeier** [comment]
Thanks, rebased and applied. @boosfelm @devbharat Please rebase your triggering efforts then on master.

**Comment by boosfelm** [comment]
thanks for the fast pace here, @birchera please take the comments into account.

**Pull request closed without merging**
