### PR TITLE
Added 45 deg pitch rotations

### PR DESCRIPTION
**Pull request by AndreasAntener**

### CODE REVIEW

**Comment by AndreasAntener** [comment]
Is this auto synced with QGC nowadays? :)

**Comment by dagar** [comment]
Do we need a mechanism for custom rotations?

**Comment by LorenzMeier** [comment]
We have that already - that's what the level calibration is doing.

**Comment by dagar** [comment]
I was thinking of external sensors and a few of the odder entries in the list. https://github.com/PX4/Firmware/blob/a5e8ae038d73b73ce8084679d7a115c3082f8618/src/lib/conversion/rotation.cpp#L243

**Comment by AndreasAntener** [comment]
The rotation offset from level calibration is not applied to the external mag so it has to be in there.

**Comment by AndreasAntener** [comment]
> The rotation offset from level calibration is not applied to the external mag

Maybe it should be. Could make a difference for a big offset.

**Comment by LorenzMeier** [comment]
Yeah, that's no good. I've captured this here:
https://github.com/PX4/Firmware/issues/8609

As for enum and sync with QGC: That process really stops to scale and we need to come up with something better.

**Comment by LorenzMeier** [comment]
@AndreasAntener Could you also send a QGC PR?

**Comment by AndreasAntener** [comment]
@LorenzMeier Sorry I missed your last request. Yes.

**Comment by AndreasAntener** [comment]
Updated

**Pull request merged**
