### PR TITLE
update mavros sitl tests and move to new Jenkins

### PR DESCRIPTION
**Pull request by lamping7**
Start off by making the tests compatible with current software environment.

### CODE REVIEW

**Comment by dagar** [comment]
Container updates. https://github.com/PX4/containers/pull/86

**Comment by dagar** [comment]
The container updates have finally gone through and tagged 2017-12-29. Let's give this another try.

**Comment by lamping7** [comment]
https://github.com/PX4/containers/pull/94

**Comment by dagar** [comment]
Two issues fixed - 
 1 - standard_vtol model was broken https://github.com/PX4/sitl_gazebo/pull/151
 2 - I updated mission_test.py to send the mission before trying to change modes

**Comment by dagar** [comment]
Some of the remaining issues are performance related. Before increasing the size of the EC2 build slaves I'm going to try and fix a few of the obvious problems.

 - GPS update at 800Hz (gpssim ~ 10% of SITL process)
 - vtol_att updating at twice the attitude controller rate and copying actuator topics multiple times per iteration
 - battery_status updating at 800Hz

**Comment by dagar** [comment]
Only the offboard position control test is currently failing.

image

**Comment by dagar** [comment]
@sanderux FYI the vtol_att_control changes in this branch cut the cpu usage of the module in half.

**Pull request merged**
