### PR TITLE
libuavcan catchup

### PR DESCRIPTION
**Pull request by pavel-kirienko**
@LorenzMeier this is the last change I was talking about.

@davids5 I'd appreciate if you could cross-check this with your bootloaders. I did not detect any issues.

### CODE REVIEW

**Comment by davids5** [comment]
@pavel-kirienko fyi @LorenzMeier 
I tested the new uavcan changes on master @29c295bf116140e2a0e6582abb48757f751b52e6

Using ftp://pkir.net/uavcan_monitor the status look to tranistion better. 

I did see multiple get node info. In one boot

image

Here is a fresh reboot forcing bootload: There are still  multiple Getinfos (hard to reproduce)

image
image
image

**Comment by pavel-kirienko** [comment]
@davids5 I confirm that there is such an issue. It was triggered by 1) an implementation bug in the library and 2) the bootloader's breaking the upper broadcast rate limit of NodeStatus.

First let me post here the tooling that I was using, in case it is needed again.

This application was running an instance of NodeInfoRetriever, the same one that Pixhawk runs:

```c++
/**
 * Build:
 *      g++ -std=c++11 -DUAVCAN_DEBUG retriever.cpp -lrt -luavcan -o retriever
 *
 * Copyright (C) 2015 Pavel Kirienko <pavel.kirienko@zubax.com>
 * License: Public domain
 */

#include <iostream>
#include <ctime>
#include <stdexcept>
// UAVCAN Linux drivers
#include <uavcan_linux/uavcan_linux.hpp>
// UAVCAN protocol
#include <uavcan/protocol/node_info_retriever.hpp>

#ifndef STRINGIZE
#  define STRINGIZE2(x)   #x
#  define STRINGIZE(x)    STRINGIZE2(x)
#endif
#define ENFORCE(x) if (!(x)) { throw std::runtime_error(__FILE__ ":" STRINGIZE(__LINE__) ": " #x); }


class NodeInfoListener : public uavcan::INodeInfoListener
{
    void handleNodeInfoRetrieved(uavcan::NodeID node_id, const uavcan::protocol::GetNodeInfo::Response& node_info)
    override
    {
        std::cout << ">>> NODE INFO FOR " << int(node_id.get()) << ":\n" << node_info << std::endl;
    }

    void handleNodeInfoUnavailable(uavcan::NodeID node_id)
    override
    {
        std::cout << ">>> NODE INFO FOR " << int(node_id.get()) << " IS UNAVAILABLE" << std::endl;
    }
};


int main(int argc, const char** argv)
{
    std::srand(std::time(nullptr));

    if (argc < 3)
    {
        std::cerr << "Usage:\n\t" << argv[0] << " <node-id> <can-iface-name-1> [can-iface-name-N...]" << std::endl;
        return 1;
    }

    /*
     * Node initialization
     */
    const auto name = "org.uavcan.test_fw_updater";
    const auto nid = std::stoi(argv[1]);
    auto node = uavcan_linux::makeNode(std::vector<std::string>(argv + 2, argv + argc));
    node->setNodeID(nid);
    node->setName(name);
    {
        const auto app_id = uavcan_linux::makeApplicationID(uavcan_linux::MachineIDReader().read(), name, nid);
        uavcan::protocol::HardwareVersion hwver;
        std::copy(app_id.begin(), app_id.end(), hwver.unique_id.begin());
        std::cout << hwver << std::endl;
        node->setHardwareVersion(hwver);
    }
    ENFORCE(0 == node->start());
    node->setModeOperational();

    /*
     * Node info retriever
     */
    uavcan::NodeInfoRetriever node_info_retriever(*node);;

    ENFORCE(0 <= node_info_retriever.start());

    NodeInfoListener listener;
    ENFORCE(0 <= node_info_retriever.addListener(&listener));

    /*
     * Logger
     */
    const auto log_sub = node->makeSubscriber<uavcan::protocol::debug::LogMessage>(
        [](const uavcan::ReceivedDataStructure<uavcan::protocol::debug::LogMessage>& msg)
        {
            std::cout << msg << std::endl;
        });

    /*
     * Running the node
     */
    while (true)
    {
        const int res = node->spin(uavcan::MonotonicDuration::fromMSec(1000));
        if (res < 0)
        {
            std::cerr << "Spin error: " << res << std::endl;
        }
        static unsigned long long prev_errors = 0;
        const unsigned long long new_errors = node->getDispatcher().getTransferPerfCounter().getErrorCount();
        if (prev_errors != new_errors)
        {
            prev_errors = new_errors;
            std::cout << ">>> NEW ERRORS: " << new_errors << std::endl;
        }
    }
}
```

The following script was used to automatically reflash the PX4CANNODE with an outdated firmware, which the bootloader was then forced to update:

```bash
#!/bin/bash

log_dir=logs-`date --iso-8601=seconds`
mkdir -p $log_dir

counter=0

while :; do
    echo "Reflashing the firmware..."
    while ! ./blackmagic_flash.sh firmware.elf; do
        echo "Retrying..."
        sleep 1
    done

    echo "Listening..."
    (candump -aeta can0 > $log_dir/candump-$counter.log &)
    counter=$[counter + 1]
    sleep 120
    killall -INT candump
done
```

The setup was running autonomously for several hours, resulting in total 149 successful firmware updates, only 52 of which have revealed the bug:

```
(1437629225.388542)  can0  1F3FFF7D   [8]  24 42 6F 6F 74 45 73 C0   '$BootEs.'
(1437629225.601501)  can0  10015564   [8]  06 14 00 00 00 00 00 C6   '........'
(1437629226.127533)  can0  10015501   [8]  F8 72 00 00 00 00 00 D8   '.r......'
(1437629226.317534)  can0  1F01557D   [8]  02 00 00 00 18 00 00 C2   '........'   NodeStatus A
(1437629226.602485)  can0  10015564   [8]  07 14 00 00 00 00 00 C7   '........'
(1437629227.130503)  can0  10015501   [8]  F9 72 00 00 00 00 00 D9   '.r......'
(1437629227.602514)  can0  10015564   [8]  08 14 00 00 00 00 00 C8   '........'
(1437629228.045506)  can0  1F01557D   [8]  03 00 00 00 18 00 00 C3   '........'   NodeStatus B
(1437629228.086535)  can0  1E01FDE4   [1]  C1                        '.'
(1437629228.097536)  can0  1E01FD81   [1]  C1                        '.'
```

In the log above, the time interval between NodeStatus A and NodeStatus B is 1.7 seconds, which exceeds the 1 second limit suggested by the specification. This fact alone should not cause any issues, but due to the bug in the implementation of NodeStatusMonitor class, the node offline timeout was limited to 1.6 seconds, instead of 2 seconds recommended by the specification. This was *sometimes* causing the library to momentarily declare the node offline, which was triggering the NodeInfoRetriever and FirmwareUpdateTrigger to re-initiate the firmware update procedure.

I have just pushed a fix to the library's master, and I'll keep the automatic test running for at least three more hours to validate it.

**Comment by davids5** [comment]
@pavel-kirienko

 Great work! (As usual :) ) Thank you for finding that. That might be the erase. I will have a look at that and see If I can fix it. It will be worse on larger parts.

**Comment by pavel-kirienko** [comment]
225 more automatic tests did not reveal the bug, so I call it fixed. This PR has already been updated.

**Pull request closed without merging**
