### PR TITLE
fix position hold logic

### PR DESCRIPTION
**Pull request by tumbili**
Actually there still was something not good with the logic of pos hold. This is now tested in SITL!

### CODE REVIEW

**Comment by tumbili** [comment]
@v01d @MappleCastle FYI

**Comment by v01d** [comment]
Thanks for letting me know. 
What was the issue you experienced before this fix?

**Comment by tumbili** [comment]
@v01d I think the position setpoint was locked too early, so that the quad was always moving back a bit after breaking. Let me have a quick look at your repo and see if I can find it.

**Comment by tumbili** [comment]
@v01d Ok, now I remember. Your solution was working fine but we wanted to position setpoint to be reset to the actual position in every step that we were not locking position. This make to make it more clear in the logs that the user was commanding velocity and not position. Doing this fix I introduced a bug which locked the position setpoint a bit too early. This is now fixed.

**Comment by v01d** [comment]
Great, thanks for the forensics on the bug =)

**Pull request merged**
