### PR TITLE
WIP: EKF2

### PR DESCRIPTION
**Pull request by tumbili**
@yyassa This is a branch which has as submodule the new ecl lib.
You can type "make posix" to build the modules.
I already added the required functions to the matrix lib so that the data management class of the ekf compiles. We still need to write tests for the new functions and also for the data management class.
I think it would be great if you could try this and see if you can get into a good work-flow with the submodules (it took me quite some time).

Note: If e.g. your ecl folder stays empty try something like
git submodule update --init --recursive --force

### CODE REVIEW

**Comment by tumbili** [comment]
@yyassa I worked a lot on this now.
You can build and test this branch by typing:
```
make posix_sitl_default gazebo
```
This will start the SITL console and you can type "base" to run the tests for the data management class. I hacked the SITL config for our tests so the upper command has nothing to do with simulation anymore.
I created the folders tests/base inside the EKF folder where you can find the main function for the base class testing. So the command "base" in the SITL shell will run this file.
So far I have tested the readIMU and the readMagData function which work fine.
I implemented all the necessary math functions which were needed for this but we still need to fix travis and provide 100 % testing coverage.

Note: I also disabled the submodules to be updated when you build so that you can work in the ecl folder without always having to commit your changes.

Note: When you make clean and try to build for the first time you will get an error about a header for a message not being available. Just type make again and it will work, need to see why this header is not being built before. However, it's completely irrelevant to the ekf work.

**Comment by tumbili** [comment]
@yyassa If you have time please let me know if the setup works for you. Also let me know on which feature you would like to work (e.g clean up math functions and do testing, implement all the other data management functions like readBaro, readGPS...)

**Comment by tumbili** [comment]
@yyassa There is now a an ek2 module in this branch.
You can type
´´´
make posix_sitl_default jmavsim
´´´
and it will already start the module for you. At the moment it just pushes simulation data into the filter.
You can use
´´´
ekf2 print
´´´
to print out the data it's got in the buffers.
I've also noticed that we do not have the delta angles and delta velocities available in SITL.
This is something that needs to be done next!

**Comment by LorenzMeier** [comment]
@tumbili As we try to use it now with more people it would be good if you could ensure that CI always passes.

**Comment by LorenzMeier** [comment]
Current state: Flying, refining.

**Pull request merged**
